### ISSUE TITLE
hhvm compile and install error: linux / perf_event.h: No such file or directory

### ISSUE THREAD

**Issue by easyhhvm** [facebook/hhvm#1005]
hhvm compile and install error: linux / perf_event.h: No such file or directory
System: Centos 5.8 X64
Error message:
[19%] Building CXX object hphp / CMakeFiles / hphp_runtime_static.dir / runtime / base / hardware-counter.cpp.o
/ usr / local / hiphop-php / hphp / runtime / base / hardware-counter.cpp: 35:30: fatal error: linux / perf_event.h: No such file or directory
compilation terminated.
make [2]: **\* [hphp / CMakeFiles / hphp_runtime_static.dir / runtime / base / hardware-counter.cpp.o] Error 1
make [1]: **\* [hphp / CMakeFiles / hphp_runtime_static.dir / all] Error 2
make: **\* [all] Error 2

Centos5.8 x64 system is not "linux / perf_event.h"
hhvm2.1 are not supported Centos 5.8 X64（Version: 2.6.18）?
To Version: 2.6.32 only "linux / perf_event.h"
Thank you, how to solve the above error?
# 

From "lxr.free-electrons.com/source/include/linux/perf_event.h" (Version: 2.6.32) copied a perf_event.h file.
hhvm make results:
[100%] Building CXX object hphp / test / CMakeFiles / test.dir / __ / hhvm / global-variables.cpp.o
Linking CXX executable test
Embedding systemlib.php in test
[100%] Built target test
[root @ localhost hiphop-php] # cd / usr / local / hiphop-php / hphp / hhvm /

[root @ localhost hhvm] #. / hhvm-m server
mapping self ...
mapping self took 0'00 "(906316 us) wall time
loading static content ...
searching all files under source root ...
analyzing 21 files under source root ...
loaded 0 bytes of static content in total
loading static content took 0'00 "(44113 us) wall time
Unable to find / load systemlib.php

hhvm make been set before / etc / profile.d /

export USE_HHVM = 1
export HPHP_HOME = / home / hiphop-php
export HPHP_LIB = / home / hiphop-php / bin
export HHVM_LIB_PATH = / home / hiphop-php / bin

HHVM still does not work.
How to correct the error?
Thank you
@sgolemon

**Comment by ycliu912** [comment]
mark:
same situation
