### ISSUE TITLE
could not allocate 1210056703 bytes for translation cache

### ISSUE THREAD

**Issue by ghost** [facebook/hhvm#1037]
Hi, just installed hiphop on my cent os 6.4 x64 using 
ref: http://nareshv.blogspot.in/2013/05/install-hhvm-hiphop-php-on-centos-64-64.html

when i try to start hhvm by doing  "sudo hhvm -m server" i am getting this error.

[root@testserver yum.repos.d]# sudo hhvm -m server
mapping self...
mapping self took 0'00" (41620 us) wall time
loading static content...
searching all files under source root...
analyzing 7 files under source root...
loaded 0 bytes of static content in total
loading static content took 0'00" (8959 us) wall time
could not allocate 1210056703 bytes for translation cache

where can i set/change the default cache value ?
Thanks

**Comment by messidiq** [comment]
hay i hava same issue, how to fix it
