### ISSUE TITLE
HipHop Fatal error: unexpected St13runtime_error: locale::facet::_S_create_c_locale name not valid

### ISSUE THREAD

**Issue by zxw0982000** [facebook/hhvm#1052]
I tried to deploy hhvm+wordpress on Aliyun ECS(Ubuntu 12.04).
'Hello World' worked fine.But when I tried to run wordpress,I just got 500 and "HipHop Fatal error: unexpected St13runtime_error: locale::facet::_S_create_c_locale name not valid" in the error log.
On the other hand,hhvm+wordpress worked fine in parallels desktop+ubuntu 13.04.

**Comment by majimboo** [comment]
The same issue with ubuntu 14.04. doing `export LC_ALL=C` fixes the problem via the command line but doesn't fix it when using hhvm with nginx.

**Comment by pkruithof** [comment]
The following works for me (on Ubuntu):

```
sudo dpkg-reconfigure locales
sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
```

This permanently updates the default locales (used by every user), set in `/etc/default/locale`. You have to log out and in again after this to see the change in effect.
