### ISSUE TITLE
Can not build hhvm (link problem with numa)

### ISSUE THREAD

**Issue by Kozzi11** [facebook/hhvm#1141]
When I try to build hhvm I get this errors:
Linking CXX executable hhvm
../../bin/libhphp_runtime.a(alloc.cpp.o): In function `HPHP::Util::set_numa_binding(int)':
alloc.cpp:(.text+0x289): undefined reference to`numa_sched_setaffinity'
alloc.cpp:(.text+0x2cb): undefined reference to `numa_no_nodes_ptr'
alloc.cpp:(.text+0x2d0): undefined reference to`numa_set_interleave_mask'
alloc.cpp:(.text+0x2d5): undefined reference to `numa_allocate_nodemask'
...

It seem to me there should be some cmake rules which add -lnuma to lib flags

**Comment by jazzdan** [comment]
It doesn't look like this ever got fixed. I tried a build today uncommenting the CMake directives that @sgolemon commented out and still got:

```
/home/dmiller/hhvm/hphp/util/alloc.cpp:198: error: undefined reference to 'numa_init'
```

We've seen big wins utilizing NUMA in other places. It would be cool to utilize it in HHVM again!

**Comment by Orvid** [comment]
Are you linking against libnuma statically or dynamically?

**Comment by gdbentley** [comment]
@jazzdan See [PR 6516](https://github.com/facebook/hhvm/pull/6516).
