### ISSUE TITLE
Docs need some major work

### ISSUE THREAD

**Issue by chrisgraham** [facebook/hhvm#1163]
I went through Runtime options on the wiki and cleaned up some outdated prose / old options, then I realised it was woefully incomplete ;-).

It looks like a large proportion of documentation is in the main git repository, and structured in terms of the old compiler:
https://github.com/facebook/hiphop-php/blob/master/hphp/doc/command.compiler
https://github.com/facebook/hiphop-php/blob/master/hphp/doc/options.compiled
https://github.com/facebook/hiphop-php/blob/master/hphp/doc/options.compiler

A good example is the "EnableHipHopSyntax" is not on the wiki at all right now.

Could we get the documentation refreshed, and all moved over to the wiki? I know it's a lot of work, but the good news is I am finding HHVM very stable and easy to get going (after coming back to the project after a fair while). You've done a great job with the technology base, the conformance, the performance, it's now only really the docs that I find are significantly lacking.

The github wiki is git-powered itself, so it seems would fit into your dev workflow quite well.

**Comment by Orvid** [comment]
@JoelMarcey Our docs are better now, right?

**Comment by JoelMarcey** [comment]
I believe so. And I am going to close this out.
