### ISSUE TITLE
Separate out extensions that should be separated out

### ISSUE THREAD

**Issue by Aatch** [facebook/hhvm#1179]
This is a bit of a meta-issue, listing all the current extensions that should probably exist as dynamically-loaded extensions instead of compiled in. This is based on the extensions in Zend PHP and may not be possible/feasible/appropriate for HHVM.
- [ ]  ZLib
- [ ] BCMath
- [ ] BZip2
- [ ] cUrl
- [ ] GD (image)
- [ ] IMAP
- [ ] Intl
- [ ] LDAP
- [ ] MBString
- [ ] MCrypt
- [ ] MySQL
- [ ] SOAP
- [ ] Sockets

**Comment by Orvid** [comment]
Well, to support dynamic extensions being compiled under MSVC, there would probably have to be a lot of fun decorating of most of HHVM, although I can think of ways to get around that.

Ignoring MSVC for now, I rewrote the mechanism used for configuring extensions in the OSS build a while back, and enabling or disabling these extensions at compile time is now as simple as setting a single CMake variable, so I wonder if there is still a benefit to extracting these to have them compile as DSOs?
