### ISSUE TITLE
Implement equivalent to "php -d key=value"

### ISSUE THREAD

**Issue by sebastianbergmann** [facebook/hhvm#1200]
Especially being able to do something like "php -d include_path=/path:/path/:..." would be extremely helpful.

**Comment by thekid** [comment]
If anyone ever searches for this, PHP also supports a short form of the this option, `-dkey=value` (without space after `-d`), while HHVM doesn't:

```sh
# Short
$ php -duser_dir=. -r 'var_dump(ini_get("user_dir"));'
string(1) "."

# With space after option
$ php -d user_dir=. -r 'var_dump(ini_get("user_dir"));'
string(1) "."
```

**Comment by JoelMarcey** [comment]
@thekid Hmmm... it should support the latter.

I use `hhvm -doption=whatever` frequently.
