### ISSUE TITLE
Support for ZeroMQ

### ISSUE THREAD

**Issue by laurinkus** [facebook/hhvm#1214]
http://zeromq.org/bindings:php

**Comment by rotor-head** [comment]
A year later since the last entry. I see an entry for 0mq in the HHVM extensions list - does this mean it's on the road map for integration? Is there a timeline for including zeromq in HHVM?

**Comment by paulbiss** [comment]
I don't see any entry in our [extension list](https://github.com/facebook/hhvm/wiki/Extensions). There's an externally maintained extension (linked above), I'm not aware of any plans to upstream it into hhvm though.

**Comment by rotor-head** [comment]
Thanks Paul. Sadly - it's not on the github list. It is in the docs manual: http://docs.hhvm.com/manual/en/book.zmq.php  Though it does state not currently implemented, it lends itself to wondering about implementation in the core.

We'd love to use HHVM for our production app, zeromq is a key component of our app.

Currently, hhvm-zmq isn't working on CentOS 7.

**Comment by paulbiss** [comment]
The docs are forked directly from PHP, hence the inclusion of extensions not currently part of hhvm. No one here is currently working on zeromq, unfortunately.

I don't have the bandwidth right now to take it on myself, but I'm happy to help anyone that wants to work on it and runs into specific issues related to hhvm.

**Comment by rotor-head** [comment]
Thanks for the clarification. We may pursue the option to build it or get it built. Bandwidth is in limited supply these days.

**Comment by SiebelsTim** [comment]
Note, that on every `Requirement` and/or `Installation` page of an extension, there's a note if it's available or not:
http://docs.hhvm.com/manual/en/zmq.requirements.php

**Comment by no1youknowz** [comment]
@rotor-head and anyone else.  Please take a look at https://github.com/no1youknowz/hhvm-zeromq-ext this works for me 90% and it's being used in a production env.  

I'd love some help in getting things that work in PHP to work with this (in hhvm) 100%.

I've tested it with push/pull, pub/sub, getsocket, poll.  I don't know c++ really, so any help and contributions welcome.

**Comment by rotor-head** [comment]
Thanks for posting! .. I'll check it out on our app and give will give feedback on what we experience.

**Comment by SiebelsTim** [comment]
Can this be closed as there is an externally provided extension?

**Comment by rotor-head** [comment]
Yes

**Comment by no1youknowz** [comment]
This works with 3.9 thanks to Orvid on #hhvm irc

**Comment by JoelMarcey** [comment]
I am going to close this out since there is an extension

@fredemmott Didn't we consider ZeroMQ at one point and weren't going to implement it ourselves, but now that there is an extension, do we consider merging that in to our codebase? Or do we leave it as a pluggable extension outside hhvm?

**Comment by scragg0x** [comment]
Can the 3rd party extension be included in the official build?  Seems like an important one to leave out. :(

**Comment by jwatzman** [comment]
Not unless we pull it into our code tree, sorry.

**Comment by Orvid** [comment]
Unfortunately, due to the inability to the way the implementation linked above is, getting the licensing sorted out would be nearly impossible. It also has various other issues with the implementation.

For that reason, I did a fresh port of the PECL extension to HNI, so that the licensing is significantly easier to sort out. To my knowledge it supports everything the original PECL extension did, and is available here: https://github.com/Orvid/php-zmq

**Comment by scragg0x** [comment]
Thanks for creating that @Orvid .  What is the next step here?  Can @jwatzman pull the code into HHVM?
