### ISSUE TITLE
xhprof output does not contain internal function calls

### ISSUE THREAD

**Issue by wwbmmm** [facebook/hhvm#1245]
$ cat test.php 
```php
<?php 
xhprof_enable();
$json = json_encode(array());
$ret = xhprof_disable();
var_dump($ret);
exit();
```
$ php test.php 
```
array(3) {
  ["main()==>json_encode"]=>
  array(2) {
    ["ct"]=>
    int(1)
    ["wt"]=>
    int(12)
  }
  ["main()==>xhprof_disable"]=>
  array(2) {
    ["ct"]=>
    int(1)
    ["wt"]=>
    int(0)
  }
  ["main()"]=>
  array(2) {
    ["ct"]=>
    int(1)
    ["wt"]=>
    int(46)
  }
}
```
$ hhvm test.php 
```
array(1) {
  ["main()"]=>
  array(2) {
    ["ct"]=>
    int(1)
    ["wt"]=>
    int(38)
  }
}
```

**Comment by paulbiss** [comment]
This feature request is not actively being worked on. We would happily consider a pull request implementing it. If you plan to work on this issue let us know in the comments and we will re-open the issue and assign it to you. If you feel strongly that this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
