### ISSUE TITLE
ini_get does not return the original config string

### ISSUE THREAD

**Issue by wwbmmm** [facebook/hhvm#1284]
$ cat test.php

```
<?php
ini_set('memory_limit', '128M');
var_dump( ini_get('memory_limit'));
```

$ php test.php 

```
string(4) "128M"
```

$ hhvm test.php 

```
string(9) "134217728"
```

**Comment by tcheko** [comment]
Still not fixed. It works as expected in command line mode but not from apache2/fastcgi.

**Comment by tcheko** [comment]
# hhvm -c /etc/hhvm/php.ini ini_get.php

Output from command line :
post_max_size 8388608
file_uploads 1
allow_url_fopen 1
register_globals 
upload_max_filesize 32M
pcre.backtrack_limit 1000000
max_execution_time 300
mbstring.func_overload 
default_charset utf-8
disable_functions 
safe_mode 
memory_limit 128M
display_errors 1

Output from HTTP using the same php.ini file for hhvm daemon :
post_max_size 
file_uploads 1
allow_url_fopen 1
register_globals 
upload_max_filesize 
pcre.backtrack_limit 1000000
max_execution_time 0
mbstring.func_overload 
default_charset utf-8
disable_functions 
safe_mode 
memory_limit 128M
display_errors 1

It looks like some vars aren't correctly get: post_max_size and upload_max_filesize at least.
