### ISSUE TITLE
Setup for AWS AMI Hangs compiling TBB

### ISSUE THREAD

**Issue by ajtrichards** [facebook/hhvm#1362]
I'm trying to get HHVM installed on an Amazon Linux 2013.09.1 machine (m1.small) and i'm getting an issue compiling Thread Building Blocks.

The command line show's

./test_atomic.exe 

And it just hangs there - I left it for 35 minutes and nothing happens.

Has anyone else had this issue and how did you resolve?

Thanks

**Comment by davidbitton** [comment]
Same issue here with the "hang". I upsized my m3.medium to a c3.8xlarge and re-make-ed with -j32. The build process blew right pas test_atomic.exe.
