### ISSUE TITLE
No signatures on the ubuntu packages from dl.hhvm.com/ubuntu

### ISSUE THREAD

**Issue by ebernhardson** [facebook/hhvm#1378]
Installing hhvm to Ubuntu currently suggests using the package repository at dl.hhvm.com.  Utilizing this repository the following message is output by `apt-get install hhvm`:

```
WARNING: The following packages cannot be authenticated!
  hhvm
```

This makes installing hhvm via automated processes(ex: puppet inside a vagrant vm) more difficult because apt-get must be provided the --force-yes option which does more than just allow unsigned packages.

To resolve this the packages should be digitally signed with gpg.  A key will need to be generated and packages signed with the `dpkg-sig` utility. The public portion of this key will need to be downloadable by users. Often the key is provided for direct download with something like:

```
wget -qO - http://dl.hhvm.com/ubuntu/archive.key | apt-key add -
```

But can also be provided by a public keyserver and installed with the `add-apt-key` utility

**Comment by aminhusni** [comment]
For those who are stuck, type this in your terminal

`sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xB4112585D386EB94`

**Comment by fredemmott** [comment]
This issue (packages were completely unsigned) was resolved in 2013. The issue you're having is separate, and due to https://hhvm.com/blog/2017/11/14/gpg-key-migration.html
