### ISSUE TITLE
Fileinfo constructor does not allow NULL as second parameter.

### ISSUE THREAD

**Issue by bantu** [facebook/hhvm#1382]
`new \finfo(FILEINFO_MIME_TYPE, null)`
results in
`Argument 2 passed to finfo::finfo() must be an instance of string, null given`

This is not compatible with http://php.net/manual/en/function.finfo-open.php

**Comment by czim** [comment]
I'm having a very similar issue in version 3.6.1 (rel).

`new \finfo(FILEINFO_MIME_TYPE, null)`

Results in (different from the first post):

`finfo::finfo() expects parameter 2 to be a valid path, string given`

**Comment by SiebelsTim** [comment]
https://3v4l.org/51jLQ

Cannot reproduce.
