### ISSUE TITLE
Invalid operand type was used: cannot perform this operation with arrays

### ISSUE THREAD

**Issue by Berdir** [facebook/hhvm#1413]
Trying to run Drupal 8 with HHVM.

Working pretty well, but getting a bunch of those:

HipHop Fatal error: Invalid operand type was used: cannot perform this operation with arrays. in /home/berdir/Projekte/d8/core/lib/Drupal/Core/Database/Query/Condition.php on line 169

Which is http://drupalcode.org/project/drupal.git/blob/874690a37b00f742343e86d1dab023658b572d36:/core/lib/Drupal/Core/Database/Query/Condition.php#l169

The error is correct because $conditions['value'] is NULL:

array(3) { ["field"]=> string(85) "node_field_data.status = 1 OR (node_field_data.uid = 1 AND 1 <> 0 AND 1 = 1) OR 1 = 1" ["value"]=> NULL ["operator"]=> NULL }

However, with Apache/PHP, the value is an empty array:
array (size=3)
  'field' => string 'node_field_data.status = 1 OR (node_field_data.uid = 1 AND 1 <> 0 AND 1 = 1) OR 1 = 1' (length=85)
  'value' => 
    array (size=0)
      empty
  'operator' => null

**Comment by wojtas** [comment]
I've just encountered the same issue in my company Symfony2 ecommerce project. Not sure now where the error is, but I'll try to make an isolated test case and provide the code in my spare time. After switching to PHP5-FPM the error disappeared, so I suppose it's something with HHVM / PHP5 parity. Somehow some arrays are treated differently. I'll get in touch soon.

**Comment by mzaslavsky** [comment]
I've experienced Berdir's issue in Drupal 7's core as well (only tested older version though - 7.22) (e.g. field.info.class.inc - https://api.drupal.org/api/drupal/modules!field!field.info.class.inc/7) and at least the entityreference module as well for example.

As Berdir noted, this happens whenever you attempt to use the array union operator (+) in cases where at least one of the operands is in fact NULL. 

For example,

    $field['settings'] += field_info_field_settings($field['type']);

will produce the fatal error described if $field['settings'] is NULL.

It appears Zend's PHP casts NULL as an array automatically before proceeding with the union (I don't know C++, but here's Zend's implementation - http://lxr.php.net/xref/PHP_5_5/Zend/zend_operators.c#843).

With HHVM, you have to cast NULL to an array manually before adding to an array, it appears. You can do it last second like so:

    $field['settings'] = (array)$field['settings'] + (array)field_info_field_settings($field['type']);

but unfortunately you can't use the contracted += format.

**Comment by mzaslavsky** [comment]
I experience the same issue with Drupal 7.22 and in my case I believe it's due to the externally-managed hhvm-pgsql driver not fully supporting Large Objects (LOBs) (https://github.com/PocketRent/hhvm-pgsql/issues/5). 

Assuming I understand correctly, since Drupal inserted/updated the data columns as streamable Large Objects the data has been stored in the system table "pg_largeobject" rather than the BYTEA column within the table itself. I believe this is why my data column is always returned as NULL.

My example
Just like Berdir's bug where an array's union with NULL was attempted, function field_read_fields() in Drupal 7 assumes that the data field will always contain the 'settings' key. Since my apparent database bug returns NULL rather than an object, $field['settings'] is never set at all, causing the fatal error described since you can't add NULL to an array.

This is the expected behaviour in PHP 5 as well (although it produces a more succinct error - "Unsupported operand types in ...").

**Comment by Berdir** [comment]
Right, the actual error is not on that line, it is somewhere else, resulting in something being NULL that should be array(). That it fails is consistent with PHP, just the error message is dfferent.

Mine was definitely for a different reason, because I'm not using pgsql.

**Comment by mzaslavsky** [comment]
Exactly. I var_dump()ed debug_backtrace(true) and exit()ed just above my fatal error to track down the anomaly.

Unfortunately I haven't had the opportunity to download and test Drupal 8 yet.

**Comment by hyperreal-info** [comment]
Still problems in D7, ```Invalid operand type was used: cannot perform this operation with arrays in /srv/http/help/includes/theme.inc on line 637```

**Comment by mgifford** [comment]
@hyperreal-info has anyone else found this? Seems folks have been able to get it working (I think). Hopefully nobody is using Drupal 7.22 now.

**Comment by DarrellDuane** [comment]
I am still getting this error for the += operator being used on Arrays with HHVM 3.12.0-dev.  I would assume that -= and others like this for Arrays are also not working but I haven't tried.  The error came from  Drupal 7.41 in the ctools module (ctools/includes/export-ui.inc) which uses the '+=' on a number of arrays.

**Comment by fredemmott** [comment]
Can you reduce it to a small example? eg https://3v4l.org/7s6Mf works fine

**Comment by SiebelsTim** [comment]
@fredemmott The error is somewhere else.
@Berdir traced it down to this https://3v4l.org/A2WW1 . We just don't know why it is null yet.
