### ISSUE TITLE
unserialize Zend DateTime values throws a warning

### ISSUE THREAD

**Issue by Maks3w** [facebook/hhvm#1541]
unserialize a DateTime object previously serialized with Zend Engine throws a warning.

`O:8:"DateTime":3:{s:4:"date";s:19:"1970-01-01 00:00:00";s:13:"timezone_type";i:1;s:8:"timezone";s:6:"+01:00";}`

`HipHop Notice: Undefined property: DateTime::$_date_time`

**Comment by Paso** [comment]
It's not only numeric timezones, 'Z' doesn't work either:
```
var_dump(unserialize(serialize(new DateTime('1970-02-01T18:00:00Z'))));
```

```
Fatal error: Uncaught exception 'Exception' with message 'DateTimeZone::__construct(): Unknown or bad timezone (Z)' in :
Stack trace:
#0 /in/mFrJh(8): DateTime->__wakeup()
#1 {main}
```

**Comment by SiebelsTim** [comment]
duplicate #3637

**Comment by JoelMarcey** [comment]
closing in favor of #3637
