### ISSUE TITLE
Support the --info flag

### ISSUE THREAD

**Issue by ghost** [facebook/hhvm#1544]
I'm working on getting the Joomla Framework to complete unit testing under hvvm on Travis.

I've run into a number of issues where extensions don't appear to be installed and such.  Since we don't have full control over the travis vm, it would be helpful if I could invoke hhvm with the --info flag to get a list of all the extensions that have been enabled/installed, the compile flags, etc.

**Comment by photodude** [comment]
@ghost Joomla staging now passes unit tests on HHVM 3.15.3 and the pre-release 3.7.0 Alpha 1 should be testable for live use with HHVM 3.15.3+
