### ISSUE TITLE
DOMNode appendChild($node) does not update parentNode

### ISSUE THREAD

**Issue by Maks3w** [facebook/hhvm#1553]
After append a child node the node still having a null `parentNode`

```
$dom = new DOMDocument();
$element = $dom->createElement($name);
$newElement = $dom->appendChild($element);

var_dump($newElement->parentNode); // null, expected to be $dom
```

**Comment by fredemmott** [comment]
Do you still have this? If so, could you provide an isolated example that does not depend on an external framework

**Comment by fredemmott** [comment]
This issue has been waiting for more info for more than 2 weeks. I'm closing it for now, but feel free to re-open it if you can provide more info. https://github.com/facebook/hhvm/wiki/Human-Timeouts
