### ISSUE TITLE
fastcgi server truncates some HTTP requests body

### ISSUE THREAD

**Issue by franckstauffer** [facebook/hhvm#1557]
This bug is kinda awkward.  I created a test.php file with the following content 

``` php
<?php

echo strlen(file_get_contents("php://input")), PHP_EOL;
```

Then if I send the following _long_ curl command  (same headers as sent by chrome browser) 

``` bash
curl 'http://localhost:8081/test.php' -H 'Pragma: no-cache' -H 'Origin: http://localhost:8081' -H 'Accept-Encoding: gzip,deflate,sdch' -H 'Host: localhost:8081' -H 'Accept-Language: en-us' -H 'Authorization: OAuth oauth_consumer_key="FoiVAEglEUGRUDRiuTIACROIvERAURioCHuizouLueqoijueqAECHUEcleuQeuFL", oauth_nonce="236B307572556040", oauth_signature="dMjYqRFphGGvDyv1byQQPpJXbdA%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1389631484", oauth_token="TiuPEUCHIMaiNAIcUEGRuasloisrIOjUIJOAsliuGRaiHEroiglUAQiPEMiuRiuS", oauth_version="1.0"' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36' -H 'Content-Type: application/json;charset=UTF-8' -H 'Accept: application/json, text/plain, */*' -H 'Cache-Control: no-cache' -H 'X-Requested-With: XMLHttpRequest' -H 'Connection: keep-alive' --data-binary '{"model":"Rbs_Notification_Notification","where":{"and":[{"op":"eq","lexp":{"property":"userId"},"rexp":{"value":100084}},{"op":"eq","lexp":{"property":"status"},"rexp":{"value":"new"}}]}}' --compressed
```

it outputs 5 instead of 188. If I send no or less/different headers, it works as expected :

``` bash
curl 'http://localhost:8081/test.php' -H 'Pragma: no-cache' --data-binary '{"model":"Rbs_Notification_Notification","where":{"and":[{"op":"eq","lexp":{"property":"userId"},"rexp":{"value":100084}},{"op":"eq","lexp":{"property":"status"},"rexp":{"value":"new"}}]}}' --compressed
```

I run the server in fastcgi behind nginx 1.4.1 on ubuntu 13.10 with a fairly straightforward configuration. I don't think it's an issue with nginx though I can not completely rule that out.

**Comment by leearmstrong** [comment]
This is happening for me in HHVM 3.6.1 using FastCGI

`$rawData = file_get_contents('php://input');`

`$rawData` appears to have been heavily truncated

**Comment by apuckey** [comment]
I've had this issue before to and fixed it by doing this: https://github.com/apuckey/hhvm/commit/9568944efa37e3ea3c0e4627b7770b37b01c526b i think it got changed back in the refactor?

**Comment by leearmstrong** [comment]
Ok thanks. I think that is it. @ptarjan

**Comment by leearmstrong** [comment]
Also any idea how to achieve this since the refactor? @apuckey

**Comment by apuckey** [comment]
probably something like:

```
+  Cursor cursor(chain.get());
+  auto s = cursor.readFixedString(chain->computeChainDataLength());
+  m_bodyQueue.append(s);
-  m_bodyQueue.append(std::move(chain));
```

but i really don't know enough about the iobuffers work to say this will work or not :)

**Comment by leearmstrong** [comment]
No, me neither!!!

**Comment by leearmstrong** [comment]
It looks like @ptarjan did the refactor so is possibly the best person to reopen this?

**Comment by paulbiss** [comment]
Hmm, I'll have a look at this tomorrow.

**Comment by leearmstrong** [comment]
Actually I think it was a red herring.  The JSON being sent had a `\0' inside that php://input stream.  that said PHP-FPM doesn't have an issue with it

**Comment by paulbiss** [comment]
Can you open a new issue for that? We should definitely fix it regardless. Thanks! :-)

**Comment by leearmstrong** [comment]
OK thanks, I will try and get the exact case and something that can be replicated outside of our environment easily.  

At the moment I think it is some text within gzdecode that itself is null terminated causing the issue
