### ISSUE TITLE
Caching, Threading and Stats

### ISSUE THREAD

**Issue by craigcarnell** [facebook/hhvm#1574]
hhvm is almost approaching useable in a production environment for us after the latest round of commits with fastcgi but I have a few questions!

Is it possible to clear the JIT cache without restarting the hhvm instance? I could create a simple control page if there is something I can hook into.

Is it possible to clear the APC cache without restarting hhvm?

Is there a web stat page for JIT/APC/HHVM?

Does HHVM automatically scale to the number of concurrent requests? How can we determine the maximum threads/users? In PHP FPM we can set things like listen.backlog, max_requests, max_children? e.g. we could have a small server instance say 2gb dealing with a low user site or a 32gb server running multiple users?

Is there any kind of stats we can integrate similar to newrelic?

**Comment by paulbiss** [comment]
We now have a new documentation site which should better outline much of this. In addition we now have a mode for recycling the TC in hhvm.
