### ISSUE TITLE
PHP-MSSQL Undefined Functions.

### ISSUE THREAD

**Issue by Hush077** [facebook/hhvm#1579]
Normally we use php-mssql and connect through php-fpm or whatever.  With HH I get it as an undefined function.  I'm assuming this hasn't been ported over yet, or I just need to compile something in?

We are a weird shop who happens to use mssql as the backend instead of mysql.

I apologize if this has been discussed for other functions, still doing research.  I'd look into implementing these if they haven't been ported, but not sure where to really start :)

HipHop Fatal error: Undefined function: mssql_connect
HipHop Fatal error: Undefined function: mssql_pconnect

Thanks!

**Comment by hhellbusch** [comment]
:+1: for this extension to be implemented.  This is holding me back from using HHVM.

**Comment by huzhiguang** [comment]
@hhellbusch ,Just don't have time to migrate to the DSO mode

**Comment by manuelbocos** [comment]
We are about to migrate a simfony app to hhvm, we installed the hhmv interpreter but...

FACEPALM! no support extension for MSSQL... we use MariaDB and MSSQL databases so this block all our project migration to hhvm.

Like US I am sure a lot of people uses MSSQL databases and dont start using hhvm beacuse of this
Support for some commercial databases like MSSQL and Oracle should be mandatory, please raise priority for this.

**Comment by clementhk** [comment]
@huzhiguang 能不能把最新代码发给我我看看？工作量不大的话我就整进去

Guys, I'll take a look next week, hopefully with the help from @huzhiguang, but I only use PDO dblib, so whoever want the rest to be working should give me a list of needed features and tests.
Keep in mind that the less features that are required, the better chance I will write it :)

**Comment by clementhk** [comment]
(I'll be glad to help Baidu hackers if they need help getting their code upstream.)

**Comment by manuelbocos** [comment]
At least for us, the most used functions are:
mssql_fetch_row
mssql_select_db
mssql_connect
mssql_num_rows
mssql_free_result
mssql_query
mssql_select_db
mssql_get_last_message
mssql_close
mssql_data_seek
mssql_bind
mssql_init
mssql_execute
mssql_fetch_array

If you can make this, I think could be enought for a initial version, and should be included in core.

**Comment by huzhiguang** [comment]
@clementhk  
我已经很久没有维护MSSQL这个扩展了，这个扩展是我在京东上班时开发的，但是我很愿意帮助你开发这个扩展迁移到DSO

I haven't maintenance MSSQL extension for a long time,this extension is when I was in JD company development,but I'm willing to help you develop this extension to DSO

**Comment by manuelbocos** [comment]
Thank you so much guys. 
You rocks!

**Comment by euphio** [comment]
+1 for MSSQL support

**Comment by euphio** [comment]
I'm going to work on a very basic skeleton extension for this if anyone wants to help out, it's been a long time since I've really got stuck in to C++ but I'll focus on laying the initial skeleton of the plugin out to reflect that of the PHP docs. 

Repo can be found at: https://github.com/euphio/hhvm-mssql

Please feel free to fork / add issues / join in

**Comment by nemphys** [comment]
Any news on this one? It's the only thing we still run on php-fpm and it's a shame to miss the performance benefits of hhvm

**Comment by paulbiss** [comment]
You might have better luck opening an issue on @euphio's repo or contributing PRs there if you're so inclined.

**Comment by wjbryant** [comment]
This is the most information I could find on using MS SQL Server with HHVM. I am currently using the pdo_dblib extension with FreeTDS to connect PHP 7 to a MS SQL database.

Has pdo_dblib been ported to HHVM or are there any plans to do so? Unfortunately, this is the only thing keeping me from being able to use HHVM.

**Comment by craigcarnell** [comment]
@wjbryant Bit off topic, but do you use stored procedures with PHP 7 and MSSQL? They don't return parameters for me.

**Comment by wjbryant** [comment]
@craigcarnell Yes, we are using stored procedures and we also do not get any return values. I think this is a limitation of the setup. We ended up writing SQL like this in our stored procedures:

```sql
SELECT @ReturnValue AS result
RETURN @ReturnValue
```

Then we can grab the value of the "result" column in the first row of the result set. If return values begin working in the future, we can just ignore the result set.

**Comment by craigcarnell** [comment]
@wjbryant Thanks, I will try that :+1:

**Comment by paulbiss** [comment]
This feature request is not actively being worked on. We would happily consider a pull request implementing it. If you plan to work on this issue let us know in the comments and we will re-open the issue and assign it to you. If you feel strongly that this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.

**Comment by beatrohrer** [comment]
We're an university and we consider switching to HHVM & Hack but all our student and course data is in a MSSQL DB and can't be moved… Also several other systems, we need data from, use MSSQL and don't provide a proper API. So we do feel strongly that this feature needs more attention.

Because `ext/mssql` has been removed in PHP7, it's probably not wise to implement it for HHVM, but a PDO library for MSSQL would be great!

**Comment by aorenste** [comment]
@beatrohrer It's unlikely we'll have time to implement this ourselves but we'd be happy to accept a pull request for it (maybe a student project?)

**Comment by beatrohrer** [comment]
@aorenste we're an art university – our students could provide great artwork depicting our frustration about the missing MSSQL support – would that be helpful? ;)

I'll look into making it myself, but my C++ is **really** rusty, I don't know much about PDO, and don't like MSSQL…
