### ISSUE TITLE
get_defined_constants() not maintaining order

### ISSUE THREAD

**Issue by simonwelsh** [facebook/hhvm#1605]
This is a zend compatibility issue. get_defined_constants() isn't returning the constants in the order that they're defined. This occurs with both constants defined in PHP-land and through Native::registerConstant().

Test case:

``` php
<?hh

define('TEST_A', 'A');
define('TEST_C', 'C');

foreach(get_defined_constants() as $name => $value) {
  if (strpos($name, 'TEST_') === 0) {
    echo "$name: $value\n";
  }
}

echo "Done\n";
```

Expected:

```
TEST_A: A
TEST_C: C
Done
```

Actual:

```
TEST_C: C
TEST_A: A
Done
```

Using TEST_B/B instead of TEST_C/C results in them being outputted in the correct order, so it's not just the list coming back in reverse.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

The current behavior doesn't match PHP, but that's okay. Hhvm and PHP split ways many years ago. Matching behavior with PHP is not a desired goal anymore.

`<opinion>`
The current behavior of returning the constants in alphabetic order makes sense in a way. If any order is chosen, a stable order would make sense. The PHP behavior depends on the include order (when constants are defined in multiple files).

When running in repo auth mode, there isn't a concept of, "is this file loaded". All code appears to be loaded even before the entry point is called. Files aren't `include`d or `require`d. Keeping track of the order in which constants in separate files would have been loaded would break that illusion.
