### ISSUE TITLE
ParamCoerceMode (previously ZendParamMode) in PHP functions

### ISSUE THREAD

**Issue by simonwelsh** [facebook/hhvm#1669]
Currently, there's no coercion of primitives when type hinting a PHP function, like there is for HNI ones. Support for this would be useful for both extensions (so they can be type hinted to something other than mixed) and user land functions.

Example test case:

``` php
<?hh
function a(float $b) { var_dump($b); }
a(3);
```

Expected out:

```
float(3)
```

Actual:

```
HipHop Fatal Error: something about argument 1 being an int, not a float
```

(I don't currently have access to a HHVM build so can't get the real error, but it's a fatal complaining about int not being float)

**Comment by SiebelsTim** [comment]
what happened here?

**Comment by paulbiss** [comment]
The fix ran into some issues with the jit that have since been resolved, I haven't had a chance to come back to it.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

The failure mode of built-in functions which are called with a wrong type changed in [hhvm 4.3](https://hhvm.com/blog/2019/04/30/hhvm-4.3.0.html) to always throwing a TypeError.
This matches user defined functions in Hack. It is not possible to get the php behavior of argument type coercion in Hack.

I don't write extensions for hhvm, so I might be misunderstanding the idea behind ParamCoerceMode.
Please reopen the issue if I misunderstood.
