### ISSUE TITLE
Failed to initialize central HHBC repository at '/var/www/.hhvm.hhbc'

### ISSUE THREAD

**Issue by cscd98** [facebook/hhvm#1704]
I am running hhvm as the www-data user in Ubuntu 13.10. The home directory for www-data is /var/www.

www-data does not have write permission to that folder so I created /var/www/.hhvm.hhbc in that folder as a empty file with ownership www-data:www-data.

Even setting it to 777 I still get an error:

-rwxrwxrwx 1 www-data www-data 0 Feb  4 10:49 /var/www/.hhvm.hhbc
Failed to initialize central HHBC repository at '/var/www/.hhvm.hhbc'

This is my command to start hphp:

```
/usr/local/src/hiphop-php/hhvm/hphp/hhvm/hhvm --mode daemon -vServer.Type=fastcgi -vServer.Port=9000 -vServer.FileSocket=/var/run/hhvm/hhvm.sock -c /etc/hhvm/config.hdf --user www-data
```

Also if I start hhvm as root (which does work) my socket is still created with the ownership of root and .hhvm.hhbc gets stored in /root/ even when started with --user www-data. However, sometimes it will not start at all with --user www-data.

Any ideas?

**Comment by jaitaiwan** [comment]
Just came across this issue in 3.9.0 ubuntu 15.04. Deleting /var/run/hhvm/hhvm.hhbc fixed the issue.

**Comment by thisismyaim** [comment]
you don't have premission if you use sudo it will work fine

**Comment by jeromystewart** [comment]
So I had the same issue and actually started fresh with Ubunu 16.04 / nginx / hhvm at least 8 times.
Each time the same issue would occur .. Finally changed ownership of hhvm.hhbc to www-data and restarted nginx & hhvm and voila
