### ISSUE TITLE
Multipart post data incorrectly parsed when using mod_fastcgi

### ISSUE THREAD

**Issue by antradar** [facebook/hhvm#1706]
Apache config:
```
FastCgiExternalServer /var/www/php.external -host 127.0.0.1:9000
AddHandler php5-fcgi .php
Action php5-fcgi /usr/lib/cgi-bin/php.external
Alias /usr/lib/cgi-bin/ /var/www/
```
Submit a multipart encoded form, e.g. file upload, the raw post data is populated correctly, the ```$_FILES``` and ```$_POST``` variables are scrambled.

This issue is only observed when mod_fastcgi and HHVM are used in conjunction. Tested on SSL, with or without SPDY.

Bug doesn't occur if Nginx fastcgi is used, or FPM is used with mod_fastcgi.

To reproduce the bug:
```
<?php
echo '<pre>';print_r($_POST); echo '</pre>';
echo '<pre>';print_r($_FILES); echo '</pre>';
?>
<form method="POST" enctype="multipart/form-data">
<input type="hidden" name="name" value="123">
<input type="file" name="file" id="file">
<input type="submit" value="Submit">
</form>
```
A temporary workaround:

```
function fixupload(){
	global $HTTP_RAW_POST_DATA;
	global $_SERVER;
	global $_POST;
	global $_FILES;

	if ($HTTP_RAW_POST_DATA==''||!empty($_FILES)||stripos($_SERVER['CONTENT_TYPE'],'multipart')===false) return;

	preg_match('/boundary=(.*)$/', $_SERVER['CONTENT_TYPE'], $matches);
	$boundary = $matches[1];

	$blocks = preg_split("/-+$boundary/", $HTTP_RAW_POST_DATA);
	array_pop($blocks);

	$_POST=array();
	$_FILES=array();

	foreach ($blocks as $block){
		if (trim($block)=='') continue;
		if (preg_match('/Content\-Disposition\:\s*form\-data;\s*name="([\S\s]+?)";\s*filename="([\S\s]+?)"\s*Content\-Type\:\s*(\S+)\s*([\S\s]+)/',$block,$matches)){
			$ofieldname=$matches[1];
			$fieldname=preg_replace('/\[\d*\]/','',$ofieldname);
			if ($ofieldname!=$fieldname){
				if (!is_array($_FILES[$fieldname]['name'])) {
					$_FILES[$fieldname]['name']=array();
					$_FILES[$fieldname]['type']=array();
					$_FILES[$fieldname]['tmp_name']=array();
					$_FILES[$fieldname]['error']=array();
					$_FILES[$fieldname]['size']=array();
				}
				array_push($_FILES[$fieldname]['name'],$matches[2]);
				array_push($_FILES[$fieldname]['type'],$matches[3]);
				$tmpname=tempnam('/tmp','mfx.'.date('md').'.');
				$f=fopen($tmpname,'wb'); fwrite($f,trim($matches[4])); fclose($f);
				array_push($_FILES[$fieldname]['tmp_name'],$tmpname);
				array_push($_FILES[$fieldname]['error'],0);
				array_push($_FILES[$fieldname]['size'],strlen(trim($matches[4])));
			} else {
				$tmpname=tempnam('/tmp','mfx.'.date('md').'.');
				$f=fopen($tmpname,'wb'); fwrite($f,trim($matches[4])); fclose($f);
				$_FILES[$fieldname]=array('name'=>$matches[2],'type'=>$matches[3],'tmp_name'=>$tmpname,'error'=>0,'size'=>strlen(trim($matches[4])));
			}
		} else {
			preg_match('/Content\-Disposition\:\s*form\-data;\s*name="([\S\s]+?)"\s*([\S\s]+)/',$block,$matches);
			$ofieldname=$matches[1];
			$fieldname=preg_replace('/\[\d*\]/','',$ofieldname);
			$value=trim($matches[2]);
			if ($fieldname!=$ofieldname) {
				if (!is_array($_POST[$fieldname])) $_POST[$fieldname]=array();
				array_push($_POST[$fieldname],$value);
			}
			else $_POST[$fieldname]=$value;
		}
	}

}

```

**Comment by jannispl** [comment]
@paulbiss I've just experienced this bug when sending an array as multipart/form-data. Array ended up with the values being duplicated (0,1,2,0,1,2 rather than 0,1,2).

**Comment by paulbiss** [comment]
@jannispl what version of HHVM are you running, and which server are you using?

**Comment by jannispl** [comment]
@paulbiss I'm running HHVM 3.8.0 with nginx fastcgi

**Comment by jannispl** [comment]
@paulbiss I've put together a script that reproduces this issue. https://gist.github.com/jannispl/5d852b2f8a9730cc209c

**Comment by paulbiss** [comment]
Thanks!

**Comment by eric-addcream** [comment]
I am also experience the issue with duplicate values.
https://gist.github.com/eric-addcream/c88c13af0278f4496581
HHVM 3.9.0, nginx 1.4.6, ubuntu 14.04
Also tested on hhvm 3.8.0

**Comment by mannebusk** [comment]
Having the problem with duplicate values in post.

##### My setup

 OS:
 
    Ubuntu 14.04 on VirtualBox with Vagrant.
 
HHVM: 

    HipHop VM 3.10.1 (rel)
    Compiler: tags/HHVM-3.10.1-0-g689b4969a141620ee5a282ce0dbf72278c84d44b
    Repo schema: 6c99ee1f98340f6f3ef397a332583f0e843a627d
 
NGINX:
 
    nginx/1.9.7

##### My form
    <form 
        action="/post.php"
        method="post"
        enctype="multipart/form-data"
    >
        <select id="webbhuset_variant_redirect_attribute_whitelist" name="groups[redirect][fields][attribute_whitelist][value][]" class=" select multiselect" size="10" multiple="multiple">
            <option value="bouncyness">Bouncyness (bouncyness)</option>
            <option value="color" selected="selected">Color (color)</option>
            <option value="cost">Cost (cost)</option>
            <option value="country_of_manufacture" selected="selected">Country of Manufacture (country_of_manufacture)</option>
            <option value="custom_design">Custom Design (custom_design)</option>
            <option value="custom_design_from">Active From (custom_design_from)</option>
            <option value="custom_design_to" selected="selected">Active To (custom_design_to)</option>
            <option value="custom_layout_update">Custom Layout Update (custom_layout_update)</option>
            <option value="description" selected="selected">Description (description)</option>
            <option value="expensiveness">Expensiveness (expensiveness)</option>
            <option value="gallery">Image Gallery (gallery)</option>
            <option value="gift_message_available">Allow Gift Message (gift_message_available)</option>
            <option value="group_price" selected="selected">Group Price (group_price)</option>
            <option value="image" selected="selected">Base Image (image)</option>
            <option value="is_recurring">Enable Recurring Profile (is_recurring)</option>
            <option value="manufacturer">Manufacturer (manufacturer)</option>
            <option value="media_gallery">Media Gallery (media_gallery)</option>
            <option value="media_image_crop">Image (media_image_crop)</option>
            <option value="meta_description">Meta Description (meta_description)</option>
            <option value="meta_keyword">Meta Keywords (meta_keyword)</option>
            <option value="meta_title">Meta Title (meta_title)</option>
            <option value="msrp">Manufacturer's Suggested Retail Price (msrp)</option>
            <option value="msrp_display_actual_price_type">Display Actual Price (msrp_display_actual_price_type)</option>
            <option value="msrp_enabled">Apply MAP (msrp_enabled)</option>
            <option value="name">Name (name)</option>
            <option value="news_from_date">Set Product as New from Date (news_from_date)</option>
            <option value="news_to_date">Set Product as New to Date (news_to_date)</option>
            <option value="options_container">Display Product Options In (options_container)</option>
            <option value="page_layout">Page Layout (page_layout)</option>
            <option value="price">Price (price)</option>
            <option value="price_view">Price View (price_view)</option>
            <option value="recurring_profile">Recurring Payment Profile (recurring_profile)</option>
            <option value="relation">asd (relation)</option>
            <option value="short_description">Short Description (short_description)</option>
            <option value="size">Size (size)</option>
            <option value="sku">SKU (sku)</option>
            <option value="small_image">Small Image (small_image)</option>
            <option value="special_from_date">Special Price From Date (special_from_date)</option>
            <option value="special_price">Special Price (special_price)</option>
            <option value="special_to_date">Special Price To Date (special_to_date)</option>
            <option value="status">Status (status)</option>
            <option value="tax_class_id">Tax Class (tax_class_id)</option>
            <option value="thumbnail">Thumbnail (thumbnail)</option>
            <option value="tier_price" selected="selected">Tier Price (tier_price)</option>
            <option value="url_key">URL Key (url_key)</option>
            <option value="visibility">Visibility (visibility)</option>
            <option value="weight">Weight (weight)</option>
            <option value="wh_image">Image (wh_image)</option>
        </select>
        <button type="submit">Submit</button>
    </form>

##### Result

```
array(1) {
  ["groups"]=>
  array(1) {
    ["redirect"]=>
    array(1) {
      ["fields"]=>
      array(1) {
        ["attribute_whitelist"]=>
        array(1) {
          ["value"]=>
          array(11) {
            [0]=>
            string(5) "color"
            [1]=>
            string(22) "country_of_manufacture"
            [2]=>
            string(16) "custom_design_to"
            [3]=>
            string(11) "description"
            [4]=>
            string(11) "group_price"
            [5]=>
            string(5) "image"
            [6]=>
            string(10) "tier_price"
            [7]=>
            string(11) "description"
            [8]=>
            string(11) "group_price"
            [9]=>
            string(5) "image"
            [10]=>
            string(10) "tier_price"
          }
        }
      }
    }
  }
}


------WebKitFormBoundaryA2g5zPkWGxBtgvqn
Content-Disposition: form-data; name="groups[redirect][fields][attribute_whitelist][value][]"

color
------WebKitFormBoundaryA2g5zPkWGxBtgvqn
Content-Disposition: form-data; name="groups[redirect][fields][attribute_whitelist][value][]"

country_of_manufacture
------WebKitFormBoundaryA2g5zPkWGxBtgvqn
Content-Disposition: form-data; name="groups[redirect][fields][attribute_whitelist][value][]"

custom_design_to
------WebKitFormBoundaryA2g5zPkWGxBtgvqn
Content-Disposition: form-data; name="groups[redirect][fields][attribute_whitelist][value][]"

description
------WebKitFormBoundaryA2g5zPkWGxBtgvqn
Content-Disposition: form-data; name="groups[redirect][fields][attribute_whitelist][value][]"

group_price
------WebKitFormBoundaryA2g5zPkWGxBtgvqn
Content-Disposition: form-data; name="groups[redirect][fields][attribute_whitelist][value][]"

image
------WebKitFormBoundaryA2g5zPkWGxBtgvqn
Content-Disposition: form-data; name="groups[redirect][fields][attribute_whitelist][value][]"

tier_price
------WebKitFormBoundaryA2g5zPkWGxBtgvqn--
```    

On my computer i consistently get duplicates when selecting 4 or more options. The problem goes away when i remove enctype="multipart/form-data" from the form tag.

We tried the same example on a co-worker's computer and he did not get this problem. The main difference between our setups is that he is running hhvm and nginx inside a docker container localy on Ubuntu 14.04. He's HHVM version 3.9.1 and Nginx 1.9.7.

We have had this problem on different sites for about a year on different HHVM versions, so I don't think it related to specific versions. We noticed that if you post different combinations of form data you can get rid of the duplicates, and this can be different combinations of form data when running on different computers.

**Comment by albertdahlin** [comment]
I can confirm this problem.
We have been running HHVM in production environment for about a year now. We are mostly running Magento sites.

Our setup varies, we have servers running nginx / hhvm and lighttpd / hhvm. All of them use fastcgi and Ubuntu server 14.04. The error occurs on both lighttpd and nginx.
It is not connected to a specific HHVM version. We have seen this error since we started using HHVM (don't remember the version) a year ago until the latest version, 3.10.1.

I have only seen this error occur on forms using the enctype="multipart/form-data" property. In Magento there are some pages that first sends the data as an url encoded post (via ajax, for validation) and then sends the same data as multipart/form-data for saving. The error never occurs on the first post (url encoded).

I have only seen the duplicate data on checkbox and multiselect inputs, which all have in common that their name ends with [], like `name="items[]"` or `name="product[options][]"`.

It seems like the process environment on the server is affecting the error (race condition?, cache problem?). It comes and goes, it happens on one server but not the other. Upgrading, restarting sometimes makes it go away, sometimes makes it come back.
However, once it is there, it is quite persistent until you restart or upgrade something.

Also changing the form data can affect it. We are using this workaround in Magento:
If the problem occurs, select a different option, save, select the correct option and save again. It works most of the time.

I hope this helps.
