### ISSUE TITLE
Default open_basedir to empty

### ISSUE THREAD

**Issue by lowjoel** [facebook/hhvm#1749]
According to [open_basedir's documentation](http://php.net/manual/en/ini.core.php#ini.open-basedir), it defaults to the empty string. HHVM however defaults to the upload filepath.

**Comment by Profforgr** [comment]
@fredemmott @sgolemon , this commit https://github.com/facebook/hhvm/commit/39ca4217056b6e3e3cd7ae20c359becc9ffe9ade most probably breaks multiple paths support in open_basedir ini variable. https://github.com/facebook/hhvm/issues/4735

There are a strong need in this support. It either needed for PHP compability and for using HHVM in common environments. Meaningless what separator would be, at least one separator should be supported (can be non-standart).
open_basedir="/a;/b"
open_basedir="/a:/b"

Why did @lowjoel modified tests with removing this check? How did that pass review?
```c#
-var_dump(ini_set('open_basedir', '/foo/a;/foo/b;'));		
+var_dump(ini_set('arg_separator.output', 'foo'));
-var_dump(ini_get('open_basedir'));		
+var_dump(ini_get('arg_separator.output'));
 ```

Can you please revert this or make a fix???

**Comment by fredemmott** [comment]
A new test was added in hphp/test/slow/ext_options/open_basedir.php

As you mentioned, there is #4735 for discussing a fix. That commit did fix some issues, and appears to test what was previously tested. Further discussion in #4735
