### ISSUE TITLE
mysqli_real_connect() parameter handling.

### ISSUE THREAD

**Issue by ipso** [facebook/hhvm#1817]
ZEND supports (bool)FALSE for mysqli_real_connect() parameters like port/socket, HHVM does not:

HipHop Fatal error: Argument 6 to mysqli_real_connect() must be of type ?int, bool given in /home/mikeb/public_html/timetrex/trunk/classes/adodb/drivers/adodb-mysqli.inc.php on line 113     

HipHop Fatal error: Argument 7 to mysqli_real_connect() must be of type ?string, bool given in /home/mikeb/public_html/timetrex/trunk/classes/adodb/drivers/adodb-mysqli.inc.php on line 117

**Comment by deltamualpha** [comment]
So folks watching this issue know: ADOdb changed some defaults in this commit: https://github.com/ADOdb/ADOdb/commit/3eb0913eecf148a7e0800fd7b4aa41af166254a3 and this specific error is resolved.

**Comment by Orvid** [comment]
PHP should not actually be allowing false as a valid alternative for false, and we don't. Null is supported.
