### ISSUE TITLE
Admin server does not work while in FastCGI mode

### ISSUE THREAD

**Issue by dkarlovi** [facebook/hhvm#1825]
This might be intentional, but I'm not sure it should be. If I run an instance in FastCGI mode, the admin server stops working, like so:

$ hhvm --mode server -vServer.Type=fastcgi -vServer.Port=9000 --admin-port=9999

(other terminal)
$ curl -v http://localhost:9999/
- Adding handle: conn: 0x966bf0
- Adding handle: send: 0
- Adding handle: recv: 0
- Curl_addHandleToPipeline: length: 1
- \- Conn 0 (0x966bf0) send_pipe: 1, recv_pipe: 0
- About to connect() to localhost port 9999 (#0)
-   Trying 127.0.0.1...
- Connected to localhost (127.0.0.1) port 9999 (#0)
  > GET / HTTP/1.1
  > User-Agent: curl/7.32.0
  > Host: localhost:9999
  > Accept: _/_
  > 
- Empty reply from server
- Connection #0 to host localhost left intact
  curl: (52) Empty reply from server

(output from hhvm)
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0215 14:40:13.050330  6966 fastcgi-session.cpp:566] FastCGI protocol: received an invalid record

$ hhvm --version
HipHop VM 2.4.0 (rel)
Compiler: tags/HHVM-2.4.0-0-gc82fcd8e6199c500454b1a8b930a876ef2c1522b
Repo schema: a536a1d1567b1fb5d722c0349a3296d4e8589f96

**Comment by mandb** [comment]
Here is what I use:

   
    location ^/hhvm/ {
        rewrite ^/hhvm/(.*)$ /$1 break;
        # pass to hhvm adminserver
        fastcgi_pass 127.0.0.1:8888; 
        include fastcgi_params;
    }

be sure to include your ?auth if you have secret enabled.
