### ISSUE TITLE
Generator behavior doesn't match PHP5

### ISSUE THREAD

**Issue by asm89** [facebook/hhvm#1871]
Apart from syntax (https://github.com/facebook/hhvm/issues/1627) and instanceof (https://github.com/facebook/hhvm/issues/1787) issues, generators in hhvm and zend behave differently.

The following gist contains three examples that show different behavior/output between hhvm and zend:
https://gist.github.com/asm89/9102248

**Comment by JeroenDeDauw** [comment]
+1 I'm also running into this

**Comment by noony** [comment]
https://3v4l.org/CjaLS
https://3v4l.org/95Q6f
https://3v4l.org/Clno2

Seems ok in 3.11. Can we close ?

**Comment by fredemmott** [comment]
Yep, likely fixed at the same time as the PHP7 changes were implemented.
