### ISSUE TITLE
Support for AMQP

### ISSUE THREAD

**Issue by zegl** [facebook/hhvm#1912]
Hi!

Is there any plans of including a AMQP-library (with RabbitMQ support) in HHVM? 

http://pecl.php.net/package/amqp

**Comment by jippi** [comment]
Is there any plans to implement AMQP ?

**Comment by fproject** [comment]
Please anyone port a AMQP extension to HHVM?

We urgently need it.

**Comment by akalend** [comment]
I begining the port AMQP project https://github.com/akalend/hhvm-amqp

**Comment by paulbiss** [comment]
Looks like there's an external project for this now.

**Comment by tslettebo** [comment]
Unfortunately, the Github extension no longer works with the latest version of RabbitMQ Library. I've talked with the author, and he confirms this.

We're using AMQP in our company, and we'd like to start using HHVM/Hack, but this prevents us from doing that.

Therefore, I'd appreciate it if this issue could be reopened.

**Comment by fredemmott** [comment]
Re-opening for now, though we're fairly likely to bulk-close extension request issues soon: we're extremely unlikely to implement any within the next year at least, given we need to develop Hack replacements for the PHP extensions that we already ship.

Your best option is probably to look at updating that external project yourself.
