### ISSUE TITLE
Suggestion to enable long polling/comet server

### ISSUE THREAD

**Issue by frodeborli** [facebook/hhvm#1927]
Due to the unique position HHVM has, it should be quite possible to create a comet server with HHVM. It would require a function such as

$socketIdentifier = hhvm_client_store();

This would put the output socket on hold. Any future PHP process could then call something like

$fp = hhvm_client_retrieve($socketIdentifier);
fwrite($fp, "HTTP output");
fclose($fp);

**Comment by paulbiss** [comment]
This feature request is not actively being worked on. We would happily consider a pull request implementing it. If you plan to work on this issue let us know in the comments and we will re-open the issue and assign it to you. If you feel strongly that this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
