### ISSUE TITLE
When hhvm crashed,it won't restart automatically

### ISSUE THREAD

**Issue by ed29** [facebook/hhvm#1939]
I am using hhvm nightly as fastcgi daemon,when hhvm crashed,it won't restart automatically and back to service,it need to start manually.

As a service,hhvm should auto restart when it crashed i think.

**Comment by unicco33** [comment]
Hi. I've not worked with bash-scripts before. Could someone try and explain how the bash-script should be used?

I don't understand the "if [ "$1" == "" ]; then". Where is $1 coming from? Do I need to parse that?

Testing the bash-script using "bash restart_hhvm.sh" returns Usage: restart_hhvm.sh svcname. So obviously the statement is true. I just dont understand how that $1 should be used?

I've set an cronjob: @hourly /path/to/script.sh, which I believe is correct.
