### ISSUE TITLE
Support Behat suites for the framework tests

### ISSUE THREAD

**Issue by stof** [facebook/hhvm#1978]
t would be great if Behat testsuites could be supported as well for the framework tests. This would allow other projects to be added to the framework suite.

Once this is supported, Behat itself could be added to the list of projects

**Comment by stof** [comment]
I was asking about supporting the test mechanism provided by Behat (which is a prerequisite for running the Behat suite)

**Comment by paulbiss** [comment]
I don't think we currently have plans to support other test mechanisms. cc @fredemmott

**Comment by fredemmott** [comment]
We'll happily review pull requests, but we're not planning on working on this.
