### ISSUE TITLE
HHVM over FastCGI hangs randomly with larger computations

### ISSUE THREAD

**Issue by treffynnon** [facebook/hhvm#2028]
I have written a small benchmarking suite that includes CLI tests for PHP, HHVM and Zephir. I am now attempting to add FastCGI tests for PHP, HHVM and Zephir.

The [code is available](https://github.com/treffynnon/Benchmark-PHP-HHVM-Zephir/tree/fcgi) in the fcgi branch on GitHub.

Essentially I have created a HHVM extension, PHP and Hack version of the same Mandelbrot set generating code (see `fcgi-hhvm-*` on GitHub project). For each of them I setup (`setup.sh`) a HHVM FastCGI server, warm it up by making a few requests against it and then benchmark with a number of runs (20 in these tests). The FastCGI request is handled by a C++ FastCGI CLI client (`fcgicli` git submodule).

It works fine with Mandelbrot sets of 100x100 and 200x200, but as soon as it is ramped up to 1,000x1,000 it randomly hangs during one of the 20 iterations for HHVM running PHP, Hack or via the HHVM extension. Sometimes it makes it as far as iteration 17 or 18, but normally it hangs after under 10 iterations. When I ask it to do a set of 2,000x2,000 it fails to complete one iteration.

Unfortunately nothing is written to the HHVM logs either and it just silently hangs. If I kill the job and try to re-run it without stopping and starting the server it hangs without executing anything. So it is leaving the server in a failed state, but not causing the server to crash or die.

I have tried changing a number of config options - see the related issue on my project: https://github.com/treffynnon/Benchmark-PHP-HHVM-Zephir/issues/7

Incidentally the PHP scripts using PHP's `php-cgi` and Zend OPcache take longer to run, but they complete successfully every time (for sets 1000x1000, 2000x2000 and 5000x5000) so I am pretty sure it isn't something in my client implementation, but something in HHVM itself - you never know though of course! The same test runs fine via HHVM on the CLI as well, but not via FastCGI.

So this could be caused by a configuration issue or by something in HHVM itself - I have no idea, but I would like to get it working so any help appreciated.

I am just gonna ping @ptarjan here as from my previous ticket I believe this maybe your area of HHVM development.

Additionally I am now running HHVM built from commit 190a12a7a5c8b79a16182107afad5ecc7971b303

**Comment by oxygens** [comment]
Why is this closed? After relatively small number of requests HHVM simply hangs, Ubuntu as well. Tried multiple versions, including the latest unstable.

This is a serious issue.

**Comment by paulbiss** [comment]
@oxygens we close issues that need follow-up information after two weeks of inactivity. If you're still seeing this in either 3.3.2 or 3.4.2 I'll reopen, as that's all @JoelMarcey wanted to know.

**Comment by digitalronin** [comment]
I'm seeing this behaviour with 3.6.1

    # hhvm --version
    HipHop VM 3.6.1 (rel)
    Compiler: tags/HHVM-3.6.1-0-gc051feff88ba8050f33f10f7b1fb07f8d3415f9e
    Repo schema: 42f49251b5c27daf4e13cb6bcd0c7ef4824b55a3

Running in a Docker container based on Ubuntu 14.04.

Everything seems fine for a few calls, then the hhvm process silently hangs, consuming virtually no CPU or memory, until I kill -9 it, then runit restarts hhvm and the whole cycle happens again.

**Comment by treffynnon** [comment]
@paulbiss I haven't had a chance to test this again, but it would appear from @digitalronin and @oxygens that this is still an ongoing problem. Is this enough to re-open the ticket?

**Comment by fredemmott** [comment]
Can this be reproduced on recent versions? If so, one of the following would be useful:
 - the output of 'thread apply all bt' from gdb
 - a screenshot of perf record/perf report -g

**Comment by mandb** [comment]
still happening on 3.10 with wordpress behind it - requests just die at random points in execution (long running scripts ie: install a plugin) will get farther before dying.   Once a thread hangs, it will no longer serve requests.

**Comment by fredemmott** [comment]
We can't do anything without output from gdb or perf. This honestly should have been closed by now for not having enough information to be looked at, and will be in a few weeks unless that changes.

**Comment by mandb** [comment]
Actuality I straced it and it was hung on an external resource, but it
stayed hung on it indefinitely, refusing to answer any other requests
routed to the affected worker by the master process and despite a max
execution time.

**Comment by kandy** [comment]
@fredemmott, Can you add script that create report for issue reporting? It will be useful for provide more information for any issue. tnx

**Comment by fredemmott** [comment]
@mandb : what kind of external resource? Do you know what PHP function was being used?
@kandy: sorry, I won't be able to do that. There is plenty of documentation available on gdb and perf on other sites though.

**Comment by fredemmott** [comment]
Closing; will re-open if needed information is provided.

**Comment by Lewiscowles1986** [comment]
I get this in xenial using stock hhvm with WordPress when deleting large numbers of posts (~4000) using the WordPress UI. Enough pkill's seems to make hhvm behave itself, and we've not encountered the issue.

Instead of using the UI, we now just delete posts and postmeta manually, and HHVM is happy. It is very definitely a bug in hhvm as calling service stop hhvm the service termination hangs. For this just put hhvm in a docker and destroy the container (a few seconds). This shouldn't happen to enough containers for it to be a problem

**Comment by Orvid** [comment]
The current package available for Xenial is 3.11, which is not a supported version. We are planning on starting the process of building the packages for 3.14, which will include packages for Xenial, later today. It takes time to do and we plan on releasing a point update for 3.9, 3.12, and 3.13 before building the packages for 3.14.

**Comment by Lewiscowles1986** [comment]
It's fine, it's a vagrant box for a project I'm working on, so no big deal really. Still using Trusty and your official repos in the wild and not encountered the issue there :wink:

**Comment by treffynnon** [comment]
It is very unlikely that I'll have interest in testing this again. If anyone wants to fix this issue then the code I've referenced is clearly documented and you can run the project yourselves against a build of HHVM.

**Comment by Lewiscowles1986** [comment]
Latest HHVM still does it, I've just marked as a not now solution if it cannot reliably handle a WordPress install something is wrong
