### ISSUE TITLE
"libevent" migrate to "libev" or "libuv" engine

### ISSUE THREAD

**Issue by denji** [facebook/hhvm#2047]
Boost network performance libev. libevent have overhead initialization start
http://software.schmorp.de/pkg/libev.html

[Appendix: Benchmark graphs for libev 4.03, libevent 1.4.13, libevent 2.0.10](http://libev.schmorp.de/bench.html)

Libev (first released in 2007-11-12) is also a high-performance event loop, supporting eight event types (I/O, real time timers, wall clock timers, signals, child status changes, idle, check and prepare handlers).

It uses a priority queue to manage timers and uses arrays as fundamental data structure. It has no artificial limitations on the number of watchers waiting for the same event. It offers an emulation layer for libevent and optionally the same DNS, HTTP and buffer management (by reusing the corresponding libevent code through its emulation layer).

Download: http://dist.schmorp.de/libev/Attic/libev-4.15.tar.gz ([archive download](http://dist.schmorp.de/libev/Attic/?M=D))

[Design libev and libevent](http://blog.gevent.org/2011/04/28/libev-and-libevent/)

**Comment by steelbrain** [comment]
Tara Rum Pum, Bump.

**Comment by steelbrain** [comment]
Now that HHVM uses Proxygen instead of libevent, I think this issue should be closed, I would've loved to see libuv supported in HHVM though, the community extensions are out of date.

**Comment by Orvid** [comment]
HHVM still uses libevent in a few places, I know this, because I've had to do some adjustments to a few libevent APIs in order to make it play nicer with they way I ported HHVM to windows.

**Comment by steelbrain** [comment]
@Orvid are those places planned to be removed or they are gonna be around for some time?

**Comment by fredemmott** [comment]
closing:
 - the libevent 1.x server is about to be completely removed (and is an optional build component anyway)
 - the performance argument here does not justify the effort to replace libevent 2.0 in other places given it has *never* shown up as a significant factor in real application profiles

If you have a non-performance reason for replacing the remaining libevent code with something else, please file another issue. If you want a new extension exposing it to userspace, that could be a separate feature request issue, however we're unlikely to implement it - it would be better addressed by a community extension.
