### ISSUE TITLE
high hhvm CPU usage when idle after high usage

### ISSUE THREAD

**Issue by gasparfm** [facebook/hhvm#2069]
Hi,
I'm using hhvm 2.4.2 on an Ubuntu server 12.04 machine with Apache 2.2 in fastcgi mode, and using a WordPress blog to make all the tests Everything works out of the box, but from another server I do:

$ ab -n 50000 -c 400 http://my/server

The test goes fine, but after the test hhvm process keeps eating 100% CPU until I restart the server. How can I know what is hhvm doing? I've tested php-fpm and it doesn't do the same.

Thanks

**Comment by chielsen** [comment]
I have the exact same thing as TS with 3.5.0 (rel). I see no other errors. Any advise on how to debug further?

**Comment by jwatzman** [comment]
A backtrace from the stuck thread could be useful.

**Comment by chielsen** [comment]
How do i do that?

**Comment by jwatzman** [comment]
Run `sudo gdb $(which hhvm) $(pidof hhvm)`, then `thread apply all bt` at the `gdb` prompt.

**Comment by dstelter** [comment]
I'm experiencing the same issue on a fairly large code base. Been waiting for an hour without any changes.
strace shows a lot of timing and epoll calls (epoll_wait(5, {}, 32, 10)   = 0) for a while, which stop after a few minutes, but the CPU remains at 100%.
Thread stacks:

Thread 4 (Thread 0x7fc6887ff700 (LWP 26161)):
#0  0x00007fc692ed36a3 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007fc696c7b813 in ?? () from /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5
#2  0x00007fc696c67907 in event_base_loop () from /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5
#3  0x0000000001fd2d57 in folly::EventBase::loopBody(int) ()
#4  0x0000000001fd5a03 in folly::EventBase::loopForever() ()
#5  0x0000000001e4e4ba in proxygen::WorkerThread::runLoop() ()
#6  0x0000000001e4f8d5 in std::thread::_Impl<std::_Bind_simple<proxygen::WorkerThread::start()::{lambda()#1} ()> >::_M_run() ()
#7  0x00007fc69376bbf0 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007fc6939c6182 in start_thread (arg=0x7fc6887ff700) at pthread_create.c:312
#9  0x00007fc692ed300d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 3 (Thread 0x7fc680fff700 (LWP 26163)):
#0  0x00000000020fa3db in HPHP::FixedStringMap<unsigned int, true, unsigned int>::find(HPHP::StringData const*) const ()
#1  0x0000000000ba90d9 in HPHP::Class::getDeclPropIndex(HPHP::Class const*, HPHP::StringData const*) const ()
#2  0x00000000020fcd0e in HPHP::ObjectData::propW(HPHP::TypedValue*&, HPHP::TypedValue&, HPHP::Class*, HPHP::StringData const*) ()
#3  0x000000000104f2c9 in HPHP::jit::MInstrHelpers::cGetPropSO(HPHP::Class*, HPHP::TypedValue*, HPHP::StringData*, HPHP::MInstrState*) ()
#4  0x0000000003628070 in ?? ()
#5  0x0000000002105b48 in enterTCHelper ()
#6  0x0000000002105bc9 in HPHP::jit::x64::BackEnd::enterTCHelper(unsigned char*, HPHP::jit::TReqInfo&) ()
#7  0x0000000002105595 in HPHP::jit::MCGenerator::enterTC(unsigned char*, void*) ()
#8  0x00000000021048b9 in HPHP::ExecutionContext::invokeFunc(HPHP::TypedValue*, HPHP::Func const*, HPHP::Variant const&, HPHP::ObjectData*, HPHP::Class*, HPHP::VarEnv*, HPHP::StringData*, HPHP::ExecutionContext::InvokeFlags) ()
#9  0x000000000215a619 in HPHP::ExecutionContext::invokeUnit(HPHP::TypedValue*, HPHP::Unit const*) ()
#10 0x000000000215a4a7 in HPHP::invoke_file(HPHP::String const&, bool, char const*) ()
#11 0x00000000009ee552 in HPHP::include_impl_invoke(HPHP::String const&, bool, char const*) ()
#12 0x00000000008444f2 in HPHP::hphp_invoke(HPHP::ExecutionContext*, std::string const&, bool, HPHP::Array const&, HPHP::VRefParamValue const&, std::string const&, std::string const&, bool&, std::string&, bool, bool, bool) ()
#13 0x0000000000b27e27 in HPHP::HttpRequestHandler::executePHPRequest(HPHP::Transport*, HPHP::RequestURI&, HPHP::SourceRootInfo&, bool) ()
#14 0x0000000000b296aa in HPHP::HttpRequestHandler::handleRequest(HPHP::Transport*) ()
#15 0x0000000000b357cd in HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJob(std::shared_ptr<HPHP::FastCGIJob>) ()
#16 0x0000000000b3e326 in HPHP::JobQueueWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::Server*, true, false, HPHP::JobQueueDropVMStack>::start() ()
#17 0x0000000001bf6e07 in HPHP::AsyncFuncImpl::ThreadFunc(void*) ()
#18 0x00000000009be3f7 in HPHP::start_routine_wrapper(void*) ()
#19 0x00007fc6939c6182 in start_thread (arg=0x7fc680fff700) at pthread_create.c:312
#20 0x00007fc692ed300d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 2 (Thread 0x7fc67bbff700 (LWP 26210)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x0000000001bd2908 in HPHP::SynchronizableMulti::waitImpl(int, int, bool, timespec*) ()
#2  0x0000000000b3e10a in HPHP::JobQueueWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::Server*, true, false, HPHP::JobQueueDropVMStack>::start() ()
#3  0x0000000001bf6e07 in HPHP::AsyncFuncImpl::ThreadFunc(void*) ()
#4  0x00000000009be3f7 in HPHP::start_routine_wrapper(void*) ()
#5  0x00007fc6939c6182 in start_thread (arg=0x7fc67bbff700) at pthread_create.c:312
#6  0x00007fc692ed300d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 1 (Thread 0x7fc681bff700 (LWP 26157)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x0000000000b33168 in HPHP::HttpServer::runOrExitProcess() ()
#2  0x000000000085ae6a in HPHP::execute_program_impl(int, char**) ()
#3  0x000000000085c3df in HPHP::execute_program(int, char**) ()
#4  0x00000000007d893c in main ()

**Comment by ksaltik** [comment]
Same situation and can't get any answer from developers. 

Read it 

https://www.redy.host/blog/drupal-8-stress-test-round-3
In our previous test (Making Drupal 8 Fly), this same setup (but using HHVM) was maxing out at 13542 responses received (the test stopped counting responses strictly at 1 minute 00 seconds since the test start) and the average response time was 4426ms. As you see in the picture above, PHP7 was able to outperform HHVM by serving 32.7% more responses in 33.3% less average response time.

As mentioned in this article after one minute HHVMstarts to eat CPU it doesn't matter how many cores you have.

.they don't accept this issue because accepting this issue will make them vulnerable to attacks and recent failures of Facebook shows the problem is obvious.

**Comment by fredemmott** [comment]
Deleted @ksaltik's comment for spamming it all over the place.

**Comment by steelbrain** [comment]
Thanks @fredemmott much appreciated!
