### ISSUE TITLE
symlink issues

### ISSUE THREAD

**Issue by HemeraGP** [facebook/hhvm#2083]
Hi currently I'am experiencing some trouble with being in the correct working directory

When I var_dump the getcwd()

folder according to hhvm:
/usr/home/www/production/current/mainsite/js
folder according to php5-fpm:
/home/www/production/20140317/js

there is a require in the files which are inside here which use relative paths (../folder/bla.php)
now you can probably imagine that we do have the folder in the fpm case but not in the hhvm. Since it only goes up one directory it has one to short to land in the right directory.

Some folder structure information:

/usr/home symlinks to /home

inside /home/www/production
current -> 20140218

inside /home/www/production/current/mainsite
js -> ../js

I tried enabling Eval.CheckSymLink=true but I think this is for something diffrent

**Comment by Orvid** [comment]
I believe this has been fixed already.
