### ISSUE TITLE
is_dir does not support FTP wrapper

### ISSUE THREAD

**Issue by idn2104** [facebook/hhvm#2108]
This causes failure of a symfony test case.

Code:

```
<?php
$uri = 'ftp://ftp.mozilla.org/';
var_dump(is_dir($uri));
```

zend:

```
bool(true)
```

hhvm:

```
bool(false)
```

(What level of support does hhvm intend to provide for the FTP wrapper / wrappers in general?)

http://uk3.php.net/manual/en/wrappers.php - list of wrappers
http://uk3.php.net/manual/en/wrappers.ftp.php - functions supported by zend FTP wrapper

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Support for wrappers and filters has been removed from hhvm.
`Warning: Unknown URI scheme "ftp"`

Tested with hhvm 4.56.
