### ISSUE TITLE
Oracle oci8 and pdo_oci support

### ISSUE THREAD

**Issue by ravzanlive** [facebook/hhvm#213]
Hi.

I need oci support and in PDO too (oci8 and pdo_oci extensions).

"HipHop Fatal error: Uncaught exception could not find driver"

Best regards

**Comment by wickedsheep** [comment]
Hi, are there any plans on supporting Oracle?

**Comment by fredemmott** [comment]
We have an extension that historically we've not released as we did not support disabling extensions, it's a pain to build, and requires a proprietary .so. We will almost certainly not include this in our packages, but I'll see if we can at least start distributing source.

**Comment by wickedsheep** [comment]
That would be much appreciated, thank you.

**Comment by paulbiss** [comment]
This feature request is not actively being worked on. We would happily consider a pull request implementing it. If you plan to work on this issue let us know in the comments and we will re-open the issue and assign it to you. If you feel strongly that this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
