### ISSUE TITLE
stream_socket_client() raises OpenSSL error (works fine in PHP)

### ISSUE THREAD

**Issue by marcoarment** [facebook/hhvm#2154]
As part of my Apple Push Notification (APN) class, I open an SSL connection with `stream_socket_client`:

``` php
$ctx = stream_context_create();
stream_context_set_option($ctx, 'ssl', 'local_cert', $cert_filename);
stream_context_set_option($ctx, 'ssl', 'passphrase', $cert_password);

$connection = stream_socket_client(
    'ssl://gateway.sandbox.push.apple.com:2195', $err, $errstr, 60,
    STREAM_CLIENT_CONNECT | STREAM_CLIENT_PERSISTENT, $ctx
);
```

(abridged; [file's full source](https://gist.github.com/marcoarment/9718357#file-applepushnotification-php-L110))

This is called from a CLI script. With PHP 5.4.26, it works fine every time, on the same server, in the same directory, with the same data, immediately before or after trying it in HHVM. I think this safely rules out certificate or connection issues.

When run under HHVM, this happens every time:

```
SSL operation failed with code 1. OpenSSL Error messages:
error:14094410:SSL routines:func(148):reason(1040)

#0 (): reprise_error_handler()
#1 /.../ApplePushNotification.php(107): stream_socket_client()
#2 /.../ApplePushNotification.php(69): ApplePushNotification::connection()
#3 /.../APNS.php(44): ApplePushNotification::send_to_device()
...
```

HHVM info:

```
$ hhvm --version
HipHop VM 2.4.0 (rel)
Compiler: tags/HHVM-2.4.0-0-gc82fcd8e6199c500454b1a8b930a876ef2c1522b
Repo schema: c63b08a9dc618c8a3eaea633d4d1776b668c75d6
```

**Comment by integrii** [comment]
I am still getting this error with HHVM 3.8.  Issue #1647 says this was fixed.  I am simply trying to send apple push notifications with hhvm.  
```
hhvm --version
HipHop VM 3.9.0 (rel)
Compiler: 1440451850_669097242
Repo schema: 657201f20f0018d281a00312af666e3ccd48b89a
```

**Comment by paulbiss** [comment]
@integrii you mentioned HHVM 3.8 but the paste shows 3.9 (also note that the most current release is 3.9.1). This issue is about a missing feature which has since been implemented. Please open a new issue with more detail about the error you're seeing.

**Comment by integrii** [comment]
Thanks @paulbiss. I actually just got this working.  My startup script was starting an old HHVM binary even though I had deployed the new patched one.

**Comment by aquasmit** [comment]
@integrii How you got it working. I am getting same error. I am using hhvm 3.12 but still i m getting same error "Unable to enable crypto on TCP connection gcm-http.googleapis.com"

**Comment by fredemmott** [comment]
Please give example code in a new issue - closed issues are rarely looked at.
