### ISSUE TITLE
capture_peer_cert for SSL context does not have any effect

### ISSUE THREAD

**Issue by rmccue** [facebook/hhvm#2156]
As far as I can tell, setting the `capture_peer_cert` option on the SSL stream context does not appear to have any effect. The `peer_certificate` option is not populated after the request is made, so it's impossible to parse this out.

To reproduce:
```php

$context = stream_context_create(['ssl' => ['verify_peer' => true, 'capture_peer_cert' => true]]);

$connection = stream_socket_client('ssl://httpbin.org:443', $errno, $errstr, 10, STREAM_CLIENT_CONNECT, $context);

var_dump(stream_context_get_options($context));
```

**Comment by Orvid** [comment]
Looks to be fixed: https://3v4l.org/RUU3g
