### ISSUE TITLE
htmlentities() fails with valid ISO-8859-1 chars

### ISSUE THREAD

**Issue by garyemiller** [facebook/hhvm#2186]
Similar to bug #1875   htmlentities() is stripping valid ISO-8859-1 characters from its input.

```
cat /tmp/tmp.php

<?php

echo "\n";
$s = chr( 0xAE ); // this is an ISO-8859-1 circle R

var_dump( htmlentities( $s, ENT_QUOTES | ENT_IGNORE, 'ISO-8859-1'));

echo "\n";

?>
```

Test code works in PHP:

```
php /tmp/tmp.php

string(5) "®"
```

Test code fails in hhvm:

```
hhvm /tmp/tmp.php

string(0) ""
```

**Comment by jesseschalken** [comment]
The PHP/HHVM docs for `htmlspecialchars` says:

> The translations performed are:
> 
> - `&` (ampersand) becomes `&amp;`
> - `"` (double quote) becomes `&quot;` when ENT_NOQUOTES is not set.
> - `'` (single quote) becomes `&#039;` (or `&apos;`) only when ENT_QUOTES is set.
> - `<` (less than) becomes `&lt;`
> - `>` (greater than) becomes `&gt;`
> 
> ...
> 
> For the purposes of this function, the encodings ISO-8859-1, ISO-8859-15, UTF-8, cp866, cp1251, cp1252, and KOI8-R are effectively equivalent, provided the string itself is valid for the encoding, as the characters affected by htmlspecialchars() occupy the same positions in all of these encodings.
> 
> ...
> 
> Note:
> Note that this function does not translate anything beyond what is listed above. For full entity translation, see htmlentities().

Which all makes sense to me.

But according to this bug PHP/HHVM will do *extra* replacements eg `"\xAE"` => `"&reg;"` if `$encoding` is  ISO-8859-1? If so, where can I find a correct description of what `htmlspecialchars` actually *does*?

And am I better off doing a simple

```php
$r = array(
    '&' => '&amp;', 
    '"' => '&quot;',
    "'" => '&#039;',
    '<' => '&lt;',  
    '>' => '&gt;',  
);
str_replace(array_keys($r), array_values($r), $text);
```
(assuming `$text` is  UTF-8 or ISO-8859-1)

?
