### ISSUE TITLE
Bring the Code Model API (HH\CodeModel) back

### ISSUE THREAD

**Issue by sebastianbergmann** [facebook/hhvm#2228]
In https://github.com/facebook/hhvm/commit/347684a844ecf1b865bc069c17ef7f8c96b7398a the Code Model API was removed because it caused a breakage on Travis.

The purpose of this ticket is to track the progress of bringing the Code Model API back.

**Comment by paulbiss** [comment]
This feature request is not actively being worked on. We would happily consider a pull request implementing it. If you plan to work on this issue let us know in the comments and we will re-open the issue and assign it to you. If you feel strongly that this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.

**Comment by paulbiss** [comment]
As a side note the project has been reverted internally as well.
