### ISSUE TITLE
Request for --parse, or a way to compile Hack to PHP if only type annotations are used

### ISSUE THREAD

**Issue by marcoarment** [facebook/hhvm#2236]
You've all done a great job with the Hack language, but as it's so new, I'm hesitant to start writing all of my code in Hack. But I'd love to start using Hack's type annotations in otherwise pure-PHP code. I bet I'm not the only one.

This would be a way for _lots_ of PHP programmers to dip their toes into Hack while still having an easy exit if it doesn't work out, short- or long-term: we could gain most of the benefits of type annotations with HHVM's analysis in development and testing, even if the production environment is running stock PHP.

What's needed is a simple compiler that strips Hack's type annotations out, leaving valid PHP behind. Obviously, this would only work on the additions in Hack that are easily stripped out or compiled to PHP, but even if it's **just** the type annotations, that's still **extremely** beneficial and in-demand among PHP coders.

`token_get_all()` does work on Hack syntax, but tokens aren't _that_ helpful — what we really need to do it right is the parse tree. If you implement the `--parse` command-line flag, it would be trivial to write such a tool. (And it probably wouldn't be that much more work to just build this entire feature.)

Thanks for your consideration.

**Comment by Pacerier** [comment]
Re "at which point it just makes more sense to use HHVM", you've **completely** missed the point. I can write in PHP and it can run **everywhere**. I can write in Hack and it can't run anywhere.

Hack **only** makes sense if it can be converted to PHP.
