### ISSUE TITLE
RFC: Add pgsql as bundled DSO

### ISSUE THREAD

**Issue by Aatch** [facebook/hhvm#2245]
So I've been maintaining `hhvm-pgsql` for a while now as a separate extension, as it could not be easily included in the main tree without introducing a dependency on pgsql. With 7b75fff03900d it looks like that isn't problem any more and the extension could be bundled into the tree.

**Comment by MegaByte** [comment]
Any plans to move on this?

**Comment by photodude** [comment]
:+1: 

@paulbiss, @sgolemon, @scannell, @LiraNuna, Any plans to move on this?

**Comment by photodude** [comment]
strange, wonder why the assignment changed to remove @sgolemon as the assigned (it's not like I should be able to do that)

**Comment by SiebelsTim** [comment]
There was a PR for this if I remember correctly.
