### ISSUE TITLE
RFC: Ability to mark functions as non-terminating/noreturn

### ISSUE THREAD

**Issue by Aatch** [facebook/hhvm#2252]
## Overview

Allow developers to inform the Hack typechecker that a function never returns.

## Motivation

It is not uncommon to have helper functions and methods that always cause execution to diverge, i.e. not follow normal flow. This can be through throwing an exception, raising an error or calling a function like `exit`. Right now these functions are treated like any other function in Hack, requiring code like this:

```php
function foo(bool $cond) {
  if ($cond) {
    do_error();
    invariant_violation("unreachable");
  }
}
```

While this isn't always a big deal, a function with a sequence of checks one after the other requires an `invariant_violation` call to be added for each check, adding significantly to the noise in a function.

This is because Hack only recognises `throw`, `return` and a handful of special-cased functions as affecting control flow.

## Proposal

There are a few options for this.

### User Attribute

A user attribute, such as `<<__NoReturn>>` could be added to the function, marking it as a function that doesn't return. This has the advantage of not requiring any user-visible changes to HHVM or Hack. The disadvantage is that it relies on the programmer ensuring that it's true.

### Special Type

A special "diverging" type could be added. This type would be considered a subtype of all other types, would only be valid in the return position of a function or method and would indicate that the function diverges. This has the advantage of fitting in well with the typesystem, allowing for cases like `return do_fail()` to work seemlessly. It also allows functions to be better checked, if somebody marks a function as "returning" a diverging type and then does something like this: `return "foo";` then the type checker will catch this as `string` is not a subtype of this hypothetical type.

It would require changes to Hack and HHVM to handle the type annotation. Rust uses `!` as the diverging type, however this is relatively unimportant. Furthermore, this would require changes to the Hack typesystem and would link the typesystem and the terminal checker.

### Inference

Kinda similar to the previous option, however instead of requiring an explicit type for functions that don't return, instead Hack could "work out" that a function never returns and mark that internally. This has the same advantage as the first option of not requiring any user-visible features. However, if a change is made to the function that causes the terminating inference to fail, it could cause many errors that would be indicated away from the true source of the issue. Also, there would be no indication in the source of the functions terminating status, which could cause some confusing messages.

---

I'm personally fond of the second option, due to it's relative simplicity.

This change would also allow the current hard-coded functions, `assert`, `invariant` and `invariant_violation` to be handled like normal functions, instead of hard coded into the Hack typechecker.

**Comment by jwatzman** [comment]
Since it just came up again, an update, this is still on our radar. It's something we really want to do (it's a useful feature with huge demand both inside and outside FB), but unfortunately the typechecker needs a somewhat involved refactor to be able to support it. @elgenie has tossed around some ideas and I think is planning to eventually do that refactor (it's good in general, will get us some perf and memory savings), but hasn't started on it yet.

**Comment by BobertForever** [comment]
For a temp-fix, is it best to just change the file to be in decl mode?

**Comment by fredemmott** [comment]
You could mark the block // UNSAFE, or the expression // UNSAFE_EXPR

**Comment by jwatzman** [comment]
You can also stick `invariant_violation('cannot get here');` after every function that would otherwise be noreturn.

**Comment by fredemmott** [comment]
it looks like @elgenie started working on this

**Comment by sgolemon** [comment]
He finished working on it as well, in June. :)

http://beta.docs.hhvm.com/hack/types/type-system#noreturn
