### ISSUE TITLE
Optimisation: Keep Imm* collection literals between requests

### ISSUE THREAD

**Issue by Aatch** [facebook/hhvm#2259]
Currently literal arrays are created once at compile time, meaning that large tables of constant data can be re-used between requests. This works because arrays are copy-on-write.

With the recent addition of `ImmVector` and it's immutable friends, a similar optimisation could be done, as the data cannot be changed after creation. This would obviously be limited to Imm* collections created using the literal syntax.

**Comment by Orvid** [comment]
Don't we already do this?

**Comment by paulbiss** [comment]
We do for the underlying array, we can't do that with the object wrapper though the immutable object project/rfc may make this possible.
