### ISSUE TITLE
Provide INI options for all HDF options, add documentation

### ISSUE THREAD

**Issue by flashek** [facebook/hhvm#2267]
Hi,

I have found that some settings from HDF style configuration weren't ported into new INI one. This affects ````hhvm.repo.authoritative```` and other similiar. Should I add those features using command line ````-v````?

**Comment by paulbiss** [comment]
There are some areas where we are missing equivalent options, particularly for some of the more complex syntax supported by HDF, but the basic set of options is both well supported and well documented.

https://docs.hhvm.com/hhvm/configuration/INI-settings
