### ISSUE TITLE
FreeBSD installation

### ISSUE THREAD

**Issue by gsoul** [facebook/hhvm#2312]
Hello everyone.

It would be wonderful if you could start supporting FreeBSD.

But for now even the hackish way from docs is not valid:
https://github.com/facebook/hhvm/wiki/Building-and-Installing-on-FreeBSD-8.2

Triing to follow the instructions I get:

> fatal: unable to connect to canonware.com:
> canonware.com[0: 204.109.63.53]: errno=No error
> git did not exit cleanly (exit code 128)

On the first step. Could you please at least provide a way to install hhvm on FreeBSD?
P.S. Many thanks for the great product! I'm very excited about how it speeds up the sites.

**Comment by jrobeson** [comment]
i think it should probably closed, and then new issues can be opened as they appear and tracked separately instead of having to go through comments to see all the issues within it.

**Comment by jwatzman** [comment]
Yeah I don't see much use in keeping this issue open. If someone would like to get it working, please feel free to update the wiki, and we'd love to take any (clean) PRs to fix issues. But it's unlikely the team will officially support any of the BSDs right now.

**Comment by fredemmott** [comment]
Added a header to the wiki page.
