### ISSUE TITLE
Option to format ServerErrorMessage

### ISSUE THREAD

**Issue by gabelevi** [facebook/hhvm#2341]
PHP developers are used to seeing errors outputted to the browser, rather than tailing an error file. The `ServerErrorMessage` runtime option does turn on this functionality, but it's not formatted as they expect (it's missing the file name, maybe some other information). It's also not well documented, so people often ask how to do this.

**Comment by paulbiss** [comment]
This feature request is not actively being worked on. We would happily consider a pull request implementing it. If you plan to work on this issue let us know in the comments and we will re-open the issue and assign it to you. If you feel strongly that this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
