### ISSUE TITLE
Service Unavailable Timeout

### ISSUE THREAD

**Issue by TheRyanHowell** [facebook/hhvm#2362]
There doesn't appear to be any up-to date documentation on increasing time-outs, I am running an extremely load intensive SQL query through PDO and require longer time-outs.

I'm using Apache 2.4 with FastCGI, any help would be appreciated.

**Comment by paulbiss** [comment]
Timeout options are now well documented here: https://docs.hhvm.com/hhvm/configuration/INI-settings
