### ISSUE TITLE
Request for scrypt (password hash algorithm) PECL extension

### ISSUE THREAD

**Issue by marcoarment** [facebook/hhvm#2369]
Having widespread availability of the [scrypt function](http://pecl.php.net/package/scrypt), a possible successor to bcrypt that's gaining traction and much more resistant to FPGA brute-forcing, would help us build more secure password systems. More info:

* [Is bcrypt better than scrypt?](http://security.stackexchange.com/questions/26245/is-bcrypt-better-than-scrypt)
* [Don't use bcrypt](http://www.unlimitednovelty.com/2012/03/dont-use-bcrypt.html)

There's a pure-PHP implementation that could be used in the extension's absence, but it's about 100 times slower than the native extension when running under normal PHP. While it's better under HHVM, it's even better as a real extension: it's of utmost importance that it be as fast as possible so implementations can set high-needs parameters, since attackers can obviously just use the fastest implementation themselves.

**Comment by joelastpass** [comment]
FYI LastPass has a pull request open on adding an scrypt extension to HHVM: https://github.com/facebook/hhvm/pull/7024

**Comment by Orvid** [comment]
The PR in question has been merged for a while now, and is included in 3.15.
