### ISSUE TITLE
flatMap() / reduce() on collections

### ISSUE THREAD

**Issue by JosephMoniz** [facebook/hhvm#2402]
It was brought up during the hack dev day yesterday that there were more combinators to come to hhvm/hack collections. I just want to +1 the prioritization of either or both flatMap() and reduce() because if you have either one of those you can implement all other functional combinators in terms of them. Thus it probably makes sense to consider releasing them as soon as they become available so developers can start extending collections as soon as possible via composition.

**Comment by paulbiss** [comment]
Might be worth considering something like this for the new hack array standard library, it's unlikely we will be adding new features to collections.
