### ISSUE TITLE
hh_client: provide way to dump list of known classes, constants, functions, and type aliases

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#2406]
Would want information on where they're defined too.

This would make it trivial to build a map to pass to HH\autoload_set_paths

**Comment by Orvid** [comment]
I believe we already have similar functionality in place, if all else the auto-complete system can probably be adapted enough for any use-cases of this.

**Comment by fredemmott** [comment]
Not really, still an open issue, within FB too.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

I believe [hhvm-autoload](https://github.com/hhvm/hhvm-autoload) achieves the goal that you wanted to achieve. `hh_client` does not have a method / api that gives you this list. If this is something that still needs to be built, please reopen this issue.
