### ISSUE TITLE
Support XHP Array Attribute Types

### ISSUE THREAD

**Issue by Swahvay** [facebook/hhvm#2431]
XHP supports array types when defining attributes, such as:

```
attribute array<Foo> arrayOfFooInstances;
attribute array<string => array<int>> mapOfStringsToAnArrayOfInts;
```

The syntax was added in two revisions:
https://github.com/facebook/xhp/commit/14bdf9917ac762217de8bbdeefdc41870e33cbff
https://github.com/facebook/xhp/commit/cd4c1024af99d8141779e4dfbd256c3f35b1d36b

**Comment by simonwelsh** [comment]
I have a feeling that this is done with the HHVM-only version of XHP basically using the same types now as Hack.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Hhvm accepts this type of typehints for xhp attributes.
