### ISSUE TITLE
i added mongo,but it doesn't work

### ISSUE THREAD

**Issue by 4-1-1** [facebook/hhvm#2443]
i add it to the config.hdf file,and restart hhvm, no erroe and no warning
DynamicExtensions {
   mongo = /home/shiyongyong/ext/mongo.so
 }
but the mongo class is still undefined

**Comment by waterone** [comment]
Hi I am using mongo-hhvm-driver it is saying me 
Fatal error: Class undefined: MongoClient 

and also when I am compiling mongofill 


 /root/hhvm/hhvm-mongodb/mongofill-hhvm/src/bson.cpp:3:0:
/usr/local/include/bson.h:64:2: error: #error Must compile with c99 or define MONGO_HAVE_STDINT, MONGO_HAVE_UNISTD, MONGO_USE__INT64, or MONGO_USE_LONG_LONG_INT.
 #error Must compile with c99 or define MONGO_HAVE_STDINT, MONGO_HAVE_UNISTD, MONGO_USE__INT64, or MONGO_USE_LONG_LONG_INT.
  ^


this error
