### ISSUE TITLE
3.X Regression in FastCGI - connection breaks after first request

### ISSUE THREAD

**Issue by banks** [facebook/hhvm#2522]
After spending a day debugging a client app that talks to HHVM directly (that worked with HHVM 2.x) I discovered that HHVM 3.x is not handling FastCGI correctly.

Specifically, the second request sent on a connection is not executed and the socket is closed by the server.

To demonstrate this (and compare same client working as expected with php-fpm) please see. https://github.com/banks/hhvm-bug-demo

Note that this is not apparently an error due to my client code. Firstly the client used to work, it still does with php-fpm.

I have not been able to tell conclusively if nginx is actually masking the issue by reconnecting on the failure to write/read subsequent requests to backend. If this is the case though then that is a significant performance hit caused by this issue.

Hope this helps. If the repo above does not reproduce the issue for you, I will investigate more widely on other systems.

Thanks

**Comment by paulbiss** [comment]
KeepAlive support has been added back and we no longer report that we support multiplexing.
