### ISSUE TITLE
Memleak when define a constant using a dynamic string value

### ISSUE THREAD

**Issue by wwbmmm** [facebook/hhvm#2538]
First we write a script that define a constant using a dynamic string value.

```
$ cat webroot/test.php
<php
define('LOG_ID', (string) mt_rand() ) ;
```

And we request this script for 10000 time, and see the allocated bytes through admin server

```
$ for((i=0;i<10000;i++)); do curl http://localhost:8096/test.php; done
$ curl http://localhost:8196/jemalloc-stats 2>/dev/null | grep allocated
  <allocated>175422376</allocated>
```

Now we request this script for 10000 times again, and see about 480000 new bytes allocated.

```
$ for((i=0;i<10000;i++)); do curl http://localhost:8096/test.php; done
$ curl http://localhost:8196/jemalloc-stats 2>/dev/null | grep allocated
  <allocated>175908312</allocated>
```

If we keep doing this request, memory usage will keep increasing by about 48 byte per request.

The reason is that every time we define a constant using a string value, hhvm try to create a static string :
`f_define`->`Unit::defCns`->`Unit::defCnsHelper`->`Variant::setEvalScalar`->`makeStaticString`
But this value is different for each request, so we need to create a new static string every time. This cause the memory leak.

This issue is the same:https://github.com/facebook/hhvm/issues/707.
But the code below can't reproduce:

``` php
<?php
error_reporting(E_ERROR);
for ($i=0; $i < 100000000; $i++) {
  $str = time().'.'.rand(10000, 99999) ;
  define('LOG_ID', $str ) ;
}
```

Because constant can't be redefined, it will raise a notice other than calling Variant::setEvalScalar

``` cpp
uint64_t Unit::defCnsHelper(uint64_t ch,
                            const TypedValue *value,
                            const StringData *cnsName) {
  TypedValue* cns = &RDS::handleToRef<TypedValue>(ch);
  if (UNLIKELY(cns->m_type != KindOfUninit) ||
      UNLIKELY(cns->m_data.pref != nullptr)) {
    raise_notice(Strings::CONSTANT_ALREADY_DEFINED, cnsName->data()); 
  } else if (UNLIKELY(!tvAsCVarRef(value).isAllowedAsConstantValue())) {
    raise_warning(Strings::CONSTANTS_MUST_BE_SCALAR);
  } else {
    Variant v = tvAsCVarRef(value);
    v.setEvalScalar(); // this cause the memleak
    cns->m_data = v.asTypedValue()->m_data;
    cns->m_type = v.asTypedValue()->m_type;
    return true;
  }
  return false;
}
```

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This issue applies to running php code on hhvm. Hhvm [nolonger supports running php code](https://hhvm.com/blog/2018/09/12/end-of-php-support-future-of-hack.html) since [hhvm version 4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html).

In Hack, the define function is not valid since [hhvm 4.1.0](https://hhvm.com/blog/2019/04/09/hhvm-4.1.0.html).
