### ISSUE TITLE
running composer install with HHVM takes longer than doing it with PHP

### ISSUE THREAD

**Issue by stayeronglass** [facebook/hhvm#2554]
http://blog.servergrove.com/2014/04/17/running-composer-hhvm-fast/

Composer install with PHP:
real 0m2.547s
user 0m1.190s
sys 0m0.919s

Composer install with HHVM:
real 0m4.905s
user 0m3.010s
sys 0m1.337s

Composer install with HHVM and JIT disabled:
real 0m3.062s
user 0m1.604s
sys 0m1.158s

**Comment by paulbiss** [comment]
We have some long term items on the roadmap to help with interpreter performance and smarter CLI performance with the JIT but they aren't high priority as hhvm is mostly tuned to be an efficient server and will likely always have an observable startup cost.
