### ISSUE TITLE
HHVM fastcgi in daemon mode with FileSocket refuses connection after some time

### ISSUE THREAD

**Issue by StrathCole** [facebook/hhvm#2570]
Dear people,
I know, this kind of issue report is not the best, because it is hard to reproduce, but maybe someone might be able to help.

I am running hhvm (3.0.1 from repository) in fastcgi daemon mode on a debian wheezy server with apache 2.2.

The command line to start hhvm is:
```
 /usr/bin/hhvm --mode daemon -vServer.Type=fastcgi --user web4 -vServer.FileSocket=/var/run/hhvm/hhvm.web4.sock -vLog.Level=Debug -vLog.UseLogFile=true -vRepo.Central.Path=/var/run/hhvm/hhvm.web4.hhbc -vLog.File=/var/run/hhvm/hhvm.web4.log -vLog.AlwaysLogUnhandledExceptions=true -vLog.RuntimeErrorReportingLevel=8191 -vPidFile=/var/run/hhvm/hhvm_web4.pid
```

The part of the apache config that matters is:
```
<IfModule mod_fastcgi.c>
	<Directory /var/www/web4/cgi-bin>
		Order allow,deny
		Allow from all
	</Directory>
	<FilesMatch "\.php[345]?$">
		SetHandler php5-fcgi
	</FilesMatch>
	Action php5-fcgi /php5-fcgi
	Alias /php5-fcgi /var/www/web4/cgi-bin/hhvm
	FastCgiExternalServer /var/www/web4/cgi-bin/hhvm -idle-timeout 300 -socket /var/run/hhvm/hhvm.web4.sock -pass-header Authorization
</IfModule>
```

Everything runs fine, web pages are delivered fast.
But after some time (may be one hour, may be one day, different all the time) the delivery stops and apache has lots of errors in log:
```
(111)Connection refused: FastCGI: failed to connect to server "/var/www/web4/cgi-bin/hhvm": connect() failed
```

The hhvm process is still running and there is nothing in the hhvm log, not even a single line. Logfile permissions are set to 777 just to ensure it can be accessed.

**Comment by ankitpr89** [comment]
Getting same on my server too.
Looks there is no fix for now, I am shifting to php5-fpm.

**Comment by ankitpr89** [comment]
Workaround for me:
There were multiple instances of hhvm running. Killed all and then started hhvm again. It worked.

**Comment by mkzero** [comment]
I still have this issue with hhvm 3.5.0(tagged version: tags/HHVM-3.5.0-0-ga90f4733cfa0d8fefdafc7433f758f78cdc75424). 

I get the following error:

`Uncaught exception: 98failed to bind to async server socket: /var/run/hhvm/hhvm.sock: Address already in use`

Despite the fact, that, according to lsof, nothing is using that socket. This really is a buzzkill, as after an update my sites go down until I delete the socket file and restart the daemon..

**Comment by wpreview** [comment]
I had the sock error - what i have done was stop hhvm instances - removed everything in the /var/run/hhvm* folders and restartet all the instances ->worked for me

**Comment by wpreview** [comment]
On every restart of hhvm it fails, this is in the log:

Uncaught exception: 98failed to bind to async server socket: /var/run/hhvm-wpfree/hhvm.sock: Address already in use

What happens is that the hhvm.sock is not deleted, i need to manually delete it and do a hhvm restart to get a new hhvm.sock after that my site is running again.
Here ist the ls -la from hhvm after a restart:

-rw-r--r--  1 wpfree wpfree 35560448 Feb 23 10:30 hhvm.hhbc
srwxrw----  1 wpfree wpfree        0 Feb 23 10:18 hhvm.sock
-rw-r--r--  1 wpfree wpfree        0 Feb 23 10:30 pid

as you can see the hhvm.sock is aged....

AFAIK it should have the permission from the directory it sits in - but that seems to be wrong, at least in my case :)

Would appreciate any help!

**Comment by AlteranAncient** [comment]
I can +1 this issue. After some time of using a file socket, Nginx starts to report "Connection refused" and everyone just starts receiving blank pages until I restart the hhvm service. The service appears to be running still, but Nginx throws a wobbly and all my sites stop working until I manually restart it. No helpful errors on HHVM's part to indicate why this is happening, but if Nginx is the one throwing the "(111) Connection Refused" error on the socket, that implies the request isn't actually making it to HHVM.

Occurs on:
```
HipHop VM 3.9.1 (rel)
Compiler: tags/HHVM-3.9.1-0-g0f72cfc2f0a01fdfeb72fbcfeb247b72998a66db
Repo schema: 6416960c150a4a4726fda74b659105ded8819d9c
```

A solution would be nice, but I can just switch over to using a port if I need to. My FPM fallback uses a file socket, so I can just have HHVM use Port 9000 in the interim.

**Comment by fredemmott** [comment]
@AlteranAncient : can you open a separate issue for HHVM stopping accepting connections for you? It would be useful if when this happens, you could attach gdb, and run 'thread apply all bt' and include the output of that in the issue.

**Comment by fredemmott** [comment]
Actually, the gdb output would be useful in this issue for people that are having HHVM stop accepting connections - it's the comments about needing to delete the socket file that should be separate.

**Comment by royalterra** [comment]
This issue is open from 2014 but today 2016 still I have the seam issue 
Only HHVM use port 9000 but is working anyway 

ar 28 22:52:55 privyemail hhvm[22479]: E0328 22:52:55.791282 22479 fastcgi-server.cpp:105] 98failed to bind to async server socket: [::]:9000: Address already in use
Mar 28 22:52:55 privyemail hhvm: command failed: "lsof -t -i :9000 | xargs kill -9"
Mar 28 22:52:56 privyemail hhvm[22479]: E0328 22:52:56.811738 22479 fastcgi-server.cpp:105] 98failed to bind to async server socket: [::]:9000: Address already in use
Mar 28 22:52:56 privyemail hhvm: command failed: "lsof -t -i :9000 | xargs kill -9"
Mar 28 22:52:57 privyemail hhvm[22479]: E0328 22:52:57.837301 22479 fastcgi-server.cpp:105] 98failed to bind to async server socket: [::]:9000: Address already in use
Mar 28 22:52:57 privyemail hhvm: command failed: "lsof -t -i :9000 | xargs kill -9"
Mar 28 22:52:58 privyemail hhvm[22479]: E0328 22:52:58.862524 22479 fastcgi-server.cpp:105] 98failed to bind to async server socket: [::]:9000: Address already in use
Mar 28 22:52:58 privyemail hhvm: command failed: "lsof -t -i :9000 | xargs kill -9"

**Comment by paulbiss** [comment]
It appears as though we still need additional information to properly investigate this issue. We're closing it per our [Human Timeouts](https://github.com/facebook/hhvm/wiki/Human-Timeouts) policy.
