### ISSUE TITLE
Not showing errors

### ISSUE THREAD

**Issue by natanaelsimoes** [facebook/hhvm#2571]
<?php include('file_not_exists.php'); ?>

It don't show any error at browser, but shows at command-line and log file!

My /etc/hhvm/php.ini is setted like following:
display_errors = yes
track_errors = yes
error_reporting = E_ALL

**Comment by AndyWendt** [comment]
If you stumble upon this, this link may also be helpful: https://github.com/facebook/hhvm/issues/4818
