### ISSUE TITLE
bug when use memcache to set a value by a special key

### ISSUE THREAD

**Issue by wdjwxh** [facebook/hhvm#2572]
I have this strange bug.
hhvm version is tag 3.0.1 .

just this code
```php
<?php
$a = new Memcache();

$value = array('a'=>'1','b'=>'2');
$testkey = '1f';
$key = hex2bin($testkey).'ab';
$a->connect('localhost',11211);
$a->set($key,$value,0, 300);

var_dump($a->get($key));
```

The special key is a string that  contains a binary .
The php 5.4 is ok .
```
[root@byrbt test]# php a.php
array(2) {
  ["a"]=>
  string(1) "1"
  ["b"]=>
  string(1) "2"
}
[root@byrbt test]# 
```

but on hhvm it will output NULL. In other case , it may output the filrst some letters of the write value..  It's very strange..

I have test many strings, it only occurs some special binary. like 'acdae02' and so on.

I fix my code to avoid this question by not use binary key. Bug I still want to figure it out..

**Comment by paulbiss** [comment]
Closing for now as we no longer support 3.0.1, please re-open if you find that you have the same problem with 3.3, 3.5, or master. Thanks!
