### ISSUE TITLE
/var/log/hhvm/error.log does not include timestamps

### ISSUE THREAD

**Issue by jameshfisher** [facebook/hhvm#2589]
Is this intentional? It makes it much harder to track what's going on.

    $ hhvm --version
    HipHop VM 3.0.1 (rel)
    Compiler: tags/HHVM-3.0.1-0-g1da451b79f40686de6472d23cf90fdd09fa4dc23
    Repo schema: 11f0d546efba889ced1f9b92d9c9249f494d0b84

    $ uname -a
    Linux swarm-idp 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Orvid** [comment]
The escaping behavior is expected. And this is fixed.
