### ISSUE TITLE
Hack: XHP classes aren't looked for in the global namespace

### ISSUE THREAD

**Issue by simonwelsh** [facebook/hhvm#2616]
```php
<?hh // strict

namespace a;

function test(): :x:frag {
        return <x:frag />;
}
```

This results in `test.php:5:19,24: Unbound name: a\:x:frag` (and you get a similar error for the `<x:frag />` in the body), even though XHP classes are always looked for in the global namespace.

**Comment by TheRyanHowell** [comment]
Any updates? This basically forces any PSR-4 package to choose between using strict mode and using XHP in a class.

**Comment by fredemmott** [comment]
This is changing, differently: https://github.com/facebook/xhp-lib/issues/64

Closing here as duplicate so we don't track it in two places.
