### ISSUE TITLE
JITed array construction uses memory/time exponential in the size of the array

### ISSUE THREAD

**Issue by radford** [facebook/hhvm#2638]
Running the output of this code in HHVM with and without the JIT shows a huge slowdown and memory increase.

```php
<?php echo "<?php\n"; ?>
function f() {
    $a = dirname('/a/b');
    $c = array(
<? for ($i = 0; $i < 3000; $i++ ) { ?>
        'a<?= $i ?>' => $a . 'b<?= $i ?>',
<? } ?>
       );
}

echo 'Before ' . memory_get_peak_usage() . "\n";
f();
echo 'After ' . memory_get_peak_usage() . "\n";
```
The output of the output of the above shows it takes half a gigabyte of memory and 5 seconds to generate an array with 3000 entries.
```
Before 2097152
After 591396864
```
This leads to Composer sucking up time and memory for no good reason under HHVM.

**Comment by Orvid** [comment]
I don't think this is still an issue. Our performance is roughly the same as the PHP5 version, although interestingly PHP7 manages it in 1/4th of the time.

https://3v4l.org/6e2t0

As a side note, in this particular test case, enabling repo-auth mode would mean `$a` would be constant folded in, and the entire array would be static.

**Comment by edwinsmith** [comment]
@Orvid 1/4 the time of HHVM or PHP5? if hhvm, this could be a possible perf-lockdown task, if we're leaving perf on the table.

**Comment by Orvid** [comment]
PHP7 takes about 1/4th of the time that both HHVM and PHP5 take, at least when running on 3v4l. HHVM and PHP5 both take about 0.8 seconds, PHP7 only takes about 0.2 seconds.
