### ISSUE TITLE
Improve on PHP - different default serialization. (igbinary, messagepack, ...)

### ISSUE THREAD

**Issue by quentin389** [facebook/hhvm#2654]
Hi,
For me HHVM+hack has two major and extremely important types of improvements over PHP:
- It heavily focuses on performance (and delivers).
- It's set to improve the bad sides of PHP programming.

**_TL;DR:_ I propose to depreciate default PHP serialization and stick with two options: JSON and the fastest most compact binary implementation available.**

Because everything has to be converted from PHP to HACK by hand, and it's quite clear to me that Facebook programmers aren't afraid to completely change some basic ways PHP work, it seems to me like it's a perfect opportunity to fix a quite large performance issue caused by the choice of the default serializer.

Perhaps many people don't realize it, but <code>serialize()</code> and <code>unserialize()</code> functions are terribly slow and inefficient. They are so bad, that in every project I start, one of the first things I do is I try to install <code>igbinary</code> extension (which unfortunately is not always an option).

Every test I've done over the years consistently shows that in vast majority of cases when using igbinary as a serializer:
- serialization is much faster than the standard one
- deserialization is much faster than the standard one
- the resulting serialized data size is much much smaller than what standard method provides (eg. I store large PHP objects taken from database in Redis cache. 8 GB RAM can hold 2 million <code>igbinary_serialized</code> items, and only 200k <code>serialized</code>)

The only two drawbacks of using binary serialization, that in my opinion are worth any attention, are:
- you can't read the serialized string, which means that if you, for example, store it in a field in a database, it may be sometimes an issue
- it uses all ASCII codes instead of just "human readable" ones so in certain situations you have to keep that in mind in order not to mess up your data

I've been using igbinary for years, and that's the only thing I can compare the default serializer to, however apparently there are some other promising technologies out there. One of them being <code>MessagePack</code>, which according to https://github.com/nicolasff/phpredis/pull/404 is even better than igbinary (way better? O.o). Focusing on this binary serializer instead of igbinary may be a good idea as igbinary seems to be abandoned (?), and it does have a bad history of segfaulting.

In my opinion, if someone needs a human readable serialization format, there is no reason to provide them with two methods of serialization - native PHP and JSON. They are similar enough to just ditch the PHP way and just use JSON. There are some issues here (e.g. circular references), but I think they can be resolved, considering that <code>json_encode()</code> already has a plethora of options.

In all the other situations we should start using a binary serializer. That is especially important when sending values to memcache and Redis (+any other in-memory caching system). Binary serialization has been implemented for a long time in both those caches. One other good example is using binary serialized strings with REST.
I think, that in case of caching systems, binary serialization should be the default option.

Since HHVM is so performance focused, and it strives to fix many PHP issues, adding binary serialization as a basic serialization system in HHVM should be quite important.

Here are some connected topics, but I didn't want to piggyback to any of them:
https://github.com/facebook/hhvm/issues/1248
https://github.com/facebook/hhvm/issues/685
https://github.com/facebook/hhvm/issues/1620

I may be missing some obvious issues, or perhaps be even completely wrong, but I think the idea presented above is very much worth discussing.

**Comment by xiaoxuz** [comment]
Support hhvm？
