### ISSUE TITLE
Typecheck XHP attributes properly

### ISSUE THREAD

**Issue by jwatzman** [facebook/hhvm#2658]
Hack currently has little/no support for properly checking XHP. It would be really great if we could properly typecheck attribute declarations. Currently, attributes are read/written via `getAttribute('name')` and `setAttribute('name', $val)`. This isn't typeable as-is since the return type of `getAttribute` depends on its name. We have few options here, in order from my preferred to least preferred:

- Move attributes from an array in the XHP superclasses into an `stdClass`; they would then be accessed through `$this->attributes->name`. We'd add a tiny special case to the typechecker to know what all the fields of `$this->attributes` are. Benefit: changes are pretty minor in XHP superclasses (`stdClass` behaves largely like an array), we can keep the old `getAttribute` methods for backwards compat (and to allow FB www to slowly convert as we get things to typecheck properly), IDE autocomplete just falls out. Downside: I don't see much?
- Special-case `getAttribute` etc in the typechecker. If we require a constant string as an argument, we can know the type and do the right thing. Benefit: requires no changes to PHP code anywhere. Downside: IDE autocomplete for attributes will have to be more special case code.
- Move attributes to be protected members directly on the XHP classes. Still need a typechecker special case to convert the `attribute` declaration into members. Benefit: really nice client API -- `$this->attributeName`. Downside: probably impossible to cleanly convert since XHP classes might use attributes with conflicting names, similarly impossible to cleanly enumerate for something like `transferAttributes`.

It will probably be a few weeks at the earliest before I can get around to any of this, but just wanted to have the issue open for discussion to make sure the approach was good.

**Comment by simonwelsh** [comment]
I think this is done with `$this->:attribute` support

**Comment by fredemmott** [comment]
Sort of - we might want to make -> work as an value too for setAttribute

--
Typed with my thumbs

On Aug 21, 2015, at 20:34, Simon Welsh <notifications@github.com<mailto:notifications@github.com>> wrote:


I think this is done with $this->:attribute support

**Comment by fredemmott** [comment]
Closing, ->: as an assignment operator sohuld really be a separate issu.e
