### ISSUE TITLE
hhvm.log.level ignored

### ISSUE THREAD

**Issue by MarkGavalda** [facebook/hhvm#2675]
Trying to focus on Errors only, but when setting hhvm.log.level = Error (or hhvm.log.level = error) it's just ignored.
Latest nightly on Ubuntu 14.04.  `hhvm-nightly (2014.05.14~trusty)`

**Comment by MarkGavalda** [comment]
@ptarjan  Unfortunately I could never get this to work. No matter what I set and where HHVM always logs notices and warnings too. :-/

**Comment by ronilaukkarinen** [comment]
I also have this issue... my error logs are gigantic sometimes if there's too many warnings and notices. I only need errors. What to do?

**Comment by creativeprogramming** [comment]
i've to use ramfs for logging to avoid disk burning due to tons of notices due to this issue

**Comment by Orvid** [comment]
Actually, could you file a separate issue for this? The base issue from this should already have been solved.
