### ISSUE TITLE
Document Apache 2.2 + mod_fcgid

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#2689]
We have documentation for Apache 2.2 + mod_fastcgi, however that's not included in Debian stable - as mod_fcgid is, we should document it.

**Comment by Orvid** [comment]
Is this still needed?

**Comment by paulbiss** [comment]
If someone wants to send us a documentation PR to update [this page](https://docs.hhvm.com/hhvm/advanced-usage/fastCGI) I'd be happy to take it. As we now offer proxygen as an alternative and our docs describe fastcgi as an advanced configuration I'm going to close this.
