### ISSUE TITLE
404 File Not Found on Apache 2.4.7, Ubuntu 14.04, FastCGI

### ISSUE THREAD

**Issue by indikatordesign** [facebook/hhvm#2692]
Hello,

I use hhvm on Ubuntu 14.04 and on Apache 2.4.7. I configured everything like you´re described for the use with FastCGI on virtual host, but if I try to open the "domain/index.php" in Browser, I get: 404 File Not Found.

If I try it with "domain/index.html", all works fine, that means that the vhost must set right.

If I go in console to the public folder where the index.php is included and insert "hhvm index.php" the output is "HipHop", cause in the file I use phpinfo(). That means HHVM works fine.

I used the Prebuilt for 14.04.

After install-routine I used: "/usr/share/hhvm/install_fastcgi.sh" and "/etc/init.d/hhvm restart"

Type: "hhvm --version" results in:
HipHop VM 3.0.1 (rel)
Compiler: tags/HHVM-3.0.1-0-g1da451b79f40686de6472d23cf90fdd09fa4dc23
Repo schema: 11f0d546efba889ced1f9b92d9c9249f494d0b84

I also used: "a2enmod proxy_fcgi" to enable Module proxy and Module proxy_fcgi.

This is my config for virtual host:

---

virtualhost *:80>

        # Admin email, Server Name (domain name) and any aliases

        ServerAdmin admin@domain.de
        ServerName domain.de
        ServerAlias www.domain.de

        # Index file and Document Root (where the public files are located)

        DirectoryIndex index.php index.html
        DocumentRoot /var/www/vhosts/domain/public_html

        # Custom log file locations

        LogLevel debug
        #LogLevel warn

        ErrorLog /var/www/vhosts/domain/logs/errors.log
        CustomLog /var/www/vhosts/domain/logs/access.log combined

```
ProxyPassMatch ^/(.*\.php(/.*)?)$ fcgi://127.0.0.1:9000/var/www/vhosts/domain/public_html/$1

    <Directory /var/www/vhosts/domain/public_html>
            Options Indexes FollowSymLinks MultiViews
            AllowOverride FileInfo  All
            Order allow,deny
            Allow from all
            Require all granted
    </Directory>
```

/virtualhost>

---

/etc/hosts/
127.0.0.1       domain.de

---

/etc/hhvm/server.ini: hhvm.server.default_document = index.php

---

Here is our: netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:\*               LISTEN      808/sshd
tcp        0      0 127.0.0.1:3306          0.0.0.0:\*               LISTEN      951/mysqld
tcp6       0      0 :::22                   :::\*                    LISTEN      808/sshd
tcp6       0      0 :::9000                 :::\*                    LISTEN      1939/hhvm
tcp6       0      0 :::80                   :::\*                    LISTEN      1906/apache2

---

Here is our: ls -ld /var/www/vhosts/domain
drwxrwxr-x 4 root developers 4096 May 16 07:57 /var/www/vhosts/domain

---

Here is our: getent group developers
developers:x:1001:me,root,www-data

---

This is an entry in our error log: [Thu May 15 21:51:48.005072 2014] [proxy:debug] [pid 1429] proxy_util.c(1690): AH00924: worker fcgi://127.0.0.1:9000/var/www/$1 s$

---

Any idea how to fix it?

Any reference to do anything else important for the use with WordPress?

Best regards

**Comment by grep-awesome** [comment]
I am experiencing this issue as well

**Comment by dbu** [comment]
same here. i tried to set up a ProxyPass to something else than /var/www and it gets overwritten by `/etc/apache2/mods-enabled/hhvm_proxy_fcgi.conf` - not sure what created that file and why, but it seems pretty stupid to me. would be nice to fix that to make life easier when setting up hhvm...

**Comment by SoundAxis** [comment]
I was having this issue, but changing fcgi://127.0.0.1:900/var/www/$1 to fcgi://127.0.0.1:900/var/www/html/$1 in /etc/apache2/mods-enabled/hhvm_proxy_fcgi.conf fixed the issues for me.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Hhvm doesn't ship with built-in webserver configuration anymore. Setting it up, just like one would for php, works fine just fine. For any remaining server questions, please open a new issue.
