### ISSUE TITLE
Default socket name for local MySQL connects

### ISSUE THREAD

**Issue by oneinstack** [facebook/hhvm#2700]
default socket name for local MySQL connects: /var/lib/mysql/mysql.sock
I want to set :/tmp/mysql.sock , Can you help me ?

**Comment by frijsdijk** [comment]
Even if I set hhvm.mysql.socket=/var/run/mysqld/mysqld.sock in hhvm.ini, which shows up in a hhvm-phpinfo, it still seems to look for /tmp/mysql.sock in stead.

Btw, this works as well as a quick work-around (but dirty):

ln -s /var/run/mysqld/mysqld.sock  /tmp/mysql.sock
