### ISSUE TITLE
Uploaded file get invalid permission

### ISSUE THREAD

**Issue by lscgzwd** [facebook/hhvm#2707]
HHVM run command:
```
/usr/bin/hhvm --config /etc/hhvm/10daitou.ini --user 10daitou --mode daemon -vPidFile=/var/run/hhvm/10daitou/pid

user 10daitou with group www-data
```
when we upload a file, file get permission with group root owner , not user 10daitou's group www-data. 
eg:
`-rw-------  1 10daitou root     122547 May 19 23:57 537a29e69bdee.jpg`

I think this is not work fine. the files uploaded should with owned by the user's group. Not the root.

I have try to add param --group www-data to start-stop-daemon, It dose not work.
```
hhvm version:
HipHop VM 3.1.0-dev+2014.05.12 (rel)
Compiler: heads/master-0-g9512a32186775cbe3d3867d0797772d6885bd1b4
Repo schema: 91d45a89ef73e711a368c9e5631a164e4c2f348e
```

**Comment by paulbiss** [comment]
Still no repro and no new reports since 2014. Since it's still unclear how this was ever happening I'm going to close the issue. If anyone is still experiencing this issue, or better still, has an isolated repro, please comment below.
