### ISSUE TITLE
Segfault on concurrent request on ZF1

### ISSUE THREAD

**Issue by chielsen** [facebook/hhvm#2721]
Hey there,

I have searched a lot but cannot find a solution to my problem.
When i run my ZF1 app with ab and some concurrent request (4 is enough) i get a segfault.

DBG says this:

`Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffa9fff700 (LWP 8622)]
0x00007ffff57fc1af in free () from /usr/lib/x86_64-linux-gnu/libjemalloc.so.1
traps: hhvm[8504] general protection ip:7fc1186d31af sp:7fc0adb75590 error:0`

Kernel log:

`traps: hhvm[8504] general protection ip:7fc1186d31af sp:7fc0adb75590 error:0
May 21 18:35:37 hhvm kernel: [250233.508087] traps: hhvm[8492] general protection ip:7fc1186d31af sp:7fc0ef775590 error:0 in libjemalloc.so.1[7fc1186cf000+30000]
May 21 18:35:37 hhvm kernel: [250233.525381]  in libjemalloc.so.1[7fc1186cf000+30000]
May 21 18:35:37 hhvm kernel: [250233.539244] hhvm[8517]: segfault at 200 ip 00007fc113be6621 sp 00007fc070373768 error 6 in libc-2.19.so[7fc113b59000+1bc000]`

Unfortunately i dont have any more stacktraces.

This on nightly-dbg. I have the same problems on stable / dbg or non dbg.

**Comment by haringsrob** [comment]
I'm also having this issue, error's a little different:

Jul  5 21:15:30 tripthusiast kernel: [794102.865676] traps: hhvm[29931] general protection ip:13930ef sp:7fc1a07f90a0 error:0 in hhvm[400000+37b5000]

Happens once a day, not really a pattern, happend around 16h00 some days, yesterday around 21h00

**Comment by vikash-itspe** [comment]
hhvm[2599]: segfault at ffffffffffffffff ip 00005641d675093d sp 00007ffdda65f220 error 7 in hhvm[5641d59aa000+3cce000]
Jan 16 14:44:30 ip-172-31-13-103 kernel: [ 5389.330045] Code: 00 00 f0 48 0f c1 1d aa ad 2c 03 48 81 fb ff ff ff 1f 77 7d e8 b4 fc ff ff 48 89 da 48 8b 4d 80 48 c1 e2 04 48 01 d0 8b 55 88 <48> 89 08 89 50 08 48 8b 55 b0 89 d8 89 5a 20 e9 7c ff ff ff e8 fa


Error : hhvm -m daemon -d hhvm.server.type=proxygen -d hhvm.server.port=8080 -vEval.SyncGdbChunks=1 vServer.AllowRunAsRoot=1 -d hhvm.log.file=/var/log/hhvm/error.log
Segmentation fault (core dumped)

Please suggest any solution
