### ISSUE TITLE
hh_client fails to identify function object field

### ISSUE THREAD

**Issue by homerhsing** [facebook/hhvm#2730]
<?hh
class C {
  public function __construct(private $ppfunc) {
    ($this->ppfunc)(1);    // $this->ppfunc is an function object. call $this->ppfunc
  }
}

$ppfunc = function($arg) {
  echo "Hello $arg\n";
};

new C($ppfunc); // pass function object into constructor

Above code can be successfully executed in HHVM. But hh_client fails to identify "$this->ppfunc", it says "The method ppfunc is undefined in an object of type C".

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

The [blogpost of hhvm 4.10](https://hhvm.com/blog/2019/06/18/hhvm-4.10.0.html) mentions the fix for this issue:
_Callable properties can now be invoked by parenthesizing, e.g. ($foo->bar)()._
