### ISSUE TITLE
Support disable_functions

### ISSUE THREAD

**Issue by deamwork** [facebook/hhvm#2745]
By using hhvm, how to disable dangerous PHP function, or when will support to disable the following PHP functions?
Dangerous functions that suggest to be non-functional: dl,exec,popen,system,phpinfo,passthru,shell_exec,proc_open,proc_close,show_source,escapeshellarg,escapeshellcmd
Not disabled these function by default may be cause hhvm dangerous even will lead to hacking.

**Comment by creativeprogramming** [comment]
Please don't forget this issue.

**Comment by paulbiss** [comment]
We could intercept [registerBuiltinFunction(...)](https://github.com/facebook/hhvm/blob/463bf994adc41f5e89950641de61a1cf81e97d48/hphp/runtime/vm/native.h#L437) and inject a function pointer to a stub that fails the call [like](https://github.com/php/php-src/blob/fcc6f2df5986bb9615a658cc717b1a92922462d2/main/main.c#L176-L209) [zend](https://github.com/php/php-src/blob/3d04b5c2881095b11296fdef37878d60c0704426/Zend/zend_API.c#L2769). We can do this in the same way that we [handle unimplemented functions](https://github.com/facebook/hhvm/blob/master/hphp/runtime/vm/native.cpp#L501-L505).

**Comment by Andi-K** [comment]
Can someone explain why this got closed without a commend? It's not fixed.

At least the HHVM Docs should point out that this PHP security feature won't be supported by HHVM.
