### ISSUE TITLE
setcookie inconsistency

### ISSUE THREAD

**Issue by schien-dong** [facebook/hhvm#2758]
Just found out that the path is not the issue. When a cookie is set twice, the second set is ignored:

```
setcookie('cookiename','value1');
setcookie('cookiename','value2');
```

The cookie will read as value1 in subsequent page load. In Zend PHP, there's an implicit header output buffer for cookies, so even output buffer is not used, the second cookie value should still overwrite the first one.
@JoelMarcey could this be related to Issue #2526 ?

**Comment by jeroenvermeulen** [comment]
Thanks @danslo, the ini setting
`hhvm.server.allow_duplicate_cookies = 0` 
solved a problem with Magento customer login for us.
