### ISSUE TITLE
Eval.PerfPidMap = false Not stopping Perf files

### ISSUE THREAD

**Issue by wwallace** [facebook/hhvm#2761]
setting hhvm.Eval.PerfPidMap to false is not stopping perf-*.map files from being written to /tmp. This could be user error, I may not be setting this correctly. Maybe there should be documentation about this config, as disk space fills up pretty quickly when running artisan commands on a 1 minute cron. The artisan commands aren't failing either, so i'm not sure why the garbage collection is failing.

**Comment by bvidinli** [comment]
I am living similar situation.
No map file generated, but map file routines are run in hhvm, so it comsumes much cpu
using hhvm 3.8
trying to solve this.

**Comment by JoelMarcey** [comment]
@bvidinli Are you setting `hhvm.eval.perf_pid_map = true` in your ini file?

**Comment by RalphCorderoy** [comment]
HHVM's php(1) creates zero-length /tmp/perf-*.map.
It doesn't seem to pay attention to any settings mentioned here.

    $ hhvm --version
    HipHop VM 3.9.1 (rel)
    Compiler: tags/HHVM-3.9.1-0-g0f72cfc2f0a01fdfeb72fbcfeb247b72998a66db
    Repo schema: 6416960c150a4a4726fda74b659105ded8819d9c
    $ ls -l /tmp/perf-*.map
    ls: cannot access /tmp/perf-*.map: No such file or directory
    $ php -l /dev/null
    $ ls -l /tmp/perf-*.map
    -rw-rw-r-- 1 ralph ralph 0 Oct  9 11:48 /tmp/perf-376.map
    $

**Comment by pratham2003** [comment]
Still have this problem in HipHop VM 3.18.3 (rel)

**Comment by heyrex** [comment]
I confirm this issue has returned on 3.20.2

**Comment by RAIMUNDOS54** [comment]
Yes. Very annoying. hhvm.eval.perf_pid_map = false doesn't work and new perf files are being created like crazy.

**Comment by heyrex** [comment]
Specifying the option via the command line seems to work but the option
name is different. See the related issues for a workaround in some
situations.
