### ISSUE TITLE
3.1.0 release tarball has empty third_party directory

### ISSUE THREAD

**Issue by SjonHortensius** [facebook/hhvm#2806]
In the 3.0.1 release this directory contained the actual content of this submodule; but it's an empty directory in 3.1.0.tar.gz

**Comment by devurandom** [comment]
For 3.5.0 the third-party download link is: https://github.com/hhvm/hhvm-third-party/archive/d0cad57b5427f84af8f77d60b8b53de4aaea4694.tar.gz
For other versions choose the commit accordingly.

@javer, @reanimus, @kristapsk: That way you do not need to use Git in the ebuilds.
