### ISSUE TITLE
Ubuntu 14.04 libcurl.so.4

### ISSUE THREAD

**Issue by trK54Ylmz** [facebook/hhvm#2845]
I installed hhvm on repository. When I try to start hhvm, its says libcurl has errors. 

``` shell
sudo service hhvm start
```

or

```
hhvm --mode server -vServer.Type=fastcgi -vServer.Port=9000
```

and result is :

```
/usr/bin/hhvm: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/hhvm)
```

**Comment by mzaslavsky** [comment]
Without any more information, my guess would be that a "packaged" curl library has been installed somewhere else previously (the error message seems unrelated at first but this error is quite common) and this version was installed in the default path. If you find another copy of libcurl.so.4 somewhere (e.g. most likely /usr/lib) you can try uninstalling from your locally compiled source (e.g. probably in /usr/local/src/curl or if you followed, for example, Ubuntu 12.04 build directions from Facebook - /usr/local/src/hhvm-dev/curl).

The following command should work:
sudo make uninstall

(If you've accidentally already run "make clean" on your source directory you can re-install and try the above command again).
