### ISSUE TITLE
The stdlib HHI files should be properly typed

### ISSUE THREAD

**Issue by Aatch** [facebook/hhvm#2849]
In order to inform Hack about the standard library, there are a number of `.hhi` files distributed as "interface" files. The ones for standard Hack stuff (collections etc.) are fine, but the regular PHP library files are completely without type information. This can cause errors or, worse, mask potential bugs.

**Comment by paulbiss** [comment]
We're taking PRs for these but it's not something we're likely to go through and do systematically right now.
