### ISSUE TITLE
Options for JitASize, JitAStubsSize and JitGlobalDataSize won't apply

### ISSUE THREAD

**Issue by peanut-lord** [facebook/hhvm#2851]
Hello Folks,

while running a script in the terminal, which does some heavy work, I got following error:

```
Assertion failure: 0
data block = prof
message: Attempted to emit 1 byte(s) into a 67108864 byte DataBlock with 0 bytes available. This almost certainly means the TC is full. If this is the case, increasing Eval.JitASize, Eval.JitAStubsSize and Eval.JitGlobalDataSize in the configuration file when running this script or application should fix this problem.


/tmp/tmp.OjiPDtAJbS/hphp/runtime/vm/jit/mc-generator.cpp:2049: HPHP::JIT::Translator::TranslateResult HPHP::JIT::MCGenerator::translateTracelet(HPHP::JIT::Tracelet&): assertion `0' failed.

Notice: Array to string conversion
terminate called after throwing an instance of 'HPHP::Exception'
  what():  unexpected N4HPHP13DataBlockFullE: Attempted to emit 1 byte(s) into a 67108864 byte DataBlock with 0 bytes available. This almost certainly means the TC is full. If this is the case, increasing Eval.JitASize, Eval.JitAStubsSize and Eval.JitGlobalDataSize in the configuration file when running this script or application should fix this problem.

Aborted (core dumped)
```

I added the ini options as described here: https://github.com/facebook/hhvm/wiki/INI%20Settings, but it won't change anything:

```ini
; Site for the jit
hhvm.jit_asize =  536870912 ; 512M
hhvm.jit_astubs_size = 536870912 ; 512M
hhvm.jit_global_data_size = 536870912 ; 512M
```

After that, I changed the /etc/hhvm/defaults and added those lines:

ADDITIONAL_ARGS="vEval.JitASize=536870912 -vEval.JitAStubsSize=536870912 -vEval.JitGlobalDataSize=536870912"

Still no change, same error, so I tried one last thing. I wrote a config.hdf file with this content:

```
Eval {
	Jit = true
	JitASize = 536870912
	JitAStubsSize = 536870912
	JitGlobalDataSize = 536870912
}
```

But still, no change, same error. Perhaps this is no bug and I am missing something - does anyone have an idea? Thank you!

**Comment by lbadger** [comment]
Any update on this? I'm still getting these error at least 3-4 times a week. I've even updated to 
```
HipHop VM 3.4.2 (rel)
Compiler: tags/HHVM-3.4.2-0-g40d85d7386b3342ab848fc45c6892433c89ef5b2
Repo schema: 13cba877c4300d1d0481b3f40eb128a5115d4e08
Extension API: 20140829
```
Error in log
```
[Wed Jan 14 12:35:18 2015] [hphp] [3977:7f25023ff700:3095:000001] [] \nFatal error: unexpected N4HPHP13DataBlockFullE: Attempted to emit 13 byte(s) into a 25165824 byte DataBlock with 5 bytes available. This almost certainly means the TC is full. If this is the case, increasing Eval.JitASize, Eval.JitAColdSize, Eval.JitAFrozenSize and Eval.JitGlobalDataSize in the configuration file when running this script or application should fix this problem.
```

Here is my server.ini config
```
pid = /var/run/hhvm/pid
hhvm.eval.jit = true
hhvm.server.port = 9000
hhvm.server.type = fastcgi
hhvm.server.default_document = index.php
hhvm.log.header = true
hhvm.log.use_log_file = true
hhvm.log.file = /var/log/hhvm/error.log
hhvm.repo.central.path = /var/run/hhvm/hhvm.hhbc
hhvm.jit_asize = 1073741824
hhvm.jit_astubs_size = 1073741824
hhvm.jit_global_data_size = 1073741824
hhvm.jit_acold_size = 1073741824
hhvm.jit_afrozen_size = 1073741824
hhvm.log.level = Warning
hhvm.log.always_log_unhandled_exceptions = true
hhvm.log.no_silencer = true
hhvm.log.injectedstacktrace = true
hhvm.log.nativestacktrace = true
hhvm.log.MaxMessagesPerRequest = -1
```

**Comment by simonwelsh** [comment]
@lbadger the settings now use `hhvm.jit_a_` as the prefix

**Comment by frijsdijk** [comment]
Is there a way to limit the TC from filling up? Or do we have to keep giving hhvm more memory untill it stops filling?

**Comment by paulbiss** [comment]
Currently the only solution is to find a set of sizes that are appropriate for your project. We're actively working on a better solution.

**Comment by yustein** [comment]
In my situation the service does not stop, there is no core dump after this error, the server just returns a white screen.

Any ideas?
Tony

**Comment by MarkGavalda** [comment]
@yustein that is unfortunately the worst case scenario, it does happen from time to time to us as well. Couldn't figure out a way to make HHVM "properly crash" in these cases, manual intervention is needed...

**Comment by yustein** [comment]
@MarkGavalda  Ok, I will do a simple health check then. Do you have any suggestions for that? Monit seems to be erratic, it also couldn't see HHVM properly.

**Comment by JoelMarcey** [comment]
I am closing this issue because the options are applying, are documented on the wiki (I will be working on a big doc overhaul in H2), and the other ancillary problems are being worked on but are not necessarily directly related to the issue of these options not applying.
