### ISSUE TITLE
command line arguments don't accept hex values

### ISSUE THREAD

**Issue by rrh** [facebook/hhvm#2863]
This invocation:
  hhvm --xhprof-flags 0x200
Results in this error message:
  Error in command line: the argument ('0x200') for option '--flags' is invalid

It seems unreasonable that the argument scanner doesn't accept hex radix numbers following the lexical conventions of C.  In this case, the flags are a bit mask, and appear in the hhvm source code in hex radix.

**Comment by paulbiss** [comment]
This feature request is not actively being worked on. We would happily consider a pull request implementing it. If you plan to work on this issue let us know in the comments and we will re-open the issue and assign it to you. If you feel strongly that this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
