### ISSUE TITLE
Fatal error: unexpected N4HPHP13DataBlockFullE

### ISSUE THREAD

**Issue by MarkGavalda** [facebook/hhvm#2870]
Latest nightly isn't segfaulting (as it used to) anymore but becomes non-working until it's restarted. I have tried all kinds of variations of these parameters, currently using the following in server.ini:

``` ini
hhvm.jit_a_size = 201326592
hhvm.jit_astubs_size = 201326592
hhvm.jit_global_data_size = 201326592
hhvm.jit_acold_size = 201326592
hhvm.jit_afrozen_size = 201326592
```

No matter what I do, it keeps running into this same issue for us.
We're hosting WordPress based sites only!

Same happens on all kinds of machines, with 2GB RAM to 32GB.

Please let me know what else do I need to post to get this resolved I'll be happy to test and debug and whatnot. :)

`\nFatal error: unexpected N4HPHP13DataBlockFullE: Attempted to emit 1 byte(s) into a 62914560 byte DataBlock with 18446744073709551607 bytes available. This almost certainly means the TC is full. If this is the case, increasing Eval.JitASize, Eval.JitAColdSize, Eval.JitAFrozenSize and Eval.JitGlobalDataSize in the configuration file when running this script or application should fix this problem.`

**Comment by frijsdijk** [comment]
Question: is there no way to limit this TC filling, or can something be flushed/purged to prevent it from filling up? It either hangs or crashes.. and periodicaly restarting it to prevent this sounds lame.

**Comment by jazzdan** [comment]
@frijsdijk it's my understanding that there is no way to flush or purge the translation cache short of restarting the server like you described. I believe it is this way because, if you run in Repo Authoritative mode as Facebook does, you need to restart your server on code deploy anyways.

**Comment by danslo** [comment]
There was some earlier discussion about this [here](https://www.facebook.com/groups/hhvm.dev/permalink/247749128747527/).

**Comment by paulbiss** [comment]
It's something we are actively working, it's definitely become a major pain-point.

**Comment by doringheorghe** [comment]
I really hope the issue will be resolved soon. I have the same problem on a production site. Everytime HHVM goes down because of this.

**Comment by paulbiss** [comment]
@doringheorghe: It's currently my highest priority, but it may be awhile before we have something that's production ready for this.

**Comment by doringheorghe** [comment]
I know. I used EasyEngine with HHVM and PHP5-FPM as a backup. I recommend php5-fpm as a backup anytime before HHVM is 100% stable.

**Comment by frijsdijk** [comment]
You can tune hhvm for this, it will cope alot better then. Of periodicaly restart hhvm. It's ugly I know, but you don't have to wait for it to crash.

**Comment by doringheorghe** [comment]
@frijsdijk what do you mean? can you please explain ?

**Comment by fredemmott** [comment]
also, it's worth checking your backtrace - if it includes f_create_function() , you might be able to solve your problems by replacing:

```PHP
$foo = create_function('bar()');
```

with:

```PHP
$foo = function() { bar(); }
```

(we have leak issues with the first one as it technicaly creates a globally accesible function, whereas the latter doesn't)

**Comment by frijsdijk** [comment]
@doringheorghe increase the sizes of the various parameters, like the coredump file suggest. I've ended up quadroupling the values from default (Ubuntu 14.04):

hhvm.jit_a_size=251658240
hhvm.jit_a_cold_size=100663296
hhvm.jit_a_frozen_size=167772160
hhvm.jit_a_prof_size=268435456
hhvm.jit_a_max_usage=251658240
hhvm.jit_global_data_size=62914560
