### ISSUE TITLE
hhvm runtime options wiki page needs updates

### ISSUE THREAD

**Issue by prognew** [facebook/hhvm#2880]
I followed what described in https://github.com/facebook/hhvm/wiki/runtime-options#sandbox-environment, but I can't cause hphpd to break on requests to my sandbox. Since we've replaced hdf with ini file, I've also changed server.ini to something like below. 

hhvm.Sandbox.SandboxMode = true
hhvm.Sandbox.Pattern = sb-sb.example.com
hhvm.Sandbox.Home = '/home'
hhvm.Sandbox.ConfFile = '.hphp'

hhvm.Eval.Debugger.EnableDebugger = true
hhvm.Eval.Debugger.EnableDebuggerServer = true
hhvm.Eval.Debugger.Port = 8089

**Comment by Orvid** [comment]
New documentation has this.
