### ISSUE TITLE
Reduce inter-extension dependencies

### ISSUE THREAD

**Issue by simonwelsh** [facebook/hhvm#2884]
This is another generic wish-list type issue akin to the HNI conversion.

Currently, there's a rather large amount of dependencies between the different extensions. I made a graph of them: ([PDF](http://assets.simon.geek.nz/HHVM/extension-deps.pdf) | [OmniGraffle](http://assets.simon.geek.nz/HHVM/extension-deps.graffle)) (`a --> b` means `a` includes at least one header file related to `b`)

To help allow making more extensions optional (which is what my next task after finishing HNI will be), it'll be good to reduce the amount of connections between extensions.

**Comment by Orvid** [comment]
The vast majority of them are optional now.
