### ISSUE TITLE
Logging stops after fatal error

### ISSUE THREAD

**Issue by csvan** [facebook/hhvm#2891]
Version: 3.1, running behind Apache 2.4 on Ubuntu 14.04

Scenario:
With log level set to Verbose, tailing the hhvm error log shows normal, verbose logging, until a fatal error is encountered ("Fatal error: class X not found in Y"). After this, even though hhvm continues to respond to requests normally, no info at all is written to the log.

**Comment by pokrface** [comment]
Confirming that I am having the same issue, also with Roundcube (though since this issue has been filed, Roundcube has been updated to 1.1.0). The last thing I see in hhvm's error.log is:

```
\nFatal error: Class undefined: html in /var/www-roundcube/program/lib/Roundcube/rcube_plugin_api.php on line 566
```
Roundcube fails to load, and no further messages are written to the hhvm log file.

Running `strace -p <pid>` for hhvm's pid shows this:

```
futex(0x7fa2a7047654, FUTEX_WAIT_PRIVATE, 1, NULL
```
...and that's it.

This is with Ubuntu 12.04, Nginx 1.7.0 (from the mainline repo branch), and hhvm 3.5.1:
```
HipHop VM 3.5.1 (rel)
Compiler: tags/HHVM-3.5.1-0-gb723e67c88bc008676687a04dff00db1faf250b3
Repo schema: a395edf8708632a3d09f417dbd9b1bd1d5b50bbe
```

**Comment by pokrface** [comment]
Not sure if this is even remotely helpful, but the code section in `rcube_plugin_api.php' that's causing it to barf looks like this:
```
    /**
     * Include a plugin script file in the current HTML page
     *
     * @param string $fn Path to script
     */
    public function include_script($fn)
    {
        if (is_object($this->output) && $this->output->type == 'html') {
            $src = $this->resource_url($fn);
            $this->output->add_header(html::tag('script',
                array('type' => "text/javascript", 'src' => $src)));
        }
    }
```

**Comment by pokrface** [comment]
Error still present in 3.6, same behavior.

**Comment by dhpowrhost** [comment]
Having the same issue on Debian, except for the fact that it does not only encounter on a fatal error - hhvm just stops loggin randomly after 3-7 minutes aprox.

**Comment by Orvid** [comment]
This issue has been waiting for more info for more than 2 weeks. Closing for now, feel free to re-open it if you can provide more info.

https://github.com/facebook/hhvm/wiki/Human-Timeouts
