### ISSUE TITLE
Moodle unit test fails under HHVM

### ISSUE THREAD

**Issue by csvan** [facebook/hhvm#2949]
**Environment:**
- Ubuntu 14.04
- Moodle 2.6 stable
- HHVM 3.1 (from repo)
- PHP 5.5.6

**Scenario:**
Run Moodle tests with PHP and HHVM.

**Expected:**
All unit tests passed by PHP should also be passed by HHVM.

**Actual:**
Test case causes fatal error under HHVM, but not PHP:

"Fatal error: An iterator cannot be used with foreach by reference in /***/lib/navigationlib.php on line 879"

The test case in question is here:
https://github.com/moodle/moodle/blob/MOODLE_26_STABLE/lib/tests/navigationlib_test.php#L144

The snippet causing the exception is here:
https://github.com/moodle/moodle/blob/MOODLE_26_STABLE/lib/navigationlib.php#L869

**Steps to replicate:**
1. Check out: https://github.com/moodle/moodle/tree/MOODLE_26_STABLE
2. Set up test environment (http://docs.moodle.org/dev/PHPUnit)
3. run vendor/bin/phpunit --debug core_navigationlib_testcase lib/tests/navigationlib_test.php

**Comment by shimondoodkin** [comment]
https://gist.github.com/shimondoodkin/5a3ae5b32f63553385f5
