### ISSUE TITLE
hhvm laravel memory leak

### ISSUE THREAD

**Issue by xterm-inator** [facebook/hhvm#2973]
After installing base laravel package then running Apache benchmark the memory usage of hhvm will continue to rise till 100% of the systems memory is used.  The system is running nginx 1.4.1, hhvm 3.1.0, laravel 4.1.30 on ubuntu 13.10.

**Comment by farizluqman** [comment]
Hello, I can confirm the problem still exists on the current Laravel release especially when it involves Laravel's Eloquent model. Will update to reproduce the problem

**Comment by jidebingchuan** [comment]
Any news? we use lumen framework, after about 2hours will restart by memory increase to limit which defined by hhvm.hdf.

**Comment by velegip** [comment]
No news. Laravel and lumen announces. They not support hhvm.
