### ISSUE TITLE
SimpleXMLElement::asXML differs from Zend for empty elements

### ISSUE THREAD

**Issue by HRMsimon** [facebook/hhvm#2983]
```php
<?php

$a = new SimpleXMLElement("<a/>");
$a->addChild('b');
var_dump($a->asXML());
```

Expected (Zend) output:
```
string(34) "<?xml version="1.0"?>
<a><b/></a>
"
```

Actual output:
```
string(37) "<?xml version="1.0"?>
<a><b></b></a>
"
```

The `<b>` is self-closing under Zend but not HHVM. This only seems to happen with nodes added dynamically. If passed as part of the string used during construction, the outputs both have the self-closing tag.

// @danslo

**Comment by Orvid** [comment]
This works on the current version of HHVM. https://3v4l.org/BAnGT
