### ISSUE TITLE
Hack support for auto_prepend_file/auto_append_file

### ISSUE THREAD

**Issue by gabelevi** [facebook/hhvm#2990]
https://github.com/facebook/hhvm/pull/2171 added support for a feature that automatically prepends or appends a file to every PHP file. Tony Wuersch from Wayfair mentioned that there may be some strange interactions of this hhvm feature with Hack.

At the moment, Hack doesn't really consider how files are loaded. Hack assumes everything is in scope. Therefore as long as the file you're autoprepending is in the same repository, it should be seen by Hack. So this should basically just work. I'll reach out to Tony to get an example of what might be going wrong.

**Comment by fredemmott** [comment]
-t analyze is unsupported/removed, and was separate to hack - I don't think there's still an issue here. If you think there is, please could you clarify?

**Comment by awuersch** [comment]
no, I don't think there is anymore.
