### ISSUE TITLE
No such file or directory during ./build.sh

### ISSUE THREAD

**Issue by szop85** [facebook/hhvm#3014]
Hello guys,

guess this question won't take much of your time, but took very lot of mine. I've downloaded the latest HipHop VM 3.2.0-dev (rel)
Compiler: heads/master-0-g3b5e28c1f1f9562c8c7313b5ad1fc4d46c5d190f and it's running fine.

Now I've tried to compile the mongo-hhvm-driver from https://github.com/10gen-labs/mongo-hhvm-driver but receiving errors like "No such file or directory" after running the mongodb-hhbm-driver ./build.sh script:

```
make[2]: *** [CMakeFiles/mongo.dir/src/ext_mongo.cpp.o] Error 1
make[2]: *** [CMakeFiles/mongo.dir/src/MongoClient.cpp.o] Error 1
In file included from /root/hhvmsrc/hhvm/third-party/folly/src/folly/Format.h:418:0,
                 from /root/hhvmsrc/hhvm/hphp/runtime/base/datatype.h:24,
                 from /root/hhvmsrc/hhvm/hphp/runtime/base/types.h:35,
                 from /root/hhvmsrc/hhvm/hphp/runtime/base/zend-functions.h:21,
                 from /root/hhvmsrc/hhvm/hphp/runtime/base/hphp-system.h:27,
                 from /root/hhvmsrc/hhvm/hphp/runtime/base/base-includes.h:24,
                 from /root/hhvmsrc/mongo-hhvm-driver/src/mongo_common.h:4,
                 from /root/hhvmsrc/mongo-hhvm-driver/src/ext_mongo.h:4,
                 from /root/hhvmsrc/mongo-hhvm-driver/src/MongoCursor.cpp:2:
/root/hhvmsrc/hhvm/third-party/folly/src/folly/Format-inl.h:21:29: fatal error: folly/Exception.h: No such file or directory
 #include "folly/Exception.h"
```

It seem's like the paths are relative and that's why it's failing. I could edit alle .h files, but this would drive me nuts. My current folder structure looks like this:

```
/root/
-- hhvmsrc
     |-- hhvm
     |-- mongo-c-driver
     |-- mongo-hhvm-driver
```

Is there a way to tell the ./build.sh script to look in a different directory for all .h a required files? Currently my /root/hhvmsrc/hhvm/third-party/folly/src/folly/Format-inl.h looks like this:

```
#include "folly/Exception.h"
#include "folly/Traits.h"
```

Guess this is some kind of basic stuff, hope you can help me out or point me in a direction.

Thanks a lot,
Cheers

**Comment by Orvid** [comment]
This was an issue with mongodb. Closing.
