### ISSUE TITLE
Func::isBuiltin() is not returning true for all SystemLib functions

### ISSUE THREAD

**Issue by kmiller68** [facebook/hhvm#3043]
I noticed that the Func::isBuiltin() function is returning false for ArrayObject::setIteratorClass(). According to the documentation in func.h isBuiltin() should return true for all the SystemLib functions. I attempted to debug this and found that in emitter.cpp the buildMethodAttrs() function does set the AttrBuiltin attribute for setIteratorClass but this gets unset later. I was unable to find the point where it is getting unset however.

**Comment by Orvid** [comment]
Is this still the case?

**Comment by paulbiss** [comment]
Unclear, but I don't think I found anything the last time I investigated it.
