### ISSUE TITLE
SqlPriorityQueue PHP5 Compatibility Issue (infinite recursion)

### ISSUE THREAD

**Issue by jvanharn** [facebook/hhvm#3099]
The HHVM implementation of **SqlPriorityQueue** is broken and/or breaks compatibility with PHP5 by containing a reference to itself via the *heap* (**_SplPriorityQueueHeap**)->*priorityQueue* property.
When using var_export or other methods that recursively enumerate object properties this results in either a Fatal Error (In the case of var_export) or in infinite loops (in badly written code). I have attached a testcase that demonstrates this behaviour.

The following outputs are for the conflicting platforms:
**PHP5** (5.5.9-1ubuntu4.2):
```php
SplPriorityQueue::__set_state(array())
```

**HHVM** (HHVM-3.1.0-0 g71ecbd8fb5e94b2a008387a2b5e9a8df5c6f5c7b)
```
Fatal error: Nesting level too deep - recursive dependency? in /***/testcase.php on line 4
```

Attached testcase.php:
```php
<?php
$testQueue = new SplPriorityQueue();
$result = var_export($testQueue, true); // this fatals due to the self-reference
echo $result;
```

**Comment by SiebelsTim** [comment]
Looks like this is resolved in 3.8.1
