### ISSUE TITLE
\nFatal error: unexpected St13runtime_error: locale::facet::_S_create_c_locale name not valid

### ISSUE THREAD

**Issue by Snake231088** [facebook/hhvm#3112]
If i have a simple index.php with only phpinfo() all works fine, but if i use for example laravel or phpmyadmin i have this error in hhvm.log
Any help??

**Comment by allan-simon** [comment]
just for people who might see this ticket (it appears when you google the error message)

using the `export LC_ALL=C`  worked for me

**Comment by quydo** [comment]
thanks all, I fixed this problem :D
