### ISSUE TITLE
jemalloc lock and crash problem

### ISSUE THREAD

**Issue by huzhiguang** [facebook/hhvm#3122]
hi,I have 2 jemalloc problem in hhvm. 
First problem is jemalloc crash in hhvm.
Second problem is jemalloc hang(lock) in hhvm.

we use jemalloc version is 3.4.0,  we want to update jemalloc version(3.6.0) to slove this problem.
Beacause we can't stable emersion this two questions, so I want to know whether you encountered such a problem.

first problem crash stack:

	# 0  HPHP::bt_handler(int) at crash-reporter.cpp:0
	# 1  __restore_rt at sigaction.c:0
	# 2  HPHP::JIT::FixupMap::fixup(HPHP::ExecutionContext*) const at bin/hhvm_bin:0
	# 3  HPHP::JIT::MCGenerator::syncWork() at bin/hhvm_bin:0
	# 4  HPHP::ExecutionContext::debugBacktrace(bool, bool, bool, HPHP::VMParserFrame*, bool, int) at bin/hhvm_bin:0
	# 5  HPHP::debug_string_backtrace(bool, bool, int) at bin/hhvm_bin:0
	# 6  HPHP::bt_handler(int) at crash-reporter.cpp:0
	# 7  __restore_rt at sigaction.c:0
	# 8  arena_dalloc_bin_locked at :0
	# 9  tcache_bin_flush_small at :0
	# 10 tcache_event_hard at :0
	# 11 malloc at /home/../lib/libjemalloc.so.1:0
	# 12 mbfl_convert_filter_new at bin/hhvm_bin:0
	# 13 mbfl_buffer_converter_new at bin/hhvm_bin:0
	# 14 HPHP::php_mb_convert_encoding(char const*, unsigned long, char const*, char const*, unsigned int*) at ext_mb.cpp:0
	# 15 HPHP::f_mb_convert_encoding(HPHP::String const&, HPHP::String const&, HPHP::Variant const&) at bin/hhvm_bin:0

second problem hang stack (gdb attach)

	#0  0x00007f53eb551e14 in __lll_lock_wait ()
	   from /home/lib/libpthread.so.0
	#1  0x00007f53eb54d6b7 in _L_lock_535 ()
	   from /home/lib/libpthread.so.0
	#2  0x00007f53eb54d4e0 in pthread_mutex_lock ()
	   from /home/lib/libpthread.so.0
	#3  0x00007f53ed43c30f in arena_dalloc_large ()
	   from /home/lib/libjemalloc.so.1
	#4  0x00000000009dc42c in HPHP::MemoryManager::resetAllocator() ()
	#5  0x0000000000a11ed7 in HPHP::/home() ()
	#6  0x0000000000ea02b5 in HPHP::HttpRequestHandler::handleRequest(HPHP::Transport*) ()
	#7  0x0000000000e6bb45 in HPHP::ServerWorker<std::shared_ptr<HPHP::LibEventJob>, HPHP::LibEventTransportTraits>::doJob
	Impl(std::shared_ptr<HPHP::LibEventJob>, bool) ()
	#8  0x0000000000e6bd98 in HPHP::ServerWorker<std::shared_ptr<HPHP::LibEventJob>, HPHP::LibEventTransportTraits>::doJob
	(std::shared_ptr<HPHP::LibEventJob>) ()
	#9  0x0000000000e6aac8 in HPHP::JobQueueWorker<std::shared_ptr<HPHP::LibEventJob>, HPHP::Server*, true, false, HPHP::J
	obQueueDropVMStack>::start() ()
	#10 0x000000000153b527 in HPHP::AsyncFuncImpl::ThreadFunc(void*) ()
	#11 0x00007f53eb54b1c1 in start_thread ()
	   from /home/lib/libpthread.so.0
	#12 0x00007f53eaa610ad in clone ()

Thanks.

**Comment by Orvid** [comment]
This issue has been waiting for more info for more than 2 weeks. Closing for now, feel free to re-open it if you can provide more info.

https://github.com/facebook/hhvm/wiki/Human-Timeouts
