### ISSUE TITLE
How to profile the PHP code in HHVM?

### ISSUE THREAD

**Issue by lokeshhctm** [facebook/hhvm#3123]
is there a way to identify the time and CPU spent in anywhere in PHP in HHVM?
Actually we are working on some optimization. Out current system whcih does in memory processing and and we are not able to go beyond 200 QPS on 8 Core machine. but our expectation was that it should support around 500 QPS. is there a way to to profile the code in production and see withing current time to execution, how much time we are spending where?

**Comment by paulbiss** [comment]
Xenon is probably your best bet here. You may also be able to build your own sampling profiler on top of the IntervalTimer extension.
