### ISSUE TITLE
runtime option to limit the size of incoming request queue size

### ISSUE THREAD

**Issue by lokeshhctm** [facebook/hhvm#3165]
Is there any runtime option to limit the maximum size of "queued" requests to hhvm? i mean is there any throttling feature which can be sued to discard the request if queue is full.

**Comment by fadimko** [comment]
up

**Comment by bakks** [comment]
Bump on this. Having a really deep request queue means that a latency issue with a small portion of requests to our HHVM proxygen server can cause a lasting backup that affects latency across all requests. Even with the `hhvm.server.thread_job_lifo_switch_threshold` option, really quick/easy requests get stuck in the queue.

From what I can tell, the request queue is distinct from the connection queue, which you can manipulate with the `hhvm.server.backlog` variable.

We have a preference in our infrastructure of failing requests immediately when there's a major upstream issue, and so we would prefer a shorter request queue. It seems like there's a missing config value here. Is there any way now to enforce a shorter request queue? Am I understanding the issue correctly?

**Comment by paulbiss** [comment]
I would look at `hhvm.server.thread_job_max_queuing_milli_seconds` it won't let you adjust the queue size but it will let you timeout requests that have spent too long in the queue, which should achieve the desired effect of preventing a large backlog. Even with this setting using `hhvm.server.thread_job_lifo_switch_threshold` is probably also a good idea.

https://docs.hhvm.com/hhvm/configuration/INI-settings#server-mode
