### ISSUE TITLE
Eval.EnableZendZorting/hhvm.enable_zend_zorting needed for some magento extensions

### ISSUE THREAD

**Issue by juliorosier** [facebook/hhvm#3202]
Magento website breaks with this module turned on.
In app/etc/modules there are a couple of TBT*.xml files that belong to the module

We found out that if we turn of TBT_RewardsOnly.xml. the problem is fixed.
But off course that is not a beautiful option.

Also there is a calculation issue when updating product amount  in shopping cart
from lets say 1 to 3 the subtotal stays at the price of 1 piece.

Using Rubic_FixTotalSorting. does not fix this problem

thanks

**Comment by rossmc** [comment]
@danslo I tried adding both `hhvm.EnableZendSorting = 1` and `-vEval.EnableZendSorting=1` to both my */etc/hhvm/php.ini* file or */etc/hhvm/server.ini* file.  

Neither worked but your Rubic_FixTotalSorting module did.  I would prefer to use the recommened EnableZendSorting solution, am I implementing it correctly?

**Comment by danslo** [comment]
@rossmc In ini files it should be ``hhvm.enable_zend_sorting = 1``. Also don't forget to restart HHVM and clear mage to cachrs as it caches sort orders.

**Comment by rossmc** [comment]
@danslo,thanks I'll try that tomorrow.  Should it be in both ini files? /etc/hhvm/php.ini file and /etc/hhvm/server.ini file

**Comment by danslo** [comment]
Either should be fine. Php.ini is used for both the server and command line.

**Comment by rossmc** [comment]
@danslo `hhvm.enable_zend_sorting = 1` fixed the issue I had with magento adding up tax totals correctly but I'm still having an issue with the sorting of currency rates.  
http://magento.stackexchange.com/questions/76727/hhvm-is-breaking-display-in-manage-currency-rates

**Comment by danslo** [comment]
Separate issue for sure, if I had to guess it probably has something to do with [this](https://github.com/facebook/hhvm/blob/4498e2b25bc17ace502b4c86c551dbab25f284bf/hphp/doc/inconsistencies#L15) inconsistency. Can't exactly say I have a lot of time to investigate this issue though. It would help if someone could narrow it down to a couple lines of PHP (outside of Magento).

**Comment by danslo** [comment]
I also cannot reproduce this on the latest nightly, so please provide exact instructions.

**Comment by rossmc** [comment]
@danslo I created a [new issue](https://github.com/facebook/hhvm/issues/5862) for this, can you check if I should have enough details provided in it? I tired too add as much as I could think of.
