### ISSUE TITLE
Problems compiling 3.2 branch on Ubuntu stack

### ISSUE THREAD

**Issue by mmucklo** [facebook/hhvm#3255]
I get an error with double conversion.

```
[ 24%] Building CXX object hphp/tools/bootstrap/CMakeFiles/gen-class-map.dir/gen-class-map.cpp.o
[ 24%] Building CXX object hphp/tools/bootstrap/CMakeFiles/gen-class-map.dir/idl.cpp.o
Linking CXX executable gen-class-map
[91mCMakeFiles/[0m[91mgen-class-map.dir/gen-class-map.cpp.o: In function `std::enable_if<std::is_floating_point<double>::value, double>::type folly::to<double>(folly::Range<char const*>*[0m[91m)':
```

```
cmake -D CMAKE_PREFIX_PATH=/usr/local -D DOUBLE_CONVERSION_INCLUDE_DIR="/usr/local/include/double-conversion" -D DOUBLE_CONVERSION_LIBRARY="/usr/local/lib/libdouble-conversion.a" -D FREETYPE_INCLUDE_DIRS="/usr/include/freetype2" -D LIBDWARF_LIBRARIES="/usr/local/lib/libdwarf.a" -D LIBDWARF_INCLUDE_DIRS="/usr/local/include/dwarf" .
```

Double conversion is compiled like this:
```
double-conversion-1.1.5 && cmake . && make install
```

master branch compiles fine with the same config as of c380b4972e48b708cd2844c7af501e0638ce0914

Ubuntu 14.10 (via a docker container on CentOS 6.4)

(see https://github.com/oodle/docker-hhvm-build - BTW to reproduce the problem, check out commit https://github.com/oodle/docker-hhvm-build/commit/fbccb0e103dfea5642357e7e21cfedeb6bcd51ce)

**Comment by jrobeson** [comment]
can you reproduce this with any newer version of HHVM? I don't think 3.2 is supported anymore.

**Comment by mmucklo** [comment]
I've switched over to CentOS 7 and had no more troubles with compiling as of 3.4 or later.  Closing this out...
