### ISSUE TITLE
hhvm uptime discovery

### ISSUE THREAD

**Issue by ck-on** [facebook/hhvm#3306]
This is a wishlist feature request.

I was looking at `REQUEST_START_TIME` in `$_SERVER` and was wondering if HHVM uptime could be provided there as well.

Or if that is wasteful on every request, perhaps via some kind of api function query.

**Comment by paulbiss** [comment]
This feature request is not actively being worked on. We would happily consider a pull request implementing it. If you plan to work on this issue let us know in the comments and we will re-open the issue and assign it to you. If you feel strongly that this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.

**Comment by paulbiss** [comment]
Actually it looks like `server_process_start_time()` is being added in internal diff D3628152
