### ISSUE TITLE
nginx - upstream prematurely closed connection while reading response header from upstream

### ISSUE THREAD

**Issue by craigcarnell** [facebook/hhvm#3308]
Could they be timing out? Is there a way to set the timeout of a PHP request?

What is the difference between:

hhvm.server.request_timeout_seconds
max_execution_time
hhvm.server.connection_timeout_seconds? 

How does this relate to fastcgi_read_timeout 900s; for example?

What does 0 mean? Unlimited? What does -1 mean?

I can set these to 120 for example in my php.ini/server.ini, but by default they are 0 over fastcgi?

In https://github.com/facebook/hhvm/blob/9832a93f9ccb58b244d6140ea2e2444b454f7df2/hphp/runtime/server/fastcgi/fastcgi-server.cpp#L215 it says the default for connectionTimeoutSeconds should be 120 but it doesn't seem to be applied here.

```
 ["hhvm.server.request_timeout_seconds"]=>
  array(3) {
    ["global_value"]=>
    string(1) "0"
    ["local_value"]=>
    string(1) "0"
    ["access"]=>
    int(4)
  }

["max_execution_time"]=>
  array(3) {
    ["global_value"]=>
    string(1) "0"
    ["local_value"]=>
    string(1) "0"
    ["access"]=>
    int(7)
  }

  ["maximum_execution_time"]=>
  array(3) {
    ["global_value"]=>
    string(1) "0"
    ["local_value"]=>
    string(1) "0"
    ["access"]=>
    int(7)
  }

["hhvm.server.connection_timeout_seconds"]=>
  array(3) {
    ["global_value"]=>
    string(2) "-1"
    ["local_value"]=>
    string(2) "-1"
    ["access"]=>
    int(4)
  }
```

Also, I've noticed ini_get_settings is missing several settings such as http://php.net/manual/en/mysql.configuration.php#ini.mysql.connect-timeout

It also says in the docs this should be in seconds, but in the source it is Milli-seconds?

https://github.com/facebook/hhvm/blob/2bcb8e08e05051b7db52b551c42706154a1f30ac/hphp/runtime/ext/mysql/ext_mysql.h#L77

**Comment by craigcarnell** [comment]
Still getting this issue? 

``
upstream prematurely closed connection
```

10000 thread_count

**Comment by 1pulse** [comment]
I'd the same problem, because hhvm couldn't read my configuration, so it take the defaults.

/usr/bin/hhvm --config /etc/hhvm/php.ini --config /etc/hhvm/server.ini --user www-data --mode daemon -vPidFile=/var/run/hhvm/pid
syntax error, unexpected $end, expecting TC_DOLLAR_CURLY or TC_QUOTED_STRING or '"' in /etc/hhvm/server.ini on line 79\n

Just commented any line and works great:
; hhvm.log.access.*.format = %h %l %u % t \"%r\" %>s %b
