### ISSUE TITLE
hhvm does not remove .pid and .sock files despite clean exit

### ISSUE THREAD

**Issue by ck-on** [facebook/hhvm#3327]
Since hhvm creates the pid and sock files itself, it should be responsible for cleaning them up after exiting or restarting?

That is not the behavior I am seeing with HHVM 3.2, they are left over instead and `systemd` will warn when restarting. The files are owned by the same user hhvm is running as, obviously since it created them.

I had to add this to the service file to stop the warnings but it is a messy workaround.

```
ExecStopPost=/bin/rm -f  /var/run/hhvm/hhvm.pid  /var/run/hhvm/hhvm.sock
```

Unless maybe systemd is sending the wrong signal to hhvm to stop it but I doubt that?

**Comment by jkoudys** [comment]
I can't click into the referenced commit -- should this be merged in with 3.5.0? I'm still seeing it there (clean `service hhvm stop` and my /var/run/hhvm/hhvm.sock is still there, preventing restart from working as it won't overwrite the existing socket)
