### ISSUE TITLE
Memcache::cas doesn't convert timeout string to int

### ISSUE THREAD

**Issue by jmarrama** [facebook/hhvm#3332]
A minor parity bug, but a parity bug nonetheless.

``` php
$m = new Memcached();
var_dump($m->cas(3.14159, "foo", "bar", "1"));
/*
devVM:~/scratch/cas_exp_str]$ php t.php
bool(false)
devVM:~/scratch/cas_exp_str]$ hhvm t.php

Fatal error: Argument 4 passed to Memcached::cas() must be an instance of int, string given in /home/jmarrama/scratch/cas_exp_str/t.php on line 4
 */
```

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

The failure mode of built-in functions which are called with a wrong type changed in [hhvm 4.3 ](https://hhvm.com/blog/2019/04/30/hhvm-4.3.0.html)to always throwing a TypeError.
This matches user defined functions in Hack. It is not possible to get the php behavior of argument type coercion in Hack.
