### ISSUE TITLE
Invalid chunk size "" unable to read chunked body

### ISSUE THREAD

**Issue by matthewalanwilliams** [facebook/hhvm#3339]
Got an issue that i have residing in a plugin for magento. Seems to be an issue with HHVM and the zend framework. Plugin is searchanise and in magento when i select connect store to searchanise it loops round and the log prints:

2014-08-01T09:41:47+00:00 DEBUG (7): Searchanise # Error: Invalid chunk size "" unable to read chunked body

I think the issue maybe with  Zend_Http_Client function

**Comment by craigcarnell** [comment]
Any updates on this one? We have run into this issue

**Comment by fcorriga** [comment]
I've used curl instead of zend_http_client wherever possible, but still have some magento modules that use the http_client (searchanise is one of them) and it seems i can't find a solution unless this gets fixed.

**Comment by fcorriga** [comment]
Forcing http 1.0 seems to "fix" the problem.

**Comment by mqudsi** [comment]
FWIW, XenForo also similarly breaks when it uses zend_http_client to make remote requests:

	#0 /var/www/neosmart.net/forums/library/Zend/Http/Client.php(989): Zend_Http_Client_Adapter_Socket->read()
	#1 /var/www/neosmart.net/forums/library/XenForo/ControllerPublic/Register.php(1041): Zend_Http_Client->request()
	#2 /var/www/neosmart.net/forums/library/XenForo/FrontController.php(347): XenForo_ControllerPublic_Register->actionGoogle()
	#3 /var/www/neosmart.net/forums/library/XenForo/FrontController.php(134): XenForo_FrontController->dispatch()
	#4 /var/www/neosmart.net/forums/index.php(13): XenForo_FrontController->run()
	#5 {main}

**Comment by binnykumar** [comment]
Hi All,

I was facing same problem, when i tried to login via google connect.

But i have modified littile code in zend magento library, now i am not facing this issue.

Path : lib/zend/Http/Client/Adapter/Socket.php
Find function read() and change it to

public function read()
    {
            $response = '';
    $gotStatus = false;
    while ($line = @fgets($this->socket)) {
        $gotStatus = $gotStatus || strpos($line, 'HTTP') !== false;
        if ($gotStatus) {
            $response .= $line;
            if (!chop($line)) {
                break;
            }
        }
    }
    // Handle 100 and 101 responses internally by restarting the read again
    if (Zend_Http_Response::extractCode($response) == 100 || Zend_Http_Response::extractCode($response) == 101) {
        return $this->read();
    }
    // If this was a HEAD request, return after reading the header (no need to read body)
    if ($this->method == Zend_Http_Client::HEAD) {
        return $response;
    }
    // Check headers to see what kind of connection / transfer encoding we have
    $headers = Zend_Http_Response::extractHeaders($response);
    // if the connection is set to close, just read until socket closes
    if (isset($headers['connection']) && $headers['connection'] == 'close') {
        while ($buff = @fread($this->socket, 8192)) {
            $response .= $buff;
        }
        $this->close();
        // Else, if we got a transfer-encoding header (chunked body)
    } elseif (isset($headers['transfer-encoding'])) {
        if ($headers['transfer-encoding'] == 'chunked') {
            do {
                $chunk = '';
                $line = @fgets($this->socket);
                $chunk .= $line;
                $hexchunksize = ltrim(chop($line), '0');
                $hexchunksize = strlen($hexchunksize) ? strtolower($hexchunksize) : 0;
                $chunksize = hexdec(chop($line));
                if (dechex($chunksize) != $hexchunksize) {
                    @fclose($this->socket);
                    require_once 'Zend/Http/Client/Adapter/Exception.php';
                    throw new Zend_Http_Client_Adapter_Exception('Invalid chunk size "' . $hexchunksize . '" unable to read chunked body');
                }
                $left_to_read = $chunksize;
                while ($left_to_read > 0) {
                    $line = @fread($this->socket, $left_to_read);
                    $chunk .= $line;
                    $left_to_read -= strlen($line);
                }
                $chunk .= @fgets($this->socket);
                $response .= $chunk;
            } while ($chunksize > 0);
        } else {
            throw new Zend_Http_Client_Adapter_Exception('Cannot handle "' . $headers['transfer-encoding'] . '" transfer encoding');
        }
        // Else, if we got the content-length header, read this number of bytes
    } elseif (isset($headers['content-length'])) {
        $left_to_read = $headers['content-length'];
        $chunk = '';
        while ($left_to_read > 0) {
            $chunk = @fread($this->socket, $left_to_read);
            $left_to_read -= strlen($chunk);
            $response .= $chunk;
        }
        // Fallback: just read the response (should not happen)
    } else {
        while ($buff = @fread($this->socket, 8192)) {
            $response .= $buff;
        }
        $this->close();
    }
    return $response;
}

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This issue applies to running php code on hhvm. Hhvm [nolonger supports running php code](https://hhvm.com/blog/2018/09/12/end-of-php-support-future-of-hack.html) since [hhvm version 4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html).
