### ISSUE TITLE
Security Feature: PCRE Eval should be configurable

### ISSUE THREAD

**Issue by filex** [facebook/hhvm#3341]
In the PCRE regex replace functions the modifier `e` may be used to `eval()` code. The modifier is deprecated for a while, but it still works. In HHVM the `eval` modifier works, too. (Unless `RepoAuthoritive` mode is active).

From on operator's point of view, I would love to have a `php.ini` option like 
```
pcre.eval = 0
```
to disable this attack vector. All code that requires this kind of feature may be changed to `pcre_replace_callback()`, which does the same while leaving the developer in control, whereas now every `pcre_replace()` has to be protected by the developer - which is cumbersome.

Code:
```php
echo preg_replace('/./e', '12+34', 'x');
```

Expected result _with `pcre.eval=0` in `php.ini`_:
```
12+34
```

Actual result with HHVM:
```
46
```

**Comment by paulbiss** [comment]
This feature request is not actively being worked on. We would happily consider a pull request implementing it. If you plan to work on this issue let us know in the comments and we will re-open the issue and assign it to you. If you feel strongly that this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
