### ISSUE TITLE
caution: hhvm.log.level = verbose, will cause 20% performance hit

### ISSUE THREAD

**Issue by ck-on** [facebook/hhvm#3346]
This isn't actually a bug, just needs to be added to the documentation eventually.

Don't set ` hhvm.log.level = verbose` on a live server as it will cause a 20% performance hit.

Took me awhile to figure out and remember that I had left that setting in place.

All other logging levels, including `info` do not appear to add any performance penalty.

**Comment by creativeprogramming** [comment]
it's the disk write bottleneck not an issue
