### ISSUE TITLE
HHVM 3.2 on Centos 6.5

### ISSUE THREAD

**Issue by Firebrand** [facebook/hhvm#3360]
Hello. From what I've seen online there's a lot of people who wish there was an easy pre-built way to install HHVM 3.2 on Centos 6.5. Thanks

**Comment by NotApplicableBeech** [comment]
@sandeepone  ill be honest, we have given up, its a mess the installation of HHVM on Centos 6.6 (which has WHM/CPanel-Nginx) with no documentation. 

So we have set up a AWS EC2 with Ubunu -nginx and HHVM but now hitting a stone wall as no one seems to know how to migrate a site (6gig) and set it up live on the new server (configured and operational) so if you know of anywhere we can hire someone to do this please get in touch

**Comment by sandeepone** [comment]
@NotApplicableBeech Please contact me [SANDEEPONE at GMAIL dot COM]

**Comment by southerncomputer** [comment]
where did yum.gleez.com go?

**Comment by sandeepone** [comment]
It’s up and running now. Ever since we moved to docker we didn’t get chance to look at the yum repo. While migrating to another server, our engineer thought absolute and didn’t put up the Yum server. 


Sandeep Sangamreddi
Founder & Director
Gleez Technologies P Ltd
