### ISSUE TITLE
Incorrect precedence in closure with colliding argument and used variable name.

### ISSUE THREAD

**Issue by TimeToogo** [facebook/hhvm#3406]
Zend uses the used variable instead of the argument whereas HHVM does not.
This is demonstrated here:
http://3v4l.org/V4LSE

**Comment by aorenste** [comment]
Note that php7 doesn't allow the names to collide:
Fatal error: Cannot use lexical variable $foo as a parameter name in /in/V4LSE on line 3

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

PHP 7 and hhvm agree that this is an error.
