### ISSUE TITLE
make crash at 24%

### ISSUE THREAD

**Issue by zh-daniel-huang** [facebook/hhvm#3418]
On Amazon Linux
I followed https://github.com/facebook/hhvm/wiki/Building-and-installing-HHVM-on-Amazon-Linux-2014.03

$ make
...
Scanning dependencies of target hphp_thrift
[ 23%] Building CXX object third-party/thrift/CMakeFiles/hphp_thrift.dir/lib/cpp/concurrency/PosixThreadFactory.cpp.o
[ 23%] Building CXX object third-party/thrift/CMakeFiles/hphp_thrift.dir/lib/cpp/concurrency/Util.cpp.o
[ 23%] Building CXX object third-party/thrift/CMakeFiles/hphp_thrift.dir/lib/cpp/concurrency/TimerManager.cpp.o
[ 23%] Building CXX object third-party/thrift/CMakeFiles/hphp_thrift.dir/lib/cpp/concurrency/Monitor.cpp.o
[ 23%] Building CXX object third-party/thrift/CMakeFiles/hphp_thrift.dir/lib/cpp/concurrency/Mutex.cpp.o
[ 23%] Building CXX object third-party/thrift/CMakeFiles/hphp_thrift.dir/lib/cpp/concurrency/ThreadManager.cpp.o
[ 23%] Building CXX object third-party/thrift/CMakeFiles/hphp_thrift.dir/lib/cpp/transport/TSocketAddress.cpp.o
[ 24%] Building CXX object third-party/thrift/CMakeFiles/hphp_thrift.dir/lib/cpp/transport/TFDTransport.cpp.o
[ 24%] Building CXX object third-party/thrift/CMakeFiles/hphp_thrift.dir/lib/cpp/transport/TSocketPool.cpp.o
[ 24%] Building CXX object third-party/thrift/CMakeFiles/hphp_thrift.dir/lib/cpp/transport/TServerSocket.cpp.o
[ 24%] Building CXX object third-party/thrift/CMakeFiles/hphp_thrift.dir/lib/cpp/transport/TTransportException.cpp.o
[ 24%] Building CXX object third-party/thrift/CMakeFiles/hphp_thrift.dir/lib/cpp/transport/TSocket.cpp.o
[ 24%] Building CXX object third-party/thrift/CMakeFiles/hphp_thrift.dir/lib/cpp/ShutdownSocketSet.cpp.o
[ 24%] Building CXX object third-party/thrift/CMakeFiles/hphp_thrift.dir/lib/cpp/util/FdUtils.cpp.o
[ 24%] Building CXX object third-party/thrift/CMakeFiles/hphp_thrift.dir/lib/cpp/Thrift.cpp.o
[ 24%] Building CXX object third-party/thrift/CMakeFiles/hphp_thrift.dir/lib/cpp/async/TEventHandler.cpp.o
[ 24%] Building CXX object third-party/thrift/CMakeFiles/hphp_thrift.dir/lib/cpp/async/Request.cpp.o
[ 24%] Building CXX object third-party/thrift/CMakeFiles/hphp_thrift.dir/lib/cpp/async/TEventBaseManager.cpp.o
[ 24%] Building CXX object third-party/thrift/CMakeFiles/hphp_thrift.dir/lib/cpp/async/TAsyncTimeoutSet.cpp.o
[ 24%] Building CXX object third-party/thrift/CMakeFiles/hphp_thrift.dir/lib/cpp/async/TAsyncSignalHandler.cpp.o
[ 24%] Building CXX object third-party/thrift/CMakeFiles/hphp_thrift.dir/lib/cpp/async/TEventBase.cpp.o
/home/ec2-user/hhvm/third-party/thrift/lib/cpp/async/TEventBase.cpp: In member function ‘void apache::thrift::async::TEventBase::terminateLoopSoon()’:
/home/ec2-user/hhvm/third-party/thrift/lib/cpp/async/TEventBase.cpp:311:28: error: ‘event_base_loopbreak’ was not declared in this scope
   event_base_loopbreak(evb_);
                                               ^
make[2]: *** [third-party/thrift/CMakeFiles/hphp_thrift.dir/lib/cpp/async/TEventBase.cpp.o] Error 1
make[1]: *** [third-party/thrift/CMakeFiles/hphp_thrift.dir/all] Error 2
make: *** [all] Error 2

**Comment by SiebelsTim** [comment]
I think this can be closed. If anyone gets a similar error, a new issue will suffice.
