### ISSUE TITLE
Commit composer.lock files for all tested frameworks

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#3446]
- Possibly store as hphp/test/frameworks/framework_class_overrides/FRAMEWORK_NAME.lock
- Framework runner should refuse to run if there's no .lock file for this framework

Open questions:
- when does this get updated? Maybe on --record? This means --record will have to clean and re-run composer, rather than just running and re-recording the tests. This will slow people down who are workign on framework compatibility

cc @GrahamCampbell, @JoelMarcey

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Hhvm nolonger publishes framework compatibility, since hhvm cannot run php code since [hhvm 4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html).
