### ISSUE TITLE
Getting 404 File Not Found on Apache 2.4, FastCGI and Ubuntu 14.04

### ISSUE THREAD

**Issue by Zeokat** [facebook/hhvm#3472]
My first step was install HHVM following this guide: https://github.com/facebook/hhvm/wiki/Prebuilt-packages-on-Ubuntu-14.04

Then i run the script with the command: ´sudo /usr/share/hhvm/install_fastcgi.sh´

Then i test if hhvm was installed with command ´php -v´ and the output is OK, says that HIPHOP VM is runing.

The problem arrives when i try to access to a PHP file, Apache always return 404 error. In the other hand html files and static files works good. I only receive 404 error with php files.

I search on Google and found many people with same issue but no solutions. Perhaps someone can help.

**Comment by spamtrawler** [comment]
As the issue still persists for fresh installations on Ubunty 14.04 (x64), here is what worked for us when testing HHVM.

As removing "/etc/apache2/mods-enabled/hhvm_proxy_fcgi.conf" from the system will result in PHP scripts not being served by HHVM, it is not a solution for the issue at hand.

Instead we had to do the following:
1. Login to your server via SSH
2. sudo nano /etc/apache2/mods-enabled/hhvm_proxy_fcgi.conf
3. Find: 
   `ProxyPassMatch ^/(.+\.(hh|php)(/.*)?)$ fcgi://127.0.0.1:9000/var/www//$1`
   Replace with:
   `ProxyPassMatch ^/(.+\.(hh|php)(/.*)?)$ fcgi://127.0.0.1:9000/var/www/html/$1`
4. Save the file (CTRL+X, y)
5. Restart Apache (service apache2 restart)

Hope this is of any help :-)

**Comment by patrickfabrizius** [comment]
@spamtrawler, it seems to me that hhvm_proxy_fcgi.conf sets a global proxypass. This might work on a single-site installation, but adding "html/" only makes that global proxy look in another directory - it still blocks any vhost config. Removing the file and setting ProxyPass directives locally (vhost conf) made it work for me. 

I'm sure there is a more clean solution, but I havn't found it ...

**Comment by fatbattk** [comment]
So I had the exact same problem, tried all the suggestions here, but for some reason it still 404'd.

Thanks to #hhvm chat, I tried `hhvm.server.fix_path_info = false` and oddly, that worked for me (I do use *mod_rewrite*).
So if you're stuck too, give it a shot!

> HipHop VM 3.7.0 (rel)
Compiler: tags/HHVM-3.7.0-0-gc8baf9cd3cb603e030969bfe24634d5e85549915

**Comment by herrbischoff** [comment]
Also had this issue and had to do a mixture of steps:

1. Delete `/etc/apache2/mods-enabled/hhvm_proxy_fcgi.conf`
2. Add `ProxyPassMatch ^/(.*\.php(/.*)?)$ fcgi://127.0.0.1:9000/var/www/html/$1` to Apache site config
3. Set `hhvm.server.fix_path_info = false` in `/etc/hhvm/server.ini`
4. Restart both Apache and hhvm

### Environment

```
$ uname -a
Linux vagrant-ubuntu-trusty-64 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```
```
$ hhvm --version
HipHop VM 3.7.1 (rel)
Compiler: tags/HHVM-3.7.1-0-g111c76378ac29aa8f25e6bb3c5f15b628e6bbea1
Repo schema: be14a89778f35ca7f7dd4aca7fff0793e8ae3334
```

**Comment by jelqui** [comment]
Setting HHVM with apache 2.4 running fastcgi:
#nano /etc/apache2/mods-enabled/hhvm_proxy_fcgi.conf
comment this line
#ProxyPassMatch ^/(.+\.(hh|php)(/.*)?)$ fcgi://127.0.0.1:9000/var/www/$1
Why did we comment that line? to avoid having it running globally on apache instead we are going to edit each virtualhost on apache to make it run by each virtualhost    

Edit  nano /etc/apache2/sites-available/virtualhost.conf
#beginning  of virtualhost file
<VirtualHost *:80>
        ServerName example.com

        ServerAdmin webmaster@partshighway.com
        DocumentRoot /home/www/public_html
        ProxyPassMatch ^/(.*\.php(/.*)?)$ fcgi://127.0.0.1:9000/home/www/public_html/$1

        ErrorLog /home/www/log/error.log
        CustomLog /home/www/log/access.log combined

        <Directory /home/www/public_html/>
                DirectoryIndex index.php
                AllowOverride All
                Require all granted
        </Directory>
</VirtualHost>
# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
#end of virtualhost file

#sudo service apache2 stop
#sudo service hhvm stop
than
#sudo service hhvm start
#sudo service apache2 start

**Comment by Maxence** [comment]
Thanks @SiebelsTim, hhvm.server.fix_path_info solved my issue here.

**Comment by paulbiss** [comment]
Looks like there's a resolution here. fix_path_info is now documented here: https://docs.hhvm.com/hhvm/configuration/INI-settings#common-options
