### ISSUE TITLE
how to enable mod_proxy and mod_proxy_fcgi for  apache 2.4.10 

### ISSUE THREAD

**Issue by dkeuhxx** [facebook/hhvm#3475]
how to enable mod_prox and mod_proxy_fcgi for  apache 2.4.10 ?  i need mod_proxy and mod_proxy_fcgi run /usr/share/hhvm/install_fastcgi.sh

**Comment by paulbiss** [comment]
https://docs.hhvm.com/hhvm/advanced-usage/fastCGI
https://httpd.apache.org/docs/2.4/mod/mod_proxy_fcgi.html
https://httpd.apache.org/docs/2.4/mod/mod_proxy.html
