### ISSUE TITLE
Async MySQL Writes

### ISSUE THREAD

**Issue by infusion** [facebook/hhvm#3486]
Hi,

I implemented an async write queue thread in PHP back then. We now have async functions in hack, but what do you think about some "fire and forget" queries, for which it isn't necessary to get the result or a confirmation?

An example from my API change in PHP:

$db = mysqli_connect(..., MYSQLI_DELAYED); // lookup a con in the delayed pool or connect
mysqli_query($db, "INSERT INTO stats..."); // Is not sent to the server, but added to a linked list, which is written async

Previously, I started hacking with pcntl_fork() & a new connection, which was far away from performant. The fork overhead killed everything.

I think facebook itself could benefit from a feature like that, too.

What do you think?

Robert

**Comment by mikeytown2** [comment]
Both of those issues look fixed. Any word on when we could see this in HHVM? I use the async connection to detect metadata locks and kill them before they become an issue and redo the query in a safe but slow way; TRUNCATE vs DELETE in this case.

**Comment by fredemmott** [comment]
This is in the nightlies, and will be in 3.6. We open-sourced Facebook's internal async MySQL.

http://docs.hhvm.com/manual/en/book.hack.async.mysql.php

**Comment by craigcarnell** [comment]
@fredemmott What happened to the release of 3.6? It was supposed to be released on the 27th Feb. Thanks!

**Comment by fredemmott** [comment]
It should be out today; we're not aware of issues, but wanted to spend a little while longer testing first.
