### ISSUE TITLE
Using HHVM as a daemon

### ISSUE THREAD

**Issue by infusion** [facebook/hhvm#3502]
Hi,

I use PHP as a daemon, which forks itself using pcntl_fork(). I now try to port this to hhvm, which should be quite easy if something like

hhvm --mode daemon worker.php

would work. Unfortunately, the intuitive shot didn't work. I tried to figure out if you use a special -vServer.Type setting, but couldn't find anything except the fastcgi & relict libevent parameter. Did I miss something in the source or don't you use HHVM as a background worker at facebook?

If it's not possible yet, what would you think of to add this feature?

Robert

**Comment by Orvid** [comment]
We already support this I believe. The test runner even uses `pcntl_fork`
