### ISSUE TITLE
"What is this phabricator thing, and how do I use it?" cheat sheet on the github wiki

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#3544]
Should explain why we have it, and explain the work flow. In particular:
 - what 'accept' means when an FB employee does it
 - how the test runs work
 - if we request changes, what do you need to do? It basically means 'request changes or reply to question; we need /something/ from you'. This might be an update the PR, or it might just be write a comment in phabricator answering a question, and selecting 'Request review'
 - how to add reviewers if you know who's relevant. If not, don't worry, we'll see them (even if they have no reviewers)

**Comment by asgrim** [comment]
I have started this document here:
https://github.com/facebook/hhvm/wiki/What-is-Phabricator

**Comment by reeze** [comment]
Can you please add an explanation about what 'Test plan' is, and what should I write and shouldn't write?

**Comment by fredemmott** [comment]
I've added some information on the test plan field.

**Comment by asgrim** [comment]
@fredemmott can I ask for clarification on https://github.com/facebook/hhvm/wiki/What-is-Phabricator#getting-a-change-accepted ? I wrote:

> Once that happens, the HHVM team will merge the change and it will "land" in GitHub.

Is this correct? Or should we be clicking "Land to GitHub" button in Phabricator? Thanks :)

**Comment by SiebelsTim** [comment]
The @hhvm-bot will automatically land the diff to github. Don't use the `Land to GitHub` button.

**Comment by asgrim** [comment]
@SiebelsTim thanks for clarification - I have updated the wiki

**Comment by SiebelsTim** [comment]
I think this can be closed.
