### ISSUE TITLE
oss make clean leaves stuff behind

### ISSUE THREAD

**Issue by rrh** [facebook/hhvm#3554]
An invocation of
  make clean
in open source land doesn't remove many build products.

It would be nice if there were a root level entry point that removed every build product, including build products from cmake.  

For example:
  files in hphp/hack/src/** ending with: .annot, .o, .a, .so
  all directories CMakeFiles (this may be a bit of a big hammer)
  The ocaml byproduct files such as those matching egrep -e "\.(cmo|cma|cmi|cmx|cmxa)$"
  and more

AFAICT there are no entry points in the generated Makefile such as: purge, really_clean, dist_clean or related traditional verbs.

I just wasted 2+ hours recompiling in an existing directory, eventually figuring out that freeetype's cmake determined configuration hadn't been redone to track recent changes to the logic of where to find freetype.  I had started with 'make clean' first!

**Comment by Orvid** [comment]
This issue has been waiting for more info for more than 2 weeks. Closing for now, feel free to re-open it if you can provide more info.

https://github.com/facebook/hhvm/wiki/Human-Timeouts
