### ISSUE TITLE
Typechecker doesn't understand ++ on a string

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#3555]
``` PHP
<?hh

function foo(string $bar) {
  var_dump($bar);
}

function main() {
  $x = 'foo 0';
  ++$x;
  foo($x);
}

main();
```

```
[fredemmott@devbig076 ~/hhfail] hh_client
/home/fredemmott/hhfail/test.php:9:3,6: Typing error
  /home/fredemmott/hhfail/test.php:9:3,6: This is a num (int/float) because this is used in an arithmetic operation
  /home/fredemmott/hhfail/test.php:8:8,14: It is incompatible with a string
[fredemmott@devbig076 ~/hhfail] hhvm test.php
string(5) "foo 1"
```

See https://github.com/php/php-langspec/blob/master/spec/10-expressions.md#postfix-increment-and-decrement-operators and https://github.com/php/php-langspec/blob/master/spec/10-expressions.md#prefix-increment-and-decrement-operators

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

The error message that hh_client issues in 2020 makes sense. The `++` operator on the string is blamed and the type of the variable remains string. So passing it to takes_string() is valid, but passing it to takes_num() is invalid (matching runtime behavior).
