### ISSUE TITLE
ini_set error_log not working

### ISSUE THREAD

**Issue by kristapsk** [facebook/hhvm#3558]
Test script:
```PHP
<?php
ini_set('error_log', '/tmp/test1.log');
error_log('Message #1');
ini_set('error_log', '/tmp/test2.log');
error_log('Message #2');
```
PHP:
```
$ php test.php
$ cat /tmp/test*.log
[22-Aug-2014 16:49:56 UTC] Message #1
[22-Aug-2014 16:49:56 UTC] Message #2
```
HHVM:
```
$ hhvm test.php
Message #1
Message #2
$ cat /tmp/test*.log
cat: /tmp/test*.log: No such file or directory
```
It's with a few hours old HHVM master.

**Comment by naydav** [comment]
Have you any updates? We have problem with ini_get('soap.wsdl_cache_enabled')

**Comment by ThomasBS** [comment]
Any updates?

We're looking forward to use HHVM in our setup but we're holding back because of this bug.

**Comment by diegocn** [comment]
I've tested @lifeihuang workaround (set path twice) and it worked.

HipHop VM 3.2.0 (rel)
Compiler: tags/HHVM-3.2.0-0-g01228273b8cf709aacbd3df1c51b1e690ecebac8
Repo schema: c52ba40f4a246d35a88f1dfc1daf959851ced8aa

**Comment by digitalronin** [comment]
The ini_set call is doing *something* - just not what it's supposed to do.

The only way I could get errors to log to a file was to have these;

    log_errors = On
    error_log = /var/log/hhvm_errors.log

...in the INI file *and* a call to ini_set error_log in my code;

    ini_set('error_log', 'this value is irrelevant');

Putting the log_errors part into another ini_set call didn't work.

    // This, without the INI file settings, didn't work
    ini_set('log_errors', 'On');
    ini_set('error_log', '/var/log/hhvm_errors.log');


Here is a minimal setup to demonstrate this;


hhvm.ini

    ; This setting is only here so that, when the test
    ; script runs, we can tell that this INI file is
    ; having *some* effect.
    date.timezone = 'Asia/Tokyo'

    ; These two lines have to be here, but are not
    ; sufficient
    log_errors = On
    error_log = /var/log/hhvm_errors.log

    ; These settings seem to have no effect
    ; hhvm.log.use_log_file = true
    ; hhvm.log.file = /var/log/hhvm_errors.log


test.hh

    <?hh

    // Without this line *and* log_errors and error_log defined
    // in the INI file, errors are not written to the file

    ini_set('error_log', 'you can put anything at all here');


    // Output the date with timezone, so we know that the ini file 
    // is being used

    echo date('r');

    // write something to the error log file (hopefully)

    error_log("something");

    // raise an error (which should be logged in the file)

    no_such_method();


Execute like this;

    hhvm -c ./hhvm.ini test.hh

This is my hhvm version

    # hhvm --version
    HipHop VM 3.6.1 (rel)
    Compiler: tags/HHVM-3.6.1-0-gc051feff88ba8050f33f10f7b1fb07f8d3415f9e
    Repo schema: 42f49251b5c27daf4e13cb6bcd0c7ef4824b55a3

**Comment by Profforgr** [comment]
Can someone look at that?

This commit seems to still not fix the issues https://github.com/facebook/hhvm/commit/27da833fb848c94df30447b39edb4b430128d40f
Still ini_set('error_log','...'); redirect full server log to selected file. Not only current request, but of all websites or scripts running at the server.

That's very bad from different points:
1. Security. Any script on the server can have error logs of all other scripts on the server (even outside of sandboxes, file access rules).
2. Compability. Plain php definitely does not acts that way.
3. Convenience. When your error log full of logs from other scripts, that's crazy. Especially crazy if there are many frequently-accessed scripts on the server.

**Comment by dy93** [comment]
any update?

**Comment by JoelMarcey** [comment]
@Orvid Can you verify if this is still broken?

**Comment by Orvid** [comment]
This is not an issue in the current version of HHVM.

**Comment by kmaslack** [comment]
Rasmus' original repro in the first message still fails in exactly this way for me on 3.12.2. How current do things need to be?

**Comment by Orvid** [comment]
You have to have error_log enabled for logging to go to file. 3v4l.org doesn't have error_log enabled, so it can't be reproduced there. My test was against the current trunk version of HHVM, but there hasn't been any changes to that area in quite a while.

**Comment by edwinsmith** [comment]
is it really the intended behavior for hhvm to require the error_log ini setting in the file, *and* via code, to make it work? (re-reading @digitalronin 's description)

**Comment by Orvid** [comment]
It doesn't require it via code. This issue was specifically related to setting it via code, specifically, it was due to wanting to log different parts of the script to different files.
