### ISSUE TITLE
hh_client reports a lot of PHP "globals"

### ISSUE THREAD

**Issue by infusion** [facebook/hhvm#3565]
Hi,

hh_client reports a lot of PHP internals, which should be defined for the type checker. Here a unique list of my actual run:

/www/dev/lib/route.php:25:9,12: Unbound name: exit
/www/dev/lib/db.php:8:21,33: Unbound name: mysqli_result
/www/dev/lib/db.php:39:92,102: Unbound name: mysqli_info
/www/dev/lib/db.php:79:18,33: Unbound name: mysqli_fetch_row
/www/dev/lib/db.php:79:35,46: Unbound name: mysqli_query
/www/dev/lib/db.php:163:35,43: Unbound name: E_WARNING
/www/dev/lib/db.php:161:26,44: Unbound name: mysqli_get_warnings
/www/dev/lib/db.php:159:21,40: Unbound name: mysqli_warning_count
/www/dev/lib/db.php:152:39,50: Unbound name: mysqli_errno
/www/dev/lib/db.php:476:29,44: Unbound name: mysqli_thread_id
/www/dev/lib/db.php:149:35,41: Unbound name: E_ERROR
/www/dev/lib/db.php:472:14,24: Unbound name, Typing: mysqli_ping
/www/dev/lib/db.php:204:9,26: Unbound name: mysqli_free_result
/www/dev/lib/db.php:218:61,72: Unbound name: MYSQLI_ASSOC
/www/dev/lib/db.php:218:16,31: Unbound name: mysqli_fetch_all
/www/dev/lib/db.php:261:21,39: Unbound name: MYSQLI_STORE_RESULT
/www/dev/lib/db.php:259:21,37: Unbound name: MYSQLI_USE_RESULT
/www/dev/lib/db.php:480:54,73: Unbound name: mysqli_get_host_info
/www/dev/lib/db.php:356:104,123: Unbound name: mysqli_connect_error
/www/dev/lib/db.php:351:52,67: Unbound name: mysqli_select_db
/www/dev/lib/db.php:481:20,26: Unbound global constant (Typing)
         (line 481: $err = E_ERROR;)

But also:
/www/dev/lib/route.php:84:43,49: Unbound name: include
/www/dev/lib/project.php:82:21,28: Undefined variable: $_SERVER
/www/dev/lib/route.php:78:25,33: Undefined variable: $_SESSION
/www/dev/lib/route.php:44:44,48: Undefined variable: $_GET
/www/dev/tests/class.path.php:543:14,18: Unbound name: empty

As empty/unset isn't known, it gets also reported on different namespaces:
/www/dev/lib/process/path.php:153:29,33: Unbound name, Typing: process\empty
/www/dev/lib/process/path.php:154:29,33: Unbound name, Typing: process\unset
/www/dev/lib/process/keyword.php:160:45,54: Unbound name: process\ENT_QUOTES

I also get a warning if a (static) method is called inside another method, which is defined right after the calling method.

Thanks Robert

@
$ hhvm --version
HipHop VM 3.3.0-dev+2014.08.22 (rel)
Compiler: heads/master-0-gcf0499dc86b49d69c3aeb77b19660371fada3fb7
Repo schema: 7a43960ad8bafac63a0edae194227c3ace511328
Extension API: 20140702

**Comment by amit66944** [comment]
same i thing i am facing

**Comment by amit66944** [comment]
I am also facing problem when its strict mode

Unbound name: mysqli_connect (a global function) (Naming[2049])

**Comment by jwatzman** [comment]
Yep, feel free to send us a PR to add the funtion to the hhi files, as in my comment above. There are just a few places in the stdlib that we missed function definitions and need to inform the typechecker about them.

**Comment by paulbiss** [comment]
Generally we will take PRs for missing hhi interfaces but it's not something we're actively pursuing.
