### ISSUE TITLE
Overriding native function return values

### ISSUE THREAD

**Issue by infusion** [facebook/hhvm#3566]
Hi,

internal PHP functions rely on array() as a return value. I have no idea how the API could look like, but what do you think about adding a way to return values as a Map or Vector out of native php functions like func_get_args(), mysqli_***, ...?

For the mysql[i]-API, another constant would be possible, like:

$res = mysqli_query("...", MYSQLI_MAP_VECTOR);

which will result in a vector of maps for mysqli_fetch_all, a map for mysqli_fetch_assoc and a vector for mysqli_fetch_row.

Robert

**Comment by paulbiss** [comment]
Closing this discussion for now. If someone wants to propose a mechanism for this I would be interested to hear it, but I think the right answer here is to design a saner standard library to work with collections or more likely the new hack arrays.
