### ISSUE TITLE
Getting php errors to show in HHVM daemon

### ISSUE THREAD

**Issue by Firebrand** [facebook/hhvm#3576]
Hi guys and gals. I have HHVM running as a daemon (hhvm --mode daemon -vServer.Type=fastcgi -vServer.Port=9000 -vPidFile=/var/run/hhvm.pid). When I should be seeing PHP errors/warnings I just get a black page. How can I display PHP errors/warnings/notices, or at the very least, log them into a file?

Thanks!

**Comment by paulbiss** [comment]
Longer discussion of this is at #4436
