### ISSUE TITLE
HHVM does not allow foreach by reference with generators

### ISSUE THREAD

**Issue by TimeToogo** [facebook/hhvm#3585]
HHVM fatals on foreach by reference on an iterator. 
Some special iterators in PHP such as `Generator` permit this usage.

Example code: http://3v4l.org/ZL84S

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This issue relies on `&$references`, which were [removed](https://hhvm.com/blog/2019/10/01/deprecating-references.html) from hhvm.
