### ISSUE TITLE
Add ability to flakeylist/blacklist/clownlist specific tests, not entire files

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#3592]
For example, SlimTest::testExpiresAsString() is flakey - it assumes that getting the current time in seconds twice in a row will get the same result. This currently requires flakeylisting all of SlimTest, which is huge.

cc @GrahamCampbell, @JoelMarcey who might be interested in this

**Comment by paulbiss** [comment]
This feature request is not actively being worked on. We would happily consider a pull request implementing it. If you plan to work on this issue let us know in the comments and we will re-open the issue and assign it to you. If you feel strongly that this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
