### ISSUE TITLE
fastcgi keep connect crash

### ISSUE THREAD

**Issue by huzhiguang** [facebook/hhvm#3599]
I use hhvm version 3.0.1 ,but fastcgi function I have patched hhvm version 3.2.

I don't make easy test case to you ,I only our server environment replay this crash problem,I have tracked the problem related to keep connect function(short connect not problem).

crash throw message:

	E0827 14:50:09.402464  1925 fastcgi-session.cpp:570] FastCGI protocol: received an invalid record
	pure virtual method called
	terminate called without an active exception
	Segmentation fault (core dumped)

crash stack:

	#0  0x000000000372a6a6 in apache::thrift::async::TEventBase::inRunningEventBaseThread (this=0x0)
	    at /mnt/huzhiguang/all_project/hhvm-3.0.1/public/hhvm/hhvm-src-301-debug/hhvm-HHVM-3.0.1/hphp/third_party/thrift/lib/cpp/async/TEventBase.h:326
	#1  0x00000000037293f9 in apache::thrift::async::TEventBase::runInEventBaseThread(std::tr1::function<void ()> const&) (this=0x0, fn=...)
	    at /mnt/huzhiguang/all_project/hhvm-3.0.1/public/hhvm/hhvm-src-301-debug/hhvm-HHVM-3.0.1/hphp/third_party/thrift/lib/cpp/async/TEventBase.cpp:383
	#2  0x00000000025f96e0 in HPHP::FastCGITransport::sendImpl (this=0x7fb780f88e18, data=0x7fb71300ff68, size=121, code=200, chunked=false)
	    at /mnt/huzhiguang/all_project/hhvm-3.0.1/public/hhvm/hhvm-src-301-debug/hhvm-HHVM-3.0.1/hphp/runtime/server/fastcgi/fastcgi-transport.cpp:319
	#3  0x00000000025b7921 in HPHP::Transport::sendRawLocked (this=0x7fb780f88e18, data=0x7fb70ea0e048, size=121, code=200, compressed=false, chunked=false, codeInfo=0x0)
	    at /mnt/huzhiguang/all_project/hhvm-3.0.1/public/hhvm/hhvm-src-301-debug/hhvm-HHVM-3.0.1/hphp/runtime/server/transport.cpp:779
	#4  0x00000000025b7b08 in HPHP::Transport::sendRaw (this=0x7fb780f88e18, data=0x7fb70ea0e048, size=121, code=200, compressed=false, chunked=false, codeInfo=0x0)
	    at /mnt/huzhiguang/all_project/hhvm-3.0.1/public/hhvm/hhvm-src-301-debug/hhvm-HHVM-3.0.1/hphp/runtime/server/transport.cpp:794
	#5  0x0000000002585bf5 in HPHP::HttpRequestHandler::executePHPRequest (this=0x7fb7273fc740, transport=0x7fb780f88e18, reqURI=..., sourceRootInfo=..., cachableDynamicContent=false)
	    at /mnt/huzhiguang/all_project/hhvm-3.0.1/public/hhvm/hhvm-src-301-debug/hhvm-HHVM-3.0.1/hphp/runtime/server/http-request-handler.cpp:370
	#6  0x000000000258513d in HPHP::HttpRequestHandler::handleRequest (this=0x7fb7273fc740, transport=0x7fb780f88e18)
	    at /mnt/huzhiguang/all_project/hhvm-3.0.1/public/hhvm/hhvm-src-301-debug/hhvm-HHVM-3.0.1/hphp/runtime/server/http-request-handler.cpp:289
	#7  0x000000000260f3a7 in HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJobImpl (this=0x7fb743e3e0c0, job=..., abort=false)
	    at /mnt/huzhiguang/all_project/hhvm-3.0.1/public/hhvm/hhvm-src-301-debug/hhvm-HHVM-3.0.1/hphp/runtime/server/server-worker.h:103
	#8  0x000000000260ed4c in HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJob (this=0x7fb743e3e0c0, job=...)
	    at /mnt/huzhiguang/all_project/hhvm-3.0.1/public/hhvm/hhvm-src-301-debug/hhvm-HHVM-3.0.1/hphp/runtime/server/server-worker.h:57
	#9  0x000000000260723c in HPHP::JobQueueWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::Server*, true, false, HPHP::JobQueueDropVMStack>::start (this=0x7fb743e3e0c0)
	    at /mnt/huzhiguang/all_project/hhvm-3.0.1/public/hhvm/hhvm-src-301-debug/hhvm-HHVM-3.0.1/hphp/util/job-queue.h:409
	#10 0x00000000026084cd in HPHP::AsyncFunc<HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits> >::run_ (obj=0x7fb780ce6f00)
	    at /mnt/huzhiguang/all_project/hhvm-3.0.1/public/hhvm/hhvm-src-301-debug/hhvm-HHVM-3.0.1/hphp/util/async-func.h:205
	#11 0x00000000034d0585 in HPHP::AsyncFuncImpl::threadFuncImpl (this=0x7fb780ce6f00)
	    at /mnt/huzhiguang/all_project/hhvm-3.0.1/public/hhvm/hhvm-src-301-debug/hhvm-HHVM-3.0.1/hphp/util/async-func.cpp:131
	#12 0x00000000034d0169 in HPHP::AsyncFuncImpl::ThreadFunc (obj=0x7fb780ce6f00) at /mnt/huzhiguang/all_project/hhvm-3.0.1/public/hhvm/hhvm-src-301-debug/hhvm-HHVM-3.0.1/hphp/util/async-func.cpp:51
	#13 0x00007fb78c0671c1 in start_thread () from /home/work/local/hhvm/lib64/libpthread-2.18.so
	#14 0x00007fb78b57d0ad in clone () from /home/work/local/hhvm/lib64/libc-2.18.so

I tracking this problem and I want you to track together.Thanks.

**Comment by jwatzman** [comment]
I am fairly confident that this is fixed by e13ca7d910554bd455980be1cac65d888d71a931 which will start showing up in nightly builds dated 2015.02.03, as well as in 3.6.0, 3.5.1, and 3.3.4 whenever those come out. I'm going to close this now; please reopen if you can repro in any of those versions.
