### ISSUE TITLE
Not a valid stream resource when attempting to fopen a named pipe

### ISSUE THREAD

**Issue by wagideas** [facebook/hhvm#3602]
mkfifo /tmp/cashed

In Code:
   $pipe =  @fopen("/tmp/cashed", 'w');
    fwrite($pipe, 1);
    fclose($pipe);

I get a "Not a valid stream resource" which I assume is because HHVM does not support named pipes on linux [Ubuntu] ?

**Comment by jesseschalken** [comment]
Works for me:

```php
<?php

$pipe = fopen('./pipe', 'w');
fwrite($pipe, "hello\n");
fclose($pipe);
echo "finished\n";

```
```
$ mkfifo pipe
$ hhvm test.php &
[1] 22258
$ cat pipe
finished
hello
[1]+  Done                    hhvm test.php
$
```

Using HHVM 3.19.1

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This issue has been fixed since your issue was created. Your repro works as expected in hhvm 3.19.1 and 4.56.
