### ISSUE TITLE
Add support for user attributes on class properties

### ISSUE THREAD

**Issue by maciej-sz** [facebook/hhvm#3605]
Syntax already supported for classes, methods and parameters, but not for class properties:

```
class Foo {
    <<MyAttribute>> public string $bar;
}

$attributes = (new \ReflectionClass(Foo::class))->getProperty('bar')->getAttributes();
```

Opening this mainly for status updates. Any ETA?

**Comment by tristanpemble** [comment]
:+1:, worth noting the documentation says:

> Attributes in Hack provide the ability to give **any reflectable piece of code** additional contextual information.

so, this might be considered a bug based on that description, since properties are reflectable code ;)

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This issue has been fixed at some point. Reflection on annotations on class properties works as expected.
