### ISSUE TITLE
Assertion failure: deltaFits(table, sz::dword) on OSX

### ISSUE THREAD

**Issue by ciaranmcnulty** [facebook/hhvm#3642]
Installed 3.3.0 using Homebrew. On execution of any script I get this issue:

Assertion failure: deltaFits(table, sz::dword)
Destructor function table is expected to be in the data segment, with addresses less than 2^31

/usr/local/Cellar/hhvm/3.3.0/src/hphp/runtime/vm/jit/code-gen-helpers-x64.h:215: HPHP::jit::MemoryRef HPHP::jit::X64::lookupDestructor(HPHP::jit::X64Assembler&, HPHP::jit::PhysReg): assertion `deltaFits(table, sz::dword)' failed.

**Comment by slimlv** [comment]
is this really fixed ?

localhost bin #  hhvm --version
HipHop VM 3.3.4 (rel)
Compiler: tags/HHVM-3.3.4-0-gd047f568f631cab5836d573432459d02b24c622e
Repo schema: 63182c581872ce472074c5585fb2fd2e83559c2b
Extension API: 20140829
localhost bin # hhvm --mode server -vServer.Type=fastcgi -vServer.Port=9898

Assertion failure: deltaFits(table, sz::dword)
Destructor function table is expected to be in the data segment, with addresses less than 2^31

/var/tmp/portage/dev-php/hhvm-3.3.4/work/hhvm-3.3.4/hphp/runtime/vm/jit/code-gen-helpers-x64.h:215: HPHP::jit::MemoryRef HPHP::jit::x64::lookupDestructor(HPHP::jit::X64As
:jit::PhysReg): assertion `deltaFits(table, sz::dword)' failed.
Aborted

**Comment by jwatzman** [comment]
We haven't gotten any recent complaints of this on Linux, and in my testing of the Mac build (getting it working again) I haven't seen it there either. It's unclear if the fix ever made it into the 3.3 release; if someone wants to send a PR against that branch to merge something, happy to do that, otherwise closing this as fixed.
