### ISSUE TITLE
Notice: Array to string conversion in array_intersect - why?

### ISSUE THREAD

**Issue by levixie** [facebook/hhvm#3644]
Hi There
I notice hhvm will throw array to string conversion error on this code which works perfect on php
Can anyone tell me what is the right way to avoid it or it is a bug in hhvm

<?php
$array1 = array("a" => array(1));
$array2 = array("b" => array("1"));
$result = array_intersect($array1, $array2);
print_r($result);

> hhvm test.php

Notice: Array to string conversion in /home/jesse/test.php on line 4

Notice: Array to string conversion in /home/jesse/test.php on line 4

**Comment by kodmanyagha** [comment]
I found a solution. You can use `array_keys` for first array.

```
    public function create(array $data): mixed
    {
        $save = new User();

        $fillable = array_values($save->getFillable());
        $keys     = array_keys($data);
        $fillable = array_intersect($keys, $fillable);

        foreach ($fillable as $key) {
            $save->$key = $data[$key];
        }
        $save->save();

        return $save;
    }

```
