### ISSUE TITLE
Incompatible handling of date-times during DST transitions

### ISSUE THREAD

**Issue by BenMorel** [facebook/hhvm#3651]
Consider the following code:

    $datetimes = [
        '2014-10-05T01:59:59',
        '2014-10-05T02:00:00',
        '2014-10-05T02:59:59',
        '2014-10-05T03:00:00'
    ];

    foreach ($datetimes as $datetime) {
        $dt = new DateTime($datetime, new DateTimeZone('Australia/Sydney'));
        echo $dt->format(DateTime::ISO8601) . PHP_EOL;
    }

Result with PHP 5.5:

> 2014-10-05T01:59:59+1000
> 2014-10-05T03:00:00+1100
> 2014-10-05T03:59:59+1100
> 2014-10-05T03:00:00+1100

Result with HHVM 2.4.0:

> 2014-10-05T01:59:59+1000
> 2014-10-05T02:00:00+1100 // wrong
> 2014-10-05T02:59:59+1100 // wrong
> 2014-10-05T03:00:00+1100

As you can see, times between `2:00 AM` and `3:00` AM (at which clocks are set back 1 hour), are calculated in a different way in PHP and HHVM.

Both results are actually correct, as between 2 AM and 3 AM, 2 valid offsets exist for any given time; but it is important to align the behavior of HHVM on PHP.

**Comment by BenMorel** [comment]
Hi, it's been more than a year since this bug has been tagged as "probably easy", but nothing has been done so far. Are you planning to fix it?

**Comment by lucastadeu** [comment]
I haven't been working with HHVM since last year.
Completely forgot to remove this.

Feel free to tackle it.

**Comment by paulbiss** [comment]
@BenMorel no one here has had a chance to look at it yet. Sorry about the delay there are only so many of us so. We generally add the probably easy tag to issues we feel would be simple enough a new contributor could send us a pull request, it's unrelated to the relative priority of issues.

**Comment by BenMorel** [comment]
Thank you! :+1:
