### ISSUE TITLE
Cygwin: No FSEVENTS in dfind, unsupported OS while make

### ISSUE THREAD

**Issue by DeniR** [facebook/hhvm#3660]
Compile using make break at:
\home\user\hhvm\hphp\hack\src\dfind\Makefile
ifndef FSEVENTS
  $(error Unsupported os: OS)
endif 

$ make install
[  0%] Built target fastlz
[  0%] Built target afdt
[  5%] Built target mbfl
[  5%] Built target sqlite3
[  6%] Built target timelib
[  6%] Built target lz4
[  6%] Built target double-conversion
[  9%] Built target folly
[ 16%] Built target zip_static
[ 16%] Built target gen-class-map
[ 16%] Built target gen-ext-hhvm
[ 16%] Built target gen-infotabs
[ 16%] Built target hphp_system
[ 16%] Built target hphp_parser
[ 23%] Built target hphp_analysis
Makefile:20: *** Unsupported os: OS.  Stop.
Makefile:157: recipe for target 'depend' failed
make[3]: *** [depend] Error 2
hphp/hack/CMakeFiles/hack.dir/build.make:52: recipe for target 'hphp/hack/CMakeFiles/hack' failed
make[2]: *** [hphp/hack/CMakeFiles/hack] Error 2
CMakeFiles/Makefile2:853: recipe for target 'hphp/hack/CMakeFiles/hack.dir/all' failed
make[1]: *** [hphp/hack/CMakeFiles/hack.dir/all] Error 2
Makefile:106: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Orvid** [comment]
We're preferring actual MSVC support over Cygwin.
