### ISSUE TITLE
Memory leak when self-referencing

### ISSUE THREAD

**Issue by sannysoft** [facebook/hhvm#3661]
Found the following problems when working with Yii2 events - it stores [$this,'functionName'] in object events array to call it with call_user_func later - it leads to memory leak and termination.

Here is a test case:
```
<?php

class TestClass
{
    private $_events = [];

    public function __construct()
    {
        $this->_events[] = $this;
    }
}

while (1)
    $hotel = new TestClass();
```

**Comment by paulbiss** [comment]
We now have support for enabling the GC

**Comment by edwinsmith** [comment]
-vEval.EnableGC=1 on the commandline enables automatic backup mark/sweep collection, as well as enabling gc_collect_cycles() to actually run an on-demand collection. Unlike PHP7,  HHVM's implementation of gc_collect_cycles() does not count the number of cycles.
