### ISSUE TITLE
System wide environment variables.

### ISSUE THREAD

**Issue by bweston92** [facebook/hhvm#3665]
I'm getting similar behavior to #1650 . Except it is system environment variables set in `/etc/environment` works on command line but fastcgi just not working.

I've set the environment variable in fastcgi params and it works, really is just system environment variables not being read.

```
HipHop VM 3.2.0 (rel)
Compiler: tags/HHVM-3.2.0-0-g01228273b8cf709aacbd3df1c51b1e690ecebac8
Repo schema: c52ba40f4a246d35a88f1dfc1daf959851ced8aa
```

**Comment by Orvid** [comment]
This issue has been waiting for more info for more than 2 weeks. Closing for now, feel free to re-open it if you can provide more info.

https://github.com/facebook/hhvm/wiki/Human-Timeouts
