### ISSUE TITLE
500 hphp_invoke white screen of dead

### ISSUE THREAD

**Issue by ingomarent** [facebook/hhvm#3667]
I´m having trouble with some WordPress Plugins.
I´m getting 500 hphp_invoke status and a white screen of dead.

My Problem is that nothing is logged to /var/log/hhvm/error.log.
What setting do i have to make to log the reason of this error.

Please help.

My php.ini:
hhvm.mysql.typed_results = false
pid = /var/run/hhvm/pid
hhvm.server.port = 9000
hhvm.server.type = fastcgi
hhvm.server.default_document = index.php
hhvm.log.use_log_file = true
hhvm.log.file = /var/log/hhvm/error.log
hhvm.repo.central.path = /var/run/hhvm/hhvm.hhbc
hhvm.log.level = Verbose
hhvm.log.always_log_unhandled_exceptions = true
hhvm.log.no_silencer = true
hhvm.log.injectedstacktrace = true
hhvm.log.nativestacktrace = true
hhvm.log.MaxMessagesPerRequest = -1

**Comment by aftabnaveed** [comment]
\nFatal error: Object of class Magmi_ProductImportEngine could not be converted to string in /path/to/magmi/inc/magmi_mixin.php

Today I got that issue with Magmi, a magent product importer, while it works with Zend PHP 5.6

**Comment by Mwesome** [comment]
I also keep getting these error everytime i make changes to my wordpress php files.
The only solution i have is to restart hhvm but that is no good if the no. of edits increase :/
Help?

**Comment by terah** [comment]
This may or may not help someone.  I was getting this error and it turned out to be a case sensitivity issue in my composer.json where I specified a lower case path to an include dir and the dir had an upper case letter in it.  The composer autoloader couldn't find the file. The problem didn't show up using PHP on my mac dev machine.

**Comment by RalphCorderoy** [comment]
I'm seeing `HTTP/1.1 500 hpph_invoke` with nothing in hhvm.log when a non-existent method is called on an object.
