### ISSUE TITLE
Hack: detect if trying to access a non-static property statically, give nicer error

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#3678]
When I have declared 'private string $foo' and try to access self::$foo:

```
Could not find class variable $foo
```

It'd be helpful if it said maybe I want $this->foo, or to add 'static' to the declaration.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This issue has been fixed, but there is now a different problem with the error message.
_No property 'foo' in ClassName (did you mean static method '$foo')?_
I'll pull this out into a new issue.
