### ISSUE TITLE
Mysqlnd

### ISSUE THREAD

**Issue by ghost** [facebook/hhvm#3679]
How do we know HHVM connect to the database with what drivers? I want to make sure that mysqlnd instead of libmysql? But can not see anything with phpinfo

**Comment by tecfu** [comment]
+1 for mysqlnd because it returns native types. 

Also, whoever thought it would be a good idea to clone the php5 docs and relabel them hhvm docs without noting all the features hhvm does not support has wasted a lot of time for adopters.

**Comment by simonwelsh** [comment]
You can set `hhvm.mysql.typed_results = true` to have native types returned.

**Comment by tecfu** [comment]
Thank you Simon.

**Comment by fatbattk** [comment]
:+1: +1 for mysqlnd support.

>Also, whoever thought it would be a good idea to clone the php5 docs and relabel them hhvm docs without noting all the features hhvm does not support has wasted a lot of time for adopters.

Agree! The docs are misleading and I can't see the value add of this. Was not aware `mysqlnd` is not supported till this issue!

**Comment by sudochop** [comment]
+1 100% necessary. Type safety should be a number 1 priority!

**Comment by SiebelsTim** [comment]
@fatbattk There's been some effort showing what functions/classes/extensions aren't supported:
 - You'll see `NOT SUPPORTED IN HHVM` on the function page
 - Every extension should inform you how to install it. You should see a not supported notice on those pages as well.
I agree with you, that this isn't ideal yet though ;)

**Comment by paulbiss** [comment]
I had a quick look yesterday, the typed_results setting should work for the mysql extension, so I suspect the bug is in PDO but didn't have time to dig any further.

**Comment by creativeprogramming** [comment]
1+ for mysqlnd (and PECL/mysqlnd-qc) support (for efficient query caching purpose, with slam defense):

http://php.net/manual/en/mysqlnd-qc.quickstart.concepts.php

**Comment by paulbiss** [comment]
This feature request is not actively being worked on. We would happily consider a pull request implementing it. If you plan to work on this issue let us know in the comments and we will re-open the issue and assign it to you. If you feel strongly that this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.

**Comment by ArmeniaH** [comment]
Hey guys !

We want to change our server environment and use hhvm, we already have a very big project implemented, where we heavily depend on these kind of type castings. 

We use laravel as our backend framework and use it's Eloquent ORM, and with hhvm we get issue !

**Comment by JanisE** [comment]
Here is another problem with libmysql working all right in php-mysqlnd: http://stackoverflow.com/a/36163689/99904 – BIGINT types being sent distorted to MySQL.
