### ISSUE TITLE
Unable to locate package hhvm

### ISSUE THREAD

**Issue by rudiedirkx** [facebook/hhvm#3691]
I've followed the steps on https://github.com/facebook/hhvm/wiki/Prebuilt-Packages-on-Ubuntu-12.04 exactly, but I still can't install `hhvm`:

```
rudie@devver:~$ sudo apt-get install hhvm
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package hhvm
```

The relevant `apt-get update` output:

```
rudie@devver:~$ sudo apt-get update | grep hhvm
Hit http://dl.hhvm.com precise Release.gpg
Hit http://dl.hhvm.com precise Release
Hit http://dl.hhvm.com precise/main i386 Packages
Ign http://dl.hhvm.com precise/main TranslationIndex
Ign http://dl.hhvm.com precise/main Translation-en_GB
Ign http://dl.hhvm.com precise/main Translation-en
```

So that worked (I think). Why can't it still not find a package?

I'm a total linux noob, sorry.

**Comment by alexrayu** [comment]
Mine hits i386 as well, even though I am no a 64 bit system. Anything an be done?

**Comment by sajjadkazemi10ss** [comment]
What type of Linux operating system is required to install?
How can I get hhvm?
