### ISSUE TITLE
user rights

### ISSUE THREAD

**Issue by SkiAn2007** [facebook/hhvm#3692]
how to run the name of different users?
I use the panel to configure the host and to preserve the security need this feature

nginx+hhvm

**Comment by fadimko** [comment]
Up. I run HHVM-3.9.1 as root. Setting `hhvm.server.user = nginx` in php.ini or adding `-vServer.User=nginx` to arguments don't changes user of hhvm process.

May be I misunderstood the meaning of this setting?
@JoelMarcey

**Comment by fadimko** [comment]
```
# cat php.ini
hhvm.server.user=nginx
# hhvm --mode daemon -c php.ini -vServer.Type=fastcgi -vServer.FileSocket=/var/run/hhvm.sock
Log file not specified under daemon mode.\n\n
# ps aux |grep hhvm
root     61699  0.5  0.5 727584 43500 ?        Ssl  01:07   0:00 hhvm --mode daemon -c php.ini -vServer.Type=fastcgi -vServer.FileSocket=/var/run/hhvm.sock
```

**Comment by r3wt** [comment]
Just be wary that you need to chown all the files and edit init.d for hhvm to use a different user. everytime you upgrade hhvm, you will have to repeat process.

**Comment by JoelMarcey** [comment]
@fadimko 

What happens if you just specify user directly at the command line?

```
hhvm --mode daemon --user nginx -vServer.Type=fastcgi -vServer.FileSocket=/var/run/hhvm.sock
```

**Comment by fadimko** [comment]
I created directory `/var/run/hhvm`, which is owned by user `nginx` and added `--no-config` to the command line.
```
# hhvm --mode daemon --no-config --user nginx -vServer.Type=fastcgi -vServer.FileSocket=/var/run/hhvm/hhvm.sock
Log file not specified under daemon mode.\n\n
# ps aux |grep hhvm
root     59880  1.6  0.5 727320 43472 ?        Ssl  18:23   0:00 hhvm --mode daemon --no-config --user nginx -vServer.Type=fastcgi -vServer.FileSocket=/var/run/hhvm/hhvm.sock
```

**Comment by fadimko** [comment]
Can you reproduce this problem?
