### ISSUE TITLE
CURLOPT_REDIR_PROTOCOLS not defined

### ISSUE THREAD

**Issue by dan-nl** [facebook/hhvm#3702]
while working on an extension for mediawiki i ran into an issue where several curl options were not set and resulted in the extension not being able to follow URL redirects. the curl options that we would need to focus on are listed here http://php.net/manual/en/function.curl-setopt.php in the CURLOPT_PROTOCOLS section.

the mediawiki bug i opened for the issue is here: https://bugzilla.wikimedia.org/show_bug.cgi?id=70570

**Comment by EwanValentine** [comment]
Any news on this? I can't seem to use certain cURL requests + hhvm :(

**Comment by josephscott** [comment]
Bumping up against this as well ( CURLOPT_PROTOCOLS and CURLOPT_REDIR_PROTOCOLS ).

**Comment by EwanValentine** [comment]
@josephscott I had to use nightly builds, that seemed to work, but... not ideal!

**Comment by Orvid** [comment]
I'm going to assume that the fix is in LTS releases now, so closing this.
