### ISSUE TITLE
Finish xdebug

### ISSUE THREAD

**Issue by jlreyes** [facebook/hhvm#3704]
Making an issue so there's a reference to what's left, also to have an issue to point to for TODOs. This does not include features implemented in the PR I'm going to send out, but is a comprehensive list of what's left afterwards.

While there's a lot here, it's almost all small. Everything is here because it was blocked by another unimplemented feature (beginning with `var_dump()`). 
 
# Var Dump
Xdebug has a custom implementation of `var_dump()` that overrides the default implementation. Almost everything left relies on this, so this should get high priority.
- [ ] Import and refactor var dump code from php5 xdebug
- [ ] Implement `xdebug_debug_zval()` and  `xdebug_debug_zval_stdout()`

## Related ini settings
- [ ] `cli_color, var_display_max_children, var_display_max_data, var_display_max_depth` Cosmetic
- [ ] `collect_includes, collect_params, collect_return` When enabled, the var_dump code is used to output more contextual information when tracing

# Error handling
Almost all of the work here involves refactoring the error handling code to allow extensions to override the default behavior. This primarily means modifying `program_functions.cpp`.
- [ ] Enable extension overriding of default error handling
- [ ] `xdebug_start_error_collection()`, `xdebug_stop_error_collection()`, `xdebug_get_collected_errors()` When error collection is enabled, non fatal error output is "collected" into an array that can be retrieved

## Related ini settings
- [ ]  `show_exception_trace` When an exception is thrown, print a stack trace (which relies on the below)

# Stack trace printing
On fatal errors a stack trace needs to be printed. The stack trace can be heavily customized through ini settings
- [ ] Use the above error handling overriding code to implement basic functionality
- [ ] `xdebug_dump_superglobals()` Dump the superglobals based on below ini settings

## Related ini settings
- [ ] `collect_memory, collect_time` If enabled, need to pull in time/memory information from the profiler
- [ ] `default_enable` Whether or not to enable stack traces, 
- [ ] `show_local_vars` Dump local variables at each level
- [ ] `dump_globals, dump.*` Dump superglobals on errors based on the latter settings

# Misc
- [ ] Documentation
- [ ] `file_link_format` ini setting. Users can specify the file link format used in stack traces and remote debugging.
- [ ] `get_headers()` function. Collects calls to `header()` and `setcookie()` and outputs them even when not running as a server.
- [ ] `JitEnableRenameFunction` should be enabled when xdebug is enabled in order for profiling to include builtins
- [ ] Match ini setting scope with php5 xdebug. Right now all settings are changeable and thread local. This is a problem as modifying certain ini settings during runtime could lead to weird state issues. We should just be able to match php5 xdebug's scopes.

# Cleanup/Improvements
Everything here is definitely not critical to being feature complete
- [ ] Clean up XDebugUtils
- [ ] Refactor and replace `php5_xdebug/xdebug_xml` with a less clunky api
- [ ] Remove `php5_xdebug/xdebug_str`
- [ ] Remove `php5_xdebug/xdebug_mm`
- [ ] Clean up and refactor `php5_xdebug/xdebug_var`
- [ ] Eliminate php5_xdebug folder
- [ ] `xdebug_call_*` functions should use the corresponding `ExecutionContext` methods and the hni functions and should not be `NoFCallBuiltin`
- [ ] Potentially allow setting a maximum buffer size for the profiler
- [x] `hhvm.xdebug-not-done` -> `xdebug`
- [ ] Remove `XDEBUG_NOTIMPLEMENTED`

**Comment by tuminoid** [comment]
Is this still valid issue and current state is reflected?

**Comment by fredemmott** [comment]
We have compatibility with major IDEs and have not had issues reported for a while; this issue is probably not valuable any more. If issues still exist, they should be filed as separate issues.
