### ISSUE TITLE
Compiling 3rd party extensions with HHVM

### ISSUE THREAD

**Issue by JoiceJ** [facebook/hhvm#3720]
Hi,

We have been planning to live our server with HHVM . I have been working to enable voltdb extension with hhvm. 
We are unable make the installation. Leaving us with the below Error. 

==============
[100%] Building CXX object CMakeFiles/voltdb.dir/voltdb.cpp.o
/root/voltdb-client-php-extension-2.8.4/voltdb-client-php/voltdb.cpp:29:17: fatal error: php.h: No such file or directory
 #include "php.h"
                 ^
compilation terminated.
make[2]: *** [CMakeFiles/voltdb.dir/voltdb.cpp.o] Error 1
make[1]: *** [CMakeFiles/voltdb.dir/all] Error 2
make: *** [all] Error 2
================

You can download the voltdb extension with the below for the recreation. 

http://voltdb.com/downloads/technologies/client/voltdb-client-php-extension-2.8.4.tar.gz

Below is the URL I have been following to the add this extension. 
https://github.com/facebook/hhvm/wiki/Extension-API

Any suggestion is really appreciated. 

Regards,
Joice

**Comment by paulbiss** [comment]
https://github.com/facebook/hhvm/tree/master/hphp/runtime/ext_zend_compat
