### ISSUE TITLE
CMake Error: Error evaluating generator expression

### ISSUE THREAD

**Issue by sandeepuno** [facebook/hhvm#3728]
During recent compile the cmake is generating this error, this wasn't happend earlier.  I'm on Centos 6.5 and cmake 2.8

```
  $<LINK_ONLY:-Wl,--wrap=pthread_create>

  $<LINK_ONLY> expression requires exactly one parameter.

CMake Warning (dev) in hphp/runtime/CMakeLists.txt:
  Policy CMP0022 is not set: INTERFACE_LINK_LIBRARIES defines the link
  interface.  Run "cmake --help-policy CMP0022" for policy details. 

```

Related information about the bug in the cmake maling list
http://thread.gmane.org/gmane.comp.programming.tools.cmake.user/48007

**Comment by burner1024** [comment]
So... why is this closed? CMake version is still not bumped, so the build fails (3.4 and 3.5 fail, 3.3 works).
