### ISSUE TITLE
bit xor on strings leaks memory

### ISSUE THREAD

**Issue by adrianheine** [facebook/hhvm#3740]
The following script echoes `2097152` (2MB) for me with hhvm 3.2, while zend gives `904` (1KB).
```
<?php

$baseMemory = memory_get_usage();

$algo = 'sha256';
$iterations = 40000;

$ctx = hash_init($algo, HASH_HMAC, "\0");
$xor = hash_final($ctx);
for ($j = 1; $j < $iterations; $j++) {
  $ctx = hash_init($algo, HASH_HMAC, "\0");
  $xor ^= hash_final($ctx);
}

echo memory_get_usage() - $baseMemory, "\n";
```

This is a simplified excerpt of `hash_pbkdf2` calling `hash_hmac`. This is an issue for MediaWiki, since it uses pbkdf2 by default for password hashing.

**Comment by mariushoch** [comment]
This is actually hitting us in production: https://phabricator.wikimedia.org/T78727 (That's a function that merges several account on various wikis into one global account... to do that, the user gives the password for all these accounts and we then compare that with the account passwords in a loop).

**Comment by swtaarrs** [comment]
I verified that this is a real leak - when I make the loop infinite, memory usage does keep going up indefinitely. I'll see what I can figure out.

**Comment by swtaarrs** [comment]
Fix should be out soon. The leak was actually in `operator ^=` on strings and had nothing to do with hashing.

**Comment by reeze** [comment]
:+1:

**Comment by adrianheine** [comment]
Great, thanks :)
