### ISSUE TITLE
Hack style guide and conformance checker for code within HHVM

### ISSUE THREAD

**Issue by rrh** [facebook/hhvm#3746]
Please publish a Hack language style/coding conventions guideline document,  paralleling what's in https://github.com/facebook/hhvm/blob/master/hphp/doc/coding-conventions.md for C++.  There are enough differences to warrant either a separate document, or separate parallel sections in the C++ document.

Please open source the Hack conventions checking tool that is behind phabricator, or else provide some service we can submit candidates to.   Doing so might save 1 or more rounds of review from OSS submissions.

**Comment by Orvid** [comment]
Hack formatter has been ready and in use for a while now, closing.

**Comment by fredemmott** [comment]
hh_format is unmaintained, and needs a rewrite :( it also doesn't comply with our guidelines.

**Comment by lexidor** [comment]
@fredemmott is `hackfmt` the reborn `hh_format`?
If yes, does this mean that the issue has been resolved?

**Comment by fredemmott** [comment]
Yep
