### ISSUE TITLE
session cleanup never occurs?

### ISSUE THREAD

**Issue by r3wt** [facebook/hhvm#3747]
Is there someway i can enable garbage collection for old sessions in hhvm? they seem to be persisting for months.

**Comment by SalmanKhan86** [comment]
delete these see_ files using find /tmp -name "sess_*" -cmin +24 -delete option is permanent soltion for this. pls suggest. there are lot of perf-15808.map files in /tmp dir how to handle this..and in my hhvm error log there are lot of eror like this [hphp] [16198:7f877bbff700:445:000001] [] \nFatal error: entire web request took longer than 45 seconds and timed out.

pls help me to resolve this
