### ISSUE TITLE
64-bit integer for filesize

### ISSUE THREAD

**Issue by schien-dong** [facebook/hhvm#3749]
The current PHP implementation uses a 32bit integer to describe file sizes. From PHP Documentation:

"Because PHP's integer type is signed and many platforms use 32bit integers, some filesystem functions may return unexpected results for files which are larger than 2GB."

HHVM runs on 64bit environments and there is no reason to restrict the file size to 2GB. Can we change the integer type so that files larger than 4GB can be finally uploaded directly?

**Comment by ethanjyx** [comment]
Has this been resolved? I am meeting the same issue now.

**Comment by paulbiss** [comment]
HHVM doesn't even have a 32bit integer size, so filesize is and has always returned a 64 bit integer. That being said, if your system stat() give st_size as a 32bit integer then you'll hit this issue.
