### ISSUE TITLE
HHVM 3.3.0-dev - [ERROR 3067] Failed to parse the XML resource

### ISSUE THREAD

**Issue by Macsch15** [facebook/hhvm#3751]
Hello,
I use Translations from Symfony 2 and xliff format for resource, but HHVM 3.3.0-dev (hhvm-nightly) throws errors in tests:

```
[ERROR 3067] Element '{http://www.w3.org/2001/XMLSchema}import': Failed to parse the XML resource 'file:////home/travis/build/Macsch15/Tricolore/library/Symfony/Component/Translation/Loader/schema/dic/xliff-core/xml.xsd'. (in in_memory_buffer - line 33, column 0)
```

https://travis-ci.org/Macsch15/Tricolore/jobs/35261477

On PHP 5.5, 5.6 and HHVM 3.2.0 works fine.

It's HHVM fault or... maybe Symfony?

**Comment by jrborbars** [comment]
Yes. HHVM 3.4.2 in arch linux and the problem has gone! Thanks!  The fix of @SeerUK works for me too!
