### ISSUE TITLE
How to load dynamic extensions?

### ISSUE THREAD

**Issue by GasimGasimzada** [facebook/hhvm#3769]
I am trying to add mongodb driver for hhvm. The zend compat mongodb is not loaded for some reasons (other zend_compat extensions are loaded), so I tried to go with mongofill. The installation went successful with no problem at all. However, I don't know how to add this to my configuration as an extension. I am using the INI version:

```
hhvm.dynamic_extension_path = "/etc/hhvm/ext"
hhvm.dynamic_extensions.mongo = mongo.so
```

When I check the loaded dynamic extensions, it shows nothing about mongo. I thought maybe `get_loaded_extensions` doesn't show dynamic extensions, so made a simple call:

```
$mongo = new MongoClient;
```

and got "class undefined: MongoClient ..."

My HHVM version is 3.4.0-dev. How can I load the extension using INI?

**Comment by bhargav3** [comment]
Nothing to preview
