### ISSUE TITLE
GMP missing 5.6 features

### ISSUE THREAD

**Issue by MaideCa** [facebook/hhvm#3791]
The following changes are missing from our implementation of GMP that were added in PHP 5.6:
- GMP object instead of resource
- Warnings raised for bad rounding modes
- Some functions previously returned integers if integers were passed in; we should always return a GMP object on succesful returns
- GMP object arithmatic, bitwise, and comparison overloading

I plan to be working on these features in my spare time over the next week.  The first three bullets are easy, but I'm currently unsure about the class overloading.  I guess I'll cross that bridge when I get there...

**Comment by Orvid** [comment]
Ping?

**Comment by paulbiss** [comment]
The comparison overloads can probably be done atop the support that already exists for SimpleXML, the rest of the overloads will definitely require changes inside the JIT. It's unlikely these changes would negatively impact performance, but deciding how general they need to be is going to be an important conversation.

**Comment by lexidor** [comment]
The following have been fixed:
 * GMP object instead of resource
 * Warnings raised for bad rounding modes

I don't know which functions are returning ints, so I can't validate that.

`<` and `>` are not overloaded for GMP objects and normal objects rules (neither is greater than the other) applies.

**Comment by fredemmott** [comment]
Overloading is not going to be added, and will hopefully be removed from other existing cases.

int stuff: extremely unlikely to be addressed as part of the existing API: it'll be a breaking change, and we'd probably prefer to introduce a new hack-style API then kill the PHP one than introduce a breaking change like that to the PHP API (unless prompted by language-level issues).
