### ISSUE TITLE
dyld: Library not loaded: libjemalloc.1.dylib when executing hhvm binary on Mac OS X

### ISSUE THREAD

**Issue by c9s** [facebook/hhvm#3792]
Platform: Mac OS 10.9
Branch: HHVM-3.2

I used otool to list the library, and found the path of libjemalloc is wrong:

```
otool -L hphp/hhvm/hhvm | grep jema
	libjemalloc.1.dylib (compatibility version 0.0.0, current version 0.0.0)
```

which should be `/opt/local/lib/libjemalloc.1.dylib`. I use:

```
install_name_tool -change libjemalloc.1.dylib /opt/local/lib/libjemalloc.1.dylib hphp/hhvm/hhvm
```

To fix the library path, then it works.

**Comment by Orvid** [comment]
Is this still an issue?

**Comment by c9s** [comment]
No thanks!

Orvid King <notifications@github.com> 於 2016年4月30日 星期六寫道：
