### ISSUE TITLE
DateTimeImmutable::setDate() should allow string arguments

### ISSUE THREAD

**Issue by evert** [facebook/hhvm#3796]
Reproduction steps:

``` php
  $dt = new DateTimeImmutable('now');
  $dt->setDate('2015','1', '1');
```

In vanilla php this is successful, but in hhvm this error is emitted:

```
Fatal error: Argument 1 passed to DateTimeImmutable::setDate() must be an instance of int, string given in /in/acak4 on line 4
```

**Comment by evert** [comment]
Any news on this?

**Comment by Hywan** [comment]
@evert: :+1:, no news?

**Comment by paulbiss** [comment]
I had something to fix this but haven't had a chance to get back to it yet.

**Comment by Hywan** [comment]
\o/

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

In [hhvm 4.3.0](https://hhvm.com/blog/2019/04/30/hhvm-4.3.0.html) the failure mode of calling a built-in function with the wrong types has been changed to be a TypeError. This matches the user defined Hack functions. It is not possible to get the PHP coercion behavior. PHP support was dropped with the release of [hhvm 4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html) and Hack does not coerce typehints.
