### ISSUE TITLE
ReflectionParameter::isDefaultValueConstant() is missing

### ISSUE THREAD

**Issue by BenMorel** [facebook/hhvm#3812]
As mentioned in #1600, this method is missing. (#1600 was addressing this issue, but was closed because too broad.)

**Comment by BenMorel** [comment]
Any update on this one?

**Comment by BenMorel** [comment]
Up!

**Comment by Orvid** [comment]
This sounds like it was implemented.

**Comment by paulbiss** [comment]
Doesn't appear to have been merged though

**Comment by JoelMarcey** [comment]
Implemented now.

**Comment by BenMorel** [comment]
@JoelMarcey Thank you, what's the fix version for this bug? The latest release, 3.11.1 is still affected.

**Comment by SiebelsTim** [comment]
@BenMorel This was just three days ago
https://github.com/facebook/hhvm/commit/80d73f5fab5a00aead4fcba630c4162750ebad26

You can expect it to be in 3.11.2

**Comment by fredemmott** [comment]
Is there a PR for the 3.11 branch? At the moment it's not in there

**Comment by SiebelsTim** [comment]
@fredemmot Is 3.11 going to be 3.11.2, without a new cut? 
Then it's not going to be in 3.11.2 :D

**Comment by fredemmott** [comment]
We re-cut for y releases, z releases are cherry-picks on top of the HHVM-x.y branch

**Comment by JoelMarcey** [comment]
I didn't think this was 100% necessary for a z-release cherry-pick. I was thinking this would go into 3.12. Has 3.12 been cut?

**Comment by fredemmott** [comment]
Yep, cut on the 18th: https://docs.hhvm.com/hhvm/installation/release-schedule

**Comment by JoelMarcey** [comment]
So, I would be in favor of either cherry-picking into 3.12 or waiting until 3.13. I think we have enough to deal with in 3.11.x at this point.

**Comment by bobthecow** [comment]
So if I'm matching against a version number for this, what version should I be using?

**Comment by JoelMarcey** [comment]
Right now there is nor version number to match. You need to download the nightlies (http://dl.hhvm.com/) or build from `master`.
