### ISSUE TITLE
mPDF - Fatal error: Switch statements may only contain one default: clause 

### ISSUE THREAD

**Issue by ghost** [facebook/hhvm#3822]
\nFatal error: Switch statements may only contain one default: clause in mpdf56/mpdf.php on line 1419

And there is my problem, I can't find out what route should I use.

**Comment by ig-pritam** [comment]
I have a silmilar problem.Is there any solution for this??

**Comment by romadhonbyar** [comment]
@ig-pritam change PHP 7.* to PHP 5.6

![selection_033](https://user-images.githubusercontent.com/606799/36084904-15e9ae28-0ff4-11e8-8be4-e7fe680d1276.png)

**Comment by fredemmott** [comment]
Sorry, this behavior won't be changed:
 - it was a bug in PHP to allow this
 - it was a bug in PHP applications to depend on this; two defaults in a switch statement does not make sense
 - [HHVM will not support PHP5 in future releases](https://hhvm.com/blog/2018/01/16/hhvm-3.24.html)
