### ISSUE TITLE
Unattended Upgrades

### ISSUE THREAD

**Issue by jg-development** [facebook/hhvm#3861]
Hi,

I am trying to get hhvm automaticly upgraded with unattended upgrades. However it does not work.
I am working with ubuntu 14.04 and using the "50unattended-upgrades" file.
The origin:archive from hhvm is unknown to me. Does anybody knows the correct combination?
        "HHVM trusty-main";
        "HHVM trusty-stable";
        "HHVM stable";
        "HHVM trusty";
does not work.
The http://dl.hhvm.com/ubuntu/dists/trusty/Release only shows the origin, but not the archive. Is it possible to integrate hhvm to unattended upgrades?

Greetings Jan

**Comment by paulbiss** [comment]
Hmm, this probably would be a better question for someone more familiar with debian packaging.
