### ISSUE TITLE
Nginx fastcgi_cache not working with HHVM

### ISSUE THREAD

**Issue by ADDISON74** [facebook/hhvm#3879]
I am using Magento for a shopping cart. After many issues with Turpentine I decided to give a try to FASTCGI_CACHE feature in Nginx server. I followed the instructions from here:

http://reviewsignal.com/blog/2014/06/25/40-million-hits-a-day-on-wordpress-using-a-10-vps/

HHVM is not working with FASTCGI_CACHE. Nothing happens, my configuration in HHVM is checked. I switched back to PHP5-FPM/PHP5 and FASTCGI_CACHE is working without any issues. Comparing with Varnish, Fastcgi boosted 10 times the results, it is a wise decision to leave Varnish for Nginx with FASTCGI_CACHE. 

I used HHVM with Varnish and I would like to keep HHVM as PHP interpreter. I like it. Unfortunately I cannot use it with FASTCGI_CACHE. Can you help me? Is it a feature you plan to add to HHVM? Really this boosts webserver performance. Let me give you an example:

Hardware
Processor: 4 Cores x 4 GHz AMD
RAM: 8 GB 1600 MHz
Storage: HDD SATA-3

ab -n 1000 -c 100 http://IP_ADDRESS/

- PHP-FPM + PHP5.5 w/ Zend OpCache + Lesti::FPC : 28 requests/sec
- HHVM + Lesti::FPC: 72 requests/sec
- VARNISH + HHVM + TURPENTINE: 1200 requests/sec
- NGINX w/FASTCGI_CACHE + PHP-FPM + PHP5.5 w/ Zend OpCache + Lesti::FPC: 11709 requests/sec

If HHVM is not working with FASTCGI_CACHE I have to abandon it. Please help.

**Comment by creativeprogramming** [comment]
I'm also unable to get fastcgi_cache working with hhvm. It works fine with php5-fpm but i'm getting always a MISS with hhvm

**Comment by creativeprogramming** [comment]
I also had problems, but now it works fine...

In my case the miss it was due to this:

```
fastcgi_buffering off;
fastcgi_request_buffering off;
```

Buffering should be **on ** instead to let fastcgi cache work well

**Comment by creativeprogramming** [comment]
check if you have 

#fastcgi_buffering off;
or
#fastcgi_request_buffering off;

for me the issue was due to buffering turned off

**Comment by paulbiss** [comment]
Sounds like this may be a configuration issue. If anyone can come up with an isolated repro comment here so we can investigate.
