### ISSUE TITLE
Variadics do not support by-reference capture

### ISSUE THREAD

**Issue by Majkl578** [facebook/hhvm#3888]
It should be possible to pass variadic function's parameters by reference.
PHP RFC: https://wiki.php.net/rfc/variadics#by-reference_capture

``` php
function test($foo, &...$bar) {
    var_dump(func_get_args());
}

$a = 123;
$b = 234;
$c = 345;
test(1, $a, $b, $c);
```

$ hhvm test.php
Fatal error: syntax error, unexpected ..., expecting T_VARIABLE in /www/temp.php on line 3

```
```

```
$ php test.php
array(4) {
  [0] =>
  int(1)
  [1] =>
  int(123)
  [2] =>
  int(234)
  [3] =>
  int(345)
}
```

http://3v4l.org/LTG8J

**Comment by theodorejb** [comment]
This still results in a fatal error:

> Fatal error: Parameter $bar is both variadic and by reference; this is unsupported in /in/1qOVG on line 3

See https://3v4l.org/1qOVG.
