### ISSUE TITLE
Make unknown attributes that start with "__" a runtime and typechecker error

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#3889]
As __Foo is reserved for HHVM internals, we should be able to maintain a list of valid ones. Raising an error would make typos easier to debug/not be silently ignored.

**Comment by simonwelsh** [comment]
This is done in Hack, so also done in HHVM if calling out to the type checker is enabled.

**Comment by paulbiss** [comment]
Probably not worth it to deal with the runtime side of this, as there many of these attributes are only meaningful to hh_client anyway.
