### ISSUE TITLE
32-bit assumptions about location of g_destructors

### ISSUE THREAD

**Issue by rrh** [facebook/hhvm#3896]
There are several asserts checking that the location of g_destructors is in an address in the low 31 bits:
  https://github.com/facebook/hhvm/blame/master/hphp/runtime/vm/jit/code-gen-helpers-x64.h#L216
These assumptions are not true if hhvm is compiled (ubuntu 14.04, gcc 4.9.1) with the -fPIE (Position independent executable) flag, in which case the data segment is mapped to some location in massively high memory.

There may be more assertions like this; the execution stops at the first failure!

The only reason why I ended up using -fPIE was to use gcc 4.9.1 -fsanitize=thread (See https://code.google.com/p/thread-sanitizer/wiki/CppManual) as an online detection for data races.

**Comment by Orvid** [comment]
We require that the destructor table be in the lower 4gb of memory, and have a check in place to give an appropriate error if it isn't. Closing.
