### ISSUE TITLE
Apparent incompatibility with XenForo/Zend

### ISSUE THREAD

**Issue by Zenexer** [facebook/hhvm#3905]
XenForo and HHVM don't seem to work well together, at least in my environment.  I swapped PHP-FPM out for HHVM; most pages work, but `/admin.php` just loads forever until Nginx gives up.  HHVM isn't producing any logs on the matter, even with `hhvm-dbg`.

**Comment by PunKeel** [comment]
Hi,

I'm having a stacktrace (and HHVM stopping working) with Apache 2.2, Debian 7.8, and Xenforo 1.4.3.

Here is the stacktrace: http://pastebin.com/rCwuG1F4

Thanks in advance,

**Comment by steelbrain** [comment]
@PunKeel That is a bug in `mysqli_stmt->fetch`, You should open a separate issue for it.

**Comment by PunKeel** [comment]
Done, thanks @steelbrain #4845
