### ISSUE TITLE
test/slow/ext_icu/uspoof.php consistently fails

### ISSUE THREAD

**Issue by rrh** [facebook/hhvm#3925]
On my ubuntu 14.04 system this test
   test/run test/slow/ext_icu/uspoof.php
consistently fails.

I have run
  sudo locale-gen zh_CN.utf8 
which is part of how FB's travis jig https://github.com/facebook/hhvm/blob/master/.travis.yml#L22 is setup.

I'm told that all tests pass on FB's travis system, so presumably this test passes there, so I presume there's something missing from my environment.  Perhaps I need another locale that's not documented in travis.yml?

Where did the test code
  https://github.com/facebook/hhvm/blob/master/hphp/test/slow/ext_icu/uspoof.php
come from?

However I'm wondering if the test itself is bogus.
  https://github.com/facebook/hhvm/blob/master/hphp/test/slow/ext_icu/uspoof.php#L120
is a test that 2 Han Chinese characters are "suspiciously" present when SINGLE_SCRIPT semantics holds sway.  Both of these characters  http://www.fileformat.info/info/unicode/char/8005/index.htm and http://www.fileformat.info/info/unicode/char/5fcd/index.htm are labeled as "Han Chinese", so I'd think (I am not an i18n person) they could co-exist without suspicion.

This piece of php code also fails on ubuntu 14.04's default php5-intl installation, eg php5.5.9 with intl support ICU version 52.1.

**Comment by vielmetti** [comment]
This test fails on aarch64 with Ubuntu 16.04, with ICU 55:

```
hhvm@ed-2a-sjc-dcos:/home/src/github.com/facebook/hhvm/hphp$ ldd hhvm/hhvm | grep -i icu      
        libicui18n.so.55 => /usr/lib/aarch64-linux-gnu/libicui18n.so.55 (0x0000ffffb5240000) 
        libicuuc.so.55 => /usr/lib/aarch64-linux-gnu/libicuuc.so.55 (0x0000ffffb50a2000)      
        libicudata.so.55 => /usr/lib/aarch64-linux-gnu/libicudata.so.55 (0x0000ffffb2291000)
```
