### ISSUE TITLE
hhvm's XDebug and the GEBEN debugging plugin can get into a state where hhvm reports thousands of identical errors

### ISSUE THREAD

**Issue by mattflaschen** [facebook/hhvm#3926]
I've been testing HHVM with remote XDebug and Emacs's [GEBEN plugin](https://code.google.com/p/geben-on-emacs/) (the client/IDE side of the protocol).  I've used GEBEN successfully with stock XDebug in the past.

It's not as reliable in general (e.g. it sometimes displays the line of an outer function instead of the line where you are, and commands sometimes apparently take retrying to work), but the specific bug I'm reporting here is where the error reporting hits a loop.

I've seen this with both "parse error in command" and "command is not available".

I think this might be some bad interaction where HHVM isn't doing what GEBEN expects; GEBEN might be retrying in a loop, or HHVM might just be getting caught in its own loop (not sure).

So e.g. Emacs displays this as:

Command error: parse error in command [60013 times]

(meaning that output was put into Emacs's message buffer 60,013 times) or:

Command error: command is not available [50061 times]

I've specifically seen this with geben-run-to-cursor (telling the debugger to run until you get to the current line).  I think this may be because HHVM isn't expecting this at the current time (possibly because of the above-mentioned confusion about what line/scope it's on).

**Comment by Orvid** [comment]
Any updates?

**Comment by flinttechnology** [comment]
A related compatibility issue seems to be that hhvm responds with filename="systemlib.phpxdebug" during debugging when an xdebug_break() statement is reached:

```
(cmd) stack_get -i 30019
<?xml version="1.0" encoding="iso-8859-1"?>
<response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="stack_get" transaction_id="30019">
  <stack where="xdebug_break" level="0" type="file" filename="systemlib.phpxdebug" lineno="18"/>
  <stack where="include" level="1" type="file" filename="file:///var/www/2.0.4/lib/internal/Magento/Framework/App/Http.php" lineno="18"/>
  <stack where="Composer\Autoload\includeFile" level="2" type="file" filename="file:///var/www/2.0.4/vendor/composer/ClassLoader.php" lineno="412"/>
  <stack where="Composer\Autoload\ClassLoader::loadClass" level="3" type="file" filename="file:///var/www/2.0.4/vendor/composer/ClassLoader.php" lineno="301"/>
  <stack where="Magento\Framework\ObjectManager\Factory\AbstractFactory::createObject" level="4" type="file" filename="file:///var/www/2.0.4/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php" lineno="115"/>
  <stack where="Magento\Framework\ObjectManager\Factory\Compiled::create" level="5" type="file" filename="file:///var/www/2.0.4/lib/internal/Magento/Framework/ObjectManager/Factory/Compiled.php" lineno="88"/>
  <stack where="Magento\Framework\ObjectManager\ObjectManager::create" level="6" type="file" filename="file:///var/www/2.0.4/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php" lineno="57"/>
  <stack where="Magento\Framework\App\Bootstrap::createApplication" level="7" type="file" filename="file:///var/www/2.0.4/lib/internal/Magento/Framework/App/Bootstrap.php" lineno="233"/>
  <stack where="{main}" level="8" type="file" filename="file:///var/www/2.0.4/pub/index.php" lineno="36"/>
</response>

```

This causes an immediate "can not open file" error in the next message, when geben attempts to retrieve the file "systemlib.phpxdebug".

```
(cmd) source -i 30020 -f systemlib.phpxdebug
<?xml version="1.0" encoding="iso-8859-1"?>
<response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="source" transaction_id="30020">
  <error code="100">
    <message>can not open file</message>
  </error>
</response>

```

**Comment by Orvid** [comment]
It wouldn't be able to retrieve that file anyways because that is the systemlib that is embedded in the HHVM binary.

**Comment by flinttechnology** [comment]
Yes, is seems hhvm is not xdebug compliant.

The filename attribute should contain a valid "file URI", as stated by the xdebug specification (https://xdebug.org/docs-dbgp.php#stack-get).

**Comment by mattflaschen** [comment]
@Orvid I think the intended behavior for xdebug_break is to break on the line where xdebug_break() is present.  So it should return the file that calls xdebug_break(), rather than needing to return a file inside HHVM.

**Comment by ebluestein** [comment]
Closing this issue since XDebug is no longer supported.
