### ISSUE TITLE
Typechecker should raise syntax error for 'new Foo()->bar()'

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#3946]
Bad code:

``` PHP
<?hh

class Foo {
  public function bar() {
  }
}

function main() {
  new Foo()->bar();
}
main();
```

```
[fredemmott@devbig076 ~/hhtest] hh_client
No errors!
[fredemmott@devbig076 ~/hhtest] hhvm test.php

Fatal error: syntax error, unexpected T_OBJECT_OPERATOR in /home/fredemmott/hhtest/test.php on line 9
```

Changing to `(new Foo())->bar()` fixes it at runtime

**Comment by mwpastore** [comment]
Same with Collection literals followed by method calls, i.e. this doesn't work and the typechecker doesn't catch it:

    Map {}->addAll($pairs);

The solution is to change it to this:

    (Map {})->addAll($pairs);

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Both problems addressed in this issue have been resolved.
`new Obj()->method()` is a typechecker error and `Map{}->at(1)` calls this `at()` method on the newly created `\HH\Map<Tk, Tv>`.
