### ISSUE TITLE
HHVM slowly leaking memory

### ISSUE THREAD

**Issue by elpescador-nl** [facebook/hhvm#3958]
Joomla! runs fine and fast practically, however there is a memory leak which makes it unuseable. Is there any known issue about this?

I did some testing with apache2-utils: `ab [url] -n 1000 -c 1`

**HHVM Version**
HipHop VM 3.3.0 (rel)
Compiler: tags/HHVM-3.3.0-0-g0a3cfb87b8a353fc7e1d15374f4adc413e37aba9
Repo schema: 9a391d9a03e15fccba1cde6d35c05b7cdd380238
Extension API: 20140829

Platform is **Ubuntu 14.04 LTS**

**Joomla version**
Joomla! 3.3.6 Stable (based on Joomla Platform 13.1.0 Stable)
Settings tested:
Caching: off; file-cache
Database API: mysql and mysqli

**nginx**
fastcgi_keep_conn on;
fastcgi_pass unix:/var/run/hhvm/hhvm.sock;
fastcgi_buffers 8 256K;
fastcgi_buffer_size 128K;

**Comment by hgati** [comment]
setting server.ini
hhvm.enable_obj_destruct_call = 1

all php framework's memory leak removed.

**Comment by jaredkipe** [comment]
@hgati Nope, I have "hhvm.enable_obj_destruct_call = 1" in my server.ini and I still leak ~4GB per day.
