### ISSUE TITLE
array_pop is untyped

### ISSUE THREAD

**Issue by y-uti** [facebook/hhvm#3960]
array_pop possibly invalidates shape objects, but that isn't checked by hh_client.
Following code illustrates the problem. hh_client reports no errors, but results fatal error if executed.

```
<?hh // strict
type myshape = shape('foo' => int);
function getFoo(myshape $s): int { return $s['foo']; }

function main(): void {
    $s = shape('foo' => 1);
    array_pop($s);
    print getFoo($s) . "\n";
}
```

**Comment by lexidor** [comment]
`\array_pop()` is still untyped. The case you showed with passing a shape is still a violation of the expectations of the typechecker. Array pop now takes its argument as inout. The typechecker now acknowledges that the argument may be modified any which way, and models this with the TAny type `_`. The hsl has `C\pop_back()` for the maybe empty case and `C\pop_backx()` for the non empty case. These functions are well typed.
