### ISSUE TITLE
Should be able to call no-arg functions at toplevel in strict Hack

### ISSUE THREAD

**Issue by steelbrain** [facebook/hhvm#3964]
I am using the code that's kinda like the one below, hh_client is throwing an error `Remove all toplevel statements except for requires`. As you can see there's no top level code except for `main()`. I got the idea of the main function from the [hack manual](http://docs.hhvm.com/manual/en/hack.unsupportedphpfeatures.toplevelcode.php).

``` php
<?hh //strict
class TestClass{
    public static function init():void{
        echo "Hey, I reached here";
    }
}
function main():void{
    TestClass::init();
}
main();
```

any ideas how to fix it?

**Comment by bbulkow** [comment]
+1 this is annoying and "silly". I write a lot of single-file programs and I'd like to use // strict.

**Comment by fredemmott** [comment]
As for why: it's not generally possible to make top-level code 'safe' due to things like how locals are sort-of global, and strict mode does not allow any unsafe code.

If we just allowed it, the typechecker would be allowing code it doesn't fully understand, which would go against the usual expectation of strict mode. Whatever's done to address this needs to be more involved than simply removing the restriction.

**Comment by jwatzman** [comment]
I //think// @int3 is going to allow a single function call at toplevel, which should be safe. (We talked about it last week at least.) That would solve a large part of the problem here without being unsafe.

**Comment by bbulkow** [comment]
How's about this. Main can be a well defined class or function. If there is a class that matches the signature, call it. In some sense, that's what every language does. Java has a lot of problems with this exact launching problem, because they're not willing to have a "sensible default policy" but that doesn't hurt anything about type checking.

**Comment by jwatzman** [comment]
I'd rather just allow calling functions with no arguments at toplevel -- it's a lot more familiar to existing PHP devs, it doesn't require changes to the runtime, and I also always found the magic `public static void main` of Java too, well, magical and confusing.

**Comment by fredemmott** [comment]
With no-args, how should access to $_SERVER, $_GET, $_POST managed while still staying fully-strict?

**Comment by jwatzman** [comment]
@fredemmott one problem at a time ;)

**Comment by fredemmott** [comment]
Is there a plan to solve that? I don't see how this would be useful otherwise - with no access to request URI, cookies, or get/request parameters, the kind of sites that can be made will be extremely limited.

**Comment by jwatzman** [comment]
Not imminently, no, though we should at some point. Current best suggestion is to write partial-mode wrappers that do type conversion and then return the right type into strict mode, e.g., `Request::getInt('uid')` or similar.

**Comment by fredemmott** [comment]
If we still require partial, the no-arg approach doesn't feel like it gains much - just one fewer partial file, but at the cost of dictating a certain design; for example, this would effectively deprecate this style:

```Hack
main(new Map($_SERVER), new Map($_GET));
```

... but this style would actually need less partial code.

**Comment by Orvid** [comment]
Perhaps a single argument to main which encapsulates the request variables, as well as the arguments if the script was run from the command line? Would salso need to contain whether or not it actually was run from the command line.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

In hhvm [3.27.3 and 3.28.2](https://hhvm.com/blog/2018/09/28/hhvm-3.28.2.html) the `__Entrypoint` attribute was added to address this issue.
In more recent versions of hhvm, the spelling changed to `__EntryPoint`.

```HACK
<<__EntryPoint>>
function main(): void {
  echo 'Hello World';
}
```
