### ISSUE TITLE
RFC: Add a "default" keyword for parameters to Hack

### ISSUE THREAD

**Issue by simonwelsh** [facebook/hhvm#3973]
This idea is a potential solution for a problem that came up in IRC. It's loosely based on a PHP RFC that I can't find.

My idea is to allow providing `default` as the default value for function parameters, instead of using `null`. This is to separate the value used to designate a default value from the value used to designate an error return.
### Code example

``` php
function someFunc(int $value, int $base = default): int {
  if ($base === default) {
    $base = strlen((string)$value);
  }
  return $base * $value;
}

function otherFunc(mixed $foo): ?int {
  if (is_scalar($foo)) {
    return intval($foo);
  }
  return null;
}

var_dump(someFunc(2, default));
var_dump(someFunc(3, otherFunc([])));
```

The typechecker will now force you to handle the error case, whereas, if `$base` had a `null` default, it would go along and do whatever the default is. The programmer is unlikely to have thought about this case, so it is probably not the behaviour they want.
### Limitation of token usage

`default` can only be able to be used like this
- In a comparison statement inside a function body;
- As the expression for a case statement;
- As the default value for a function parameter; or
- Explicitly passed as an argument to a function.

Using it as a value anywhere else will by a syntax error. As `default` cannot be currently used in any of these places, there shouldn't be any ambiguity introduced between using it as a value and designating the default block in a `switch` statement.
### Possible implementation details

A value of `default` will be false-y.

Most of the checking will be done by the type checker, where `default` will be handled like `null` (in that it must be explicitly checked for) with the added caveat that if a variable could still be `default`, it cannot be passed to another function.

To make implementation easier, `default` could be silently turned into `null` by the runtime. However, this would mean that `default` cannot be used with nullables or `mixed`. Alternatively, `KindOfDefault` could be introduced to have it be separate from `null`.

If another name for the token is picked, that is fine. Please don't bikeshed over that until the technical merits have been discussed though :)

**Comment by azjezz** [comment]
i personally agree with @TheRyanHowell here, i don't see what difference would `default` make than just using nullable ( or maybe `nullable` types didn't exists in 2014 ? :laughing: ) : 
```hack
function someFunc(int $value, ?int $base = null): int {
  if ($base === null) {
    $base = strlen((string)$value);
  }
  return $base * $value;
}

function otherFunc(mixed $foo): ?int {
  if (is_scalar($foo)) {
    return intval($foo);
  }
  return null;
}

var_dump(someFunc(1));
var_dump(someFunc(2, null));
var_dump(someFunc(3, otherFunc([])));
```

**Comment by simonwelsh** [comment]
`null` is a valid value with its own meaning. It's the same reason why shapes have nullability and optionality being separate.

This is solved by default expressions though.

```hack
function someFunc(int $value, int $base = \strlen($value)): int {
```

**Comment by fredemmott** [comment]
Hmm, we should perhaps think optionality now we have the nothing type

**Comment by simonwelsh** [comment]
Named parameters? :p
