### ISSUE TITLE
HHVM 3.3 crashes after many requests only in non-debug built

### ISSUE THREAD

**Issue by JohannesBeranek** [facebook/hhvm#3989]
gdb output:
```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe0bff700 (LWP 19995)]
0x00000000009a0300 in HPHP::Sweepable::SweepAll() ()
```

gdb-backtrace (non debug build):
```
#0  0x00000000009a0300 in HPHP::Sweepable::SweepAll() ()
#1  0x0000000000a3c028 in HPHP::MemoryManager::sweep() ()
#2  0x0000000000a71c08 in HPHP::hphp_session_exit() ()
#3  0x0000000000bc57b9 in HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJobImpl(std::shared_ptr<HPHP::FastCGIJob>, bool) ()
#4  0x0000000000bc59e8 in HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJob(std::shared_ptr<HPHP::FastCGIJob>) ()
#5  0x0000000000bc4958 in HPHP::JobQueueWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::Server*, true, false, HPHP::JobQueueDropVMStack>::start() ()
#6  0x000000000162fa97 in HPHP::AsyncFuncImpl::ThreadFunc(void*) ()
#7  0x00007ffff1230b50 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#8  0x00007ffff05ace6d in clone () from /lib/x86_64-linux-gnu/libc.so.6
#9  0x0000000000000000 in ?? ()
```

in debug build I always hit the assertion for m_keepConn before getting there

system is debian 7.6, kvm virtualized running apache + mod_php stable for > 2 years
hhvm is 3.3 from debian repo for wheezy

**Comment by griffin1987** [comment]
@paulbiss from what I have seen so far running different hhvm versions across different servers it could be an out of memory issue. Server has 32 gig of ram and about 100gig swap space, and it seems to happen after about 4 gig already, so if it really is a memory issue and not just some coincidence - are there configurable limits? Also, in case it's some configurable limit, shouldn't the log say something? And yes, I'm still hitting this up to 3.4.2

**Comment by Orvid** [comment]
This issue has been waiting for more info for more than 2 weeks. Closing for now, feel free to re-open it if you can provide more info.

https://github.com/facebook/hhvm/wiki/Human-Timeouts
