### ISSUE TITLE
Segmentation fault on var_dump() of simplehtmldom object

### ISSUE THREAD

**Issue by andrisi** [facebook/hhvm#3991]
When loading bigger files using the simplehtmldom library (http://simplehtmldom.sourceforge.net/) and then doing a var_dump on it will cause a Segmentation fault. Just do a "wget -o index.html http://index.hu" and then run the code below.

```
<?
require('lib/simplehtmldom/simple_html_dom.php');
$dom = file_get_html('index.html');
var_dump($dom);
```

**Comment by jurosh** [comment]
I have error: Fatal error: String length exceeded 2^31-2 on HipHop VM 3.7.0 using on project in Laravel...

**Comment by paulbiss** [comment]
The fix for this bug involved triggering a fatal error if the maximum size of the output buffer is exceeded.

**Comment by andrisi** [comment]
Perhaps printing nothing, or just stopping would be a more plesant fix, then throwing a fatal error on a simple var_dump? We shall do some (unreliable) check before every var_dump() to avoid fatal errors? But of course, using var_dump() in a real setting is uncommon.

**Comment by jurosh** [comment]
Ok, so my app is working now - I had missing storage folders for some caching... but it was really strange what it was doing...
