### ISSUE TITLE
debug_backtrace() do not show ob_* calls

### ISSUE THREAD

**Issue by nicolas-grekas** [facebook/hhvm#3997]
See: http://3v4l.org/P521O or this:

```php
function foo() { $GLOBALS['stack'] = debug_backtrace(); }
ob_start('foo');
ob_get_flush();
print_r($stack);
```

PHP mentions `ob_get_flush` in the stack, but HHVM don't.
This is especially annoying when considering that calling `ob_start` in a output buffering handler raises a fatal error: while in PHP I can prevent this by checking the stack trace, I have no way to work around the fatal error on HHVM (since 3.3 at least, the fatal wasn't there before).

**Comment by paulbiss** [comment]
Going to close this for now as something which we are unlikely to fix. The problem boils down to the way that we handle inlining, and would be fundamentally difficult to fix in a generic fashion. It may be worth revisiting in the future but no one currently has the bandwidth to fix this.
