### ISSUE TITLE
PDOException::$errorInfo not populated correctly for MySQL

### ISSUE THREAD

**Issue by deeky666** [facebook/hhvm#4003]
Since 3.3.0 [our test suite is failing again with HHVM](https://travis-ci.org/doctrine/dbal/jobs/38169316).
This is caused by `PDOExcpeiton::$errorInfo` not being populated correctly for error during connection establishment, I suppose.
HHVM does not provide the native server error code in `PDOExcpeiton::$errorInfo[1]`, the key does not even exist while the PHP implementation does provide the native error code.
This looks like a regression because it [was already working prior to 3.3.0](https://travis-ci.org/doctrine/dbal/jobs/37350367).

**Comment by jbruni** [comment]
I can say it has not been fixed yet, since I just got into the issue.

**Comment by jbruni** [comment]
I'm in a Debian system, and `hhvm --version` returns:

    HipHop VM 3.7.3 (rel)
    Compiler: tags/HHVM-3.7.3-0-g08c64d25f6c2cd316730b1d37db9eb33744cb306
    Repo schema: 6ba408ef27e1fc7820c8bd6352989f40c1acb812

Indeed, we expect to find the MySQL error code at `$pdoException->errorInfo`, but it is not available there.

But as said above, the error information is available through `$pdoInstance->errorInfo()`, which returns exactly the information we expect to find at `$pdoException->errorInfo`.

**Comment by jbruni** [comment]
So, the code which currently sets the `errorInfo` property of the `PDOException` is at [http/runtime/ext/pdo/ext_pdo.cpp, lines 489 to 491](https://github.com/facebook/hhvm/blob/c0776edffc1e977a82ed666b33f17fd9c7f8f8c5/hphp/runtime/ext/pdo/ext_pdo.cpp#L489-L491)

It is the value of the second parameter (`info`) passed to the `throw_pdo_exception` function.

Searching for `throw_pdo_exception` in the same file, we are able to see different strategies to provide the `info` value.

We can see it is always set to `uninit_null()` except at two occurrences: inside `pdo_raise_impl_error` and `pdo_handle_error` functions.

Inside `pdo_handle_error`, we have for **the third time** inside the same source code file, an attempt to get the `errorInfo` contents. Look:

1. [`errorInfo` being grabbed at `PDO::errorInfo`](https://github.com/facebook/hhvm/blob/c0776edffc1e977a82ed666b33f17fd9c7f8f8c5/hphp/runtime/ext/pdo/ext_pdo.cpp#L1454-L1484)

2. [`errorInfo` being grabbed at `PDOStatement::errorInfo`](https://github.com/facebook/hhvm/blob/c0776edffc1e977a82ed666b33f17fd9c7f8f8c5/hphp/runtime/ext/pdo/ext_pdo.cpp#L3121-L3143)

3. and, finally, [`errorInfo` being grabbed at `pdo_handle_error`](https://github.com/facebook/hhvm/blob/c0776edffc1e977a82ed666b33f17fd9c7f8f8c5/hphp/runtime/ext/pdo/ext_pdo.cpp#L542-L556)

It is easy to conclude that this implementation inside `pdo_handle_error` is not able to perform the same good job which `PDO::errorInfo` does.

#### Solution

I know PHP very well, but not C++. Someone must code the solution here, which is to substitute the failing code inside `pdo_handle_error` by a call to `PDO::errorInfo` (or at least base its code on the working code from it)

I'm not sure why `throw_pdo_exception` itself needs to receive the `info` parameter at all. Why can't it get rid of it and simply call `PDO::errorInfo` from inside, to get the `errorInfo` property for the exception?

**Comment by jbruni** [comment]
It worths quoting the PHP official documentation for PDOException:

> errorInfo
> Corresponds to PDO::errorInfo() or PDOStatement::errorInfo()

Source: http://php.net/manual/en/class.pdoexception.php

**Comment by jbruni** [comment]
I've provided more info. I hope someone can code the fix.

**Comment by jbruni** [comment]
@JoelMarcey - I've provided more info. I hope someone can code the fix. Thank you.

**Comment by deeky666** [comment]
@JoelMarcey I created a simple test case repository here: https://github.com/deeky666/hhvm-pdo-mysql-errorinfo

Also you can see it failing on [Travis](https://travis-ci.org/deeky666/hhvm-pdo-mysql-errorinfo)

If you need further information, just poke me. Thanks!

**Comment by JoelMarcey** [comment]
I am looking at this right now and will see if I can come up with a diff tonight or tomorrow.

**Comment by JoelMarcey** [comment]
Internal diff D2443664

**Comment by deeky666** [comment]
@JoelMarcey awesome, thx.

**Comment by jbruni** [comment]
:+1:

**Comment by zeroedin-bill** [comment]
:clap:
