### ISSUE TITLE
Status page not showing full urls and vhosts in drupal application

### ISSUE THREAD

**Issue by JohanTan** [facebook/hhvm#4004]
I set up the admin server for hhvm and start monitoring traffic. It seems to capture all requests, but not showing the correct results for some of the fields. Also the "URL" field shows "index.php" as opposed to the request uri, which makes it difficult to distinguish requests.
Example request:

```
{
"id": 139740523263744,
"tid": 6096,
"req": 72,
"bytes": 5725122,
"start": "Thu, 16-Oct-2014 16:23:05 PDT",
"duration": "0.428 seconds",
"memory": {
"current usage": 6421800,
"current alloc": 10485760,
"peak usage": 6421800,
"peak alloc": 10485760
},
"io": 0,
"mode": "process",
"url": "index.php",
"client": "",
"vhost": ""
}
```

Is there any special setting I need to turn on to get the fields displaying their real value?

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This issue applies to a very old built-in webserver which hasn't been shipped with hhvm for a long while.
