### ISSUE TITLE
HHVM crashes with BackupBuddy for WordPress

### ISSUE THREAD

**Issue by DanielJLewis** [facebook/hhvm#4005]
I'm running WordPress Multisite on HHVM, Nginx, and MariaDB. I have the BackupBuddy plugin for backup, but simply visiting a BackupBuddy page in WordPress will crash HHVM.

Maybe this is HHVM's fault, maybe it's BackupBuddy's. Whatever the case, I think there's something broken between the two and I wanted to report it. (I also posted this on the BackupBuddy forums.)

**Comment by Orvid** [comment]
This issue has been waiting for more info for more than 2 weeks. Closing for now, feel free to re-open it if you can provide more info.

https://github.com/facebook/hhvm/wiki/Human-Timeouts
