### ISSUE TITLE
socket_create() should return a Socket not a stream

### ISSUE THREAD

**Issue by clementhk** [facebook/hhvm#4036]
```
<?php
$c = socket_create(AF_UNIX, SOCK_STREAM, 0);
echo get_resource_type($c);

// returns stream, expecting Socket
```

**Comment by Orvid** [comment]
Well, this still exists, but a quick test is claiming that socket_create doesn't exist in PHP, which is odd:
https://3v4l.org/ZMVUk

**Comment by apeabody** [comment]
@Orvid Socket support is optional in PHP, my assumption is that it was purposely NOT included (--enable-sockets) in 3v4l.org given the opportunity for abuse.
