### ISSUE TITLE
hhvm basic soap error

### ISSUE THREAD

**Issue by purplegourd** [facebook/hhvm#4043]
In my project i have a script wich works with soap client from PHP,but in hhvm make fault error.
This line of code is a test demo  how I create the SoapClient object :

``` php
//client.php
<?php
$options = array (
        'location' => "http://10.201.20.22/server.php",
        'uri' => 'http://testuri/',
        'encoding'=>'UTF8',
);

try{
$client = new SoapClient ( NULL, $options );

$jj = $client->__soapCall('tttt', array(),$options);
}
catch (Exception $e){
    print_r($e);
}
print_r($jj);
```

``` php
//server.php
<?php
class server{
    public function tttt(){
        return   "alpha";
    }
}

$options = array(
        'uri' => 'http://testuri/',
        'encoding'=>'UTF8'
);
$server = new SoapServer(NULL, $options);

$server->setClass("server");

$server->handle();
```

```
//error as follow

SoapFault Object ( [faultcode] => HTTP [faultcodens] => [faultstring] => SOAP-ENV:Server [faultactor] => [detail] => [_name] => [headerfault] => [message:protected] => SOAP-ENV:Server [string:Exception:private] => [code:protected] => 0 [file:protected] => [line:protected] => [trace:Exception:private] => Array ( [0] => Array ( [function] => __dorequest [class] => SoapClient [type] => -> [args] => Array ( [0] => [1] => http://10.201.20.22/server.php [2] => http://testuri/#tttt [3] => 1 [4] => ) ) [1] => Array ( [file] => /usr/share/nginx/www/client.php [line] => 11 [function] => __soapcall [class] => SoapClient [type] => -> [args] => Array ( [0] => tttt [1] => Array ( ) [2] => Array ( [location] => http://10.201.20.22/server.php [uri] => http://testuri/ [encoding] => UTF8 ) ) ) ) [previous:Exception:private] => ) 
```

php environment is ok，print 'alpha'.

**Comment by rrh** [comment]
I also seem to have problems with the soap implementation.  I have a simple text book test that looks much like purplegourd's test included in this issue above.  The test only passes of I run the client side with zend-php5. I can run the server side with either hhvm or zend-php-5.6.

Running the hhvm client side (the buggy half of the combination) talking to hhvm server side shows that the response is:
$17 = { HPHP::KindOfString, "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<SOAP-ENV:Envelope xmlns:SOAP-ENV=\"http://schemas.xmlsoap.org/soap/envelope/\"><SOAP-ENV:Body><SOAP-ENV:Fault><faultcode>SOAP-ENV:Server</faultcode></SOAP-ENV:Fault></SOAP-ENV:Body></SOAP-ENV:Envelope>\n" }
without much information about the cause of the Fault.  

Swapping out the server side to use php5+httpd, the reported fault is back to hhvm client is:
{ HPHP::KindOfString, "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<SOAP-ENV:Envelope xmlns:SOAP-ENV=\"http://schemas.xmlsoap.org/soap/envelope/\"><SOAP-ENV:Body><SOAP-ENV:Fault><faultcode>SOAP-ENV:Client</faultcode><faultstring>looks like we got \"Body\" without function call</faultstring></SOAP-ENV:Fault></SOAP-ENV:Body></SOAP-ENV:Envelope>\n" }

While my note taking isn't great, I suspect based on other remembered chronologies that my test worked prior to commit 
 https://github.com/facebook/hhvm/commit/b9af980210301d79a86015e2d1e01f76831a5694
aka "convert soap to HNI" from 16Nov2014.

Unfortunately, I've not been able to build from source from this commit or the ones prior to it as a way to jog my memory.

**Comment by rrh** [comment]
I built HHVM from source for Branch HHVM-3.2 on ubuntu 14; HHVM-3.2 predates the conversion of soap to HNI.  Alas, unfortunately, HHVM-3.2 on ubuntu suffers from the illness regarding buggy access to ~/.hhvm.hhbc and I can not remember the workaround to make that annoyance go away.

**Comment by rrh** [comment]
I remembered how to disable the libsqlite3 from hhvm and use the system installed one instead.

HHVM-3.2 still shows the same problems as the one build from HEAD, namely the httpd/php5 soap client gins up a fault string thusly:
 <faultstring>looks like we got "Body" without function call</faultstring>

**Comment by jkuettner** [comment]
With version 3.7.1 we got the same problem with the soapclient

```
# hhvm --version
HipHop VM 3.7.1 (rel)
Compiler: tags/HHVM-3.7.1-0-g111c76378ac29aa8f25e6bb3c5f15b628e6bbea1
Repo schema: be14a89778f35ca7f7dd4aca7fff0793e8ae3334
```

```Fatal error: Uncaught SoapFault exception: [env:Sender] looks like we got "Body" without function call```

**Comment by moxx** [comment]
same issue here, i was wondering this bug is open since 2014?

-> ngrep show that the SOAP-ENV:Envelope is complete empty
T 0.0.0.0:34893 -> 0.0.0.0:xxx[AP]
  POST /soap HTTP/1.1..Host: someuri:xxx..Accept: */*..Accept-Encoding: deflate, gzip..SOAPAction: "urn::SomeCommand::call"..Content-Type: text/xml; charset=utf-8..Content-Length: 154....<?xml version="1.0" encoding="UTF-8"?>.<SOAP-ENV:Envelope xmlns:
  SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"><SOAP-ENV:Body/></SOAP-ENV:Envelope>.

$ hhvm --version
HipHop VM 3.7.3 (rel)

**Comment by Bogdaan** [comment]
same issue:
```
looks like we got "Body" without function call

# hhvm --version
HipHop VM 3.13.2 (rel)
Compiler: tags/HHVM-3.13.2-0-g64d6782149a51585d2bdc3b67dd399f2ef630517
Repo schema: 8c57ad2276433d9fafaf454878290df2e75e03a0
```
