### ISSUE TITLE
custom exception handler cannot use exit or die

### ISSUE THREAD

**Issue by Max-Sum** [facebook/hhvm#4055]
example:

    <?php
    set_exception_handler("custom_exception_handler");
    function custom_exception_handler($e){
        echo "foo";
        exit;
    }    

    throw new Exception("bar");
    ?>

will throw

            exception 'Exception' with message 'bar' in *****:8 Stack trace: #0 {main}

**Comment by paulbiss** [comment]
I believe this is due to a lack of implicit flush, you could try `hhvm.server.implicit_flush=true`

**Comment by Morik** [comment]
Seams to work.
But won't this worse the performance ?

**Comment by colin-kiegel** [comment]
implicit_flush is the right direction. If you flush() before exit() HHVM behaves the same as PHP. Interestingly this issue only occurs in callbacks registered with set_exception_handlers - not in regular code.

```php
<?php
set_exception_handler("custom_exception_handler");
function custom_exception_handler($e){
    echo "I need to get flushed!";
    flush(); // happens implicitly with PHP, but not with HHVM.
    exit;
}    

throw new Exception("bar");
?>
```

```php
<?php
    echo "I am flushed anyway";
    exit; // flush() implicitly called with PHP+HHVM
?>
```

**Comment by joshuaspence** [comment]
I'm curious, why was this issue closed?
