### ISSUE TITLE
Open-source idx implementation or remove from hhi

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#4071]
eg https://github.com/facebook/hhvm/commit/1c0fbc72ca6e3aac1bc4600a2df31e80849568e9

That change is only safe because idx() happens to be unused now in that subtree - otherwise, that change would have broken the test for anyone other than Facebook.

Should also check for other FBOnly functions

cc @jano, @jwatzman

**Comment by jwatzman** [comment]
cf. https://reviews.facebook.net/D38985

**Comment by jwatzman** [comment]
I have a diff up internally to do this, waiting on some cleanup in FB's frontend to percolate through.
