### ISSUE TITLE
Obey fastcgi aborts

### ISSUE THREAD

**Issue by simonwelsh** [facebook/hhvm#4077]
If an abort is sent over FastCGI (whether from a user cancelling the request or nginx timing it out), HHVM should abort the request.

**Comment by paulbiss** [comment]
This feature request is not actively being worked on. We would happily consider a pull request implementing it. If you plan to work on this issue let us know in the comments and we will re-open the issue and assign it to you. If you feel strongly that this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
