### ISSUE TITLE
Hack Strict mode is to Strict

### ISSUE THREAD

**Issue by dbergloev** [facebook/hhvm#4085]
First issue. I get why it does not allow code outside of functions and classes, I myself hate the fact that PHP is even capable of this. I don't even like multiple classes in the same file. However, we need to start somewhere. One class or function has to be initialized somewhere, and this is not possible in any correct way. If I am to be using HHVM and Hack, I want it set in Strict mode (If you are going to do something, don't cut corners). But I do not want to see an error all of the time, because I am initializing a main method. We need some clever way to do this, without allowing global code and without switching away from Strict mode in some main index file. 

second issue. I cannot use isset() or empty() in strict mode, not without errors. Why? PHP does not allow one to check something using $var==null, so how is one to check these things? 

Third issue. I get errors in Strict mode when accessing global variables like $_SERVER and such. These contains all information parsed by the web server. You cannot do much without the information attached, so why would this not be allowed in Strict mode? 

Besides these issues, which I cannot get around for now, I love this idea. I have been trying to get more type control and such added to PHP, but it was rejected. After working a few years with Android/Java, it is difficult to get back to PHP due to the lack of these things. It makes it easier to manage large code bases.

**Comment by luisaglez1** [comment]
"Uncovering the Truth: Is Your Partner Cheating on Facebook?"
Facebook, a platform built for connection, can sometimes become a space for secrecy. If you’re noticing changes in your partner’s online behavior, [hacking facebook](https://hackfreeonline.com/facebook/
) and it’s natural to wonder if something deeper is going on. While it’s important to approach the situation calmly and respectfully, there are subtle signs to watch for if you suspect infidelity.

The first sign may be a sudden increase in time spent on Facebook. If your partner becomes overly protective of their device or frequently hides their screen when you’re nearby, it could raise concerns. Additionally, changes to their profile—such as hiding friends lists, making posts private, or removing relationship statuses—can indicate a desire for more secrecy. [hacking facebook](https://hackfreeonline.com/facebook/
) and These changes alone don’t confirm infidelity but might warrant further observation.

Another red flag is unusual interactions. Watch for excessive engagement with a specific individual, such as frequent likes, comments, or shared posts that seem flirtatious. Deleted messages or cleared activity logs could also indicate that your partner is trying to hide something. Before drawing conclusions, it’s essential to communicate openly. Express your feelings and observations without being accusatory, as this can often lead to clarity and strengthen your relationship through honest dialogue. Trust and transparency are the cornerstones of any healthy partnership.
