### ISSUE TITLE
HHVM throws hphp_invoke error when using WP Migrate DB Pro in WordPress

### ISSUE THREAD

**Issue by joeguilmette** [facebook/hhvm#4097]
Error output in browser is `Status: 500 hphp_invoke`. Nothing in `/var/log/hhvm/error.log`. HHVM doesn't crash.

If I switch to php5-fpm and restart Nginx everything runs fine.

`$ hhvm --version` output:

```
HipHop VM 3.3.1 (rel)
Compiler: tags/HHVM-3.3.1-0-ge0c98e21167b425dddf1fc9efe78c9f7a36db268
Repo schema: f53e1743f31a2dee70c46aa66fb1b321c3e97c10
Extension API: 20140829
```

Running Ubuntu 14.04, with Nginx 1.6.2

**Comment by Orvid** [comment]
3.3 is unsupported. If this is still a problem, re-open the issue.
