### ISSUE TITLE
libxml memory model is fundamentally broken

### ISSUE THREAD

**Issue by atdt** [facebook/hhvm#4108]
In light of #2408, #3523, #4084, and #4086, I'm taking the liberty of promoting @fredemmott's prescient [comments](https://github.com/facebook/hhvm/issues/2408#issuecomment-45017422) to an issue:

> Our libxml memory model is fundamentally broken. We basically need an equivalent to php_libxml_node_object from php5, and both simplexml + domelement need to do their operations on this, and not own anything directly. I expect we'll keep having similar bugs until DOMElement and simplexml are rewritten to use a common refcounted internal libxml object (PHP5 does this), instead of the 'owner' concept.

**Comment by lokeshhctm** [comment]
is anybody working on this?

**Comment by lokeshhctm** [comment]
is there any update on this issue?

**Comment by paulbiss** [comment]
@lokeshhctm I'm looking at it, and I'll hopefully have something for it when my on-call ends. As a general rule we'll update the issue when we have news on a particular bug.

There are only so many of us, if something really matters to you often the best way to get it prioritized is to send us a pull-request with a fix. In this case, I'm on it, and will report back when I have some spare cycles to put a patch together. :)

**Comment by nokitakaze** [comment]
Another one piece of code to reproduce this bug: http://pastebin.com/Ka9ZpNgf
Heap dump before code http://pastebin.com/kxwHHnkn
Heap dump with running code http://pastebin.com/ZwiL7Wvh
Heap dump after running http://pastebin.com/f7idizDr
pprof http://img.kanaria.ru/storage/hhvm-heap-prof-2015-03-09-12-32.pdf

```
iteration #0 end
47 2Mb 3.6Mb 
8 2Mb 4Mb 
11 2Mb 4.4Mb 
14 2Mb 4.4Mb 
22 2Mb 4.4Mb 
30 2Mb 4.4Mb 
```

```
iteration #8377 end
47 4Mb 3309.2Mb 
8 4Mb 3309.2Mb 
11 4Mb 3309.6Mb 
14 4Mb 3309.6Mb 
22 4Mb 3309.6Mb 
30 4Mb 3309.6Mb 
```

With apache this iteration shows
```
iteration #8377 end
47 0.4Mb 0.5Mb 
8 0.4Mb 0.7Mb 
11 0.4Mb 0.7Mb 
14 0.4Mb 0.7Mb 
22 0.4Mb 0.5Mb 
30 0.4Mb 0.5Mb
```

More than that. After some limit HHVM start to echo data in random order. Like

```
iteration #321 4Mb 8376 end
47 4M8 3298.2Mb 
8 4M021 4Mb 4Mb 3309.b  4Mb 3303.3Mb 
22 4Mb 3284.4MbMb 0 4Mb 3303.3Mb b 0 4Mb 30 4Mb 330end
47 4Mb 3284.4Mb 
8 4Mb 3274.9Mb Mb 0 4Mb 4Mb 3309.14 4Mb 3284.8MbMb 0 4Mb 3303.7Mb 
30 4Mb 3224.7MbMb 0 4Mb 30 4Mb 330end
47 4Mb 3301.7Mb 
b 3235.8Mb 
8 4Mb 0 4Mb 4Mb 3309.14 4Mb 3304.1Mb 
22 4Mb 3285.2MbMb 0 4Mb 3304.1Mb b 0 4Mb 30 4Mb 330end
47 4Mb 3300.2Mb 
8 4Mb 3275.7Mb Mb 0 4Mb 4Mb 3309.14 4Mb 3304.5Mb 322 4Mb 3285.6MbMb 0 4Mb 3304.5Mb b 0 4Mb 30 4Mb 330end
47 4Mb 3285.6Mb 48 4Mb 3276.1Mb Mb 0 4Mb 4Mb 3309.14 4Mb 3285.9MbMb 0 4Mb 3302.9Mb 330 4Mb 3285.9MbMb 0 4Mb 30 4Mb 330end
47 4Mb 3302.9Mb 48 4Mb 3276.5Mb Mb 0 4Mb 4Mb 3309.14 4Mb 3303.3Mb
```

```
HipHop VM 3.5.1 (dbg)
Compiler: tags/HHVM-3.5.1-0-gb723e67c88bc008676687a04dff00db1faf250b3
Repo schema: a395edf8708632a3d09f417dbd9b1bd1d5b50bbe
```

**Comment by paulbiss** [comment]
https://reviews.facebook.net/D35439

**Comment by danslo** [comment]
@paulbiss You are awesome :+1:

**Comment by r3wt** [comment]
Thanks a million! been waiting for this

**Comment by atdt** [comment]
@paulbiss Kudos and thanks!
