### ISSUE TITLE
Takeover functionality is not supported with FastCGI

### ISSUE THREAD

**Issue by lavagetto** [facebook/hhvm#4129]
I was experimenting with the idea of having HHVM restarts being graceful without needing to drain traffic from the upstream HTTP proxy, and found the TakeOverFilename option, which seemed promising.

When I noticed it doesn't work, I also saw it didn't just because the new server tries to stop the old one by calling `/stop` on the admin server port, via http - as can be seen in `hphp/runtime/server/http-server.cpp` at line 549. Unluckily, the admin server now speaks fastcgi, not http, so what you get in the stdout of the "old" server is:

```
$ hhvm -m server -vServer.Type=fastcgi -vServer.Port=9000 -vServer.TakeoverFilename=/tmp/hhvm-takeover -vAdminServer.Port=9001
mapping self...
mapping self took 0'00" (2198 us) wall time
loading static content...
loading static content took 0'00" (0 us) wall time
page server started
admin server started
all servers started
FastCGI protocol: received an invalid record
FastCGI protocol: received an invalid record
FastCGI protocol: received an invalid record
FastCGI protocol: received an invalid record
FastCGI protocol: received an invalid record
FastCGI protocol: received an invalid record
FastCGI protocol: received an invalid record
FastCGI protocol: received an invalid record
```

and so on ad-libitum. The correct fix for this would be to make the takeover mechanism use the fastcgi protocol, while an hotfix would be letting people specify an AdminServer.HttpPort runtime option.

**Comment by atdt** [comment]
Ping :)

**Comment by dpaneda** [comment]
Having this fixed would be cool. The fastcgi mode is better but not able to use the takeover mechanism is reason enough to not use it.

**Comment by fredemmott** [comment]
@dpaneda: what server type are you currently using? We're planning to remove the libevent server in favor of proxygen

**Comment by fredemmott** [comment]
This is more likely to be solved now that we have a fully supported http-server again.

**Comment by dpaneda** [comment]
We are moving from hphp and we are not yet using hhvm on live. I've seen that the libevent mode is deprecated, leaving fastcgi as the only possible option i guess (not a lot of documentation on this). Is the proxygen option already available?

We need is some way to push a new release (we will probably use authoritative mode) and the takeover approach works just fine. Having proxygen or fastcgi working with takeover will be a way to do that.

Another (probably worse) way would be to allow the server to be created with SO_REUSEPORT option and leave the kernel do the hard work. If the server waits for the current requests to be terminated on a stop command, this could be an option too.

**Comment by fredemmott** [comment]
Yep, proxygen is included in HHVM 3.8 and above - just replace Server.Type=fastcgi with Server.Type=proxygen (or the ini equivalent) and you then have an HTTP server.

**Comment by jazzdan** [comment]
Take over would also be useful for us doing continuous deployment with repo auth mode in the future. 60+/deploys per day when you have to drain and restart the whole fleet isn't very feasible.

**Comment by dpaneda** [comment]
That's great news!, does the takeover works on proxygen mode?

**Comment by fredemmott** [comment]
Facebook uses it. I'm not aware of it being tested in an OSS build, but the differences are pretty minimal: proxygen-fb is a tiny subclass that just changes some logging and monitoring configuration.

**Comment by dpaneda** [comment]
Good to know is being used on live, I've tested it and works perfect. This is a double win for us because we also use the administrative port for stats, and having to use it with fastcgi protocol was also a problem.

Thank you very much for the fast reply :)

**Comment by paulbiss** [comment]
This feature request is not actively being worked on. We would happily consider a pull request implementing it. If you plan to work on this issue let us know in the comments and we will re-open the issue and assign it to you. If you feel strongly that this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
