### ISSUE TITLE
__ParamCoerce(Null | False) should Check Object Classes

### ISSUE THREAD

**Issue by paulbiss** [facebook/hhvm#4135]
Currently parameter coercion only checks DataType but does not inspect the class of objects, effectively ignoring this portion of the annotation.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

In [hhvm 4.3.0](https://hhvm.com/blog/2019/04/30/hhvm-4.3.0.html) the failure mode of calling a built-in function with the wrong types has been changed to be a TypeError. This matches the user defined Hack functions. PHP support was dropped with the release of [hhvm 4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html) and Hack does not coerce to make values match typehints.

`__ParamCoerceNull` is also not a thing anymore, I believe, but I can't find the commit that removed it.
