### ISSUE TITLE
"Port is not numeric" unbuntu 14.10

### ISSUE THREAD

**Issue by thanhliem89dn** [facebook/hhvm#4140]
I got this error when run phpmyadmin.

```
OS Ubuntu 14.10
HipHop VM 3.4.0-dev (rel)
Compiler: heads/master-0-g3202eed2084eea587992864b066e1c006cfc7eee
Repo schema: e639665f1ef3c6532e5bf47ddd92aabd553f8788
Extension API: 20140829


Fatal error: Uncaught exception 'Exception' with message 'Port is not numeric' in :
Stack trace:
  #0 (): mysqli->real_connect()
  #1 /usr/share/phpmyadmin/libraries/dbi/DBIMysqli.class.php(114): mysqli_real_connect()
  #2 /usr/share/phpmyadmin/libraries/dbi/DBIMysqli.class.php(191): PMA_DBI_Mysqli->_realConnect()
  #3 /usr/share/phpmyadmin/libraries/DatabaseInterface.class.php(2078): PMA_DBI_Mysqli->connect()
  #4 /usr/share/phpmyadmin/libraries/common.inc.php(978): PMA_DatabaseInterface->connect()\n#5 /usr/share/phpmyadmin/index.php(12): include()
  #6 {main}
^X^X
```

**Comment by mosamlife** [comment]
Same problem here :(

**Comment by mosamlife** [comment]
HHVM logs the problem with mising port number. Adding $cfg['Servers'][$i]['port'] = '3306'; to phpmyadmin's  config.inc.php fixed the problem.

**Comment by BlakePetersen** [comment]
@mosamlife is spot on, setting the port fixes it and easier than updating an apt-get version to master branch, I'd just **update $dbport in /etc/phpmyadmin/config-db.php to '3306'**, config.inc.php seems to be all about it with that require on 58.

**Comment by mandb** [comment]
Yep that worked for me, also it can be in **phpmyadmin/libraries/config.default.php**

**Comment by ffxsam** [comment]
For me, editing the config.inc.php did not work. Nor editing config.default.php.

I had to edit phpmyadmin/libraries/dbi/mysqli.dbi.lib.php and add this line near the top:

`$GLOBALS['cfg']['Server']['port'] = 3306;`

**Comment by alex-mashin** [comment]
This helps. Is HHVM going to do anything about this?
