### ISSUE TITLE
building and PCRE questions (HHVM 3.3.1)

### ISSUE THREAD

**Issue by christopherowen** [facebook/hhvm#4150]
1) Why is PCRE a dependency and additionally included?
2) Why are binaries compiled that conflict with the binaries from the dependency required?

Please see: https://github.com/mcuadros/homebrew-hhvm/issues/124

**Comment by jwatzman** [comment]
Is there anything left to do here? @jrobeson and @tstarling had some packaging fixups that I think fixed the "we install a conflicting PCRE when we shouldn't" issue, and it sounds like the issue around the validity of the test for the JIT in the CMake stuff was a misunderstanding? I'm going to close this; LMK if there's something left to do and happy to reopen.
