### ISSUE TITLE
hhbbc aborts on symfony

### ISSUE THREAD

**Issue by Remper** [facebook/hhvm#4170]
Seg faults every time at random places while inferring types. I'm trying to compile my symfony-based project with `hhvm --hphp --target hhbc --input-dir /path/to/project -o ./ -k1 -l4`.

Stacktrace:

```
Host: Sandbox
ProcessID: 13602
ThreadID: 7f8573bff700
ThreadPID: 13607
Name: /usr/bin/hhvm
Type: Segmentation fault
Runtime: hhvm
Version: tags/HHVM-3.3.1-0-ge0c98e21167b425dddf1fc9efe78c9f7a36db268
DebuggerCount: 0


#0  ?? at hhvm:0
#1  HPHP::ObjectPropertyExpression::inferTypes(std::shared_ptr<HPHP::AnalysisResult>, std::shared_ptr<HPHP::Type>, bool) at hhvm:0
#2  HPHP::Expression::inferAndCheck(std::shared_ptr<HPHP::AnalysisResult>, std::shared_ptr<HPHP::Type>, bool) at hhvm:0
#3  HPHP::BinaryOpExpression::inferTypes(std::shared_ptr<HPHP::AnalysisResult>, std::shared_ptr<HPHP::Type>, bool) at hhvm:0
#4  HPHP::Expression::inferAndCheck(std::shared_ptr<HPHP::AnalysisResult>, std::shared_ptr<HPHP::Type>, bool) at hhvm:0
#5  HPHP::IfBranchStatement::inferTypes(std::shared_ptr<HPHP::AnalysisResult>) at hhvm:0
#6  HPHP::StatementList::inferTypes(std::shared_ptr<HPHP::AnalysisResult>) at hhvm:0
#7  HPHP::IfStatement::inferTypes(std::shared_ptr<HPHP::AnalysisResult>) at hhvm:0
#8  HPHP::StatementList::inferTypes(std::shared_ptr<HPHP::AnalysisResult>) at hhvm:0
#9  HPHP::BlockStatement::inferTypes(std::shared_ptr<HPHP::AnalysisResult>) at hhvm:0
#10 HPHP::ForStatement::inferTypes(std::shared_ptr<HPHP::AnalysisResult>) at hhvm:0
#11 HPHP::StatementList::inferTypes(std::shared_ptr<HPHP::AnalysisResult>) at hhvm:0
#12 HPHP::MethodStatement::inferFunctionTypes(std::shared_ptr<HPHP::AnalysisResult>) at hhvm:0
#13 HPHP::DepthFirstVisitor<HPHP::InferTypes, HPHP::OptVisitor>::visitScope(HPHP::hphp_raw_ptr<HPHP::BlockScope>) at hhvm:0
#14 HPHP::OptWorker<HPHP::InferTypes>::doJob(HPHP::BlockScope*) at hhvm:0
#15 HPHP::JobQueueWorker<HPHP::BlockScope*, void*, true, true, HPHP::detail::NoDropCachePolicy>::start() at hhvm:0
#16 HPHP::AsyncFuncImpl::ThreadFunc(void*) at hhvm:0
#17 start_thread at /build/buildd/eglibc-2.19/nptl/pthread_create.c:312
#18 clone at /build/buildd/eglibc-2.19/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:113
```

HHVM output:

```
www-data@Sandbox:/opt/www$ hhvm --hphp --target hhbc --input-dir /path/to/project -o ./ -k1 -l4
running hphp...
parsing inputs...
parsing (a lot of files) ...
Unable to stat file (some files) 
analyzeProgram...
Analyzing Includes
Analyzing All
analyzeProgram took 0'06" (6299964 us) wall time
parsing inputs took 0'14" (14914279 us) wall time
pre-optimizing...
pre-optimizing took 0'16" (16385412 us) wall time
analyze includes...
analyze includes took 0'00" (15719 us) wall time
inferring types...
Set X's return type Y (bunch of them too)
....
Set symfony\\component\\validator\\validatorbuilder::addmethodmappings's return type Object - symfony\\component\\validator\\validatorbuilder
Core dumped: Segmentation fault
Set symfony\\component\\validator\\validatorbuilder::setmetadatafactory's return type Object - symfony\\component\\validator\\validatorbuilder
hphp failed
running hphp took 0'37" (37591979 us) wall time
```

ValidatorBuilder here is just for example -- it fails at random places every time.
Hope this is enough! Good luck!

**Comment by firodj** [comment]
the assertion occur when unique class expected to be unique (`if (!(cls->attrs & AttrUnique)) continue`) but there are more than one signature (see: `index.cpp`).
I've found that `Symfony HttpFoundation component` alse declares `SessionHandlerInterface` which is HHVM already have.

* `hphp/system/php/sessions/SessionHandlerInterface.php`
* `symfony/http-foundation/Resources/stubs/SessionHandlerInterface.php`

It is more convenient way to change the assert message to show which and where are the duplicates. Just remove symfony's SessionHandlerInterface.

**Comment by paulbiss** [comment]
Hmm, that would make sense. HHBBC unilaterally marks all builtins as unique, as defining your own versions would be an error anyway. We should probably improve the error message, but the error itself is unsurprising.

It sounds like the file is available for legacy compatibility with older versions of PHP. The right way to handle this would probably be to pass an exclude rule to hhvm when building the repo so that it does not attempt to analyze legacy compatibility files.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This issue applies to running php code on hhvm. Hhvm [nolonger supports running php code](https://hhvm.com/blog/2018/09/12/end-of-php-support-future-of-hack.html) since [hhvm version 4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html).

The underlying issue may still be around, but we can't repro this anymore, since hhvm 3.30 is no longer supported.
