### ISSUE TITLE
error_reporting(0) incompatibly ensures error_get_last() == NULL

### ISSUE THREAD

**Issue by radford** [facebook/hhvm#4174]
The following shows ```NULL``` with HHVM, but non-```NULL``` with Zend.

```php
    @strpos(); var_dump(error_get_last());

**Comment by samdark** [comment]
@paulbiss is it in master now?

**Comment by paulbiss** [comment]
It was causing some test failures and I didn't have a chance to dig into it, I'll take another look.

**Comment by radford** [comment]
@paulbiss, any updates on this?

**Comment by paulbiss** [comment]
I haven't had a chance to look at it yet, sorry

**Comment by radford** [comment]
This is fixed in 3.8.1.
