### ISSUE TITLE
Symfony Process Component Broken On Nightly

### ISSUE THREAD

**Issue by GrahamCampbell** [facebook/hhvm#4195]
```php
$process = new \Symfony\Component\Process\Process("example command", __DIR__);
$process->run();
```
Does nothing.

**Comment by Orvid** [comment]
This issue has been waiting for more info for more than 2 weeks. Closing for now, feel free to re-open it if you can provide more info.

https://github.com/facebook/hhvm/wiki/Human-Timeouts
