### ISSUE TITLE
Please include libiberty in the source

### ISSUE THREAD

**Issue by christopherowen** [facebook/hhvm#4196]
https://gcc.gnu.org/onlinedocs/libiberty/Using.html#Using

HHVM has libiberty as a dependency.  However, the upstream recommends that users of libiberty include the source for it in their software.

'For your own projects, an approach which offers stability and flexibility is to include libiberty with your code, but allow the end user to optionally choose to use a previously-installed version instead.'

that fact that libiberty is not included with hhvm is turning out to be an inconvenience in OS X as we have to build libiberty separately from our package system for hhvm to work (and separately depending on our compiler toolchain).

**Comment by christopherowen** [comment]
would it be possible to get assistance with this one?

**Comment by christopherowen** [comment]
#4444

**Comment by Orvid** [comment]
We chose to go a different route.
