### ISSUE TITLE
Segfault during Exception handling

### ISSUE THREAD

**Issue by mindplay-dk** [facebook/hhvm#4201]
HHVM on Travis-CI encountered a segfault when running a simple unit-test:

https://travis-ci.org/mindplay-dk/kisstpl/jobs/39546929

I asked the Travis-CI team about it, and they asked me to refer it to you.

Note that I have no particular interest in supporting HHVM myself, so I will probably just disable testing under HHVM and say it's not supported. If you're interested in fixing it, please work with the Travis-CI team, they should have an interest in seeing this fixed too. I don't personally have any real experience with HHVM, no real C experience, and limited Linux knowledge, so I probably can't be of much help.

**Comment by Orvid** [comment]
This issue has been waiting for more info for more than 2 weeks. Closing for now, feel free to re-open it if you can provide more info.

https://github.com/facebook/hhvm/wiki/Human-Timeouts
