### ISSUE TITLE
Bad config node warning for: ErrorHandling.ThrowBadTypeExceptions and ErrorHandling.ThrowNotices

### ISSUE THREAD

**Issue by mssola** [facebook/hhvm#4233]
In HHVM I get the following two warnings:

~~~
Possible bad config node: ErrorHandling.ThrowBadTypeExceptions
Possible bad config node: ErrorHandling.ThrowNotices
~~~

Are these two options still available ? I've read about these two options from the [wiki](https://github.com/facebook/hhvm/wiki/runtime-options).

**Comment by paulbiss** [comment]
New docs site: https://docs.hhvm.com/hhvm/configuration/INI-settings
