### ISSUE TITLE
PCRE is compiled without UTF support ?

### ISSUE THREAD

**Issue by ViolentVotan** [facebook/hhvm#4242]
Hello, 

I receive a lot of warnings in the log files that look like these:

```
\nWarning: Compilation failed: this version of PCRE is compiled without UTF support at offset 0 in /path/to/some/script.php on line 1984
```

Is HHVM not using the pcre fro the system, if not, is there a reason why the included pcre installation does not come with utf?

**Comment by ck-on** [comment]
Using the current trunk of HHVM  (3.7-dev) it still fails to properly detect that the system version of PCRE on CentOS 7 does not have proper support and fails to activate the third-party library - please advise how to force it to use third-party hhvm?
```
pcretest -C
PCRE version 8.32 2012-11-30
Compiled with
  8-bit support
  No UTF-8 support
  No Unicode properties support
  No just-in-time compiler support
```

**Comment by ck-on** [comment]
As of May 2nd 2015, HHVM still fails to detect the PCRE on CentOS 7 does not have proper support and I still have to use the above workaround.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

The hal `Regex\` code exposes the `/u` modifier and is backed by the same regex code as preg_ is. So this works fine on all supported distributions.
