### ISSUE TITLE
Instance Variables in Class Declaration

### ISSUE THREAD

**Issue by steelbrain** [facebook/hhvm#4243]
[Feature Request]
There are a lot of situations where we have to create extra useless functions just to initialize static instance variables in a class. For example the DB class
```php
<?hh
class DB{
   public static ?PDO $pdo = null;
   public static function init():void{
      self::$pdo = new PDO('...');
   }
   public static function query(string $query, Map<string,string> $args):Map<string>{
      if(self::$pdo == null){
         // We have to throw the exception, because self::init is not completely understood by typechecker
         throw new Exception("Thy must initialize first");
      $query = self::$pdo->prepare($query);
      $query->execute($args);
      return $query->fetchAll(PDO::FETCH_ASSOC);
   }
}
```
and then wherever we access the DB::$pdo we have to check for null. It can all be removed if we support Instance variable declaration in class declaration.

**Comment by steelbrain** [comment]
Bump

**Comment by Eccenux** [comment]
There is now an official RFC for this issue in PHP: https://wiki.php.net/rfc/static_class_constructor

**Comment by steelbrain** [comment]
:heart:

**Comment by paulbiss** [comment]
> This feature request is not actively being worked on. We would happily consider a pull request implementing it. If you plan to work on this issue let us know in the comments and we will re-open the issue and assign it to you. If you feel strongly that this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.

If the RFC passes feel free to re-open this as a compat issue.
