### ISSUE TITLE
hhvm may have caused kernel error

### ISSUE THREAD

**Issue by Richardevs** [facebook/hhvm#4246]
CentOS 6.6, 2.6.32-504.1.3.el6.x86_64
HHVM runs under port 9001 and used by Nginx.

After I started HHVM, the CPU can be easily going up to 100% and HHVM will be killed.
dmerg shows below:
hhvm[10038]: segfault at 0 ip 0000000000bb11fb sp 00007f2b43df9660 error 4 in hhvm[400000+1fb3000]
hhvm[11272] general protection ip:9051a8 sp:7fa3505fa5f0 error:0 in hhvm[400000+1fb3000]
hhvm[13834] general protection ip:9051c8 sp:7f0b0edfa5f0 error:0 in hhvm[400000+1fb3000]

**Comment by Orvid** [comment]
This issue has been waiting for more info for more than 2 weeks. Closing for now, feel free to re-open it if you can provide more info.

https://github.com/facebook/hhvm/wiki/Human-Timeouts
