### ISSUE TITLE
HHVM doesn't support tar, tar.gz, tar.bz2 and zip versions of Phar archives

### ISSUE THREAD

**Issue by nazar-pc** [facebook/hhvm#4263]
tar.gz and tar.bz2 fails with:
> \nFatal error: Uncaught exception 'PharException' with message 'Corrupt phar, can't read 4 bytes starting at offset 1140' in ...

tar fails with:
> \nFatal error: Uncaught exception 'PharException' with message 'Malformed manifest. Expected 0 bytes, got 40' in ...

zip fails with:
> \nFatal error: Uncaught exception 'PharException' with message 'Not a phar: phar:///text.phar.php/text' in ...

Since all this variant supposed to be supported it is a huge incompatibility with PHP5 and should be fixed in next version.

**Comment by mwjames** [comment]
Do we see any chance that in near future phar archives will receive fully support and PHP compatibility?

**Comment by jwatzman** [comment]
No immediate plans that I'm aware of. I might have time to take a look in the next couple days, but other stuff might come up, we'll see how it goes.

**Comment by jwatzman** [comment]
And it does *not* repro with an internal build of master, so sounds like some difference there. Exciting.

**Comment by jwatzman** [comment]
I looked at this briefly; we're getting stuck in a `read` syscall, called as part of `fread`, when first reading from what looks to be a pipe into the child process `timeout`. AFAICT we call `read` once and it never returns. It was not immediately clear what would cause that, and I didn't have time to look into it any deeper. Will comment again if I get more time to dig in further, this is pretty interesting.

**Comment by jwatzman** [comment]
[Above two comments deleted, they were on the wrong task, sorry.]

**Comment by andrerom** [comment]
Duplicate: #5139 "Phing phar outputs gibberish on hhvm"
Related: #1854 "ob_gzhandler not implemented"

This is blocking use of compression by default in Composer: https://github.com/composer/composer/pull/3890 _(typically wasting quite a lot of bandwith, at least when using satis)_

**Comment by nazar-pc** [comment]
Not sure that #1854 is really related, looks like totally different area.

**Comment by andrerom** [comment]
Yes, it was regarding missing compression support in general, but deleted that part now.

**Comment by bauerj** [comment]
Also, it does not seem that #5139 is related as the file in question seems not to be compressed.

**Comment by nazar-pc** [comment]
There is https://pear.php.net/package/PHP_Archive/ licensed under PHP License.

Is it possible to just to include it into HHVM, register as stream wrapper for `phar` and forget about all issues with Phar?
There are some features marked as missing in docs:
> The PHP_Archive class differs in approach from the Phar class in that it does not support the ArrayAccess interface for accessing internal files, and does not support iteration over contents using foreach(). However, full support for the phar:// stream wrapper, support of Phar-specific metadata setting and retrieval using PHP_Archive::getPharMetaData() and file-specific metadata using PHP_Archive::getFileMetaData(), zlib and bzip2 compression of individual files, and archive-wide SHA1/MD5 signature makes PHP_Archive just as powerful as the Phar extension for distributing phars.

It can be at least taken as foundation for further improvements since PHP License is fine for HHVM.

I can try to bring it in, but I need some confirmation that this is actually good thing to do and it will be accepted in such form.

**Comment by Orvid** [comment]
No, we can't have that replace the existing Phar support, because that deliberately has a different API. It is reasonable to use that as a base to improve the existing Phar support though.

**Comment by nazar-pc** [comment]
Good, I'll try to do something about it.

**Comment by nazar-pc** [comment]
It is interesting that some tar/zip have some initial support in `PharData` already.
Working on support in Phar here: https://github.com/facebook/hhvm/compare/master...nazar-pc:phar-compression-support?diff=split&expand=1&name=phar-compression-support

Will PR when read support is ready, seems pretty doable as far as it is mostly PHP, not Hack/C :smile:

**Comment by Orvid** [comment]
Awesome!

Ideally those docs changes should go in a separate PR, as they're far easier to review and are a lot of lines. (the format you switched them to is what the rest of the docs in the runtime use, so it's a good change)

**Comment by nazar-pc** [comment]
I've separated them into distinct commits intentionally.
There will be changes for PhpDoc sections for related classes, so I'll try to put all of that together afterwards.

**Comment by nazar-pc** [comment]
`.phar.gz`, `.phar.bz2`, `.phar.tar`, `.phar.tar.gz`, `.phar.tar.bz2`, `.phar.zip` and all mentioned under generic `.phar` format are supported.
There are some basic tests to ensure things will work.

I'll decouple massive trivial PhpDoc changes separately and afterwards will rebase and submit another PR. More details will be in PRs.

Feel free to test it in the mean time (and submit more tests) :bomb: :rocket: :star2:

**Comment by nazar-pc** [comment]
#7028 it contains description and implementation of support for all kinds of compressed Phar and some additional stuff.

**Comment by nazar-pc** [comment]
Closing this as #7028 was merged
