### ISSUE TITLE
Database Extensions

### ISSUE THREAD

**Issue by dk-zero-cool** [facebook/hhvm#4269]
According to [this](https://github.com/facebook/hhvm/tree/master/hphp/runtime/ext/mysql), you have the mysqli class added to HHVM, however the type checker does not seam to be aware of this. I get `Unbound name: mysqli` when trying to use it. 

HHVM does not have any problems locating it or use it however. The problem lies with the type checker.

**Comment by paulbiss** [comment]
PR has timed out and it doesn't look like anyone is still interested in this. We'd still be happy to take a pull request if anyone out there needs this.
