### ISSUE TITLE
mysqli error handling discrepancies with php5

### ISSUE THREAD

**Issue by rrh** [facebook/hhvm#4273]
mysqli_multi_query, and perhaps others in the mysqli family, do not recover from mis-typed arguments in the same way that zend php5 does.  If the 2nd argument to mysqli_multi_query is an array and not a string, then a "catchable fatal error" is generated (the name sounds like an oxymoron), and execution stops, even if @ is used.  Php5 will recover and continue executing.

This example presupposes a local mysql database instance "drupal6".  HHVM does not print "after", but php5 does.

<?php
$link = mysqli_connect ("localhost", "root", "root", "drupal6");
$A = array (1);
echo "before... \n";
@mysqli_multi_query ($link, $A);  // deliberate type mismatch
echo "after...\n";

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Mysqli support was dropped in hhvm [4.9.0](https://hhvm.com/blog/2019/06/10/hhvm-4.9.0.html).
