### ISSUE TITLE
[php5.6] Constant arrays not supported

### ISSUE THREAD

**Issue by TazeTSchnitzel** [facebook/hhvm#4277]
See: https://github.com/php/php-langspec/pull/90

http://3v4l.org/nX5if

**Comment by Kozzi11** [comment]
@paulbiss what's the current status?

**Comment by TazeTSchnitzel** [comment]
Did this get in?

**Comment by hopeseekr** [comment]
I am pretty sure that this is still not supported :-((

**Comment by Webysther** [comment]
There is an alternative to get around the problem that can be reversed when it is fixed?

**Comment by TazeTSchnitzel** [comment]
No workaround is needed for defining with `const`, HHVM supports that now.

If you need `define()`, though, try this:

```php
function defineWorkaroundForHHVM(string $name, $value) /* : void */ {
    $slashPos = strpos($name, '\\');
    $namespace = "";
    if ($slashPos !== false) {
        $namespace = substr($name, 0, $slashPos);
        $name = substr($name, $slashPos + 1);
    }
    $value = var_export($value, true);
    eval('namespace ' . $namespace . '{ const ' . $name . ' = ' . $value . '; }');
}
```

(You probably shouldn't use this code.)

**Comment by Webysther** [comment]
Sorry @TazeTSchnitzel, I was not clear, is about arrays class constant values.

https://3v4l.org/T0cPe

**Comment by Erwyn** [comment]
It does not work on PHP7 compatibility neither:

`hhvm -d hhvm.php7.all=1 whatever.php`

result: `Arrays are not allowed in class constants`

**Comment by craigcarnell** [comment]
Doesn't work for me in latest either

**Comment by wulftone** [comment]
Been a few months, this deserves a bump.  I would like to use arrays in class constants, too!

**Comment by oakad** [comment]
I wonder, why this, absolutely harmful in its absence, feature is still not supported by hhvm after 3 years?

A brief inspection of code indicates, that prohibition of const arrays (either global scope or in-class) even managed to survive the recent refactoring of datatype/variant handling, so it probably was a deliberate decision by the implementors.

However, nowadays massive amounts of php code depend on const arrays and their use is increasing, thus making migration to hhvm outright impossible, despite all the other advantages hhvm may have provided.

**Comment by TazeTSchnitzel** [comment]
Almost all my new PHP code uses constant arrays somewhere, and therefore probably won't work on HHVM. I doubt I'm alone here, it's a very useful feature.

**Comment by Kozzi11** [comment]
I have to refactor all our codebase to remove all const array to try hhvm and after that I realize it is impossible to use latest hhvm on anything else than ubuntu and debian, so this is a bye bye to HHVM OTOH php 7 is even faster in my tests so no harm here :)

**Comment by fredemmott** [comment]
@mofarrell @paulbiss *bump* 

Added 'probably easy' given I guess a lot of the required work was already done to support https://github.com/facebook/hhvm/blob/master/hphp/test/quick/vec/static.php

**Comment by oakad** [comment]
@fredemmott 

To my humble understanding fixing this would require a new class derived from Array (something like "StaticArray" with appropriate bounds on keys and values). There's no indication in current code (3.17 that is) that anything was done in this direction.

**Comment by fredemmott** [comment]
IIRC that's existed for a long time (used by array literals and APC) - but the plumbing to hook them up to classes didn't exist.

**Comment by oakad** [comment]
HHVM is a nice tech, especially when it's native api is concerned, but this feature here is a huge blocker. On behalf of the wider user community I urge you to take a look at fixing this. :-)

**Comment by TysonAndre** [comment]
Re: https://github.com/facebook/hhvm/issues/4277#issuecomment-66213113

It seems like reviews.facebook.net is no longer a public site  (or just the review https://reviews.facebook.net/D29163).

Is it possible to commit the original commits for that PR and link to it (Or just post a patch file of the diff for that commit) in this issue?

**Comment by Orvid** [comment]
There is work ongoing internally to fix this as part of supporting hack arrays properly.

**Comment by fredemmott** [comment]
reviews.facebook.net no longer exists in any form - it's not just no longer public.

**Comment by fredemmott** [comment]
@ricklavoie

![post-67207-monty-python-and-there-was-muc-vyis](https://cloud.githubusercontent.com/assets/360927/24159274/f16b4064-0e1b-11e7-92c6-c4f5adcdcdd9.jpeg)

**Comment by eryi** [comment]
Is this only for PHP? Hack code still gives the same error.

````
<?hh

class Foo {
  const array<mixed> BAR = [];
}
````

Tested using 3.19.1
````
hhvm: Catchable fatal error: Hack type error: Illegal constant value at ...
hh_client: Illegal constant value (Naming[2023])
````

**Comment by fredemmott** [comment]
HHVM supports it, the typechecker doesn't.

**Comment by fredemmott** [comment]
@wulftone : typechecker now supports it
