### ISSUE TITLE
thrift/lib/cpp/transport/TSocketAddress.h:25:22: fatal error: features.h: No such file or directory

### ISSUE THREAD

**Issue by denji** [facebook/hhvm#4286]
Darwin MacBook-Pro.local 14.0.0 Darwin Kernel Version 14.0.0: Fri Sep 19 00:26:44 PDT 2014; root:xnu-2782.1.97~2/RELEASE_X86_64 x86_64 

```
[ 18%] Building CXX object third-party/thrift/CMakeFiles/hphp_thrift.dir/thrift/lib/cpp/async/TAsyncServerSocket.cpp.o
In file included from /usr/local/Cellar/hhvm/3.4.0/src/third-party/thrift/thrift/lib/cpp/async/TAsyncServerSocket.h:28:0,
                 from /usr/local/Cellar/hhvm/3.4.0/src/third-party/thrift/thrift/lib/cpp/async/TAsyncServerSocket.cpp:21:
/usr/local/Cellar/hhvm/3.4.0/src/third-party/thrift/thrift/lib/cpp/transport/
[TSocketAddress.h]:25:22: fatal error: features.h: No such file or directory
 #include <features.h>
                      ^
compilation terminated.
```

https://github.com/facebook/fbthrift/commit/781469edeebad2cb69c7083061b5204dcc13a358

**Comment by slashmili** [comment]
@denji Did you find a solution? My build is still failing because of this error

**Comment by denji** [comment]
https://github.com/hhvm/hhvm-third-party/commit/a24248d97f4704aa35cbe213d0c8f62842444f03

**Comment by mikaelmattsson** [comment]
I'm still having problems with this. If facebook has fixed the bug, how do I make sure I use the fixed version of facebook/fbthrift?
