### ISSUE TITLE
HHVM 3.4.0 sometimes calling https

### ISSUE THREAD

**Issue by ghost** [facebook/hhvm#4289]
Sorry my english, enter e.g http://10.2.2.1/phpmyadmin/ GET request later sometimes browser waiting 10 seconds and my web browser calling https://10.2.2.1:80/phpmyadmin/

Finished singleJitRequest 1
Finished singleJitRequest 2
Finished singleJitRequest 3
Finished singleJitRequest 4
Finished singleJitRequest 5

I am use nginx and SSL no enable. I not see this problem HHVM 3.3.0. Does anyone encountered this problem too?

**Comment by podarok** [comment]
> Those messages are not issues, they are normal behavior.
If so, they shouldn't be in error.log, right? @fredemmott

**Comment by fredemmott** [comment]
they're useful for context if there's also timeout/slow errors in the log.
