### ISSUE TITLE
Update password_compat library to 1.0.4 release

### ISSUE THREAD

**Issue by ircmaxell** [facebook/hhvm#4294]
I just released version [1.0.4 of password_compat](https://github.com/ircmaxell/password_compat/tree/v1.0.4)

This has a few bug fixes to bring behavior back inline with PHP, as well as support PHPUnit.

The only change that would impact HHVM is supporting non-string scalar parameters (namely integer and `null`):

The problem will be that two tests will fail the version that you're using:

    password_hash(null, PASSWORD_BCRYPT, array("salt" => "1234567890123456789012345678901234567890"));

And

    password_hash(12345, PASSWORD_BCRYPT, array("salt" => "1234567890123456789012345678901234567890"));

Both work in PHP, both work in the compatibility library (as of 1.0.4), but [neither work on HHVM](https://travis-ci.org/ircmaxell/password_compat/jobs/41635027) due to the added type annotations to the parameters (defining the password as a string).

Due to the modifications, the changes would need to be custom ported to HHVM, rather than just merged (though parts may be merged).

**Comment by Orvid** [comment]
Works for me.
