### ISSUE TITLE
Include proper version numbers to NEWS file

### ISSUE THREAD

**Issue by prof-milki** [facebook/hhvm#4299]
I do appreciate that there's a maintained NEWS file, not jus blog posts - but a bit more standardized would be helpful.
Albeit the release monikers are a neat idea, it's quirky to follow / much less to parse for packaging tools.

     3.4.0 "Xzibit" 20-Nov-2014

Wouldn't work?
(Letting the non-ISO dates go unmentioned..)

**Comment by Orvid** [comment]
NEWS is dead. Long live the commit history.
