### ISSUE TITLE
libinotify portable version for non-Linux

### ISSUE THREAD

**Issue by denji** [facebook/hhvm#4301]
Undefined behavior libinotify on Apple and *BSD,
Does forced to compile?

Warning about his absence:
```
Could NOT find LIBINOTIFY (missing:  LIBINOTIFY_LIBRARY LIBINOTIFY_INCLUDE_DIR) 
```

Gist log: https://gist.github.com/sfroment42/735ed43a0c4a0e0fbd86

Portable [`dmatveev/libinotify-kqueue`](https://github.com/dmatveev/libinotify-kqueue) `third-party` NetBSD, OpenBSD, FreeBSD, Mac OS X (reported to work).

ref: #4189

**Comment by paulbiss** [comment]
We now have a mac port and a windows port on the way. I don't think this is a blocker anymore.
