### ISSUE TITLE
copy() empty file from within phar to regular filesystem returns false

### ISSUE THREAD

**Issue by nazar-pc** [facebook/hhvm#4314]
This is an epic incompatibility.
Stub:
```php
<?php
if (PHP_SAPI == 'cli') {
	Phar::mapPhar('cleverstyle_cms.phar');
	include 'phar://cleverstyle_cms.phar/install.php';
} else {
	Phar::webPhar(null, 'install.php');
}
__HALT_COMPILER();
```

Code inside `install.php` like this:
```php
var_dump(copy('phar://cleverstyle_cms.phar/empty_file', getcwd().'/empty_file'));
```
PHP5:
> true

HHVM:
> false

`getcwd()` is used to get path to directory where phar file placed itself.
There is not such problem with regular copying of empty files, also file is actually copied, but returns `false` on HHVM.

A bit of nagging
*I found so many weird things while trying to make installation/update of my CleverStyle CMS working with HHVM: first was bug with halt token, then absent support of compressed tar.bz2 and many bugs with anything except pure phar, then inability to copy file with name `0`, now this. So many hours spent, still need more workarounds for HHVM:( Probably, you may need to find some time specifically for focusing on ZEND compatibility, I can help with founding bugs, I'm facing them a lot:)*

**Comment by nazar-pc** [comment]
Can anyone take a look at this?

**Comment by jwatzman** [comment]
I'm not aware of anyone having time to look at this one yet, sorry.

**Comment by nazar-pc** [comment]
Three months later, maybe someone will find a bit of time to fix this annoying issue?
Looks like number of copied bytes just casted to boolean and returned from function, but I didn't succeed to find where it happens.

**Comment by nazar-pc** [comment]
Guys, I found a place where it happens:
https://github.com/facebook/hhvm/blob/2efae48af4a77db990e068f7a577e439f785a89f/hphp/runtime/ext/std/ext_std_file.cpp#L1537
It is true, when you copy stream to other stream there are 0 bytes in empty file, but anyway it is copied properly, looks like there is a need for some additional check, but I'm not C++ developer, I can only make test case for this as phpt test if you want.

**Comment by nazar-pc** [comment]
Almost half a year later, can anyone take a look at this finally?

**Comment by jwatzman** [comment]
I'm really sorry, but no one has still had a chance to look into this. There's only five of us working on our gigantic issue queue, and we're also responsible for things like supporting PHP7 features, etc. We'd love to be able to get to all the small issues like this, but tend to have higher priority issues come through. This is still in our queue, and is still something we'd like to get to, but we just haven't had time.
