### ISSUE TITLE
hhvm segfault in /var/log/messages

### ISSUE THREAD

**Issue by yiqun** [facebook/hhvm#4318]
##### /var/log/message kernel error
> Nov 21 21:56:44 10-10-40-154 kernel: [161296.975463] hhvm[3497]: segfault at 0 ip 0000000000e52731 sp 00007fe725ff9ee0 error 4 in hhvm[400000+2922000]

##### ```root@10-10-40-154:~# more /tmp/stacktrace.2780.log ```
> Host: 10-10-40-154
> ProcessID: 2782
> ThreadID: 7fe725fff700
> ThreadPID: 3497
> Name: /etc/init.d/hhvm
> Type: Segmentation fault
> Runtime: hhvm
> Version: tags/HHVM-3.4.0-0-g817b3a07fc4e509ce15635dbc87778e5b3496663
> DebuggerCount: 0
> 
> ThreadType: Web Request
> Server_SERVER_NAME: www.domain.com
> Server: www.domain.com
> URL: /member/collect
> 
> `#` 0  HPHP::jit::callDestroysLocals(HPHP::jit::NormalizedInstruction const&, HPHP::Func const*) at /usr/bin/hhvm:0
> `#` 1  HPHP::jit::IRTranslator::translateInstrWork(HPHP::jit::NormalizedInstruction const&) at /usr/bin/hhvm:0
> `#` 2  HPHP::jit::selectTracelet(HPHP::jit::RegionContext const&, bool, bool) at /usr/bin/hhvm:0
> `#` 3  HPHP::jit::selectRegion(HPHP::jit::RegionContext const&, HPHP::jit::TransKind) at /usr/bin/hhvm:0
> `#` 4  HPHP::jit::MCGenerator::translateWork(HPHP::jit::TranslArgs const&) at /usr/bin/hhvm:0
> `#` 5  HPHP::jit::MCGenerator::translate(HPHP::jit::TranslArgs const&) at /usr/bin/hhvm:0
> `#` 6  HPHP::jit::MCGenerator::retranslate(HPHP::jit::TranslArgs const&) at /usr/bin/hhvm:0
> `#` 7  HPHP::jit::MCGenerator::createTranslation(HPHP::jit::TranslArgs const&) at /usr/bin/hhvm:0
> `#` 8  HPHP::jit::MCGenerator::bindJmpccSecond(unsigned char*, int, HPHP::jit::ConditionCode, bool&) at /usr/bin/hhvm:0
> `#` 9  HPHP::jit::MCGenerator::handleServiceRequest(HPHP::jit::TReqInfo&, unsigned char*&, HPHP::SrcKey&) at /usr/bin/hhvm:0
> `#` 10 HPHP::jit::MCGenerator::enterTC(unsigned char*, void*) at /usr/bin/hhvm:0
> `#` 11 HPHP::ExecutionContext::invokeFunc(HPHP::TypedValue*, HPHP::Func const*, HPHP::Variant const&, HPHP::ObjectData*, HPHP::Class*, HPHP::VarEnv*, HPHP::StringData*, HPHP::Executi
onContext::InvokeFlags) at /usr/bin/hhvm:0
> `#` 12 HPHP::ExecutionContext::invokeUnit(HPHP::TypedValue*, HPHP::Unit const*) at /usr/bin/hhvm:0
> `#` 13 HPHP::include_impl_invoke(HPHP::String const&, bool, char const*) at /usr/bin/hhvm:0
> `#` 14 HPHP::hphp_invoke(HPHP::ExecutionContext*, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, HPHP::Array const&, HPHP::VRefParamValue const&
, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool&, std::basic_st
ring<char, std::char_traits<char>, std::allocator<char> >&, bool, bool, bool) at /usr/bin/hhvm:0
> `#` 15 HPHP::HttpRequestHandler::executePHPRequest(HPHP::Transport*, HPHP::RequestURI&, HPHP::SourceRootInfo&, bool) at /usr/bin/hhvm:0
> `#` 16 HPHP::HttpRequestHandler::handleRequest(HPHP::Transport*) at /usr/bin/hhvm:0
> `#` 17 HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJob(std::shared_ptr<HPHP::FastCGIJob>) at /usr/bin/hhvm:0
> `#` 18 HPHP::JobQueueWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::Server*, true, false, HPHP::JobQueueDropVMStack>::start() at /usr/bin/hhvm:0
> `#` 19 HPHP::AsyncFuncImpl::ThreadFunc(void*) at /usr/bin/hhvm:0
> `#` 20 HPHP::start_routine_wrapper(void*) at /usr/bin/hhvm:0
> `#` 21 start_thread at /lib/x86_64-linux-gnu/libpthread.so.0:0
> `#` 22 __clone at /lib/x86_64-linux-gnu/libc.so.6:0

##### ```root@10-10-40-154:~# hhvm --version```
> HipHop VM 3.4.0 (rel)
> Compiler: tags/HHVM-3.4.0-0-g817b3a07fc4e509ce15635dbc87778e5b3496663
> Repo schema: 0e12aaa31fae66b5591f65603de50c9d62caafac
> Extension API: 20140829

##### ```root@10-10-40-154:~# lsb_release -a```
> No LSB modules are available.
> Distributor ID:	Debian
> Description:	Debian GNU/Linux 7.7 (wheezy)
> Release:	7.7
> Codename:	wheezy

##### ```root@10-10-40-154:~# more /etc/hhvm/server.ini ```
> ; php options
> 
> pid = /var/run/hhvm/pid
> 
> ; hhvm specific
> 
> ;hhvm.server.port = 9000
> hhvm.server.file_socket=/var/run/hhvm/hhvm.sock
> hhvm.server.type = fastcgi
> hhvm.server.default_document = index.php
> hhvm.server.thread_count = 5000
> 
> hhvm.log.use_log_file = true
> hhvm.log.file = /var/log/hhvm/error.log
> 
> hhvm.repo.central.path = /var/run/hhvm/hhvm.hhbc
> 
> hhvm.eval.jit = true
> hhvm.eval.jit_a_size = 536870912
> hhvm.eval.jit_a_cold_size = 536870912
> hhvm.eval.jit_a_frozen_size = 536870912
> hhvm.eval.jit_global_data_size = 268435456
> hhvm.eval.perf_pid_map = false
> 
> hhvm.resource_limit.core_file_size = 0
> hhvm.resource_limit.max_socket = 30000
> hhvm.resource_limit.socket_default_timeout = 5
> ;hhvm.resource_limit.max_rss = 5
> ;hhvm.resource_limit.max_rss_polling_cycle = 300
> hhvm.resource_limit.drop_cache_cycle = 1800

**Comment by Orvid** [comment]
This issue has been waiting for more info for more than 2 weeks. Closing for now, feel free to re-open it if you can provide more info.

https://github.com/facebook/hhvm/wiki/Human-Timeouts
