### ISSUE TITLE
Add support for Phar::running()

### ISSUE THREAD

**Issue by fpoirotte** [facebook/hhvm#4323]
HHVM is currently lacking an implementation for the `Phar::running()` method (http://php.net/manual/en/phar.running.php).

This causes some projects like Phing (http://www.phing.info/) to exit with a fatal error (`Call to undefined method Phar::running()` in classes/phing/system/io/UnixFileSystem.php).

The issue was previously raised on the hhvm irc channel (see http://irc.cakephp.nu/hhvm/2014-02-14#MPuHals6PSj6mKifIfzjjMg). I'm merely opening an issue to keep track of this problem.

**Comment by reeze** [comment]
This clould be cloesed : https://github.com/facebook/hhvm/commit/7d53dd076f8f5b71947b963068d3bdf11a43b176

**Comment by fpoirotte** [comment]
Indeed. Closing as the FR has now been implemented.
