### ISSUE TITLE
crypt(): raise a notice if no salt

### ISSUE THREAD

**Issue by denji** [facebook/hhvm#4361]
| 5.6.0 | Raise E_NOTICE security warning if salt is omitted. |
| --- | --- |

Result: http://3v4l.org/8K3Ob
In recent releases of php appears unsafe behavior in the absence of salt:

hhvm-3.0.1 - 3.4.0: 

``` php
string(34) "$1$bJoWf/..$mTgm1g69VfN9GIbOKxYPv0"
string(34) "$1$4DmSm...$LT1vPcM6123p5LRkQVZrs1"
string(34) "$1$dV7DY/..$pZStzg9hvGAcTg5clHhqp."
```

Output for 5.6.3:

``` php
Notice: crypt(): No salt parameter was specified. You must use a randomly generated salt and a strong hash function to produce a secure hash. in /in/8K3Ob on line 4

Notice: crypt(): No salt parameter was specified. You must use a randomly generated salt and a strong hash function to produce a secure hash. in /in/8K3Ob on line 5

Notice: crypt(): No salt parameter was specified. You must use a randomly generated salt and a strong hash function to produce a secure hash. in /in/8K3Ob on line 6
string(34) "$1$YNMNnxw2$CdQixoEVsaI6XjVyjB1dZ1"
string(34) "$1$Led6ElOJ$WhfQd3/YD0OAyine4P7yD."
string(34) "$1$toyOWA0X$QLYH3zVNmjAVhavpAlfQN0"
```

In addition to the above, there are performance issues: http://3v4l.org/8K3Ob/perf#tabs

**Comment by samaiyan** [comment]
message crypt() no salt parameters specified.you must use a randomly generated salt  and strong hash function  to a produce secure hash

**Comment by denji** [comment]
@samaiyan To use Password Hashing API (`password_hash `, `password_verify `) and safe comparison for preventing time attack `hash_compare`.
For example, two safe mechanism of salt `openssl_random_pseudo_bytes` and `mcrypt_create_iv`.

- [Compatibility for older versions of PHP](https://github.com/ircmaxell/password_compat)

**Comment by samaiyan** [comment]
decription:
  i am using codeigniter framework.
  this issue only for latest PHP version. 
 after signup just flash message.

error message:
message crypt() no salt parameters specified.you must use a randomly generated salt and strong hash function to a produce secure hash.

How to solve the problem?can you help me....................

**Comment by denji** [comment]
@samaiyan https://github.com/bcit-ci/CodeIgniter/blob/cd3d9dbcbc99fa956b7400d328f202e1bcab4677/user_guide_src/source/general/compatibility_functions.rst#password-hashing

**Comment by samaiyan** [comment]
decription:
i am using codeigniter framework.
this issue only for latest PHP version. 
after signup just flash message.

error message:

PHP error was encountered;
sevenity:Notice
message crypt() no salt parameters specified.you must use a randomly generated salt and strong hash function to a produce secure hash.
File path:libraries/Dx_auth.php
Line number:0



How to solve the problem?can you help me....................

                        Thank You

**Comment by samaiyan** [comment]
hi gi,

decription:
i am using codeigniter framework.
this issue only for latest PHP version. 
after signup just flash message error.

error message:

PHP error was encountered;
sevenity:Notice
message crypt() no salt parameters specified.you must use a randomly generated salt and strong hash function to a produce secure hash.
File path:libraries/Dx_auth.php
Line number:0

**Comment by simonwelsh** [comment]
@samaiyan that sounds like a problem you should bring up with Code Igniter. It's not related to HHVM.
