### ISSUE TITLE
Particular URLs to hhvm and particular URLs to php with same virtual host

### ISSUE THREAD

**Issue by cthakar** [facebook/hhvm#4362]
Hi folks,

I have created one heavy loaded php site with hhvm + Nginx + Fast CGI it works fine without any issue,But I want to run particular stuff through php and particular stuff through hhvm in same virtual host configuration. currently all the php pages are working through hhvm but is there any way that I can make particular pages through php and except all through hhvm. Help will be greatly appreciated !

Thank you so much in advance !
-Chintan thakar
http://about.me/chintan.thakar

**Comment by paulbiss** [comment]
Closing this as an external issue. Should still be indexed if anyone has the same problem and comes hunting for solutions.
