### ISSUE TITLE
Unable to find/load systemlib.php when running under user as root

### ISSUE THREAD

**Issue by andreubotella** [facebook/hhvm#4368]
After compiling from source on Fedora 20, when running HHVM under a user as root, I get this error and the server dies:

    $ sudo hhvm -m server -u apache -vServer.Type=fastcgi -vServer.FileSocket=/path/to/socket
    mapping self...
    mapping self took 0'00" (112338 us) wall time
    loading static content...
    loading static content took 0'00" (1 us) wall time
    Unable to find/load systemlib.php

But not when I take out the `-u apache`:

    $ sudo hhvm -m server -vServer.Type=fastcgi -vServer.FileSocket=/path/to/socket
    mapping self...
    mapping self took 0'00" (33370 us) wall time
    loading static content...
    loading static content took 0'00" (1 us) wall time
    page server started
    all servers started

Using a file or network socket, or loading the configuration from a file makes no difference.

**Comment by jrobeson** [comment]
@unok-kun : so what happens if you try executing a php file with hhvm from the console ? does it work as expected then?

**Comment by Orvid** [comment]
This issue has been waiting for more info for more than 2 weeks. Closing for now, feel free to re-open it if you can provide more info.

https://github.com/facebook/hhvm/wiki/Human-Timeouts
