### ISSUE TITLE
Exception code problem in user-defined exceptions

### ISSUE THREAD

**Issue by cagataygurturk** [facebook/hhvm#4379]
I've a code perfectly working in Zend PHP Engine, but not HHVM.

I use user-defined exceptions to return appropiate HTTP Status codes in my REST API.

I've an exception like this:

```php
namespace Application\Exception;
use \Exception;
class NotLoggedInException extends Exception {
    protected $code = 401;
}
```

Then when it's necessary I throw this exception and catch in another method:

```php
public function update($id, $data) {
        try {
            if (!$this->getLoggedUser()) {
                throw new \Application\Exception\NotLoggedInException();
            }
         } catch (\Exception $e) {
            return $this->throwError($e);
        }

}


 protected function throwError(\Exception $error) {
        
        $response = $this->getResponse();

        $response->getHeaders()->addHeaders(array('Content-Type' => 'application/json'));
        try {
            $response->setStatusCode($error->getCode());
        } catch (\Zend\Http\Exception\InvalidArgumentException $e) {
            $response->setStatusCode(500);
        }
        $response->setContent(json_encode(array('code' => $error->getCode(), 'error' => $error->getMessage(), 'exception' => get_class($error))));
        return $response;
    }

```

But in the last method the getCode always returns "0", it does not see the $code definition in the exception.

When I throw the Exception like this

  throw new \Application\Exception\NotLoggedInException('Test', 401);

getCode() returns 401.

As it's a working code in Zend PHP I think it's a problem specific to HHVM

Version info

HipHop VM 3.4.0 (rel)
Compiler: tags/HHVM-3.4.0-0-g817b3a07fc4e509ce15635dbc87778e5b3496663
Repo schema: 0e12aaa31fae66b5591f65603de50c9d62caafac
Extension API: 20140829

**Comment by apeabody** [comment]
It appears, if this test case is correct, that this issue was resolved prior/in HHVM-3.9.1

https://3v4l.org/hC4hk
