### ISSUE TITLE
Exception getCode() is not final method

### ISSUE THREAD

**Issue by cagataygurturk** [facebook/hhvm#4380]
In original PHP Exception class getCode() has final keyword, not overridable. But in HHVM it can be overriden. It's an incompability.

See: http://3v4l.org/j5h20

Related with #4379

**Comment by cagataygurturk** [comment]
Actually I do not understand why in Zend engine getCode() has final keyword. This incompatibility does not kill any cats in the world. Anyone that knows the rationale of final keyword in Zend engine?

**Comment by paulbiss** [comment]
Since cleaning this up will be a mess, and it's probably not going to matter much in the end I'm going to close this issue. If anyone can think of a good reason this method needs to be final please comment below.
