### ISSUE TITLE
xhprof does not respect ignored_functions

### ISSUE THREAD

**Issue by AaronSchulz** [facebook/hhvm#4385]
The 'ignored_functions' option in http://php.net/manual/en/function.xhprof-enable.php does not appear to be implemented in
https://github.com/facebook/hhvm/blob/000d9ee25869e96f74912771e29e1b10e8660ef8/hphp/runtime/ext/ext_hotprofiler.h .

In PECL xhprof, it is implemented in https://github.com/phacility/xhprof/blob/master/extension/xhprof.c#L717-L734 .

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Closing as support for XHProf has been removed from hhvm: https://github.com/facebook/hhvm/commit/aac7c37fb6dea26186da0571ca14fff674f60427
