### ISSUE TITLE
Add YAML extension to HHVM

### ISSUE THREAD

**Issue by ktamas77** [facebook/hhvm#4387]
http://docs.hhvm.com/manual/en/yaml.installation.php

"This extension is not available in HHVM yet."

**Comment by df2** [comment]
@SiebelsTim  Could you provide more information on how to enable zend_compat. Do I have to compile HHVM manually? I am using version 3.5.0 from the Ubuntu pre-built packages and hhvm.enable_zend_compat = true in /etc/hhvm/php.ini. No effect: "Call to undefined function app\\controllers\\yaml_parse()", or "Call to undefined function yaml_parse()" if I do: return \yaml_parse($yaml); Libyaml 0.1.6 is installed also. Thanks.

**Comment by SiebelsTim** [comment]
@df2 Mh, I can't get it to work with the precompiled package either. My compiled version works though.

Filed https://github.com/hhvm/packaging/issues/99 for it.

**Comment by df2** [comment]
Okay, thanks a lot @SiebelsTim for trying that-- I found out the issue I was having was due to not having the binary compiled for my Ubuntu minor version (14.10). Switching the repo. to 'utopic' and then upgrading hhvm make it work right away. Have updated packaging issue.
