### ISSUE TITLE
Memory leak when E_NOTICE is triggered

### ISSUE THREAD

**Issue by jhammer** [facebook/hhvm#4389]
We are using HHVM for a long-running CLI process (using `-vEval.Jit=true`). There is a loop that executes ~3M times. A handful of E_NOTICE errors (uninitialized variable) were being triggered *each time* through the loop. Our php.ini files has `error_reporting = E_ALL & ~E_NOTICE`.

Before we cleaned up the E_NOTICE errors, we observed that the process would rapidly eat through ~2 GB of heap while executing that loop before being killed. Disabling JIT seemed to fix the problem, or at least make the memory leak small enough that we didn't notice. After fixing the issues that caused the E_NOTICE errors (and re-enabling JIT), the process holds steady at just ~100 MB heap.

This is on current hhvm and hhvm-nightly packages on Ubuntu 14.04.

If it helps, here is our error handler:

```php
set_error_handler(function( $errno, $errstr, $errfile, $errline ){
    if ( !( error_reporting() & $errno ) ) {
        // This error code is not included in error_reporting
        return;
    }
				
    throw new ErrorException( $errstr, 0, $errno, $errfile, $errline );
});
```

**Comment by Orvid** [comment]
This issue has been waiting for more info for more than 2 weeks. Closing for now, feel free to re-open it if you can provide more info.

https://github.com/facebook/hhvm/wiki/Human-Timeouts
