### ISSUE TITLE
Install failed with mac os 10.10 

### ISSUE THREAD

**Issue by mymicroblog** [facebook/hhvm#4391]
cmd:brew install hhvm --HEAD

Hunk #1 FAILED at 1191.
1 out of 1 hunk FAILED -- saving rejects to file hphp/runtime/base/program-functions.cpp.rej
patching file hphp/util/compilation-flags.h
Error: Failure while executing: /usr/bin/patch -g 0 -f -d /private/tmp/hhvm-AxyI0a -p1 -i /private/tmp/hhvm--patch-YH3Oia/3517.diff

**Comment by fredemmott** [comment]
Closing given http://hhvm.com/blog/10043/experimental-mac-os-x-support

**Comment by JoelMarcey** [comment]
Instructions here: https://docs.hhvm.com/hhvm/installation/mac
