### ISSUE TITLE
HHVM can't compatible with woocommerce2.2.X ?

### ISSUE THREAD

**Issue by duoba** [facebook/hhvm#4393]
my environment：CentOS6.5 64bit + nginx1.6  + mysql5.5 + hhvm 3.4  + wordpress4.0.1 + woo2.2.8

issue:Stuck in the settle accounts step.

but woo2.1.12 not this issue.

**Comment by Orvid** [comment]
This issue has been waiting for more info for more than 2 weeks. Closing for now, feel free to re-open it if you can provide more info.

https://github.com/facebook/hhvm/wiki/Human-Timeouts
