### ISSUE TITLE
Memory Limits  / Handling Errors, breaks exec

### ISSUE THREAD

**Issue by TheRyanHowell** [facebook/hhvm#4422]
I've found what seems like a few bugs to do with memory handling / exec, all only seem to happen over fastcgi.
Depending on your config / machine it seems to expose different bugs, but I haven't been able to run it at all without at least one bug appearing.

Below is a test script I've written trying to diagnose a problem in production with not being able to run exec after a while, which I ran on a 8GB and 4GB Ubuntu 14.04 VM running nginx 1.4.6 / 1.6.2 and hhvm 3.4.0.
http://pastebin.com/m8bT2NSc

Bugs I've seen:
- memory_limit completed ignored, from server config or ini_set
- Failure to run exec after certain amount of memory reached (usually ~90%).
- Subsequent requests being unable to run exec at all
- Script never ends, never hitting a limit or failure
- The default memory limit is insane (~9223 PB)

By comparison, standard php5-fpm with nginx runs the command once, hits the default memory limit (128MB).

Might be related to #3340 / #4268

It does hit the memory limit in hhvm 3.3.0, in the nightly it appears to fix everything apart from it doesn't hit the memory limit, and the default memory limit is insane and the command still does fail after a while.

**Comment by amq** [comment]
Memory usage is the only reason why I have switched my Piwik setup back to PHP-FPM.

Memory usage in 4 hours from start with HHVM: 500M
Memory usage with PHP-FPM: 160M

4 threads were configured for both solutions.
