### ISSUE TITLE
Problem with error reporting levels

### ISSUE THREAD

**Issue by pperegrina** [facebook/hhvm#4423]
Hi,

On HHVM 3.4.0 debian wheezy in fastcgi mode behind ngnix, I get tons of Notice and Warning messages in /var/log/hhvm/error.log, where I would like to only see Errors.

Here is my config:
php.ini http://pastebin.com/TTawYGBR
server.ini http://pastebin.com/fHE542RU

And resulting log example:
error.log http://pastebin.com/kMzYKHFk

As you can see I should only see E_ERROR (before that I tried several other combinations, with E_ syntax or plain integer, using http://www.bx.com.au/tools/ultimate-php-error-reporting-wizard, no more luck)

Please could you tell me what I am doing wrong?

Thanks.

**Comment by JoelMarcey** [comment]
@pperegrina What happens if you add `error_reporting=1` to your server.ini?

**Comment by Orvid** [comment]
This issue has been waiting for more info for more than 2 weeks. Closing for now, feel free to re-open it if you can provide more info.

https://github.com/facebook/hhvm/wiki/Human-Timeouts

**Comment by creativeprogramming** [comment]
I've the same issue, no effect with `error_reporting=1` nor in server.ini nor in php.ini.
