### ISSUE TITLE
XML-RPC issue

### ISSUE THREAD

**Issue by mmarleta** [facebook/hhvm#4428]
Hi,

I found an issue with XML-RPC using Magento. 
I'm using:
HipHop VM 3.5.0-dev (rel)

When I try something like this in a python console:

   >> from xmlrpclib import ServerProxy
   >> p = ServerProxy('http://www.mysite.com/index.php/api/xmlrpc')
   >> p.login('user', 'password')

I got this error:
014-12-11T11:24:31+00:00 ERR (3): Warning: Invalid operand type was used: expecting an array  in lib/Zend/XmlRpc/Value.php on line 456
           list($type, $value) = each($xml);

2014-12-11T11:24:31+00:00 ERR (3): Warning: Invalid operand type was used: expecting an array  lib/Zend/XmlRpc/Value.php on line 462
          list($type, $value) = each($namespaceXml);

If I disable hhvm it works as expected.
Could you please help ?

**Comment by surajsanchit** [comment]
Did anyone solve this for their magento installation?

**Comment by 2ps** [comment]
Yes!  You can fix this problem by using a line from the new Zend2 XmlRpc director.  Add this to the top of the `lib/Zend/XmlRpc/Value.php` file’s `_extractTypeAndValue` function:

```php
$xml = (array)$xml;
```

**Comment by paulbiss** [comment]
Closing this as a [documented inconsistency](https://docs.hhvm.com/hhvm/inconsistencies/classes-and-objects#object-internal-cursors), as it sounds like there are some good workarounds already.

**Comment by DavideDyrecta** [comment]
Hi, i've the same error:

2017-05-18T07:48:14+00:00 ERR (3): Warning: Invalid operand type was used: expecting an array  in /var/www/html/lib/Zend/XmlRpc/Value.php on line 492
2017-05-18T07:48:14+00:00 ERR (3): Warning: Invalid operand type was used: expecting an array  in /var/www/html/lib/Zend/XmlRpc/Value.php on line 498

I'm running odoo connect and have problem to connect with hhvm, whit php-fpm all work correctly.

Did anyone solve this problem?

**Comment by 2ps** [comment]
@DavideDyrecta :  What we did to worka round this is to upgrade the XmlRpc directory in Zend to the latest version by just copying and pasting the new files over it.  The bug is in the zend code and it is particularly goofy when you get to it.

**Comment by DavideDyrecta** [comment]
ok, thanks so much, i try upload new Zend2 XmlRpc on magento 1.9.2.4
I upgrade you
