### ISSUE TITLE
Missing Exception Stack Traces In Browser

### ISSUE THREAD

**Issue by joefallon** [facebook/hhvm#4436]
It's not possible to display exception stack traces and other errors in the browser. This makes it exceedingly difficult to use HHVM in a development environment. This is a feature millions upon millions of PHP developers use every single day and is an extremely severe PHP incompatibility.

**Comment by paulbiss** [comment]
I would support a PR to offer this as an optional (defaulted to off) feature, but I don't think anyone is currently working on it.
