### ISSUE TITLE
Minor interop issue with ReflectionParameter

### ISSUE THREAD

**Issue by Seldaek** [facebook/hhvm#4442]
Demo: http://3v4l.org/5ZCMb

ReflectionParameter's constructor throws an `Exception` instead of `ReflectionException`, which actually broke our test suite as we were catching the latter specifically :)

**Comment by JoelMarcey** [comment]
@danslo Did you actually get the `caughtcaught` output that you specified in your patch with @Seldaek's pull request?

We are not. We are just getting `caught`. There is a suggestion from @staabm in #4443 to remedy the problem we are seeing.

**Comment by danslo** [comment]
@JoelMarcey Yeah I didn't actually try @Seldaek's patch, just produced that testcase by reading the code. PHP5 will produce ``caughtcaught``, so the testcase is correct but might not match the patch.
