### ISSUE TITLE
depend on jsonc unconditionally (or at least run tests against it)

### ISSUE THREAD

**Issue by jrobeson** [facebook/hhvm#4452]
The JSON parser currently included with HHVM has to be stripped out of every official package for distributions such as:  Debian, Ubuntu, Fedora, and RHEL/CentOS and thus will end up stripped out of official packages for all their downstreams.

If it truly cannot be removed, then i request that tests be against ext_json linked to jsonc.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Support for the json-c parser has been removed from hhvm. https://github.com/facebook/hhvm/commit/ef919bb81cc2326a24d07bb9b7b7574eced09366
