### ISSUE TITLE
Fatal on user class implementing Traversable directly

### ISSUE THREAD

**Issue by SiebelsTim** [facebook/hhvm#4458]
A class can be traversed through `foreach` if it implements `Traversable`. However you shouldn't be able to have a class implement Traversable directly. You need to implement either `Iterator` or `IteratorAggregate`. We should fail like php does.

I haven't looked into this, but this might be non-trivial (see #3536).

http://3v4l.org/84PLF

``` php
<?php

class X implements Traversable {}

foreach(new X() as $key=>$val) {
    var_dump($val);
}

echo "we got here";
```

**Expect**

```
Fatal error: Class X must implement interface Traversable as part of either Iterator or IteratorAggregate
```

**Actual**

```
we got here
```

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

The `\Traversable` interface has been removed from hhvm in [4.32](https://hhvm.com/blog/2019/11/19/hhvm-4.32.html) and `\HH\Traversable<T>` (the Hack equivalent) is `__Sealed`, so you cannot implement either.
