### ISSUE TITLE
E_USER_DEPRECATED test regression

### ISSUE THREAD

**Issue by bobthecow** [facebook/hhvm#4463]
Ruler's test suite passed in hhvm [as of the last build](https://travis-ci.org/bobthecow/Ruler/builds/35987370), but [it doesn't right now](https://travis-ci.org/bobthecow/Ruler/jobs/44164290).

`Ruler\Operator\Contains` [triggers E_USER_DEPRECATED](https://github.com/bobthecow/Ruler/blob/master/src/Ruler/Operator/Contains.php#L40-L48), and a test case [asserts that a PHPUnit error exception is thrown](https://github.com/bobthecow/Ruler/blob/master/tests/Ruler/Test/RuleBuilder/VariablePropertyTest.php#L158-L186).

Nothing changed between the two test runs. Well, a README did. But no code. Tests continue to pass in PHP 5.3 - 5.6.

**Comment by Orvid** [comment]
This issue has been waiting for more info for more than 2 weeks. Closing for now, feel free to re-open it if you can provide more info.

https://github.com/facebook/hhvm/wiki/Human-Timeouts

**Comment by bobthecow** [comment]
> This issue has been waiting for more info for more than 2 weeks. 

68 weeks more :)
