### ISSUE TITLE
Segfault using ${ENV_VAR} in php.ini

### ISSUE THREAD

**Issue by willdurand** [facebook/hhvm#4469]
Hi.

Following this [documentation section](http://docs.hhvm.com/manual/en/configuration.file.php), I set the following server variable in my `/etc/hhvm/php.ini` file:

```
hhvm.server_variables[SYMFONY_ENV] = ${SYMFONY_ENV}
```

Running `hhvm` (3.4.1) then leads to the following output, which is... not really helpful unfortunately (sorry for that):

```
Segmentation fault
```

Setting an hardcoded value works though (like `dev` rather than `${SYMFONY_ENV}`). Is there anything to do/ensure in order to pass system env variables to `hhvm`?

William

**Comment by Orvid** [comment]
Is this still an issue?

**Comment by paulbiss** [comment]
This issue has been waiting for more info for more than 2 weeks. I'm closing it for now, but feel free to re-open it if you can provide more info. https://github.com/facebook/hhvm/wiki/Human-Timeouts
