### ISSUE TITLE
Libgeos not supported in HHVM

### ISSUE THREAD

**Issue by TouriSpo** [facebook/hhvm#4479]
I was able to use LibGeos (http://download.osgeo.org/geos/) with Zend Engine by following tutorials like these: http://www.saintsjd.com/2014/06/05/howto-intsall-libgeos-with-php5-bindings-ubuntu-trusty-14.04.html

After switching to HHVM I cannot see any way how to use LibGeos. Is there a ways to use LibGeos with HHVM?

Thanks in advance 
Martin

**Comment by paulbiss** [comment]
This feature request is not actively being worked on. We would happily consider a pull request implementing it. If you plan to work on this issue let us know in the comments and we will re-open the issue and assign it to you. If you feel strongly that this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
