### ISSUE TITLE
Suggestion: Case sensitive keywords

### ISSUE THREAD

**Issue by Aatch** [facebook/hhvm#4483]
PHP has case insensitive keywords. This is crazy. It also means that many names for classes, traits and types are invalid because they parse as keywords.

It would be nice if Hack undid this and changed to using only lowercase keywords. Personally, I've never seen anybody use keywords in any form other than their lowercase one. Nowhere in PEAR can I find a case of it. I doubt many people even realise PHP can do this until they hit a parsing error.

**Comment by paulbiss** [comment]
As we still need to support PHP I'm not sure there's a particularly sane way for us to do this. I would be okay with a flag that can switch the behavior in the scanner, but it doesn't seem like something we'd prioritize adding ourselves.
