### ISSUE TITLE
Make it work on Windows! Please...!

### ISSUE THREAD

**Issue by raeesiqbal** [facebook/hhvm#4493]
Hello, I've been writing in Hack from month with @steelbrain and it is an awesome project.

I've been using Windows from a long time and cannot convert to Ubuntu or any other just because I want to use HHVM, so, I'm using HHVM through a Ubuntu virtual machine. But there are a lot of downsides to it, it is slow, the kernel events on files dont work so I cannot use hh_client. And for the same reason I cannot use Autocomplete plugin for Atom or the syntax checker. It is painful.

Now I'm sure a lot of other people on Windows are doing the same or similar to use HHVM (@steelbrain has done it for a long time). I'm using it to write a website engine like WordPress in Hack, it is called [QuickPress](https://github.com/raeesiqbal/QuickPress), its not complete yet but it processes a page in ~4ms and is not good enough because I cannot use Syntax checking or Autocomplete or anyother great features in my editor.

I know that you are very awesome people and you CAN make this happen, so, please make it work on cygwin. (if you wish) I'll send you some chocolates also, if thee can make this dream come true.

**Comment by steelbrain** [comment]
@wjywbs, more errors, this time with tbb :smile: https://gist.github.com/steelbrain/619a9dcafc4441ac0c4f

**Comment by wjywbs** [comment]
I did mention this above: If it has errors about undefined function "tbb::..." when linking, `vi hphp/hhvm/CMakeFiles/hhvm.dir/link.txt` and add `-ltbb -L/bin`.

**Comment by steelbrain** [comment]
@wjywbs, Thanks for your awesome work. I've updated the wiki according to include your method. and I guess this issue should be closed now.

**Comment by raeesiqbal** [comment]
Future visitors can use the [Building and Installing HHVM on Cygwin](https://github.com/facebook/hhvm/wiki/Building-and-Installing-HHVM-on-Cygwin) guide. It has been updated.

**Comment by wjywbs** [comment]
I uploaded the following patches for building hhvm 3.6.0 in cygwin:

hhvm_360_win.diff
folly_360_win.diff
squangle_360_win.diff
third_party_360_win.diff
thrift_360_win.diff

https://gist.github.com/wjywbs/a417b98644dc9d6fdc85

Jit works partially. Mcrouter is disabled. Async mysql extension can build, but I didn't test it. Closures may crash hhvm.
