### ISSUE TITLE
mbfilter.c constantly being recompiled

### ISSUE THREAD

**Issue by rrh** [facebook/hhvm#4502]
Every build in OSS land at/near head recompiles mbfilter.c each time, even though my incremental change is in a completely unrelated piece of code:
  Building C object third-party/libmbfl/mbfl/CMakeFiles/mbfl.dir/mbfilter.c.o

**Comment by jrobeson** [comment]
it doesn't do that in the upstream version of libmbfl: https://github.com/moriyoshi/libmbfl/blob/master/mbfl/CMakeLists.txt

**Comment by JoelMarcey** [comment]
@rrh I will look at fixing this. Basically `eaw_table.h` is a generated file that we don't keep as part of our github repo. However it is also part of the `make clean` process too. So when you do a `make clean` before rebuilding, it regenerates the file.

That said, there is no check to see if `eaw_table.h` exists. So when you run cmake, it assumes that we need to generate this file all the time and build it.

So, we can instead create a generate script that checks for the file and creates it. That way that check is run all the time and should stop the constant rebuilding even with incremental builds.

cc: @jwatzman

**Comment by jrobeson** [comment]
so does that mean this can be closed now as soon as you update the submodule reference?

**Comment by JoelMarcey** [comment]
@jrobeson Yep. I will be landing that today.
