### ISSUE TITLE
could not access PID file for hhvm [Ubuntu 12.04]

### ISSUE THREAD

**Issue by brianveltman** [facebook/hhvm#4518]
Just installed hhvm 3.4.2 on Ubuntu 12.04 using apt-get install hhvm and bumped into starting issues when executing: sudo service hhvm start

Tried on Ubuntu 14.04 and there were no issues at all, works pretty smooth.

**Comment by paulbiss** [comment]
Could you be more specific about the issue? I assume the error message is the title of this issue, is the PID file being created in a non-existent location, or with bad permissions, or just not at all?

**Comment by davidbitton** [comment]
i just resolved an issue with `Unable to open pid file /var/run/hhvm.pid for write`. My machine is an AWS m3.medium EC2 instance seeded with an AWS Marketplace CentOS 7 AMI.

*AMI Instance details:*
```
CentOS 7 (x86_64) with Updates HVM
CentOS 7 x86_64 (2014_09_29) EBS HVM
Root Device Type: ebs Virtualization type: hvm
```
#### Evidence
HHVM generates the following error output. I noticed this while in the process of tightening up the `hhvm.service` systemd config file.
```
Unable to open pid file /var/run/hhvm.pid for write
```
#### Issue
HHVM is switching users from `root` to whatever is specified on the command line

*Typical launch command:*
```
/usr/local/bin/hhvm --config /etc/hhvm/server.ini --user nginx --mode daemon
```
#### Resolution
... be right back... 21:56:00 EDT

**Comment by paulbiss** [comment]
When a server user is specified we setuid [here](https://github.com/facebook/hhvm/blob/d326199e5c0f982a9ed31ec9995fdba857039664/hphp/runtime/base/program-functions.cpp#L917-L918) but the PID file isn't created until the server is started [here](https://github.com/facebook/hhvm/blob/d326199e5c0f982a9ed31ec9995fdba857039664/hphp/runtime/base/program-functions.cpp#L977) and creates the PID file [here](https://github.com/facebook/hhvm/blob/d326199e5c0f982a9ed31ec9995fdba857039664/hphp/runtime/server/http-server.cpp#L314).

We could move the PID file creation out into program-functions and call it before privilege deescalation, but from a security standpoint the current behavior may be preferable. I don't have a strong opinion here.

**Comment by davidbitton** [comment]
I neglected to include my HHVM build version.
```
HipHop VM 3.6.1-dev (rel)
Compiler: heads/HHVM-3.6-0-ge70948b2907531350bf716af33562d69f780c024
Repo schema: cc8a58a7565cd6e21a61a89c5649566838fef4d6
```
