### ISSUE TITLE
Array type aliases with default values throw fatals

### ISSUE THREAD

**Issue by milesj** [facebook/hhvm#4519]
As shown here: http://3v4l.org/MVg9l

**Comment by milesj** [comment]
Any update on this?

**Comment by JoelMarcey** [comment]
@jwatzman Is this expected behavior in Hack, or is this an HHVM bug?

**Comment by jwatzman** [comment]
This looks like an HHVM bug to me.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Your repro works as expected in hhvm 4.56. No Throwable is thrown.
