### ISSUE TITLE
HHVM_VERSION_ID was not updated for 3.4.2

### ISSUE THREAD

**Issue by jrobeson** [facebook/hhvm#4521]
FAILED: hphp/test/slow/constant/version.php
004+ HHVM_VERSION does NOT match HHVM_VERSION_ID, please make sure update both of them
004- HHVM_VERSION matches HHVM_VERSION_ID

hopefully it will be updated for 3.4.3, when it is released.

**Comment by jrobeson** [comment]
the main problem in this ticket is resolved. I'd suggest you file another ticket (in your own words) about updating the CONTRIBUTING.md file.

**Comment by jwatzman** [comment]
`CONTRIBUTING.md` updated, I think everything here has been addressed.
