### ISSUE TITLE
DOMDocument::createDocumentFragment() not returning DOMDocumentFragment

### ISSUE THREAD

**Issue by bacinsky** [facebook/hhvm#4525]
Seems like iterating childNodes where one is element and another text node within custom DOM element class method, following by nodeValue = '', breaks the createDocumentFragment() method. Because it returns object of a custom element class type instead of DOMDocumentFragment.

```php
<?php

class NewDomElement extends DOMElement {
    function foo () {
        foreach ($this->childNodes as $childNode) {}
    }
}

$dom = new DomDocument;
$dom->registerNodeClass('DOMElement', 'NewDomElement');
$dom->loadHtml('<div><span/>text</div>'); // this is important !!! text node after element node

$node = $dom->getElementsByTagName('div')->item(0);
$node->foo();
$node->nodeValue = '';
$frag = $node->ownerDocument->createDocumentFragment();
echo get_class($frag); // Expected DOMDocumentFragment instead of NewDomElement
```

**Comment by paulbiss** [comment]
Looks like recent versions of HHVM are now matching PHP 5 and 7. There was a rewrite of the DOMDocument extension which likely fixed this problem.
