### ISSUE TITLE
Could not resolve host

### ISSUE THREAD

**Issue by duyazhe** [facebook/hhvm#4528]
we use HHVM/3.2.0 online,sometimes i see the curl error and error info is 'Could not resolve host: (nil); Unknown error'.why?

**Comment by paulbiss** [comment]
We aren't supporting 3.2 anymore unfortunately. Do you see these same problems with 3.3 (our LTS release) or 3.4 (our most recent release)?

**Comment by fredemmott** [comment]
https://github.com/facebook/hhvm/wiki/Human-Timeouts
