### ISSUE TITLE
What does "Unable to stat file" mean?

### ISSUE THREAD

**Issue by hwongcom** [facebook/hhvm#4532]
I did...
    hhvm --hphp --target hhbc --input-list /tmp/files.list -o /var/www/hhbc -k1 -l3
saw
    Unable to stat file...

crashed. how do I see more errors?

**Comment by Orvid** [comment]
This issue has been waiting for more info for more than 2 weeks. Closing for now, feel free to re-open it if you can provide more info.

https://github.com/facebook/hhvm/wiki/Human-Timeouts
