### ISSUE TITLE
What version of libxml2 HHVM needs?

### ISSUE THREAD

**Issue by lokeshhctm** [facebook/hhvm#4543]

**Comment by jrobeson** [comment]
i don't know the exact version, but the one in distros such as CentOS 6.x seems sufficient.

**Comment by paulbiss** [comment]
We don't search for a particular version in our cmake configuration. @lokeshhctm are you having issues with the version you're building with?

**Comment by fredemmott** [comment]
Closing - needs more info > 2 weeks: https://github.com/facebook/hhvm/wiki/Human-Timeouts
