### ISSUE TITLE
Not found HHVM

### ISSUE THREAD

**Issue by eva-phuc** [facebook/hhvm#4549]
Hi,

I had installed hhvm on centos 6.4

[Building and installing HHVM on centos 6.4](https://github.com/facebook/hhvm/wiki/Building-and-installing-HHVM-on-CentOS-6.4)

But I can't find hhvm in /etc/init.d/.

**Comment by jrobeson** [comment]
hhvm doesn't ship an init file for centos, you'll have to find your own somewhere. I know some exist, but i have no link.

**Comment by JoelMarcey** [comment]
@eva-phuc Maybe I am misunderstanding, and please re-open if I am, but if you built HHVM from scratch, the `hhvm` executable will be in `<path to hhvm source code>/hphp/hhvm/hhvm`

If you just installed hhvm via some sort of package (i.e., https://github.com/facebook/hhvm/wiki/Prebuilt-Packages-on-Centos-6.x), then you should check for the `hhvm` executable in `/usr/bin/hhvm`

Btw, `hhvm-fastcgi` could be in `/etc/init.d` depending on what you installed, but that may not be related to this.
