### ISSUE TITLE
mysqli_begin_transaction should supply default parameters

### ISSUE THREAD

**Issue by jhammer** [facebook/hhvm#4553]
`mysqli_begin_transaction` is missing default parameters for `$flags` and `$name`. PHP declares the function as:

```php
bool mysqli_begin_transaction ( mysqli $link [, int $flags [, string $name ]] )
```
but HHVM incorrectly requires `$flags` and `$name` parameters:
```hh
function mysqli_begin_transaction(mysqli $link,
                                  int $flags,
                                  string $name): bool {
  return $link->begin_transaction($flags, $name);
}
```

**Comment by Stelian** [comment]
@jhammer the php.net documentation does not actually have the default values for the flags and name, will look into the code and see what they use as defaults.

**Comment by Stelian** [comment]
So, php defines the function as follows in /PHP_5_6/ext/mysqli/mysqli_nonapi.c
```c
PHP_FUNCTION(mysqli_begin_transaction)
{
	MY_MYSQL	*mysql;
	zval		*mysql_link;
	long		flags = TRANS_START_NO_OPT;
	char *		name = NULL;
	int			name_len = -1;
	zend_bool	err = FALSE;

	if (zend_parse_method_parameters(ZEND_NUM_ARGS() TSRMLS_CC, getThis(), "O|ls", &mysql_link, mysqli_link_class_entry, &flags, &name, &name_len) == FAILURE) {
		return;
	}
	MYSQLI_FETCH_RESOURCE_CONN(mysql, &mysql_link, MYSQLI_STATUS_VALID);
	if (flags < 0) {
		php_error_docref(NULL TSRMLS_CC, E_WARNING, "Invalid value for parameter flags (%ld)", flags);
		err = TRUE;
	}
	if (!name_len) {
		php_error_docref(NULL TSRMLS_CC, E_WARNING, "Savepoint name cannot be empty");
		err = TRUE;
	}
	if (TRUE == err) {
		RETURN_FALSE;			
	}
	
#if !defined(MYSQLI_USE_MYSQLND)
	if (mysqli_begin_transaction_libmysql(mysql->mysql, flags, name TSRMLS_CC)) {
		RETURN_FALSE;
	}
#else
	if (FAIL == mysqlnd_begin_transaction(mysql->mysql, flags, name)) {
		RETURN_FALSE;
	}
#endif
	RETURN_TRUE;
}
```
and `TRANS_START_NO_OPT` is defined in /PHP_5_6/ext/mysqli/mysqli_libmysql.h as 
```c
#define TRANS_START_NO_OPT                      0
```

With this in mind, I will attempt a pull request with 0 and null as default parameters, not sure if tests will pass though or if anything else might be affected.

**Comment by Stelian** [comment]
@JoelMarcey can this be closed? Phabricator says the commit has landed, a bit confused on where and how.

**Comment by paulbiss** [comment]
Ah, our bot didn't understand "Covers #4553", if you add "Closes #XXXX" to your summary we'll auto-close the issue.

**Comment by SiebelsTim** [comment]
Not to be pedantic, but it's actually github itself who closes issues when in one of these formats:

- close
- closes
- closed
- fix
- fixes
- fixed
- resolve
- resolves
- resolved

**Comment by paulbiss** [comment]
@SiebelsTim: heh, TIL.
