### ISSUE TITLE
overboxing in zend_API.c

### ISSUE THREAD

**Issue by rrh** [facebook/hhvm#4554]
https://github.com/facebook/hhvm/commit/091d00c2cc9942ea740baef445f9726db04d74a2
near line 1637 of zend_API.cpp added a call
  tvBox(prop);
without first checking if prop is already boxed.

**Comment by paulbiss** [comment]
@rrh want to submit that as a PR? :)

**Comment by rrh** [comment]
yes.  still recovering from 2 chopped up weeks...
