### ISSUE TITLE
Process exited with code 153.

### ISSUE THREAD

**Issue by j0101s** [facebook/hhvm#4555]
http://3v4l.org/brar6

**Comment by JoelMarcey** [comment]
This may have been a bug in earlier versions, but we are compatible with PHP 5.x, etc. and consistent in recent versions of HHVM

**Comment by SjonHortensius** [comment]
This is a bug on my server; I have been searching but cannot find what causes this.. Anyone who knows why hhvm would exit with code 153?

**Comment by Pacerier** [comment]
For Exit code 153, see the live run on http://stackoverflow.com/q/17528280/632951

Also http://3v4l.org/vMp25

**Comment by SjonHortensius** [comment]
I have no clue why/when hhvm exits with this code, I have removed additional versions to prevent this from happening
