### ISSUE TITLE
Problem installing from source on centos 7 

### ISSUE THREAD

**Issue by rawmaterials** [facebook/hhvm#4557]
[root@myhost hhvm]# cmake \
> -DLIBMAGICKWAND_INCLUDE_DIRS="/usr/include/ImageMagick-6" \
> -DLIBMAGICKCORE_LIBRARIES="/usr/lib64/libMagickCore-6.Q16.so" \
> -DLIBMAGICKWAND_LIBRARIES="/usr/lib64/libMagickWand-6.Q16.so" .
-- Build type not specified: cmake build type Release.
-- Boost version: 1.53.0
-- Found the following Boost libraries:
--   system
--   program_options
--   filesystem
-- MySQL Include dir: /usr/include/mysql  library dir: /lib64/mysql
-- MySQL client libraries: mysqlclient_r
-- Found libevent: /usr/lib64/libevent.so
-- Found libsqlite3: /usr/lib64/libsqlite3.so
-- Could NOT find DOUBLE_CONVERSION (missing:  DOUBLE_CONVERSION_LIBRARY DOUBLE_CONVERSION_INCLUDE_DIR)
-- Using third-party bundled double-conversion
-- Found LZ4: /usr/lib64/liblz4.so
-- libzip is too old, found 0.10.1 and we need 0.11+, using third-party bundled libzip
-- Found ICU header files in /usr/include
-- Found ICU libraries: /usr/lib64/libicuuc.so
-- Found jemalloc: /usr/lib64/libjemalloc.so
-- Found Intel TBB
-- Found mcrypt: /usr/lib64/libmcrypt.so
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_LIBRARIES
  OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindOpenSSL.cmake:313 (find_package_handle_standard_args)
  CMake/HPHPFindLibs.cmake:285 (find_package)
  CMake/HPHPSetup.cmake:97 (include)
  third-party/CMakeLists.txt:18 (include)

-- Configuring incomplete, errors occurred!

**Comment by rawmaterials** [comment]
[root@myhost hhvm]# yum install libzip
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.rit.edu
 * epel: mirrors.einstein.yu.edu
 * extras: mirrors.lga7.us.voxel.net
 * updates: mirrors.mit.edu
Package libzip-0.10.1-8.el7.x86_64 already installed and latest version
Nothing to do
[root@myhost hhvm]# yum install openssl
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.rit.edu
 * epel: mirrors.einstein.yu.edu
 * extras: mirrors.lga7.us.voxel.net
 * updates: mirrors.mit.edu
Package 1:openssl-1.0.1e-34.el7_0.6.x86_64 already installed and latest version
Nothing to do

**Comment by rawmaterials** [comment]
more info .

Linux myhost 3.10.0-123.8.1.el7.x86_64 #1 SMP Mon Sep 22 19:06:58 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Majkl578** [comment]
You need development packages for OpenSSL, not sure how it's called on Centos, look for a package called openssl-dev/openssl-devel.

**Comment by jrobeson** [comment]
libzip is too old on centos7 so don't bother trying to install it. If you're interested in testing a prebuilt package, checkout my repository: https://copr.fedoraproject.org/coprs/jrobeson/hhvm/

**Comment by sandeepone** [comment]
Pre built packages are available from my repo
http://yum.gleez.com/7/x86_64/repoview/hhvm.html

**Comment by jrobeson** [comment]
@sandeepone : your package seems to clobber system libraries. You shouldn't be installing imagemagick, glog, or anything like that in the hhvm package.

**Comment by sandeepone** [comment]
They wont affect system libraries. They are installed in hhvm sub folder.
So they are linked only to hhvm binary not other binaries.

**Comment by jrobeson** [comment]
there's no need for it in any case @sandeepone : my repo does not have them at all

**Comment by ck-on** [comment]
I have zero problems building on CentOS 7. 

https://ckon.wordpress.com/2014/07/18/hhvm-centos-7/

**Comment by apeabody** [comment]
This is a rather old thread, but a quick note that I currently/frequently/successfully build HHVM master on CentOS 7. I try to keep this particular page updated: https://github.com/facebook/hhvm/wiki/Building-and-installing-hhvm-on-CentOS-7.x
