### ISSUE TITLE
Add silex to the list of supported frameworks

### ISSUE THREAD

**Issue by Stelian** [facebook/hhvm#4561]
Disclosure: I do not own or am I in any way connected to the silex framework, this is just a user request.

Silex is one of the most popular micro frameworks out there and it would be nice to have it in the list of supported frameworks. Github page: https://github.com/silexphp/Silex

**Comment by JoelMarcey** [comment]
@Stelian I commented on the PR, but you need to add the `.expect` file from the framework run to the PR too.

**Comment by Stelian** [comment]
@JoelMarcey I will come back to this PR since there seem to be some issues with the tests in the 1.2 (latest stable) branch of Silex, mostly caused by deprecation warning. 

I have opened an issue there and looking into checking which would be the correct approach for fixing those first: https://github.com/silexphp/Silex/issues/1085

**Comment by fredemmott** [comment]
Seems to be resolved
