### ISSUE TITLE
Add Yii2 to supported frameworks

### ISSUE THREAD

**Issue by pcfreak30** [facebook/hhvm#4563]
Yii2 is now production ready and should be added.

https://github.com/yiisoft/yii2

**Comment by steelbrain** [comment]
https://reviews.facebook.net/D30879

**Comment by JoelMarcey** [comment]
@steelbrain I commented on the PR as well; you need to add the `.expect` file from the framework run to the PR too.

**Comment by RdeWilde** [comment]
Where did this go? I don't see it in the list, only Yii1
