### ISSUE TITLE
array_multisort does not work correctly with SORT_DESC and SORT_NATURAL

### ISSUE THREAD

**Issue by lorenzo** [facebook/hhvm#4567]
Please take a look to this script http://3v4l.org/ftFM8

You can see there that HHVM is not able to sort correctly in descending order, unlike zend's implementation.

**Comment by WizKid** [comment]
I think the problem is https://github.com/facebook/hhvm/blob/cbeea88ed6355a80fb6858d158552a62f97d4db2/hphp/runtime/ext/array/ext_array.cpp#L2569-2572 . It doesn't care about the ascending flag that is passed in for natural sort

**Comment by reeze** [comment]
I didn't add automatic close tag in my commit, this was fixed, could you please close it?
