### ISSUE TITLE
error 4 in hhvm  (segfault) 3.5.0-dev

### ISSUE THREAD

**Issue by ck-on** [facebook/hhvm#4571]
Not sure how to report this in a useful way but since it happens every other hour I can get more info if helpful.

Linux 3.10.0-123.13.2.el7.x86_64 #1 SMP x86_64   (CentOS7)

Built trunk last night:

     Jan  4 08:21:15 srv123 kernel: [76213.809416] hhvm[11966]: segfault at 0 ip 000000000205784f sp 00007f48a03f8540 error 4 in hhvm[400000+26b6000]
     Jan  4 08:21:15 srv123 kernel: hhvm[11966]: segfault at 0 ip 000000000205784f sp 00007f48a03f8540 error 4 in hhvm[400000+26b6000]
     Jan  4 08:21:15 server21 systemd: hhvm.service: main process exited, code=killed, status=11/SEGV
     Jan  4 08:21:15 server21 systemd: Unit hhvm.service entered failed state.

**Comment by ck-on** [comment]
Many more crashes, like once every hour now.

A couple have extra info in that they mention libonig

     Jan  4 21:40:02  kernel: [124184.845837] hhvm[24813]: segfault at 7f6200000008 ip 00007f629b22b1a4 sp 00007f6271ff9650 error 4 in libonig.so.2.0.0[7f629b21f000+70000]
     Jan  4 22:11:40  kernel: [126084.940904] hhvm[27131]: segfault at 7fd400000009 ip 00007fd4a85d8edc sp 00007fd48aff9680 error 4 in libonig.so.2.0.0[7fd4a85c9000+70000]

**Comment by Majkl578** [comment]
Can you build a debug version (using cmake -DCMAKE_BUILD_TYPE=Debug`) and post a backtrace? Also a repro script would be nice.

**Comment by ck-on** [comment]
I updated oniguruma from 5.9.5 to 5.9.6 and updated the trunk copy by 24 hours and no crashes for 24 hours.

So problem solved, somehow.

This ticket can be closed.
