### ISSUE TITLE
cal_days_in_month

### ISSUE THREAD

**Issue by patstuart** [facebook/hhvm#4572]
My installation of hhvm is reporting that `cal_days_in_month` doesn't exist as a function. 

Apologies if this is an environment issue; not sure what it would be though.

Details:
test.php:

    <?php 
    var_dump( cal_days_in_month(CAL_GREGORIAN, 2, 2014));

Output:

    Fatal error: Call to undefined function cal_days_in_month() in /****/test.php on line 2

Installation details, Ubuntu 14.04 x64:

    HipHop VM 3.4.2 (rel)
    Compiler: tags/HHVM-3.4.2-0-g40d85d7386b3342ab848fc45c6892433c89ef5b2
    Repo schema: 13cba877c4300d1d0481b3f40eb128a5115d4e08
    Extension API: 20140829

**Comment by steelbrain** [comment]
I can confirm this behavior of HHVM on 3.5.0-dev nightly build.

**Comment by SiebelsTim** [comment]
Make sure to enable the compat layer.
http://docs.hhvm.com/manual/en/configuration.zend.compat.php

**Comment by paulbiss** [comment]
@SiebelsTim is correct, if you enable the compat layer this function should be available.

**Comment by patstuart** [comment]
This did indeed cause the function to report the correct value. Not sure if this is still a bug or not, so I'm leaving it open.

**Comment by JoelMarcey** [comment]
@patstuart It is not a bug. Some functions haven't been directly baked into HHVM, and the Zend Compatibility Layer is one way we came up with to help fill the gap. Implementing these directly in HHVM would be a nice to have, but at this point is a wishlist item. Of course, a pull request would be welcomed. I would think that many of these could be implemented in PHP in `hphp/system/php` via https://github.com/facebook/hhvm/wiki/Extension-API#php-only-extensions

Glad you got it working :)
