### ISSUE TITLE
Verification Error only machine (use RepoAuthoritative )

### ISSUE THREAD

**Issue by huzhiguang** [facebook/hhvm#4582]
Other machines running is no problem to use RepoAuthoritative, only run a virtual machine has a problem.

Compile command:

    ~/all_project/hhvm-3.0.1/public/hhvm/hhvm-src-301-debug/hhvm-HHVM-3.0.1/hphp/hhvm/hhvm --hphp -thhbc -o tmphhbc test_main.php 

hdf conf : 
    
     	Server {
	    Port = 8083
	    IP = 0.0.0.0
	    ThreadCount = 128
	    FatalErrorMessage = error_message
	    DefaultDocument = index.php
	    SourceRoot = /mnt/huzhiguang/data/test
	    IncludeSearchPaths {
	          * = /mnt/huzhiguang/data/test
	    }
	}
	
	Eval {
	    Jit = true
	    JitWarmupRequests = 0
	}
	
	
	Repo {
	  Authoritative = true
	  Central {
	      Path = /mnt/huzhiguang/data/test/tmphhbc/hhvm.hhbc
	
	     }
	}
	
	AdminServer {
	  Port = 8084
	}

debug and release hhvm will crash in this machine (only in this machine)
debug hhvm run error:

		mapping self...
		mapping self took 0'00" (31815 us) wall time
		loading static content...
		loading static content took 0'00" (1 us) wall time
		Verification Error (unit systemlib.php func stream_bucket_new): region fpi 114922:114945 boundaries are inbetween instructions
		Verification Error (unit systemlib.php func filter_has_var): region fpi 115091:115141 boundaries are inbetween instructions
		Verification Error (unit systemlib.php func filter_input): label dv-entry 115652 is not on a valid instruction boundary
		Verification Error (unit systemlib.php func filter_input): label dv-entry 115663 is not on a valid instruction boundary
		Verification Error (unit systemlib.php func _filter_var_array_single): label dv-entry 115880 is not on a valid instruction boundary
		Verification Error (unit systemlib.php func filter_var_array): label dv-entry 116785 is not on a valid instruction boundary
		Verification Error (unit systemlib.php func filter_var_array): label dv-entry 116795 is not on a valid instruction boundary
		Verification Error (unit systemlib.php func filter_var_array): region fpi 115916:115966 boundaries are inbetween instructions
		Verification Error (unit systemlib.php func filter_var_array): region fpi 116071:116101 boundaries are inbetween instructions
		Verification Error (unit systemlib.php func filter_var_array): region fpi 116313:116340 boundaries are inbetween instructions
		.......................................
		Verification Error (unit systemlib.php.zip func addPattern): label dv-entry 627 is not on a valid instruction boundary
		Verification Error (unit systemlib.php.zip func addPattern): label dv-entry 641 is not on a valid instruction boundary
		Verification Error (unit systemlib.php.zlib func gzencode): label dv-entry 210 is not on a valid instruction boundary
		Verification Error (unit systemlib.php.zlib func gzgetss): label dv-entry 322 is not on a valid instruction boundary
		Verification Error (unit systemlib.php.zlib func gzputs): label dv-entry 465 is not on a valid instruction boundary
		Verification Error (unit systemlib.php.zlib func gzseek): label dv-entry 532 is not on a valid instruction boundary
		page server started
		admin server started
		all servers started

test_main.php

	<?php
	
	function main() {
	    echo "hello";
	}
	main();

To access test_main.php will crash,crash stack:

	# 0  bt_handler at /mnt/huzhiguang/all_project/hhvm-3.0.1/public/hhvm/hhvm-src-301-debug/hhvm-HHVM-3.0.1/hphp/runtime/base/crash-reporter.cpp:63
	# 1  __restore_rt at sigaction.c:0
	# 2  __GI_raise at :0
	# 3  __GI_abort at :0
	# 4  __assert_fail_base at :0
	# 5  __GI___assert_fail at :0
	# 6  HPHP::LitstrTable::lookupNamedEntityPairId(int) const at /mnt/huzhiguang/all_project/hhvm-3.0.1/public/hhvm/hhvm-src-301-debug/hhvm-HHVM-3.0.1/hphp/runtime/vm/unit
	.h:1005
	# 7  HPHP::Unit::lookupNamedEntityPairId(int) const at /mnt/huzhiguang/all_project/hhvm-3.0.1/public/hhvm/hhvm-src-301-debug/hhvm-HHVM-3.0.1/hphp/runtime/vm/unit.h:483
	# 8  HPHP::ExecutionContext::iopFPushFuncD(unsigned char const*&) at /mnt/huzhiguang/all_project/hhvm-3.0.1/public/hhvm/hhvm-src-301-debug/hhvm-HHVM-3.0.1/hphp/runtime/
	vm/bytecode.cpp:5629
	# 9  void HPHP::ExecutionContext::dispatchImpl<2>(int) at /mnt/huzhiguang/all_project/hhvm-3.0.1/public/hhvm/hhvm-src-301-debug/hhvm-HHVM-3.0.1/hphp/runtime/vm/bytecode
	.cpp:7643
	# 10 HPHP::ExecutionContext::dispatchBB() at /mnt/huzhiguang/all_project/hhvm-3.0.1/public/hhvm/hhvm-src-301-debug/hhvm-HHVM-3.0.1/hphp/runtime/vm/bytecode.cpp:7686
	# 11 HPHP::JIT::MCGenerator::enterTC(unsigned char*, void*) at /mnt/huzhiguang/all_project/hhvm-3.0.1/public/hhvm/hhvm-src-301-debug/hhvm-HHVM-3.0.1/hphp/runtime/vm/jit
	/mc-generator.cpp:1157
	# 12 HPHP::JIT::MCGenerator::enterTCAfterPrologue(unsigned char*) at /mnt/huzhiguang/all_project/hhvm-3.0.1/public/hhvm/hhvm-src-301-debug/hhvm-HHVM-3.0.1/hphp/runtime/
	vm/jit/mc-generator.h:305
	# 13 HPHP::ExecutionContext::enterVMAtFunc(HPHP::ActRec*) at /mnt/huzhiguang/all_project/hhvm-3.0.1/public/hhvm/hhvm-src-301-debug/hhvm-HHVM-3.0.1/hphp/runtime/vm/bytec
	ode.cpp:1552
	# 14 HPHP::ExecutionContext::enterVM(HPHP::ActRec*) at /mnt/huzhiguang/all_project/hhvm-3.0.1/public/hhvm/hhvm-src-301-debug/hhvm-HHVM-3.0.1/hphp/runtime/vm/bytecode.cp
	p:1600
	# 15 HPHP::ExecutionContext::invokeFunc(HPHP::TypedValue*, HPHP::Func const*, HPHP::Variant const&, HPHP::ObjectData*, HPHP::Class*, HPHP::VarEnv*, HPHP::StringData*, H
	PHP::ExecutionContext::InvokeFlags) at /mnt/huzhiguang/all_project/hhvm-3.0.1/public/hhvm/hhvm-src-301-debug/hhvm-HHVM-3.0.1/hphp/runtime/vm/bytecode.cpp:1807
	# 16 HPHP::ExecutionContext::invokeUnit(HPHP::TypedValue*, HPHP::Unit*) at /mnt/huzhiguang/all_project/hhvm-3.0.1/public/hhvm/hhvm-src-301-debug/hhvm-HHVM-3.0.1/hphp/ru
	ntime/vm/bytecode.cpp:1960
	# 17 HPHP::invoke_file_impl(HPHP::Variant&, HPHP::String const&, bool, char const*) at /mnt/huzhiguang/all_project/hhvm-3.0.1/public/hhvm/hhvm-src-301-debug/hhvm-HHVM-3
	.0.1/hphp/runtime/base/builtin-functions.cpp:855
	# 18 HPHP::invoke_file(HPHP::String const&, bool, char const*) at /mnt/huzhiguang/all_project/hhvm-3.0.1/public/hhvm/hhvm-src-301-debug/hhvm-HHVM-3.0.1/hphp/runtime/bas
	e/builtin-functions.cpp:836
	# 19 HPHP::include_impl_invoke(HPHP::String const&, bool, char const*) at /mnt/huzhiguang/all_project/hhvm-3.0.1/public/hhvm/hhvm-src-301-debug/hhvm-HHVM-3.0.1/hphp/run
	time/base/builtin-functions.cpp:819
	# 20 HPHP::hphp_invoke(HPHP::ExecutionContext*, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, HPHP::Array const&, HPHP::VRefParam
	Value const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > cons
	t&, bool&, std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, bool, bool, bool) at /mnt/huzhiguang/all_project/hhvm-3.0.1/public/hhvm/hhvm-src-301
	-debug/hhvm-HHVM-3.0.1/hphp/runtime/base/program-functions.cpp:1691
	# 21 HPHP::HttpRequestHandler::executePHPRequest(HPHP::Transport*, HPHP::RequestURI&, HPHP::SourceRootInfo&, bool) at /mnt/huzhiguang/all_project/hhvm-3.0.1/public/hhvm
	/hhvm-src-301-debug/hhvm-HHVM-3.0.1/hphp/runtime/server/http-request-handler.cpp:360
	# 22 HPHP::HttpRequestHandler::handleRequest(HPHP::Transport*) at /mnt/huzhiguang/all_project/hhvm-3.0.1/public/hhvm/hhvm-src-301-debug/hhvm-HHVM-3.0.1/hphp/runtime/ser
	ver/http-request-handler.cpp:289

Please author help me solve this problem ,Thanks.

**Comment by paulbiss** [comment]
Are you seeing these crashes with 3.3 or 3.4?

**Comment by huzhiguang** [comment]
All version will crash,3.4 will crash in this machine and other machines no problem

**Comment by Zenexer** [comment]
Just a guess, but was /mnt/huzhiguang/data/test/tmphhbc/hhvm.hhbc from a different machine?  Perhaps the machine that created it was 32-bit and your servers are 64-bit, or something along those lines?

**Comment by huzhiguang** [comment]
@Zenexer ,hhbc create in local machine and then no repoAuthoritative no problem ,and then this machine is 64-bit,Thanks

**Comment by Zenexer** [comment]
I assume that you can't move the file between 32-bit and 64-bit architectures.

**Comment by staabm** [comment]
Hhvm does only support 64bit os'ses, doesnt it?

**Comment by wjywbs** [comment]
Maybe your kernel can't correctly mmap() hhvm itself?

**Comment by huzhiguang** [comment]
@Zenexer ,I use system is 64 bit linux and then hhvm only support 64 bit,I don't move the file between 32 bit and 64 bit architectures;

@wjywbs , I think this problem should not mmap problem ,because hhvm not problem in repoAuthoritative  mode,this problem only appear in repoAuthoritative  mode. Thanks

**Comment by Orvid** [comment]
This issue has been waiting for more info for more than 2 weeks. Closing for now, feel free to re-open it if you can provide more info.

https://github.com/facebook/hhvm/wiki/Human-Timeouts
