### ISSUE TITLE
Possible to run hhvm with certain parts being bytecode encoded?

### ISSUE THREAD

**Issue by hwongcom** [facebook/hhvm#4590]
I'm trying to run hhvm like "ioncube alternative style" bytecode encoder...

I can't do ioncube with hhvm, would like to do certain parts of bytecoded hhvm... is this possible?

Also, I can't do hhbc on all the files i have because I can't do create_function on repoauthoritative mode... so i would like to run non repoauthoritatively on the create_function, eval files and then only hhbc part... is this possible?

**Comment by steelbrain** [comment]
@hwongcom, HHVM support lambdas natively, I don't really see the need for create_function

**Comment by fredemmott** [comment]
This isn't possible - Repo Authoritative mode does optimizations that require knowledge of the entire codebase. If new code comes along later (eg from create_function(), new require()) etc, the optimizations are likely to be incorrect.

If you can use either anonymous functions or lambdas, you should be able to avoid this requirement.

**Comment by hwongcom** [comment]
i have too many create_functions in my php code. everything works with hhvm without the repoauthoritative part...
is it possible to have a "script" that can convert all my create_functions (500+ of them) to lambdas/anonymous functions? eval as well? anything close to that?
