### ISSUE TITLE
include a php.ini file with good/acceptable defaults

### ISSUE THREAD

**Issue by jrobeson** [facebook/hhvm#4594]
adding various ones from hhvm packages i've found:

php.ini
---------
hhvm: https://raw.githubusercontent.com/hhvm/packaging/master/hhvm/deb/skeleton/etc/hhvm/php.ini
debian: https://alioth.debian.org/plugins/scmgit/cgi-bin/gitweb.cgi?p=pkg-hhvm/hhvm.git;a=blob_plain;f=debian/php.ini;h=68f181c9df3a3cfeb4b1dd297a58783c4c78facf;hb=HEAD
pld: https://raw.githubusercontent.com/pld-linux/hhvm/master/php.ini
arch: https://projects.archlinux.org/svntogit/community.git/plain/trunk/php.ini?h=packages/hhvm

server.ini
-------------
hhvm: https://raw.githubusercontent.com/hhvm/packaging/master/hhvm/deb/skeleton/etc/hhvm/server.ini
debian: https://alioth.debian.org/plugins/scmgit/cgi-bin/gitweb.cgi?p=pkg-hhvm/hhvm.git;a=blob_plain;f=debian/server.ini;hb=HEAD
arch: https://projects.archlinux.org/svntogit/community.git/plain/trunk/server.ini?h=packages/hhvm

so it would be nice to adopt (or synthesize) one of these as the default OR do like php does and include one for development and production.

**Comment by ViolentVotan** [comment]
I have all in a php.ini file, why do I need a server.ini?

**Comment by jrobeson** [comment]
no one said you needed anything, but since they all still ship a server.ini, i figured i would mention it.

**Comment by oojacoboo** [comment]
I couldn't agree more - this is much needed.  Or, at the least, someone to update the ini docs...

https://github.com/facebook/hhvm/wiki/INI-Settings

**Comment by Orvid** [comment]
We'll leave the default ini to the individual distro packages.
