### ISSUE TITLE
Any chances to migrate the SolrClient extension?

### ISSUE THREAD

**Issue by CaledoniaProject** [facebook/hhvm#4599]
Hi

SolrClient is not on the default extension list so I'm wondering if I can request it here.

I tried to compile it myself but there's no phpize in hhvm so I don't know where to start .. sigh
I didn't find document telling me how to migrate a PHP extension to HHVM either ..

**Comment by JoelMarcey** [comment]
@CaledoniaProject We have `hphpize` in `./hphp/tools/hphpize/hphpize`

You can check this out too: https://github.com/facebook/hhvm/wiki/Extension-API#dynamically-loadable-objects

**Comment by aftabnaveed** [comment]
@CaledoniaProject  were you able to compile that yet ?

**Comment by CaledoniaProject** [comment]
@aftabnaveed Nope, I'm facing multiple problems.

First of all, the config.cmake doesn't contain the hhvm headers, I had to add them with CMAKE_C_FLAGS, that's weird.

Second, the old PHP extensions are C stuff ... that won't work with C++, needs a bit of tweak ..

=======================
I think I did something quiet dumb, I downloaded the SolrClient pear package and created a config.cmake:

set(CMAKE_C_FLAGS "-I/usr/include/hphp/runtime/ext_zend_compat/php-src/ -I/usr/include/hphp/runtime/ext_zend_compat/php-src/Zend/ -I/usr/include/hphp/runtime/ext_zend_compat/php-src/TSRM/ -I/usr/include/x86_64-linux-gnu/c++/4.8/ -I/usr/include/c++/4.8/")

HHVM_EXTENSION(solr php_solr.c
        php_solr_client.c
        php_solr_dismax_query.c
        php_solr_document.c
        php_solr_exception.c
        php_solr_input_document.c
        php_solr_object.c
        php_solr_params.c
        php_solr_query.c
        php_solr_response.c
        php_solr_utils.c
        solr_functions_client.c
        solr_functions_debug.c
        solr_functions_document.c
        solr_functions_helpers.c
        solr_functions_params.c
        solr_functions_response.c
        solr_string.c
        )
target_link_libraries(solr ${LIBFOO_LIBRARIES})

Then I did a "mkdir build && cd build && cmake .. && make" and lots of errors ... I guess I missed something here

**Comment by aftabnaveed** [comment]
I am not sure, but this might help https://github.com/facebook/hhvm/tree/master/hphp/runtime/ext_zend_compat

**Comment by paulbiss** [comment]
This feature request is not actively being worked on. We would happily consider a pull request implementing it. If you plan to work on this issue let us know in the comments and we will re-open the issue and assign it to you. If you feel strongly that this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
