### ISSUE TITLE
destructors are not called at end of web request hhvm 3.4.0, 3.4.2, 3.5.0-dev

### ISSUE THREAD

**Issue by amolrajoba** [facebook/hhvm#4600]
destructor is not called at end of request in hhvm 3.4.0, 3.4.2, 3.5.0-dev when tried with web request
This doesn't work even if we start HHVM server with option `-vEval.EnableObjDestructCall=1`

```
hphp/hhvm/hhvm --mode server -vServer.Type=fastcgi -vServer.IP=0.0.0.0 -vServer.Port=9005 -vAdminServer.Port=9006 -vAdminServer.ThreadCount=1 -vServer.ThreadCount=10 -vServer.APC.EnableApc=true -vEval.Jit=true -vEval.EnableObjDestructCall=1
```
But  it works in refcounted situations as explained in [issue 3152](https://github.com/facebook/hhvm/issues/3152)

Also when tried with CLI/command-line option destructor gets called.
code
```
<?php
class MyDestructableClass {
   function __construct() {
       print "In constructor\n";
       $this->name = "MyDestructableClass";
   }

   function __destruct() {
       print "Destroying " . $this->name . "\n";
   }
}

$obj = new MyDestructableClass();
```

So please let us know what should be done to get destructors called at end of web request as default?

**Comment by JoelMarcey** [comment]
cc: @fredemmott You looked at this a bit in #3152 ... is this is a pseudomain issue or something?

**Comment by fredemmott** [comment]
This is documented in inconsistencies, and in 3152. Add hhvm.enable_obj_destruct_call = true to your ini, or Eval.EnableObjDestructCall to your HDF.

**Comment by JoelMarcey** [comment]
@fredemmott ... @amolrajoba said he tried `-vEval.EnableObjDestructCall=1` at the command line and that didn't work.

I saw this in inconsistencies, but wasn't sure it applied to this...

https://github.com/facebook/hhvm/blob/master/hphp/doc/inconsistencies#L40

**Comment by fredemmott** [comment]
We do call them - however output is not sent to the browser.

You can test this by adding a file_put_contents() in your destructor or similar.

**Comment by JoelMarcey** [comment]
@fredemmott :+1:  Nice ....

**Comment by fredemmott** [comment]
Do you require the output? If so, could you explain how you're using it?

**Comment by fredemmott** [comment]
PHP5 does send the output, at least with the '-S' built-in server

**Comment by amolrajoba** [comment]
@fredemmott I require the destructor output for remote debug/check of aplications in automated or manual way. this works in PHP5 fpm.

**Comment by SiebelsTim** [comment]
It's not safe to rely on that in php5 either, if I remember correctly.

**Comment by bvidinli** [comment]
I put hhvm.enable_obj_destruct_call = true in server.ini, 
I tested with file_put_contents, still not called. 
no error generated,

**Comment by paulbiss** [comment]
Do you have some code to repro the problem?

**Comment by bvidinli** [comment]
the code at here:

http://stackoverflow.com/questions/6245971/accurate-way-to-measure-execution-times-of-php-scripts

code is:

```
<?php
class loadTime{
    private $time_start     =   0;
    private $time_end       =   0;
    private $time           =   0;
    public function __construct(){
        $this->time_start= microtime(true);
    }
    public function __destruct(){
        $this->time_end = microtime(true);
        $this->time = $this->time_end - $this->time_start;
        echo "Loaded in $this->time seconds\n";
    }
}
```

That is, it is plain class code. 
I also tested with file_put_contents...

**Comment by SiebelsTim** [comment]
Seems to work, even with echo (which is not guaranteed to be visible)
http://3v4l.org/hdl5T

**Comment by bvidinli** [comment]
I am using HipHop VM 3.3.0-dev, 
your link uses hhvm 3.6, 3.7.

Is there a practical way to install hhvm 3.6 or 3.7 onto ubuntu ?

I normally installed using apt-get.

**Comment by SiebelsTim** [comment]
@bvidinli You should get updates for ubuntu, as long as you're not on saucy. The latest LTS version is 3.6. So your version is outdated.

**Comment by bvidinli** [comment]
I tried to install on the server, however, it still installs 3.3.0, How can I install hhvm 3.6 or 3.7 ? other than compiling ? 
where are ubuntu deb packages ? 

I tried to install using https://github.com/facebook/hhvm/wiki/Prebuilt-packages-on-Ubuntu-14.04
but, no luck.

**Comment by SiebelsTim** [comment]
What ubuntu version are you using?

**Comment by paulbiss** [comment]
This report has unanswered questions, and the bug should be fixed in more recent versions with the ini option mentioned above.
