### ISSUE TITLE
memcached extension missing deletemulti and setmulti

### ISSUE THREAD

**Issue by rrh** [facebook/hhvm#4602]
The memcached support apparently does not implement either deleteMulti or setMulti families of operations
  
http://php.net/manual/en/memcached.deletemulti.php
http://php.net/manual/en/memcached.setmulti.php

https://github.com/facebook/hhvm/blame/master/hphp/runtime/ext/memcached/ext_memcached.cpp#L1333

I haven't done a comprehensive delta between the functions documented here http://php.net/manual/en/class.memcached.php and what's in hhv

**Comment by Stelian** [comment]
Is anyone looking into this? I could pick it up if no other takers.

**Comment by rrh** [comment]
I'm not.  thanks for your offer!

**Comment by Stelian** [comment]
Should be a pretty easy fix, since setMulti and deleteMulti is a "loop alias" for set and delete: https://github.com/php-memcached-dev/php-memcached/blob/def716a80f1be732b5dad1c13d3023248db64881/php_memcached.c#L1227

**Comment by noony** [comment]
can be closed by : https://github.com/facebook/hhvm/commit/fa0de179a9de28f130b9b5cb819807a77af3065a
