### ISSUE TITLE
TypeChecker fails to recognize Enums

### ISSUE THREAD

**Issue by steelbrain** [facebook/hhvm#4604]
hh_client is having some problem detecting enums, It fails to recognize some functions like assert/isValid etc. As a workaround we have to goto the file that has the enum declaration and save it.

It happens everytime hh_server is respawned.

**Comment by jwatzman** [comment]
We insert `BuiltinEnum` as a parent during declaration, which is too late for the "make sure my parent is declared before I am" logic, and so we race enum declarations against `BuiltinEnum`. I'm **shocked** we haven't seen this internally.

**Comment by jwatzman** [comment]
And massive thanks @steelbrain for the info, this could have been a huge pain to track down.

**Comment by jwatzman** [comment]
https://reviews.facebook.net/D31203
