### ISSUE TITLE
 Apache/2.4.7 (Ubuntu) +HHVM Can not  get Authorization header 

### ISSUE THREAD

**Issue by JasonXt** [facebook/hhvm#4605]
GET  HTTP/1.1
Host: 121.42.51.177
Authorization: Bearer VlSZxDKU0xlmEh4ByOtOYkzK9k58Sal3KaFdwWm0
GGGGGGGGG: GGGGG
Cache-Control: no-cache
Postman-Token: 89838e15-cf4c-c769-e795-4a0e31e01a86

PHP $_SERVER:

Array
(
    [REQUEST_START_TIME] => 1420786433
    [REQUEST_TIME] => 1420786433
    [REQUEST_TIME_FLOAT] => 1420786433.3101
    [HTTP_GGGGGGGGG] => GGGGG
    [HTTP_HOST] => 121.42.51.177
    [HTTP_USER_AGENT] => Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36
    [HTTP_CONNECTION] => keep-alive
    [HTTP_CACHE_CONTROL] => no-cache
    [HTTP_POSTMAN_TOKEN] => 3892223b-6521-820c-b6be-14409f34c459
    [HTTP_ACCEPT_ENCODING] => gzip, deflate, sdch
    [HTTP_ACCEPT] => */*
    [HTTP_ACCEPT_LANGUAGE] => zh-CN,zh;q=0.8,en;q=0.6
    [GATEWAY_INTERFACE] => CGI/1.1
    [SERVER_ADDR] => 121.42.51.177
    [SERVER_NAME] => 121.42.51.177
    [SERVER_PORT] => 80
    [SERVER_SOFTWARE] => Apache/2.4.7 (Ubuntu)
    [SERVER_PROTOCOL] => HTTP/1.1
    [SERVER_ADMIN] => webmaster@591mian.com
    [SERVER_SIGNATURE] =>
<address>Apache/2.4.7 (Ubuntu) Server at 121.42.51.177 Port 80</address>

    [REMOTE_ADDR] => 221.224.121.154
    [REQUEST_METHOD] => GET
    [QUERY_STRING] => 
    [DOCUMENT_ROOT] => /var/www/html/public
    [REMOTE_PORT] => 60198
    [REQUEST_SCHEME] => http
    [REQUEST_URI] => /
    [proxy-nokeepalive] => 1
    [SCRIPT_FILENAME] => /var/www/html/public/index.php
    [CONTEXT_PREFIX] => 
    [CONTEXT_DOCUMENT_ROOT] => /var/www/html/public
    [SCRIPT_NAME] => /index.php
    [PATH] => /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    [SCRIPT_URL] => /index.php
    [SCRIPT_URI] => http://121.42.51.177/index.php
    [PHP_SELF] => /index.php
    [PATH_TRANSLATED] => /var/www/html/public/index.php
    [HTTPS] => 
    [argv] => Array
        (
            [0] => 
        )

    [argc] => 1
    [THREAD_TYPE] => Web Request
)

the Authorization header is missing   Tried a lot  ways  but  still missing  

Any help please

**Comment by apuckey** [comment]
You need to rewrite it so it picks it up from the ENV:

```
  RewriteEngine On
  RewriteCond %{HTTP:Authorization} ^(.*)
  RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]
```

**Comment by simonwelsh** [comment]
It should also be returned by `apache_request_headers()`

**Comment by paulbiss** [comment]
Are you running on master? 60ed68cc1697a897a90a1712e8aa040235efc8a5

**Comment by JasonXt** [comment]
I add the rewrite rules   then  just have the  REDIRECT_HTTP_AUTHORIZATION header  there still no HTTP_AUTHORIZATION header  I am a poor fresh man  ... What can I do ,Please

**Comment by JasonXt** [comment]
@paulbiss   I just   install it  by apt-get

**Comment by JasonXt** [comment]
Here is my .htaccess   in laravel's  public  dir
<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews
    </IfModule>

    RewriteEngine On
    RewriteCond %{HTTP:Authorization} ^(.*)
    RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]
    # Redirect Trailing Slashes...
    RewriteRule ^(.*)/$ /$1 [L,R=301]
    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]

</IfModule>

**Comment by paulbiss** [comment]
The patch for authorization headers didn't make the 3.4 cut, when we release 3.5 this should be resolved. If you're running the nightly packages there may still be an issue that hasn't been fixed, please run `hhvm --version` and paste the result here.

**Comment by JasonXt** [comment]
Here is the result:
HipHop VM 3.4.2 (rel)
Compiler: tags/HHVM-3.4.2-0-g40d85d7386b3342ab848fc45c6892433c89ef5b2
Repo schema: 13cba877c4300d1d0481b3f40eb128a5115d4e08
Extension API: 20140829

**Comment by paulbiss** [comment]
That version doesn't have the patch, you can try the 3.5 nightly if you'd like to see if it will be fixed in the next release.

**Comment by JasonXt** [comment]
OK  , I will check it right now ,  Thank you so so much !

**Comment by lucian303** [comment]
This is still happening in 3.6 as far as I can tell. The rewrite does work. 

HipHop VM 3.6.1 (rel)
Compiler: tags/HHVM-3.6.1-0-gc051feff88ba8050f33f10f7b1fb07f8d3415f9e
Repo schema: 42f49251b5c27daf4e13cb6bcd0c7ef4824b55a3

**Comment by paulbiss** [comment]
Hmm, we added a [test](https://github.com/facebook/hhvm/blob/master/hphp/test/server/fastcgi/tests/headerTest.php) for this when we patched it and it's been passing. Maybe there's something different about your setup?

**Comment by JasonXt** [comment]
@lucian303  My solution is 

if(!is_null($_SERVER['REDIRECT_HTTP_AUTHORIZATION'])){
    $_SERVER['HTTP_AUTHORIZATION']=$_SERVER['REDIRECT_HTTP_AUTHORIZATION'];
}

In the http header  there is a  REDIRECT_HTTP_AUTHORIZATION  so I add it manually .

Rewrite:
<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews
    </IfModule>

    RewriteEngine On

    # Redirect Trailing Slashes...
    RewriteRule ^(.*)/$ /$1 [L,R=301]


    RewriteCond %{HTTP:Authorization} ^(.*)
    RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]
    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]

</IfModule>

**Comment by paulbiss** [comment]
Hmm, the fix kept the name of the field as "Authorization" (e.g. $_SERVER['Authorization']). It should be pretty easy to rewrite the header to "HTTP_AUTHORIZATION" if that's the requirement here, or to add both (60ed68cc1697a897a90a1712e8aa040235efc8a5).

**Comment by paulbiss** [comment]
I'm still unclear on what the issue with the header name is here, but if it just needs to be mapped to something other than 'Authorization' that shouldn't be difficult with the above fix. Comment below if you're still having problems with this.
