### ISSUE TITLE
adminer.php does not run in hhvm

### ISSUE THREAD

**Issue by techjewel** [facebook/hhvm#4606]
Hello,
Recently I start using hhvm and so far I am happy with the performance. But I can not use adminer.php
After login that shows a blank screen. Don't know what is the problem. I don't want to use phpmyadmin because of that is too large to manage database.

Please let me know if there has any fix or any alternative.

Thanks

**Comment by SiebelsTim** [comment]
That's because Adminer does a good job putting the silence operator infront of everything. Without them we would see 

    Catchable fatal error: Argument 1 to mysqli::real_connect() must be of type ?string, bool given in /var/www/adminer/adminer/drivers/mysql.inc.php on line 25

**Comment by SiebelsTim** [comment]
@techjewel  You can workaround this the following way: 
Use the hostname and username field for the login.
Also add the port to hostname
Example url: 

    http://localhost/adminer.php?server=localhost:3360&username=root&

Example login:

```
Server: localhost:3360
Username: root
Password: yourpassword
Database: may_be_empty
```

**Comment by techjewel** [comment]
It works great @SiebelsTim 
Thanks you so much. You made my day.

**Comment by JoelMarcey** [comment]
SiebelsTim :+1: on the workaround. Thanks!

I will create a new issue that explicitly calls out supporting mysql/mysqli ini settings.
