### ISSUE TITLE
Support mysql/mysqli ini settings

### ISSUE THREAD

**Issue by JoelMarcey** [facebook/hhvm#4608]
See #4606 for context

http://docs.hhvm.com/manual/en/mysql.configuration.php
http://docs.hhvm.com/manual/en/mysqli.configuration.php

**Comment by adrianmak** [comment]
I added mysql ini settings in /etc/hhvm/php.ini

; mysql specific
mysql.default_port=3360
mysql.default_host=127.0.0.1
mysqli.default_port=3360
mysqli.default_host=127.0.0.1


but opening adminer still gave me a blank page
