### ISSUE TITLE
mktime() fails to throw E_STRICT

### ISSUE THREAD

**Issue by rrh** [facebook/hhvm#4611]
http://docs.hhvm.com/manual/en/function.mktime.php says that mktime with 0 arguments throws E_STRICT.

The hhvm implementation doesn't throw anything.  The code just happily accepts the default argument values (PHP_INT_MAX for all args)

**Comment by Zenexer** [comment]
[Confirmed](http://3v4l.org/iHLBP)

**Comment by noony** [comment]
Fixed by https://github.com/facebook/hhvm/pull/5809
