### ISSUE TITLE
move emacs plugin to its own repository

### ISSUE THREAD

**Issue by jrobeson** [facebook/hhvm#4613]
vim-hack is already at https://github.com/hhvm/vim-hack/

**Comment by jrobeson** [comment]
Can some hhvm person create hhvm/emacs-hack and get those files there?

**Comment by jrobeson** [comment]
I don't even know who to ping to make this happen.

**Comment by jrobeson** [comment]
ping?

**Comment by paulbiss** [comment]
cc @jwatzman this sounds like a good idea, it looks like emacs is the only plugin under hphp/hack/editor-plugins

**Comment by jwatzman** [comment]
Yeah probably, though it takes just enough time to set up the new repo that it's pretty low pri on my list. Also the emacs plugin is just one file, and sees much less usage and changes than the vim one, so I don't think it's super important?

**Comment by SiebelsTim** [comment]
@jwatzman What about I create the repo and try to transfer ownership to the http://github.com/hhvm?

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

It appears that there is such an emacs repo at https://github.com/hhvm/hack-mode
