### ISSUE TITLE
Upgrade HHVM to latest stable release Ubuntu

### ISSUE THREAD

**Issue by aftabnaveed** [facebook/hhvm#4614]
I am running HHVM on production, and would like to keep that upto date with latest stable release, is there a way to upgrade it from provided Ubuntu repositories? 

I tried sudo apt-get install hhvm=3.4.x but that won't work.

Thank you

**Comment by GrahamCampbell** [comment]
What ubuntu version?

**Comment by aftabnaveed** [comment]
Ubuntu 14.04 LTS,  where as hhvm version is 3.3.1 I would like to upgrade that to the latest stable release

**Comment by aftabnaveed** [comment]
I am not sure if this is the best method, but I re-added these sources  and followed the instructions, which  removed the previous version and installed the new, and it did keep my configuration.

https://github.com/facebook/hhvm/wiki/Prebuilt-packages-on-Ubuntu-14.04

Can any one please shed light, if that would be the right way of upgrading it?

**Comment by fcorriga** [comment]
use this:
deb http://dl.hhvm.com/debian wheezy-lts-3.3 main

instead of the default (deb http://dl.hhvm.com/debian wheezy main)

**Comment by jwatzman** [comment]
- @fcorriga's directions will keep you on the 3.3 LTS branch. https://github.com/facebook/hhvm/wiki/Long-term-support-%28LTS%29 has details.
- Other than that, the default directions will keep you on the stable branch. 3.4 is the old stable branch and is now unsupported. 3.5 is the current stable branch. Stable branches get support for about 8 weeks.
- If you want support for more than 8 weeks, use the aforementioned LTS branches, which are supported for 48 weeks. The link above has details on this.
