### ISSUE TITLE
Support parse and dump ast command again.

### ISSUE THREAD

**Issue by reeze** [facebook/hhvm#4615]
It is quite useful feature when developing.

http://stackoverflow.com/questions/17477528/hhvm-the-parse-command-line-option-is-not-supported

@ptarjan  replied it in SO, for the record, I create this issue.

**Comment by paulbiss** [comment]
This feature request is not actively being worked on. We would happily consider a pull request implementing it. If you plan to work on this issue let us know in the comments and we will re-open the issue and assign it to you. If you feel strongly that this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
