### ISSUE TITLE
Memcache::set / get doesn't work hhvm-3.5.0-4

### ISSUE THREAD

**Issue by redstrike** [facebook/hhvm#4617]
OS: CentOS release 6.6 (Final)
Prebuilt package: gleez's repo, hhvm-3.5.0-4.el6.x86_64

As I understand, HHVM included memcache extension with its runtime. Each time my pages slow down and freezing... a fatal error from hhvm show me the line where my code use $memcache to get / set data.

I've tested by using a script, force set data to a key, and var_dump the data from get. But the script was hanging then show a blank string.

I wonder this bug is known and fixed in master branch? Sr, I'm using CentOS and my country's internet connection is very slow at this moment, so I can't compile the master ver and test it myself.

I will do a test with memcached ext and come back later.

Thanks for your effort.

Edit: memcached ext works.

**Comment by DmitrySoshnikov** [comment]
@**redstrike**, do you have a repro script when `memcache` freezes?

**Comment by redstrike** [comment]
I tested HHVM on my main site's production server which is using LiteSpeed Std Edition not Nginx. My test script was something simple like this:

```php
<?php
$mc = new Memcache;
$mc->connect('tcp://MEMCACHED_IP_ADDRESS', 11211) or die ("Could not connect to MC!");
$ok = $mc->set('test', 'hello Tung');
var_dump($ok, $mc->get('test'));
```

```
Runtime options:
hhvm -u nobody --mode deamon -vServer.Type=fastcgi -vServer.Port=9000
hhvm -u nobody --mode daemon -vServer.Type=fastcgi -vServer.FileSocket=/tmp/lshttpd/hhvm.sock
```

Please test HHVM FastCGI with LiteSpeed in your env, it's usually freeze and crash after a few requests, no matter settings I tried. Because our site's production server was crashed and unstable after installed a lot packages for HHVM (I have re-installed it), so I will spend my time to setup a production env on my local machine to test again.

I will come back soon.

**Comment by redstrike** [comment]
Hi,

I have installed HHVM on a Ubuntu 12.04.5 box via Docker and re-tested it directly on my production server. At first I got memcache and memcached issues on both stable (3.4.2) and nightly build version (3.6.0-dev). After that, I realized that my Boost isn't meet the requirement of HHVM. Now, both of them are working correctly.

I think my problem on CentOS is the same, because HHVM doesn't have an official prebuilt package for it and we have to work around to install HHVM, and HHVM doesn't notify us the library doesn't meet its requirements.

Thanks to Docker, I could use HHVM on its prefer environment and avoid messing around the source code (compile it costs a lot of time and so much mistakes).

IMO, HHVM should have the ability to self-detect and notify us about the missing lib or something does not meet its expected like PHP's "extension cannot be loaded".

I don't want to follow this bug anymore. Thanks for your efforts to make HHVM become an open PHP runtime for general users like me.

Tung.

**Comment by jwatzman** [comment]
IMO it's not really HHVM's job to detect at *runtime* that support libraries have been mysteriously changed. It does do a compile time check during configuration, and from there it's up to the folks that distribute the binaries to make sure that the version of boost or whatever on the target system is acceptable. Our debian packages do this with debian package version dependencies; presumably the person who built the CentOS packages can do the same with yum/rpm's equivalent feature.

It sounds like this was solved and there isn't much more to do here? Please feel free to reopen if I'm incorrect or have misunderstood something!
