### ISSUE TITLE
HHVM can't send email in Laravel 4.2

### ISSUE THREAD

**Issue by 13g** [facebook/hhvm#4620]
It is normally to send email in laravel with the enviroment of WAMP or LAMP. But sending email doesn't success when use HHVM

**Comment by itskevinsam** [comment]
possibly related to https://github.com/facebook/hhvm/issues/1647

**Comment by fredemmott** [comment]
Yeah, this sounds like #1647. If you disagree, please respond with error message details/backtrace etc, and I'll re-open

**Comment by 13g** [comment]
Thanks for your answers, and I use another way to send email.

**Comment by iveoles** [comment]
I upgraded to HHVM 3.5.0 the other day and it appears as though the email sending has been fixed, however we only have one codebase to test on our HHVM production server. Could someone else confirm?

**Comment by lima01** [comment]
Not working for me. Same error that the encrypt function not found.
