### ISSUE TITLE
Wrong output with utf8_decode + non-CP1252 char

### ISSUE THREAD

**Issue by nicolas-grekas** [facebook/hhvm#4621]
Not seen on 3.4.1 but seen on travis 3.5.0-dev~nightly.2015.01.07
https://travis-ci.org/tchwork/utf8/jobs/46713155

``` php
echo utf8_decode('Σ');
```

outputs `�` where `?` is expected

**Comment by paulbiss** [comment]
Looks like the behavioral change was introduced in 2ec45df3bd3b9019974868aeb908472f71313a8c

**Comment by jesseschalken** [comment]
HHVM produces `?` like Zend now (https://3v4l.org/08qlB)
