### ISSUE TITLE
Installing Binary on Ubuntu 14.04

### ISSUE THREAD

**Issue by thomsol** [facebook/hhvm#4622]
Attempting to follow instructions at: https://github.com/facebook/hhvm/wiki/Prebuilt-packages-on-Ubuntu-14.04

Getting GPG error:  Clearsigned file isn't valid, got 'NODATA' (does the network require authentication?)

**Comment by paulbiss** [comment]
Sounds like an error downloading the package. If you're convinced the error is on our end please file an issue on https://github.com/hhvm/packaging
