### ISSUE TITLE
settype($val, 'double') not works (PHP5 incompatiblity)

### ISSUE THREAD

**Issue by dg** [facebook/hhvm#4624]
`settype($val, 'double')` leaves `$val` unconverted, see http://3v4l.org/9bfAV.

`double` is in fact deprecated variant, but `gettype(1.0)` still returns `'double'`.

**Comment by Majkl578** [comment]
Note that `float` works: http://3v4l.org/f4ibH
There is a missing branch for double here: https://github.com/facebook/hhvm/blob/9778521aa100ae460831d395521bbcf68cb27580/hphp/runtime/ext/std/ext_std_variable.cpp#L76

**Comment by dg** [comment]
Thank you
