### ISSUE TITLE
Missing $file in custom error handler

### ISSUE THREAD

**Issue by dg** [facebook/hhvm#4625]
In this case (http://3v4l.org/dWuvG) is `$file` empty string:

``` php
namespace X;

class Test
{
    public static function invoke()
    {
        set_error_handler(function($severity, $message, $file) {
            var_dump($file);
        });

        // E_WARNING trim() expects parameter 1 to be string, array give
        call_user_func_array('trim', array(array()));
    }

}

Test::invoke();
```

If you remove a namespace declaration, the problem will disappear (see http://3v4l.org/dETSj)

**Comment by noony** [comment]
new 3v4l seems ok now : https://3v4l.org/CNbVj

**Comment by noony** [comment]
printing backtrace content at https://github.com/facebook/hhvm/blob/master/hphp/runtime/base/exceptions.cpp#L116 shows that we have an empty content at 0 when we declare a namespace :

`````
bt[7] | file :  , line : 0
bt[6] | file :  , line : 0
bt[5] | file :  , line : 0
bt[4] | file :  , line : 0
bt[3] | file :  , line : 0
bt[2] | file : /home/tcolomb/hhvm/hphp/test.php , line : 19
bt[1] | file : /home/tcolomb/hhvm/hphp/test.php , line : 14
bt[0] | file :  , line : 0
`````

**Comment by jesseschalken** [comment]
If you replace the `call_user_func_array('trim', array(array()))` with `\trim(array())`, it produces the same result as Zend: https://3v4l.org/AHPHU

If you keep the `call_user_func_array`, for some reason HHVM behaves as though `strict_types=1` and throws a `TypeError`, which I have filed separately: https://github.com/facebook/hhvm/issues/7834

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

I have tested your repro, but with an explicit `\trigger_error()` and the filename was printed correctly.

```HACK
<?hh // partial
namespace X;

class Test {
    public static function invoke() {
        \set_error_handler(function($severity, $message, $file) {
            \var_dump($file);
        });

        \trigger_error('array given', \E_USER_WARNING);
    }

}

Test::invoke();
```
