### ISSUE TITLE
inconsistent implementation of @ for statically mistyped args

### ISSUE THREAD

**Issue by rrh** [facebook/hhvm#4626]
The following 3 liner should print out 2 things, as it does in zend php5 (but not in php7), but hhvm only prints out 1 thing.  In both cases an array(1) is passed to a function typed to receive a string.

The hhvm documentation leads me to believe hhvm should print out nothing (eg fail on the first type mismatch):

<?php
@(new XMLReader())->XML(array(1)); printf("finished XML\n");
@(new finfo())->file(array(1)); printf ("finished finfo\n");

What I don't understand is why the XML test succeeds, but the finfo one fails. AFAICT, both are classes and methods are defined in the hhvm source tree in <?hh files; both are methods on some constructed class, etc.

The behavior of the @ for the finfo case seems consistent with the documentation http://docs.hhvm.com/manual/en/language.operators.errorcontrol.php specifically in the Warning documentation at the end of that page.

I think it is unfortunate that @ is implemented in hhvm to fail hard and silently; even a try/catch to catch an Exception doesn't catch the "Catchable fatal".

This issue cropped up for me "in real life" with mysqli multi_query(), but that's harder to simply reproduce because it needs valid mysql credentials.

**Comment by rrh** [comment]
See http://3v4l.org/qcHLJ

**Comment by markw65** [comment]
We match php5/php7 for user functions with typehints:

<?php
function foo(array $a) {}
@foo(5);

So its not that @ suppresses catchable fatals in php5, its that builtin functions/methods don't raise catchable fatals, they raise warnings. But for hhvm, if a builtin function is entirely defined in php, we currently treat it the same as a user function, and raise a catchable fatal. I believe there's work underway to fix that. Note that XMLReader::XML is defined as an <<__Native>> function (and so correctly raises a warning, and returns null on parameter mismatch), while finfo::file is defined in pure php.

**Comment by jesseschalken** [comment]
@markw65 Even if `finfo::file()` is implemented in pure PHP, shouldn't `declare(strict_types=0);` trigger loose type checking and suppress that error?

https://3v4l.org/arNaE

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

In [hhvm 4.3.0](https://hhvm.com/blog/2019/04/30/hhvm-4.3.0.html) the failure mode of calling a built-in function with the wrong types has been changed to be a TypeError. This matches the user defined Hack functions. It is not possible to get the PHP coercion behavior. PHP support was dropped with the release of [hhvm 4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html) and Hack does not coerce to make values match typehints.

I expected this to be an issue with the `@` operator at first (that it somehow would not suppress `@(new IWarn())->method();` correctly. It seems to do this as expected.

The difference is in the failure mode for passing incorrect types, which has been changed across the  board to throw a TypeError.
