### ISSUE TITLE
test/run too sensitive to ini setting variables_order

### ISSUE THREAD

**Issue by rrh** [facebook/hhvm#4627]
The test/run script (which is run with /usr/bin/env php) evaluates superglobal $_ENV and passes the environment from that into the child hhvm process under test.

Unfortunately, for zend php5 at least, $_ENV will only be filled if the variables_order initialization
  http://php.net/manual/en/ini.core.php#ini.variables-order
has 'E' in the string.  This means that evaluation of test/run is at the mercy of the evaluating php's .ini file.

This means that the desired effect of setting environment variable MYSQL_TEST_PASSWD (say) to control the test evaluation may not have the desired effect on the tested program.

OTOH, maybe you don't want environment variables to perturb the desired execution?  Or maybe you want to pass through just a handful of env vars?

Perhaps complain/fatal when the environment from $_ENV is the empty array, so that the invoker can manually fiddle with variables_order in the corresponding php.ini file

**Comment by jrobeson** [comment]
see this PR: https://github.com/facebook/hhvm/pull/4593

**Comment by reeze** [comment]
@jrobeson  It seems the different problem, what @rrh said is the test runner script. it was executed by `php` but not `hhvm`, that php may not have $_ENV available.

Maybe we could use `getenv()` instead of $_ENV to make it more stable.

**Comment by jrobeson** [comment]
ah yes, i read it backwards!

**Comment by reeze** [comment]
`$_ENV` variable could be replaced by `getenv()` but `$_SERVER` couldn't, complain about it would be better. just sent a PR for this.

**Comment by rrh** [comment]
You can't use getenv for this purpose in the test/run script, since test/run wants to forward all environment values ($_ENV) through to the subprocess rather than just ones it knows about a-priori (getenv("VARNAME"))

**Comment by reeze** [comment]
Indeed,    https://github.com/reeze/hhvm/blob/01cd765fea07ddce1613147c75204566006cbd72/hphp/test/run#L1038-L1042  it add two more variables, without that it might be possible, it could inherent from `test/run`

Anyway, enable `$_ENV` should be a clean & better way:)

**Comment by reeze** [comment]
This could be closed.
