### ISSUE TITLE
Strange issues, Magento price

### ISSUE THREAD

**Issue by gewaechshaus** [facebook/hhvm#4630]
After switching from php5-fpm to 

   HipHop VM 3.4.2 (rel)
   Compiler: tags/HHVM-3.4.2-0-g40d85d7386b3342ab848fc45c6892433c89ef5b2
    Repo schema: 13cba877c4300d1d0481b3f40eb128a5115d4e08
    Extension API: 20140829

we are running into some issues with Magento and the price rendering. While values are still right in sales_flat_order, a total value of 36.00€ is shown as 36000000.00€. The same appears at the frontend product view, checkout cart etc. - so prices are high actualy :) Before a deeper inspection, does anybody ever notice something like this? Could this be related to localization, rounding or the issues underneath?

I stumple upon
https://github.com/facebook/hhvm/pull/2802

and had the problems like described here
https://github.com/facebook/hhvm/pull/2802

fixed it with installing
https://github.com/danslo/Rubic_FixTotalSorting

**Comment by paulbiss** [comment]
Have you tried setting `hhvm.enable_zend_sorting=1` in your ini file?

**Comment by gewaechshaus** [comment]
No, will give it a try!

**Comment by gewaechshaus** [comment]
First test cases look good, will continue tomorow... Keep you informed.

**Comment by gewaechshaus** [comment]
Still appears... Will need a deeper investigation.

**Comment by gewaechshaus** [comment]
Can be temporary closed as with got new results, see the issue above.

**Comment by Orvid** [comment]
This issue has been waiting for more info for more than 2 weeks. Closing for now, feel free to re-open it if you can provide more info.

https://github.com/facebook/hhvm/wiki/Human-Timeouts
