### ISSUE TITLE
StringData::reserve() reserves extra memory but some bits of code assume that it doesn't

### ISSUE THREAD

**Issue by dmitry-brizhinev** [facebook/hhvm#4631]
For example, StringBuffer::growBy() has a comment suggesting that it expects reserve() to be reserving precisely the correct amount of memory, and makes an effort to make them powers of two.

There are no correctness issues, but it may be worth having a separate function for those cases when code actually knows exactly how much memory it will need.

**Comment by paulbiss** [comment]
Closing this github issue since I don't think anyone is working on it, and it doesn't sound like this is currently a problem. @edwinsmith feel free to reopen if you disagree.

**Comment by edwinsmith** [comment]
at best this would be a lockdown task to just optimize string growth.
