### ISSUE TITLE
StringData::shrink() compares the new length to the old length, but should compare against the old capacity

### ISSUE THREAD

**Issue by dmitry-brizhinev** [facebook/hhvm#4632]
Code that actually uses shrink() sometimes treats it as a way of cleaning up after reserving a large string and only using part of it. But in those cases, the "length" is still zero, and the shrink() call is being relied on to set the new length, so it will not have the (desired?) behaviour of reallocating the string to save memory if a large saving is possible.

I can attach a pull request identifying some of those uses soonish

**Comment by dmitry-brizhinev** [comment]
Pull request: #4635

**Comment by SiebelsTim** [comment]
closed in  49b263f673b041201
