### ISSUE TITLE
StringData::bufferSlice() is redundant and users of it could instead call StringData::mutableData()

### ISSUE THREAD

**Issue by dmitry-brizhinev** [facebook/hhvm#4633]
StringData::bufferSlice() and the wrapper function String::bufferSlice() are used in several areas of the code, but always according to the pattern:
string.bufferSlice().ptr
or
string.bufferSlice().begin()
which both simply return a pointer to the data, the same behaviour as StringData::mutableData()

The MutableSlice's len field is never used, so that function call generates a redundant request for the StringData's capacity().

I can submit a pull request that changes the behaviour soonish

**Comment by dmitry-brizhinev** [comment]
Pull request: #4634

**Comment by r3wt** [comment]
:+1:
