### ISSUE TITLE
static analyze and CodeError.js

### ISSUE THREAD

**Issue by karpa13a** [facebook/hhvm#4638]
some time ago, static analyze works like a sharm, but currently, only Stats.js and hhvm.hhbc files written.
running command like:
hhvm --hphp --target hhbc --input-list ../files.list -k1 --gen-stats=true --include-path="./" -c ../config_hphp.txt --output-dir=/tmp/test.hhvm

```
HipHop VM 3.5.0-dev~nightly.2015.01.11 (rel)
Compiler: heads/master-0-ge3761e46300e2dd92feab7ff984029369362de6f
Repo schema: 6fec97a49b717f7eb4f7c9948bdeec3d0ca46fa2
Extension API: 20140829
```

did i miss smth?

**Comment by paulbiss** [comment]
The analysis pass has been removed in favor of hh_client, there aren't currently any plans to reenable it. See #3987.
