### ISSUE TITLE
missing hphp/include/version.h

### ISSUE THREAD

**Issue by rrh** [facebook/hhvm#4639]
I compile hhvm, then run 
  sudo make install
I then build my extension as a DSO in a separate directory, which is set up to point -I at /usr/local/include/hphp somehow.

The file hphp/runtime/version.h is now missing.  It probably isn't installed with the recent changes to version.h.

Here's the gcc error message:

In file included from /usr/local/include/hphp/runtime/base/base-includes.h:24:0,
                 from /usr/local/include/hphp/runtime/ext/std/ext_std.h:4,
                 from /usr/local/include/hphp/runtime/ext/std/ext_std_errorfunc.h:21,
                 from /home/rrh/git-work-2/php_agent/php_agent_hhvm/newrelic.cpp:48:
/usr/local/include/hphp/runtime/ext/extension.h:26:34: fatal error: hphp/runtime/version.h: No such file or directory
 #include "hphp/runtime/version.h"

**Comment by chregu** [comment]
Yep, have the same problem.

**Comment by rrh** [comment]
After doing a 'make install', I now do this step manually, perhaps with a 'sudo' prefix:
  cp -p hphp/runtime/version.h /usr/local/include/hphp/runtime/version.h

**Comment by sgolemon** [comment]
Sorry about that!   New headers are usually picked up automatically, but hphp/runtime/ didn't have headers in it prior to this (well, it did ages ago, but not since the header installs came about).

You can add:

  list(APPEND HEADER_SOURCES "${CMAKE_CURRENT_SOURCE_DIR}/version.h")

to hphp/runtime/CMakeLists.txt line 5 (just below the foreach) while you're waiting for my fix to land, or just copy it mainually as @rrh suggested.

**Comment by sgolemon** [comment]
Fix should be out within 30 minutes

**Comment by chregu** [comment]
thanks a lot

**Comment by chregu** [comment]
It's still missing from the HHVM-3.5 branch, right? (No idea, how the process of merging to version branches works at HHVM)

**Comment by bountin** [comment]
Is there a plan when to release 3.5.1 or will it be just 3.6.0? The build of hhvm-pgsql currently fails because of this.

**Comment by steelbrain** [comment]
@bountin You might want to read [this wiki page][1].

[1]:https://github.com/facebook/hhvm/wiki/DSO-3.5.0

**Comment by bountin** [comment]
Great! Thanks!
