### ISSUE TITLE
Travis build errors

### ISSUE THREAD

**Issue by Majkl578** [facebook/hhvm#4640]
There is a lot of borked builds for PRs on Travis (https://travis-ci.org/facebook/hhvm/pull_requests), e.g.:
```
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
make[2]: *** [hphp/compiler/CMakeFiles/hphp_analysis.dir/package.cpp.o] Error 4
make[2]: *** Waiting for unfinished jobs...
```

**Comment by wjywbs** [comment]
How about changing `time make -j 6` to `time make -j 6 || time make -j 6` in .travis.yml? So it can try to build again. Decreasing the job numbers in the 2nd try may also help.

**Comment by jrobeson** [comment]
maybe it ran out of memory? that's the same error i'd get before i setup a swap file on my vm.

**Comment by denji** [comment]
@jrobesonIn travis disabled by default swap, so he immediately after memory leaks crashed!
 https://github.com/travis-ci/travis-ci/issues/1972#issuecomment-35351862
> builds have 3 GB of memory available
http://docs.travis-ci.com/user/ci-environment/#The-Build-Machine

**Comment by jwatzman** [comment]
@paulbiss @sgolemon why do we even still have the travis config? It's consistently broken and we ignore it anyways. Should we just remove it?

**Comment by denji** [comment]
@jwatzman It would be better if fb has offered its version of travis to check the pull request and live migration.

**Comment by jrobeson** [comment]
the travis configuration has been dropped from HHVM as of https://github.com/facebook/hhvm/commit/658ca01c71251ea1b4b8667d402915269906e86e so this issue should be closed
