### ISSUE TITLE
Multiple Linode NodeBalancers = Spewing Half-Open Connections

### ISSUE THREAD

**Issue by CannibalVox** [facebook/hhvm#4644]
Hi,

We've just ended this issue, but for this past week, our website has been nearly unvisitable due to HHVM spewing half-open connections all over the file system.  These connections would show up in lsof, but not ss or netstat.  We changed several network, HHVM, and nginx properties, restarted HHVM and nginx over a dozen times, and restarted the box a couple times too.  During a period of time when our file count cap was extremely high, we could rack up between 500,000 and 1,000,000 of these half-open connections over night and the performance of the server was badly degraded for most of the time.

Ultimately, we were able to correct the problem by removing a second Linode NodeBalancer that we'd added earlier in the week.  Now all four boxes are humming along just fine.  The boxes are Linode 8GB boxes, with nginx and HHVM connected via fastcgi.  The balancers are standard NodeBalancers set up with table-based session stickiness and new connections were routed with a least-connections algorithm.  Our site is behind CloudFlare- we added the second balancer to cloudflare to put it into the rotation and removed it from cloudflare when we got rid of it.

I have no idea how this is even possible, but having a second balancer wrecked our hardware pretty badly.

**Comment by CannibalVox** [comment]
On our machines, HHVM is version 3.4.2.

**Comment by fcorriga** [comment]
Having the same problem, without linode though.
Actually HHVM 3.4.x fills up the file open limit in 10-12 hours (over 1.5 millions of open files). As usual, the problem happens on the production server only.
Everything works with HHVM 3.3.x

**Comment by paulbiss** [comment]
We've made significant changes to our fastcgi implementation since this was reported (87f853d16db9fb0b443f856de1c5f28a6803b5c8 in 3.6+). As there wasn't a clear repro in the first place I'm going to close the issue. If anyone is still experiencing this problem please comment so we can investigate further.
