### ISSUE TITLE
Method 'ArrayObject::getIterator' returns different results in HHVM and PHP

### ISSUE THREAD

**Issue by Sanuch** [facebook/hhvm#4645]
Method [getIterator](http://3v4l.org/Nu4rE) always return same object in PHP and new object in HHVM

**Comment by SiebelsTim** [comment]
This actually fails due to HHVM not using a reference to `ArrayObject` in `ArrayIterator` as `$storage`.

Consider this test case http://3v4l.org/ef5at. With that test we see, that the issue is in `ArrayIterator`: http://3v4l.org/5c5LX

**Comment by SiebelsTim** [comment]
This is still a valid issue. But it will be a pain to fix :p

**Comment by paulbiss** [comment]
@SiebelsTim: worth reopening?

**Comment by SiebelsTim** [comment]
@paulbiss I can see people running into troubles because objects are passed by reference and people expect that. 
Unfortunately fixing this is horrible. But I'd reluctantly say yes.

**Comment by zxqfox** [comment]
Thanks ;-( Will wait for a fix.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

It appears ArrayObject was removed from hhvm in January of 2020 in this [diff](https://github.com/facebook/hhvm/commit/6cf35c3ec4408eab3e4ffe1c8132c529a25d81ea#diff-cf73158617a5d4d976eda8e2f5132659). This roughly to hhvm 4.42-ish, but the blogpost does not mention this breaking change.
