### ISSUE TITLE
mb_convert_variables: Cannot access property started with '\0'

### ISSUE THREAD

**Issue by karpa13a** [facebook/hhvm#4646]
sorry for ugly test case
rename issue if needed (i don't know where problem is or it affects another functions)

$ hhvm --version
HipHop VM 3.5.0-dev~nightly.2015.01.11 (rel)
Compiler: heads/master-0-ge3761e46300e2dd92feab7ff984029369362de6f
Repo schema: 6fec97a49b717f7eb4f7c9948bdeec3d0ca46fa2
Extension API: 20140829
$ php5 -v
PHP 5.5.9-1ubuntu4.5 (cli) (built: Oct 29 2014 11:59:10) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
$ cat 1.php 

``` php
<?php
class Dummy {
    public $pub = 0;
    protected $prot = 1;
    private $priv = 2;
}

$value = new Dummy();
mb_convert_variables( 'utf-8', 'windows-1251', $value );
var_dump($value);
```

$ php5 1.php

```
object(Dummy)#1 (3) {
  ["pub"]=>
  int(0)
  ["prot":protected]=>
  int(1)
  ["priv":"Dummy":private]=>
  int(2)
}
```

$ hhvm 1.php 

Fatal error: Cannot access property started with '\0' in 1.php on line 9

**Comment by karpa13a** [comment]
ping

**Comment by paulbiss** [comment]
We probably need to pass a context parameter to `o_set` to allow private property access [here](https://github.com/facebook/hhvm/blob/cbeea88ed6355a80fb6858d158552a62f97d4db2/hphp/runtime/ext/mbstring/ext_mbstring.cpp#L1343-L1344), though to be honest the way this function is structured is pretty horrible, might be worth refactoring the way we do the property access. Alternatively, you could change `toArray()` above to `toArray(true)` to only update public members. I'm unclear on how `mb_convert_variables` behaves w/r/t private/protected properties though.

**Comment by karpa13a** [comment]
okay. next round:
4646-2.php:
```php
<?php
class Dummy {
    public $pub = 0;
    public $pub_string = "string";
    protected $prot = 1;
    protected $prot_string = "string";
    private $priv = 2;
    private $priv_string = "string";
}

$value = new Dummy();
$json=json_encode($value);
var_dump($value);
var_dump($json);
```

produces segfault:
```
ProcessID: 1562
ThreadID: 7faace524680
ThreadPID: 1562
Name: /usr/bin/hhvm
Type: Segmentation fault
Runtime: hhvm
Version: heads/master-0-ge4efb81d9d8d302cd46400c44dada7d387308083
DebuggerCount: 0

Arguments: 4646-2.php
ThreadType: CLI

# 0  ?? at hhvm:0
# 1  HPHP::jit::x64::BackEnd::enterTCHelper(unsigned char*, HPHP::ActRec*) at hhvm:0
# 2  HPHP::jit::MCGenerator::enterTC(unsigned char*, HPHP::ActRec*) at hhvm:0
# 3  HPHP::ExecutionContext::invokeFunc(HPHP::TypedValue*, HPHP::Func const*, HPHP::Variant const&, HPHP::ObjectData*, HPHP::Class*, HPHP::VarEnv*, HPHP::StringData*, HPHP::ExecutionContext::InvokeFlags) at hhvm:0
# 4  HPHP::ExecutionContext::invokeUnit(HPHP::TypedValue*, HPHP::Unit const*) at hhvm:0
# 5  ?? at hhvm:0
# 6  HPHP::include_impl_invoke(HPHP::String const&, bool, char const*) at hhvm:0
# 7  HPHP::hphp_invoke(HPHP::ExecutionContext*, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, HPHP::Array const&, HPHP::VRefParamValue const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool&, std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, bool, bool, bool) at hhvm:0
# 8  HPHP::hphp_invoke_simple(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) at hhvm:0
# 9  ?? at hhvm:0
# 10 HPHP::execute_program(int, char**) at hhvm:0
# 11 main at hhvm:0
# 12 __libc_start_main at /lib/x86_64-linux-gnu/libc.so.6:0
# 13 ?? at hhvm:0
```

and first example also sigfaults with same message

**Comment by karpa13a** [comment]
one more hit about mb_convert_variables:
```php
<?php
$a[] = &$a;
mb_convert_variables('utf-8', 'auto', $a);
```
produces sigfault with today's nightly
```
HipHop VM 3.7.0-dev (rel)
Compiler: heads/master-0-gcf047fe5c43aa7133ce5703d883251a3da486821
Repo schema: 9981acfe90e4e9812a5f3b03362744cae060a1d0
```

repro from https://bugs.php.net/bug.php?id=66964

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones are very unlikely to be worked on.

This PHP function takes arguments `3..n` by reference. This has been replaced with Hack `inout` in the 3rd argument, and the 4th to the nth argument are not used (I believe). I expect the more regular, string in, string out, conversion functions to be used in a majority of usecases. Compatibility with PHP has been dropped with hhvm 4.0.0. Fixes to rarely used `__PHPStdLib` functions seem very unlikely to me.
