### ISSUE TITLE
Unserialize fails when missing trailing semi-colon.

### ISSUE THREAD

**Issue by TJ09** [facebook/hhvm#4647]
Trying to ``unserialize`` a string that is missing the final character fails with an E_NOTICE in HHVM. While this initially sounds like the sane thing to do, Zend PHP happily accepts the string, so this is some form of PHP incompatibility:

```php
<?php

var_dump(unserialize('s:4:"abcd"'));
var_dump(unserialize('s:4:"abcd";'));
```

http://3v4l.org/rFHFn shows that Zend PHP accepts both strings, while HHVM refuses the first one.

**Comment by reeze** [comment]
HHVM is more strict

```php
<?php
var_dump(unserialize('s:4:"abcd"XXXX'));    // works in PHP but not HHVM
```

**Comment by sgolemon** [comment]
Sigh... PHP...
