### ISSUE TITLE
uasort() different behaviour then php5 for equal values

### ISSUE THREAD

**Issue by tmotyl** [facebook/hhvm#4649]
The order of the sorted values is different on PHP5 than sorting in HHVM.
```
function compare( $a, $b) {
    $key = 'title';
    $ascending = true;
    return ($ascending) ? strcasecmp($a[$key], $b[$key]) : strcasecmp($b[$key], $a[$key]);
}

$x = array(
					22 => array(
						'uid' => '22',
						'title' => 'b',
						'dummy' => 2
					),
					24 => array(
						'uid' => '24',
						'title' => 'a',
						'dummy' => 3
					),
					23 => array(
						'uid' => '23',
						'title' => 'a',
						'dummy' => 4
					),
				);
uasort($x, 'compare');
var_dump($x);
```
see
http://3v4l.org/kCEKI

Because of that some TYPO3 unit tests are failing. e.g.
TYPO3\CMS\Core\Tests\Unit\Utility\ArrayUtilityTest::sortArraysByKeyCheckIfSortingIsCorrect

**Comment by WizKid** [comment]
There is a setting if you want PHP5 sort order. But it is slower.

**Comment by paulbiss** [comment]
`hhvm.enable_zend_sorting=1`

**Comment by fredemmott** [comment]
There is no 'correct' ordering for elements that compare equal. We won't be changing the default behavior in this case.

**Comment by tmotyl** [comment]
Thanks for clarification!

**Comment by tmotyl** [comment]
What is the best practice? Should I mark these tests as blacklist in TYPO3 parity suite, or configure hhvm somehow to use zend sorting?

**Comment by fredemmott** [comment]
Modify whatever depends on this (just the tests?) to not depend on undefined behavior.

**Comment by fredemmott** [comment]
This behavior is also changing in PHP7 (though I'm not sure about this specific example): https://github.com/php/php-src/pull/999

**Comment by aftabnaveed** [comment]
hhvm.enable_zend_sorting=1 I am not sure if that settings has any impact on the performance, I tried that that with magento pricing and I don't see any performance penalty

**Comment by paulbiss** [comment]
The implementation is of sort is somewhat less performant but you may not notice a measurable difference, in which case it likely doesn't matter for your application.
