### ISSUE TITLE
Add <<__Deprecated>> attribute

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#4651]
New feature in C++14 :)

I'd suggest:
- typechecker error when called unless there's an HH_FIXME
- runtime notice
- [edit] support ReflectionFunctionAbstract::isDeprecated()

**Comment by elgenie** [comment]
Yeah, I've had some thoughts about this one for a while :)

The inspiration is actually http://php.net/manual/en/reflectionfunctionabstract.isdeprecated.php and making that work correctly in both the runtime and the typechecker

**Comment by int3** [comment]
I'd like to take this on. Both the Hack and runtime parts :)

**Comment by reeze** [comment]
:+1:

**Comment by steelbrain** [comment]
https://github.com/facebook/hhvm/commit/f38531e42f740a7ee942216da2a6b6ca01b2270c

**Comment by reeze** [comment]
@int3  So the runtime part will come later right? :)

**Comment by paulbiss** [comment]
There's already support in ext_reflection (43c6134bceacc4c15e3969dea3f229c37722d1df). I think @int3 is planning to add E_DEPRECATED messages to functions marked deprecated in a followup patch.

**Comment by int3** [comment]
Yes, runtime support will be coming later.

**Comment by milesj** [comment]
I did something similar in user-land: https://github.com/titon/framework/blob/master/src/Titon/Debug/Annotation/Deprecated.hh

But would much prefer this built-in! Especially if it also worked on methods.

**Comment by fredemmott** [comment]
This is now a built-in for the typechecker (https://github.com/facebook/hhvm/commit/f38531e42f740a7ee942216da2a6b6ca01b2270c), but not enforced by the runtime.

**Comment by milesj** [comment]
Awesome! Looking forward to this in 3.6?

**Comment by int3** [comment]
@elgenie implemented runtime support in fd94fd1e22a7ad332dc5967403be1687de89b940.
