### ISSUE TITLE
Make shapes implement KeyedIterable<string,mixed>?

### ISSUE THREAD

**Issue by kilahm** [facebook/hhvm#4662]
Would it be possible for the type checker to not balk at iterating over shapes?  Essentially making them implement the `KeyedIterable<string,mixed>` interface (at least according to the type checker).

I love how shapes can mirror the structure of the DB table, or just be a specific data structure to be passed around your code.  But it would be great if we could erase the definite structure (i.e., transform the shape into one of the collection types) to perform map/reduce (or any other generic transform) on the data.

One prominent use case would be to use the shape to generate an SQL insert or update statement in a generic way.  (i.e., a single function could take any keyed iterable to create a prepared statement).

**Comment by jwatzman** [comment]
This really isn't the intended use case for shapes -- they're like a super lightweight object, with all public members. I'm against for this for the same reason that I'd be against making objects `KeyedIterable<string, mixed>` -- if you want to iterate over it, don't use a shape/object, use a map.

What would the body of the loop look like? What would it do with the data? It's still going to have to do some case analysis on the type, at which point you've lost the benefit of it being a shape.

If you *really* want to, I think you can cast to array?

**Comment by kilahm** [comment]
> I think you can cast to array?
When casting to an array: `(array) cast forbidden in strict mode; arrays with unspecified key and value types are not allowed (Typing[4007])`

Array casting would certainly fit my use case.

> It's still going to have to do some case analysis on the type, at which point you've lost the benefit of it being a shape.
I agree that the loop or mapping function, or whatever transform to be done would need to do some sort of type analysis.  However, I do not believe you've lost the benefit of it being a shape.  Every other place the data was passed to would know of the definite structure.

In my example, I want to use a shape when loading data from a persistent store.  This will allow the type checker to tell me if I forgot to load a particular field (especially important on a schema change).

I now have the data in a nice and organized shape, but I want to send some updated data back to the store.  As it stands now, I have to explicitly name each of my fields to generate my SQL insert/update statement (or whatever other type of data store I'm using).  The same type checking must happen, I'm just typing out each of the elements of the shape.

> if you want to iterate over it, don't use a shape/object, use a map
If I use a map for the iteration, I've lost the type checker yelling at me when I don't include a field while loading data.

Not allowing for iteration on shapes seems like an artificial limitation.  Shapes (and objects with only public members) are conceptually the same as `Map<string, mixed>`.  The case of the `Map`, the keys are dynamically defined, and the type that each key is mapped to is dynamically defined.  In the case of the `shape`/`class`, the keys are statically defined as well as the type that each key is mapped to.

I can understand not allowing iteration over objects because of the existence of shapes.  I just don't understand why iterating over shapes is any worse than iterating over `Map<string, mixed>`.

**Comment by simonwelsh** [comment]
I feel like this is fixed by `Shapes::toArray`, which works in strict mode.
