### ISSUE TITLE
__get(), no reference return, indirect motification: should trigger notice.

### ISSUE THREAD

**Issue by hrach** [facebook/hhvm#4664]
In PHP if you try to write into magic property not returned as reference, E_NOTICE is thrown.

``` php
class Row
{
    public function __get($name)
    {
        return [];
    }
}

$row = new Row();
$row->whatever[] = 'Foo'; // this triggers E_NOTICE in PHP.
```

`Notice: Indirect modification of overloaded property Row::$whatever has no effect in test.php on line 12`

**Comment by SiebelsTim** [comment]
duplicate #1418

This title is way better though.

**Comment by paulbiss** [comment]
I think we should be able to do this by raising a notice when we're going to return the result of invokeGet from propImpl with MOpFlags::Define. We'll need to evaluate the performance implications but I doubt there will be any.

https://github.com/facebook/hhvm/blob/913ad365f65991c1d4f3ecd507386bbdc8eb011f/hphp/runtime/base/object-data.cpp#L1212-L1214

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

The magic method `__get()` has been removed from hhvm in version [4.56](https://hhvm.com/blog/2020/05/04/hhvm-4.56.html) and references were removed in version [4.41](https://hhvm.com/blog/2020/01/21/hhvm-4.41.html).
