### ISSUE TITLE
HTTP Cache doesn't work as expected

### ISSUE THREAD

**Issue by redstrike** [facebook/hhvm#4665]
I detected this issue on both HHVM stable 3.4.2 & HHVM 3.6.0-dev. I want to take advantage of public proxy & client's browser cache for faster UX, but it seem that HHVM prevents public proxy (I'm not sure) & browser from caching those requests.

My web server (LiteSpeed) added a redundant Cache-Control header beside mine, but PHP runtime works fine. HHVM doesn't on the same codebase.

```
Cache-Control: public, max-age=0
Cache-Control: public, s-maxage=300, max-age=900
```

**Comment by jwatzman** [comment]
- What is the output when run on PHP5?
- To be clear, one of those lines is added by you, the other added by HHVM, and the HHVM one is interfering with the behavior you want? Which line is which?

**Comment by redstrike** [comment]
Cache-Control: public, max-age=0
=> This header is automatically added by LiteSpeed / LSWS (it seem not a PHP's behavior).

Cache-Control: public, s-maxage=300, max-age=900
=> This is my app's caching policy.

In short, with same app source code, LSWS + PHP5 => browser can cache the response. LSWS + HHVM => browser cannot (I don't know why).

If you cannot repro this bug/behaviour on your machine, maybe it's not HHVM's bug.

**Comment by jwatzman** [comment]
> In short, with same app source code, LSWS + PHP5 => browser can cache the response. LSWS + HHVM => browser cannot (I don't know why).

Are the headers the same in the two cases? In particular, what do the headers look like when running with PHP5?

**Comment by redstrike** [comment]
HHVM
![hhvm_cache](https://cloud.githubusercontent.com/assets/2168227/5831524/07d0ce9c-a167-11e4-9d3c-67e7e23f98c9.jpg)

PHP5
![lsphp5_cache](https://cloud.githubusercontent.com/assets/2168227/5831525/08739a1e-a167-11e4-8f57-536a5ff1a245.jpg)

The differences are at:
Content-Length: 
Transfer-Encoding: chunked

```
# HHVM normal page load
Cache-Control: private, max-age=900
Cache-Control: public, max-age=0
Connection: Keep-Alive
Content-Encoding: gzip
Content-Type: text/html; charset=utf-8
Date: Wed, 21 Jan 2015 04:59:41 GMT
Expires: Wed, 21 Jan 2015 04:59:41 GMT
Keep-Alive: timeout=5, max=100
Server: LiteSpeed
Transfer-Encoding: chunked
Vary: Accept-Encoding
X-Powered-By: HHVM/3.6.0-dev
X-UA-Compatible: IE=edge

# PHP5 normal page load
Cache-Control: private, max-age=900
Cache-Control: public, max-age=0
Connection: Keep-Alive
Content-Encoding: gzip
Content-Length: 10709
Content-Type: text/html; charset=UTF-8
Date: Wed, 21 Jan 2015 04:34:37 GMT
Expires: Wed, 21 Jan 2015 04:34:37 GMT
Keep-Alive: timeout=5, max=100
Server: LiteSpeed
Vary: Accept-Encoding
X-Powered-By: PHP/5.6.4
X-UA-Compatible: IE=edge
```

```
# HHVM XHR Response
Cache-Control:public, max-age=0
Cache-Control:public, s-maxage=900, max-age=3600
Connection:Keep-Alive
Content-Encoding:gzip
Content-Length:2832
Content-Type:text/html; charset=utf-8
Date:Wed, 21 Jan 2015 05:12:51 GMT
Expires:Wed, 21 Jan 2015 05:12:51 GMT
Keep-Alive:timeout=5, max=100
Server:LiteSpeed
Vary:Accept-Encoding
X-Powered-By:HHVM/3.6.0-dev
X-UA-Compatible:IE=edge

# PHP5 XHR Response
Cache-Control:public, max-age=0
Cache-Control:public, s-maxage=900, max-age=3600
Connection:Keep-Alive
Content-Encoding:gzip
Content-Type:text/html; charset=UTF-8
Date:Wed, 21 Jan 2015 05:13:31 GMT
Expires:Wed, 21 Jan 2015 05:13:31 GMT
Keep-Alive:timeout=5, max=100
Server:LiteSpeed
Transfer-Encoding:chunked
Vary:Accept-Encoding
X-Powered-By:PHP/5.6.4
X-UA-Compatible:IE=edge
```

**Comment by jnyrup** [comment]
According to https://code.google.com/p/chromium/issues/detail?id=106555 you have to set the `Last-Modified` header, otherwise a chunked response cannot be validated against the cache.

**Comment by jwatzman** [comment]
Yeah, the headers look pretty consistent, so this does look like the browser deciding it doesn't like some subtle way that you've violated the spec (as opposed to an HHVM bug; it wouldn't surprise me if some config would cause PHP5 to do the same). What @jnyrup posted above about the chunked vs. last-modified looks like a plausible first place to start.

**Comment by redstrike** [comment]
Ok, so this problem doesn't belong to HHVM. I will contact LiteSpeed team to inform them about this.
