### ISSUE TITLE
hh_client didn't check a simple php error, $this->$value.

### ISSUE THREAD

**Issue by Rainha** [facebook/hhvm#4668]
Hi. I typo a member variable $this->$value in a php class.
And I typing command line "hh_client", and result is "No errors!".
I ran the php file in my web browser, but nothing was printed. 
I felt it's strange, so I ran the same php file in my apache server without HHVM.
and the result is this,
"Fatal error: Cannot access empty property in /filelocation/ on line #. "
Is it right hhvm says the php file has a error?

this is my hhvm version.

HipHop VM 3.5.0-dev~nightly.2015.01.11 (dbg)
Compiler: heads/master-0-ge3761e46300e2dd92feab7ff984029369362de6f
Repo schema: 6fec97a49b717f7eb4f7c9948bdeec3d0ca46fa2
Extension API: 20140829

**Comment by SiebelsTim** [comment]
It's not an error per se. Consider this

```
<?php
class C {
  public $a = "xx";
  public function test() {
    $b = 'a';
    echo $this->$b; // b evaluated to 'a'. so we access $this->a
  }
}
(new C)->test();
```

The manuals says: 
> While Hack is quite symbiotic with the PHP language, there are some PHP features that are not supported by Hack and the type checker. Here is a non-exhaustive list:
> -  [...]  Variable variables (e.g. $a = "hello"; $$a = "world"; echo "$a + $hello";) [...]

http://docs.hhvm.com/manual/en/hack.unsupported.php

I am not sure if the typechecker should issue a warning.

cc @jwatzman

**Comment by Rainha** [comment]
Abosultely you r right :D Thanks

**Comment by jwatzman** [comment]
- The code @SiebelsTim listed is valid PHP.
- Hack indeed does not support that syntax, as the link he added indicates.
- So it's not valid Hack, but the typechecker won't yell at you since you started the file with `<?php` and not `<?hh` -- you didn't indicate that it's Hack code.
