### ISSUE TITLE
error_log() does not support message_type 4

### ISSUE THREAD

**Issue by whatthejeff** [facebook/hhvm#4671]
http://3v4l.org/NjkJI

**Comment by paulbiss** [comment]
Type 4 is SAPI, I don't think we currently have any support for that outside of ext_zend_compat.

https://github.com/php/php-src/blob/695176458f0b039cd601ea2c7ca006f59efbc56a/ext/standard/basic_functions.c#L4752-L4758

**Comment by lexidor** [comment]
This is still true, updated repro because 3v4l does not support running code on hhvm anymore.

```Hack
<<__EntryPoint>>
function main(): void {
    \error_log('hello', 4);
}
```

It literally prints `error_log does not support message_type 4!`.

The zend compat mode was removed and @paulbiss says that we can't support this outside of that. @paulbiss can this issue be closed?

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

I forgot to loop back to this issue after asking the question above. I'll assume that the removal of zend compat and hhvm's departure from php are enough reason to mark this as wontfix.
