### ISSUE TITLE
Connection to Redis failed after 2 failures (persistent only)

### ISSUE THREAD

**Issue by craigcarnell** [facebook/hhvm#4674]
When using hhvm-3.5.0 and enabling persistent connections to Redis, I am getting the following error. If I disable persistent connections, it works without issue.

ls -la /tmp/redis_6379.sock
```
srwxrwxrwx 1 root root 0 Jan  9 11:22 /tmp/redis_6379.sock
```

Magento system.log
```
2015-01-19T10:35:00+00:00 ERR (3): Warning: unable to connect to unix:///tmp/redis_6379.sock:0 [2]: No such file or directory  in  on line 0
2015-01-19T10:35:00+00:00 ERR (3): Warning: Failed connecting to redis server at unix:///tmp/redis_6379.sock: No such file or directory  in  on line 0
2015-01-19T10:35:00+00:00 ERR (3): Warning: unable to connect to unix:///tmp/redis_6379.sock:0 [2]: No such file or directory  in  on line 0
2015-01-19T10:35:00+00:00 ERR (3): Warning: Failed connecting to redis server at unix:///tmp/redis_6379.sock: No such file or directory  in  on line 0
```

Magento report:
```
a:4:{i:0;s:44:"Connection to Redis failed after 2 failures.";i:1;s:1831:"#0 /var/www/vhosts/magento-capistrano-staging/releases/20150119101721/lib/Credis/Client.php(426): Credis_Client->connect()
#1 /var/www/vhosts/magento-capistrano-staging/releases/20150119101721/lib/Credis/Client.php(688): Credis_Client->connect()
#2 /var/www/vhosts/magento-capistrano-staging/releases/20150119101721/lib/Credis/Client.php(586): Credis_Client->__call()
#3 /var/www/vhosts/magento-capistrano-staging/releases/20150119101721/lib/Cm/Cache/Backend/Redis.php(135): Credis_Client->select()
#4 /var/www/vhosts/magento-capistrano-staging/releases/20150119101721/lib/Zend/Cache.php(153): Cm_Cache_Backend_Redis->__construct()
#5 /var/www/vhosts/magento-capistrano-staging/releases/20150119101721/lib/Zend/Cache.php(94): Zend_Cache::_makeBackend()
#6 /var/www/vhosts/magento-capistrano-staging/releases/20150119101721/app/code/core/Mage/Core/Model/Cache.php(137): Zend_Cache::factory()
#7 /var/www/vhosts/magento-capistrano-staging/releases/20150119101721/app/code/core/Mage/Core/Model/Config.php(1348): Mage_Core_Model_Cache->__construct()
#8 /var/www/vhosts/magento-capistrano-staging/releases/20150119101721/app/Mage.php(463): Mage_Core_Model_Config->getModelInstance()
#9 /var/www/vhosts/magento-capistrano-staging/releases/20150119101721/app/code/core/Mage/Core/Model/App.php(401): Mage::getModel()
#10 /var/www/vhosts/magento-capistrano-staging/releases/20150119101721/app/code/core/Mage/Core/Model/App.php(295): Mage_Core_Model_App->_initCache()
#11 /var/www/vhosts/magento-capistrano-staging/releases/20150119101721/app/code/core/Mage/Core/Model/App.php(337): Mage_Core_Model_App->baseInit()
#12 /var/www/vhosts/magento-capistrano-staging/releases/20150119101721/app/Mage.php(684): Mage_Core_Model_App->run()
#13 /var/www/vhosts/magento-capistrano-staging/releases/20150119101721/index.php(117): Mage::run()
#14 {main}";s:3:"url";s:1:"/";s:11:"script_name";s:10:"/index.php";}
```

Magento is EE 1.14.1.0. CM Redis Cache and CM Redis Session modules are in use. Configuration is specified in local.xml, e.g. persistent is set to cache-db0 etc.

**Comment by jwatzman** [comment]
- Is this a regression in 3.5.0, or is that the first version you've tried? If you've tried, has it worked on PHP5? I'm trying to rule out a misconfiguration unrelated to HHVM. (Though it looks like this is a standard Magento option, so such a misconfiguration sounds unlikely?)
- What user is HHVM running as? Is the socket *actually* readable -- I realize the `ls` you listed indicates so, but IIRC there's some weird stuff with sockets and permissions?
- Do you have a repro case we could use? i.e., if this is an umodified Magento install with some particular configuration change?

**Comment by aftabnaveed** [comment]
can you try setting <standalone>0</standalone> in your local.xml,  I am using the Credis library and it works perfectly fine, but having issue with the standalone mode.

**Comment by craigcarnell** [comment]
@jwatzman It's the first time persistent connections are supported. It works in PHP5.
HHVM is running as www-data. It can connect to the socket when persistent connections are not being used.
For the repo, no it is a modified magento install.

@aftabnaveed I tried that, made no difference. Thanks

**Comment by pepijnblom** [comment]
We have been running various production magento sites on hhvm since more than a year and afaik persistent redis connections have never been possible.

**Comment by craigcarnell** [comment]
@pepijnblom Persistent support was added recently in the new stable 3.5.0 build

**Comment by pepijnblom** [comment]
@craigcarnell I somehow missed that in the changelog I guess, thanks for the info. We'll start testing this on a smaller site..

**Comment by brijesh07** [comment]
Hi, 
I have a Error  "Connection to Redis failed after 2 failures."
When Using  code in local.xml file
<config>
<global>
     ....
<cache>
		  <backend>Cm_Cache_Backend_Redis</backend>
		  <backend_options>
			<server>23.229.229.65</server> 
			<port>6379</port>
			<persistent></persistent> 
			<password></password> 
			<force_standalone>0</force_standalone>  
			<connect_retries>1</connect_retries>    
			<read_timeout>10</read_timeout>         
			<automatic_cleaning_factor>0</automatic_cleaning_factor> 
			<compress_data>1</compress_data>  
			<compress_tags>1</compress_tags>  
			<compress_threshold>20480</compress_threshold>  
			<compression_lib>gzip</compression_lib> 
			<use_lua>0</use_lua> 
		  </backend_options>
		</cache>
</global>
</config>

Please Provide some solution

Thanks.
GitHub team

**Comment by paulbiss** [comment]
@brijesh07 please open a new issue with more details and preferably a small isolated example of the problem.
