### ISSUE TITLE
mysqli query HHVM  private object issue 

### ISSUE THREAD

**Issue by praveenkathari** [facebook/hhvm#4675]
HHVM :+1: 

mysqli_result Object ( [__result:mysqli_result:private] => Resource id #7 [__resulttype:mysqli_result:private] => 0 [__done:mysqli_result:private] => ) 

PHP 5.5
mysqli_result Object ( [current_field] => 0 [field_count] => 6 [lengths] => [num_rows] => 132 [type] => 0 ) 

Latest build on ubuntu 14.04  today

**Comment by WizKid** [comment]
Does this cause a problem? We do not have the same internal structure of objects and there is no plan to do.

**Comment by praveenkathari** [comment]
yes we are having issue , isset($query->num_rows)  returns  no value , so the query fetch no results .

**Comment by WizKid** [comment]
Can you write a small repro case? It should work even if it isn't stored as a private variable

**Comment by WizKid** [comment]
Hmm, I guess __isset needs to be implemented for mysqli_result just like we implemented __get here: https://github.com/facebook/hhvm/blob/cfbb62942298f079c6f7d028c4ec860fa4905f01/hphp/runtime/ext/mysql/ext_mysqli.php#L986

**Comment by praveenkathari** [comment]
<?php
final class DBMySQLi {
	private $link;

	public function __construct($hostname, $username, $password, $database) {
		$this->link = new mysqli($hostname, $username, $password, $database);

		if (mysqli_connect_error()) {
			throw new ErrorException('Error: Could not make a database link (' . mysqli_connect_errno() . ') ' . mysqli_connect_error());
		}

		$this->link->set_charset("utf8");
		$this->link->query("SET SQL_MODE = ''");

For testing When we call the function db here it working fine  
	}


	public function query($sql) {
		$query = $this->link->query($sql);

		if (!$this->link->errno){

It results the No value in the 'if' condition here , so we are seeing the above mentioned issue when we var_dump the query , all is well in PHP 5.5
			if (isset($query->num_rows)) {
				$data = array();

				while ($row = $query->fetch_assoc()) {
					$data[] = $row;
				}

				$result = new stdClass();
				$result->num_rows = $query->num_rows;
				$result->row = isset($data[0]) ? $data[0] : array();
				$result->rows = $data;

				unset($data);

				$query->close();

				return $result;
			} else{
				return true;
			}
		} else {
			throw new ErrorException('Error: ' . $this->link->error . '<br />Error No: ' . $this->link->errno . '<br />' . $sql);
			exit();
		}
	}

	public function __destruct() {
		$this->link->close();
	}
}
?>

**Comment by DmitrySoshnikov** [comment]
We'll have to move this to native prop handlers instead of user-level `__get` and `__isset`. And for this we'll need to fix working with classes defined directly in PHP extension file (like this one `mysqli_result`). In this case the fix will be a bit bigger than just adding the `__isset`.
