### ISSUE TITLE
PDO mysql Driver 

### ISSUE THREAD

**Issue by SolStis86** [facebook/hhvm#4677]
Hi,

I really struggled to get PDO to work with the mysqlnd driver through HHVM.  Using the ubuntu 14.04 and 14.01 packages, both seem to default to the standard mysqllib driver which when return DB  models, all data values are returned as strings not their assigned data type.  This caused severe issues when migrating my laravel app onto a nginx hhvm stack, specifically front end consumption of the REST API, so I've had to revert back to nginx fast cgi.  

The post here details the issue: http://stackoverflow.com/questions/26801856/how-to-make-mysql-driver-for-hhvm-return-ids-as-integers

 Has anyone come across this or found a solution for rebuilding the package with the correct mysql driver?

Thanks

**Comment by DmitrySoshnikov** [comment]
Yeah, I don't think HHVM has `mysqlnd` yet implemented.

**Comment by WizKid** [comment]
We don't support mysqlnd but that shouldn't be the reason you have these problems. If you can write a minimal repro that would be awesome.

**Comment by paulbiss** [comment]
Closing this as it's been waiting on additional information for more than a year.
