### ISSUE TITLE
Can we make phpinfo() better?

### ISSUE THREAD

**Issue by JoelMarcey** [facebook/hhvm#4678]
http://stackoverflow.com/questions/28015051/phpinfo-not-working-correctly-in-hhvm

**Comment by Majkl578** [comment]
:+1:

**Comment by reeze** [comment]
:+1:  I will try to improve it. There always someone asking what happened when he trying to test HHVM.

**Comment by reeze** [comment]
Sorry I didn't notice that @JoelMarcey  already self-assigned :) @JoelMarcey will be a better man to do the `ini` thing.

**Comment by tubaguy50035** [comment]
For others looking for a quick way to check settings: https://gist.github.com/ck-on/67ca91f0310a695ceb65

**Comment by shehi** [comment]
Jan 20th... Hmm...

**Comment by SiebelsTim** [comment]
@shehi This actually got better in 57b7c37cfbc00948860e43
Maybe this can be closed even.

**Comment by Orvid** [comment]
It still doesn't output compilation options or what extensions were compiled in though. The former should be relatively simple to implement, but the latter will take a significant refactor of the extension build setup.

**Comment by jwatzman** [comment]
Yeah, I don't consider this finished, just with a "quick fix" in place. Feel free to send a PR to add more stuff if you want it, but I'm not actively working on this right now.

**Comment by Orvid** [comment]
Well, with #5571 there is slightly more reason to implement the extension side. It can probably be done with the existing extension registry, although I've not looked at what exactly it provides. 

Compiler options should be easy to implement in CMake, but how hard would it be for FB's build?

**Comment by jwatzman** [comment]
> Compiler options should be easy to implement in CMake, but how hard would it be for FB's build?

Probably irrelevant for FB's purposes, we have a very uniform build system and so this info is much less useful for us, and we probably aren't going to be using `phpinfo()` anyways. As long as it doesn't break in our builds, it's fine.

**Comment by paulbiss** [comment]
Going to close this issue as the general functionality has been improved. If there are specific features anyone needs please open issues for them.
