### ISSUE TITLE
Memory issue with multiple IF/else

### ISSUE THREAD

**Issue by janwinkler** [facebook/hhvm#4683]
if you combine multiple if/else, hhvm fails with "Fatal error: memory exhausted in ....". on my test machine the magic number was 97 if/else. very simple sample code:

<?
  $s = rand(0,1999);
  if($s == 3){$x =0;}
else if($s == 11){$x =1;}
else if($s == 13){$x =2;}
else if($s == 15){$x =3;}
else if($s == 17){$x =4;}
else if($s == 19){$x =5;}
else if($s == 21){$x =6;}
else if($s == 23){$x =7;}
else if($s == 25){$x =8;}
else if($s == 27){$x =9;}
else if($s == 29){$x =10;}
else if($s == 31){$x =11;}
else if($s == 33){$x =12;}
else if($s == 35){$x =13;}
else if($s == 37){$x =14;}
else if($s == 39){$x =15;}
else if($s == 41){$x =16;}
else if($s == 43){$x =17;}
else if($s == 45){$x =18;}
else if($s == 47){$x =19;}
else if($s == 49){$x =20;}
else if($s == 51){$x =21;}
else if($s == 53){$x =22;}
else if($s == 55){$x =23;}
else if($s == 57){$x =24;}
else if($s == 59){$x =25;}
else if($s == 61){$x =26;}
else if($s == 63){$x =27;}
else if($s == 65){$x =28;}
else if($s == 67){$x =29;}
else if($s == 69){$x =30;}
else if($s == 71){$x =31;}
else if($s == 73){$x =32;}
else if($s == 75){$x =33;}
else if($s == 77){$x =34;}
else if($s == 79){$x =35;}
else if($s == 81){$x =36;}
else if($s == 83){$x =37;}
else if($s == 85){$x =38;}
else if($s == 87){$x =39;}
else if($s == 89){$x =40;}
else if($s == 91){$x =41;}
else if($s == 93){$x =42;}
else if($s == 95){$x =43;}
else if($s == 97){$x =44;}
else if($s == 99){$x =45;}
else if($s == 101){$x =46;}
else if($s == 103){$x =47;}
else if($s == 105){$x =48;}
else if($s == 107){$x =49;}
else if($s == 109){$x =50;}
else if($s == 111){$x =51;}
else if($s == 113){$x =52;}
else if($s == 115){$x =53;}
else if($s == 117){$x =54;}
else if($s == 119){$x =55;}
else if($s == 121){$x =56;}
else if($s == 123){$x =57;}
else if($s == 125){$x =58;}
else if($s == 127){$x =59;}
else if($s == 129){$x =60;}
else if($s == 131){$x =61;}
else if($s == 133){$x =62;}
else if($s == 135){$x =63;}
else if($s == 137){$x =64;}
else if($s == 139){$x =65;}
else if($s == 141){$x =66;}
else if($s == 143){$x =67;}
else if($s == 145){$x =68;}
else if($s == 147){$x =69;}
else if($s == 149){$x =70;}
else if($s == 151){$x =71;}
else if($s == 153){$x =72;}
else if($s == 155){$x =73;}
else if($s == 157){$x =74;}
else if($s == 159){$x =75;}
else if($s == 161){$x =76;}
else if($s == 163){$x =77;}
else if($s == 165){$x =78;}
else if($s == 167){$x =79;}
else if($s == 169){$x =80;}
else if($s == 171){$x =81;}
else if($s == 173){$x =82;}
else if($s == 175){$x =83;}
else if($s == 177){$x =84;}
else if($s == 179){$x =85;}
else if($s == 181){$x =86;}
else if($s == 183){$x =87;}
else if($s == 185){$x =88;}
else if($s == 187){$x =89;}
else if($s == 189){$x =90;}
else if($s == 191){$x =91;}
else if($s == 193){$x =92;}
else if($s == 195){$x =93;}
else if($s == 197){$x =94;}
else if($s == 199){$x =95;}
else if($s == 201){$x =96;}
else if($s == 203){$x =97;}
//else if($s == 205){$x =98;} //uncomment this line and the code fails with memory error

?>ok

**Comment by staabm** [comment]
I somehow rember we had reports of this in the past.. did you search the issue-tracker before?

**Comment by janwinkler** [comment]
i searched but did not find anything matching

**Comment by reeze** [comment]
It should be this one, https://github.com/facebook/hhvm/issues/2699 but they are not the same.

**Comment by janwinkler** [comment]
ah yes. ok close this one

**Comment by reeze** [comment]
And that fix are release with 3.5.0, and I can confirm that was fixed.  3.4.0 - have the problem  http://3v4l.org/JJeNS
