### ISSUE TITLE
failed to build with Intel compiler (icc) because lack of -std=c++11 option

### ISSUE THREAD

**Issue by domainname** [facebook/hhvm#4687]
I'm trying to build HHVM with Intel compiler (icc), by using the following commands.  Got an error saying -std=c++11 is missing.

```
$ cmake . -DCMAKE_C_COMPILER=icc -DCMAKE_CXX_COMPILER=icpc
$ make
...
[  6%] Building CXX object third-party/folly/CMakeFiles/folly.dir/folly/String.cpp.o
In file included from /usr/include/c++/4.8/unordered_set(35),
                 from /home/fhuang1/dev/hhvm.icc/third-party/folly/folly/String.h(31),
                 from /home/fhuang1/dev/hhvm.icc/third-party/folly/folly/String.cpp(17):
/usr/include/c++/4.8/bits/c++0x_warning.h(32): error: #error directive: This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
  #error This file requires compiler and library support for the \
   ^
...
```

I had to manually add this option to line 110 in CMake/HPHPCompiler.cmake:

```
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -no-ipo -fp-model precise -wd584 -wd1418 -wd1918 -wd383 -wd869 -wd981 -wd424 -wd1419 -wd444 -wd271 -wd2259 -wd1572 -wd1599 -wd82 -wd177 -wd593 -fno-omit-frame-pointer -ftemplate-depth-180 -Wall -Woverloaded-virtual -Wno-deprecated -w1 -Wno-strict-aliasing -Wno-write-strings -Wno-invalid-offsetof -fno-operator-names")
```

**Comment by paulbiss** [comment]
I think our configuration is only designed to support clang and gcc currently.

**Comment by jwatzman** [comment]
Yep, happy to take a PR to fix it, but we don't currently support icc.

**Comment by domainname** [comment]
It appears that you do support icc.  See https://github.com/facebook/hhvm/blob/master/CMake/HPHPCompiler.cmake#L107

```
# using Intel C++
elseif ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Intel")
  set(CMAKE_C_FLAGS   "${CMAKE_C_FLAGS} -no-ipo -fp-model precise -wd584 -wd1418 -wd1918 -wd383 -wd869 -wd981 -wd424 -wd1419 -wd444 -wd271 -wd2259 -wd1572 -wd1599 -wd82 -wd177 -wd593 -w")
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -no-ipo -fp-model precise -wd584 -wd1418 -wd1918 -wd383 -wd869 -wd981 -wd424 -wd1419 -wd444 -wd271 -wd2259 -wd1572 -wd1599 -wd82 -wd177 -wd593 -fno-omit-frame-pointer -ftemplate-depth-180 -Wall -Woverloaded-virtual -Wno-deprecated -w1 -Wno-strict-aliasing -Wno-write-strings -Wno-invalid-offsetof -fno-operator-names")
```

**Comment by paulbiss** [comment]
Hmm, interesting. I know in the past we've experimented with icc, but it never really worked well. We should probably either remove that or issue some sort of warning about the functionality not being officially supported.

**Comment by domainname** [comment]
Hi Paul,

I'm very interested in compiling HHVM with icc.  Since the conditional branch for icc is already there, why not add -std=c++11 to CMAKE_CXX_FLAGS, instead of removing the branch?

ps. I'll continue working on the compilation.  And will report back if there is any new issues.

**Comment by paulbiss** [comment]
@domainname: Sure, we can keep the branch, if you want to send us a PR to add that flag (and any others necessary) we'll gladly take it. To set expectations, we haven't attempted an icc build internally for a long time and are unlikely to be interested in doing so again.

Practically speaking, what that means is if you find issues building or running using icc we won't be able to offer much help (and if you do find crashes while running hhvm, we'd ask that you first reproduce them in either a gcc or a clang build before filing issues here). FWIW, the last time we had a working icc build I believe our gcc build was still outperforming it.

In any event, best of luck, and we'd definitely be happy to take your PRs. I just can't promise that we won't break icc unknowingly as we don't having any testing for it.

**Comment by domainname** [comment]
@paulbiss Thank you for keeping it.  Here is the PR I created a few sec ago.  https://github.com/facebook/hhvm/pull/4696

Sure.  I fully understand what you said.

**Comment by edwinsmith** [comment]
If people wan to make HHVM work with ICC, cool. I think you're seeing leftovers in our code from previous projects using ICC, but it's been along time since we've tried it (afaik, anyway).
