### ISSUE TITLE
"Frame buffer invalid" error when trying to profile via xdebug

### ISSUE THREAD

**Issue by ghost** [facebook/hhvm#4690]
Hey guys,

I'm trying to get HHVM to output xdebug cachegrind profile files, which I got working (after quite a bit of googling), but when running a script (via nginx) hhvm prints:

```
Error when writing xdebug profiling file /... Frame buffer invalid.
```

A cachegrind file is still created and I can open it with kcachegrind, but it seems incomplete with regards to the script that was called (also, I'm comparing it to the cachegrind file for the same script when run via php-fpm).

Here are some specs:

I'm running HHVM via:

```
hhvm --mode server -vServer.Type=fastcgi -vServer.Port=9001
```

**uname -a**

```
Linux labs-085 3.5.0-54-generic #81~precise1-Ubuntu SMP Tue Jul 15 04:02:22 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

**cat /etc/lsb-release**

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=12.04
DISTRIB_CODENAME=precise
DISTRIB_DESCRIPTION="Ubuntu 12.04.5 LTS"
```

**php -v**

```
PHP 5.4.32-1~ppa1~precise (cli) (built: Aug 29 2014 21:30:18) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
with Xdebug v2.2.1, Copyright (c) 2002-2012, by Derick Rethans
with uopz v2.0.5, Copyright (c) 2014, by Joe Watkins <krakjoe@php.net>
```

**cat /etc/hhvm/php.ini**

```
; php options
session.save_handler = files
session.save_path = /var/lib/php5
session.gc_maxlifetime = 1440

; hhvm specific
hhvm.log.level = Warning
hhvm.log.always_log_unhandled_exceptions = true
hhvm.log.runtime_error_reporting_level = 8191
hhvm.mysql.typed_results = false

; xdebug
xdebug.enable=1
xdebug.profiler_enable=1
xdebug.profiler_output_dir=/srv/log/xdebug
xdebug.profiler_output_name=cachegrind.out.%t.%p
```

Like I said, the cachegrind file is still created and the script does finish correctly (and way faster than with php-fpm, I might add), it's just that I get that error and the profile file is clearly incomplete (ie. there are a bunch of calls missing).

**Comment by ehcpdeveloper** [comment]
same situation on my side. similar configuration.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Xdebug support was removed from hhvm in version [3.27.0](http://hhvm.com/blog/2018/06/18/hhvm-3.27.0.html).
