### ISSUE TITLE
hh_client allows DEFAULT as constant name and HHVM does not

### ISSUE THREAD

**Issue by homerhsing** [facebook/hhvm#4694]
Cannot define following enum:

enum SomeEnum : string as string {
  DEFAULT = 'def';
}

because the constant name is "DEFAULT".

**Comment by reeze** [comment]
`DEFAULT` is a keyword they are case insensitive , you can not use it.

**Comment by jwatzman** [comment]
Yep, we're unlikely to support it, though `hh_client` would ideally report the error and currently does not.

**Comment by lexidor** [comment]
> Yep, we're unlikely to support it, though `hh_client` would ideally report the error and currently does not.

Actually, hhvm supports enum members named `default` and `DEFAULT` in hhvm 4.56. :smiley:.
```HACK
<<__EntryPoint>>
function main(): void {
    echo SomeEnum::default;
}

enum SomeEnum: string as string {
    default = 'def';
}
```

This echoes `def`.
