### ISSUE TITLE
HH Client Autocomplete should spawn a server

### ISSUE THREAD

**Issue by steelbrain** [facebook/hhvm#4697]
`hh_client` spawns a server and runs smoothly.
`hh_client --auto-complete` does not spawn a server only connects to it.
```
Error: could not connect to hh_server, retrying...
Error: could not connect to hh_server, retrying...
Error: could not connect to hh_server, giving up!
```

**Comment by SiebelsTim** [comment]
I think I stumbled upon this some time ago too.

**Comment by jwatzman** [comment]
Yeah, the "spawn a server if can't connect" logic is super janky and haphazard. IIRC the way `hh_client` is structured now you have to put it in each individual subcommand, which is pretty bad :( So the right way to fix this IMO is to refactor `hh_client` so you don't have to do that, which @int3 or @elgenie might have been thinking about? Maybe not.

**Comment by int3** [comment]
I have been thinking about it, yes. There are similar options handled subtly differently amongst the various subcommands, though, so I think there'll be some effort required to make sure we aren't breaking any of the consumers of these commands when we factor out that logic.

**Comment by int3** [comment]
This should be fixed now.

**Comment by steelbrain** [comment]
:clap: Awesome Thanks!
