### ISSUE TITLE
HHVM serialize() cannot handle non-UTF-8 high-value characters

### ISSUE THREAD

**Issue by hopeseekr** [facebook/hhvm#4700]
For this bug, we will use the French 'ç' character.

It has a high-ASCII ordinate value of 231 in the ISO-88591-1 character set, and a high ordinate value of 50087 in UTF-8.

HHVM, when it encounters high-value ISO-88591-1 data in the serialize(), it unceremoniously drops the characters, without a warning or otherwise any notification of what it has done.

Example:
```
function unichr($intval, $fromChar='UTF-8') {
    return mb_convert_encoding(pack('n', $intval), 'UTF-8', $fromChar);
}

$data = [
    'high UTF-8 char' => '-'.unichr(50087).'-',
    'high ISO-8859-1 char' => '-'.unichr(231).'-'
];

$serialized = serialize($data);
echo "Serialized: $serialized\n";
echo "Base64 serialized: " . base64_encode($serialized) . "\n";
$data = unserialize($serialized);

print_r($data);

foreach ($data as $key => $value) {
    echo "Base64 of $key: " . base64_encode($value) . "\n";
}
/* OUTPUT:
PHP 5.6.5:
Serialized: a:2:{s:15:"high UTF-8 char";s:4:"-ç-";s:20:"high ISO-8859-1 char";s:4:"-?-";}
Base64 serialized: YToyOntzOjE1OiJoaWdoIFVURi04IGNoYXIiO3M6NDoiLcOnLSI7czoyMDoiaGlnaCBJU08tODg1OS0xIGNoYXIiO3M6NDoiLQA/LSI7fQ==
Array
(
    [high UTF-8 char] => -ç-
    [high ISO-8859-1 char] => -?-
)
Base64 of high UTF-8 char: LcOnLQ==
Base64 of high ISO-8859-1 char: LQA/LQ==

HHVM latest-dev [and 3.4.0]:
Serialized: a:2:{s:15:"high UTF-8 char";s:4:"-ç-";s:20:"high ISO-8859-1 char";s:3:"--";}
Base64 serialized: YToyOntzOjE1OiJoaWdoIFVURi04IGNoYXIiO3M6NDoiLcOnLSI7czoyMDoiaGlnaCBJU08tODg1OS0xIGNoYXIiO3M6MzoiLQAtIjt9
Array
(
    [high UTF-8 char] => -ç-
    [high ISO-8859-1 char] => --
)
Base64 of high UTF-8 char: LcOnLQ==
Base64 of high ISO-8859-1 char: LQAt
*/
```

**Comment by jwatzman** [comment]
I'm skeptical of the security implications of this, but I'll put it at the top of my things to look into this coming week.

**Comment by jwatzman** [comment]
It doesn't look to be an issue with serialize, rather with your `unichr` function. Here's a different driver I wrote around your function:

```php
<?php
function unichr($intval, $fromChar='UTF-8') {
    return mb_convert_encoding(pack('n', $intval), 'UTF-8', $fromChar);
}

$c = [unichr(231)];
var_dump($c);
echo bin2hex($c[0]) . "\n";
echo base64_encode($c[0]) . "\n";

$s = serialize($c);
var_dump($s);

$us = unserialize($s);
var_dump($us);
echo bin2hex($us[0]) . "\n";
echo base64_encode($us[0]) . "\n";
```

According to http://3v4l.org/KR7KE even different versions of PHP disagree on the output -- some of them say the result of the `unichr` call is `00`, others say `003f`. The versions of HHVM on 3v4l.org say the former, but the build I have locally says the latter.

I don't know much about character encodings, but from reading your description plus your code for `unichr`, it sounds like you're trying to convert something that isn't actually unicode from unicode into unicode, or something weird like that? In which case I bet it's an i18n or character encoding library that gives different results depending on its exact version -- I know HHVM uses `libicu` at least which has historically been super finicky just like this about exact results in different edge cases.

**Comment by paulbiss** [comment]
Looks like recent versions of HHVM at least agree with PHP 7 and some versions of PHP 5

https://3v4l.org/U3T31
https://3v4l.org/caCee
