### ISSUE TITLE
Deprecate // UNSAFE, introduce equivalent // UNSAFE_BLOCK

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#4701]
Just for clarity.

**Comment by int3** [comment]
This would also solve the thing where people write `// UNSAFE_EXPR` (we interpret this the same way as `// UNSAFE` since it has the same prefix... changing it to recognize `// UNSAFE` with either a following space or newline would require some ugly lexer hacks)

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

`// UNSAFE`, `//UNSAFE_EXPR` and `// UNSAFE_BLOCK` were removed in hhvm version [4.8.0](https://hhvm.com/blog/2019/06/03/hhvm-4.8.0.html).
`HH_FIXME[4110]` is now the recommended way to inform the typechecker that you know something that it does not.
