### ISSUE TITLE
Segfaults when session storage is not writable

### ISSUE THREAD

**Issue by Diftraku** [facebook/hhvm#4703]
I got this weird occurrence, where if there happens to be a problem opening the session storage and a fatal occurs (in my case: undefined class) HHVM segfaults. Most curious is, this is very much repeatable.

I tried fiddling with ``gdb`` but alas, I am not yet versed in how it pokes at the internals of virtual memory. Most of the time, attaching gdb to the PID caused it to freeze and running ``bt`` would just show it is waiting for an event. After detaching, it would segfault when the query from nginx hit hhvm.

OS: Debian 7.8
HHVM Source: packages from dl.hhvm.com
HHVM: 3.5.0 (rel)
Compiler: tags/HHVM-3.5.0-0-ga90f4733cfa0d8fefdafc7433f758f78cdc75424
Repo schema: b88b6fee8ef78ab638506d212abcbefe74a276ac
Nginx: 1.6.2
HHVM is listening over unix socket.

Provided below are error logs and a stack trace from hhvm.
````
\nWarning: open(/var/lib/php5/sessions/sess_ec5b424fcb9f0b49ca94fab9308d7273, O_RDWR) failed: Permission denied (13) in /var/www/api/index.php on line 143
\nFatal error: Class undefined: R in /var/www/api/vendor/Diftraku/DerpyURL/DerpyURL/DerpyURL.php on line 94
Unhandled server exception: exception 'ErrorException' with message 'open(/var/lib/php5/sessions/sess_ec5b424fcb9f0b49ca94fab9308d7273, O_RDWR) failed: Permission denied (13)' in :0\nStack trace:\n#0 (): Slim\\Slim::handleErrors()\n#1 {main}
Core dumped: Segmentation fault
Stack trace in /tmp/stacktrace.1602.log
````
````
Host: fluffle
ProcessID: 1603
ThreadID: 7f20efbff700
ThreadPID: 1605
Name: unknown program
Type: Segmentation fault
Runtime: hhvm
Version: tags/HHVM-3.5.0-0-ga90f4733cfa0d8fefdafc7433f758f78cdc75424
DebuggerCount: 0


# 0  folly::IOBuf::countChainElements() const at /usr/bin/hhvm:0
# 1  folly::AsyncSocket::writeChain(folly::AsyncSocket::WriteCallback*, std::unique_ptr<folly::IOBuf, std::default_delete<folly::IOBuf> >&&, folly::WriteFlags) at /usr/bin/hhvm:0
# 2  HPHP::FastCGISession::writeStream(unsigned short, HPHP::FastCGISession::RecordType, std::unique_ptr<folly::IOBuf, std::default_delete<folly::IOBuf> >) at /usr/bin/hhvm:0
# 3  HPHP::FastCGITransaction::onStdOut(std::unique_ptr<folly::IOBuf, std::default_delete<folly::IOBuf> >) at /usr/bin/hhvm:0
# 4  std::_Function_handler<void (), HPHP::FastCGITransport::sendImpl(void const*, int, int, bool)::{lambda()#1}>::_M_invoke(std::_Any_data const&) at fastcgi-transport.cpp:0
# 5  folly::EventBase::runFunctionPtr(std::function<void ()>*) at /usr/bin/hhvm:0
# 6  folly::NotificationQueue<std::pair<void (*)(void*), void*> >::Consumer::consumeMessages(bool) at /usr/bin/hhvm:0
# 7  event_base_loop at /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5:0
# 8  folly::EventBase::loopBody(int) at /usr/bin/hhvm:0
# 9  folly::EventBase::loopForever() at /usr/bin/hhvm:0
# 10 proxygen::WorkerThread::runLoop() at /usr/bin/hhvm:0
# 11 std::thread::_Impl<std::_Bind_simple<proxygen::WorkerThread::start()::{lambda()#1} ()> >::_M_run() at WorkerThread.cpp:0
# 12 execute_native_thread_routine at /home/hiphop/gcc-build/x86_64-unknown-linux-gnu/libstdc++-v3/include/bits/shared_ptr_base.h:665
# 13 HPHP::start_routine_wrapper(void*) at /usr/bin/hhvm:0
# 14 start_thread at /lib/x86_64-linux-gnu/libpthread.so.0:0
# 15 __clone at /lib/x86_64-linux-gnu/libc.so.6:0
````

The file in question where the error log refers is https://github.com/Diftraku/DerpyURL/blob/d1c819a055bab01fd467f11d3df1b063f55ce66b/DerpyURL/DerpyURL.php#L93
After checking, the version running on the server does have a ``use R;``

I'll be glad to provide more info if required, thus far it is limited by my own inability to work gdb.

**Comment by jwatzman** [comment]
- This is weird. I wasn't able to reproduce this with the 3.5 build on wheezy -- same setup as you except for apache vs nginx, which I don't *think* should matter here?
- Can you paste the output of `ls -alR /var/lib/php5/sessions` so we can see what the permissions of that directory are? What user is `hhvm` running as? Can you paste the contents of any `ini` files that HHVM is using (`/etc/hhvm/*.ini` in a stock install).
- I think this should get you a backtrace. Figure out HHVM's pid (I usually use `ps auxwww | grep hhvm` though I think there are nicer ways). Run `sudo gdb $(which hhvm)`. Then `attach pid-of-hhvm`. When it attaches, `gdb` will stop the process, use `c` to continue it. It should continue responding, now run it to a segfault. GDB should catch that automatically and drop you to a prompt, then do `thread apply all bt`.
- If possible, when doing the above, replace the `hhvm` package with `hhvm-dbg`, which will get much richer information in the backtrace.

**Comment by Diftraku** [comment]
````
# ls -alR /var/lib/php5/sessions
ls: cannot access /var/lib/php5/sessions: No such file or directory
````
HHVM runs as ``www-data`` as per default on Debian.
Segfault backtrace: https://gist.github.com/Diftraku/e278e7c5b00e6928c8e9
php.ini: https://gist.github.com/Diftraku/cd2ed84ee9635aff574c
server.ini: https://gist.github.com/Diftraku/7ad4e7451aeec1876c50

I'll try to repro on the dbg version later on, so far this is on the prepackaged Debian version. I was unable to get the compiled from source version to even start.

**Comment by jwatzman** [comment]
Yeah, info from the `-dbg` version would probably be useful, no need to compile from source.

Can you do

`sudo mkdir -p /var/lib/php5/sessions && sudo chmod 777 /var/lib/php5/sessions && sudo chmod +t /var/lib/php5/sessions`

and see if that fixes it? We still shouldn't be crashing if the sessions directory doesn't exist and can't be created, but maybe the two are unrelated.

**Comment by jwatzman** [comment]
Yeah the session storage thing might be a red herring; the crash looks identical to #4703.

**Comment by Diftraku** [comment]
````
# hhvm --version
HipHop VM 3.5.0 (dbg)
Compiler: tags/HHVM-3.5.0-0-ga90f4733cfa0d8fefdafc7433f758f78cdc75424
Repo schema: b88b6fee8ef78ab638506d212abcbefe74a276ac
````
Segfault on -dbg: https://gist.github.com/Diftraku/1fe013a1a21d525924bd

After creating the sessions directory as ``www-data``:
````
# ls -alR /var/lib/php5/sessions
/var/lib/php5/sessions:
total 8
drwxr-xr-x 2 www-data www-data 4096 Jan 27 23:26 .
drwx-wx-wt 3 root     root     4096 Jan 27 23:24 ..
-rw------- 1 www-data www-data    0 Jan 27 23:26 sess_c719727c995bf5defd3b39301c1f86bf
````

I get an error for missing file (RedBean) as expected.

**Comment by jwatzman** [comment]
> After creating the sessions directory as www-data:

So it stopped crashing when you did this?

**Comment by Diftraku** [comment]
Yup, it sure did. When I was running the debug version, I could see the JSON output saying it could not find a file (RedBean) and never got the EOF, leaving the browser waiting for hhvm to send it while it segfaulted.

Could be that nginx leaves the connection open until it receives EOF from the fastcgi process, even though it segfaults.

**Comment by baptistemarchand** [comment]
Hi,

I just wanted to leave a quick comment here because we had a similar problem for a long time and just managed to fix it. We had the warning: Failed to write session data (user). Please verify that the current setting of session.save_path is correct. We tried changing the path and its permissions etc but actually our application was overriding the session handler and using memcached instead of files. The error happened because we couldn't write to memcached for some unrelated reason.
So don't trust the error message or the php.ini file and check the session handler!

Hopefully this can help someone one day.

**Comment by paulbiss** [comment]
Sounds like the mystery here is mostly resolved. If anyone finds a repro for the crash in a more recent hhvm comment here so we can try to fail more gracefully.
