### ISSUE TITLE
Inconsistency when using mt_srand

### ISSUE THREAD

**Issue by chrismou** [facebook/hhvm#4711]
I've come across something while testing a plugin for an IRC client that performs a "dice roll" and returns the results.  I got around testing it by seeding it with mt_srand in advance, noting the output, then using that pre-calculated output to compare to the actual output in the unit test.

This works with PHP 5.4, 5.5 and 5.6.  With HHVM, it returns a different set of random numbers every time, suggesting that the mt_srand seed isn't actually affecting it.

After a bit more digging, I think I've managed to establish that I *can* get it to work, but only if mt_srand is called within the same method as mt_rand.  If you call mt_srand externally (in my case, from within the unit test), it looks to be ignored.

Code is here: https://github.com/chrismou/phergie-irc-plugin-react-dice
Last travis build before I removed hhvm checks is here: https://travis-ci.org/chrismou/phergie-irc-plugin-react-dice/builds/48150199

Simplest way to see it fail is to grab the project using composer, then run vendor/bin/dunit from the project root, which should run the tests in docker using all 4 PHP versions (assuming you have docker installed).

If you want to compare the number output, the simplest way is just to var_dump the $response on about line 71, just before it's sent to the event queue and compare what's output on terminal.

If you add mt_srand(0); just before the mt_rand call on line 101, then do the above, they'll all come out the same (in my case, I'm seeing 3+3+3+3+3)

Let me know if you need any more info!

**Comment by fredemmott** [comment]
Added the tag as a trivial attempt to reproduce in a smaller codebase fails:

```PHP
<?php
function seed() {
  mt_srand(123);
}

function get() {
  var_dump(mt_rand());
}

seed();
get();
```

**Comment by paulbiss** [comment]
There are a few places we call mt_rand from within the runtime. In particular Vector::shuffle, and the first time spl_object_hash is called.

**Comment by chrismou** [comment]
Urgh, I just noticed my first link was to the wrong repo :-/  I've updated the ticket, sorry.

**Comment by Orvid** [comment]
This issue has been waiting for more info for more than 2 weeks. Closing for now, feel free to re-open it if you can provide more info.

https://github.com/facebook/hhvm/wiki/Human-Timeouts
