### ISSUE TITLE
Add option to /always/ log error messages

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#4713]
We've had a few issues along the lines of "HHVM silently fails", because of an error handler silencing everything.

One way to fix this would be to add an off-by-default option that *always* logs an error, even if there is an error handler installed. This should be the only difference - the error handler should still be called. For example, if it's a catchable fatal which the handler completely swallows up, it should be logged, but the page shouldn't fatal.

**Comment by corientdev** [comment]
+1

**Comment by SiebelsTim** [comment]
Similar: http://php.net/manual/en/book.scream.php

**Comment by kyleferguson** [comment]
+1

**Comment by paulbiss** [comment]
This feature request is not actively being worked on. We would happily consider a pull request implementing it. If you plan to work on this issue let us know in the comments and we will re-open the issue and assign it to you. If you feel strongly that this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
