### ISSUE TITLE
long2ip() gives incorrect results for octals IP strings

### ISSUE THREAD

**Issue by jazzdan** [facebook/hhvm#4715]
To reproduce: http://3v4l.org/a6cps

The php.net documentation states that long2ip() takes a strong as its argument http://php.net/manual/en/function.long2ip.php

In our testing other IP strings seem to work fine.

**Comment by jwatzman** [comment]
Thanks for the report and the repro case! We'll take a look when someone gets some time. (And of course, if you want to submit a PR to fix it yourself, that will get it fixed fastest :))

**Comment by jazzdan** [comment]
This repro is more informative: http://3v4l.org/OV7TX

It appears that if you call long2ip with a string hhvm will cast it to an int/float. This gives the output as 30000001353 instead of 3221226219 resulting in the weird IP. 

Changing the type of the param [here](https://github.com/facebook/hhvm/blob/master/hphp/runtime/ext/std/ext_std_network.php#L424) should do the trick. I'll give this a shot.

**Comment by jazzdan** [comment]
Additionally zend uses http://linux.die.net/man/3/strtoul to convert strings to a long. It respects the leading 0.

**Comment by jwatzman** [comment]
Something seems to have confused github's linking here; for the record, there's now a PR open at https://github.com/facebook/hhvm/pull/4716 -- thanks!

**Comment by MattEagle** [comment]
Since his code was against an older version of HHVM and wasn't passing the tests, I fixed the bug against the current version and I added a test case.

**Comment by jazzdan** [comment]
Thanks @MattEagle and @sherlockhua both for jumping on this before I could even power on my Ubuntu vm.  :horse_racing: :dash: :smiley:

**Comment by jazzdan** [comment]
This is fixed as of 3aca1cc410f8ab3cc0d7a5916d1273711d009038.
