### ISSUE TITLE
Thread Safety?

### ISSUE THREAD

**Issue by fossxplorer** [facebook/hhvm#4719]
Is HHVM thread safe?

**Comment by paulbiss** [comment]
I'm not sure I understand the question. Within a single request there is no concurrency (one request, one thread). Requests are isolated (have their own heaps, state, etc.) so in that respect it's thread safe.

**Comment by jazzdan** [comment]
With the possible exception of this caveat with `setlocale()` which, granted, exists in other sapi's as well.

https://github.com/facebook/hhvm/blob/master/hphp/doc/limitations

**Comment by SiebelsTim** [comment]
readline doesn't match php5 completely due to the thread vs mutliple process model.

**Comment by fredemmott** [comment]
Closing - nothing to do here afaict.
