### ISSUE TITLE
Support PHPRC (or a new HHVMRC) for defining path to default php.ini

### ISSUE THREAD

**Issue by chregu** [facebook/hhvm#4722]
In PHP I can set the env variable PHPRC to point to a php.ini, which gets automatically included. In HHVM I can't do that (or similar with eg. HHVMRC), the path to /etc/hhvm/php.ini is hardcoded

Would be great if that path could be overwritten with HHVMRC (I'd prefer that to PHPRC)

**Comment by jrobeson** [comment]
if somebody does start working on this, i'd like it if they used http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html and thus stored this file in $XDG_CONFIG_DIR/hhvm/hhvmrc with a default of .config/hhvm/hhvmrc/

**Comment by paulbiss** [comment]
This feature request is not actively being worked on. We would happily consider a pull request implementing it. If you plan to work on this issue let us know in the comments and we will re-open the issue and assign it to you. If you feel strongly that this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
