### ISSUE TITLE
Default memory_limit is a bit silly :)

### ISSUE THREAD

**Issue by dzuelke** [facebook/hhvm#4725]
```
$ hhvm --php -r 'var_dump(ini_get("memory_limit"));'
string(19) "9223372036854775807"
```

PHP's is currently at `128M`

**Comment by netroby** [comment]
I thought we have no enough memory to handle this. and if hhvm not working as behavior as php, this setting will be useless.

**Comment by paulbiss** [comment]
We already set this internally to something that makes sense for us, I'd be more than happy to take a PR for a more sensible default.

https://github.com/facebook/hhvm/blob/1b7c1eac1fa03ac8396deb6201e639b7ed7b0ede/hphp/runtime/base/runtime-option.cpp#L164-L165

**Comment by apeabody** [comment]
It appears this change happened in #4760, but the correct keywords to automatically close this ticket weren't included in the pull request, so unfortunately hhvm-bot didn't automatically close this ticket.
