### ISSUE TITLE
HHVM in Repo Authoritative Mode 

### ISSUE THREAD

**Issue by trivedipankaj** [facebook/hhvm#4726]
I am trying out HHVM on production and there is huge performance boost, however there are a couple of issues

a) We are trying to use hhvm.repo.authoritative=true but hhvm does not start with the following settings:
hhvm.repo.authoritative=true
hhvm.repo.local.path=/var/run/hhvm/local.hhvm.hhbc
hhvm.jit_a_hot_size=268435456

I suspect that a few configurations might be missing. The error log for hhvm does not say anything. 

b) HHVM crashes every 3-4 hours with stacktrace.<pid>.log file /tmp without much information to debug. We should be able to figure out what's wrong to able to fix it.

The HHVM version is as following:

HipHop VM 3.5.0-dev+2014.12.11 (rel)
Compiler: heads/master-0-g546087bf1b0560c4a9e254fcad46a9212e42ccc2
Repo schema: cf1780b3cc3857e091e924935ae6267e9794de9c
Extension API: 20140829

Please help.

**Comment by danslo** [comment]
You could start with providing the stacktrace.

**Comment by trivedipankaj** [comment]
As I told you, there is not enough information (at least that's what I thought) in the stacktrace log. 

ost: ip-172-31-7-232.compute.internal
ProcessID: 7766
ThreadID: 7f3e765ff700
ThreadPID: 9244
Name: /usr/bin/hhvm
Type: Segmentation fault
Runtime: hhvm
Version: heads/master-0-g546087bf1b0560c4a9e254fcad46a9212e42ccc2
DebuggerCount: 0

ThreadType: Web Request
Server_SERVER_NAME: www.example.com
Server: www.example.com
URL: /checkout/payment

**Comment by danslo** [comment]
Is that the entire file?

**Comment by trivedipankaj** [comment]
Yes. and it breaks every time with a similar file with different URLs.

**Comment by trivedipankaj** [comment]
server.ini



pid = /var/run/hhvm/pid

; hhvm specific
hhvm.server.file_socket=/var/run/hhvm/hhvm.sock
hhvm.server.type = fastcgi
hhvm.server.default_document = index.php
hhvm.log.use_log_file = true
hhvm.log.file = /var/log/hhvm/error.log
hhvm.repo.central.path =/var/run/hhvm/hhvm.hhbc
hhvm.server.thread_count=8

hhvm.jit =true
hhvm.jit_warmup_requests = 10
hhvm.jit_a_size = 536870912
hhvm.jit_a_cold_size = 268435456
hhvm.jit_a_frozen_size = 536870912
hhvm.jit_a_prof_size = 536870912
hhvm.jit_a_max_usage = 536870912

;hhvm.repo.authoritative=true
;hhvm.repo.local.path=/var/run/hhvm/local.hhvm.hhbc
;hhvm.jit_a_hot_size=268435456

hhvm.log.level = Warning
hhvm.log.no_silencer = true
hhvm.log.header = typed_results
hhvm.log.use_log_file = true
hhvm.log.use_syslog = false
hhvm.log.access.file = /var/log/hhvm-access.log
hhvm.log.access.format = "%u %t \"%r\" %>s %bbyte %Dms"
hhvm.log.always_log_unhandled_exceptions = true
hhvm.log.injected_stack_trace = true
hhvm.log.native_stack_trace = true
hhvm.log.runtime_error_reporting_level = 8191

;debug and error handling

hhvm.error_handling.call_user_handler_on_fatals = true
hhvm.error_handling.max_loop_count = 0
hhvm.error_handling.no_infinite_recursion_detection = false
hhvm.error_handling.throw_bad_type_exceptions = false
hhvm.error_handling.throw_too_many_arguments = false
hhvm.error_handling.warn_too_many_arguments = false
hhvm.error_handling.throw_missing_arguments = false
hhvm.error_handling.throw_invalid_arguments = false
hhvm.error_handling.enable_hip_hop_errors = true
hhvm.error_handling.notice_frequency = 1
hhvm.error_handling.warning_frequency = 1
hhvm.error_handling.assert_active = false
hhvm.error_handling.assert_warning = false

hhvm.debug.full_backtrace = true
hhvm.debug.server_stack_trace = true
hhvm.debug.server_error_message = true
hhvm.debug.translate_source = true
hhvm.debug.record_input = false
hhvm.debug.clear_input_on_success = true

**Comment by jwatzman** [comment]
> The HHVM version is as following:
> HipHop VM 3.5.0-dev+2014.12.11 (rel)

This is a month-old nightly build. Please upgrade to a release build (3.5.0 release is out), try again, and then answer the following questions.

- What OS are you using?
- For repo authoritative, "hhvm does not start with the following settings" [isn't super informative](https://www.facebook.com/notes/evan-priestley/please-please-please-include-error-text-when-reporting-that-you-received-an-erro/123321921752). [Did you follow all the directions to get a bytecode repo set up](https://github.com/facebook/hhvm/wiki/Performance-Tuning#use-repoauthoritative---20), and did they complete without error? You say nothing in the log, but is any error printed to the console? How do you know "it does not start" -- you tell HHVM to start up, and literally nothing happens?
- For the crash, can you install the `hhvm-dbg` package, attach to `hhvm` with `gdb`, and get backtraces with `thread apply all bt`? A core dump would be useful as well. If you don't know how to do what I just said, let us know and we can provide more explicit directions.

But please upgrade to a supported stable release first.

**Comment by trivedipankaj** [comment]
Thank you jwatzman for your response.

I am going to upgrade and try with the stable release. 

a) We are using CentOS 6.5
b) Setting up our code for repo, we need to run the command mentioned in the documentation for all our php files explicitly? if yes, it is not hard to write a script that does it. and yes we din't do that. 
c) We will install hhvm-dbg package to get the stacktrace. Please elaborate more on that if possible.

Thank you once again for very informative reponse. let me try all these and post the results here.

**Comment by trivedipankaj** [comment]
And for the hhvm starting thing. 
a) sudo service hhvm restart
Stopping hhvm .............[OK] 
Staring hhvm .................[OK]
b) sudo service hhvm status
hhvm has stopped.

No errors on the console or in the error logs.

**Comment by jwatzman** [comment]
> We are using CentOS 6.5

It's worth noting that CentOS isn't really supported. The crash you are reporting is quite likely to *not* be CentOS related, so I'd still like to get info on it, but it's worth noting you are in largely unmapped territory here :)

> Setting up our code for repo, we need to run the command mentioned in the documentation for all our php files explicitly? if yes, it is not hard to write a script that does it. and yes we din't do that. 

Yeah this explains why repo auth didn't work, you need to compile your code into bytecode beforehand. The page I linked explains how. Probably best to start with repo auth off, get everything working, and go from there.

> We will install hhvm-dbg package to get the stacktrace. Please elaborate more on that if possible.

Note that the debug version is considerably slower than the optimized version, but it gives much more informative crash logs.

To get a backtrace:

- Start up HHVM as usual, verify it's working, but don't do whatever it is that causes the crash.
- Run `pidof hhvm` to figure out what the PID of the HHVM process is.
- Run `sudo gdb $(which hhvm)` to start up gdb. You may need to explicitly pass a path to HHVM if it isn't on your `$PATH`, depends on how the CentOS packages install it.
- Tell gdb `attach pid`, where "pid" is the pid of HHVM from above.
- This will attach to the running HHVM and stop a random thread. Use the `c` command to resume execution.
- Let it run. AFAIK having gdb attached doesn't slow down HHVM any more beyond just using the debug build.
- When it crashes, GDB will automatically break back out to its command prompt. Run `thread apply all bt` to get full backtraces of every thread.
- Copy-paste the entire output of GDB (everything it produced, not just the results of the last step) and paste those into a gist or pastebin or something and link it here.

Information on what PHP code you're running, and what exactly triggers the crash (the best you can tell) is also useful.

**Comment by trivedipankaj** [comment]
Thank you Josh,

We are using CentOS (over Ubuntu) for a few good reasons that work well for us, and hence we want to try out on the same first, but if it takes to switch to Ubuntu to make HHVM work (stable), then that is not out of consideration. 

We are running Magento framework (and we have extended it quite a bit), but I am pretty much sure that there are no php incompatibilities so far as we have run the complete website for several hours on hhvm.

I will post the results here.

**Comment by trivedipankaj** [comment]
So, we decided to run our production servers on Ubuntu for the stability and further support, the hhvm does not crash anymore, but there is another troubling concern: All the transactions are almost 2 times slower than what we observed on CentOS with nightly version with the same configuration.

**Comment by jwatzman** [comment]
Glad you got it working. I'm actually surprised the debug build was only 2x slower, I would have expected it to be **much** slower than that :)

**Comment by trivedipankaj** [comment]
In fact, the release version on Ubuntu (the current set up) is at least 20% faster than dev nightly version we installed at CentOS. So, the debug version is probably a bit slower than what I thought earlier. We are now running our site 60-70% faster (compared to nginx+fpm set up) on at least half of the hardware with lesser CPU and memory consumption (out of the box). Awesome, isn't it?

I am looking forward to set it up in Repo Authoritative mode and see the performance factor.

**Comment by algrims** [comment]
Hello trivedipankaj,

Did you ever get it to work with Repo Authoritative mode enabled?
Once you complie it into hhbc what are the following steps to get it configured to use with a webserver?

Thanks.

**Comment by trivedipankaj** [comment]
Yes, I could make it work. After compiling it into hhbc, simply put hhvm.repo.authoritative=true in configuration and it should just work!

**Comment by algrims** [comment]
Thanks for your reply.  What I am struggling with is how to get it running.  My web server root is /wev/myapp where I have multiple php scripts such as index.php.
Any suggestions would be great.

1. I compile with    hhvm --hphp -t hhbc -vRepo.Central.Path="/web/myapp/hhvm.hhbc" -dhhvm.force_hh=true --input-dir /web/myapp

2. It generates hhvm.hhbc that I copy to /web/myapp and I delete the rest of the of my php scripts.

3. I got to my web page at /myapp to see my content

Unfortunately I see an error.  What am I missing.

**Comment by jwatzman** [comment]
Have you followed the directions [in our documentation](https://docs.hhvm.com/hhvm/advanced-usage/repo-authoritative)? There's a nice shell script to help you with it. If you can't use the script, there are manual directions too -- in particular, note the two INI options you have to set once you have finished building the repo and restart HHVM.

**Comment by algrims** [comment]
Yes thanks! I did take a look.  I am fine when it's one file index.php. But when I have another script test.php when I go to my web page it only executes index.php when try to run test.php.
in my url I enter http://host/web/test.php and it still runs index.php.

**Comment by algrims** [comment]
My server.ini settings are below. 
I must be missing something somewhere.  
I have 2 files in /web/test folder index.php and test.php.  
I compiled with hhvm --hphp -t hhbc hhbc -v AllVolatile=true  -dhhvm.force_hh=true --input-dir /web/test.
I then copy the hhvm.hhbc created in the /tmp/ folder to /var/run/hhvm/hhbc
I restart hhvm and it runs index.php when I run /test/test.php in the browser.

Any suggestions would be great.


; hhvm specific
hhvm.pid_file = "/var/log/hhvm/pid"
hhvm.server.port = 80
hhvm.server.type = proxygen
hhvm.server.default_document = index.php
hhvm.server.graceful_shutdown_wait = 5
hhvm.server.enable_keep_alive = true
hhvm.server.apc.enable_apc = true
hhvm.server.request_timeout_seconds = 120
hhvm.server.expose_hphp = false
hhvm.server.error_document404 = index.php
; default is the current directory where you launched the HHVM binary
hhvm.server.source_root=/web
hhvm.repo.authoritative=true
hhvm.log.level = Debug
hhvm.log.always_log_unhandled_exceptions = true
hhvm.log.runtime_error_reporting_level = 8191
hhvm.log.use_log_file = true
hhvm.log.use_syslog = false
hhvm.log.file = /tmp/error.log
hhvm.log.header = true
hhvm.log.native_stack_trace = true
hhvm.repo.central.path = /var/run/hhvm/hhvm.hhbc
hhvm.jit = false
;hhvm.jit_a_size = 100000000
;hhvm.jit_a_frozen_size = 100000000
;hhvm.jit_a_cold_size = 33000000
hhvm.mysql.socket = /var/lib/mysql/mysql.sock
hhvm.mysql.typed_results = false
hhvm.mysql.slow_query_threshold = 5000
;hhvm.eval.perf_pid_map = false
;hhvm.keep_perf_pid_map = 0
;hhvm.perf_pid_map = 0
;hhvm.perf_data_map = 0
[date]
date.timezone = Asia/Calcutta
default_socket_timeout = 120
memory_limit = 256M
