### ISSUE TITLE
Incompatibility with timezone_name_from_abbr()

### ISSUE THREAD

**Issue by soundslocke** [facebook/hhvm#4727]
According to the [documentation for `timezone_name_from_abbr()`](http://docs.hhvm.com/manual/en/function.timezone-name-from-abbr.php) the third parameter defaults to -1 but can be passed as 0 or 1.

When testing this function in HHVM 3.5.0 that doesn't appear to be the case.

In Zend PHP:
```php
var_dump(timezone_name_from_abbr('', -18000, 0)); // string(16) "America/New_York"
var_dump(timezone_name_from_abbr('', -18000, 1)); // string(15) "America/Chicago"
```

In HHVM:
```php
var_dump(timezone_name_from_abbr('', -18000, 0)); // string(16) "America/New_York"
var_dump(timezone_name_from_abbr('', -18000, 1)); // bool(false)
```

It seems that if you pass anything other than 0 as the third parameter it will always return false in HHVM.

**Comment by SiebelsTim** [comment]
Resolved in 48d1e887b5820b63
