### ISSUE TITLE
hh_client does not detect end of logical flow when exit() is inside an out of scope function

### ISSUE THREAD

**Issue by BobertForever** [facebook/hhvm#4729]
For the situation:

```hh
class Test {
    public static function getUser(): ?User {
        // return User or null
    }

    public static function useUser(User $user): void {
        // do something
    }

    public static function callExit(): void {
        exit();
    }
}

$user = Test::getUser();

if(!$user) {
    Test::callExit();
}

Test::useUser($user);
````

The call to useUser would throw an Invalid Argument warning by `hh_client`, mentioning that `useUser` is and it is incompatible with a nullable type.

By replacing the call to callExit with an `exit()` call, the error goes away.

This exact example does not cause the problem since Test is in scope but in a project I'm working on, I am seeing this behavior. The lines in question of my actual project can be seen here:
https://github.com/TexasLAN/Omega/blob/master/routes/SignupController.php#L65-L79

Running hh_client on this code base produces the following output:
```
/var/www/routes/SignupController.php:79:21,25: Invalid argument (Typing[4110])
  /var/www/lib/Session.php:17:33,36: This is an object of type User
  /var/www/lib/dao/User.php:24:6,10: It is incompatible with a nullable type
```

Replacing the call to `Route::redirect('/signup');` with
```
header('Location: /signup');
exit();
```
Makes the error go away.

**Comment by jwatzman** [comment]
Duplicate #2252
