### ISSUE TITLE
gentoo hhvm ebuild broken, outdated

### ISSUE THREAD

**Issue by lutel** [facebook/hhvm#4732]
>>> Installing (1 of 1) dev-php/hhvm-3.2.0::javer
 * This package will overwrite one or more files that may belong to other
 * packages (see list below). You can use a command such as `portageq
 * owners / <filename>` to identify the installed package that owns a
 * file. If portageq reports that only one package owns a file then do
 * NOT file a bug report. A bug report is only useful if it identifies at
 * least two or more packages that are known to install the same file(s).
 * If a collision occurs and you can not explain where the file came from
 * then you should simply ignore the collision since there is not enough
 * information to determine if a real problem exists. Please do NOT file
 * a bug report at http://bugs.gentoo.org unless you report exactly which
 * two packages install the same file(s). See
 * http://wiki.gentoo.org/wiki/Knowledge_Base:Blockers for tips on how to
 * solve the problem. And once again, please do NOT file a bug report
 * unless you have completely understood the above message.
 *
 * Detected file collision(s):
 *
 *      /usr/include/zip.h
 *      /usr/include/zipconf.h
 *      /usr/lib/libzip.so
 *
 * Searching all installed packages for file collisions...
 *
 * Press Ctrl-C to Stop
 *
 * dev-libs/libzip-0.11.2:0::gentoo
 *      /usr/include/zip.h
 *      /usr/include/zipconf.h
 *      /usr/lib/libzip.so
 *
 * Package 'dev-php/hhvm-3.2.0' NOT merged due to file collisions. If
 * necessary, refer to your elog messages for the whole content of the
 * above message.

**Comment by jwatzman** [comment]
This Gentoo package isn't maintained by the HHVM team. You should report issues at https://github.com/javer/gentoo-overlay. I'll update our Wiki page to make that clear.
