### ISSUE TITLE
XDebug: Documentation missing, how to setup?

### ISSUE THREAD

**Issue by EugenMayer** [facebook/hhvm#4733]
I got told that xdebug would work. So basically how would i configure it to include the xdebug extension?

old docs say, that it is enabled like this hhvm.xdebug-not-done.enable=1, but this seems to habe changed - though it is missing here: https://github.com/facebook/hhvm/wiki/INI-Settings

So were to put those configurations and were they are defined? server.ini / php.ini ..docs?

For now iam using

(root:testng)➜ cat /etc/hhvm/server.ini | grep xdebug
hhvm.xdebug.enable=1
hhvm.xdebug.remote_enable=1
hhvm.xdebug.remote_host="localhost"
hhvm.xdebug.remote_port=9000
using ssh local portforward for port 9000 as i usually do, but no connection happening. Anything else to fix? So iam not really remote debugging. Using xdebug-helper under chrome.

Thats what i usually do with a normal PHP-FPM setup, maybe you could help a bit getting this straight. ill then step through the code to see in which region or which method actually produces this special overflow.

I need this to further work on #4698

**Comment by paulbiss** [comment]
The settings shouldn't be prefixed with `hhvm.`.

**Comment by EugenMayer** [comment]
interesting, but still - nothing in the docs. Shouldnt we fix this - iam absolutely not the only one asking (according to google) and a solid answer is basically not give yet. Thank you for clarifying!

**Comment by paulbiss** [comment]
Re-opening for documentation problems. @EugenMayer, we'll close once the docs are up to date.

**Comment by paulbiss** [comment]
@EugenMayer, you're welcome to edit the INI settings page, it's a wiki.

**Comment by EugenMayer** [comment]
very happy with that, thank you!

**Comment by EugenMayer** [comment]
Ah, interesting - would do. I would, but iam not totaly sure what optionas are availble - every option available in the xdebug docs (php extension)?

**Comment by paulbiss** [comment]
Here are the ini settings we currently bind, I haven't checked to see if we actually support all of them though:

https://github.com/facebook/hhvm/blob/cbeea88ed6355a80fb6858d158552a62f97d4db2/hphp/runtime/ext/xdebug/ext_xdebug.h#L80-L156

**Comment by SiebelsTim** [comment]
> @EugenMayer, you're welcome to edit the INI settings page, it's a wiki.

Also feel free to send a PR to the docs repository. Merges are fast as lightning. (Or alternatively open a issue there containing information on where you think something is missing)
https://github.com/hhvm/hack-hhvm-docs

**Comment by EugenMayer** [comment]
well it does simply not work :)

this is the config

> (root:testng)➜  hhvm  cat /etc/hhvm/server.ini | grep xdebug
xdebug.enable=true
xdebug.remote_enable=true
xdebug.remote_host="localhost"
xdebug.remote_port=9000
xdebug.remote_autostart=true

this is how i connect to forward the port:
> ssh myhost -R 9000:localhost:9000

Using IntelliJ Ultimate to debug. 

Just in case, questions arrize: Iam doing this a lot with FPM, so there is no obvious reason or something. I know everything arround the IDE, remote debugging using ssh localport forwarding. Pretty sure this is an hhvm issue ;/

**Comment by jwatzman** [comment]
Did you try a port other than 9000? That's the default fastcgi port, and xdebug may be failing to allocate a port due to the conflict.

AFAIK putting it in `server.ini` should be fine.

**Comment by EugenMayer** [comment]
Well this was a very good call @jwatzman. I switched over to 9990 and this worked out. This means, xdebug will not work out of the box due to - thank you!

> FastCgiExternalServer /hhvm -host 127.0.0.1:9000 -pass-header Authorization -idle-timeout 300

I am not sure if this is somewere in the hhvm docs or tutorials, but since you even expected FastCGI to be on 9000, we should
 a) either change it (best option) so fastcgi is on something else
 b) or change the xdebug default port with a huge exclamation mark in the docs ( horrible idea)

For the docs, i would have for now
 - place to put those is server.ini
 - xdebug. no usual hhvm. (thats very bad though...)
 - care about the default xdebug port on FastCGI setup due to the conflict

**Comment by EugenMayer** [comment]
well, i rarely can use this xdebug connection. It seems to not be able to work in a solid way, basically connects one, but it cannot detect the code-base , then, it simply fails to connect. 

I tried to compile hhvm using homebrew on my mac, but this even fails... as known with http://goo.gl/zNoFaA .. it seems like everything i though is broken at some degree.

@jwatzman not really able to get xdebug to be of any use here - maybe when iam able to compile xdebug to be able to use it locally

**Comment by lhorace** [comment]
I am also looking into a good documentation regarding XDebug in HHVM. This bug has been open since January and yet there isn't any good documentation here https://github.com/facebook/hhvm/wiki/INI-Settings where as most of those settings are not well documented. http://doc.hhvm.com is great but neither the search function or trowling through the links document anything about XDebug. 

I assume the implementation here (barely understanding the source code) https://github.com/facebook/hhvm/blob/cbeea88ed6355a80fb6858d158552a62f97d4db2/hphp/runtime/ext/xdebug/ext_xdebug.h configurations options are documented here http://xdebug.com/docs/?

**Comment by jwatzman** [comment]
cc @JoelMarcey might be good to mention somewhere in the new docs site that we support XDebug and link to the relevant upstream docs.

**Comment by raeesiqbal** [comment]
bump....
