### ISSUE TITLE
Cannot use APC prime library documentation and sample code 

### ISSUE THREAD

**Issue by archibaldhaddock** [facebook/hhvm#4734]
Hello everybody !

I'm having a look at the HEAD branch (commit bf9ccffc9ce71b3ccf1a47e6387e2eef751117d) configurable features...

I can read from hphp/doc/options.compiled an easy way to create dynamic libraries to feed apc at startup time. But...
=> the sample php script apc_sample_serializer.php uses a class (CacheArchiveSerializer) that is  defined nowhere in hhvm.git
=> if we delete "extends CacheArchiveSerializer", we actually obtain a cpp source file...That includes a file (apc_prime.h) that cannot be found either in the git repo...
=> How the CompletionKeys parameter has to be used (hphp/doc/options.compiled is not very clear about it ) ? 

Maybe this functionnality has been deprecated ?

**Comment by paulbiss** [comment]
APC priming is something we use internally, it's not so much deprecated as the machinery we use to create apc_prime.so was never part of the repo. We should definitely update the documentation, and potentially add a generic sample implementation.

**Comment by archibaldhaddock** [comment]
Ok. 
thank you for your quick answer !

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

APC prime has been [removed](https://github.com/facebook/hhvm/commit/13de0f440a23035e3379249623c525442a6322ce) from hhvm
