### ISSUE TITLE
Multiple paths in open_basedir

### ISSUE THREAD

**Issue by amq** [facebook/hhvm#4735]
HHVM doesn't parse something like this correctly:

```
open_basedir=/var/www/site:/usr/share/php
```

While it is completely legitimate in regular php.ini.

Result with HHVM 3.5.0:

```
File could not be loaded: ../var/www/site/index.php
```

**Comment by jwatzman** [comment]
Thanks for the report! Someone will take a look when we get a chance.

**Comment by thuantran** [comment]
I also have this issue on version 3.6. Hopefully this is fixed soon.

**Comment by worldowner** [comment]
Same issue on 3.6.1.

**Comment by MarkGavalda** [comment]
@jwatzman could you please let us know if someone's working on this? Thanks!

**Comment by paulbiss** [comment]
@MarkGavalda I don't think anyone has had a chance to look at it yet

**Comment by Profforgr** [comment]
Too bad, that so less attention to this important issue. Because of it, security with HHVM is something impossible.

**Comment by thuantran** [comment]
You can use uwsgi external daemon and namespace unshare/pivot root features to handle jailing hhvm process.

In any case, if hhvm wants to be a compatible implementation of php then things like this should work.

**Comment by Profforgr** [comment]
> You can use uwsgi external daemon and namespace unshare/pivot root features to handle jailing hhvm process.

Thanks for the idea, but chroot is another question, it is completely different story. open_basedir is rather easy solution for security with 100% compability with scripts.

> In any case, if hhvm wants to be a compatible implementation of php then things like this should work.

I think open_basedir is rather easy to implement and it's strange, that it's not fully supported. There are talks about frameworks, CMS compability, but so basic important features is not implemented correctly.

**Comment by Profforgr** [comment]
test.php:
```php
<?php
// /home/test1.txt should exists and have "test1.txt data" contents   echo "test1.txt data" > /home/test1.txt
// /tmp/aasdfasdf/test2.txt should exists and have "test2.txt data" contents  mkdir /tmp/aasdfasdf && echo "test2.txt data" > /tmp/aasdfasdf/test2.txt
// /tmp/test3.txt should exists and have "test3.txt data" contents  echo "test3.txt data" > /tmp/test3.txt

// delimiter :
var_dump(ini_set('open_basedir','/home:/tmp:/invalid_root_dir_asdfasdf/dfg:dfg:')); // expected string(0) ""
var_dump(ini_get('open_basedir')); // expected string(46) "/home:/tmp:/invalid_root_dir_asdfasdf/dfg:dfg:"
print file_get_contents('/home/test1.txt'); // expected test1.txt data

// Can add since we have /tmp in above open_basedir set
var_dump(ini_set('open_basedir', '/tmp/aasdfasdf:')); // expected string(46) "/home:/tmp:/invalid_root_dir_asdfasdf/dfg:dfg:"
var_dump(ini_get('open_basedir')); // expected string(15) "/tmp/aasdfasdf:"
// We still can access /tmp/aasdfasdf
print file_get_contents('/tmp/aasdfasdf/test2.txt'); // expected test2.txt data
// We can not access /tmp anymore
var_dump(file_get_contents('/tmp/test3.txt')); // expected bool(false)

// Can't add /nonexistent since we not added /nonexistent to the above open_basedir set
var_dump(ini_set('open_basedir', '/nonexistent:')); // expected bool(false)
var_dump(ini_get('open_basedir')); // expected string(15) "/tmp/aasdfasdf:"
```

Expected:

```text
string(0) ""
string(46) "/home:/tmp:/invalid_root_dir_asdfasdf/dfg:dfg:"
test1.txt data
string(46) "/home:/tmp:/invalid_root_dir_asdfasdf/dfg:dfg:"
string(15) "/tmp/aasdfasdf:"
test2.txt data
bool(false)
bool(false)
string(15) "/tmp/aasdfasdf:"
```

Results:

```bash
# php test.php
string(0) ""
string(46) "/home:/tmp:/invalid_root_dir_asdfasdf/dfg:dfg:"
test1.txt data
string(46) "/home:/tmp:/invalid_root_dir_asdfasdf/dfg:dfg:"
string(15) "/tmp/aasdfasdf:"
test2.txt data
bool(false)
bool(false)
string(15) "/tmp/aasdfasdf:"
# hhvm test.php
string(0) ""
string(46) "/home:/tmp:/invalid_root_dir_asdfasdf/dfg:dfg:"
bool(false)
string(46) "/home:/tmp:/invalid_root_dir_asdfasdf/dfg:dfg:"
bool(false)
bool(false)
string(46) "/home:/tmp:/invalid_root_dir_asdfasdf/dfg:dfg:"
```

As you can see it is not working. You can't read from the directories you specify with delimiter ":".

**Comment by fredemmott** [comment]
@Profforgr mentioned 39ca421 in #1735 - based on both the code and tests there, and https://github.com/facebook/hhvm/blob/master/hphp/runtime/base/request-injection-data.cpp#L254-303 - it appears that HHVM only supports semicolons; can you confirm if replacing ':' with ';' works for you?

If so, can you confirm that ':' works for PHP and this isn't just a typo? If so, this issue should stay open to extend HHVM to support either character.

**Comment by J0WI** [comment]
replacing ':' with ';' results in ```RequestInitDocument Not Found``` for me.
':' works fine in PHP 5.5.

**Comment by AdeFlit** [comment]
You can use this instead:

```
hhvm.server.safe_file_access = true
hhvm.server.allowed_directories[] = /dir1
hhvm.server.allowed_directories[] = /dir2
```

**Comment by fredemmott** [comment]
cc @JoelMarcey

**Comment by amq** [comment]
@AdeFlit thanks, that's helpful.

I wish we could also solve a related issue:
https://github.com/facebook/hhvm/issues/3730

**Comment by JoelMarcey** [comment]
There is now an internal diff out to hopefully fix this problem.

**Comment by J0WI** [comment]
Thanks!
