### ISSUE TITLE
Couchbase Extension in HHVM

### ISSUE THREAD

**Issue by saverio** [facebook/hhvm#4737]
Is there any plan to get Couchbase (https://github.com/couchbase/php-ext-couchbase) working with HHVM? I haven't seen anyone mention this and I'm curious if there's any demand for it, but we lean on Couchbase pretty heavily and it's the one thing holding us back from taking HHVM into production.  Figured I'd drop a line here to see if anyone has had any success before digging deeper.

**Comment by paulbiss** [comment]
We have a great extension layer and a number of third-party extensions already exist for hhvm, if you have the time an inclination you could consider attempting a port. As things stand it's unlikely that anyone on our side will have time to pick this up anytime soon, but you have it on our radar now. Thanks!

**Comment by MarkehMe** [comment]
@trondn @janl and @mnunberg appear to be the biggest contributors to the php extension, maybe they would be interested in helping?

**Comment by mnunberg** [comment]
https://github.com/couchbase/php-ext-couchbase is no longer actively maintained (it's in maintenance mode only). The new extension is maintained under a different name as https://github.com/couchbaselabs/php-couchbase and Brett Lawson (@brett19) is the current maintainer. I'd suggest initially trying to port, and bug us in #libcouchbase (on freenode) if you run into issues, or send one of us (brett or me) an email.

**Comment by paulbiss** [comment]
This feature request is not actively being worked on. We would happily consider a pull request implementing it. If you plan to work on this issue let us know in the comments and we will re-open the issue and assign it to you. If you feel strongly that this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
