### ISSUE TITLE
Type checker should consider 'string' attributes in XHP to be strings, not Stringish

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#4738]
Related: https://github.com/facebook/xhp-lib/issues/96

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This issue has been addressed in xhp-lib version [3.0.0](https://github.com/hhvm/xhp-lib/releases/tag/v3.0.0).
