### ISSUE TITLE
Feature request: PDO execute() to support named-parameter arrays

### ISSUE THREAD

**Issue by hopeseekr** [facebook/hhvm#4740]
I would like to be able to do this:

    $fooIds = [1, 2, 3];
    $sql = 'SELECT * FROM Foo WHERE id IN (:fooIds)';
    $stmt = $pdo->prepare($sql);
    $stmt->execute(['fooIds' => $fooIds]);

Currently, I have to do this:

    $fooIds = [1, 2, 3];
    $qMarks = str_repeat('?,', count($fooIds) - 1) . '?';
    $sql = 'SELECT * FROM Foo WHERE id IN ($qMarks)';
    $stmt = $pdo->prepare($sql);
    $stmt->execute($fooIds);

This feature has been missing from PHP for 10 1/2 years and the feature request has been marked as WONT_ADD forever. The plus is that this request is logically consistent, more secure, and backwards compatible, since WHERE INs never worked with PDO named parameters.

I understand your concerns about PHP equality, so including this feature ONLY in HackLang would also be a win in my book.

**Comment by reeze** [comment]
Maybe you raise you voice on php-internals mailing list (There are a lot of features be turned down are now been accepted). Maybe a new api or just make it work as you wish.  
This is not a language feature but api improvement, I don't think this should be a feature of HHVM :)

**Comment by jwatzman** [comment]
Yeah, we'll keep stuff like this in mind if Hack ever dramatically modifies the standard library, but there are no immediate plans to do so, and PDO would be a ways down the list if we ever did get around to that.
