### ISSUE TITLE
Add support for making the typechecker ignore subdirectories

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#4743]
I'm adding some tests to the hack branch of XHP, and want to check that the typechecker raises specific errors - so the project as a whole won't typecheck. For now, I'm going to make the files '.hh.test' or similar to work around this.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

The `.hhconfig` file supports the `ignored_paths` key, which allows you to ignore subdirectories.

Example usage (from type-assert) `ignored_paths = [ "vendor/.+/tests/.+", "vendor/hhvm/hhast/.+" ]`.
