### ISSUE TITLE
Xenon breaks sleep()

### ISSUE THREAD

**Issue by Norbyte** [facebook/hhvm#4744]
It seems that Xenon sampling interrupts system calls on the thread it is sampling in run mode, which breaks sleep(), usleep() and possibly lots of other functionality.

**How to reproduce:**
Add this to your .ini file:

``` ini
hhvm.xenon.period = 1
```

Sleep code:

``` php
<?php
sleep(10);
```

`hhvm --config test.ini sleep.php`

HHVM will sleep for ~1 seconds when Xenon is enabled, and will sleep 10 secs if it is disabled.

**Version:**
HipHop VM 3.5.1-dev (rel)
Compiler: heads/HHVM-3.5-0-g38307a5527296bb724606ea43dd8b611d9aff87e
Repo schema: ee0aa41edd9c6e09b913d8898015219fa62850fb

**Comment by paulbiss** [comment]
Looks like we make a bare call to sleep and don't bother to check if we were interrupted:

https://github.com/facebook/hhvm/blob/9778521aa100ae460831d395521bbcf68cb27580/hphp/runtime/ext/std/ext_std_misc.cpp#L300

**Comment by Norbyte** [comment]
Well `sleep()` was just an example, the syscall interrupt behavior can break many other things.
(Note that this only occurs in --mode run, --mode server/daemon is fine.)
Some errors that we only encountered after enabling hhvm.xenon.period:

**Redis breakage:**
```
Fatal error: Uncaught exception 'ErrorException' with message 'unable to connect to XX.XX.20.50
[4]: Interrupted system call' in :0
```

**cURL connections breaking:**
```
Exception of type SoapFault: SOAP_ERROR: Parsing WSDL: Couldn't load from 'https://adwords.google.com/api/adwords/ch/v201409/CustomerSyncService?wsdl'
Exception of type SoapFault: Failed Sending HTTP Soap request
```

**Database connections lost:**
```
Exception of type PDOException: [0]: server closed the connection unexpectedly
This probably means the server terminated abnormally
before or while processing the request.
```

**Comment by enjmusic** [comment]
@fredemmott This should be closed by https://github.com/facebook/hhvm/commit/c7622408c8b3a6f861ae9292433623163966cd21
