### ISSUE TITLE
Typecheck abstract functions in XHP classes

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#4745]
This passes the typechecker:

```PHP
<?hh // strict

class :Foo {
  abstract public function derp(): void;
}

class :Bar extends :Foo { }
```

**Comment by fredemmott** [comment]
Heh, actually, it should complain about two things:

- :Foo contains an abstract function, but is not an abstract class
- :Bar does not define derp()

**Comment by jwatzman** [comment]
You chatted in person with @elgenie about this, but for posterity, the problem is that we force the typechecker to treat all XHP classes as if they had an unknown PHP superclass, due to legacy FB-specific reasons. Adding an option for this might be reasonable?

**Comment by fredemmott** [comment]
Yep :) my preference would be strict-by-default, with FB switching it off - xhp 1.x actually is all PHP superclasses, and 2.x is a BC break.

**Comment by fredemmott** [comment]
Will try just making the existing constant a flag - if that's sufficient, I'll put a diff up for HHVM and WWW.

**Comment by fredemmott** [comment]
https://github.com/facebook/hhvm/commit/45811e5217a92c505867015901de253c493feeb8
