### ISSUE TITLE
Hack Type Checking

### ISSUE THREAD

**Issue by aftabnaveed** [facebook/hhvm#4750]
I am trying to declare a a variable of type "resource" (//strict mode) inside a function (local scope)  type hint seems  to not like that,    here is the code snippet followed by Ubound name error

<code>
    public function accept() : SmtpSocket {  

        resource $remote;
        $remote = socket_accept($this->_socket);
        if(socket_getpeername($remote, $this->_remoteAddress)) {
            print "Could not determine remote address...";
        }

        print "Accepted connection from " . $this->_remoteAddress;

        return new SmtpSocket($remote);

    }
</code>

and Error

SmtpSocket.hh", line 51, characters 9-16: Unbound name: resource (Naming[2049])

**Comment by aftabnaveed** [comment]
I think to have figured it out, but just wanted to confirm if I might have missed some thing here,  we don't need to declare a variable in local scope, but if that is the case then I might assign any thing to it which probably is a bit confusing

**Comment by WizKid** [comment]
Correct. You can not type local variables. They will be inferred.

**Comment by aftabnaveed** [comment]
is that something intentional, and isn't it confusing, in other type checked languages even local variables has to be annotated,  forgive me if  my knowledge is outdated.

**Comment by WizKid** [comment]
Yes it is intentional

**Comment by JoelMarcey** [comment]
Just to give you a little more perspective ... as you know PHP was designed to be dynamically typed language. With Hack, we wanted to introduce explicit typing to the language, but only in the places where it was necessary to help the major Hack goals of reducing runtime errors and better API design and readability. And this was on the "boundaries". By boundaries I mean places where a piece of code could be affected by an outside piece of code. This is the parameters, returns, class properties, etc.

And given that code within a boundary (e.g., locals in a function) are readily inferred by the Hack type checker, we felt that adding even further static typing to a language that had never seen static typing before was unnecessary.

cc: @jwatzman

**Comment by aftabnaveed** [comment]
cool I think that makes sense,  thanks for explaining it.

**Comment by jwatzman** [comment]
Yep, @JoelMarcey that's right, with one addendum: we've definitely considered adding declared variables like described here, they could definitely be useful. They're just not hi-pri though.
