### ISSUE TITLE
Declare Member Constants

### ISSUE THREAD

**Issue by aftabnaveed** [facebook/hhvm#4751]
how do I declare member constants in hack ?  

protected final string SMTP_LOG = 'smtp.log';
protected const string SMTP_LOG = 'smtp.log';

Both of the above statements won't work.

**Comment by jwatzman** [comment]
- What do you mean, they "don't work"? [What error message did you get? What happened when you tried it?](https://secure.phabricator.com/book/phabflavor/article/please_please_please/)
- Type annotations on members definitely work; [our documentation has many examples in the section on type annotations](http://docs.hhvm.com/manual/en/hack.annotations.introexample.php).

**Comment by aftabnaveed** [comment]
They definitely do, sorry if I was kind of too harsh on this,  I was wondering how can i type annotate constant members, 

<code>
<?hh //strict
class Test {

    private const int $SMTP_LOG = 'smtp.log';
    public function a(int $b) : int {
        return 1;
    }   
}
</code>

That would throw this error

<code>
  1 test.hh|3 col 7 error|  The class member _ is not always properly initialized                                                                                                              
  2 || Make sure you systematically set $this->_ when the method __construct is called
  3 || Alternatively, you can define the type as optional (?...)
  4 ||  (NastCheck[3015])
  5 ||
  6 test.hh|5 col 13 error|  Unbound name: const (Naming[2049])
  7 ||
  8 test.hh|5 col 19 error|  Expected variable (Parsing[1002])

</code>

**Comment by jwatzman** [comment]
Something is still up with your code vs error messages -- the line numbers you provided don't line up, assuming I'm counting correctly. In any event, you probably meant either

```php
<?hh // strict

class Test {
  const string SMTP_LOG = 'smtp.log';
  public function a(int $b) : int {
      return 1;
  }   
}
```

or perhaps

```php
<?hh // strict

class Test {
  private string $SMTP_LOG = 'smtp.log';
  public function a(int $b) : int {
      return 1;
  }   
}
```

depending if you wanted `SMTP_LOG` to be mutable or not.

**Comment by aftabnaveed** [comment]
sorry I took that snipped from my SmtpServer class, but modified it for simplicity, it is indeed string,  this works for me,  I was always under this impression that syntax and type annotation checker was file based but it check the whole directory,  this issue is not fixed. 

Thank you
