### ISSUE TITLE
Redis SCAN not implemented

### ISSUE THREAD

**Issue by JohanTan** [facebook/hhvm#4755]
Redis library seems to have not implemented SCAN commanded which comes with Redis 2.8 release. I am referring to https://github.com/facebook/hhvm/blob/master/hphp/system/php/redis/Redis.php. Is there plans on adding this in?

**Comment by paulbiss** [comment]
I don't think anyone is actively working on redis on our end. We would happily take a pull request to add this functionality.

**Comment by SiebelsTim** [comment]
There are probably a bunch of other functions that are relatively easy to implement.

(#4764 for example)

**Comment by noony** [comment]
Can be closed. https://github.com/facebook/hhvm/commit/29713843c04f2ed4a5ae6b03b059263c9c0a8789
