### ISSUE TITLE
PHP incompatibility on ternary $foo = isset($foo) ? $foo : $bar->buh

### ISSUE THREAD

**Issue by uwetews** [facebook/hhvm#4756]

**Comment by uwetews** [comment]
if $foo is set PHP returns $foo even when $bar is not an object. HHVM returns an error of accessing a property on a none object.

**Comment by paulbiss** [comment]
I can't repro this: http://3v4l.org/gXfO8

**Comment by uwetews** [comment]
I found this problem with some complex PHPunit test. I will try to reproduce it in some simpler test case and let you know.

**Comment by uwetews** [comment]
Sorry, the error was in the PHPUnit test.
