### ISSUE TITLE
.deb package sets session.save_path to non-existent directory

### ISSUE THREAD

**Issue by tstarling** [facebook/hhvm#4757]
The HHVM package from http://dl.hhvm.com/ubuntu installs a /etc/hhvm/php.ini with session.save_path=/var/lib/php5 , but this directory is not created by the package. The directory is created by the php5-common package with mode 01733 but if php5-common is not installed then the directory does not exist.

**Comment by Majkl578** [comment]
This belongs to [hhvm/packaging](https://github.com/hhvm/packaging/issues/new).

**Comment by tstarling** [comment]
https://github.com/hhvm/packaging/issues/101
