### ISSUE TITLE
hhvm --mode server start motionless

### ISSUE THREAD

**Issue by lj2007331** [facebook/hhvm#4762]
<pre># hhvm --version
HipHop VM 3.5.0-dev+2014.12.11 (rel)
Compiler: heads/master-0-g546087bf1b0560c4a9e254fcad46a9212e42ccc2
Repo schema: cf1780b3cc3857e091e924935ae6267e9794de9c
Extension API: 20140829</pre>

<pre># /usr/bin/hhvm --mode daemon --user www --config /etc/hhvm/server.ini \
--config /etc/hhvm/php.ini --config /etc/hhvm/config.hdf  # OK

# /usr/bin/hhvm --mode server --user www --config /etc/hhvm/server.ini \
--config /etc/hhvm/php.ini --config /etc/hhvm/config.hdf # motionless , why ??</pre>

<pre>[root@linuxeye hhvm]# ls -ld  /var/run/hhvm
drwxr-xr-x 2 www www 4096 Feb  3 12:15 /var/run/hhvm
[root@linuxeye hhvm]# ls -ld /var/log/hhvm
drwxrwxr-x 2 www www 4096 Feb  3 12:04 /var/log/hhvm</pre>
<pre>[root@linuxeye hhvm]# cat /etc/hhvm/php.ini
hhvm.mysql.socket = /tmp/mysql.sock
expose_php = 0
memory_limit = 400000000
post_max_size = 50000000</pre>
<pre>[root@linuxeye hhvm]# cat server.ini
; php options
pid = /var/run/hhvm/pid
; hhvm specific
;hhvm.server.port = 9000
hhvm.server.type = fastcgi
hhvm.server.file_socket = /var/run/hhvm/sock
hhvm.server.default_document = index.php
hhvm.log.use_log_file = true
hhvm.log.file = /var/log/hhvm/error.log
hhvm.repo.central.path = /var/run/hhvm/hhvm.hhbc</pre>
<pre>[root@linuxeye hhvm]# cat /etc/hhvm/config.hdf
ResourceLimit {
CoreFileSize = 0 # in bytes
MaxSocket = 10000 # must be not 0, otherwise HHVM will not start
SocketDefaultTimeout = 5 # in seconds
MaxRSS = 0
MaxRSSPollingCycle = 0 # in seconds, how often to check max memory
DropCacheCycle = 0 # in seconds, how often to drop disk cache
}
Log {
Level = Info
AlwaysLogUnhandledExceptions = true
RuntimeErrorReportingLevel = 8191
UseLogFile = true
UseSyslog = false
File = /var/log/hhvm/error.log
Access {
* {
File = /var/log/hhvm/access.log
Format = %h %l %u % t \"%r\" %>s %b
}
}
}
MySQL {
ReadOnly = false
ConnectTimeout = 1000 # in ms
ReadTimeout = 1000 # in ms
SlowQueryThreshold = 1000 # in ms, log slow queries as errors
KillOnTimeout = false
}
Mail {
SendmailPath = /usr/sbin/sendmail -t -i
ForceExtraParameters =
}</pre>

**Comment by fredemmott** [comment]
What do you mean by motionless? What would you expect to happen?

**Comment by lj2007331** [comment]
According to the above configuration, service HHVM start
Can't start, stuck

**Comment by fredemmott** [comment]
--mode server is meant to stay in the foreground - I'm not sure if that's what you mean?

**Comment by fredemmott** [comment]
Closing - appears to be a misunderstanding between --mode daemon and --mode server
