### ISSUE TITLE
redis bug occurrence of high concurrency;native PHP no this bug

### ISSUE THREAD

**Issue by bbs3723216** [facebook/hhvm#4763]
Fatal error: Uncaught exception 'RedisException' with Message 'protocol error, got 'o' as reply type

**Comment by fredemmott** [comment]
Could you provide some isolated example code that demonstrates the problem?

**Comment by simonwelsh** [comment]
Also, we see this a lot with PHP 5.5 when running multiple PHP resque workers. Isn't specific to HHVM.

**Comment by fredemmott** [comment]
Without an isolated repro, and with it being potentially an issue with redis itself, there's nothing we can do here.
