### ISSUE TITLE
AsyncServerSocket.cpp:702] accept failed: out of file descriptors; entering accept back-off state

### ISSUE THREAD

**Issue by joacub** [facebook/hhvm#4765]
] error accepting on acceptor socket: accept() failed
 hhvm[2905]: \nFatal error: Class undefined: Doctrine\\DBAL\\Driver\\PDOException in /var/www/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php on line 47

**Comment by Orvid** [comment]
Is this still occurring?

Also need a proper stack trace for this.

**Comment by paulbiss** [comment]
This issue has been waiting for more info for more than 2 weeks. I'm closing it for now, but feel free to re-open it if you can provide more info. https://github.com/facebook/hhvm/wiki/Human-Timeouts
