### ISSUE TITLE
json_encode fails differently on invalid UTF-8 strings in arrays

### ISSUE THREAD

**Issue by jmarrama** [facebook/hhvm#4774]
```php
<?php
$s = hex2bin("88");
$a = ['foo' => 'bar', 'special' => $s];
var_dump(json_encode($a));
/**
 * HHVM outputs: bool(false)
 * PHP outputs:  string(28) "{"foo":"bar","special":null}"
*/
```

**Comment by jmarrama** [comment]
This discrepancy in behavior exists on both 3.3.1 and HEAD

**Comment by plstand** [comment]
This was actually a change introduced in PHP 5.5 (php/php-src@84fe2cc890e49f40bac7c3ba74b3cfc6dc4cef2f, php/php-src@4662151ea7d7b6920d115cf2a2d6e9d4232727a3, php/php-src@974324676b2436f159f42d9241c569f813471684). To restore the old behavior (except for the formerly generated warnings), specify the JSON_PARTIAL_OUTPUT_ON_ERROR option.

**Comment by jmarrama** [comment]
Ah, great to know! Thanks for your investigation on this, closing this issue.
