### ISSUE TITLE
Session handler redis issue in HHVM 3.5.0 (rel)

### ISSUE THREAD

**Issue by pandian05** [facebook/hhvm#4778]
I am testing my existing application with HHVM and it is working fine but i got some error on Session section. Here i have attached Session error

Session callback expects true/false return value (/var/www/yii/framework/web/CHttpSession.php:181)
Versions: HHVM - 3.5.0 (rel) Yii - 1.1.14

And i am using redis to store the session. Can you anybody suggest me how to fix this issue?

Thank you...

**Comment by paulbiss** [comment]
I believe this is related to #3055. The fix is to have the handler return a sensible value, e.g. true or false.

**Comment by paulbiss** [comment]
The change in c844c035f3acd8b2a3a2c43c9a1cb7a1b1e2f26a added looser handling for this but probably not as loose as is required here. It was the compromise we were prepared to make so I'm going to close this. If anyone has strong feelings please comment.
