### ISSUE TITLE
HHVM does not build in PowerPC64

### ISSUE THREAD

**Issue by gustavotemple** [facebook/hhvm#4780]
This issue will be use to keep track of PowerPC64 related pull requests / issues in the HHVM

**Comment by fredemmott** [comment]
We'll be happy to review pull requests (and merge them if they're clean), but this platform isn't popular enough for us to work on this. For now, our priorities are OSX and Windows on x86_64, and Linux on ARM.

**Comment by edwinsmith** [comment]
What OS would this be?

**Comment by gustavotemple** [comment]
Thank you @fredemmott !

@edwinsmith, there are: Debian [1], Fedora [2], Ubuntu [3], Suse [4], RHEL.

Because the consortium [5], there are more softwares coming soon [6].

[1] https://wiki.debian.org/ppc64el
[2] http://fedoraproject.org/wiki/Architectures/PowerPC
[3] https://wiki.ubuntu.com/PowerPCFAQ
[4] https://en.opensuse.org/Portal:PowerPC
[5] http://openpowerfoundation.org
[6] http://www.ovirt.org/OVirt_3.4_Release_Notes#Preview:_PPC64

**Comment by edwinsmith** [comment]
Ok, cool; so I would expect platform incompatibilities to be small.
I expect the first round of issues are going to be related to big-endian.
Beyond that, random bits of inline asm will need porting or workarounds; at that point, getting the interpreter working should be feasible.

From there, work can start on the JIT. We also have the beginnings of ARM-64, but be careful (ask here) before using it as an example of adding a different arch; We're partway through eliminating code-gen-arm.cpp in an effort to reduce the amount of arch-specific code necessary for the JIT. I can go into more detail if you like; I'm not sure how familiar you are yet with HHVM's jit codebase.

**Comment by gustavotemple** [comment]
@edwinsmith, would be something related to the vixl or the llvm?

**Comment by edwinsmith** [comment]
hhbc = hip hop bytecode
vixl = arm64 simulator
vasm = "virtual" asm, the name of our low level intermediate format
hhir = hip hop IR, our high level intermediate format
llvm = llvm.org

our current backend works by converting hhir to arch-neutral vasm, then lowering to either llvm, or arch-specific vasm-arm64 or vasm-x64. Then finally to native code. Adding PPC64 will require adding vasm-ppc64 instructions (probably not very many, we only need 10 or so when adding arm), and fleshing out arch-specific passes (like vasm-fold-imms.cpp).  Obviously with LLVM, code generation for ppc should be mostly automatic, however the LLVM backend isn't production ready yet, and when it is, we expect to have to do a lot of tuning to handle it's much slower compile speed.

**Comment by gustavotemple** [comment]
@edwinsmith, wow! Thank you very much for the explanation and tips!

**Comment by gustavotemple** [comment]
https://github.com/facebook/folly/pull/127

**Comment by gustavotemple** [comment]
https://github.com/facebook/hhvm/pull/4825

**Comment by gustavotemple** [comment]
https://github.com/facebook/hhvm/pull/4847

**Comment by gustavotemple** [comment]
@fredemmott, @edwinsmith, @paulbiss: last year I sent to Zend four PRs [1][2][3][4] about overflow checking in some operations (e.g. inc, dec, add, sub) and we, my teammates and I, think this is a interesting improvement for the HHVM, since we are working for ppc64 support. Is the correct workflow of the Zend source a general upgrade or I should send a PR with these changes? 

[1] https://github.com/php/php-src/pull/919
[2] https://github.com/php/php-src/pull/920
[3] https://github.com/php/php-src/pull/921
[4] https://github.com/php/php-src/pull/922

**Comment by paulbiss** [comment]
@gustavotemple: For [1] we don't appear to do any sort of overflow checking in our version of safe_address, so that might not be a bad idea. If you plan to just add overflow checking for PPC I can't imagine it would be an issue, if you want to add it for intel as well the function is pretty hot so it would have to be done carefully.

For [2]-[4], we don't actually have fast architecture specific versions of these functions as we rely on the JIT to generate and inline architecture specific versions. If you plan to get the JIT working you'll likely end up incorporating these routines in the code-gen phase.

**Comment by edwinsmith** [comment]
Yes, lets keep the interpreter arch-neutral, it's not hot enough to matter. Once you start adding JIT support, take a look at CodeGenerator::cgAddIntO (and SubIntO, MulIntO) to see how it's done. VASM is our low-level intermediate format; it has an X64 flavor to it, but it shouldn't be hard to translate addq{} + jcc{CC_O} into the appropriate powerpc instructions. Note that VASM treats condition codes as a pseudo-register; I'm aware that PPC has 8 actual sets of flags. I doubt that it's very important to use all 8, but it's theoretically possible, and just doing 1 should be easy.

**Comment by gustavotemple** [comment]
Thank you for the explanation, guys!

**Comment by gustavotemple** [comment]
https://github.com/facebook/hhvm/pull/4941

**Comment by leitao** [comment]
What is the final decision about this pull request?

**Comment by paulbiss** [comment]
Going to close this tracking task, the ppc port has made substantial progress since this was opened.
