### ISSUE TITLE
"Need to call next() first" exception when calling current() to get Generator value

### ISSUE THREAD

**Issue by theodorejb** [facebook/hhvm#4781]
When I call the `current` method of a new Generator to get its first value, HHVM throws a "Need to call next() first" exception (from [line 80](https://github.com/facebook/hhvm/blob/35383658c272c70b4308a95ab0c54258549d027e/hphp/runtime/ext/ext_generator.h#L80) of ext_generator.h).

However, if I call `next` first to fix the error, I have a compatibility problem with PHP, which returns the second generator value rather than the first. Compare http://3v4l.org/etpMf and http://3v4l.org/B8N2f.

**Comment by fredemmott** [comment]
#1871
