### ISSUE TITLE
connection refused

### ISSUE THREAD

**Issue by SkiAn2007** [facebook/hhvm#4782]
hhvm working with nginx
after some work stops accepting connections and nginx says connection refused
the logs are no errors and no apparent reason.

And the second question.
how to create a socket to another group?
eg hhvm works under user1 and socket is created user1: user1
and I need to user1: www-data as possible to set these settings?

If you manually change the permissions, the service is restarted, all rights revert to the original position

**Comment by jrobeson** [comment]
the socket group is fixed in an outstanding diff: https://reviews.facebook.net/D30039

**Comment by SkiAn2007** [comment]
how i can use it?

**Comment by JoelMarcey** [comment]
@jrobeson Actually that diff has gone stale. We closed the pull request. I haven't abandoned it manually yet as I was going to give @kristapsk a chance to see he wanted to pursue it more. If not, then someone has to take over the mantle.

**Comment by jrobeson** [comment]
@SkiAn2007 : someone has to finish it like @JoelMarcey says.

**Comment by Orvid** [comment]
This issue has been waiting for more info for more than 2 weeks. Closing for now, feel free to re-open it if you can provide more info.

https://github.com/facebook/hhvm/wiki/Human-Timeouts
