### ISSUE TITLE
Missing hphpize tool in official Ubuntu 14.04 build package

### ISSUE THREAD

**Issue by davemasterdave** [facebook/hhvm#4786]
I am trying to build the Mongofill for HHVM Extension(https://github.com/mongofill/mongofill-hhvm) on a Ubuntu 14.04 VM 64-bit. One of the tools required for this is hphpize. However, this tool seems to be missing from the pre-built packages provided. I tried hhvm-nightly & hhvm-nightly-dbg, but both failed to build the extension because of the missing hphpize tool.

Thanks in advance.

**Comment by jrobeson** [comment]
you need to install hhvm-dev package too.
