### ISSUE TITLE
install failures with new gdb support

### ISSUE THREAD

**Issue by rrh** [facebook/hhvm#4792]
Against master/head in OSS ubuntu 14.04, trying to install has a new failure related to a missing file deref.py, probably related to https://github.com/facebook/hhvm/commit/a6e38277af05fde89004464b9a51224b5edadabf

 CMake Error at hphp/tools/gdb/cmake_install.cmake:40 (file):
  file INSTALL cannot find
  "/home/rrh/git-work-2/php_agent/hhvm/hphp/tools/gdb/deref.py".

Further, running
  git status
now shows
  hphp/tools/gdb/hhvm-gdb
Is this a derived file that is not enumerated in a corresponding .gitignore file?

**Comment by reeze** [comment]
@rrh  Thank you for your feedback! 
After I sent the PR, the file `deref.py` was removed, I think I should find all of the `*.py` files but not enumerate them, I will send another PR to fix that.

**Comment by Orvid** [comment]
This was fixed.
