### ISSUE TITLE
session_unset() and session_destroy() set $_SESSION to null, should be []

### ISSUE THREAD

**Issue by iansltx** [facebook/hhvm#4793]
Repro: https://github.com/auraphp/Aura.Session/blob/develop-2/tests/unit/src/SessionTest.php; test will fail on lines 75 and 105. Zend runtime returns array() for a session that has been destroyed or unset, whereas HHVM returns null.

@sgolemon This might be one of the bugged areas?

https://github.com/facebook/hhvm/blob/master/hphp/runtime/ext/session/ext_session.cpp#L1835

**Comment by DmitrySoshnikov** [comment]
@iansltx, FYI: the `session_unset` is broken (it should be an empty array), however, the `session_destroy` don't clear any global vars associated with the session (so after `session_destroy` the `$_SESSION` will stay the same, though the session is destroyed).

```
<?php

session_start();

// empty array on each refresh, since session_destroy kills the session
var_dump($_SESSION);

if (empty($_SESSION)) {
  echo "Setting session value\n"; // always here
  $_SESSION['x'] = 10;
}

var_dump($_SESSION); // array('x' => 10)

session_destroy();

var_dump($_SESSION); // still array('x' => 10), but session is destroyed
```

**Comment by Majkl578** [comment]
This one may be related: #4838
