### ISSUE TITLE
Gearman extension in HHVM

### ISSUE THREAD

**Issue by Chintanvpatel** [facebook/hhvm#4795]
Hi,

Gearman extension is not implemented in HHVM. I found this one , https://github.com/longlong2010/hhvm-gearman

But it's not fully implemented ( missing methods ) and i'm not good at building extension. So, hope we can see fully compatible gearman extension in future which will work with HHVM.

Thanks,
Chintan V. Patel

**Comment by fredemmott** [comment]
We're unlikely to work on this; have you tried filing issues against hhvm-gearman for the missing methods?

**Comment by Chintanvpatel** [comment]
I emailed him. I will open issue.
