### ISSUE TITLE
[bug] [3.5.0] T_ELSEIF

### ISSUE THREAD

**Issue by keradus** [facebook/hhvm#4796]
In the following code:
```php
<?php if (1) {} else if (2) {}
```

the `else if` part is treated as `T_ELSEIF`.
Before 3.5 version or on all PHP version it is treated as `T_ELSE, T_WHITESPACE, T_IF`.
This breaks the behavior of tokenizer.

http://3v4l.org/ZB0k4#vhhvm-350

**Comment by Majkl578** [comment]
Thís is broken by the fix for #2699.
I also had objections to the fix, see the comments on d3375f7f49fa83bc3ebe273d6beb54992c75ae6f. This is exactly the case I was afraid of.

**Comment by jwatzman** [comment]
Personally, I'm *deeply* curious what code you have that cares about the difference between `else if` and `elseif` given that the two have identical semantics.

**Comment by Majkl578** [comment]
@jwatzman: For example a tool, which fixes coding standard. It should not change your code itself.

**Comment by keradus** [comment]
There may be a little bigger question here. Does HHVM with follow one-to-one behavior of PHP or not?

**Comment by fredemmott** [comment]
In general, yes, however we do make tradeoffs in some cases where we think the difference is negligible.

**Comment by keradus** [comment]
And in this issue in what direction you want to go ?

**Comment by paulbiss** [comment]
We've had this discussion before, and while I'm open to being convinced that this should be done differently I don't think any of the arguments presented so far have been compelling.

@sgolemon linked her alternative fix which didn't alter the token stream, we'd consider a PR for it provided that it came with a really convincing argument in favor of taking it.

https://gist.github.com/sgolemon/1e030d03d6445694a9b5

**Comment by keradus** [comment]
There is just one major - keeping compatibility with PHP from Zend.
To have same code running same on both implementation of PHP.

**Comment by paulbiss** [comment]
@keradus I agree, but I just don't see this as being a meaningful compatibility break. The T_ELSEIF token is semantically identical to T_ELSE T_WHITESPACE T_IF. That being said if someone can point me to a major framework or project that is broken by this change I would consider that a compelling argument, toy examples notwithstanding.

**Comment by keradus** [comment]
I agree there is no noticable different between them, but I also see it change the result of function I use.
Maybe it's just a matter of philosophy... or first step to introduce more and more incompatibilities.

**Comment by paulbiss** [comment]
If you look at our commit history you'll see that we generally try pretty hard to remove incompatibilities. I really wouldn't read much into this beyond that it was a lot cleaner than the other proposed patch, and as I mentioned I would be willing to go with the other fix if anyone has a practical real world example of this being a problem.

**Comment by keradus** [comment]
AS @Majkl578 [said](https://github.com/facebook/hhvm/issues/4796#issuecomment-73381045):
https://travis-ci.org/keradus/PHP-CS-Fixer/builds/49792688

**Comment by Majkl578** [comment]
bump

**Comment by sgolemon** [comment]
Fiiiiiiiiiiiine https://reviews.facebook.net/D35223

**Comment by keradus** [comment]
You are so totally great @sgolemon ! Thank you!
