### ISSUE TITLE
Multiple calls of 'include' do not check for file modification HHVM 3.5.0

### ISSUE THREAD

**Issue by uwetews** [facebook/hhvm#4797]
<?php
file_put_contents('foo.php', "<?php \n\$i=1;\n");
include 'foo.php';
echo $i;
sleep(2); // just to make sure that timestamp is different 
file_put_contents('foo.php', "<?php \n\$i=2;\n");
include 'foo.php';
echo $i;

Does not the modified include file on second call.
The echoed output is: 1 1

It does work under apache PHP.  The echoed output is: 1 2
NOTE: byte cache like APC must be configured to check file status on each request

HHVM should have a configuration parameter for file modification checks, or did I just not see it?

This problem popped up while making the Smarty template engine full HHVM compilant.

**Comment by fredemmott** [comment]
This is not currently supported. While we do intend to fix this eventually when running from source files, keep in mind it will not be fully compatible, as we will not support this (or any kind of eval()/generated code) in Repo Authoritative mode.

**Comment by fredemmott** [comment]
There is an incomplete patch at https://github.com/facebook/hhvm/pull/2357

This is also related to #1447

**Comment by uwetews** [comment]
Smarty does compile template source into PHP files and/or creates output PHP cache files.
When a page is called normally the compiled or cache template PHP files are included for processing.
These files contain code and data about template and subtemplate source dependicies and other information to determine if the compiled template or cache file is still valid or needs to be updated.
In the later case Smarty does overwrite the include file with same name but new content. The new include file is loaded again for processing and displaying the page.

Because of the problem the include file was updated on disk, but the old content will be displayed on the current request.  The new content will be displayed correct on the next request for that page.

PHP does recheck the filestats on each include/require, will detect the file modification and include the updated file when called multiple times in the same script.

Using timestamp or hash of source does not work in our case because compiled and cache files may contain content of many individual template source files. So the file name can't be computed when a page is called. 

I think this could be a major problem for all applications which will create/update PHP or Hack files.

Currently many of our units test do fail under HHVM as we do test recompilation and cache updates very intense. Currently we do have about 1900 individual tests to run. I tried to isolate the critical tests and run them in separate processes. But it seems that there could be race conditions between the individual processes as I get random errors.

**Comment by r3wt** [comment]
i just disable the templating and use nginx fastcgi cache as a work around.

**Comment by mikehaertl** [comment]
+1 For fixing this. Another affected package is the [yii2-composer](https://github.com/yiisoft/yii2-composer/blob/master/Installer.php) package, which is a requirement for installing Yii2 via composer. This is a composer plugin that updates a list of installed extensions in `vendor/yiisoft/extensions.php` and therefore reads and writes that file a couple of times during the runtime of composer.

**Comment by belgattitude** [comment]
+1 for fixing this or at least being able to reset cache, very useful when unit testing.

**Comment by uwetews** [comment]
For Smarty I have implemented a workaround for this problem.
The patch is the Smarty dev-master branch and will later be included in Smarty 3.1.28.

**Comment by mofarrell** [comment]
This was fixed.
