### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by wsycarlos** [facebook/hhvm#4798]
[ 40%] Built target hphp_analysis
Finished, 14 targets (14 cached) in 00:00:00.
+ /usr/bin/ocamldep.opt -modules third-party/core/container.ml > third-party/core/container.ml.depends
File "third-party/core/container.ml", line 2, characters 23-29:
Error: Syntax error
Command exited with code 2.
Compilation unsuccessful after building 567 targets (566 cached) in 00:00:06.
make[3]: *** [build-hack] Error 10
make[2]: *** [hphp/hack/CMakeFiles/hack] Error 2
make[1]: *** [hphp/hack/CMakeFiles/hack.dir/all] Error 2
make: *** [all] Error 2

System:Debian 7.0 64bit

**Comment by jwatzman** [comment]
@int3 can you look at this, looks like part of the Jane Street Core stuff you added doesn't build in 3.12 :\

**Comment by int3** [comment]
`make -C hphp/hack/src clean` will fix this.

**Comment by jwatzman** [comment]
@int3 nope, you have issues confused -- this looks to be an actual incompatibility with ocaml 3.12

**Comment by int3** [comment]
Closed by 9485c91.
