### ISSUE TITLE
Redis auto reconnect using database != 0

### ISSUE THREAD

**Issue by thomaswacker** [facebook/hhvm#4802]
In case of an automatic reconnect, the selected database index should be set to the last database index. This looks like to be correctly implemented:

https://github.com/facebook/hhvm/blob/master/hphp/system/php/redis/Redis.php#L968

But doConnect resets dbNumber to 0, so this line will never be executed.

**Comment by paulbiss** [comment]
Should be an easy fix. Line with attached hash for context: https://github.com/facebook/hhvm/blob/dd8bf4193cc37a39ce112a11301cee17b409b1fd/hphp/system/php/redis/Redis.php#L1067-L1069
