### ISSUE TITLE
Make typechecker return autocomplete suggestions for standard PHP in addition to Hack

### ISSUE THREAD

**Issue by cweagans** [facebook/hhvm#4806]
My code file (`test.php`):

```
<?hh

  class Foo {
    private ?int $bar;

    public function baz(): int {
      return $this->bAUTO332
    }
  }
```

If I run `hh_client --auto-complete --json < test.php`, I get this:

```
[{"name":"bar","type":"?int","pos":{"filename":"","line":4,"char_start":13,"char_end":16},"func_details":null,"expected_ty":false},{"name":"baz","type":"(function(): int)","pos":{"filename":"","line":6,"char_start":21,"char_end":23},"func_details":{"min_arity":0,"return_type":"int","params":[]},"expected_ty":false}]
```

which is exactly what I expect. However, if I modify my file to be like this:

```
<?php

class Foo {
  private $bar;

  public function baz() {
    return $this->bAUTO332
  }
}
```

and run the same command as before, I get:

```
[]
```

There's literally nothing else available that provides intelligent autocomplete suggestions for PHP that can be plugged into vim or Atom. I'd _love_ for this behavior to be supported.

**Comment by steelbrain** [comment]
@cweagans Until this is implemented by HHVM, You can do something like this
```php
<?php
class Main{
  public $db;
  public function __construct(){
    $this->db = new PDO('...');
  }
}
```
The HHI file for the above PHP code would be
```hack
<?hh //decl
class Main{
  public PDO $db;
  public function __construct();
}
```

**Comment by jwatzman** [comment]
Unfortunately `hh_server` has nearly 0 knowledge of PHP files, we don't even have a full PHP parser. So getting this info would be tricky.

There is some FB-internal code which attempts to "parse" enough of PHP files to generate a full autoload class map from FBs mixed PHP and Hack codebase. But I'm pretty sure that "parser" is just a regex looking for class definitions.

**Comment by garex** [comment]
+1 here it will be ideal and then Atom become usable for both PHP and Hack

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This issue applies to php code on hhvm. Hhvm [nolonger supports php code](https://hhvm.com/blog/2018/09/12/end-of-php-support-future-of-hack.html) since [hhvm version 4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html).

It is no longer possible to have Hack code call into PHP code.
