### ISSUE TITLE
c library calls to getgrnam_r and getgrgid_r fail

### ISSUE THREAD

**Issue by rrh** [facebook/hhvm#4807]
The C library calls to getgrnam_r and getgrid_r may fail if the buffer size isn't sufficient.  In this case, errno==ERANGE and you get to jack up the buffer size again until success.

The existing code in https://github.com/facebook/hhvm/blob/master/hphp/runtime/ext/posix/ext_posix.cpp
  most recently touched in https://github.com/facebook/hhvm/commit/3de3d68ded624f5c5486f97a169772f60948844e by Tim Siebels https://github.com/SiebelsTim 
isn't nuanced enough to handle this situation when errno==ERANGE, so the call to getgrnam_r or getgrgid_r will fail depending on the location of the sought after name/gid in /etc/group, and, possibly, the presence of large groups.

See http://tomlee.co/2012/10/problems-with-large-linux-unix-groups-and-getgrgid_r-getgrnam_r/ for a discussion and some (buggy and poorly rendered) code showing how one might loop to expand the buffer.

**Comment by rrh** [comment]
Fred says that most FB machines run nscd, http://linux.die.net/man/8/nscd so they may never see this issue.  I also suspect that most dev installations probably have a small /etc/group and so also never see this situation.

**Comment by SiebelsTim** [comment]
Interesting... I don't see that php-src handles this either. (https://github.com/php/php-src/blob/fc33f52d8c25997dd0711de3e07d0dc260a18c11/ext/posix/posix.c#L991)

I really hope there aren't a million other errors we don't catch :x

**Comment by Orvid** [comment]
This issue has been waiting for more info for more than 2 weeks. Closing for now, feel free to re-open it if you can provide more info.

https://github.com/facebook/hhvm/wiki/Human-Timeouts
