### ISSUE TITLE
[bug][3.5.0] T_OPEN_TAG_WITH_ECHO

### ISSUE THREAD

**Issue by ajgarlag** [facebook/hhvm#4809]
In the following code:

```php
<?=""?>
```
The first token `<?=` is parsed as `T_ECHO` while in PHP >=5.4 is parsed as `T_OPEN_TAG_WITH_ECHO`. In PHP <5.4 it depends on the `short_open_tag` setting: if enabled is parsed as `T_OPEN_TAG_WITH_ECHO`, if not it is parsed as `T_INLINE_HTML`.

http://3v4l.org/OJhCX

**Comment by keradus** [comment]
Any news on that ?

**Comment by paulbiss** [comment]
Looks like a pretty straightforward PR if you want to have a look at the lexer. No one has had the cycles to go after these lately on our end, so if it's important I'd recommend sending us a patch.

**Comment by keradus** [comment]
I won't send PR to fix it, I don't know the backend vell.
I saw incompatibility that affects me too so just ping to have that bug fix.

**Comment by keradus** [comment]
Bug opened for almost 3 months... any chances to get that fixed?

**Comment by paulbiss** [comment]
@keradus: I'm sorry about the delay in resolving your issue. While there are quite a few engineers on the team (a number of whom dedicate their time to community issues) there simply aren't enough of us to guarantee a response time for every issue that's open.

We prioritize the work we do based on a combination of impact, difficulty, skill required, and overarching goals set roughly every six months. In this case the issue simply hasn't been triaged by the team, it's most likely to get resolved by a community member (I mentioned this before). If not it's something we will be happy to look at when time allows.

Sadly, I can't give rough ETAs for all currently open issues (check the queue, this is quite far from the oldest issue), only the ones that are being actively worked on. While we would love to have the resources to resolve every issue in a fix timeframe, it's simply not possible. I'm very sorry for your frustration, I will make sure we keep track of the issue.

**Comment by keradus** [comment]
thank you @meghana1811  !
