### ISSUE TITLE
[bug][3.5.0] T_HASHBANG

### ISSUE THREAD

**Issue by ajgarlag** [facebook/hhvm#4810]
In the following code:

```php
#!/usr/bin/env php
<?php
?>
```
The first token `#!/usr/bin/env php\n` is parsed as `T_HASHBANG`.

This token does not exits in PHP. In PHP it is parsed as `T_INLINE_HTML`.

http://3v4l.org/OD95A

**Comment by paulbiss** [comment]
It was added to fix #1502. Is there a reason that having it causes a problem?

**Comment by keradus** [comment]
Same as #4796, #4809, to be compatible with PHP when someone work on result of `token_get_all`.

**Comment by ajgarlag** [comment]
Another problem is that `T_HASHBANG` constant is not defined in HHVM

http://3v4l.org/JdmTM

**Comment by keradus** [comment]
Any news on that ?

**Comment by paulbiss** [comment]
I don't think anyone is actively working on it. If you'd like to send us a PR that resolves it without re-breaking (#1159) we'd be happy to take it. (One option would be to hide the existence of the token from `token_get_all` and return `T_INLINE_HTML` instead).

**Comment by keradus** [comment]
I won't send PR to fix it, I don't know the backend vell.
I saw incompatibility that affects me too so just ping to have that bug fix.
