### ISSUE TITLE
Error handling config defaults don't match Zend

### ISSUE THREAD

**Issue by iansltx** [facebook/hhvm#4819]
...resulting in issues like #4818, which I've run into as well.

Probably just need to change here:

https://github.com/facebook/hhvm/blob/4d9b5b19afc0581856c79298f0672d7b55df9339/hphp/runtime/base/runtime-option.cpp#L841

for that default, and here:

https://github.com/facebook/hhvm/blob/4d9b5b19afc0581856c79298f0672d7b55df9339/hphp/runtime/base/runtime-option.cpp#L843

for throwing errors rather than exceptions on undef functions.

The latter of the two is convenient as-is, but unexpected when you're coming from PHP 5.6.

**Comment by paulbiss** [comment]
I'm unclear on what needs to be changed about `CallUserHandlerOnFatals`, @Majkl578 changed it in 6bf51a7b9fa28a4f3a2d1b29594e89c534355276 to match PHP 5.

Insofar as `ThrowExceptionOnBadMethodCall` is concerned, we would be willing to take a PR updating the default to whatever matches PHP 5.

**Comment by iansltx** [comment]
I need to do additional testing here, as it turns out. Closing this 'til I have a better repro scenario. May end up opening a more specific issue for the bad method call handling (I believe the divergence is around calling methods on non-objects).
