### ISSUE TITLE
HHVM hangs on OOM(?) condition

### ISSUE THREAD

**Issue by MaxSem** [facebook/hhvm#4821]
```
$ hhvm --version
HipHop VM 3.3.1 (rel)
Compiler: heads/master-0-g3efe530cd55a886d88b29acc014dde14c4cff755
Repo schema: b538518f4338eecd9dc2ff13865fd306926fde1b
Extension API: 20140829
$ hhvm -a
hphpd> $a=[]; while(true) { $x = new stdClass; $x->foo='gsergergergerger'; $a[]=$x; }
```
After a couple seconds, resource usage of hhvm stabilizes at 1% of CPU and 1.3G memory (out of 2G) and stays this way forever. No swapping occurs (disabled in my VM). After a few minutes, trying Control-C doesn't interrupt it:

```
^CPausing program execution, please wait...
^CStill attempting to pause program execution...
  Sometimes this takes a few seconds, so give it a chance,
  or press ctrl-c again to give up and terminate the debugger.
^CDebugger is quitting.
terminate called after throwing an instance of 'HPHP::Eval::DebuggerClientExitException'
  what():  Debugger client has just quit, request (if any) terminated.
^CDebugger is quitting.
^C^C^C^C
```

No termination ever happens. Trying to execute the same code from web via FastCGI results in a similar hangup of the HHVM server.

**Comment by paulbiss** [comment]
You can set the `memory_limit` ini setting to avoid process-wide OOMing. It should cause the request to terminate once it exceeds the limit.

**Comment by MaxSem** [comment]
Yep, if memory_limit is hit it works. However, this bug is about the exhaustion of physical memory (e.g. due to a heavy load) and it not being handled properly because the memory never gets released so other threads run out of memory too and you very quickly end up with a total memory starvation. It would be much nicer if physical memory allocation problems didn't make the exhaustion permanent.

**Comment by paulbiss** [comment]
This behavior in the absence of a memory limit seems reasonable. The alternative would be to have a default memory limit, I'd be fine with that too but don't feel it's a bug to have the process OOM without one set.
