### ISSUE TITLE
autoload_set_paths incorrectly typed

### ISSUE THREAD

**Issue by oyamauchi** [facebook/hhvm#4823]
This is the signature for `autoload_set_paths`, in functions.hhi:

``` hack
  function autoload_set_paths(
    \Indexish<string, \Indexish<string, string>> $map,
    string $root,
  ): bool;
```

This causes an error if the map includes the 'failure' key, because it maps to a function, which isn't Indexish.

Unfortunately, I think the best we can do is to change the type of $map to `Indexish<string, mixed>`. Another option is to split the failure callback into a separate parameter (which seems cleaner overall), but that would break BC.

**Comment by fredemmott** [comment]
Could this be done as a shape?

**Comment by jwatzman** [comment]
Yeah, the keys are fixed right, this sounds like a shape to me.

**Comment by oyamauchi** [comment]
Oh yeah, you're right. So the shape is:

```hack
type autoload_map = shape(
  'function' => \Indexish<string, string>,
  'class'    => \Indexish<string, string>,
  'constant' => \Indexish<string, string>,
  'type'     => \Indexish<string, string>,
  'failure'  => (function(string, string): ?bool)
);
```

**Comment by oyamauchi** [comment]
I guess, strictly speaking, `?bool` is stricter than what the runtime expects the failure callback to return (it distinguishes true, false, and anything else at all), but I think it should be fine.

BTW, we're only getting away with this internally because our autoload setup looks like this:

```hack
class Autoloader {
  private static $map;
  public static function register() {
    \HH\autoload_set_paths(
      array('function' => self::$map->getFunctionMap(), /* ... */),
      /* ... */
    );
  }
```

`self::$map` is untyped, so the type of `$autoload_map` is `array(string, _)` and the typechecker's happy.

**Comment by simonwelsh** [comment]
All the keys are currently optional, so using a shape would require that to change.

**Comment by jwatzman** [comment]
We could make all the values nullable or something like that. (Queue can of worms about nullable vs optional fields in shapes, and how we deal with both at runtime.)

**Comment by simonwelsh** [comment]
If you don't want to get into that, could move the failure out of the `$map` and add it as a third, optional argument.

**Comment by lexidor** [comment]
The current hhi is also wrong, but differently:
```HACK
  function autoload_set_paths(
    KeyedContainer<string, KeyedContainer<string, string>> $map,
    string $root,
  ): bool;
``` 
Calling this function in your application code has not been needed for some time. [hhvm-autoload](https://github.com/hhvm/hhvm-autoload) calls it for you (with an `HH_FIXME`). The days of this function are numbered, since native autoloading will be the only way in some time. Changing the type now would not be a valuable use of time. I am closing this issue, so it does not stay open after native autoloading becomes the only way.
