### ISSUE TITLE
Amazon Linux build fails (3.4, 3.5 branches)

### ISSUE THREAD

**Issue by burner1024** [facebook/hhvm#4826]
Same issue as #3728. Not sure why it was closed. 3.3 builds fine, 3.4 and 3.5 fail.
```
 $<LINK_ONLY:-Wl,--wrap=pthread_create>

  $<LINK_ONLY> expression requires exactly one parameter.

CMake Warning (dev) in hphp/runtime/CMakeLists.txt:
  Policy CMP0022 is not set: INTERFACE_LINK_LIBRARIES defines the link
  interface.  Run "cmake --help-policy CMP0022" for policy details. 
```

**Comment by eugene1g** [comment]
Are you using Cmake 3? I had to compile 3.5 on Amazon Linux over the last few days and had no issues after using Cmake3, so I updated the Amazon Linux procedure with a new entry https://github.com/facebook/hhvm/wiki/Building-and-installing-HHVM-3.5-on-Amazon-Linux-2014.09.2

**Comment by burner1024** [comment]
Specs say "cmake >= 2.8.7". I'm using whatever comes in stock on Amazon, I believe it's 2.8.12 now.

I also believe it's a good policy to have the code compile on common distributives without too many custom modifications.

**Comment by Orvid** [comment]
We don't use that expression in HHVM...
