### ISSUE TITLE
502 bad gateway

### ISSUE THREAD

**Issue by obb12** [facebook/hhvm#4827]
I installed hhvm but its not passing through
What port should i change it to?

**Comment by steelbrain** [comment]
@obb12 How did you install HHVM, did you compile from source, or used a pre-built package?
If you used a prebuilt extension, Are you sure that HHVM service is running?
HHVM by default uses 9000 fcgi port.

**Comment by obb12** [comment]
I use the brebuilt and i check via sudo service hhvm status that its Running

**Comment by steelbrain** [comment]
Does `telnet localhost 9000` give you connection refused?

**Comment by coderxlsn** [comment]
show log /var/log/hhvm/error.log

**Comment by obb12** [comment]
Yes and the log is empty

**Comment by steelbrain** [comment]
@obb12 If it gives you connection refused then HHVM is not listening on port 9000, can you post your configuration files located in `/etc/hhvm`

**Comment by obb12** [comment]
HTTP.PORT 9000

**Comment by obb12** [comment]
HHVM.SERVER.PORT 9000

**Comment by coderxlsn** [comment]
cat server.hdf 
PidFile = /var/run/hhvm/pid

Server {
  Port = 9201
  SourceRoot = /var/www/
  DefaultDocument = index.php
}

**Comment by coderxlsn** [comment]
show 
ps ax|grep hhvm

**Comment by obb12** [comment]
Where that file should be?

**Comment by coderxlsn** [comment]
/etc/hhvm/server.hdf

**Comment by obb12** [comment]
I only have php.ini and server.ini

**Comment by coderxlsn** [comment]
show server.ini

**Comment by steelbrain** [comment]
@obb12 I think it's more of a question than a bug, Lets discuss this in the IRC channel

**Comment by obb12** [comment]
I will when i can

**Comment by obb12** [comment]
Irc?

**Comment by obb12** [comment]
What channel?

**Comment by steelbrain** [comment]
#hhvm on freenode

**Comment by obb12** [comment]
I will be there tommorrow
