### ISSUE TITLE
Building on OS X 10.10.2 - libevent issue

### ISSUE THREAD

**Issue by craigcarnell** [facebook/hhvm#4829]
The current wiki instructs you to use brew install libevent which is not compatible with hhvm as it installs libevent 2.xx

Following some rather old instructions here:

```
git clone git://github.com/libevent/libevent.git
cd libevent
git checkout release-1.4.14b-stable
cat ../hiphop-php/hphp/third_party/libevent-1.4.14.fb-changes.diff | patch -p1
./autogen.sh
./configure --prefix=$CMAKE_PREFIX_PATH
make
sudo make install
cd ..
```

The compiler creates /usr/local/lib/libevent.dylib -> libevent-1.4.2.dylib

When I try to compile hhvm I get:

```
- Found libevent: /usr/local/lib/libevent.dylib
CMake Error at third-party/libafdt/CMakeLists.txt:71 (message):
  Couldn't find at least libevent 1.4.3+
```

**Comment by danslo** [comment]
Probably best to focus our efforts here:
https://github.com/facebook/hhvm/issues/4444
