### ISSUE TITLE
Support protected methods in interfaces if 'require extends' is used

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#4830]
I'd like:

``` PHP
interface Foo {
  require extends Bar;
  protected function baz(): herp;
}

...
class Bar {
  ...
  function doBaz() {
    if ($x instanceof Foo) {
      $x->baz();
    }
  }
  ...
}
```

This currently needs:

``` PHP
interface FooMarker {
}
trait FooImpl {
  require implements FooMarker;
  require extends Bar;
  abstract protected function baz(): herp;
}

...
class Bar {
...
  function doBaz() {
    if ($x instanceof FooMarker) {
      // UNSAFE
      $x->baz();
    }
  }
...
}
```

**Comment by fredemmott** [comment]
FB example: GenXHP :)

**Comment by Swahvay** [comment]
Just pinging this, cause I'd really like it too. :)

**Comment by fredemmott** [comment]
@paulbiss, @Orvid, @aorenste : is this something you'd be interested in a PR for?

**Comment by paulbiss** [comment]
I'd be ambivalent, I don't think it would be a bad change to make. Probably better to check with @dlreeves @andrewjkennedy and @alexchow first though.

**Comment by fredemmott** [comment]
Fixed by @vladima in https://github.com/facebook/hhvm/commit/6e594fc34d2e2270a12c46a858c8069a95ff9493
