### ISSUE TITLE
$_SESSION should be undefined until session_start() is called

### ISSUE THREAD

**Issue by Majkl578** [facebook/hhvm#4838]
``` php
<?php
var_dump($_SESSION);
session_start();
var_dump($_SESSION);
```

HHVM:

```
array(0) {
}
array(0) {
}
```

PHP:

```
<?php
Notice: Undefined variable: _SESSION in /in/U7f4d on line 3
NULL
array(0) {
}
```

http://3v4l.org/U7f4d

**Comment by DmitrySoshnikov** [comment]
There were recent changes to the session module, currently this one doesn't repro in master (can someone confirm, please?). We don't issue the warning, but the `$_SESSION` is actually `NULL` in first case.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Hhvm stopped supporting `$_SESSION` in hhvm [4.4.0](https://hhvm.com/blog/2019/05/06/hhvm-4.4.0.html).
