### ISSUE TITLE
Empty functions have return type ignored

### ISSUE THREAD

**Issue by TazeTSchnitzel** [facebook/hhvm#4839]
```hack
<?hh

function foo(): int {}

var_dump(foo()); // NULL
```

http://3v4l.org/8Oc3N

I'm talking at runtime. The type-checker isn't happy, of course.

**Comment by jwatzman** [comment]
@paroski didn't you fix this recently?

**Comment by paulbiss** [comment]
Yep, looks like it ef04103b39e59445c440c97fdccb735533cd5f96. Should be fixed in 3.6 when that goes out.
