### ISSUE TITLE
Invalid timezones (old timelib)

### ISSUE THREAD

**Issue by lystor** [facebook/hhvm#4842]
Hi

* CentOS 7
* tzdata-2015a-1.el7_0.noarch

HHVM 3.5.0 has old timelib.

### test_timelib.php
```php
<?php
foreach (timezone_identifiers_list() as $timezone) {
	exec("TZ=$timezone date '+%H:%M %Z'", $date_system);
	$date_system = $date_system[0];
	
	date_default_timezone_set($timezone);
	$date_php = date("H:i T");

	if ($date_system != $date_php) {
		echo sprintf("%-20s\t%s\t%s\n", $timezone, $date_system, $date_php);
	}
}
```

### php 5.6.5 WITHOUT any patches
```
America/Cancun      	18:19 EST	17:19 CST
```

### hhvm 3.5.0 WITHOUT use-system-tzinfo.patch
```
America/Cancun      	18:18 EST	17:18 CST
America/Metlakatla  	15:18 PST	15:18 MEST
Antarctica/Casey    	07:18 AWST	07:18 WST
Asia/Irkutsk        	07:18 IRKT	08:18 IRKT
Asia/Kashgar        	05:18 XJT	07:18 CST
Asia/Khandyga       	08:18 YAKT	09:18 YAKT
Asia/Krasnoyarsk    	06:18 KRAT	07:18 KRAT
Asia/Magadan        	09:18 MAGT	11:18 MAGT
Asia/Novokuznetsk   	06:18 KRAT	06:18 NOVT
Asia/Novosibirsk    	05:18 NOVT	06:18 NOVT
Asia/Omsk           	05:18 OMST	06:18 OMST
Asia/Sakhalin       	09:18 SAKT	10:18 SAKT
Asia/Urumqi         	05:18 XJT	07:18 CST
Asia/Ust-Nera       	09:18 VLAT	10:18 VLAT
Asia/Vladivostok    	09:18 VLAT	10:18 VLAT
Asia/Yakutsk        	08:18 YAKT	09:18 YAKT
Asia/Yekaterinburg  	04:18 YEKT	05:18 YEKT
Australia/ACT       	10:18 AEDT	10:18 EST
Australia/Adelaide  	09:48 ACDT	09:48 CST
Australia/Brisbane  	09:18 AEST	09:18 EST
Australia/Broken_Hill	09:48 ACDT	09:48 CST
Australia/Canberra  	10:18 AEDT	10:18 EST
Australia/Currie    	10:18 AEDT	10:18 EST
Australia/Darwin    	08:48 ACST	08:48 CST
Australia/Eucla     	08:03 ACWST	08:03 CWST
Australia/Hobart    	10:18 AEDT	10:18 EST
Australia/LHI       	10:18 LHDT	10:18 LHST
Australia/Lindeman  	09:18 AEST	09:18 EST
Australia/Lord_Howe 	10:18 LHDT	10:18 LHST
Australia/Melbourne 	10:18 AEDT	10:18 EST
Australia/North     	08:48 ACST	08:48 CST
Australia/NSW       	10:18 AEDT	10:18 EST
Australia/Perth     	07:18 AWST	07:18 WST
Australia/Queensland	09:18 AEST	09:18 EST
Australia/South     	09:48 ACDT	09:48 CST
Australia/Sydney    	10:18 AEDT	10:18 EST
Australia/Tasmania  	10:18 AEDT	10:18 EST
Australia/Victoria  	10:18 AEDT	10:18 EST
Australia/West      	07:18 AWST	07:18 WST
Australia/Yancowinna	09:48 ACDT	09:48 CST
Europe/Kaliningrad  	01:18 EET	02:18 FET
Europe/Minsk        	02:18 MSK	02:18 FET
Europe/Moscow       	02:18 MSK	03:18 MSK
Europe/Simferopol   	02:18 MSK	03:18 MSK
Europe/Volgograd    	02:18 MSK	03:18 VOLT
Pacific/Guam        	09:18 ChST	09:18 CHST
Pacific/Saipan      	09:18 ChST	09:18 CHST
```

### hhvm 3.5.0 WITH use-system-tzinfo.patch
```
Pacific/Guam        	09:19 ChST	09:19 CHST
Pacific/Saipan      	09:19 ChST	09:19 CHST
```

Please:
    1. Use system tzdata by default OR
    2. Add cmake parameter to use system tzdata OR
    3. Update timelib regularly on HHVM but it is not a panacea, because users do not update regularly HHVM to the latest version. tzdata is updated on all Linux distributions by vendors regularly.

Wikimedia patches HHVM and uses system tzdata:
* https://phabricator.wikimedia.org/T74556

Original discussion with rejected patch:
* https://github.com/hhvm/hhvm-third-party/pull/40

use-system-tzinfo.patch was found on:
* https://copr-be.cloud.fedoraproject.org/results/jrobeson/hhvm/epel-7-x86_64/hhvm-3.5.0-8.fc20/hhvm-3.5.0-8.el7.centos.src.rpm

Thank you

--
With best regards,
Mykola

**Comment by jrobeson** [comment]
@lystor : here is the associated discussion (and original source of the patch) https://github.com/hhvm/hhvm-third-party/pull/40

**Comment by jrobeson** [comment]
:( i didn't know that you linked ot the same discussion. I've heard that this proposal is being reconsidered, so try checking back in a week.

**Comment by lystor** [comment]
OK. Thank you

**Comment by fredemmott** [comment]
- 3.3, 3.6, and 3.7 branches now have 2015c tzdata (2015d has only been out a few days, and the implementation in timelib has had issues - not comfortable merging that yet)
- 3.8 is expected to use system tzdata (it's merged, but not been thoroughly tested yet)

**Comment by fredemmott** [comment]
(3.3, 3.6, and 3.7 will get updated tzdata in their next releases - new packages have not yet been released with these changes)
