### ISSUE TITLE
Xenforo and mysqli_stmt->fetch

### ISSUE THREAD

**Issue by PunKeel** [facebook/hhvm#4845]
Hi,
I'm having a stacktrace (and HHVM stopping working) with Apache 2.2, Debian 7.8, and Xenforo 1.4.3.
Here it is: http://pastebin.com/rCwuG1F4
Thanks in advance,

According to Xenforo, the error is : http://pastebin.com/XXjLvqPD `Array to string conversion`

**Comment by paulbiss** [comment]
This looks like it may be related to #4505. Can you test your code with d6577daf89598be8bdaa42d7489950b7fd8da265 (it's in master, you can use the nightly)?

**Comment by PunKeel** [comment]
Hi,
Just tested it in CLI (`hhvm index.php`), with hhvm-nightly, and it worked.
I'll stay with nightly build for now, thanks!

And thanks for the fast reply.
This issue can so be closed. <3

Le lundi 16 février 2015, Paul Bissonnette <notifications@github.com> a
écrit :

> This looks like it may be related to #4505
> <https://github.com/facebook/hhvm/issues/4505>. Can you test your code
> with d6577da
> <https://github.com/facebook/hhvm/commit/d6577daf89598be8bdaa42d7489950b7fd8da265>
> (it's in master, you can use the nightly)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/hhvm/issues/4845#issuecomment-74452820>.
>


-- 

------------------------------

Cordialement, *PunKeel*'.
