### ISSUE TITLE
extract() + namespaces = memory leak

### ISSUE THREAD

**Issue by terah** [facebook/hhvm#4846]
``` php
<?php

// The namespace is part of the bug
// remove it and the bug disappears
namespace HHVMTest\BuggyStaticClass;

class BuggyExtractClass
{
    public static function bigIteration()
    {
        for ( $i = 0; $i < 1000000 ; $i++ )
        {
            static::modifyRow(['value' => 1, 'value2' => 'something else', 'value3' => 2.3]);
            static::modifyRow(['value' => 1, 'value2' => 'something else', 'value3' => 2.3]);
            static::modifyRow(['value' => 1, 'value2' => 'something else', 'value3' => 2.3]);
            if ( $i % 100000 === 0 )
            {
                echoHumanFileSize();
            }
        }
        return true;
    }

    protected static function modifyRow($args)
    {
        // Memory is lost here
        extract($args);
    }
}

BuggyExtractClass::bigIteration();

function echoHumanFileSize()
{
    $bytes  = memory_get_usage();
    $sz     = 'BKMGTP';
    $factor = floor(( strlen($bytes) - 1 ) / 3);
    $mem    = sprintf("%.2f", $bytes / pow(1024, $factor)) . $sz[(int)$factor];
    echo("Memory Usage: {$mem}" . PHP_EOL);
}

//bash-4.2# hhvm --version
//HipHop VM 3.6.0-dev (rel)
//Compiler: heads/master-0-ga9e2a34d62dd95d72eb31b2e73ce475d73d87e2f
//Repo schema: e05b63d7e028ccfb71cf09a8df4753e70080d510

// Output
//bash-4.2# hhvm test_hhvm_mem_usage.php
//Memory Usage: 2.00M
//Memory Usage: 84.00M
//Memory Usage: 166.00M
//Memory Usage: 248.00M
//Memory Usage: 330.00M
//Memory Usage: 414.00M
//Memory Usage: 496.00M
//Memory Usage: 578.00M
//Memory Usage: 660.00M
//Memory Usage: 742.00M
```

**Comment by wjywbs** [comment]
The difference without and with namespace in hhas is:

```
   .method [protected static] modifyRow($args) {
-    FPushFuncD 1 "__SystemLib\\extract"
+    FPushFuncU 1 "HHVMTest\\BuggyStaticClass\\extract" "extract"
```

At https://github.com/facebook/hhvm/blob/d1cbb45ff50a63bb880737bf9a7d33458b063058/hphp/runtime/vm/jit/irgen-ret.cpp#L166, the current function with namespace does not have the "AttrMayUseVV" attribute, so iopRetC is not generated in the machine code and the local variables created by extract() will not be freed.

Since the variables are smart allocated, the memory will still be freed when the script finishes.

**Comment by paulbiss** [comment]
We now mark all functions as AttrMayUseVV outside of repo-mode.

There are still some significant bugs here though:

- We don't mark functions as AttrMayUseVV if they contain an FPushFuncU to an unqualified extract
- We don't mark dynamic calls as AttrMayUseVV in force_hh mode but we only enforce that all calls to extract be when Eval.DisallowDynamicVarEnvFuncs is set to ON.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Hhvm nolonger supports functions that inspect the environment of the caller. `extract()` has been removed around hhvm [4.1.0](https://hhvm.com/blog/2019/04/09/hhvm-4.1.0.html).
