### ISSUE TITLE
Saving localized floats to database cuts off decimal numbers

### ISSUE THREAD

**Issue by lowerends** [facebook/hhvm#4848]
I noticed that a Laravel DB insert with floating numbers using HHVM is cutting off the decimal part. In the example below, the value actually stored in the MySQL database is 7.00. The MySQL field is a decimal field.

    DB::table('test')->insert([
        [
            'name'        => 'Some name',
            'description' => 'Some description',
            'price'       => 7.99
    ]);

When using PHP instead of HHVM, the value is stored correctly. Also, when replacing 7.99 with '7.99' (as a string) using HHVM, the value is also stored correctly.
Is this an incompatibility between Laravel's insert() function and HHVM, or am I overlooking something here?

**Comment by r3wt** [comment]
typecast it to a double or string.

**Comment by fredemmott** [comment]
Could you reduce this to an example built on top of lower-level (mysql_* functions or PDO) statements instead of Laravel?

**Comment by lowerends** [comment]
I'll try to.

**Comment by lowerends** [comment]
Ok, so I've debugged a bit more and, apparently, it boils down to the locale that is being set, so it's got nothing to do with Laravel.

Here's a simple example to reproduce the problem.

This is the code with default localization:

````
$array = [
    'string' => '0.99',
    'float'   => 0.99,
];

var_dump($array);
````

The output using PHP is:

````
array(2) {
  'string' =>
  string(4) "0.99"
  'float' =>
  double(0.99)
}
````

The output using HHVM is:

````
array(2) {
  ["string"]=>
  string(4) "0.99"
  ["float"]=>
  float(0.99)
}
````

Now with another localization, where a comma is used as the decimal separator instead of a point:

````
setlocale(LC_ALL, 'nl_BE.UTF-8');

$array = [
    'string' => '0.99',
    'float'   => 0.99,
];

var_dump($array);
````

The output using PHP now is:

````
array(2) {
  'string' =>
  string(4) "0.99"
  'float' =>
  double(0.99)
}
````

The output using HHVM now is:

````
array(2) {
  ["string"]=>
  string(4) "0.99"
  ["float"]=>
  float(0,99)
}
````

Notice how the floating number now is represented as ````float(0,99)````, essentially leading to ````pdo->prepare($statement)->execute($bindings)```` to drop the decimal part.

Is this expected behaviour?

**Comment by Orvid** [comment]
This issue has been waiting for more info for more than 2 weeks. Closing for now, feel free to re-open it if you can provide more info.

https://github.com/facebook/hhvm/wiki/Human-Timeouts
