### ISSUE TITLE
CMake build fail : undefined reference to dwarf_producer_init_c - Ubuntu 14.04

### ISSUE THREAD

**Issue by k4zuk0** [facebook/hhvm#4849]
Hi,

I'm trying to build HHVM on Ubuntu 14.04. I first followed the instructions to isntall prebuilt packages for HHVM, but it lead me to a MongoClient error. To fix it, I found a repo by mcuadros to build a mongo.so specifically for HHVM. Then, the `build.sh` wanted to execute `hphpize`, and since the prebuilt packages don't provide hphp lib (or it seems so), I figured I should build HHVM from source.

I followed all the instructions I found for Ubuntu, even tried for several fixes alike to mine (some for Cent OS), but I still have the same mistake all over again :
When I'm in the hhvm directory, `cmake .` exits with errors, here are the ending of the cmake output

    -- Build type not specified: cmake build type Release.
    -- Boost version: 1.54.0
    -- Found the following Boost libraries:
    --   system
    --   program_options
    --   filesystem
    -- System PCRE does not have JIT enabled - will use hhvm-third-party/pcre
    -- Found libevent: /usr/lib/x86_64-linux-gnu/libevent.so
    -- Could NOT find LibUODBC (missing:  LIBODBC_LIBRARIES LIBODBC_INCLUDE_DIRS) 
    -- Found libsqlite3: /usr/lib/x86_64-linux-gnu/libsqlite3.so
    -- Could NOT find DOUBLE_CONVERSION (missing:  DOUBLE_CONVERSION_LIBRARY DOUBLE_CONVERSION_INCLUDE_DIR) 
    -- Using third-party bundled double-conversion
    -- Could NOT find LZ4 (missing:  LZ4_LIBRARY LZ4_INCLUDE_DIR) 
    -- Using third-party bundled LZ4
    -- Could NOT find FastLZ (missing:  FASTLZ_LIBRARY FASTLZ_INCLUDE_DIR) 
    -- Using third-party bundled fastlz
    -- Could NOT find LIBZIP (missing:  LIBZIP_LIBRARY LIBZIP_INCLUDE_DIR_ZIP LIBZIP_INCLUDE_DIR_ZIPCONF) 
    -- Using third-party bundled libzip
    -- Found ICU header files in /usr/include/x86_64-linux-gnu
    -- Found ICU libraries: /usr/lib/x86_64-linux-gnu/libicuuc.so
    -- Found jemalloc: /usr/lib/x86_64-linux-gnu/libjemalloc.so
    -- Found Intel TBB
    -- Found mcrypt: /usr/lib/libmcrypt.so
    -- Looking for dwarf_producer_init
    -- Looking for dwarf_producer_init - found
    -- Performing Test DW_CONST
    -- Performing Test DW_CONST - Failed
    -- Looking for dwarf_producer_init_c
    -- Looking for dwarf_producer_init_c - not found
    -- libdwarf uses char* type
    -- libdwarf does not have dwarf_producer_init_c, using dwarf_producer_init
    Generating Release build
    -- Found ocamlc: /usr/bin/ocamlc
    -- Found ocamlc.opt: /usr/bin/ocamlc.opt
    -- GNU FriBidi not found
    -- Using built-in JSON parser
    -- Building async MySQL extension
    -- Found gold: /usr/bin/gold
    -- Configuring incomplete, errors occurred!
    See also "/usr/local/include/hhvm/CMakeFiles/CMakeOutput.log".
    See also "/usr/local/include/hhvm/CMakeFiles/CMakeError.log".

(I don't know if it matters, but since I'm building it from `/usr/local/include/hhvm` (don't ask me why I picked this folder, I don't even know), I'm sudoing it)

When I look into the `CMakeError.log` file, it seems to be related to libdwarf, here are the last lines (some of them are in French, I'm really sorry about that) :

    /usr/local/include/hhvm/CMakeFiles/CMakeTmp/src.cxx:6:52: warning: no return statement in function returning non-void [-Wreturn-type]
             Dwarf_Unsigned * g, Dwarf_Ptr h, int * i) {}
                                                        ^
    /usr/local/include/hhvm/CMakeFiles/CMakeTmp/src.cxx: In function ‘int main()’:
    /usr/local/include/hhvm/CMakeFiles/CMakeTmp/src.cxx:7:128: error: invalid conversion from ‘int (*)(const char*, int, Dwarf_Unsigned, Dwarf_Unsigned, Dwarf_Unsigned, Dwarf_Unsigned, Dwarf_Unsigned*, Dwarf_Ptr, int*) {aka int (*)(const char*, int, long long unsigned int, long long unsigned int, long long unsigned int, long long unsigned int, long long unsigned int*, void*, int*)}’ to ‘Dwarf_Callback_Func {aka int (*)(char*, int, long long unsigned int, long long unsigned int, long long unsigned int, long long unsigned int, int*, int*)}’ [-fpermissive]
           int main() { dwarf_producer_init(0, dwarfCallback, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr); return 0; }
                                                                                                                                    ^
    /usr/local/include/hhvm/CMakeFiles/CMakeTmp/src.cxx:7:128: error: too many arguments to function ‘Dwarf_P_Debug_s* dwarf_producer_init(Dwarf_Unsigned, Dwarf_Callback_Func, Dwarf_Handler, Dwarf_Ptr, Dwarf_Error_s**)’
    In file included from /usr/local/include/hhvm/CMakeFiles/CMakeTmp/src.cxx:2:0:
    /usr/include/libdwarf.h:2246:15: note: declared here
     Dwarf_P_Debug dwarf_producer_init(
                   ^
    make[1]: *** [CMakeFiles/cmTryCompileExec665323765.dir/src.cxx.o] Erreur 1
    make[1]: quittant le répertoire « /usr/local/include/hhvm/CMakeFiles/CMakeTmp »
    make: *** [cmTryCompileExec665323765/fast] Erreur 2
    
    Source file was:
    
          #include <libdwarf.h>
          #include <cstddef>
          int dwarfCallback(const char * a, int b, Dwarf_Unsigned c,
            Dwarf_Unsigned d, Dwarf_Unsigned e, Dwarf_Unsigned f,
            Dwarf_Unsigned * g, Dwarf_Ptr h, int * i) {}
          int main() { dwarf_producer_init(0, dwarfCallback, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr); return 0; }
    Determining if the function dwarf_producer_init_c exists failed with the following output:
    Change Dir: /usr/local/include/hhvm/CMakeFiles/CMakeTmp
    
    Run Build Command:"/usr/bin/make" "cmTryCompileExec2545180586/fast"
    /usr/bin/make -f CMakeFiles/cmTryCompileExec2545180586.dir/build.make CMakeFiles/cmTryCompileExec2545180586.dir/build
    make[1]: entrant dans le répertoire « /usr/local/include/hhvm/CMakeFiles/CMakeTmp »
    /usr/local/bin/cmake -E cmake_progress_report /usr/local/include/hhvm/CMakeFiles/CMakeTmp/CMakeFiles 1
    Building C object CMakeFiles/cmTryCompileExec2545180586.dir/CheckFunctionExists.c.o
    /usr/bin/cc   -ftrack-macro-expansion=0 -fno-builtin-memcmp -w -DCHECK_FUNCTION_EXISTS=dwarf_producer_init_c -std=c++0x   -o CMakeFiles/cmTryCompileExec2545180586.dir/CheckFunctionExists.c.o   -c /usr/local/share/cmake-3.1/Modules/CheckFunctionExists.c
    Linking C executable cmTryCompileExec2545180586
    /usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTryCompileExec2545180586.dir/link.txt --verbose=1
    /usr/bin/cc    -ftrack-macro-expansion=0 -fno-builtin-memcmp -w -DCHECK_FUNCTION_EXISTS=dwarf_producer_init_c -std=c++0x   CMakeFiles/cmTryCompileExec2545180586.dir/CheckFunctionExists.c.o  -o cmTryCompileExec2545180586 -rdynamic -Wl,-Bstatic -ldwarf -Wl,-Bdynamic -lelf
    CMakeFiles/cmTryCompileExec2545180586.dir/CheckFunctionExists.c.o: dans la fonction « main »:
    CheckFunctionExists.c:(.text+0x15): référence indéfinie vers « dwarf_producer_init_c »
    collect2: error: ld returned 1 exit status
    make[1]: *** [cmTryCompileExec2545180586] Erreur 1
    make[1]: quittant le répertoire « /usr/local/include/hhvm/CMakeFiles/CMakeTmp »
    make: *** [cmTryCompileExec2545180586/fast] Erreur 2

The versions of the different tools I can think of :
CMake : 3.1.3 (tried with 2.8.12.2, same error)
Full `hhvm --version` output :

    HipHop VM 3.5.0 (rel)
    Compiler: tags/HHVM-3.5.0-0-ga90f4733cfa0d8fefdafc7433f758f78cdc75424
    Repo schema: b88b6fee8ef78ab638506d212abcbefe74a276ac

gcc & g++ : (Ubuntu 4.8.2-19ubuntu1) 4.8.2

**Comment by jrobeson** [comment]
so did you install hhvm-dev before trying to build yourself? It's not clear from the initial report.

**Comment by k4zuk0** [comment]
I installed hhvm using `sudo apt-get install hhvm`, following the instructions provided on hhvm's repo for my version of Ubuntu. It installed fine, but when I tried to use it instead of PHP for my Symfony2 project, I had the MongoClient error. Then again, to build the mongo.so for hhvm I needed HPHP, which I didn't have after installing it via apt-get. I'm not sure I'm really clear..

**Comment by jrobeson** [comment]
you have to install hhvm-dev if you want to build your own extensions. I suggest deleting your own attempt at hhvm compilation and trying with the hphpize provided with hhvm-dev

**Comment by k4zuk0** [comment]
I didn't know I could get hphpize this way. Thanks a lot for helping me !

**Comment by k4zuk0** [comment]
It fixed my problem. I just had one more bug (mission /usr/include/hphp/runtime/version.h), but I found a fix reading https://github.com/chregu/hhvm-newrelic-ext, and the extension built successfully !

**Comment by bluetazmanian** [comment]
Hi @k4zuk0,

I know this is an old post. I'm trying to build HHVM on alpine linux and I'm having the same error. How did you resolve it?

Cheers,
B
