### ISSUE TITLE
Array-like objects and some array functions

### ISSUE THREAD

**Issue by nazar-pc** [facebook/hhvm#4852]
When calling `current()`, `key()` (probably, some other similar functions) on array-like object (that implements `ArrayAccess` and `Iterator` interfaces) I'm getting:
> Warning: Invalid operand type was used: expecting an array in ...

Current HHVM Nightly

**Comment by fredemmott** [comment]
Documented inconsistency: https://github.com/facebook/hhvm/blob/master/hphp/doc/inconsistencies#L73-78

Implementing this behavior has a high cost, and it's best avoided anyway - it will not work correctly, even in PHP5, except in the simplest of cases - eg, if you subclass an SPL iterator and change the behavior of next(), the functions will not pay attention.

**Comment by fredemmott** [comment]
Example: http://3v4l.org/mGi69

**Comment by nazar-pc** [comment]
In fact this is pretty simple, if object passed and it implements `Iterator` interface - just convert `current($foo)` to `$foo->current()`. Basically this is everything what is needed here, class will handle cursor by itself according to interface. How it does that doesn't matter.

**Comment by fredemmott** [comment]
Sorry, it's unfortunately not that simple: http://3v4l.org/7DZuZ

**Comment by nazar-pc** [comment]
What did you meant by that example, class is not used?

**Comment by fredemmott** [comment]
Whoops: http://3v4l.org/ZY8gV

**Comment by nazar-pc** [comment]
Wow, that is strange. Possibly, some documented "feature"?)
Anyway, it would be great to handle at trivial cases, I have pretty obvious case that is not using built-in iterators, just implements mentioned interfaces.

**Comment by fredemmott** [comment]
- it's an unpredictable (and unsafe) way to write code, because of how many edge cases there are
- there's a performance overhead to implementing this
- it's likely we'd under-specify the 'trivial' cases
- we feel that it's better to emit a warning in too many cases,than to silently do the wrong thing - especially when silently doing the 'right' thing is likely not what the author is expecting in some common cases.
