### ISSUE TITLE
Make type checker aware of vendor files

### ISSUE THREAD

**Issue by milesj** [facebook/hhvm#4856]
As the title states. It would be nice if the type checker was aware of vendor files that aren't a part of the source directory where `.hhconfig` is located.

**Comment by SiebelsTim** [comment]
Getting `.hhi` files from a project would solve this and would be a nice feature. This would also be awesome for hhvm itself, since we are missing a lot of `.hhi` definitions.

**Comment by jwatzman** [comment]
The expectation is that the hhconfig lives up above the vendor directory, so it's all checked together. hhi files are another option.

I'll be honest -- I haven't thought this case through very carefully, so interested to see what you all feel are the pros/cons of different approaches, issues we aren't solving well, what I'm missing and not understanding, etc.

**Comment by milesj** [comment]
My current situation is that I want to type check our source folder and "fix" (or remove) the type checker errors for vendors, which is primarily these unbound errors: "Unbound name: Psr\Http\Message\OutgoingResponseInterface".

But now that I think about it, moving it up another folder *would* work, as the type checker ignores normal PHP files correct? It only type checks `<?hh` files.

**Comment by jwatzman** [comment]
> But now that I think about it, moving it up another folder would work, as the type checker ignores normal PHP files correct? It only type checks <?hh files.

Correct.

> Also, what's the state of the hhi files? I have an HHVM fork where I've added a handful of unbound fixes but haven't pushed them yet as the state of hhi may/was going to change.

hhi files are still a thing, except the ones defining the standard system libraries are now automatically included with the `hh_server` binary (and having your own copies is an error). hhi files defining other things will still work, but of course can't be checked against the code they describe, and so are susceptible to bitrot.

**Comment by milesj** [comment]
I suppose another possible situation is Hack files within vendors and not wanting to type check them, but reference that they exist.

**Comment by milesj** [comment]
I moved the `.hhconfig` file up a directory so that vendors would be included and I'm still getting unbound errors.

    /vagrant/src/Titon/Controller/Controller.hh:102:32,55: Unbound name: Psr\Http\Message\IncomingRequestInterface (an object type) (Naming[2049])

Is it because they are not Hack files?

**Comment by jwatzman** [comment]
In strict mode (or with `assume_php = false` in your `hhconfig`) anything you call has to be in a Hack file, yes.

**Comment by milesj** [comment]
Ah right. Totally forgot about that requirement. Cheers.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Hhvm only supports running Hack code since hhvm [4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html). This means that there are no `<?php` files in your vendor directory that hhvm can execute. The typechecker sees all Hack files and doesn't need to ignore any in a well-typed codebase.

If you need to ignore files, you can use the `ignored_paths` option in the `.hhconfig` file.
