### ISSUE TITLE
Multiple hack attributes of the same name

### ISSUE THREAD

**Issue by milesj** [facebook/hhvm#4857]
This is currently not supported for user-land attributes but would be very nice to have. An example of this usage:

```hack
<<BelongsTo('User', 'user_id'), BelongsTo('Topic', 'topic_id')>>
class Post extends Model { }
```

This should definitely not be possible for built-ins like `<<__Memoize>>`.

**Comment by paulbiss** [comment]
This feature request is not actively being worked on. We would happily consider a pull request implementing it. If you plan to work on this issue let us know in the comments and we will re-open the issue and assign it to you. If you feel strongly that this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
