### ISSUE TITLE
Throw exception immediately when memory limit is exceeded

### ISSUE THREAD

**Issue by tstarling** [facebook/hhvm#4862]
It would be nice if HHVM would check if an allocation will exceed the memory limit, and immediately throw an exception if it would, instead of allocating the requested memory and setting a flag in RequestInjectionData. This would improve HHVM's resistance to DoS attacks, and make it simpler to provide a correct PHP stack at the site of the OOM.

@swtaarrs previously told me that there were callers that required a non-throwing allocator, but he wasn't sure if any such callers still existed. If they do still exist, perhaps a non-throwing alternative to smart_malloc() could be provided, which calls abort() instead.

Note that smart_malloc() can in fact already throw an exception if jemalloc is not used -- safe_malloc() will throw if the OS cannot supply enough memory. If jemalloc is used, mallocx() is called, which apparently segfaults on OOM. This is not ideal.

**Comment by tstarling** [comment]
July 16, 2014:
[swtaarrs_]	TimStarling: there are some places that need to allocate memory but aren't safe places to throw exceptions from
[TimStarling]	yeah, but safe_malloc() does throw, and newSlab() calls safe_malloc()
[TimStarling]	so you're screwed anyway
[swtaarrs_]	doesn't safe_malloc abort?
[swtaarrs_]	if malloc returns nullptr
[TimStarling]	inline void* safe_malloc(size_t size) {
[TimStarling]	  void* p = malloc(size);
[TimStarling]	  if (!p) throw OutOfMemoryException(size);
[TimStarling]	  return p;
[TimStarling]	}
[swtaarrs_]	huh
[swtaarrs_]	that's news to me
[swtaarrs_]	but more importantly, there's a difference between malloc failing and exceeding the PHP memory usage limit
[TimStarling]	of course, malloc() rarely fails under linux -- the only way to make it fail that I know of is with ulimit -v
[TimStarling]	if you exceed the amount of physical mem + swap, oom-killer will just kill the process, malloc() will never fail
[swtaarrs_]	oom-killer can react quickly enough?
[swtaarrs_]	what if you ask malloc for 2^64 - 1 bytes?
[TimStarling]	yeah, maybe
[TimStarling]	I wonder how many callers can't tolerate exceptions being thrown
[swtaarrs_]	the situation might be better now
[swtaarrs_]	I was just thinking about it
[swtaarrs_]	lots of places that can allocate can already throw for other reasons, but it might be in a slightly different part of the code
[swtaarrs_]	like appending to strings and arrays
[TimStarling]	we could have an explicitly non-throwing allocator, and make plain smart_malloc() throw
[TimStarling]	my concern is a DoS attack which causes HHVM to be killed by oom-killer due to carefully constructed input text
[TimStarling]	e.g. some devs use explode() without checking the string length first
[swtaarrs_]	yeah
[swtaarrs_]	brb
[TimStarling]	when you expect a 10-byte string, that's ok, but then an attacker gives you 1GB and you're in trouble
[swtaarrs_]	yeah it's probably worth trying again
[swtaarrs_]	although I think we use smart_malloc to back emalloc and I bet that's expect to return null on failure
[swtaarrs_]	but that's easy to make happen
[swtaarrs_]	if needed
[TimStarling]	I don't think any allocator should ever return null on failure
[TimStarling]	but maybe I'm scarred by some experiences with ImageMagick
[swtaarrs_]	heh
[TimStarling]	we used to use ulimit -v, so malloc would fail for large images
[swtaarrs_]	well when we're implementing an existing interface we should play along
[TimStarling]	and it had about 100 different ways of crashing
[swtaarrs_]	oof
[TimStarling]	sometimes it would politely segfault
[TimStarling]	sometimes it would deadlock and hang forever, which was less polite
[TimStarling]	maybe 70% of callers would check for allocation failure
[TimStarling]	but those callers would just unexpectedly return NULL to their callers, and make them segfault instead
[swtaarrs_]	hahaha

**Comment by bertmaher** [comment]
Yeah, I'd love to have this fixed in general but there are decidedly still some random places where we crash if you throw.  I've been picking at it by modifying the allocator to throw randomly with some probability, and then running our test suite repeatedly and debugging the crashes.  I don't know that I have time to actually get us over the line, so if you're interested in helping I can put up my random-OOM diff as a stress test mode and we can both hammer on it :-).

**Comment by bertmaher** [comment]
Oh, and I was just thinking of the "smart" allocator... of course anything that calls malloc directly just doesn't care about the request memory limit until it's too late.  It'd be really nice to hunt down mallocs that are really request-local and convert them to smart alloc.

**Comment by r3wt** [comment]
@bertmaher as a temporary work around, it could be done with http://php.net/manual/en/function.register-tick-function.php

every tick you check memory usage. throw if getting close to the limit, etc.

**Comment by paulbiss** [comment]
@r3wt: we already do this implicitly when running PHP code via surprise flags. If you've exceeded your memory limit then an exception will be thrown on the next surprise check (generally any backward branch, or return, or function/closure/generator/async entry).

The main problem here is that an extension can exhaust all request memory and continue to allocate without being stopped because in C++ you have to explicitly trigger a surprise check and the allocator will not fail if you've exceeded the request limit. If the extension eventually returns control to PHP then an exception will be thrown, but there's a real danger that the extension may OOM the entire process before ever reentering PHP.

**Comment by paulbiss** [comment]
This is still something I'd be interested in seeing but it's a large and rathe risky project and I don't think anyone currently has the bandwidth for it. If anyone wants it let me know and I will reopen/assign to you.
