### ISSUE TITLE
Implement %L{Csdf} in AsyncMysqlClient::queryf()

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#4866]
This would allow:

```
SELECT %LC FROM %T WHERE %C IN (%Ls)
```

These should require Vector<string|int|float>

**Comment by fredemmott** [comment]
cc @drilibo

**Comment by paulbiss** [comment]
Hi Fred! If you're still working on this feel free to re-open it.

**Comment by simonwelsh** [comment]
The [docs](https://docs.hhvm.com/hack/reference/class/AsyncMysqlConnection/queryf/) say that this is done already.
