### ISSUE TITLE
Interest in the cPanel arena

### ISSUE THREAD

**Issue by ylluminate** [facebook/hhvm#4867]
As one can review [*here*](http://features.cpanel.net/responses/php-hhvm-support-for-better-performance), there is some real interest for integration of HHVM within the cPanel community and by cPanel themselves if a few things are figured out.

First, they are looking for real world scenarios of deployment.  I'm willing to give them this if I can work through some of the details.

Second, what is the current situation with running HHVM in a shared environment? The vast majority of people that use cPanel & WHM do so in a shared, multi-user environment that requires a per user control so that the system can keep users isolated.  Can this be done readily and if so, are there any instructions presently for this?

I thought I'd go ahead and pose these items in hope to get some clarity before I really start digging into one of our servers to see how to go about adding this.  It's nice to have some clarity going in... :)

**Comment by WizKid** [comment]
Some discussion about multi user environment you can read about in #4859

**Comment by Ninos** [comment]
May dublicate of #1616 (for reference)

**Comment by paulbiss** [comment]
Going to close this for now. Please open new issues if you'd like to follow up on any of these points.
