### ISSUE TITLE
MySQLi is not connecting to MySQL server in latest nightly

### ISSUE THREAD

**Issue by nazar-pc** [facebook/hhvm#4869]
Ubuntu 15.04 x64, worked before with Nightly, also works fine with stable

**Comment by POPSuL** [comment]
Yep, I confirm that!
Example:

```php
<?php

$link = new mysqli('localhost', 'root', 'root');
die($link->error);
```

Expected:
```bash
[popsul] /tmp  % php ./test.php 
[popsul] /tmp  % 
```

Actual:
```bash
[popsul] /tmp  % hhvm ./test.php

Warning: mysql_connect(): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)

Warning: invalid object or resource mysqli in /tmp/test.php on line 4
```

**Comment by PunKeel** [comment]
Had this bug too, in last build
To fix it, simply change `localhost` to `127.0.0.1` and it should work again

**Comment by steelbrain** [comment]
It is because of switch from mysqlclient to webscalesqlclient? Maybe.

**Comment by drbild** [comment]
Still a problem on the latest Ubuntu 14.04 LTS release, 3.6.0~trusty.  

As suggested by @PunKeel, changing the mysql connection from `localhost` to `127.0.0.1` fixed the error.

**Comment by Orvid** [comment]
This appears to have been fixed already.
