### ISSUE TITLE
$_SERVER['HTTPS'] is set when not in HTTPS mode

### ISSUE THREAD

**Issue by hopeseekr** [facebook/hhvm#4870]
This is a trivial PHP incompatibility, but it did totally break the last site my corporation has yet to port to HHVM...

In PHP, when not in https://, the $_SERVER['HTTPS'] variable is never set, but in HHVM, it is.  This leads to the following code returning "http://" via PHP but "https://" via HHVM:

    $protocol = !isset($_SERVER['HTTPS']) ? 'http' : 'https';

In our particular case it was more severe than on first blush, since we had:

          <base href="https://www.incendiary.ws/"/>

instead, and it broke the entire site with insecurity mismatch errors and the refusal of CSS and images to load.

**Comment by paulbiss** [comment]
I believe that we're looking for the fastcgi parameter "HTTPS" and that it isn't set to "OFF" for compatibility with IIS.

https://github.com/facebook/hhvm/blob/87f853d16db9fb0b443f856de1c5f28a6803b5c8/hphp/runtime/server/fastcgi/fastcgi-transport.cpp#L301-L304

https://github.com/facebook/hhvm/blob/5a46b50d809590b8feeeb05ede056106bcfb12a6/hphp/runtime/server/http-protocol.cpp#L734-L735

**Comment by simonwelsh** [comment]
> In PHP, when not in https://, the $_SERVER['HTTPS'] variable is never set

That's not true. From the [docs](http://php.net/manual/en/reserved.variables.server.php):

> Set to a non-empty value if the script was queried through the HTTPS protocol.

There are certainly PHP SAPIs that set `HTTPS` to the empty string, which `isset` would return true for.

**Comment by hopeseekr** [comment]
Sorry. I didn't realize that it behaved that way on IIS. That's still — what? — 1% of all PHP installs, if that? :-) It's just a footnote on the PHP docs...

**Comment by SimoneLazzaris** [comment]
I've stumbled into this issue too: I've found that not only  $_SERVER['HTTPS'] is set, but its value is "on", which is clearly incorrect.

I've crafted a simple test file:
<?php print json_encode($_SERVER); ?>

And with curl I see:
simone@orion:~$ curl http://loadtest2.interac.it/t1.php 
{"REQUEST_START_TIME":1426585205,"REQUEST_TIME":1426585205,"REQUEST_TIME_FLOAT":1426585205.0109,"HTTP_USER_AGENT":"curl\/7.41.0","HTTP_CONTENT_LENGTH":"","HTTP_HOST":"loadtest2.interac.it","HTTP_CONTENT_TYPE":"","HTTP_ACCEPT":"*\/*","GATEWAY_INTERFACE":"CGI\/1.1","SERVER_ADDR":"212.183.164.138","SERVER_NAME":"loadtest2.interac.it","SERVER_PORT":"80","SERVER_SOFTWARE":"nginx\/1.2.1","SERVER_PROTOCOL":"HTTP\/1.1","SERVER_ADMIN":"","SERVER_SIGNATURE":"","CONTENT_LENGTH":"","REQUEST_METHOD":"GET","CONTENT_TYPE":"","REMOTE_PORT":39042,"REDIRECT_STATUS":"200","DOCUMENT_URI":"\/t1.php","SCRIPT_NAME":"\/t1.php","HTTPS":"on","SCRIPT_FILENAME":"\/srv\/www\/loadtest2.interac.it\/t1.php","REQUEST_URI":"\/t1.php","REMOTE_ADDR":"212.183.161.99","DOCUMENT_ROOT":"\/srv\/www\/loadtest2.interac.it","QUERY_STRING":"","SCRIPT_URL":"\/t1.php","SCRIPT_URI":"https:\/\/loadtest2.interac.it\/t1.php","PHP_SELF":"\/t1.php","PATH_TRANSLATED":"\/srv\/www\/loadtest2.interac.it\/t1.php","argv":[""],"argc":1,"THREAD_TYPE":"Web Request"}simone@orion:~$ 

As you can see, HTTPS is "ON", and SCRIPT_URI is "https://...." which is wrong. I had to override wordpress ssl detection to make my site work.

I'm using hhvm 3.6.0, on a debian wheezy (64bit) with nginx 1.2.1

**Comment by craigcarnell** [comment]
There is a bug in 3.6.0 which has just been fixed. It will be included in 3.6.1 or use a nightly (not built yet maybe tomorrow)

**Comment by SimoneLazzaris** [comment]
Thanks, I'll try and let you know.

**Comment by desbo** [comment]
This was breaking my WordPress installation by forcing it to request assets over https, which my server doesn't support. 

As a temporary fix (but only if you don't use HTTPS) edit ```is_ssl()``` in wp-include/functions.php to always return false.

**Comment by paulbiss** [comment]
This should be fixed as of 2a50896c0aba5378a4d2e3bdd2dea7ab3783cb9b
