### ISSUE TITLE
Build error on using LLVM + HHVM for 

### ISSUE THREAD

**Issue by sathvikl** [facebook/hhvm#4871]
I modified CMake/FindLLVM.cmake to build with LLVM.  The modifications were done to list all the required llvm libraries, however it fails at the build step itself.  
When the USE_LLVM debug symbol is enabled - I get these build errors. I am using LLVM version -  3.5.2 

[ 41%] Building CXX object hphp/runtime/CMakeFiles/hphp_runtime_static.dir/vm/jit/vasm-llvm.cpp.o
/home/sathvikl/HHVM/hhvm-fb-github-fork/hphp/runtime/vm/jit/vasm-llvm.cpp:423:16: error: ‘virtual bool HPHP::jit::{anonymous}::TCMemoryManager::allowStubAllocation() const’ marked override, but does not override
   virtual bool allowStubAllocation() const override {
                ^
/home/sathvikl/HHVM/hhvm-fb-github-fork/hphp/runtime/vm/jit/vasm-llvm.cpp: In constructor ‘HPHP::jit::{anonymous}::LLVMEmitter::LLVMEmitter(const HPHP::jit::Vunit&, HPHP::jit::Vasm::AreaList&)’:
/home/sathvikl/HHVM/hhvm-fb-github-fork/hphp/runtime/vm/jit/vasm-llvm.cpp:507:32: error: ‘X86_64_HHVM_TC’ is not a member of ‘llvm::CallingConv’
     m_function->setCallingConv(llvm::CallingConv::X86_64_HHVM_TC);
                                ^
/home/sathvikl/HHVM/hhvm-fb-github-fork/hphp/runtime/vm/jit/vasm-llvm.cpp: In member function ‘void HPHP::jit::{anonymous}::LLVMEmitter::emit(const HPHP::jit::bindjmp&)’:
/home/sathvikl/HHVM/hhvm-fb-github-fork/hphp/runtime/vm/jit/vasm-llvm.cpp:1595:9: error: ‘class llvm::CallInst’ has no member named ‘setSmashable’
   call->setSmashable();
         ^
/home/sathvikl/HHVM/hhvm-fb-github-fork/hphp/runtime/vm/jit/vasm-llvm.cpp:1599:21: error: ‘MD_locrec’ is not a member of ‘llvm::LLVMContext’
   call->setMetadata(llvm::LLVMContext::MD_locrec,
                     ^
/home/sathvikl/HHVM/hhvm-fb-github-fork/hphp/runtime/vm/jit/vasm-llvm.cpp: In member function ‘llvm::CallInst* HPHP::jit::{anonymous}::LLVMEmitter::emitTraceletTailCall(llvm::Value*)’:
/home/sathvikl/HHVM/hhvm-fb-github-fork/hphp/runtime/vm/jit/vasm-llvm.cpp:1667:24: error: ‘X86_64_HHVM_TC’ is not a member of ‘llvm::CallingConv’
   call->setCallingConv(llvm::CallingConv::X86_64_HHVM_TC);
                        ^
/home/sathvikl/HHVM/hhvm-fb-github-fork/hphp/runtime/vm/jit/vasm-llvm.cpp: In member function ‘void HPHP::jit::{anonymous}::LLVMEmitter::emitCall(const HPHP::jit::Vinstr&)’:
/home/sathvikl/HHVM/hhvm-fb-github-fork/hphp/runtime/vm/jit/vasm-llvm.cpp:1770:26: error: ‘X86_64_HHVM_C’ is not a member of ‘llvm::CallingConv’
     call->setCallingConv(llvm::CallingConv::X86_64_HHVM_C);
                          ^
/home/sathvikl/HHVM/hhvm-fb-github-fork/hphp/runtime/vm/jit/vasm-llvm.cpp:1776:28: error: ‘X86_64_HHVM_C’ is not a member of ‘llvm::CallingConv’
     invoke->setCallingConv(llvm::CallingConv::X86_64_HHVM_C);
                            ^
/home/sathvikl/HHVM/hhvm-fb-github-fork/hphp/runtime/vm/jit/vasm-llvm.cpp:1788:27: error: ‘MD_locrec’ is not a member of ‘llvm::LLVMContext’
     callInst->setMetadata(llvm::LLVMContext::MD_locrec,
                           ^
/home/sathvikl/HHVM/hhvm-fb-github-fork/hphp/runtime/vm/jit/vasm-llvm.cpp: In member function ‘void HPHP::jit::{anonymous}::LLVMEmitter::emit(const HPHP::jit::fallback&)’:
/home/sathvikl/HHVM/hhvm-fb-github-fork/hphp/runtime/vm/jit/vasm-llvm.cpp:1968:9: error: ‘class llvm::CallInst’ has no member named ‘setSmashable’
   call->setSmashable();
         ^
/home/sathvikl/HHVM/hhvm-fb-github-fork/hphp/runtime/vm/jit/vasm-llvm.cpp:1972:21: error: ‘MD_locrec’ is not a member of ‘llvm::LLVMContext’
   call->setMetadata(llvm::LLVMContext::MD_locrec,
                     ^
/home/sathvikl/HHVM/hhvm-fb-github-fork/hphp/runtime/vm/jit/vasm-llvm.cpp: In member function ‘void HPHP::jit::{anonymous}::LLVMEmitter::emit(const HPHP::jit::jmpi&)’:
/home/sathvikl/HHVM/hhvm-fb-github-fork/hphp/runtime/vm/jit/vasm-llvm.cpp:2193:24: error: ‘X86_64_HHVM_TC’ is not a member of ‘llvm::CallingConv’
   call->setCallingConv(llvm::CallingConv::X86_64_HHVM_TC);
                        ^
/home/sathvikl/HHVM/hhvm-fb-github-fork/hphp/runtime/vm/jit/vasm-llvm.cpp: In member function ‘void HPHP::jit::{anonymous}::LLVMEmitter::emit(const HPHP::jit::svcreq&)’:
/home/sathvikl/HHVM/hhvm-fb-github-fork/hphp/runtime/vm/jit/vasm-llvm.cpp:2599:24: error: ‘X86_64_HHVM_SR’ is not a member of ‘llvm::CallingConv’
   call->setCallingConv(llvm::CallingConv::X86_64_HHVM_SR);
                        ^
hphp/runtime/CMakeFiles/hphp_runtime_static.dir/build.make:8272: recipe for target 'hphp/runtime/CMakeFiles/hphp_runtime_static.dir/vm/jit/vasm-llvm.cpp.o' failed
make[2]: *** [hphp/runtime/CMakeFiles/hphp_runtime_static.dir/vm/jit/vasm-llvm.cpp.o] Error 1
CMakeFiles/Makefile2:1288: recipe for target 'hphp/runtime/CMakeFiles/hphp_runtime_static.dir/all' failed
make[1]: *** [hphp/runtime/CMakeFiles/hphp_runtime_static.dir/all] Error 2
Makefile:103: recipe for target 'all' failed
make: *** [all] Error 2

@swtaarrs , I think the calling convention enums such as X86_64_HHVM_TC.. are defined in  llvm/IR/CallingConv.h and  class llvm::CallInst seems to have been modified. 

Can you please help me with this.

**Comment by swtaarrs** [comment]
Unfortunately this is expected right now and unlikely to change within the next few months. The LLVM backend is still experimental, and it depends on a number of changes we've made to LLVM internally (this is why it's disabled in the GitHub build). When our internal changes to LLVM slow down and stabilize, we'll try to get everything upstreamed, but just getting it working is higher priority for now.

**Comment by sathvikl** [comment]
Hi Brett,

I am tyring to enable code layout segregration using LLVM as it's being done in HHVM custom code backend. Is it possible to get a fork of the current branch of LLVM you are using along with the internal changes. 

If there is anything I can help in getting HHVM to work with LLVM, I would be happy to pursue it. 
  
In the worst case If I can get llvm/IR/CallingConv.h and the files containing the associated declarations for MD_locrec and CallInst::setSmashable() I think I would be able to proceed.

**Comment by swtaarrs** [comment]
In case anyone else is watching this issue and didn't see the IRC conversations: we decided that until our changes to LLVM stabilize and make it upstream, we're going to keep a patch in `hphp/tools/llvm` that can be applied to trunk llvm, recreating what we have internally.

**Comment by sathvikl** [comment]
@maks_ @swtaarrs  
Can you please tell me which version of llvm was the diff performed against ? a commit hash ID or the git-svn-id would work if you are using the git repo. 
I am trying it with v3.5.2  and then I tried 3.6, 3.6 certainly does not work .. 

error: patch failed: include/llvm/IR/LLVMContext.h:54
error: include/llvm/IR/LLVMContext.h: patch does not apply
error: patch failed: lib/CodeGen/AsmPrinter/AsmPrinter.cpp:792
error: lib/CodeGen/AsmPrinter/AsmPrinter.cpp: patch does not apply
error: patch failed: lib/CodeGen/MachineFunction.cpp:75
error: lib/CodeGen/MachineFunction.cpp: patch does not apply
error: patch failed: lib/IR/LLVMContext.cpp:76
error: lib/IR/LLVMContext.cpp: patch does not apply
error: patch failed: lib/MC/MCObjectFileInfo.cpp:589
error: lib/MC/MCObjectFileInfo.cpp: patch does not apply
error: patch failed: lib/Target/X86/X86AsmPrinter.cpp:739
error: lib/Target/X86/X86AsmPrinter.cpp: patch does not apply
error: patch failed: lib/Target/X86/X86AsmPrinter.h:43
error: lib/Target/X86/X86AsmPrinter.h: patch does not apply
error: patch failed: lib/Target/X86/X86MCInstLower.cpp:65
error: lib/Target/X86/X86MCInstLower.cpp: patch does not apply
error: test/CodeGen/X86/patchpoint-webkit_jscc.ll: No such file or directory

**Comment by swtaarrs** [comment]
The README file in the directory with the patch has that information in it.

**Comment by sathvikl** [comment]
Thank you, I missed it while going through it..
