### ISSUE TITLE
Typechecker unaware of T_TYPE, T_NEWTYPE, T_TYPELIST_LT, T_TYPELIST_GT

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#4872]
```
hphpd> =token_name(403)
=token_name(403)
"T_TYPE"
hphpd> =token_name(405)
=token_name(405)
"T_NEWTYPE"
hphpd> =T_TYPE
=T_TYPE

Notice: Use of undefined constant T_TYPE - assumed 'T_TYPE'
"T_TYPE"
hphpd> =T_NEWTYPE
=T_NEWTYPE

Notice: Use of undefined constant T_NEWTYPE - assumed 'T_NEWTYPE'
"T_NEWTYPE"
```

**Comment by fredemmott** [comment]
(Version: 2015.02.20~trusty)

**Comment by fredemmott** [comment]
same for T_TYPELIST_LT (398), T_TYPELIST_GT(399)

**Comment by fredemmott** [comment]
These are intentionally excluded in test/slow/ext_misc/token_consistency.php -, along with T_AWAIT, T_ASYNC, T_SHAPE, and a load of XHP tokens :/

**Comment by fredemmott** [comment]
Most of the list in there seem suspect actually

**Comment by TJ09** [comment]
As of 3.7, these are now defined:

```
hphpd> =T_TYPELIST_LT
398
hphpd> =T_TYPE
403
```

However, hh_server is still unaware of them, so strict mode complains about undefined constants.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Support for anything having to do with tokens was removed in hhvm [4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html).
