### ISSUE TITLE
Collection and ImmCollection automatically imported into namespaces, but not ConstCollection?

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#4874]
ConstSet, ConstVector, ConstMap need to be explicitly referred to as \ConstSet, \ConstVector, \ConstMap.
- should they be auto-imported?
- shouldn't they be in the HH namespace instead, not root?

**Comment by simonwelsh** [comment]
Looks like this is fixed in 3.9

**Comment by JoelMarcey** [comment]
@fredemmott The whole collection interface specification is a bit screwy. `interface Collection` is in the `\HH\` namespace; most of the others are not, even things that implement `Collection`. It's weird.

**Comment by fredemmott** [comment]
Yep, it's also inconsistent between the HHI and systemlib.

**Comment by fredemmott** [comment]
If this was fixed, it's regressed - it can't be used in namespaced code as the HHI and systemlib disagree, as of 3.13-dev

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

ConstCollection and Collection are autoimported. ImmCollection appears to be completely removed.

```
hphpd> function root_imm(\ImmCollection $_): void {}
function root_imm(\ImmCollection $_): void {}
hphpd> function hh_imm(\HH\ImmCollection $_): void {}
function hh_imm(\HH\ImmCollection $_): void {}
hphpd> =root_imm(ImmVector{});
=root_imm(ImmVector{});
Hit a php exception : TypeError: Argument 1 passed to root_imm() must be an instance of ImmCollection, HH\ImmVector given in :1
Stack trace:
#0 (1): root_imm()
#1 (1): include()
#2 {main}
hphpd> =hh_imm(ImmVector{});
=hh_imm(ImmVector{});

Hit a php exception : TypeError: Argument 1 passed to hh_imm() must be an instance of HH\ImmCollection, HH\ImmVector given in :1
Stack trace:
#0 (1): hh_imm()
#1 (1): include()
#2 {main}
```
