### ISSUE TITLE
Fix copyright header in hhi

### ISSUE THREAD

**Issue by jwatzman** [facebook/hhvm#4876]
https://github.com/facebook/hhvm/blob/145512b64ccfdf4b850df562a79c6ca6ff2b64a5/hphp/hack/hhi/stdlib/builtins_asio_utils.hhi#L2 has the FB copyright, should be BSD.

Sorry to be pedantic, but Debian will (and has) rejected us for exactly this sort of pedantry.

**Comment by jwatzman** [comment]
If I remember and you don't beat me to it, I'll do this myself on Monday, but I don't want to forget.

**Comment by jwatzman** [comment]
Should probably make a pass thru all the hhi files while we're at it.

**Comment by fredemmott** [comment]
Off the grid for a week

**Comment by jwatzman** [comment]
Whoops, forgot about that. I'll deal with this.

**Comment by jwatzman** [comment]
https://reviews.facebook.net/D33993, landing shortly
