### ISSUE TITLE
Make Ctrl-Enter proceed through the tutorial

### ISSUE THREAD

**Issue by anka-213** [facebook/hhvm#4879]
It would make the [tutorial](http://hacklang.org/tutorial) easier to use if you could proceed through it with some kind of keyboard shortcut (e.g. Ctrl-Enter), instead of having to reach for the mouse after every step. Not a big thing, but it would be nice.

**Comment by paulbiss** [comment]
@JoelMarcey would this be easy to change?

**Comment by JoelMarcey** [comment]
Should work now. `ctrl-b` and `ctrl-n`
