### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by ViolentVotan** [facebook/hhvm#4883]
Hello,

I just did a checkout form the Master branch, 23.02.2015 09:30 GMT+1 and it fails when building:

```
[ 91%] Building CXX object libmysql/CMakeFiles/clientlib.dir/__/sql/net_serv.cc.o
In file included from /tmp/hhvm/third-party/webscalesqlclient/webscalesql-5.6/include/probes_mysql_dtrace.h:9:0,
                 from /tmp/hhvm/third-party/webscalesqlclient/webscalesql-5.6/include/probes_mysql.h:24,
                 from /tmp/hhvm/third-party/webscalesqlclient/webscalesql-5.6/sql/net_serv.cc:46:
/tmp/hhvm/third-party/webscalesqlclient/webscalesql-5.6/sql/net_serv.cc: In function ‘net_async_status net_write_command_nonblocking(NET*, uchar, const uchar*, size_t, const uchar*, size_t, my_bool*)’:
/tmp/hhvm/third-party/webscalesqlclient/webscalesql-5.6/sql/net_serv.cc:547:29: error: ‘len’ was not declared in this scope
       MYSQL_NET_WRITE_START(len);
                             ^
/tmp/hhvm/third-party/webscalesqlclient/webscalesql-5.6/sql/net_serv.cc:547:7: note: in expansion of macro ‘MYSQL_NET_WRITE_START’
       MYSQL_NET_WRITE_START(len);
       ^
/tmp/hhvm/third-party/webscalesqlclient/webscalesql-5.6/include/probes_mysql_dtrace.h:526:1: error: template argument 1 is invalid
 DTRACE_PROBE1(mysql,net__write__start,arg1)
 ^
/tmp/hhvm/third-party/webscalesqlclient/webscalesql-5.6/sql/net_serv.cc:547:7: note: in expansion of macro ‘MYSQL_NET_WRITE_START’
       MYSQL_NET_WRITE_START(len);
       ^
make[5]: *** [libmysql/CMakeFiles/clientlib.dir/__/sql/net_serv.cc.o] Error 1
make[4]: *** [libmysql/CMakeFiles/clientlib.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [third-party/webscalesqlclient/build/src/webscalesqlclient-stamp/webscalesqlclient-build] Error 2
make[1]: *** [third-party/webscalesqlclient/CMakeFiles/webscalesqlclient.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by yaslama** [comment]
IMHO, webscalesql submodule in third-party needs to be updated to https://github.com/webscalesql/webscalesql-5.6/commit/13e32199550b144252b07cbdba9c80e1ceeef7bf or better https://github.com/webscalesql/webscalesql-5.6/commit/3b23e80ac275f3c20729c78dd712085b9e6d0141

These commits fix the build

**Comment by paulbiss** [comment]
cc @fredemmott @sgolemon

**Comment by jwatzman** [comment]
Our nightly builds are succeeding, so curious what's going on here. What OS are you on?

@yaslama what you linked indicates this is some problem with building without dtrace? I don't think HHVM has any dtrace facilities, is this something specific to the way webscalesql configures itself?

**Comment by yaslama** [comment]
@jwatzman the build error occurs even without dtrace. The reason is that the variable len is unknown in the scope, so even if the macro expends to nothing, the compiler detects that the variable is not declared.
See https://github.com/webscalesql/webscalesql-5.6/issues/17 and https://reviews.facebook.net/D33777

**Comment by jwatzman** [comment]
Yeah but it doesn't always trigger -- do you know what has to happen to trigger this? The HHVM builds I've been doing from github are all still succeeding and have been for a while. Just don't want to blindly bump the submodule without confirming it fixes the issue here.

**Comment by yaslama** [comment]
@jwatzman  the problem is triggered in my laptop (debian sid) because the package called systemtap-sdt-dev is installed and contains /usr/bin/dtrace .Per https://github.com/webscalesql/webscalesql-5.6/blob/webscalesql-5.6.23/cmake/dtrace.cmake#L34 ENABLE_DTRACE is defined.
This causes third-party/webscalesqlclient/webscalesql-5.6/include/probes_mysql_dtrace.h to be included instead of third-party/webscalesqlclient/webscalesql-5.6/include/probes_mysql_nodtrace.h

**Comment by jwatzman** [comment]
Thanks for the info. I'll poke this in a few days if no one beats me to it (I'm super busy right now).

**Comment by ViolentVotan** [comment]
A new checkout from today yields similiar results>

[ 91%] Building CXX object libmysql/CMakeFiles/clientlib.dir/__/sql/net_serv.cc.o
In file included from /tmp/hhvm/third-party/webscalesqlclient/webscalesql-5.6/include/probes_mysql_dtrace.h:9:0,
                 from /tmp/hhvm/third-party/webscalesqlclient/webscalesql-5.6/include/probes_mysql.h:24,
                 from /tmp/hhvm/third-party/webscalesqlclient/webscalesql-5.6/sql/net_serv.cc:46:
/tmp/hhvm/third-party/webscalesqlclient/webscalesql-5.6/sql/net_serv.cc: In function ‘net_async_status net_write_command_nonblocking(NET*, uchar, const uchar*, size_t, const uchar*, size_t, my_bool*)’:
/tmp/hhvm/third-party/webscalesqlclient/webscalesql-5.6/sql/net_serv.cc:547:29: error: ‘len’ was not declared in this scope
       MYSQL_NET_WRITE_START(len);
                             ^
/tmp/hhvm/third-party/webscalesqlclient/webscalesql-5.6/sql/net_serv.cc:547:7: note: in expansion of macro ‘MYSQL_NET_WRITE_START’
       MYSQL_NET_WRITE_START(len);
       ^
/tmp/hhvm/third-party/webscalesqlclient/webscalesql-5.6/include/probes_mysql_dtrace.h:526:1: error: template argument 1 is invalid
 DTRACE_PROBE1(mysql,net__write__start,arg1)
 ^
/tmp/hhvm/third-party/webscalesqlclient/webscalesql-5.6/sql/net_serv.cc:547:7: note: in expansion of macro ‘MYSQL_NET_WRITE_START’
       MYSQL_NET_WRITE_START(len);
       ^
make[5]: *** [libmysql/CMakeFiles/clientlib.dir/__/sql/net_serv.cc.o] Error 1
make[4]: *** [libmysql/CMakeFiles/clientlib.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [third-party/webscalesqlclient/build/src/webscalesqlclient-stamp/webscalesqlclient-build] Error 2
make[1]: *** [third-party/webscalesqlclient/CMakeFiles/webscalesqlclient.dir/all] Error 2
make: *** [all] Error 2

**Comment by davidbitton** [comment]
HHVM is not compiling with the same failure as @ViolentVotan above on an AWS EC2 m3.medium with Fedora 21.

**Comment by davidbitton** [comment]
If you raw dog the changes made in this webscale [commit](https://github.com/webscalesql/webscalesql-5.6/commit/3b23e80ac275f3c20729c78dd712085b9e6d014), the build continues.

**Comment by uxbod** [comment]
Confirmed like @davidbitton that if you edit as per that commit latest pull builds fine.

**Comment by burner1024** [comment]
Which version has it made into?

**Comment by simonwelsh** [comment]
@burner1024 If you look at the commit, it lists the tags it's in. That one is in 3.7.0 and 3.7.1.

**Comment by burner1024** [comment]
@simonwelsh oh right. Thanks.
