### ISSUE TITLE
Missing FTP_* constants

### ISSUE THREAD

**Issue by guilhermeblanco** [facebook/hhvm#4887]
While attempting to use ftp_* functions, I found out that some FTP_* constants are not declared.
The ones I could spot are `FTP_ASCII` (equals to 1) and `FTP_BINARY` (equals to 2).

We should keep the constants in sync with available FTP library constants in PHP.
PR will be done tonight (my intent).

**Comment by paulbiss** [comment]
I believe you need to enable the PHP 5 computability layer for those constants to be defined, as that's where the ftp functions are currently defined, `hhvm.enable_zend_compat=true` is the ini option you want.

**Comment by guilhermeblanco** [comment]
@paulbiss I thought the compatibility layer was only used if you wanted to compile a PHP extension to be used with HHVM. That's what I could extract when I read this page: https://github.com/facebook/hhvm/blob/master/hphp/doc/php.extension.compat.layer

**Comment by paulbiss** [comment]
There are some extensions that are built with hhvm but still use the compat layer as no one has re-implemented them on top of the hhvm runtime, [ftp](https://github.com/facebook/hhvm/blob/master/hphp/runtime/ext_zend_compat/ftp/ext_ftp.php) is one such extension.

**Comment by paulbiss** [comment]
Looks like this was resolved but never closed.
