### ISSUE TITLE
++ on string starting with integer is non-compliant with PHP behavior

### ISSUE THREAD

**Issue by Ralt** [facebook/hhvm#4889]
```php
<?php

$foo = "100 apples";
echo ++$foo; // 101 on HHVM, "100 applet" on PHP
```

Proof: http://3v4l.org/8ZoSO

When doing `$foo = "apples"; echo ++$foo`, HHVM correctly returns `"applet"`. So it's a matter of precedence.

**Comment by sgolemon** [comment]
https://reviews.facebook.net/D34335
