### ISSUE TITLE
test/run --fbmake only writes to STDERR

### ISSUE THREAD

**Issue by rrh** [facebook/hhvm#4898]
It would be great if hphp/test/run would have some way to write its test result output to something other than STDERR, so that, for example, --fbmake could be plumbed to one named file which wouldn't be a vacuum on all of the other non-json glop that subprocesses might also be writing to STDERR

**Comment by fredemmott** [comment]
It might be better to add another option entirely

- fbmake requires STDERR usage
- the fbmake output format is considered FB-internal, and may change without warning as Facebook's test infrastructure (not HHVM-specific) develops

**Comment by fredemmott** [comment]
fbmake's JSON format also isn't exactly the most consistent and well-thought-out thing either, and there's bugs in the implementation that mean the JSON is a bit of a lie in some cases (especially for test start times).

TAP (https://testanything.org/) might be a good thing to implement.

**Comment by rrh** [comment]
Yeah, having it spit out TAP or Junit directly would be good.  For now, I have a ruby[cough cough] script that takes the --fbmake output and converts it to TAP sufficient for my needs.
