### ISSUE TITLE
Phar write support

### ISSUE THREAD

**Issue by nazar-pc** [facebook/hhvm#4899]
There is read support for Phar for quite a while, what about write support?
I'm currently running tests of my system on Travis CI for PHP 5.4-5.6, but I can't do that directly for HHVM because I need write support for that (system should be built into phar file, installed from it and only then rest of tests follow).

**Comment by nazar-pc** [comment]
Any chance to get this feature in near future?
Can't test my system of HHVM without Phar write support.

**Comment by photodude** [comment]
This is still an issue with hhvm 3.15.2 and with the nightly build 3.16.0-dev

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Hhvm does not support the phar extension anymore since hhvm [4.1.0](https://hhvm.com/blog/2019/04/09/hhvm-4.1.0.html).
