### ISSUE TITLE
Feature Suggestion: configurable error log header format and timestamps

### ISSUE THREAD

**Issue by raymondjplante** [facebook/hhvm#4904]
Hey, thanks for everyone working on HHVM!  I've got a small suggestion.

Right now your header function (https://github.com/facebook/hhvm/blob/master/hphp/util/logger.cpp)  that inserts into the error log hard-codes the format of the timestamp and other info.  This is the output:
    
       [Wed Feb 25 18:03:17 2015] [hphp] [6483:7f31f35ff700:4:000001] []

Ideally this format could be configurable in your `ini` settings file. 

Also, it would be great to be able to specify a timestamp format users could have HHVM logs could match whatever format they need--if they're using a log analysis tool for example expecting preset format.

If not possible at this time to make timestamp configurable, it would be useful to base the hardcoded timestamp format use to be closer to something like ISO 8601, at the very least include the UTC offset, to assist  aggregating logs across machines from timezones.  Something like  `2015-02-25 16:42:11 -0500`  or `2015-02-25T16:42:11-05:00`

**Comment by doliver3** [comment]
Yes, this would be really helpful.  So much useful information is missing as is usually available on other platforms. I'd like to be able to see the class name that logged the line as well.

**Comment by steelbrain** [comment]
:+1:

**Comment by Orvid** [comment]
To point at the specific line this is done, [logger.cpp:237](https://github.com/facebook/hhvm/blob/master/hphp/util/logger.cpp#L237) is where the primary format occurs.

**Comment by jwatzman** [comment]
Probably not something we'll have time to work on, but if done cleanly, I see no reason we wouldn't take a PR for this.

**Comment by paulbiss** [comment]
This feature request is not actively being worked on. We would happily consider a pull request implementing it. If you plan to work on this issue let us know in the comments and we will re-open the issue and assign it to you. If you feel strongly that this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
