### ISSUE TITLE
HHVM silently fails to start with a third-party ZEND extension

### ISSUE THREAD

**Issue by alex-mashin** [facebook/hhvm#4905]
I don't know whether it is an HHVM issue or it just insufficient documentation or I simply need community support.

There is a third-party Zend extension: MediaWiki's luasandbox. It is meant to be used with both PHP and HHVM and is reported to run under HHVM on WikiMedia projects.

Previously, I built, installed and used it successfully with php5-fpm.

However, it wouldn't work under HHVM (absent from get_loaded_extensions ()).

After building luasandbox, I can see world-readable file luasandbox.so in /usr/lib/x86_64-linux-gnu/hhvm/extensions/20150112; the extension_dir is /usr/lib/x86_64-linux-gnu/hhvm/extensions.

I have
hhvm.enable_zend_compat = true
extension=luasandbox.so
in my /etc/hhvm/php.ini.

There is nothing noteworthy in the logs.

I had the issue with both hhvm (3.5.1) and hhvm-nightly (3.4.0).

My OS is Ubuntu 14.04.

Perhaps, there are instructions on loading third-party extensions or a way to debug HHVM startup, which the community can point to. So far, there was no feedback from MediaWiki community.

**Comment by jrobeson** [comment]
hhvm's extension importing doesn't use the same as php's 

you need something like

hhvm.dynamic_extension_path = /path/to/hhvm/extensions
hhvm.dynamic_extensions[luasandbox] = luasandbox.so

**Comment by alex-mashin** [comment]
Thank you, it worked.

**Comment by alex-mashin** [comment]
The primary issue is that HHVM service fails to start silently: arter `sudo service hhvm restart` it doesn't listen to the port 9000 as `sudo netstat -tulpn` proves.

I have
    ; hhvm specific
    hhvm.log.use_log_file = true
    hhvm.log.file = /var/log/hhvm/error.log
    hhvm.log.level = Warning
    hhvm.log.always_log_unhandled_exceptions = true
    hhvm.log.runtime_error_reporting_level = 8191
but no errors are recorded in `/var/log/hhvm/error.log` (though when I remove luasandbox from php.ini and start `hhvm`, errors are logged there) on attempted service start, nor in `/var/log/syslog`.

**Comment by jrobeson** [comment]
fails to start silently isn't really relevant in this issue context. If extensions do work, then close this issue and open another one.

**Comment by alex-mashin** [comment]
This is exactly the problem—that when a third-party extension prevents hhvm service from starting, there is no trace in the logs.

Wherever the bug be, in the extension or HHVM Zend compability layer, there is no way to know it, because there are no information in the logs.

That is the problem for now—no information in the logs.

**Comment by alex-mashin** [comment]
As of 3.7.0, HHVM service prints the exception message, when it fails to start. So, I belive the bug may be closed.
