### ISSUE TITLE
popen is broken

### ISSUE THREAD

**Issue by weltling** [facebook/hhvm#4906]
======== /tmp/hhvm_chdir.php =======
```
<?php
 
$pwd = getcwd();
echo "in ".$pwd."\r\n";
chdir("/tmp/somedir");
echo "now in ".getcwd()."\r\n";
 
$r = popen("./bash_cmd", "r");
$s = fgets($r, 1024);
pclose($r);
 
var_dump($s);
?>
```
 
 
======== /tmp/somedir/bash_cmd =========
```
#!/bin/sh
 
echo $PWD
 
exit 0
```
 
 
 
=========== hhvm ================
``` 
hhvm hhvm_chdir.php
in /tmp
now in /tmp/somedir
sh: ./bash_cmd: No such file or directory
bool(false)
```
 
 
========== php ==================
```
php hhvm_chdir.php
in /tmp
now in /tmp/somedir
string(13) "/tmp/somedir
"
```

**Comment by paulbiss** [comment]
I think we just need to pass the optional cwd argument to the LightProcess [here](https://github.com/facebook/hhvm/blob/master/hphp/runtime/base/pipe.cpp#L39).
