### ISSUE TITLE
build error: small_vector.h:642:47: error: ‘malloc_usable_size’ was not declared in this scope

### ISSUE THREAD

**Issue by levixie** [facebook/hhvm#4908]
HI There
  I need to build the hhvm 3.5.1 myself, I got this error for malloc_usable_size not declared error. And I was able to build it. Do I need to change any configuration?
Thanks!
my system is ubuntu 12.01TLS:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=12.04
DISTRIB_CODENAME=precise
DISTRIB_DESCRIPTION="Ubuntu 12.04.3 LTS"
NAME="Ubuntu"
VERSION="12.04.3 LTS, Precise Pangolin"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu precise (12.04.3 LTS)"
VERSION_ID="12.04"

here is how run: ./package ubuntu precise 3.5.1

In file included from /tmp/tmp.2HWR9oy7AG/third-party/folly/folly/wangle/rx/Observable.h:26:0,
                 from /tmp/tmp.2HWR9oy7AG/third-party/folly/folly/wangle/concurrent/ThreadPoolExecutor.h:21,
                 from /tmp/tmp.2HWR9oy7AG/third-party/folly/folly/wangle/concurrent/ThreadPoolExecutor.cpp:17:
/tmp/tmp.2HWR9oy7AG/third-party/folly/folly/small_vector.h: In instantiation of ‘folly::small_vector<T, M, A, B, C>::size_type folly::small_vector<T, M, A, B, C>::capacity() const [with Value = folly::wangle::Observer<folly::wangle::ThreadPoolExecutor::TaskStats>*; long unsigned int RequestedMaxInline = 3ul; PolicyA = void; PolicyB = void; PolicyC = void; folly::small_vector<T, M, A, B, C>::size_type = long unsigned int]’:
/tmp/tmp.2HWR9oy7AG/third-party/folly/folly/small_vector.h:663:18:   required from ‘void folly::small_vector<T, M, A, B, C>::push_back(folly::small_vector<T, M, A, B, C>::value_type&&) [with Value = folly::wangle::Observer<folly::wangle::ThreadPoolExecutor::TaskStats>*; long unsigned int RequestedMaxInline = 3ul; PolicyA = void; PolicyB = void; PolicyC = void; folly::small_vector<T, M, A, B, C>::value_type = folly::wangle::Observer<folly::wangle::ThreadPoolExecutor::TaskStats>*]’
/tmp/tmp.2HWR9oy7AG/third-party/folly/folly/small_vector.h:674:28:   required from ‘void folly::small_vector<T, M, A, B, C>::push_back(const value_type&) [with Value = folly::wangle::Observer<folly::wangle::ThreadPoolExecutor::TaskStats>*; long unsigned int RequestedMaxInline = 3ul; PolicyA = void; PolicyB = void; PolicyC = void; folly::small_vector<T, M, A, B, C>::value_type = folly::wangle::Observer<folly::wangle::ThreadPoolExecutor::TaskStats>*]’
/tmp/tmp.2HWR9oy7AG/third-party/folly/folly/wangle/rx/Observable.h:171:13:   required from ‘void folly::wangle::Observable<T, InlineObservers>::forEachObserver(F) [with F = folly::wangle::Subject<T>::onNext(const T&) [with T = folly::wangle::ThreadPoolExecutor::TaskStats]::__lambda2; T = folly::wangle::ThreadPoolExecutor::TaskStats; long unsigned int InlineObservers = 3ul]’
/tmp/tmp.2HWR9oy7AG/third-party/folly/folly/wangle/rx/Subject.h:30:5:   required from ‘void folly::wangle::Subject<T>::onNext(const T&) [with T = folly::wangle::ThreadPoolExecutor::TaskStats]’
/tmp/tmp.2HWR9oy7AG/third-party/folly/folly/wangle/concurrent/ThreadPoolExecutor.cpp:67:58:   required from here
/tmp/tmp.2HWR9oy7AG/third-party/folly/folly/small_vector.h:642:47: error: ‘malloc_usable_size’ was not declared in this scope
       return malloc_usable_size(u.pdata_.heap_) / sizeof(value_type);
                                               ^
make[2]: *** [third-party/folly/CMakeFiles/folly.dir/folly/wangle/concurrent/ThreadPoolExecutor.cpp.o] Error 1
make[1]: *** [third-party/folly/CMakeFiles/folly.dir/all] Error 2
make: *** [all] Error 2

**Comment by danslo** [comment]
Ran into this as well on Ubuntu 14.10. The solution is to ``#include <jemalloc/jemalloc.h>`` in small_vector.h.

**Comment by glensc** [comment]
i'm getting also this, i build 3.6.1 with:

```
cmake \
    -DUSE_JEMALLOC=OFF \
    -DUSE_TCMALLOC=OFF \
```

**Comment by glensc** [comment]
for me applying this patch helped: 1b6b1a5e311df5e2b57f580657666be7778def54

**Comment by lokeshhctm** [comment]
seeing this error again in master code while compilation.

**Comment by Orvid** [comment]
This was fixed.
