### ISSUE TITLE
Redis driver doesn't allow saving null value with setex

### ISSUE THREAD

**Issue by kamermans** [facebook/hhvm#4910]
In PHP you can save a `null` value via `Redis::setex()`, but in HHVM you cannot.

Example:

```
<?php
$cache = new Redis();
$cache->connect("127.0.0.1");

$id = "foo";
$lifetime = 3600;
$data = null;

$cache->setex($id, $lifetime, $data);

echo "Key $id: ".var_export($cache->get($id), true)."\n";
```

Run in PHP 5.5 (notice the `null` came back as an empty string):
```
# php /tmp/hhvm_bug.php
Key foo: ''
```

Run in HHVM 3.5.1 (HHVM-3.5.1-0-gb723e67c88bc008676687a04dff00db1faf250b3):
```
# hhvm /tmp/hhvm_bug.php
Fatal error: Redis::setex requires at least 3 parameters 3 given in /tmp/hhvm_bug.php on line 10
```

The unfortunate wording of the error message took me a while to understand :)

It seems like the solution here is to make the third argument (`data`) optional with a default value of an empty string.

**Comment by Stelian** [comment]
Looking into this.

**Comment by SiebelsTim** [comment]
duplicate #6062

**Comment by JoelMarcey** [comment]
Closing https://github.com/facebook/hhvm/commit/34de1a279b3b66458ff980d12ef347022f2def04
