### ISSUE TITLE
hhvm issues with nginx

### ISSUE THREAD

**Issue by digra5319** [facebook/hhvm#4913]
Phpunit tests will pass on hhvm but when running the application in a browser I will receive a 502 Bad Gateway nginx/1.6.2 after sending an ajax request and will need to restart hhvm. After restarting hhvm the data from the post request is there. Are there specific settings hhvm must be on when using nginx?

**Comment by digra5319** [comment]
This is the hhvm/error.log

cap_set_proc failed
Finished singleJitRequest 1
Finished singleJitRequest 2
Finished singleJitRequest 3
Finished singleJitRequest 4
Finished singleJitRequest 5

**Comment by paulbiss** [comment]
Have you looked at the instructions [here](https://github.com/facebook/hhvm/wiki/FastCGI#running-the-server)? The singleJitRequest messages are standard warmup messages indicating that you did in fact receive requests. The cap_set_proc message is probably related to failing to setuid to another user, though it's hard to say for sure.

It would also help to know what version of HHVM you're running, and what you have in your config files for hhvm and nginx.

**Comment by digra5319** [comment]
HHVM version 3.5

nginx.config:

error_log  /var/log/nginx/error.log;
#error_log  /var/log/nginx/error.log  notice;
#error_log  /var/log/nginx/error.log  info;

pid        /var/run/nginx.pid;


events {
    worker_connections  2048;
    multi_accept on;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;
    #
    # sendfile off;
    # types_hash_max_size 2048;
    # server_tokens off;

    #client_body_buffer_size 1m;
    #client_body_timeout 12;
    #client_header_timeout 12;
    #keepalive_timeout 15;
    #send_timeout 10;
    client_max_body_size 100M;

    proxy_connect_timeout  600s;
    proxy_send_timeout  600s;
    proxy_read_timeout  600s;
    fastcgi_send_timeout 600s;
    fastcgi_read_timeout 600s;

    #fastcgi_buffers 8 16k;
    #fastcgi_buffer_size 32k;

    gzip             on;
    gzip_comp_level  2;
    gzip_min_length  1000;
    gzip_proxied     expired no-cache no-store private auth;
    gzip_types       text/plain application/x-javascript text/xml text/css application/xml;

    # Load modular configuration files from the /etc/nginx/conf.d directory.
    # See http://nginx.org/en/docs/ngx_core_module.html#include
    # for more information.
    include /etc/nginx/conf.d/*.conf;

    index  index.php index.html index.htm ;
    server {
        listen 80;
        server_name 172.17.8.101 192.168.254.96;
        #access_log logs/leonardo.access.log;
        root /var/www/leonardo/public;

        try_files $uri $uri/ /index.php$uri /index.php?$args;

        location / {
        #    index  index.html index.htm index.php $uri;
        }

        location ~* \.(jpg|jpeg|gif|png|html|css|zip|tgz|gz|rar|doc|xls|pdf|ppt|tar|wav|bmp|rtf|swf|flv|txt|xm
l|docx|xlsx|js)$ {
            try_files $uri $uri/ /index.php$uri =404;
            access_log off;
            expires 30d;
        }

        # unless the request is for a valid file (image, js, css, etc.), send to bootstrap
        if (!-e $request_filename)
        {
            rewrite ^/(.*)$ /index.php?/$1 last;
            break;
        }
        location ~ \.(hh|php)$ {
           fastcgi_pass 127.0.0.1:9000;
           fastcgi_index  index.php;
           fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
           fastcgi_param   PATH_INFO               $fastcgi_path_info;
           include        fastcgi_params;
        }
    }

**Comment by digra5319** [comment]
PHP.INI

; php options
;
session.save_handler = files
session.save_path = /var/lib/php5
session.gc_maxlifetime = 1440
; hhvm specific
hhvm.server.port=9000
hhvm.server.type= fastcgi
hhvm.server.source_root=/var/www/leonardo/public
hhvm.server.default_document = index.php
hhvm.log.level = Warning
hhvm.log.always_log_unhandled_exceptions = true
hhvm.log.runtime_error_reporting_level = 8191
hhvm.mysql.typed_results = false
; Xdebug options
xdebug.enable=1
xdebug.remote_enable=1
xdebug.idekey="xyz"
xdebug.remote_host="localhost"
xdebug.remote_port=9000
hhvm.libxml.ext_entity_whitelist = file,http

....

SERVER.INI

; php options

pid = /var/run/hhvm/pid

; hhvm specific

hhvm.server.port = 9001
hhvm.server.type = fastcgi
hhvm.server.default_document = index.php
hhvm.log.use_log_file = true
hhvm.log.file = /var/log/hhvm/error.log
hhvm.repo.central.path = /var/run/hhvm/hhvm.hhbc
hhvm.libxml.ext_entity_whitelist = file,http

**Comment by paulbiss** [comment]
I'm not seeing anything obvious. I'll give it a closer look, but is there a reason you set the port to 9000 in php.ini and 9001 and server.ini?

**Comment by digra5319** [comment]
No reason, I switched it back to 9000 and it did not seem to make a difference.

**Comment by digra5319** [comment]
I found the root of the problem. 

There was an error in a piece of my html markup which gets modified by PhpQuery. Once it tired to modify the bad html it would crash the application. This should probably throw an exception instead of a complete crash.

**Comment by digra5319** [comment]
I found the root of the issue.

There was an error in a piece of my html markup which gets modified by PhpQuery library. Once it tired to modify the bad html it would crash the application.

--

BAD HTML - bolded area was the problem : (duplicate <span>)

<h1><span class="doctor_firstname templateKey">{doctor_firstname}</span> <span class="initial templateKey">{initial}</span> <span class="doctor_lastname templateKey"><span class="doctor_lastname templateKey">{doctor_lastname}</span>,</span><span class="doctor_suffix templateKey">{doctor_suffix}</span> <span class="doctor_title templateKey">{doctor_title}</span></h1>

<p><img class="doctor_biopic picLeft" src="[[doctor_biopic]]" alt=""><div class="biography templateKey">{biography}</div></p>

<h2>Education</h2>
<p><div class="medschool templateKey">{medschool}</div></p>

<h2>Board Certification(s)</h2>
<p><div class="board_certificates templateKey">{board_certificates}</div></p>

<h2>Hospital Affiliations</h2>
<p><div class="residency templateKey">{residency}</div></p>

<h2>Professional Memberships, Awards</h2>
<p><span class="doctor_prefix templateKey">{doctor_prefix}</span> <span class="doctor_lastname templateKey">{doctor_lastname}</span> is a member of the following professional organizations:</p>
<p><div class="organizations templateKey">{organizations}</div></p>

--

This line of code is inside a loop to modify the html based on the classname :
pq( $elementClass, $this->doc )->text( $value );

example variable values:
$elementClass = {doctor_lastname}
$value = Doe

--

PhpQuery function where the application would crash : 

public function _empty() {
     foreach($this->stack(1) as $node) {
          // thx to 'dave at dgx dot cz'
          $node->nodeValue = '';
     }
     return $this;
}

Once the function hit the bad $node value which looks like this ---> '{doctor_lastname},’ it would crash.

--
The fix was deleting the duplicate <span> tag

**Comment by paulbiss** [comment]
Thanks for the update!
