### ISSUE TITLE
Segmentation Fault while throwing a custom Exception

### ISSUE THREAD

**Issue by navarr** [facebook/hhvm#4914]
I'm having trouble figuring out what exactly is causing this, but I'm getting this segmentation fault when trying to throw an Exception.

    .hhvm: /tmp/tmp.uQ4AAm53Qc/hphp/runtime/vm/func-inl.h:73: void HPHP::Func::validate() const: Assertion `this && m_magic == kMagic' failed.

I can recreate this with the code:

    $c = @socket_create(9001,9001,9001);
    throw new \Navarr\Socket\Exception\SocketException();

where \Navarr\Socket\Exception\SocketException is defined as https://github.com/navarr/Sockets/blob/master/src/Exception/SocketException.php

The old fashioned method of inserting echo statements into SocketException's constructor to see where things go wrong isn't working (it appears to fail at throwing it)

I'm triggering this by running my automated tests for my library: https://github.com/navarr/Sockets/blob/master/tests/SocketTest.php#L29

**Comment by paulbiss** [comment]
Can you give us a complete backtrace from the crash (a stacktrace file should have been created in your tmp directory). I see you're already running a debug build, is it from the nightly?

**Comment by navarr** [comment]
I'm not running nightly.  I did the good ol' apt-get install hhvm-dbg on Ubuntu 14.04.

Here is the dump:

	Host: ubuntu
	ProcessID: 17802
	ThreadID: 7f775edb6c80
	ThreadPID: 17802
	Name: /usr/bin/hhvm
	Type: Aborted
	Runtime: hhvm
	Version: tags/HHVM-3.5.1-0-gb723e67c88bc008676687a04dff00db1faf250b3
	DebuggerCount: 0

	Arguments: vendor/bin/phpunit
	ThreadType: CLI

	# 0  ?? at hhvm:0
	# 1  gsignal at /lib/x86_64-linux-gnu/libc.so.6:0
	# 2  abort at /lib/x86_64-linux-gnu/libc.so.6:0
	# 3  uselocale at /lib/x86_64-linux-gnu/libc.so.6:0
	# 4  __assert_fail at /lib/x86_64-linux-gnu/libc.so.6:0
	# 5  ?? at hhvm:0
	# 6  HPHP::jit::FixupMap::fixupWork(HPHP::ExecutionContext*, HPHP::ActRec*) const at hhvm:0
	# 7  HPHP::jit::FixupMap::fixup(HPHP::ExecutionContext*) const at hhvm:0
	# 8  HPHP::jit::MCGenerator::syncWork() at hhvm:0
	# 9  HPHP::VMRegAnchor::VMRegAnchor() at hhvm:0
	# 10 HPHP::createBacktrace(HPHP::BacktraceArgs const&) at hhvm:0
	# 11 HPHP::debug_string_backtrace(bool, bool, long) at hhvm:0
	# 12 ?? at hhvm:0
	# 13 __dynamic_cast at /usr/lib/x86_64-linux-gnu/libstdc++.so.6:0
	# 14 HPHP::f_socket_last_error(HPHP::Resource const&) at hhvm:0
	# 15 HPHP::Native::callFuncInt64Impl(HPHP::TypedValue* (*)(HPHP::ActRec*), long*, int, double*, int) at hhvm:0
	# 16 void HPHP::Native::callFunc<false, false>(HPHP::Func const*, void*, HPHP::TypedValue*, HPHP::TypedValue&) at hhvm:0
	# 17 HPHP::TypedValue* HPHP::Native::functionWrapper<false, false>(HPHP::ActRec*) at hhvm:0
	# 18 HPHP::jit::x64::BackEnd::enterTCHelper(unsigned char*, HPHP::jit::TReqInfo&) at hhvm:0
	# 19 HPHP::jit::MCGenerator::enterTC(unsigned char*, void*) at hhvm:0
	# 20 HPHP::jit::MCGenerator::enterTCAfterPrologue(unsigned char*) at hhvm:0
	# 21 HPHP::ExecutionContext::enterVMAtFunc(HPHP::ActRec*, HPHP::ExecutionContext::StackArgsState) at hhvm:0
	# 22 HPHP::ExecutionContext::enterVM(HPHP::ActRec*, HPHP::ExecutionContext::StackArgsState, HPHP::Resumable*, HPHP::ObjectData*) at hhvm:0
	# 23 HPHP::ExecutionContext::invokeFunc(HPHP::TypedValue*, HPHP::Func const*, HPHP::Variant const&, HPHP::ObjectData*, HPHP::Class*, HPHP::VarEnv*, HPHP::StringData*, HPHP::ExecutionContext::InvokeFlags) at hhvm:0
	# 24 HPHP::ObjectData::o_invoke(HPHP::String const&, HPHP::Variant const&, bool) at hhvm:0
	# 25 HPHP::f_hphp_invoke_method(HPHP::Variant const&, HPHP::String const&, HPHP::String const&, HPHP::Variant const&) at hhvm:0
	# 26 HPHP::jit::x64::BackEnd::enterTCHelper(unsigned char*, HPHP::jit::TReqInfo&) at hhvm:0
	# 27 HPHP::jit::MCGenerator::enterTC(unsigned char*, void*) at hhvm:0
	# 28 HPHP::jit::MCGenerator::enterTCAfterPrologue(unsigned char*) at hhvm:0
	# 29 HPHP::ExecutionContext::enterVMAtFunc(HPHP::ActRec*, HPHP::ExecutionContext::StackArgsState) at hhvm:0
	# 30 HPHP::ExecutionContext::enterVM(HPHP::ActRec*, HPHP::ExecutionContext::StackArgsState, HPHP::Resumable*, HPHP::ObjectData*) at hhvm:0
	# 31 HPHP::ExecutionContext::invokeFunc(HPHP::TypedValue*, HPHP::Func const*, HPHP::Variant const&, HPHP::ObjectData*, HPHP::Class*, HPHP::VarEnv*, HPHP::StringData*, HPHP::ExecutionContext::InvokeFlags) at hhvm:0
	# 32 HPHP::ExecutionContext::invokeUnit(HPHP::TypedValue*, HPHP::Unit const*) at hhvm:0
	# 33 ?? at hhvm:0
	# 34 ?? at hhvm:0
	# 35 HPHP::include_impl_invoke(HPHP::String const&, bool, char const*) at hhvm:0
	# 36 HPHP::hphp_invoke(HPHP::ExecutionContext*, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, HPHP::Array const&, HPHP::VRefParamValue const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool&, std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, bool, bool, bool) at hhvm:0
	# 37 HPHP::hphp_invoke_simple(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) at hhvm:0
	# 38 ?? at hhvm:0
	# 39 HPHP::execute_program(int, char**) at hhvm:0
	# 40 main at hhvm:0
	# 41 __libc_start_main at /lib/x86_64-linux-gnu/libc.so.6:0
	# 42 ?? at hhvm:0

**Comment by paulbiss** [comment]
Looks like a call to `socket_last_error` in the constructor for the exception is causing a crash, and the subsequent attempt to generate data about the crash using debug backtrace is also failing.

**Comment by navarr** [comment]
Just finished installing Nightly - doesn't seem to be an error there.
