### ISSUE TITLE
Allow "this" as a function type hint argument

### ISSUE THREAD

**Issue by milesj** [facebook/hhvm#4918]
I'm attempting to write a class level cache method that passes the current "this" instance as an argument to the callable, so that any functionality on the current class can be used. Here's a quick example.

``` hack
class Foo {
    public function cache(string $key, (function(this): mixed) $callback): mixed {
        if ($this->hasCache($key)) {
            return $this->getCache($key);
        }

        return $this->setCache($key, $callback($this));
    }

    public function doSomething(): string {
        return (string) $this->cache('cacheKey', ($self) ==> {
            return ''; // Do something expensive
        });
    }
}
```

I'm type hinting the callable as `(function(this): mixed)`, which works and the code executes correctly, but fails the type checker. 

```
The type "this" can only be used as a return type, to instantiate a covariant type variable, or as a private non-static member variable (Naming[2043])
```

This seems like a legitimate use case for using "this" as a type hint, but correct me if I am wrong.

**Comment by WizKid** [comment]
Not that it answer your question but `<<__Memoize>>` does very similar stuff to what you are building. http://docs.hhvm.com/manual/en/hack.attributes.memoize.php

**Comment by milesj** [comment]
Yeah. This is mainly for situations that fall outside of `<<__Memoize>>`s limitations.

**Comment by int3** [comment]
Yes, our variance checks are somewhat wonky at the moment. That's a legitimate use case.

**Comment by acrylic-origami** [comment]
I've noticed `this` works in function type annotations... sometimes. As well as in other places (like type constraints)! [I tested its variance behaviours](http://stackoverflow.com/questions/37626416/hacklang-where-can-and-cant-the-this-type-be-used), and it seems that some work has been done on `this` since last February? It's a really interesting type, and its existing uses are awesome to work with -- hoping there's a future for it.

**Comment by paulbiss** [comment]
@andrewjkennedy this looks like something you might be interested in.

**Comment by andrewjkennedy** [comment]
Yes! Function types are currently covariant in return type and invariant in parameter type. So `(function(mixed):string)` is convertible to `(function(mixed):mixed)`, but not convertible to `(function(string):mixed)`.

I have a change ready to make functions contravariant in parameter types, which would support this, and I believe would also support the behaviour that you're seeking. But we have some outstanding bugs in the area of contravariance so I'm waiting until these are addressed before pushing this one.

Thanks for the interesting use case, by the way!

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

`this` is now allowed in the position you showed. The following code typechecks.

```HACK
class Foo {
  public function cache((function(this): mixed) $callback): void {
    $callback($this);
  }
}
```
