### ISSUE TITLE
Variable number of arguments for function type hints

### ISSUE THREAD

**Issue by milesj** [facebook/hhvm#4919]
It would be nice to declare function type hints to support a variable number of arguments. Something like.

```hack
type Callback = (function(...): mixed);
function register(Callback $callable): void {}

register(() ==> {});
register(($foo) ==> {});
register(($foo, $bar) ==> {});
```

This currently doesn't work as it throws one of the following type checker errors.

* Invalid argument (Typing[4039]) - Number of arguments doesn't match
* Invalid argument (Typing[4041]) - Too many mandatory arguments

**Comment by int3** [comment]
I don't think we'd want to support this; there'd be no way for Hack to prove that `register` is using `$callable` safely. `register2()`, `register3()`, etc might be your best bet.

**Comment by milesj** [comment]
Yeah, I figured that was the issue. I'll have to think of a way around this, thanks.

**Comment by milesj** [comment]
Is there a non-type safe way to make this work? Like assuming that all arguments are `mixed` or a `T`?

**Comment by fredemmott** [comment]
An alternative design would be for your listeners to take a 'Message' object or similar, or a Vector of arguments.

**Comment by milesj** [comment]
I actually ended up passing the arguments through the `Event` object. However, I still believe that this feature would be useful. For example, micro frameworks and routing.

```hack
$app->get('/user/{id}', ($id) ==> {});
$app->get('/blog/{year}/{month}/{day}', ($year, $month, $day) ==> {});
// etc
```

Just would be nice to assume that all arguments are mixed.

**Comment by fredemmott** [comment]
That design is unsafe; supporting it just seems like it would just be hiding that fact.

**Comment by milesj** [comment]
Using my example above, I tried using variadic arguments, but it still errors...

```hack
type Callback = (function(...): mixed);
function register(Callback $callable): void {}

register((...$args) ==> {});
```

What does `...` in the type alias mean then?

**Comment by fredemmott** [comment]
varargs are supported, but coercing non-varargs functions to varargs isn't and won't be
