### ISSUE TITLE
FBIDE release?

### ISSUE THREAD

**Issue by garex** [facebook/hhvm#4920]
Hi dear FB people!

Summer 14' already gone, but we still not hear anything about FBIDE.

Currently one stopper for moving to hacklang is that there are no so many plugins for popular *free* IDEs like eclipse/netbeans/... I mean not editors, but IDEs with normal code completion and code navigation.

ps: Atom not yet IDE in this sense, but they are working hard to implement there adequate code completion.

**Comment by steelbrain** [comment]
__Note:__ To get the code completion on Atom, You need to install `autocomplete-plus` as well.

**Comment by garex** [comment]
@steelbrain, I tried it already. It's anyway not context-oriented. For example for class it shows me not it's and it's parent methods, but all methods in a whole world.

**Comment by steelbrain** [comment]
Well, It uses `hh_client` to get the auto-completions and that's an hhvm executable.
So it only works on Hack Files, But I think there's an open issue for typechecker php support.
![screenshot from 2015-02-28 03 09 22](https://cloud.githubusercontent.com/assets/4278113/6425987/6a2a4f0c-bef7-11e4-92f4-9fd359a0428f.png)
![screenshot from 2015-02-28 03 10 08](https://cloud.githubusercontent.com/assets/4278113/6425988/6a2abe9c-bef7-11e4-877a-00676094bbb1.png)
As you can see the results are scope-based in both screenshots.

**Comment by garex** [comment]
It's a good news, but we need good old PHP also :(

**Comment by steelbrain** [comment]
#4806 is the issue BTW.

**Comment by garex** [comment]
@steelbrain anyway I want to try this http://youtu.be/UCR4Ac6z_l0?t=4m39s

**Comment by steelbrain** [comment]
@garex Even if they release FBIDE, It won't support PHP until that issue is resolved.

**Comment by garex** [comment]
@steelbrain May be those issue is a blocker for release? :)

**Comment by steelbrain** [comment]
That issue was opened about 19 days ago, so In my humble opinion, It's not the one responsible for delay in release.

**Comment by garex** [comment]
Anyway we should wish to both FB people and Atom people extra-luck to finish such a nice works for the world.

**Comment by jwatzman** [comment]
IDE work is still ongoing internally. Things have just been taking a lot longer than expected, but it's still being worked on, and continuing to get closer. Sorry it's taken so so much longer than we expected :(

I'm going to close this issue since there's not really anything here to track.

**Comment by garex** [comment]
@jwatzman yeah, we know what it is ))
Anyway, can you ... I know, that we are hate this -- giving prognoses, but!
Can you esti... sorry, just say, when do you think it could be theoretically released? In this year, or in next? In this half of the year or next?

**Comment by jwatzman** [comment]
I really can't say any more, given that I'm not on the team and wouldn't presume to speak for them about timelines, and given that the last that estimations about FBIDE were so far off. But there *is* very real progress, in the "I can personally see progress being made" sense (as opposed to "some far-off team claims things are going on"). Sorry I can't be more specific.

**Comment by garex** [comment]
@jwatzman Can you invite here somebody from fbide team?

**Comment by jamesgpearce** [comment]
I'm not from the fbide team, but I can tell you we'll have something good to tell you very soon. Aaaand... we think it will be worth waiting for :)

**Comment by garex** [comment]
@jamesgpearce Soon by Earth time or by Saturnian? :))  What do you think about releasing FBIDE on 23 March?

**Comment by jamesgpearce** [comment]
What's happening on the 23rd? :)

**Comment by garex** [comment]
@jamesgpearce The release of the FBIDE?! Anyway say there we are waiting to try it.

**Comment by SiebelsTim** [comment]
Let's bump this issue with [Nuclide](https://www.facebook.com/groups/nuclide/)

https://www.youtube.com/watch?v=X0VH78ye4yY&list=PLb0IAmt7-GS1_7FcSupSJoUe21tF12eu8&t=795

**Comment by jwatzman** [comment]
:)
