### ISSUE TITLE
re-entrant http calls (over fastcgi) hang hhvm until the client times out

### ISSUE THREAD

**Issue by ibrezac** [facebook/hhvm#4921]
The following code hangs hhvm:

**prog.php:**
<?php echo file_get_contents("http://{$_SERVER['HTTP_HOST']}/prog1.php");

**prog1.php:**
<?php echo file_get_contents("http://{$_SERVER['HTTP_HOST']}/prog2.php");

**prog2.php:**
<?php echo 'Hello';

curl http://localhost/prog.php hangs hhvm until curl times out.  I use a very basic nginx/fastcgi hhvm (latest nightly build) configuration.  The same scenario works using fpm.

**Comment by simonwelsh** [comment]
If you've only got 1 core, this is expected (as HHVM defaults to only running 2*|cores| requests simultaneously). You could set `hhvm.server.thread_count = 5` to change the amount of threads handling requests.
