### ISSUE TITLE
Gettext support missing - hhvm 3.5 / 3.6-dev

### ISSUE THREAD

**Issue by OskHa** [facebook/hhvm#4923]
Hello, i can't get get text working.
(Debian wheezy, Nginx, HHVM fcgi)

**Zend Extensions are enabled.**
`hhvm.enable_zend_compat = true`

**Gettext is installed**
`apt-get install gettext`

I do compared my code to http://docs.hhvm.com/manual/en/function.gettext.php

On PHP 5.x - 5.6 everything is working fine.

Any ideas?

**Comment by SiebelsTim** [comment]
Hi,

what is the error message you get? Function not defined? 

Make sure to pass the config file to your hhvm instance with the `-c` option.

**Comment by OskHa** [comment]
Hi @SiebelsTim, maybe that newbie but how do i pass config file ?

I know that only from centos. I have installed hhvm via APT and only change the php.ini.

**Comment by OskHa** [comment]
Hi @SiebelsTim. It was something completely different!

HHVM works like a charm. It is debian config problem,

Solution here: http://stackoverflow.com/a/10610683
