### ISSUE TITLE
 hphp/test/slow/array_for_each/479.php , 480.php expects different results to PHP5

### ISSUE THREAD

**Issue by psmarshall** [facebook/hhvm#4925]
hphp/test/slow/array_for_each/479.php and  hphp/test/slow/array_for_each/480.php both expect:

    key=0 val=0
    key=a val=1
    key=b val=3

however, php5 (PHP 5.5.22 (cli) (built: Feb 26 2015 13:41:27) ) gives:

    key=0 val=0
    key=a val=1
    key=0 val=0
    key=a val=1
    key=b val=3

HHVM (HipHop VM 3.6.0-dev (rel)
Compiler: heads/master-0-gf40e5dbb65c1f9d7bf46fd8f29abcbddd0813481
Repo schema: 7b1edeaa708e2696830f813b1cd5a84db6cde661 ) agrees with the .expect files and the tests pass - are the test cases meant to match PHP5?

**Comment by paulbiss** [comment]
This looks like an instance of this [inconsistency](https://github.com/facebook/hhvm/blob/master/hphp/doc/inconsistencies#L29-L35).

**Comment by SiebelsTim** [comment]
@paulbiss But we aren't supposed to have test for this, are we?

**Comment by paulbiss** [comment]
@SiebelsTim I'm not sure I see the problem with having this test, generally if something is in the inconsistencies document we don't plan to fix it, and even if it's inconsistent with PHP 5, it's nice to have test coverage so we know it isn't completely broken or inconsistent between our own releases unintentionally.

**Comment by psmarshall** [comment]
@paulbiss I came across this because I was trying out some different copy on write behaviour that didn't rely on refcounts and inadvertently fixed the inconsistency (so far as this test case knows, anyway)  - so in that way it was useful for the test to specify the expected behaviour. Question is, on that branch would I then change the test cases and update the documentation to indicate that the inconsistency is resolved, or should I try to replicate the inconsistency...

**Comment by paulbiss** [comment]
@psmarshall I'm not entirely sure I follow your question, but if you want to change the COW behavior then you should update the test at the same time. If you're sure your changes make us consistent you can remove the section too; otherwise you should update it to explain how the new COW may differ.

**Comment by SiebelsTim** [comment]
@paulbiss My thoughts were that if someone changes the behaviour he'll see bad tests and has to resolve them. Especially tests aginst "unpredictedable" behaviour are somewhat contradictory. I don't feel strongly about this though.
