### ISSUE TITLE
Is it possible to hide sources under HHVM?

### ISSUE THREAD

**Issue by garex** [facebook/hhvm#4929]
Under pure PHP we can use something like ioncube/else with obfuscation. Under pre-HHVM we can use already compiled code without sources. But under current HHVM can we somehow hide our sources?

**Comment by paulbiss** [comment]
You could compile a bytecode repository and run that, but it's not something that would be difficult to reverse engineer.

**Comment by garex** [comment]
@paulbiss Can you show some RTFM about it? 

Also what about good-old obfuscation?

**Comment by paulbiss** [comment]
There isn't any great documentation on building repos. The wrapper script in `tools/hhvm_wrapper.php` has some useful shortcuts, you can look at the help options. There really isn't a great option for obfuscation, but repo-authoritative is probably your best bet as it will do some optimizations on top of the bytecode.

**Comment by garex** [comment]
@paulbiss tnx. I will try to play with it.

**Comment by WizKid** [comment]
I would also suggest that you search old issues because this question been asked several times before

**Comment by garex** [comment]
For those who will come here from google see *howto* with gist at SO: http://stackoverflow.com/a/28815472/388929
