### ISSUE TITLE
Mapping between PHP named variables and HHBC numLocals

### ISSUE THREAD

**Issue by ThierrySans** [facebook/hhvm#4930]
Hi,

Is it right to assume that each named variable in PHP has a corresponding entry in numLocals in HHBC?

If yes, is there a way to get a mapping between the PHP named variables and their corresponding index in numLocals? 

Thanks.

**Comment by paulbiss** [comment]
Yes, although I'm not aware of a convenient way to dump the mapping, it would be nice to add it to the bytecode output.

**Comment by paulbiss** [comment]
This feature request is not actively being worked on. We would happily consider a pull request implementing it. If you plan to work on this issue let us know in the comments and we will re-open the issue and assign it to you. If you feel strongly that this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
