### ISSUE TITLE
Covariance doesn't work correctly for function type hints

### ISSUE THREAD

**Issue by milesj** [facebook/hhvm#4933]
Given the following code:

```hack
type Callback = (function(Foo): mixed);

class Foo {}
class FooChild extends Foo {}

function register(Callback $callback) {}
function a(Foo $foo) {}
function b(FooChild $foo) {}

register(fun('a'));
register(fun('b')); // Errors
```

Produces the following type checker errors:

* Invalid argument (Typing[4110])
* This is an object of type FooChild
* It is incompatible with an object of type Foo

**Comment by fredemmott** [comment]
This is correct; callback is defined as accepting /any/ Foo - 'b' only takes some Foos.

**Comment by milesj** [comment]
Ah, you're totally right. Was thinking this in reverse. I should take a break.
