### ISSUE TITLE
Class undefined: PHP_Token_HASHBANG (when using phpUnit)

### ISSUE THREAD

**Issue by jpSimkins** [facebook/hhvm#4936]
Only on HHVM I get this error:
`PHPUnit_Framework_Exception: Fatal error: Class undefined: PHP_Token_HASHBANG in phar://phpunit-4.5.0.phar/php-token-stream/Token/Stream.php on line 185`

https://travis-ci.org/jpSimkins/SimplaForm/jobs/52837363

All others are fine. I don't believe it to be a code issue on my part but an issue with the environment.

Hope this helps

**Comment by paulbiss** [comment]
@jpSimkins: It's a KP, we added that token to deal with another issue (#1159), see #4810.

**Comment by nikic** [comment]
Can probably close this, as it ought to be fixed by the referenced commit.
