### ISSUE TITLE
unwind-x64.cpp bug

### ISSUE THREAD

**Issue by rrh** [facebook/hhvm#4946]
ubuntu 14.04 debug build of hhvm master at/near head

running test/run slow I now see ~8 slow unit tests all fail with an unwind-x64.cpp bug.  Here's the first of them:

test/run --threads 8 'test/slow/ext_ezc_test/caught-exception-recursive.php'

```
002+ hhvm: /home/rrh/dev1/hhvm/hphp/runtime/vm/jit/mc-generator.cpp:1797: void HPHP::jit::MCGenerator::requestExit(): Assertion `!std::uncaught_exception() && "Uncaught exception live at request shutdown. " "Probably an unwind-x64.cpp bug."' failed.
```
Here are the top useful frame from gdb
```
#3  0x00007f59c14d0c32 in __GI___assert_fail (
    assertion=0x2da1f80 "!std::uncaught_exception() && \"Uncaught exception live at request shutdown. \" \"Probably an unwind-x64.cpp bug.\"", 
    file=0x2da1980 "/home/rrh/dev1/hhvm/hphp/runtime/vm/jit/mc-generator.cpp", 
    line=1797, 
    function=0x366aee0 <HPHP::jit::MCGenerator::requestExit()::__PRETTY_FUNCTION__> "void HPHP::jit::MCGenerator::requestExit()") at assert.c:101
#4  0x0000000001d9d97d in HPHP::jit::MCGenerator::requestExit (
    this=<optimized out>)
    at /home/rrh/dev1/hhvm/hphp/runtime/vm/jit/mc-generator.cpp:1795
#5  0x0000000001938500 in HPHP::ExecutionContext::requestExit (
    this=this@entry=0x7f59b68064b0)
    at /home/rrh/dev1/hhvm/hphp/runtime/vm/bytecode.cpp:7757
#6  0x00000000016328ef in HPHP::hphp_context_exit (
    shutdown=shutdown@entry=true)
    at /home/rrh/dev1/hhvm/hphp/runtime/base/program-functions.cpp:1979
#7  0x0000000001632c58 in HPHP::execute_command_line_end (xhprof=0, 
    coverage=coverage@entry=true, 
    program=0x7f59b2008b18 "test/slow/ext_ezc_test/caught-exception-recursive.php") at /home/rrh/dev1/hhvm/hphp/runtime/base/program-functions.cpp:712
#8  0x0000000001642990 in HPHP::execute_program_impl (argc=argc@entry=11, 
    argv=argv@entry=0x7fff428ee0c8)
    at /home/rrh/dev1/hhvm/hphp/runtime/base/program-functions.cpp:1628
#9  0x0000000001643700 in HPHP::execute_program (argc=argc@entry=11, 
    argv=argv@entry=0x7fff428ee0c8)
    at /home/rrh/dev1/hhvm/hphp/runtime/base/program-functions.cpp:1025
#10 0x00000000015ef5a8 in main (argc=11, argv=0x7fff428ee0c8)
    at /home/rrh/dev1/hhvm/hphp/hhvm/main.cpp:60
```

**Comment by rrh** [comment]
I did a git bisect and that pointed its finger to the culprit being this commit

https://github.com/facebook/hhvm/commit/e5ecbc4ebd21221c7e9e5a684f9d842013757d7a

**Comment by swtaarrs** [comment]
Thanks for the report. I haven't looked into this yet, but it's likely that the bug has been around for a while and is just now being exposed by the new assert. What compiler are you using to build? The tests all pass for me so it may be a libunwind version difference or something annoying like that.

**Comment by rrh** [comment]
I'm using
  gcc-4.8.real (Ubuntu 4.8.2-19ubuntu1) 4.8.2
I follow
  https://github.com/facebook/hhvm/wiki/Building-and-installing-HHVM-on-Ubuntu-14.04

ldd hphp/hhvm/hhvm is captured in this gist: https://gist.github.com/rrh/b982060137e4e2adde5b

I can run experiments, gdb, if you want.

**Comment by rrh** [comment]
This issue should be tagged as a "Crash" by the admins of this git hub

**Comment by rrh** [comment]
Any thoughts of fixes on the horizon for this?

**Comment by swtaarrs** [comment]
Sorry, I've been caught up with other stuff for the past few days. I'll try to take a look soon, but in the meantime if this is causing problems for you go ahead and comment out the assertion in your build. We lived in a broken state for many, many months before I added the assertion and exposed the problem.

**Comment by swtaarrs** [comment]
Whoops, forgot about this task. The assert was removed in af8cc357c2f0714a4390ba303214287281e4c0e4.
