### ISSUE TITLE
Mysql Fatal build

### ISSUE THREAD

**Issue by coderxlsn** [facebook/hhvm#4948]
I have last git repository version
```
[ 29%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/db-mysql.cpp.o
In file included from /usr/local/src/hhvm/hphp/util/db-mysql.cpp:16:0:
/usr/local/src/hhvm/hphp/util/db-mysql.h:20:19: fatal error: mysql.h: No such file or directory
 #include <mysql.h>
make[2]: *** [hphp/util/CMakeFiles/hphp_util.dir/db-mysql.cpp.o] Error 1
make[1]: *** [hphp/util/CMakeFiles/hphp_util.dir/all] Error 2
compilation terminated.

**Comment by coderxlsn** [comment]
$ whereis mysql.h
mysql: /usr/bin/mysql /usr/lib64/mysql /usr/include/mysql /usr/share/mysql /usr/share/man/man1/mysql.1.gz

**Comment by joostshao** [comment]
$ locate mysql.h  ?

/usr/include/hphp/runtime/ext/pdo_mysql.h
/usr/include/hphp/runtime/ext/mysql/ext_mysql.h
/usr/include/hphp/util/db-mysql.h
/usr/include/mysql/mysql.h
/usr/include/php5/ext/mysqli/mysqli_libmysql.h

**Comment by coderxlsn** [comment]
locate mysql.h 
/usr/include/mysql/mysql.h
/usr/local/include/hphp/runtime/ext/pdo_mysql.h
/usr/local/include/hphp/runtime/ext/mysql/ext_mysql.h
/usr/local/include/hphp/util/db-mysql.h
/usr/local/src/hhvm/hphp/hack/hhi/stdlib/builtins_async_mysql.hhi
/usr/local/src/hhvm/hphp/hack/hhi/stdlib/builtins_mysql.hhi
/usr/local/src/hhvm/hphp/runtime/ext/pdo_mysql.h
/usr/local/src/hhvm/hphp/runtime/ext/async_mysql/ext_async_mysql.h
/usr/local/src/hhvm/hphp/runtime/ext/mysql/ext_mysql.h
/usr/local/src/hhvm/hphp/util/db-mysql.h

**Comment by jazzdan** [comment]
If you tried to build without the mysql.h, and then you installed it and rebuilt you might have to go a `git clear -fdx`. In the past I've had problems where cmake leaves old make files around that point to the wrong places for dependencies.

**Comment by coderxlsn** [comment]
Than. fix problem
