### ISSUE TITLE
Implement FCGI_GET_VALUES

### ISSUE THREAD

**Issue by PunKeel** [facebook/hhvm#4951]
- [ ] Implement FCGI_GET_VALUES
- [ ] Write tests

```php
<?php
include('Client.php');
use Adoy\FastCGI\Client;

$client = new Client('localhost', '9000');
var_dump($client->getValues(['MAX_CONNS'])); // Raises an exception
/*
Fatal error: Uncaught exception 'Exception' with message 'Unexpected response type, expecting GET_VALUES_RESULT' in /root/Client.php:406
Stack trace:
#0 ./x.php(6): Adoy\FastCGI\Client->getValues()
#1 {main}
*/

**Comment by paulbiss** [comment]
Hmm, this should be implemented.

**Comment by jrobeson** [comment]
@paulbiss : as in, it should have already been implemented? or it should be implemented in the future?

**Comment by paulbiss** [comment]
As in I thought we already had an implementation of this feature.

**Comment by PunKeel** [comment]
I also thought so, but the php code didn't work as expected, (and a Monit
code, tested & working with another fastcgi implementation, is not working
either)

2015-03-09 19:01 GMT+01:00 Paul Bissonnette <notifications@github.com>:

**Comment by paulbiss** [comment]
Hmm, it's probably a bug in the implementation.

**Comment by felixbuenemann** [comment]
This would be great to allow a simple health check in monit. Currently the socket read just hangs, if I write a minimal get values message like `\x01\x09\x00\x00\x00\x00\x08\x00\x00\x00\x00\x00\x00\x00\x00\x00`.

**Comment by felixbuenemann** [comment]
@Orvid Is this problem fixed in master or why was the issue closed?

**Comment by Orvid** [comment]
Yes, it looks like it should be implemented.
