### ISSUE TITLE
Unpacked argument reverses variadic parameter order

### ISSUE THREAD

**Issue by mpajunen** [facebook/hhvm#4952]
When passing both normal and unpacked arguments to a function with a variadic parameter, the parameters are in the wrong order. For example:
```php
function test(...$params)
{
    echo $params[0] . $params[1] . $params[2] . $params[3];
}
test(1, 2, 3, ...[4]); // Expected output: 1234, actual: 3214
```
Comparison: http://3v4l.org/6KIR5

**Comment by nikic** [comment]
Problem is probably in https://github.com/facebook/hhvm/blob/87dcc5b561f138b6dbf3e2d38e0bd80f70371712/hphp/runtime/vm/bytecode.cpp#L1780 (and similar code starting L1747) where the top of the stack is appended to the variadic argument array and popped from the stack. This will reverse the order of the (normal) arguments going into a variadic args array.
