### ISSUE TITLE
Error compile mongofill-hhvm from hhvm 3.7.0

### ISSUE THREAD

**Issue by coderxlsn** [facebook/hhvm#4953]
[ 33%] Building CXX object CMakeFiles/mongo.dir/src/bson.cpp.o
/usr/local/src/mongofill-hhvm/src/bson.cpp: В функции «HPHP::String HPHP::f_bson_encode_multiple(const HPHP::Array&)»:
/usr/local/src/mongofill-hhvm/src/bson.cpp:62:32: ошибка: переменная «HPHP::ArrayIter iter» инициализирована, хотя имеет неполный тип
for (ArrayIter iter(documents); iter; ++iter) {

**Comment by coderxlsn** [comment]
https://github.com/mongofill/mongofill-hhvm/issues/31

**Comment by paulbiss** [comment]
I can't read your compiler output, but it looks as though their source isn't compatible with the most recent version of hhvm, you could try building against 3.5 or 3.3.

**Comment by coderxlsn** [comment]
Yes. In version 3.6.0 This module works

**Comment by fredemmott** [comment]
Closing, the issue on their tracker is in the correct place.
