### ISSUE TITLE
dl_fini time segfault through jemalloc on ubuntu 14.04 debug build

### ISSUE THREAD

**Issue by rrh** [facebook/hhvm#4954]
Syncing to master head (why do I do this?) and rebuilding on ubuntu 14.04 with a debug build fails on every execution on the way out when dl_fini is executed.  I can't tell from what state gdb can sniff out what the offending .so is.

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff4f4c1af in free () from /usr/lib/x86_64-linux-gnu/libjemalloc.so.1
(gdb) where
#0  0x00007ffff4f4c1af in free () from /usr/lib/x86_64-linux-gnu/libjemalloc.so.1
#1  0x00007fffe9e1d8dd in ?? () from /usr/lib/x86_64-linux-gnu/libp11-kit.so.0
#2  0x00007ffff7dea73a in _dl_fini () at dl-fini.c:252
#3  0x00007ffff0990259 in __run_exit_handlers (status=0, listp=0x7ffff0d126c8 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true) at exit.c:82
#4  0x00007ffff09902a5 in __GI_exit (status=<optimized out>) at exit.c:104
#5  0x00007ffff0975ecc in __libc_start_main (main=0x15f1c8a <main(int, char**)>, argc=11, argv=0x7fffffffe4e8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe4d8) at libc-start.c:321
#6  0x00000000015f1249 in _start ()

**Comment by JoelMarcey** [comment]
sending out a revert of 5a8046c10c4f6fc0b76a1e57772bbe7f7d6247a4 now.
