### ISSUE TITLE
Extension information incomplete / not implemented

### ISSUE THREAD

**Issue by milesj** [facebook/hhvm#4958]
So recently I was bored and attempted to write a Hack script that generates HHI files by using reflection. Sounds simple enough. 

My first attempt was to use `ReflectionExtension`, which would always return an empty array for constants, classes, interfaces, etc. Turns out that this hasn't even been implemented yet. https://github.com/facebook/hhvm/blob/2c44df29b89367fd29196f90b5ccd130cd60f41a/hphp/runtime/ext/reflection/ext_reflection.cpp#L162

My second attempt was to use `get_defined_constants()`, which works. However, the categorize (by extension) argument does not work. It only categorizes by User and Core. https://github.com/facebook/hhvm/blob/d03545c30ab83b497341b896c567a666b7daf6df/hphp/runtime/base/static-string-table.cpp#L264

My third attempt was to use `get_extension_funcs()`, which throws an error: "Fatal error: f_get_extension_funcs is not supported: extensions are built differently in /vagrant/bin/generate_hhi.hh on line 36".

I'm assuming these are all related in some way, just thought I would point this out.

**Comment by Orvid** [comment]
#6497 is newer, but clearer about `get_extension_funcs` not being implemented.

Leaving this open to track `ReflectionExtension` not being implemented.

**Comment by Orvid** [comment]
We're a small team, and it doesn't look as though anyone in the community is actively working on this issue, so we've decided to close it. If you plan to send us a pull request resolving the issue let us know in the comments and we will re-open it and assign it to you. If you feel this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
