### ISSUE TITLE
multiple CLI invocations, one process?

### ISSUE THREAD

**Issue by andrisi** [facebook/hhvm#4959]
Would it be possible to execute multiple scripts with HHVM on the command line, but using only one HHVM instance. We need to run several long running processes, and spawning a new instance from the cli seems to be an overkill, while running over HTTP is complicated. I seem to remember that some linux tool does just this, handing over tasks to a main cli process if invoked multiple times.

**Comment by danslo** [comment]
I think the easiest way to do that right now, would be to use something like [PHP FastCGI Client](https://github.com/adoy/PHP-FastCGI-Client).

**Comment by andrisi** [comment]
Interesting, but to run it, you would need yet another PHP CLI interpreter... :-)

**Comment by danslo** [comment]
That's true. But all it would do is make a request and keep some connection open. The brunt of the work would be done by the long-living process, JIT is already active and found hot paths for incoming requests, etc.

I agree that it isn't ideal :)

**Comment by paulbiss** [comment]
This feature request is not actively being worked on. We would happily consider a pull request implementing it. If you plan to work on this issue let us know in the comments and we will re-open the issue and assign it to you. If you feel strongly that this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
