### ISSUE TITLE
ext_zend_compat doc: "persistent" argument of zend_hash_init() function.

### ISSUE THREAD

**Issue by fadimko** [facebook/hhvm#4964]
If `persistent` != 0 in `zend_hash_init()` call, HHVM will crash with the message `"zend_hash_init: "persistent" is unimplemented"`. PHP documentation says that passing 0 as `persistent` argument (that will simply be passed to `pemalloc()` calls) will cause the hash table to be released after a PHP request. So am I right, that HHVM will work the same way? And if so, is there any way to create a hash table that will live until HHVM stops or I call `zend_hash_destroy()`?

**Comment by paulbiss** [comment]
I'm not familiar enough with the ext_zend_compat layer to know how easy it would be to do. Intuitively the allocation could be done with the standard allocator rather than the smart allocator so that it doesn't live on the request heap.
