### ISSUE TITLE
Possible issues in mysqli_stmt::hh_Init

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#4971]
- It looks like a MySQL* (connection) is being cast to a MySQLStmt* (statement)
- It looks like there's both a shared pointer and a smart pointer referecing the same MySQL* - this seems like a double-free

**Comment by Orvid** [comment]
@fredemmott This is a "possible issue". Is it still one?

**Comment by Orvid** [comment]
This issue has been waiting for more info for more than 2 weeks. I'm closing it for now, but feel free to re-open it if you can provide more info. https://github.com/facebook/hhvm/wiki/Human-Timeouts
