### ISSUE TITLE
Error in command line: unrecognised option '-S'

### ISSUE THREAD

**Issue by erikmp** [facebook/hhvm#4973]
Output of hhvm --version:
HipHop VM 3.5.1 (rel)
Compiler: tags/HHVM-3.5.1-0-gb723e67c88bc008676687a04dff00db1faf250b3
Repo schema: a395edf8708632a3d09f417dbd9b1bd1d5b50bbe

Output of php -v:
PHP 5.5.9-1ubuntu4.6 (cli) (built: Feb 13 2015 19:17:11) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies

Running on Linux Mint 17.1

Using the Laravel Framework, version 5 hhvm artisan serve yields: 

Laravel development server started on http://localhost:8000
Error in command line: unrecognised option '-S'

Then exits

**Comment by reeze** [comment]
As far as I know HHVM doesn't support builtin http server anymore. It might implement it again @JoelMarcey should know more about this.

**Comment by yangshengjie** [comment]
@reeze since when?

**Comment by paulbiss** [comment]
We stopped supporting it officially when we added FastCGI. You need to build hhvm with a modified libevent for it to work and some extra cmake flags. I'm not sure if we still have instructions around.

We're interested in releasing the proxygen server we use internally to run hhvm but we're still waiting on some dependencies to be cleaned up.
