### ISSUE TITLE
Hack Main Function / No Globals

### ISSUE THREAD

**Issue by TheRyanHowell** [facebook/hhvm#4982]
It doesn't currently seem possible to run entirely in hack strict mode without changing the configuration of the init document / function to add a function to the shutdown queue which executes a main function.

It would be extremely helpful and a nice design choice if we could simply have a default main function which is only called if it's defined, we have reached the end of the request and no code has been executed in the global scope, only function / class declartions and includes etc.

As a nice side effect of this you could completely remove the need for any global variables / arrays, by passing through all the normal global scope data ($_GET, $_POST, $_ENV, $_SERVER etc.) into the main function, and use collections instead of arrays.

Then it's possible for frameworks and applications to be entirely written in hack strict mode, never use a single php array and never use any global variables / code.

**Comment by paulbiss** [comment]
My understanding is that this is something we'd like to add, we just haven't agree on how it should behave.

**Comment by tslettebo** [comment]
A reasonable workaround seems to be to use the (currently undocumented) [HH_FIXME](https://github.com/hhvm/hack-hhvm-docs/issues/359) feature.

An advantage of this over removing "strict" or using UNSAFE is that it only removes the specified message, while still parsing and checking the rest of the code.

At least, that's how it appears to work, so anyone at FB, feel free to comment or correct.

Thus, the following works, and correctly detects the missing type declarations on the function definition, whereas UNSAFE can't be used, and removing "strict" makes all type declarations optional.
```
<?hh // strict

/* HH_FIXME[1002] Remove all toplevel statements except for requires */

f("Test");

// ...

function f($value) // Error messages about missing type declarations
{
  echo $value;
}
```

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Hhvm [3.28.2](https://hhvm.com/blog/2018/09/28/hhvm-3.28.2.html) addressed the idea of an entrypoint to an application via the `__Entrypoint` (later `__EntryPoint`) attribute. This function should take no arguments and will be called when a request hits that script. When the file is `require_once`'d, the attribute is ignored and the code inside will not be executed.
