### ISSUE TITLE
Change listening port. 9000 clashes with PHP remote debugger.

### ISSUE THREAD

**Issue by mcd-php** [facebook/hhvm#4983]
After weekend, all of a sudden PHP debug in IDE quits working. With a little help of `lsof -i :9000` found guilty hhvm.

As of http://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers and https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.txt , the next free one is 9003, so I changed my local config for this.

Also, the wiki article above says 9000 is used by Hadoop and PHP-FPM, this can be used together with hhvm and port clash will cause additional trouble for their admins.

**Comment by jwatzman** [comment]
I think 9000 makes sense as a default -- it's the standard FastCGI port (as you note, PHP-FPM uses it for that reason). Makes sense to emulate PHP-FPM to me.

You can always change the port in the config if you need to run more than one of these at once, which most people don't. Or change the port of one of the other commands, for that matter.

**Comment by paulbiss** [comment]
Yeah- I think we want to keep the same default as PHP here. I agree this behavior is unfortunate, but it would be potentially very confusing for people coming from PHP if our default was different.
