### ISSUE TITLE
HHVM 3.6.0 fix_path_info causes "file not found"

### ISSUE THREAD

**Issue by keepxtreme** [facebook/hhvm#4986]
Since the Update from 3.5.0 (completly working) to 3.6.0 setting "hhvm.server.fix_path_info = true" will cause a printed error: File not found

OS: Debian Jessie
Apache 2.4 via mod_proxy_fcgi

**Comment by paulbiss** [comment]
I cherry-picked 3a123f3628951a255bcc5c537612131325cb44d8 into the 3.6 branch yesterday which was supposed to fix this. Are you still seeing the problem with that commit?

**Comment by keepxtreme** [comment]
well, I had it enabled until this morning when I updated from 3.5.0 to 3.6.0. Afterwards I got "File Not Found" in Apache. The setting"hhvm.server.fix_path_info=false" solved the problem (had been true until this morning) - so I don't know how much this is effected by this patch

I'm running latest stable from debian/jessie repository

**Comment by lwansbrough** [comment]
This broke our deployment. Would love to know if `hhvm.server.fix_path_info=false` is the new default or if I should expect a fix to re-introduce the `hhvm.server.fix_path_info=true` behaviour. Would hate for our site to 404 twice because of this.

**Comment by paulbiss** [comment]
During a recent fastcgi refactor [these checks](https://github.com/facebook/hhvm/blob/d163af25cde2878320f01fff4e42de2d946ffb77/hphp/runtime/server/fastcgi/fastcgi-transport.cpp#L268-L282) were reordered because the previous ordering looked suspect.

I believe that this is the source of the discrepancy. We can reorder them if this change was incorrect (the comment explains the reasoning), but unless it's a bug I have no reason to believe we'll need to change it again.

**Comment by lwansbrough** [comment]
I've version locked at 3.6 and changed that configuration setting - I'll roll with these changes going forward. Thanks @paulbiss

**Comment by castarco** [comment]
I don't have touched the hhvm settings after the installation, and neither in /etc/hhvm/php.ini nor /etc/hhvm/server.ini exists this line. So, should i guess that the default value is true?

**Comment by jeroenvermeulen-eu** [comment]
I had `hhvm.server.fix_path_info = true` in my `php.ini` because on some servers I run Apache+HHVM.
Previously with this setting it worked both on Nginx and Apache.
Since HHVM 3.6.0 the setting has to be removed (default=false) to work under Nginx.
I did not test under Apache yet.

**Comment by keepxtreme** [comment]
I had this issue with Apache 2.4

**Comment by PunKeel** [comment]
Same issue under Apache 2.4

**Comment by sarathsp06** [comment]
Here is my hhvm --version 
`
$=> hhvm --version
HipHop VM 3.6.4 (rel)
Compiler: tags/HHVM-3.6.4-0-gd99cdd36692bbfdf2729011094e2a4e3f2baab6e
Repo schema: 7be7d7f958557834c0d96589ccafa0063e6007da
`
Here is the system info
`
Linux sarath-Lenovo-B490 3.13.0-53-generic #89~precise1-Ubuntu SMP Wed May 20 17:42:16 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
`

I have installed hhvm and ran it on port 9000 .Used nginx to pass the requestes to hhvm .In nginx i was using php5-fpm .So i did not made any change in the nginx config file

I am getting **404 File Not Found** error on making web request
