### ISSUE TITLE
HHVM 3.6.0 - Cross-Origin Request Blocked - HTTPS detection broken?

### ISSUE THREAD

**Issue by craigcarnell** [facebook/hhvm#4990]
I'm having an issue with my application, seems to be detecting it as HTTPS in the new HHVM 3.6.0 release which is causing a major problem so I will have to roll back.

In my Magento body I have some code from Nexcessnet Turpentine which does a GET request to a URL:

``
jQuery.ajax(
                    {
                        url: esiUrl,
                        type: "get",
                        dataType: "html"
                    }
                ).done(function() {
                    $(blockTag).fadeIn(300);
                });
``

The base URL is http.
The AJAX URL is something like (it's on the same domain!): 
```
http://www.xxx.co.uk/turpentine/esi/getBlock/method/ajax/access/private/ttl/0/hmac/41fc14efe41a43e7b24bfa6611baf6f6cc6e3df35335c8a49876970ebe3cee89/data/TBaREDnaCNetzBDCDLMcqpgj8voNRzvyptIi6uSUdxJcTCEVZk2TAJhIZdOsoHb0idTa0beIf1XNH6FVhB2giWHwx21qBU2lL8AJ7l2LRYJjdxDj8.G91hfozEq0jos-C.xcjF9GWkSN2Y3hpR7cC.aXKXim4FxtttnVhyiIVfJVn-.1lRsoywccc0s.Hw7ItdOg0BCnx57PvJDQ.Lreyqn.7z4cIljxx-6CnAIe4i.YSF2fR.ZgRtKYhtN9gKzze.Ar07eReTBumOe6zSIp62vZ.vsVFQeMgf4p0RfIPkfDMrEbE7Ok-6uNIC1E4kscP1eiOPyi9SkeqhOS8QBc-UtXhSPpRHJk/
```

With HHVM 3.5.0 this worked fine. However, with 3.6.0 this has become the following and results in an error:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://www.xxx.co.uk/turpentine/esi/getBlock/method/ajax/access/private/ttl/0/hmac/41fc14efe41a43e7b24bfa6611baf6f6cc6e3df35335c8a49876970ebe3cee89/data/TBaREDnaCNetzBDCDLMcqpgj8voNRzvyptIi6uSUdxJcTCEVZk2TAJhIZdOsoHb0idTa0beIf1XNH6FVhB2giWHwx21qBU2lL8AJ7l2LRYJjdxDj8.G91hfozEq0jos-C.xcjF9GWkSN2Y3hpR7cC.aXKXim4FxtttnVhyiIVfJVn-.1lRsoywccc0s.Hw7ItdOg0BCnx57PvJDQ.Lreyqn.7z4cIljxx-6CnAIe4i.YSF2fR.ZgRtKYhtN9gKzze.Ar07eReTBumOe6zSIp62vZ.vsVFQeMgf4p0RfIPkfDMrEbE7Ok-6uNIC1E4kscP1eiOPyi9SkeqhOS8QBc-UtXhSPpRHJk/. This can be fixed by moving the resource to the same domain or enabling CORS.
```

This is because the request is no longer GET but OPTIONS, no longer http but https.

The only difference is HHVM 3.5.0 to 3.6.0. No code changes?

Varnish etc. is the same. I simply tried copying over the 3.5.0 binary and restarting hhvm and it was fixed.

This for me unfortunately is a application breaking issue. Could it be that nginx fastcgi params are not being sent across? etc.

OS: Ubuntu 14.04 (64-bit), official hhvm package 3.6.0
Application: Magento Enterprise 1.14.1.0 EE
Web server: nginx 1.6.2, Varnish 4.0.2

**Comment by craigcarnell** [comment]
Also tested on hhvm-nightly_2015.03.10, same issue

**Comment by CremboC** [comment]
It seems like this completely borked Laravel's ```HTML::style()``` and ```HTML::script()```... Now it automatically generates https:// links which breaks all old code if your nginx is not configured to handle https..

I mean guys, thanks a lot for your hard work, but how does this get pass QC :/

**Comment by paulbiss** [comment]
@CremboC we recently did some refactoring on the application server. I apologize for the inconvenience, we don't have great test coverage for fastcgi, and hammering on it with unit-tests and our benchmarking harness didn't expose this problem.

I'm looking into it now, you're welcome to contribute tests. :)

**Comment by CremboC** [comment]
I see, thanks for the quick comment. Sorry for being so rude, just as always all issues come up at the same time... Thanks a lot for your hard work. I'll be using php5-fpm until this is fixed unless there is a way to revert to 3.5.0 easily?

Thanks a lot again.

**Comment by paulbiss** [comment]
Not sure which distro you're running but you can download the 3.5 deb [here](http://dl.hhvm.com/ubuntu/pool/main/h/hhvm/). Sorry again for the inconvenience, as soon as we figure out what's going on we'll push a patch for 3.6.

**Comment by paulbiss** [comment]
Okay, I've done some digging and `HTML::style()` in laravel will eventual resolve whether or not to use `https` based on the `isSecure()` method of the symfony request object, [here](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/HttpFoundation/Request.php#L1237-L1246).

It looks to me like this method will inspect either the `X-Forwarded-Proto` header or `$_SERVER["HTTPS"]`. In my test instance with 3.6.0 connected to nginx `$_SERVER["HTTPS"]` was the empty string and the other header was not set.

Is there anything in your nginx or hhvm configuration files that may be setting these values?

**Comment by CremboC** [comment]
This is my specific website config in nginx:
```
server {
    root /usr/share/nginx/www/<omitted>;
    index index.php;

    server_name <omitted>;

    access_log /var/log/nginx/localhost.laravel-access.log;
    error_log  /var/log/nginx/localhost.laravel-error.log error;

    charset utf-8;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { log_not_found off; access_log off; }
    location = /robots.txt  { log_not_found off; access_log off; }

    error_page 404 /index.php;
    include hhvm.conf;  # The HHVM Magic Here

    # Deny .htaccess file access
    location ~ /\.ht {
        deny all;
    }
}
```

This is the general nginx config:
```
user www-data;
worker_processes 4;
pid /var/run/nginx.pid;

events {
        worker_connections 768;
        # multi_accept on;
}

http {

        ##
        # Basic Settings
        ##

        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        client_max_body_size 20M;
        types_hash_max_size 2048;
        # server_tokens off;

        # server_names_hash_bucket_size 64;
        # server_name_in_redirect off;

        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        ##
        # Logging Settings
        ##

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        ##
        # Gzip Settings
        ##

        gzip on;
        gzip_disable "msie6";

        # gzip_vary on;
        # gzip_proxied any;
        # gzip_comp_level 6;
        # gzip_buffers 16 8k;
        # gzip_http_version 1.1;
        # gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
        # nginx-naxsi config
        ##
        # Uncomment it if you installed nginx-naxsi
        ##

        #include /etc/nginx/naxsi_core.rules;

        ##
        # nginx-passenger config
        ##
        # Uncomment it if you installed nginx-passenger
        ##

        #passenger_root /usr;
        #passenger_ruby /usr/bin/ruby;

        ##
        # Virtual Host Configs
        ##

        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-enabled/*;
}
```

and hhvm:
```
; php options
session.save_handler = files
session.save_path = /var/lib/php5
session.gc_maxlifetime = 1440

hhvm.server.max_post_size = 20MB
hhvm.server.upload.upload_max_file_size = 20MB

; hhvm specific
hhvm.log.level = Warning
hhvm.log.always_log_unhandled_exceptions = true
hhvm.log.runtime_error_reporting_level = 8191
hhvm.mysql.typed_results = false
```

```
; php options

pid = /var/run/hhvm/pid

; hhvm admin
hhvm.admin_server.thread_count = 1

; hhvm specific

hhvm.server.port = 9000
hhvm.server.type = fastcgi
hhvm.server.default_document = index.php
hhvm.log.use_log_file = true
hhvm.log.file = /var/log/hhvm/error.log
hhvm.repo.central.path = /var/run/hhvm/hhvm.hhbc
hhvm.repo.authoritative = false
hhvm.jit = true
```

Sorry for the enormous post.. Just wanted to be as thorough as possible...

**Comment by paulbiss** [comment]
Thanks! What's in hhvm.conf?

**Comment by CremboC** [comment]
Just the default:
```
location ~ \.(hh|php)$ {
    fastcgi_keep_conn on;
    fastcgi_pass   127.0.0.1:9000;
    fastcgi_index  index.php;
    fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
    include        fastcgi_params;
}
```

**Comment by paulbiss** [comment]
Hmm, I'm just not seeing this behavior with the setup I'm testing. Our configuration is pretty much identical. From my understanding of the laravel implementation the problem is either the X-Forwarded-Proto header or the HTTPS fastcgi parameter.

You could try explicitly setting `fastcgi_param  HTTPS off;` to see if the problem is the latter. If you can dump the contents of `$_SERVER` that might provide some clues as well. It's clearly an hhvm/fastcgi problem but I suspect there's some subtle interaction I'm missing in my test setup.

**Comment by MarkGavalda** [comment]
I can confirm that something strange is happening in HHVM 3.6: after switching a site to it, it tried to force https without anything being in the nginx config files even remotely connected to https. The whole site is not configured for https at all. Switching back to HHVM 3.5 and/or PHP-FPM "solves" the issue immediately.

**Comment by CremboC** [comment]
@paulbiss is it enough to just create a ```<?php var_dump($_SERVER)``` file and run it with HHVM?

**Comment by craigcarnell** [comment]
@paulbiss The offending code might be this line:

https://github.com/facebook/hhvm/blob/master/hphp/runtime/server/fastcgi/fastcgi-transport.cpp#L302

```
if (m_requestParams.count("HTTPS") &&
strcasecmp(m_requestParams["HTTPS"].c_str(), "OFF")) {
setSSL();
}
```

Whereas the code before that change just called setSSL() if it wasn't equal to "OFF". HTTPS should be not set if it's a blank string (as is the case in most people's setup) or equal to OFF (which most configurations do not set).

**Comment by craigcarnell** [comment]
Unfortunately I can't just set fastcgi_param HTTP off in my application, as this is done via a load balancer with SSL termination which I have no control over

**Comment by MarkGavalda** [comment]
Is this issue not affecting others or you're just not commenting about it? :) It seems strange that it tries to force HTTPS on multiple machines of ours (those who participated in this topic), with out of the box HHVM settings and it wouldn't affect others the same way!?

**Comment by paulbiss** [comment]
@CremboC sure, that should do it.

**Comment by paulbiss** [comment]
@craigcarnell: Hmm, that's interesting, perhaps the following change might help?

```c++
if (m_requestParams.count("HTTPS") && !m_requestParams["HTTPS"].empty() &&
  strcasecmp(m_requestParams["HTTPS"].c_str(), "OFF")) {
  setSSL();
}
```

**Comment by CremboC** [comment]
@paulbiss Not sure if it's still relevant:
```
array(34) {
  ["TERM"]=>
  string(14) "xterm-256color"
  ["SHELL"]=>
  string(9) "/bin/bash"
  ["XDG_SESSION_COOKIE"]=>
  string(60) "<omitted>"
  ["SSH_CLIENT"]=>
  string(19) "<omitted>"
  ["OLDPWD"]=>
  string(12) "/home/crembo"
  ["SSH_TTY"]=>
  string(10) "/dev/pts/0"
  ["LC_ALL"]=>
  string(11) "en_US.UTF-8"
  ["USER"]=>
  string(6) "crembo"
  ["LS_COLORS"]=>
  string(1302) "<omitted>"
  ["MAIL"]=>
  string(16) "/var/mail/crembo"
  ["PATH"]=>
  string(56) "/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games"
  ["WWW_HOME"]=>
  string(21) "<omitted>"
  ["PWD"]=>
  string(20) "<omitted>"
  ["LANG"]=>
  string(11) "en_US.UTF-8"
  ["NODE_PATH"]=>
  string(59) "/usr/lib/nodejs:/usr/lib/node_modules:/usr/share/javascript"
  ["SHLVL"]=>
  string(1) "1"
  ["HOME"]=>
  string(12) "/home/crembo"
  ["LANGUAGE"]=>
  string(8) "en_US:en"
  ["LS_OPTIONS"]=>
  string(15) "--color=auto -h"
  ["LOGNAME"]=>
  string(6) "crembo"
  ["SSH_CONNECTION"]=>
  string(33) "<omitted>"
  ["LC_CTYPE"]=>
  string(11) "en_US.UTF-8"
  ["_"]=>
  string(13) "/usr/bin/hhvm"
  ["GLIBCPP_FORCE_NEW"]=>
  string(1) "1"
  ["GLIBCXX_FORCE_NEW"]=>
  string(1) "1"
  ["REQUEST_START_TIME"]=>
  int(1426115161)
  ["REQUEST_TIME"]=>
  int(1426115161)
  ["REQUEST_TIME_FLOAT"]=>
  float(1426115161.6504)
  ["DOCUMENT_ROOT"]=>
  string(0) ""
  ["SCRIPT_FILENAME"]=>
  string(8) "test.php"
  ["SCRIPT_NAME"]=>
  string(8) "test.php"
  ["PHP_SELF"]=>
  string(8) "test.php"
  ["argv"]=>
  array(1) {
    [0]=>
    string(8) "test.php"
  }
  ["argc"]=>
  int(1)
}
```

**Comment by paulbiss** [comment]
https://reviews.facebook.net/D34875

**Comment by craigcarnell** [comment]
@paulbiss :+1:

**Comment by craigcarnell** [comment]
@paulbiss Any updates on your PR being merged, this is quite a big bug for me? Thanks

**Comment by paulbiss** [comment]
@craigcarnell sorry about the delay. Patch has been pushed to master, should show up in the next sync. I'll merge it into 3.6.1 once it's been pushed out to github.

**Comment by craigcarnell** [comment]
@paulbiss Thanks Paul! :+1:

**Comment by icex84** [comment]
Hi guys, 
It looks like in version 3.7.0 the issue is there again.
nginx version: nginx/1.8.0
HipHop VM 3.7.0 (rel)
Compiler: tags/HHVM-3.7.0-0-gc8baf9cd3cb603e030969bfe24634d5e85549915
Repo schema: 1988ce75e6a571ce9c79c60fd7dc3ca8a5a5d403

hhvm.conf -> fastcgi_param  HTTPS $https if_not_empty;

Can some one help?
Thanks.

**Comment by CremboC** [comment]
@icex84 works fine here since 3.6.1. Also running on 3.7 and everything works fine.
