### ISSUE TITLE
Question about hhvm setup

### ISSUE THREAD

**Issue by endymon** [facebook/hhvm#4994]
Hi,
We have a setup with multiple wordpress installs running under HHVM.
Each install is symlinked to a common set of wordpress core files.
My question: 
Is HHVM bytecode and compiled native code engine smart enough to recognize the vast majority of identical code being run on each site, or is it performing separate compilations for each "install"?

And if not:
Are there any configuration options that can help hhvm intelligently optimize this setup?

**Comment by paulbiss** [comment]
IIRC the unit-cache is keyed on file paths, and we do [resolve symbolic links](https://github.com/facebook/hhvm/blob/6be30c00a19c7b5a07d3da949839f20a82729fdf/hphp/runtime/base/unit-cache.cpp#L247-L258) but only if you enable `hhvm.check_sym_link` in your ini settings.

**Comment by endymon** [comment]
Added that to the php.ini file. Is there any way to confirm that its working? I don't see any noticeable difference in the memory footprint of hhvm in memory.

**Comment by paulbiss** [comment]
Hmm, it actually looks like it's on by default. I suppose you could turn it off and see if your memory footprint goes up.

**Comment by Orvid** [comment]
Looks like this was resolved. Feel free to re-open if it wasn't.
