### ISSUE TITLE
hhvm build error in Gentoo involving libfolly

### ISSUE THREAD

**Issue by gopedib** [facebook/hhvm#4995]
I am trying to build hhvm in Gentoo, towards the end of build process, I am getting some lining error involving libfolly.a. https://github.com/javer/gentoo-overlay/issues/13 saw similar error before, but https://github.com/facebook/hhvm/commit/ed49813ffd618eaedb3926f244e1c19527a33511
does not mention anything on fixing libfolly.
[100%] Built target systemlib
Linking CXX executable hhvm
../../third-party/folly/libfolly.a(SSLContextManager.cpp.o):SSLContextManager.cpp:function folly::SSLContextManager::addSSLContextConfig(folly::SSLContextConfig const&, folly::SSLCacheOptions const&, folly::TLSTicketKeySeeds const*, folly::SocketAddress const&, std::shared_ptr<folly::SSLCacheProvider> const&): error: undefined reference to 'EC_KEY_new_by_curve_name'
../../third-party/folly/libfolly.a(SSLContextManager.cpp.o):SSLContextManager.cpp:function folly::SSLContextManager::addSSLContextConfig(folly::SSLContextConfig const&, folly::SSLCacheOptions const&, folly::TLSTicketKeySeeds const*, folly::SocketAddress const&, std::shared_ptr<folly::SSLCacheProvider> const&): error: undefined reference to 'EC_KEY_free'
collect2: error: ld returned 1 exit status
make[2]: *** [hphp/hhvm/hhvm] Error 1
make[1]: *** [hphp/hhvm/CMakeFiles/hhvm.dir/all] Error 2
make: *** [all] Error 2

**Comment by tlevi** [comment]
This seems to be caused by libevent >= 2.1.0.
Workaround for me is to add DEPENDS:
<dev-libs/libevent-2.1.0

**Comment by vguardiola** [comment]
HI I have the same error o similar, but I have libevent-2.0.22

Linking CXX static library libfolly.a
[ 19%] Built target webscalesqlclient
Linking CXX static library libfolly.a
[ 19%] Built target folly
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2
 * ERROR: dev-php/hhvm-3.6.1::hhvm failed (compile phase):
 *   emake failed

some idea?
