### ISSUE TITLE
hhvm 

### ISSUE THREAD

**Issue by obb12** [facebook/hhvm#4997]
hhvm says 500 internal server error on my valid php code why?

**Comment by steelbrain** [comment]
Check your hhvm error logs.

**Comment by castarco** [comment]
Are you sure that the 500 comes from HHVM, or from your web server? (Apache, Nginx...).

To check your HHVM logs you should go to /var/log/hhvm/ . The "same" with Apache or Nginx, go to /var/log/apache/ and check the error.log and access.log, or go to /var/log/nginx and check whatever you find there.

**Comment by obb12** [comment]
Tested to code with php5.5.9-fpm and nginx and no errors


Lähetetty Samsung Mobilesta

-------- Alkuperäinen viesti --------
Lähettäjä: Andreu Correa Casablanca <notifications@github.com> 
Päivämäärä:  
Saaja: facebook/hhvm <hhvm@noreply.github.com> 
Kopio: obb12 <omar.bb@hotmail.fi> 
Aihe: Re: [hhvm] hhvm  (#4997) 
 
Are you sure that the 500 comes from HHVM, or from your web server? (Apache, Nginx...).

To check your HHVM logs you should go to /var/log/hhvm/ . The "same" with Apache or Nginx, go to /var/log/apache/ and check the error.log and access.log, or go to /var/log/nginx and check whatever you find there.

**Comment by castarco** [comment]
Yes, but in any case, in my opinion you aren't provinding enough info. What about the error logs with HHVM? and what about your settings?

**Comment by obb12** [comment]
does hhvm support phpmailer?

**Comment by obb12** [comment]
\nNotice: Undefined property: mysqli::$close in /var/www/html/ajax/en/signup.php on line 33
\nNotice: Undefined property: mysqli::$close in /var/www/html/ajax/en/signup.php on line 33
\nStrict Warning: It is not safe to rely on the system's timezone settings. Please use the date.timezone setting, the TZ environment variable or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'Europe/Helsinki' for 'EET/2.0/no DST' instead in /var/www/html/ajax/en/signup.php on line 52
\nFatal error: Call to undefined function stream_socket_enable_crypto() in /var/www/html/libs/mailer/class.smtp.php on line 339

**Comment by obb12** [comment]
500 hphp_invoke

**Comment by steelbrain** [comment]
The only fatal error I can see is `stream_socket_enable_crypto` being undefined.
and It's being tracked in Bug #1647

**Comment by obb12** [comment]
i wanted to use hhvm on my website but i can't send email

**Comment by steelbrain** [comment]
@obb12 As I said, It's because HHVM doesn't support TLS and SSL for streams.
So You might have disable encryption in your SMTP Connection.

**Comment by obb12** [comment]
disable encryption between my server and google there is only my isp connecting to google and no middle but my password would leak

**Comment by steelbrain** [comment]
Well, until that issue is resolved, You could use `mail()` and modify `sendmail_path` as described in [this answer][ans] for it to use an external configuration. You can then specify your SMTP credentials in that configuration file.

[ans]:http://stackoverflow.com/a/20338651/2652018

**Comment by fredemmott** [comment]
#1647
