### ISSUE TITLE
Magento 1.8.x - 1.9.x problems with HHVM 3.6

### ISSUE THREAD

**Issue by fcorriga** [facebook/hhvm#5000]
I've updated hhvm from 3.3.x to 3.6 and i've found an issue in the backend in a standard Magento installation.
When editing a product (Catalog/Manage products), the "Image" tab does not contain the Browse and Upload buttons. Switching back to hhvm 3.3, they're there and working.
![magento_imagebuttons](https://cloud.githubusercontent.com/assets/1699391/6599627/2c79cdfa-c80b-11e4-947e-8ef3758fdd35.jpg)

**Comment by danslo** [comment]
Pretty sure this is a dupe of https://github.com/facebook/hhvm/issues/4993.

**Comment by fcorriga** [comment]
Yes, the problem seems to be in $this->getDataMaxSizeInBytes() returning nothing

**Comment by fcorriga** [comment]
is there a fix coming up?

**Comment by ksaltik** [comment]
Merging js cause this error not hhvm. Just merge js in frontend.
