### ISSUE TITLE
HHVM 3.6 not building on Centos 7

### ISSUE THREAD

**Issue by systemshq** [facebook/hhvm#5007]
I've tried building HHVM 3.6 as per the instructions and I'm getting a link error at the end:-

[100%] Generating systemlib.php
[100%] Built target systemlib
Linking CXX executable hhvm
../runtime/ext/libhphp_runtime_ext.a(gd_jpeg.cpp.o):gd_jpeg.cpp:function fatal_jpeg_error(jpeg_common_struct*): error: undefined reference to 'jpeg_destroy'
../runtime/ext/libhphp_runtime_ext.a(gd_jpeg.cpp.o):gd_jpeg.cpp:function gdImageJpegCtx: error: undefined reference to 'jpeg_std_error'
../runtime/ext/libhphp_runtime_ext.a(gd_jpeg.cpp.o):gd_jpeg.cpp:function gdImageJpegCtx: error: undefined reference to 'jpeg_CreateCompress'
../runtime/ext/libhphp_runtime_ext.a(gd_jpeg.cpp.o):gd_jpeg.cpp:function gdImageJpegCtx: error: undefined reference to 'jpeg_set_defaults'
../runtime/ext/libhphp_runtime_ext.a(gd_jpeg.cpp.o):gd_jpeg.cpp:function gdImageJpegCtx: error: undefined reference to 'jpeg_set_quality'
../runtime/ext/libhphp_runtime_ext.a(gd_jpeg.cpp.o):gd_jpeg.cpp:function gdImageJpegCtx: error: undefined reference to 'jpeg_start_compress'
../runtime/ext/libhphp_runtime_ext.a(gd_jpeg.cpp.o):gd_jpeg.cpp:function gdImageJpegCtx: error: undefined reference to 'jpeg_write_marker'
../runtime/ext/libhphp_runtime_ext.a(gd_jpeg.cpp.o):gd_jpeg.cpp:function gdImageJpegCtx: error: undefined reference to 'jpeg_write_scanlines'
../runtime/ext/libhphp_runtime_ext.a(gd_jpeg.cpp.o):gd_jpeg.cpp:function gdImageJpegCtx: error: undefined reference to 'jpeg_finish_compress'
../runtime/ext/libhphp_runtime_ext.a(gd_jpeg.cpp.o):gd_jpeg.cpp:function gdImageJpegCtx: error: undefined reference to 'jpeg_destroy_compress'
../runtime/ext/libhphp_runtime_ext.a(gd_jpeg.cpp.o):gd_jpeg.cpp:function gdImageJpegCtx: error: undefined reference to 'jpeg_write_scanlines'
../runtime/ext/libhphp_runtime_ext.a(gd_jpeg.cpp.o):gd_jpeg.cpp:function gdImageJpegCtx: error: undefined reference to 'jpeg_simple_progression'
../runtime/ext/libhphp_runtime_ext.a(gd_jpeg.cpp.o):gd_jpeg.cpp:function gdImageCreateFromJpegCtxEx: error: undefined reference to 'jpeg_std_error'
../runtime/ext/libhphp_runtime_ext.a(gd_jpeg.cpp.o):gd_jpeg.cpp:function gdImageCreateFromJpegCtxEx: error: undefined reference to 'jpeg_CreateDecompress'
../runtime/ext/libhphp_runtime_ext.a(gd_jpeg.cpp.o):gd_jpeg.cpp:function gdImageCreateFromJpegCtxEx: error: undefined reference to 'jpeg_resync_to_restart'
../runtime/ext/libhphp_runtime_ext.a(gd_jpeg.cpp.o):gd_jpeg.cpp:function gdImageCreateFromJpegCtxEx: error: undefined reference to 'jpeg_save_markers'
../runtime/ext/libhphp_runtime_ext.a(gd_jpeg.cpp.o):gd_jpeg.cpp:function gdImageCreateFromJpegCtxEx: error: undefined reference to 'jpeg_read_header'
../runtime/ext/libhphp_runtime_ext.a(gd_jpeg.cpp.o):gd_jpeg.cpp:function gdImageCreateFromJpegCtxEx: error: undefined reference to 'jpeg_start_decompress'
../runtime/ext/libhphp_runtime_ext.a(gd_jpeg.cpp.o):gd_jpeg.cpp:function gdImageCreateFromJpegCtxEx: error: undefined reference to 'jpeg_destroy_decompress'
../runtime/ext/libhphp_runtime_ext.a(gd_jpeg.cpp.o):gd_jpeg.cpp:function gdImageCreateFromJpegCtxEx: error: undefined reference to 'jpeg_read_scanlines'
../runtime/ext/libhphp_runtime_ext.a(gd_jpeg.cpp.o):gd_jpeg.cpp:function gdImageCreateFromJpegCtxEx: error: undefined reference to 'jpeg_finish_decompress'
../runtime/ext/libhphp_runtime_ext.a(gd_jpeg.cpp.o):gd_jpeg.cpp:function gdImageCreateFromJpegCtxEx: error: undefined reference to 'jpeg_destroy_decompress'
../runtime/ext/libhphp_runtime_ext.a(gd_jpeg.cpp.o):gd_jpeg.cpp:function gdImageCreateFromJpegCtxEx: error: undefined reference to 'jpeg_read_scanlines'
../runtime/ext/libhphp_runtime_ext.a(gd_jpeg.cpp.o):gd_jpeg.cpp:function jpeg_gdIOCtx_src(jpeg_decompress_struct*, gdIOCtx*): error: undefined reference to 'jpeg_resync_to_restart'

**Comment by sandeepone** [comment]
I'm able to build normally.

**Comment by tony601818** [comment]
I have the same problem with you, could you tell me how you solved it?

**Comment by tony601818** [comment]
I have the same problem with you, could you tell me how you solved it?

**Comment by jrobeson** [comment]
do you have gd-devel ?

**Comment by skl1f** [comment]
There is some problem with ImageMagick and it needed to install updated version.

Try this, it's work for me:

rpm -Uvh http://rpms.famillecollet.com/enterprise/remi-release-7.rpm

yum remove ImageMagick
yum install -y ImageMagick-last\* --enablerepo=remi

cmake \
-DLIBMAGICKWAND_INCLUDE_DIRS="/usr/include/ImageMagick-6" \
-DLIBMAGICKCORE_LIBRARIES="/usr/lib64/libMagickCore-6.Q16.so" \
-DLIBMAGICKWAND_LIBRARIES="/usr/lib64/libMagickWand-6.Q16.so" .

make -j$(($(nproc)+1))

**Comment by systemshq** [comment]
The imagemagick upgrade has also worked for me. Many thanks!

**Comment by SiebelsTim** [comment]
I think this is resolved.
