### ISSUE TITLE
test/run -e arguments don't accumulate

### ISSUE THREAD

**Issue by rrh** [facebook/hhvm#5008]
test/run -e foo says that a test named foo is an exception and should not be run.

Unfortunately
  test/run -e foo -e bar -e bat
doesn't accumulate the list of tests that are exceptions.  That would be nice.

Same for -E.  There may be other arguments where accumulation is useful.

I can achieve my goals by now by using
  test/run -E '/foo|bar|bat/'
but that's cumbersome.

**Comment by paulbiss** [comment]
This feature request is not actively being worked on. We would happily consider a pull request implementing it. If you plan to work on this issue let us know in the comments and we will re-open the issue and assign it to you. If you feel strongly that this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
