### ISSUE TITLE
Translation cache problem concerning dynamic code execution

### ISSUE THREAD

**Issue by daniele-rapagnani** [facebook/hhvm#5009]
We recently switched to HHVM for our project which has a big codebase and that receives quite a lot of traffic. 
After the switch, while testing HHVM in production, we experienced almost periodic crashes caused by a full TC. We managed to stretch the time between the crashes by increasing the TC size to the total supported limit of 2GB but we had no success in resolving the issue.

Upon further investigation we found out that the translation cache seems to grow boundless and the growth seems to be caused by **eval**'d code and **create_function** code spread around our codebase (which includes wordpress and question2answer, both affected by the problem).

We hacked out some code to patch the eval/create_function code fragments away, and now the TC seems to grow much slower. I'm wondering though if it will still be growing to its limits and crashing like it did before.

Is this the expected behavior? Is eval/create_function code bound to make HHVM crash after a certain amount of time or are we missing something?

We really need a clean way to deal with this considering that so many popular framework still make use of this old features (and we make use of them :).

**Comment by fredemmott** [comment]
Known issue: #4250 - eval() will be the same problem.

@paulbiss has been looking at this recently
