### ISSUE TITLE
utf8_decode edge case broken in 3.5+

### ISSUE THREAD

**Issue by smalyshev** [facebook/hhvm#5010]
Check out: http://3v4l.org/tGl5f

This code:
```
<?php

var_dump(utf8_decode("яяяя"));
```
works differently in 3.5+ than in previous versions and in php - non-iso characters no longer produce ? but instead produce some random other chars.

**Comment by paulbiss** [comment]
cc @sgolemon

**Comment by DmitrySoshnikov** [comment]
@sgolemon is looking into it already.
