### ISSUE TITLE
zeromq extension with 3.6 causing segfault.

### ISSUE THREAD

**Issue by no1youknowz** [facebook/hhvm#5011]
Building the extension found here:  https://github.com/duxet/hhvm-zmq

I am using

    Centos 7 minimal
    hhvm 3.6 (installed from source)
    ZeroMQ 4.0.5

When I go to test, I get:

[root@ip-10-0-0-63 hhvm-zmq-master]# sh test.sh 

	zmq extension loaded: 1
	Core dumped: Segmentation fault
	Stack trace in /tmp/stacktrace.20032.log
	test.sh: line 11: 20032 Segmentation fault      ${HPHP_HOME}/hhvm -vDynamicExtensions.0=${DIRNAME}/zmq.so ${DIRNAME}/test.php

[root@ip-10-0-0-63 hhvm-zmq-master]# cat /tmp/stacktrace.20032.log

	Host: ip-10-0-0-63.ec2.internal
	ProcessID: 20032
	ThreadID: 7f0d456ae740
	ThreadPID: 20032
	Name: /usr/local/bin/hhvm
	Type: Segmentation fault
	Runtime: hhvm
	Version: tags/HHVM-3.6.0-0-g6ef13f20da20993dc8bab9eb103f73568618d3e8
	DebuggerCount: 0

	Arguments: /root/hhvm-zmq-master/test.php
	ThreadType: CLI

	# 0  __restore_rt at sigaction.c:0
	# 1  free at /lib64/libjemalloc.so.1:0
	# 2  HPHP::FileData::closeImpl() at /usr/local/bin/hhvm:0
	# 3  HPHP::SocketData::~SocketData() at /usr/local/bin/hhvm:0
	# 4  HPHP::MixedArray::Release(HPHP::ArrayData*) at /usr/local/bin/hhvm:0
	# 5  HPHP::freeDynPropArray(HPHP::ObjectData*) at object-data.cpp:0
	# 6  HPHP::ObjectData::release() at /usr/local/bin/hhvm:0
	# 7  HPHP::(anonymous namespace)::tearDownFrame(HPHP::ActRec*&, HPHP::Stack&, unsigned char const*&, HPHP::Fault const&)::{lambda()#1}::operator()() const at unwind.cpp:0
	# 8  HPHP::(anonymous namespace)::unwind(HPHP::ActRec*&, HPHP::Stack&, unsigned char const*&, HPHP::Fault) at unwind.cpp:0
	# 9  HPHP::exception_handler() at /usr/local/bin/hhvm:0
	# 10 HPHP::ExecutionContext::invokeFunc(HPHP::TypedValue*, HPHP::Func const*, HPHP::Variant const&, HPHP::ObjectData*, HPHP::Class*, HPHP::VarEnv*, HPHP::StringData*, HPHP::ExecutionContext::InvokeFlags) at /usr/local/bin/hhvm:0
	# 11 HPHP::ExecutionContext::invokeUnit(HPHP::TypedValue*, HPHP::Unit const*) at /usr/local/bin/hhvm:0
	# 12 HPHP::invoke_file(HPHP::String const&, bool, char const*) at builtin-functions.cpp:0
	# 13 HPHP::include_impl_invoke(HPHP::String const&, bool, char const*) at /usr/local/bin/hhvm:0
	# 14 HPHP::hphp_invoke(HPHP::ExecutionContext*, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, HPHP::Array const&, HPHP::VRefParamValue const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool&, std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, bool, bool, bool) at /usr/local/bin/hhvm:0
	# 15 HPHP::hphp_invoke_simple(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) at /usr/local/bin/hhvm:0
	# 16 HPHP::execute_program_impl(int, char**) at program-functions.cpp:0
	# 17 HPHP::execute_program(int, char**) at /usr/local/bin/hhvm:0
	# 18 main at /usr/local/bin/hhvm:0
	# 19 __libc_start_main at /lib64/libc.so.6:0
	# 20 _start at /usr/local/bin/hhvm:0

	PHP Stacktrace:

	#0  send_message(tcp://localhost:5555) called at [/root/hhvm-zmq-master/test.php:25]

**Comment by no1youknowz** [comment]
Asked the fb team to take a look at this:

<@paulbiss>	paul_uk: without having looked too closely this looks really suspect to me: https://github.com/duxet/hhvm-zmq/blob/master/zmq.cpp#L116

[19:17:30]  <@paulbiss>	paul_uk: it's extracting a raw pointer to a resource- generally not a good idea, and certainly a first place to look for ref-counting bugs (the crash you pasted looks like a double-free)

[19:18:02]  <@paulbiss>	in any event I don't have time to build and test this extension, but you might point that line out to the authors and have them peak at some of our builtin extensions for examples of how to better handle resources

**Comment by paulbiss** [comment]
@no1youknowz you should cross-post this to hhvm-zmq, it's unlikely anyone here will be able to do anything with this.

**Comment by no1youknowz** [comment]
I am so fried, I been at this all day lol with zmq.  I thought I was in hhvm-zmq! :)

**Comment by no1youknowz** [comment]
Ignore, kinda resolved for now :+1:
