### ISSUE TITLE
Deprectaed FastCgi Hint in error.log

### ISSUE THREAD

**Issue by jg-development** [facebook/hhvm#5013]
Without using the fastcgi the error.log gives a hint like this:
```bash
Uncaught exception: HHVM no longer supports the built-in webserver as of 3.0.0. Please use your own webserver (nginx or apache) talking to HHVM over fastcgi. https://github.com/facebook/hhvm/wiki/FastCGI\n
```
The link itself does not exist anymore. I think this can be removed.

Greetings Jan

**Comment by simonwelsh** [comment]
https://github.com/facebook/hhvm/wiki/FastCGI works for me.

**Comment by jg-development** [comment]
Ok, that link comes with the "\n" =  "https://github.com/facebook/hhvm/wiki/FastCGI\n" in the log.
Maybe you should remove the "\n".

**Comment by paulbiss** [comment]
The logger currently uses "\n" to separate lines in mulitline errors to improve grepability and make the logs more parseable. Most of use use a pretty simple pretty-printer when we actually read the logs that replaces "\n" with a real newline. The advantage here is that you can first pipe the log to grep and then to the pretty-printer without losing parts of multiline messages.

**Comment by jg-development** [comment]
Thanks for the information.

Greetings Jan
