### ISSUE TITLE
HHVM Magento - Image type and information need to be specified for each shop view

### ISSUE THREAD

**Issue by matthewalanwilliams** [facebook/hhvm#5017]
Got a new issue arisen since i upgraded stable. I cannot upload and view images in the product section. Even if there were already images added, they cannot be viewed within admin.
![product_images_hhvm_magento](https://cloud.githubusercontent.com/assets/8156323/6640463/76a42abc-c98f-11e4-8200-f4485ecd1305.png)

**Comment by fcorriga** [comment]
It's a known issue.
https://github.com/facebook/hhvm/issues/5000

**Comment by matthewalanwilliams** [comment]
Hh sorry did a search but couldn't find it, i was surprised it hadn't been seen.

**Comment by ksaltik** [comment]
Merging js cause this error not hhvm. Just merge js in frontend.

**Comment by faheemnet** [comment]
OPEN: /etc/hhvm/php.ini
ADD: hhvm.enable_zend_ini_compat=false
