### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by lifeofguenter** [facebook/hhvm#5020]
hhvm 3.6 does not work:

"RequestInitDocument Not Found"

Default installation with Nginx 1.7.10 on Debian 7

**Comment by paulbiss** [comment]
Can you paste your configs for hhvm and nginx?

**Comment by castarco** [comment]
Why bugs with so little information are handled, and what I've posted ( #4998 ), isn't even tagged or discussed by developers?

**Comment by paulbiss** [comment]
@castarco there's no need to ping other people's issues to get attention on your own. We follow everything in this repo. I saw your issue but it looked like there had already been some suggestions, some of which you had yet to follow up on.

**Comment by Orvid** [comment]
This issue has been waiting for more info for more than 2 weeks. Closing for now, feel free to re-open it if you can provide more info.

https://github.com/facebook/hhvm/wiki/Human-Timeouts
