### ISSUE TITLE
Running Hacklang scripts using HHVM on Secure Shell throws exception

### ISSUE THREAD

**Issue by raj-nt** [facebook/hhvm#5029]
I did a setup of Ubuntu 14.04+HHVM on a virtual machine. When I try to **execute a hacklang script using a secure shell (ssh) hhvm fails to execute** and returns below message
```
(unknown exception was thrown)
``` 
The same script **executes when i run it in terminal of virtual machine**.

This is the script 
```
<?hh

echo "Hello World\n";
```

If I use a php script instead of hacklang
```
<?php

echo "Hello World\n";
```
The PHP script executes as expected both in terminal of virtual machine as well as in the secure shell.

![image](https://cloud.githubusercontent.com/assets/881307/6684091/bcdb1244-ccb3-11e4-984d-46c3650215f0.png)

the shell on left in above screenshot is terminal in the vm and the one on right is access via ssh

**Comment by raj-nt** [comment]
BTW HHVM version is 3.6.0

**Comment by r3wt** [comment]
You need to create a `.hhconfig` file for your project, then you need to run the hacklang type checker, `hh_client`. http://docs.hhvm.com/manual/en/install.hack.bootstrapping.php

**Comment by raj-nt** [comment]
@r3wt ```.hhconfig``` exists. If ```.hhconfig``` was not present hhvm would return below error

```

Fatal error: /home/vagrant/test.hh appears to be a Hack file, but you do not appear to be running the Hack typechecker. See the documentation at http://docs.hhvm.com/manual/en/install.hack.bootstrapping.php for information on getting it running. You can also set Hack.Lang.LookForTypechecker=0 to disable this check (not recommended).
```

**Comment by raj-nt** [comment]
Figured it out. Not a HHVM Issue. Locale Variable LC_ALL was not set on VM.

**Comment by SiebelsTim** [comment]
That's the second time this issue appears here. Maybe a better warning would do it?

**Comment by raj-nt** [comment]
@SiebelsTim Agree with you. TO figure out the issue, had to compile HHVM from source. With catch (...) blocks commented. Better warning should do or a line in installation doc would be helpful.

**Comment by guilhermegeek** [comment]
I had this problem in the past, always with VM. The easiest way for debian derivative is to completely purge the locales, install again and reconfigure with dpkg. I guess the problem comes also from the SSH client trying to set the locales with AcceptEnv LANG LC_*  on /etc/ssh/sshd_config.
