### ISSUE TITLE
HHVM php extensions does not support const and define

### ISSUE THREAD

**Issue by Kozzi11** [facebook/hhvm#5037]
I make this simple extension in php and build it as extension for hhvm. I can call testExistConst without problem but output is wrong, because it seems that consttant TEST_CONST1 and TEST_CONST2 are not defined.

	<?php

	namespace {    
		const TEST_CONST1 = true;
		define("TEST_CONST2", true);
		
		function testExistConst() {
			var_dump(constant("TEST_CONST1"));
			var_dump(constant("TEST_CONST2"));
			var_dump(TEST_CONST1);
			var_dump(TEST_CONST2);
		}
	}

**Comment by reeze** [comment]
AFAIK, you need to define it in C++, like this: https://github.com/facebook/hhvm/blob/master/hphp/runtime/ext/stream/ext_stream.cpp#L69 , in system lib only class and function declarations are allowed.

**Comment by paulbiss** [comment]
We also don't currently support type, newtype, or shape in hni files. We definitely plan to add support for these things, for now @reeze is correct, you should declare your constants in C++.

**Comment by paulbiss** [comment]
This feature request is not actively being worked on. We would happily consider a pull request implementing it. If you plan to work on this issue let us know in the comments and we will re-open the issue and assign it to you. If you feel strongly that this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
