### ISSUE TITLE
HHVM script simply stops

### ISSUE THREAD

**Issue by edwh** [facebook/hhvm#5038]
Got an odd problem which I think has started happening since I upgraded to this release:

HipHop VM 3.6.0 (rel)
Compiler: tags/HHVM-3.6.0-0-g6ef13f20da20993dc8bab9eb103f73568618d3e8
Repo schema: 3ab6576af394a33abbb29796c652f06b1c7640ce

I have a script which simply stops executing.  I don't see anything in error.log, and a 0-length response goes back to the client.  If I put error_log() calls in my script, I can see that it appears to stop in between them.  

If I roll back to 3.5.0 then I don't see this issue.

I'm not sure quite how to provide better diags for this.

**Comment by bauerj** [comment]
Is it possible to run this script in the console (e.g. `hhvm script.php`)? If so, what's the output?

Can you show us some code that reproduces this behaviour?

**Comment by jwatzman** [comment]
Do you perhaps have a custom error handler swallowing your errors? We've seen this before with Drupal (which tries to write them to a DB instead of the error log in some cases). Also, do you have error reporting turned on in your ini file? I assume you do if it was working on 3.5?

**Comment by edwh** [comment]
One problem - which may be the whole problem - is that HHVM seems to be intolerant of Windows line endings, whereas standard PHP is OK with them.

**Comment by Orvid** [comment]
HHVM didn't like the OSX part of the windows line endings. The current version runs fine.
