### ISSUE TITLE
Unable to change the exit code from exception handler

### ISSUE THREAD

**Issue by milo** [facebook/hhvm#5039]
When the `exit()` is called from an exception hander, the exit code is not changed. Exit code is 255. This is incompatible with PHP.
```php
<?php

set_exception_handler(function($e) {
    echo "In handler\n";
    exit(123);
});

throw new Exception;
```

```
$ hhvm exit-code.php; echo $?
In handler
255
```

Using:
```
$ hhvm --version
HipHop VM 3.7.0-dev (rel)
Compiler: heads/master-0-g7c6bb04e3b64c9797345c7ec503299fda92d6abe
Repo schema: f835dfec9770ecf3fe872098af226a72520b8759
```

**Comment by Orvid** [comment]
We're a small team, and it doesn't look as though anyone in the community is actively working on this issue, so we've decided to close it. If you plan to send us a pull request resolving the issue let us know in the comments and we will re-open it and assign it to you. If you feel this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
