### ISSUE TITLE
Sybase and SQL-Server

### ISSUE THREAD

**Issue by majimboo** [facebook/hhvm#5041]
Is there any hack to use them with hhvm now or rather when is this features scheduled or planned to be implemented on hhvm?

**Comment by capsandiego** [comment]
I was looking for this extension myself. Sad to see it's not there yet. Do you think I can load dynamically the extension, like dl('mssql.so')? Will this work?

**Comment by Orvid** [comment]
Correct me if I'm wrong, but I don't think either of those extensions are distributed normally as part of PHP.

**Comment by Orvid** [comment]
We're a small team, and it doesn't look as though anyone in the community is actively working on this issue, so we've decided to close it. If you plan to send us a pull request resolving the issue let us know in the comments and we will re-open it and assign it to you. If you feel this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
