### ISSUE TITLE
[php7] Implement Scalar Type Declarations v0.5 RFC

### ISSUE THREAD

**Issue by TazeTSchnitzel** [facebook/hhvm#5052]
See php.net approach: https://github.com/php/php-src/commit/430266edfa93e04cf5199d289050ba14866645b3

RFC: https://wiki.php.net/rfc/scalar_type_hints_v5

**Comment by TazeTSchnitzel** [comment]
HHVM already has limited strict hinting for Hack. However, there are some things it needs:

* It needs to actually be activated in PHP mode
* Weak typing support (similar to, but not exactly the same as, zpp-style weak typing, particularly NULL handling, throwing of exceptions)
* Int->float promotion
* Class name reservations
* Conditional strict mode for internal functions
* Probably other things

**Comment by TazeTSchnitzel** [comment]
Also, might need to check HHVM's weak typing actually matches PHP 7's. I don't know if you guys implemented ZPP Failure on Overflow, did you?

**Comment by jwatzman** [comment]
This is probably going to be slightly blocked on us figuring out how we're going to do PHP7 compatibility (rather, the impetus for us getting around to actually figuring it out instead of tossing around ideas :)). But super happy to get to take "scalar type annotations need to be implemented" and slap the "PHP incompatibility" tag on it.

**Comment by jwatzman** [comment]
Should we rename the tag "php incompatibility" or create a new "php7 incompatibility"?

**Comment by paulbiss** [comment]
+1 on adding a php7 incompatibility tag- would be nice to track them separately since they are incompatible with each other and we have yet to decide how to resolve that.

**Comment by sgolemon** [comment]
for now, I'd make separate tags

**Comment by fredemmott** [comment]
GH race condition on the tags - it should be a different one, we're going to want to track them separately.

For anyone implementing this: keep in mind we want to keep supporting PHP5, including classes called 'string', so we need some way to identify php5 vs php7 files, and we'd prefer this to be per-file.

Also, there are two ways to workaround the first point and use scalar types in PHP files:

 - set hhvm.force_hh=true in your ini file
 - use 'hh\int', 'hh\string', etc

**Comment by TazeTSchnitzel** [comment]
Isn't "php incompatibility" for HHVM mistakenly not matching behaviour? This would be better suited to something like "missing php features"?

**Comment by fredemmott** [comment]
![image](https://cloud.githubusercontent.com/assets/360927/6762449/a493c958-cf1d-11e4-8275-429b130b8bf6.jpg)

**Comment by TazeTSchnitzel** [comment]
I'd suggest just toggling everything with one flag.

**Comment by paulbiss** [comment]
I'd like php5 and php7 interoperability the same way we have hack and php5 interoperability. Large code bases can gradually convert.

**Comment by fredemmott** [comment]
We don't want to do that; it'd be very, very cool to support {Hack,PHP5,PHP7} applications using libraries written for any of the others.

**Comment by TazeTSchnitzel** [comment]
Also, it's best not to create applications that only work in some frankenstein half 5, half 7 mode, if possible.

**Comment by TazeTSchnitzel** [comment]
A suggestion: conditionally apply changes in default weak mode, always use PHP 7 mode in a file with `declare(strict_types=1);`?

**Comment by fredemmott** [comment]
I feel that frankenstein applications are OK as long as they're just a migration step, and the goal is to move it over once the libraries are ready - this avoids a chicken-and-egg "please support PHP7" => "but no-one uses PHP7!" => "Because there are no libraries for it!" situation.

**Comment by paulbiss** [comment]
> best not to create applications that only work in some frankenstein half 5

The idea was that this would be an upgrade path for existing projects that are either too large to convert wholesale or have unconverted dependancies that cannot be forked not a permanent situation.

**Comment by jwatzman** [comment]
There's a lot of random discussion above. To summarize the bits parts of this from the HHVM side,

1. Threading through to the callee what mode the caller is in, so it can do the check/cast properly
1. Implementing a new type of type annotation and cast/enforcement
1. Futzing with the parser/emitter to distinguish between PHP5 (`string` means a class named `string`), PHP7 (`string` means scalar string with the PHP7 rules), and Hack (`string` means `\HH\string` and the usual Hack strict rules)
1. Doing this without affecting perf elsewhere
1. Maybe even making HHBBC/etc aware of the semantics of the new annotations and allowing them to take perf advantage of them

The first two are the real meat here.

**Comment by Orvid** [comment]
As a random thought, would it be reasonable to make php5/php7 modes a compile-time setting? Are there any realistic environments where both are needed side-by side?

**Comment by fredemmott** [comment]
That's likely to be more work than supporting both directly, due to the work needed to test and package two versions then.

**Comment by jwatzman** [comment]
There are a couple issues at play:

- We need to support PHP7 since users of HHVM will want PHP7 support :)
- We need to support PHP5 since existing users of HHVM will want to continue using their installations, and we don't want to do such a big BC break, and it actually isn't that much effort for us to support both
- Given we're supporting both, making it a runtime INI option as opposed to a compile time option is actually easier, as @fredemmott said
- We originally planned to support some files in PHP5 mode and some files in PHP7 mode via other INI options to say which is which. HHVM's compiler/JIT will be able to do this no problem, but actually threading through into HHVM's internals which units are which is trickier than I had thought, so we're punting on that for now.

**Comment by TazeTSchnitzel** [comment]
Given https://github.com/facebook/hhvm/commit/ae189f38c3e5d914f007bf939d48c68eed27d5c6, https://github.com/facebook/hhvm/commit/7e4ec9bbc9ff20d08d7a96651bdd95fe72010721 and https://github.com/facebook/hhvm/commit/92e7566d479ad8b7bb9184b87bf5a5fc1b5ace27, shouldn't this issue be closed? @paulbiss

**Comment by paulbiss** [comment]
Oops, thanks!
