### ISSUE TITLE
Missing Error-Info file/line/stack on Fatal (eval in RepoAuthoritative)

### ISSUE THREAD

**Issue by colin-kiegel** [facebook/hhvm#5054]
While trying RepoAuthoritative I sumbled across 'Fatal error: You can't use eval in RepoAuthoritative mode.' I understand that this is not a bug in HHVM but intentional.

However I am missing information about 'where' this error occured. 

It would be really nice to have some line numbers with this error, because I am having difficult to pin-point the relevant source(s) of this error in a rather large codebase... Even a custom error handler doesn't provide addionation insight.

function handler ( int $errno , string $errstr [, string $errfile [, int $errline [, array $errcontext ]]] ) { ... }
set_error_handler('handler');

I am using the custom error handler (with set_error_handler) to retrieve info like stacktrace, file and line number. This generally works with HHVM - but not in this case. The custom error handler indeed gets called for this type of error. However no values are provided for $errfile, $errline and also debug_backtrace() yields no information.

**Comment by colin-kiegel** [comment]
PS: These are the log / debug settings I use in /etc/hhvm/php.ini

hhvm.log.level = Warning
hhvm.log.always_log_unhandled_exceptions = true
hhvm.log.runtime_error_reporting_level = 22519
; 22519 = E_ALL & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED
hhvm.error_handling.call_user_handler_on_fatals = true
hhvm.debug.server_error_message = true

It would be really nice to get filenames and linenumbers for this kind of error as for any other error.

**Comment by colin-kiegel** [comment]
Can you confirm this issue?
Or do you need more information?

**Comment by huguesalary** [comment]
I am currently running into this exact same issue.

I'm using a large Magento codebase with lots of custom code and can not for the life of me find where in my code this error occurs. If hhvm could output the file and the line, that would be of great help.

**Comment by Orvid** [comment]
We recently landed a fix that should output where the error occured now.
