### ISSUE TITLE
"Duplicate modifier" error not thrown for "private private"

### ISSUE THREAD

**Issue by trevorassaf** [facebook/hhvm#5055]
`class Hacklang {
private private ?string $isAwesome;
}`

^this doesn't trigger a "Duplicate modifier" error from hh_client/hh_server.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

It appears this issue has been fixed at some point, but I can't find the blogpost for it.
Your repro now reports:
```
Parsing[1002] Properties cannot have duplicate modifiers
   --> file.hack
  7 |   private private ?string $isAwesome;
    |           ^^^^^^

Parsing[1002] Properties cannot have multiple visibility modifiers
   --> file.hack
  7 |   private private ?string $isAwesome;
    |           ^^^^^^

2 errors found.
```
