### ISSUE TITLE
HHVM hangs randomly with full CPU usage

### ISSUE THREAD

**Issue by raeesiqbal** [facebook/hhvm#5056]
Hello, I'm running
```
HipHop VM 3.7.0-dev (rel)
Compiler: heads/master-0-g376368ed080ff7d8529c5d6f0c171cd8029564b7
Repo schema: bd61f873eabc218f2733bc0963e573ae1ee8abd8
```
on Ubuntu 14.04 on 512MB Digital Ocean droplet, using
Nginx stable version as server and ```MariaDB 10.0.17``` and ```Redis 2.8.9``` as Databases.

HHVM hangs randomly. This is the first line of ```top``` command. You can see that its taking up all the resources.
```
PID    USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
11633 www-data  20   0 1064692  62192  11940 S 99.9  12.4 170:12.09 hhvm
```
As you can see the CPU is at 99.9%.
I've tried destroying and creating a new server but it didn't have any effect. This problem appeared out of no-where so I don't really have any clue about why it is happening.

Note: I'm running a news website with it that has an Arabic version.

**Comment by raeesiqbal** [comment]
I had set logging level to ```Verbose``` and got this error a couple of times in the ```error.log```
```
perf_event_open failed with: Invalid argument
perf_event_open failed with: Invalid argument
```

**Comment by raeesiqbal** [comment]
bump

**Comment by paulbiss** [comment]
Can you attach gdb and dump backtraces for all the threads?

**Comment by raeesiqbal** [comment]
For anyone else who is getting the same problem. In my case the problem was with usage of SimpleXML. HHVM at that time had memory leaks with SimpleXML. Don't know the current status.

**Comment by fredemmott** [comment]
We have significantly rewritten SimpleXML and DOM* since this issue was filed.
