### ISSUE TITLE
debug vs non debug builds when loading zend compat DSOs

### ISSUE THREAD

**Issue by rrh** [facebook/hhvm#5059]
If HHVM is compiled with Debug and a zend compat DSO is compiled with Release (Eg, non debug) the HHVM debug runtime will fail when it detects incoming zvals that don't have all of the magic values written as guard or tag words in the data structure.  There's probably not a lot that can be done about this, unless some there were some dynamically settable flag that disabled the memory checking in Debug builds, but that's a can of worms, I'm sure.

I haven't tried the opposite situation, which is more likely to be encountered in practice in my situation.

**Comment by Orvid** [comment]
Mixing debug and non-debug objects is just asking for trouble.
