### ISSUE TITLE
Unable to start hhvm server with unix socket in Ubuntu

### ISSUE THREAD

**Issue by cortopy** [facebook/hhvm#5060]
After installing HHVM for the first time I'm unable to start the server using an unix socket. The command just gets stuck on the console. I stopped it after 15 minutes but I could see the file "sock" was indeed created. The command didn't finish however as nginx would not accept the unix socket configuration only the 9000 port. 

I'm trying to set it with

```
sudo hhvm --mode server -vServer.Type=fastcgi -vServer.FileSocket=/var/run/hhvm/sock
```

I'm running this on an Ubuntu 14.10 server.

**Comment by Orvid** [comment]
Does this still happen?

**Comment by cortopy** [comment]
I wouldn't be able to tell. I've moved on from HHVM so I'm closing to make things easier
