### ISSUE TITLE
mktime return an error value in jit

### ISSUE THREAD

**Issue by damenjs** [facebook/hhvm#5062]
test php script:
<code>
<?php 
</code>
<code>
  function test(){
</code>
<code>
    $aa['year'] = 2015;
</code>
<code>
    $bb = $aa['year'];
    var_dump(mktime('0','0','0',3,18,2015));
</code>
<code>
    var_dump(mktime('0','0','0',3,18,$aa['year']));
</code>
<code>
    var_dump(mktime('0','0','0',3,18,$bb));
</code>
<code>
  }
</code>
<code>
  test();
</code>
run it in jit:
<code>
 ./hhvm -vEval.Jit=true test.php
</code>
result is:
<code>
int(1426608000)
</code>
<code>
int(953308800)
</code>
<code>
int(1426608000)
</code>
the hhvm version is 2.2. I know 3.0+ has fixed the problem, but how? anyone can tell me?

**Comment by paulbiss** [comment]
We no longer support 2.2 (and haven't for quite some time), additionally, there are a number of very serious security vulnerabilities in that version of hhvm that have been fixed. I strongly recommend you upgrade to either 3.3 or 3.6.
