### ISSUE TITLE
Disable mysql connections for scripts requiring no database query

### ISSUE THREAD

**Issue by gopedib** [facebook/hhvm#5064]
Hi, I was wondering, if my php script does not involve any database query, can I disable the mysql connections (e.g. disabling the unix socket) or any other persistent network connections in hhvm build process/binary. I am trying to run a simple hello world script in a striped out version of ubuntu, where the mysql unix sockets might now work. So I am trying to turn off the mysql or any other network connections that is not necessary for my simple php scripts, so that mysql does not start automatically when hhvm attempts to execute simple hello world like scripts.

**Comment by fredemmott** [comment]
We should only open connections as they are used. What's leading you to think that HHVM is connecting?
