### ISSUE TITLE
Add <<__Deprecates>> attribute

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#5066]
cc @elgenie

Example usage:

``` Hack
<<__Deprecates(:form, 'Use :csrf-safe:form')>>
class :csrf-safe:form {
}
```

**Comment by fredemmott** [comment]
Another example:

```
class Str {
  <<__Deprecates(str_replace, "needle/haystack consistency")>>
  function replace(...) {
  ...
  }
}

**Comment by elgenie** [comment]
Can you explain how __Deprecates is supposed to be resolved in the runtime / typechecker? There seems to be a very clear possibility of conflicts.

In the runtime, would a call to str_replace be expected to be aware of the potentially yet-to-be-loaded Str::replace function?

**Comment by paulbiss** [comment]
There's not really a way to handle this sanely at runtime unless __Deprecates is restricted to systemlib. IIRC the attribute would be typechecker only. I'm still not sold on the need for this attribute though.

**Comment by fredemmott** [comment]
This would still be useful even with just typechecker support. I'm not familiar enough with the typechecker to comment on implementation.

**Comment by lexidor** [comment]
In modern Hack, you'd put `__Deprecated(<%reason%>)` on top of the deprecated entity, instead of `__Deprecates(<%deprecated entity%>, <%reason%>)` on the replacement.

I believe `__Deprecated` was around when you made this issue, so I assume that you wanted this to be the inverse of `__Deprecated`. If it was not around back then, does this satisfy your need?

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Three years later...

If the goal is to deprecate code you don't own, I'd suggest doing to in hhast. This allows you to deprecate without needing to provide an alternative. It also is clear it won't have a runtime logging effect that way.
