### ISSUE TITLE
Tracking bug for Cygwin / Windows build

### ISSUE THREAD

**Issue by wjywbs** [facebook/hhvm#5068]
The Cygwin wiki works fine for older hhvm versions, but newer versions need to be patched again.

This is a tracking bug for Cygwin build for fixing build errors and bugs, such as jit support, failed tests and various crashes.

Hopefully hhvm code can be built directly on Windows and Mac without patches.

**Comment by wjywbs** [comment]
I looked at the current JIT status on Windows. The data section will be mapped to a 64-bit address far beyond 2GB address space for the code blocks. Because the emitJmp functions do not support jumping to 64-bit addresses, the basic service requests and far jump instructions can not be generated. The linker option "/LARGEADDRESSAWARE:NO" for mapping the data section to a lower address did not work in cygwin.

@paulbiss Do you think it is needed to add support for 64-bit jumps (maybe only on Windows) or try to find some other ways to put the code blocks on lower address?

**Comment by paulbiss** [comment]
@wjywbs If you can map to lower addresses that would be much better than trying to plumb through 64bit jumps for this.

**Comment by Orvid** [comment]
I much prefer to support it natively via MSVC, so closing this one.
