### ISSUE TITLE
How to use a newer version of ImageMagick?

### ISSUE THREAD

**Issue by alexbilbie** [facebook/hhvm#5071]
I'm using Ubuntu 14.04 and HHVM 3.6.1 (downloaded from HHVM official repo).

This version of HHVM has `ImageMagick 6.7.7-10 2014-03-06 Q16` compiled in however I need to use a newer version because of colour space improvements for PNGs in `ImageMagick  6.8.0-3` (see http://www.imagemagick.org/script/color-management.php).

How can I update HHVM's version of ImageMagick?

**Comment by Orvid** [comment]
You'd have to re-compile HHVM against a newer version. The current version of HHVM should have an updated version with those color space changes.
