### ISSUE TITLE
should hhvm support the jsond parser implemented in php7 (and as pecl)

### ISSUE THREAD

**Issue by jrobeson** [facebook/hhvm#5075]
Quoting the first part of the RFC introduction:

The current Json Parser in the json extension does not have a free license which is a problem for many Linux distros. This has been referenced at Bug #63520. That results in not packaging json extension in the many Linux distributions.

See  https://wiki.php.net/rfc/jsond for details

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Support for alternative json parsers has been removed in this commit. ef919bb
