### ISSUE TITLE
Prebuild 3.6.1 on Ubuntu 14.04  segafaulting after 2 requests (seemingly if the first request uses PDO)

### ISSUE THREAD

**Issue by raymondjplante** [facebook/hhvm#5077]
After a second request to nginx/hhvm, if the first request had any PDO mysql calls in it my hhvm dies once returning the second response to nginx.  The build 3.5.1 from `http://dl.hhvm.com/ubuntu/pool/main/h/hhvm/` works fine.
 
Running AWS image of Ubuntu trusty: Linux version 3.13.0-44-generic (buildd@lamiak) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) )

I've got 2 CPU's and 4gb ram

`nginx version: nginx/1.4.6 (Ubuntu)`

Did the following:

    sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0x5a16e7281be7a449
    sudo add-apt-repository 'deb http://dl.hhvm.com/ubuntu trusty main'
    sudo apt-get update
    sudo apt-get install hhvm-dbg
    sudo update-rc.d hhvm defaults

This installed:

     HipHop VM 3.6.1 (dbg)
     Compiler: tags/HHVM-3.6.1-0-gc051feff88ba8050f33f10f7b1fb07f8d3415f9e
     Repo schema: 42f49251b5c27daf4e13cb6bcd0c7ef4824b55a3

Here's my php.ini:

     ; php options
     expose_php=off
     pid = /var/run/hhvm/pid
     date.timezone="America/New_York"
     ; hhvm specific
     hhvm.server.file_socket=/var/run/hhvm/hhvm.sock
     ;hhvm.server.port = 9000
     hhvm.server.type = fastcgi
     hhvm.server.default_document = index.php
     hhvm.log.level = Warning
     hhvm.log.always_log_unhandled_exceptions = true
     hhvm.log.runtime_error_reporting_level = 8191
     hhvm.log.use_log_file = true
     hhvm.log.file = /var/log/hhvm/error.log
     hhvm.log.header = true
     hhvm.repo.central.path = /var/run/hhvm/hhvm.hhbc
     hhvm.mysql.typed_results = false
    ;hhvm.eval.jit_warmup_requests = 0

Made sure /var/run/hhvm was empty then started hhvm

     /etc/init.d/hhvm start

Noticed a pid file and a hhvm.hhbc file created in /var/run/hhvm

Made a request to nginx, served up fine, /var/run/hhvm/hhvm.sock created

On second request, I get the response, but then I see this in the error log:

     [Wed Mar 25 16:20:10 2015] [hphp] [29609:7faa377ff700:2:000001][25567d4:164617c:7faa485e4d40] Core dumped: Segmentation fault
     [Wed Mar 25 16:20:10 2015] [hphp] [29609:7faa377ff700:2:000002] [25567d4:1646192:7faa485e4d40] Stack trace in /tmp/stacktrace.29609.log

At this point, the hhvm daemon has died.

Here is the stacktrace.log file
    
     Host: <hidden>
     ProcessID: 29610
     ThreadID: 7faa377ff700
     ThreadPID: 29617
     Name: /etc/init.d/hhvm
     Type: Segmentation fault
     Runtime: hhvm
      Version: tags/HHVM-3.6.1-0-gc051feff88ba8050f33f10f7b1fb07f8d3415f9e
     DebuggerCount: 0
 
     Server: <hidden>
     ThreadType: Web Request
     Server_SERVER_NAME:  <hidden>
         URL: /v1/

      # 0  bt_handler at /tmp/tmp.YaWuYMxxFl/hphp/runtime/base/crash-reporter.cpp:82
  
      PHP Stacktrace:

The stacktrace portion is empty

**Comment by raymondjplante** [comment]
One thing of note is when establishing my PDO connection I'm using persistent connections:
     
          $dbh = new \PDO($dsn, $options['username'], $options['password'],
                                           array(1002 => "SET NAMES 'UTF8'",  PDO::ATTR_PERSISTENT => true));
           $dbh->setAttribute (PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

**Comment by paulbiss** [comment]
Sounds like a dup of #5016

**Comment by raymondjplante** [comment]
Disabling persistent and trying with prebuilt 3.6.1 right now

**Comment by raymondjplante** [comment]
yup, seems to work fine when  I get rid of persistent connections.
