### ISSUE TITLE
Centos 7 HHVM 3.6.0/1 segfaulting.  Possibly on PDO.

### ISSUE THREAD

**Issue by no1youknowz** [facebook/hhvm#5078]
Centos 7, HHVM 3.6.0 or 3.6.1 installed.  HHVM 3.5.0 is currently in production and has no issues.

HipHop VM 3.6.1 (rel)
Compiler: tags/HHVM-3.6.1-0-gc051feff88ba8050f33f10f7b1fb07f8d3415f9e
Repo schema: 42f49251b5c27daf4e13cb6bcd0c7ef4824b55a3

My code, really simple:

	// App
	$data = array(
		'foo' => 'bar'
	);

	$click_id = $this->click_model->insert_click($data);

	// Click model
	public function insert_click_token($data)
	{
		$this->insert('tracking_click_tokens', $data);
	}

	// Base model
	public function insert($table, $data)
	{
		$keys = array_keys($data);
		$values = array_values($data);
		$param_values = array();

		// Generate ?
		foreach($data as $key => $value)
		{
			$param_values[] = "?";
		}

		$sql = "INSERT INTO ".$table." (`".implode("`, `", $keys)."`) VALUES (".implode(", ", $param_values).");";
		$this->simple_query($sql, $values);
	}

	public function simple_query($sql, $values)
	{
		$stmt = $this->write_db->prepare($sql);
		return $stmt->execute($values);
	}

Here is my segfault:

	Host: localhost.localdomain
	ProcessID: 23269
	ThreadID: 7fdfeefff700
	ThreadPID: 23274
	Name: unknown program
	Type: Segmentation fault
	Runtime: hhvm
	Version: tags/HHVM-3.6.1-0-gc051feff88ba8050f33f10f7b1fb07f8d3415f9e
	DebuggerCount: 0

	Server: slimdev.com
	ThreadType: Web Request
	Server_SERVER_NAME: www.slimdev.com
	URL: /go/start/6bdb123598bafae6

	# 0  __restore_rt at sigaction.c:0
	# 1  HPHP::PDORequestData::requestShutdown() at /usr/local/bin/hhvm:0
	# 2  HPHP::ExecutionContext::onRequestShutdown() at /usr/local/bin/hhvm:0
	# 3  HPHP::hphp_context_shutdown() at /usr/local/bin/hhvm:0
	# 4  HPHP::HttpRequestHandler::executePHPRequest(HPHP::Transport*, HPHP::RequestURI&, HPHP::SourceRootInfo&, bool) at /usr/local/bin/hhvm:0
	# 5  HPHP::HttpRequestHandler::handleRequest(HPHP::Transport*) at /usr/local/bin/hhvm:0
	# 6  HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJobImpl(std::shared_ptr<HPHP::FastCGIJob>, bool) at /usr/local/bin/hhvm:0
	# 7  HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJob(std::shared_ptr<HPHP::FastCGIJob>) at /usr/local/bin/hhvm:0
	# 8  HPHP::JobQueueWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::Server*, true, false, HPHP::JobQueueDropVMStack>::start() at /usr/local/bin/hhvm:0
	# 9  HPHP::AsyncFuncImpl::ThreadFunc(void*) at /usr/local/bin/hhvm:0
	# 10 HPHP::start_routine_wrapper(void*) at /usr/local/bin/hhvm:0
	# 11 start_thread at pthread_create.c:0
	# 12 __clone at /lib64/libc.so.6:0

	PHP Stacktrace:

**Comment by paulbiss** [comment]
Looks like a dup of #5016
