### ISSUE TITLE
3.6.x Overriding the 100mb Upload Limit, which option to use

### ISSUE THREAD

**Issue by no1youknowz** [facebook/hhvm#5080]
I've got this working with 
    
    hhvm.server.max_post_size = 250MB
    
But I've seen other options:

    hhvm.server.post_max_size
    hhvm.server.upload.upload_max_file_size

Which is the correct option?

**Comment by no1youknowz** [comment]
So it seems that I need:

    hhvm.server.max_post_size = 250MB
    hhvm.server.upload.upload_max_file_size = 250MB

What is post_max_size then?

**Comment by rrh** [comment]
As I understand it, post_max_size is what's in the php standard http://php.net/manual/en/ini.core.php#ini.post-max-size but the early HHVM mistyped the name as 'max_post_size', which lives on as 'hhvm.server.max_post_size'.

Alas, I broke ini_get of post_max_size (and 4 other per-dir settings), and there's a PR out to address this https://github.com/facebook/hhvm/pull/5057  I don't know what the trajectory of fixes is, however.

**Comment by no1youknowz** [comment]
Thanks @rrh.  I'll close this and wait for the fix.
