### ISSUE TITLE
Failed Assertion: /tmp/tmp.3qsenbhpG8/hphp/runtime/vm/jit/vasm-x64.cpp:458: void HPHP::jit::{anonymous}::Vgen::emit(HPHP::jit::ldimmb&): assertion `0' failed.

### ISSUE THREAD

**Issue by sisve** [facebook/hhvm#5082]
Execution output:

    vagrant@homestead:~$ hhvm --php repro.php 
    not implemented: /tmp/tmp.3qsenbhpG8/hphp/runtime/vm/jit/vasm-x64.cpp:458 emit
    /tmp/tmp.3qsenbhpG8/hphp/runtime/vm/jit/vasm-x64.cpp:458: void HPHP::jit::{anonymous}::Vgen::emit(HPHP::jit::ldimmb&): assertion `0' failed.

    Notice: Array to string conversion in /<...snip...>/repro.php on line 25
    Core dumped: Aborted
    Stack trace in /tmp/stacktrace.24003.log
    Aborted (core dumped)

Content of `/tmp/stacktrace.24003.log`

    vagrant@homestead:~$ cat /tmp/stacktrace.24003.log
    Host: homestead
    ProcessID: 24003
    ThreadID: 7f26c1e6d640
    ThreadPID: 24003
    Name: /usr/bin/hhvm
    Type: Aborted
    Runtime: hhvm
    Version: tags/HHVM-3.6.0-0-g6ef13f20da20993dc8bab9eb103f73568618d3e8
    DebuggerCount: 0

    Failed Assertion: /tmp/tmp.3qsenbhpG8/hphp/runtime/vm/jit/vasm-x64.cpp:458: void HPHP::jit::{anonymous}::Vgen::emit(HPHP::jit::ldimmb&): assertion `0' failed.
    Arguments: repro.php
    ThreadType: CLI

    # 0  ?? at hhvm:0
    # 1  __GI_raise at /build/buildd/eglibc-2.19/signal/../nptl/sysdeps/unix/sysv/linux/raise.c:56
    # 2  __GI_abort at /build/buildd/eglibc-2.19/stdlib/abort.c:91
    # 3  HPHP::assert_fail(char const*, char const*, unsigned int, char const*) at hhvm:0
    # 4  ?? at hhvm:0
    # 5  ?? at hhvm:0
    # 6  HPHP::jit::Vasm::finishX64(HPHP::jit::Abi const&, HPHP::jit::AsmInfo*) at hhvm:0
    # 7  HPHP::jit::x64::BackEnd::genCodeImpl(HPHP::jit::IRUnit&, HPHP::jit::AsmInfo*) at hhvm:0
    # 8  HPHP::jit::genCode(HPHP::jit::IRUnit&) at hhvm:0
    # 9  HPHP::jit::MCGenerator::traceCodeGen(HPHP::jit::HTS&) at hhvm:0
    # 10 HPHP::jit::translateRegion(HPHP::jit::HTS&, HPHP::jit::RegionDesc const&, HPHP::hphp_hash_set<HPHP::jit::ProfSrcKey, HPHP::jit::ProfSrcKey::Hasher, std::equal_to<HPHP::jit::ProfSrcKey> >&, HPHP::jit::TransFlags) at hhvm:0
    # 11 HPHP::jit::MCGenerator::translateWork(HPHP::jit::TranslArgs const&) at hhvm:0
    # 12 HPHP::jit::MCGenerator::translate(HPHP::jit::TranslArgs const&) at hhvm:0
    # 13 HPHP::jit::MCGenerator::retranslateOpt(int, bool) at hhvm:0
    # 14 MCGenerator_handleServiceRequest at hhvm:0
    # 15 handleSRHelper at hhvm:0
    # 16 enterTCExit at hhvm:0
    # 17 HPHP::jit::x64::BackEnd::enterTCHelper(unsigned char*, HPHP::ActRec*) at hhvm:0
    # 18 HPHP::jit::MCGenerator::enterTC(unsigned char*, HPHP::ActRec*) at hhvm:0
    # 19 HPHP::ExecutionContext::invokeFunc(HPHP::TypedValue*, HPHP::Func const*, HPHP::Variant const&, HPHP::ObjectData*, HPHP::Class*, HPHP::VarEnv*, HPHP::StringData*, HPHP::ExecutionContext::InvokeFlags) at hhvm:0
    # 20 HPHP::ExecutionContext::invokeUnit(HPHP::TypedValue*, HPHP::Unit const*) at hhvm:0
    # 21 ?? at hhvm:0
    # 22 HPHP::include_impl_invoke(HPHP::String const&, bool, char const*) at hhvm:0
    # 23 HPHP::hphp_invoke(HPHP::ExecutionContext*, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, HPHP::Array const&, HPHP::VRefParamValue const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool&, std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, bool, bool, bool) at hhvm:0
    # 24 HPHP::hphp_invoke_simple(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) at hhvm:0
    # 25 ?? at hhvm:0
    # 26 HPHP::execute_program(int, char**) at hhvm:0
    # 27 HPHP::emulate_zend(int, char**) at hhvm:0
    # 28 main at hhvm:0
    # 29 __libc_start_main at /build/buildd/eglibc-2.19/csu/libc-start.c:321
    # 30 ?? at hhvm:0

    PHP Stacktrace:

    #0  createArray(Array) called at [/<...snip...>/repro.php:19]
    #1  main() called at [/<...snip...>/repro.php:25]

Code:

    <?php

    function createArray($data) {
        array(
            'A' => isset($data[0]) ? $data[0] : '', // Remove one
            'B' => isset($data[0]) ? $data[0] : '', // of these
            'C' => isset($data[0]) ? $data[0] : '', // and the
            'D' => isset($data[0]) ? $data[0] : '', // problem
            'E' => isset($data[0]) ? $data[0] : '', // goes away!
            'F' => isset($data[0]) ? $data[0] : ''  //
        );
    }

    function main() {
        $data = array('Hello world');

        // Issue occurs at $i === 100
        for($i = 1; $i < 10000; $i++) {
            createArray($data); // line 19
        }

        print('SUCCESS...?');
    }

    main(); // line 25

I'm running Laravel's Homestead environment.

    vagrant@homestead:~$ uname -a
    Linux homestead 3.13.0-46-generic #79-Ubuntu SMP Tue Mar 10 20:06:50 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

    vagrant@homestead:~$ hhvm --version
    HipHop VM 3.6.0 (rel)
    Compiler: tags/HHVM-3.6.0-0-g6ef13f20da20993dc8bab9eb103f73568618d3e8
    Repo schema: 3ab6576af394a33abbb29796c652f06b1c7640ce

I've also verified this in our virtual production environment.

    deploy@multiverse:~$ uname -a
    Linux multiverse 3.16.0-28-generic #37-Ubuntu SMP Mon Dec 8 17:15:28 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
    
    deploy@multiverse:~$ hhvm --version
    HipHop VM 3.6.1 (rel)
    Compiler: tags/HHVM-3.6.1-0-gc051feff88ba8050f33f10f7b1fb07f8d3415f9e
    Repo schema: 42f49251b5c27daf4e13cb6bcd0c7ef4824b55a3

**Comment by Orvid** [comment]
If this is still an issue, feel free to re-open, but I'm closing this for now.

https://github.com/facebook/hhvm/wiki/Human-Timeouts
