### ISSUE TITLE
Ubuntu 12.04 compiler error

### ISSUE THREAD

**Issue by robocoder** [facebook/hhvm#5083]
FYI a clean build of f58e33730312d2edcfe6e7a1b5d7c34018694e01 failed.
gcc version 4.8.1 (Ubuntu 4.8.1-2ubuntu1~12.04)

```
...
[ 43%] Building CXX object hphp/compiler/CMakeFiles/hphp_analysis.dir/analysis/emitter.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
make[2]: *** [hphp/compiler/CMakeFiles/hphp_analysis.dir/analysis/emitter.cpp.o] Error 4
make[1]: *** [hphp/compiler/CMakeFiles/hphp_analysis.dir/all] Error 2
make: *** [all] Error 2
```

This is a recent regression (sometime since last Saturday), i.e., I had a working build from 4ef02d0992cd640ae6bfd622cb66d04f94acfdde:
```
HipHop VM 3.7.0-dev (rel)
Compiler: heads/master-0-g4ef02d0992cd640ae6bfd622cb66d04f94acfdde
Repo schema: c27f8653b02bdc97d6cdeb44757784eab5689e84
```

**Comment by jwatzman** [comment]
This looks a lot like "g++ ran out of RAM and got killed by the OOM killer". How much RAM does the computer you're using to compile HHVM have, and what `-j` option do you pass to `make`?

**Comment by robocoder** [comment]
Ah yes that was it. That particular VM was misconfigured. Thanks.
