### ISSUE TITLE
Do not trust facebook hhvm open source project 

### ISSUE THREAD

**Issue by netroby** [facebook/hhvm#5084]
https://github.com/facebook/hhvm/blob/07f8201682818abdcc0aa581c9eaa991b2b04965/hphp/hack/PATENTS

Additional Grant of Patent Rights

"Software" means the Hack software distributed by Facebook, Inc.

Facebook hereby grants you a perpetual, worldwide, royalty-free, non-exclusive,
irrevocable (subject to the termination provision below) license under any
rights in any patent claims owned by Facebook, to make, have made, use, sell,
offer to sell, import, and otherwise transfer the Software. For avoidance of
doubt, no license is granted under Facebook's rights in any patent claims that
are infringed by (i) modifications to the Software made by you or a third party,
or (ii) the Software in combination with any software or other technology
provided by you or a third party.

The license granted hereunder will terminate, automatically and without notice,
for anyone that makes any claim (including by filing any lawsuit, assertion or
other action) alleging (a) direct, indirect, or contributory infringement or
inducement to infringe any patent: (i) by Facebook or any of its subsidiaries or
affiliates, whether or not such claim is related to the Software, (ii) by any
party if such claim arises in whole or in part from any software, product or
service of Facebook or any of its subsidiaries or affiliates, whether or not
such claim is related to the Software, or (iii) by any party relating to the
Software; or (b) that any right in any patent claim of Facebook is invalid or
unenforceable.

**Comment by HRMsimon** [comment]
Looks like a fairly common grant of patent rights to me. The Apache license has a very similar clause.

**Comment by netroby** [comment]
@HRMsimon There be law risk. Not funny. sir, if your company be sued by Facebook . you will lost much more than you thought

**Comment by bauerj** [comment]
> if your company be sued by Facebook  . you will lost much more than you thought

Nowhere in the text is said that you will lose your licence if Facebook sues you.

**Comment by jwatzman** [comment]
I'm not sure what the action item from this issue is, other than "please change the license", which we are not going to do. Closing.

**Comment by netroby** [comment]
Please change your license to MIT . like react js
