### ISSUE TITLE
Passing an array to `Exception` doesn't write error message to error log

### ISSUE THREAD

**Issue by r3wt** [facebook/hhvm#5089]
Just sends 500 server error and exits.

Php outputs message about wrong parameters.

http://3v4l.org/PoaGb

**Comment by Orvid** [comment]
We're a small team, and it doesn't look as though anyone in the community is actively working on this issue, so we've decided to close it. If you plan to send us a pull request resolving the issue let us know in the comments and we will re-open it and assign it to you. If you feel this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
