### ISSUE TITLE
"Name already bound" error when defining a method with the same name as a built-in function

### ISSUE THREAD

**Issue by tslettebo** [facebook/hhvm#5093]
I have a class with a method called "copy". When running the type checker, I get this error message:

/tmp/hh_server_webserveruser/hhi_230ea355/stdlib/builtins_file.hhi:88:10,13: Name already bound: copy (Naming[2012])

Doesn't the type checker distinguish between free/built-in functions and methods when matching names?

**Comment by jwatzman** [comment]
> Doesn't the type checker distinguish between free/built-in functions and methods when matching names?

No. Don't define functions with the same name as builtins. (Similar to how you can't have a class named `string` in Hack.)

**Comment by tslettebo** [comment]
Thanks for your reply.

> No. Don't define functions with the same name as builtins. (Similar to how you can't have a class named  string  in Hack.)

But these are member functions, not free functions. Having a member function with the same name as a free function (built-in or not) is perfectly legal in PHP, as well as other languages like C++ and Java.

I haven't seen anything in the Hack documentation that this is an unsupported PHP feature:

http://docs.hhvm.com/manual/en/hack.unsupported.php

I understand that PHP compatibility is very important for the Hack team, and I think that's great. What's the rationale for not supporting this valid PHP code?

**Comment by jwatzman** [comment]
Can you provide the full error message, and if possible the source for the file triggering this error?

I misunderstood your original report -- I thought you were defining a toplevel function called `copy`, and yeah that isn't going to work of course. But this code does work for me:

```hack
<?hh

class C {
  public function copy(): void {}
}
```

Which makes me suspect something else is going on.

**Comment by tslettebo** [comment]
@jwatzman:
```
<?hh

class C {
  public function copy(): void {}
}
```

Yeah, that works for me, too, so something else is going on, as you said.

We're in the middle of converting our systems to HHVM/Hack, and currently, we have a lot of error messages from the type checker, so I've just marked this as something to return to once this part passes the type checker.
