### ISSUE TITLE
exec() does not strip \f and \v from the end of the output

### ISSUE THREAD

**Issue by mjrider** [facebook/hhvm#5096]
php5 seems to strip the \f ( 0x0C, aka NP form feed )  on the end of each line for the result of exec()
hhvm, the following code demonstrates that difference when executed in php5 and hhvm

exec's documentations specifies that whitespace on the end of the line is stripped, but there is a difference in the definition of 'whitespace'
 
<?php
	exec('/bin/echo -n -e "line1\x0Cmoreline1\r\nline2\x0C"', $result, $ret);
	var_dump($result);
	$content = implode($result,"\n");
	var_dump($content);
?>

**Comment by mjrider** [comment]
after browsing the source of php and hhvm a bit more:
* hhvm calls rtrim for stripping whitespace
* php checks the last char with isspace(), and if it's a space, the char is stripped

from http://www.cplusplus.com/reference/cctype/isspace/:
For the "C" locale, white-space characters are any of:
' '	(0x20)	space (SPC)
'\t'	(0x09)	horizontal tab (TAB)
'\n'	(0x0a)	newline (LF)
'\v'	(0x0b)	vertical tab (VT)
'\f'	(0x0c)	feed (FF)
'\r'	(0x0d)	carriage return (CR)

**Comment by mjrider** [comment]
seems that \v and \f are missing, not only \f

**Comment by gfleury** [comment]
Actually HHVM trim everything else similar to php5 but '\f'
There is an PR to fix this #5107
