### ISSUE TITLE
Hack code coverage errors when running phpunit test

### ISSUE THREAD

**Issue by digra5319** [facebook/hhvm#5099]
I am trying to run phpunit tests with hack code coverage but receive the error below.

````
Fatal error: Class undefined: PHP_Token_WHERE in phar://phpunit-4.5.0.phar/php-token-stream/Token/Stream.php on line 185
````

After adding the undefined PHP_Token_WHERE class I received more errors from the classes below and added them as well to resolve them. My concern is that I tried researching theses classes and found no documentation related to hhvm/hack. Are these legitimate classes to add for resolving this error?

````
class PHP_Token_WHERE extends PHP_Token {}
class PHP_Token_ENUM extends PHP_Token {}
class PHP_Token_JOIN extends PHP_Token {}
class PHP_Token_ONUMBER extends PHP_Token {}
````

**Comment by paulbiss** [comment]
Enums are a hack [feature](http://docs.hhvm.com/manual/en/hack.enums.php) and use the enum keyword (T_ENUM), Hack supports octals in XHP via T_ONUMBER, as for the rest, they're part of a project that was never completed and will probably be removed (T_WHERE, T_JOIN).

I think if you run in PHP mode these tokens aren't available anyway.

**Comment by digra5319** [comment]
Thank you for the insight.
