### ISSUE TITLE
Building tag 3.6.0/3.6.1 fails due to error in webscalesqlclient

### ISSUE THREAD

**Issue by lavagetto** [facebook/hhvm#5100]
Steps to reproduce:

- clone the repo, checkout the HHVM-3.6.1 or 3.6.0 tags
- cmake .
- make -j8

```
Building CXX object libmysql/CMakeFiles/clientlib.dir/__/sql-common/client_authentication.cc.o
Building CXX object libmysql/CMakeFiles/clientlib.dir/__/sql/net_serv.cc.o
[100%] Building C object libmysql/CMakeFiles/clientlib.dir/__/sql-common/pack.c.o
[100%] Building C object libmysql/CMakeFiles/clientlib.dir/__/sql/password.c.o
In file included from /tmp/build/hhvm/third-party/webscalesqlclient/webscalesql-5.6/include/probes_mysql_dtrace.h:9:0,
                 from /tmp/build/hhvm/third-party/webscalesqlclient/webscalesql-5.6/include/probes_mysql.h:24,
                 from /tmp/build/hhvm/third-party/webscalesqlclient/webscalesql-5.6/sql/net_serv.cc:46:
/tmp/build/hhvm/third-party/webscalesqlclient/webscalesql-5.6/sql/net_serv.cc: In function ‘net_async_status net_write_command_nonblocking(NET*, uchar, const uchar*, size_t, const uchar*, size_t, my_bool*)’:
/tmp/build/hhvm/third-party/webscalesqlclient/webscalesql-5.6/sql/net_serv.cc:547:29: error: ‘len’ was not declared in this scope
       MYSQL_NET_WRITE_START(len);
                             ^
/tmp/build/hhvm/third-party/webscalesqlclient/webscalesql-5.6/sql/net_serv.cc:547:7: note: in expansion of macro ‘MYSQL_NET_WRITE_START’
       MYSQL_NET_WRITE_START(len);
       ^
/tmp/build/hhvm/third-party/webscalesqlclient/webscalesql-5.6/include/probes_mysql_dtrace.h:526:1: error: template argument 1 is invalid
 DTRACE_PROBE1(mysql,net__write__start,arg1)
 ^
/tmp/build/hhvm/third-party/webscalesqlclient/webscalesql-5.6/sql/net_serv.cc:547:7: note: in expansion of macro ‘MYSQL_NET_WRITE_START’
       MYSQL_NET_WRITE_START(len);
       ^
make[5]: *** [libmysql/CMakeFiles/clientlib.dir/__/sql/net_serv.cc.o] Error 1
make[5]: *** Waiting for unfinished jobs....
make[4]: *** [libmysql/CMakeFiles/clientlib.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [third-party/webscalesqlclient/build/src/webscalesqlclient-stamp/webscalesqlclient-build] Error 2
make[1]: *** [third-party/webscalesqlclient/CMakeFiles/webscalesqlclient.dir/all] Error 2
make: *** [all] Error 2
```

The solution is to apply the patch (which is already in newer commits) that you can find here:

https://gerrit.wikimedia.org/r/#/c/200513/1/debian/patches/fix-webscalesql.patch

**Comment by jwatzman** [comment]
Interesting -- what OS is this? We had no trouble building on our packaging VMs, which run fairly stock Debian 7/8 and Ubuntu 12.04/14.04/14.10.

**Comment by jwatzman** [comment]
(I'm curious what causes this to break since we haven't had any issues ourselves.)

**Comment by jrobeson** [comment]
and we have no such issues on Fedora or CentOS 7 either.

**Comment by lavagetto** [comment]
This only happens when checking out the HHVM-3.6.1 tag and checking out the third-party submodules at that point in commit history, which means you get webscalesqlclient at a specific version:

https://github.com/webscalesql/webscalesql-5.6/tree/004b6b348fdf48f0aa4e3fe1010b891d4fdb9f70

If you look at the function it's pretty clear "len" is undefined:

https://github.com/webscalesql/webscalesql-5.6/blob/004b6b348fdf48f0aa4e3fe1010b891d4fdb9f70/sql/net_serv.cc#L547

and a clear bug that has been solved in subsequent versions:

https://github.com/webscalesql/webscalesql-5.6/commit/13e32199550b144252b07cbdba9c80e1ceeef7bf

and

https://github.com/webscalesql/webscalesql-5.6/commit/3b23e80ac275f3c20729c78dd712085b9e6d0141#diff-948a62114b2d496cdb951e94147d9491

the issue has been reported originally here:

https://github.com/webscalesql/webscalesql-5.6/issues/17

**Comment by jwatzman** [comment]
Aha, here's why we didn't see it before. From the fixrev:

> This code is not actully built (the macro is defined to empty), when not
> built with dtrace (or systemtap) so we did not detect this problem.

I'll bump the submodules later.

**Comment by fredemmott** [comment]
This was fixed a while back.
