### ISSUE TITLE
A lot of the async MySQL API has no generics

### ISSUE THREAD

**Issue by oyamauchi** [facebook/hhvm#5102]
Even something trivial like `AsyncMysqlClient::connect()` has a return type of `ExternalThreadEventWaitHandle`, which is correct but would be much more expressive as `Awaitable<?AsyncMysqlConnection>`. I'm sure there are other functions that could use similar treatment.

This does have the potential "downside" that it would introduce much stricter checking and cause new errors -- e.g. how many people are actually null-checking the result of `AsyncMysqlClient::connect`?

It looks like it's all been this way since the HNI conversion, which was before it was open-sourced.

**Comment by paulbiss** [comment]
Hack doesn't read types from HNI files (yet), but looking at the corresponding HHI file it doesn't appear to have a return type declared at all.

https://github.com/facebook/hhvm/blob/master/hphp/hack/hhi/stdlib/builtins_async_mysql.hhi#L67

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

The hhi for AsyncMysql is now far better than you was when you made files this issue.
A quick guestimate by scrolling through is that more than 95% of the function in there are typed.
Some work for this was done around [4.24.0](https://hhvm.com/blog/2019/09/23/hhvm-4.24.0.html) and more types were added later.

**Comment by oyamauchi** [comment]
Nice, thanks.
