### ISSUE TITLE
jpeglib.h: No such file or directory - CentOS 7

### ISSUE THREAD

**Issue by Sakretsos** [facebook/hhvm#5103]
Hello there, as title says i try to install hhvm on centos 7 i have already install libjpeg 1.4 ( latest rpms ) but i get this error :100:

[ 76%] Building CXX object hphp/runtime/ext/CMakeFiles/hphp_runtime_ext.dir/gd/libgd/gd_jpeg.cpp.o
/tmp/hhvm/hphp/runtime/ext/gd/libgd/gd_jpeg.cpp:38:21: fatal error: jpeglib.h: No such file or directory
#include "jpeglib.h"

compilation terminated.
make[2]: *** [hphp/runtime/ext/CMakeFiles/hphp_runtime_ext.dir/gd/libgd/gd_jpeg.cpp.o] Error 1
make[1]: *** [hphp/runtime/ext/CMakeFiles/hphp_runtime_ext.dir/all] Error 2
make: *** [all] Error 2

**Comment by jrobeson** [comment]
do you have /usr/include/jpeglib.h ?

**Comment by jrobeson** [comment]
what cmake command did you use?

**Comment by no1youknowz** [comment]
Are you installing libjpeg-turbo-devel ?

    yum install libjpeg-turbo-devel

**Comment by jrobeson** [comment]
in any case though, hhvm should error out at the cmake step if it can't find any required libraries.

**Comment by englianhu** [comment]
```
sudo yum -y install libjpeg*
```

**Comment by Orvid** [comment]
LibJpeg has been properly required for a while now.
