### ISSUE TITLE
HHVM cannot be build on aarch64. Dependency says "SmallLocks.h is currently x64-only."

### ISSUE THREAD

**Issue by Alexander-Alexeev** [facebook/hhvm#5106]
Log from the Build.
[  1%] Building CXX object third-party/folly/CMakeFiles/folly.dir/folly/wangle/bootstrap/ServerBootstrap.cpp.o
In file included from /home/alexander/hhvm-clean/hhvm-src/hhvm/third-party/folly/folly/wangle/rx/Observable.h:24:0,
                 from /home/alexander/hhvm-clean/hhvm-src/hhvm/third-party/folly/folly/wangle/concurrent/ThreadPoolExecutor.h:21,
                 from /home/alexander/hhvm-clean/hhvm-src/hhvm/third-party/folly/folly/wangle/concurrent/IOThreadPoolExecutor.h:21,
                 from /home/alexander/hhvm-clean/hhvm-src/hhvm/third-party/folly/folly/wangle/bootstrap/ServerBootstrap-inl.h:20,
                 from /home/alexander/hhvm-clean/hhvm-src/hhvm/third-party/folly/folly/wangle/bootstrap/ServerBootstrap.h:18,
                 from /home/alexander/hhvm-clean/hhvm-src/hhvm/third-party/folly/folly/wangle/bootstrap/ServerBootstrap.cpp:16:
/home/alexander/hhvm-clean/hhvm-src/hhvm/third-party/folly/folly/SmallLocks.h:51:3: error: #error "SmallLocks.h is currently x64-only."
 # error "SmallLocks.h is currently x64-only."

**Comment by edwinsmith** [comment]
Were you able to fix this by modifying folly to use std::mutex or (or another std class)?

**Comment by sskblr** [comment]
Hi Alexander-Alexeev,
 
Could you make progress compiling HHVM for ARM64? I am stuck with this and many other compile issues in hphp code.

Thanks,
sskblr

**Comment by apinski-cavium** [comment]
https://github.com/facebook/folly/pull/190

**Comment by apinski-cavium** [comment]
https://github.com/facebook/folly/pull/187

**Comment by sskblr** [comment]
Thanks you for the links.

**Comment by Orvid** [comment]
Fixed upstream many ages ago.
