### ISSUE TITLE
\nFatal error: syntax error, unexpected T_ELSE, expecting $end in<Redacted>/blog/wp-content/themes/lustrous/functions/theme-functions.php on line 1

### ISSUE THREAD

**Issue by r3wt** [facebook/hhvm#5115]
but line 1 of the file is

`<?php`

:confused:

**Comment by jrobeson** [comment]
can you replicate when using php? If you can, then it's a bug in your code, if you can't, then you're going to have to link to the code otherwise this issue cannot be reproduced.

**Comment by r3wt** [comment]
its a bug in hhvm. obviously. i need to delete the jit cache

**Comment by r3wt** [comment]
rolling back to 3.5.0 version used in dev, issue dissapears.

**Comment by paulbiss** [comment]
Can you paste a contained example showing the error? Hard to tell exactly what's going on here from from what you've said.

**Comment by r3wt** [comment]
MVC SLIM APP contains '/blog' route. this route includes the wp index.php file

**Comment by paulbiss** [comment]
If you can come up with an isolated example that has the same problem it would be really helpful. Without more to go on, unfortunately, I'm not sure how much we're going to be able to do.

**Comment by r3wt** [comment]
it works on 3.5.0 and doesn't in 3.6.1 what did you change?

**Comment by paulbiss** [comment]
There were 580 commits spanning 3,612 files. You're welcome to bisect, but as I've said, with such little information there's not really anything I can do to narrow it down for you.

https://github.com/facebook/hhvm/compare/HHVM-3.5...HHVM-3.6

**Comment by aingram** [comment]
I can repro by running ```hhvm functions/theme-functions.php```, a file found in https://downloads.wordpress.org/theme/lustrous.1.3.1.zip. Repro'd in hhvm 3.6.2. FYI, the file has Mac-style line endings (carriage return, no newline). I'm guessing that's the trigger of the problem, and it's probably why the error is reported on "line 1."

**Comment by r3wt** [comment]
@aingram  you can use mac2unix to convert the line endings.
