### ISSUE TITLE
IntlDateFormatter not supported by type checker?

### ISSUE THREAD

**Issue by tslettebo** [facebook/hhvm#5116]
The following code gives an error message, but runs fine on HHVM (when passed appropriate arguments to the constructor):

Unbound name: IntlDateFormatter (an object type) (Naming[2049])

```
<?hh // strict

function f(): void
{
  $test=new IntlDateFormatter();
}
```

**Comment by paulbiss** [comment]
Looks like we're missing an HHI file for IntlDateFormater

**Comment by tslettebo** [comment]
Thanks, I can add a "decl" file locally.

**Comment by paulbiss** [comment]
If you want to add the definitions [here](https://github.com/facebook/hhvm/blob/master/hphp/hack/hhi/stdlib/builtins_icu.hhi) you can also send us a PR so that it's fixed in future releases.

**Comment by tslettebo** [comment]
@paulbiss Thanks for the tip. Shouldn't these be in their own HHI files, like IntlDateFormatter.hhi, rather than in builtins_icu.hhi?

It seems DomDocument is missing, too.

Maybe adding the standard library functions and classes to the type checker is a work in progress, or are you adding them on an as-needed basis?

**Comment by paulbiss** [comment]
It's definitely a work in progress. Many of these were added as we converted FB to hack, and many others were added by PRs as external developers encountered standard library functions they needed.

@jwatzman can better answer how best to divide these up (putting them in their own file sounds like it's probably a good idea).

You can also use [HH_FIXME](https://github.com/hhvm/hack-hhvm-docs/issues/359) to mark specific expressions that need to be fixed, which may cut down on the amount of files you need to remove strict from (we don't seem to have documentation for it yet). I'm sure Josh can chime in with advice on things of this nature.

**Comment by tslettebo** [comment]
Thanks for the information. I've been using "// UNSAFE" wherever I can, rather than removing "strict", in order to keep as much as possible of the code in strict mode, but it can't be used for code outside functions, like class instance variables.

I've tried HH_FIXME and it works fine. Now we can get those files back to strict more, again.

**Comment by tslettebo** [comment]
What are HHI files, anyway (I can't find any documentation on them), where can I find them, and are these compiled in, or parsed at server startup?

**Comment by staabm** [comment]
See https://github.com/facebook/hhvm/tree/master/hphp/hack/hhi

**Comment by tslettebo** [comment]
Thanks, I had actually found those (Paul linked to them in an earlier post). What I meant was: Where in the file system, after you have installed HHVM, can these be found, or are they compiled in, because I can't find them?

Anyway, it seems *.hhi files for mysqli is missing, so I'm working on adding that. Please let me know if I've overlooked it, but I get type checker errors both for the OO and the procedural API.

**Comment by paulbiss** [comment]
I don't think we have any for mysqli yet. Right now the ones that are bundled with hhvm/hh_server are actually part of the hh_server binary, but as you work on them you can put them anywhere in your document root and hack will find them while you wait for them to get upstreamed.

**Comment by jwatzman** [comment]
Yeah, you can play with brand-new hhi files just by dropping into your project (but you can't modify/replace builtin ones this way, you'll have to actually change them in the source and rebuild and then do `hh_client restart`).

How you want to organize them is up to taste. They're mostly in huge long files right now since that's the way the tool that originally built them spit them out, but there's no good reason for that, so if you think they should go in a separate file (they probably should) then go for it.

**Comment by tslettebo** [comment]
Thanks, both of you. Yes, I noticed that if I put an *.hhi anywhere in the document root, it got parsed and the error messages disappeared.

>How you want to organize them is up to taste. They're mostly in huge long files right now since that's the way the tool that originally built them spit them out, but there's no good reason for that, so if you think they should go in a separate file (they probably should) then go for it.

I notice that the [stdlib](https://github.com/facebook/hhvm/tree/master/hphp/hack/hhi/stdlib) directory contains one file per extension, which makes sense, and there's even one for [mysql](https://github.com/facebook/hhvm/blob/master/hphp/hack/hhi/stdlib/builtins_mysql.hhi), so I guess we can just follow that pattern with the mysqli extension.

**Comment by simonwelsh** [comment]
There's a HHI file `IntlDateFormatter` in 3.9
