### ISSUE TITLE
Add typechecker support for "self" type

### ISSUE THREAD

**Issue by tslettebo** [facebook/hhvm#5117]
The following runs fine on HHVM:

```
<?php

$a=new Length(1);
$b=new Length(2);

echo $a->add($b)->value;

class Length
{
  public function __construct($value)
  {
    $this->value=$value;
  }

  public function add(self $other)
  {
    return new self($this->value+$other->value);
  }

  public $value;
}

?>
```

Yet, when converted to Hack, I get an error message (apart from the top-level code due to "strict"):

Unbound name: self (an object type) (Naming[2049])

```
class Length
{
  public function __construct(num $value)
  {
    $this->value=$value;
  }

  public function add(self $other): self
  {
    return new self($this->value+$other->value);
  }

  public num $value;
}
```

**Comment by jwatzman** [comment]
Huh, I thought we supported `self` like this. @elgenie?

**Comment by jwatzman** [comment]
(But yeah I can repro with your example.)

**Comment by jwatzman** [comment]
Oops, I misread the issue. I thought you were complaining about `new self`, which we do indeed correctly support.

The problem is that we don't support `self` as a type. For now, you should either just use the name of the class, or if you need the late-bound version, use `this`.

We might want to eventually support `self`, it could be useful in traits, but it's a super low pri feature request.

**Comment by tslettebo** [comment]
Thanks for your reply. Yes, for the return type, "this" may be used, but you can't use it for the parameter type,

The advantage of the "self" type is of course avoiding duplication: Without it you have to write the class name every time you want to refer to the current class (I haven't tried it, but I assume __CLASS__ won't work, either), and this class has many member functions using the "self" type.

Since using "self" works in regular PHP, and since you have a stated aim for compatility with PHP (this page - http://hhvm.com/blog/category/parity - states "Compatibility is still a huge priority for us"),, you might want to bump this up a little from "super low pri feature request".

It also seems to me that supporting "self" as a synonym to the current class name shouldn't be that complex to implement, but then again, I don't know the HHVM implementation.

Yes, it's possible to do without it, so what we'll do is to replace "self" with the class name in our code.

**Comment by simonwelsh** [comment]
`self` works fine in HHVM. The problem here is with the Hack typechecker, which has nothing to do with PHP compatibility (or PHP at all for that matter)

**Comment by tslettebo** [comment]
Ah, yes, you're right. In that case, I agree that this need not be given priority.

**Comment by lexidor** [comment]
The `self` typehint cannot be used in Hack. Compatibility with PHP has been dropped with hhvm version 4.0.0. Either use `this` or the name of the surrounding class, depending on context.
