### ISSUE TITLE
mysqli_stmt::fetch fails when fetching a bit field

### ISSUE THREAD

**Issue by rainbow-alex** [facebook/hhvm#5119]
When fetching a row with a BIT field, nothing is bound. No error is shown or logged.

```
<?php
// create table some_table ( some_bit_field bit(1), some_int_field int(1) );
// insert into some_table ( some_bit_field, some_int_field ) values ( 1, 1 );
$c = mysqli_connect("localhost", "root", "", "hhvm_test");
$stmt = $c->prepare("select some_bit_field from some_table");
$stmt->execute();
$stmt->bind_result($a);
$stmt->fetch();
var_dump($a);
```

Expected: `int(1)`
Got: `NULL`

Not just the bit field, but all fields fail to bind. E.g. if I execute `select * ...` and fetch, _both_ bindings are `NULL`.

I am running 3.6.1:

```
$ hhvm --version
HipHop VM 3.6.1 (rel)
Compiler: tags/HHVM-3.6.1-0-gc051feff88ba8050f33f10f7b1fb07f8d3415f9e
Repo schema: 42f49251b5c27daf4e13cb6bcd0c7ef4824b55a3
```

**Comment by Orvid** [comment]
This occurs for me as well.

It would probably be best to include the selection of the second column in the test to better illustrate the scope of the problem.
```PHP
// create table some_table ( some_bit_field bit(1), some_int_field int(1) );
// insert into some_table ( some_bit_field, some_int_field ) values ( 1, 1 );
$c = mysqli_connect("localhost", "root", "", "hhvm_test");
$stmt = $c->prepare("select some_bit_field, some_int_field from some_table");
$stmt->execute();
$stmt->bind_result($a, $b);
$stmt->fetch();
var_dump($a);
var_dump($b);
```

**Comment by Orvid** [comment]
Hrmm.... I should probably fix the issue that I ran into myself >_>.....

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Hhvm dropped support for mysqli with hhvm [4.9.0](https://hhvm.com/blog/2019/06/10/hhvm-4.9.0.html).
