### ISSUE TITLE
HHVM stream_select() behaviour differs from PHP stream_select()

### ISSUE THREAD

**Issue by satakecode** [facebook/hhvm#5120]
Nothing too serious but could cause some complications for compatibility with old PHP code.

 function stream_select ( array &$read , array &$write , array &$except , int $tv_sec [, int $tv_usec = 0 ] ): int 

In PHP the array $read will maintain its original key order, HHVM does not.

$read = array(0 => (resource 0), 1 => (resource 1), 2 => (resource 2) ...);
if( stream_select($read, $w=NULL, $err=NULL, NULL) > 0) {
     var_dump($read);
     // In PHP this would come with the original key order -> array(2 => (resource 2))
     // HHVM will reassign the keys from 0 -> array(0 => (resource 2))
}

Like I said, something minor.

**Comment by Orvid** [comment]
We're a small team, and it doesn't look as though anyone in the community is actively working on this issue, so we've decided to close it. If you plan to send us a pull request resolving the issue let us know in the comments and we will re-open it and assign it to you. If you feel this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
