### ISSUE TITLE
Allow extensions to add to the auto alias list

### ISSUE THREAD

**Issue by simonwelsh** [facebook/hhvm#5127]
It would be nice if extensions could add to the map returned by `Parser::getAutoAliasesClassesHelper` or `Parser::getAutoAliasedClasses`.

I'd like to provide some Hack wrappers to ext/pgsql including null-on-failure versions of the pg_* functions, so would like to hide the global namespace functions.

**Comment by paulbiss** [comment]
This feature request is not actively being worked on. We would happily consider a pull request implementing it. If you plan to work on this issue let us know in the comments and we will re-open the issue and assign it to you. If you feel strongly that this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
