### ISSUE TITLE
Can't use $this in assertions

### ISSUE THREAD

**Issue by Zenexer** [facebook/hhvm#5128]
Example code: (http://3v4l.org/vLuJS)

``` php
<?php

assert_options(ASSERT_ACTIVE, 1);
assert_options(ASSERT_BAIL, 1);

class A
{
    private $isTrue = true;
    
    public function run()
    {
        assert('$this->isTrue');
        echo 'Success';
    }
}

$a = new A();
$a->run();
```

Result in PHP 5.0.0+:

    Success

Result in HHVM:

    $this is null

Result in [adapted code](http://3v4l.org/ohfEi) for PHP 4 with PHP:

    Success

Result in [adapted code](http://3v4l.org/ohfEi) for PHP 4 with HHVM:

    $this is null

At the very least, I would expect the same result as `assert('false');`.  The current error is difficult to debug.  However, full support for `$this` would be ideal.

**Comment by Zenexer** [comment]
Context:

We make use of assertions heavily in code that deals with monetary transactions to double-check sanity of state.  Since most of this code is object-oriented, many of the assertions rely on `$this`.  While the assertions can be safely disabled for the time being, it would be ideal to have that extra layer of protection.

**Comment by Zenexer** [comment]
Looks like there are other assertion issues, too.  HHVM dies with error code 139 on some pages that are heavy on assertions.  No error logs, no output.

**Comment by r3wt** [comment]
@Zenexer yep, i have some mysterious results as well with assertions. scrapped em all for alternative strategies.

**Comment by fredemmott** [comment]
@paulbiss: this should probably change to high pri or we revert the assertions-on-by-default change

**Comment by mwjames** [comment]
This issue becomes somewhat of a pain stick, it would be nice to see this resolved as I'm reluctant to make a HHVM only `if .. else` check.

**Comment by simonwelsh** [comment]
@mwjames you can use an expression instead of a string, in which `$this` works as expected (e.g. `assert($this->someFunc())` instead of `assert('$this->someFunc()')`)

**Comment by mwjames** [comment]
> you can use an expression instead of a string, in which $this works as expected

I don't have access locally to HHVM but a user on HHVM 3.13.1 tried to use the modified version of `assert( '$this->m_unitfactors[$this->m_unitin] != 0' )` without `'` and got the same error, he then quote: "... as you suggested and it gave the same errror ... I downgraded to HHVM 3.6.6 ..." since the error doesn't occur with 3.6

**Comment by Orvid** [comment]
The error doesn't occur in 3.6.6 because asserts are disabled by default on it.

**Comment by mwjames** [comment]
> The error doesn't occur in 3.6.6 because asserts are disabled by default on it.

Which is fine.

All this didn't really bother me until now but since an actually user hit the incompatibility wagon, I thought I let you know.

**Comment by SiebelsTim** [comment]
> I downgraded to HHVM 3.6.6 ..." since the error doesn't occur with 3.6

A much much much better way would be disabling assertions in a newer version, as it's the same workaround he did with downgrading.
Which confirms that most php developers have no idea about assertions.

**Comment by Orvid** [comment]
As of HHVM 3.12 we no longer complain about `$this` being `null`, but instead complain that `Cannot access private property A::$isTrue`, which is the same error that PHP7.1 is producing.
