### ISSUE TITLE
Async socket_accept

### ISSUE THREAD

**Issue by steelbrain** [facebook/hhvm#5129]
It's a nice to have feature, It'll allow us to accept multiple socket connections concurrently. Which means, that we will be able to create a unix socket and a pool of hhvm processes and have them communicate with each other in real time.

**Comment by r3wt** [comment]
concurrently**

**Comment by steelbrain** [comment]
I was not planning it to use for websockets right now, but I have in the past. HHVM would become a swiss army knife with this feature :wink:
I am primarily gonna use it for a redis like no-sql data store. (that I have currently implemented in NodeJS until hhvm supports it)

**Comment by paulbiss** [comment]
If you can use streams you could pretty easily implement an async accept on top of the async [stream_await](https://github.com/facebook/hhvm/blob/master/hphp/runtime/ext/stream/ext_stream.php#L323-L341) api.

**Comment by paulbiss** [comment]
Actually that function should work with any file or socket resource. So yeah, it should do what you want.

**Comment by steelbrain** [comment]
@paulbiss The last time I tried (yesterday), I was unable to accept multiple sockets co-currently, and that is what was asking for :)
I have to disconnect the accepted socket to be able to accept a new one.

**Comment by paulbiss** [comment]
Hmm, I don't think stream sockets have this limitation.

**Comment by steelbrain** [comment]
Repro Case:
```bash
cd /tmp
git clone https://github.com/steelbrain/HHVM-Stream-Test
#Terminal 1
hhvm Example.hh # Launch the Server
hhvm Client.hh # Connect to the Server
```

Expected Output:

```
# Terminal 1

Client Connected
Client Sent Data: HELL YEAH
Client Connected
Client Sent Data: HELL YEAH
Client Connected
Client Sent Data: HELL YEAH
Client Connected
Client Sent Data: HELL YEAH
Client Connected
Client Sent Data: HELL YEAH
Client Connected
Client Sent Data: HELL YEAH
Client Disconnected
Client Disconnected
Client Disconnected
Client Disconnected
Client Disconnected
Client Disconnected

# Terminal 2

SENT: 5
SENT: 1
SENT: 2
SENT: 6
SENT: 3
SENT: 4
```

Actual Output:

```
# Terminal 1

Client Connected
Client Sent Data: HELL YEAH
Client Disconnected
Client Connected
Client Sent Data: HELL YEAH
Client Disconnected
Client Connected
Client Sent Data: HELL YEAH
Client Disconnected
Client Connected
Client Sent Data: HELL YEAH
Client Disconnected
Client Connected
Client Sent Data: HELL YEAH
Client Disconnected
Client Connected
Client Sent Data: HELL YEAH
Client Disconnected

# Terminal 2
SENT: 5
SENT: 1
SENT: 2
SENT: 6
SENT: 3
SENT: 4
```

You can see that the previous client is disconnected before connecting to a previous one.

**Comment by paulbiss** [comment]
I see a couple of issues, you don't ever await the wait handle that the callback returns [here](https://github.com/steelbrain/HHVM-Stream-Test/blob/master/Server.hh#L12) so it's never actually guaranteed to complete, and I see a bunch of async functions calling each other, but I don't actually see any calls to an async primitive such as stream_await that would allow you to asynchronously wait for data to arrive on a socket.

**Comment by steelbrain** [comment]
@paulbiss Man!!! You rock! I'll be posting my complete solution on how I got it to work soon.

**Comment by steelbrain** [comment]
https://github.com/steelbrain/HHVM-Async-Server
