### ISSUE TITLE
Typed array type alias problem

### ISSUE THREAD

**Issue by tslettebo** [facebook/hhvm#5133]
The following works:

```
<?hh // strict

type Test = array<int>;

f();

function f(array<int> $t = [1]): void
{
  var_dump($t);
}
```

However, if you change the function definition, changing "array<int>" to "Test", it fails when you run it:

"Default value for parameter t with type Array needs to have the same type as the type hint Test "

Both versions pass the type checker.

**Comment by paulbiss** [comment]
Hmm, looks like a bug [here](https://github.com/facebook/hhvm/blob/b32415fd623c0b81a643776016d9defa6678ba5c/hphp/compiler/expression/parameter_expression.cpp#L189) where we check the default value type at compile time. I don't see anything here dealing with the possibility of a type alias.

**Comment by HRMsimon** [comment]
We've run into this with shapes as well.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

It appears like this problem was fixed at some point, but I can't find the blogpost for it.
Your repro var_dump()'s `array[1]{ [0] => int(1) }`.

```Hack
<<__EntryPoint>>
function main(): void {
  f();
}

type Test = array<int>;

function f(Test $t = varray[1]): void {
  var_dump($t);
}

```
