### ISSUE TITLE
Error running PHP_CodeSniffer phar.

### ISSUE THREAD

**Issue by leewillis77** [facebook/hhvm#5140]
Grabbing the current release of PHP CodeSniffer as a PHAR:

phpcs.phar curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar

On PHP (v5.5.14), the phar is executed as expected:

```
$ php phpcs.phar -h
Usage: phpcs [-nwlsaepvi] [-d key[=value]] [--colors] [--no-colors]
[...]
```

The same phar run through hhvm (v3.6.1) fails with a Fatal Error:

```
$ hhvm phpcs.phar -h

Fatal error: syntax error, unexpected '}', expecting $end in phar://phpcs.phar/CodeSniffer/CLI.php on line 1
```

Linting the phar reports no syntax errors.
`$ hhvm -l phpcs.phar 
No syntax errors detected in phpcs.phar`

**Comment by barbu110** [comment]
Same problem here on HHVM 3.12!

**Comment by jesseschalken** [comment]
Running the file from https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar under HHVM 3.19.1 seems to work now.
