### ISSUE TITLE
Support for conditionally defined constants

### ISSUE THREAD

**Issue by tslettebo** [facebook/hhvm#5146]
Is there a way to make the following pass the type checker?
```
<?hh // strict

function f(): void
{
  if(defined("TEST") && TEST)
    echo "Test";
}
```
It gives the error message: "Unbound name: TEST"

So far I've worked around it, placing constant definitions in an HHI file.

**Comment by r3wt** [comment]
remove the `binary and` then everything after it?

**Comment by tslettebo** [comment]
Thanks for the suggestion. The problem is, the constant might or might not be defined, and when it's defined, it may be true or false.

It should only print "Test" if it's both defined as well as being true.

I guess we could change that, and either check for if the constant is defined, or make sure it's always defined, and check for true/false.

**Comment by jwatzman** [comment]
The typechecker needs to know everything that's defined, and has no notion of conditional declaration like this. Basically: we need to know the type of `TEST`.

What you can do is to have a set of variables that are always defined, but will be set to either `true` or `false` depending on the environment. FB does something like a big bitmask in `$_ENV` somewhere, with convenience functions to check for specific bits, if you want to go that route -- but I'm not sure if you can do that in strict mode.
