### ISSUE TITLE
MD5 serialize null crash

### ISSUE THREAD

**Issue by fire015** [facebook/hhvm#5147]
Running the following in hhvm 3.6.0:

```echo md5(serialize(null));```

Results in:

```Process exited with code 137.```

http://3v4l.org/TkRPf

However doing the equivalent:

```echo md5('N;');```

Will result in the correct MD5 hash.

**Comment by bauerj** [comment]
Can't confirm this:

root@bauerj ~/test # cat > 5147.php
<?php
echo md5(serialize(null));
root@bauerj ~/test # php5 5147.php
dcca48101505dd86b703689a604fe3c4#                                                                                                     root@bauerj ~/test # hhvm 5147.php
dcca48101505dd86b703689a604fe3c4#
