### ISSUE TITLE
DateTimeImmutable microseconds stripped when updating the TimeZone

### ISSUE THREAD

**Issue by nyamsprod** [facebook/hhvm#5152]
When using `DateTimeImmutable::setTimeZone` the microseconds part seems to be truncated/stripped.

http://3v4l.org/suejm

``` php
    $d = new DateTimeImmutable('2012-02-01 00:00:00.123456');
    $d = $d->setTimeZone(new DateTimeZone('UTC'));
    echo $d->format('u'); // output '000000'
```

**Comment by nyamsprod** [comment]
This bug may be related since it also only affected `DateTimeImmutable`.

http://3v4l.org/vIJ2E

```php
    $d = new DateTimeImmutable('2012-01-01 00:00:00.123456');
    $new = $d->add(new DateInterval('PT3H'));
    echo $new->format('u'), PHP_EOL; //outputs '000000'
```
Altering `DateTimeImmutable` remove the microseconds data

**Comment by jesseschalken** [comment]
The 3v4l links (https://3v4l.org/suejm, http://3v4l.org/vIJ2E) shows the same result on HHVM and PHP now.
