### ISSUE TITLE
nginx ssi not worked with hhvm

### ISSUE THREAD

**Issue by 6api** [facebook/hhvm#5153]
code in my php file
```
<!--#include file="ssi/head.html"-->
```

it's no problem with nginx+php, but not worked with nginx+hhvm

how can i fix this?

**Comment by paulbiss** [comment]
Nginx is responsible for processing the ssi lines in the response, is hhvm not echoing them out? Maybe there's something wrong with your nginx configuration? It would help to know more about what's happening here.

**Comment by 6api** [comment]
i have fixed this
just disable gzip in hhvm.

**Comment by jrobeson** [comment]
maybe this this ticket should be retitled "Don't gzip output by default" or something like that?

**Comment by idr0id** [comment]
@6api could you explain me, how did you disable gzip?

**Comment by boynet** [comment]
@idr0id 
I can confirim this bug nginx ssi not working until putting 
````
hhvm.server.gzip_compression_level = 0
````
in /etc/hhvm/php.ini.

turn gzip on, on nginx conf working good

**Comment by alex-mashin** [comment]
It looks like this is nginx's problem not HHVM's. The same happens when apache works behind nginx and serves compressed pages. See http://habrahabr.ru/post/180019/, first part, for details.
