### ISSUE TITLE
Bizarre slowdown with php-di library

### ISSUE THREAD

**Issue by moberemk** [facebook/hhvm#5154]
I've been using the [php-di](https://github.com/mnapoli/PHP-DI) library as my dependency injection container because its autowiring capabilities are pretty fantastic. Problem is, HHVM seems to run the script significantly slower as described in my issue https://github.com/mnapoli/PHP-DI/issues/227. At least part of the issue is because I'm running it on a Vagrant box, and app performance is significantly increased overall when not running through Vagrant, but it's still way slower than with vanilla PHP.

Any insight as to what might be causing that?

**Comment by paulbiss** [comment]
I'm not familiar with php-di but if you're running it as script or timing any of the first few requests then what you're going to see is the time we spend in the JIT generating machine code. If you are running this as a script (unit tests?) then I'd suggest turning off the JIT (hhvm.jit=false), if you're running a server then send some warmup requests (at minimum 12) before you start benchmarking.

Obviously turning off the JIT Is less than ideal, but for a script there's no opportunity to reuse the JIT'ed code anyway unless it's an extremely long running script.

**Comment by moberemk** [comment]
That was something I checked early on, and there IS a noticeable performance improvement which I can measure over the course of a few repeated requests, with the average request going from over a minute end-to-end time to ~550ms on average, with most of that coming in during the DI container setup.

**Comment by Orvid** [comment]
This issue has been waiting for more info for more than 2 weeks. Closing for now, feel free to re-open it if you can provide more info.

https://github.com/facebook/hhvm/wiki/Human-Timeouts
