### ISSUE TITLE
Can't return an array of references

### ISSUE THREAD

**Issue by Orvid** [facebook/hhvm#5155]
I ran into this while writing a thin wrapper layer around statement preparation. Basically the issue is that, although `$results` shows up as containing references within `refArray`, the value it returns no longer are references.

```PHP
function refArray($arr)
{
	var_dump($arr);
	$refs = [];
	foreach ($arr as $key => $value)
		$refs[$key] = &$arr[$key];
	var_dump($refs);
	return $refs;
}

$arr = [3, "hello", 0.8, null];
$referenceArray = refArray($arr);
echo "----------------------\r\n";
var_dump($arr);
var_dump($referenceArray);
```

Prints out this:
```
array(4) {
  [0]=>
  int(3)
  [1]=>
  string(5) "hello"
  [2]=>
  float(0.8)
  [3]=>
  NULL
}
array(4) {
  [0]=>
  &int(3)
  [1]=>
  &string(5) "hello"
  [2]=>
  &float(0.8)
  [3]=>
  &NULL
}
----------------------
array(4) {
  [0]=>
  int(3)
  [1]=>
  string(5) "hello"
  [2]=>
  float(0.8)
  [3]=>
  NULL
}
array(4) {
  [0]=>
  int(3)
  [1]=>
  string(5) "hello"
  [2]=>
  float(0.8)
  [3]=>
  NULL
}
```

I'm using v3.6.1 from the Ubuntu 14.04 repository (`3.6.1~trusty`).

For the moment I've managed to work around it by passing `$arr` in by-reference. I believe the issue here is actually that, for some reason, `$arr` is being returned from the function rather than `$refs`. When passing in `$arr` by-reference, using the same function body, it actually modifies the values of `$arr` to be the references that are supposed to be in `$refs`. As I've probably failed to explain my change and it's (wrong) behavior properly, this code (the only addition is the `&` before `$arr` in the function definition):

```PHP
function refArray(&$arr)
{
	var_dump($arr);
	$refs = [];
	foreach ($arr as $key => $value)
		$refs[$key] = &$arr[$key];
	var_dump($refs);
	return $refs;
}

$arr = [3, "hello", 0.8, null];
$referenceArray = refArray($arr);
echo "----------------------\r\n";
var_dump($arr);
var_dump($referenceArray);
```
ouptuts this:
```
array(4) {
  [0]=>
  int(3)
  [1]=>
  string(5) "hello"
  [2]=>
  float(0.8)
  [3]=>
  NULL
}
array(4) {
  [0]=>
  &int(3)
  [1]=>
  &string(5) "hello"
  [2]=>
  &float(0.8)
  [3]=>
  &NULL
}
----------------------
array(4) {
  [0]=>
  &int(3)
  [1]=>
  &string(5) "hello"
  [2]=>
  &float(0.8)
  [3]=>
  &NULL
}
array(4) {
  [0]=>
  &int(3)
  [1]=>
  &string(5) "hello"
  [2]=>
  &float(0.8)
  [3]=>
  &NULL
}
```

**Comment by paulbiss** [comment]
This is the same behavior exhibited by both PHP 5 and 7 (http://3v4l.org/Ihmh2).

The problem is that arrays in PHP have value semantics, so unless refArray takes its parameter as a reference what you get is a /copy/ of the array passed in. When you return from refArray that copy is destroyed-- at which point the reference counts of the values in `$refs` return to 1 and they cease to be references.

**Comment by Orvid** [comment]
Ah, I'd completely forgotten about arrays being passed by-value.
