### ISSUE TITLE
How to go from untyped data to typed array?

### ISSUE THREAD

**Issue by tslettebo** [facebook/hhvm#5156]
We're currently converting our systems to Hack, and going one step at a time, we're going from arrays to typed arrays (rather than collections).

We've run into a problem when a database query returns a result of vaue "mixed", how to make the type checker understand that it has a specific format.

The problem is illustrated with the following simplified version of our database query function:

```
<?hh // strict

type RawRecordSet = array<array<arraykey,string>>;

function fetch_recordset(string $sql): RawRecordSet
{
  $db_connection=mysqli_connect(DB_HOST,DB_USERNAME,DB_PASSWORD,DB_DATABASE);

  $result=mysqli_query($db_connection,$sql);

  $result_array=mysqli_fetch_all($result,MYSQLI_ASSOC);

  return $result_array;
}
```

// The following is found in builtins_mysqli.hhi:

```
function mysqli_fetch_all(mysqli_result $result, int $resulttype = MYSQLI_NUM): mixed;
```

The above code gives these error messages:
test.php:13:10,22: Invalid return type (Typing[4110])
  test.php:5:40,51: This is an array (used like a vector)
  builtins_mysqli.hhi:189:81,85: It is incompatible with a mixed value

I'd appreciate any suggestions about how we may go from mixed to array<array<arraykey,string>> like this.

If it's not possible using typed arrays, is it possible using collections, and if so, how?

**Comment by jwatzman** [comment]
There are a couple of ways to do this.

You could actually convince the typechecker that your data is what you say it is, through a cumbersome series of asserts, something like this:

```hack
$result_array = mysqli_fetch_all($result, MYSQLI_ASSOC);
invariant(is_array($result_array), 'expected array');

$ret = array();
foreach ($result_array as $result) {
  invariant(is_array($result), 'expected array');

  $sub_ret = array();
  foreach ($sub_ret as $k => $v) {
    invariant(is_string($v), 'expected string');
    $sub_ret[$k] = $v;
  }

  $ret[] = $sub_ret;
}

return $ret;
```

If you want to fully assert that the types really are what you say, that's what you'll have to do. (FB actually has a library for nicely expressing these nested assertions, which I hope we can open source at some point.)

Alternatively, you can just [use the `// UNSAFE` annotation](http://docs.hhvm.com/manual/en/hack.modes.unsafe.php), telling the type system, "trust me, I know what I'm doing".

**Comment by jwatzman** [comment]
I was also thinking that maybe mysqli shouldn't have a return annotation here, but I actually think I like it just for this reason: it really really is mixed, and you need to assert or unsafe it.

**Comment by tslettebo** [comment]
Thanks for your reply. Going back to the function signature of [mysqli_fetch_all()] (http://php.net/manual/en/mysqli-result.fetch-all.php), it's correct that it states its result type as "mixed" (which is why I used that for the HHI file), but the description is actually more specific:

"Returns an array of associative or numeric arrays holding result rows."

The description of [mysqli_fetch_array()] (http://php.net/manual/en/mysqli-result.fetch-array.php) further says:

"Returns an array of strings that corresponds to the fetched row or NULL if there are no more rows in resultset."

The latter returns a single row, while the former returns all rows, and the description of the latter indicates that the data for each column is returned as a string (if not, we could use mixed).

Thus, depending on the second argument, mysqli_fetch_all() returns a value either of type:

* array<array<int,string>>
* array<array<string,string>>

It seems therefore that we could actually use array<array<arraykey,string>> as the return type of mysqli_fetch_all(), which would solve the issue.

What do you think?

I didn't know that you could essentially turn off the type checking by not including the return type in the HHI file, but I agree with you: It's better to be explicit about it, either through assertions or "UNSAFE", than the type checker silently assuming you know what you're doing.

**Comment by jwatzman** [comment]
Are there any error cases when it can return `null` or `false`? If so it needs to stay as `mixed`. Otherwise I wouldn't be opposed to a PR changing it as you indicated, if that is indeed the right type.

**Comment by tslettebo** [comment]
Not according to the documentation. mysqli_fetch_array() can return `null`, when there are no more records, but mysqli_fetch_all() is documented to only return a recordset.

Currently, there's no HHI file for the mysqli extension, but I've made one locally based on the documentation, and I'll make a PR once I've got everything set up. I'm on vacation with limited Internet connectivity.

**Comment by tslettebo** [comment]
@jwatzman FB actually has a library for nicely expressing these nested assertions

Speaking of such assertions in general, I've found a way to encapsulate these things, and maybe you do it something like this, as well.

That is, instead of code like this:
```
$value=f(); // Returns mixed

invariant(is_int($value),"");

// $value can be used as int here
```

we may instead do like this:

```
$value assert_int(f());

...

function assert_int(mixed $value): int
{
  invariant(is_int(),"");

  return $value;
}
```

Maybe you've done something similar?

I've not been able to make such assertions for general classes, though (without having to write a function for each), since you can't specify the type at the call site.

If you could, you might do something like this:

` $user = assert_object<User>(f()); `

Any suggestions for avoiding explicit invariant() at each point something like this is needed?

**Comment by steelbrain** [comment]
Bump. Also
```
$user = assert_object<User>(f());
```
is super nice. I would love to have that in HHVM.

**Comment by tslettebo** [comment]
@steelbrain There's now a way to do this in the [nightly build](5918):
```
function assert_object<T>(classname<T> $class_name,mixed $value): T
{
  invariant($value instanceof $class_name,"");

  return $value;
}

$user = assert_object("User",f());
```

**Comment by steelbrain** [comment]
@tslettebo Beautiful! This example should be in the docs site somewhere.

**Comment by fredemmott** [comment]
3.9 is also going up with support for this. Another handy one is:

````Hack
function nullthrows<T>(?T $value): T {
  invariant($value !== null, 'unexpected null');
  return $value;
}
```

**Comment by fredemmott** [comment]
We might add another hhvm/ composer package + github repo for some of these.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

For all these situations and more, we've got [hhvm/type-assert](https://github.com/hhvm/type-assert). This has `TypeSpec\of<T>()->coerceType();`, where `T` can be almost all types in the typesystem.
For types that don't work here, use `TypeSpec\darray(TypeSpec\string(), TypeSpec\int());`

But for situations where you can't pay the runtime cost, the only solution is an `HH_IGNORE_ERROR[4110]` somewhere.

It is easy to overuse things like this.
```HACK
function typechecker_just_trust_me<T>(mixed $in): T {
  /*HH_IGNORE_ERROR[4110]
    This is super unsound, but we cannot afford the runtime costs*/
  return $in;
}
```
