### ISSUE TITLE
[Typechecker] $stClassObject->{$var} notation shouldn't be a parse error in strict mode

### ISSUE THREAD

**Issue by tchapi** [facebook/hhvm#5157]
> NB : the original report is [here](https://github.com/hhvm/hack-hhvm-docs/issues/534#issuecomment-91283548) in the [hack-hhvm-docs](https://github.com/hhvm/hack-hhvm-docs) repository

The $stClassObject->{$var} notation gives an **Expected Expression** error in strict mode (_apart from the Dynamic method call problem, which is perfectly legit_); In the following example running on the 3.6.1 build, the last line should only return a Dynamic method call problem as suggested by @jwatzman : 

``` hack
<?hh // strict
class Stuff  {
  public function test(): void {
    $object = new stdClass();
    $object->a = "foobar";
    $a = 'a';
    $object->$a; // 2. Dynamic method call (Naming[2011])
    $object->{$a}; // 3. Expected expression (Parsing[1002]) + Dynamic method call (Naming[2011])
  }
}
```

Thanks a lot,

**Comment by jwatzman** [comment]
Not sure when someone will be able to get to this, but good to track.

**Comment by maryambanoo82r** [comment]
Thankyou

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

I have tested your repro in hhvm 4.56.
The "Parsing[1002] Expected expression" is fixed.

#### Additional context
The special rules for `\stdClass` have been removed in all Hack modes, and the following errors are now generated.
```
Typing[4053] No property 'a' in stdClass
   --> file.hack
 12 |         $object = new stdClass();
    |                       ^^^^^^^^ This is why I think it is an object of type stdClass
 13 |         $object->a = "foobar";
    |                  ^
   --> /tmp/hh_server/hhi_14e83db6/classes.hhi
 30 | final class stdClass {}
    |             ^^^^^^^^ Declaration of stdClass is here

Naming[2011] Dynamic method or attribute access is not allowed on a non-dynamic value.
   --> file.hack
 15 |         $object->$a;
    |                  ^^

Naming[2011] Dynamic method or attribute access is not allowed on a non-dynamic value.
   --> file.hack
 16 |         $object->{$a};
    |                   ^^

3 errors found.
```

These errors are "correct" and suggest using a `dynamic` (a new type that was added in [3.26.0](https://hhvm.com/blog/2018/05/07/hhvm-3.26.html)).
Adding `$object = new stdClass() as dynamic;` to your repro make all the errors go away.

**Comment by tchapi** [comment]
🎉
