### ISSUE TITLE
no found packages    amd64/Packages  404  Not Found

### ISSUE THREAD

**Issue by tort3** [facebook/hhvm#5159]
after doing this tells me

sudo add-apt-repository ppa:mapnik/boost
sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0x5a16e7281be7a449
echo deb http://dl.hhvm.com/ubuntu precise main | sudo tee /etc/apt/sources.list.d/hhvm.list
sudo apt-get update
sudo apt-get install hhvm

W: Imposible obtener http://ppa.launchpad.net/mapnik/boost/ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found

W: Imposible obtener http://ppa.launchpad.net/mapnik/boost/ubuntu/dists/trusty/main/binary-i386/Packages  404  Not Found

https://github.com/facebook/hhvm/wiki/Building-and-installing-HHVM-on-Ubuntu-12.04#installing-boost-149

I tried it with this form

sudo apt-get install git-core gawk cmake g++ libmysqlclient-dev \
  libxml2-dev libmcrypt-dev libicu-dev openssl build-essential binutils-dev \
  libcap-dev libgd2-xpm-dev zlib1g-dev libtbb-dev libonig-dev libpcre3-dev \
  autoconf automake libtool libcurl4-openssl-dev \
  wget memcached libreadline-dev libncurses-dev libmemcached-dev libbz2-dev \
  libc-client2007e-dev php5-mcrypt php5-imagick libgoogle-perftools-dev \
  libcloog-ppl0 libelf-dev libdwarf-dev subversion python-software-properties \
  libmagickwand-dev libxslt1-dev ocaml-native-compilers libevent-dev gawk \
  libyaml-dev gperf

and tells me

Leyendo la información de estado... Hecho
Nota, seleccionando «libncurses5-dev» en lugar de «libncurses-dev»
E: No se ha podido localizar el paquete libcloog-ppl0

sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install gcc-4.8 g++-4.8

W: Imposible obtener http://ppa.launchpad.net/mapnik/boost/ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found

W: Imposible obtener http://ppa.launchpad.net/mapnik/boost/ubuntu/dists/trusty/main/binary-i386/Packages  404  Not Found

E: Algunos archivos de índice fallaron al descargar. Se han ignorado, o se han utilizado unos antiguos en su lugar

Can someone help me ?
i use ubuntu 12.04
thank you

**Comment by oyamauchi** [comment]
@fredemmott @sgolemon  do you know what might be up?

**Comment by fredemmott** [comment]
cc @jwatzman .

Sounds like the repository we were depending on for an updated boost has dropped support for 12.04.

**Comment by jwatzman** [comment]
> W: Imposible obtener http://ppa.launchpad.net/mapnik/boost/ubuntu/dists/trusty/main/binary-amd64/Packages 404 Not Found

That's `trusty` which is 14.04. 12.04 is `precise`.

@tort3 are you sure you're on 12.04? what is the output of the following command?

`lsb_release -a ; uname -a ; cat /etc/issue ; cat /etc/apt/sources.list ; cat /etc/apt/sources.list.d/*`

**Comment by tort3** [comment]
i'm sorry.
I thought I had the 10..04 , and really is  14.04

**Comment by jwatzman** [comment]
I think this will get you to a point where you can install HHVM by following the 14.04 directions on our wiki; if not, you may want to reimage and try again, following the proper directions.

```
sudo add-apt-repository -r ppa:mapnik/boost
sudo rm /etc/apt/sources.list.d/hhvm.list
```

**Comment by tort3** [comment]
thanks
I can already install and operate
a greeting
