### ISSUE TITLE
Run-time dependencies for HHVM

### ISSUE THREAD

**Issue by estebanmatias92** [facebook/hhvm#5160]
Hi,

Sorry for the ignorance, i would like to know which of [this dependencies](https://github.com/facebook/hhvm/wiki/Building-and-installing-HHVM-on-Debian-8) are exclusively for run-time.

Thanks in advance.

**Comment by paulbiss** [comment]
I'm not sure I follow your question. They're all for the runtime in the sense that you can't build it without them. There are only a few extensions that can currently be disabled at compile time, this is something we plan to improve in future releases.

**Comment by estebanmatias92** [comment]
Thanks for the answer @paulbiss.
