### ISSUE TITLE
coding hhvm extensions : is it possible to cache objects or arrays without serializing/unserializing ?

### ISSUE THREAD

**Issue by gwenael** [facebook/hhvm#5167]
Hi everybody,

I'm coding an hhvm extension and I do appreciate the ease of it.
Here is my problem : I have to read a rather big file, containing data stored in a rather complicated format and put these data in an array. As it takes a lot of time (a significant part of every request), I would like to do it once for all.
Of course, I could use apc_add/fetch, but I am wondering why I could not store the hhvm underlying object itself. I mean with apc (and with every other caching method) I just replace one type of "serialization" (the file format) with another (the apc serialization format) and to get a proper php array, the apc unserialization has to be done over and over...
For what I could read in hhvm code, objects and arrays are created with allocators that reduce their lifetime to the request duration. Is there currently a way to code in HHVM c++ something like "create this array using only everlasting memory" so that I will only have to cache a pointer to it to get a "zero serialization/unserialization" cache ?

Thanks for your answer(s) !

**Comment by oyamauchi** [comment]
If it's an array, storing it in APC is probably your best option. It actually does what you want -- the "underlying hhvm object" is stored in APC, and it's only copied if PHP code tries to modify it. So if your PHP code isn't going to modify the array, using APC should be fine.

Rolling your own cross-request memory management and synchronization is delicate and tricky, which is why we generally discourage it.

**Comment by gwenael** [comment]
Thank you Owen for your answer.
This is the way I understand it : 

1) arrays are not serialized/unserialized but stored as is, whereas objects are stored serialized.  

2) creating an object using (for example) the std allocators rather than allocators that are reset at request shutdown is not implemented (and will possibly never be)
 
Thanks again !
