### ISSUE TITLE
test/run test/slow/ext_hh_client/typecheck.php fails

### ISSUE THREAD

**Issue by rrh** [facebook/hhvm#5168]
This test now (*) fails on a ubuntu 14.04 debug build against master head
  test/run test/slow/ext_hh_client/typecheck.php

(*) I haven't run any hhvm tests for 9 days, so I don't know when this may have snuck in.

**Comment by paulbiss** [comment]
cc @jwatzman

**Comment by jwatzman** [comment]
Interesting, I'll take a look, thanks!

**Comment by jwatzman** [comment]
It passes for me on the 14.04 build machine, though I guess I am using a release build, but that shouldn't matter at all? What's the error output?

**Comment by rrh** [comment]
ubuntu@ip-10-229-13-150:~/dev/hhvm/hphp$ test/run test/slow/ext_hh_client/typecheck.php
Running 1 tests in 1 threads (0 in serial)

FAILED: test/slow/ext_hh_client/typecheck.php
086+ 
087+ Fatal error: hphp_array_idx: search must be an array
086- object(HH\Client\TypecheckResult)#3 (3) {
087-   ["status":"HH\Client\TypecheckResult":private]=>
088-   int(3)
089-   ["error":"HH\Client\TypecheckResult":private]=>
090-   string(%d) "Hack typechecking failed: typechecker command not found: %s/this_file_does_not_exist"
091-   ["rawResult":"HH\Client\TypecheckResult":private]=>
092-   NULL
093- }
094- {"passed":false,"errors":[{"message":[{"descr":"Hack typechecking failed: typechecker command not found: %s\/this_file_does_not_exist"}]}]}
095- 
096- Warning: Hack type error: Invalid return type at test.php line 1 in %s/typecheck.php on line 19
097- 
098- Catchable fatal error: Hack type error: Invalid return type at test.php line 1 in %s/typecheck.php on line 20

1 tests failed

**Comment by rrh** [comment]
[sorry to no have included that in the original issue]

**Comment by jwatzman** [comment]
Can you paste the `typecheck.php.out` file? Can you also paste the output of

```
which which
which /this_file_does_not_exist
echo $?
```

It's curious how it's even getting far enough in that test case to hit the `hphp_array_idx` error, it should early return well before that...

**Comment by rrh** [comment]
ubuntu@ip-10-229-13-150:~/dev/hhvm/hphp$ which which; which /this_file_does; echo $?
/home/ubuntu/bin/which
0

**Comment by rrh** [comment]
object(HH\Client\TypecheckResult)#1 (3) {
  ["status":"HH\Client\TypecheckResult":private]=>
  int(0)
  ["error":"HH\Client\TypecheckResult":private]=>
  NULL
  ["rawResult":"HH\Client\TypecheckResult":private]=>
  array(3) {
    ["passed"]=>
    bool(true)
    ["errors"]=>
    array(0) {
    }
    ["version"]=>
    string(4) "mock"
  }
}
{"passed":true,"errors":[],"version":"mock"}
object(HH\Client\TypecheckResult)#2 (3) {
  ["status":"HH\Client\TypecheckResult":private]=>
  int(1)
  ["error":"HH\Client\TypecheckResult":private]=>
  string(55) "Hack type error: Invalid return type at test.php line 1"
  ["rawResult":"HH\Client\TypecheckResult":private]=>
  array(3) {
    ["passed"]=>
    bool(false)
    ["errors"]=>
    array(1) {
      [0]=>
      array(1) {
        ["message"]=>
        array(3) {
          [0]=>
          array(6) {
            ["descr"]=>
            string(19) "Invalid return type"
            ["path"]=>
            string(8) "test.php"
            ["line"]=>
            int(1)
            ["start"]=>
            int(1)
            ["end"]=>
            int(1)
            ["code"]=>
            int(4110)
          }
          [1]=>
          array(6) {
            ["descr"]=>
            string(16) "This is a string"
            ["path"]=>
            string(8) "test.php"
            ["line"]=>
            int(2)
            ["start"]=>
            int(2)
            ["end"]=>
            int(2)
            ["code"]=>
            int(4110)
          }
          [2]=>
          array(6) {
            ["descr"]=>
            string(30) "It is incompatible with an int"
            ["path"]=>
            string(8) "test.php"
            ["line"]=>
            int(1)
            ["start"]=>
            int(3)
            ["end"]=>
            int(3)
            ["code"]=>
            int(4110)
          }
        }
      }
    }
    ["version"]=>
    string(4) "mock"
  }
}
{"passed":false,"errors":[{"message":[{"descr":"Invalid return type","path":"test.php","line":1,"start":1,"end":1,"code":4110},{"descr":"This is a string","path":"test.php","line":2,"start":2,"end":2,"code":4110},{"descr":"It is incompatible with an int","path":"test.php","line":1,"start":3,"end":3,"code":4110}]}],"version":"mock"}

Fatal error: hphp_array_idx: search must be an array

**Comment by jwatzman** [comment]
What is `/home/ubuntu/bin/which`? Its exit codes seem broken:

```
ptarjan@ubuntu1404:~/hhvm$ which which
/usr/bin/which
ptarjan@ubuntu1404:~/hhvm$ /bin/which /asdf
ptarjan@ubuntu1404:~/hhvm$ echo $?
1
ptarjan@ubuntu1404:~/hhvm$ /usr/bin/which /asdf
ptarjan@ubuntu1404:~/hhvm$ echo $?
1
```

**Comment by rrh** [comment]
oh s**t.  kick me.  mea culpa.  The "pure" ubuntu image got contaminated with some tooling that shouldn't be there.  That tooling contains a buggy implementation of which, which I wrote in 1987.  I'll close this off.  the test works fine without this crap which.

**Comment by jwatzman** [comment]
Haha, np. I got a chuckle out of it if nothing else :)
