### ISSUE TITLE
PHP Hack parser

### ISSUE THREAD

**Issue by flip111** [facebook/hhvm#5175]
It would be nice to have the hack equivalent of the [PHP-Parser](https://github.com/nikic/PHP-Parser) and additionally have a visitor to strip hack specific features from the code. This would enable library authors to start developing in hack and release a PHP-only version as well.

**Comment by jazzdan** [comment]
Does the [Hack-to-PHP transpiler](http://docs.hhvm.com/manual/en/install.hack.h2tp.php) meet your requirements?

**Comment by flip111** [comment]
@jazzdan that's just wonderfull !

Though a Hack-Parser to get the AST would be useful as well. Shall i leave the issue open for this or close it?

**Comment by jazzdan** [comment]
@flip111 Ah, I believe [pfff](https://github.com/facebook/pfff) has support for what you are trying to do.

**Comment by flip111** [comment]
Oooh OCaml well i'm not familiar with that language. Anyway since the tools are there and i was mostly considering the transpiler i will close the issue. Thanks for support.
