### ISSUE TITLE
Debian Package: Mark apache and nginx config as conffiles

### ISSUE THREAD

**Issue by gmbs80** [facebook/hhvm#5178]
Currently the config files /etc/apache2/mods-available/hhvm_proxy_fcgi.conf and /etc/nginx/hhvm.conf aren't marked as conffiles and get overwritten with updates of the package. I've checked the current lts packages hhvm_3.3.5~jessie_amd64.deb, hhvm_3.6.1~jessie_amd64.deb. In 3.3.5 /etc/init.d/hhvm should also be marked as a config file.

**Comment by oyamauchi** [comment]
@jwatzman are you the right person to do this?

**Comment by jwatzman** [comment]
Yep, once I get around to it -- though there looks like there's an open PR for it too, so @bauerj might have beat me to it :)
