### ISSUE TITLE
Different handling of POST with no data on Apache vs HHVM

### ISSUE THREAD

**Issue by justinhj** [facebook/hhvm#5181]
When sending a request as follows, the request works fine on Apache but not on HHVM (which returns a 400 code and the message "method not supported").

In the example the request is a POST but it sends no data.

I've changed the host name which would be the IP of the server.

I believe the issue is related to the lack of the Content-Length to the header. If I add the Content-Length and set it to 0 then the call works on both Apache and HHVM.

Any ideas why this doesn't work on HHVM? Ideally I would like to make it work without any changes to the legacy system which is using this call pattern, by instead making a config change to the HHVM server.

POST /index.php/get_time HTTP/1.1
User-Agent: SuperApp
Content-Type: application/json
Accept-Encoding: gzip
Host: xx.xx.xx.xx
Connection: Keep-Alive, TE
TE: identity

**Comment by oyamauchi** [comment]
Just to clarify, how exactly are you running HHVM? As a FastCGI server behind nginx?

**Comment by justinhj** [comment]
Running hhvm as a stand alone server

**Comment by paulbiss** [comment]
Are you using the builtin libevent server?

**Comment by justinhj** [comment]
Yeah

**Comment by paulbiss** [comment]
Unfortunately we aren't supporting the libevent server anymore (it's not part of our packaging or default builds).

**Comment by fredemmott** [comment]
As above. If you're comfortable building from source, you can build with the proxygen-based replacement server which is supported.
