### ISSUE TITLE
hvvm compiles php code different from php-fpm in wordpress

### ISSUE THREAD

**Issue by selu91** [facebook/hhvm#5182]
I have a wordpress instance running on nginx with HHVM and having PHP-FPM as a fallback.

When using HHVM im getting 500 error code with this message:
```
\nFatal error: syntax error, unexpected $end in /var/www/html/wordpress/wp-content/plugins/fbar/fbar.php on line 1
```
But when I use php-fpm the code compiles just fine. Could be any differences in compiling the code using HHVM and PHP-FPM ? 

Here are the information you need to replicate the bug: 

OS:  Ubuntu 14.04.1 LTS
Nginx: 1.7.11 
HHVM: HipHop VM 3.6.1 (rel)
Wordpress: 4.1.1 https://wordpress.org/latest.zip
Just install this plugin Fbbar 1.0 : https://www.dropbox.com/s/ex2tfe1i1x90fjy/fbar.zip?dl=0 

And you will get the error i was talking about. 

Thank you !

**Comment by paulbiss** [comment]
It would help if you could paste the code that won't parse (or better, a short self-contained example that illustrates the same problem that we can run ourselves).

**Comment by selu91** [comment]
@paulbiss thank you for your reply. 

As i have described in the issue description, in order to replicate it you will need to install the latest version of wordpress along with that plugin that i have attached and you get that error. 

Here you have fbbar.php where the error is triggering: https://www.dropbox.com/s/hpfqxuzs0y1l4h5/fbar.php?dl=0 

Let me know if i can help you with anything else.

Thank you !

**Comment by r3wt** [comment]
possibly related to https://github.com/facebook/hhvm/issues/5115

**Comment by selu91** [comment]
I see there that downgrading to 3.5 will fix the issue. i will do that and check if is working ok.

**Comment by paulbiss** [comment]
It would be much easier to work on this if you could design an isolated repro of the problem. Leaving it open, but we're generally able to get to issues with isolated repros faster.

**Comment by wjywbs** [comment]
You fbar.php uses Classic Mac line ending, which is \r only. Converting the file to Linux's \n line ending fixes it.

**Comment by selu91** [comment]
@wjywbs you were right. Now works just fine. 

Thank you  for your help !

**Comment by Orvid** [comment]
Fixed many moons ago.
