### ISSUE TITLE
problem with Curl

### ISSUE THREAD

**Issue by leenjewel** [facebook/hhvm#5189]
My curl_test.php file :

```php
<?php
$url = "http://127.0.0.1/index.php";
$ch = curl_init($url);
curl_setopt($ch, CURLOPT_HEADER, 0);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_TIMEOUT, 50);
echo curl_exec($ch);
curl_close($ch);
?>
```

And my index.php file :

```php
<?php
echo "Hello World";
?>
```

When I request curl_test.php with jmeter 300 threads and 100 loops，HHVM return 504 Timeout Error.

When I change `url` from `lookback` to `other url` , HHVM could work well.

Why? Thanks!

**Comment by bauerj** [comment]
`lookback`? You mean `localhost`?

**Comment by oyamauchi** [comment]
What happens if you use `curl` on the command line?

**Comment by leenjewel** [comment]
curl work well  on the command line like

```shell
$ curl http://127.0.0.1/index.php
```
HHVM run `curl_test.php` with low load EX 1 thread 30 loops very well but with high load return 504 Timeout Error

**Comment by Orvid** [comment]
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.
