### ISSUE TITLE
Lots of incorrect usage of strncmp

### ISSUE THREAD

**Issue by apinski-cavium** [facebook/hhvm#5195]
Just an example:
base/http-stream-wrapper.cpp:  if (strncmp(filename.data(), "http://",  sizeof("http://")  - 1) &&

strncmp does not have to return 0 or 1, rather it returns 0 or non-zero.

On AARCH64 it returns the difference of the characters.

**Comment by paulbiss** [comment]
I don't see how this is a problem. The return value doesn't have to be 0 or 1 to be used in a boolean context so long as it's always non-zero when it should be truthy, and always 0 when it should be falsey.

**Comment by apinski-cavium** [comment]
Never mind, I did not see where the -1 is located.  there must be a better way of doing the above something like:
#define startswith(a, b) (strncmp(a, b, strlen(b)) == 0)
#define doesnotstartswith(a, b) (strncmp(a, b, strlen(b)) != 0)

And then use startswith and doesnotstartswith in the places where the string is used twice.

**Comment by paulbiss** [comment]
I'm loathed to describe macros as a "better" solution, an inline function would have worked, but this is pretty idiomatic, I don't really see the problem with using it.
