### ISSUE TITLE
[WIP in details] One Issue, One Elephpant project

### ISSUE THREAD

**Issue by guilhermeblanco** [facebook/hhvm#5196]
**This issue is currently in WIP of details**

Tracking USPS #: CX563999105CA

Hi Facebookers!

This issue is part of "One issue, one elephpant" project, which means I spoke with @sgolemon that I'd send you one big blue elephpant to FB headquarters in exchange for this issue to be resolved. I'll add the tracking number of the posting as soon as I get back from post office.

Currently, the company I work for is unable to switch from PHP 5.5 to HHVM due to a road blocker bug: you cannot authenticate. The same issue is also reproducible with the old AcmeDemoBundle authentication example, and I've been investigating the issue since last Friday.

I'm working on a reproducible "app" (with latest Symfony 2.7 version) by now to demonstrate where it breaks, then we can narrow down the exact location where it crashes. Once I get it done, I'll replace parts of the content with more focused, detailed information. As I said, with vanilla Symfony Standard 2.4 install (the last one with AcmeDemoBundle) also exposes the same issue I'm having.

From my initial investigation findings, I have a guess the problem is around SessionStorage, but I'm not 100% sure at this point. However, running the HttpFoundation components tests isolated with nightly build (grabbed from Travis) give us the following result that may worth be looked at:

```bash
PHPUnit 4.6.4 by Sebastian Bergmann and contributors.
Configuration read from /home/travis/build/symfony/symfony/phpunit.xml.dist
...............................................................  63 / 813 (  7%)
............................................................... 126 / 813 ( 15%)
..............................................S................ 189 / 813 ( 23%)
............................................................... 252 / 813 ( 30%)
............................................................... 315 / 813 ( 38%)
............................................................... 378 / 813 ( 46%)
............................................................... 441 / 813 ( 54%)
............................................................... 504 / 813 ( 61%)
............................................................... 567 / 813 ( 69%)
............................................................... 630 / 813 ( 77%)
.....................................................SSSSSSSSSS 693 / 813 ( 85%)
SSSSSSSSSSSSSSSSSSSSSS...E..................................... 756 / 813 ( 92%)
................S..ES.....S.S..S.ES......................
Time: 13.03 seconds, Memory: 18.00Mb

There were 3 errors:

1) Symfony\Component\HttpFoundation\Tests\Session\Storage\Handler\NativeFileSessionHandlerTest::testConstructSavePath with data set #2 ('5;0600;/tmp/foo', '5;0600;/tmp/foo', '/tmp/foo')
PHPUnit_Framework_Exception: Segmentation fault
2) Symfony\Component\HttpFoundation\Tests\Session\Storage\NativeSessionStorageTest::testRestart
PHPUnit_Framework_Exception: Segmentation fault
3) Symfony\Component\HttpFoundation\Tests\Session\Storage\Proxy\AbstractProxyTest::testId
PHPUnit_Framework_Exception: Segmentation fault
FAILURES!

Tests: 813, Assertions: 1680, Errors: 3, Skipped: 39.
```

**Comment by SiebelsTim** [comment]
We can send elephants to get issues resolved? Great!

**Comment by guilhermeblanco** [comment]
@SiebelsTim Only if you fit in one of these: https://twitter.com/SaraMG/status/590256085803474944 =)

**Comment by sgolemon** [comment]
Bribery is by no means necessary, but I won't turn down an elephpant. :)

**Comment by Orvid** [comment]
It works for me....
