### ISSUE TITLE
MySQL too many connections

### ISSUE THREAD

**Issue by florianbeer** [facebook/hhvm#5198]
I just installed hhvm on my server to use it for Piwik (which is hhvm compatible according to their devs). If I refresh the Piwik webinterface a few times, I am quickly hitting my MySQL max_connecitons limit. It seems none of the opened MySQL connections are being closed. This doesn't happen when running the same application through PHP.

OS: Debian 7.8
hhvm: 3.6.1~wheezy
mysqld: 5.5.40-0+wheezy1

**Comment by bauerj** [comment]
The cause seems to be #5202

**Comment by gmagana** [comment]
See #5132 also.
