### ISSUE TITLE
interface Serializable is hack typed with wrong type

### ISSUE THREAD

**Issue by homerhsing** [facebook/hhvm#5199]
To reproduce:

class SomeClass implements Serializable {
  public function serialize(): string {
    return 'something';
  }
  public function unserialize(string $serialized): void {
  }
}

Run this code, get error: 

PHP Fatal error: Declaration of SomeClass::unserialize() must be compatible with that of Serializable::unserialize()

**Comment by homerhsing** [comment]
The reason is probably parameter of Serializable:: unserialize() is marked as "mixed" (or not typed).  According to PHP document, the parameter type should be "string".

**Comment by homerhsing** [comment]
The Document 
   http://docs.hhvm.com/manual/en/class.serializable.php

The Document says:
Serializable {
/* Methods */
abstract public function serialize ( void ): string
abstract public function unserialize ( string $serialized ): void
}

The parameter type is "string"

**Comment by simonwelsh** [comment]
Same issue as #2268. The actual interface is untyped, since it's used by PHP.

**Comment by homerhsing** [comment]
I see. Thanks for explain.
