### ISSUE TITLE
fb_serialize doesn't support an instance of Serializable

### ISSUE THREAD

**Issue by homerhsing** [facebook/hhvm#5200]
To reproduce:
1. Create a class which implements Serializable interface.
2. Call fb_serialize
3. You will get "null".

**Comment by fredemmott** [comment]
It's not meant to be a drop-in replacement for serialize() - just faster, and fits our needs. We'd be happy to review a pull request, however we're unlikely to implement this ourselves.

**Comment by homerhsing** [comment]
Thanks for explain, I am using serialize() instead
