### ISSUE TITLE
HHI for Redis

### ISSUE THREAD

**Issue by steelbrain** [facebook/hhvm#5206]
Because HHVM's redis_ext is in pure PHP, Maybe we can provide our typechecker an HHI decl file to get auto-completions and validations. Currently I have to write my own definitions.hhi in each project and write Redis definitions there. It would be cool to have it built into hhvm just like the ext.
Something like this
```hack
final class Redis{
  public function __construct();
  public function get(string $key); // string or false
  public function set(string $key,mixed $value):void;
  public function incr(string $key):void;
  public function connect(string $hostname, int $port):void;
  public function del(string $key):void;
  public function publish(string $channel,string $message):void;
  public function smembers(string $key):array<string>;
  public function lrange(string $key, int $start, int $stop):array<string>;
  public function lrem(string $key, int $limit, string $item):void;
  public function lpop(string $key); // string or false
  public function hget(string $key, string $hkey); // string or false
  public function hdel(string $key, ... string $hkey);
  public function hset(string $key,string $hkey,string $value):void;
  public function hexists(string $key, string $hkey):bool;
  public function exists(string $key):bool;
  public function sadd(string $key, mixed $sval):void;
  public function srem(string $key, mixed $sval):void;
  public function sismember(string $key, mixed $sval):bool;
  public function rpush(string $key, mixed $lval):void;
  public function expire(string $key, mixed $duration):void;
  public function flushdb():void;
}
```

**Comment by jwatzman** [comment]
Would be happy to review a PR for this, but not something we're likely to get to soon.

**Comment by steelbrain** [comment]
btw, some of the functions we have currently have a non-standard behavior, `string | false` instead of `?string` should they be keep that way to be api compatible with php redis or should we follow the [Redis Protocol][1]?

[1]:redis.io/topics/protocol

**Comment by SiebelsTim** [comment]
HHVM is supposed to be a drop-in replacement for php. So I guess matching php is the way to go.

(I really liked how pgsql has a option to turn off php madness)

**Comment by JoelMarcey** [comment]
@steelbrain I definitely don't think it would be a *bad* thing to have a type-checked version of Redis; has there been a push for this? Or is this something that has caused you heartburn and you just want to "fix". 

Also, on IRC, you mentioned that you might want to create something called `RedisNG` as the replacement. Am I missing something, or could you just throw the update into the `HH` namespace? `HH/Redis` or something like that.

**Comment by steelbrain** [comment]
Would putting something in `HH` namespace mean that Hack would use stuff from it even when it's available in the global namespace?

**Comment by fredemmott** [comment]
HH/ doesn't seem appropriate - the same API could be implemented as userspace PHP code, and any hack version could be compatible.

**Comment by steelbrain** [comment]
Because @paulbiss and @fredemmott mentioned in the IRC that this is something that can be easily done in the User Land. I have created [RedisNG][1], installable via composer as `steelbrain/redis-ng`. It is correctly typed and unlike the Redis client in systemlib, it's predictable and acts according to the Redis Protocol Specifications.
[1]:https://github.com/steelbrain/RedisNG
