### ISSUE TITLE
libgcrypt11 and libgnutls26  is not installable

### ISSUE THREAD

**Issue by unicco33** [facebook/hhvm#5210]
While trying to install HHVM on the newest Ubuntu Server release (Ubuntu 15.04 (Vivid Vervet)), I'm getting two dependency-errors. I'm unsure how to resolve them.

Followed installating-guidelines: https://github.com/facebook/hhvm/wiki/Prebuilt-packages-on-Ubuntu-15.04-%28vivid%29

    apt-get install hhvm

    The following packages have unmet dependencies.
    hhvm : Depends: libgcrypt11 but it is not installable
    Depends: libgnutls26 but it is not installable
    E: Unable to correct problems, you have held broken packages.

**Comment by bauerj** [comment]
Duplicate: #5203

**Comment by jwatzman** [comment]
Yep.
