### ISSUE TITLE
addAll() on an empty Map ?

### ISSUE THREAD

**Issue by tchapi** [facebook/hhvm#5214]
Hello,

Calling `addAll()` on an empty **Map** currently throws an InvalidArgumentException :

```hack
<?hh // partial
  $test = Map{};
  $test2 = Map{ "foo" => "bar"};
  $test->addAll($test2);  // Exception : 'Parameter must be an instance of Pair'
```

Am I missing something ? The behaviour of `setAll()` is different (no error thrown); It seems to me that `addAll()` on an empty Map should just work — is this on purpose, and if it is the case, why would it be problematic to add a Traversable<Pair> to an empty Map ?

Thanks a lot !

_HipHop VM 3.6.1 (rel)_
_Compiler: tags/HHVM-3.6.1-0-gc051feff88ba8050f33f10f7b1fb07f8d3415f9e_

**Comment by paulbiss** [comment]
The `addAll` function expects a traversable of Pair objects
```php
<?hh // partial
  $test = Map{};
  $test2 = Vector{ Pair{"foo", "bar"} };
  $test->addAll($test2);  // Exception : 'Parameter must be an instance of Pair'
```

**Comment by WizKid** [comment]
Or `$test->addAll($test2->items());`

**Comment by tchapi** [comment]
Thanks guys — this does make sense ! My bad !
