### ISSUE TITLE
'Class already declared' when using phpunit phar

### ISSUE THREAD

**Issue by splitbrain** [facebook/hhvm#5215]
This was originally reported at sebastianbergmann/phpunit/issues/1684

I'm trying to get started with testing with HipHopVM, however I have trouble even get it to run:

```
$ hhvm --version
HipHop VM 3.6.1 (rel)
Compiler: 1428401411_698854969
Repo schema: 479647c3ad87f2e920ac085aa1424e2b8101da45
```

All the available phpunit versions throw the same error:

```
$ php phpunit.phar --version
PHPUnit 4.6.4 by Sebastian Bergmann and contributors.
$ hhvm phpunit.phar --version
Fatal error: Class already declared: PHPUnit_Framework_Error in phar://phpunit-4.6.4.phar/phpunit/Util/../Framework/Error.php on line 22

$ php phpunit-beta.phar --version
PHPUnit beta-2015-04-17 by Sebastian Bergmann and contributors.
$ hhvm phpunit-beta.phar --version
Fatal error: Class already declared: PHPUnit_Framework_Error in phar://phpunit-beta-2015-04-17.phar/phpunit/Util/../Framework/Error.php on line 22

$ php phpunit-alpha.phar --version
PHPUnit alpha-2015-04-17 by Sebastian Bergmann and contributors.
$ hhvm phpunit-alpha.phar --version
Fatal error: Class already declared: PHPUnit_Framework_Error in phar://phpunit-alpha-2015-04-17.phar/phpunit/Util/../Framework/Error.php on line 22
```

**Comment by spiritix** [comment]
This was working yesterday, seems to be related to the last Travis CI rollout.
https://github.com/travis-ci/travis-ci/issues/3790

**Comment by machee** [comment]
Travis was running PHPUnit 4.5.0 yesterday. The problem only occurs with 4.6.1-4.6.4. PHPUnit 4.5.1 works for me as a work around but I don't know if that's easy to replace on Travis.

https://phar.phpunit.de/phpunit-4.5.1.phar

**Comment by colinodell** [comment]
As a workaround, I've modified my .travis.yml to use a Composer-installed copy of PHPUnit instead of relying on the presence of their pre-installed .phar.

**Comment by fredemmott** [comment]
I'm guessing (but not confirmed) that we're not properly normalizing paths in phars - so not realizing that  phar://phpunit-4.6.4.phar/phpunit/Util/../Framework/Error.php and  phar://phpunit-4.6.4.phar/phpunit/Framework/Error.php are the same thing.

**Comment by fredemmott** [comment]
Makes sense given that 4.5 has an autoloader, 4.6 has a big pile of requires at the top of the phar.

**Comment by fredemmott** [comment]
We implement phar:// includes as a standard stream include. Need to check:
 - how/when PHP normalizes stream includes
 - how this should interact with __DIR__

**Comment by Orvid** [comment]
It works for me.
