### ISSUE TITLE
Upgrade from 3.6.1 to 3.7.0: TTFB from 0.06s to 1s for static files, 20s+ for dynamic files

### ISSUE THREAD

**Issue by dmsnell** [facebook/hhvm#5216]
Debian wheezy on Linode 2GB instance

I had been happily running HHVM 3.6.1 and my WordPress installation was loading in about 1.5s on webpagestest.org for the first load and 0.8s for the second load (warmed cache).

This morning, I ran `apt-get update; apt-get upgrade` and HHVM updated to 3.7.0.

```
2015-04-27 23:59:19 startup archives unpack
2015-04-27 23:59:19 upgrade hhvm:amd64 3.6.1~wheezy 3.7.0~wheezy
2015-04-27 23:59:19 status half-configured hhvm:amd64 3.6.1~wheezy
2015-04-27 23:59:19 status unpacked hhvm:amd64 3.6.1~wheezy
2015-04-27 23:59:19 status half-installed hhvm:amd64 3.6.1~wheezy
2015-04-27 23:59:20 status half-installed hhvm:amd64 3.6.1~wheezy
2015-04-27 23:59:20 status unpacked hhvm:amd64 3.7.0~wheezy
2015-04-27 23:59:20 status unpacked hhvm:amd64 3.7.0~wheezy
2015-04-27 23:59:21 startup packages configure
2015-04-27 23:59:21 configure hhvm:amd64 3.7.0~wheezy <none>
2015-04-27 23:59:21 status unpacked hhvm:amd64 3.7.0~wheezy
2015-04-27 23:59:21 status unpacked hhvm:amd64 3.7.0~wheezy
2015-04-28 00:00:29 conffile /etc/hhvm/php.ini keep
2015-04-28 00:00:29 status unpacked hhvm:amd64 3.7.0~wheezy
2015-04-28 00:00:29 status unpacked hhvm:amd64 3.7.0~wheezy
2015-04-28 00:00:29 status unpacked hhvm:amd64 3.7.0~wheezy
2015-04-28 00:00:29 status unpacked hhvm:amd64 3.7.0~wheezy
2015-04-28 00:00:29 status unpacked hhvm:amd64 3.7.0~wheezy
2015-04-28 00:00:29 status half-configured hhvm:amd64 3.7.0~wheezy
2015-04-28 00:00:29 status installed hhvm:amd64 3.7.0~wheezy
```

You can see that I kept the `php.ini` file - I had some memory settings changes, but here it is in entirety. I did update the session save path, but didn't think that was related to my issues.

```
; php options
session.save_handler = files
session.save_path = /var/lib/hhvm/sessions/
session.gc_maxlifetime = 1440
upload_max_filesize = 256M
memory_limit = 64M
post_max_size = 256M

; hhvm specific
hhvm.log.level = Warning
hhvm.log.always_log_unhandled_exceptions = true
hhvm.log.runtime_error_reporting_level = 8191
hhvm.mysql.typed_results = false
```

Also, `update-alternatives --list php` yields `hhvm` and the `install_fastcgi.sh` script did not run but I already have `include hhvm.conf` in my nginx configs.

I'm not sure if this was caused by HHVM or my environment, but I would appreciate some help in figuring it out.

**Comment by jwatzman** [comment]
The first 12 requests are all "warmup" requests. What does the speed comparison look like for 3.6 vs 3.7 on the 13th and later requests? Does it hit a steady state? Warmup being slower isn't great, but is much less big of a deal than everything being slower :)

**Comment by jwatzman** [comment]
You can also downgrade to 3.6 again and see what happens, to isolate HHVM changes from other environment changes. The debs are all on dl.hhvm.com, in particular wheezy 3.6.1 is [here](http://dl.hhvm.com/debian/pool/main/h/hhvm/hhvm_3.6.1~wheezy_amd64.deb).

**Comment by dmsnell** [comment]
Thanks @jwatzman! The warmup was one of my first thoughts, but it didn't seem to make much of a difference.

In the meantime, I `apt-get remove hhvm`'d and did a manual `dpkg -i hhvm-3.6.1-wheezy` from the `dl.hhvm` repository and I didn't get my speed back.

**Comment by jwatzman** [comment]
Then something else must have changed. Did you do anything else when you upgraded your HHVM version? Did WordPress upgrade, or nginx/apache, or something like that? Configuration changes for anything like that? What about Linode -- do they share VMs on the same host, and you may suddenly have a "noisy neighbor"?

Since it doesn't look like the HHVM version affects things here, not sure what else we can do to help, other than the general debugging suggestions above :\

**Comment by jwatzman** [comment]
Also if you are getting your perf numbers from a 3rd party (webpagetest.org), *they* may be having issues, you may want to try `siege` locally or something like that.

**Comment by dmsnell** [comment]
@jwatzman I [track my /etc directory](https://cloudup.com/cXVxmy7WUXv) in Git, and was surprised at how few changes there were with the HHVM update.

The most bizarre result is that the time to first byte reported by webpagetest.org is now higher (slower) for the primed cache-view of the page than for the cold view.

![](https://cldup.com/gwbvWeS-gT.png)
http://www.webpagetest.org/result/150428_CT_136P/

I don't see any changes to the WordPress code either. Granted, I _am_ on Linode and they share the servers, but I also didn't see anything on the steal percentage from monitoring the CPU under load (I saw it at one point jump to 0.2 under 100% load on all cores).

[Here are the siege results](https://cloudup.com/cz5W6z4orCx) for this site and for a site similarly configured (albeit with Apache). Unfortunately I don't have any other nginx deployments on public servers to compare against, but these two sites performed very similarly before on webpagetest.org.

Are you aware of any guides I could use to start investigating that initial waiting time? I don't have any errors in my log files and it's not only slower in the tools, but noticeably slower when visiting the site in a browser.

**Comment by paulbiss** [comment]
Is the repeated view row after running a series of warmup requests? The first 11 requests are run without the JIT on for profiling, and you should run at least 50-100 requests to warm the translation cache before you start measuring speed. You can also try setting hhvm.jit_pseudoemain=false to reduce the time to fill the TC.

**Comment by dmsnell** [comment]
I've run `siege` multiple times and hit the website even more. I'm not sure on the results from `siege` but it looks like it hit the web server around 1,000 times each round. Unfortunately I still have 1.0s+ delays.

I'm going to reopen a support ticket with Linode and see if they have anything to add, but will report back here just in case there is some anomoly in the HHVM update.

**Comment by dmsnell** [comment]
After Linode migrated my server to another host in the datastore the issue still persists.

**Comment by jwatzman** [comment]
Since the issue persisted after downgrading HHVM, this really looks like something else, not part of the HHVM upgrade. (We don't have complicated preinst/postinst scripts that would mess things up -- their source is at https://github.com/hhvm/packaging/tree/master/hhvm/deb/skeleton/DEBIAN.)

If you're interested in general profiling advice, happy to write some of that up, but since the regression seems to be something external to HHVM, I don't think there's much we can do other than give you some pointers to help you track it down...

**Comment by dmsnell** [comment]
Thanks @jwatzman. I'm sorry I couldn't prioritize the profiling better - gotta keep the day job going.
