### ISSUE TITLE
assertion `moves[rTmp] == InvalidReg' failed

### ISSUE THREAD

**Issue by yan12125** [facebook/hhvm#5219]
I've built commit ccd1a77862aa4f5545dd4341a2010bc70abf6f7a with some patches for successful building: #5191, #5218 and google/re2@7d502a5ba41476f935bdb965f0d68c7ce01979cd

I use the following commands to build:
```
CXXFLAGS="-Wno-bool-compare" \
cmake \
    -DCMAKE_BUILD_TYPE=Debug \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DCMAKE_PREFIX_PATH="$srcdir" \
    -DMYSQL_UNIX_SOCK_ADDR=/run/mysqld/mysqld.sock \
    .
make VERBOSE=1
```
However, for the following simplest php file:
```
<?php
echo "OK\n";
?>
```
hhvm gives me the following error:
https://gist.github.com/yan12125/fe9b15f766cf8a4220ce

Environment:
OS: Arch Linux x86_64
GCC: 5.1.0

**Comment by jwatzman** [comment]
Probably related to GCC 5, which we don't support yet. Thanks for filing the issue though, useful to track for when we do get around to supporting GCC 5.

**Comment by wjywbs** [comment]
Please check https://github.com/facebook/hhvm/issues/5474#issuecomment-113299594 for the patch to fix this issue.

**Comment by yan12125** [comment]
With gcc 5.3.0, clang 3.7 and commit c72c876ab99a4343ef642e2133113612d91d853e this bug is gone.
