### ISSUE TITLE
Nightly packages for Precise

### ISSUE THREAD

**Issue by BanzaiMan** [facebook/hhvm#5220]
Hello there.

Users are reporting build breakage with `hhvm-nightly` on Travis CI, and I believe this is due to discontinuation of Precise packages. (http://dl.hhvm.com/ubuntu/dists/precise/main/binary-amd64/Packages no longer lists hhvm-nightly.)

Is there a reason for the discontinuation?

Thanks!

**Comment by paulbiss** [comment]
We aren't building nightlies for precise anymore, we also aren't planning to package 3.7 for precise. We will continue supporting 3.6, the 3.6.2 release is being packaged for precise now.

**Comment by paulbiss** [comment]
As to the reason, the distro is too old, and supporting it has become difficult. In particular the OCaml, gcc, and boost packaged with this distro are all out of date.
