### ISSUE TITLE
test/run --server is deprecated

### ISSUE THREAD

**Issue by rrh** [facebook/hhvm#5230]
test/run --server no longer works. It seems to be wanting to run hhvm in its deprecated server mode, although that's hard to find out, since the thrown exception within hhvm seems to get swallowed up.

Perhaps there's a replacement for these semantics that uses fcgi somehow?

There's a suggestion IRC just now that the proxygen server needs to be included by default in the build, and once that's done then one could change test/run so that "add Server.Type=proxygen to wherever it's adding -m server :)"

**Comment by fredemmott** [comment]
- proxygen enabled by default just landed internally
- diff up to change Server.Type for test/run. Hopefully we'll change the server.type default for 3.9
