### ISSUE TITLE
proxygen build leaves behind detritus confusing git

### ISSUE THREAD

**Issue by rrh** [facebook/hhvm#5231]
Running the hhvm build here in OSS land leaves behind detritus when building proxygen submodule.

git status
  	modified:   third-party (modified content)

cd third-party; git status
 	modified:   proxygen/src (untracked content)

cd proxygen/src; git status
  Untracked files:
  (use "git add <file>..." to include in what will be committed)

	proxygen/lib/http/HTTPCommonHeaders.cpp
	proxygen/lib/http/HTTPCommonHeaders.h

Perhaps there needs to be a .gitignore added, although its a little creepy to ignore what appears from the suffix/extension to be source files.

**Comment by simonwelsh** [comment]
facebook/proxygen#40

**Comment by rrh** [comment]
When will the hhvm git submodule info be updated to incorporate the referenced changes to proxygen?

**Comment by fredemmott** [comment]
Merged it into third-party. Diff up internally to bump the version of third-party we use.
