### ISSUE TITLE
GDB can't read symbols from HHVM build (malloc assertion fails)

### ISSUE THREAD

**Issue by psmarshall** [facebook/hhvm#5232]
I've got local modifications to HHVM which compile and pass all quick tests, but GDB has issues when I try to use it with my build:

    Reading symbols from hphp/hhvm/hhvm...gdb: malloc.c:3695: _int_malloc: Assertion `(unsigned long) (size) >= (unsigned long) (nb)' failed.
    Aborted (core dumped)

~~I don't get the same issue with GDB on the master branch.~~
Master does actually give me the same problem.

    $ hphp/hhvm/hhvm --version
    HipHop VM 3.8.0-dev (dbg)
    Compiler: heads/master-0-g2a222078e4fdd55a1165275353e581b0340cd98a
    Repo schema: ef28538528ed1b5ba510e5673f4431e805d46379

    $ gdb -v
    GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1

How could I debug it further?

**Comment by edwinsmith** [comment]
I've never seen this, but I don't often work on ubuntu, and wonder if it has something to do with the version of malloc. I think by default you don't get jemalloc, but we do pretty much all work with jemalloc, so maybe try that.

**Comment by wjywbs** [comment]
Can you try `LD_PRELOAD=/path/to/libjemalloc.so gdb hphp/hhvm/hhvm`? I also had this error.

**Comment by psmarshall** [comment]
@wjywbs That fixed it! Thanks
