### ISSUE TITLE
compile hhvm 3.8.0-dev  when run cmake .  show error

### ISSUE THREAD

**Issue by javacty** [facebook/hhvm#5234]
-- Found Freetype: /usr/lib64/libfreetype.so
-- Building async MySQL extension
-- GNU FriBidi not found
-- Found LibMagicWand: /usr/lib64/libMagickWand-6.Q16.so
-- Found LibYaml: /usr/lib64/libyaml.so
You have called ADD_LIBRARY for library hphp_ext_zend_compat without any source files. This typically indicates a problem with your CMakeLists.txt file
-- Found gold: /usr/bin/ld.gold
-- Configuring done
CMake Error: Cannot determine link language for target "hphp_thrift".
CMake Error: CMake can not determine linker language for target:hphp_thrift
CMake Error: Cannot determine link language for target "hphp_hhbbc".
CMake Error: CMake can not determine linker language for target:hphp_hhbbc
-- Generating done
-- Build files have been written to: /data/test/hhvm

**Comment by fredemmott** [comment]
Some fixes were done overnight, and I just managed a clean build. Are you still unable to build with a fresh checkout?

**Comment by Sakretsos** [comment]
Hello, for me all works perfect with the build 3.8.0-dev ( tested on CentOS 7 x64 )

**Comment by fredemmott** [comment]
Stale issue, closing per https://github.com/facebook/hhvm/wiki/Human-Timeouts
