### ISSUE TITLE
why benchmark hhvm is get larger score than php7 with whole benchmark scripts, but singly is smaller than php7 ?

### ISSUE THREAD

**Issue by joostshao** [facebook/hhvm#5235]
why benchmark hhvm is get larger score than php7 with whole benchmark scripts, but singly is smaller than php7 ?
```
/usr/local/php7/bin/php  run.php 
Huffman: 981
Richards: 616
DeltaBlue: 2315
Splay: 1114
SplayLatency: 1350
QuickHull: 1843
----
Score (version 9): 1253
hhvm  run.php 
Huffman: 638
Richards: 426
DeltaBlue: 538
Splay: 5638
SplayLatency: 11649
QuickHull: 2323
----
Score (version 9): 1677

----------------------------------------------------------------------------

/usr/local/php7/bin/php run.php 
Huffman: 1034
Score (version 9): 1034
hhvm  run.php 
Huffman: 668
Score (version 9): 668

**Comment by joostshao** [comment]
ubuntu@ubuntu:/media/ubuntu/data/src/hhvm/hphp/benchmarks/php-octane$ /usr/local/php7/bin/php run.php 
Huffman: 1034
----
Score (version 9): 1034
ubuntu@ubuntu:/media/ubuntu/data/src/hhvm/hphp/benchmarks/php-octane$ hhvm  run.php 
Huffman: 668
----
Score (version 9): 668
ubuntu@ubuntu:/media/ubuntu/data/src/hhvm/hphp/benchmarks/php-octane$

**Comment by joostshao** [comment]
ubuntu@ubuntu:/media/ubuntu/data/src/hhvm/hphp/benchmarks/php-octane$ hhvm  run.php 
Richards: 459
----
Score (version 9): 459
ubuntu@ubuntu:/media/ubuntu/data/src/hhvm/hphp/benchmarks/php-octane$ /usr/local/php7/bin/php run.php 
Richards: 651
----
Score (version 9): 651

**Comment by joostshao** [comment]
ubuntu@ubuntu:/media/ubuntu/data/src/hhvm/hphp/benchmarks/php-octane$ /usr/local/php7/bin/php run.php 
DeltaBlue: 2427
----
Score (version 9): 2427
ubuntu@ubuntu:/media/ubuntu/data/src/hhvm/hphp/benchmarks/php-octane$ hhvm  run.php 
DeltaBlue: 583
----
Score (version 9): 583

**Comment by joostshao** [comment]
ubuntu@ubuntu:/media/ubuntu/data/src/hhvm/hphp/benchmarks/php-octane$ /usr/local/php7/bin/php run.php 
Splay: 1146
SplayLatency: 1380
----
Score (version 9): 1258
ubuntu@ubuntu:/media/ubuntu/data/src/hhvm/hphp/benchmarks/php-octane$ hhvm  run.php 
Splay: 6166
SplayLatency: 12288
----
Score (version 9): 8704

**Comment by joostshao** [comment]
ubuntu@ubuntu:/media/ubuntu/data/src/hhvm/hphp/benchmarks/php-octane$ /usr/local/php7/bin/php run.php 
QuickHull: 2205
----
Score (version 9): 2205
ubuntu@ubuntu:/media/ubuntu/data/src/hhvm/hphp/benchmarks/php-octane$ hhvm  run.php 
QuickHull: 2465
----
Score (version 9): 2465

**Comment by paulbiss** [comment]
I'm not sure I understand your question. The numbers look fairly consistent between your runs. You might try running hhvm with `--count 10` and take the last set of results (to allow the JIT to warmup).

**Comment by joostshao** [comment]
hei,  i mean that , test all ,hhvm is faster, but when compare single case, php7 is faster.

/*****run.php****/
include 'base.php';
include 'huffman.php';
// include 'richards.php';
// include 'deltablue.php';
// include 'splay.php';
// include 'quick-hull.php';


/usr/local/php7/bin/php run.php 
----
Score (version 9): 1015

but for HHVM:

---
Score (version 9): 739
----
Score (version 9): 716
----
Score (version 9): 751
----
Score (version 9): 713
----
Score (version 9): 746
----
Score (version 9): 762
----
Score (version 9): 747
----
Score (version 9): 767
----
Score (version 9): 769
----
Score (version 9): 769
----
Score (version 9): 759
----
Score (version 9): 757
----
Score (version 9): 704
----
Score (version 9): 730
----
Score (version 9): 725
----
Score (version 9): 747
----
Score (version 9): 789
----
Score (version 9): 793
----
Score (version 9): 797
----
Score (version 9): 799
----
Score (version 9): 787
----
Score (version 9): 785
----
Score (version 9): 771

**Comment by paulbiss** [comment]
It looks to me like Huffman also scored pretty low when run with the other tests on hhvm, but the average was brought up by other tests that scored higher.

**Comment by joostshao** [comment]
yes, your tested result is similar to me, but i want to know the reason, don't you ?

**Comment by fredemmott** [comment]
Sorry, going to close this: in general we do not care about microbenchmarks - we optimize HHVM based on profiling results for real sites instead.
