### ISSUE TITLE
Documentation request: Enhanced autoloading

### ISSUE THREAD

**Issue by tslettebo** [facebook/hhvm#5238]
I haven't been able to find documentation about the enhanced autoloading facility available in HHVM, using autoload_set_paths().

Since this also includes autoloading of functions, among other things, it would be very useful for people to know about it, so it would be good if someone could add it to the HHVM documentation.

I only found out about it by reading Owen Yamauchi's early-release [Hack & HHVM] (http://hhvm.com/blog/8981/announcing-our-book-hack-hhvm) book.

**Comment by paulbiss** [comment]
Actually, can you open a bug report against our docs repo to document `autoload_set_paths`?

https://github.com/hhvm/hack-hhvm-docs

**Comment by tslettebo** [comment]
Sure, I've done that now so you may close this issue.
