### ISSUE TITLE
object-property access

### ISSUE THREAD

**Issue by gopedib** [facebook/hhvm#5242]
I am running this simple program on hhvm. As described in http://hhvm.com/blog/713/hhvm-optimization-tips, I was expecting hhvm to access the "X" property at getProp() site using property map (constant offset). However for me, it is calling the <call 0xeb3c50 <HPHP::jit::MInstrHelpers::cGetPropSO> having about ~250 instructions> everytime it is accessing the "X" at getProp(). Is there any switch I have to turn on during hhvm build to see this optimization in my hhvm debug-trace? Any idea?

function test($n) {
   class C {
      private $X;
      public function getProp() {
         return $this->X;
      }
   }
   for ($i = 0; $i < $n; ++$i) {
      $obj = new C;
      echo $obj->getProp();
   }
}
test(20);

**Comment by gopedib** [comment]
Sorry, failed to mention the function (the post above) access of "X" is calling is:

call 0xeb3c50 <HPHP::jit::MInstrHelpers::cGetPropSO> having ~250 instructions

**Comment by paulbiss** [comment]
Are you running in repo-authoritative mode? http://hhvm.com/blog/4061/go-faster

A lot of our member instruction optimizations only kick in when running a compiled repo.

**Comment by gopedib** [comment]
Thanks, I was not running in repo-authoritative mode. So now I am running my dinky program w/ the following:

First of all, trying to build the cache: hhvm --hphp --target hhbc --input-list /tmp/files.list --output-file hhvm.hhbc.sq3 -k1 -l3

One thing I am hitting here:
Error in command line: unrecognised option '--output-file', I do not see any option to mention output file in the updated usage shown. What should be the option to mention output file?

Then trying to run my program w/:
TRACE=printir:2 HPHP_TRACE_FILE=obj-prop-access_hphp.log ~/hhvm/hphp/hhvm/hhvm_w_mysql_sock -vRepo.Authoritative=true obj-prop-access.php

I am hitting some error:

Failed to load Repo::GlobalData:
  /root/.hhvm.hhbc: No rows in main.GlobalData_3483f4063f9ed48b8597877b6825ea1ea0f535f8. Did you forget to compile that file with this HHVM version?

Do I need to re-build the hhvm binary or Am I missing/wrongly mention any switch in hhvm run? Any idea? I haven't used the Repo.Authoritative mode before! I am simply running dinky programs in my host machine with hhvm built.

**Comment by gopedib** [comment]
Thanks @paulbiss. With RepoAuthoritative mode turned on w/ following commands, it seems that optimizations got placed in:

./hphp/hhvm/hhvm --hphp --target hhbc --input-list /tmp/files.list  -k1 -l3

./hphp/hhvm/hhvm -v Repo.Central.Path=/tmp/hphp_F09X3s/hhvm.hhbc -v Repo.Authoritative=true obj-prop-access.php
