### ISSUE TITLE
zend compat PHPAPI zend_startup_strtod not called

### ISSUE THREAD

**Issue by rrh** [facebook/hhvm#5245]
The zend PHPAPI function zend_startup_strtod (and its companion zend_shutdown_strtod) isn't called at all, never mind at the right time.

This function is implemented in
  ./hphp/runtime/ext_zend_compat/php-src/Zend/zend_strtod.cpp
and establishes mutexes around a lazily computed table of powers of 5.

The function zend_startup_strtod isn't called as part of program start. It has to be called in order to make the end PHP API zend_strtod work.

To further blow smoke on the matter, the file to implement basic hhvm functionality:
  ./hphp/runtime/base/zend-strtod.cpp
contains much the same code for zend_strtod as
    ./hphp/runtime/ext_zend_compat/php-src/Zend/zend_strtod.cpp

This seems confusing, wasteful and clearly expedient at the time.

**Comment by paulbiss** [comment]
Hmm, interesting. The zend-strtod file in base was there long before the zend compat layer was added to ext, and the compat layer was by-in-large in import of the core zend APIs.
