### ISSUE TITLE
intermediate variable access

### ISSUE THREAD

**Issue by gopedib** [facebook/hhvm#5246]
Hi, I was looking at hhvm generated machine codes. I can see, the intermediate variables (producer of prior tracelet and consumer of the following tracelet) across two adjacent tracelets store values to memory at the end of the prior tracelet and reload them at the beginning of the following tracelet w/ associated guard checks. I was wondering what does limit hhvm to keep those intermediate variables in registers and this eliminate the two memory accesses?

**Comment by paulbiss** [comment]
Thanks for the suggestion! Tracelets can be entered into from the interpreter as well as from other tracelets, so the calling convention for entering a tracelet needs to be shared between tracelets that are chained together and enterTC (the main entry point back into the translation cache from the VM).

We've talked about using a smarter calling convention specialized on individual tracelets. I don't think it's been tried yet to see how much it effects performance but it's definitely on our list of things to do.

**Comment by paulbiss** [comment]
This feature request is not actively being worked on. We would happily consider a pull request implementing it. If you plan to work on this issue let us know in the comments and we will re-open the issue and assign it to you. If you feel strongly that this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
