### ISSUE TITLE
WordPress Customizer HHVM Error - BadMethodCallException

### ISSUE THREAD

**Issue by collinbarrett** [facebook/hhvm#5247]
Forgive me if this is not the correct place to ask this, if so, please point me to a more appropriate forum...

So, for the last couple days, I have been getting a white screen of death in the WordPress Customizer. The HHVM (v3.7.0) log is reporting this fatal error:

Uncaught exception 'BadMethodCallException' with message 'Call to a member function is_theme_active() on a non-object (NULL)' in /var/www/mydomain.com/wp-admin/customize.php:88\nStack trace:\n#0 {main}

I do not think I have changed anything (plugins, themes, server config) since it was last working except for possibly the upgrade to WP 4.2 / WP 4.2.1 (I don't specifically remember it working since that upgrade, but I may not have entered the customizer since that upgrade). I am running a multisite installation and I get the same results on all of my sites for both super admins as well as site admins. The customizer gives a white screen with a 500 (hphp_invoke) error in the browser console.

Any ideas on how I can go about debugging this further? Could this be an HHVM / WordPress compatibility bug, or is it more likely something incorrect with my WordPress install? Thanks!

**Comment by steelbrain** [comment]
Does it work with php-fpm? I think this problem is very much a bug in wordpress rather than HHVM.

**Comment by collinbarrett** [comment]
I rolled back to a previous server state and incrementally made all of the changes that I remembered changing since it was working, and I don't have any other issues. I'm not sure what the bug was, but, yes, it was likely a WordPress issues.
