### ISSUE TITLE
Please add s9y/Serendipity

### ISSUE THREAD

**Issue by fishnix** [facebook/hhvm#5248]
Hi!   
Please add https://github.com/s9y/Serendipity to your list of tested frameworks.  
Thanks!

**Comment by bauerj** [comment]
I don't think that would be worth the work.

They only have like three tests and if the date on their Github is correct, parts of their tests are eight years old (although it's a bit odd that the author of phpunit contributed to their tests back then).

**Comment by Orvid** [comment]
I have to agree here, the project has no real tests that we can run.

I'm closing this for now, but if things change, feel free to re-open it.
