### ISSUE TITLE
Incorrect handling of "\e"

### ISSUE THREAD

**Issue by jwatzman** [facebook/hhvm#5252]
Incorrect handling of "\e"

HHVM reports that `var_dump("\e")` => `string(2) "\e"`. The escape sequence is not being recognized.

It should give `string(1) "<esc>"`. (Zend 32/64 have it right.)

**Comment by Orvid** [comment]
The escape sequence should be getting recognized, [scanner.cpp:726](https://github.com/facebook/hhvm/blame/master/hphp/parser/scanner.cpp#L726).

**Comment by jwatzman** [comment]
@meghana1811 can you write up here what you found when you were looking into this? Didn't you hit something really weird?

**Comment by meghana1811** [comment]
@jwatzman http://3v4l.org/Wbe5Z had equivalent php and hhvm behavior, but I had seen different behavior of both php and hhvm on a CentOS machine. 
Php reported: string(1) "
HHVM reported: string(1) " (with no ending new line character)

**Comment by Orvid** [comment]
This looks like it was never an issue, closing.
