### ISSUE TITLE
Process exited with code 137; code runs in all versions of php that support closures

### ISSUE THREAD

**Issue by r3wt** [facebook/hhvm#5257]
http://3v4l.org/O9HeQ

its a long one liner, so i'll dissect it here.
```php
for(
	$i = 3; 
	$i > 0; 
	call_user_func(
		function($i){
			$ob='';
			for( $j = 0; $j<$i; $ob.='Smile!', $j++ );
			echo $ob."\n"; 
		},
		$i
	), 
	$i--
);
```

Some type of PHP incompatibility. code works fine when using function instead of closure:

http://3v4l.org/Ki0PQ

**Comment by paulbiss** [comment]
I can't reproduce the crash, and it appears to be working fine on 3v4l.

**Comment by r3wt** [comment]
Did you even read this post?

it clearly crashes on HHVM 3.6-3.7 on 34v1 : http://3v4l.org/O9HeQ

![img](http://puu.sh/hEupW/fd0506e5fe.png)

you must have scrolled through and clicked the last link to 3v4l.org, which linked to a working version without a closure.

**Comment by paulbiss** [comment]
No idea, transient 3v4l issue maybe?
