### ISSUE TITLE
Optimize subclasses of builtin classes

### ISSUE THREAD

**Issue by paulbiss** [facebook/hhvm#5267]
We currently fail to inline calls to builtin methods when they happen within subclasses that call through to builtin methods with `parent::` or `self::`.

In non-repo mode it should be fairly straightforward to optimize this on direct subclasses of builtins (pretty common in some of these frameworks). In repo mode we can perform the same optimization on indirect decedents via HHBBC since we should be able to understand the entire inheritance hierarchy.

**Comment by jwatzman** [comment]
I didn't manage to get anywhere with this. Was trying to do this by setting the `funcd` using type information from the IR, but when we were munging bytecodes... that didn't work out too well. I suspect we have a better place we can look for these patterns of bytecodes and somehow pass that information along to make sure the `funcd` gets set properly, but I didn't have enough context to do it, especially remote from London while trying to do non-lockdown things there :)

I'm still interested in this, but freeing it up in case someone else wants to take over it on the last day, I'm not going to get to it for lockdown proper.

**Comment by paulbiss** [comment]
If no one else picks it up I'm happy to chat about it when you get back.

**Comment by jwatzman** [comment]
This might be easier to do in the emitter directly.
