### ISSUE TITLE
Optimize CMake build flags

### ISSUE THREAD

**Issue by paulbiss** [facebook/hhvm#5268]
We've likely diverged quite a bit from our internal settings-- let's make sure we're using the best possible build flags. We should also make sure we're building with the best toolchain (switching around versions of gcc has been known to have a measurable impact on perf).

**Comment by jwatzman** [comment]
From one of the Intel guys:

> 3) Using options -ffunction-section + -freorder-blocks-and-partition I see a 0.5%-1% win on wordpress but there a lot of linker features which we don't use yet like ICF - identical code folding so all of them stacked together should yield a measurable win.

**Comment by paulbiss** [comment]
:+1: Want to take this one? I noticed we also do some LTO (link time optimization) internally, probably worth turning that on. I tried turning it on across the board and it slowed things down way too much but turning it on for some files/static libraries may be a reasonable approach.

**Comment by jwatzman** [comment]
Yeah, seems like some easy stuff to play around with in between my shenanigans in London.

**Comment by jwatzman** [comment]
- We're already specifying `-ffunction-sections` internally and externally, so no gain there.
- There are a few flags in internal build flags that aren't external. Adding all these was about a 1% *regression*. Might be worth playing with internally. (I didn't play with them individually because it took too long to rebuild/retest.)
  - `-fno-tree-vectorize`
  - `-fno-ipa-cp-clone`
  - `-fno-unswitch-loops`
  - `-fno-prefetch-loop-arrays`
- Also tested `-freorder-blocks-and-partition` on the OSS build, it was about a 1% *regression* on Wordpress.
- @paulbiss I assume the LTO you are talking about is `-Wl,-icf=all,--gc-sections`, will play with that too.

**Comment by paulbiss** [comment]
Actually it's `-fuse-linker-plugin` and `-flto=<n>`. Also, I'm not sure if we have it on by default as it makes debugging harder but from the original diff it sounds like it has potential (D1117071).

**Comment by jwatzman** [comment]
`-Wl,-icf=all,--gc-sections` (which is specified at FB) was neutral.

For the typical GCC LTO, I tried this patch:

```
diff --git a/CMake/HPHPCompiler.cmake b/CMake/HPHPCompiler.cmake
index 36fbcf0..a7322ef 100644
--- a/CMake/HPHPCompiler.cmake
+++ b/CMake/HPHPCompiler.cmake
@@ -81,11 +81,14 @@ elseif ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
   set(CMAKE_C_FLAGS_DEBUG    "-Og -g")
   set(CMAKE_CXX_FLAGS_DEBUG  "-Og -g")
 
+  set(CMAKE_AR "gcc-ar" CACHE INTERNAL "ar")
+  set(CMAKE_RANLIB "gcc-ranlib" CACHE INTERNAL "ranlib")
+
   # Generic GCC flags and Optional flags
   set(CMAKE_C_FLAGS_MINSIZEREL       "-Os -DNDEBUG")
   set(CMAKE_CXX_FLAGS_MINSIZEREL     "-Os -DNDEBUG")
-  set(CMAKE_C_FLAGS_RELEASE          "-O3 -DNDEBUG")
-  set(CMAKE_CXX_FLAGS_RELEASE        "-O3 -DNDEBUG -fno-gcse ${CMAKE_CXX_OMIT_LEAF_FRAME_POINTER} --param max-inline-insns-auto=100 --param early-inlining-insns=200 --param max-early-inliner-iterations=50")
+  set(CMAKE_C_FLAGS_RELEASE          "-O3 -DNDEBUG -flto -fno-fat-lto-objects")
+  set(CMAKE_CXX_FLAGS_RELEASE        "-O3 -DNDEBUG -fno-gcse ${CMAKE_CXX_OMIT_LEAF_FRAME_POINTER} --param max-inline-insns-auto=100 --param early-inlining-insns=200 --param max-early-inliner-iterations=50 -flto -fno-fat-lto-objects")
   set(CMAKE_C_FLAGS_RELWITHDEBINFO   "-O2 -g")
   set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-O2 -g")
   set(CMAKE_C_FLAGS                  "${CMAKE_C_FLAGS} ${GNUCC_OPT} -w")
```

Compile time didn't seem any different. Linking took >15m and 5G of RAM, which might make this something we can't do. Strangely, the resulting HHVM executable segfaults when running on `perf.php`, but seems to run Wordpress just fine and shows about a 2% improvement there. I'll look into this more extensively tomorrow or Wed.

@paulbiss turning it on for just some files/libraries doesn't really make any sense, AIUI a lot of the benefit is from doing it on the whole program, so the linker can inline across compilation units and things like that.

http://hubicka.blogspot.com/2014/04/linktime-optimization-in-gcc-2-firefox.html was an interesting resource on LTO and the ways to get the compilation flags wrong and not do what you want. (Pretty sure my patch above is correct?)

**Comment by jwatzman** [comment]
About a 1-1.5% win on Drupal7. Backtrace in case someone else wants to quickly look at it:

```
$ gdb --args ../hhvm/hphp/hhvm/hhvm perf.php
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ../hhvm/hphp/hhvm/hhvm...done.
(gdb) r
Starting program: /home/jwatzman/hhvm/hphp/hhvm/hhvm perf.php
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00000000014d1551 in HPHP::tg_3Map_keys(HPHP::ActRec*) ()
(gdb) bt
#0  0x00000000014d1551 in HPHP::tg_3Map_keys(HPHP::ActRec*) ()
#1  0x0000000007403a17 in ?? ()
#2  0x000000000278ee26 in enterTCHelper ()
#3  0x00000000008389a4 in HPHP::jit::x64::(anonymous namespace)::BackEnd::enterTCHelper(unsigned char*, HPHP::ActRec*) [clone .5891011] ()
#4  0x000000000101d7d4 in HPHP::jit::MCGenerator::enterTC(unsigned char*, HPHP::ActRec*) ()
#5  0x0000000001eb64a7 in HPHP::enterVM(HPHP::ActRec*, HPHP::StackArgsState, HPHP::Resumable*, HPHP::ObjectData*, HPHP::VarEnv*) [clone .3138762] ()
#6  0x0000000001eb6943 in HPHP::ExecutionContext::invokeFunc(HPHP::TypedValue*, HPHP::Func const*, HPHP::Variant const&, HPHP::ObjectData*, HPHP::Class*, HPHP::VarEnv*, HPHP::StringData*, HPHP::ExecutionContext::InvokeFlags) [clone .constprop.35100] ()
#7  0x00000000014344b4 in HPHP::include_impl_invoke(HPHP::String const&, bool, char const*) ()
#8  0x0000000002468eac in HPHP::hphp_invoke(HPHP::ExecutionContext*, std::string const&, bool, HPHP::Array const&, HPHP::VRefParamValue const&, std::string const&, std::string const&, bool&, std::string&, bool, bool, bool) ()
#9  0x000000000246c2d8 in HPHP::hphp_invoke_simple(std::string const&, bool) ()
#10 0x00000000024bc136 in HPHP::execute_program_impl(int, char**) [clone .1005430.288400] ()
#11 0x00000000024bedb7 in HPHP::execute_program(int, char**) ()
#12 0x00000000024c15e0 in main ()
```
