### ISSUE TITLE
Huge pages

### ISSUE THREAD

**Issue by paulbiss** [facebook/hhvm#5269]
These are only turned on for internal kernels, we should enable them when supported externally.

**Comment by paulbiss** [comment]
I think I've got this partially working. I'm not seeing anything measurable from huge pages in the JIT, but I haven't gotten hugifyText working for hot runtime functions yet.

**Comment by wjywbs** [comment]
How's your progress? I replaced hash_string_cs_fallback with simply `return hash_string_cs_unaligned_crc(arKey, nKeyLength);` and saw 1-2% improvement. It would be beneficial to get copyHashFuncs working.

https://github.com/facebook/hhvm/blob/4498e2b25bc17ace502b4c86c551dbab25f284bf/hphp/util/hash.cpp#L48

**Comment by paulbiss** [comment]
@wjywbs I had some issues with mapping the text section, I'll see if I can take another swing at it this week. Thanks for the update!

**Comment by markw65** [comment]
We should definitely get the huge page thing working, but we should also probably add a compilation option to just use the sse4 version of the crc code, rather than trying to dynamically patch it. Most people will either want it on, or want it off (rather than having a mix of machines, some with, and some without sse4).

**Comment by octmoraru** [comment]
@paulbiss What was the outcome of this effort? Were you able to make it work or was it dropped?

**Comment by paulbiss** [comment]
@octmoraru we bulk closed a bunch of lockdown issues, we haven't done this yet and we definitely should.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

The last comment in #9063 confirms the huge page support:

>  (in order to make use of the optimization you need to configure the kernel to make huge pages available at boot time, and most users won't want this).
