### ISSUE TITLE
Fast-path for string concatenation

### ISSUE THREAD

**Issue by paulbiss** [facebook/hhvm#5272]
When no resize is needed can call directly to memcpy or for short strings inline the concatenation in the TC to avoid the call entirely. This will likely go very well with smart string size allocations through PGO.

**Comment by jwatzman** [comment]
@paulbiss we're already doing this, right -- https://reviews.facebook.net/diffusion/HHVM/browse/master/hphp/runtime/vm/runtime.cpp;8a587d50f6c03573ebb9a131fe722c4e128247ee$79

Or did you have something else in mind?

**Comment by jwatzman** [comment]
(Did you mean to literally inline that code into the TC, as opposed to being a C++ helper? Seems like a kind of complicated function to do that to?)

**Comment by jwatzman** [comment]
From our in-person conversations and my own digging, I'm pretty sure we are indeed already doing this, please reopen if I've missed something you see :)

**Comment by paulbiss** [comment]
Yeah, I was thinking about inlining more of it into the TC (for example if the string didn't need to be allocated). But since it sounds like we're mostly missing in the non-allocation path probably not worth it.
