### ISSUE TITLE
Pre-allocate extra space for strings

### ISSUE THREAD

**Issue by paulbiss** [facebook/hhvm#5274]
When strings are concatenated sometimes we can reuse the buffer of one of the existing strings. If we track how large buffers of smart allocated strings grow before they are ultimately free'd we can use PGO to allocate appropriately pre-sized strings in hot translations. This will work nicely with an optimization to bypass the slow-path for string resizing.

**Comment by jwatzman** [comment]
I've tried a couple variations of this:

```
diff --git a/hphp/runtime/base/string-data.cpp b/hphp/runtime/base/string-data.c
index 5a2d60e..a74768e 100644
--- a/hphp/runtime/base/string-data.cpp
+++ b/hphp/runtime/base/string-data.cpp
@@ -71,6 +71,7 @@ std::pair<StringData*,CapCode> allocFlatForLen(size_t len) {
   if (UNLIKELY(len > StringData::MaxSize)) {
     throw_string_too_large(len);
   }
+  len += len;
   auto const encoded = CapCode::ceil(len);
   auto const need = encoded.decode() + kCapOverhead;
   if (LIKELY(need <= kMaxSmartSize)) {
```

(that doubles the length, also tried `len += len/4`). Idea was a dumb approximation of what this could do, better CPU at the expense of more memory usage. No change in Drupal 7 RPS, and I don't think a significant change in the profile of the callers of `memcpy`. Will continue playing around a little tomorrow, but not super hopeful here.

**Comment by jwatzman** [comment]
Same with

```
diff --git a/hphp/runtime/base/string-data.cpp b/hphp/runtime/base/string-data.cpp
index 5a2d60e..45af1a5 100644
--- a/hphp/runtime/base/string-data.cpp
+++ b/hphp/runtime/base/string-data.cpp
@@ -54,6 +54,7 @@ ALWAYS_INLINE
 std::pair<StringData*,CapCode> allocFlatForLen(size_t len) {
   static_assert(StringData::MaxSize + 1 < CapCode::Max, "");
   static_assert(CapCode::Threshold >= kCapOverhead, "");
+  len += len;
 
   if (LIKELY(len <= CapCode::Threshold - kCapOverhead)) {
     // fast path for most small strings
```

which not only didn't help, but made the RPS less for some reason I didn't track down. Since overallocating isn't decreasing the number of `memcpy`s, I'm going to close this as not worth the not insignificant effort to get working.
