### ISSUE TITLE
Cache common allocation sizes

### ISSUE THREAD

**Issue by paulbiss** [facebook/hhvm#5275]
Create a thread-local cache for common allocation sizes that can be accessed directly from the TC without a call into C++. This issue goes with similar issues created for caching common string, object, and array sizes.

**Comment by edwinsmith** [comment]
are you talking about a new cache, or just inlining the fast-path of the allocator (check the freelist, only call into C++ on empty freelists). I'm skeptical about overhead of a new cache data structure.

**Comment by paulbiss** [comment]
Inlining the freelist check may be the best way to go. The thought was that if particular sizes are very hot it may be worth having free blocks of those sizes ready to go. Probably not worth doing, but it seemed like a nifty way to use PGO to speed up common allocations.
