### ISSUE TITLE
Update 3.7

### ISSUE THREAD

**Issue by cooleisbaer** [facebook/hhvm#5280]
Hi there.
As announced, 3.7 should be avaible -> http://hhvm.com/blog

But for my Ubuntu 12.04 I just get 3.6.2 via apt-get update/upgrade and then apt-get install hhvm.

**Comment by paulbiss** [comment]
Sorry, we've dropped support for 12.04 with 3.7 (we will continue to support 12.04 with new 3.3 and 3.6 packages).
