### ISSUE TITLE
Investigate disabling EnableObjDestruct

### ISSUE THREAD

**Issue by paulbiss** [facebook/hhvm#5281]
It may break some of these frameworks and it's technically not compatible with vanilla PHP but it would give us an upper bound on the potential wins from optimizing the object destruction table.

We have this off internally for production and it makes a huge difference in object allocation time. At a bare minimum we should do something to make this hashmap faster.

**Comment by r3wt** [comment]
:+1:

**Comment by paulbiss** [comment]
Tried this and didn't really see much when setting the option. It's possible user defined constructors aren't common enough to make it matter in any of these frameworks.
