### ISSUE TITLE
Optimize Unserialize

### ISSUE THREAD

**Issue by paulbiss** [facebook/hhvm#5283]
Functions split between units, variable unserializer class is a mess
* f_unserialize (ext_std_variable.cpp)
* unserialize_ex (builtin-functions.cpp)
* VariableUnserializer::unserialize (variable-unserializer.cpp)
* unserializeVariant (type-variant.cpp)
* Various calls back into variable-unserializer.cpp

**Comment by paulbiss** [comment]
I tried reducing the indirection here and didn't see a lot, I think most of the cost is coming from string copies. Per @fredemmott's patch to mediawiki there isn't a lot of value in this anymore, marking as wishlist.

**Comment by Orvid** [comment]
We're a small team, and it doesn't look as though anyone in the community is actively working on this issue, so we've decided to close it. If you plan to send us a pull request resolving the issue let us know in the comments and we will re-open it and assign it to you. If you feel this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
