### ISSUE TITLE
Optimize Array/Object casts

### ISSUE THREAD

**Issue by paulbiss** [facebook/hhvm#5285]
Array <=> Object casts are common in wordpress. We can just juggle the dynprop array.

Fast path for casting an array to an object would be to promote array to a dynprop array for a new stdClass-- this may be visible if the array contains refs but that's good (http://3v4l.org/9sF88) since the current behavior is actually broken.

**Comment by edwinsmith** [comment]
are they typically Objects with no declared properties and only dynamic properties?

**Comment by paulbiss** [comment]
Yeah, the typical cast is `(object)$array` which creates a new `stdClass` with dynprops from the array.

**Comment by paulbiss** [comment]
Doing this in conjunction with fixing up `get_object_vars` is getting me what appears to be a small gain in rps. I'm still trying to verify that it's outside the noise, but there are a few hot functions in wordpress that take advantage of this.
