### ISSUE TITLE
Optimize mem* standard library functions

### ISSUE THREAD

**Issue by paulbiss** [facebook/hhvm#5305]
memset, memcmp, memchr; RDS (request data segment) memset clearing - optimize these functions similarly to what was done for memcpy. This looks like about .6% of CPU time. We think the speedup from this may be too small to distinguish from noise.

**Comment by apinski-cavium** [comment]
You should file a bug upstream in glibc if you find an better implementation.  Also you should try a newer version of glibc before trying to optimize this functions as there have been some implementations done for newer intel chips by the folks at Alibaba.

**Comment by paulbiss** [comment]
@apinski-cavium: we have our own implementations of some of these functions, and what's faster for us may not be faster in general. That being said I don't think much was done here during our lockdown.
