### ISSUE TITLE
Experiment with gcc’s auto FDO (feedback directed optimization)

### ISSUE THREAD

**Issue by paulbiss** [facebook/hhvm#5306]
Skeptical about the practicality of this but I'd be interested to see how it does.

**Comment by sathvikl** [comment]
Here are the numbers with various compiler options on wordpress-4 - 
---------------------------------------------------------------------------------------------
compiler           ||     fps  #         ||     binary size   ||        options       ||
---------------------------------------------------------------------------------------------
gcc 4.8.2          ||     342-356     ||        68 MB     ||     default-baseline
gcc 4.8.2          ||     298-305     ||        38 MB     ||     -fprofile-generate + -fprofile-use 
gcc 4.9-google ||     360-377    ||         39 MB     ||     -fauto-profile
gcc 4.9-google ||      311-318    ||        37 MB     ||     -fprofile-generate + -fprofile-use 

The auto-profile option is only available in GCC 5.1.0 and the google gcc branch 4.8+ it takes only the lbr data which is near taken branches and branch misses to do the code optimizations, more info is here https://gcc.gnu.org/git/?p=gcc.git;a=commitdiff;h=94bed7c33d801ea3b1fb6b10ff395af74a98244e

The options to deploy it would be to get HHVM to compile with GCC 5.1.0 or use the auto-profile input 
and convert it to something (.gcno + .gcda) that -fprofile-generate can use.
