### ISSUE TITLE
Experiment with gcc alignment settings

### ISSUE THREAD

**Issue by paulbiss** [facebook/hhvm#5307]
Measure the performance effects of varying the –falign-functions, -falign-labels, -falign-loops, and -falign-jumps.

**Comment by jwatzman** [comment]
In particular, the FB internal build scripts specify a lot of these (in `hphp/BUILD_FLAGS` I think) -- do we set the same ones in the cmake build? If not, that's probably a good place to start. Beyond that... do the ones that work best for FB actually make sense externally?

**Comment by jwatzman** [comment]
See also #5268

**Comment by apinski-cavium** [comment]
I don't think you should do this really.  If you find that effects the performance, it is best if GCC defaults to the correct one for the target.  ARM64 will have a different behavior for each target too.

**Comment by paulbiss** [comment]
@apinski-cavium: we use very specific settings internally. We've found that tuning these does a lot for performance on our workload and want to study the effects on other workloads (and make sure that our external settings match those internally effective as our cmake scripts already use many custom tuned options).
