### ISSUE TITLE
Check likely/unlikely hinting

### ISSUE THREAD

**Issue by paulbiss** [facebook/hhvm#5309]
Measure branch prediction and cache line packing effects of the LIKELY() and UNLIKELY() macros in HHVM sources to ensure these are providing the correct predictions. There are a lot of these (~2000) so this could take a long time to do. (This may be too tedious to do during lockdown).

**Comment by jwatzman** [comment]
I'm not super convinced this is something we can do a lot with, and seems better left for the JIT team?

**Comment by paulbiss** [comment]
I'm not super optimistic that they're going to be able to do much with it either. There are somewhere around 860 of them under hphp (and more littered elsewhere in dependent libraries), and the only thing we know for sure is that removing all of them is a regression.

The effect of any one of these would be unlikely to be measurable, and nearly all of them were placed based solely on intuition.

**Comment by jwatzman** [comment]
Doing something completely unrelated, I came across this in the Linux kernel: https://github.com/torvalds/linux/blob/v4.0/include/linux/compiler.h#L111-L136

Basically, we could make our `LIKELY`/`UNLIKELY` macros actually record the result of the branch in some debug mode, so we could check our intuition, see what the distribution is, etc. Still some work in recording, printing, etc this data, as well as reading the data and playing with the results, but there's probably stuff to look at here.

**Comment by paulbiss** [comment]
I like this idea!

**Comment by jwatzman** [comment]
If you don't mind, I still think this is worth doing, unless it's been done internally (which I wouldn't have heard about)? I may come back to it at a hackathon or something for fun.

**Comment by Orvid** [comment]
I just went through and closed all of the lockdown issues, which is where this came from :P

**Comment by Orvid** [comment]
There are some automated tools that, with some modification, would do this far better and easier than manual review, so this is a task best discussed internally.
