### ISSUE TITLE
Please add Bonfire to your list of tested frameworks

### ISSUE THREAD

**Issue by alexandre0sheva** [facebook/hhvm#5313]
Hi!

Please add https://github.com/ci-bonfire/Bonfire  to your list of tested frameworks.

Thanks!

**Comment by fredemmott** [comment]
We only support PHPUnit tests; while these look very similar, they're actually SimpleTest.

**Comment by fredemmott** [comment]
(we're not against supporting additional test systems, it just isn't a productive use of our time - we'd be happy to review pull requests)
