### ISSUE TITLE
Inconsistency with ~ bitwise operator on string

### ISSUE THREAD

**Issue by 5lava** [facebook/hhvm#5315]
(HHVM 3.7.0)
```php
<?hh // strict
function f():string {
	return ~"xxx";
}
```

Result:
```
Typing error (Typing[4110])
This is an int because this is used in an arithmetic operation
It is incompatible with a string
```

However:
```php
<?hh
assert(~"xxx" instanceof string);
var_dump(~"xxx");
```
confirms `~"xxx"` it's still a string.

PHP documentation (http://php.net/manual/en/language.operators.bitwise.php): *If the operand for the ~ operator is a string, the operation will be performed on the ASCII values of the characters that make up the string and the result will be a string*.

Hack documentation (http://docs.hhvm.com/manual/en/language.operators.bitwise.php) is not clear about that.

**Comment by paulbiss** [comment]
The error message is a typing error from the Hack typechecker, while the code is executed by the hhvm runtime. The runtime supports `~` on strings because it's a PHP language feature, however, Hack does not recognize `~` on strings.

**Comment by 5lava** [comment]
Thank you. Maybe it's worth mentioning it in Hack documentation.

Btw, just curious, what's wrong with ~ operator applied to a string (from Hack's/Facebook's point of view)?

**Comment by paulbiss** [comment]
Well it's an odd operator to want to use on a string. In the case of `~"foo"` it's pretty clearly intentional, however, it's less clear that `~$foo` is correct or that `$foo` should have been an integer. In any event I think the operator added little to the language and the feeling was that Hack was better off without it.

**Comment by 5lava** [comment]
Thank you Paul.
