### ISSUE TITLE
HHVM always compresses output if Accept-Encoding: gzip is set, even if zlib.output_compression=Off is set

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#5316]
Should be off by default. Recurrence of #3744

**Comment by Orvid** [comment]
This is caused by some malformed logic in [transport.cpp:811-821](https://github.com/facebook/hhvm/blob/master/hphp/runtime/server/transport.cpp#L811-821) In particular, the current logic reads as:
```
compressionLevel = gzipCompressionLevel;
if (zlib.output_compression) { compressionLevel = zlip.output_compresssion_level; }
compress(compressionLevel);
```

**Comment by werdnum** [comment]
Workaround: set zlib.output_compression to true and zlib.output_compression_level to 0

**Comment by Orvid** [comment]
This has been fixed.
