### ISSUE TITLE
Wordpress wp-admin fails with hhvm

### ISSUE THREAD

**Issue by cortopy** [facebook/hhvm#5323]
I've been reading that HHVM is 100% compatible with Wordpress now. However, it's not working for my wp-amin page (e.g.: http://code.tutsplus.com/articles/using-hhvm-with-wordpress--cms-21596)

To be more precise, HHVM is unable to handle `load-scripts.php`

Is it true that HHVM is fully compatible now?

**Comment by Mwesome** [comment]
I have ran wordpress on hhvm for a few weeks and it ran fine.
Could you tell us exactly what is happening, what errors are you getting?

**Comment by cortopy** [comment]
Thanks for the reply @Mwesome 
Having read what you said, I've done more digging and it turned out nginx was causing the problem. Sorted now
