### ISSUE TITLE
Please add support for Vector<Foo> User Defined Types (UDT)

### ISSUE THREAD

**Issue by user1862165** [facebook/hhvm#5324]
It would really help me to be able to do this:
```
<?hh
#imaginary code
CreateUDT Foo = <string,int,int>;
$iv = ImmVector<Foo> {
['uuid1',425,244],
['uuid2',658,836]
};
print_r($iv);
```

You mentioned Vector&lt;Foo&gt; here
http://docs.hhvm.com/manual/en/hack.collections.literalsyntax.php

I really need it :) Please add+++

http://stackoverflow.com/questions/30158012/hhvm-staticly-typing-lookup-tables-and-keeping-them-fully-cached-in-ram

**Comment by paulbiss** [comment]
We currently support newtype and type to create type aliases. From your example it looks to me as though what you're asking for is union types. I'll let @jwatzman explain why we don't want to support those.

**Comment by nikic** [comment]
Maybe looking for tuples?

```php
<?hh
newtype Foo = (string,int,int);
$iv = ImmVector<Foo> {
tuple('uuid1',425,244),
tuple('uuid2',658,836),
};
print_r($iv);
```

**Comment by paulbiss** [comment]
Ah, I misread the example, yeah that looks like what he's looking for.

**Comment by jwatzman** [comment]
Yeah, I think a tuple is what you want. @user1862165, does what @nikic suggested work for you?

**Comment by user1862165** [comment]
@nikic I'm looking at your example above, but I don't see how the line `type Foo = (string,int,int);` **relates to the lines following that?**

I was hoping there would be a way to create a UDT (string,int,int) and then create an ImmVector such that any code accessing **any element** of the vector, knows exactly what types to expect without inspecting that element?

http://docs.hhvm.com/manual/en/hack.tuples.implementation.php says that tuples are currently implemented as pure php:
`function tuple(...) { return func_get_args();}`
That's not going to improve performance at all?

I'm not interested in doing this from a bugs-finding perspective (getting type checking errors)

I'm just looking to get whatever performance benefits I can.

If you look at my (imaginary) code above it gives an idea of what I'm looking for. A way to create a vector where **every** value in the vector's type is already known by looking at the ImmVector definition, without even looking at the vector's values. `$iv = ImmVector<Foo> {`

**Comment by paulbiss** [comment]
IIRC tuples are implemented as an ast level transform to an array, but hack understands their types statically.

**Comment by user1862165** [comment]
@paulbiss: thanks, please see above.

**Comment by paulbiss** [comment]
Well, `ImmVector<Foo> { ... }` isn't valid hack (just leave out <...> hack will figure out the type). If you're interested only in perf an `array(...)` is going to be faster than an `ImmVector`. I should also add that you can store a static array in APC and it won't need to be serialized/deserialized.

In any event tuples are arrays so they're quite fast, Vectors currently aren't as fast as arrays, and their construction can't be done statically and in place in the same fashion (yet).

**Comment by user1862165** [comment]
Oh, that's unexpected. I would have thought Vectors would be faster than arrays, since you don't have to check the index type, and an ImmVector even faster because you know it's constant.

Ah well :/

**Comment by user1862165** [comment]
In that case, when will const arrays be fixed? https://github.com/facebook/hhvm/issues/4277

**Comment by fredemmott** [comment]
Vectors and ImmVectors have the potential to be faster for the reasons you said - the optimizations haven't been done yet though.

**Comment by user1862165** [comment]
Ok, please let me know when they are.

I'm considering trying out a C implementation soon, where I can avoid type checking on every iteration for the array indexes and the values.
If I do move to C I'll probably keep using HHVM for developing new algorithms. I'll have to see after I get more experience deving my project in C.

**Comment by Orvid** [comment]
We're a small team, and it doesn't look as though anyone in the community is actively working on this issue, so we've decided to close it. If you plan to send us a pull request resolving the issue let us know in the comments and we will re-open it and assign it to you. If you feel this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
