### ISSUE TITLE
Wrong behaviour of lchgrp

### ISSUE THREAD

**Issue by dosten** [facebook/hhvm#5330]
I'm not sure if this is a expected behaviour or not, but if i do `lchgrp('myfile.txt', 'invalid_group');` this returns `true`, in php this same piece of code returns false because the group doesn't exists.

**Comment by fredemmott** [comment]
This should be fixed in the nightly builds and the next release: https://github.com/facebook/hhvm/commit/8358b899bfd6d224fb85b08d7a2620172bf0fc7a
