### ISSUE TITLE
AsyncMysqlConnectionPool acts weirdly

### ISSUE THREAD

**Issue by 5lava** [facebook/hhvm#5331]
HHVM 3.7.0.

```php
<?hh
$pool = new AsyncMysqlConnectionPool([]);
$db = $pool->connect('127.0.0.1', 3306, 'db', 'user', 'password')->getWaitHandle()->join();
```
This code works perfectly fine in interactive mode (`hhvm -a`).
However when executed as file (`hhvm file.php`) it throws `AsyncMysqlConnectException` with message `Error executing AsyncMysql operation: TimedOut (mysql error: 1041: connection to 127.0.0.1:3306 timed out in pool(open 0, opening 0) (took 1003.51ms))'` and does not actually make a connection to MySQL.

Now let's remove `$db = ` assignment:
```php
<?hh
$pool = new AsyncMysqlConnectionPool([]);
$pool->connect('127.0.0.1', 3306, 'db', 'user', 'password')->getWaitHandle()->join();
```
This doesn't throw any errors and actually does connect to MySQL (the connection is seen in MySQL). The program finishes normally but after some noticeable pause...
```php
<?hh
$pool = new AsyncMysqlConnectionPool(['idle_timeout_micros' => 5e6]);
$pool->connect('127.0.0.1', 3306, 'db', 'user', 'password')->getWaitHandle()->join();
echo "foo\n";
```
Turns out the pause is as long as `idle_timeout_micros` (I see echoed `foo` and the program finishes after 5 seconds).

Now let's get back to the original code, get rid of `$pool` and make the code one-liner:
```php
<?hh
(new AsyncMysqlConnectionPool([]))->connect('127.0.0.1', 3306, 'db', 'user', 'password')->getWaitHandle()->join();
```
This throws `AsyncMysqlConnectException` with message `Error executing AsyncMysql operation: Cancelled'`.

Looks like GC/memory management related.

**Comment by fredemmott** [comment]
It's uninitialized memory in the implementation - the specific cases where it works vary from system to system. #5143

**Comment by 5lava** [comment]
Thanks @fredemmott, somehow I missed that ticket when searched for similar issues.
