### ISSUE TITLE
AsyncMysqlClient and UNIX sockets

### ISSUE THREAD

**Issue by 5lava** [facebook/hhvm#5332]
Currently there's no way to connect to UNIX socket using `AsyncMysqlClient`: https://github.com/facebook/squangle/blob/master/squangle/mysql_client/Operation.cpp#L320
I was told (in IRC) this feature isn't there because you guys don't need it (pretty reasonable :)).

Desired (perhaps) can be achieved by using `adoptConnection()`, but it's still a workaround. Is UNIX socket connection with `connect()` somewhat planned?

Thank you.

**Comment by fredemmott** [comment]
it's not planned. It's probably best to file an issue against Squangle first - if they add support for it, it'll be very easy to get it into hhvm.

**Comment by paulbiss** [comment]
This feature request is not actively being worked on. We would happily consider a pull request implementing it. If you plan to work on this issue let us know in the comments and we will re-open the issue and assign it to you. If you feel strongly that this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
