### ISSUE TITLE
MySQLi persistent connections aren't persistent

### ISSUE THREAD

**Issue by 5lava** [facebook/hhvm#5334]
Tested on HHVM 3.7.0 and nightly.

Following code is supposed to create persistent connection to mysql (hostname is prepended with `p:`).

``` php
<?php
$db = new MySQLi('p:127.0.0.1', 'root', 'testpass');
```

Connection stays alive when the code is run with php-fpm, but it's closed when run with hhvm (connection is created but then closed).

**Comment by fredemmott** [comment]
Is it definitely being closed, not just getting a different connection for the next request? How are you confirming this?

It looks like it's implemented, however it's persistent per-thread - so, by default, there will be up to 2*cores persistent connections if under load, and worst case you won't start seeing re-use until you reach that point.

**Comment by 5lava** [comment]
* mysql's `show processlist` confirms there are no open connections;
* next connection to mysql gets subsequent id, which confirms the connection from hhvm was actually established.

**Comment by fredemmott** [comment]
Thanks - your first point shows a problem, the second doesn't because of the thread-local sharing.

**Comment by 5lava** [comment]
I meant mysql's connection id, not PHP resource id. As far as I know mysql's connection id is growing monotonically (while the instance is running) — I might be wrong though, it's just based on my observations. If don't execute that php script, next mysql connection would get `id=(last_seen_id + 1)`, instead of `(last_seen_id + 2)`.

**Comment by fredemmott** [comment]
I'd expect it to increase monotonically until you have 2*CPU-cores requests, as that's the default value of hhvm.server.thread_count - though, as you mentioned, `show processlist` should have kept showing them.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Hhvm no longer supports the mysqli extension. It was dropped in version [4.9.0](https://hhvm.com/blog/2019/06/10/hhvm-4.9.0.html) which released in June of 2019.
