### ISSUE TITLE
Use of undefined constant JSON_OBJECT_AS_ARRAY - assumed 'JSON_OBJECT_AS_ARRAY'

### ISSUE THREAD

**Issue by gossi** [facebook/hhvm#5335]
Hey,

One of my test suites is failing on travis, see here: https://travis-ci.org/phootwork/json/jobs/62220828

I am using the constant `JSON_OBJECT_AS_ARRAY`, which gives the error: `Use of undefined constant JSON_OBJECT_AS_ARRAY - assumed 'JSON_OBJECT_AS_ARRAY'`

php says:
```
$ php -r "echo JSON_OBJECT_AS_ARRAY;"
1
```

php: 5.4.40
hhvm: 3.5.0

gossi

**Comment by staabm** [comment]
php has this const since 5.4
hhvm seems not to support it at all, even in newer stable versions:

http://3v4l.org/50NU6

**Comment by fredemmott** [comment]
Just to check: how are you expecting to use this? It appears to be completely undocumented.

I guess you're just using it as a truthy value to pass to the boolean second argument of json_decode() ? It doesn't seem like it should be valid for $options

**Comment by gossi** [comment]
I made a json-wrapper library and supported the available php constants: https://github.com/phootwork/json

Well, travis failed with hhvm at the end.
