### ISSUE TITLE
HHVM crash with JIT turned on when compiled with gcc 5.1.0

### ISSUE THREAD

**Issue by sathvikl** [facebook/hhvm#5343]
Using the CXX flags -Wno-error=narrowing -Wno-bool-compare -D_GLIBCXX_USE_CXX11_ABI=0  
and removing third-party/re2/src/re2/testing/re2_test.cc 
( or using https://github.com/google/re2/commit/7d502a5ba41476f935bdb965f0d68c7ce01979cd )
will fix all compilation errors.  
use -DFOLLY_HAVE_MALLOC_H so that malloc.h is included for malloc_usable_size(). 

This should resolve all compilation errors. However while executing it crashes when JIT is turned on with this trace. 

Although hphp/vm/debug/gdb-jit.cpp registers the JITed functions I am not able to see any function names here -

#0  0x0000000000d6a466 in iopDefCns (pc=<optimized out>) at /home/sathvikl/HHVM/apr29-src/hphp/runtime/vm/bytecode.cpp:3809
#1  iopRetWrapper (pc=<optimized out>, fn=<optimized out>) at /home/sathvikl/HHVM/apr29-src/hphp/runtime/vm/bytecode.cpp:7561
#2  HPHP::interpOneDefCns (fp=0x2e002ae, sp=0x2e002ae, pcOff=48235182) at /home/sathvikl/HHVM/apr29-src/hphp/runtime/vm/bytecode.cpp:7610
#3  0x0000000002e003cc in ?? ()
#4  0xf045c74809f845c6 in ?? ()
#5  0xf0758d4800000001 in ?? ()
#6  0x8948c28948c18948 in ?? ()
#7  0x48c58948c48948c3 in ?? ()
#8  0xc08949c78948c689 in ?? ()
#9  0x8949c28949c18949 in ?? ()
#10 0x49c58949c48949c3 in ?? ()
#11 0x0f4866c78949c689 in ?? ()

see also #5208 #5184

**Comment by Orvid** [comment]
I believe this has already been fixed.
