### ISSUE TITLE
PHP Incompatibility: Class undefined: MultipleIterator

### ISSUE THREAD

**Issue by r3wt** [facebook/hhvm#5350]
It's bummer too because i really needed(**wanted**) it.
http://3v4l.org/JBhNb

```php
$required = [1,2,3];
$optional = [4,5,6];
$rules = new MultipleIterator(MultipleIterator::MIT_KEYS_ASSOC);
$rules->attachIterator( new ArrayIterator($required) , 'required' );
$rules->attachIterator( new ArrayIterator($optional), 'optional' );

foreach($rules as $rule){
    echo $rule['required'].'<br/>';
    echo $rule['optional'].'<br/>';
}
```

**Comment by alesblaznik** [comment]
@r3wt I've just tried on my HipHop VM 3.6.2 (rel) and it works. As it is said in the docs, SPL library is integrated by itself: https://github.com/facebook/hhvm/wiki/Extensions

**Comment by r3wt** [comment]
< please> </please>

**Comment by jwatzman** [comment]
I'm not sure when we'll have time to get to this, sorry. Would be more than happy to review a PR for it if you're interested in implementing it yourself.

**Comment by lorenzo** [comment]
Would submitting a php implementation work?

**Comment by paulbiss** [comment]
If it's compatible with the PHP 5 implementation, absolutely!

**Comment by lorenzo** [comment]
I made this package out of the original implementation in SPL. Will try to make it pass using the core php tests during this week and then submit it to hhvm. https://github.com/lorenzo/multiple-iterator

**Comment by paulbiss** [comment]
Awesome! You'll want to add it to systemlib here:

https://github.com/facebook/hhvm/tree/master/hphp/system/php/spl/iterators

**Comment by r3wt** [comment]
@sgolemon  Thanks!
