### ISSUE TITLE
Shell script for automatic repo generation

### ISSUE THREAD

**Issue by jwatzman** [facebook/hhvm#5356]
Repo auth is vaguely complicated to set up. There are all sorts of magic clever things we can do to generate it in the background etc... but as a quick setup, we can ship a shell script in our Debian repos to generate it, turn on the INI option, etc. (And another to turn it off.)

**Comment by jrobeson** [comment]
is there any reason it shouldn't go in this repo itself vs specifically for debian packages?

**Comment by jwatzman** [comment]
Hm yeah, I was thinking that we'd have to hardcode the paths etc, but I think we can just read the relevant bits out of the INI files. That's a better idea :)

**Comment by jwatzman** [comment]
This is done, committed, and wiki pages updated.
