### ISSUE TITLE
Request: Complete builtins_spl.hhi

### ISSUE THREAD

**Issue by tslettebo** [facebook/hhvm#5359]
We're using the SPL iterators and noticed that some of them were not recognised by the typechecker.

We're adding these components locally for now.

**Comment by jwatzman** [comment]
Happy to take a PR for this!

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

I have found all iterators which are on [this list](https://www.php.net/manual/en/spl.iterators.php) in the php manual.
They are all present to the typechecker.
