### ISSUE TITLE
oss ubuntu 14.04 build broken regarding clientCheckStatus.mli

### ISSUE THREAD

**Issue by rrh** [facebook/hhvm#5363]
Doing a careful git bisect, it appears that commit 7e4edce breaks the build on OSS Ubuntu 14.04. The commit changes the name/suffix of clientCheckStatus and then there's a missing cmi file. I know nothing of the ocaml portion of hhvm, so can't comment on a fix.

Mentioning https://github.com/int3

Here's the output from make:

/usr/bin/ocamlc.opt -c -I client -I globals -I stubs -I utils -I typing -I deps -I parsing -I socket -I search -I procs -I hhi -I heap -I naming -I dfind -I h2tp -I server -I fsnotify_linux -I format -I third-party/inotify -I third-party/core -I third-party/avl -I h2tp/mapper -I h2tp/test -I h2tp/unparser -I h2tp/common -o client/clientCheckStatus.cmo client/clientCheckStatus.ml File "client/clientCheckStatus.ml", line 1: Error: Could not find the .cmi file for interface client/clientCheckStatus.mli. [ 30%] Command exited with code 2.

**Comment by jwatzman** [comment]
`cd hphp/hack/src; rm -rf _build` should fix it.

The way ocaml builds is incredibly stupid and prone to breakages like this. There are certain changes you can make where there's no way to rebuild, you just have to clean. I guess this was one of them.
