### ISSUE TITLE
ArrayObject data reference

### ISSUE THREAD

**Issue by Raphhh** [facebook/hhvm#5372]
When it receieve an object as data, ArrayObject does not use it with a reference behaviour.

For example:

```php
$arrayObject1 = new ArrayObject(['key' => 'abc']);
$arrayObject2 = new ArrayObject($arrayObject1);

//we redefine the value of the first object
$arrayObject1['key'] = 'def';

//we test the value of the second object
var_dump($arrayObject2['key']); //'def' for php but 'abc' for hhvm
```

See build with different php versions and hhvm: https://travis-ci.org/Raphhh/puppy-config/builds/53544511

**Comment by SiebelsTim** [comment]
Duplicate #4645

Though it might be worth mentioning this over there, so it is more clear.
