### ISSUE TITLE
hhvm apc gui

### ISSUE THREAD

**Issue by motiejuss** [facebook/hhvm#5373]
Is there a web gui for apc monitoring? I'm using WordPress W3 Total Cache. APC caching is enabled and I can verify it by viewing html commented output at the bottom of each page:

```
Page Caching using apc
Database Caching 39/65 queries in 0.006 seconds using apc
Object Caching 3856/3900 objects using apc
```

`apc.php` doesn't seem to be working (got it from: https://pecl.php.net/package/APC)

Any suggestions?

**Comment by paulbiss** [comment]
We don't have an apc gui, but our admin server does support a few apc commands.

https://github.com/facebook/hhvm/blob/master/hphp/runtime/server/admin-request-handler.cpp#L214-L222

**Comment by paulbiss** [comment]
This feature request is not actively being worked on. We would happily consider a pull request implementing it. If you plan to work on this issue let us know in the comments and we will re-open the issue and assign it to you. If you feel strongly that this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
