### ISSUE TITLE
Generics not solidifying

### ISSUE THREAD

**Issue by kilahm** [facebook/hhvm#5387]
I'm quite confused by this snippet:

```php
<?hh // strict

class A<T>
{
    public function __construct(private T $x)
    {
    }

    public function in(T $y) : void
    {
    }
}

function test() : void
{
    $a = new A('a');
    $a->in(1);
}
```

I would think that since `A` is instantiated with a string, the generic `<T>` should resolve to type `string` for that instance.  Yet, the type checker has no problems with an `int` as a parameter to method `A::in`.

My expectation that `$a->in(1)` should be a type error seems to be supported by the [docs](http://docs.hhvm.com/manual/en/hack.generics.class.php), especially the comment:

```
// The mailbox can contain any type, but, per instantiation, once associated
// with a type, it cannot change. Mailbox<int>, Mailbox<string>, Mailbox<mixed>
```

This seems to imply that `$a` is of type `A<string>` because of the constructor parameter, and the generic type cannot change after it is thus set.

Is this expected behavior?  Is the type checker treating the instance `$a` as type `A<mixed>` after calling `$a->in(1)`?

**Comment by jwatzman** [comment]
>  Is the type checker treating the instance $a as type A<mixed> after calling $a->in(1)?

Yep. We don't fix the type until you hit a type annotation, either by passing to another function or returning from the current function. But we do track it -- this code, for example, is an error:

```hh
<?hh // strict

class A<T> {
    public function __construct(private T $x) {}
    public function in(T $y): void {}
    public function get(): T { return $this->x; }
}

function test(): int {
  $a = new A('a');
  $a->in(1);
  $a->get(); // Error: T can be a string
}
```
