### ISSUE TITLE
hhvm server bind on ipv4 + ipv6 parallel?

### ISSUE THREAD

**Issue by Reiner030** [facebook/hhvm#5393]
Hello,

There is yet no option to bind on both stacks in parallel... 
If I use localhost it binds only to IPv6.

```
hhvm.server.ip = 127.0.0.1,::1
```
gave this error:
```
Uncaught exception: Failed to resolve address for "127.0.0.1,::1": Name or service not known (error=-2): Unknown error -2
```
and no port binding.

And this line:
```
hhvm.server.ip  = 127.0.0.1 ::1
```

binds also only on IPv4:
```
# lsof -nPi :9000
COMMAND   PID     USER   FD   TYPE     DEVICE SIZE/OFF NODE NAME
hhvm    14819 www-data   17u  IPv4 1932820148      0t0  TCP 127.0.0.1:9000 (LISTEN)
```` 

Bests

Reiner

**Comment by paulbiss** [comment]
This feature request is not actively being worked on. We would happily consider a pull request implementing it. If you plan to work on this issue let us know in the comments and we will re-open the issue and assign it to you. If you feel strongly that this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
