### ISSUE TITLE
mysqli_result does not implement Traversable

### ISSUE THREAD

**Issue by addshore** [facebook/hhvm#5395]
Since 5.4 php mysqli_result has implemented Traversable

In current master of hhvm this is not the case:
https://github.com/facebook/hhvm/blob/master/hphp/runtime/ext/mysql/ext_mysqli.php#L882

Found by debugging https://phabricator.wikimedia.org/T100164

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Mysqli is nolonger supported. Support was dropped in hhvm [4.9.0](https://hhvm.com/blog/2019/06/10/hhvm-4.9.0.html).
