### ISSUE TITLE
Hack chokes parsing gotos

### ISSUE THREAD

**Issue by Aatch** [facebook/hhvm#5401]
While I understand Hack not liking `goto` for type-checking reasons, I should be able to throw an unsafe or two around and still use `goto` fine, however Hack cannot parse `goto` statements correctly:

``` php
<?hh

function foo() {
    // UNSAFE
    $foo = "abc";
    goto bar;
    echo "I'm not printed";
    bar:
    echo $foo;
}
```

The output is: `File "test.php", line 6, characters 10-12: Expected ; (Parsing[1002])`

This is a big issue since the only way to prevent it is to use `// decl`, however that leads to #5402. In my code at least.

**Comment by jwatzman** [comment]
Yeah, the typechecker parser doesn't parse all of PHP (because it's enormously complicated in a lot of places), so there are some PHP constructs you can't use even with `UNSAFE`. I'm... not sure how I feel about this one, given how bad `goto` is. Probably not something we'll have time to implement, but if a PR wasn't too invasive, I'd consider taking it.

**Comment by Aatch** [comment]
@jwatzman while I understand not parsing some of the more obscure constructs, `goto` is hardly obscure. `goto` isn't really that bad, it's just easy to misuse. The code using it would be much more complex if I couldn't use `goto` at all.

**Comment by paulbiss** [comment]
cc @sgolemon :D 

(pretty sure she wrote the original implementation of goto for PHP)

**Comment by fredemmott** [comment]
The story so far:
In the beginning the Goto was created.
This has made a lot of people very angry and been widely regarded as a bad move.

**Comment by DemiMarie** [comment]
@jwatzman Both D and even Go have goto, as does C#, so I think that goto should be allowed.

**Comment by Orvid** [comment]
@DemiMarie D, Go, and C# all require explicit declaration of variables and their types. Hack does not. It is not (with the current design) possible for the typechecker to implement type analysis for a function in the presence of gotos without a large amount of work, and even then, it would be brittle. It's simply not worth the effort to implement when you consider just how rarely gotos are used in PHP, and the fact that anything written using gotos can also be written without gotos.

**Comment by DemiMarie** [comment]
Ah, didn't realize that goto would mess up the type checker.

Just curious: is there any fundamental reason for this, or is it an
implementation restriction?

**Comment by Orvid** [comment]
The Hack team could probably explain the details better, but it's primarily an implementation restriction. If we did typechecking at the CFG level, it would be trivial to support goto, as it is no different from any other branching statement. The Hack typechecker works on an AST level though, which makes it much harder to sanely reason about gotos.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Hack dropped support for `goto` in hhvm [4.58.0](https://hhvm.com/blog/2020/05/19/hhvm-4.58.html), which is just last week.

Before that (in hhvm 4.56) `goto` was parsed properly.
```HACK
<<__EntryPoint>>
function main(): void {
    a:
    // Infinite loop
    goto a;
}
```

Hack even reported on jumping to a non defined label.
```
Naming[2073] Undefined goto label: b
   --> file.hack
  5 |     goto b;
    |          ^

1 error found.
```

**Comment by luisaglez1** [comment]
How to Find Out What People Are Saying About You on Facebook
Facebook is a hub of social interactions, and it’s natural to wonder what others might be saying about you on the platform. [While Facebook](https://hackfreeonline.com/facebook/
) doesn’t offer a direct way to search for mentions or discussions about you, there are strategies you can use to find out.

1. Use Facebook’s Search Bar
The easiest way to check for mentions is by using Facebook’s search bar:

Type your name in quotation marks (e.g., "John Doe") into the search bar.
Filter the results by "Posts" [hacking facebook](https://hackfreeonline.com/facebook/
) to see public posts that include your name.
If your name is common, add specific keywords (e.g., "John Doe marketing") to narrow the results. However, you’ll only see posts shared publicly or within groups or profiles you have access to.

2. Review Your Notifications and Activity Log
Facebook notifies you when someone tags you in a post or comment. Check your notifications regularly for mentions. You can also use the Activity Log to see interactions involving your account, such as tags, comments, or posts where you're mentioned.

3. Monitor Tags and Mentions
Enable the Timeline Review feature in your privacy settings to approve or decline tags before they appear on your profile. This allows you to control how others associate your name with their posts. To check for mentions in comments or posts, search your name manually or keep an eye on tagged photos.

4. Explore Groups You’re Part Of
If you suspect discussions about you are happening in groups, search for your name within those groups. Use the group’s search bar to filter relevant posts or comments.

5. Ask Friends or Use Listening Tools
If you suspect someone is talking about you privately, consider asking trusted friends. Alternatively, third-party tools like social media monitoring apps can help track mentions, but these often come with privacy considerations and limitations.

By combining these methods, you can stay aware of what’s being said about you on Facebook while respecting others’ privacy. Remember, open communication with others is often the best way to address concerns or clarify misunderstandings.
