### ISSUE TITLE
Hack reports methods as definition of standard library functions

### ISSUE THREAD

**Issue by Aatch** [facebook/hhvm#5402]
This happened with `pack` and `unpack` methods, however attempts at creating a minimal test case have been unsuccessful so far. I have a class with a `pack` instance method and an `unpack` static method. The file itself is `// decl` but I can't seem to replicate the error at all in a test case.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

I can't reproduce this issue either. Hack seems to handle this properly. Also, `// decl` is no longer supported, since hhvm 4.x.0, but I can't find the blogpost for it.

```
Parsing[1002] Incorrect comment; possible values include strict, partial, or empty
   --> file.hh
  1 | <?hh // decl
    | ^^^^^^
```

**Comment by lexidor** [comment]
#5776 has a repro which errors about `\gettype()` and `Derp::getType()` only differing in capitalization. The cause for this was missing visibility modifiers.

This issue has also been fixed in newer versions. This was quite an interesting find.

```HACK
<?hh
class Derp {
    function a() {
        echo 'herp';
    }

    function getType() {
        return 'derp';
    }
}
```


Typechecker output:

```
test.hh:3:5,12: Expected modifier (Parsing[1002])
/tmp/hh_server/hhi_f8220b4/stdlib/builtins_variable.hhi:28:10,16: Name already bound: gettype (Naming[2012])
  test.hh:7:14,20: Previous definition getType differs only in capitalization
  test.hh:7:14,20: This appears to be defined in an hhi file included in your project root. The hhi files for the standard library are now a part of the typechecker and must be removed from your project. Typically, you can do this by deleting the "hhi" directory you copied into your project when first starting with Hack.
```
