### ISSUE TITLE
How to change HHVM user?

### ISSUE THREAD

**Issue by thibaultlavoisey** [facebook/hhvm#5404]
Hi,

Today, I changed the user running my Web server (Nginx) from www-data to www.
After that, all my PHP vhosts not working at all, due to HHVM user permission denied. When I stop/start HHVM service, the pid file is always created with www-data user as owner.
I tried to force the user in server.ini file, same errors.
If I manually change the user to www-data, HHVM is ok again.

How to properly change the user?

I use Nginx 1.9 and HHVM 3.7.

Thank's all :)

**Comment by fcorriga** [comment]
Modify the hhvm init script.
change the following lines:

**Comment by thibaultlavoisey** [comment]
Where I can find this script? Thank's!

**Comment by fcorriga** [comment]
/etc/init.d/hhvm

usually...

**Comment by fcorriga** [comment]
you can also change the user editing the /etc/default/hhvm
without changing the init script

**Comment by jwatzman** [comment]
Yeah, `/etc/default/hhvm` is the place to change. You'll also have to do some `chown`'ing to make sure it has read/write permission to the right places, in particular `/var/run/hhvm`.

Does that work for you?

**Comment by thibaultlavoisey** [comment]
I try this today and I come back to you! Thank's!

**Comment by thibaultlavoisey** [comment]
It works! Thank's :)
