### ISSUE TITLE
object conversion, err msg wrong, int instead of float

### ISSUE THREAD

**Issue by robstoll** [facebook/hhvm#5408]
````php
<?php
class A{}
var_dump((float) new A());
?>
````
The output should be: "Notice: Object of class A could not be converted to float in /in/jD88b on line 4
float(1)"

Current output: "Notice: Object of class A could not be converted to int in /in/jD88b on line -1
float(1)"

**Comment by jwatzman** [comment]
http://3v4l.org/Li1DX

**Comment by corientdev** [comment]
I am interested to solve this one atleast can anybody please guide me how could i? I mean i am touching the SC of HHVM for the first time

**Comment by WizKid** [comment]
The problem is here: https://github.com/facebook/hhvm/blob/9ee718b0e4df33c30d2607c5f98ff2b58c75d0d5/hphp/runtime/base/object-data-inl.h#L201-214 . toDouble fallbacks to toInt64 and it raises the notice
