### ISSUE TITLE
gettext problem on Debian 7

### ISSUE THREAD

**Issue by effeks** [facebook/hhvm#5409]
Hi,

Not sure this is even an issue in hhvm, but for the sake of helping others, we just spend hours trying to figure out why gettext didn't work in hhvm, on Debian 7.

Zend compat was enabled:
```
hhvm.enable_zend_compat = true
```

Turned out that the environment variable "LANGUAGE" was set in "/etc/default/locale" (not sure why even), and that prevented hhvm from finding the correct .mo-file:
```
$ cat test.php
<?php
setlocale(LC_MESSAGES, 'de_DE.UTF-8');
bindtextdomain("messages", '/var/lib/system/lang/');
bind_textdomain_codeset('messages', 'UTF-8');
textdomain("messages");

print_r(_('Latest activity'));
echo "\n";
$ echo $LANG
en_US.UTF-8
$ echo $LANGUAGE
en_US:en
$ hhvm test.php
Latest activity
$ export LANGUAGE=''
$ hhvm test.php
Letzte Aktivität
```

Hope it helps someone else out there.

**Comment by Profforgr** [comment]
/var/lib/system/lang/ does not seems to be standart folder at Debian 7 and does not appeared to be supported officially. How did you get that folder?

**Comment by effeks** [comment]
`/var/lib/system/lang/` is just an example of where the translation files, .mo, are kept. Or did I misunderstand what you mean?

**Comment by Profforgr** [comment]
> /var/lib/system/lang/ is just an example of where the translation files, .mo, are kept. Or did I misunderstand what you mean?

Ah, OK :) I were thinking there are some build-in translation of basic words in system :) Just misunderstand the path meaning.

I found that gettext works fine on hhvm. But sometimes (especially with modified OS distribution or cloud-init powered ones) some tweaking in system required. I assume "apt-get -y install locales-all" can fix your problem without needing for any "export".
