### ISSUE TITLE
simplexml_load_file and http stream segfaults

### ISSUE THREAD

**Issue by ibrezac** [facebook/hhvm#5416]
```php
<?php
simplexml_load_file('http://idonotrespond/');
```

Causes hhvm (3.7 and 3.6.1) to segfault.  It seems that any error in retrieving the stream causes the error (timeout, hostname lookup, etc)

**Comment by paulbiss** [comment]
Do you have a stacktrace?

**Comment by ibrezac** [comment]
Host: qa-hhvm37
ProcessID: 3342
ThreadID: 7f855fa217c0
ThreadPID: 3342
Name: /usr/bin/hhvm
Type: Segmentation fault
Runtime: hhvm
Version: tags/HHVM-3.7.0-0-gc8baf9cd3cb603e030969bfe24634d5e85549915
DebuggerCount: 0

Arguments: ./i.php
ThreadType: CLI

# 0  ?? at hhvm:0
# 1  HPHP::f_simplexml_load_file(HPHP::String const&, HPHP::String const&, long, HPHP::String const&, bool) at hhvm:0
# 2  ?? at hhvm:0
# 3  HPHP::jit::MCGenerator::enterTC(unsigned char*, HPHP::ActRec*) at hhvm:0
# 4  ?? at hhvm:0
# 5  HPHP::ExecutionContext::invokeFunc(HPHP::TypedValue*, HPHP::Func const*, HPHP::Variant const&, HPHP::ObjectData*, HPHP::Class*, HPHP::VarEnv*, HPHP::StringData*, HPHP::ExecutionContext::InvokeFlags) at hhvm:0
# 6  HPHP::ExecutionContext::invokeUnit(HPHP::TypedValue*, HPHP::Unit const*) at hhvm:0
# 7  HPHP::include_impl_invoke(HPHP::String const&, bool, char const*) at hhvm:0
# 8  HPHP::hphp_invoke(HPHP::ExecutionContext*, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, HPHP::Array const&, HPHP::VRefParamValue const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool&, std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, bool, bool, bool) at hhvm:0
# 9  HPHP::hphp_invoke_simple(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) at hhvm:0
# 10 ?? at hhvm:0
# 11 HPHP::execute_program(int, char**) at hhvm:0
# 12 main at hhvm:0
# 13 __libc_start_main at /lib/x86_64-linux-gnu/libc.so.6:0
# 14 ?? at hhvm:0

PHP Stacktrace:
