### ISSUE TITLE
Result is not correct

### ISSUE THREAD

**Issue by ihsanudin** [facebook/hhvm#5420]
I try to create a simple script like this
```php
<?php
$a = 0;

for ($i =1; $i <= 10000; $i++) {
        $a += $i;
}

echo $a;
```
and then run hhvm script.php

the result is not *10000* but *50005000*.

Like have 2 worker to calculate that job but not merging the result

**Comment by nikic** [comment]
Huh? Isn't result 50005000 = 10000 * (10000 + 1) / 2 exactly what you'd expect?

**Comment by ihsanudin** [comment]
sorry for i confuse :-(
