### ISSUE TITLE
missing init.d file when installing hhvm 3.7.1 in Docker container

### ISSUE THREAD

**Issue by kilahm** [facebook/hhvm#5423]
Last night I ran into this issue when attempting to build a docker container with hhvm.

The relevant Dockerfile instruction is included in the error message:

```
(messages about other packages)

invoke-rc.d: unknown initscript, /etc/init.d/hhvm not found.
dpkg: error processing archive /var/cache/apt/archives/hhvm_3.7.1~trusty_amd64.deb (--unpack):
 subprocess new pre-installation script returned error exit status 100

(messages about other packages)

Errors were encountered while processing:
 /var/cache/apt/archives/hhvm_3.7.1~trusty_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
INFO[0097] The command [
     /bin/sh -c DEBIAN_FRONTEND=noninteractive sudo apt-get install -y software-properties-common &&
     apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0x5a16e7281be7a449 && 
     add-apt-repository 'deb http://dl.hhvm.com/ubuntu trusty main' &&
     apt-get update &&
     apt-get install -y hhvm &&
     /usr/bin/update-alternatives --install /usr/bin/php php /usr/bin/hhvm 60 &&
     rm -rf /tmp/*] returned a non-zero code: 100
```

Could it be that the pre-install script is attempting to nicely shut down any currently running hhvm daemon by calling the init.d script, then exiting with a 100 since the script does not exist yet?

BTW, I was able to build by docker image by adding the `trusty-lts-3.6` repository instead of the plain `trusty`.

**Comment by jwatzman** [comment]
Yeah, https://github.com/hhvm/packaging/commit/86e6b8b1ca2a7c2baa4fef5c7d801370a83f43eb fixes this, but I missed it when building the trusty 3.7.1 package :( I'll do a 3.7.1-1 or something later, sorry about that.

**Comment by bartclarkson** [comment]
I've been lurking over this issue a couple days.  Something we can all do in the meantime is just "vi /etc/init.d/hhvm" and write the file.  The install will then run into your file and ask if you want to replace it.

```bash
Configuration file '/etc/init.d/hhvm'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** hhvm (Y/I/N/O/D/Z) [default=N] ? Y
Installing new version of config file /etc/init.d/hhvm ...
********************************************************************
* HHVM is installed.
```

**Comment by igorclark** [comment]
Nice tip @bartclarkson - as we're including this in our debian VM images, which are built with bootstrap scripts, I also added the following to create the file and make `apt-get` install it without barfing on confirmation for the config overwrite, by passing the right option to `dpkg` under the hood:

    touch /etc/init.d/hhvm
    chmod u+x /etc/init.d/hhvm
    apt-get install -y -o Dpkg::Options::="--force-confnew" hhvm

Hope that's useful for anybody digging around for the right parameters :-)

**Comment by jwatzman** [comment]
This should have been fixed -- what OS are you on, that you're still encountering this problem?

**Comment by TwoWholeWorms** [comment]
Hmm… I'm using the source at `deb http://dl.hhvm.com/debian wheezy main` and I don't have 3.7.1-1 yet, just 3.7.1, which, obviously, suffers from this error. :/ Any ideas? I've run `apt-get update`.

**Comment by jwatzman** [comment]
Most OSes didn't need the `-1`, I thought it was just trusty I messed up, but may have been wheezy too. Stand by.

**Comment by jwatzman** [comment]
OK, wheezy now has `3.7.1-1` which should fix the issue there too. LMK if it doesn't.

**Comment by jwatzman** [comment]
And sorry for the trouble.

**Comment by TwoWholeWorms** [comment]
Thanks, Josh, this has fixed it. :)

On Friday, 5 June 2015, Josh Watzman <notifications@github.com> wrote:

> And sorry for the trouble.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/hhvm/issues/5423#issuecomment-109073575>.
>


-- 
Regards,

Benjamin Nolan,
Vinari Ltd.

E-Mail: benjamin.nolan@vinari.co.uk
Business Landline: (020) 8660 6869
Mobile: (07932) 060-308
LinkedIn: http://uk.linkedin.com/in/benjaminnolan

Company number: 6055645
Registered office: 72 Waddington Avenue, Old Coulsdon, Surrey, CR5 1QN.
