### ISSUE TITLE
unable to compile hhvm-3.6.1 on Gentoo / hardened

### ISSUE THREAD

**Issue by lutel** [facebook/hhvm#5424]
Linking CXX static library libfolly.a
[ 19%] Built target folly
[ 19%] Building CXX object third-party/thrift/CMakeFiles/hphp_thrift.dir/thrift/lib/cpp/async/TBinaryAsyncChannel.cpp.o
[ 19%] Building CXX object third-party/thrift/CMakeFiles/hphp_thrift.dir/thrift/lib/cpp/async/TAsyncSocketFactory.cpp.o
[ 19%] Building CXX object third-party/thrift/CMakeFiles/hphp_thrift.dir/thrift/lib/cpp/async/TAsyncSignalHandler.cpp.o
[ 19%] Building CXX object third-party/thrift/CMakeFiles/hphp_thrift.dir/thrift/lib/cpp/async/TAsyncSSLSocketFactory.cpp.o
[ 19%] Building CXX object third-party/thrift/CMakeFiles/hphp_thrift.dir/thrift/lib/cpp/VirtualProfiling.cpp.o
[ 19%] Building CXX object third-party/thrift/CMakeFiles/hphp_thrift.dir/thrift/lib/cpp/Thrift.cpp.o
[ 20%] Building CXX object third-party/thrift/CMakeFiles/hphp_thrift.dir/thrift/lib/cpp/EventHandlerBase.cpp.o
[ 20%] Building CXX object third-party/thrift/CMakeFiles/hphp_thrift.dir/thrift/contrib/thrift_dump.cpp.o
Linking CXX static library libhphp_thrift.a
[ 20%] Built target hphp_thrift
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2
 * ERROR: dev-php/hhvm-3.6.1::hhvm failed (compile phase):
 *   emake failed
 *
 * If you need support, post the output of `emerge --info '=dev-php/hhvm-3.6.1::hhvm'`,
 * the complete build log and the output of `emerge -pqv '=dev-php/hhvm-3.6.1::hhvm'`.
 * The complete build log is located at '/tmp/portage/dev-php/hhvm-3.6.1/temp/build.log'.
 * The ebuild environment file is located at '/tmp/portage/dev-php/hhvm-3.6.1/temp/environment'.
 * Working directory: '/tmp/portage/dev-php/hhvm-3.6.1/work/hhvm-3.6.1'
 * S: '/tmp/portage/dev-php/hhvm-3.6.1/work/hhvm-3.6.1'

>>> Failed to emerge dev-php/hhvm-3.6.1, Log file:

>>>  '/tmp/portage/dev-php/hhvm-3.6.1/temp/build.log'

 * Messages for package dev-php/hhvm-3.6.1:

 * ERROR: dev-php/hhvm-3.6.1::hhvm failed (compile phase):
 *   emake failed
 *
 * If you need support, post the output of `emerge --info '=dev-php/hhvm-3.6.1::hhvm'`,
 * the complete build log and the output of `emerge -pqv '=dev-php/hhvm-3.6.1::hhvm'`.
 * The complete build log is located at '/tmp/portage/dev-php/hhvm-3.6.1/temp/build.log'.
 * The ebuild environment file is located at '/tmp/portage/dev-php/hhvm-3.6.1/temp/environment'.
 * Working directory: '/tmp/portage/dev-php/hhvm-3.6.1/work/hhvm-3.6.1'
 * S: '/tmp/portage/dev-php/hhvm-3.6.1/work/hhvm-3.6.1'

**Comment by fredemmott** [comment]
We do not provide packaging for gentoo - you need to follow up with wherever you got the ebuild from.
