### ISSUE TITLE
hhvm + nginx + wordpress - upload problem

### ISSUE THREAD

**Issue by speedwheel** [facebook/hhvm#5427]
I installed nginx 1.7.12 + hhvm 3.7.0 + wordpress 4.2.2 on digital ocean droplet.

I am trying to upload a theme that is  17 mb. While uploading, after exactly 30 seconds the upload restarts itself 3-4 times and than I get an error page.

All the settings are default, I even tryed to put this in php.ini (hhvm):

max_execution_time = 300
max_input_time = 60
memory_limit = 128M
post_max_size = 50M
upload_max_filesize = 50M

But nothing changed.

**Comment by speedwheel** [comment]
I fixed it by putting this in nginx.conf

client_max_body_size 200M;

**Comment by jwatzman** [comment]
Glad you got it fixed :)
