### ISSUE TITLE
Open source AsyncPoll

### ISSUE THREAD

**Issue by apuckey** [facebook/hhvm#5428]
I've been playing around with awaitables with kestrel queues and currently have a working solution here: https://gist.github.com/apuckey/b3d688d73e28a0b1dc29 

Whilst this works, due to the nature of kestrel if the first 2 queues return instantly then the entire process will still wait until all have finished so that the loop can start again. I can reduce the timeout but this increases network activity.

What would be awesome is i could set the timeout to say 10 seconds and if say queue_one gets lots of messages it happily processes one then restarts itself as they come in whilst the other queues are still waiting.

Maybe this exists already and I have missed it. ( hopefully :) )

**Comment by apuckey** [comment]
Maybe even the ability to add new awaitables to the queue on the fly would be even better

**Comment by jwatzman** [comment]
I don't know anything about kestrel, so it's easily possible I misunderstand the problem, or am missing some subtlety, so please feel free to elaborate and correct me.

In general, the idea of awaitables is that they run to completion -- we don't want partially-completed bits of code lying around, which could lead to all sorts of surprising things. (This is also why if you `await \HH\Asio\v($stuff)` and one of element of `$stuff` fails, all the others will still run to completion before the exception is re-thrown.) You want to make your dependency structure very explicit -- if you don't really need something, then don't await on it. This gives the scheduler maximum flexibility in scheduling async functions in the way that's the fastest, and also avoids the issue you're running into, where extra stuff you don't care about blocks you.

The upcoming [Hack book](http://shop.oreilly.com/product/0636920037194.do) has a chapter on async which IIRC goes into this in some detail with some good examples.

**Comment by apuckey** [comment]
Kestrel uses the memcache protocol but is a queue system.

So you do: "GET queue/open/t=10000" and the socket will remain open for 10 seconds if the queue is empty and if a message gets published it will send to one of the consumers.

So what i wanted was having say 10 sockets in async waiting for messages and if a queue gets busy it can restart/resubmit itself after finishing so it doesnt need to wait the entire 10 seconds for the rest of them to finish.

I can soty of get around it by reducing the timeout to something like 500ms but then i get a lot more load on kestrel servers ( and im stil waiting 500ms for fast running queues )

What im trying to achieve is running this in 1 hhvm instance so i can spawn more of them as opposed to running 1 hhvm per queue which means on non-busy queues its basically wasted resources.

Hope this makes a little more sense as to what im trying to do :)

**Comment by jwatzman** [comment]
I think I see. The right abstraction might actually be some sort of `stream_multi_await` or `stream_select_await` or something like that, so the `await` will finish as soon as *one* of the sockets is ready, instead of using the approach with `\HH\Asio\v` and `stream_await` which waits until *all* are ready -- that would also solve your problem, correct? You can maybe hack something right now with a loop around `stream_select` with a low/zero timeout, and `SleepWaitHandle`, though that isn't very pretty. Adding an awaitable version of `stream_select` might not be that hard?

**Comment by jwatzman** [comment]
Also this is only a problem if you want to combine results from different queues into your own queue in Hack; if a given piece of code only cares about one queue, it can just `await` on the socket for the one queue it cares about, and the advice I gave above about dependency structure still applies. I'd probably try to do this, actually, and nix the entire idea of your `run` function if I could, and just use `KestrelSocket` directly.

**Comment by jwatzman** [comment]
@jano I also hear you're working on some async polling stuff, that might be applicable here? I don't know anything about it, has it hit trunk yet / is it open source?

**Comment by jano** [comment]
We have a low level concept that allows you to synchronize against asynchronous operation -- ConditionWaitHandle. Our internal codebase has abstraction built on top of that called AsyncPoll (implemented fully in PHP) that allows you to poll for events. It is not yet fully mature, but maybe we can open source it as part of the asio utils package and once the API stabilizes, move it to the HHVM repo. It is used as:

$poll = AsyncPoll::from($awaitables);
foreach ($poll await as $result) {
  // process $result of one of the $awaitables above
  // optionally $poll->add($another_awaitable);
}

**Comment by apuckey** [comment]
@jano Yes this is exactly what we need ( and I do use ConditionWaitHandle already in this test ) 

I dont really care that 9/10 queues dont return anything but I do want them to keep waiting for the timeout, The 1/10 queue thats getting messages I want it to get the message, process it and then wait on the queue again.

 AsyncPoll sounds exactly what is needed here

**Comment by jwatzman** [comment]
Awesome, retitled this as just open-sourcing that, some point in the future when it's ready, hopefully not too long. cc @fredemmott

**Comment by jano** [comment]
@apuckey: see https://github.com/hhvm/asio-utilities/pull/11

**Comment by apuckey** [comment]
@jano very excited thanks :)

**Comment by fredemmott** [comment]
(closing as duplicate, meant to do at the time)
