### ISSUE TITLE
feedback spec file

### ISSUE THREAD

**Issue by sbagmeijer** [facebook/hhvm#5441]
Hello,

I maintain a repository for red hat based linux and I provide rpms that are up to date with the newest version of hhvm. (repository can be found here: https://community.ulyaoth.net/threads/ulyaoth-repositories.3/ )

I notice that the hhvm rpm it is getting more and more used by people so I was wondering if someone perhaps could have a look at spec file I created and perhaps you see some improvements I could make or packages that are not really required for building hhvm. (the rpms work fine I am only curious if there are improvements to make)

Build script I use:
https://github.com/sbagmeijer/ulyaoth/blob/master/Repository/ulyaoth-hhvm/build-ulyaoth-hhvm.sh

Spec file:
https://github.com/sbagmeijer/ulyaoth/blob/master/Repository/ulyaoth-hhvm/SPECS/ulyaoth-hhvm.spec

Something I was wondering also is if you need to add some special flag to build it for production, right now when I install the rpm it does show a header like this on request: "X-Powered-By    HHVM/3.7.2-dev"

Does the "-dev" mean it is build for development? or does this always show?

Anyway any feedback is welcome to improve the rpms!, thank you in advanced.

**Comment by jrobeson** [comment]
We're been building a spec file here (alongside some packaged extensions) https://github.com/no1youknowz/hhvm-repo

**Comment by jwatzman** [comment]
Yeah, no one on the team knows very much about yum packaging, and we don't officially support any yum-based distro right now. @jrobeson is a community member who's been doing a lot of work on yum packaging, he's the best one to talk to :)
