### ISSUE TITLE
how to stop hphp_request* file generation? in /tmp?

### ISSUE THREAD

**Issue by lokeshhctm** [facebook/hhvm#5442]
We see a lot of files being created under /tmp with prefix hphp_request_<RANDOM>. How can we stop these?

**Comment by paulbiss** [comment]
Looks like you may have set hhvm.record_input?

https://github.com/facebook/hhvm/blob/5a46b50d809590b8feeeb05ede056106bcfb12a6/hphp/runtime/server/http-protocol.cpp#L789-L790

**Comment by lokeshhctm** [comment]
Thanks for giving this, it is helpful
