### ISSUE TITLE
error files not being generated.

### ISSUE THREAD

**Issue by lokeshhctm** [facebook/hhvm#5443]
There are not error files being create in HHVM.
We have this settings in hdf file:

# error log settings
    UseLogFile = true
    UseCronolog = true
    File = /mnt/log/hiphop/error_%Y%m%d.log

**Comment by UnsecPhu** [comment]
Does HHVM have permissions to right on that folder?

**Comment by lokeshhctm** [comment]
Thanks for giving an hint. It is working now for me.
