### ISSUE TITLE
Compiling Errors (hphp) -- HHVM Fails to Compile on gcc 4.9

### ISSUE THREAD

**Issue by UnsecPhu** [facebook/hhvm#5444]
> [  0%] Built target timelib
> [  0%] Built target double-conversion
> [  7%] Built target folly
> [ 12%] Built target hphp_proxygen
> [ 16%] Built target hphp_thrift
> [ 16%] Built target afdt
> [ 16%] Built target eaw_table
> [ 22%] Built target mbfl
> [ 26%] Built target re2
> [ 27%] Built target webscalesqlclient
> [ 28%] Built target squangle
> [ 36%] Built target mcrouter
> [ 36%] Built target fastlz
> [ 36%] Built target sqlite3
> [ 36%] Built target lz4
> [ 38%] Built target pcre
> [ 38%] Built target pcre_jit_test
> [ 38%] Built target pcrecpp
> [ 38%] Built target pcre_scanner_unittest
> [ 38%] Built target pcre_stringpiece_unittest
> [ 38%] Built target pcrecpp_unittest
> [ 38%] Built target pcreposix
> [ 38%] Built target pcregrep
> [ 38%] Built target pcretest
> [ 38%] Built target gen-class-map
> [ 38%] Built target gen-ext-hhvm
> [ 38%] Built target gen-infotabs
> [ 41%] Built target hphp_util
> [ 41%] Built target hfsort
> [ 41%] Built target jit_sort
> [ 41%] Built target version
> [ 41%] Built target hphp_system
> [ 41%] Built target hphp_parser
> [ 48%] Built target hphp_analysis
> [ 48%] Built target hack
> [ 50%] Built target hphp_hhbbc
> [ 50%] Built target neo
> [ 50%] Built target ALL_SCAN_HEADER
> Scanning dependencies of target hphp_runtime_static
> [ 50%] Building CXX object hphp/runtime/CMakeFiles/hphp_runtime_static.dir/base/heap-collect.cpp.o
> Linking CXX static library libhphp_runtime.a
> [ 76%] Built target hphp_runtime_static
> [ 77%] Building CXX object hphp/runtime/ext/CMakeFiles/hphp_runtime_ext.dir/zip/ext_zip.cpp.o
> /usr/local/hhvm/hphp/runtime/ext/zip/ext_zip.cpp: In member function ‘bool HPHP::ZipDirectory::close()’:
> /usr/local/hhvm/hphp/runtime/ext/zip/ext_zip.cpp:234:26: error: ‘zip_discard’ was not declared in this scope
>         zip_discard(m_zip);
                          ^
> make[2]: *** [hphp/runtime/ext/CMakeFiles/hphp_runtime_ext.dir/zip/ext_zip.cpp.o] Error 1
> make[1]: *** [hphp/runtime/ext/CMakeFiles/hphp_runtime_ext.dir/all] Error 2
> make: *** [all] Error 2

It fails to compile on that part.
Im using the tutorial on howto compile it on CentOS 6.6

CentOS 6.6 64bit
GCC 4.9

**Comment by jwatzman** [comment]
>  Im using the tutorial on howto compile it on CentOS 6.6

We don't officially support CentOS -- I assume https://github.com/facebook/hhvm/wiki/Building-and-installing-HHVM-on-CentOS-6.6 is the tutorial you're using?

That said, some thoughts. `zip_discard` is supposed to be defined in `hhvm/third-party/libzip/zip.h` -- can you confirm that file exists, and contains a definition of `zip_discard`? Can you see if there's another `zip.h` on your system, in `/usr/include` or something, that might be getting picked up instead, and which doesn't contain `zip_discard`? Can you link to a pastebin with the full output of `VERBOSE=1 make`?

**Comment by UnsecPhu** [comment]
Make Output (VERBOSE=1)
http://pastebin.com/AbMJ0pmn

hhvm/third-party/libzip/zip.h
> ls | grep zip.h
> Output:
> zip.h

/usr/include/zip.h
> ls | grep zip.h
> Output:
> zip.h
> 
> cat zip.h | grep zip_discard
> Output:
> None
And yes im using that tutorial as that is the most reliable one i found.

So zip.h was the problem and i replaced the on in /usr/include with the one included in hhvm and it was complaining about a missing zipconf.h include. I downloaded zipconf.h from libzip github repo.
i thought that i was using the bundled libzip since its already included.

Errors about libzip is already fixed but new errors came up (http://pastebin.com/J3bMXCd4)
And it seems imagemagick is the one with the errors. here is the content of ext_imagick.h which the constant.cpp uses (http://pastebin.com/wrZRj9xr) And it doesnt have the functions that constants.cpp needs.

**Comment by jwatzman** [comment]
It sounds like something is quite broken, and potentially include directives are missing somewhere? You should not need to replace system libraries with versions from the HHVM repo.

**Comment by jwatzman** [comment]
```
[ 77%] Building CXX object hphp/runtime/ext/CMakeFiles/hphp_runtime_ext.dir/zip/ext_zip.cpp.o
cd /usr/local/hhvm/hphp/runtime/ext && /usr/bin/c++   -DENABLE_FASTCGI=1 -DENABLE_ZEND_COMPAT=1 -DFOLLY_HAVE_CLOCK_GETTIME=1 -DFOLLY_HAVE_FEATURES_H=1 -DFOLLY_HAVE_PTHREAD_ATFORK=1 -DFOLLY_HAVE_PTHREAD_SPINLOCK_T=1 -DFOLLY_HAVE_WEAK_SYMBOLS=1 -DFOLLY_NO_CONFIG=1 -DHAVE_BOOST1_49 -DHAVE_ELF_GETSHDRSTRNDX -DHAVE_FEATURES_H=1 -DHAVE_GD_JPG -DHAVE_GD_PNG -DHAVE_LIBDL -DHAVE_LIBVPX -DHHVM -DHHVM_DYNAMIC_EXTENSION_DIR=\"/usr/local/lib64/hhvm/extensions\" -DHPHP_OSS=1 -DLIBDWARF_CONST_NAME -DLIBDWARF_USE_INIT_C -DNDEBUG -DNO_LIB_GFLAGS -DNO_TCMALLOC=1 -DPACKAGE=hhvm -DPACKAGE_VERSION=Release -DPHP_MYSQL_UNIX_SOCK_ADDR=\"/var/lib/mysql/mysql.sock\" -DPNG_SKIP_SETJMP_CHECK -DRELEASE=1 -DTHRIFT_MUTEX_EMULATE_PTHREAD_TIMEDLOCK -DUSE_CMAKE -DUSE_JEMALLOC=1 -D_GNU_SOURCE -D_PTHREADS=1 -D_REENTRANT=1 -D__STDC_FORMAT_MACROS -Wall -std=gnu++11 -ffunction-sections -fno-gcse -fno-omit-frame-pointer -Woverloaded-virtual -Wno-deprecated -Wno-strict-aliasing -Wno-write-strings -Wno-invalid-offsetof -fno-operator-names -Wno-error=array-bounds -Wno-error=switch -Werror=format-security -Wno-unused-result -Wno-sign-compare -Wno-attributes -Wno-maybe-uninitialized -Wno-unused-local-typedefs -fno-canonical-system-headers -Wno-deprecated-declarations -Wno-unused-function  -ftrack-macro-expansion=0 -fno-builtin-memcmp -fno-delete-null-pointer-checks -mcrc32 -O3 -DNDEBUG -fno-gcse -momit-leaf-frame-pointer --param max-inline-insns-auto=100 --param early-inlining-insns=200 --param max-early-inliner-iterations=50 -I/usr/local/boost/include -I/include -I/usr/local/hhvm/third-party/re2/src -I/usr/local/hhvm/third-party/squangle/src -I/usr/local/hhvm/third-party/webscalesqlclient/src/include -I/usr/include/libxml2 -I/usr/include/security -I/usr/local/hhvm/hphp -I/usr/local/hhvm/third-party/libsqlite3 -I/usr/local/hhvm/third-party/double-conversion/src -I/usr/local/hhvm/third-party/lz4 -I/usr/local/hhvm/third-party/pcre -I/usr/local/hhvm/third-party/fastlz -I/usr/local/hhvm/third-party/timelib -I/usr/local/hhvm/third-party/libafdt/src -I/usr/local/hhvm/third-party/libmbfl -I/usr/local/hhvm/third-party/libmbfl/mbfl -I/usr/local/hhvm/third-party/libmbfl/filter -I/usr/local/hhvm/third-party/mcrouter -I/usr/local/hhvm/third-party/folly -I/usr/local/hhvm/third-party/thrift -I/usr/local/hhvm/third-party -I/usr/local/hhvm -I/usr/include/ImageMagick -I/usr/include/imap -I/usr/include/vpx -I/usr/include/freetype2    -DHAVE_LIBFREETYPE -DHAVE_GD_FREETYPE -DENABLE_GD_TTF -o CMakeFiles/hphp_runtime_ext.dir/zip/ext_zip.cpp.o -c /usr/local/hhvm/hphp/runtime/ext/zip/ext_zip.cpp
/usr/local/hhvm/hphp/runtime/ext/zip/ext_zip.cpp: In member function ‘bool HPHP::ZipDirectory::close()’:
/usr/local/hhvm/hphp/runtime/ext/zip/ext_zip.cpp:234:26: error: ‘zip_discard’ was not declared in this scope
         zip_discard(m_zip);
                          ^
```

This notably does not include any `-I` directive that points to the third-party libzip.

**Comment by UnsecPhu** [comment]
I only replaced the header but i jsut renamed the old one and i moved it back.

Only problems i have now is on Imagick
