### ISSUE TITLE
Can't call array_sum on a Vector of floats

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#5454]
http://3v4l.org/6ZsAu

``` Hack
<?hh

var_dump(array_sum(Vector{1,2,3,4})); // int(10)
var_dump(array_sum([1.0, 2.0, 3.0, 4.0])); // float(10)
var_dump(array_sum(Vector{1.0 ,2.0, 3.0, 4.0}));  // Fatal error: taking reference on iterator object
```

**Comment by Newman101** [comment]
The error is defined here: 

hhvm/hphp/runtime/base/array-iterator.cpp

  if (!hasArrayData()) {
    throw FatalErrorException("taking reference on iterator objects");
  }

After going through some of the HHVM documentation, I tried this: 

<?hh

function main(): void {
$x = array(1.0, 2.0, 3.0, 4.0);
$y = new Vector($x);
var_dump(array_sum($y));
}

main();

And got the same error. Seems to be with the Vector when there is a float involved.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This issue has been fixed.

Output in hhvm 4.56:
```
int(10)
float(10)
float(10)
```
