### ISSUE TITLE
HHVM (master) not building on Centos 7

### ISSUE THREAD

**Issue by C1n** [facebook/hhvm#5456]
I'm building HHVM (master branch) on Centos 7 and I'm getting an error at the end:

[ 74%] Building CXX object hphp/runtime/CMakeFiles/hphp_runtime_static.dir/base/heap-collect.cpp.o
Linking CXX static library libhphp_runtime.a
[100%] Built target hphp_runtime_static
Linking CXX executable hhvm
/usr/bin/ld.gold: error: cannot find -lre2
../runtime/ext/libhphp_runtime_ext.a(gd_jpeg.cpp.o):gd_jpeg.cpp:function fatal_jpeg_error(jpeg_common_struct*): error: undefined reference to 'jpeg_destroy(jpeg_common_struct*)'
../runtime/ext/libhphp_runtime_ext.a(gd_jpeg.cpp.o):gd_jpeg.cpp:function gdImageJpegCtx: error: undefined reference to 'jpeg_std_error(jpeg_error_mgr*)'
../runtime/ext/libhphp_runtime_ext.a(gd_jpeg.cpp.o):gd_jpeg.cpp:function gdImageJpegCtx: error: undefined reference to 'jpeg_CreateCompress(jpeg_compress_struct*, int, unsigned long)'
../runtime/ext/libhphp_runtime_ext.a(gd_jpeg.cpp.o):gd_jpeg.cpp:function gdImageJpegCtx: error: undefined reference to 'jpeg_set_defaults(jpeg_compress_struct*)'
../runtime/ext/libhphp_runtime_ext.a(gd_jpeg.cpp.o):gd_jpeg.cpp:function gdImageJpegCtx: error: undefined reference to 'jpeg_set_quality(jpeg_compress_struct*, int, int)'
../runtime/ext/libhphp_runtime_ext.a(gd_jpeg.cpp.o):gd_jpeg.cpp:function gdImageJpegCtx: error: undefined reference to 'jpeg_start_compress(jpeg_compress_struct*, int)'
../runtime/ext/libhphp_runtime_ext.a(gd_jpeg.cpp.o):gd_jpeg.cpp:function gdImageJpegCtx: error: undefined reference to 'jpeg_write_marker(jpeg_compress_struct*, int, unsigned char const*, unsigned int)'
../runtime/ext/libhphp_runtime_ext.a(gd_jpeg.cpp.o):gd_jpeg.cpp:function gdImageJpegCtx: error: undefined reference to 'jpeg_write_scanlines(jpeg_compress_struct*, unsigned char**, unsigned int)'
../runtime/ext/libhphp_runtime_ext.a(gd_jpeg.cpp.o):gd_jpeg.cpp:function gdImageJpegCtx: error: undefined reference to 'jpeg_finish_compress(jpeg_compress_struct*)'
../runtime/ext/libhphp_runtime_ext.a(gd_jpeg.cpp.o):gd_jpeg.cpp:function gdImageJpegCtx: error: undefined reference to 'jpeg_destroy_compress(jpeg_compress_struct*)'
../runtime/ext/libhphp_runtime_ext.a(gd_jpeg.cpp.o):gd_jpeg.cpp:function gdImageJpegCtx: error: undefined reference to 'jpeg_write_scanlines(jpeg_compress_struct*, unsigned char**, unsigned int)'
../runtime/ext/libhphp_runtime_ext.a(gd_jpeg.cpp.o):gd_jpeg.cpp:function gdImageJpegCtx: error: undefined reference to 'jpeg_simple_progression(jpeg_compress_struct*)'
../runtime/ext/libhphp_runtime_ext.a(gd_jpeg.cpp.o):gd_jpeg.cpp:function gdImageCreateFromJpegCtxEx: error: undefined reference to 'jpeg_std_error(jpeg_error_mgr*)'
../runtime/ext/libhphp_runtime_ext.a(gd_jpeg.cpp.o):gd_jpeg.cpp:function gdImageCreateFromJpegCtxEx: error: undefined reference to 'jpeg_CreateDecompress(jpeg_decompress_struct*, int, unsigned long)'
../runtime/ext/libhphp_runtime_ext.a(gd_jpeg.cpp.o):gd_jpeg.cpp:function gdImageCreateFromJpegCtxEx: error: undefined reference to 'jpeg_resync_to_restart(jpeg_decompress_struct*, int)'
../runtime/ext/libhphp_runtime_ext.a(gd_jpeg.cpp.o):gd_jpeg.cpp:function gdImageCreateFromJpegCtxEx: error: undefined reference to 'jpeg_save_markers(jpeg_decompress_struct*, int, unsigned int)'
../runtime/ext/libhphp_runtime_ext.a(gd_jpeg.cpp.o):gd_jpeg.cpp:function gdImageCreateFromJpegCtxEx: error: undefined reference to 'jpeg_read_header(jpeg_decompress_struct*, int)'
../runtime/ext/libhphp_runtime_ext.a(gd_jpeg.cpp.o):gd_jpeg.cpp:function gdImageCreateFromJpegCtxEx: error: undefined reference to 'jpeg_start_decompress(jpeg_decompress_struct*)'
../runtime/ext/libhphp_runtime_ext.a(gd_jpeg.cpp.o):gd_jpeg.cpp:function gdImageCreateFromJpegCtxEx: error: undefined reference to 'jpeg_destroy_decompress(jpeg_decompress_struct*)'
../runtime/ext/libhphp_runtime_ext.a(gd_jpeg.cpp.o):gd_jpeg.cpp:function gdImageCreateFromJpegCtxEx: error: undefined reference to 'jpeg_read_scanlines(jpeg_decompress_struct*, unsigned char**, unsigned int)'
../runtime/ext/libhphp_runtime_ext.a(gd_jpeg.cpp.o):gd_jpeg.cpp:function gdImageCreateFromJpegCtxEx: error: undefined reference to 'jpeg_finish_decompress(jpeg_decompress_struct*)'
../runtime/ext/libhphp_runtime_ext.a(gd_jpeg.cpp.o):gd_jpeg.cpp:function gdImageCreateFromJpegCtxEx: error: undefined reference to 'jpeg_destroy_decompress(jpeg_decompress_struct*)'
../runtime/ext/libhphp_runtime_ext.a(gd_jpeg.cpp.o):gd_jpeg.cpp:function gdImageCreateFromJpegCtxEx: error: undefined reference to 'jpeg_read_scanlines(jpeg_decompress_struct*, unsigned char**, unsigned int)'
../runtime/ext/libhphp_runtime_ext.a(gd_jpeg.cpp.o):gd_jpeg.cpp:function jpeg_gdIOCtx_src(jpeg_decompress_struct*, gdIOCtx*): error: undefined reference to 'jpeg_resync_to_restart(jpeg_decompress_struct*, int)'
../../third-party/squangle/libsquangle.a(Row.cpp.o):Row.cpp:function facebook::common::mysql_client::parseTimeOnly(folly::Range<char const*>, enum_field_types): error: undefined reference to 're2::RE2::Arg::parse_string(char const*, int, void*)'
../../third-party/squangle/libsquangle.a(Row.cpp.o):Row.cpp:function facebook::common::mysql_client::parseTimeOnly(folly::Range<char const*>, enum_field_types): error: undefined reference to 're2::RE2::Arg::parse_int(char const*, int, void*)'
../../third-party/squangle/libsquangle.a(Row.cpp.o):Row.cpp:function facebook::common::mysql_client::parseTimeOnly(folly::Range<char const*>, enum_field_types): error: undefined reference to 're2::RE2::Arg::parse_int(char const*, int, void*)'

I found a similar issue (#5007 and #5036), but the solution does not work.

**Comment by jwatzman** [comment]
Hm, this does look like a similar error to the linked task, an old version or mismatch between headers/libraries or something like that.

We don't officially support CentOS, none of us on the team really have the expertise in that distro. Also the packages in it tend to be older (due to its stability guarantees), but HHVM tends to need much newer versions of everything, which makes building a huge pain.

One suggestion, is that some libraries seem to be missing. Not sure about the jpeg stuff, but

>  /usr/bin/ld.gold: error: cannot find -lre2
> ...
>  ../../third-party/squangle/libsquangle.a(Row.cpp.o):Row.cpp:function facebook::common::mysql_client::parseTimeOnly(folly::Range, enum_field_types): error: undefined reference to 're2::RE2::Arg::parse_int(char const, int, void)'

These errors seem to be related. And since that is happening, it wouldn't surprise me if some similar problem were with the jpeg stuff too.

**Comment by apeabody** [comment]
This is a rather old thread, but a quick note that I currently/frequently/successfully build HHVM master on CentOS 7.  I try to keep this particular page updated: https://github.com/facebook/hhvm/wiki/Building-and-installing-hhvm-on-CentOS-7.x

I'd say based on the error above you are missing package *re2-devel* which can be found in EPEL - I'd suggest following the page referenced above to install that and any other dependencies.
