### ISSUE TITLE
isset(null) is true

### ISSUE THREAD

**Issue by robocoder** [facebook/hhvm#5457]
I think this is a side effect of mis-refcounting.
* HHVM 3.8.0-dev b5fe4eec09c160f4a291faf55629b4b9bbffe661
* Ubuntu 12.04, libboost 1.55, ocaml 4.02.1

```php
<?php
function assertNullNess($array) {
    if (isset($array[0])) {
        die("WTF?!\n");
    }
}

$array[] = null;

foreach ($array as &$item)
    ;

assertNullNess($array);
echo "WORKSFORME\n";
```

**Comment by fredemmott** [comment]
```
fred@hhvm-oss-bench:~/hhvm$ hhvm -v Eval.Jit=0 test.php
WORKSFORME
fred@hhvm-oss-bench:~/hhvm$ hhvm -v Eval.Jit=1 test.php
WTF?!
```

:/

**Comment by fredemmott** [comment]
Here's another example avoiding the foreach-by-ref:

```Hack
<?php

function foo($arr) {
  if (isset($arr[0])) {
    die("herp\n");
  }
}

$x = null;

$y = [];
$y[] = &$x;

foo($y);

echo "derp\n";
```

**Comment by fredemmott** [comment]
A bit more fun:

```
<?php

function foo($arr) {
  var_dump(isset($arr[0]));
}

$v1 = null;
$v2 = null;

$byref1 = [&$v1];
$byref2 = [];
$byref2[] = &$v2;

//foo($byref1); // Uncomment this and both dump `false`
foo($byref2);
```

**Comment by fredemmott** [comment]
```
foo($byref2); // true
foo($byref1); // false
foo($byref2); // true

var_dump($byref1 === $byref2); // true
```

**Comment by fredemmott** [comment]
Looks like `emitPackedArrayIsset` handles null by checking the type, but that won't handle a reference to null.

**Comment by nazar-pc** [comment]
@fredemmott, leafo/scssphp just dropped HHVM support because of this.
What is priority for this task? It may silently cause unexpected issues anywhere.

**Comment by fredemmott** [comment]
Not currently scheduled. We don't tend usually set priorities for individual tasks like this - instead it may be addressed next time we schedule a block of time for php5 or framework compatibility issues.

**Comment by Orvid** [comment]
This appears to have been fixed.
