### ISSUE TITLE
Dynamic Shape not throwing at runtime

### ISSUE THREAD

**Issue by bodinsamuel** [facebook/hhvm#5458]
Hi,

I'v been struggling to understand how to use correctly shape with dynamic data.
This structure is very intersting for storing data but I found the lack of error throwing a little bit surprising.
Maybe I'm wrong and there is an options or something to do this.

From documentation, all examples are simple and works perfectly
```php
type Point2D = shape('x' => int, 'y' => int);

# hh_client = Success
$myShape = shape('x' => 3, 'y' => 3);

#hh_client = Error
$myShape = shape('x' => true, 'y' => 3);

#hh_client = Success
$myDynamicVar = GetADataFromSomewhere();
$myShape = shape('x' => $myDynamicVar, 'y' => 3);
```

The third point is where I can't understand, hh_client report a succes which is normal as it cannot be checked statically. But there is no error at runtime.

Executing the script will predictively return an error on the second scenario but not the third. The shape will be created with a wrong structure.
If I need to check all my data structure manually I can only assume my script will be safe up to a certain point but I find doing this not so good as the point of Shape is to structure data without the hassle of doing this with array and checking everything by hand.

The documentation tell me "However, HHVM will run this code correctly, most likely with unexpected results." I struggle to understand why?
Is there a solution, or am I missing something?

PS: running hhvm 3.8.0 nightly from today on Debian 8

**Comment by paulbiss** [comment]
We don't type-check shapes at runtime, so that's why the runtime isn't complaining. If `GetADataFromSomewhere` is typed then Hack should be able to check it, if it's truly too dynamic to type-check then it's not valid Hack.

If this code isn't in a function then Hack isn't actually checking it since it doesn't operate on pseudomains.

```php
type Point2D = shape('x' => int, 'y' => int);
function GetADataFromSomewhere(): int { /* ... */ }

function foo(): void {
  $myShape = shape('x' => 3, 'y' => 3);
  $myShape = shape('x' => true, 'y' => 3);
  $myDynamicVar = GetADataFromSomewhere();
  $myShape = shape('x' => $myDynamicVar, 'y' => 3);
}
```

**Comment by jwatzman** [comment]
Also keep in mind that shape structure isn't checked until it actually passes a type annotation, in particular in @paulbiss's example nothing actually is checked against `Point2D`.

**Comment by Orvid** [comment]
We're a small team, and it doesn't look as though anyone in the community is actively working on this issue, so we've decided to close it. If you plan to send us a pull request resolving the issue let us know in the comments and we will re-open it and assign it to you. If you feel this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
