### ISSUE TITLE
xdebug: Could not start xdebug profiler. Another profiler is likely already attached to this thread.

### ISSUE THREAD

**Issue by Yogu** [facebook/hhvm#5459]
With the following configuration in php.ini:

    xdebug.enable=1
    xdebug.max_nesting_level = 65536

hhvm fails to start even for empty files (`hhvm empty_file.php`) with the following error:

    Uncaught exception: Could not start xdebug profiler. Another profiler is likely already attached to this thread.

This seems to be independend of the `max_nesting_level` value, even for `0` it fails.

**Comment by Orvid** [comment]
We're a small team, and it doesn't look as though anyone in the community is actively working on this issue, so we've decided to close it. If you plan to send us a pull request resolving the issue let us know in the comments and we will re-open it and assign it to you. If you feel this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
