### ISSUE TITLE
[1]    30483 segmentation fault (core dumped)  hhvm when install hhvm for ubuntu  14.04

### ISSUE THREAD

**Issue by joostshao** [facebook/hhvm#5461]
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty

 crashfile: 
https://www.dropbox.com/s/p1gk1xarc6alwce/_usr_bin_hhvm.1000.crash?dl=0

someone can help me ?

**Comment by paulbiss** [comment]
Not a lot here to go on. Do you have an isolated repro or the stacktrace file hhvm dumped?

**Comment by aingram** [comment]
The crash dump indicates that /usr/local/lib/libjemalloc.so.3.3.0 was loaded in the crashed process, but elsewhere in the crash file it indicates that there's a dependency on jemalloc 3.5.1. I think your /usr/local/lib copy of jemalloc is conflicting with the one that, I believe, is installed by the package manager. Try removing the copy in /usr/local/lib and let me know if that works.

**Comment by joostshao** [comment]
@aingram , thank you very much , it works.
if remove the jemalloc and reinstall it, is ok now.
hhvm is working.

this is ubuntu 14.04 , 64 bit, jemalloc object
/usr/lib/x86_64-linux-gnu/libjemalloc.so.1
