### ISSUE TITLE
Ubuntu 14.04 hhvm-nightly package is broken

### ISSUE THREAD

**Issue by Orvid** [facebook/hhvm#5462]
When trying to install via aptitude on Ubuntu 14.04, it claims it can't find a source to download version `2015.06.08~trusty` of `hhvm-nightly:amd64`.

**Comment by flowl** [comment]
Looking into the package information (http://dl.hhvm.com/ubuntu/dists/trusty/main/binary-amd64/Packages) you will see that `hhvm-dev-nightly_2015.06.10~trusty_amd64.deb` is currently available. Nightly builds are not 100% stable.

I guess your problem is already resolved automatically?

**Comment by Orvid** [comment]
That is correct, the current version is fine.
