### ISSUE TITLE
Debian jessie package doesn't work on Debian stretch

### ISSUE THREAD

**Issue by Calinou** [facebook/hhvm#5464]
I use Debian stretch and would like to use HHVM for benchmarks, so I installed the Debian jessie repository and package. However, when trying to use the `hhvm` command, I get this:

```
hhvm: error while loading shared libraries: libvpx.so.1: cannot open shared object file: No such file or directory
```

Trying to `apt-get install libvpx1` tells me:

```
Package libvpx1:i386 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libvpx1

E: Package 'libvpx1:i386' has no installation candidate
```

I am on amd64 architecture.

**Comment by paulbiss** [comment]
This might be a better issue for the packaging repo (https://github.com/hhvm/packaging). We're not building stretch packages yet, but I imagine the fix for this will be to start doing that rather than changing the way Jessie is packaged.

**Comment by fredemmott** [comment]
Yep, Jessie packages are only intended for Jessie.

**Comment by motin** [comment]
This is being tracked in https://github.com/hhvm/packaging/issues/128
