### ISSUE TITLE
strtr( $str, $replace_pairs ) performs poorly with certain inputs

### ISSUE THREAD

**Issue by atdt** [facebook/hhvm#5471]
`strtr()` invoked with an array `$replace_pairs` as the second argument appears to perform much worse under HHVM than PHP5.

Test case: `strtr( $text, $zh2Hant )`, where `$text` is the contents of http://www.gutenberg.org/files/23835/23835-0.txt and $zh2Hant is as defined in https://github.com/wikimedia/mediawiki/blob/master/includes/ZhConversion.php

Working script: https://github.com/atdt/hhvm-strtr

HHVM 3.6.1: 2279.07ms
PHP5: 83.26ms

**Comment by atdt** [comment]
PHP's implementation of multiple-string search was formerly quite naive, which was the subject of [PHP bug](https://bugs.php.net/bug.php?id=63893). In 2013, it was [rewritten](http://git.php.net/?p=php-src.git;a=commitdiff;h=ccf15cf2dc92d11f92ee30c97e2d86b07f81e030) to utilize a clever and efficient algorithm for multi-pattern searching ([Wu-Manber](http://webglimpse.net/pubs/TR94-17.pdf)), and then [further optimized](http://git.php.net/?p=php-src.git;a=commitdiff;h=cddbb98ada6bdba1596ea82386401edf9b680d47). It looks like HHVM's implementation is based on the naive implementation PHP sported before PHP 5.4, which explains the poor performance.

**Comment by joostshao** [comment]
it is amazing!  

HHVM (-vEval.Jit=true -vEval.JitProfileInterpRequests=0):3080.78ms
PHP5:93.76ms

**Comment by SiebelsTim** [comment]
Closed in #5517
