### ISSUE TITLE
hhvm.debug.profiler_output_dir being ignored by xhprof?

### ISSUE THREAD

**Issue by cosmok** [facebook/hhvm#5473]
I am seeing:

"Warning: Must specify directory location for XHProf runs. Trying /tmp as default. You can either pass  the directory location as an argument to the constructor for XHProfRuns_Default() or set xhprof.output_dir ini param." 
in hhvm error.log
   
   $hhvm --version
    HipHop VM 3.7.1 (rel)
    Compiler: tags/HHVM-3.7.1-0-g111c76378ac29aa8f25e6bb3c5f15b628e6bbea1
    Repo schema: be14a89778f35ca7f7dd4aca7fff0793e8ae3334

The output dir exists is is writable by hhvm.

**Comment by Orvid** [comment]
We're a small team, and it doesn't look as though anyone in the community is actively working on this issue, so we've decided to close it. If you plan to send us a pull request resolving the issue let us know in the comments and we will re-open it and assign it to you. If you feel this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
