### ISSUE TITLE
HHVM not Logging after you manually remove the error.log

### ISSUE THREAD

**Issue by kenliao94** [facebook/hhvm#5477]
Hi, I am running HHVM 3.7. However I discovered that HHVM failed to log if I remove or rename the error.log at the log path. My php.ini setting is:

  ; php options
  session.save_handler = memcached
  session.save_path = "127.0.0.1:11211"
  session.gc_maxlifetime = 7200
  memcached.sess_prefix = "memc.sess.key."
   
 ; hhvm specific 
  hhvm.log.level = Warning
  hhvm.log.always_log_unhandled_exceptions = true
  hhvm.log.runtime_error_reporting_level = 8191
  hhvm.mysql.typed_results = false

To reproduce the issue, you rename error.log to error. Then intentionally trigger an error. A new error.log is not generated. If you try "touch error.log", then intentionally trigger an error, it will not append to the newly generated error.log. I am new to HHVM & Web dev in general, not sure if this is a lack of feature or bug. But it will be great if a new error.log is generated since I occasionally copy over the old error.log and rename so I don't have to look at all the error msg on one file. 

P.S It can be fixed by restarting HHVM

**Comment by mattlqx** [comment]
Daemons in general don't re-open file descriptors without instruction to do so. You usually force a reload (if the daemon implements it) or just plain old restart it for it to open a new file descriptor for that path. If you want to truncate the file without interrupting operation of the daemon, you should just cat /dev/null to it, ala `cat /dev/null > /var/log/hhvm/error.log`.
