### ISSUE TITLE
$_SERVER["SCRIPT_NAME"] is always overwritten

### ISSUE THREAD

**Issue by Congelli501** [facebook/hhvm#5480]
I want to pass a special SCRIPT_NAME server variable to hhvm to get symfony understand my route properly.
I'm using ngnix + 3.7.1

I'm using this ngnix parameter:

    fastcgi_param SCRIPT_NAME /front/app_dev.php;

This works fine using php-fpm: `var_dump($_SERVER['SCRIPT_NAME'])` will print `/front/app_dev.php`

With hhvm, the param get overwritten. I get `app_dev.php`, which seems to be `basename($_SERVER['SCRIPT_FILENAME'])`

If set, hhvm should not overwrite the SCRIPT_NAME parameter.

**Comment by Orvid** [comment]
We're a small team, and it doesn't look as though anyone in the community is actively working on this issue, so we've decided to close it. If you plan to send us a pull request resolving the issue let us know in the comments and we will re-open it and assign it to you. If you feel this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
