### ISSUE TITLE
Allow user attributes on properties

### ISSUE THREAD

**Issue by jwatzman** [facebook/hhvm#5493]
I see no reason why not, I think this was just omitted since FB never needed it but there's no fundamental problem with it?

**Comment by guilhermegeek** [comment]
:+1: Thank you for opening, wish i could help with code. Would be really usefull on DTOs mapping scenarious  http://3v4l.org/2MTUg

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This works in modern versions of hhvm. You need to create a class for the attribute and implement `\HH\InstancePropertyAttribute`.
