### ISSUE TITLE
admin_server fails to return a response

### ISSUE THREAD

**Issue by pluggema** [facebook/hhvm#5495]
Hi All,

I'm having difficulties getting the admin server to work. It looks like it accepts the connection, but then fails to respond to a GET. I'm running HHVM in a loadbalanced environment, but even on the localhost it simply won't respond. The OS is CentOS 7.1, HHVM is built as per https://github.com/facebook/hhvm/wiki/Building-and-installing-hhvm-on-CentOS-7.x. I also gave the RPM a try, but that shows the exact same behaviour, so I'm starting to feel this is me misconfiguring something. 

Please find more details below (below commands are executed as root (HHVM runs as root too) with SELinux disabled and firewalld disabled. The webserver used is apache 2.4.12:
[root@webnode3 ~]# cat /etc/hhvm/server.ini
pid = /var/run/hhvm/pid

hhvm.server.ip = 127.0.0.1
hhvm.server.port = 9000
hhvm.server.type = fastcgi
hhvm.server.default_document = index.php
hhvm.source_root = /var/www/container
hhvm.server.always_use_relative_path = false
hhvm.server.thread_count = 32
hhvm.resource_limit.max_socket = 65536

hhvm.jit = true
hhvm.jit_a_size = 67108864
hhvm.jit_a_stubs_size = 22554432
hhvm.jit_global_data_size = 22554432

hhvm.mysql.typed_results = true

; logging
hhvm.log.use_syslog = true
hhvm.log.use_log_file = true
hhvm.log.file = /var/log/hhvm/error.log
hhvm.log.access.file = /var/log/hhvm/access.log
hhvm.log.level = Verbose
hhvm.log.always_log_unhandled_exceptions = true
hhvm.log.runtime_error_reporting_level = 8191

; mp
; hhvm.repo.authoritative=true
hhvm.repo.central.path=/opt/tmp/hhvm.hhbc
hhvm.admin_server.port=8088
hhvm.admin_server.thread_count=1
hhvm.admin_server.type=fastcgi
hhvm.admin_server.password=password
hhvm.error_handling.enable_hip_hop_errors = true
hhvm.error_handling.notice_frequency = 1
hhvm.error_handling.warning_frequency = 1
hhvm.error_handling.assert_active = false
hhvm.error_handling.assert_warning = false
hhvm.server.max_post_size = 10485760

[root@webnode3 ~]# hhvm --version
HipHop VM 3.8.0-dev (rel)
Compiler: heads/master-0-g989a6ea99e7c2a102edfb95a6f7497cd94430561
Repo schema: 952f4c193a8ef5cb73b7cdde275857248069ca2e

[root@webnode3 ~]# netstat -anp |grep hhvm
tcp        0      0 127.0.0.1:9000          0.0.0.0:*               LISTEN      31105/hhvm
tcp        0      0 127.0.0.1:8088          0.0.0.0:*               LISTEN      31105/hhvm
unix  3      [ ]         STREAM     CONNECTED     1090714  31105/hhvm
unix  3      [ ]         STREAM     CONNECTED     1090713  31105/hhvm
unix  3      [ ]         STREAM     CONNECTED     1090712  31105/hhvm
unix  3      [ ]         STREAM     CONNECTED     1091617  31105/hhvm
unix  2      [ ]         DGRAM                    1090705  31105/hhvm
unix  3      [ ]         STREAM     CONNECTED     1090711  31105/hhvm

[root@webnode3 ~]# systemctl status hhvm
hhvm.service - HHVM HipHop Virtual Machine (FCGI)
   Loaded: loaded (/usr/lib/systemd/system/hhvm.service; enabled)
   Active: active (running) since Tue 2015-06-16 10:42:48 CEST; 22min ago
  Process: 31102 ExecStartPre=/usr/bin/chown apache /var/run/hhvm (code=exited, status=0/SUCCESS)
  Process: 31100 ExecStartPre=/usr/bin/mkdir -p /var/run/hhvm (code=exited, status=0/SUCCESS)
 Main PID: 31105 (hhvm)
   CGroup: /system.slice/hhvm.service
           └─31105 /usr/local/bin/hhvm --config /etc/hhvm/server.ini --user apache --mode daemon -vServer.Type=fastcgi -vServer.Port=9000

Jun 16 11:04:58 webnode3.pluggema.nl hhvm[31105]: receiving test.php
Jun 16 11:04:58 webnode3.pluggema.nl hhvm[31105]: receiving test.php
Jun 16 11:05:04 webnode3.pluggema.nl hhvm[31105]: receiving test.php

[root@webnode3 ~]# cat /etc/httpd/conf.modules.d/00-base.conf
LoadModule access_compat_module modules/mod_access_compat.so
<snip>

<IfModule !mod_php5.c>
    <FilesMatch \.php$>
        SetHandler "proxy:fcgi://127.0.0.1:9000"
    </FilesMatch>
</IfModule>

[root@webnode3 ~]# curl -v 'http://localhost:8088'
* About to connect() to localhost port 8088 (#0)
*   Trying ::1...
* Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8088 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:8088
> Accept: */*
>
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer

Any suggestions on how to debug or reconfigure are welcome, I'm pretty much out of ideas now :(

Thanks in advance,

**Comment by simonwelsh** [comment]
The admin server is also a FastCGI server, so you need to talk to it through Apache (or something else that can make FastCGI requests), rather than directly through curl.

**Comment by pluggema** [comment]
You're absolutely right. Thanks for your quick response. Setting a virtualhost up with a proxypass worked like a charm:
[root@webnode3 ~]# curl 'http://hiphop.pluggema.nl/check-health?auth=password'
{
 "load":0
, "queued":0
, "hhbc-roarena-capac":0
, "tc-hotsize":0
, "tc-size":265761
, "tc-profsize":0
, "tc-coldsize":118791
, "tc-frozensize":149466
, "rds":6384
, "rds-local":304
, "rds-persistent":52408
, "units":84
, "funcs":6460
}


Guess http://hhvm.com/blog/521/the-adminserver set me off on the wrong foot, should've noticed that that blog was from 2012 and probably outdated!

Cheers!
