### ISSUE TITLE
New CSPRNG in PHP7

### ISSUE THREAD

**Issue by jwatzman** [facebook/hhvm#5498]
PHP7 is exposing some new RNG API functions, which we'll need to implement. We should look into reusing their CSPRNG implementation as well.

**Comment by jwatzman** [comment]
https://github.com/facebook/hhvm/pull/5925 is in progress which I think might cover this.

**Comment by JoelMarcey** [comment]
Assigning `facebook-github-bot` for those that are claimed, but cannot be directly assigned to the user.

**Comment by jwatzman** [comment]
https://wiki.php.net/rfc/easy_userland_csprng
