### ISSUE TITLE
Add Spaceship operator

### ISSUE THREAD

**Issue by sgolemon** [facebook/hhvm#5499]

**Comment by steelbrain** [comment]
:heart:

**Comment by jwatzman** [comment]
RFC: https://wiki.php.net/rfc/combined-comparison-operator
Internal task: 7888640

**Comment by Orvid** [comment]
What's the current progress of this?

**Comment by JoelMarcey** [comment]
We have internal diff for this:  D2438952. It is in review.

cc: @ricklavoie

**Comment by steelbrain** [comment]
:tada:
