### ISSUE TITLE
Add ifsetor / null coalescing operator `??`

### ISSUE THREAD

**Issue by sgolemon** [facebook/hhvm#5500]
`expr1 ?? exp2` => `isset(expr1) ? expr1 : expr2`

**Comment by steelbrain** [comment]
Bump

**Comment by jwatzman** [comment]
@steelbrain we are just now starting to spin up our PHP7 efforts in earnest. Will still be a few months, but we want to be done by the time PHP7 itself is out.

**Comment by steelbrain** [comment]
@jwatzman Great Thanks for the update :clap:

**Comment by jwatzman** [comment]
RFC: https://wiki.php.net/rfc/isset_ternary
Internal task: 7888690

**Comment by jwatzman** [comment]
This is claimed by @ricklavoie btw, sorry for not updating here sooner. It's waiting on some other refactoring to land.

**Comment by JoelMarcey** [comment]
Assigning `facebook-github-bot` for those that are claimed, but cannot be directly assigned to the user, this case @ricklavoie

**Comment by jwatzman** [comment]
Closed by fcf8d4dea785cdbcba02baa7a0d94020d14a9a10
