### ISSUE TITLE
Certain places construct Mutex<T> incorrectly

### ISSUE THREAD

**Issue by Orvid** [facebook/hhvm#5503]
Mutex is defined [here](https://github.com/facebook/hhvm/blob/master/hphp/util/mutex.h#L190), and, as you can see, the first argument is expected to be a bool, however there are some places that attempt to pass an `HPHP::Rank` in for the first value rather than the second. This is hidden due to the warnings that are currently disabled in the HHVM build. I only noticed it because I'm building with significantly fewer warnings disabled while I port HHVM to MSVC.

The first place is [here](https://github.com/facebook/hhvm/blob/master/hphp/util/synchronizable-multi.cpp#L28) in the constructor of SyncronizableMulti.
The second place is [here](https://github.com/facebook/hhvm/blob/master/hphp/util/synchronizable.cpp#L27) in the constructor of Syncronizable.

I would submit a PR to fix this myself, but my working directory is a mess due to the port, and isolating small fixes like this is not easy, especially when there are just over 200 modified files in HHVM itself, and even more in it's dependencies.

**Comment by fredemmott** [comment]
This was fixed.
