### ISSUE TITLE
Warning: Validation failed: no DTD found ! in Entity

### ISSUE THREAD

**Issue by lsmith77** [facebook/hhvm#5506]
I am getting these warnings on HHVM:
https://travis-ci.org/jackalope/jackalope-doctrine-dbal/jobs/67356904#L218

Which I am not seeing with PHP builds:
https://travis-ci.org/jackalope/jackalope-doctrine-dbal/builds/67356891

**Comment by Orvid** [comment]
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.
