### ISSUE TITLE
incompatible with laravel

### ISSUE THREAD

**Issue by obb12** [facebook/hhvm#5519]
just rendering one blade file
fails

**Comment by Orvid** [comment]
Which version of HHVM, and which version of Laravel? Would it be possible for you to include the file that fails to render as well? I know there are multiple people using Laravel with HHVM successfully, so it may be a small, specific piece that you're having issues with. The Laravel tests are also currently showing as passing 100%.

**Comment by obb12** [comment]
laravel 5.1

**Comment by fredemmott** [comment]
We can't work on this without an isolated example.

**Comment by obb12** [comment]
just laravel 5.1 without editing any file

**Comment by paulbiss** [comment]
An isolated example generally means a single (short) PHP file we can run without installing any frameworks or other code (ideally in CLI mode, though that isn't always possible). You should try to figure out what in laravel isn't working and distill it down to something we can look at (we're all quite familiar with hhvm but not so much laravel, so doing the debugging in laravel really wouldn't be a good use of our time :)).

**Comment by obb12** [comment]
it was laravel cache files that needed chmod 775 nothing else
closed
