### ISSUE TITLE
Segmentation fault with HHVM and Travis CI

### ISSUE THREAD

**Issue by photodude** [facebook/hhvm#5520]
We have ran into the [following issue](https://travis-ci.org/joomla/joomla-cms/jobs/62108921) running HHVM on Travis CI with PHPUnit 4.1.6 or PHPUnit 4.6.6  (There is a possibility that Travic CI is forcing PHPUnit 4.5)
```
Fatal error: request has exceeded memory limit in /vendor/phpunit/php-timer/PHP/Timer.php on line 138
/home/travis/build.sh: line 41:  5463 Segmentation fault      phpunit --configuration travisci-phpunit.xml
```
Related report in PHPUnit
https://github.com/sebastianbergmann/phpunit/issues/1714

Possibly related report with HHVM and PHPUnit
https://github.com/facebook/hhvm/issues/5421

**Comment by fredemmott** [comment]
Travis is running HHVM 3.5.0, which is an outdated and unsupported version. Can you reproduce a problem on 3.8?

**Comment by photodude** [comment]
I don't know about 3.8 I currently have 3.6.6 on Travis-CI

I'm no longer getting the memory issue just the Segfault with that
https://travis-ci.org/photodude/joomla-cms/jobs/109432023
```
Core dumped: Segmentation fault
Stack trace in /tmp/stacktrace.2792.log
/home/travis/build.sh: line 45:  2792 Segmentation fault (core dumped)
libraries/vendor/bin/phpunit --configuration travisci-phpunit.xml
```

**Comment by fredemmott** [comment]
3.6 and 3.8 are no longer supported; Travis do not have any supported versions.

**Comment by photodude** [comment]
Apparently Travis Containers are stuck with hhvm 3.6 since I believe their container is Ubuntu 12.04 Precise which only ships with hhvm3.6

I'll have to see if there is a way to get around that build issue.
