### ISSUE TITLE
var_export/fopen/php://stdout -- inconsistent behavior between php/hhvm

### ISSUE THREAD

**Issue by ralt** [facebook/hhvm#5521]
```php
<?php

var_export(fopen('php://stdout', 'w'));
```

Has this behavior on PHP:

```
NULL
```

And this behavior on HHVM:

```
array (
)
```

Fiddle with it: http://3v4l.org/ZParq

<sub>Originally reported by [Ocramius](https://twitter.com/Ocramius/status/612998893392003072).</sub>

**Comment by Ocramius** [comment]
Note: should throw an exception, tbh. `var_export(resource)` should simply fail.

I'd rather have this discussed between the HHVM and the PHP team than fixed to something that is not useful in first place.

**Comment by krakjoe** [comment]
I think compatibility is the primary issue, there is little to no chance of getting a change through php-src that makes a core function throw an exception, especially such an old one ... I'm not sure what kind of change would be acceptable.

**Comment by Ocramius** [comment]
@krakjoe agreed on that, still a problem tho. Notice/warning is sufficient there IMO

**Comment by Orvid** [comment]
We match the PHP behavior as-of 3.12
