### ISSUE TITLE
http_response_code() different from PHP5 for HTTP 200 codes

### ISSUE THREAD

**Issue by richardkmiller** [facebook/hhvm#5522]
Setting `http_response_code(200)` or getting `http_response_code()` where the value should be 200 return `-1`. In PHP5 they return `200`.

The test code in 6698889 returns the following values:
````
int(-1)
int(-1)
int(-1)
int(-1)
int(-1)
int(-1)
int(295)
int(295)
int(295)
int(295)
int(404)
````

The same test in PHP5 returns the following values:
````
int(200)
int(200)
int(200)
int(200)
int(-1)
int(-1)
int(295)
int(295)
int(295)
int(295)
int(404)
````

**Comment by fredemmott** [comment]
- we continually test the output matches the .expect file
- we appear to match every current version of PHP: http://3v4l.org/XAoIr

**Comment by richardkmiller** [comment]
@fredemmott I should have mentioned: these were web requests using hhvm daemon and php5-fpm. The versions were `hhvm 3.7.2~trusty` and `php5-fpm 5.5.9+dfsg-1ubuntu4.9`.

**Comment by Orvid** [comment]
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.
