### ISSUE TITLE
Uniform variable syntax

### ISSUE THREAD

**Issue by jwatzman** [facebook/hhvm#5523]
https://wiki.php.net/rfc/uniform_variable_syntax
https://github.com/php/php-src/pull/686
How we want to deal with the BC here is interesting, alongside PHP5 and Hack.

**Comment by jwatzman** [comment]
Plan is to have the parser support both (somehow, hopefully through some not-totally-ugly Bison or preprocessor magic; an "ambiguous parser" AST node would be really nice so we can do this in a pass later, without forking the parser).

There will be an INI option to set whether you want the PHP5 or PHP7 behavior, and another INI option to override that to the other setting for a list of directories. This is the best way we came up with to allow mixed projects without breaking compat with PHP5/PHP7 themselves (different opening tags) or without doing something ugly like file extensions or semantically-meaningful comments.

**Comment by nikic** [comment]
That sounds like pretty big overkill. To the best of my knowledge the BC impact of this change is very low in practice and it should not break the world to just switch this at some point.

**Comment by jwatzman** [comment]
It's still a BC break, and a very subtle one at that. And we'll need the switch for more than just this one I think, for a couple other BC breaks in PHP7 like typehints or array->string conversion.

**Comment by jwatzman** [comment]
I'm starting to look into what the parser changes might have to look like to support both.

**Comment by jwatzman** [comment]
Relevant commits seem to be

- https://github.com/nikic/php-src/commit/95a3a126577aae761a93b06b051b23322d9a6e41
- https://github.com/nikic/php-src/commit/b8b3b355be4ac5c537dd5fc60c929f9f15c5c636
- https://github.com/nikic/php-src/commit/a8c1595012a59d5b4e8a8d0b90650f3075f02869

@nikic does that seem reasonable? (Plus a few refactors you did that we may or may not want to do, depending on whether it makes it easier or harder to maintain the PHP5/PHP7 split.)

Our parser originally traces its lineage back to PHP's, enough so that it's pretty straightforward to make equivalent changes to ours... the actual parser changes don't seem that painful if we could just make them. But figuring out how to generate two bison outputs from one input is what I'm currently thinking through. `cpp` doesn't really work since there are other preprocessor directives in there we don't want expanded until the file is actually compiled (*after* it's run through bison). I'd really love to just pull out the 5-10 different rules though. Maybe some shell script / sed magic, though that's pretty ugly and painful to read / regenerate. There's also probably some lexer hack we could do (e.g., `$` is T_PHP5_DOLLAR or T_PHP7_DOLLAR, so certain rules only work sometimes depending on what the lexer spits out, and there's a bison rule that is either one if you don't care). But that's not necessarily generalizable, and probably even *harder* to read/maintain :)

**Comment by jwatzman** [comment]
I'm going to try the "split out part of the bison file and use sed to inject the right version", which I *think* will work well for the three commits above. I need to remember this RFC also added new syntax (or, rather, made syntax that you would have thought would have work all along, actually work), which could put a wrench in that, will need to investigate.

**Comment by nikic** [comment]
Yeah, those three commits may cover the BC breaking changes, but there should be a bunch more that add new syntax. You already support some of it like `(function(){})()`, but not everything (like `foo()()`).

I don't envy you this parser split, sounds like maintenance nightmare :)

**Comment by jwatzman** [comment]
@nikic I'm going to try the parser split, I don't think it will be that bad, and if it is, I think I can do it in only like a day of work or so anyways. (Since I'm basically ripping off your amazing work :-P)

As we're continuing to evaluate this, do you know if someone ever wrote a tool that looked for the BC-breaking constructions? I'd like to run it on FB's frontend, as well as Wordpress/Drupal/MediaWiki/etc (which someone else has probably already done) to see how tractable just going "fuck it" and changing the parser would be. Basically, you seem to think that the BC breaks aren't that bad, and my intuition mostly agrees with you, but I want to check some actual data :)

**Comment by nikic** [comment]
I used this script to find potential cases for the RFC: https://gist.github.com/nikic/ffd019ef78b72934c7cc It's not accurate though (false positives)

I also have an accurate implementation locally that does automatic code fixes, but never published that project. Of course it doesn't support Hack, so probably not super useful for FB code.

Here's the results for some projects. When writing the RFC I also tested Symfony+deps (no problems) and ZF2 (one occurrence).

Mediawiki 1.25.2:

```
../mediawiki-1.25.2\includes\jobqueue\jobs\UploadFromUrlJob.php:
@@ -170,7 +170,7 @@
         */
        public function initializeSessionData() {
                $session =& self::getSessionData( $this->params['sessionKey'] );

-               $$session['result'] = 'Queued';
+               ${$session['result']} = 'Queued';
        }

        /**
```

Drupal 7.39, Drupal 6.37, WordPress 4.3: Nothing.

One software I just tested where there is a higher impact is Magento 1.9.2.0 with nine places:

```
../magento-1.9.2.0\magento\app\code\core\Mage\Catalog\Model\Product\Link\Api\V2.php:
@@ -61,8 +61,8 @@
 
         $links[(int)$linkedProductId] = array();
         foreach ($collection->getLinkModel()->getAttributes() as $attribute) {
-            if (isset($data->$attribute['code'])) {
-                $links[(int)$linkedProductId][$attribute['code']] = $data->$attribute['code'];
+            if (isset($data->{$attribute['code']})) {
+                $links[(int)$linkedProductId][$attribute['code']] = $data->{$attribute['code']};
             }
         }
 
@@ -118,8 +118,8 @@
         }
 
         foreach ($collection->getLinkModel()->getAttributes() as $attribute) {
-            if (isset($data->$attribute['code'])) {
-                $links[(int)$linkedProductId][$attribute['code']] = $data->$attribute['code'];
+            if (isset($data->{$attribute['code']})) {
+                $links[(int)$linkedProductId][$attribute['code']] = $data->{$attribute['code']};
             }
         }

../magento-1.9.2.0\magento\app\code\core\Mage\Core\Model\Layout.php:
@@ -552,7 +552,7 @@
         $out = '';
         if (!empty($this->_output)) {
             foreach ($this->_output as $callback) {
-                $out .= $this->getBlock($callback[0])->$callback[1]();
+                $out .= $this->getBlock($callback[0])->{$callback[1]}();
             }
         }
 
../magento-1.9.2.0\magento\app\code\core\Mage\ImportExport\Model\Export\Entity\Customer.php:
@@ -247,7 +247,7 @@
                 $data = $this->_attributeOverrides[$attribute->getAttributeCode()];
 
                 if (isset($data['options_method']) && method_exists($this, $data['options_method'])) {
-                    $data['filter_options'] = $this->$data['options_method']();
+                    $data['filter_options'] = $this->{$data['options_method']}();
                 }
                 $attribute->addData($data);
             }

../magento-1.9.2.0\magento\app\code\core\Mage\ImportExport\Model\Export\Entity\Product\Type\Abstract.php:
@@ -96,7 +96,7 @@
             $data = $this->_attributeOverrides[$attribute->getAttributeCode()];
 
             if (isset($data['options_method']) && method_exists($this, $data['options_method'])) {
-                $data['filter_options'] = $this->$data['options_method']();
+                $data['filter_options'] = $this->{$data['options_method']}();
             }
             $attribute->addData($data);

../magento-1.9.2.0\magento\app\code\core\Mage\ImportExport\Model\Import\Uploader.php:
@@ -132,7 +132,7 @@
         //run validate callbacks
         foreach ($this->_validateCallbacks as $params) {
             if (is_object($params['object']) && method_exists($params['object'], $params['method'])) {
-                $params['object']->$params['method']($filePath);
+                $params['object']->{$params['method']}($filePath);
             }
         }
     }

../magento-1.9.2.0\magento\downloader\lib\Mage\Connect\Packager.php:
@@ -918,13 +918,13 @@
 
                         $names = array("pMin","pMax","hasMin","hasMax");
                         for ($i=0, $c=count($names); $i<$c; $i++) {
-                            if(!isset($$names[$i])) {
+                            if(!isset(${$names[$i]})) {
                                 continue;
                             }
-                            if(false !== $$names[$i]) {
+                            if(false !== ${$names[$i]}) {
                                 continue;
                             }
-                            $$names[$i] = $i % 2 == 0 ? "0" : "999999999";
+                            ${$names[$i]} = $i % 2 == 0 ? "0" : "999999999";
                         }
 
                         if(!$cache->hasVersionRangeIntersect($pMin,$pMax, $hasMin, $hasMax)) {

../magento-1.9.2.0\magento\lib\Mage\Connect\Packager.php:
@@ -564,13 +564,13 @@
 
                         $names = array("pMin","pMax","hasMin","hasMax");
                         for($i=0, $c=count($names); $i<$c; $i++) {
-                            if(!isset($$names[$i])) {
+                            if(!isset(${$names[$i]})) {
                                 continue;
                             }
-                            if(false !== $$names[$i]) {
+                            if(false !== ${$names[$i]}) {
                                 continue;
                             }
-                            $$names[$i] = $i % 2 == 0 ? "0" : "999999999";
+                            ${$names[$i]} = $i % 2 == 0 ? "0" : "999999999";
                         }
 
                         if(!$cache->hasVersionRangeIntersect($pMin,$pMax, $hasMin, $hasMax)) {

../magento-1.9.2.0\magento\lib\Varien\File\Uploader.php:
@@ -256,7 +256,7 @@
         //run validate callbacks
         foreach ($this->_validateCallbacks as $params) {
             if (is_object($params['object']) && method_exists($params['object'], $params['method'])) {
-                $params['object']->$params['method']($this->_file['tmp_name']);
+                $params['object']->{$params['method']}($this->_file['tmp_name']);
             }
         }
     }
```

**Comment by jwatzman** [comment]
@nikic thanks, the info is super useful! Yeah too bad we can't use it at FB due to Hack features, but I might be able to adapt it or do something similar if my current attempt to split the parser fails.

**Comment by jwatzman** [comment]
Some diffs for this are starting to land. The one that adds new static member access forms doesn't support `var_dump(['array', 'literal'][0]::$x)` -- PHP7 has an inconsistency in that it doesn't support `new ['array', 'literal'][0]::$x` either, but in HHVM that actually ended up causing parser conflicts to support the former. (Since our two forms there are somewhat more related.)

**Comment by nikic** [comment]
Nice work!

**Comment by jwatzman** [comment]
OK, there are still a bunch of diffs yet to land, but I think I've implemented everything that's worth implementing here. I'll post again when the diffs are all out so @nikic or anyone else can take a look :)

**Comment by jwatzman** [comment]
I think this is done.

**Comment by jwatzman** [comment]
Internal user discovered this case doesn't work:

```php
<?php

class C {
  const X = 1;

  static function f() {
    return new C();
  }
}

var_dump(C::f()::X);
```

**Comment by jwatzman** [comment]
OK, I think this is done, again :)
