### ISSUE TITLE
HHVM compilation on Centos 7 results in errors

### ISSUE THREAD

**Issue by zaiddabaeen** [facebook/hhvm#5536]
I have copy pasted under a root user what is provided in [Centos 7 compilation page](https://github.com/facebook/hhvm/wiki/Building-and-installing-hhvm-on-CentOS-7.x), however:

```
[ 43%] Building CXX object hphp/hhbbc/CMakeFiles/hphp_hhbbc.dir/emit.cpp.o
[ 43%] Building CXX object hphp/compiler/CMakeFiles/hphp_analysis.dir/analysis/emitter.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
make[2]: *** [hphp/hhbbc/CMakeFiles/hphp_hhbbc.dir/emit.cpp.o] Error 4
make[1]: *** [hphp/hhbbc/CMakeFiles/hphp_hhbbc.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 43%] Building CXX object hphp/compiler/CMakeFiles/hphp_analysis.dir/analysis/function_scope.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
make[2]: *** [hphp/compiler/CMakeFiles/hphp_analysis.dir/analysis/emitter.cpp.o] Error 4
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [hphp/compiler/CMakeFiles/hphp_analysis.dir/all] Error 2
make: *** [all] Error 2
```

I have retried the compilation multiple times.

**Comment by jwatzman** [comment]
`c++: internal compiler error: Killed (program cc1plus)`

The cause of this is almost invariably running out of RAM. How much memory does your machine have? You'll need at least 4G or so, more if you're using `make -j`.

**Comment by Sydney-o9** [comment]
This is correct @jwatzman, I tested this in a vagrant machine.

I got the error with 1Gb RAM, the error disappears if RAM > 2.8Gb (might work with less but didn't try to get lower than that)

My compiler is GCC v4.9.2.

If you guys are using Vagrant, just modify your Vagrantfile:

````
  config.vm.provider "virtualbox" do |v|
    v.memory = 2800
    v.cpus = 2
  end
````

**Comment by jwatzman** [comment]
Glad you got it sorted.

**Comment by Kompas** [comment]
I'm using Digital Ocean. I got the issue solved by changing the memory from 1GB to 2GB.

Specs VM:
2GB Ram
2 CPU's
30GB SSD Disk
CentOS 7.1 x64

**Comment by zaiddabaeen** [comment]
Yes it is confirmed the issue is caused by low RAM.

**Comment by jwatzman** [comment]
Yep, HHVM takes a lot of RAM to compile. It takes somewhat less to run, so you can play with decreasing the RAM again after the compile is done.
