### ISSUE TITLE
Behavior doesn't match PHP when 'use()' variable name matches parameter name

### ISSUE THREAD

**Issue by hussainweb** [facebook/hhvm#5541]
The problem could be said to be the code, but both PHP5/7 and HHVM accept it, but behave differently.

If one of the parameters in a closure has the same name as one of the variables in the use construct, then only one of them can be used. PHP5/7 uses the variable in the use construct whereas HHVM uses the one in the parameters. See this eval: http://3v4l.org/1LTC3

I originally identified this when fixing Guzzle to pass tests on HHVM. See https://github.com/guzzle/guzzle/pull/1143 for the PR. The actual line is at https://github.com/guzzle/guzzle/pull/1143/files#diff-97598a53896efebd2fe6eed1a5f2284aR68.

I tried searching for this issue but couldn't find it. I apologize if it is a duplicate.

**Comment by SiebelsTim** [comment]
This is stupid actually. I thin emitting a warning would be better than match php.

**Comment by hussainweb** [comment]
+1 to the warning, but I think it will also be good to match PHP behaviour. It doesn't look like a valid use case, and hence, I don't think anyone would be using this consciously. It is not really a question of which behaviour is correct. If it is simple to change, it seems certainly better to match PHP.

**Comment by nikic** [comment]
@SiebelsTim PHP 7.1 agrees that this is stupid and will throw a compile-time error:

    $ sapi/cli/php -r 'function($x) use($x) {};'
    Fatal error: Cannot use lexical variable $x as a parameter name in Command line code on line 1
