### ISSUE TITLE
Resources not supported as constant values

### ISSUE THREAD

**Issue by lstrojny** [facebook/hhvm#5549]
### Example

``` php
<?php
define('OHHAI', hash_init('gost'));
var_dump(OHHAI);
```
### Expected

```
resource(4) of type (Hash Context)
```
### Actual

```
Warning: Constants may only evaluate to scalar values in /in/Xl0di on line 3

Notice: Use of undefined constant OHHAI - assumed 'OHHAI' in /in/Xl0di on line 5
string(5) "OHHAI"
```

http://3v4l.org/Xl0di

**Comment by Orvid** [comment]
While a select few resources might be able to be initialized once and used from there across many requests, cases like this would need to be initialized and referenced separately for each request, which means the value can't be inlined. I do wonder the purpose of allowing resource values as constants in the first place...

**Comment by lstrojny** [comment]
@Orvid no good real world usecase I would know about but I use it as a hack to express a special purpose argument here: https://github.com/lstrojny/functional-php/blob/master/src/Functional/PartialAny.php#L53

**Comment by Orvid** [comment]
This should be fixed as-of https://github.com/facebook/hhvm/commit/9559420b8c227ecaf89756a1b02b16b993987542.
