### ISSUE TITLE
Variant Type

### ISSUE THREAD

**Issue by bolvarak** [facebook/hhvm#5550]
# Feature Request

While this class works quite nicely, it would be really awesome to see something like this natively, it basically replicates the fluid conversion and type juggling of QVariant from the QT​ framework.  A lot of people would like to see something similar for strings to the various scalar conversions, but I think this is a happy alternative that way in PHP's loose typing (even in Hack) that way strings stay strings and anything that can be fluidly converted would take on the Variant type.  A real world example of this would be for SQL query results, because mapTyped doesn't work as well as it should, so instead return a Map<string, Variant> that way the developer can choose to convert the type to what they expect.
# Example

``` php
// Run the query, not 100% syntactically correct, I know
$qryResults = MySqlAsyncConnection::queryf('SELECT * FROM %T LIMIT 1', 'fubar_table');
// Set the variant
$varRow = Variant::Factory($qryResults->mapRowsTyped()->get(0));
// Do something
$blnVar     = $varResult->get('someColumn')->toBool();
```
# Opposed to

``` php
// Run the query, not 100% syntactically correct, I know
$qryResults = MySqlAsyncConnection::queryf('SELECT * FROM %T LIMIT 1', 'fubar_table');
// Do something
$blnVar     = boolval($qryResult->get(0)->get('someColumn'));
```
# The Solution

Create a global type of Variant or HH\Variant and when `AsyncMysqlQueryResult::mapRows()` or `AsyncMysqlQueryResult::mapRowsTyped()` is called return a  `Vector<Map<string, Variant>>` instead of a `Vector<Map<string, mixed>>`;
# Sources

[Variant Source by Bolvarak](https://github.com/bolvarak/hackalicious/blob/master/Variant.hh)
[Qt's QVariant Header](http://code.metager.de/source/xref/lib/qt/src/corelib/kernel/qvariant.h)
[Qt's QVariant Source](http://code.metager.de/source/xref/lib/qt/src/corelib/kernel/qvariant.cpp)
# Alternative

Use something similar to QString or std::string as an option, let's say, HackString type, that allows a string to be converted to any scalar type.
# Summary

All in all, I believe this to be something needed and very useful, I could be wrong, but in the world of OOP and fluid interfaces it just makes sense to have this feature natively.

**Comment by bolvarak** [comment]
Also added in support for VariantMap and VariantList (Vector of Variants) which are the relative equivilant of QVariantMap and QVariantList

[VariantMap](https://github.com/bolvarak/hackalicious/blob/master/VariantMap.hh)
[VariantList](https://github.com/bolvarak/hackalicious/blob/master/VariantList.hh)

**Comment by azjezz** [comment]
this is something we can accomplish right now using [@hhvm/type-assert](https://github.com/hhvm/type-assert/), and having something like `Variant` won't add much, but maybe merging `type-assert` into HHVM would be nice :smile: 

```hack
use namespace Facebook\TypeAssert;
use namespace Facebook\TypeSpec;

$mixed = getMixedVariable();

// $int is now `int`
$int = TypeAssert\int($mixed);

$spec = TypeSpec\dict(
  TypeSpec\string(),
  TypeSpec\int(),
);

// $dict is now `dict<string, int>`
$dict = $spec->assertType($mixed);

```

**Comment by lexidor** [comment]
This feature is implemented for AsyncMysqlRow:

    ->at(mixed $field): mixed
        Get field (column) value indexed by the field
    ->count(): int
        Get the number of fields (columns) in the current row
    ->fieldType(mixed $field): int
        Returns the type of the field (column)
    ->getFieldAsDouble(mixed $field): float
        Get a certain field (column) value as a double
    ->getFieldAsInt(mixed $field): int
        Get a certain field (column) value as an int
    ->getFieldAsString(mixed $field): string
        Get a certain field (column) value as a string
    ->getIterator(): KeyedIterator<string, mixed>
        Get the iterator over the fields in the current row
    ->isNull(mixed $field): bool
        Returns whether a field (column) value is null

The method you need for this is AsyncMysqlQueryResult::rowBlocks().

Is this what you were looking for @bolvarak?

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

I am closing this issue. Hack supports type assertions using the `as` keyword. If you want an object that wraps mixed and exposes typed methods instead, this isn't something hhvm will provide.
