### ISSUE TITLE
hhvm toString php error

### ISSUE THREAD

**Issue by rossmc** [facebook/hhvm#5551]
I have HHVM running on our server and I'm getting this error in the HHVM logs when I try to run the import.

`\nCatchable fatal error: Object of class Magmi_ProductImportEngine could not be converted to string in /var/www/qa-hoi/magmi-importer/inc/magmi_mixin.php on line 9

On the browser the import just hangs on *Import Mode: Create* and I get a  `Failed to load resource: the server responded with a status of 500 (hphp_invoke)` error in the browser console.

Line 9 of the *magmi_mixin.php* is 
`$this->_callers=array_unique($this->_callers);`

It seems that this line of code is not following HHVM standards.  See
http://stackoverflow.com/a/31079404/1814446

This is occurring with the Magmi Product import plugin for a Magento eCommerce app.  The OS is Ubuntu & the Server is NGINX.

**Comment by fredemmott** [comment]
Can you provide a complete example which does not depend on a framework?

**Comment by rossmc** [comment]
hmm, I'm not sure how to.  The conflict is with a plugin for the Magento framework.

**Comment by hafi4u** [comment]
Me too having same issues.

**Comment by hafi4u** [comment]
Just commented 

```
public function bind($caller)
{
    $this->_callers[]=$caller;
    // $this->_callers=array_unique($this->_callers);  // LINE 9   
}
```

in file magmi/inc/magmi_mixin.php

and it worked.

Thanks to everyone in here and to R1CHY_RICH from ..
http://stackoverflow.com/a/31079404/1814446

**Comment by rossmc** [comment]
@hafi4u thanks for sharing :+1:
