### ISSUE TITLE
file_get_contents with http stream produces extra space in custom header values

### ISSUE THREAD

**Issue by vearutop** [facebook/hhvm#5553]
HHVM adds extra space after `:` for headers in context options. Default headers are not affected. This behavior does not violate HTTP protocol, but is a slight incompatibility with PHP.

```
$ hhvm --version
HipHop VM 3.8.0-dev (rel)
Compiler: heads/master-0-gfdd32b806ab1b2949e8e11fa22500894bc32fa65
Repo schema: b921f793b7c4b3a3035d156c96059d8fdf787bff
```

Test Code, checked with mirroring web service

``` php
        var_dump(file_get_contents('http://phph.tk:1337', false, stream_context_create(array(
            'http' => array(
                'method' => 'GET',
                'follow_location' => false,
                'header' => 'X-Any: value'
            ),
        ))));
```

Output, note extra space in `X-Any` header

```
string(68) "GET / HTTP/1.1
Host: phph.tk:1337
Accept: */*
X-Any:  value

"
```

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Using fgc() on urls is a phpism. Hhvm strongly encourages using curl instead. Fixing fgc is not likely going to happen. PHP code is unsupported, so we don't have to consider all the php code using fgc() anymore.
