### ISSUE TITLE
Missing semicolon for return statement in create_function results in error in debug log with no line number/ file info

### ISSUE THREAD

**Issue by r3wt** [facebook/hhvm#5554]
`\nFatal error: syntax error, unexpected '}'`

**repro:**
http://3v4l.org/HSdIG
```php
$f = create_function( '$x','return ( $x / 2 )' );
$f(5);
```

**Comment by r3wt** [comment]
Yeah, i went through my code with a fine eye and can't find the error. 
just to give you an idea of what i'm doing here's a picture:

![img](http://puu.sh/iFIcA/31d796b26c.png)

**Comment by r3wt** [comment]
another possible culprit:
```php
foreach($checkbox as $c)
{
	$model->{$c} = (int) isset($post[$c]) && $post[$c] == 1;
}
```

**Comment by r3wt** [comment]
To clarify, this should specify that it came from a user created lambda function, like php does...

**Comment by paulbiss** [comment]
Normally we don't make a point of matching exactly the error strings in PHP 5, but I could see how the extra context here would be useful.

**Comment by Orvid** [comment]
It's not as helpful as PHP, but 3.12 and above do provide a line number.
