### ISSUE TITLE
ext_hash uses an internal furc_hash function in OSS build

### ISSUE THREAD

**Issue by Orvid** [facebook/hhvm#5555]
The first (there may be more, I haven't checked) of the places where this is visible is in [ext_hash.cpp:39](https://github.com/facebook/hhvm/blob/master/hphp/runtime/ext/ext_hash.cpp#L39). The MCRouter version of this function is open source, so why is HHVM using an internal implementation? I propose that it be switched to use MCRouter's implementation if MCRouter is enabled. (I don't remember if it's currently possible to enable or disable MCRouter off the top of my head; If it isn't currently, then forcefully using MCRouter's implementation for now would be best.)

**Comment by fredemmott** [comment]
It's currently possible to disable it, as it requires boost::context, which isn't available on all the distributions we support/supported for 3.6. We can re-check the dependencies.

**Comment by fredemmott** [comment]
I'd also rather we don't switch implementations based on the mcrouter as that would require testing another build variant.

**Comment by Orvid** [comment]
Based on the conditional, I'd assume FB already builds using the MCRouter implementation, so that wouldn't add another build variant would it?

**Comment by fredemmott** [comment]
We currently just do a single OSS build. We would then have to do both OSS-with-mcrouter and OSS-without-mcrouter.
