### ISSUE TITLE
any thrift support within HHVM?

### ISSUE THREAD

**Issue by levixie** [facebook/hhvm#5557]
hi There
  I am trying to use the thrift with hhvm, I follow the steps from thrift.apache.org and it works.
  I found the runtime/ext/thirft in hhvm, and I am wondering if there any thrift support within hhvm
Thanks

**Comment by fredemmott** [comment]
Yes, see ext_thrift.php for supported functions. Recently, this has only been tested with fbthrift, though for most cases this may be compatible with apache thrift.

**Comment by levixie** [comment]
hi Fred, 
  what is the right way to use it? same as the thrift.apache.org? I try php/hhvm, both work but looks more like pure php code

**Comment by fredemmott** [comment]
that file is built into HHVM.

**Comment by levixie** [comment]
I looked into the php lib for Thrift, and I understand what your mean now.
Thanks!
