### ISSUE TITLE
Catchable fatal error: Hack type error: Unbound name: Redis (an object type)

### ISSUE THREAD

**Issue by milesj** [facebook/hhvm#5559]
Updated to the latest HHVM nightly and am now receiving this error when running tests or running individual Hack files. The full error is:

Catchable fatal error: Hack type error: Unbound name: Redis (an object type) at /vagrant/src/Titon/Cache/Storage/RedisStorage.hh line 33

And the file in question:

https://github.com/titon/framework/blob/master/src/Titon/Cache/Storage/RedisStorage.hh#L33

Has something changed recently in regards to Redis? No longer supported?

I tried creating a really basic file, and ran it like so `hhvm test.hh`, yet the error still occurs.

```
<?hh
echo 'foo';
```

**Comment by milesj** [comment]
Another weird thing. I removed that file completely and re-started HHVM. I now get this error:

Catchable fatal error: Hack type error: Could not find static method composeLocale in type Locale at /vagrant/src/Titon/Intl/Locale.hh line 239

All of these errors are missing information from HHI/IDL files. What changed recently in HHVM?

**Comment by fredemmott** [comment]
We changed hhvm to automatically invoke the typechecker.

**Comment by milesj** [comment]
So what can I do to mitigate this, just swallow fatal errors?

**Comment by fredemmott** [comment]
Options are:
 - make your code valid hack
 - persuade your users to add 'hhvm.hack.lang.auto_typecheck=0' to their ini files (we will strongly recommend against this though)

Swallowing fatal errors won't work as the typechecker is invoked pre-execution.

**Comment by milesj** [comment]
Redis and the Locale stuff is definitely valid, as seen here:

https://github.com/facebook/hhvm/blob/4498e2b25bc17ace502b4c86c551dbab25f284bf/hphp/runtime/ext/icu/ext_icu_locale.php#L66

The problem looks like the incomplete definitions in HHI:

https://github.com/facebook/hhvm/blob/4498e2b25bc17ace502b4c86c551dbab25f284bf/hphp/hack/hhi/stdlib/builtins_intl.hhi#L236

Doesn't look like something I can just "fix".

**Comment by paulbiss** [comment]
You can send us a PR to add the definitions, in the meantime you have several options, any one of these should work, I'd recommend the first, the second is not unreasonable.
 - add the HHI file to your project until the changes are merged
 - add HH_FIXME's on the lines immediately before the functions are called
 - don't call the functions in // strict files

**Comment by milesj** [comment]
For the 1st item, does HHVM automatically detect the file, or do I need to do something specific?

**Comment by paulbiss** [comment]
Should automatically pick it up, not sure if it will work if there are existing builtin HHI files that are incorrect though. In that case you may need to use HH_FIXME until it gets fixed upstream.

**Comment by milesj** [comment]
Thanks for the info.

Going to go with the 1st item as well as submitting a pull request for anything I find missing.

**Comment by milesj** [comment]
Fixed all of them locally. It *would* be nice if HHI definitions merged instead of conflicted, so we could avoid this:

```
/tmp/hh_server/hhi_39e7e34c/stdlib/builtins_intl.hhi:233:7,12: Name already bound: Locale (Naming[2012])
  /vagrant/hhi/intl.hhi:182:7,12: Previous definition is here
  /vagrant/hhi/intl.hhi:182:7,12: This appears to be defined in an hhi file included in your project root. The hhi files for the standard library are now a part of the typechecker and must be removed
from your project. Typically, you can do this by deleting the "hhi" directory you copied into your project when first starting with Hack.
```

I'll submit a pull sometime this week.

**Comment by steelbrain** [comment]
@milesj I ran into the same problem a while ago, but then I wrote this https://github.com/steelbrain/RedisNG

**Comment by milesj** [comment]
I got a good amount of HHI definitions fixed here: https://github.com/titon/framework/tree/master/hhi
