### ISSUE TITLE
Calling parse_ini_file with invalid ini file do not take the usual error handling path

### ISSUE THREAD

**Issue by nicolas-grekas** [facebook/hhvm#5561]
```php
<?php

set_error_handler(function() {var_dump(func_get_args());});
@parse_ini_file(__FILE__);
```

displays "syntax error, unexpected JUNK, expecting $end or TC_SECTION or TC_LABEL or END_OF_LINE".

But the error should be @-silenced, and the user error handler should be called also.

**Comment by Orvid** [comment]
We're a small team, and it doesn't look as though anyone in the community is actively working on this issue, so we've decided to close it. If you plan to send us a pull request resolving the issue let us know in the comments and we will re-open it and assign it to you. If you feel this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
