### ISSUE TITLE
Invalid default return value for setlocale()

### ISSUE THREAD

**Issue by nicolas-grekas** [facebook/hhvm#5562]
Trying to fetch the default locale returns the empty string, when in fact it should be "C".
Since setting the locale to the empty string changes it to the default of the system (which is not C usually), this makes it impossible to save the current locale, do some stuff, and restore it correctly afterwards.

``` php
var_dump(setlocale(LC_NUMERIC, 0));
echo sprintf('%s', 4.3), "\n";

var_dump(setlocale(LC_NUMERIC, ''));
echo sprintf('%s', 4.3), "\n";
```

echoes:

```
string(0) ""
4.3
string(0) ""
4,3
```

Not the comma vs dot in the float to string conversion.

The same script on PHP echoes:

```
string(1) "C"
4.3
string(11) "fr_FR.UTF-8"
4,3
```

which is much better.

**Comment by Orvid** [comment]
This sounds suspiciously like a misbehaving libc, as [ext_string.cpp:1865](https://github.com/facebook/hhvm/blob/master/hphp/runtime/ext/string/ext_string.cpp#L1865) is where this is implemented, and the value is returned pretty much directly. The [documentation](http://linux.die.net/man/3/setlocale) for setlocale claims that the return value should be able to restore the old locale.

**Comment by nicolas-grekas** [comment]
Not sure, maybe PHP has a workaround embedded: http://3v4l.org/3hgmL

**Comment by Orvid** [comment]
Well, it does appear that [PHP's implementation of setlocale](https://github.com/php/php-src/blob/master/ext/standard/string.c#L4468) does do a bit more than just return the value, but I'm not familiar enough with PHP's codebase to tell you what exactly it is that's being done.

**Comment by smalyshev** [comment]
Looks like the problem is this part: https://github.com/php/php-src/blob/master/ext/standard/string.c#L40 namely, libicu redefines setlocale and looks like that is exactly what hhvm is using - ICU's setlocale instead of system's setlocale.
