### ISSUE TITLE
HHVM does not trigger any strict notice/warning

### ISSUE THREAD

**Issue by nicolas-grekas** [facebook/hhvm#5583]
Reading the source, this is expected. But is it planned to add this feature at some point?

**Comment by nicolas-grekas** [comment]
```
class a
{
    function f()
    {
    }
}

class b extends a
{
    function f($z)
    {
    }
}
```

PHP:
Warning: Declaration of b::f() should be compatible with a::f()

HHVM:
*nothing*

**Comment by milesj** [comment]
Are they not logged to the HHVM error log? Pretty sure HHVM doesn't display the errors on the page, only writes them.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Duplicate of #4896 (Strict Standards and method overriding)
