### ISSUE TITLE
Typechecker doesn't recognize Generic Constraints inside a class

### ISSUE THREAD

**Issue by steelbrain** [facebook/hhvm#5584]
```
type SomeShape = shape('first' => int);
class A<T>{}
class B<T as SomeShape> extends A<T>{
  public function __construct(public T $Test){}
  public function test():void{
    $this->Test['first']; // Error: This is not an object of KeyedContainer, this is a value of generic type T
  }
}
```

**Comment by jwatzman** [comment]
If I had to guess, it's not generic constraints specifically, but the array index operator. We probably have a `unify` where there should be a `sub_type`.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Thanks for the easy repro. This works in newer hhvm versions. Accessing a key which is not declared generates an error and accessing 'first' is fine.
