### ISSUE TITLE
hh_server going unresponsive

### ISSUE THREAD

**Issue by steelbrain** [facebook/hhvm#5595]
```
<?hh
namespace libphonenumber{\/
  class PhoneNumber{

  }
  class PhoneNumberUtil{
    public static function getInstance():PhoneNumber;
    public static function isValidNumber(PhoneNumber):bool
  }
}
```
Paste the code above in a temp file, run `hh_client` and You'll see something like this with top
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 2726 steel     30  10 22.218g  71588   2296 R 100.0  0.9   0:13.08 hh_server
```

**Comment by Orvid** [comment]
I'm going to claim this is a parser issue, as I see 2 separate places where there should be syntax errors being triggered. The end of line 2, the `\/` is the first, and the end of line 8, `isValidNumber(PhoneNumber):bool`, which I would imagine needs at least a semicolon after the bool, is the second.

**Comment by jwatzman** [comment]
Yeah we've def had infinite loop issues in the parser before. Thanks for reporting, will take a look when I get a chance.

**Comment by jwatzman** [comment]
I have a diff up internally to fix -- this is due to a silly bug in an interaction between how we detect the end of namespaces and how we deal with syntax errors.
