### ISSUE TITLE
Repo Auth Mode - can't find hhvm-repo-auth

### ISSUE THREAD

**Issue by inssein** [facebook/hhvm#5600]
Over the weekend I got HHVM going with CentOs 7 + Nginx, and I am running a Symfony 2.3 application, however, it is not currently running is repo authoritative mode.

I read https://github.com/facebook/hhvm/wiki/Performance-Tuning, and in there it talks about a "hhvm-repo-auth" script, but I can't find the source for that anywhere. I wanted to port it over for my application.

Is there any other documentation / script available regarding the repo authoritative mode?

**Comment by fredemmott** [comment]
As documented, this is included in 3.8 onwards, which is the next release; you can grab it from the tree and run it with an earlier version.

**Comment by inssein** [comment]
@fredemmott I am actually running 3.8. I have actually looked at the master branch of the facebook/hhvm remo and hhvm/packaging. Would you mind pointing me to the right place please?

**Comment by fredemmott** [comment]
3.8 doesn't exist yet, however:

- https://github.com/facebook/hhvm/blob/master/hphp/tools/oss-repo-mode is what you want
- reopening as the documentation appears incorrect

**Comment by jwatzman** [comment]
The Debian packaging script copies it (and renames it to the name in the docs -- I thought `oss-repo-mode` was more useful in the repository, but not a good name for `/usr/bin`). If you aren't on Debian, you are probably using `make install`, which I think I forgot to add this to -- I'll do that. We are missing some stuff in `make install` in general, so I'll audit that while I'm at it.

**Comment by inssein** [comment]
thank you @fredemmott.

I have one quick question, and the answer seems obvious but I just want to be sure. With repo authoritative mode, you are only running one codebase per hhvm server right? (As in, running one php project per server).

**Comment by fredemmott** [comment]
yep

**Comment by jwatzman** [comment]
Well, depends on what you mean by "project"; it's possible to compile as much code as you want into a repo, including, for instance, both a WordPress and a Drupal site. But you only get the one repo, which is probably what you meant.

**Comment by inssein** [comment]
@jwatzman makes sense. Probably not a good idea from a system administration point of view to have two separate projects (a wordpress site and a drupal site) in the same repo, as updating one would have to re-generate the entire repo though, right?

I am having a lot of issues running my project in repo auth mode (currently it segfaults, previously it was unable to find files in composer autoloader, etc.) I will make a separate issue later with all the details.

**Comment by jwatzman** [comment]
> as updating one would have to re-generate the entire repo though, right?

Yep.
