### ISSUE TITLE
trigger_error(..., E_USER_ERROR) stops execution

### ISSUE THREAD

**Issue by nazar-pc** [facebook/hhvm#5605]
```php
trigger_error("Message", E_USER_ERROR);
```
Completely stops further code execution which is very different from original PHP5 implementation, which continues code execution after this.

**Comment by DerPapst** [comment]
E_USER_ERROR is a fatal error. For me code execution stops in PHP4 to 7 too.
http://3v4l.org/REn5u

**Comment by paulbiss** [comment]
Yeah, E_USER_ERROR should stop execution. http://3v4l.org/FW7mA
