### ISSUE TITLE
Can't run hack script without type checker

### ISSUE THREAD

**Issue by sgolemon** [facebook/hhvm#5612]
First, I try to run a file using the obvious syntax and am told to disable looking for the type checker.

```
$ hphp/hhvm/hhvm /tmp/hackfile.php

Fatal error: /tmp/hackfile.php appears to be a Hack file, but you do not appear to be running the Hack typechecker. See the documentation at http://docs.hhvm.com/manual/en/install.hack.bootstrapping.php for information on getting it running. You can also set Hack.Lang.LookForTypechecker=0 to disable this check (not recommended).
```

This does seem to get me further, but HHVM still wants an .hhconfig tag (though IMO it shouldn't)

```
$ hphp/hhvm/hhvm -vHack.Lang.LookForTypechecker=0 /tmp/hackfile.php

Catchable fatal error: Error: could not find a .hhconfig file in /tmp or any of its parent directories. Do you have a .hhconfig in your code's root directory?
```

Even with one, it then complains that the typechecker isn't running.

```
$ touch /tmp/.hhconfig
$ hphp/hhvm/hhvm -vHack.Lang.LookForTypechecker=0 /tmp/hackfile.php

Catchable fatal error: Hack typechecking failed: server not ready
```

:(

**Comment by jwatzman** [comment]
The first error message is correct though super misleading -- it does turn off that particular check, but doesn't turn off the typechecker invocation itself. These two options should probably be one and the same (though having the HHVM behavior of actually looking for the hhconfig is, I think, still useful).

As far as "server not ready", I thought I fixed that with a longer timeout -- though Kendall complained yesterday and there may be some recent issue with `hh_client` respecting timeouts and otherwise getting into an always-failed state, cc @int3.

**Comment by simonwelsh** [comment]
Just ran into this when trying to get one of our CLI jobs to always run (hh_client startup was timing out). Using `Hack.Lang.AutoTypecheck=0` made it not do the auto type check, so the CLI job no longer fatals due to timeouts.

**Comment by jwatzman** [comment]
@simonwelsh do you know why it was timing out? I'd expect `hh_server` to be up and running after the first -- was it not starting successfully? How long did it actually take to start up?

I am probably going to downgrade "server not ready" into a warning, if I can't find a nice solution to this.

**Comment by jwatzman** [comment]
Internal change D2270297 will make AutoTypecheck default to LookForTypechecker, which is probably what you want (and makes the error message more useful again). Still figuring out if we can do something clever about the timeouts, or if I need to downgrade to a warning.

**Comment by simonwelsh** [comment]
* It takes 5.4s to start up the first time
* The script that was failing was part of the setup process for our CI, so we need it to always pass (hh_client itself is then run later as part of the actual testing)

**Comment by jwatzman** [comment]
https://github.com/facebook/hhvm/commit/24798b1db19d358d973ca002ea2a12296bf4fbb1 changes the default, screwed up the commit message linking it here. D2274538 will downgrade "server not ready" to a warning.
