### ISSUE TITLE
hh_client incorrectly reports "Could not find method inTransaction in an object of type PDO"

### ISSUE THREAD

**Issue by cmbrownfield** [facebook/hhvm#5619]
Looks like [this commit](https://github.com/facebook/hhvm/commit/ae30d570745427b7ad7ac03f04002160dd891030) added "inTransaction" to the PDO object, but hh_client is still throwing errors for it's use.

**Comment by jwatzman** [comment]
Probably needs to get added to the relevant hhi file, feel free to send a PR, not sure when we'll get around to it otherwise.

**Comment by steelbrain** [comment]
Fixed by https://github.com/facebook/hhvm/commit/4eff7b6f23b0013746041b34f213c273abfdc25d

**Comment by jwatzman** [comment]
Thanks!
