### ISSUE TITLE
ubuntu 11.10 NOT find LIBINOTIFY

### ISSUE THREAD

**Issue by gujianghua5712** [facebook/hhvm#563]
I have a problem with compile HipHop

-- CMAKE_PREFIX_PATH was missing, proceeding anyway
-- Could NOT find LIBINOTIFY (missing:  LIBINOTIFY_LIBRARY LIBINOTIFY_INCLUDE_DIR) 
CMake Error at CMake/FindLibunwind.cmake:19 (message):
  libunwind.h found without matching unwind.h
Call Stack (most recent call first):
  CMake/HPHPFindLibs.cmake:38 (find_package)
  CMake/HPHPSetup.cmake:46 (include)
  src/CMakeLists.txt:18 (include)

*SE:
Thread model: posix
gcc version 4.6.1 (Ubuntu/Linaro 4.6.1-9ubuntu3) 
root@ubuntu:/export/servers/dev/hiphop-php# cd ..
root@ubuntu:/export/servers/dev# cd hiphop-php
root@ubuntu:/export/servers/dev/hiphop-php# sudo apt-get install git-core cmake g++ libboost-dev libmysqlclient-dev libxml2-dev libmcrypt-dev libicu-dev openssl build-essential binutils-dev libcap-dev libgd2-xpm-dev zlib1g-dev libtbb-dev libonig-dev libpcre3-dev autoconf libtool libcurl4-openssl-dev libboost-system-dev libboost-program-options-dev libboost-filesystem-dev wget memcached libreadline-dev libncurses-dev libmemcached-dev libbz2-dev libc-client2007e-dev php5-mcrypt php5-imagick libgoogle-perftools-dev libcloog-ppl0
Reading package lists... Done
Building dependency tree  
Reading state information... Done
Note, selecting 'libncurses5-dev' instead of 'libncurses-dev'
autoconf is already the newest version.
build-essential is already the newest version.
cmake is already the newest version.
g++ is already the newest version.
git-core is already the newest version.
libboost-dev is already the newest version.
libcap-dev is already the newest version.
libcloog-ppl0 is already the newest version.
libgd2-xpm-dev is already the newest version.
libmemcached-dev is already the newest version.
libncurses5-dev is already the newest version.
libpcre3-dev is already the newest version.
libreadline-dev is already the newest version.
libtool is already the newest version.
memcached is already the newest version.
wget is already the newest version.
zlib1g-dev is already the newest version.
libboost-filesystem-dev is already the newest version.
libboost-program-options-dev is already the newest version.
libboost-system-dev is already the newest version.
libc-client2007e-dev is already the newest version.
libgoogle-perftools-dev is already the newest version.
libmcrypt-dev is already the newest version.
libonig-dev is already the newest version.
libtbb-dev is already the newest version.
php5-imagick is already the newest version.
php5-mcrypt is already the newest version.
binutils-dev is already the newest version.
libbz2-dev is already the newest version.
libcurl4-openssl-dev is already the newest version.
libicu-dev is already the newest version.
libmysqlclient-dev is already the newest version.
libxml2-dev is already the newest version.
openssl is already the newest version.

How to fix this problem?

**Comment by ankitsablok89** [comment]
I tried building the hhvm using the procedure mentioned here - https://github.com/facebook/hhvm/wiki/Building-and-installing-HHVM-on-Ubuntu-14.04#building-hhvm
but as and when I run "cmake ." I get the following log:

I am building hhvm on a virtual machine the details of which are as follows -:

"Linux ubuntu 3.16.0-31-generic #43~14.04.1-Ubuntu SMP Tue Mar 10 20:13:38 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux"


asablok@ubuntu:~/Desktop/hhvm$ cmake .
-- Performing Test IS_X64
-- Performing Test IS_X64 - Success
-- Performing Test IS_AARCH64
-- Performing Test IS_AARCH64 - Failed
-- Performing Test IS_PPC64
-- Performing Test IS_PPC64 - Failed
-- Performing Test PTHREAD_TIMEDLOCK
-- Performing Test PTHREAD_TIMEDLOCK - Failed
-- Build type not specified: cmake build type Release.
-- Found LibDL: /usr/lib/x86_64-linux-gnu/libdl.so  
-- Performing Test LIBDL_NEEDS_UNDERSCORE
-- Performing Test LIBDL_NEEDS_UNDERSCORE - Failed
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   system
--   program_options
--   filesystem
-- Found LIBGLOG: /usr/lib/x86_64-linux-gnu/libglog.so  
-- Could NOT find LIBINOTIFY (missing:  LIBINOTIFY_LIBRARY) 
-- Could NOT find LIBICONV (missing:  LIBICONV_LIBRARY) 
-- Performing Test LIBICONV_CONST
-- Performing Test LIBICONV_CONST - Failed
CMake Error at CMake/HPHPFindLibs.cmake:86 (message):
  Could not find MySQL socket path - if you install a MySQL server, this
  should be automatically detected.  Alternatively, specify
  -DMYSQL_UNIX_SOCK_ADDR=/path/to/mysql.socket ; if you don't care about unix
  socket support for MySQL, specify -DMYSQL_UNIX_SOCK_ADDR=/dev/null
Call Stack (most recent call first):
  CMake/HPHPSetup.cmake:118 (include)
  third-party/CMakeLists.txt:18 (include)


-- Configuring incomplete, errors occurred!
See also "/home/asablok/Desktop/hhvm/CMakeFiles/CMakeOutput.log".
See also "/home/asablok/Desktop/hhvm/CMakeFiles/CMakeError.log".

Can somebody tell me as to what is the problem?

**Comment by vocalogic** [comment]
@ankitsablok89 Try putting this line before the cmake. This is what fixed it for me. 

 (optional) export LD_LIBRARY_PATH=/usr/local/lib64/
