### ISSUE TITLE
HHVM 3.8.0 fails if a PHP Script starts with the <?= -style echo tag

### ISSUE THREAD

**Issue by adrian-bl** [facebook/hhvm#5696]
I noticed that HHVM 3.8 fails to parse files that *start* with a ```<?=``` tag.

Example code:
```php
<?= (1+1) ?>
```

This code echos '2' in HHVM 3.7.2 and PHP (5.4.40) but fails on HHVM 3.8.0 with the following error message:

```
./hhvm-38 /tmp/test.php
Fatal error: syntax error, unexpected T_OPEN_TAG_WITH_ECHO, expecting $end in /tmp/test.php on line 1
```

HHVM 3.8 does *not* fail if the php file does not start with the ```<?=``` tag.
So these examples work just fine on hhvm 3.8:
```
<?php ?><?= (1+1) ?>
```
..or:
```
 <?= (1+1) ?>
```
(note the whitespace)

**Comment by Orvid** [comment]
I think there was a recent adjustment to how this was handled... Don't think it made it into 3.8 though...

**Comment by adrian-bl** [comment]
The binary was compiled using the HHVM-3.8 branchs HEAD a few hours ago:
```
./hhvm-38 --version
HipHop VM 3.8.1-dev (rel)
Compiler: heads/HHVM-3.8-0-gff62432c080a51d2bcd54dfcfe9aca81bba758a8
Repo schema: 57d3d7404b0fae47066d233aba33a64e9a198635
```
(= https://github.com/facebook/hhvm/commit/ff62432c080a51d2bcd54dfcfe9aca81bba758a8)

**Comment by keiosweb** [comment]
We can confirm this problem, HHVM 3.8.0 (rel).
File with contents:

    <?= $this->makePartial('warnings') ?>

crashes with: 

    Fatal error: syntax error, unexpected T_OPEN_TAG_WITH_ECHO, expecting $end in /path/to/some/view/file.php on line 1

**Comment by LeonB** [comment]
Same issue here. When upgrading hhvm a file stopped working that worked with hhvm 3.7

**Comment by AngeloG** [comment]
Would love to see this fixed.

**Comment by Orvid** [comment]
I believe this is a regression introduced by #5028, specifically [this change](https://github.com/facebook/hhvm/pull/5028/files#diff-e492acfd187fc619ea60de323af8a3acR845). I believe handling `T_OPEN_TAG_WITH_ECHO` [here in the parser](https://github.com/facebook/hhvm/blob/master/hphp/parser/hphp.y#L938) should fix this, but I don't currently have the ability to regenerate the parser.

**Comment by keiosweb** [comment]
In which future version could we can expect this to be fixed? We waited for 3.8.0 because of https://github.com/facebook/hhvm/issues/1647 and we can't move to it because of this issue.

**Comment by fredemmott** [comment]
I'll start digging. cc @noony

**Comment by fredemmott** [comment]
Cause: https://github.com/facebook/hhvm/commit/d181ac0d8d9878122be1b96ae7c9d889a3b07e85

Fix (FB: D2282645):

```
diff --git a/hphp/parser/hphp.y b/hphp/parser/hphp.y
index be54ee3..bdbfd60 100644
--- a/hphp/parser/hphp.y
+++ b/hphp/parser/hphp.y
@@ -936,6 +936,7 @@ statement:
   | T_GLOBAL global_var_list ';'       { _p->onGlobal($$, $2);}
   | T_STATIC static_var_list ';'       { _p->onStatic($$, $2);}
   | T_ECHO expr_list ';'               { _p->onEcho($$, $2, 0);}
+  | T_OPEN_TAG_WITH_ECHO expr_list ';' { _p->onEcho($$, $2, 0);}
   | T_UNSET '(' variable_list ')' ';'  { _p->onUnset($$, $3);}
   | ';'                                { $$.reset(); $$ = ';';}
   | T_INLINE_HTML                      { _p->onEcho($$, $1, 1);}
diff --git a/hphp/test/quick/open_tag_with_echo.php b/hphp/test/quick/open_tag_with_echo.php
new file mode 100644
index 0000000..2da945e
--- /dev/null
+++ b/hphp/test/quick/open_tag_with_echo.php
@@ -0,0 +1 @@
+<?= "hello, world\n" ?>
diff --git a/hphp/test/quick/open_tag_with_echo.php.expect b/hphp/test/quick/open_tag_with_echo.php.expect
new file mode 100644
index 0000000..4b5fa63
--- /dev/null
+++ b/hphp/test/quick/open_tag_with_echo.php.expect
@@ -0,0 +1 @@
+hello, world
```

Parser needs regenerating after that change.

**Comment by fredemmott** [comment]
@keiosweb : if I've not missed something in my fix, this should be in 3.9.0 and 3.8.1

**Comment by keiosweb** [comment]
Great, thanks :+1:

**Comment by AngeloG** [comment]
Nice! Thank you guys. :)

**Comment by tim-bezhashvyly** [comment]
Thanks a lot.
