### ISSUE TITLE
hh_format is over-aggressive at removing whitespace from literal string children in XHP

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#5710]
- clone github.com/hhvm/xhp-lib
- run hh_format tests/
- BasicsTest::testDivWithString() now fails:

```
   public function testDivWithString() {
-    $xhp =
-      <div>
-        Hello, world.
-      </div>;
+    $xhp = <div>Hello, world.</div>;
     $this->assertEquals('<div> Hello, world. </div>', $xhp->toString());
```

Any non-zero amount of whitespace can be reduced to a single space, but it can not be removed completely without changing the meaning.

**Comment by steelbrain** [comment]
Bump. This issue really takes quite a lot of time to debug, I have to embed `&nbsp;` manually to fix this.

**Comment by Orvid** [comment]
Well, the general area where this is handled in the formatter is [format_hack.ml:1832](https://github.com/facebook/hhvm/blob/master/hphp/hack/src/format/format_hack.ml#L1832). It is however possible that the Hack typechecker is lexing the body of the elements incorrectly. As I don't know OCaml, and I don't have any way to actually check if any fix I attempt works, I can't do much more than point in a possible general direction.

**Comment by int3** [comment]
Hmm, this is tricky. We have a similar issue with breaking long XHP lines:

`<a>a_very_long_string</a>` gets converted to
```
<a>
  a_very_long_string
</a>
```

adding potentially significant whitespace in the process. However, it seems like the only reasonable way of fitting things into 80 columns. So from that angle it seems reasonable to remove the leading/trailing spaces when fitting things onto one line.

That said, I agree that doing this silently is pretty clowny since it potentially creates bugs. The best UX I can think of right now is to emit warnings whenever we do these changes. Thoughts?

**Comment by fredemmott** [comment]
My preference would be to ignore 80 cols if it potentially requires semantic changes. If a linter is running, that can highlight it for manual fixup.

What's the hh_format workflow if a warning were added? It sounds like this would make a 'hh_format is a no-op' commit check impossible - and manually running 'hh_format $(pwd)/src/' would require manual review and partial revert on every commit?

**Comment by Orvid** [comment]
I'll agree with fredemmott here, and say that ignoring the 80-col restriction if it potentially requires semantic changes would be the best way to do it, and let a linter handle notifying the user if that is the case. Emitting a warning might be viable, as long as it is possible to disable the warning. I do believe though that the best course of action, even if a warning were added, would be to not make the change at all if it potentially makes semantic changes.

**Comment by fredemmott** [comment]
Closing because hh_format is now unsupported, and hackfmt is fine:

```
fredemmott-mbp1:xhp-lib fredemmott$ find src/ tests/ -name '*.php' | xargs -n1 hackfmt -i
fredemmott-mbp1:xhp-lib fredemmott$ hh_client
No errors!
fredemmott-mbp1:xhp-lib fredemmott$ hhvm vendor/bin/phpunit tests/
PHPUnit 5.7.13 by Sebastian Bergmann and contributors.

...............................................................  63 / 120 ( 52%)
.........................................................       120 / 120 (100%)

Time: 4.21 seconds, Memory: 0.69MB

OK (120 tests, 186 assertions)
```
