### ISSUE TITLE
Multithreading context issue

### ISSUE THREAD

**Issue by vbudhya** [facebook/hhvm#5711]
Hello,

Let me thank you guys for such an excellent work you done on HHVM.

My Task -
I am writing a HHVM extension basically it is the wrapper above the c Library(.so)

Overview of problem I am facing -

I am using c *.so for creating a threads needed for my task, What I observed is when I am creating threads using c .so at that time context of main thread and other threads are different, At some extent it is true but at least they should have a common access to global things that i don't see. While creating threads I have a start thread method that is in c .so only and doesn't have any info related to HHVM. Here what i am trying to say is, Is there any HHVM APIs need to get called when I am creating threads using that c .so to share the global data.

1) When I am accessing g_context(global context variable) in newly created threads then I can see it is NULL, But I think It should have some value copied from the first thread. Even if I just tried to create a String object in the new thread, getting below error,

hhvm: /home/vishal/hhvm-dev/hhvm/hphp/util/thread-local.h:289: static T* HPHP::ThreadLocalSingleton<T>::getNoCheck() [with T = HPHP::MemoryManager]: Assertion `s_singleton == (T*)&s_storage' failed.

2) For above problem if I call the below API, It is allowing me to create a String objects as memory is getting allocated by it,

MemoryManager::TlsWrapper::getCheck();

3) But my purpose is not only creating the string objects but I want to call "vm_call_user_func()" for callback(Calling a PHP callback function from new thread). HHVM is generating a core for same. then I checked that function using is_callable() but it is showing that funtion is not callable. Here I realized that this is the issue related to context of the threads because the same function was callable and getting called from main thread(First thread created by HHVM).

4) For above problem, After going through the HHVM code I came across the hphp_session_init() API(which is getting called for a HHVM first thread) who is initializing the g_context and Memory allocation mentioned in point 2, This API is allowing me to call vm_call_user_func() on PHP funtion also. My work is done.

So here is the summary of problems I faced in HHVM and related solutions I find for those problems.

***** What I expect from you guys?

1) Is this correct to call hphp_session_init() when I create new threads using other c .so? If not Do you provide any other API to do so?
2) Why I am asking above question because I can find many memory leaks in HHVM after adding hphp_session_init() function call even if I am calling this only when g_context is NULL,

        if (g_context.isNull()) {
            hphp_session_init();
        }

3) If what I am doing above is correct then is there any API i need to call to free the memory allocated by the new threads created using c .so?

Let me thank you in advance for your quick response as always and let me know if you need any more information related to what i am trying to do.

Thanks,
Vishal

**Comment by paulbiss** [comment]
g_context is thread local, calling `init_thread_locals()` should initialize it, but it sounds like you want to create strings in one thread and use them in a different (request) thread (which this won't allow you to do). In that case you'll need the g_context from the original thread (note that by-in-large g_conext and other request data isn't atomic and using it in two threads is asking for trouble).

**Comment by vbudhya** [comment]
Thanks for response.

I have few followup questions,
1) any comments on using hphp_session_init()?
2) How can I get g_context from original thread?
3) ignoring the sharing for strings between threads, I am creating the String object in new thread then also it is giving me below error,

hhvm: /home/vishal/hhvm-dev/hhvm/hphp/util/thread-local.h:289: static T* HPHP::ThreadLocalSingleton::getNoCheck() [with T = HPHP::MemoryManager]: Assertion `s_singleton == (T*)&s_storage' failed


Thanks,
Vishal

**Comment by paulbiss** [comment]
1) Probably not what you want to do if you're making a string in thread A and using it in thread B it needs to be in the same request heap (so made with the same g_context).
2) You could pass a pointer into the thread when you create it.
3) The problem is that operating on the request heap itself isn't threadsafe so just creating the string may cause concurrency issues. You probably don't want to pass around request local strings, maybe consider using a static string or an uncounted string instead and ignore the g_conext issue entirely?

**Comment by vbudhya** [comment]
Thanks,

2) Fine
3) Fine

Continuing on point 1)
Below is thread info of my HHVM process,

  2    Thread 0x7fffe07ff700 (LWP 8759) "hhvm" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
* 1    Thread 0x7ffff7fc07c0 (LWP 8758) "hhvm" HPHP::c_Example_ni_rec (this_=0x7fffe540ae30, php_rec=..., options=...)

Above thread 1 is created by HHVM at start and then thread 2 is created by c .so file which is used by my HHVM extension only when required.

Here in thread 1, I am receiving a function object(PHP function) and if I call vm_call_user_func(function_object, args) in thread 1 then I am able to call a PHP function from my extension. But if I passed that function object to thread 2 and try to call vm_call_user_func() there then I am getting a core dump. Even I tried to check is_callable before calling a function it returns false.

Do I need to call any extra AIPs to make it work.

bool callback(void *func)
{
    init_thread_locals();
    Callback *callback = (Callback *)func;

    Array php_record = Array::Create();
    Variant ret = vm_call_user_func(callback->function, php_record); //Here core is getting generated
	return true;
}

Above function is getting called in thread 2 context.


Thanks,
Vishal

**Comment by paulbiss** [comment]
You really shouldn't be interacting with the VM in non-request threads, it's basically guaranteed to cause grief since most of that context isn't designed to be shared between threads. If you have a worker thread you should have it send whatever context it needs to the request thread and then let the request thread handle interacting with the VM.

**Comment by vbudhya** [comment]
My understanding is that you are suggesting me to interact with VM using thread 1(from last comment) only??

But here my concern is, thread 1 has called a c library function and that is a blocking call. So here I don't have a request thread to interact with the VM unless I am done with the worker thread(Thread 2) i.e a PHP callback using vm_call_user_func().

Is that the only valid possible way to call a PHP callback function using vm_call_user_func() only from a request thread(thread 1) and not from worker thread(thread 2)??

Thanks,
Vishal

**Comment by fredemmott** [comment]
All PHP code must execute in the thread for that request. One way to work with this is to use Hack's async support - for example, take a look at the implementation of curl_multi_await() - for an example use, see HH\Asio\curl_exec())

**Comment by paulbiss** [comment]
If the request thread is in a blocked state it may be possible to interact with the VM in another thread but it's still very much not recommended, and calling a function is still unlikely to work properly. It sounds to me like there may be some issues with the way you've architected your extension. If you want to find us on Freenode (#hhvm-dev) we'd be happy to discuss extension design or look at some of your code and offer general advice.

**Comment by vbudhya** [comment]
ya sure thanks.

Let me make it as per the standard as suggested by you. I will make the required changes and let request thread to communicate with the VM in all cases as it is possible but need some changes to be done. I will make those changes first and test the extension for all scenarios and will let you know the result.


Thanks,
Vishal.
