### ISSUE TITLE
hh_server consumes 800MB of RAM even on small projects

### ISSUE THREAD

**Issue by infusion** [facebook/hhvm#5712]
Hi,

after upgrading HHVM via apt-get I get this strace output:

    [pid 23640] access("/tmp/hh_server/stamp", F_OK) = -1 ENOENT (No such file or directory)
    [pid 23640] stat("/tmp/hh_server/stamp", 0x7feef69f9f30) = -1 ENOENT (No such file or directory)
    [pid 23640] write(5, "\\nCatchable fatal error: Hack typechecking failed: server not ready\n", 68) = 68
    [pid 23640] write(9, "\1\0\0\0\0\0\0\0", 8) = 8

/tmp/hh_server exists with the right permissions. Is there something I can do or is this a bug?

Thanks Robert

**Comment by jwatzman** [comment]
The server should start up in 2-3 seconds -- does it? (i.e., does the error go away?)

**Comment by infusion** [comment]
There is no problem with the start up process, the server runs perfectly. I get this behavior while serving a page. I think I could narrow down the problem to hack. Whenever I use the <?hh tag in either auto_prepend_file (which I disabled for the test here) or a normal file served via fcgi, I get an error related to the stamp file.

I'm running on heads/master-0-gb1dec0bd2b938659d32527e9e292e09ec05193ae on a debian8 atm, after having the same trouble with the stable release. (installed with apt-get install hhvm-nightly)

Actually, I get this problem also when I just use this simple script:

    <?php
    phpinfo();

and change it to

    <?hh
    phpinfo();

Here a new strace: 
```
[pid  9391] stat("/www/dev/index.hh", {st_mode=S_IFREG|0644, st_size=18, ...}) = 0
[pid  9391] access("/tmp/hh_server/stamp", F_OK) = -1 ENOENT (No such file or directory)
[pid  9391] stat("/tmp/hh_server/stamp", 0x7fb73fdf9c70) = -1 ENOENT (No such file or directory)
[pid  9391] write(5, "\\nCatchable fatal error: Server launched with the following command: \\t'hh_server' -d '/www/dev'  --waiting-client 9395 Spawned hh_server (child pid=9398) Logs will go to /tmp/hh_server/zSwwwzSdev.log hh_server still initializing. This can take some time. Retrying... - Error: hh_client hit timeout, giving up! in /www/dev/index.hh on line 3\n", 343) = 343
```

Contents of `/tmp/hh_server/zSwwwzSdev.log`:
```
[2015-07-18 10:42:13] Initializing Server (This might take some time)
[2015-07-18 10:42:13] Parsing ... 0.258364
[2015-07-18 10:42:14] Heap size: 1999168
[2015-07-18 10:42:14] Naming ... 0.006633
[2015-07-18 10:42:14] Type-decl ... 0.883126
[2015-07-18 10:42:15] Heap size: 4994688
[2015-07-18 10:42:15] Type-check ... 0.202912
```

And this initialization is not finished after 2-3sec, it even doesn't work after minutes/hours. In /www/dev are only 4+1 hhconfig files, so I think creating the index should be reasonable fast:

```
> l /www/dev                                                                     
total 20K
drwxr-xr-x 2 root   root   4,0K Jul 18 10:41 .
drwxr-xr-x 5 master master 4,0K Jul 18 10:50 ..
-rw-r--r-- 1 root   root      8 Jul 18 10:36 global.hh
-rw-r--r-- 1 root   root      0 Jul 18 10:41 .hhconfig
-rw-r--r-- 1 root   root     18 Jul 18 10:40 index.hh
-rw-r--r-- 1 root   root     27 Jul 18 10:36 index.php
```

When I run hh_client manually, I see the same output as in the strace, and it restarts over and over again:

```
> hh_client                                                                                                                           
Server launched with the following command:
	'hh_server' -d '/www/dev'  --waiting-client 11171
Spawned hh_server (child pid=11174)
Logs will go to /tmp/hh_server/zSwwwzSdev.log
Server launched with the following command:
	'hh_server' -d '/www/dev'  --waiting-client 11171
Spawned hh_server (child pid=11343)
Logs will go to /tmp/hh_server/zSwwwzSdev.log
Server launched with the following command:
	'hh_server' -d '/www/dev'  --waiting-client 11171
Spawned hh_server (child pid=11505)
Logs will go to /tmp/hh_server/zSwwwzSdev.log
Server launched with the following command:
	'hh_server' -d '/www/dev'  --waiting-client 11171
Spawned hh_server (child pid=11667)
Logs will go to /tmp/hh_server/zSwwwzSdev.log
Server launched with the following command:
	'hh_server' -d '/www/dev'  --waiting-client 11171
Spawned hh_server (child pid=11861)
Logs will go to /tmp/hh_server/zSwwwzSdev.log
hh_server still initializing. This can take some time. Retrying... -^C
```

**Comment by jwatzman** [comment]
Does `/tmp/hh_server` exist and is writable (by both you and HHVM)? `hh_server` is supposed to create it, and `/tmp/hh_server/zSwwwzSdev.sock`, on startup. What are its permissions?

**Comment by infusion** [comment]
yep, the directory exists and has the right permissions:

```
> l /tmp/hh_server                                                                                                                                                                      
insgesamt 20K
drwxrwxrwx  3 hhvm hhvm 4,0K Jul 21 16:04 .
drwxrwxrwt 12 root   root   4,0K Jul 21 16:08 ..
drwxr-xr-x  6 hhvm hhvm 4,0K Jul 21 10:00 hhi_1139c516
-rw-rw-rw-  1 hhvm hhvm    0 Jul 21 16:04 zSwwwzSdev.init
-rw-rw-rw-  1 hhvm hhvm    0 Jul 21 16:04 zSwwwzSdev.lock
-rw-rw-rw-  1 hhvm hhvm  328 Jul 21 16:04 zSwwwzSdev.log
-rw-rw-rw-  1 hhvm hhvm   24 Jul 21 16:04 zSwwwzSdev.pids
```

I also removed /tmp/hh_server and re-installed hhvm like:

apt-get remove hhvm-nightly
apt-get install hhvm-nightly

with no effect, though...

**Comment by jwatzman** [comment]
Can you do `hh_server --check /www/dev` and paste the output here?

**Comment by infusion** [comment]
> hh_server --check /www/dev            
[2015-07-21 22:50:49] Parsing ... 0.141139
[2015-07-21 22:50:49] Heap size: 1999168
[2015-07-21 22:50:49] Naming ... 0.006418
[2015-07-21 22:50:49] Type-decl ... 0.111515
[2015-07-21 22:50:49] Heap size: 4994688
[2015-07-21 22:50:49] Type-check ... 0.090241
[1]    7034 killed     hh_server --check /www/dev

**Comment by jwatzman** [comment]
OK, that "killed" is weird, and the same problem as #5738. Here's my suggestion on that task, can you do the same?

Can you try to figure out why it was killed? Maybe run `hh_server --check /www/dev` and, if it gets killed again, do `dmesg | tail -n 50` and see what's there (paste it here if you're comfortable) -- in particular, looking for things from the OOM killer.

How much RAM does this system have total, and how much is free? Does running `gdb --args hh_server --check /www/dev` give any more useful information on why it was killed?

**Comment by infusion** [comment]
Ha, I think you asked the right question...The system is quite undersized with 384mb ram in total, which leads to the following dmesg output:

[16185749.307683] Out of memory in UB 131: OOM killed process 7180 (hh_server) score 9 vm:23288428kB, rss:6420kB, swap:0kB
[16185749.313677] Out of memory in UB 131: OOM killed process 7034 (hh_server) score 0 vm:23265464kB, rss:332756kB, swap:0kB
[16186755.912925] Out of memory in UB 131: OOM killed process 7542 (hh_server) score 9 vm:23288428kB, rss:6408kB, swap:0kB
[16186755.921182] Out of memory in UB 131: OOM killed process 7396 (hh_server) score 0 vm:23265464kB, rss:332740kB, swap:0kB

Is there a way to reduce the memory consumption?

**Comment by jwatzman** [comment]
There are a couple of folks running into this. If you're writing Hack code, you need a system which can run the typechecker -- a modern laptop should be fine. If your code does not pass `hh_client`, then the behavior when running on HHVM is undefined. Unfortunately peak memory usage seems to be a few hundred MB, which precludes it running on the small production servers you have.

While I question the wisdom of using such an undersized server, there is an option you can set in HHVM to turn off this auto-typechecking, which will leave it up to you to manually run `hh_client` and make sure it reports "No errors!" -- the INI option is `hhvm.hack.lang.auto_typecheck=false`. If you set that, then HHVM won't try to call `hh_client` anymore.

I'm going to separately look into reducing memory consumption of `hh_server`, I think there are a couple of easy wins, but it will only drop it down to 100-200MB, which is still probably not small enough for you.

**Comment by Orvid** [comment]
It might be worth adding a check for available system memory and producing a warning at the very least in the log file if there isn't a reasonable amount of memory available.

**Comment by jwatzman** [comment]
We've been having similar OOM problems at FB too... it turns out determining "available system memory" is a really tricky thing to pin down.

**Comment by jwatzman** [comment]
Internal diff (D2266342) is up to try to help out with this

**Comment by infusion** [comment]
100-200mb would be perfect. The thing is, it consumes that much memory not only on "small projects" but also on a simple hello world file, which doesn't make hhvm the best fit for cronjobs when memory consumption spikes that much - especially if some of such jobs should work in parallel.

The server where I'm running this code on is not production, but a small dev-VM. Turning the typechecker off, as you suggested, worked like a charm. Thanks for that.

**Comment by jwatzman** [comment]
Mmm yeah, the hhi files we load by default would almost certainly bump up the dep table (the culprit for a lot of the unnecessary RAM usage) enough to be noticeable. The linked diff should help when it's out -- I'll try to merge it into 3.8.1.

**Comment by jwatzman** [comment]
Diff landed -- can you try tomorrow's nightly build (dated 2015-07-23 or later) and see if it helps?

**Comment by infusion** [comment]
Okay, I just tried the new nightly build and must say that it still doesn't work on my VM with 384M. If you've seen improvement with your change then it's just fine. As I said this box is just for development and as long as I can turn off the type checker I can work with it. The production system is proper sized and it works there without any problems.

What you could do, though, is turning off the type-checker if the system has not enough memory. Simply reading /proc/meminfo should do the job. Poor performance is better than not working at all, or even "crashing". A notice in the logfile and it should be fine.

**Comment by jwatzman** [comment]
Unfortunately the amount of memory we need is an extremely complicated function of your code size, and the amount of free memory remaining is also a complicated concept. (And `/proc/meminfo` isn't portable beyond Linux.)

I'm going to close this as fixed, since the usage is dramatically reduced; sorry it still doesn't fit in 384M, but honestly I bet HHVM is going to run up against those limits before too long too. You were definitely intended to be able to turn this off, but how to do so ended up pretty buried -- #5612 is tracking some changes to defaults and error message wording to make that smoother.

**Comment by infusion** [comment]
Thanks for mentioning #5612.

**Comment by fredemmott** [comment]
`As I said this box is just for development and as long as I can turn off the type checker I can work with it. The production system is proper sized and it works there without any problems.`

As a side note, this is pretty much the opposite to how Hack should be used - the typechecker should be running on development and CI systems, but doesn't matter so much in production; it's not even possible to use it with repo-auth mode.
