### ISSUE TITLE
Cannot access docs.hhvm.com and dl.hhvm.com

### ISSUE THREAD

**Issue by parhamdoustdar** [facebook/hhvm#5713]
I know this is unrelated to the HHVM project, but I could not find anywhere else to report this. If there's a better place for this, please direct me to it.

I cannot access `dl.hhvm.com` and `docs.hhvm.com` from Iran. Using a VPN/proxy works, but without it, I can only open `hhvm.com`.

**Comment by jwatzman** [comment]
Eh this is a good as place as any to report.

What happens when you try to access them? Where does it fail?

- Does the DNS resolve?
- Can you ping them?
- What does the traceroute look like?
- Can you establish a TCP connection?
- What about an HTTP GET?

**Comment by parhamdoustdar** [comment]
Thanks for your questions! They led me to the solution!

The Iranian DNS servers cannot resolve `docs.hhvm.com` and `dl.hhvm.com` for some reason. I switched to using `8.8.8.8` and that did it.

Sorry for taking your time.

**Comment by jwatzman** [comment]
np, glad you got it sorted. I don't know much about DNS or networking, but that sounds like the sort of thing we have no control over. If there's anything you think we could do or investigate on our end, let us know.
