### ISSUE TITLE
Left bit shift in global scope reports hack error in decl mode.

### ISSUE THREAD

**Issue by TJ09** [facebook/hhvm#5716]
This is an oddly-specific case, but for whatever reason, doing a left bit shift in the global scope reports a hack error, but only in decl mode (right bit shift is fine). See the following code:

``` php
<?hh // decl

// No error, decl doesn't look inside function bodies.
function test($y) {
  (1 << $y);
}

// test.php:9:7,8: Expected attribute name (Parsing[1002])
(1 << $y);
```

outside of `// decl`, hh_client reports no errors:

``` php
<?hh

// No error
function test($y) {
  (1 << $y);
}

// No error
(1 << $y);
```

This occurs on both HHVM 3.7 and 3.8.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Decl mode has been removed from hhvm in 4.x.0, but I can't find the exact version.

Modern versions of hhvm report:
```
Parsing[1002] Incorrect comment; possible values include strict, partial, or empty
   --> file.php
  1 | <?hh // decl
    | ^^^^^^^^^^^^

1 error found.
```
