### ISSUE TITLE
ARM codegen is included in all builds

### ISSUE THREAD

**Issue by Orvid** [facebook/hhvm#5729]
Currently the ARM codegen is included in all builds, totaling, for me on windows, without debug info, ~10mb in objects exclusively for ARM codegen. There is also the 10mb vixl library that is needed for ARM codegen. I believe it should be possible to reduce the final size of the HHVM binary by anywhere from 1-5mb by excluding ARM support from the normal build.

I propose that it be made possible to select ARM, x64, or both,  codegen at compile time. Although I don't see why you'd need both, I see no reason to prevent it, as that's how it's been up until now.

Once I get a build of HHVM that links correctly on MSVC (shouldn't be too much longer, I've dealt with the external library's issues, just have to deal with the last 8 or so unresolved symbols in HHVM itself due to ASM stubs), I intend to set this up.

**Comment by edwinsmith** [comment]
cc @mxw

**Comment by gut** [comment]
bump. I'm also interested on this decision as I'm working on a powerpc port. I'd like to avoid x64 and arm compilation units but I'm not sure if HHVM has something against it.

**Comment by edwinsmith** [comment]
I don't have anything against having cmake options to disable arm/x64 when compiling natively on ppc. (or generally, options to only enable target X when compiling on X).

vixl is kind of a special case, to enable simulating arm when compiling on non-arm hosts (the non-arm host shouldn't have to be x64, but if it makes the work easier, it's fine to make vixl depend on x64).

**Comment by gut** [comment]
I thought about enabling arm on cmake when IS_AARCH64 is true. Is `__AARCH64EL__` defined when arm is being simulated on x64?

**Comment by Orvid** [comment]
I believe it would be better to use a custom set of defines for enabling architectures. `ENABLE_JIT_X64`, `ENABLE_JIT_ARM`, `ENABLE_JIT_ARM_EMUL`, etc. That assumes though that the emulation is separately disable-able.

**Comment by edwinsmith** [comment]
I don't think so; it's just our normal x64 build with a runtime flag to generate arm code and simulate it using vixl. The runtime is still all x64.

**Comment by gut** [comment]
Got it. So as there is no ARM-only build version of HHVM, I'll consider it as a part of the X64 build.
Thanks for the clarification.
