### ISSUE TITLE
Fatal error: Windows-1252 is not implemented yet.

### ISSUE THREAD

**Issue by craigjbass** [facebook/hhvm#5732]
* http://dev.mysql.com/doc/refman/5.6/en/charset-we-sets.html

Windows-1252 / cp1252 is the same as MySQL's latin1. Without this support things like the very common € sign do not render correctly if using the IANA latin1 charset.

**Comment by Orvid** [comment]
Where in HHVM is that character set not implemented?

**Comment by Orvid** [comment]
This issue has been waiting for more info for more than 2 weeks. Closing for now, feel free to re-open it if you can provide more info.

https://github.com/facebook/hhvm/wiki/Human-Timeouts
