### ISSUE TITLE
Hackificator could auto-add missing visibility

### ISSUE THREAD

**Issue by jazzdan** [facebook/hhvm#5734]
Hey all,

It would be cool if the Hackificator could auto-add visibility to functions that don't specify it, like so

```php
- function foo() {
+ public function foo() {
    echo 'Derp';
}
```

This would eliminate a whole class of errors that we encounter later on during a conversion to Hack. (And also make the world a better place!)

**Comment by jwatzman** [comment]
We discussed this on IRC and the hackificator does this properly, correct?
