### ISSUE TITLE
Hack typechecking failed: server not ready

### ISSUE THREAD

**Issue by nathandavies91** [facebook/hhvm#5738]
Hi,

Since I upgraded to 3.8.0-trusty, I appear to be getting the following issue:

```
Catchable fatal error: Hack typechecking failed: server not ready
```

Running with hh_client, this appears to be making several requests before reaching its' limit and 'giving up'..

```
Server launched with the following command:
	'hh_server' -d '/path/to/project'  --waiting-client XXXX
Spawned hh_server (child pid=XXXX)
```

With `hh_server -d '/path/to/project'` it does inform me that the .hhconfig file cannot be found, despite this existing in the parent folder; from what I can see, this is allowed: http://docs.hhvm.com/manual/en/install.hack.bootstrapping.php

```
Error: could not find a .hhconfig file in /path/to/project or any of its parent directories.
Do you have a .hhconfig in your code's root directory?
```

If I do include an empty .hhconfig file in the /path/to/project code root, then no errors are apparent, but the site is still inaccessible.

```
Spawned hh_server (child pid=XXXX)
```

Any assistance would be greatly appreciated.
If there's anything I can do to assist with this issue, just let me know.

---

May be similar to issues #5406 and #5612

**Comment by jwatzman** [comment]
I'll look into this on Monday -- there's likely some more info I'll need, but it's too late on a Friday night for me to get it together what that is :)

**Comment by jwatzman** [comment]
Can you do the following and paste the output?

```
ls -al /path/to/project
killall -9 hh_server
hh_server --version
hh_client --version
hh_server --check /path/to/project
cd /path/to/project && hh_client
```

**Comment by nathandavies91** [comment]
**ls -al /path/to/project**

```
drwxrwxr-x  2 nathandavies www 4096 Jul 21 19:15 .
drwxrwx--- 11 nathandavies www     4096 Jul 21 19:14 ..
-rw-r--r--  1 nathandavies         www            1 Jul 21 19:15 .hhconfig
-rw-r--r--  1 nathandavies         www           35 Jul 21 19:15 index.hh
```

.hhconfig file is empty.
index.hh includes a simple test at the moment `<?hh echo "Hello world!";`.

**killall -9 hh_server**

```
hh_server: no process found
```
Strange...

**hh_server --version**

```
bb32f8d645b28561d8491870c44730b9b3f08d35 Jul 13 2015 11:56:03
```

**hh_client --version**

```
bb32f8d645b28561d8491870c44730b9b3f08d35 Jul 13 2015 11:56:03
```

**hh_server --check /path/to/project**

```
[2015-07-21 18:46:06] Parsing ... 0.213178
[2015-07-21 18:46:06] Heap size: 1764544
[2015-07-21 18:46:06] Naming ... 0.008917
[2015-07-21 18:46:06] Type-decl ... 0.206726
[2015-07-21 18:46:07] Heap size: 4431808
[2015-07-21 18:46:07] Type-check ... 0.143477
Killed
```

**cd /path/to/project && hh_client**

```
Server launched with the following command:
	'hh_server' -d '/path/to/project'  --waiting-client 5014
Spawned hh_server (child pid=16344)
Server launched with the following command:
	'hh_server' -d '/path/to/project'  --waiting-client 5014
Spawned hh_server (child pid=16481)
...
hh_server is busy, retrying... -
Error: Ran out of retries, giving up!
```

This went on for about 20 minutes before fastcgi become unresponsive and started throwing `502 Bad Gateway`, and took around 25 minutes before giving up completely.

**hhvm /path/to/project/index.hh**

```
Catchable fatal error: Hack typechecking failed: server not ready
```

---

**Further details:**

- Ubuntu 14.04.2 LTS (GNU/Linux 3.13.0-32-generic x86_64) [[Supported]](https://github.com/facebook/hhvm/wiki/Prebuilt-Packages-for-HHVM)
- [Hosted using Digital Ocean's basic package](https://www.digitalocean.com/pricing?refcode=7b17e5dc30e5)

I have had sites running on the previous version without issue. I also tried purging the set up, and reinstalling from fresh.

Hope that helps. :)

**Comment by nathandavies91** [comment]
The issue #5712 also seems remarkably similar, apologise I missed that.

---

Looking at your comments on that issue, I can add that:

> Does `/tmp/hh_server` exist and is writable (by both you and HHVM)? `hh_server` is supposed to create it, and `/tmp/hh_server/zSwwwzSdev.sock`, on startup. What are its permissions?

/tmp/hh_server/ exists, but there are no .sock files in that directory. Permissions are set to `-rw-rw-rw-`.

Server.ini has been configured with the following:
```
hhvm.server.file_socket = /var/run/hhvm/sock
hhvm.server.type = fastcgi
```

While `/var/run/hhvm/sock` exists; trying to read it results in `Error reading sock: No such device or address`.

**Comment by jwatzman** [comment]
```
$ hh_server --check /path/to/project
[2015-07-21 18:46:06] Parsing ... 0.213178
[2015-07-21 18:46:06] Heap size: 1764544
[2015-07-21 18:46:06] Naming ... 0.008917
[2015-07-21 18:46:06] Type-decl ... 0.206726
[2015-07-21 18:46:07] Heap size: 4431808
[2015-07-21 18:46:07] Type-check ... 0.143477
Killed
```

That's incredibly weird and very likely the source of the problem -- can you try to figure out why it was killed? Maybe run `hh_server --check /path/to/project` and, if it gets killed again, do `dmesg | tail -n 50` and see what's there (paste it here if you're comfortable) -- in particular, looking for things from the OOM killer.

How much RAM does this system have total, and how much is free? Does running `gdb --args hh_server --check /path/to/project` give any more useful information on why it was killed?

**Comment by nathandavies91** [comment]
So `dmesg | tail -n 50` noticeably returns:

```
[  268.816272] [ 1575]  1000  1575  5815550    90234     256        0             0 hh_server
[  268.816273] Out of memory: Kill process 1575 (hh_server) score 721 or sacrifice child
[  268.816322] Killed process 1575 (hh_server) total-vm:23262200kB, anon-rss:40216kB, file-rss:320720kB
```

This is a significant increase on the last version.
My server is 512Mb.

**Comment by jwatzman** [comment]
Cool, same problem as #5712, going to close this out and respond to both of you there.
