### ISSUE TITLE
Cookies too strict in newest 3.9.0-dev "Cookie domains can not contain"

### ISSUE THREAD

**Issue by ck-on** [facebook/hhvm#5740]
This didn't happen from the dev build 3 weeks ago.

Building today we get

      Fatal error: Cookie domains can not contain any of the following ',; \\t\\r\\n\\013\\014'

This error was caused by old PHP before it supported HTTPONLY directory, you would simply append this to the cookie domain:

             . '; HttpOnly'

Which is now a fatal instead of a warning.

Too strict, and not necessary.

Legacy code would have to be rewritten. 

PHP 5.6 does not have this strictness.

**Comment by Orvid** [comment]
We're a small team, and it doesn't look as though anyone in the community is actively working on this issue, so we've decided to close it. If you plan to send us a pull request resolving the issue let us know in the comments and we will re-open it and assign it to you. If you feel this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
