### ISSUE TITLE
gperf: command not found

### ISSUE THREAD

**Issue by sebastianbergmann** [facebook/hhvm#5744]
Would be nice if `cmake` would bail out when `gperf` is not installed.

```
/usr/local/src/hhvm/src/third-party/proxygen/lib/http/gen_HTTPCommonHeaders.cpp.sh: line 44: gperf: command not found
```

**Comment by apeabody** [comment]
@Orvid I believe this was resovled in the following commit: https://github.com/hhvm/hhvm-third-party/commit/a8e605a35f00c67294c5b1908cb48c529b619848

**Comment by Orvid** [comment]
So it was. Closing.
