### ISSUE TITLE
Parsing <?php as `default_mode

### ISSUE THREAD

**Issue by olleharstedt** [facebook/hhvm#5746]
Hi!

I'm making a type-inferring engine for PHP using Hack parser/lexer. I've found a weird phenomenon.

I want Hack to parse `<?php` as `<?hh`, so I changed this (lexer_hack.mll)

    | <?php {`php_mode}

into this

    | <?php {`default_mode}

_But_, now this file won't return any syntax tree:

    <?php
    // a line comment
    $a = 10;

If I remove the line-comment, the parser returns expected syntax tree.

Any idea what's going on?

**Comment by jwatzman** [comment]
I'd expect that to work? Can you step through with ocamldebug and see what it ends up doing -- my guess would be that one of the other lexer rules is interacting weirdly?

Also remember we ignore expressions at toplevel (in all modes) -- I don't recall at what level it's discarded or if it still shows up in the AST. You might want to try having a function at toplevel, which I know will show up.

**Comment by Orvid** [comment]
This issue has been waiting for more info for more than 2 weeks. I'm closing it for now, but feel free to re-open it if you can provide more info. https://github.com/facebook/hhvm/wiki/Human-Timeouts
