### ISSUE TITLE
stream_await() and related constants not in HHI

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#5748]

**Comment by SiebelsTim** [comment]
Resolved in 73dfc36

**Comment by SiebelsTim** [comment]
@fredemmott You're oncall, right? Close this :P

**Comment by fredemmott** [comment]
That commit didn't actually go into master and doesn't show up in a clone :/ Actually fixed by https://github.com/facebook/hhvm/commit/cbc3e821fe07b10aee2e9d8751bcbf86f507fdb4
