### ISSUE TITLE
Handle "foo::bar" callbacks as string

### ISSUE THREAD

**Issue by nicolas-grekas** [facebook/hhvm#5753]
PHP7 fixed this here: https://bugs.php.net/bug.php?id=68475
`call_user_func($a) not equivalent to $a()`

```php
$cb = 'foo::bar';
call_user_func($cb);
$cb(); // <- this now works on PHP7
```

**Comment by nicolas-grekas** [comment]
http://3v4l.org/SjSJN

**Comment by jwatzman** [comment]
For our own bookkeeping... it looks like this was just changed, there wasn't an RFC this was part of?

**Comment by nicolas-grekas** [comment]
Nope: discussion on PHP internals only
