### ISSUE TITLE
auto-typecheck should look in the same directory as hhvm for hh_client

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#5755]
we currently use 'which'; this would be useful if multiple HHVMs are installed - eg 3v4l or general testing.

**Comment by jwatzman** [comment]
Per in-person discussion, we should look next to hhvm first, and use the current logic as a fallback.

**Comment by fredemmott** [comment]
would it make sense to also check ../hack/bin/ ?

**Comment by jwatzman** [comment]
Internal diff up to fix: D2260916
