### ISSUE TITLE
curl_multi_strerror not available 

### ISSUE THREAD

**Issue by mwjames** [facebook/hhvm#5760]
During testing [0], hhvm complains about "Fatal error: Call to undefined function ... curl_multi_strerror()" on HipHop VM 3.5.0 (rel) / Compiler: tags/HHVM-3.5.0-0-ga90f4733cfa0d8fefdafc7433f758f78cdc75424

http://php.net/manual/en/function.curl-multi-strerror.php / PHP 5 >= 5.5.0

[0] https://travis-ci.org/onoi/http-request/jobs/71877151

**Comment by fredemmott** [comment]
Also not present in 3.8.0.

**Comment by noony** [comment]
Can be closed by https://github.com/facebook/hhvm/commit/7f8a5eb563aafe285a6543a4dc2d4f90463a798b
