### ISSUE TITLE
Undefined constant CURLMOPT_MAXCONNECTS

### ISSUE THREAD

**Issue by mwjames** [facebook/hhvm#5761]
HipHop VM 3.5.0 (rel) / Compiler: tags/HHVM-3.5.0-0-ga90f4733cfa0d8fefdafc7433f758f78cdc75424

Test [0] returns with "Use of undefined constant CURLMOPT_MAXCONNECTS - assumed 'CURLMOPT_MAXCONNECTS'".

Available since/as of PHP 5 >= 5.5.0 [1].

[0] https://travis-ci.org/onoi/http-request/jobs/71877529
[1] http://php.net/manual/en/function.curl-multi-setopt.php

**Comment by fredemmott** [comment]
Also not in 3.8.0.

As a side note, 3.5.0 is unsupported, and has known security issues.

**Comment by mwjames** [comment]
> As a side note, 3.5.0 is unsupported, and has known security issues.

Well, that's the Travis/HHVM test environment.

**Comment by noony** [comment]
This issue can be closed : https://github.com/facebook/hhvm/commit/8328b80e3d11f9abcb52bf28945622279483bc67
