### ISSUE TITLE
Default path for dynamic extensions and configuration directory

### ISSUE THREAD

**Issue by dpaneda** [facebook/hhvm#5774]
It would be cool to have a default path for the dynamic extensions, and a config directory to store the configuration file to load/configure each extension (I'm thinking in something like /etc/php5/conf.d)

With that, it will be possible for the extension authors to provide a package that installs/activates the extension. Right now, you have to create your own package and change the configuration and we are all replicating the same work.

**Comment by paulbiss** [comment]
This sounds like a good idea. cc @sgolemon

**Comment by dpaneda** [comment]
I see that some work have been done on the hphpize to install the extension on a specific directory, which depends on the API version (e.g. /usr/lib/x86_64-linux-gnu/hhvm/extensions/20150212/). This is cool, and the first time of the problem could be fixed making that directory the default path for dynamic extensions.

**Comment by paulbiss** [comment]
This feature request is not actively being worked on. We would happily consider a pull request implementing it. If you plan to work on this issue let us know in the comments and we will re-open the issue and assign it to you. If you feel strongly that this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
