### ISSUE TITLE
Regression: segfault in 3.8.0 using csstidy

### ISSUE THREAD

**Issue by zinigor** [facebook/hhvm#5777]
When using HHVM to host WordPress with Jetpack it segfaults after being updated to 3.8.0 from 3.6.5. The issue is described in more detail here: https://github.com/Automattic/jetpack/issues/2431

You can see there two files to reproduce the issue, but you need a WordPress installation with Jetpack enabled to do that. In case you need additional info, please let me know. I'd be happy to test custom builds if needed.

**Comment by fredemmott** [comment]
We're currently unlikely to investigate issues that do not have reproduction instructions that do not depend on external frameworks/libraries/applications - as we have enough to work on that do have good repro instructions, it's not a good use of time. This is especially true without a C++ backtrace (this can be obtained by installing the hhvm-dbg package or building with CMAKE_BUILD_TYPE=Debug and using gdb)

**Comment by zinigor** [comment]
@fredemmott I understand. Would it be enough if I supplied a C++ backtrace and bundled several files into a gz archive with instructions on how to execute the script?

**Comment by fredemmott** [comment]
Not really - the most time-consuming part is usually the process of reducing it to a few lines of PHP. The backtrace by itself /might/ help.

**Comment by wjywbs** [comment]
I got a minimized repro:
```
<?php
setlocale(LC_ALL, 'LC_CTYPE=;LC_NUMERIC=C;LC_TIME=;LC_COLLATE=;LC_MONETARY=;LC_MESSAGES=;LC_PAPER=;LC_NAME=;LC_ADDRESS=;LC_TELEPHONE=;LC_MEASUREMENT=;LC_IDENTIFICATION=');
```
Stacktrace:
```
# 0  strlen at ...
# 1  HPHP::ThreadSafeLocaleHandler::actuallySetLocale(int, char const*) at hhvm:0
# 2  HPHP::f_setlocale(int, HPHP::Variant const&, HPHP::Array const&) at hhvm:0
# 3  HPHP::jit::x64::(anonymous namespace)::BackEnd::enterTCHelper(unsigned char*, HPHP::ActRec*) at back-end-x64.cpp:0
...
```
Patch:
```
diff --git a/hphp/runtime/base/thread-safe-setlocale.cpp b/hphp/runtime/base/thread-safe-setlocale.cpp
index 54179de..7d67a9d 100644
--- a/hphp/runtime/base/thread-safe-setlocale.cpp
+++ b/hphp/runtime/base/thread-safe-setlocale.cpp
@@ -163,7 +163,7 @@ const char* ThreadSafeLocaleHandler::actuallySetLocale(
          */
         for (auto &i : m_category_locale_map) {
           if (i.category_str == key) {
-            i.locale_str = value;
+            i.locale_str = value ? value : "";
             break;
           }
         }
```

**Comment by fredemmott** [comment]
@wjywbs : do you plan to send a pull request? If so, please include your example as an automated test
