### ISSUE TITLE
XMLReader::open() + zip stream does not check for file existence

### ISSUE THREAD

**Issue by adrilo** [facebook/hhvm#5779]
I noticed an inconsistency between PHP5 and HHVM (3.3.1 at least).
It seems like when using the XMLReader::open() function with a zip stream, the existence of the file within the zip is not checked. This is inconsistent with PHP5 behavior.

To reproduce:

``` php
// creating an empty zip file
$filename = './test.zip';
$zip = new ZipArchive();
if ($zip->open($filename, ZipArchive::CREATE) !== true) {
    exit("cannot open <$filename>\n");
}
$zip->close();

libxml_use_internal_errors(true);

$xmlReader = new XMLReader();
if ($xmlReader->open('zip://test.zip#non/existing/file.xml') === false) {
    throw new Exception("The file does not exist");
}

echo "This should not be reached\n";
if (libxml_get_last_error() === false) {
    echo "And there should be an error...";
}
```

The exception is thrown with PHP but with HHVM, the last lines are echoed

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This issue has been fixed.
Your repro run with the following output in hhvm 4.56.
```
Warning: Unable to open source data in /path/to/file.hack on line 13

Fatal error: Uncaught exception 'Exception' with message 'The file does not exist' in /path/to/file.hack:14
Stack trace:
#0 (): main()
#1 {main}
```
