### ISSUE TITLE
How to connect to Mongodb server in hiphop-php

### ISSUE THREAD

**Issue by 360buyliulei** [facebook/hhvm#578]
first of all, thanks to sandeepone ,for your comment i have implement that connecting to Redis server on php using pure php code , and successfully transfered to hiphop-php.

then,  How to connect to Mongodb server in hiphop-php?

my test php code (using php extension: mongodb-mongo-php-driver-1.3.0beta1-15-ge426381.tar.gz  https://github.com/mongodb/mongo-php-driver/downloads):
<?php
$oMongo = new Mongo( "192.168.12.34:20011", array( 'timeout'=>3000)  );
?>

hiphop-php/build/src/hphp/hphp --log=4   test_mongodb.php
result:
HipHop Fatal error: unknown class Mongo

any good method to resolved ?

**Comment by ardianys** [comment]
Sadly,

10gen's official driver is unsupported 

``https://github.com/mongodb-labs/mongo-hhvm-driver-unsupported``

**Comment by thawkins** [comment]
The standard mongodb php driver now supports both php7 and hhvm

See

https://github.com/mongodb/mongo-php-driver

**Comment by fredemmott** [comment]
@ardianys : https://github.com/mongodb/mongo-hhvm-driver - see the first line in the README of the repo you linked.

**Comment by fredemmott** [comment]
@thawkins : it's just saying that mongo-php-driver and mongo-hhvm-driver expose the same API; it doesn't say that the php-driver works with HHVM, and it doesn't look like that is true. cc @derickr

**Comment by thawkins** [comment]
10gen have unified all thier drivers as being layers ontop of thier "c"
driver and "bson" driver. The low level drivers are useable from both php7
and hhvm. There is a second layer called the "php library" which is written
in pure php and sits ontop of the new low level driver which provide as
close as possible emulation of tbe legacy php driver.

As you have noted i linked to the php driver, you are correct in that there
is a seperate hhvm version that you linked to. But they both use the same
userland php-library.

Its all very confusing and 10gen have been very bad at commicating what is
going on.

But essential you are correct the php driver stack now consistes of 4
components

1. Low level driver for mongo and bson for "c"
2. Lowlevel driver for php 5.5+ and php7 that sits ontop of 1.
3. Lowlevel driver for hhvm that sits ontop of 1
4. Php driver library in php that sits ontop of 2 or 3.

**Comment by ardianys** [comment]
Thanks for your comments @thawkins  and @fredemmott 
You're right, I can't link the native php driver which I installed using phpize to HHVM. 
Thus I can't make my Symfony2 website work because it's Doctrine library require native php mongo driver.
Maybe this problem should be addressed to the Doctrine team ?

**Comment by derickr** [comment]
From what I know @ardianys , the Doctrine team is working on getting it all to work nicely with our new driver API - which would also work on HHVM. Using "phpize" for to install extensions for HHVM is not likely to work...

**Comment by fredemmott** [comment]
@ardianys : In the short-term, do mongofill or mongofill-hhvm fill your needs?

**Comment by ardianys** [comment]
@derickr thanks for your info.
@fredemmott I'll try it.
thanks for all.
