### ISSUE TITLE
ReflectionParameter doesn't throw an exception when created with an unknown parameter

### ISSUE THREAD

**Issue by mnapoli** [facebook/hhvm#5781]
This is a zend incompatibility:

```php
function foo() {}
new \ReflectionParameter('foo', 'bar');
```

In the Zend Engine it will throw a `ReflectionException`, in HHVM the process fails with code 137 without any message.

See it run: http://3v4l.org/VNiOi

**Comment by paulbiss** [comment]
Hmm, I'm seeing an exception: http://3v4l.org/7BYj6

**Comment by mnapoli** [comment]
Is this some kind of sorcery? Or more probably a problem with 3v4l yesterday, I could swear the HHVM results were showing an empty output with `Process exited with code 137`.

Well, I guess this can be closed then… :)
