### ISSUE TITLE
Error suppression operator @ is ignored by DOMXPath::evaluate

### ISSUE THREAD

**Issue by Naktibalda** [facebook/hhvm#5790]
code:

``` php
$locator = 'and position()=1]';

$document = new \DOMDocument('1.0', 'UTF-8');
$xpath = new \DOMXPath($document);
var_dump( @$xpath->evaluate($locator, $document) );
```

Expected result:

```
bool(false)
```

Actual result:

```
XPath error : Invalid expression
and position()=1]
    ^
bool(false)
```

**Comment by Maks3w** [comment]
Additionally the error can't be catched with `set_error_handler`

**Comment by sepehr** [comment]
Any progress on this? The issue is tearing the world apart.

**Comment by aorenste** [comment]
Example in eval: https://3v4l.org/2QpST

**Comment by paulbiss** [comment]
As a workaround you can probably suppress these errors with:
```php
libxml_use_internal_errors(true);
libxml_suppress_errors(true);
```

We should probably start always registering an error handler with `xmlSetGenericErrorFunc` the way PHP does, right now I think libxml is just dumping out the errors itself, which would circumvent our error handlers.

https://3v4l.org/njhn8
https://github.com/php/php-src/blob/ef0279b640b19f6294a1429f9e04019b1f72d69c/ext/libxml/libxml.c#L880

**Comment by Orvid** [comment]
You'll have to make sure all of the calls to the XML functions in DOMDocument have the appropriate anchors though, otherwise any exceptions will crash :(

**Comment by paulbiss** [comment]
@Orvid well we should be doing that anyway

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Hhvm has not been php compatible since version 4.0.0. The `@` operator in Hack is sugar for setting the error reporting level. DomXPath doesn't interact with the error handler in the PHP way. Removing the operator in php emits a warning.
