### ISSUE TITLE
XHP attribute assignment message is confusing

### ISSUE THREAD

**Issue by steelbrain** [facebook/hhvm#5792]
```
->: syntax is not supported for lvalues
```

I think it should be something like

```
->: syntax is not supported for assignments
```

**Comment by paulbiss** [comment]
I think lvalue is actually more consistent with other errors in Hack, and for what its worth I find it clearer as an assignment context isn't the only place you can find lvalues.

**Comment by steelbrain** [comment]
> I find it clearer as an assignment context isn't the only place you can find lvalues.

It is clearer to the people who wrote it, I personally didn't know about it and figured it from the context.

**Comment by paulbiss** [comment]
FWIW, I think lvalue is fairly common among compiler warnings and errors (gcc and clang both use it in describing a variety of issues), it's certainly not a Hack/HHVM specific term. I can see how this could be confusing to someone unfamiliar with the term though, perhaps we can add more context to the message or a more detailed explanation in the docs.

**Comment by jwatzman** [comment]
HHVM itself emits

> Fatal error: Using ->: syntax in write context is not supported

which is maybe marginally better? I also think lvalue is a pretty standard term, which I heard long before working on a compiler.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Assigning to a `->:attributename` emits two errors in hhvm 4.56.
The first error is identical to the new runtime error.

```HACK
<<__EntryPoint>>
function main(): void {
    $x = <html />;
    $x->:id = 'id';
}
```

```
Parsing[1002] ->: operator is not allowed in write context
   --> file.hack
  4 |     $x->:id = 'id';
    |     ^^^^^^

Parsing[1002] ->: syntax is not supported for lvalues
   --> file.hack
  4 |     $x->:id = 'id';
    |     ^^^^^^^

2 errors found.
```
 
```
Fatal error: Uncaught Error: ->: operator is not allowed in write context in /path/to/file.hack:4
Stack trace:
#0 {main}
```
