### ISSUE TITLE
Can't get file name from anonymous function reflection

### ISSUE THREAD

**Issue by johnbillion** [facebook/hhvm#5807]
Given the following code:

``` php
$function = create_function( '$x', 'return $x;' );
$ref      = new ReflectionFunction( $function );
var_dump( $ref->getFileName() );
```

PHP outputs the file name and line number that the anonymous function was created on; something along the lines of:

`/path/file.php(3) : runtime-created function`

but HHVM doesn't output the file name or line number, and instead outputs the following:

`//`

Repro: http://3v4l.org/TDgF5

**Comment by jesseschalken** [comment]
This seems to be just a quirk of `create_function()`. Using a normal closure works fine: https://3v4l.org/osdPY

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

`\create_function()` has been removed from hhvm in version [4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html).
