### ISSUE TITLE
HHVM slow log

### ISSUE THREAD

**Issue by dieend** [facebook/hhvm#5810]
Is this feature exists?

I have problem with my application, where the server intermittently have big queue (I check this using admin server, /check-health) and the number of queued reached hundreds. I guessed it is because somewhere in my code there is a blocking or very slow parts, that made the queue bloated and the servers down. Any other way to investigate it other than slowlog is appreciated.

**Comment by fredemmott** [comment]
Options include:
- look at your webserver access logs for specific requests that take a long time and see if there's a pattern
- attach gdb and use 'thread apply all bt' and see if all the workers are in locks, and if so, what's calling them
- Using 'perf' to profile HHVM (it will include both C++ code and jit-ed PHP code) and see where the time is being spent

If nothing's obviously wrong, it could simply be that the thread count is too lower - try increasing hhvm.server.thread_count to eg 10x the number of CPU cores. The default is 2x, which is fine for heavily async code, but not for more traditionally-architected PHP software.

**Comment by dieend** [comment]
Thanks! That helped.

But how about if the slows happen always when no one available to access the server? The options you suggest only if we can access the server when the slowdown happened. Is there any way to know what request that took to much time happened in the past?

**Comment by fredemmott** [comment]
Your webserver access logs may have that data.

**Comment by Orvid** [comment]
We're a small team, and it doesn't look as though anyone in the community is actively working on this issue, so we've decided to close it. If you plan to send us a pull request resolving the issue let us know in the comments and we will re-open it and assign it to you. If you feel this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
