### ISSUE TITLE
JSON_parser for json-c runs in non-strict mode, cannot be made strict

### ISSUE THREAD

**Issue by anomiex** [facebook/hhvm#5813]
This causes an incompatibility with PHP: Under HHVM, `json_decode('[1,]')` returns `array(1)` while under PHP it returns null with JSON_ERROR_SYNTAX.

It looks like there's code in JSON_parser to enable json-c's strict mode unless a `k_JSON_FB_LOOSE` option is passed, but it's commented out.

**Comment by mattflaschen** [comment]
Working on this.

**Comment by jesseschalken** [comment]
Has this issue been fixed? This code produces the same result on PHP and HHVM:

```php
var_dump(json_decode('[1,]'));
var_dump(json_last_error());
```
```
NULL
int(4)
```

https://3v4l.org/bnsPt

**Comment by lexidor** [comment]
Yep, this issue has been resolved.
```
hphpd> \var_dump(\json_decode('[1,]'));
\var_dump(\json_decode('[1,]'));
NULL
```

**Comment by fredemmott** [comment]
@lexidor did you test this with a custom build of HHVM with `-DUSE_JSONC=ON` passed to cmake?

**Comment by lexidor** [comment]
Oops, I thought JSONc was the default. Good catch. Reopened the issue and asked Scott. (They have an hhvm build with JSONc iirc.) Same mistake made in #8726.

**Comment by lexidor** [comment]
Scott confirmed, JSONc is always in loose mode.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Support for json-c has been removed. https://github.com/facebook/hhvm/commit/ef919bb81cc2326a24d07bb9b7b7574eced09366
