### ISSUE TITLE
preg_replace with /e doesn't support self::

### ISSUE THREAD

**Issue by tonygaillard** [facebook/hhvm#5820]
preg_replace execute a function if the delimiter /e is used.

http://3v4l.org/iTlhX

```php
<?php
class user
{
    static function init()
    {
        preg_replace('/hi/e', "self::hello()", "hi");
    }
    
    static function hello()
    {
        return "hello";
    }
}
user::init();
```

PHP 5.5, PHP 5.6, deprecated.
PHP 7, warning
PHP 5 - 5.4, the function is well executed and can access to self::
HHVM, Fatal error: Cannot access self:: when no class scope is active

Note: if we declare the function hello out of the class, we can access it. We should not be able to reference a function as a second argument of preg_replace function.

I think the problem is the execution of the function with the delimiter /e and not that the scope self is not available, but we have 2 problems here.

**Comment by Orvid** [comment]
We're a small team, and it doesn't look as though anyone in the community is actively working on this issue, so we've decided to close it. If you plan to send us a pull request resolving the issue let us know in the comments and we will re-open it and assign it to you. If you feel this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
