### ISSUE TITLE
iconv ASCII transliteration

### ISSUE THREAD

**Issue by andrisi** [facebook/hhvm#5825]
Not sure if this is a bug, but HHVM behaves differently, but when calling:
```sh
iconv('UTF-8', 'ASCII//TRANSLIT', $name); 
```
with the strings below. PHP's implementation will drop the accents, while HHVM's will put question marks in place of them. PHP adds question marks only for non-latin chars, that can not be "truncated" to plain ASCII by dropping the accents.
- provence-alpes-côte d'azur
- île-de-france

**Comment by andrisi** [comment]
Setting the locale with the call below corrects the behaviour, so it's more likely to be related to some defaults being set to different values in PHP vs. HHVM. Sorry, if this is an issue for me only.
```sh
setlocale(LC_ALL, 'en_US.UTF-8');
```

**Comment by jwatzman** [comment]
http://3v4l.org/0aZiW shows consistent output, so yeah, this looks like some config difference on your end.
