### ISSUE TITLE
Alpine package

### ISSUE THREAD

**Issue by mancvso** [facebook/hhvm#5826]
In the spirit of minimal Docker containers we've been granted with Alpine Linux (a minimal distribution in only 5Mb). Optional support for glibc can be added.

Is there any chance to get HHVM for Alpine? At least any hint?

I know I'm asking too much, but wanted to ask anyway. Thanks in advance.

**Comment by mancvso** [comment]
Issue raised upstream
http://bugs.alpinelinux.org/issues/4503

**Comment by fredemmott** [comment]
Sorry, we are very unlikely to do this. We may support Docker in the future, but packaging directly for additional distributions is very time-consuming and takes away from main development.

**Comment by mancvso** [comment]
I understand completely your point. But can HHVM be statically compiled? I can make the package, but currently it cannot be compiled in a single binary.

**Comment by fredemmott** [comment]
We do that internally, but not via CMake. It should be possible, but I don't know the details.

**Comment by etopian** [comment]
In relation to this, can HHVM compile on musl libc rather than glibc? Alpine uses musl libc instead of glibc

**Comment by andrewmclagan** [comment]
This would really move HHVM into the docker eco-system.

Im sure Facebook is using some kind of linux container based distribution? Would not that also have benefits internally?

**Comment by fredemmott** [comment]
Yes we do, but it's not a standard distribution, and it's not via cmake. We also already provide docker containers, built on Ubuntu 14.04: https://hub.docker.com/r/hhvm/

**Comment by lambertlu** [comment]
I start an new repository for HHVM running on Alpine Linux.
Please take a look and help me push on it.

**Comment by lambertlu** [comment]
https://github.com/lambertlu/alpine-hhvm
