### ISSUE TITLE
HHVM 3.8 stream_socket_client returns Unable to set verify locations promblem

### ISSUE THREAD

**Issue by caolixiang** [facebook/hhvm#5830]
## Description
When I update hhvm form 3.7 to 3.8, problem occurred with my laravel project.
With vendor ([pingpp-php](https://github.com/PingPlusPlus/pingpp-php)), when I created a charge, my program went wrong.

##Error Log
```
[2015-08-01 09:53:04] local.ERROR: exception 'ErrorException' with message 'Unable to set verify locations `/home/wwwroot/laravel/vendor/pingplusplus/pingpp-php/lib/../data/ca-certificates.crt' `'' in /home/wwwroot/laravel/vendor/pingplusplus/pingpp-php/lib/ApiRequestor.php:386
Stack trace:
#0 (): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /home/wwwroot/laravel/vendor/pingplusplus/pingpp-php/lib/ApiRequestor.php(386): stream_socket_client()
#2 /home/wwwroot/laravel/vendor/pingplusplus/pingpp-php/lib/ApiRequestor.php(171): Pingpp\ApiRequestor->checkSslCert()
#3 /home/wwwroot/laravel/vendor/pingplusplus/pingpp-php/lib/ApiRequestor.php(116): Pingpp\ApiRequestor->_requestRaw()
#4 /home/wwwroot/laravel/vendor/pingplusplus/pingpp-php/lib/ApiResource.php(102): Pingpp\ApiRequestor->request()
#5 /home/wwwroot/laravel/vendor/pingplusplus/pingpp-php/lib/ApiResource.php(134): Pingpp\ApiResource::_staticRequest()
#6 /home/wwwroot/laravel/vendor/pingplusplus/pingpp-php/lib/Charge.php(37): Pingpp\ApiResource::_create()
#7 /home/wwwroot/laravel/app/Http/Controllers/myOrder/BuyerPayController.php(49): Pingpp\Charge::create()
#8 (): App\Http\Controllers\MyOrder\BuyerPayController->postPayInformation()
```

##After
I found that the problem is due to stream_socket_client() method, when setting verify_peer false, the stream_socket_client can be pass.
Codes from pingpp-php:
```php
        $url = parse_url($url);
        $port = isset($url["port"]) ? $url["port"] : 443;
        $url = "ssl://{$url["host"]}:{$port}";

        $sslContext = stream_context_create(
            array('ssl' => array(
                'capture_peer_cert' => true,
                'verify_peer'   => true,
                'cafile'        => $this->caBundle(),
            ))
        );
        $result = stream_socket_client(
            $url, $errno, $errstr, 30, STREAM_CLIENT_CONNECT, $sslContext
        );
```  

So I wonder if there's something wrong with hhvm 3.8 which has relationship with stream_socket_client or methods that deal with ssl.

hhvm 3.7 everything goes fine.

Thank you!

**Comment by fredemmott** [comment]
Which specific versions? 3.7.3 likely has the same problem 3.7.2 and below did not verify certificates at all.

I believe this was fixed by https://github.com/facebook/hhvm/commit/65e4a75724f80f5e544c0bc4210d033535866c20

As a workaround, you should also be able to set 'capath'

**Comment by caolixiang** [comment]
Thanks a lot!

The specific version is 3.7.0.

When I add 'dev/null' as parameters of context it passed, indeed a workaround.
To let the program go, I should also delete some other code as following:

```php

$params = stream_context_get_params($result);

        $cert = $params['options']['ssl']['peer_certificate'];

        openssl_x509_export($cert, $pem_cert);

        if (self::isBlackListed($pem_cert)) {
            throw new Error\ApiConnection(
                'Invalid server certificate. You tried to connect to a server '.
                'that has a revoked SSL certificate, which means we cannot '.
                'securely send data to that server.  Please email '.
                'support@pingxx.com if you need help connecting to the '.
                'correct API server.'
            );
        }

```

If I didn't delete it, it will throw a exception:

```
Undefined index: peer_certificate
```

Em, does it mean that although the location path setting problem solved through set a capath, but it still can't get the right context content if 'verify_peer' setting to true.

Thanks again, and I love the Facebook and your hard and creative working, which make Internet better.

**Comment by fredemmott** [comment]
Could you file capture_peer_cert/peer_certificate as a separate issue (so there's not two problems in one thread). Closing this as it's fixed in master (and the hhvm-nightly packages).
