### ISSUE TITLE
exec/shellexec/passthru returns incorrect data

### ISSUE THREAD

**Issue by r3wt** [facebook/hhvm#5831]
```bash
mpstat | awk '$12 ~ /[0-9.]+/ { print 100 - $12 }'
```
**output** `0.35`
```php
$res = [];
exec("mpstat | awk '$12 ~ /[0-9.]+/ { print 100 - $12 }'",$res);
print($res[0]);
```
**output** `100`

if i exec the script in the shell its fine. however, execing it in browser causes output to become 100.

EDIT: Changing hhvm user to same user as file owner solved the problem.

**Comment by jwatzman** [comment]
Closing since this sounds like `mpstat` not doing what you thought it was doing. If you can come up with a repro case that doesn't rely on system-specific configuration, happy to reopen.
