### ISSUE TITLE
Cannot set default charset

### ISSUE THREAD

**Issue by kandy** [facebook/hhvm#5832]
http://3v4l.org/OoO8R

**Comment by tonygaillard** [comment]
You can set a default charset, example:

ini_set('default_charset', 'UTF-16');
var_dump(ini_get('default_charset'));

As indicated in the page http://php.net/ini_set, the return value of the function ini_set is a string. This string is the previous value. "Returns the old value on success, FALSE on failure."

You can test it with:

var_dump(ini_set('default_charset', 'UTF-18'));

**Comment by danslo** [comment]
@tonygaillard Even in that case, seems like a regression since 3.7 in regards to the default value.

**Comment by paulbiss** [comment]
cc @JoelMarcey

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Hhvm is moving away from a global charset. The hsl has introduced `Locale` as a replacement. This `Locale` does not automatically affect string manipulation functions. It is passed in as a parameter instead. https://hhvm.com/blog/2021/10/05/hhvm-4.130.html
