### ISSUE TITLE
3.9 LTS - Precise 12.04

### ISSUE THREAD

**Issue by jg-development** [facebook/hhvm#5835]
Hi,
I have a documentation question. Will there be a LTS Release 3.9 for Ubuntu 12.04?
The stream_socket_enable_crypto feature is needed badly from my side.

Greetings 
Jan

**Comment by fredemmott** [comment]
3.6 was the last release with 12.04 - see https://github.com/facebook/hhvm/wiki/Prebuilt-Packages-on-Ubuntu-12.04

Your options are to upgrade, or use a vm or container system (eg docker).
