### ISSUE TITLE
Is it possible to exclude script.php from using HHVM?

### ISSUE THREAD

**Issue by daniel1943** [facebook/hhvm#5838]
I am loving HHVM but there is issue with one WP plugin(justified image grid) which uses TIMTHUMB to resize images and this one doesn't seem to play with HHVM.

I am using fallback like this:

http://i.imgur.com/wn3UklV.png

But it doesn't work. 

Is it possible to make an exception and make timthumb.php file use only PHP-FPM?

**Comment by Orvid** [comment]
Are you working with Apache or nginx? Based on the screenshot I'm going to claim nginx, as it doesn't look like an Apache config I've seen, but I only have minimal experience with Apache, and none at all with nginx, so I may very well be wrong about that.

If this were apache, and you were using the default proxy-pass-match setup that HHVM ships with on Ubuntu 14.04, you could add the file as a specific exclusion to the regex used to determine what to pass to HHVM.

**Comment by sagsai** [comment]
Didn't try with wordpress, but the following setting was able to run a a single php file selectively using php5-fpm. Also not sure if it will work with repo auth mode on.

    location ~ timthumb.php$ {
        try_files $uri =404;
        # With php5-fpm:
        fastcgi_pass unix:/var/run/php5-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
        # other stuff...
    }
    
    location ~ \.(hh|php|php5)$ {
        try_files $uri =404;
        # using unix socket for hhvm instead of a port
        fastcgi_pass unix:/var/run/hhvm/hhvm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
        # other stuff...
    }

**Comment by jwatzman** [comment]
If you are able to get a repro case or otherwise help us figure out why that one script isn't working on HHVM, please file a separate issue about it -- we'd like to fix it! Beyond that, this is purely an nginx configuration issue, for which this isn't really the right forum.
