### ISSUE TITLE
__IsFoldable not recognized by typechecker

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#5840]
Unrecognized user attribute: __IsFoldable starts with __ but is not a standard attribute (Naming[2049])

**Comment by paulbiss** [comment]
I don't think marking a function as foldable will have any effect outside of systemlib, and my understanding is we'd like to move this behavior to hhbbc and deprecate the attribute entirely anyway.

**Comment by jwatzman** [comment]
Yeah, I really don't think this should be done outside systemlib?

**Comment by jwatzman** [comment]
(And if we do typecheck systemlib, we can add this attribute to the hhconfig for systemlib specifically.)
