### ISSUE TITLE
Test castDbl diverts behaviour on mode 'interp'

### ISSUE THREAD

**Issue by lbianc** [facebook/hhvm#5847]
Running the HHVM tests on interpreter mode, it fails on hphp/test/quick/castDbl.php:

```
FAILED: hphp/test/quick/castDbl.php
011+ int(-1)
011- int(0)
```

It's related with a cast of "18446744073709551615.0" to int, which when using JIT it returns 0, but using the interpreter mode, it returns -1.
Is it a bug or there is a reason for that?

**Comment by SiebelsTim** [comment]
I don't have a machine right now to test it myself. But I think `quick/` runs on every diff, both in JIT and interp mode. So it might be caused by your setup (which it really shouldn't). Mind sharing hhvm version and operating system?

**Comment by paulbiss** [comment]
The JIT emits a cvtsi2sd instruction to perform the conversion, while the interpreter uses a c-style cast. It's possible that your compiler has done something different for the cast.

**Comment by jwatzman** [comment]
Yeah, OS, HHVM version, and output of `gcc --version` would be useful.

**Comment by Orvid** [comment]
That would have to be a bug in the optimizer for that compiler, wouldn't it? I don't see how it's possible for any of the normal fp modes to be able to get -1. As a random thought,  shouldn't we be using the double-conversion library here, or does that library serve somr other purpose?

**Comment by lbianc** [comment]
Today I was trying to reproduce the issue, but the one I reported does not happen anymore for the machine described bellow. The test failing now is this:

```
FAILED: hphp/test/quick/array_plus_eq_dtor.php
010+ done
011- done

```

This test fails with release flags, but does not with debug flags. 
It changed behaviour after I build HHVM again.
Is this an expected behaviour?


About the hphp/test/quick/castDbl.php, I will debug it to check and I share here any news.



Environment details:
```
OS system:
Linux debian 3.2.0-4-amd64 #1 SMP Debian 3.2.65-1+deb7u1 x86_64 GNU/Linux


gcc version:
gcc (Debian 4.9.2-22) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


HHVM version:
HipHop VM 3.9.0-dev (rel)
Compiler: heads/dev-0-g1900c0bb9fa1b5d3e7977ed13503b0b1b6b83c51
Repo schema: 944e4a6af06e38729edd988da3aee9a91d72fd46


Command line to execute tests:
hphp/test/run --mode 'interp'
```

**Comment by paulbiss** [comment]
It's not expected, but it sounds like an issue with gcc. Here's where the cast happens in the interpreter, you might try disassembling this function in your builds to see what's different:

https://github.com/facebook/hhvm/blob/046a8404751f269cf849108c6907cd43729fbb51/hphp/runtime/base/tv-helpers.cpp#L180-L182

**Comment by lbianc** [comment]
Thanks @paulbiss.
I'm closing this issue, since I couldn't reproduce the original issue, but I've just opened a new one, where I describe that the cast from double to uin64_t is casting values that do not fit in uint64_t. Please, check it: https://github.com/facebook/hhvm/issues/5932.
