### ISSUE TITLE
fetch_fields() on a non-object (boolean) [mysqli_stmt->store_result]

### ISSUE THREAD

**Issue by rdpse** [facebook/hhvm#5849]
Context: trying to get [IPS4 Forums](https://www.invisionpower.com/features/apps#forums) to work with hhvm.

    [hphp] [9423:7f267cbff700:9:000001] [] Fatal error: Uncaught exception 'BadMethodCallException' with message 'Call to a member function fetch_fields() on a non-object (boolean)' in :
    Stack trace:
    #0 /var/www/domain.tld/system/Db/Db.php(414): mysqli_stmt->store_result()
    #1 /var/www/domain.tld/system/Db/Db.php(645): IPS\\_Db->preparedQuery()
    #2 /var/www/domain.tld/system/Session/Front.php(297): IPS\\_Db->replace()
    #3 (): IPS\\Session\\_Front->write()
    #4 (): call_user_func()
    #5 (): __SystemLib\\SessionForwardingHandler->write()
    #6 (): session_write_close()
    #7 {main}

[Db.php](https://gist.github.com/rdpse/56c2597621750751d635)
 
Debian 8
>HipHop VM 3.8.1 (rel)
Compiler: tags/HHVM-3.8.1-0-g3006bc45691762b5409fc3a510a43093968e9660
Repo schema: 253b3802ce1bcd19e378634342fc9c245ac76c33

**Comment by jwatzman** [comment]
Can you give a little more info? First, the code you've provided doesn't seem to correspond to the error -- notably, I don't see a `fetch_fields` in your provided `Db.php`. It would also be useful if you'd do a little more digging into what was going wrong -- where is that boolean coming from, for example?

**Comment by rdpse** [comment]
It happens while trying to login. Here's the full [error.log](https://gist.github.com/rdpse/cd09d682ae3f97b5caa6) and the [init.php](https://gist.github.com/rdpse/d8eb966d931828ec579c) file which is referenced in it.

I'll try to do more digging tomorrow.

**Comment by jwatzman** [comment]
The `Db.php` you provided doesn't have a call to `fetch_fields` on line 414. Are you sure you provided the right `Db.php`?

**Comment by rdpse** [comment]
Yes, it's the right file. fetch_fields() isn't called (at least not verbatim) in a single file related to the application. 

Here's [Select.php](https://gist.github.com/rdpse/935cea08e01448c1c1af#file-select-php), a companion to Db.php. fetch_field() occurs one single time [here](https://gist.github.com/rdpse/935cea08e01448c1c1af#file-select-php-L340). And [this](https://gist.github.com/rdpse/935cea08e01448c1c1af#file-select-php-L491) also seems relevant.

**Comment by jwatzman** [comment]
Nothing obvious jumps out at me from the files you've posted. Unfortunately it's going to be hard for me to debug this from here -- you're going to have to debug a little yourself; if you can come up with something more specific where we differ from PHP, that's something we can look into.

**Comment by r3wt** [comment]
@jwatzman The guy (Emil Hesslow) who wrote the MySQLi extension for HHVM left out alot of functionality and methods. Not sure if he or anyone else ever implemented them fully, but when i complained about it eons ago the response was "we'll be happy to accept a pull request"

**Comment by WizKid** [comment]
Without debugging it it is impossible to say if this is an error in MySQLi or somewhere else. What is $stmt before line 414? 

And the only part I know I left out was was the MySQLND stuff that normal PHP also leave out if you don't compile with the ND option.

**Comment by rdpse** [comment]
Unfortunately I don't really have enough time or knowledge to debug this properly right now. If any of you are intrigued enough I can provide access to a VM in a replicated environment. Just hit me on freenode (same username).
