### ISSUE TITLE
allow_url_include not implemented

### ISSUE THREAD

**Issue by marcokh** [facebook/hhvm#5852]
Hello,

I just installed a fresh hhvm to try running my php project and everything seem to work perfectly out of the box except for those lines 

		$f = @fopen($config['bridge_url'], 'r');
		$meta = @stream_get_meta_data($f);
		@fclose($f);
		if($meta['mode'] != 'r') {
			echo "main bridge not available <br>";
			throw new Exception("main bridge not available");
		} else {
			require_once($config['bridge_url']);
		}

the call to fopen is making sure that the stream is available before calling require_once, still, hhvm trigger a fatal error "file not found" (which is weird as it should more likely refer to the http wrapper or eventually the stream not being available)

\nFatal error: File not found: http://localhost:8087/JavaBridge/java/Java.inc 

The php application already have the setting allow_url_include = On but since I'm unsure if hhvm reads php's ini file at all I have also tried to include the setting into /etc/hhvm/php.ini

However, regardless of what I am setting into the ini file, it seem that hhvm's allow_url_include is never set and that allow_url_fopen is always set to 1 or at least that is the value I'm getting when I'm trying 

echo ini_get('allow_url_include') // return empty string
echo ini_get('allow_url_fopen') // return 1 even if I set it to 0 in the ini file.

My hhvm version 

marco@marco-newlap:~$ hhvm --version
HipHop VM 3.8.1 (rel)
Compiler: tags/HHVM-3.8.1-0-g3006bc45691762b5409fc3a510a43093968e9660
Repo schema: 253b3802ce1bcd19e378634342fc9c245ac76c33

The relevant part of the /etc/init.d/hhvm script that was used to start hhvm 

CONFIG_FILE="/etc/hhvm/server.ini"
SYSTEM_CONFIG_FILE="/etc/hhvm/php.ini"

Any help deeply appreciated

**Comment by jwatzman** [comment]
As you suspected, it looks like we don't support `allow_url_include`, which is a documented PHP5 INI option: http://php.net/manual/en/filesystem.configuration.php#ini.allow-url-include

However, that flag looks like a terrible idea to add from a security standpoint, @sgolemon et al, do you think we should support this or wontfix?

**Comment by salvettimarc** [comment]
thanks for your answer jwatzman, that clarifies it. 

I understand what you mean about security but I suppose there was a reason this flag was introduced in the first place. 

In my particular use case, we are talking about an app running on local network and needing to access local devices from the file system. This is achieved by communicating between php and a java service using the java bridge which is available through the http:// wrapper. 

If you have a better way to do this I'll be glad to hear it as this was a major headache in the project.

I guess we could have a discussion about how this is bad for security and what the alternatives would be but I'm not sure this would be the place.

**Comment by jwatzman** [comment]
> I understand what you mean about security but I suppose there was a reason this flag was introduced in the first place. 

You've got the causality backwards. `require` etc used to go through the same stream layer as anything else in PHP, and so PHP accidentally allowed you to `require` things over the network. The PHP devs agreed this was a terrible idea for security and disabled it, leaving the INI option in place just in case folks were relying on it. So the option wasn't added to enable this behavior, it was added for BC when the behavior was deliberately *disabled*.

> In my particular use case, we are talking about an app running on local network and needing to access local devices from the file system.

Why can't it just read the files off of disk? Why is your application dynamically including this code in the first place -- why isn't it a source file like any other?

> If you have a better way to do this I'll be glad to hear it as this was a major headache in the project.

You can always do something like this:

```php
$data = file_get_contents($url);
eval($data);
```

(Or write it to `/tmp` and include that.) That's just being honest about what you're trying to do -- load data off of the network and eval it!

In any event, your architecture is your own... but IMO this is such a terrible feature for security that I'm not sure we'd even merge a PR that implemented it. If you (or anyone) is interested in writing one, please let us know first so we can get agreement on whether we'd merge it before you spend effort on it. But I don't think we'll work on this ourselves either.

**Comment by salvettimarc** [comment]
your points are perfectly valid and I understand what you are saying. I also agree that my architecture may be wrong, just not so sure how your solution might work in my use case. My code merely implement the javabridge solution described here http://php-java-bridge.sourceforge.net/doc/desktop-apps.php

At the moment, the php app needs to share objects with the desktop java app. Those objects may be serialized, stored in the db and reloaded by the java app which hand them over to the php code and back. This is because the java app handles the communication with the local devices and the app is already existing. My code is acting as a remote control for that part.

As I understand you, to get totally rid of this mess would mean to re-code / translate all the java app into a new php app, and I'm not even sure about the ability to drive a device like a printer directly from php, although I'm probably just lacking experience in that field.

Anyway, thanks for your input. I'll give it more thoughts before I decide which way I should be going.

**Comment by Orvid** [comment]
We're a small team, and it doesn't look as though anyone in the community is actively working on this issue, so we've decided to close it. If you plan to send us a pull request resolving the issue let us know in the comments and we will re-open it and assign it to you. If you feel this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
