### ISSUE TITLE
Why do we support shape values for user attributes?

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#5855]
- user attribute values can not be typechecked
- it's a plain array when retrieved
- so, it's just an unsafe array that looks like it's safe...

Just remove/deprecate support?

**Comment by jwatzman** [comment]
+1

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

In hhvm [3.29.0](https://hhvm.com/blog/2018/10/22/hhvm-3.29.html), user attributes are now typechecked.
You declare a class like this.
```HACK
final class MyAttribute implements \HH\FunctionAttribute {
  public function __construct(public shape('alpha' => string, 'numeric' => num) $shape)
}
```

This will enforce you use the correct properties at the declaration and when you reflect them back.
```HACK
<<MyAttribute(shape('alpha' => 'I am typechecked', 'numeric' => 10.))>>
function my_function(): void {}
(new ReflectionFunction('my_function')->getAttributeClass(MyAttribute::class)->data['alpha'];
```
