### ISSUE TITLE
Anonymous function name is prepended with a null character when performing reflection

### ISSUE THREAD

**Issue by johnbillion** [facebook/hhvm#5856]
Given the following:

    $foo = create_function( '$a', 'return $a;' );
    $ref = new ReflectionFunction( $foo );
    var_dump( $ref->getName() );

Results in this output:

    string(9) "lambda_1"

The function name is being prepended with an invisible `null` character (resulting in the string containing 9 characters). A hex dump of the string confirms this:

    0000  00 6c 61 6d 62 64 61 5f  31                        .lambda_ 1

Related: #5807

**Comment by paulbiss** [comment]
I believe this is by design to prevent it from clashing with any user defined functions.

**Comment by Orvid** [comment]
Perhaps it sjould use some character that is actually visible to do this? `$` for instance?

**Comment by paulbiss** [comment]
That would probably be fine too, though I'm not sure what's wrong with using a null-character

**Comment by jwatzman** [comment]
Marking wishlist in case someone wants to send a PR to change this, but we're unlikely to do it ourselves.

**Comment by Orvid** [comment]
We're a small team, and it doesn't look as though anyone in the community is actively working on this issue, so we've decided to close it. If you plan to send us a pull request resolving the issue let us know in the comments and we will re-open it and assign it to you. If you feel this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
