### ISSUE TITLE
Raise error if __ConsistentConstruct is used on a function

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#5857]
It needs to be on the class. Using it on __construct results in confusing errors, eg https://gist.github.com/fredemmott/e1b08c92a8a432d7ddd7

**Comment by Orvid** [comment]
We're a small team, and it doesn't look as though anyone in the community is actively working on this issue, so we've decided to close it. If you plan to send us a pull request resolving the issue let us know in the comments and we will re-open it and assign it to you. If you feel this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
