### ISSUE TITLE
Errors about timezone in HHVM 3.8.1

### ISSUE THREAD

**Issue by JasonXt** [facebook/hhvm#5861]
Ubuntu 14.04

HipHop VM 3.8.1 (rel)
Compiler: tags/HHVM-3.8.1-0-g3006bc45691762b5409fc3a510a43093968e9660
Repo schema: 253b3802ce1bcd19e378634342fc9c245ac76c33

In my ubuntu I have set the timezone to Asia/Shanghai by using tzselect command;
check it:
   #date
   Thu Aug  6 09:42:00 CST 2015

then , in HHVM  I do nothing  just install it by apt-get  then check the config by phpinfo()
   date.timezone =     
it's empty
in my php script /var/www/html/public/test.php
   <?php
      // phpinfo();
     date_default_timezone_set('Asia/Shanghai');
     $timestamp = date('Y-m-d H:i:s', time());
     var_dump($timestamp);

CLI:
   # hhvm -f /var/www/html/public/test.php
   string(19) "2015-08-06 09:52:48"
   # php -f /var/www/html/public/test.php
    string(19) "2015-08-06 09:53:52"

using apache by fastcgi
apache config file 
   ProxyPassMatch ^/(.+\.(hh|php)(/.*)?)$ fcgi://127.0.0.1:9000/var/www/html/public/$1
request: 127.0.0.1/test.php
   string(19) "2015-08-06 01:57:23"

the result is different from the cli . 
What's the problem?????

**Comment by jwatzman** [comment]
This works for me -- loading on the CLI and via a webserver gives the same result:

```sh
root@vagrant-ubuntu-trusty-64:/usr/share/nginx/html# date
Thu Aug  6 23:21:21 UTC 2015
root@vagrant-ubuntu-trusty-64:/usr/share/nginx/html# cat date.php
<?php

date_default_timezone_set('Asia/Shanghai');
$timestamp = date('Y-m-d H:i:s', time());
var_dump($timestamp);
root@vagrant-ubuntu-trusty-64:/usr/share/nginx/html# hhvm date.php 
string(19) "2015-08-07 07:20:24"
root@vagrant-ubuntu-trusty-64:/usr/share/nginx/html# curl localhost/date.php
string(19) "2015-08-07 07:20:29"
```

Are you sure your load of `test.php` via web request is referring to the same `test.php`?

**Comment by Orvid** [comment]
This issue has been waiting for more info for more than 2 weeks. I'm closing it for now, but feel free to re-open it if you can provide more info. https://github.com/facebook/hhvm/wiki/Human-Timeouts
