### ISSUE TITLE
Array output in incorrect order on Magento Currencies 

### ISSUE THREAD

**Issue by rossmc** [facebook/hhvm#5862]
(Following on from a comment [issues3202#issuecomment-128024603](https://github.com/facebook/hhvm/issues/3202#issuecomment-128024603))

#### The Issue
On Magento there is an issue with how the currency rates table is displayed.  It is outputting the currencies in the wrong order.

With HHVM on, the base currency input field is in the second column. i.e. the Euro rate is 1.0000, it should be under the Euro column not the GBP column.
![Curency Rates with HHVM on](http://i.stack.imgur.com/R2vmb.jpg)
When HHVM is off it is displayed correctly.
![Curency Rates with HHVM off](http://i.stack.imgur.com/imDET.jpg)

#### My Environment
This issue is occuring on our Magento store (v1.9.2) and a fresh Magento instalation(v1.9.1.1).   Our PHP Version is 5.6.99-hhvm and HHVM Version 3.7.2.

Also I have `hhvm.enable_zend_sorting = 1` & `hhvm.enable_obj_destruct_call = 1` set in my */etc/hhvm/php.ini* and */etc/hhvm/server.ini* files.

#### To Reproduce
To replicate the issue on Magento you need to have three [currency rates set](http://merch.docs.magento.com/ce/user_guide/Magento_Community_Edition_User_Guide.html#configuration/currency-setup.html), one base currency and two allowed currencies, then you will see the issue when you got to *System > Manage Currency Rates* from the Magento admin panel.

#### My Debugging
I'm trying to find the unsupported PHP code but my debugging skills are not there yet, so far I've found that in: 
*app/design/adminhtml/default/default/template/system/currency/rate/matrix.phtml*
`$_oldRates = $this->getOldRates();` is getting an array in the wrong order with HHVM turned on.  With xDebug in PHPStorm it is showing the result as:
```
$_oldRate = {array}[1]
  EUR = {array}[3]
    USD = "1.0861"
    EUR = "1.0000"
    GBP = "0.6969"
```
But with HHVM off the result is correctly:
```
$_oldRate = {array}[1]
  EUR = {array}[3]
    EUR = "1.0000"
    GBP = "0.6969"
    USD = "1.0861"
```
I'm not sure were the unsupported PHP code is though, I thought it might be in *Mage_Adminhtml_Block_System_Currency_Rate_Matrix::prepareRates* but that function returns the array in the correct order. 

xDebug  also brought me into *Varien_Object::getData* were I found that `$this->_data` was also returning the `EUR` array in the wrong order but I'm not sure were to look next.

Any advice on how I can find the unsupported piece of PHP code would be appreciated.

In  [issues 3202](https://github.com/facebook/hhvm/issues/3202#issuecomment-128024603) @danslo commented that it may have something to do with [this inconsistency](https://github.com/facebook/hhvm/blob/4498e2b25bc17ace502b4c86c551dbab25f284bf/hphp/doc/inconsistencies#L15)

**Comment by danslo** [comment]
Does this happen with the latest nightly?

**Comment by rossmc** [comment]
@danslo, I'll check.  I've never used the latest nightly before. I suppose I just need to follow the instructions at [hhvm.com/blog/3203/nightly-packages](http://hhvm.com/blog/3203/nightly-packages).

Do you know can if/how I revert back to the HHVM version I'm on now afterwards, I would like to keep my local testing environment on the same as our production environment.

**Comment by danslo** [comment]
If you're using apt repos you can easily switch by just apt-get installing ``hhvm`` or ``hhvm-nightly``, they should replace eachother. I don't know what happens to stuff in ``/etc/hhvm/`` so you may want to back that up manually.

**Comment by rossmc** [comment]
@danslo  Thanks, do you mean something along the lines of:
```
mkdir ~/hhvm-bkup-0608/
sudo cp /etc/hhvm/ ~/hhvm-bkup-0608/
sudo apt-get remove hhvm
sudo add-apt-repository ppa:mapnik/boost
wget -O - http://dl.hhvm.com/conf/hhvm.gpg.key | sudo apt-key add -
echo deb http://dl.hhvm.com/ubuntu precise main | sudo tee /etc/apt/sources.list.d/hhvm.list
sudo apt-get update
sudo apt-get install hhvm-nightly
```
And to revert back to my original HHVM (v3.7.2):
```
sudo apt-get remove hhvm-nightly
sudo apt-get update
sudo apt-get install hhvm
sudo rm -rf /etc/hhvm/*
sudo cp ~/hhvm-bkup-0608/hhvm/* /etc/hhvm/
```

**Comment by danslo** [comment]
You shouldn't need the ``apt-get remove``, but yeah, something like that.

**Comment by rossmc** [comment]
@danslo that worked, thanks :)

So i'm guessing this was a bug that was recently fixed, any idea what it was?

I'm reluctant to put our production site on the latest nightly as it is too unstable  Any idea when it will be released into the next major release?  I could live with this bug for a while.

Also, When I run `sudo apt-get install hhvm` it replaces the latest nightly with v3.8.1 not 3.7.2 which I have on my server.  Anyway I can get back to 3.7.2, maybe I should just leave it at 3.8.1, no big deal.  Or put production onto 3.8.1.

By the way `/etc/hhvm/ ` did not get overwritten.

**Comment by danslo** [comment]
Sorry, no clue what it was. Happy it got fixed though. Does it also occur with 3.8?

**Comment by rossmc** [comment]
Yea, still occurring in 3.8, think I'll wait for it to be released in next stable version rather than use nightly on my production server.

**Comment by danslo** [comment]
3.9 should land somewhere [next week](https://github.com/facebook/hhvm/wiki/Release-Schedule).

**Comment by rossmc** [comment]
@danslo cool, thanks for your help :smiley:

**Comment by danslo** [comment]
:+1:
