### ISSUE TITLE
Segmentation Fault when replacing DomNode in Php

### ISSUE THREAD

**Issue by decanus** [facebook/hhvm#5863]
Code:
$aside->parentNode->replaceChild($aside->ownerDocument->importNode($sidebar->firstChild, true), $aside);

Error:
Uncaught exception 'ErrorException' with message 'Object of class DOMElement could not be converted to string' in /home/vcap/app/htdocs/GankedFrontend/src/Renderers/Snippets/AsideSnippetRenderer.php:68\nStack trace:\n#0 (): Ganked\\Skeleton\\ErrorHandlers\\AbstractErrorHandler->handleError()\n#1 /home/vcap/app/htdocs/GankedFrontend/src/Renderers/Snippets/AsideSnippetRenderer.php(68): DOMNode->replaceChild()\n#2 /home/vcap/app/htdocs/GankedFrontend/src/Renderers/Snippets/AbstractSnippetRenderer.php(34): Ganked\\Frontend\\Renderers\\AsideSnippetRenderer->doRender()\n#3 /home/vcap/app/htdocs/GankedFrontend/src/Renderers/Pages/AbstractPageRenderer.php(98): Ganked\\Frontend\\Renderers\\AbstractSnippetRenderer->render()\n#4 /home/vcap/app/htdocs/GankedFrontend/src/Controllers/PageControllers/AbstractPageController.php(94): Ganked\\Frontend\\Renderers\\AbstractPageRenderer->render()\n#5 /home/vcap/app/htdocs/GankedSkeleton/src/Controllers/AbstractController.php(52): Ganked\\Frontend\\Controllers\\AbstractPageController->run()\n#6 /home/vcap/app/htdocs/GankedSkeleton/src/FrontController.php(38): Ganked\\Skeleton\\Controllers\\AbstractController->execute()\n#7 /home/vcap/app/htdocs/GankedFrontend/index.php(14): Ganked\\Skeleton\\FrontController->run()\n#8 {main}

**Comment by paulbiss** [comment]
This looks like a PHP stack trace, do you have a C++ stacktrace for the segmentation fault? It would also be helpful if you had an isolated code snippet to cause the crash, it looks like the example above isn't complete.

**Comment by decanus** [comment]
$doc = new DomHelper('<doc hasUser="' . $hasUser . '" currentPath="' . $path . '"/>');
            $sidebar = $this->xslRenderer->render('templates://xsl/sidebar.xsl', $doc);

            $template->getFirstElementByTagName('body')->setAttribute('class', 'has-sidebar');
            $aside->parentNode->replaceChild($template->importNode($sidebar->documentElement, true), $aside);

**Comment by decanus** [comment]
That is the entire code that is run, I don't have a C++ stacktrace

**Comment by decanus** [comment]
Line 68 is the last line of the sent snippet. This is where the exception is thrown when running on HHVM. The error does not occur on the PHPVM

**Comment by paulbiss** [comment]
I need something I can run by itself, not the section of the code that's crashing. The above clearly isn't isolated ($aside isn't defined, $template isn't defined, the code is not wrapped in a method but $this is accessed, what is sidebar.xsl...). It's going to be a lot easier to find a fix if there's something short I can run on my own machine to reproduce the crash.

**Comment by decanus** [comment]
The easiest way would be if I add you to the repository where the code is. As the class has quite a few dependency injections.

**Comment by christer7208** [comment]
goog

**Comment by decanus** [comment]
https://raw.githubusercontent.com/Ganked/GankedFrontend/development/src/Renderers/Snippets/AsideSnippetRenderer.php?token=AHRMSf5p30plgDN7ne3La_OQAdN0JV8wks5V1CaQwA%3D%3D Here is the entire class, and here is sidebar.xsl https://raw.githubusercontent.com/Ganked/GankedFrontend/development/data/templates/xsl/sidebar.xsl?token=AHRMSUIFOkrKiET-NXT63PxV0N-QsQgtks5V1Ca6wA%3D%3D

**Comment by paulbiss** [comment]
This still isn't sufficiently disentangled to make it easy to test locally. If I get a chance I'll see what I can do with it though.
