### ISSUE TITLE
Hack: type checker doesn't complain about reserved classes

### ISSUE THREAD

**Issue by simonwelsh** [facebook/hhvm#5865]
I noticed this when running the hackificator, which lead to some code causing fatal errors when then run in HHVM, though no errors when running `hh_client`.

```hack
<?hh // strict

class String {}
```
```
$ hh_client
No errors!
$ hhvm test.php

Fatal error: Cannot use 'String' as class name as it is reserved in /home/simon/test/test.php on line 3
```

**Comment by jwatzman** [comment]
This is probably a case-sensitivity thing.

**Comment by simonwelsh** [comment]
Turns out there didn't appear to be any checks in place for the builtin types. There is for type hints (kinda, will open another bug for those) so I added in a new check in the same place as the current collision checking for names and types. Didn't do it for functions, so I don't thing those are in the same naming space.
