### ISSUE TITLE
DateTimeZone does not support GMT offsets on HHVM, while PHP does

### ISSUE THREAD

**Issue by stof** [facebook/hhvm#5875]
``` php
$a = new DateTimeZone('+03:00');

$b = new DateTimeZone('GMT+03:00');
```

both of these are supported on PHP 5.5+ but HHVM throws exception for both of them

**Comment by derickr** [comment]
Yes, this is a new feature in PHP 5.5.

**Comment by nicolas-grekas** [comment]
Since 5.5.10 in fact

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Hhvm has support for this feature too. I can't find the commit this was added in however.
```
object(DateTimeZone) (2) {
  ["timezone_type"]=>
  int(1)
  ["timezone"]=>
  string(6) "+03:00"
}
object(DateTimeZone) (2) {
  ["timezone_type"]=>
  int(1)
  ["timezone"]=>
  string(6) "+03:00"
}
```
