### ISSUE TITLE
Open-source hack lint

### ISSUE THREAD

**Issue by steelbrain** [facebook/hhvm#5891]
In my experience with other languages like Javascript, there are linters that have a few rules and style guidelines, and report when they are violated. I find them to be highly useful to stay consistent across the codebase.
It would be nice to have TypeChecker support/report them.
Side Question: What does `hh_format` do?

**Comment by paulbiss** [comment]
Hard hack errors for style issues would be way too aggressive IMO, but I believe we support linting now.

**Comment by Orvid** [comment]
Perhaps add an option to the `.hhconfig` to have it run the linter in addition to the typechecker and to report issues detected by that, optionally reporting them as errors?

**Comment by steelbrain** [comment]
@Orvid HHVM has a linter?

**Comment by fredemmott** [comment]
`hh_format` does consistent, opinionated (no options) formatting, eg `hh_format src/`. For example, it re-indents and adds trailing commas. I wouldn't recommend using it for a real project yet - I've not been able to without finding blocking issues (eg #5752)

**Comment by steelbrain** [comment]
@fredemmott Yeah `hh_format` is nice, but does it report the style nits to the user or does it fix them automatically? In later case, it would be nice to have a `--soft` option where it shows the changes to be done, instead of actually doing them.

**Comment by fredemmott** [comment]
- if given a directory, it automatically fixes them
 - if given a file, it will show the modified output

I suspect a pull request for --soft would be accepted, but an issue would be unlikely to be worked on as it would be re-implementing a feature that can be provided by any source-control system.

As for the linter:

```
hh_client --lint $(find . -name '*.php')
```

This appears to currently be a fairly useless stub in the OSS release. cc @int3 re any future plans

**Comment by milesj** [comment]
A linter that could detect PSR-1/2 would be nice. Something like CodeSniffer for Hack.

**Comment by fredemmott** [comment]
We're extremely unlikely to make a new linter - if we release one, it'll be the same one we use internally, which will be happy with hh_format's output. I have no idea how close that is to PSR-1/2.

**Comment by int3** [comment]
`hh_format` has a `--patch` option that allows the user to accept / reject its suggested style changes. Much like `git add -p`.

`--lint` is really meant for internal use only, to implement lint rules specific to our codebase. There are no plans to do make it do more. `hh_format` should be the way to enforce language rules and style guidelines.

**Comment by steelbrain** [comment]
@int3 the `--patch` option can solve my problem.
