### ISSUE TITLE
Wrong and bizarre behavior using 'max' with 'explode'

### ISSUE THREAD

**Issue by jmarrama** [facebook/hhvm#5901]
I have no idea whats going on here:

```
devVM:~/scratch/strtoI]$ cat t.php
<?php

function foo($bar)
{
  $parts = explode('-', $bar);
  $x = (int) $parts[0];
  $y = (int) $parts[1];
  $min = min($x, $y);
  $max = max($x, $y);
  var_dump($min);
  var_dump($max);
}


foo('30 - 40');
devVM:~/scratch/strtoI]$
devVM:~/scratch/strtoI]$ hhvm t.php
int(30)
int(30)
devVM:~/scratch/strtoI]$ hhvm --version
HipHop VM 3.9.0-dev (rel)
Compiler: heads/master-0-g139206c66f1298b352a2bed65cd1706382c73944
Repo schema: da39a3ee5e6b4b0d3255bfef95601890afd80709
devVM:~/scratch/strtoI]$
devVM:~/scratch/strtoI]$ php t.php
int(30)
int(40)
```

When I move this code out of the function, it works. When I replace the assignment of $parts with a static array, it works. When I comment out the 2 lines that reference $min, it works. When I don't assign anything to $min or $max and instead var_dump the results of the calls to the 'min' and 'max' functions directly, it works. Without digging in further, the best I can think of is that explode is returning something by reference when it shouldn't.

This was on HHVM compiled from HEAD this morning.

**Comment by jwatzman** [comment]
This is pretty weird. http://3v4l.org/5Dt0f says that HHVM gives the same (correct) output as PHP.

If you can still repro it, can you try changing whitespace, or adding a random comment, something that would change the unit hash? I'm curious if we've emitted and cached bad data or something.

> Compiler: heads/master-0-g139206c66f1298b352a2bed65cd1706382c73944

I can't find commit 139206c66f1298b352a2bed65cd1706382c73944 anywhere -- do you have some local changes?

**Comment by jmarrama** [comment]
> I can't find commit 139206c66f1298b352a2bed65cd1706382c73944 anywhere -- do you have some local changes?

I compile HHVM with a small patch that partially mutes recursive printing of closures to eliminate some negative effects of clowntown in our codebase. Otherwise, this is a clean build from head. I verified this problem also exists on a build without this patch.

I made sure to clean up the .hhbc bytecode file generated between runs. Adding whitespace doesn't change anything - this deterministically repros for me. Does this problem not exist on your internal build of HHVM?

**Comment by paulbiss** [comment]
It works fine with and without the jit on using our internal build.
```
devbig095:~ paulbiss$ php -j bar.php
int(30)
int(40)
devbig095:~ paulbiss$ php bar.php
int(30)
int(40)
devbig095:~ paulbiss$ php -j bar.php
int(30)
int(40)
devbig095:~ paulbiss$ zend bar.php
int(30)
int(40)
```

**Comment by Orvid** [comment]
Perhaps this is the result of some bug in GCC?

**Comment by jmarrama** [comment]
This bug isn't present in HHVM 3.8.1, running a git bisect on it now. I'm using GCC 4.8.1

**Comment by jwatzman** [comment]
> Otherwise, this is a clean build from head.

Just to be sure we're talking about the same thing, what git hash is HEAD for you right now? What OS are you on? If the bisect doesn't turn up anything, I'm curious if I'm able to repro myself in a similar env. (As above, our internal build, and 3v4l, don't show anything wrong... but I've seen weirder bugs :))

**Comment by jmarrama** [comment]
HEAD is https://github.com/facebook/hhvm/commit/c972a1f7be77474341cb6bea30096fa83f582e01 for me. I'm on scientific linux 6. I haven't tried out the nightly build on any other OSes yet - curious to know if this regression exists there. Fortunately, it seems to be deterministic on my build.

To be clear, 3v4l likely doesn't show this regression because it doesn't exist on HHVM 3.8.1 - AFAICT it doesn't run anything newer than 3.8.1.

**Comment by jwatzman** [comment]
OK, I can repro easily in an internal build... @paulbiss not sure why you didn't see it, I see it with fbcode rev f390e613a4debb9f745553fa0da743f5f401805f, let me try something newer and see if it got fixed.

**Comment by paulbiss** [comment]
@jwatzman: I was running release, didn't realize it was a recent regression at the time.

**Comment by jmarrama** [comment]
Will do @jwatzman, bisect should be done in about 2 hours.

**Comment by jwatzman** [comment]
@paulbiss ah that explains it.

Yeah, still happening on internal HEAD (fbcode 33e61566f2f2d49bd4d16969207b81d7d822de22).

- Does not seem to happen in interp mode (`-v Eval.Jit=false`)
- If you run it with `hhvm -m debug wtf.php`, and then just run that, it repros. If you `step` all the way through, even without printing anything, then it doesn't repro -- probably related to JIT vs interp again.

Will wait on the bisect, really curious what's up here.

**Comment by jmarrama** [comment]
@jwatzman @paulbiss Bisect complete, it points to https://github.com/facebook/hhvm/commit/2f8b50d14e720f72c1c369624a0c80110b102fea. Looks suspect.

**Comment by jwatzman** [comment]
@billf is looking into it -- thanks for the report!!

**Comment by jwatzman** [comment]
Fixed in master, and picked into the upcoming 3.9 release. Thanks a ton for the report!

**Comment by jmarrama** [comment]
My pleasure, thanks for the quick turnaround :+1: - venturing into the JIT internals would've been a rabbit hole
