### ISSUE TITLE
HHVM 3.8 aws build error at libfolly

### ISSUE THREAD

**Issue by vanderhoff** [facebook/hhvm#5908]
I am compiling HHVM 3.8 from source and am being blocked by the following errors.

    CMakeFiles/gen-class-map.dir/gen-class-map.cpp.o: In function `std::enable_if<std::is_floating_point<double>::value&&folly::IsSomeString<folly::basic_fbstring<char, std::char_traits<char>, std::allocator<char>, folly::fbstring_core<char> > >::value, void>::type folly::toAppend<folly::basic_fbstring<char, std::char_traits<char>, std::allocator<char>, folly::fbstring_core<char> >, double>(double, folly::basic_fbstring<char, std::char_traits<char>, std::allocator<char>, folly::fbstring_core<char> >*, double_conversion::DoubleToStringConverter::DtoaMode, unsigned int)':
    gen-class-map.cpp:(.text._ZN5folly8toAppendINS_14basic_fbstringIcSt11char_traitsIcESaIcENS_13fbstring_coreIcEEEEdEENSt9enable_ifIXaasrSt17is_floating_pointIT0_E5valuesrNS_12IsSomeStringIT_EE5valueEvE4typeESA_PSD_N17double_conversion23DoubleToStringConverter8DtoaModeEj[_ZN5folly8toAppendINS_14basic_fbstringIcSt11char_traitsIcESaIcENS_13fbstring_coreIcEEEEdEENSt9enable_ifIXaasrSt17is_floating_pointIT0_E5valuesrNS_12IsSomeStringIT_EE5valueEvE4typeESA_PSD_N17double_conversion23DoubleToStringConverter8DtoaModeEj]+0x483): undefined reference to `google::LogMessage::stream()'
    CMakeFiles/gen-class-map.dir/gen-class-map.cpp.o: In function `std::enable_if<std::is_floating_point<double>::value&&folly::IsSomeString<std::string>::value, void>::type folly::toAppend<std::string, double>(double, std::string*, double_conversion::DoubleToStringConverter::DtoaMode, unsigned int)':
    gen-class-map.cpp:(.text._ZN5folly8toAppendISsdEENSt9enable_ifIXaasrSt17is_floating_pointIT0_E5valuesrNS_12IsSomeStringIT_EE5valueEvE4typeES3_PS6_N17double_conversion23DoubleToStringConverter8DtoaModeEj[_ZN5folly8toAppendISsdEENSt9enable_ifIXaasrSt17is_floating_pointIT0_E5valuesrNS_12IsSomeStringIT_EE5valueEvE4typeES3_PS6_N17double_conversion23DoubleToStringConverter8DtoaModeEj]+0x158): undefined reference to `google::LogMessage::stream()'
    ../../../third-party/folly/libfolly.a(json.cpp.o): In function `folly::json::escapeString(folly::Range<char const*>, folly::basic_fbstring<char, std::char_traits<char>, std::allocator<char>, folly::fbstring_core<char> >&, folly::json::serialization_opts const&)':
    json.cpp:(.text._ZN5folly4json12escapeStringENS_5RangeIPKcEERNS_14basic_fbstringIcSt11char_traitsIcESaIcENS_13fbstring_coreIcEEEERKNS0_18serialization_optsE+0x353): undefined reference to `google::LogMessage::stream()'
    ../../../third-party/folly/libfolly.a(json.cpp.o): In function `folly::json::(anonymous namespace)::Printer::operator()(folly::dynamic const&) const':
    json.cpp:(.text._ZNK5folly4json12_GLOBAL__N_17PrinterclERKNS_7dynamicE+0x536): undefined reference to `google::LogMessage::stream()'
    ../../../third-party/folly/libfolly.a(dynamic.cpp.o): In function `folly::dynamic::typeName() const':
    dynamic.cpp:(.text._ZNK5folly7dynamic8typeNameEv+0xa0): undefined reference to `google::LogMessage::stream()'
    ../../../third-party/folly/libfolly.a(dynamic.cpp.o):dynamic.cpp:(.text._ZN5folly9TypeErrorC2ERKSsNS_7dynamic4TypeE+0x200): more undefined references to `google::LogMessage::stream()' follow
    collect2: error: ld returned 1 exit status
    make[2]: *** [hphp/tools/bootstrap/gen-class-map] Error 1
    make[1]: *** [hphp/tools/bootstrap/CMakeFiles/gen-class-map.dir/all] Error 2
    make[1]: *** Waiting for unfinished jobs....
    make: *** [all] Error 2

I am compiling on aws linux ami (latest) and am following these instructions

`https://github.com/facebook/hhvm/wiki/Building%20and%20installing%20HHVM%20on%20Amazon%20Linux%202014.03`

I have also compiled cmake 3.4 from source

I have the following in `hhvm/CmakeCache.txt`

     //Path to a file.
    LIBGLOG_INCLUDE_DIR:PATH=/usr/include
    
    //Path to a library.
    LIBGLOG_LIBRARY:FILEPATH=/usr/lib64/libglog.so

What am I missing to stop the above errors?

Thx Art

**Comment by jwatzman** [comment]
You might want to try compiling with `VERBOSE=1 make` to see if glog is passed into the linker. Unfortunately we don't support Amazon Linux officially, so it's unlikely anyone will be able to take a look at this.

**Comment by jwatzman** [comment]
You should also check to make sure `libglog` actually does exist in `/usr/lib64/libglog.so`.

**Comment by vanderhoff** [comment]
@jwatzman thanks for the pointers. Yes... does exist in /usr/lib64/libglog.so.... I ran the verbose=1, but  did not see anything different, am I doing it correctly?
VERBOSE=1 make -j5 EXTRA_INCLUDE_PATHS="/usr/include" EXTRA_LIB_PATHS="/usr/lib64" EXTRA_CC_FLAGS="-DHAVE_ELF_GETSHDRSTRNDX" && \

Thx again
Art

**Comment by jwatzman** [comment]
>  VERBOSE=1 make -j5 EXTRA_INCLUDE_PATHS="/usr/include" EXTRA_LIB_PATHS="/usr/lib64" EXTRA_CC_FLAGS="-DHAVE_ELF_GETSHDRSTRNDX" && \

Where are all those extra options coming from? The directions you linked in your original post includes none of this. Can you please include a full transcript of what exactly it is you're doing?

**Comment by vanderhoff** [comment]
After a rebuild of the AMI and using 3.9 the build now works. A few tweaks needed but seems stable now.
thanks  @jwatzman for the follow up enven though AWS is unsupported.

**Comment by jwatzman** [comment]
Glad it's working!
