### ISSUE TITLE
RFC: Hack magic properties

### ISSUE THREAD

**Issue by simonwelsh** [facebook/hhvm#5910]
It's a fairly common practice to have model classes use `__get` and __set` to provide access to the fields of the object rather than having to manually define getters and setters for every field on every model class.

However, Hack doesn't support this since it can't see the properties, so doesn't believe they exist. Currently, this means something in the inheritance tree (or a trait) has to be in PHP so that the type checker stops complaining.

My suggestion for a potential solution is to copy the `@property` attribute, but as a Hack attribute.

Something like:

``` hack
<?hh

<<__Property('myProp', int), __Property('myOtherProp', ?DateTime)>>
class MyModel extends Model {
  public function testing() {
    var_dump($this->myProp, $this->myOtherProp);
  }
}
```

where `Model` is also a Hack class which contains at least `__get`. Hack would then know that `MyModel->myProp` is an `int` and `MyModel->myOtherProp` is a nullable-DateTime even though the actual properties are never defined.

This would require `__get` to be defined in the ancestry of the class and trying to assign to one would require `__set`.

**Comment by jwatzman** [comment]
Yeah -- I don't think this is an unreasonable feature to have, I'm just not sure what the right version of this would look like. You're also not the first person to ask about it :)

cc @dlreeves FYI, we probably won't get around to this any time soon, but nice to keep track of.

**Comment by ClaudiuC** [comment]
Wouldn't an `.hhi` file be right solution for this?

**Comment by simonwelsh** [comment]
No. That requires Hack to not know about the implementation of the class, which means it has to be PHP.

**Comment by ClaudiuC** [comment]
You're right, I should've tested first. Wishful thinking... Something like `.hhi` files would be nicer IMO, especially when the magic methods handle a bunch of cases.

**Comment by kastermester** [comment]
Personally I would more love to have "proper" properties, drawing inspiration from C#:

```php
<?hh
class MyClass {
   // $myProp is an int with default getters and setters, not much different
   // from simply declaring it as a field
   public int $myProp { get; set; }

   private string $_myField;
   public string $myField {
      get { return $this->_myField; }
      // In the setter, accept a "magic" variable denoting the value to be set
      set { $this->_myField = $value; }
   }
}
```
This would allow one to use properties, without the uglyness of the magic methods. Also, `get` and `set` should support having different visibilities - such that you can have a property with a public `get` and `private`/`protected` `set`.

**Comment by lexidor** [comment]
Just chiming in, my two cents. I don't make decisions about direction hhvm should go in. I am not an hhvm engineer.

HHVM has dropped support for the `__get()` and `__set()` magic methods in hhvm [4.56.0](https://hhvm.com/blog/2020/05/04/hhvm-4.56.html).
This allows the runtime to know that `$x->prop = 4` will not invoke arbitrary Hack code.
(except for throwing a TypeError or invoking a PHP error handler if there is a runtime typemismatch, depending on the `hhvm.check_prop_type_hints` setting).

I don't know how much perf can be gained by having this axiom.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Support for the magic methods and dynamic properties have been removed from hhvm. The only cases where a property is defined in such a way to be invisible to Hack is in an extension. Those extensions can declare properties in hhi files without trouble.
