### ISSUE TITLE
foreach+switch no longer works on 3.8.1

### ISSUE THREAD

**Issue by staabm** [facebook/hhvm#5914]
behaviour of this small snippet changed in 3.8.1 while it was consistent with zend-php before:

```php
foreach(range(4,10) as $i) {
    echo $i;
    switch($i) {
        default: break 1;
    }
}
```

see http://3v4l.org/HM2du

**Comment by jwatzman** [comment]
Can you try a nightly build? I can't repro this locally on a recent master build, and so I strongly suspect it will be fixed in 3.9.

**Comment by staabm** [comment]
@jwatzman just found this inconsistency while trying samples for php on 3v4l.org. I dont have hhvm running on my dev box.

**Comment by paulbiss** [comment]
@staabm: I forced a rerun of the 3v4l input and it worked fine, I think sometimes it just falls over http://3v4l.org/HM2du
