### ISSUE TITLE
Why still allow `__destruct` in strict mode? About garbage collection.

### ISSUE THREAD

**Issue by olleharstedt** [facebook/hhvm#5915]
According to the Hack blog (http://hhvm.com/blog/431/on-garbage-collection), two things enforce the use of refcount in PHP: `__destruct` semantics and arrays + references. In strict mode you already removed the use of references. If you also remove `__destruct` or change its semantics to become non-deterministic, you could use any garbage collecting strategy. Have you considered this possibility?

**Comment by paulbiss** [comment]
It's something we've talked about, and may eventually do as part of our ongoing GC project. We'd obviously want to approach the problem carefully as it would definitely be a behavioral change in the language, one option is to make it switchable (the same way that running destructors on still-live objects at request end is an option).

**Comment by olleharstedt** [comment]
Sorry for taking up your time, but did you approximate a potential speed-up gain for switching from refcount to a tracing GC?

**Comment by fredemmott** [comment]
A major problem is that this would mean that the entire project would have to be strict, not just known to the typechecker - no partial or PHP libraries could be used.

**Comment by olleharstedt** [comment]
Isn't making the entire project strict impossible since no code is allowed outside classes in strict mode? How would you initiate your framework?

With PHP libraries, do you mean the standard library like `strlen`, `var_dump` etc, or other third-party libraries?

**Comment by fredemmott** [comment]
I meant other third-party libraries.

Given that strict needs to be used with non-strict files, banning destructors in strict would not be sufficient to allow the removal of refcounting.

**Comment by olleharstedt** [comment]
Got it, thanks for your feedback!

**Comment by paulbiss** [comment]
We'd probably need to ban it at the runtime level not the type-checker level anyway. A weaker check would be to have hhbbc determine if it's safe to enable the GC by looking for destructors with side-effects in repo mode.
