### ISSUE TITLE
InvariantException missing from HHI

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#5917]

**Comment by fredemmott** [comment]
Still an issue on 3.17 :'(

**Comment by shweaye810** [comment]
Hello @fredemmott, I am new here and I don't know what is require for this issue. I searched for the files and all I see in hhi/exceptions.hhi are just declaration of classes. 
https://github.com/facebook/hhvm/blob/master/hphp/hack/hhi/exceptions.hhi

Please provide more info.

**Comment by fredemmott** [comment]
HHIs are just declarations.

It should be declared both in the HHI and runtime:
 - in the HH namespace
 - and be automatically imported into every namespace in <?hh files, but not PHP (in a similar manner to Vector, Map, and so on)

**Comment by shweaye810** [comment]
Is there a way to reproduce the error? I tried the following, but typechecker doesn't say anything.

```
$ hhvm 5917.php 
test

Fatal error: Uncaught exception 'HH\InvariantException' with message 'foo' in /mnt/mnt_hdd/code/php/test/5917.php:4
Stack trace:
#0 {main}
shwe@shwe-linux-desktop test $ cat 5917.php 
<?hh

echo "test\n";
throw new InvariantException("foo");
```
Thank you.

**Comment by shweaye810** [comment]
Is there a way to reproduce the error? I tried the following, but typechecker doesn't say anything.

```
$ hhvm 5917.php 
test

Fatal error: Uncaught exception 'HH\InvariantException' with message 'foo' in /mnt/mnt_hdd/code/php/test/5917.php:4
Stack trace:
#0 {main}
shwe@shwe-linux-desktop test $ cat 5917.php 
<?hh

echo "test\n";
throw new InvariantException("foo");
```
Thank you.

**Comment by fredemmott** [comment]
The typechecker doesn't look  at pseudomain code. Put it in a function and switch to <?hh // strict

**Comment by shweaye810** [comment]
OK. got the `Unbound name: InvariantException (an object type)` error. InvariantException seems similar to LogicException. I found Logic Exception in
```
hhvm/hphp/hack/hhi/exceptions.hhi
hhvm/hphp/runtime/ext/spl/ext_spl.php
hhvm/hphp/system/php/spl/exceptions/exceptions.php
hhvm/hphp/system/systemlib.php
```
and add InvariantException as something similar to LogicException, but still got error. Any suggestion?
