### ISSUE TITLE
Could not find member ... in an object of type stdClass

### ISSUE THREAD

**Issue by tslettebo** [facebook/hhvm#5918]
Hi.

It seems the type checking has been tightened up in later versions of Hack, as I think this didn't give an error message before:

````
<?hh // strict

/* HH_FIXME[1002] */

echo f()->something; // Error: Could not find member something in an object of type stdClass (Typing[4053])

function f(): stdClass
{
  $object=new stdClass();

  $object->something="Test";

  return $object;
}

````
Is there a way to make this code pass in strict mode, other than using /* HH_FIXME[4053] */?

**Comment by paulbiss** [comment]
Why would you want to do this? It's not type-safe, so it really should make sense that you need the HH_FIXME.

**Comment by tslettebo** [comment]
The real code is more complex than this, involing setting dynamical properties from a database query.

In many cases, we can use objects with declared properties for this, but in some cases these objects are really nothing more than a collection of properties, and hence we've been using stdClass for them. What's more, the function returning an array of such objects needs to have some kind of signature.

Since we can't specify the type as a generic paramater, this approach doesn't work:

$object_array = $query_builder->get_list<SomeClass>(); // Return an array of SomeClass objects (invalid syntax)

class QueryBuilder
{
  public function get_list<T>(): T; // Not valid, can't deduce T
}

I guess one way might be to pass in a dummy object, and then clone it in the function:

class QueryBuilder
{
  public function get_list<T>(T $dummy): T;
}

I realise that shapes is one way to create something similar, but the syntax is different, using array syntax, rather than object syntax.

I guess one approach to avoid using the HH_FIXME workaround is to declare the class (even when it's only used in a single place) and then pass in an object of it to QueryBuilder::get_list().

Any other suggestions?

**Comment by paulbiss** [comment]
We recently added support for `classname<T>` (a string that the typechecker knows is the name of some class T), it's available in the nightlies and should be out in 3.9. You can use it like this:

```hh
class QueryBuilder {
  public function get_list<T>(classname<T> $cls): T {
     // ...
     return new $cls(/* ... */);
  }
}

$object_array = $query_builder->get_list(Foo::class);
```

**Comment by jwatzman** [comment]
Yep, I'd look into classname for this. We did tighten up the typechecking here, you can no longer use dynamic properties on `stdClass` in strict mode (since you could use it to violate type safety), partial mode is fine.

**Comment by tslettebo** [comment]
Thanks a lot for your replies. Yes, I agree that it makes sense to not allow dynamic properties on  `stdClass` in strict mode.

**Comment by tslettebo** [comment]
@jwatzman:
>class QueryBuilder {
>  public function get_list<T>(classname<T> $cls): T {
>     // ...
>     return new $cls(/* ... */);
>  }
>}
>
>$object_array = $query_builder->get_list(Foo::class);

I'm afraid this didn't work. I updated to the latest nightly build (3.10.0-dev), and added the class "Foo" as an empty class, but I get error messages.

Here's the code:

````
<?hh // strict

class Foo
{
}

class QueryBuilder
{
  public function get_list<T>(classname<T> $cls): T
  {
     return new $cls();
  }
}

$object_array = $query_builder->get_list(Foo::class);
````

Ignoring the top-level code issue, I get the following error messages.

test.php:11:13,22: Invalid return type (Typing[4110])
test.php:9:51,51: This is a value of generic type T
test.php:11:13,22: It is incompatible with an object; this class name is unknown to Hack

**Comment by jwatzman** [comment]
@int3 is that code above expected to work?

@tslettebo the code at at toplevel is invalid in strict, I wonder if that's confusing things.

**Comment by tslettebo** [comment]
@jwatzman the code at at toplevel is invalid in strict, I wonder if that's confusing things.

I've changed the code to correct this, and also, the $query_builder object wasn't created. Here's the corrected code:
```
<?hh // strict

class Foo
{
}

class QueryBuilder
{
  public function get_list<T>(classname<T> $cls): T
  {
     return new $cls();
  }
}

function f(): void
{
  $object_array = (new QueryBuilder())->get_list(Foo::class);
}
```

It still gives the same error messages:

test.php:11:13,22: Invalid return type (Typing[4110])
test.php:9:51,51: This is a value of generic type T
test.php:11:13,22: It is incompatible with an object; this class name is unknown to Hack

**Comment by simonwelsh** [comment]
@tslettebo `T` isn't constrained, so could be a primitive. You'll need a common parent class/interface to constraint to, then:
```hack
<?hh // strict

class QueryBuilder
{
  public function get_list<T as Foo>(classname<T> $cls): T
  {
     return new $cls();
  }
}
```
(assuming `Foo` is the common base class)

**Comment by fredemmott** [comment]
You also need <<__ConsistentConstruct>> on the base class

**Comment by tslettebo** [comment]
Thanks for the information.
