### ISSUE TITLE
DNS cache feature (and config option)

### ISSUE THREAD

**Issue by dpaneda** [facebook/hhvm#5927]
The DNS cache feature documented on the HDF description seems not to be available anymore.

If you have a lot of threads and the DNS resolutions are common, the performance is degraded because on gethostbyname_r the thread safety is implemented with a global lock (at least on the squeeze version), so all the DNS resolution are serialized, which could lead to some serious contention on the server.

Is there any workaround about this?

We have a DNS cache implemented for the HPHP version, which should be easy to port it to the current version. Would you accept a pull request of that feature?

**Comment by jwatzman** [comment]
@paulbiss do you know if this was deliberately removed or something, it sounds like it used to exist. I guess our web frontends probably don't do too many DNS queries that require going out of the cluster, they're probably really fast.

In any event, I expect we'd take a PR for this, if it weren't too invasive, and maybe off by default?

**Comment by dpaneda** [comment]
AFAIK the feature never moved out of experimental. I also remember that the implementation was not good enough for us, but I don't recall what was the issue with it. Maybe it was just broken at that moment.

Good to know that the PR have a good chance on being accepted. I'll work on it and let you know.

**Comment by fredemmott** [comment]
Why is this useful/why should this be an HHVM feature, instead of just running a caching dns server (eg dnsmasq)?

**Comment by dpaneda** [comment]
A local DNS cache resolver does not solve the thread contention problem present on the libc. 

We use pdnsd, and it obviously helps, but more at a network level, to avoid our internal DNS server to be continuously hit by the same requests.

You can even populate your hosts file with your most frequent resolved hostnames, and you still reach thread contention with enough DNS resolutions & threads, because only one thread could be on the critical section.

**Comment by dpaneda** [comment]
PR created 
https://github.com/facebook/hhvm/pull/6068

**Comment by paulbiss** [comment]
From the comments on the PR it looks as though this is resolved.
