### ISSUE TITLE
Audit missing <<__HipHopSpecific>>

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#5931]
Needed for documentation.

Here's an automatically-generated list: https://gist.github.com/fredemmott/239c7d2b3dcb4236ef8c

Generated by https://github.com/hhvm/user-documentation/blob/master/bin/dump-unmarked-hh-specific.php - everything in systemlib or an extension that isn't marked HipHopSpecific, and isn't in the HH or __SystemLib namespace.

Has false positives because of extensions that aren't enabled by default in php5.

**Comment by fredemmott** [comment]
If we want to re-check this periodically, maybe we should also support a <<DocTag(FromPHP)>> annotation for the non-default ones?

**Comment by fredemmott** [comment]
Updated list: https://gist.github.com/fredemmott/3ddaec47975c279b070e

I've removed every function that starts with 'fb_', 'hphp_', has generics, or returns an awaitable

**Comment by fredemmott** [comment]
We can also keep a whitelist in the documentation repository - that might be better.

**Comment by JoelMarcey** [comment]
I can send out a diff explicitly annotating these things as <<__HipHopSpecific>>. They should be annotated correctly anyway for anyone reading the code, right?

For classes, e.g., something like AsyncMysqlClient, the class in and of itself isn't marked <<__HipHopSpecific>>, but all of its methods (except the constructors??) are. In general, wouldn't it make more sense to mark the class as <<__HipHopSpecific>> and that means everything in the class inherits that attribute?

**Comment by fredemmott** [comment]
Yep, the class itself should be marked.

**Comment by JoelMarcey** [comment]
I guess what I am asking is if we mark the class, can we remove the attribute from all the methods because they are inherited from the class attribute. That makes logical sense, right?

**Comment by fredemmott** [comment]
Yeah, it should be unneccessary - same way we don't require it on stuff in the HH namespace

Relatedly, AsyncMysqlClient should be moved to the HH namespace, but that's a bigger and less-safe change, so shouldn't block the doc work.

**Comment by JoelMarcey** [comment]
Docs worked around this issue. We still want to move `AsyncMysqlClient` and friends to the `HH\` namespace.
