### ISSUE TITLE
The 'rand' function is broken

### ISSUE THREAD

**Issue by jmarrama** [facebook/hhvm#5936]
```php
<?php
function printRand() {
  echo rand(0, PHP_INT_MAX)."\n";
  echo rand(0, PHP_INT_MAX)."\n";
  echo rand(0, PHP_INT_MAX)."\n";
}
printRand();
```

On HHVM compiled from HEAD yesterday and normal PHP:
```
devVM:~/scratch/rand]$ hhvm t.php
0
0
0
devVM:~/scratch/rand]$ php t.php
5178777638877003776
5946940850528321536
1598496701977460736
```

This problem is not present in HHVM 3.7.

**Comment by jmarrama** [comment]
Note that rand() gives random numbers back for values of $max much smaller than PHP_INT_MAX, but they are often out of bounds. However, if a $max is used less than 2^31, you always get a number between $min and $max. This seems like an int overflow problem.

**Comment by jwatzman** [comment]
@paulbiss you briefly were looking into this; did you figure it out, or should I take it?

**Comment by paulbiss** [comment]
It's almost certainly related to e2a16e66d8fa68c2020c4f9bd53f2513774fac33

**Comment by paulbiss** [comment]
Yep, that's it, we're using a 32-bit number now. I'll put up a fix.
```
int32_t number;
```

**Comment by Orvid** [comment]
As a random question, is there any reason we need to use the C functions for this? Would it be reasonable to use `std::random` instead? With `std::random` I don't have to pull in implementations, or implement them myself, as MSVC does implement `std::random` properly.

**Comment by paulbiss** [comment]
Hmm, does std::random() have the same behavior as C random() on linux systems? I don't feel strongly but it would probably be preferable if HHVM and PHP generated the same pseudorandom sequence given the same seed.

All things being equal I'm going to fix this without switching to the C++ api so we can merge it into 3.9, I'd be open to a pull request to switch to std::random.

**Comment by Orvid** [comment]
It doesn't overflow now, but it isn't going to generate anything above the max of an int32 is it?

**Comment by paulbiss** [comment]
That's what the RAND_RANGE macro does... It doesn't do it very well, and is the source of [this](https://www.facebook.com/147594855443853/photos/a.255658437970827.1073741828.147594855443853/334443516758985) gem.
