### ISSUE TITLE
Can ini config set Image Magick path？

### ISSUE THREAD

**Issue by AssemblyXiang** [facebook/hhvm#5998]
I am not set  it in cmake.

**Comment by Orvid** [comment]
If HHVM was built without the imagick extension, no ini setting will be able to do anything to enable it.

You should be able to set the paths in CMake via `LIBMAGICKWAND_INCLUDE_DIRS`, `LIBMAGICKWAND_LIBRARIES` and `LIBMAGICKCORE_LIBRARIES`. All 3 of these variables need to be set for the extension configuration mechanism to let you enable the imagick extension.

**Comment by AssemblyXiang** [comment]
@Orvid Thanks for reply.
