### ISSUE TITLE
Implement engine exceptions

### ISSUE THREAD

**Issue by tonygaillard** [facebook/hhvm#6012]
Fatal error catchable in HVMM, this result in the execution of the code after the fatal error, whereas PHP stop the execution. Example:

```php
<?php
$bite = null;
try
{
    $bite->hello();
}
catch (Exception $e)
{
    var_dump($e->getMessage());
}
echo "OK";
```

the echo "OK" part is not supposed to be executed in this situation. But in HHVM the output is the following:

string(56) "Call to a member function hello() on a non-object (NULL)"
OK

http://3v4l.org/ngiRa

**Comment by sandeepone** [comment]
You're running in try/catch block. So the output is correct. ````echo "OK"; ``` will execute, since the error is catches in the catch block, so it prints error and runs the next part of code. If you don't want to proceed to next line, ```throw new error```` in the catch block to stop.

**Comment by SiebelsTim** [comment]
@sandeepone No, the difference is, that HHVM throws a `BadMethodCallException` while PHP 7 throws an `Error` object.

**Comment by jwatzman** [comment]
Yeah, the right fix is to implement the proper PHP7 RFC (which will have the side effect of not making the resultant exception extend `Exception`).

https://wiki.php.net/rfc/engine_exceptions_for_php7

**Comment by jwatzman** [comment]
The hard part here is auditing where exactly these exceptions are thrown, what HHVM does with them now (which mostly, but not 100%, matches PHP5), and which ones need to be changed for PHP7.
