### ISSUE TITLE
HHVM takes long time to execute request if it was idle for a time, how to solve?

### ISSUE THREAD

**Issue by steffenbrem** [facebook/hhvm#6013]
Hi,

I have installed HHVM nightly with Nginx 1.9.x (FastCGI) and once the cache is warm, it is working perfect (response time `~30ms`). But when HHVM is idle for some time (~ 20-30 seconds) it seems to ignore the cache it he response time raises to around `250ms`. Why doesn't it stay fast? Am I missing an important configuration setting? For development this is fine, but for in production it can be quite annoying for the end-users.

This is my `php.ini`
```
; php options
date.timezone="UTC"
session.save_handler = files
session.save_path = /var/lib/hhvm/sessions
session.gc_maxlifetime = 1440

; hhvm specific
hhvm.log.level = Warning
hhvm.log.always_log_unhandled_exceptions = true
hhvm.log.runtime_error_reporting_level = 8191
hhvm.mysql.typed_results = false

hhvm.libxml.ext_entity_whitelist = file,http
```

And my `server.ini`:
```
; php options

pid = /var/run/hhvm/pid

; hhvm specific


hhvm.server.port = 9000
hhvm.server.type = fastcgi
hhvm.server.default_document = index.php
hhvm.log.use_log_file = true
hhvm.log.file = /var/log/hhvm/error.log
hhvm.repo.central.path = /var/run/hhvm/hhvm.hhbc

hhvm.jit = true
hhvm.jit_a_size = 256000000
hhvm.jit_a_cold_size = 256000000
hhvm.jit_a_max_usage = 256000000

hhvm.server.thread_count = 2
```

**Comment by paulbiss** [comment]
Hmm, this definitely sounds unusual. Is there anything else happening while the server is idle (something or someone updating the source files for instance)?

**Comment by steffenbrem** [comment]
@paulbiss No I deploy my code as a Docker image on AWS Elastic Beanstalk to be exact. And after that nothing is touching the code (only the production cache folder is being build one time, but after that is is unmodified). I also tried using RepoAuthoritative, but I got some dynamic things going so that is impossible to use for me unfortunately.

If it may help, my PHP stack is `Symfony 2` and `Doctrine` along with some other smaller libraries.

**Comment by steffenbrem** [comment]
The problem seems to have fixed itself. After another deployment, it is more stable and I only get an initial performance hit, which is normal. Then my most heavy request takes `75-100ms` instead of the previous `250ms` sometimes, even if I wait for 20-30 seconds. So I guess it is solved now.. No clue what's different this time.
