### ISSUE TITLE
UTF-8 preg_split non performant in HHVM

### ISSUE THREAD

**Issue by ishouldstudy** [facebook/hhvm#6014]
Hello,

Our server currently encrypts UTF-8 strings by running each character through a dictionary before returning response. We have been using mbstring functions to split the UTF-8 multibyte characters, but it turns out these functions become incredibly non performant as string length increases, with time cost increasing exponentially.

An oft-proposed alternative function for splitting multibyte characters is preg_split:

	
	preg_split('//u', $input, null, PREG_SPLIT_NO_EMPTY);

In base php, this function is much much more efficient with a O(n) linear cost curve. However, the same function in HHVM has an exponential time cost with increasing n, so it's unworkable for our purposes. The performance logs and test code can be found below.

Has anyone encountered this issue before, and if so, what workaround or alternative did you use? For reference, we are using version 2.4.0-dev but upgrading would not necessarily be a workable solution.

Thanks!
Dan

Test Code:

	<?php

	$testString = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nibh quam, ornare eu arcu vel, placerat tempus quam. Fusce vitae semper nulla, a faucibus dui. Quisque tempus tortor in viverra amet.";
	$testString = str_repeat($testString, 15);

	mb_internal_encoding('UTF-8');
	mb_regex_encoding('UTF-8');

	function encode($input) {
	    $inputArray = preg_split('//u', $input, null, PREG_SPLIT_NO_EMPTY);

		return;
	}

	function encodeMbfunctions($input) {
		for ($i = 0, $c = mb_strlen($input) ; $i < $c ; ++$i) 
	    {
	        $current = mb_substr($input, $i, 1);
	    }

	    return;
	}

	$totalString = '';
	$testDuplications = 20;
	$startTime = microtime(true);
	for ($i = 1; $i <= $testDuplications; $i++)
	{
		$totalString .= $testString;
		$testTimeStart = microtime(true);

		// preg_split
		$encryptedString = encode($totalString);
		
		// mbstring functions
		// $encryptedString = encodeMbfunctions($totalString);
		
		$postEncryptionTime = microtime(true);
		$totalLength = strlen($totalString);

		$timeTaken = $postEncryptionTime - $testTimeStart;

		echo "\n$i: ". round( 1000*($timeTaken / $totalLength), 5 ) . " seconds per 1000 characters. total characters: " . $totalLength;
	}

BASE php UTF-8 preg_split performance
1: 0.00088 seconds per 1000 characters. total characters: 3000
2: 0.00073 seconds per 1000 characters. total characters: 6000
3: 0.00078 seconds per 1000 characters. total characters: 9000
4: 0.0008 seconds per 1000 characters. total characters: 12000
5: 0.0008 seconds per 1000 characters. total characters: 15000
6: 0.00082 seconds per 1000 characters. total characters: 18000
7: 0.00082 seconds per 1000 characters. total characters: 21000
8: 0.00082 seconds per 1000 characters. total characters: 24000
9: 0.00082 seconds per 1000 characters. total characters: 27000
10: 0.00082 seconds per 1000 characters. total characters: 30000
11: 0.00087 seconds per 1000 characters. total characters: 33000
12: 0.00085 seconds per 1000 characters. total characters: 36000
13: 0.00085 seconds per 1000 characters. total characters: 39000
14: 0.00085 seconds per 1000 characters. total characters: 42000
15: 0.00085 seconds per 1000 characters. total characters: 45000
16: 0.00097 seconds per 1000 characters. total characters: 48000
17: 0.00085 seconds per 1000 characters. total characters: 51000
18: 0.00085 seconds per 1000 characters. total characters: 54000
19: 0.00084 seconds per 1000 characters. total characters: 57000
20: 0.00105 seconds per 1000 characters. total characters: 60000

HHVM UTF-8 preg_split performance
1: 0.00356 seconds per 1000 characters. total characters: 3000
2: 0.00644 seconds per 1000 characters. total characters: 6000
3: 0.00947 seconds per 1000 characters. total characters: 9000
4: 0.01251 seconds per 1000 characters. total characters: 12000
5: 0.01567 seconds per 1000 characters. total characters: 15000
6: 0.01965 seconds per 1000 characters. total characters: 18000
7: 0.02146 seconds per 1000 characters. total characters: 21000
8: 0.02524 seconds per 1000 characters. total characters: 24000
9: 0.02764 seconds per 1000 characters. total characters: 27000
10: 0.03145 seconds per 1000 characters. total characters: 30000
11: 0.03427 seconds per 1000 characters. total characters: 33000
12: 0.03709 seconds per 1000 characters. total characters: 36000
13: 0.04055 seconds per 1000 characters. total characters: 39000
14: 0.04343 seconds per 1000 characters. total characters: 42000
15: 0.04617 seconds per 1000 characters. total characters: 45000
16: 0.04981 seconds per 1000 characters. total characters: 48000
17: 0.05259 seconds per 1000 characters. total characters: 51000
18: 0.0557 seconds per 1000 characters. total characters: 54000
19: 0.05875 seconds per 1000 characters. total characters: 57000
20: 0.0616 seconds per 1000 characters. total characters: 60000

BASE php mbstring functions performance
1: 0.00962 seconds per 1000 characters. total characters: 3000
2: 0.01881 seconds per 1000 characters. total characters: 6000
3: 0.02778 seconds per 1000 characters. total characters: 9000
4: 0.03692 seconds per 1000 characters. total characters: 12000
5: 0.0461 seconds per 1000 characters. total characters: 15000
6: 0.0552 seconds per 1000 characters. total characters: 18000
7: 0.06425 seconds per 1000 characters. total characters: 21000
8: 0.07343 seconds per 1000 characters. total characters: 24000
9: 0.08257 seconds per 1000 characters. total characters: 27000
10: 0.09176 seconds per 1000 characters. total characters: 30000
11: 0.1011 seconds per 1000 characters. total characters: 33000
12: 0.11003 seconds per 1000 characters. total characters: 36000
13: 0.1193 seconds per 1000 characters. total characters: 39000^C
14: ... test manually terminated ...

HHVM mbstring functions performance
1: 0.02596 seconds per 1000 characters. total characters: 3000
2: 0.05142 seconds per 1000 characters. total characters: 6000
3: 0.08008 seconds per 1000 characters. total characters: 9000
4: 0.10386 seconds per 1000 characters. total characters: 12000
5: 0.13004 seconds per 1000 characters. total characters: 15000
6: 0.15602 seconds per 1000 characters. total characters: 18000
7: 0.18128 seconds per 1000 characters. total characters: 21000^C
8: ... test manually terminated ...

**Comment by ehcpdeveloper** [comment]
I have seen similar performance issues with such string functions. preg_replace etc. in past. 
But I cannot provide sample code now.

**Comment by wjywbs** [comment]
perf showed that 98% of the time hhvm was running _pcre_valid_utf. Comparing php-src and hhvm's preg_split code, php sets PCRE_NO_UTF8_CHECK regardless of the count (php_pcre.c lines 1778 and 1840), which hhvm only sets this option when count is greater than 0 and does not use this option in the 2nd pcre_exec after PCRE_ERROR_NOMATCH (preg.cpp lines 1665 and 1724).

https://github.com/php/php-src/blob/896cb514995ff98cb03257d88fc7b55aab5186f9/ext/pcre/php_pcre.c#L1778
https://github.com/facebook/hhvm/blob/ebb75b2cf901545422ec9a68c47bd07cda57bbc4/hphp/runtime/base/preg.cpp#L1665

After changing hhvm to have the same preg_split behavior as php, I got this output:
1: 0.00141 seconds per 1000 characters. total characters: 3000
2: 0.00041 seconds per 1000 characters. total characters: 6000
3: 0.00019 seconds per 1000 characters. total characters: 9000
4: 0.00019 seconds per 1000 characters. total characters: 12000
5: 0.00023 seconds per 1000 characters. total characters: 15000
6: 0.0002 seconds per 1000 characters. total characters: 18000
7: 0.00019 seconds per 1000 characters. total characters: 21000
8: 0.0002 seconds per 1000 characters. total characters: 24000
9: 0.00021 seconds per 1000 characters. total characters: 27000
10: 0.00019 seconds per 1000 characters. total characters: 30000
11: 0.00018 seconds per 1000 characters. total characters: 33000
12: 0.00018 seconds per 1000 characters. total characters: 36000
13: 0.00019 seconds per 1000 characters. total characters: 39000
14: 0.0002 seconds per 1000 characters. total characters: 42000
15: 0.00018 seconds per 1000 characters. total characters: 45000
16: 0.00018 seconds per 1000 characters. total characters: 48000
17: 0.0002 seconds per 1000 characters. total characters: 51000
18: 0.0002 seconds per 1000 characters. total characters: 54000
19: 0.00018 seconds per 1000 characters. total characters: 57000
20: 0.0002 seconds per 1000 characters. total characters: 60000

**Comment by wjywbs** [comment]
By the way, hhvm's mb_substr is slower than php's as shown in your benchmark because hhvm always calculates the length of the string (lines 2287, 2316 and 2320), while php only calculates it conditionally (lines 2800 and 2823). And php doesn't call mbfl_strlen in this case, which is 60% faster.

https://github.com/php/php-src/blob/4a2e40bb861bc3cf5fb6863e57486ed60316e97c/ext/mbstring/mbstring.c#L2800
https://github.com/facebook/hhvm/blob/f818e1aaf77bfaf49551c7c6fc4937e66ffd491b/hphp/runtime/ext/mbstring/ext_mbstring.cpp#L2287

**Comment by ishouldstudy** [comment]
Awesome, thanks wjywbs! I think we'll take your recommendation on reverting hhvm behavior to php then recompile. Would you be willing to share your changed code lines?
