### ISSUE TITLE
Hack: Redefining members not being detected

### ISSUE THREAD

**Issue by simonwelsh** [facebook/hhvm#6016]
``` hack
<?hh
abstract class A {
    protected string $name;
}
class B extends A {
    protected string $name = 'Hello';
}
```

```
$ hh_single_type_check test.php 
File "test.php", line 7, characters 7-7:
Class B does not initialize all of its members; name is not always initialized.
Make sure you systematically set $this->name when the method __construct is called.
Alternatively, you can define the member as optional (?...)
 (NastCheck[3015])
```

However, `B` is clearly initialising `$name`, just not the one explicitly defined on `A`

**Comment by jwatzman** [comment]
@int3 can you figure out if this should be an error? It's actually not clear to me either way. cc @dlreeves

**Comment by simonwelsh** [comment]
The actual use case I'm trying to do here:

```hack
<?hh

abstract class A<T as C> {
  protected classname<T> $_className;
}

class B extends A<C_SubClass> {
  protected classname<C_SubClass> $_className = C_SubClass::class;
}
```

So, if this is a bug, a nicer way of writing the `$_className` in the child class would be nice too ;)

**Comment by simonwelsh** [comment]
@int3 Any update on this?

**Comment by dlreeves** [comment]
@simonwelsh - for your particular use case can't you use a constant instead of a property?

```hack
<?hh

abstract class A<T as C> {
  abstract const classname<T> CLASSNAME;
}

class B extends A<C_SubClass> {
  const classname<C_SubClass> CLASSNAME = C_SubClass::class;
}
```

**Comment by simonwelsh** [comment]
@dlreeves took a while, but finally back to working on this part of code. Using a constant does work in this case :)

**Comment by muglug** [comment]
This _shouldn't_ be an issue – at least, it executes fine in HHVM/PHP

**Comment by simonwelsh** [comment]
This now type checks
