### ISSUE TITLE
DOMDocument.saveXML() output not pretty

### ISSUE THREAD

**Issue by niedzielski** [facebook/hhvm#6034]
We use SimpleXMLElement to build Android string translations which we output to a file[0]:

    $dom = new DOMDocument( '1.0' );
    $dom->formatOutput = true;
    $dom->loadXML( $writer->asXML() );
    echo $dom->saveXML();

In 3.6.5+dfsg1-1+wm1, this produced nice XML. e.g.:

    <?xml version="1.0" encoding="utf-8"?>
    <resources>
      <string name="key" fuzzy="true">value</string>
      <string name="anotherkey">anothervalue</string>
    </resources>

In 3.8.1, all the newlines and whitespace are stripped to produce a minified but difficult to read output:

    <?xml version="1.0" encoding="utf-8"?>
    <resources><string name="key" fuzzy="true">value</string><string name="anotherkey">anothervalue</string></resources>

We're currently tracking this issue for translatewiki.net and the Wikipedia Android app here[1].

[0] Full source example here: https://3v4l.org/OjDaB
[1] https://phabricator.wikimedia.org/T109402

**Comment by paulbiss** [comment]
The formatOutput setting is getting cleared by the call to loadXML. I'll put up a fix for this.

**Comment by niedzielski** [comment]
Thanks, @paulbiss! I've updated our Phabricator ticket[0].

[0] https://phabricator.wikimedia.org/T109402
