### ISSUE TITLE
Context sensitive lexer

### ISSUE THREAD

**Issue by jwatzman** [facebook/hhvm#6036]
https://wiki.php.net/rfc/context_sensitive_lexer

No particular gotcha's here.

**Comment by jwatzman** [comment]
And we can just do this in PHP5 mode too.

**Comment by jwatzman** [comment]
Internal task: 7687131

**Comment by alexchow** [comment]
Taking a stab at this.

**Comment by jwatzman** [comment]
https://github.com/facebook/hhvm/commit/322dd29f8cdbc443459791d8dd2ef9c772c96376 (forgot to mark that commit as closing this)

**Comment by alexchow** [comment]
There's still `die` that we don't deal well with. Should we reopen this? Or a new issue?

**Comment by jwatzman** [comment]
Oops, yeah let's reopen this

**Comment by jwatzman** [comment]
@alexchow were you planning on coming back to `die`?

**Comment by alexchow** [comment]
Yup! hopefully later this week.

**Comment by JoelMarcey** [comment]
Assigning `facebook-github-bot` for those that are claimed, but cannot be directly assigned to the user.

I assume @alexchow that you are still working on this?

**Comment by jwatzman** [comment]
@alexchow what's the status of this?

**Comment by alexchow** [comment]
My attempt at getting die working failed (I tried to make it into its own T_DIE token and have token_get_all translate back to the old token) and I got HHVM to segfault. Then I abandoned that work a long time ago. Probably not getting back to this.

**Comment by jwatzman** [comment]
OK -- so this is like 98% done, if someone cares they can come along and fix it or yell at us to fix it :)

**Comment by jails** [comment]
PHP7 is becoming a popular PHP version and this issue stops new libraries to be compatible with HHVM. Is there some plan to add full PHP>=7 support for HHVM ?

**Comment by jwatzman** [comment]
@jails The core PHP7 features have been in HHVM for over a year if you enable PHP7 mode ([see this blog post](http://hhvm.com/blog/10859/php-7-support)). The only thing remaining in this task is specific to the `die` keyword, which I'd be somewhat surprised if it were causing serious issues out in the real world. (Though I've been surprised before!)

If `die` is causing problems, that's useful to know, please comment here with a link to the library. If it's some other problem, please do feel free to [raise a new issue](https://github.com/facebook/hhvm/issues/new).

**Comment by jails** [comment]
Ah you're right it's working, thank you for the head up @jwatzman !
I think this issue can be closed :+1:

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

The hhvm and hackC lexers are indeed context sensitive.
You are allowed to create methods with the names `foreach` and `list`.
