### ISSUE TITLE
Anonymous classes

### ISSUE THREAD

**Issue by jwatzman** [facebook/hhvm#6039]
https://wiki.php.net/rfc/anonymous_classes

This is going to be somewhat tricky both in HHVM and in the typechecker... we should probably discuss if we _want_ it in the typechecker (and thus in Hack). I suspect people will want it though, if not at FB definitely externally.

**Comment by jwatzman** [comment]
Hack team, is this something you're interested in taking on, in the runtime and/or in the typechecker?

**Comment by int3** [comment]
I'm interested in taking on both parts. Might take 1 month+ though as I am simultaneously working on other stuff.

**Comment by jwatzman** [comment]
@int3 okay, I'm going to mark this one as assigned to you then. If you think you aren't going to be able to get at least the runtime portion done by, say, November, please let me know as soon as you know that -- this is on the critical path for PHP7 compatibility, which we want done by about that timeframe, and furthermore this would be a good candidate for a hackamonth but I won't submit it since you want it :)

**Comment by dlreeves** [comment]
So thinking about type checker support one thing we will need to think about is how to express the type of an anonymous class. For instance

```hack
function myclass(): ??? {
  return new class {
    public function x(): int {
      return x;
    }
  };
}
```

What would we write for the type of ???. Scala solves this with [structural/refinement types](https://twitter.github.io/scala_school/advanced-types.html#structural).

We can do close to the same thing in this case.

```hack
function myclass(): class { function x():int; } {
  return new class {
    public function x(): int {
      return x;
    }
  };
}
```

Or if it is a refinement of an interface or class then it would be

```hack
interface I {}

function myclass(): I { function x(): int } {
  return new class implements I {
    public function x(): int {
      return x;
    }
  };
}
```

This is something I have been thinking about adding anyways as a complement to type constants as well, i.e.

```hack
interface I {
  abstract const type T;
}

function expects_I_of_int(I {type T = int} $x): ??? {
  return new class {
    public function x(): int {
      return x;
    }
  };
}
```

In terms of the changes we will actually need to make in the type checker we would need to have a type that carries around the `class_type` object. I'm not sure if we would need to change all `Tclass` to work in this way or not.

**Comment by jwatzman** [comment]
The HHVM side of this was done in cb5b17a52c27414647d0c5a6cbbe1c48597ab8b9

**Comment by jesseschalken** [comment]
I imagine the easiest way to implement this in the typechecker would be to give each anonymous class an automatic name, like `anon_in_Foo_php_L16` for the anonymous class in Foo.php on line 16. Then typechecking can proceed normally as if the class was defined at the top-level, and you have a name to use in errors which the developer can understand.

This would permit all of the public interface of an anonymous class to be used locally, eg:

```hack
interface Bar {
  public function barMethod():void;
}
interface Foo {
  public function fooMethod():void;
}
function main():void {
  $obj = new class implements Foo, Bar {
    public function barMethod():void { print "bar\n"; }
    public function fooMethod():void { print "foo\n"; }
    public function otherMethod():void { print "other\n"; }
  };
  $obj->barMethod();
  $obj->fooMethod();
  $obj->otherMethod();
}
```

Hack would see `$obj` as type `anon_in_main_php_L8` which has all three methods.

But when it comes to this example:

```hack
function myclass(): ??? {
  return new class {
    public function x(): int {
      return x;
    }
  };
}
```

I think it's reasonable to expect that if the developer wants to utter their anonymous class as a type, they have to give it a name.

Usually an anonymous class is used for a one-time implementation of a specific abstract class or interface, and so the type of the anonymous class doesn't need to be uttered, the type of the class/interface it extends does.

Here is a motivating example of anonymous classes involving visitors. Note that the concrete anonymous class never needs to be mentioned as a type.

```hack
abstract class Value {
  public abstract function accept<T>(ValueVisitor<T> $visitor):T;
}

interface ValueVisitor<+T> {
  public function visitString(string $s):T;
  public function visitInt(int $i):T;
  // ..
}

function int_value(int $i):Value {
  return new class ($i) extends Value {
    public function __construct(private int $i) {}
    public function accept<T>(ValueVisitor<T>  $v):T { return $v->visitInt($this->i); }
  };
}

function string_value(string $s):Value {
  // ..
}

// ..

function get_value_type(Value $v):string {
  return $v->accept(new class implements ValueVisitor<string> {
    public function visitInt(int $i):string { return 'int'; }
    public function visitString(string $s):string { return 'string'; }
    // ..
  });
}
```

**Comment by jesseschalken** [comment]
Since this was finished in HHVM in https://github.com/facebook/hhvm/commit/cb5b17a52c27414647d0c5a6cbbe1c48597ab8b9 and only typechecker support is pending, should the "php7 incompatibility" label be removed and the "hack" label added?

**Comment by jesseschalken** [comment]
I have no idea how I just unassigned @int3 from this issue :flushed:

**Comment by jwatzman** [comment]
@jesseschalken It's a GitHub UX issue -- @int3 doesn't work on Hack any more and I think his project permissions have changed such that he's no longer "allowed" to be assigned issues in this repo (he must have removed himself?); GitHub didn't detect this change until you wrote your comment, at which point it went "oops that isn't legal let's remove @int3" and attributed it to you.

In any event, cc @dlreeves in case this is something you might eventually want for Hack? Or to close out if it's not something the typechecker will ever pick up?

**Comment by dlreeves** [comment]
This falls low on our priority list at the moment. The goal of Hack isn't to accept every feature that exist in PHP and add some typing rules for it. Hack is it's own language so we need to evaluate each new capability of the runtime and ensure it makes sense in the overall language design. We haven't had the chance to do so yet.

**Comment by GroovyCarrot** [comment]
I only really use this feature for quickly spinning up classes in unit tests, so it's not massively missed; and I can just write stubs at the top of the test. But in terms of typechecking: I think it's perfectly valid to not allow it to be returned from the function unless it implements an interface, or extends another class. I can't imagine you would be able to do anything useful with an anonymous class, without there being some contract?

The only other scenario that springs to mind is returning an anonymous class implementing `__invoke()` as `callable`. But the typechecker does not recognise these classes as `callable` anyway, and you're better off just returning a closure. You could still get around it by just implementing an `Invokable` interface, if you really must.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This issue applies to running php code on hhvm. Hhvm [nolonger supports running php code](https://hhvm.com/blog/2018/09/12/end-of-php-support-future-of-hack.html) since [hhvm version 4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html).

Hack does not support anonymous classes and runtime support for them has been removed in hhvm [4.2.0](https://hhvm.com/blog/2019/04/23/hhvm-4.2.0.html).
_Support for PHP anonymous classes have been removed from the runtime; these were not supported in Hack._

**Comment by luisaglez1** [comment]
Interacting with your audience is a fundamental way to improve your [Facebook account. ](https://hackfreeonline.com/facebook/
)It’s not enough to post content—you need to actively engage with your friends, followers, and community. Start by responding promptly to comments and messages. Acknowledge when someone compliments your post or asks a question by replying with thoughtful responses.

Liking and sharing relevant posts from your connections [hacking facebook ](https://hackfreeonline.com/facebook/
)and shows that you’re an active member of the community. For instance, if a friend shares a milestone or achievement, leave a congratulatory comment. Similarly, if someone shares an article or a piece of content that resonates with you, share it on your timeline with your own insights.

Host live sessions or Q&A events to connect with your audience in real time. For example, if you’re a fitness coach, you can host a session on workout tips. These interactive events foster stronger connections and increase your visibility on the platform.

Lastly, show appreciation to your audience by tagging them in posts or giving shoutouts. Small gestures of gratitude can significantly enhance your relationships, making your account more engaging and personable.
