### ISSUE TITLE
Generator delegation

### ISSUE THREAD

**Issue by jwatzman** [facebook/hhvm#6040]
https://wiki.php.net/rfc/generator-delegation

Hard, especially because we already differ from PHP5 with generators. The first step will probably be to get https://github.com/facebook/hhvm/pull/4915 merged, but that requires some very difficult and time-consuming cleanup internal to FB's codebase.

**Comment by jwatzman** [comment]
This is tentatively claimed by our new hackamonther Scott.

**Comment by simonwelsh** [comment]
Looks like he finished it
