### ISSUE TITLE
Remove date.timezone warning

### ISSUE THREAD

**Issue by jwatzman** [facebook/hhvm#6042]
https://wiki.php.net/rfc/date.timezone_warning_removal

We can probably just do this, even in PHP5? If not, then still easy, but needs the php5 vs php7 INI options first.

**Comment by r3wt** [comment]
:+1 most annoying PHP error ever

**Comment by JoelMarcey** [comment]
Assigning `facebook-github-bot` for those that are claimed, but cannot be directly assigned to the user.
