### ISSUE TITLE
Internal constructor behavior

### ISSUE THREAD

**Issue by jwatzman** [facebook/hhvm#6044]
https://wiki.php.net/rfc/internal_constructor_behaviour

We likely already do most if not all of this. Technically a BC break, but the old behavior is so stupendously broken we should just make the change and not worry about PHP5 vs PHP7 modes.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

In [hhvm 4.3.0](https://hhvm.com/blog/2019/04/30/hhvm-4.3.0.html) the failure mode of calling a built-in function with the wrong types has been changed to be a TypeError. This matches the user defined Hack functions.

This removed 'param coerce fail mode null'.
This means that you will not get a null from a constructor anymore.
Constructors that do internal error checking should throw, and afaik, they do.

Example from the php rfc.
```HACK
    $mf = new MessageFormatter(
        'en_US',
        '{this was made intentionally incorrect}',
    );
    if ($mf === null) {
        echo "Surprise!";
    }
```

This torws correctly in hhvm.
_Uncaught exception 'Exception' with message 'msgfmt_create: message formatter creation failed: U_PATTERN_SYNTAX_ERROR'_.

If there are still constructor out there in the wild returning nulls, we should open individual issues for them.
