### ISSUE TITLE
list() behavior consistency

### ISSUE THREAD

**Issue by jwatzman** [facebook/hhvm#6049]
https://wiki.php.net/rfc/fix_list_behavior_inconsistency

Yay -- these are equivalent now:

``` php
list($a, $b) = 'hi';
```

``` php
$x = 'hi';
list($a, $b) = $x;
```

Unclear if we'll want to gate this one -- it's a BC break, but the old behavior is pretty perverse.

**Comment by jwatzman** [comment]
Argh, PHP! Fix one inconsistency just to create another. These two are now no longer equivalent when `$x` is a string:

```php
$a = $x[0];
$b = $x[1];
```

```php
list($a, $b) = $x;
```

Which is a PITA since HHVM models them the same way in the bytecode. I don't see a good way to do this -- maybe with the new minstr splitting, I can add some feature in there, but it's going to be annoying. There's not even a good way to emit an "if is string" around the whole block of assignments, since for things like `list(list($a, $b)) = $x` we need to check if `$x[0]` is a string first (i.e., the next-to-last level).

Here's a test case for everything I could think of here, to look at when we come back to this:

```php
<?php

error_reporting(-1);

list($a, $b) = 'hi';
var_dump($a);
var_dump($b);

$hi = 'hi';
list($a, $b) = $hi;
var_dump($a);
var_dump($b);

$a = $hi[0];
var_dump($a);

list(list($a, $b)) = array('hi');
var_dump($a);
var_dump($b);
```

**Comment by nikic** [comment]
I don't think anybody will mind if you keep things as is. It's not like someone would rely on things *not* working. The decision that was reached in that vote is really nonsensical.

**Comment by jwatzman** [comment]
Had a conversation with @sgolemon and @paulbiss about this.

- The minstr splitting might make this easier, or at the very least it's going to be less work to duplicate to wait until that's done, so going to hold off until then.
- This will probably end up being related to the following change in nested list reads in PHP7 (95% sure this happened, need to double check), which I didn't do as part of LTR assignment. Might make this easier to do that first?

```php
list(list($a, $b), list($c, $d)) = $x;

// PHP5:
$a = $x[0][0];
$b = $x[0][1];
$c = $x[1][0];
$d = $x[1][1];

// PHP7 (assuming nothing is a string):
$_tmp1 = $x[0];
$a = $_tmp1[0];
$b = $_tmp1[1];
$_tmp2 = $x[1];
$c = $_tmp2[0];
$d = $_tmp2[1];
```

**Comment by jwatzman** [comment]
> It's not like someone would rely on things not working.

My concern is that people will accidentally rely on this, in ways that are unexpected -- since the behavior changed when the RHS is a *variable* it's really easy to not realize you are even occasionally passing in a string and doing this. Not the biggest thing people will look for in PHP7 support when transitioning to HHVM, but it's the little stuff that bites you :(

**Comment by lexidor** [comment]
Hi, I am reading HHVM issues to see which issues are unlikely to be fixed.

This issue was created because HHVM's behavior was/is different from PHP's. HHVM stopped striving from php compatibility with the release of version [4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html).

The current behavior, although different, is not buggy or broken. Some might say HHVM is behaving more sensibly than PHP is. Matching PHP bug-for-bug here would be rather silly now that there is no runtime oblivious `<?php` code.
