### ISSUE TITLE
Alternative open/close tags

### ISSUE THREAD

**Issue by jwatzman** [facebook/hhvm#6050]
https://wiki.php.net/rfc/remove_alternative_php_tags

We may not do anything here; we need to keep supporting them in PHP5 mode, and the slight inconsistency with PHP7 (treating them as opening tags vs. as literal text) is probably not worth the effort to fix? Gating parser stuff can be a PITA. Though with uniform variable syntax, we may have the machinery to do it anyways.

**Comment by nikic** [comment]
This should be simpler than the conditional parser changes. ASP tags are already supported based on a runtime option, see for example https://github.com/facebook/hhvm/blob/d09aa2e9e663c4239dba63b5b94e1cdb1242fa55/hphp/parser/hphp.ll#L867.

**Comment by fredemmott** [comment]
Can we remove <script language="php"> anyway just because it's an abomination? :p

**Comment by jwatzman** [comment]
Can we just close this one? To stay PHP5 and PHP7 compatible, we should just support both, and since there's no conflict of features/behavior here, we don't need an option, we can just have both, right?

**Comment by JoelMarcey** [comment]
I am also ok with closing this. We just decide to be more "backwards compatible" here :)

I do recommend NOT using these tags though :)
