### ISSUE TITLE
Catcahble "call to member on non object"

### ISSUE THREAD

**Issue by jwatzman** [facebook/hhvm#6051]
https://wiki.php.net/rfc/catchable-call-to-member-of-non-object

**Comment by jwatzman** [comment]
Internal task 8011297 -- FB folks, there is already some discussion there.

**Comment by paulbiss** [comment]
For the sake of OSS folks seeing this, the discussion was around the hhvm specific option ThrowExceptionOnBadMethodCall and the new EngineException RFC:

@billf:
> provide RuntimeOption to control the runtime triggering a recoverable error when $non_object->method() happens.
>
> currently:
>
> RuntimeOption::ThrowExceptionOnBadMethodCall = false; // fatal error
> RuntimeOption::ThrowExceptionOnBadMethodCall = true; // throw an exception
>
> proposed
>
> RuntimeOption::ThrowExceptionOnBadMethodCall = false; // fatal error
> RuntimeOption::ThrowExceptionOnBadMethodCall = true; // throw an exception
>
> RuntimeOption::RecoverableErrorOnBadMethodCall = false; // defer to ThrowExceptionOnBadMethodCall
> RuntimeOption::RecoverableErrorOnBadMethodCall = true; // trigger error
>
> discuss/investigate:
>
> what happens if both are true? combine this into one RuntimeOption? assertions that they're mutually exclusive?


@paulbiss:
> If we do go this route, I think a single tri-state option would make the most sense. That being said...
>
> Interestingly, PHP 7 will start throwing EngineExceptions for (many but not all) fatals and catchable fatals rather than raising errors (these exceptions will promote to errors if uncaught, mimicking PHP 5 behavior).
>
> In PHP 7 such exceptions implement a new Throwable interface but, critically, do not extend Exception, making their introduction safe in code-bases that already catch all regular exceptions. I don't think we need a switch between Fatal and CatchableFatal here for compatibility (what's being introduced is strictly more tolerant). With the introduction of EngineException, we won't need the ThrowExceptionOnBadMethodCall option anymore.

@billf:
> +1 on tri-state
>
> what's weird (stupid?) is that the https://wiki.php.net/rfc/catchable-call-to-member-of-non-object proposal points to both https://wiki.php.net/rfc/engine_exceptions and https://wiki.php.net/rfc/engine_exceptions_for_php7 
>
> i only noticed the first (shot-down) proposal.
>
> as you note, this task will require more thought in the face of https://wiki.php.net/rfc/engine_exceptions_for_php7

**Comment by jwatzman** [comment]
Re extra options, we're planning on adding a PHP5 vs. PHP7-mode option, which I'm probably going to add as part of my work on the AST/UVS RFCs. (See https://github.com/facebook/hhvm/issues/5523.) If you need a new config option, we should probably make it the same one?

**Comment by paulbiss** [comment]
I don't think this will require an option

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Hhvm does indeed throw instead of fatal erroring, like PHP 7.

However, hhvm throws a `BadMethodCallException` while PHP throws an `Error`.
So this code would catch the error on hhvm, but not on php.
```HACK
try {
    $null = null;
    $null->method();
} catch (\Exception $t) {
   \var_dump($t);
}
```

I would consider is a minor difference and let's not change this after all these years.
