### ISSUE TITLE
Session start changes

### ISSUE THREAD

**Issue by jwatzman** [facebook/hhvm#6053]
https://wiki.php.net/rfc/session-lock-ini

The RFC is kind of hard to read, and AFAICT not all of it passed, so the hard part might be just figuring out WTF changed :)

**Comment by raeesiqbal** [comment]
Any update on when this will be implemented?

**Comment by jwatzman** [comment]
This isn't something we've looked at yet, since it wasn't a flagship feature of PHP7, it was unclear what the benefit would be vs. the time it would take to build. If people are very interested in it, we can re-prioritize :)

**Comment by raeesiqbal** [comment]
Lets say that we have three websites running via HHVM on the same server. Now, here are the things related to Sessions that you must do for each of them.
```php
<?php
ini_set('session.cookie_lifetime', 900);
ini_set('session.cookie_path', '/');
ini_set('session.cookie_secure', true);
ini_set('session.cookie_httponly', true);
ini_set('session.cookie_domain', 'securesite.com');
session_name('securesite');
session_start();
```
and some people report that [`session_name()` is pretty expensive](http://php.net/session_name#103472).

But after this change, we can simply do:
```php
<?php
session_start([
  'cookie_lifetime' => 900,
  'cookie_path' => '/',
  'cookie_secure' => true,
  'cookie_httponly' => true,
  'cookie_domain' => '.securesite.com',
  'name' => 'securesite',
  'read_and_close' => true
]);
```
I suspect that `read_and_close` and other new parameters can help improve performance significantly in high traffic sites. Plus, its all in one place, simpler and cleaner :)

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

`$_SESSION` the functions that deal with `$_SESSION` have been removed from hhvm in version [4.4.0](https://hhvm.com/blog/2019/05/06/hhvm-4.4.0.html).
