### ISSUE TITLE
Remove hex support in numeric strings

### ISSUE THREAD

**Issue by jwatzman** [facebook/hhvm#6054]
https://wiki.php.net/rfc/remove_hex_support_in_numeric_strings

BC break that will have to be gated on PHP5 vs PHP7 mode.

**Comment by jwatzman** [comment]
Derrick Rice (FB new hire) is likely to do this one.

**Comment by DerrickRice** [comment]
Intern task 8201648

**Comment by JoelMarcey** [comment]
Assigning `facebook-github-bot` for those that are claimed, but cannot be directly assigned to the user.

**Comment by jwatzman** [comment]
c2d258d299e590bd83be6474b61da587a4415766
