### ISSUE TITLE
Expectations (assertion changes)

### ISSUE THREAD

**Issue by jwatzman** [facebook/hhvm#6055]
https://wiki.php.net/rfc/expectations

No BC breaks.

**Comment by jwatzman** [comment]
Someone else was talking to me about this, but I think it was just general discussion since no one has claimed this yet? I've claimed and will start working on it unless that person pings me :)

**Comment by fredemmott** [comment]
:/ I thought I self-assigned this on monday, but github says no... only done preliminary investigations anyway. Yay on-call.

**Comment by jwatzman** [comment]
Diffs are up internally for this.
