### ISSUE TITLE
Group use delcarations

### ISSUE THREAD

**Issue by jwatzman** [facebook/hhvm#6056]
https://wiki.php.net/rfc/group_use_declarations

Will probably want to implement this in the Hack typechecker too, in a separate patch.

**Comment by ShengZhan** [comment]
claimed by sheng zhan

**Comment by JoelMarcey** [comment]
Assigning `facebook-github-bot` for those that are claimed, but cannot be directly assigned to the user.

**Comment by jwatzman** [comment]
@ShengZhan let me know that she isn't going to have time to get to this.

**Comment by fredemmott** [comment]
Definitely want this in the typechecker - it will make using HH\Asio\everything much, much nicer.

**Comment by fredemmott** [comment]
Related: https://github.com/facebook/hhvm/issues/6081
