### ISSUE TITLE
Generator return values

### ISSUE THREAD

**Issue by jwatzman** [facebook/hhvm#6057]
https://wiki.php.net/rfc/generator-return-expressions

Probably orthogonal to the way our generator mechanics already differ from PHP5? (cf. #6040)

**Comment by jwatzman** [comment]
This is tentatively claimed by our new hackamonther Scott.

**Comment by JoelMarcey** [comment]
Assigning `facebook-github-bot` for those that are claimed, but cannot be directly assigned to the user.
