### ISSUE TITLE
intdiv function

### ISSUE THREAD

**Issue by jwatzman** [facebook/hhvm#6058]
https://wiki.php.net/rfc/intdiv

**Comment by SiebelsTim** [comment]
Closed in #6129

**Comment by nikic** [comment]
If this gets closed, there should be another issue that tracks the incorrect failure conditions.

**Comment by jwatzman** [comment]
What do you mean "incorrect failure conditions"?

**Comment by nikic** [comment]
@jwatzman Division by zero should throw DivisionByZeroError (instead of a warning) and division of -1 by PHP_INT_MIN should throw ArithmeticError instead of returning false. I assumed this wasn't done yet as it depends on the Exception/Error splitup, which probably requires some extra work.

**Comment by jwatzman** [comment]
Ah yeah, ok. That doesn't look to be part of this RFC -- which RFC was that changed in?

**Comment by nikic** [comment]
@jwatzman This did not go through an RFC. A couple of other operator error conditions were also changed:

* Division by zero with `/` now results in Inf/-Inf/NaN (and still a warning). Previously it returned false.
* Modulo by zero with `%` now throws a `DivisionByZeroError`. Previously it threw a warning and returned false.
* Bitshifts by negative numbers now throw an `ArithmeticError`. This was a warning+false for a short time, as this check was only introduced in PHP 7 anyway.

Hope I didn't miss anything.

**Comment by SiebelsTim** [comment]
Here is a not working start of Throwable implementation:
https://gist.github.com/SiebelsTim/71685ba69a452258d435

I tried to take the Exception implementation into a trait. However that results in errors, because the runtime expects `$previous` to be readable rather than calling `getPrevious()` (and probably more).

That approach might be completely unusable, but maybe it helps setting up class hierarchy or something useful.

**Comment by jwatzman** [comment]
@nikic thanks for the info, going to file a separate issue for that.
@SiebelsTim did you mean to post that on https://github.com/facebook/hhvm/issues/6037?

**Comment by SiebelsTim** [comment]
@jwatzman It would've fit there as well. But I posted it here, because nikic mentioned the error cases which need the Throwable rework.
