### ISSUE TITLE
Array-to-string conversion

### ISSUE THREAD

**Issue by jwatzman** [facebook/hhvm#6059]
https://wiki.php.net/rfc/array-to-string

Technically a BC break, but the old behavior is so perverse we should just do this IMO.

**Comment by nikic** [comment]
Note that this change never actually landed. The array-to-string behavior is still the same (notice).

**Comment by jwatzman** [comment]
@nikic not sure what the procedure is on the PHP side. Is this still going to land before release, might it show up in 7.1, or should we just close this as "lol never happened"?

**Comment by nikic** [comment]
It won't land in 7.0 and as it's a BC break it ought not land in 7.x either. So yeah, pretty much "lol never happened" ;)

**Comment by jwatzman** [comment]
![PHP Hammer](https://c4.staticflickr.com/8/7226/7095238893_5000f6e57d_b.jpg)
