### ISSUE TITLE
Stream handling has some incompatibilities with PHP5

### ISSUE THREAD

**Issue by dvdoug** [facebook/hhvm#6070]
Hi

I'm the author of a basic php stream wrapper library called StringStream. It's a simple pure in-memory implementation, but the test suite has a couple of failures when run against HHVM.

The code itself is a single class as required by PHP (http://php.net/manual/en/class.streamwrapper.php), and is pretty minimal anyway so I can't provide a more reduced testcase. Sorry.

References:
Failing tests on Travis: https://travis-ci.org/dvdoug/StringStream
Actual library code: https://github.com/dvdoug/StringStream
PHP stream wrapping: http://php.net/manual/en/function.stream-wrapper-register.php and http://php.net/manual/en/class.streamwrapper.php

Thanks,
Doug

**Comment by fredemmott** [comment]
Travis only has outdated, unsupported versions of HHVM. Do the issues still exist on a recent version?

**Comment by dvdoug** [comment]
Just tested against 3.9.0 - the results are the same as on Travis

**Comment by dvdoug** [comment]
Still an issue on 3.15

**Comment by aorenste** [comment]
I'm able to repro this.  At least one of the cases comes down to HHVM not getting the starting position of the stream after open.

**Comment by aorenste** [comment]
The error in `testWriteOnlyAppend()` is definitely an HHVM error - HHVM isn't checking the starting position after opening the file.  I have a fix working through the system now.

I think the error in `testSeekCurPastEnd()` is actually a bug in your `stream_seek()` code which is exposed by a difference between PHP and HHVM.  In general I would expect that if you try to seek past the end of the string it would just seek to the end but instead you're actually extending the string.  Even if this is the behavior you want the `SEEK_CUR` case (which HHVM is using) is missing the check to extend the string and the `SEEK_END` case looks incorrect (you're checking the length of `$this->position + $aOffset` after already adding `$aOffset` to `$this->position`).

**Comment by dvdoug** [comment]
Hi

So I think you're correct about my `SEEK_END` check being wrong which I'll take a look at (thanks!), however according to http://php.net/manual/en/function.fseek.php:

> In general, it is allowed to seek past the end-of-file; if data is then written, reads in any unwritten region between the end-of-file and the sought position will yield bytes with value 0. However, certain streams may not support this behavior, especially when they have an underlying fixed size storage

In the case of the failing test though and `SEEK_CUR` (and unlike `SEEK_SET` and `SEEK_END`), PHP seems to call `stream_truncate` itself to extend the string which HHVM doesn't seem to do. I've always thought that's weird, but that does still mean I think there's a compatibility issue in HHVM.

Unless you want to call it a PHP bug?

**Comment by aorenste** [comment]
I think you're right about the expected behavior and HHVM handles it properly for files: https://3v4l.org/t1Xq6

I'm not sure what you're saying about HHVM not calling `stream_truncate`. Can you give a concrete example?  This is what I tried: https://3v4l.org/R85Xc
I don't see PHP (or HHVM) calling `stream_truncate` in any case.

**Comment by dvdoug** [comment]
Sure, try https://3v4l.org/8mPkD - if you seek past the end of the stream using `SEEK_CUR` and then try reading in the entire contents PHP will auto truncate the stream to fill in the null bytes past the actual contents. HHVM doesn't.

It's trivial to fix in user-land (see commented out line 103) but it is a behavioral difference so wanted to point it out.

**Comment by aorenste** [comment]
@dvdoug Unless I'm mistaken that truncate() is only happening because you're calling it from within your seek() code.  The difference is that HHVM is seeking relative to the current position (as asked by the client code) whereas PHP is seeking relative to the origin (not sure why it's doing that instead of just a relative seek) and the custom stream code is handling that differently.

**Comment by dvdoug** [comment]
Wow. In a million years I wouldn't have even considered the possibility that PHP was using a different seek mode than the one I actually specified. That's just bizarre.
