### ISSUE TITLE
missing comma between string and empty square bracket in function call

### ISSUE THREAD

**Issue by r3wt** [facebook/hhvm#6076]
`
\nFatal error: Cannot use [] for reading
`

example

```
function foo($string,$array)
{
return false;
}

foo('test'[]);
```

**Comment by simonwelsh** [comment]
Same error as PHP 5.5 and up: https://3v4l.org/Htd8S

**Comment by r3wt** [comment]
I suppose it's a non issue then. I'm generally against obscure error messages, but this one isn't so obscure as to require great effort to debug.
