### ISSUE TITLE
How to correctly run CLI using hhvm?

### ISSUE THREAD

**Issue by dieend** [facebook/hhvm#6078]
Running hhvm using CLI is terribly slow. I know it's because hhvm needs some warm up.
But in case of CLI, where different process is executed every 5s using same codebase, what is the correct way to make hhvm warmed up?
I searched the old issue and some of it telling me to set Jit value to 0. But it was in HHVM 3.2.X, and now HHVM already up to 3.8. Have anything changed?

**Comment by simonwelsh** [comment]
You're better to have a non-public server instance running (say, an nginx server that's only listening to 127.0.0.1 that forwards requests to HHVM) and then make requests to that rather than lots of CLI requests. This way, you get the benefit of the JIT and don't have the warmup cost.

**Comment by dieend** [comment]
Wow. I didn't expect that. Well we can do that with refactoring here and there. Thanks!

**Comment by dieend** [comment]
@simonwelsh I have a difficulty with long running worker. #4360 is one of the problem. I don't know which process that might still running, and if in some case it goes to infinite loop, well, I can't stop that specific requests. Any idea?

**Comment by fredemmott** [comment]
Attach gdb and run 'thread apply all bt' to find out what's still running, and open a separate issue for that

As for slowness, your options are:
 - run a server and poll it like simonwelsh suggests (though you can use + firewall the builtin server to avoid setting up nginx)
 - turn off the JIT: `hhvm.jit=0` in your INI; the JIT has a high cost, which for short CLI scripts, often isn't a good choice.
