### ISSUE TITLE
NEWS file is no longer updated?

### ISSUE THREAD

**Issue by ck-on** [facebook/hhvm#6086]
I appreciate being able to check the NEWS file for updates but apparently it has not been maintained for a month now?

https://github.com/facebook/hhvm/blob/master/NEWS

Difficult to churn through the commits to understand more significant milestones.

Nothing in there since "Park" especially important things like `enable_reusable_tc`

**Comment by paulbiss** [comment]
cc @jano @markw65

**Comment by paulbiss** [comment]
Park was the previous release, Jan probably just forgot. The next release (Mark's) is still in testing.

**Comment by Orvid** [comment]
It looks like "Park" is the newest internal release, at least, that's the last one mentioned in the [blog post](http://hhvm.com/blog/9995/hhvm-3-9-0) for HHVM 3.9.0

**Comment by paulbiss** [comment]
The "Quake" release is in testing until the end of next week.

**Comment by fredemmott** [comment]
I've started an internal discussion about what we want to do for this. My current guess is we will switch to more detailed files, but only aim to update them for OSS releases.

**Comment by ck-on** [comment]
File was never updated since last September (90 days ago)

It's a shame because it was a nice changelog summary

**Comment by fredemmott** [comment]
Closing, we're not maintaining this: it was a sporadically updated dump of git log --oneline.

**Comment by jazzdan** [comment]
@ck-on @simonwelsh has a nice replacement he has been maintaining on his blog https://coding.simon.geek.nz/tag/commits/
