### ISSUE TITLE
get_browser() and `REMOTE_ADDR` are unsupported

### ISSUE THREAD

**Issue by barbu110** [facebook/hhvm#6087]
The documentation states that `get_browser` PHP's function is not supported on HHVM. I tried to get the IP address using `$_SERVER['REMOTE_ADDR']` and this is, apparently, undefined. 

Where are the alternatives?

**Comment by Orvid** [comment]
As a note, I am a firm believer that having the server determine what the client is capable of is the wrong way to do it. Capability checking should be done client-side.

**Comment by barbu110** [comment]
I am actually interested in creating an activity logger for user accounts.
I don't want to get browser capabilities, I want to get browser version,
user IP, operating system (I want IP do determine geolocation)

În data de sâmbătă, 22 august 2015, Orvid King <notifications@github.com> a
scris:

**Comment by steelbrain** [comment]
@barbu110 if you want to use it for geoip purposes, checkout hhvm-ext-geoip.

**Comment by barbu110** [comment]
okay . I checked out that extension. It still needs me to pass the user's
IP address to do anything. How am I supposed to get that IP address, if
REMOTE_ADDR is an undefined index on the SERVER variable?

În data de sâmbătă, 22 august 2015, Steel Brain <notifications@github.com>
a scris:

**Comment by steelbrain** [comment]
@barbu110 if `REMOTE_ADDR` is not available in your `$_SERVER` then it means that your nginx settings are incorrect.

**Comment by barbu110** [comment]
I am using Apache2 on Ubuntu 14.04 What settings should I check? Could you tell ne please?

**Comment by steelbrain** [comment]
@barbu110 I would suggest you move away from apache as you are not using `mod_php` anymore.
I haven't used Apache lately so don't know how to set fcgi vars.

**Comment by barbu110** [comment]
Ok then. I will change my system to use nginx (since it's a dev machine) and come back with an update, and probably close the issue. 
Thank you!

**Comment by barbu110** [comment]
Ok. I was stupid enought to run my script ONLY in the Terminal. Of course there was no `REMOTE_ADDR`. Thank you for all you've done. I am now on NGINX

**Comment by kristapsk** [comment]
For `get_browser()` there is pure PHP implementation available - http://alexandre.alapetite.fr/doc-alex/php-local-browscap/.

**Comment by Orvid** [comment]
As a note, there's also the php implementation at https://github.com/browscap/browscap-php
