### ISSUE TITLE
Class files

### ISSUE THREAD

**Issue by spaghetticodr** [facebook/hhvm#6121]
Just like namespace contents do not have to be wrapped inside curly braces if there's just one namespace in the file, same should be true with classes.

    namespace foo; // valid

    class Foo extends Stuff; // currently invalid
    // class code...

To me it's like the most annoying thing in PHP besides lack of types - having all class code nested by 1 level. Also, I don't see the point in <?hh tags, what kind of a sane developer needs to mix html and hack?

Please consider this functionality for hack lang...

**Comment by Orvid** [comment]
To put my 2 cents in on this, I personally think that the curly brackets shouldn't be optional. It's worth noting though that I also don't think the curly brackets for namespaces should be optional either.

I'm not entirely sure the full reasoning for the `<?hh` tag, as you actually can't mix HTML and Hack.

**Comment by paulbiss** [comment]
It's mostly just to distinguish it from PHP files and static content, both of which hhvm will also serve. I don't think allowing `class Foo;` to declare an entire file to be class scoped is a good idea. It doesn't add much value but it cuts down quite a bit on readability.

**Comment by spaghetticodr** [comment]
It adds to readability by giving you more space (an entire TAB per line) to work on. If you're writing OOP code a TAB is saved from like 99% of your code.

Something for inspiration:
http://greatemerald.xmpcommunity.com/uncodex/UT2004/Source_engine/gameinfo.html

**Comment by paulbiss** [comment]
You could also omit the tab. We do it all the time with namespaces in C++
