### ISSUE TITLE
Type parameter to HH\autoload_set_paths as a shape in HHI

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#6136]

**Comment by Orvid** [comment]
We're a small team, and it doesn't look as though anyone in the community is actively working on this issue, so we've decided to close it. If you plan to send us a pull request resolving the issue let us know in the comments and we will re-open it and assign it to you. If you feel this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
