### ISSUE TITLE
hhvm socket permissions in multi-user environments, and error_log permissions

### ISSUE THREAD

**Issue by mattlehner** [facebook/hhvm#6148]
When using hhvm with sockets, and using a socket for each user on a multi-user system, there's no way to set the default socket group to something that allows nginx to work with the socket unless the user is in the nginx group. This is less than ideal as it would allow users to reach each others sockets through the group permissions. Instead, we want to be able to set the socket owner:group to username:nginx. This allows us to continue to use 770 on the socket, and prevents untrusted users from being able to get at each others sockets as well.

There is currently no way to set the group of the socket aside from doing something outside of the init scripts.

A second issue is with the error.log. When running hhvm as non-root, after the process starts it's unable to write to the designated error.log as it's given 644 permissions and owned by root.

**Comment by AnoopAlias** [comment]
Hi,

Does using hhvm.log.use_syslog = true fix the error log issue?.

There is a message at startup when using syslog 

Log file not specified under daemon mode.\n\n

when mode is set to daemon .

Does that mean in daemon mode we compulsorily need logfile rather than syslog?

**Comment by paulbiss** [comment]
This feature request is not actively being worked on. We would happily consider a pull request implementing it. If you plan to work on this issue let us know in the comments and we will re-open the issue and assign it to you. If you feel strongly that this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
