### ISSUE TITLE
PHP7 return types

### ISSUE THREAD

**Issue by jwatzman** [facebook/hhvm#6152]
https://wiki.php.net/rfc/return_types

Hack already supports these, so should be just a matter of removing the "only in Hack files" check in the parser. The actual semantics are not quite the same as in Hack, but we can cover that in https://github.com/facebook/hhvm/issues/5052

**Comment by fredemmott** [comment]
Another incompatibility is the position of 'use()' relative to the return type.

**Comment by jwatzman** [comment]
@paulbiss says that his upcoming diff for [scalar types](https://github.com/facebook/hhvm/issues/5052) might enable this, but it probably doesn't do the `use` parser change (where return types and `use` clauses appear when defining an anonymous function differ between Hack and PHP7).

**Comment by jwatzman** [comment]
@paulbiss this is incorporated in your STH work right?

**Comment by paulbiss** [comment]
I didn't fix the use clause order but everything else should be there

**Comment by Orvid** [comment]
@paulbiss Is this still the case?

**Comment by jesseschalken** [comment]
Is this issue still valid? This code seems to work fine (throws `TypeError "...must be of type int, string given"`):

```php
<?php

$x = 'string';
$f = function () use ($x): int {
    return $x;
};
$f();
```

https://3v4l.org/DLKQU

**Comment by Orvid** [comment]
Probably not.
