### ISSUE TITLE
joomla mbstring

### ISSUE THREAD

**Issue by SkiAn2007** [facebook/hhvm#6153]
i have problem 
mbstring default value is not "neutral"

added line in php.ini don't work
mbstring.language = neutral

added line in nginx conf don't work
fastcgi_param PHP_VALUE "mbstring.language = neutral";

hhvm 3.9

**Comment by Orvid** [comment]
We're a small team, and it doesn't look as though anyone in the community is actively working on this issue, so we've decided to close it. If you plan to send us a pull request resolving the issue let us know in the comments and we will re-open it and assign it to you. If you feel this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.

**Comment by photodude** [comment]
@SkiAn2007 FYI Joomla staging now passes unit tests on HHVM 3.15.3 and the pre-release 3.7.0 Alpha 1 should be testable for developer site preview with HHVM 3.15.3+
