### ISSUE TITLE
Allow collections to be used in user attributes

### ISSUE THREAD

**Issue by HRMsimon** [facebook/hhvm#6156]
``` hack
<?hh

<<
RendererOptions(
  ImmMap {
    'html' => ImmMap {
      'isAngular' => false,
      'template' => 'controller/test.tpl',
    },
  },
)
>>
class Application_ControllerTest_Controller extends Application_Controller {
  ...
}
```

Results in: `E_FATAL_ERROR: User-defined constants are not allowed in user attribute expressions` (no Hack errors)

As collections are far superior to arrays, would be nice if the worked in user attributes too.

**Comment by lexidor** [comment]
In modern Hack, we'd prefer `dict[]`, `keyset[]`, and `vec[]` over `/*Imm*/Map{}`, `/*Imm*/Set{}`, and `/*Imm*/Vector{}`.
These do work in attribute contexts.

```HACK

<<
RendererOptions(
  dict[
    'html' => dict[
      'isAngular' => false,
      'template' => 'controller/test.tpl',
    ],
  ],
)
>>
class Application_ControllerTest_Controller extends Application_Controller {
  ...
}
```

These containers have value semantics (copy-on-write), making it safe to return them from the reflection functions, without the fear they may be modified by callers.
If you have a usecase which cannot be met with the Hack arrays and the HSL, please open an issue.
