### ISSUE TITLE
HHVM does not allow "current()" on an object

### ISSUE THREAD

**Issue by derickr** [facebook/hhvm#6160]
```
<?php
class foo {
	public $key = 42;
}
$c = new foo;

$s = new stdClass;
$s->key = 'value';

var_dump(current($c), current($s));
```

PHP output:
```
int(42)
string(5) "value"
```

HHVM output:
```
Warning: Invalid operand type was used: expecting an array in /tmp/hhvm-test.php on line 10

Warning: Invalid operand type was used: expecting an array in /tmp/hhvm-test.php on line 10
bool(false)
bool(false)
```

**Comment by paulbiss** [comment]
In HHVM objects don't have internal cursors. I think we had talked about trying to fix this in the past, but I seem to recall we had decided it wasn't worth potentially regressing object performance over.

**Comment by derickr** [comment]
To be fair, I think it's a bit of a dubious feature in PHP. But it is an incompatibility. Perhaps add the "php5 incompatibility" tag for and be done with it? I'll be closing this now.

**Comment by fredemmott** [comment]
Listed here: https://github.com/facebook/hhvm/blob/master/hphp/doc/inconsistencies#L73
