### ISSUE TITLE
RFC: Ban references in partial

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#6164]
Way too easy to break the type system - eg:

``` Hack
<?hh

function foo(int &$value): void {
  $value = 'herp';
}

function bar(int $value): void {
  var_dump($value);
}

function main(): void {
  $v = 123;
  foo($v);
  bar($v);
}

main();
```

This typechecks, but at runtime:

```
Catchable fatal error: Argument 1 passed to bar() must be an instance of int, string given in /home/fredemmott/hhtest/test.php on line 9
```
- hackificator could use HH_FIXME
- if this is impractical for facebook www, possibly another .hhconfig option like unsafe_xhp?

**Comment by fredemmott** [comment]
cc @JoelMarcey

**Comment by JoelMarcey** [comment]
:+1:

**Comment by fredemmott** [comment]
cc @dlreeves

**Comment by Orvid** [comment]
In my opinion the `$value = 'herp';` line should cause a typechecker error, because the parameter is strongly typed.

**Comment by JoelMarcey** [comment]
@Orvid 

It is strongly typed only if the typechecker analyzes it as strongly typed. At this point, the typechecker sees the `&` and throws its hands up and says "go ahead and do whatever you want.

Had the function been `function foo(int $value): void {`, then yes, that line you mention would have been caught.

**Comment by simonwelsh** [comment]
:+1: die references, die.

**Comment by fredemmott** [comment]
@JoelMarcey : nope, types only matter at boundaries - so the assignment would be fine. If you tried to then return it as an int it would be an error.

**Comment by Orvid** [comment]
Sounds like an issue with the typechecker then...

**Comment by fredemmott** [comment]
@Orvid : references are not valid hack. Options are:

 - make them valid hack (in which case, the behavior should be as you described) - and if this is done, there's not really a reason to ban them in strict as well
 - ban them in partial
 - stick with the current 'trust me' behavior - this is standard in partial mode for things the typechecker doesn't understand

**Comment by JoelMarcey** [comment]
@fredemmott You are right. yeah. :( 

@Orvid, I was wrong.

**Comment by dlreeves** [comment]
We do not want to support PHP's reference due to the semantics they have, but don't have a strong alternative in Hack yet. For things like that we typically ban it in strict mode, but allow it in partial mode. What we could do is add a set of configs that takes certain strict mode checks and applies them to partial mode as well.

**Comment by JoelMarcey** [comment]
@dlreeves That is exactly what @fredemmott suggested -- an option for `.hhconfig`. Cool.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

> :+1: die references, die.

Hhvm has [removed `&$references`](https://hhvm.com/blog/2019/10/01/deprecating-references.html) from the language.
