### ISSUE TITLE
Deducing a shape as a generic parameter

### ISSUE THREAD

**Issue by tslettebo** [facebook/hhvm#6167]
Hi.

Is there a way to have code like this pass the typechecker, possibly by making a named shape type, and somehow making g() deduce its T parameter as that type?
```
function f(): void
{
  $value=shape('x' => 1,'y' => 1);

  g($value);
}

function g<T>(T $value): void
{
  echo $value['x']; // Error message here
}
```

It gives the error message:

This is not an object of type KeyedContainer, this is a value of generic type T (Typing[4005])

**Comment by paulbiss** [comment]
Hmm, this looks like a bug. cc @jwatzman @dlreeves

**Comment by tslettebo** [comment]
I also tried this approach:
```
type TestShape = shape('x' => int,'y' => int);

function f(): void
{
  $value=shape('x' => 1,'y' => 1);

  g(TestShape::class,$value);
}

function g<T>(classname<T> $dummy,T $value): void
{
  echo $value['x'];
}
```

However, nope, the "::class" approach definitely won't work for shapes. :)

As I understand, these are implemented as arrays under the hood.

**Comment by tslettebo** [comment]
Actually, I think this is enough for me:
```
function g<T>(T $value): void
{
  invariant(is_array($value),"");

  echo $value['x']; // Now ok
}
```

After all, g() is supposed to be able to work on various kinds of shapes, so it makes sense to reduce the type information at the boundary, so that before the call to g(), the $value variable can be type-checked, while a more general array type-checking is done in g().

This is based on a real use-case, by the way: g() is a function taking a "context array" (or shape in this case), a bunch of data, being passed to an XSLT script to create a web page.

**Comment by fredemmott** [comment]
3.9 supports structrual subtyping for shapes - why not just:

  function g(shape(''x' => string) $var): void {
    echo $var['x'];
  }

**Comment by fredemmott** [comment]
Also, unless you constrain T, it should work for /any/ type, so the hack error is correct.

If you really want to use generics (though as above, it seems unneccessary for shapes):

```Hack
<?hh

function g<T as shape('x' => string)>(T $value): void {
  var_dump($value['x']);
}

function main(): void {
  g(shape('x' => 'foo', 'y' => 'bar'));
}

main();
```

Added needs more info as I think this addresses your question - please close the issue or add more information.

**Comment by tslettebo** [comment]
Thanks for the information, I'll explore this.
