### ISSUE TITLE
Is it legal to use ext_fb in personal projects?

### ISSUE THREAD

**Issue by steelbrain** [facebook/hhvm#6173]
The first question is in the title, second question is, is it okay to use `fb_serialize`, I mean, is it depreciated or something?

**Comment by paulbiss** [comment]
You're certainly welcome to use it (it would be odd to open source it if you weren't). It's mostly a mix of useful functions we've tacked on for internal needs, and it predates our using the HH namespace for HHVM specific APIs. I in no way promise it's a stable API but most of them have been unchanged for quite some time.

**Comment by steelbrain** [comment]
@paulbiss then can I expect the future versions to not to break `fb_serialized` stuff?

**Comment by paulbiss** [comment]
I can't make any guarantees there, but I'd say it would be unlikely. If you want to be certain of API stability you should stick to the PHP and Hack APIs.
