### ISSUE TITLE
traits with private methods

### ISSUE THREAD

**Issue by r3wt** [facebook/hhvm#6176]
Process exited with code 153.

https://3v4l.org/sAU8j

**Comment by paulbiss** [comment]
What's the issue here?

**Comment by SiebelsTim** [comment]
I guess the problem is, that it doesn't output anything since 3.8.1

**Comment by paulbiss** [comment]
I think that was a 3v4l bug, I reran it and it has output for 3.9 now

**Comment by r3wt** [comment]
@paulbiss i have not be able to use traits with private functions in my app.

**Comment by paulbiss** [comment]
@r3wt you're going to need to be a lot more specific. From what I can tell based on the 3v4l link there's nothing wrong.

**Comment by r3wt** [comment]
@paulbiss 

https://3v4l.org/sAU8j

**Comment by fredemmott** [comment]
@r3wt : still only seeing an issue with 3v4l, not hhvm. Please provide:

 - example code
 - expected output/behavior
 - actual output/behavior you are seeing
 - HHVM version number

```
fred@dev:~/test$ hhvm --version
HipHop VM 3.9.1 (rel)
Compiler: tags/HHVM-3.9.1-0-g0f72cfc2f0a01fdfeb72fbcfeb247b72998a66db
Repo schema: 6416960c150a4a4726fda74b659105ded8819d9c
fred@dev:~/test$ hhvm test.php
Hello Worldfred@dev:~/test$ cat test.php
<?php

trait Ptrait
{
    private function foo($e)
    {
        echo $e;
    }
}

class Test
{
    use Ptrait;
    private $e;
    function __construct()
    {

    }
    public function test($str)
    {
        $this->e = $str;
        $this->foo($this->e);
    }
}

$t = new Test;

$t->test('Hello World');
fred@dev:~/test$
```

**Comment by r3wt** [comment]
oddly enough it seems to be working again?
