### ISSUE TITLE
resolv.h might not be portable?

### ISSUE THREAD

**Issue by jprjr** [facebook/hhvm#6178]
Hi there -

I've been working on packaging hhvm for a Linux distro that uses [musl libc](http://www.musl-libc.org/) instead of glibc. musl libc is focused on being to-spec (and not much else).

I've had a few errors come up from the usage of resolver functions like `res_nquery` from `resolv.h`, which (as far as I can tell) isn't formally defined by any specification. I think the various c libraries just integrated libbind's implementation.

Since resolv.h (and its functions) aren't defined by [POSIX](http://pubs.opengroup.org/onlinepubs/9699919799/toc.htm) or [ISO C](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf), should DNS resolution be handled by some library, like c-ares (or similar)?

I believe (if I'm reading the code right) that musl's implementations are stateless from the get-go, making `res_n*` functions irrelevant - http://git.musl-libc.org/cgit/musl/tree/src/network

Again, since it's not a formally defined interface it might make sense to use some library

**Comment by paulbiss** [comment]
We aren't officially supporting alternatives to glibc, and pulling in yet another dependency to do something simple doesn't sound like a great idea. I'm open to other solutions if you can come up with something that doesn't add new dependencies. I'm going to close this for now as it's an unsupported build issue.

**Comment by jprjr** [comment]
I'll see if I can come up with anything!

Another thought/idea I had - I noticed a lot of `#if` directives tend to fall back to a catch-all `#else` - would it make since to remove catch-all `#else` statements? That way you'll likely hit an error sooner rather than later on an unsupported platform.

**Comment by paulbiss** [comment]
I'm not sure I follow, can you paste an example? We have a number of platform specific directives but I'm not sure how removing the else would help (perhaps adding an else with an error directive would be a helpful hint but I thought we already did that in some cases).

**Comment by jprjr** [comment]
Sure thing - here's something from [hphp/runtime/base/thread-safe-setlocale.cpp#L208-L228](https://github.com/facebook/hhvm/blob/master/hphp/runtime/base/thread-safe-setlocale.cpp#L208-L228)

```
#ifdef _MSC_VER
struct lconv* ThreadSafeLocaleHandler::localeconv() {
  // We've setup locales to be thread local, so this is no
  // problem at all.
  struct lconv *ptr = g_thread_safe_localeconv_data.get();
  struct lconv *l = ::localeconv();
  memcpy(ptr, l, sizeof(struct lconv));
  return ptr;
}
#elif defined(__APPLE__)
struct lconv* ThreadSafeLocaleHandler::localeconv() {
  // BSD/OS X has localeconv_l, which actually returns data held onto by the
  // locale itself -- and since that's thread-local (since this object instance
  // is) we can just use that.
  // TODO is the memcpy even necessary?
  struct lconv *ptr = g_thread_safe_localeconv_data.get();
  struct lconv *l = localeconv_l(m_locale);
  memcpy(ptr, l, sizeof(struct lconv));
  return ptr;
}
#else
```

There's an else which assumes `__GLIBC__`, as opposed to another `#elf defined(__GLIBC__) || defined(__otherplatforms__)...`, then having something like `#else; #error` at the very end.

**Comment by paulbiss** [comment]
I think that would be reasonable, but then any resulting compile errors should be easy to deduce as related to the api being unsupported. Since we default to glibc and all other support is partial or experimental at this point I'm not sure how much value tracking all of these down would be. I'm a bit hesitant to add more macro pollution.

**Comment by Orvid** [comment]
As a note, the MSVC implementation doesn't have the APIs either, and uses the Windows API, WinDNS instead.
