### ISSUE TITLE
hhvm fails to build on my mac

### ISSUE THREAD

**Issue by amodell** [facebook/hhvm#6186]
Even after a brew update, the following still occurs for me:
thewizard-mbp1:local thewizard$ brew install hhvm
==> Installing hhvm from hhvm/homebrew-hhvm
==> Downloading http://dl.hhvm.com/source/hhvm-3.9.1.tar.bz2
Already downloaded: /Library/Caches/Homebrew/hhvm-3.9.1.tar.bz2
==> cmake -DENABLE_MCROUTER=OFF -DENABLE_EXTENSION_MCROUTER=OFF -DENABLE_EXTENSION_IMAP=OFF -DCCLIENT_INCLUDE_PATH=0 -DMYSQL_UNIX_SOCK_ADDR=/tmp/mysql.sock 
==> make
[100%] Built target symlink_libwebscalesqlclient_r.a
[ 13%] No install step for 'webscalesqlclient'
[ 13%] Completed 'webscalesqlclient'
[ 13%] Built target webscalesqlclient
make: *** [all] Error 2

gist-logs: https://gist.github.com/364a4d8b75e5dc46a0f1

**Comment by jwatzman** [comment]
Fixed in master, cf. https://github.com/hhvm/homebrew-hhvm/issues/8#issuecomment-137182692 -- try `brew install hhvm --HEAD`. I may pull in this patch in to a revision of the brew formula, since it also makes it easier to do bottles.

**Comment by jwatzman** [comment]
(Also, thank you for reporting against the right github project, despite the solution being in an issue reported against the wrong one :))
