### ISSUE TITLE
Yosemite 10.10.5, Build of HHVM failed to link in SSL

### ISSUE THREAD

**Issue by uweoswald** [facebook/hhvm#6187]
I did exactly what was listed. Step by Step. But after almost everything is done I got this error(s)

[100%] Linking CXX executable hhvm
Undefined symbols for architecture x86_64:
  "_SSLv2_client_method", referenced from:
      HPHP::SSLSocket::setupCrypto(HPHP::SSLSocket*) in libhphp_runtime.a(ssl-socket.cpp.o)
  "_SSLv2_server_method", referenced from:
      HPHP::SSLSocket::setupCrypto(HPHP::SSLSocket*) in libhphp_runtime.a(ssl-socket.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang-3.6: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [hphp/hhvm/hhvm] Error 1
make[2]: *** [hphp/hhvm/CMakeFiles/hhvm.dir/all] Error 2
make[1]: *** [hphp/hhvm/CMakeFiles/hhvm.dir/rule] Error 2
make: *** [hhvm] Error 2

And thats it. What can I do?

Thank you in advance for your help.

**Comment by jwatzman** [comment]
Interesting. I'll probably need to ask you more info about the configuration of your system, but I'm not sure right now what the right questions are, and I need to run :) In the mean time, the results of `brew gist-log hhvm` are generally useful; if that command fails (it should work but does fail for some people) the *full* output of `brew install --verbose hhvm` is useful. (Please pastebin that and link to it, it will be huge.)

**Comment by uweoswald** [comment]
Mmmm, I only have a free account (now) which doesn't allow me to use a direct fileupload. I have created a --verbose file since the other command haven't worked for me. The output is 500k. Any other idea how I can get it to you?
Thank you very much for your help.

**Comment by uweoswald** [comment]
OK, the --verbose log I have put into gist ( I hope so :-) )

https://gist.github.com/76a9d9f0b7b32292439b.git

But I have build a tar file of all logs which were mentioned at the bottom in the log. This does not work to paste into the Gist rep.

??!!

**Comment by uweoswald** [comment]
I have added the output from my first try to build hhvm. At the end you can see the errors I have in my first post. Hope it helps. If you need something else than do just ask :-)
Thank you.

**Comment by jwatzman** [comment]
Thanks for the info! I'm traveling and won't be able to get to this until Tuesday or Wednesday next week, sorry, but I will get back to you!

**Comment by uweoswald** [comment]
No hurry. I appreciate your help. 
Cheers,
Uwe

**Comment by jwatzman** [comment]
> OK, the --verbose log I have put into gist ( I hope so :-) )
> https://gist.github.com/76a9d9f0b7b32292439b.git

Did you delete this? I *think* it was working last week but is a 404 now.

**Comment by uweoswald** [comment]
no I did nothing. Will create a new git tomorrow. Sorry.

**Comment by wjywbs** [comment]
homebrew's openssl does not have SSLv2 support: https://github.com/Homebrew/homebrew-versions/issues/790#issuecomment-97863807, but somehow these methods are still used. I think it will link after commenting out the lines in https://github.com/facebook/hhvm/blob/baced5aa45d6abef04ff6595c761ab6f8cbc77e0/hphp/runtime/base/ssl-socket.cpp#L482-L490

For the gist link above, https://gist.github.com/76a9d9f0b7b32292439b still works.

Or can you try:
```
brew remove openssl
brew install hhvm
```

**Comment by uweoswald** [comment]
Does not seem to work. Test 1 with brew commands

 🍺  mbuweoswald(~/Downloads/hhvm) $ brew remove openssl
Uninstalling /usr/local/Cellar/openssl/1.0.2d_1... (464 files, 23M)
openssl 1.0.1i, 1.0.1j, 1.0.2a-1 are still installed.
Remove them all with `brew uninstall --force openssl`.
 🍺  mbuweoswald(~/Downloads/hhvm) $ brew remove openssl
Error: openssl has multiple installed versions
Use `brew uninstall --force openssl` to remove all versions.
 🍺  mbuweoswald(~/Downloads/hhvm) $ brew uninstall --force openssl
Uninstalling openssl... (1324 files, 47M)
 🍺  mbuweoswald(~/Downloads/hhvm) $ brew install hhvm

==> Installing hhvm from hhvm/homebrew-hhvm
==> Installing dependencies for hhvm/hhvm/hhvm: openssl
==> Installing hhvm/hhvm/hhvm dependency: openssl
==> Downloading https://homebrew.bintray.com/bottles/openssl-1.0.2d_1.yosemite.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/openssl-1.0.2d_1.yosemite.bottle.tar.gz
==> Pouring openssl-1.0.2d_1.yosemite.bottle.tar.gz
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl/certs

and run
  /usr/local/opt/openssl/bin/c_rehash

This formula is keg-only, which means it was not symlinked into /usr/local.

Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/openssl/lib
    CPPFLAGS: -I/usr/local/opt/openssl/include

==> Summary
🍺  /usr/local/Cellar/openssl/1.0.2d_1: 464 files, 18M
==> Installing hhvm/hhvm/hhvm
==> Downloading http://dl.hhvm.com/source/hhvm-3.9.1.tar.bz2
Already downloaded: /Library/Caches/Homebrew/hhvm-3.9.1.tar.bz2
==> cmake -DENABLE_MCROUTER=OFF -DENABLE_EXTENSION_MCROUTER=OFF -DENABLE_EXTENSION_IMAP=OFF -DCCLIENT_INCLUDE_PATH=0 -DMYSQL_UNIX_SOCK_ADDR=/tmp/mysql.sock -DCMAKE_C_FLAGS=-I/usr/local/opt/readline/include -L/usr/local/opt/readline/lib -DCMAKE_CXX_FLAGS=-I/usr/local/opt/readline/include -L/usr/local/opt/readline/lib -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/hhvm/
==> make
[100%] Built target symlink_libwebscalesqlclient_r.a
[  5%] No install step for 'webscalesqlclient'
[  5%] Completed 'webscalesqlclient'
[  5%] Built target webscalesqlclient
make: *** [all] Error 2
couldn't understand kern.osversion `14.5.0'
Warning: It appears you have MacPorts or Fink installed.
Software installed with other package managers causes known problems for
Homebrew. If a formula fails to build, uninstall MacPorts/Fink and try again.

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/hhvm/homebrew-hhvm/issues

 🍺  mbuweoswald(~/Downloads/hhvm) $

**Comment by uweoswald** [comment]
If I try to install by hand I receive a new error. I have commented out the lines you have mentioned in your post

[ 75%] Linking CXX static library libhphp_runtime_ext.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libhphp_runtime_ext.a(gd_arc_f_buggy.cpp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libhphp_runtime_ext.a(gd_arc_f_buggy.cpp.o) has no symbols
[ 75%] Built target hphp_runtime_ext
make[1]: *** [hphp/hhvm/CMakeFiles/hhvm.dir/rule] Error 2
make: *** [hhvm] Error 2

**Comment by jwatzman** [comment]
Can you please include the *full* output from `brew install --verbose hhvm` and/or `brew gist-log hhvm`, with an *unedited* source tree and brew formula? I still don't have a full log of what's going on -- everything you've posted so far is missing key pieces :(

**Comment by uweoswald** [comment]
Hi Josh,
sorry for the delay had now time left to take care about. Here is the --verbose log you've requested. I'm not quite sure what you mean with "brew formula". I'm not experienced with brew and all that stuff. One source I have edited as "wjywbs" suggested. However, hope this bring you further and helps us...

https://gist.github.com/uweoswald/d76fd90b8ae057c4ab20

**Comment by daviddoran** [comment]
FWIW I'm getting the exact same error:

	[100%] Linking CXX executable hhvm
	Undefined symbols for architecture x86_64:
	  "_SSLv2_client_method", referenced from:
		  HPHP::SSLSocket::setupCrypto(HPHP::SSLSocket*) in libhphp_runtime.a(ssl-socket.cpp.o)
	  "_SSLv2_server_method", referenced from:
		  HPHP::SSLSocket::setupCrypto(HPHP::SSLSocket*) in libhphp_runtime.a(ssl-socket.cpp.o)
	ld: symbol(s) not found for architecture x86_64
	clang-3.6: error: linker command failed with exit code 1 (use -v to see invocation)
	make[2]: *** [hphp/hhvm/hhvm] Error 1
	make[1]: *** [hphp/hhvm/CMakeFiles/hhvm.dir/all] Error 2
	make: *** [all] Error 2

Here's the first run of `brew install hhvm -v`:
https://gist.github.com/daviddoran/8f4101eee1ffb88ad0e6

Then I ran `brew update` and `brew upgrade` and tried installing again:
https://gist.github.com/daviddoran/14a9804e5ba0a58a04ea

Then I tried @wjywbs's suggestion to `brew remove openssl` and tried installing again:
https://gist.github.com/daviddoran/8769fc592166cbd7d6d7

**Comment by jwatzman** [comment]
@uweoswald the issue in the gist you just linked is unrelated to the original issue. It looks like you have a partial install of HHVM in `/opt/local` which is confusing things -- can you figure out where that came from, and/or just remove MacPorts, since as brew says, the two don't always play nice together. I suspect your SSL issue is due to the same reason -- some stuff from MacPorts is getting picked up by the build.

@daviddoran you have the same problem. Remove MacPorts (or move it out of `/opt/local`, or move `/opt/local` out of the way temporarily) and see if that helps.

I can try to make the build script more explicit so it doesn't pick things up out of `/opt/local` when you're using brew, but that is going to be an uphill battle. The warning about using the two together is there for a reason.

**Comment by jwatzman** [comment]
Has anyone tried moving `/opt/local` out of the way? Does that fix the issue?

**Comment by denji** [comment]
@jwatzman This is due to MacPorts hacks when building HHVM?

**Comment by jwatzman** [comment]
@denji That code should probably not be there. However, this is a general problem. The brew folks themselves do not recommend that brew and MacPorts be installed together. It's too easy for brew programs to accidentally pick up MacPorts parts, and vice versa.

**Comment by denji** [comment]
We should first look for Homebrew (sandbox without-root environment) and only if it is not applicable to move to a more systematic Macports. This is my vidie solve.

**Comment by daviddoran** [comment]
Just to confirm, I removed MacPorts and HHVM built fine.

**Comment by jwatzman** [comment]
> cmake must issue a warning about the conflict

brew itself already issues this warning. It's not just an HHVM problem. That said, I'm going to try to be more explicit in our cmake library specifications when I get time, see https://github.com/hhvm/homebrew-hhvm/issues/16

> Just to confirm, I removed MacPorts and HHVM built fine.

Awesome, glad it worked out! I'm going to close out this issue since we have a working workaround. Feel free to track https://github.com/hhvm/homebrew-hhvm/issues/16 if you're interested.

**Comment by GroovyCarrot** [comment]
Removing MacPorts also solved this issue for me
