### ISSUE TITLE
Unable to compile hhvm on linux alpine

### ISSUE THREAD

**Issue by roman-shuhov** [facebook/hhvm#6188]
I'm trying to compile hhvm on linux alpine and the first part goes smooth:

cmake output - https://gist.github.com/roman-shuhov/a6c69fab292c2e82a727

but next "make" command fails to compile folly library:

https://gist.github.com/roman-shuhov/032d5fea6e5b17b5cd65

Do you know how can i fix this issue?

**Comment by paulbiss** [comment]
The warnings in the cmake output all look rather serious. I don't know anything about alpine linux, we don't officially support it. You may have better luck asking in our irc channel on Freenode (#hhvm). A number of the regulars in there have managed to get hhvm building on non-officially-supported distros.

**Comment by roman-shuhov** [comment]
Do you have any thoughts how can i fix these warnings?

**Comment by paulbiss** [comment]
Looks like it's failing to find some of the targets it needs to link against, or it's an incompatibility with the way that the linker is taking arguments. Not really sure :/ You're probably going to have better luck asking on IRC, there's not much we can do to help with an unsupported platform, particularly with so little idea what's going on.
