### ISSUE TITLE
wrong permission on external extension file

### ISSUE THREAD

**Issue by karpa13a** [facebook/hhvm#6201]
Hello
if hhvm(in daemon mode) unable to load external extension on startup due permission problems it does not fails to start or write any error in any log:
in my case (ubuntu 14.04, today nightly) with mongo.so:
adding to php.ini:
```
hhvm.dynamic_extension_path = /var/tmp/1
hhvm.dynamic_extensions[mongo] = mongo.so
```

placing mongo.so in that dir, chown root /var/tmp/1; chmod 700 /var/tmp/1
service hhvm start do not produces error. it works, but extension do not load.

**Comment by paulbiss** [comment]
This feature request is not actively being worked on. We would happily consider a pull request implementing it. If you plan to work on this issue let us know in the comments and we will re-open the issue and assign it to you. If you feel strongly that this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
