### ISSUE TITLE
Test slow/ext_string/setlocale-fail.php is locale dependend

### ISSUE THREAD

**Issue by SiebelsTim** [facebook/hhvm#6202]
This test initially sets the locale to empty string, which falls back to environment variables.
Every failing call does that too. 

So in France, every failing call trying to set a french locale returns false, but sets the locale to french.

I tried setting the environment variables with `putenv` without success.

---

The test:
```
<?php

setlocale(LC_ALL, "");

// Let's try some terrible locales to ensure they fail
test(LC_ALL, 'LC_ALL=fr_FR');
test(LC_ALL, 'LC_ALL=fr_FR;');
test(LC_ALL, 'LC_NUMERIC=fr_FR');
test(LC_ALL, 'LC_NUMERIC=fr_FR;');
test(LC_ALL, 'fr_FR;');
test(LC_ALL, '=fr_FR');
test(LC_ALL, '=fr_FR;');

test(LC_NUMERIC, 'LC_NUMERIC=fr_FR');

// This weirdly is a valid statement for newlocale/uselocale
// but not for setlocale.
// We check for and disable it explicitly in the code.
test(LC_NUMERIC, 'LC_NUMERIC=fr_FR;');

test(LC_NUMERIC, 'fr_FR;');
test(LC_NUMERIC, '=fr_FR');
test(LC_NUMERIC, '=fr_FR;');

function test($category, $locale) {
  var_dump(setlocale($category, $locale));
  echo sprintf("%.3f\n", 3.142);
  setlocale(LC_ALL, "");
}
```

**Comment by Orvid** [comment]
We're a small team, and it doesn't look as though anyone in the community is actively working on this issue, so we've decided to close it. If you plan to send us a pull request resolving the issue let us know in the comments and we will re-open it and assign it to you. If you feel this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
