### ISSUE TITLE
having problems pushing into array from for loop

### ISSUE THREAD

**Issue by r3wt** [facebook/hhvm#6208]
```php
$urls = []; //holds our urls. gets truncated every 10k urls.

for($count=0;$count<$total;$count++)
{
	
	if($count % 10000 == 0 || $count == $total)
	{
		renderSave($twig,$urls,$num,$save_path);
		truncate($urls);
		$num++;
	}
	
	$row = $all[$count];
	array_push($urls, [
		'link'=>$base_url.$row['tmp'].$row['id'].'/'.$row['uri'],
		'date'=> date('Y-m-d', time()),
		'priority'=>'1.0'
	]);
	
}
```
if i remove the if statement, it works and the url is populated

**Comment by JoelMarcey** [comment]
I am not sure I understand the problem. Are you saying you want to purposely truncate every 10000th URL and that is not working?

**Comment by SiebelsTim** [comment]
@JoelMarcey I **guess** he's saving the current array to some file after 10000 elements. To keep the array small or something.

---

Anyway, this is no isolated example. It would be best if you can come up with an isolated test case.

**Comment by fredemmott** [comment]
Sorry, we *need* a self-contained example for this. There is pretty much no chance that:
 - this will be investigated without one
 - any investigation would find the problem you have - we already have fairly imaginative tests for pushing into arrays from loops, and a lot of real code doing the same thing that works fine.

**Comment by r3wt** [comment]
@SiebelsTim every 10k entries it writes an xml file like `sitemap<num>.xml` i ended up just using array chunk and iterating over each chunk instead. don't have time to investigate it right now.

**Comment by fredemmott** [comment]
FYI, there is a bug in your example, which will result in no output if < 10,000 urls, and incomplete output if more:

```
for($count=0;$count<$total;$count++)
{

    if($count % 10000 == 0 || $count == $total)
    //                        ^^^^^^^^^^^^^^^^
    //                        ^ impossible, as you just checked $count < $total in
    //                        loop condition```
```
