### ISSUE TITLE
SegmentationFault on Deployment (Laravel 5.1)

### ISSUE THREAD

**Issue by nevrending** [facebook/hhvm#6210]
Hello
Previously I had "asked" about this at SO
http://stackoverflow.com/questions/31958862/how-to-properly-configure-supervisord-for-hhvm

But at that time I'm unable to find out the real culprit.
After some time I was quite sure that the segfault occurred after almost every deployment.

I'm deploying using a simple `shell_exec('cd .. && php artisan down && git pull origin master && php artisan clear-compiled && php artisan optimize && php artisan queue:restart && php artisan up')`

Right after deployment, when I access the website, HHVM would crash with a segfault.

    [Tue Sep  8 22:08:18 2015] [hphp] [22902:7f8ae17ff700:12:000001] [] Core dumped: Segmentation fault
    [Tue Sep  8 22:08:18 2015] [hphp] [22902:7f8ae17ff700:12:000002] [] Stack trace in /tmp/stacktrace.22902.log

The stacktrace

    PHP Stacktrace:

    #0  Illuminate\Container\Container::setInstance(Object of class Illuminate\Foundation\Application could not be converted to string) called at [/var/www/abc.com/bootstrap/cache/compiled.php:1367]
    #1  Illuminate\Foundation\Application->registerBaseBindings() called at [/var/www/abc.com/bootstrap/cache/compiled.php:1354]
    #2  Illuminate\Foundation\Application->__construct(/var/www/abc.com) called at [/var/www/abc.com/bootstrap/app.php:16]
    #3  include(/var/www/abc.com/bootstrap/app.php) called at [/var/www/abc.com/public/index.php:36]

[compiled.php:1367]

    protected function registerBaseBindings()
        {
            static::setInstance($this);    << line 1367
            $this->instance('app', $this);
            $this->instance('Illuminate\\Container\\Container', $this);
        }

[compiled.php:1354]

    public function __construct($basePath = null)
        {
            $this->registerBaseBindings();    << line 1354
            $this->registerBaseServiceProviders();
            $this->registerCoreContainerAliases();
            if ($basePath) {
                $this->setBasePath($basePath);
            }
        }

HHVM version

    HipHop VM 3.9.1 (rel)
    Compiler: tags/HHVM-3.9.1-0-g0f72cfc2f0a01fdfeb72fbcfeb247b72998a66db
    Repo schema: 6416960c150a4a4726fda74b659105ded8819d9c

Note: the `php` CLI itself is a HHVM alternative

    me@server:~$ php --version
    HipHop VM 3.9.1 (rel)
    Compiler: tags/HHVM-3.9.1-0-g0f72cfc2f0a01fdfeb72fbcfeb247b72998a66db
    Repo schema: 6416960c150a4a4726fda74b659105ded8819d9c

Note 2: HHVM is on fast-cgi with Nginx

Note 3: Strangely enough, after deploying and HHVM crashed with segfault, I'd only need to re-start HHVM, and everything will work again

Please let me know should you require additional info
Thank you

**Comment by paulbiss** [comment]
Can you extract backtraces from the core file (`thread apply all bt` in gdb)?

**Comment by nevrending** [comment]
@paulbiss Sorry I've never used gdb before. Can you please give some pointers as of how/where I can learn to do that?

**Comment by nevrending** [comment]
@paulbiss 

    (gdb) thread apply all bt

    Thread 4 (Thread 0x7fc737fff700 (LWP 30417)):
    #0  0x00007fc748866b13 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
    #1  0x00007fc74af1c813 in ?? () from /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5
    #2  0x00007fc74af08907 in event_base_loop () from /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5
    #3  0x00000000025b5056 in folly::EventBase::loopBody(int) ()
    #4  0x00000000025b76d9 in folly::EventBase::loopForever() ()
    #5  0x000000000208caca in proxygen::WorkerThread::runLoop() ()
    #6  0x000000000208cd0f in std::thread::_Impl<std::_Bind_simple<proxygen::WorkerThread::start()::{lambda()#1} ()> >::_M_run() ()
    #7  0x00007fc7490fea40 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
    #8  0x00007fc749359182 in start_thread (arg=0x7fc737fff700) at pthread_create.c:312
    #9  0x00007fc74886647d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

    Thread 3 (Thread 0x7fc732fff700 (LWP 30448)):
    #0  pthread_cond_wait@@GLIBC_2.3.2 ()
        at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
    #1  0x0000000001e5deb8 in HPHP::SynchronizableMulti::waitImpl(int, int, bool, timespec*) ()
    #2  0x0000000000e4bdea in HPHP::JobQueueWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::Server*, true, false, HPHP::JobQueueDropVMStack>::start() ()
    #3  0x0000000001e8b527 in HPHP::AsyncFuncImpl::ThreadFunc(void*) ()
    #4  0x0000000000c29287 in HPHP::start_routine_wrapper(void*) ()
    #5  0x00007fc749359182 in start_thread (arg=0x7fc732fff700) at pthread_create.c:312
    #6  0x00007fc74886647d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
    ---Type <return> to continue, or q <return> to quit---

    Thread 2 (Thread 0x7fc72c3ff700 (LWP 3714)):
    #0  pthread_cond_wait@@GLIBC_2.3.2 ()
        at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
    #1  0x0000000001e5deb8 in HPHP::SynchronizableMulti::waitImpl(int, int, bool, timespec*) ()
    #2  0x0000000000e4bdea in HPHP::JobQueueWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::Server*, true, false, HPHP::JobQueueDropVMStack>::start() ()
    #3  0x0000000001e8b527 in HPHP::AsyncFuncImpl::ThreadFunc(void*) ()
    #4  0x0000000000c29287 in HPHP::start_routine_wrapper(void*) ()
    #5  0x00007fc749359182 in start_thread (arg=0x7fc72c3ff700) at pthread_create.c:312
    #6  0x00007fc74886647d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

    Thread 1 (Thread 0x7fc7387ff700 (LWP 30085)):
    #0  pthread_cond_wait@@GLIBC_2.3.2 ()
        at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
    #1  0x0000000000e33f68 in HPHP::HttpServer::runOrExitProcess() ()
    #2  0x0000000000ceb314 in HPHP::execute_program_impl(int, char**) ()
    #3  0x0000000000ced1df in HPHP::execute_program(int, char**) ()
    #4  0x0000000000a9e4e1 in main ()

**Comment by nevrending** [comment]
@paulbiss I've managed to extract the backtraces

    Program received signal SIGSEGV, Segmentation fault.
    [Switching to Thread 0x7fffd5fff700 (LWP 16113)]
    0x0000000001002764 in HPHP::InstanceBits::lookup(HPHP::StringData const*) ()
    (gdb) thread apply all bt

    Thread 6 (Thread 0x7fffd5fff700 (LWP 16113)):
    #0  0x0000000001002764 in HPHP::InstanceBits::lookup(HPHP::StringData const*) ()
    #1  0x0000000000f84c13 in void HPHP::Class::setInstanceBitsImpl<true>() ()
    #2  0x0000000000f84da6 in HPHP::Class::setInstanceBitsAndParents() ()
    #3  0x0000000001003363 in HPHP::InstanceBits::init() ()
    #4  0x000000000109714d in HPHP::jit::irgen::(anonymous namespace)::implInstanceCheck(HPHP::jit::IRGS&, HPHP::jit::SSATmp*, HPHP::StringData const*, HPHP::jit::SSATmp*) [clone .part.144] ()
    #5  0x000000000109827a in HPHP::jit::irgen::(anonymous namespace)::verifyTypeImpl(HPHP::jit::IRGS&, int) ()
    #6  0x00000000011f3be2 in HPHP::jit::translateInstr(HPHP::jit::IRGS&, HPHP::jit::NormalizedInstruction const&, bool, bool) ()
    #7  0x0000000001369cf9 in HPHP::jit::(anonymous namespace)::RegionFormer::go() ()
    #8  0x000000000136bb09 in HPHP::jit::selectTracelet(HPHP::jit::RegionContext const&, bool, bool) ()
    #9  0x00000000010bc500 in HPHP::jit::selectRegion(HPHP::jit::RegionContext const&, HPHP::jit::TransKind) ()
    #10 0x0000000001502739 in HPHP::jit::MCGenerator::translateWork(HPHP::jit::TranslArgs const&) ()
    #11 0x0000000001504994 in HPHP::jit::MCGenerator::translate(HPHP::jit::TranslArgs const&) ()
    #12 0x0000000001504c14 in HPHP::jit::MCGenerator::retranslate(HPHP::jit::TranslArgs const&) ()
    #13 0x00000000015050fe in HPHP::jit::MCGenerator::createTranslation(HPHP::jit::TranslArgs const&)
        ()
    #14 0x0000000001505544 in HPHP::jit::MCGenerator::bindJmp(unsigned char*, HPHP::SrcKey, HPHP::jit::ServiceRequest, HPHP::jit::TransFlags, bool&) ()
    ---Type <return> to continue, or q <return> to quit---
    #15 0x000000000150b027 in MCGenerator_handleServiceRequest ()
    #16 0x000000000156bcd6 in handleSRHelper ()
    #17 0x00000000025e0a29 in enterTCHelper ()
    #18 0x0000000001196386 in HPHP::jit::x64::(anonymous namespace)::BackEnd::enterTCHelper(unsigned char*, HPHP::ActRec*) ()
    #19 0x00000000014f422b in HPHP::jit::MCGenerator::enterTC(unsigned char*, HPHP::ActRec*) ()
    #20 0x0000000000f42a4e in HPHP::enterVMAtFunc(HPHP::ActRec*, HPHP::StackArgsState, HPHP::VarEnv*)
        ()
    #21 0x00000000025dfd5a in HPHP::ExecutionContext::invokeFunc(HPHP::TypedValue*, HPHP::Func const*, HPHP::Variant const&, HPHP::ObjectData*, HPHP::Class*, HPHP::VarEnv*, HPHP::StringData*, HPHP::ExecutionContext::InvokeFlags) ()
    #22 0x0000000002624c0d in HPHP::ExecutionContext::invokeUnit(HPHP::TypedValue*, HPHP::Unit const*)
        ()
    #23 0x0000000000bbac45 in HPHP::include_impl_invoke(HPHP::String const&, bool, char const*) ()
    #24 0x0000000000cd5e84 in HPHP::hphp_invoke(HPHP::ExecutionContext*, std::string const&, bool, HPHP::Array const&, HPHP::VRefParamValue const&, std::string const&, std::string const&, bool&, std::string&, bool, bool, bool) ()
    #25 0x0000000000ddeb26 in HPHP::HttpRequestHandler::executePHPRequest(HPHP::Transport*, HPHP::RequestURI&, HPHP::SourceRootInfo&, bool) ()
    #26 0x0000000000de0c8e in HPHP::HttpRequestHandler::handleRequest(HPHP::Transport*) ()
    #27 0x0000000000e4d41a in HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJobImpl(std::shared_ptr<HPHP::FastCGIJob>, bool) ()
    #28 0x0000000000e4d98e in HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITranspo---Type <return> to continue, or q <return> to quit---
    rtTraits>::doJob(std::shared_ptr<HPHP::FastCGIJob>) ()
    #29 0x0000000000e4c006 in HPHP::JobQueueWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::Server*, true, false, HPHP::JobQueueDropVMStack>::start() ()
    #30 0x0000000001e8b527 in HPHP::AsyncFuncImpl::ThreadFunc(void*) ()
    #31 0x0000000000c29287 in HPHP::start_routine_wrapper(void*) ()
    #32 0x00007ffff15a6182 in start_thread (arg=0x7fffd5fff700) at pthread_create.c:312
    #33 0x00007ffff0ab347d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

    Thread 5 (Thread 0x7fffdb3ff700 (LWP 16015)):
    #0  pthread_cond_wait@@GLIBC_2.3.2 ()
        at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
    #1  0x0000000001e5deb8 in HPHP::SynchronizableMulti::waitImpl(int, int, bool, timespec*) ()
    #2  0x0000000000e4bdea in HPHP::JobQueueWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::Server*, true, false, HPHP::JobQueueDropVMStack>::start() ()
    #3  0x0000000001e8b527 in HPHP::AsyncFuncImpl::ThreadFunc(void*) ()
    #4  0x0000000000c29287 in HPHP::start_routine_wrapper(void*) ()
    #5  0x00007ffff15a6182 in start_thread (arg=0x7fffdb3ff700) at pthread_create.c:312
    #6  0x00007ffff0ab347d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

    Thread 4 (Thread 0x7fffdffff700 (LWP 16014)):
    #0  0x00007ffff0ab3b13 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
    #1  0x00007ffff3169813 in ?? () from /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5
    #2  0x00007ffff3155907 in event_base_loop () from /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5
    ---Type <return> to continue, or q <return> to quit---
    #3  0x00000000025b5056 in folly::EventBase::loopBody(int) ()
    #4  0x00000000025b76d9 in folly::EventBase::loopForever() ()
    #5  0x000000000208caca in proxygen::WorkerThread::runLoop() ()
    #6  0x000000000208cd0f in std::thread::_Impl<std::_Bind_simple<proxygen::WorkerThread::start()::{lambda()#1} ()> >::_M_run() ()
    #7  0x00007ffff134ba40 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
    #8  0x00007ffff15a6182 in start_thread (arg=0x7fffdffff700) at pthread_create.c:312
    #9  0x00007ffff0ab347d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

    Thread 1 (Thread 0x7ffff7fc7a00 (LWP 16005)):
    #0  pthread_cond_wait@@GLIBC_2.3.2 ()
        at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
    #1  0x0000000000e33f68 in HPHP::HttpServer::runOrExitProcess() ()
    #2  0x0000000000ceb314 in HPHP::execute_program_impl(int, char**) ()
    #3  0x0000000000ced1df in HPHP::execute_program(int, char**) ()
    #4  0x0000000000a9e4e1 in main ()

**Comment by paulbiss** [comment]
@nevrending interesting, thanks. I'll see if I can figure out what's going on here

**Comment by bratao** [comment]
Just to confirm that I also have this problem. hhvm crash every time I deploy Laravel 5.1. My system is a standard Debian 8 with nginx + hhvm.

**Comment by bratao** [comment]
@paulbiss , Sorry for pinging you, but do you have any update on this issue ? This have severely messed our environment, as on almost every deployment, hhvm crashes =(

**Comment by nevrending** [comment]
Hi @paulbiss , sorry for bumping this, just wondering if you have any update on this issue?

**Comment by jwatzman** [comment]
I don't think anyone has had time to look into this, sorry. :(
