### ISSUE TITLE
Eliminating HHI files

### ISSUE THREAD

**Issue by Orvid** [facebook/hhvm#6211]
Ideally both hh_client and HHVM can use the same set of declarations, however they currently use separate ones.

What issues currently prevent hh_client from being able to simply use the same declarations HHVM uses?

- [ ] Figure out how to handle the differences in typing between the Hack version of the PHP API, and the HHVM version. Perhaps a `coercedTo(int)` type hint, that's interpreted as `mixed` by HHVM and `int` by hh_client could help to achieve this?
- [ ] Allow declaring constants in HHVM without a value. Perhaps via `<<__Native>>`?

**Comment by JoelMarcey** [comment]
@Orvid This is on our radar to do. We need to convert a few more things to HNI first, particularly collections.

**Comment by paulbiss** [comment]
Additionally the types we expose to hh_client and hhvm aren't necessarily the same. Often we intentionally omit return types or enforce particular patterns in Hack that are not required in PHP (e.g. needle/haystack order).

**Comment by Orvid** [comment]
Towards this, it also needs to be possible to declare a constant as `<<__Native>>`, to allow it to not have a value. It's possible to declare a constant without a value with hh_client, but not with HHVM. 

Currently with HHVM, it's possible to declare the constants in the systemlib, and the value you register them to be at runtime will be what is used.

An example that won't actually compile because this is clearer:
```C++
registerClassConstant("MyClass", "MY_CONST", 30);
```
and this declaration in the systemlib:
```PHP
class MyClass {
  const int MY_CONST = 5;
}
```
Anything referencing `MyClass::MY_CONST` will (correctly) get a value of `30`, rather than the `5` that it's declared as in the systemlib.
