### ISSUE TITLE
hhvm and apache

### ISSUE THREAD

**Issue by droid-Q** [facebook/hhvm#6214]
this is my httpd-vhosts.conf:https://gist.github.com/droid-Q/35458fd74c7f695c46a6
my server.ini:https://gist.github.com/droid-Q/2e18dc7cafbe34b0ade0,
I want to apache listing the contents  that has no index.php in the http://localhost/,
Now in the http://locahost/phpMyAdmin/ the index.php is not loaded.
how can i fix it?

**Comment by paulbiss** [comment]
This looks like an apache configuration issue not an hhvm problem. I'd suggest asking in #hhvm on Freenode, someone there may be able to help you get your apache config setup.
