### ISSUE TITLE
Destroying uninitialized data with an HNI constructor for a NativeData

### ISSUE THREAD

**Issue by Orvid** [facebook/hhvm#6215]
Attempting to call an HNI constructor for a NativeData object, with invalid parameter types, results in attempting to destroy the NativeData object before it's been initialized.

If we take the following Native Data structure:
```C++
struct ZMQCert {
  zcert_t* zcert;
  ~ZMQCert() {
    if (zcert) {
      zcert_destroy(&zcert);
    }
  }
};
```
And we have its constructor defined an registered as:
```C++
void HHVM_METHOD(ZMQCert, __construct, const Variant& filename) {
  auto cert = Native::data<ZMQCert>(this_);

  if (filename.isNull()) {
    cert->zcert = zcert_new();
  } else {
    cert->zcert = zcert_load(filename.asCStrRef().c_str());
  }
}
```
And declared in the system library as:
```PHP
<<__NativeData("ZMQCert")>>
class ZMQCert {
  <<__Native>>
  public final function __construct(?string $filename = null): void;
}
```

Attempting to call it like this:
```PHP
date_default_timezone_set('Europe/London');
$dateTime = new DateTime();

try {
  $cert = new ZMQCert($dateTime);
} catch (ZMQCertException $e) {
  var_dump($e->getMessage());
}
```

Results in a call to `ZMQCert::~ZMQCert()` with an instance that hasn't been initialized yet, which in turn ends up causing a segfault inside of `zcert_destroy`.

**Comment by paulbiss** [comment]
You should be initializing zcert to nullptr in the constructor for the native-data (struct ZMQCert). The native-data C++ constructor is called unconditionally before the PHP __construct is called and should leave the native-data in a consistent state that's safe to destruct from.

**Comment by Orvid** [comment]
So, the answer is that I am simply too used to default-initialized languages -_-... Huzzah?
