### ISSUE TITLE
hhvm make error on linuxmint-17.2-cinnamon-64bit

### ISSUE THREAD

**Issue by vikasbatra** [facebook/hhvm#6228]
../hhbbc/libhphp_hhbbc.a(type-system.cpp.o):type-system.cpp:function HPHP::HHBBC::make_repo_type(HPHP::ArrayTypeTable::Builder&, HPHP::HHBBC::Type const&): error: undefined reference to 'HPHP::ArrayTypeTable::Builder::packed(HPHP::RepoAuthType::Array::Empty, std::vector<HPHP::RepoAuthType, std::allocator<HPHP::RepoAuthType> > const&)'
../hhbbc/libhphp_hhbbc.a(type-system.cpp.o):type-system.cpp:function HPHP::HHBBC::make_repo_type_arr(HPHP::ArrayTypeTable::Builder&, HPHP::HHBBC::Type const&): error: undefined reference to 'HPHP::ArrayTypeTable::Builder::packed(HPHP::RepoAuthType::Array::Empty, std::vector<HPHP::RepoAuthType, std::allocator<HPHP::RepoAuthType> > const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [hphp/hhvm/hhvm] Error 1
make[1]: *** [hphp/hhvm/CMakeFiles/hhvm.dir/all] Error 2
make: *** [all] Error 2

**Comment by Orvid** [comment]
If this is still happening on master, feel free to re-open the issue.
