### ISSUE TITLE
Calling mysqli_get_charset results in error

### ISSUE THREAD

**Issue by shadowhand** [facebook/hhvm#6231]
> Value returned from function mysqli_get_charset() must be of type object, stdClass given

Which makes it impossible to determine what the current character set in use by MySQL is.

cc @dolfelt

**Comment by SiebelsTim** [comment]
https://github.com/facebook/hhvm/blob/4498e2b25bc17ace502b4c86c551dbab25f284bf/hphp/runtime/ext/mysql/ext_mysqli.php#L1724

The return type is supposed to be `mixed`, as `mysqli::get_charset()` is mixed as well.
