### ISSUE TITLE
Calling mysqli_set_charset appears to do nothing

### ISSUE THREAD

**Issue by shadowhand** [facebook/hhvm#6232]
Calling `mysqli_set_charset` appears to have no effect on the connection. A complete test script and results can be found below.

```
$ hhvm --version
HipHop VM 3.9.1 (rel)
Compiler: tags/HHVM-3.9.1-0-g0f72cfc2f0a01fdfeb72fbcfeb247b72998a66db
Repo schema: 6416960c150a4a4726fda74b659105ded8819d9c
```

Refs #6231

cc @dolfelt

**Comment by shadowhand** [comment]
Here's a complete test script:

```php

$host = 'localhost';
$user = 'root';
$pass = '';
$db   = 'testapp';

$connection = mysqli_connect($host, $user, $pass, $db);

mysqli_set_charset($connection, 'utf8');

print_r(mysqli_fetch_row(mysqli_query(
    $connection,
    'SHOW VARIABLES LIKE "%character_set%"'
)));
```

When I execute this with `hhvm test.php` I get:

```
Array
(
    [0] => character_set_client
    [1] => latin1
)
```

I expect to get the same value that I used for `mysqli_set_charset` but did not.

**Comment by SiebelsTim** [comment]
You use `mysql_set_charset(connection, charset)`, however it is supposed to be `mysql_set_charset(charset, connection)`

**Comment by SiebelsTim** [comment]
I can't reproduce this. I have the same hhvm version.

```
$ hhvm charset.php
original: Array
(
    [0] => character_set_client
    [1] => latin1
)
functional: Array
(
    [0] => character_set_client
    [1] => utf8
)
manual: Array
(
    [0] => character_set_client
    [1] => utf8
)

```

Can you give more information on your operating system and mysql version?
```
$ mysql --version 
mysql  Ver 14.14 Distrib 5.5.44, for debian-linux-gnu (x86_64) using readline 6.3
```
On Ubuntu 14.04

**Comment by shadowhand** [comment]
@swettk can you provide some additional details about the MySQL server and HHVM package?

**Comment by SiebelsTim** [comment]
```
Server version: 5.5.44-0ubuntu0.14.04.1 (Ubuntu)
```
```
$ hhvm --version
HipHop VM 3.9.1 (rel)
Compiler: tags/HHVM-3.9.1-0-g0f72cfc2f0a01fdfeb72fbcfeb247b72998a66db
Repo schema: 6416960c150a4a4726fda74b659105ded8819d9c
```

**Comment by shadowhand** [comment]
For what it is worth, I cannot reproduce this when connecting to a single-node server either locally or over TCP. The is a working mysql:

```
$ mysql --version
mysql  Ver 14.14 Distrib 5.6.25-73.1, for debian-linux-gnu (x86_64) using readline 6.3
$ cat /etc/issue
Ubuntu 14.04.3 LTS
```

This is the mysql that is not working:

```
5.6.21-70.1-56-log
Ubuntu 12.04.5 LTS
```

**Comment by shadowhand** [comment]
We're updating the non-working box to see if mysql upgrade fixes it.

**Comment by shadowhand** [comment]
A followup on this... before attempting to upgrade, we decided to try running PDO instead of MySQLi, but the exact same symptoms appear: selecting any data with ASCII extended characters ends up coming back as ISO-8859-1 instead of UTF-8. This happens despite the fact that we worked around setting the character set and have confirmed that the entire connection is using `utf8`:

```
Array
(
    [0] => Array
        (
            [Variable_name] => character_set_client
            [Value] => utf8
        )

    [1] => Array
        (
            [Variable_name] => character_set_connection
            [Value] => utf8
        )

    [2] => Array
        (
            [Variable_name] => character_set_database
            [Value] => utf8
        )

    [3] => Array
        (
            [Variable_name] => character_set_filesystem
            [Value] => binary
        )

    [4] => Array
        (
            [Variable_name] => character_set_results
            [Value] => utf8
        )

    [5] => Array
        (
            [Variable_name] => character_set_server
            [Value] => utf8
        )

    [6] => Array
        (
            [Variable_name] => character_set_system
            [Value] => utf8
        )

    [7] => Array
        (
            [Variable_name] => character_sets_dir
            [Value] => /usr/share/mysql/charsets/
        )

)
```

**Comment by shadowhand** [comment]
Okay, we upgraded our database servers to latest version but are still experiencing the same bug. The new mysql version is:

```
5.6.24-72.2-56-log
Percona XtraDB Cluster (GPL), Release rel72.2, Revision 43abf03, WSREP version 25.11, wsrep_25.11
```

It seems quite possible that the issue is because our production machines are percona cluster, not a single MySQL server. This issue does not appear when connecting to a single DB server, only when using the cluster.

**Comment by shadowhand** [comment]
Actually it appears the issue is not percona cluster itself, but using clustering with [maxscale](https://mariadb.com/products/mariadb-maxscale) that causes the issue. When we disable maxscale and connect directly to the cluster, everything works normally.

**Comment by shadowhand** [comment]
We can reliably reproduce the issue when using maxscale with both php-fpm and hhvm, so this does not appear to be specific to HHVM. However, we are unable to produce it with Ruby connecting to maxscale, so it seems to be something specific to PHP.

**Comment by shadowhand** [comment]
We've narrowed the cause down to Maxscale, which [copies the client settings on connection][1] and never updates them after the fact. This is not a HHVM bug or a PHP bug, it is a bug in Maxscale.

Thanks for the patience, everyone!

[1]: https://github.com/mariadb-corporation/MaxScale/blob/590f66a8e899ea6ffec9906bea1c2a014ab128b5/server/modules/protocol/mysql_backend.c#L951-L964
