### ISSUE TITLE
Passing an array to a function resets the current pointer in Zend, not in HHVM

### ISSUE THREAD

**Issue by rowillia** [facebook/hhvm#6233]
```php
<?php

class ArrayTest extends PHPUnit_Framework_TestCase {
  private static $test_array = array('hello' => array('world' => 'yah'));

  public function testArrayCurrent() {
    $config = self::$test_array['hello'];
    foreach ($config as &$element) {
      $this->assertEquals('yah', $element);
    }
    $this->assertEquals('yah', $this->someBullshitFunction($config));
  }
  public function someBullshitFunction($arr) {
    return current($arr);
  }
}
```

This test passes on Zend but fails on HHVM.

PHP 5.6.13-1+deb.sury.org~trusty+3 (cli)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.3.2, Copyright (c) 2002-2015, by Derick Rethans

**Comment by jwatzman** [comment]
Pretty sure this is a known inconsistency with array pointers we aren't going to fix? https://github.com/facebook/hhvm/blob/master/hphp/doc/inconsistencies

**Comment by paulbiss** [comment]
Yeah, that's basically what the inconsistency is about. The array is passed by value so it's technically a copy even though we use COW. I don't think we're going to fix this one unless there's a pretty compelling reason to.
