### ISSUE TITLE
curl_errno() always returns 0 with HH\Asio\curl_exec

### ISSUE THREAD

**Issue by ebernhardson** [facebook/hhvm#6236]
When switching from curl_exec to HH\Asio\curl_exec the error handling properties change.  curl_exec return false on failure and reports errors through curl_errno(). HH\Asio\curl_exec returns the empty string on failure and does not appear to offer up error codes in any way.  The codes are available within HH\Asio\curl_exec while it has access to the multi handle, through curl_multi_info_read, but this is not exposed to the programmer afaict.

    <?hh

    function createHandle() : resource {
        $ch = curl_init("http://localhost:54321");
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        return $ch;
    }

    function main() : void {
        $ch = createHandle();
        curl_exec($ch);
        echo 'plain curl_exec: ';
        var_dump(curl_errno($ch));

        $ch = createHandle();
        HH\Asio\curl_exec($ch)->getWaitHandle()->join();
        echo 'async curl_exec: ';
        var_dump(curl_errno($ch));
    }

    main();

The expected result is:
    plain curl_exec: int(7)
    async curl_exec: int(7)

But the actual result is:
    plain curl_exec: int(7)
    async curl_exec: int(0)

**Comment by apeabody** [comment]
I was looking into this, but unfortunately this appears to be the expected (non-desirable) curl_errno behavior as async curl_exec is a wrapper to curl_multi_exec which requires using curl_multi_info_read to get the curl error code - this makes sense as each of the multi operations could have a different code.

https://bugs.php.net/bug.php?id=60660

@Orvid - is there someone I can tag with regards to the documentation? https://docs.hhvm.com/hack/reference/function/HH.Asio.curl_exec/

**Comment by Orvid** [comment]
Well, there's the docs repo that you can file a bug against

**Comment by apeabody** [comment]
Thanks - will do!
