### ISSUE TITLE
Build hhvm failed on fedora 22 as your guide told me

### ISSUE THREAD

**Issue by netroby** [facebook/hhvm#6244]
Linking CXX static library libhphp_runtime.a
[ 99%] Built target hphp_runtime_static
Scanning dependencies of target hhvm
[ 99%] [ 99%] [100%] Building CXX object hphp/hhvm/CMakeFiles/hhvm.dir/main.cpp.o
Building CXX object hphp/hhvm/CMakeFiles/hhvm.dir/global-variables.cpp.o
Building CXX object hphp/hhvm/CMakeFiles/hhvm.dir/process-init.cpp.o
Linking CXX executable hhvm
/usr/bin/ld.gold: error: cannot open /usr/lib64/libatomic.so.1.1.0: No such file or directory
collect2: error: ld returned 1 exit status
hphp/hhvm/CMakeFiles/hhvm.dir/build.make:351: recipe for target 'hphp/hhvm/hhvm' failed
make[2]: *** [hphp/hhvm/hhvm] Error 1
CMakeFiles/Makefile2:2046: recipe for target 'hphp/hhvm/CMakeFiles/hhvm.dir/all' failed
make[1]: *** [hphp/hhvm/CMakeFiles/hhvm.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2

Seems like library. but the guide not mention it

**Comment by netroby** [comment]
libatomic must be installed
```
 sudo dnf install -y libatomic
```

**Comment by netroby** [comment]
At last , i success build hhvm 

```
hhvm --version
HipHop VM 3.10.0-dev (rel)
Compiler: heads/master-0-g58df26f26c9bf8481a268736a82f1452bbd3ba5f
Repo schema: 2935bfea24504471c85374f116b6e8dad783f1ff

```

**Comment by paulbiss** [comment]
The guide may be out of date, building on fedora isn't officially supported. If you've found a fix please update the wiki. Should we close this or are you still having issues?
