### ISSUE TITLE
PHP7 integer division/mod changes

### ISSUE THREAD

**Issue by jwatzman** [facebook/hhvm#6248]
No RFC for this one, but per @nikic:

> - Division by zero should throw DivisionByZeroError (instead of a warning)
- Division of -1 by PHP_INT_MIN should throw ArithmeticError instead of returning false.
- Division by zero with / now results in Inf/-Inf/NaN (and still a warning). Previously it returned false.
- Modulo by zero with % now throws a DivisionByZeroError. Previously it threw a warning and returned false.
- Bitshifts by negative numbers now throw an ArithmeticError. This was a warning+false for a short time, as this check was only introduced in PHP 7 anyway.

Related to:
- [intdiv](https://github.com/facebook/hhvm/issues/6058)
- [Integer semantics changes](https://github.com/facebook/hhvm/issues/6047)
- [Engine exceptions](https://github.com/facebook/hhvm/issues/6012)

**Comment by jwatzman** [comment]
> Bitshifts by negative numbers now throw an ArithmeticError. This was a warning+false for a short time, as this check was only introduced in PHP 7 anyway.

I'm doing this one in https://github.com/facebook/hhvm/issues/6047 since it's new to this behavior anyways.

**Comment by JoelMarcey** [comment]
The other two are still needed, right?

**Comment by jwatzman** [comment]
> The other two are still needed, right?

Yep!

Keep in mind that `DivisionByZeroError` doesn't exist until https://github.com/facebook/hhvm/issues/6012 is done; for integer semantics (which has a similar issue), I think I'm going to use `InvalidOperationException` until then. You also probably want to gate these changes on the option I'm adding in D2482656.

If you get stuck with this, LMK. I'm currently digging into exactly this code as part of the integer semantics changes -- it might actually be easier for me to just do it? Unless you want some fun JIT digging :)

**Comment by JoelMarcey** [comment]
Yep. You seem to be handling all things `integer` now -- I am good assigning to you.

**Comment by jwatzman** [comment]
Sounds good. I also re-read the original thread and see I think I missed a couple of points @nikic mentioned, I just edited the original post at top and added them.

**Comment by jwatzman** [comment]
Diffs are all up internally to do this.

**Comment by jwatzman** [comment]
All that's left here is to throw the right exceptions, which is blocked on #6012.
