### ISSUE TITLE
hhvm won't link with Intel compiler because difference with gcc/icc inlining

### ISSUE THREAD

**Issue by mibintc** [facebook/hhvm#6249]
In compiling hhvm with the Intel compiler, we find that due to a difference in inlining strategy, there's an undefined symbol with the Intel compilation which doesn't occur with gcc compilation.

A small difference in the function declaration will work around the problem.

Suggested modification to file native.h:
Current:
template<bool usesDoubles, bool variadic> 
void callFunc(const Func* func, void* ctx, 
              TypedValue* args, TypedValue& ret); 

Needs to be changed to: 

template<bool usesDoubles, bool variadic> 
__ attribute __((noinline))   /* oops, work around html formatting by adding space */
void callFunc(const Func* func, void* ctx, 
              TypedValue* args, TypedValue& ret); 

Explanation:

Problem Description: 

The callFunc() function is defined in native.cpp but referenced/instantiated in bytecode.cpp. 
A compiler is not obligated to lay down an out of line definition for callFunc() in native.cpp unless the user explicitly instantiates the function or declares it as noinline. 

Other info:
compile with gnu
 nm native.cpp.gcc.o | grep callFunc 
0000000000006e80 T _ZN4HPHP6Native17callFuncInt64ImplEPFPNS_10TypedValueEPNS_6ActRecEEPliPdi 
0000000000000110 T _ZN4HPHP6Native18callFuncDoubleImplEPFPNS_10TypedValueEPNS_6ActRecEEPliPdi 
0000000000000000 W _ZN4HPHP6Native8callFuncILb0ELb0EEEvPKNS_4FuncEPvPNS_10TypedValueERS6_ 
0000000000000000 W _ZN4HPHP6Native8callFuncILb0ELb1EEEvPKNS_4FuncEPvPNS_10TypedValueERS6_ 
0000000000000000 W _ZN4HPHP6Native8callFuncILb1ELb0EEEvPKNS_4FuncEPvPNS_10TypedValueERS6_ 
0000000000000000 W _ZN4HPHP6Native8callFuncILb1ELb1EEEvPKNS_4FuncEPvPNS_10TypedValueERS6_ 

compile with Intel compiler:
 nm native.cpp.icc.o | grep callFunc 
0000000000000070 T _ZN4HPHP6Native17callFuncInt64ImplEPFPNS_10TypedValueEPNS_6ActRecEEPliPdi 
000000000000b4f0 T _ZN4HPHP6Native18callFuncDoubleImplEPFPNS_10TypedValueEPNS_6ActRecEEPliPdi 

Thanks and regards, Melanie Blower (Intel c++ compiler team)

**Comment by JoelMarcey** [comment]
@mibintc Is this something you could submit a pull request for? Thanks.

**Comment by paulbiss** [comment]
Explicitly instantiating the template is probably a better solution than declaring it noinline. We don't officially support icc but since this is really a correctness issue we'd definitely take a PR if it doesn't make too much of a mess.

**Comment by mibintc** [comment]
At Intel I'm not currently enabled to 'submit a pull request' and it would involve jumping through some hoops. Would you be able to make the update?

**Comment by paulbiss** [comment]
I can see about fixing it, but I have no way to test it. In the long term if you want to get us building with icc you're probably best off jumping through those hoops since you'll likely need to make more changes and we won't be able to do all of them.

**Comment by Orvid** [comment]
As long as I don't need to recompile the external dependencies, I can test from windows (via a student license), assuming the ICC installer doesn't get too grumpy about the current state of my system.

**Comment by mibintc** [comment]
Got that, thank you.

**Comment by Orvid** [comment]
This was fixed.
