### ISSUE TITLE
HHVM does not copy a trait's static state to using class

### ISSUE THREAD

**Issue by landaire** [facebook/hhvm#6251]
Pardon the poor title but this is kind of difficult to explain in a quick one-liner. In the process of abusing traits I discovered that in all versions of PHP 5.4.0+ classes will have the static state of a trait copied to them (whatever the state may be when the class is loaded), but will not in HHVM.

For example: in your code if you first define a trait `Foo` which contains a static method to set some static property on the trait. After `Foo` is defined if you call the setter then define a class which has `use Foo;`, the state of `Foo` will be copied to that class. This is the behavior of PHP.

In HHVM, the state of the trait is never copied to the class and in all cases where you refer to `$this->staticProperty` or `$this->staticPropertyGetter()` your result will always be `null`.

[Here is a 3v4l sample of what I mean](https://3v4l.org/X5893). The 3v4l code if that happens to disappear sometime in the new future:

```
<?php

class FirstClassUse
{
    use TestTrait;
    
    public function __construct() {
	    var_dump('=======');
	    var_dump('using $this in first class');
	    var_dump($this->getFoo());
	    var_dump($this->getFoo() === null);
		var_dump('end');
	}
}

TestTrait::setFoo('before trait, before class');

trait TestTrait
{
	private static $foo;
	
	public static function setFoo($foo) {
	    self::$foo = $foo;
	}
	
	public static function getFoo() {
		return static::$foo;
	}
}

TestTrait::setFoo('after trait, before class');

class TestClassUse
{
	use TestTrait;
	
	public function __construct() {
	    var_dump('=======');
	    var_dump('using $this');
	    var_dump($this->getFoo());
	    var_dump($this->getFoo() === 'after trait, before class');
		var_dump('end');
	}
}

class TestClassDirectReference
{
	public function __construct() {
	    var_dump('=======');
	    var_dump('direct reference');
	    var_dump(TestTrait::getFoo() === 'after trait, after class');
		var_dump('end');
	}
}

TestTrait::setFoo('after trait, after class');
$x = new FirstClassUse();
$y = new TestClassUse();
$z =  new TestClassDirectReference();
```

HHVM output for v3.6.1-3.9.0:

```
string(7) "======="
string(26) "using $this in first class"
NULL
bool(true)
string(3) "end"
string(7) "======="
string(11) "using $this"
NULL
bool(false)
string(3) "end"
string(7) "======="
string(16) "direct reference"
bool(true)
string(3) "end"
```

PHP output for 5.4.0-7.0.0.rc2:

```
string(7) "======="
string(26) "using $this in first class"
NULL
bool(true)
string(3) "end"
string(7) "======="
string(11) "using $this"
string(25) "after trait, before class"
bool(true)
string(3) "end"
string(7) "======="
string(16) "direct reference"
bool(true)
string(3) "end"
```

While I'm not certain if this should be considered a bug in PHP or a bug in HHVM I thought I'd report this here for discussion since I'm more familiar with GitHub than I am PHP's issue tracker, and this is could be considered a compatibility issue.

**Comment by paulbiss** [comment]
https://github.com/facebook/hhvm/issues/3826
