### ISSUE TITLE
CLI doesnt work on Debian jessie 8.1 

### ISSUE THREAD

**Issue by kaustavha** [facebook/hhvm#6252]
The command line option -v works, others dont. 
<img width="511" alt="screen shot 2015-09-14 at 1 35 48 pm" src="https://cloud.githubusercontent.com/assets/3248143/9861210/c77d459e-5ae5-11e5-95ce-49b2e66d94f1.png">

**Comment by paulbiss** [comment]
I'm fairly certain there are a bunch of PHP-CLI options that were never implemented. You can see the ones we support here: https://github.com/facebook/hhvm/blob/master/hphp/runtime/base/emulate-zend.cpp#L64

**Comment by kaustavha** [comment]
Hey @paulbiss  Can you help me get #6270 reviewed/merged and fix this [issue](https://github.com/virgo-agent-toolkit/rackspace-monitoring-agent/issues/873)? The newest commit should be good to go. I rebased, unsure how to make phabricator restart a build. 
First time writing cpp and I'm unfamiliar with facebooks vcs/dev practices so let me know if there's any changes you need.

**Comment by paulbiss** [comment]
Hi @kaustavha the PR looks good to me. I was having some issues with our CI infra, I'll kick a new test run.

**Comment by kaustavha** [comment]
Hey @paulbiss  fixed the lint issue that popped up in phabricator, let me know if i need to do anything else.

**Comment by kaustavha** [comment]
There's still incompatibilities with the zend cli but my issue is fixed, pr has been merged and the `--modules` flag has been added to the HHVM cli.
