### ISSUE TITLE
htmlspecialchars doesn't support windows 1251

### ISSUE THREAD

**Issue by fhntv24** [facebook/hhvm#6255]
When using htmlspecialchars with windows-1251 encoding i'm getting "Fatal error: windows-1251 is not implemented yet." error.

Win1251 used by default ( for some reason in my DLE configs ... ) in DLE. Also PHP doesn't give this error.

Using latest stable HHVM for Ubuntu 14.04 LTS

**Comment by karpa13a** [comment]
htmlentities affect this error too(
#943

**Comment by Orvid** [comment]
I'll look into this later today.

**Comment by karpa13a** [comment]
reproduced with current nightly(
```
HipHop VM 3.11.0-dev (rel)
Compiler: heads/master-0-ga2b3a8d03e16047da34410a1516b3b435facae25
Repo schema: 382e5648eab3f07e4132df0e3bd3fcd8e91d9dfb
```

```php
<?
htmlspecialchars( 'text', ENT_QUOTES, 'cp1251');
htmlentities( 'text', ENT_QUOTES, 'cp1251' );
```

```
Fatal error: cp1251 is not implemented yet. in /home/karp/943.php on line 2
```

**Comment by simonwelsh** [comment]
Given that this only landed this morning, it's rather likely that it's not in the nightly.

**Comment by karpa13a** [comment]
@simonwelsh ubuntu 14.04 hhvm-nightly 2015.10.21~trusty with same result
```
HipHop VM 3.11.0-dev (rel)
Compiler: heads/master-0-gaff732a3e827b782c4c25721ae49a6fd7c7473f7
Repo schema: 7f8f0dbca6191f8d1b135e2ff96e6ff1ed20deda
```
heads/master-0-gaff732a3e827b782c4c25721ae49a6fd7c7473f7 mean aff732a3e827b782c4c25721ae49a6fd7c7473f7 as point in repo?
may be build infra have some cached repo?

**Comment by Orvid** [comment]
Hrmm... Well, it looks like when I tested it I tested decoding rather than encoding -_-... Encoding is currently special cased to only support UTF8 and ISO-8859-1, and, although the encoding tables for the other encodings are added in my PR, I failed to actually make the changes to add a slow path for the other encodings.

Basically it looks like I added support for cp1251 to everything except what actually needed it -_-...

**Comment by Orvid** [comment]
If possible, could this and #943 be re-opened, as they aren't actually fixed properly yet?

**Comment by soundslocke** [comment]
We ran into this issue while working with mp3 files using the widely-adopted [`JamesHeinrich/getID3`](https://github.com/JamesHeinrich/getID3) library.

Specifically, it seems [this line](https://github.com/JamesHeinrich/getID3/blob/master/getid3/getid3.lib.php#L1063) calls `htmlentities()` with the `windows-1251` charset argument (or other possible charsets) given mp3 files with tags encoded with that charset. Luckily it's easy to workaround if you avoid using the library to perform the HTML escaping by setting the `option_tags_html` variable to `false`.
