### ISSUE TITLE
Enabling xdebug + remote_enable disables the aggro type checks

### ISSUE THREAD

**Issue by tomzx** [facebook/hhvm#6259]
I have two machines using the exact same build (3.9.1), one that would give me

```
Catchable fatal error: Hack type error: Remove all toplevel statements except for requires at
```

while the other would work just fine.

After debugging for a while, I figured out that having the following in my `/etc/hhvm/php.ini` was causing the difference in behavior.

```
xdebug.enable=1
xdebug.remote_enable=1
```

Is this expected behavior? Should there not be some sort of warning/notice to inform the develop that type checking is disabled?

**Comment by JoelMarcey** [comment]
I wouldn't expect xdebug to force that fatal? So in a simple code snippet like:

```
<?hh // strict

$x = 3;
```

you are getting an **HHVM** error when you have those ini settings enabled?

Can you post the code causing the problem and the ini settings on both machines you are using?

cc: @jwatzman

**Comment by tomzx** [comment]
As the title says, when xdebug is enabled I do not get type checking errors since it appears to be disabled. However, if I remove xdebug, then I get a fatal due to type checking.

**Comment by jwatzman** [comment]
This is pretty weird, I'll take a look when I get a chance. However, you really should be invoking `hh_client` yourself to get better and faster type errors.

**Comment by jwatzman** [comment]
OK, for reasons I don't recall, we don't do the Hack checks if a debugger is attached. I suspect due to its operation, XDebug is considered always attached if it's enabled.

I don't remember why -- I probably just didn't want to deal with the implications. Can revisit this later, but not a big deal IMO.

**Comment by ebluestein** [comment]
Closing this issue, since XDebug is no longer supported.
