### ISSUE TITLE
How to handle per-file constants?

### ISSUE THREAD

**Issue by tslettebo** [facebook/hhvm#6260]
In our systems, we have various configuration settings per file, using constants, like this:
```
<?hh // strict

define("USE_CACHE", true);
...
```

This used not to be a problem, as the typechecker only seemed to check for duplicate definitions when using "const" or single quotes for define() constants.

However, in the latest nightly build of HHVM, it appears that now it also complains about duplicate definition of "USE_CACHE", if the above code is found in more than one file.

There isn't a real duplicate definition, as these are top-level scripts, but I guess the typechecker assumes that any file can be included in any other file, and thus requires all constant names to be unique.

Is there a way to support such script-wide configuration settings? We can't use globals, as they are not supported by Hack.

**Comment by JoelMarcey** [comment]
cc @int3 @dlreeves 

Assuming I understand you correctly, can you put all of your possibly duplicate `define`s in their own file and then `require` that file in your code?

**Comment by tslettebo** [comment]
Hi @JoelMarcey.

Yeah, I could do that, but as these are configuration directives, that would mean a separate file for each one, and the I/O overhead of an include just to define a constant, but it would work that way.

**Comment by fredemmott** [comment]
This is not supported by Hack - Hack assumes globally unique identifiers, and I don't see us changing this.

One solution would be to refactor these to a configuration object which your scripts construct and pass in.

**Comment by tslettebo** [comment]
Thanks for your reply.
