### ISSUE TITLE
Http Headers set within SoapClient are not interpreted

### ISSUE THREAD

**Issue by tudor2004** [facebook/hhvm#6263]
It seems that http headers set into the stream_context value of the SoapClient $options are not interpreted and send to the remote server. Below are two examples that can be used as test: 
```php
<?php
/** Use this as client **/
$options = array(
    'location' => 'http://testing.dev/soap_server.php',
    'uri' => 'http://testing.dev'
);

$httpHeader = 'MY-HEADER: TEST';

$options['stream_context'] = stream_context_create(array('http' => array('header' => $httpHeader)));

$client = new SoapClient(NULL, $options);

try
{
	echo $client->__soapCall('hello', array());
}
catch(Exception $e)
{
	echo $e->getMessage();
}
```

```php
<?php
/** Use this as server **/

class MyAPI
{
	function hello()
	{
		return var_export(getallheaders(), true);
	}
}

$options=array('uri'=>'http://testing.dev');

$server = new SoapServer(NULL,$options);
$server->setClass('MyAPI');
$server->handle();
```

Using `sudo tcpdump -A -n -s 2024  dst port 80` listen to all outgoing requests. Under PHP the headers all visible and sent, under hhvm the headers are not sent. Currently testing under HHVM 3.9.1

**Comment by plentytp** [comment]
I have the same issue, any solutions ?

Best Regards

**Comment by sergejM** [comment]
have the same problem, is this a bug oder setting issue?

HipHop VM 3.9.1 (rel)

Best Regards

**Comment by corientdev** [comment]
Can anybody hint about how can we get it solved? which file to edit? i am intersted to contribute..

**Comment by SiebelsTim** [comment]
You can find the SoapClient [here](https://github.com/facebook/hhvm/blob/4a3be43df46ea29b5d7860aaa524bd3ee8aaf4c8/hphp/runtime/ext/soap/ext_soap.cpp#L2422) (linked to ctor) which uses the context options down [here](https://github.com/facebook/hhvm/blob/4a3be43df46ea29b5d7860aaa524bd3ee8aaf4c8/hphp/runtime/ext/soap/ext_soap.cpp#L2523) to a [HttpClient](https://github.com/facebook/hhvm/blob/4a3be43df46ea29b5d7860aaa524bd3ee8aaf4c8/hphp/runtime/base/http-client.cpp)

**Comment by tudor2004** [comment]
Any news on fixing this issue? I'm pretty sure this would help a lot of people.

**Comment by aszekely** [comment]
@SiebelsTim i would like to talk to you in private regarding your comment. How can i reach you ?

**Comment by SiebelsTim** [comment]
IRC: #hhvm @freenode. My nick is Sbls

**Comment by SiebelsTim** [comment]
I think this is an issue with the `HttpClient`. The HttpClient is used with context options only is soap (and UrlFile). 
The only place the `stream_context` is used is here https://github.com/facebook/hhvm/blob/4a3be43df46ea29b5d7860aaa524bd3ee8aaf4c8/hphp/runtime/base/http-client.cpp#L215 with no regard to the `headers` field. 
The `stream_context` array definitly is set properly, but I think the httpclient doesn't do much with it (except for ssl).

**Comment by SiebelsTim** [comment]
Yep, it's that. 
Here is WIP fix I will probably **not continue**. It needs a test, code cleanup (maybe something more sensible than just casting to array and fetching the headers field) and checks that it didn't break anything else (I think this will break something about the `responseHeaders` handling a few lines above).
https://gist.github.com/SiebelsTim/0094a2f179c2aaf105a0

**Comment by aszekely** [comment]
@SiebelsTim Hey Tim! great news and if i'm allowed to say: good job! Let's talk tomorrow. I will be on the channel.
