### ISSUE TITLE
Assigning large number of unique variables slow on CLI with Jit.Eval=true

### ISSUE THREAD

**Issue by aewing** [facebook/hhvm#6265]
Assigning a large number of variables in a Hack script executed with HHVM on CLI without Eval.Jit=false is rather slow. 

The following snippet runs nigh-instantly via web or with -v Eval.Jit=false, but via CLI without any extra arguments it clocks between 1.9 and 2.15 seconds for me.

https://gist.github.com/aewing/62b6f56ab7ddff68f086

**Comment by JoelMarcey** [comment]
TL;DR: Thanks. Known issue with certain code fragments.

@aewing Yeah, there has been some issues with certain code segments and fragments with the JIT lately. This looks to be one of them. I have added this example to an already created internal task about this. Thanks!

**Comment by JoelMarcey** [comment]
@aewing Can you try wrapping your code in a function to see if that changes the performance for the better?

**Comment by aewing** [comment]
@JoelMarcey I apologize for the delay. Wrapping the code in a function does cut the execution time nearly in half on nightlies.

**Comment by aewing** [comment]
That being said, the execution time has increased from 1.9-2.15 seconds to 3.3-3.5 seconds on nightlies. The execution time when wrapped in a function is between 1.75 and 1.8 seconds.

**Comment by Orvid** [comment]
This appears to be fixed on current versions of HHVM: https://3v4l.org/KHJAU
