### ISSUE TITLE
Using superglobals in strict mode should have better error message

### ISSUE THREAD

**Issue by BobertForever** [facebook/hhvm#6266]
The following code:
```hack
<?hh // strict
public static function post(): void {
  if ($_FILES['resume']['name'] === "") {
    http_response_code(400);
    return;
  }

  // Make sure the resume is a PDF
  $file_type =
    pathinfo(basename($_FILES["resume"]["name"]), PATHINFO_EXTENSION);
  if ($file_type != "pdf") {
    http_response_code(400);
    return;
  }

  $upload_dir = "uploads/resume/";
  
  // Create the upload directory for the user
  if (!file_exists($upload_dir)) {
    mkdir($upload_dir);
  }

  // Move the file to its final home
  if (!move_uploaded_file(
        $_FILES['resume']['tmp_name'],
        $upload_dir."/resume.pdf",
  )) {
    http_response_code(500);
    return;
  }
}
```
Produces this error by the typechecker:
```
Undefined variable: $_FILES (Naming[2050])
Undefined variable: $_FILES (Naming[2050])
Undefined variable: $_FILES (Naming[2050])
```
For all three occurrences of `$_FILES`. I couldn't find anywhere in the documentation about an alternative to `$_FILES` or that it was not allowed in strict mode.

**Comment by aetherson** [comment]
:cool:

**Comment by simonwelsh** [comment]
Hack does not allow any of the superglobals in strict mode. The [cookbook](http://cookbook.hacklang.org/recipes/get-and-post/) has a simple way of accessing these values in strict mode.

**Comment by BobertForever** [comment]
Ah, makes sense. I guess then my issue should be something more along the lines of "superglobals not being available in strict mode is not documented on strict documentation page (here: http://docs.hhvm.com/manual/en/hack.modes.strict.php)"

Or maybe the typechecker could say something like "superglobals are not allowed in strict mode" to reduce confusion.

**Comment by JoelMarcey** [comment]
@BobertForever we are rewriting the docs to be hopefully vastly improved. You can see a current preview of what we have written about superglobals here...

https://github.com/hhvm/user-documentation/blob/master/guides/hack/01-types/08-advanced-rules.md

**Comment by aetherson** [comment]
Any particular reason the error strings couldn't reflect this behavior?

**Comment by JoelMarcey** [comment]
@aetherson I think the way it is implemented is that in strict mode they are treated just as any other undefined variable might be treated. e.g.,

```
<?hh
function foo(): void {
  echo $x; // Undefined variable: $x (Naming[2050])
}
```

They just didn't special case the superglobals to provide a specific message.

I don't think there is any technical reason that can't be done; but I will cc a couple of folks who might be able to tell you better..

cc: @jwatzman @int3

**Comment by Orvid** [comment]
We're a small team, and it doesn't look as though anyone in the community is actively working on this issue, so we've decided to close it. If you plan to send us a pull request resolving the issue let us know in the comments and we will re-open it and assign it to you. If you feel this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
