### ISSUE TITLE
Hack with PHP

### ISSUE THREAD

**Issue by trivedipankaj** [facebook/hhvm#6267]
Hi,

We are running our php code on HHVM (3.9) now and we are pretty happy with the performance boost it has brought in with it. We are now trying to migrate some of our code base to Hack, specially to take the advantage of async feature. I just wanted to know a way to run both PHP and Hack together in a single code base, for example: How can I call a hack function in PHP code or vice versa?

**Comment by simonwelsh** [comment]
So long as your Hack code isn't in a strict file, it can call into PHP code just fine. Calling from PHP into Hack always works, though you do need to make sure the types of the values you're passing in are correct.

Nothing special has to be done to be able to use both.

**Comment by trivedipankaj** [comment]
Thanks Simon, I must be doing something really silly before, it is working now!
