### ISSUE TITLE
intermittent failure to retrieve sessions from Redis

### ISSUE THREAD

**Issue by r3wt** [facebook/hhvm#6271]
Every so many requests HHVM fails to connect to redis OR prematurely dropping sessions. cant tell, but there are no error logs available, so its impossible to get to the root of the issue

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Hhvm has dropped support for the redis extension in version [4.56.0](https://hhvm.com/blog/2020/05/04/hhvm-4.56.html).
