### ISSUE TITLE
Writing files asynchronously

### ISSUE THREAD

**Issue by trivedipankaj** [facebook/hhvm#6276]
Hi,

We have been using HHVM on our platform and we are pretty happy with the performance boost. We are now introducing Mysql, Curl async features in hack. I was just wondering if it was possible to write files asynchronously, I have come across stream_await async function but it is async only till the stream becomes available and writing files will still be synchronous. Is it possible to write files asynchronously? Please provide me a few examples! 

Thanks

**Comment by steelbrain** [comment]
Here's what I am using to write and read from async unix and tcp sockets. I believe LibUV has some fs functions as well. https://github.com/RickySu/hhvm-ext-uv

**Comment by trivedipankaj** [comment]
I believe we can't actually write files asynchronously, as hhvm is still single threaded and we can only utilize blocking IO to do things in parallel.

**Comment by steelbrain** [comment]
@trivedipankaj Yep! You got it right!

**Comment by fredemmott** [comment]
We could implement async file writes (eg async curl is a blocking API that we transparently run in another thread), but it doesn't seem worthwhile: async does have overhead, and for local file writes, it is likely that for most usage, the blocking write would actually be faster than engaging async.

**Comment by trivedipankaj** [comment]
makes sense! thanks
