### ISSUE TITLE
Centos6 64 bit hhvm compile error

### ISSUE THREAD

**Issue by dipenpatel235** [facebook/hhvm#6278]
i clone repos from  git clone https://github.com/facebook/hhvm -b master  hhvm  --recursive
then configure successfully
then below error in make command

[ 36%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/embedded-vfs.cpp.o
/tmp/hhvm/hphp/util/embedded-vfs.cpp: In function ‘int HPHP::embeddedCurrentTimeInt64(sqlite3_vfs*, sqlite3_int64*)’:
/tmp/hhvm/hphp/util/embedded-vfs.cpp:145:30: error: ‘sqlite3_vfs’ has no member named ‘xCurrentTimeInt64’
   return gEmbedded.pOrigVfs->xCurrentTimeInt64(gEmbedded.pOrigVfs, b);
                              ^
/tmp/hhvm/hphp/util/embedded-vfs.cpp: In function ‘int HPHP::sqlite3_embedded_initialize(const char*, int)’:
/tmp/hhvm/hphp/util/embedded-vfs.cpp:244:22: error: ‘sqlite3_vfs’ has no member named ‘xCurrentTimeInt64’
   gEmbedded.sThisVfs.xCurrentTimeInt64 = embeddedCurrentTimeInt64;
                      ^
make[2]: *** [hphp/util/CMakeFiles/hphp_util.dir/embedded-vfs.cpp.o] Error 1
make[1]: *** [hphp/util/CMakeFiles/hphp_util.dir/all] Error 2

**Comment by jazzdan** [comment]
I think you need to upgrade your version of SQLite. Take a look at [these instructions on the wiki](https://github.com/facebook/hhvm/wiki/Building-and-installing-HHVM-on-CentOS-6.6#9-install-sqlite).

Compiling HHVM on Cent 6 is tough, but doable. If at all possible, I would recommend upgrading to Cent 7.

**Comment by paulbiss** [comment]
Since CentOS 6 (and 7) aren't officially supported your best bet is probably to ask around in #hhvm on Freenode as most of us don't have experience building on either of those systems.
