### ISSUE TITLE
Hack: Attributes on class properties?

### ISSUE THREAD

**Issue by girvo** [facebook/hhvm#6280]
Hey all,

Attributes are an amazing feature of Hack, but one of the things I can't work out for the life of me is how to apply them to class properties. Class methods and the class itself work wonderfully, but I'd love to be able to use attributes to define metaprogramming data for a particular class; effectively, replacing the comment based annotations that we rely on in PHP with real annotations in Hack.

``` php
<?hh

class TestModel
{
    <<AssertNotNull([ 'message' => 'You must provide an ID' ])>>
    private int $id;

    // ...
}
```

Is this something that will be looked at in the future or is it not really on the roadmap?

Cheers,
Josh

**Comment by sgolemon** [comment]
> "one of the things I can't work out for the life of me is how to apply them to class properties"

Because they're not supported at this time.  Not because we wouldn't like 'em, but just because nobody's done the work to pipe them all the way through the runtime.  PRs welcome, otherwise I'm sure someone will get to it eventually.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Newer versions of hhvm support placing attributes on instance properties. The validation for attributes has changed. You need to create a class that implements the `\HH\InstancePropertyAttribute` interface (which requires no methods). This change is documented in the [3.29.0](https://hhvm.com/blog/2018/10/22/hhvm-3.29.html) release notes.
