### ISSUE TITLE
AsyncMysqlConnection::queryf and array/vector/Map

### ISSUE THREAD

**Issue by aewing** [facebook/hhvm#6282]
Per discussion with @Orvid I'm making a feature request to have AsyncMysqlConnection::queryf support an array or vector of parameters as a second argument. Currently with the variable argument support you must pass each parameter separately, which is inconvenient in situations where the data resides and has been prepared in a traversable.

**Comment by Orvid** [comment]
And, as pointed out by @simonwelsh a bit later, a [splat](http://php.net/manual/en/migration56.new-features.php#migration56.new-features.splat) (I didn't know that's what it was called either) can be used to achieve this same effect if `$args` is an array:
```PHP
$con->queryf($format, ...$args);
```
