### ISSUE TITLE
Bug - Hash tiger is based on x64 undefined behavior

### ISSUE THREAD

**Issue by lbianc** [facebook/hhvm#6284]
In the file ```hhvm/hphp/runtime/ext/hash/hash_tiger.cpp``` there is the method ```hash_final```, as shown below:

```cpp
void hash_tiger::hash_final(unsigned char *digest, void *context_) {
  PHP_TIGER_CTX *context = (PHP_TIGER_CTX*)context_;

  TigerFinalize(context);

  for(int i = 0; i < (m_digest >> 3); ++i) {
    digest[i] = (unsigned char) ((context->state[i >> 3] >>
                                    ((m_invert ? (7 - i) : i) << 3))
                                    & 0xff);
  }

  memset(context, 0, sizeof(*context));
}
```

When shifting the number by ```((m_invert ? (7 - i) : i) << 3))```, which can be 64 or greater depending of ```m_digest```, the behavior is undefined, as described in [1]. Based on that, I would propose `mod` this value by 64, which is the current behavior for ```x64``` and will be the same for other platforms (e.g: GCC on PPC64 behaves differently).

Any comment/suggestion for this solution?

Reference:
[1] The New C Standard, page 1185 - http://www.coding-guidelines.com/cbook/cbook1_1.pdf

**Comment by jwatzman** [comment]
The issue you're pointing out, as well as the gist of the solution, makes sense to me. I'm not sure I follow exactly what you're proposing (also it's late and I'm tired so might just be me) but the solution is probably best discussed in a PR, if you wouldn't mind to send one with your proposed fix, which is pretty simple right?
