### ISSUE TITLE
Redis BLPOP ignores timeout

### ISSUE THREAD

**Issue by AlexTodessa** [facebook/hhvm#6286]
Hello.
Using hhvm to speed up some processes, which use redis and blpop to get new tasks. The problem is, that if queue is ended (list gets deleted, or no records in it), with php (5.5.9) scripts just end their work, which is normal.
With hhvm they wait to get something from redis, and execution is actually blocked.

Steps to reproduce are simple:

$redis->blPop('anykey', 1);

if there is nothing to get from the list, or list doesn't even exist - with php it gets unblocked in 1 second, with hhvm - it doesn't, so stuck there forever, unless something will appear in that list.

Running using hhvm cli.
System: Ubuntu 14.04.3 LTS
PHP: 5.5.9-1ubuntu4.11 (cli) (built: Jul  2 2015 15:23:08) 
HipHop VM 3.9.1 (rel)

Thanks.

**Comment by Orvid** [comment]
We're a small team, and it doesn't look as though anyone in the community is actively working on this issue, so we've decided to close it. If you plan to send us a pull request resolving the issue let us know in the comments and we will re-open it and assign it to you. If you feel this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
