### ISSUE TITLE
Message: ps_files_cleanup_dir: opendir(/var/lib/hhvm/sessions) failed: Permission denied (13)

### ISSUE THREAD

**Issue by jelqui** [facebook/hhvm#6302]
HHVM  on GNU/LINUX Debían 8
Version: HipHop VM 3.9.1 (rel)
Compiler: tags/HHVM-3.9.1-0-g0f72cfc2f0a01fdfeb72fbcfeb247b72998a66db
Repo schema: 6416960c150a4a4726fda74b659105ded8819d9ccc

I have Codeigniter 2 running with hhvm and I got this issue
Hope this report help others.

**Comment by steelbrain** [comment]
Happens when I run hhvm as a non `www-data` user or when the `/var/lib/hhvm/sessions` isn't owned by `www-data`.

**Comment by Orvid** [comment]
We're a small team, and it doesn't look as though anyone in the community is actively working on this issue, so we've decided to close it. If you plan to send us a pull request resolving the issue let us know in the comments and we will re-open it and assign it to you. If you feel this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
