### ISSUE TITLE
GMP not included in ubuntu build

### ISSUE THREAD

**Issue by kryogenic** [facebook/hhvm#6306]
The package at http://dl.hhvm.com/ubuntu does not include GMP. Would be nice to have it.

**Comment by SiebelsTim** [comment]
@jwatzman Looks like this is intentional? https://github.com/hhvm/packaging/commit/d86d8036abac71997789d0a0d8753513826a3086

**Comment by kryogenic** [comment]
That is rather unfortunate

**Comment by SiebelsTim** [comment]
@kryogenic I'm curious about the reason though, maybe enabling this revealed some problems.

Usually the hhvm team is happy to enable any extension needed.

**Comment by simonwelsh** [comment]
Duplicate of hhvm/packaging#133

**Comment by jwatzman** [comment]
Closing in favor of hhvm/packaging#133
