### ISSUE TITLE
How to type-check partial objects loaded from the database

### ISSUE THREAD

**Issue by tslettebo** [facebook/hhvm#6313]
Hi.

This isn't an issue with HHVM/Hack, but I'd like to ask if anyone has any suggestions about how to handle the following:

I guess like many, we have an OO-relational mapping layer in our system that loads a record from the database and uses it to populate an object.

Conceptually, it works like this:
```
<?hh // strict

class User
{
  public function __construct(...) { ... } // May also use constructor argument promotion

  public int $id;
  public string $name;
  public string $address;
  ...
}

function get_user_list(string $fields): array<User>
{
  ...
}
```

Many tables have a large number of fields, and in many cases, you only need a few of them. For example, the "user" table may have 30 or so fields, but in order to display a list of users, all you may need to retrieve is the "id" and "name" fields.

Here's the issue: In the database, many fields are mandatory, so it makes sense that they are mandatory (non-null) in the corresponding User class, as well. However, when reading a partial User record (like "id" and "name") this means that those mandatory fields are not set in the object (such as "address" in this case), and the typechecker will complain.

One solution is to always make complete objects, which can be wasteful on resources, especially for long arrays of objects. Another might be to make all fields nullable in the class, but then you need to check for null everywhere you access them, again, to prevent the typechecker from complaining.

Yet another possibility might be to make partial classes, like a "User" class with only a few fields, but this could lead to a proliferation of classes in the system, one per query, which all have to be updated if the user table is updated.

Does anyone have a suggestion for how to solve this issue?

Currently, we're using code like "$name = not_null($user->name)" all over the place, but this rather messy, and having to dynamically check for non-null rather defeats the purpose of the typechecker in the first place.

**Comment by fredemmott** [comment]
We usually use something similar to not_null - https://github.com/facebook/hhvm/blob/3451e7d079c2f90e5c566fddb2f3257ac788cb4b/hphp/test/slow/inlining/nullthrows1.php#L3-L13 is pretty much it.

I disagree on having to dynamically check for non-null defeating the purpose; saying that a maybe-initialized value is non-nullable is not correct and unsafe, and the same applies to treating nullable fields as non-nullable. In both cases the typechecker is complaining because what you are doing is either unsafe (eg if you change which fields are always available), or the type data you've provided is not accurate.

An alternative would be:
 - make the fields private and nullable (eg `private ?string $address')
 - provide accessor methods that automatically do not_null()/nullthrows, eg:

```Hack
public function getAddress(): string {
  return not_null($this->address);
}
```

This would also let you transparently implement lazy loading in the future if you decided that was better.

I'd still recommend not_null/nullthrows over this, because then you can easily change what fields are always available and get typechecker errors instead of runtime exceptions if you miss a spot that now needs to explicitly fetch more data.

**Comment by tslettebo** [comment]
Hi @fredemmott.

You're right, "defeats the purpose" wasn't the right expression.

What I meant to say is that we try to get as much leverage as we can out of the typechecker, which means trying to detect any issues as early as possible (i.e. statically).

You're right that detecting any issues at run-time is equally "safe", in that the issues are still detected, but much of the advantage of Hack and the typechecker is to be able to detect any issues statically.

Thanks for your suggestions. It's very helpful to hear how other people handles these kinds of things.

Having thought a lot about this the last few days, it occurs to me that we may handle this as follows:

1) For the "domain objects", where we typically only read a small part of them from the database, it may make sense to leave them with nullable fields, and use not_null/nullthrows for accessing them.

I realise that even though the null/not-null test is moved to run-time, the test for correct type is still done at compile-time, so it's not like we get no help from the typechecker at all in this case.

2) We have some queries where we join a bunch of tables, and produce a result involving fields from several tables (sometimes with aliased filed names), and until recently, we used stdClass for that, until the typechecker was changed to complain on that in strict mode, which I agree is a good thing, by the way. :)

Thus, there are a couple of approaches to this:

1. Making some kind of TypedObject class which can hold any fields (like stdClass), and provide type-safe access to them, like this:

$result = some_query();

$user_id = $result->int("user_id"); // This one uses an invariant() to check for int for $result->user_id

2. Alternatively, making a class just for this result set, which may then contain non-null members, since in this case, we know what we expect to return, so we may avoid the null checks.

----

Our next task is to determine where to put the boundary between "typed" and "untyped" arrays in our system... :)

After all, MySQLi returns an "untyped" result (only strings) and at some point, that data, and data passing back to the database, need to be converted to typed data for the rest of the system.

Do you have any suggestions from your own experience on this?

Like, today, we have functions like:

$result_array = db_fetch_recordset($sql); // Returns an array<array<string,string>> from the MySQLi API

Further up the stack, this is converted to objects, but I'm wondering if we should treat it sooner as typed data.

The reason I've been thinking about this is that we're recently moved to handling the superglobals in a way similar to this (https://github.com/hhvm/hack-example-site/tree/master/recipes/get-and-post), implementing a TypedArray class which gets instantiated with a superglobal, and which has member functions for retrieving elements given a certain type, like this (we haven't moved to Hack in production, yet, so we're still using arrays, rather than the collection classes, to keep backwards compatibility with PHP):

```
// Non-strict file

function get(): TypedArray
{
  return new TypedArray($_GET);
}

// Strict files

$user_id = get()->int("user_id"); // Checks that the item exists and is convertible to int

or:

$get = get();

$user_id = $get->int("user_id");
```

However, I'm not sure how useful this approach would be for "untyped" data being passed between the system and the database.

**Comment by fredemmott** [comment]
shapes could work for you:

```Hack

type BasicUser = shape(
  'id' => int,
  'name' => string,
);

type UserWithAddress = shape(
  'id' => int,
  'name' => string,
  'address' => string,
);

// In  HHVM  and Hack 3.9+, UserWithAddress is considered a subtype of BasicUser because it contains all the same fields.

$fred = shape(
  'id' => 509801880,
  'name' => 'Fred',
);
// $fred can be passed to something expecting a BasicUser, and to untyped PHP expected an array. For Hack code expecting an array<string, mixed> use Shapes::toArray()
```

At runtime, they're just arrays giving you the compatibility you need, but the typechecker

**Comment by fredemmott** [comment]
This also works for nullability changes:

```Hack
<?hh // strict

type Herp = shape(
  'foo' => ?string,
);

type Derp = shape(
  'foo' => string,
);

function derpToHerp(Derp $v): Herp {
  return $v; /// Any valid Derp is also a valid Herp
}
```

**Comment by tslettebo** [comment]
Thanks @fredemmott for the information on shapes, in particular the subtype relationships, I'll check it out.
