### ISSUE TITLE
compress.bzip2 not implemented in bz2 extension

### ISSUE THREAD

**Issue by apergos** [facebook/hhvm#6314]
joe@gizmo:~$ hhvm --version
HipHop VM 3.9.1 (rel)
Compiler: tags/HHVM-3.9.1-0-g0f72cfc2f0a01fdfeb72fbcfeb247b72998a66db
Repo schema: 6416960c150a4a4726fda74b659105ded8819d9c
joe@gizmo:~$ hhvm test.php
Array
(
    [0] => compress.zlib
    [1] => data
    [2] => file
    [3] => glob
    [4] => http
    [5] => https
    [6] => phar
    [7] => php
    [8] => zip
)

I'd expect to see compress.bzip2 in that list according to the docs. And yet...
 
Consequently, when trying to run any php code relying on that streamwrapper I get the error message 
"Warning: unknown URI scheme "compress.bzip2" in blahblah.

**Comment by sgolemon** [comment]
bz2 actually *is* built and included with the prebuilt package:

`var_dump(extension_loaded("bz2"));` => `bool(true)`

The trouble is, our version of bz2 doesn't implement the `compress.bzip2` stream wrapper.  Which makes this a parity issue more than a feature request.

**Comment by sgolemon** [comment]
Diff up for review internally: D2486378
