### ISSUE TITLE
sources still checked in repo.authoritative mode

### ISSUE THREAD

**Issue by marcokh** [facebook/hhvm#6315]
Hello,

I'm using the provided script from the package to enable repo authoritative as mentioned here (easy way) https://github.com/facebook/hhvm/wiki/Performance-Tuning#use-repoauthoritative---20

This appears to be working fine, I can edit source files and my changes to the php have absolutely no effect on the code execution, which seem to indicate that hhvm is loading things from the cache as expected. 

However, if I remove the source file from the fs, I'm suddenly getting a 404 error. After checking, I can see in apache's access.log that the error is actually sent by apache before the request is forwarded to hhvm (nothing appears in hhvm logs).

I understand that the repo mode is actually working but, back to the page linked above, below the "manual way" title it states that "the recommended way to use RepoAuthoritative mode is to develop with it disabled, and then to build and deploy a repo, not source code, to production machines." which is exactly the scenario I'm trying to follow. 

Could someone with more experience let me know if I overlooked something or if the link above is simply outdated ?

Also, as described in the manual way, I managed to create an hhbc file using the following commands 

cd sourcedir
sudo find -name '*.php' -type f -print0 | xargs -0 hhvm --hphp -thhbc -o ~/testhhvm 

surprisingly this generate a much smaller hhbc file than the automated script (5mo instead of 25). 

Does someone know the reason and possible consequences behind the change of size ? More generally, does anyone knows what are the differences between the command used in the automated script and the manual command above ?

Any help would be greatly appreciated

**Comment by fredemmott** [comment]
You need to reconfigure Apache - instead of telling it to use HHVM to render PHP files, you need to tell it to either:

 - Use HHVM to render an entire subtree - eg /mysite, not just PHP files
 - Proxy any URL ending with '.php' to HHVM

ProxyPass and ProxyPassMatch + mod_proxy_fcgi could be workable approach - eg the PHP-FPM example at http://httpd.apache.org/docs/trunk/mod/mod_proxy_fcgi.html should work

**Comment by fredemmott** [comment]
The size difference is because we include non-PHP files - this makes things like `file_get_contents(__DIR__.'/foo.txt');` work

**Comment by marcokh** [comment]
Thank you for your answers Fred,

I think you are right, here is the relevant line in my apache conf

ProxyPassMatch ^(?!\/phpmyadmin\/)(.+\.(hh|php)(/.*)?)$ fcgi://127.0.0.1:9000/var/www/poscontrol/$1

I'm pretty bad at understanding regexp but I think the above is refering to all ".php or .hh files"

Following your advice, I have tried to change it to a more generic pattern :

 ProxyPassMatch ^(?!\/phpmyadmin\/)(.+\.(/.*)?)$ fcgi://127.0.0.1:9000/var/www/poscontrol/$1

However, this is getting exactly the same results. I have looked at the doc page you linked in your answer but couldn't figure out how I should configure apache

Could you please let me know if you can see what is wrong in my config attempts ?

**Comment by marcokh** [comment]
Fred, I gave it a second look and realized I had misread your message and didn't look precisely at the PHP-FPM example so I tried again, this time without the $1 at the end and with the additional parameter :

ProxyPassMatch "^/.*\.php(/.*)?$" "fcgi://localhost:9000/var/www/poscontrol/" enablereuse=on

This resulted in apache2 being unable to restart :
Sep 30 16:12:22 marco-newlap apache2[16864]: AH00526: Syntax error on line 42 of /etc/apache2/sites-enabled/poscontrol.conf:
Sep 30 16:12:22 marco-newlap apache2[16864]: ProxyPass unknown Worker parameter

I tried again without the enablereuse=on but apache is still getting called and return a 404 error if the src file is missing.

**Comment by marcokh** [comment]
In case someone ever find this, I have now tried other matching options, as documented below but all of them share the same behavior and seem to request the php file to be present on the file system before forwarding the request to fastcgi

https://github.com/facebook/hhvm/wiki/FastCGI
