### ISSUE TITLE
Reclassify E_STRICT warnings

### ISSUE THREAD

**Issue by jwatzman** [facebook/hhvm#6318]
https://wiki.php.net/rfc/reclassify_e_strict

I don't think this is terribly hard, just a bunch of bookkeeping? Might be worth doing in tandem with [engine exceptions](https://github.com/facebook/hhvm/issues/6012), or at least covered by the same option?

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

I have had a look at the link to the rfc. Everything listed there is either invalid Hack these days or "fine just fine". If there are any specific strict warnings I have overlooked, let me know or better yet, open a new issue.
