### ISSUE TITLE
Frameworks page is empty

### ISSUE THREAD

**Issue by paulocoghi** [facebook/hhvm#6323]
The current HHVM page about frameworks compatibility is empty, although the [JSON file](http://graph.facebook.com/hhvm_oss_tests) is available and not empty.

![hhvm-empty-frameworks](https://cloud.githubusercontent.com/assets/378397/10248490/33678a44-68f6-11e5-8a24-306686a6dba8.png)

**Comment by SiebelsTim** [comment]
duplicate #6290

bump @fredemmott
