### ISSUE TITLE
Mac OS X 10.11 build error

### ISSUE THREAD

**Issue by baozigit** [facebook/hhvm#6324]
[ 28%] Linking CXX static library libwangle.a
cd /usr/local/Cellar/hhvm/3.9.1/src/third-party/wangle && /usr/local/Cellar/cmake/3.3.2/bin/cmake -P CMakeFiles/wangle.dir/cmake_clean_target.cmake
cd /usr/local/Cellar/hhvm/3.9.1/src/third-party/wangle && /usr/local/Cellar/cmake/3.3.2/bin/cmake -E cmake_link_script CMakeFiles/wangle.dir/link.txt --verbose=1
/usr/bin/ar cq libwangle.a  CMakeFiles/wangle.dir/src/wangle/acceptor/Acceptor.cpp.o CMakeFiles/wangle.dir/src/wangle/acceptor/ConnectionManager.cpp.o CMakeFiles/wangle.dir/src/wangle/acceptor/LoadShedConfiguration.cpp.o CMakeFiles/wangle.dir/src/wangle/acceptor/ManagedConnection.cpp.o CMakeFiles/wangle.dir/src/wangle/acceptor/SocketOptions.cpp.o CMakeFiles/wangle.dir/src/wangle/acceptor/TransportInfo.cpp.o CMakeFiles/wangle.dir/src/wangle/channel/Pipeline.cpp.o CMakeFiles/wangle.dir/src/wangle/codec/ByteToMessageCodec.cpp.o CMakeFiles/wangle.dir/src/wangle/codec/LengthFieldBasedFrameDecoder.cpp.o CMakeFiles/wangle.dir/src/wangle/codec/LengthFieldPrepender.cpp.o CMakeFiles/wangle.dir/src/wangle/codec/LineBasedFrameDecoder.cpp.o CMakeFiles/wangle.dir/src/wangle/concurrent/Codel.cpp.o CMakeFiles/wangle.dir/src/wangle/concurrent/CPUThreadPoolExecutor.cpp.o CMakeFiles/wangle.dir/src/wangle/concurrent/GlobalExecutor.cpp.o CMakeFiles/wangle.dir/src/wangle/concurrent/IOThreadPoolExecutor.cpp.o CMakeFiles/wangle.dir/src/wangle/concurrent/ThreadPoolExecutor.cpp.o CMakeFiles/wangle.dir/src/wangle/deprecated/rx/Dummy.cpp.o CMakeFiles/wangle.dir/src/wangle/ssl/PasswordInFile.cpp.o CMakeFiles/wangle.dir/src/wangle/ssl/SSLContextManager.cpp.o CMakeFiles/wangle.dir/src/wangle/ssl/SSLSessionCacheManager.cpp.o CMakeFiles/wangle.dir/src/wangle/ssl/SSLUtil.cpp.o CMakeFiles/wangle.dir/src/wangle/ssl/TLSTicketKeyManager.cpp.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libwangle.a(Dummy.cpp.o) has no symbols
/usr/bin/ranlib libwangle.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libwangle.a(Dummy.cpp.o) has no symbols
[ 28%] Built target wangle
make: *** [all] Error 2

**Comment by baozigit** [comment]
OSX 10.11

**Comment by jwatzman** [comment]
What you've provided doesn't actually include the relavent info. Could you provide the output of `brew gist-log hhvm`, or if you can't do that for some reason, the *full* output from `brew install --verbose hhvm`?

**Comment by Orvid** [comment]
Closing, still needs more info (https://github.com/facebook/hhvm/wiki/Human-Timeouts) - will reopen if provided.

**Comment by threkk** [comment]
Hello,
I have the same error. My `gist-log` tool is not working but I uploaded all the logs in here https://gist.github.com/threkk/4aad7009e22dc60ba94675e19f293603

**Comment by jwatzman** [comment]
@threkk what version of jemalloc do you have installed, and if it's not version 4 can you upgrade it? (Brew should have version 4.) I *think* but haven't confirmed we accidentally started requiring jemalloc 4 at some point.

**Comment by threkk** [comment]
I have the version 4.0.0. Do I need to downgrade?

**Comment by jwatzman** [comment]
No, I thought 4.0.0 would work :( I guess it's a different problem. Can you file a new issue please, it's easier to track than something stuffed at the bottom of a closed one :)

**Comment by threkk** [comment]
I just created it, let me know if you need more information.
