### ISSUE TITLE
how to use fsockopen from ext/sockets/ext_sockets.cpp instead the one from ext/std/ext_std_network.cpp 

### ISSUE THREAD

**Issue by JesseXie** [facebook/hhvm#6333]
Hi There
  We have a thrift service. We are using TSocket which uses fsockopen. And we found out fsockopen is very slow(around 35ms).
  We use python client to make sure there is nothing wrong on the server side, which is less then 1ms.
  
  I looked around and found several threads complained about it.
  In side the hhvm code base, we already have ext/sockets/ext_sockets.cpp which already implement the fsockopen. Can we use it instead the ext/std/ext_std_network.cpp?
  We can build it ourselves, what is the right way to change the code?
Thanks
Jesse

https://github.com/facebook/hhvm/search?l=cpp&q=fsockopen&utf8=%E2%9C%93

**Comment by Orvid** [comment]
They are the same.

**Comment by JesseXie** [comment]
I see, they ext_std_network just use the one from sockets. Why it has such slow behavior?

**Comment by JesseXie** [comment]
it turned out is our own issues.  sorry for the noise
