### ISSUE TITLE
Cannot access protected property

### ISSUE THREAD

**Issue by iveoles** [facebook/hhvm#6337]
Hi

Since upgrading from 3.7.0 to 3.9.1 we're having issues on our sites.

    Fatal error: Cannot access protected property Illuminate\\Support\\Collection::$items in /home/*/public_html/vendor/laravel/framework/src/Illuminate/Support/Collection.php on line 411

    	/**
	 * Put an item in the collection by key.
	 *
	 * @param  mixed  $key
	 * @param  mixed  $value
	 * @return void
	 */
	public function put($key, $value)
	{
		$this->items[$key] = $value;
	}

This doesn't appear to be a code issue as it disappears after restarting HHVM. I realise this may not be possible to reproduce, but it's happening several times a day for us, so any help would be appreciated.

**Comment by JohanTan** [comment]
We've been experiencing the same issue. It's been intermittent but strongly correlated with code deployments. Restarting HHVM and it goes away. Could it be something with the central repo cache?

**Comment by Orvid** [comment]
Closing, still needs more info (https://github.com/facebook/hhvm/wiki/Human-Timeouts) - will reopen if provided.
