### ISSUE TITLE
Tests with undefined behavior will vary depending on the architecture

### ISSUE THREAD

**Issue by fabioperez** [facebook/hhvm#6339]
The results for the following test files have undefined behaviour as stated by \[1\] (page 1185): "If the value of the right operand is negative or is greater than or equal to the width of the promoted left operand, the behavior is undefined".

    hphp/test/zend/good/tests/lang/operators/bitwiseShiftLeft_variationStr_64bit.php
    hphp/test/zend/good/tests/lang/operators/bitwiseShiftRight_basiclong_64bit.php
    hphp/test/zend/good/tests/lang/operators/bitwiseShiftLeft_basiclong_64bit.php
    hphp/test/spec/tests/expressions/bitwise_shift_operators/bitwise_shift.php

The output expected by HHVM is based on the implementation by x86, which takes into account only the 6 least-significant bits of the shift count \[2\] (page 4-340). In POWER, the behaviour is to shift the register by the number of bits specified by the shift count register \[3\] (page 99).

For example, when executed by PHP 5, the command

    echo 9223372036854775807 << -1;

will print `0` on POWER and `-9223372036854775808` on x86-64.

Shouldn’t some of these tests (e.g. shifting by negative numbers of by numbers larger than 64) be removed as they lead to undefined behaviours? 

[1] JONES, Derek M. The New C Standard http://www.coding-guidelines.com/cbook/cbook1_1.pdf 
[2] Intel® 64 and IA-32 Architectures Software Developer’s Manual Volume 2 (2A, 2B & 2C): Instruction Set Reference, A-Z http://www.intel.com.br/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-software-developer-instruction-set-reference-manual-325383.pdf
[3] Power ISA™ Version 2.07 < https://www.power.org/wp-content/uploads/2013/05/PowerISA_V2.07_PUBLIC.pdf>

**Comment by fredemmott** [comment]
The zend tests are taken from PHP - we need to test compatibility, so will not remove these tests, especially as x64 is currently the only supported architecture.

If this is blocking porting work, the script to import the zend tests should be modified to add .skipif files for non-portable tests that check the architecture.

We'd also be happy to take a PR adding a skipif for the bitwise_shift.php test.

**Comment by fabioperez** [comment]
How about the tests that have deterministic behaviours included in these files? Should we also skip them? They are useful for the porting.

**Comment by fredemmott** [comment]
The zend/ tests must not be modified at all - they are periodically wiped and replaced with verbatim copies from upstream PHP. If you want part of their content, you need to add new tests outside of zend/ duplicating them.

For bitwise_shift.php, possibly split it up to bitwise_shift.php + bitwise_shift-x64.php, and add a skipif for the latter.

**Comment by SiebelsTim** [comment]
>  they are periodically wiped and replaced with verbatim copies from upstream PHP

Last two times weren't wiped I believed. Periodically... Last time is about a year ago (16.10.2014)? :D

**Comment by fabioperez** [comment]
@fredemmott Thanks.

`hphp/test/slow/ext_gmp/mostInOne.php` is also testing an undefined behaviour.

From https://secure.php.net/manual/en/function.gmp-divexact.php:

> Divides n by d, using fast "exact division" algorithm. This function produces correct results only when it is known in advance that d divides n.

The following part of the test is trying to divide 10 by 3:

    $div2 = gmp_divexact("10", "3"); // bogus result
    echo gmp_strval($div2) . "\n";

What can be done about this one?

**Comment by fredemmott** [comment]
> Periodically... Last time is about a year ago (16.10.2014)?

s/Periodically/Occasionally/ :p

> mostInOne.php

This sounds like it should also have the arch-specific stuff split to separate files with .skipifs
