### ISSUE TITLE
hacklang plugin for visual studio

### ISSUE THREAD

**Issue by furesoft** [facebook/hhvm#6346]
please add an visual studio plugin for hack

**Comment by Orvid** [comment]
That would be pointless without the hack typechecker fully functioning under Windows. Also, creating a Visual Studio plugin for a language is a significant undertaking, syntax highlighting is relatively easy, but the semantic help that you normally expect out of Visual Studio takes significantly more work.

**Comment by fredemmott** [comment]
This would be best:
 - left until the typechecker runs on windows (in progress)
 - done as a separate project so that people responsible for maintaining it are people who actually use visual studio
