### ISSUE TITLE
Apache performs worse using HHVM than with php5 module or php5 cgi

### ISSUE THREAD

**Issue by greencopper** [facebook/hhvm#6349]
I wanted to do some basic testing before choosing between Nginx with HHVM and Apache2 with HHVM.

I have run the test on Qemu, so it does not represent a real world scenario, and as such might be useless. However, I would like to understand why there is such a huge difference and what it might represent.

For the benchmark I have used http://www.php-benchmark-script.com/

```
Nginx running with normal PHP
------------------------------------------------
test_math                        : 37.250 sec.
test_stringmanipulation   : 34.207 sec.
test_loops                        : 12.634 sec.
test_ifelse                         : 7.601 sec.
------------------------------------------------
Total time:                        : 91.692 sec.

Apache running with PHP as a module
------------------------------------------------
test_math                        : 36.436 sec.
test_stringmanipulation   : 33.752 sec.
test_loops                        : 13.437 sec.
test_ifelse                         : 7.570 sec.
------------------------------------------------
Total time:                        : 91.195 sec.
```

As expected the results where pretty close.

```
Nginx running with HHVM
------------------------------------------------
test_math                        : 13.193 sec.
test_stringmanipulation   : 17.806 sec.
test_loops                        : 1.129 sec.
test_ifelse                         : 0.553 sec.
------------------------------------------------
Total time:                        : 32.681 sec.
```

Nginx is performing about 3 times as fast with HHVM, which pretty much match what's seen on the Internet of different benchmarks and tests.

```
Apache running with HHVM
------------------------------------------------
test_math                        : 24.825 sec.
test_stringmanipulation   : 26.041 sec.
test_loops                        : 40.565 sec.
test_ifelse                         : 24.442 sec.
------------------------------------------------
Total time:                        : 115.873 sec.
```

This is a pretty big decrease in performance. I have run the tests several times in order to try to improve the results, as I know that the JIT will be slower for the first few requests on almost any workload, but without any noticeable improvements, the results vary between 113.xxx to 118.xxx sec.

**Comment by fredemmott** [comment]
- we do not optimize for such microbenchmarks. Optimizing for math, loops, if/else microbenchmarks etc often causes tradeoffs (eg code inlining) that actually harm real-world performance
 - comparing HHVM + Apache with Apache + PHP-FPM would be a more reasonable comparison than mod_php - FastCGI itself has overhead
 - it's unclear if HHVM's jit was warmed up properly

**Comment by greencopper** [comment]
I did test Apache with FPM too, but gained similar results as with mod_php.

The HHVM jit ran many times as I tried to improve the results, but the results was almost identical.

**Comment by greencopper** [comment]
I would like to perform a test with a Magento installation to measure that, but thanks for your reply! :)

**Comment by greencopper** [comment]
Now I am actually getting around the same results for Nginx, so clearly something is wrong in this setup since the good results I got with Nginx was from yesterday.

```
--------------------------------------
| PHP BENCHMARK SCRIPT |
--------------------------------------
Start : 2015-10-09 02:23:34
Server : _@192.168.1.100
PHP version : 5.6.99-hhvm
Platform : Linux
--------------------------------------
test_ifelse                        : 24.995 sec.
test_math                        : 25.639 sec.
test_stringmanipulation   : 25.774 sec.
test_loops                        : 40.702 sec.
--------------------------------------
Total time:               : 117.11 sec.
```

**Comment by fredemmott** [comment]
You might want to look at extending https://github.com/hhvm/oss-performance to support Apache
