### ISSUE TITLE
infinite recursion detected - magento2

### ISSUE THREAD

**Issue by craigcarnell** [facebook/hhvm#6350]
hhvm error.log:

```
[Fri Oct  9 08:59:46 2015] [hphp] [26909:7fa9dd3ff700:66:000001] [] \nFatal error: infinite recursion detected in /var/www/vhosts/magento2-capistrano/releases/20151009085140/app/code/Magento/ProductVideo/Block/Adminhtml/Product/Edit/NewVideo.php on line 218
```

Magento 2: Adding a product to the backend throws this error on asort

```
$mediaRoles = $this->getProduct()->getMediaAttributes();
asort($mediaRoles);
```

https://github.com/magento/magento2/issues/2067

hhvm --version
```
HipHop VM 3.9.1 (rel)
Compiler: tags/HHVM-3.9.1-0-g0f72cfc2f0a01fdfeb72fbcfeb247b72998a66db
Repo schema: 6416960c150a4a4726fda74b659105ded8819d9c
```

**Comment by fredemmott** [comment]
Are you able to reduce this to a small, standalone example? It is extremely unlikely that we will investigate a framework issue without one.

**Comment by craigcarnell** [comment]
@fredemmott Sure, if you can leave it open for now I will get some code to you

**Comment by craigcarnell** [comment]
@fredemmott I tried to dump the contents of the array using PHP however I was rather unsuccessful. I was going to then set up the same array contents in HHVM and run asort on it. They have changed this upstream to ksort which resolves part of the issue for now.
