### ISSUE TITLE
The error message when I do not implement all the methods of an interface doesn't seem accurate

### ISSUE THREAD

**Issue by vdurmont** [facebook/hhvm#6353]
Hi,

I have the following code:

```php
<?hh // strict
// This is MyInterface.hh

interface MyInterface {
  public function someMethod() : string;
}
```

```php
<?hh // strict
// This is MyWrongImplementation.hh

class MyWrongImplementation implements MyInterface {
}
```

When I run it with hhvm, I get the following error:

> Catchable fatal error: Hack type error: This object is of type MyWrongImplementation at /Users/vdurmont/development/hhvm/MyWrongImplementation.hh line 4

It is totally normal that I get an error here since I didn't implement all the methods of the interface.

I just think that the error message should be different. Something along the lines of:

> Catchable fatal error: Hack type error: The object of type MyWrongImplementation must implement the method MyInterface::someMethod at /Users/vdurmont/development/hhvm/MyWrongImplementation.hh line 4

What do you think?

I didn't dive into the code for this error so maybe my suggestion is not accurate but from a "user" point of view, I think it would make more sense.

I am using:
HipHop VM 3.9.1 (rel)
Compiler: 1442179036_N
Repo schema: 736bbc826148eaf3e9af86092b7f0902f922a3bd

**Comment by SiebelsTim** [comment]
This is due to the runtime calling `hh_client`. `hh_client` catches the error with way more information for you. I guess the runtime only includes the first line.

**Comment by fredemmott** [comment]
We can't include the full error without breaking a large number of common (not FB) logging systems. As @SiebelsTim said, you want to run hh_client to get the full thing:

![screen shot 2015-10-09 at 1 43 07 pm](https://cloud.githubusercontent.com/assets/360927/10405111/b0effc2c-6e8b-11e5-8bca-5fa71c9e2d63.png)

**Comment by vdurmont** [comment]
Thanks for your quick answer, it totally makes sense. I took the (wrong?) habit to use `hhvm <myfile>` to run my code instead of using the client first.
