### ISSUE TITLE
Release of 3.3.6 appears before 3..9.1

### ISSUE THREAD

**Issue by hubdotcom** [facebook/hhvm#6355]
![screenshot 2015-10-10 13 54 19](https://cloud.githubusercontent.com/assets/5274747/10411001/73dbec30-6f56-11e5-9a19-dd5928879409.png)

**Comment by JoelMarcey** [comment]
That's ok. These are sorted by date of release as you see. And 3.6.x is an LTS release, so we backport key patches (security, etc.) to that release. We do the same with 3.9.x too. We just happened to do 3.9.x first this time.
