### ISSUE TITLE
repo authoritative and server reboot

### ISSUE THREAD

**Issue by marcokh** [facebook/hhvm#6356]
Hello,

I'm trying to setup hhvm on ubuntu, with apache, fastcgi setup and repo.authoritative mode.

Everything so far is working great but I'm having some difficulties with the final setup.

I noticed that when the computer reboot (not just hhvm server), the content of the directory /var/run/hhvm get cleaned up and a new hhvm.hhbc file is generated. 

In the scenario I'm trying to achieve, the hhvm.hhbc file is generated on a different computer and downloaded by the target computer, which doesn't host the source files and may have to reboot. 

Generating the file remotely work fine, I can update the repo and restart hhvm, the newly updated repo is then run successfully. However, if the computer reboot, something is trying to generate a new repo file which breaks my application.

I have looked into the startup script /etc/init.d/hhvm but couldn't find out where those actions are called. I also didn't find any trace of it in my system log or in hhvm error.log

What would be the way to switch off this behavior ?

Any help would be greatly appreciated

**Comment by karpa13a** [comment]
@marcokh 
/var/tmp cleaned up during boot. it's a in-memory directory.
change repo-path to smth like /var/lib/hhvm or to /home/[user]/hhvm.cache (create this dir before, check permissions, and change your upload cripts)

**Comment by marcokh** [comment]
Thanks for the quick answer Karpa! I am talking about the default run dir for hhvm  /var/run/hhvm , not about /var/tmp

However I'm going to try your suggestion of changing the repo path and see if it also get cleaned up or not as it may just be my solution :)

**Comment by karpa13a** [comment]
@marcokh see https://github.com/hhvm/packaging/issues/132 this issue. wait for next hhvm release or apply diff by hand.

**Comment by marcokh** [comment]
@karpa13a I tried to change the repo path as you suggested but restarting hhvm fail :

Failed to initialize central HHBC repository:\n  Failed to initialize schema in /home/marco/hhvm.hhbc: \n  Failed to open /var/www/.hhvm.hhbc: 14 - unable to open database file\n

I think the permissions are set correctly :

marco@ellies-cafe:~$ ls -l /home/marco/hhvm.hhbc 
-rw-r--r-- 1 www-data www-data 23431168 ១០ 11 12:30 /home/marco/hhvm.hhbc

Does it need the pid file to be next to it ?

**Comment by karpa13a** [comment]
ls -l /home|grep marco
to see dir permissions
i think they are 750 marco/marco )

**Comment by marcokh** [comment]
sorry but that doesn't seem to be the issue, have rx rights for others

marco@ellies-cafe:~$ ls -l /home|grep marco
drwxr-xr-x 16 marco marco 4096 ១០ 11 12:30 marco

**Comment by karpa13a** [comment]
@marcokh try:
cd /
sudo -u www-data touch /home/marco/hhvm.hhbc
it's ok?

**Comment by marcokh** [comment]
same error on hhvm restart

Failed to initialize central HHBC repository:\n  Failed to initialize schema in /home/marco/hhvm.hhbc: \n  Failed to open /var/www/.hhvm.hhbc: 14 - unable to open database file\n

**Comment by marcokh** [comment]
I think I found a working configuration. The only difference is that the hhbc file should be run from inside a folder that belong to the same user who is running it. The startup script use www-data so the running folder should belong to www-data:www-data

sudo mkdir -p -m0755 /var/cache/hhvm
sudo chown www-data:www-data /var/cache/hhvm/
sudo cp /home/marco/hhvm.hhbc /var/cache/hhvm/

Also, placing the repo in another directory than the default /var/run/hhvm is preventing the file from being rewritten on reboot, which is what I was looking for so this issue is now fixed for me.

@karpa13a thanks a lot for your help!

**Comment by jwatzman** [comment]
It doesn't matter where you put it, as long as the permissions are correct, and the INI file is up to date :) From discussion on https://github.com/hhvm/packaging/issues/132 and https://github.com/hhvm/packaging/pull/134 I think `/var/run` is where I'll move it to. This may or may not happen before 3.10 is released, sorry.

**Comment by jwatzman** [comment]
(And going to close out since it seems like the immediate problem here is solved; feel free to comment on https://github.com/hhvm/packaging/issues/132.)
