### ISSUE TITLE
Configure HHVM for Repo Authoritative Mode

### ISSUE THREAD

**Issue by redconfetti** [facebook/hhvm#6358]
There is a way to configure HHVM to know that certain PHP files will go unchanged, and thus avoid refreshing it's own APC-like cacheing of compiled PHP code.

Taken from [Go Faster!](http://hhvm.com/blog/4061/go-faster)
> HHVM is still going to default to checking the subject file each time it’s requested to make sure it hasn’t changed. That means disk I/O, and that means time. For a production server where source files are confidently not-changing, that’s just a waste.

**Comment by redconfetti** [comment]
oops wrong repo. Sorry FB

**Comment by jwatzman** [comment]
Not sure where you intended to open this, but for reference, https://github.com/facebook/hhvm/wiki/Performance-Tuning has much more recent and up to date info about repo auth. It's about a lot more than just file IO at this point, tons of perf optimizations can be done only in that mode.

**Comment by redconfetti** [comment]
Thanks for the tip @jwatzman. I meant to open this in our own private issues area, not in the Facebook HHVM issues.
