### ISSUE TITLE
Delay in HHVM Release. Release Schedule not updated

### ISSUE THREAD

**Issue by corientdev** [facebook/hhvm#6359]
It seems there is delay in HHVM 3.10.0 Release. 

Anyway just wanted to remind Release Schedule is not updated yet.

Kindly edit it somebody.

https://github.com/facebook/hhvm/wiki/Release-Schedule

**Comment by jwatzman** [comment]
We're a little behind, as we are with most releases :) I'll update the wording on the page to tell people just to expect this. I intend to publish the 3.10 branch this morning, and the release early this week.
