### ISSUE TITLE
Core dumped: Segmentation fault

### ISSUE THREAD

**Issue by TakeshiOgimi** [facebook/hhvm#6366]
Environment
* Ubuntu 14.04.3 LTS
* HipHop VM 3.9.1 (rel)
 * Installation in the following URL of procedure
[Prebuilt packages on Ubuntu 14.04 · facebook/hhvm Wiki](https://github.com/facebook/hhvm/wiki/Prebuilt-packages-on-Ubuntu-14.04)

Problem occurs with the following code
```
<?php
extract(array(), EXTR_REFS);
```

**Comment by JoelMarcey** [comment]
@TakeshiOgimi Thanks for the simple reproduction case. I can confirm this happening as well. I modified the sample a bit to be:

```
<?php
var_dump(extract(array(), EXTR_REFS));
```

PHP 5/7 returns

```
int(0)
```

We (HHVM) segfault as stated. 

```
hhvm: hphp/runtime/base/empty-array.cpp:60: NvGetKey: Assertion `false' failed.
Core dumped: Aborted
```

Here is a piece of the stacktrace:

```
Arguments: /tmp/dd.php
ThreadType: CLI

# 4  HPHP::EmptyArray::NvGetKey(HPHP::ArrayData const*, HPHP::TypedValue*, long) at /tmp/hphp/runtime/base/empty-array.cpp:60
# 5  HPHP::ArrayData::nvGetKey(HPHP::TypedValue*, long) const at /tmp/hphp/runtime/base/array-data-defs.h:171
# 6  HPHP::ArrayData::getKey(long) const at /tmp/hphp/runtime/base/array-data-defs.h:139
# 7  HPHP::extract_impl(HPHP::VRefParamValue const&, int, HPHP::String const&)::{lambda(HPHP::Array&)#1}::operator()(HPHP::Array&) const at /tmp/hphp/runtime/ext/std/ext_std_variable.cpp:401
# 8  HPHP::f_SystemLib_extract(HPHP::VRefParamValue const&, long, HPHP::String const&) at /tmp/hphp/runtime/ext/std/ext_std_variable.cpp:421

PHP Stacktrace:
```

On the surface, we are failing an assertion test when maybe we shouldn't be in this case.

**Comment by TakeshiOgimi** [comment]
Thank you for kind comment. 

However It was confirmed that works well on CentOS with manual build.
- OS: CentOS 7.1.1503 (x86_64)
- HHVM: 3.9.1 (rel) 

Be solved by modifying the configuration file?
```
; php options

pid = /var/run/hhvm/pid

; hhvm specific

hhvm.server.port = 9000
hhvm.server.type = fastcgi
hhvm.server.default_document = index.php
hhvm.log.use_log_file = true
hhvm.log.file = /var/log/hhvm/error.log
hhvm.repo.central.path = /var/run/hhvm/hhvm.hhbc
```

**Comment by satoshiyamamoto** [comment]
I have same problem. But works fine if following environment.

Result: 
```
int(0)
```

HHVM Version:
```
HipHop VM 3.3.7 (rel)
Compiler: tags/HHVM-3.3.7-0-ge0344cb6ab126e50e611332f03f447f586cc763a
Repo schema: 248991c4ea4ca3f926dc6ea361a60b4a0345857a
Extension API: 20140829
```

Ubuntu Version:
```
$ lsb_release 
LSB Version:	core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch:core-4.1-amd64:core-4.1-noarch:security-4.0-amd64:security-4.0-noarch:security-4.1-amd64:security-4.1-noarch
```
3.9.x is it still is better not to use?

**Comment by TakeshiOgimi** [comment]
@JoelMarcey Thank you for kind comment. 
Was confirmed in an older version, it was confirmed that the work.

HHVM Version.
```
HipHop VM 3.6.6 (rel)
Compiler: tags/HHVM-3.6.6-0-gead6875c956d4bd5e906ebea899c71c3b8a7182d
Repo schema: 5034239b4e72c991556d7e651946e7fe89d8c2f4
```
Result:
```
int(0)
```

Whether it is better not to use the 3.9.x?

**Comment by jwatzman** [comment]
Thanks for the repro case, and figuring out that it works on older versions. Hopefully someone can get time to bisect it or otherwise look into the issue.

I'd still strongly recommend using 3.9 -- the 3.3 series is out of support and won't be getting security fixes.

**Comment by satoshiyamamoto** [comment]
@jwatzman Thanks for the advice. 
If resolved the this issue by 3.9.x version updates, will be FuelPHP runnning on the HHVM.

**Comment by danslo** [comment]
@JoelMarcey Interestingly it [doesn't segfault](https://3v4l.org/F66uH) on 3v4l for any HHVM version.

**Comment by JoelMarcey** [comment]
@danslo Hmm.... that is very odd. It is asserting on GitHub master and trunk internally. :/

**Comment by jwatzman** [comment]
I'm attempting to bisect this, if I can get it done before I have to go to dinner :)

**Comment by jwatzman** [comment]
Looks like it's 6d05e5b97eda8dfa6443cd70f86a8cc0be9dd1ff. Will debug later if I get some time.

**Comment by jwatzman** [comment]
Going to close as dupe of #6498 even though it's newer since it has a PR attached.

**Comment by satoshiyamamoto** [comment]
Thank you for your support!
