### ISSUE TITLE
mb_convert_variables , convert array() to NULL unexpectedly (hhvm 3.0.1)

### ISSUE THREAD

**Issue by ever-rhythm** [facebook/hhvm#6367]
which is different from php5 and i regard it as a bug .

HipHop VM 3.0.1;baidu version:1.0.7.0 (rel)
Compiler: 1433213110_059317031
Repo schema: HHVM_3_0_1

PHP 5.2.17 (cli) (built: Jul  7 2014 17:40:30) 

	<?php
	
	   $a = array(
	       'x' => array(),
	   );
	
	   mb_convert_variables( 'utf8' , 'auto' , $a );
	
	   var_dump($a);

hhvm will get 

	array(1) {
	  ["x"]=>
	  NULL
	}

php will get 

	array(1) {
	  ["x"]=>
	  array(0) {
	  }
	}

And i found it's caused by php_mbfl_convert() in hphp/runtime/ext/ext_mb.cpp

	static Variant php_mbfl_convert(const Variant& var,
	                                mbfl_buffer_converter *convd,
	                                mbfl_string *string,
	                                mbfl_string *result) {
	  if (var.is(KindOfArray)) {
	    Array ret; //  Array ret = Array::Create(); will be ok 
	    Array items = var.toArray();
	    for (ArrayIter iter(items); iter; ++iter) {
	      ret.set(iter.first(),
	              php_mbfl_convert(iter.second(), convd, string, result));
	    }
	    return ret;
	  }
	 ....

My first Issue , hoping to be taken seriously : )

**Comment by simonwelsh** [comment]
This doesn't replicate on 3.6 and up (https://3v4l.org/58NEh). I suggest you upgrade (3.0 is a rather old release and is no longer supported).

**Comment by JoelMarcey** [comment]
@simonwelsh Thanks. 

Yes, 3.0 is quite old, unsupported. Please upgrade if you can.

**Comment by jwatzman** [comment]
(Beyond being unsupported, 3.0 has multiple known security vulnerabilities. I cannot emphasize strongly enough how much I recommend you upgrade.)

**Comment by ever-rhythm** [comment]
I will try , thx : )
