### ISSUE TITLE
mb_encoding_aliases is not implemented

### ISSUE THREAD

**Issue by nicolas-grekas** [facebook/hhvm#6372]
Looks like this PHP function is missing an implementation in HHVM

**Comment by jwatzman** [comment]
Looks like. There's already `test/zend/bad/ext/mbstring/tests/mb_encoding_aliases.php` if someone wants to look into this.

**Comment by noony** [comment]
This issue can be closed. fixed by 4d2e1091abf0aaa90439e8aa783a21e2d6e17407

**Comment by nicolas-grekas** [comment]
Cool, thanks
