### ISSUE TITLE
make-parser.sh fails with: PHP5 and PHP7 headers differ, must be the same tokens

### ISSUE THREAD

**Issue by jrobeson** [facebook/hhvm#6376]
the actual error is
```bash
$ ./hphp/parser/make_parser.sh
/home/johnny/hhvm/hphp/parser/hphp.5.tab.hpp /home/johnny/hhvm/hphp/parser/hphp.7.tab.hpp differ: byte 1534, line 33
PHP5 and PHP7 headers differ, must be the same tokens
```

This is with current master and the 3.10 branch

**Comment by jwatzman** [comment]
Can you diff the output files and see what's different? The script works just fine internally.

**Comment by jrobeson** [comment]
`[johnny@localhost hhvm]$ diff -u hphp/parser/hphp.5.tab.hpp hphp/parser/hphp.7.tab.hpp `
```diff
--- hphp/parser/hphp.5.tab.hpp	2015-10-16 20:36:50.550566921 +0000
+++ hphp/parser/hphp.7.tab.hpp	2015-10-16 20:36:51.240566921 +0000
@@ -30,14 +30,14 @@
    This special exception was added by the Free Software Foundation in
    version 2.2 of Bison.  */
 
-#ifndef YY_COMPILER5_HOME_JOHNNY_HHVM_HPHP_PARSER_HPHP_5_TAB_HPP_INCLUDED
-# define YY_COMPILER5_HOME_JOHNNY_HHVM_HPHP_PARSER_HPHP_5_TAB_HPP_INCLUDED
+#ifndef YY_COMPILER7_HOME_JOHNNY_HHVM_HPHP_PARSER_HPHP_7_TAB_HPP_INCLUDED
+# define YY_COMPILER7_HOME_JOHNNY_HHVM_HPHP_PARSER_HPHP_7_TAB_HPP_INCLUDED
 /* Debug traces.  */
 #ifndef YYDEBUG
 # define YYDEBUG 0
 #endif
 #if YYDEBUG
-extern int Compiler5debug;
+extern int Compiler7debug;
 #endif
 
 /* Token type.  */
@@ -249,6 +249,6 @@
 
 
 
-int Compiler5parse (HPHP::HPHP_PARSER_NS::Parser *_p);
+int Compiler7parse (HPHP::HPHP_PARSER_NS::Parser *_p);
 
-#endif /* !YY_COMPILER5_HOME_JOHNNY_HHVM_HPHP_PARSER_HPHP_5_TAB_HPP_INCLUDED  */
+#endif /* !YY_COMPILER7_HOME_JOHNNY_HHVM_HPHP_PARSER_HPHP_7_TAB_HPP_INCLUDED  */

```

**Comment by jrobeson** [comment]
so what do you think?

**Comment by jwatzman** [comment]
I've been super busy... there is supposed to be stuff in `make-parser.h` that `sed`'s away the differences. Though we may check the parsers being the same before that, and our version of bison makes them the same?

As a practical matter, the versions of these files that get committed and pushed in our repo will be generated from FB infra anyways, so you can probably just comment out that check and things will work, and we'll generate the files we want on our end anyways. But we shouldn't be erroring on this, but I'm not sure when I'll get time to dig into it.

**Comment by paravoid** [comment]
This happens here as well — verified with bison 3.0.2 and 3.0.4. Post-processing bison's output is probably the source of this issue, also see e.g. #2573 for similar woes in the past.

**Comment by jwatzman** [comment]
This is unfortunately not something I'm going to get to before leave the HHVM team... sorry :\

**Comment by jwatzman** [comment]
Nice, thanks!
