### ISSUE TITLE
iconv_mime_decode doesn't honor ICONV_MIME_DECODE_CONTINUE_ON_ERROR

### ISSUE THREAD

**Issue by nicolas-grekas** [facebook/hhvm#6378]
Instead, it throws a warning and returns false in this situations:

`iconv_mime_decode('Illegal encoded-word: =?utf-8?Q?'.chr(0xA1).'?= .', ICONV_MIME_DECODE_CONTINUE_ON_ERROR)`

See https://3v4l.org/TNRrh

**Comment by noony** [comment]
Fixed by 00f62fa093ed77d5fa12d3b9117d79c3e4b7aed2 this issue can be closed.
