### ISSUE TITLE
Problem upgrading when running as non www-data user

### ISSUE THREAD

**Issue by codeaken** [facebook/hhvm#6383]
We are running HHVM under the hhvm user (default is www-data). Everytime we upgrade to a new version HHVM has problems restarting. We get these errors in the error log:

    [Fri Oct 16 22:14:20 2015] [hphp] [1794:7f75dc758ac0:0:000001] [] Permission denied opening socket at /var/run/hhvm/sock
    [Fri Oct 16 22:14:20 2015] [hphp] [1794:7f75dc758ac0:0:000002] [] Unable to start page server
    [Fri Oct 16 22:14:20 2015] [hphp] [1794:7f75dc758ac0:0:000003] [] Shutting down due to failure(s) to bind in HttpServer::runAndExitProcess

After upgrading, the directory `/var/run/hhvm` is owned by `www-data:www-data`. If we change the owner of this directory to `hhvm:hhvm` we are able start hhvm successfully. 

Our `/etc/default/hhvm` file contains:

    RUN_AS_USER="hhvm"
    RUN_AS_GROUP="hhvm"

Is it possible to alter the upgrade script so that we get the correct permissions on the directories per what is defined in the defaults file?

We are running under Debian 8.2.

**Comment by r3wt** [comment]
Fyi, it does no good to gripe at them about this. They'll just tell you to fuck off basically.

**Comment by simonwelsh** [comment]
I just submitted a PR against the packaging repo to do this: hhvm/packaging#135

**Comment by r3wt** [comment]
@simonwelsh thanks, i know alot of people have been having problems with this.

**Comment by codeaken** [comment]
@simonwelsh Thanks alot Simon, it looks like your PR will be merged :)
