### ISSUE TITLE
Call to undefined method mysqli_stmt::num_rows() (3.10.0)

### ISSUE THREAD

**Issue by r0bdiabl0** [facebook/hhvm#6391]
I am getting this error when using mysqli with hhvm 3.10.0. I haven't tried this with any other version yet.  Here is some sample code:

    <?php
    $db = new mysqli('127.0.0.1', 'user', 'password, 'db');
    $stmt = $db->prepare("SELECT id FROM users ORDER BY RAND() LIMIT 3");
    $stmt->bind_result($id);
    $stmt->execute();
    $stmt->store_result();

    echo $stmt->num_rows();

I have confirmed that I am able to connect to my database server because other mysqli calls work just fine and data is returned.

**Comment by codeaken** [comment]
You are calling it wrong, `num_rows` is not a function but a variable. Change the line to look like this instead and it should work:

    echo $stmt->num_rows;

**Comment by r0bdiabl0** [comment]
My bad. I copied this code from some old tutorial and didn't even check that. I looked it over a thousand times. What's crazy is it works with another version of just php.
