### ISSUE TITLE
HHVM 3.10 crashes constantly

### ISSUE THREAD

**Issue by Krapulat** [facebook/hhvm#6397]
I have a webserver with several wordpress installations. And HHVM crashes constantly.

This is the c++ stack trace: http://pastebin.com/Z8ZWMJSW

It crashed in thread 9.

**Comment by paulbiss** [comment]
Looks to me like your TC is filling up. You can try increasing the size, although it may just be a leak. The assertion message should explain how to adjust the size of the TC. We've had some known leaks with wordpress from create_function, but they should be resolved in 3.10.

**Comment by Krapulat** [comment]
@paulbiss How can I increase the TC size?

**Comment by paulbiss** [comment]
```
hhvm.jit_a_size = ...
hhvm.jit_a_frozen_size = ...
hhvm.jit_a_prof_size = ...
hhvm.jit_a_cold_size =  ...
hhvm.jit_a_max_usage = ...
```

**Comment by Krapulat** [comment]
@paulbiss If I set "hhvm.jit_a_prof_size" hhvm doesn't start. I have to comment this line. Why?

I set all the others vars to 1000000000, and for now it doesn't crash :)

**Comment by paulbiss** [comment]
The TC has to fit in low memory, it's possible that with the increase in prof size the TC was just too large. Aprof is the region that we JIT profiling translations into.
