### ISSUE TITLE
Hack: optionally error on invalid shape keys

### ISSUE THREAD

**Issue by HRMsimon** [facebook/hhvm#6399]
Since Hack only checks that a shape being passed in is a valid super-type of the type-hinted shape, it doesn't pick up typos in shape keys if the actual key is optional. It'd be nice if there was some way to mark a shape as only accepting the defined keys, so errors get thrown on typos.

For example, it'd be nice if this could throw some sort of error (either with a `.hhconfig` setting or deceleration-site setting somehow)

``` hack
<?hh // strict

function foo(shape('hello' => ?string) $a): void {}

function bar(): void {
  foo(shape('Hello' => 'world'));
}
```

**Comment by paulbiss** [comment]
I know that this was discussed as one of the potential drawbacks of shape subtyping when we added it. cc @jwatzman @dlreeves

**Comment by jwatzman** [comment]
@dabek

**Comment by Wilfred** [comment]
No longer relevant according to @simonwelsh. `hh` no longer accepts the code shown :)
