### ISSUE TITLE
Regression: file_exists( '.' ) returns false in 3.10 and 3.10.1

### ISSUE THREAD

**Issue by Nikerabbit** [facebook/hhvm#6402]
https://3v4l.org/oNZon

Also present in 3.10.1 (tested locally).

**Comment by Nikerabbit** [comment]
Downstream bug report: https://phabricator.wikimedia.org/T116216

**Comment by paulbiss** [comment]
Blame rev: 881302b0375d0cda56783f73245a872dccb7aa2f

**Comment by jwatzman** [comment]
Thanks for pinning this down.

@paulbiss we probably don't want to revert that rev, right, and should fix forward?

**Comment by paulbiss** [comment]
Yeah, we don't want to back this out. I should have some time this week to poke at it, I suspect it'll be an easy fix.

**Comment by Nikerabbit** [comment]
Maybe this week? ;) Otherwise I will make my temporary realpath() workaround more permanent.

**Comment by jwatzman** [comment]
`FileUtil::canonicalize` improperly "caonicalizes" `.` into the empty string. Before 881302b0375d0cda56783f73245a872dccb7aa2f we hid this by `TranslatePath` treating the empty string as CWD.

I'm going to give fixing it a shot.

**Comment by jwatzman** [comment]
D2620909 is up for review internally to fix this.
