### ISSUE TITLE
filter_input_array() expects at least 2 parameters, 1 given

### ISSUE THREAD

**Issue by Krapulat** [facebook/hhvm#6403]
HHVM outputs this warning when using the function: filter_input_array( INPUT_GET ).

When second argument in filter_input_array is optional: http://docs.hhvm.com/manual/en/function.filter-input-array.php

Demonstration: https://3v4l.org/9E7GL

**Comment by noony** [comment]
I'm handling this php incompatibility.

**Comment by Alehap** [comment]
Hello, how can I solve this trouble?

**Comment by fredemmott** [comment]
Fixed by https://github.com/facebook/hhvm/commit/dcb0fe19c5e7419cdfb5e066660b0f51f946fbee - install hhvm-nightly package or wait for 3.12
