### ISSUE TITLE
foreach($array['non_existant_key'] as &$row) silently modifies array

### ISSUE THREAD

**Issue by r3wt** [facebook/hhvm#6404]
Dropping this here as it also effects HHVM. Instead of undefined index we get a new index in the array.

repro: https://3v4l.org/UNIe4

bug report: https://bugs.php.net/bug.php?id=70771&thanks=4

**Comment by paulbiss** [comment]
This may be an intentional side effect of by-reference iteration. In HHVM we bind the array slot by reference to the iterator. Binding by reference to a nonexistent key implicitly inserts it into the array https://3v4l.org/FIZkY

**Comment by r3wt** [comment]
If you think its a non issue then please accept my apologies and close thread

**Comment by paulbiss** [comment]
@r3wt no worries, I just wanted to offer some perspective from our side. Looks like @nikic closed the issue over on php.net so I'm going to do the same here.
