### ISSUE TITLE
HHVM 3.10.1 (hhvm-dbg) crashes an leaves no stacktrace

### ISSUE THREAD

**Issue by rschenk0** [facebook/hhvm#6405]
I tried using hhvm-dbg to get a stacktrace of our frequently (~1x-2x/h) segfaulting hhvm's on six loaded workers

hhvm-dbg:
  Installed: 3.10.1~trusty
  Candidate: 3.10.1~trusty
  Version table:
 *** 3.10.1~trusty 0
        500 http://dl.hhvm.com/ubuntu/ trusty/main amd64 Packages

It crashed 2 times (and was restarted by monit) but left no data in /tmp/stacktrace.XXX.log (0 byte)

/var/log/kern.log
Oct 22 20:33:39 www-X kernel: [219462.038577] hhvm[10043]: segfault at 0 ip 0000000003c0f570 sp 00007f4b54ff7df0 error 4 in hhvm[400000+7432000]
Oct 22 21:23:48 www-X kernel: [222468.571863] hhvm[15041]: segfault at 1d ip 00000000059152de sp 00007fb1eeff7e10 error 4 in hhvm[400000+7432000]

HHVM has following config:
root@www-X:~# cat /etc/hhvm/server.ini
; php options

pid = /var/run/hhvm/pid

; hhvm specific
hhvm.server.ip = 0.0.0.0
hhvm.server.port = 9001
hhvm.server.type = fastcgi
hhvm.server.default_document = index.php
hhvm.repo.central.path = /var/run/hhvm/hhvm.hhbc

;hhvm.http.default_timeout = 50
;hhvm.server.connection_timeout_seconds = 50
;hhvm.server.thread_count = 1000
hhvm.http.slow_query_threshold = 2500
hhvm.mysql.slow_query_threshold = 2000

; JIT Settings
hhvm.jit = true
hhvm.jit_warmup_requests = 10
hhvm.jit_a_size = 536870912
hhvm.jit_a_cold_size = 268435456
hhvm.jit_a_frozen_size = 536870912
hhvm.jit_a_prof_size = 536870912
hhvm.jit_a_max_usage = 536870912

; Debug
hhvm.debug.full_backtrace = true
hhvm.debug.server_stack_trace = true
hhvm.debug.server_error_message = true
hhvm.debug.translate_source = true
hhvm.debug.core_dump_report_directory = /tmp

What can we do ?

**Comment by reeze** [comment]
How did you debug it with `hhvm-dbg` it is a wrapper for `gdb` command. Maybe gdb itself crashed. did you enabled core dump?

**Comment by rschenk0** [comment]
I did not debug it with gdb I only wanted to get informative stacktraces from hhvm logged instead of zero byte files to identify the problem. hhvm-dbg Ubuntu package is the alternative binary-build of hhvm itself.

**Comment by reeze** [comment]
my mistake. You mean the debug release. You can enable core dump and use gdb to get backtrace instead.

**Comment by effeks** [comment]
Having similar issue with 3.10.1 on Debian Jessie. Segfault, but empty stacktrace file. Running HHVM without repo-mode enabled.

Not completely verified, but seems that it's possible to replicate by simply changing one of the files served by HHVM.

Oct 26 15:27:58 localhost kernel: [19013.318699] hhvm[20945]: segfault at 0 ip 00000000013988d7 sp 00007f7909bf84c0 error 4 in hhvm[400000+2fbb000]

How do I make sure the stacktrace-file is not empty? Thanks!

**Comment by jazzdan** [comment]
Hey @effeks,

From what I remember the empty stacktrace file is a known problem with recent versions of HHVM. =\

**Comment by effeks** [comment]
@jazzdan bummer! =/
