### ISSUE TITLE
Curl Connection Pooling in HHVM

### ISSUE THREAD

**Issue by trivedipankaj** [facebook/hhvm#6406]
Hi 

Is there a way to do connection pooling for curl in HACK?

**Comment by JoelMarcey** [comment]
You mean something like `HH\Asio\curl_exec()`? (basically asynchronous curl)

**Comment by trivedipankaj** [comment]
No, I am talking about a connection pool, where connections to the remote server are created and maintained so that we can avoid connection creation at the run time. Connections are used from the pool and returned to the pool once communication is over.

**Comment by JoelMarcey** [comment]
cc @fredemmott 

I know we have something similar for MySQL....

**Comment by fredemmott** [comment]
Looks like we do:

 http://hhvm-hack-docs-prod.elasticbeanstalk.com/hack/reference/function/curl_init_pooled/
