### ISSUE TITLE
Support for late static binding

### ISSUE THREAD

**Issue by tslettebo** [facebook/hhvm#6421]
The following runs, but fails the typechecker:
```
class Base
{
  public function __construct()
  {
    echo static::value();
  }
}

class Derived extends Base
{
  public static function value(): string { return "Test"; }
}

$test=new Derived();
```
Is there a way to make it pass the typechecker?

**Comment by nebez** [comment]
It fails with good reason. `Base` should have a static function `value()` defined in its interface.
If a child of `Base` hasn't defined `value()`, this will lead to a runtime error when that child is constructed.
It makes sense to me that the typechecker catches this beforehand.

**Comment by paulbiss** [comment]
Yeah, it sounds like what you want here is an abstract base that requires derived classes to define value().

**Comment by tslettebo** [comment]
Hi @nebez and @paulbiss 

These are "enum" classes. The reason we're not using Hack's own suppoty for enums is to able to write these somewhat shorter, and not having to name each value.

To take the example in the Hack [documentation](http://docs.hhvm.com/manual/en/hack.enums.php), we have a Weekday class which is defined like this:
```
final class Weekday extends Enum_<int>
{
  public static function values(): array<int>
  {
    return [,2,3,4,5,6,7];
  }
}
```
Here's the base class:
```
abstract class Enum_<T> extends ImmutableValue<T>
{
  public function __construct(T $value)
  {
    if(!in_array($value,static::values()))
      throw new Exception(...);

    parent::__construct($value);
  }
}
```
Note that the values() method in the subclass is static, and this relies on late static binding to work, which actually works, but doesn't work with the typechecker.

I guess in order to get it to work with the typechecker, we need to use a non-static values() method in the base and derived class, as you suggested.

> It fails with good reason.  Base  should have a static function  value()  defined in its interface.
> If a child of  Base  hasn't defined  value() , this will lead to a runtime error when that child is constructed.
> It makes sense to me that the typechecker catches this beforehand.

Would it help for Base to have a static values() function defined in its interface? After all, this is not a polymorphic method, so any corresponding static method in a derived class won't override it, only hide it.

It seems to me that defining a static values() method in the Base class will simply make it pass the typechecker, but won't detect a missing values() method in a derived class, and at most will only fail at runtime (if the base class method throws).

**Comment by simonwelsh** [comment]
@tslettebo Looks like you want `abstract public static function values(): array<T>;` in `Enum_<T>`. Will appease the type checker and still complain if you define a concrete subclass of `Enum_` without also defining the `values` method.

**Comment by tslettebo** [comment]
@simonwelsh: That works, thanks.
