### ISSUE TITLE
Curl version error upon upgrade through package manager

### ISSUE THREAD

**Issue by knoxcard** [facebook/hhvm#6425]
hhvm: /usr/local/lib/libcurl.so.4: no version information available (required by hhvm

I am getting this error when I run hhvm from the command line.  Happened after I ran 
apt-get update
apt-get upgrade

**Comment by J0WI** [comment]
Can you give us more information about your system and used sources?

**Comment by jwatzman** [comment]
In particular, the output of the following is useful:

```
uname -a
cat /etc/issue
cat /etc/apt/sources.list
cat /etc/apt/sources.list.d/*
```

**Comment by knoxcard** [comment]
uname -a
*Linux indoworld 4.1.5-x86_64-linode61 #7 SMP Mon Aug 24 13:46:31 EDT 
2015 x86_64 GNU/Linux**
*

|cat /etc/apt/sources.list|

*# deb cdrom:[Debian GNU/Linux 7.4.0 _Wheezy_ - Official amd64 NETINST 
Binary-1 20140208-13:45]/ wheezy main**
**
**#deb cdrom:[Debian GNU/Linux 7.4.0 _Wheezy_ - Official amd64 NETINST 
Binary-1 20140208-13:45]/ wheezy main**
**
**deb http://mirrors.linode.com/debian/ wheezy main**
**deb-src http://mirrors.linode.com/debian/ wheezy main**
**
**deb http://security.debian.org/ wheezy/updates main**
**deb-src http://security.debian.org/ wheezy/updates main**
**
**# wheezy-updates, previously known as 'volatile'**
**deb http://mirrors.linode.com/debian/ wheezy-updates main**
**deb-src http://mirrors.linode.com/debian/ wheezy-updates main*

cat /etc/apt/sources.list.d/*
*deb http://dl.hhvm.com/debian wheezy main**
*

**Comment by jwatzman** [comment]
- OK, you're consistently using the wheezy version of everything, good.
- Do you have some extra curl in `/usr/local/lib` or something? No idea where that's coming from.
- The HHVM you're using is installed from our packages, not built from source, right?
- Can you paste the output of these commands:

```
which hhvm
ldd `which hhvm`
```

**Comment by knoxcard** [comment]
*which hhvm
*/usr/bin/hhvm*
*
*ldd `which hhvm`*
/usr/bin/hhvm: /usr/local/lib/libcurl.so.4: no version information 
available (re quired by /usr/bin/hhvm)
         linux-vdso.so.1 =>  (0x00007ffccb88c000)
         libyaml-0.so.2 => /usr/lib/x86_64-linux-gnu/libyaml-0.so.2 
(0x00007f9bcf 622000)
         libmemcached.so.10 => 
/usr/lib/x86_64-linux-gnu/libmemcached.so.10 (0x00 007f9bcf3ec000)
         libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0 
(0x00007f9bcf1db000 )
         libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 
(0x00007f9bcef6c0 00)
         libldap_r-2.4.so.2 => 
/usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2 (0x00 007f9bced1b000)
         libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 
(0x00007f9bceaf0000 )
         libmcrypt.so.4 => /usr/lib/libmcrypt.so.4 (0x00007f9bce8be000)
         libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 
(0x00007f 9bce61f000)
         libjpeg.so.8 => /usr/lib/x86_64-linux-gnu/libjpeg.so.8 
(0x00007f9bce3e40 00)
         libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 
(0x00007f9bce1bd000 )
         libxslt.so.1 => /usr/lib/x86_64-linux-gnu/libxslt.so.1 
(0x00007f9bcdf7f0 00)
         libexslt.so.0 => /usr/lib/x86_64-linux-gnu/libexslt.so.0 
(0x00007f9bcdd6 9000)
         libMagickWand.so.5 => 
/usr/lib/x86_64-linux-gnu/libMagickWand.so.5 (0x00 007f9bcda4f000)
         libMagickCore.so.5 => 
/usr/lib/x86_64-linux-gnu/libMagickCore.so.5 (0x00 007f9bcd5a3000)
         libc-client.so.2007e => /usr/lib/libc-client.so.2007e 
(0x00007f9bcd28e00 0)
         liblber-2.4.so.2 => /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2 
(0x00007f 9bcd07f000)
         libonig.so.2 => /usr/lib/libonig.so.2 (0x00007f9bcce19000)
         libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f9bccc14000)
         libicudata.so.48 => /usr/lib/x86_64-linux-gnu/libicudata.so.48 
(0x00007f 9bcb8a4000)
         libicui18n.so.48 => /usr/lib/x86_64-linux-gnu/libicui18n.so.48 
(0x00007f 9bcb4d9000)
         libicuuc.so.48 => /usr/lib/x86_64-linux-gnu/libicuuc.so.48 
(0x00007f9bcb 169000)
         libcurl.so.4 => /usr/local/lib/libcurl.so.4 (0x00007f9bcaf07000)
         libcap.so.2 => /lib/x86_64-linux-gnu/libcap.so.2 
(0x00007f9bcad03000)
         libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 
(0x00007f9bcaaec0 00)
         libtbb.so.2 => /usr/lib/libtbb.so.2 (0x00007f9bca8be000)
         libxml2.so.2 => /usr/lib/x86_64-linux-gnu/libxml2.so.2 
(0x00007f9bca55e0 00)
         libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 
(0x00007f9bca326000 )
         librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f9bca11e000)
         libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f9bc9f07000)
         libevent-2.0.so.5 => 
/usr/lib/x86_64-linux-gnu/libevent-2.0.so.5 (0x0000 7f9bc9cbe000)
         libreadline.so.6 => /lib/x86_64-linux-gnu/libreadline.so.6 
(0x00007f9bc9 a77000)
         libelf.so.1 => /usr/lib/libelf.so.1 (0x00007f9bc9862000)
         libssl.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0 
(0x00007f9b c9600000)
         libcrypto.so.1.0.0 => 
/usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00 007f9bc9208000)
         libjemalloc.so.1 => /usr/lib/hhvm/libjemalloc.so.1 
(0x00007f9bc8fc0000)
         libglog.so.0 => /usr/lib/hhvm/libglog.so.0 (0x00007f9bc8d90000)
         libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 
(0x00007f9bc8b7 4000)
         libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f9bc88f2000)
         libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9bc8566000)
         /lib64/ld-linux-x86-64.so.2 (0x000055add425d000)
         libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 
(0x00007f9bc8 25f000)
         libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 
(0x00007f9bc8049000 )
         libsasl2.so.2 => /usr/lib/x86_64-linux-gnu/libsasl2.so.2 
(0x00007f9bc7e2 d000)
         libgnutls.so.26 => /usr/lib/x86_64-linux-gnu/libgnutls.so.26 
(0x00007f9b c7b6d000)
         libgcrypt.so.11 => /lib/x86_64-linux-gnu/libgcrypt.so.11 
(0x00007f9bc78e e000)
         liblcms2.so.2 => /usr/lib/x86_64-linux-gnu/liblcms2.so.2 
(0x00007f9bc76a 0000)
         libtiff.so.4 => /usr/lib/x86_64-linux-gnu/libtiff.so.4 
(0x00007f9bc743a0 00)
         liblqr-1.so.0 => /usr/lib/x86_64-linux-gnu/liblqr-1.so.0 
(0x00007f9bc722 3000)
         libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 
(0x00007f9bc6 f2a000)
         libfontconfig.so.1 => 
/usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00 007f9bc6cf3000)
         libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 
(0x00007f9bc6ae10 00)
         libXt.so.6 => /usr/lib/x86_64-linux-gnu/libXt.so.6 
(0x00007f9bc6879000)
         liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 
(0x00007f9bc6656000)
         libltdl.so.7 => /usr/lib/x86_64-linux-gnu/libltdl.so.7 
(0x00007f9bc644d0 00)
         libSM.so.6 => /usr/lib/x86_64-linux-gnu/libSM.so.6 
(0x00007f9bc6245000)
         libICE.so.6 => /usr/lib/x86_64-linux-gnu/libICE.so.6 
(0x00007f9bc602a000 )
         libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 
(0x00007f9bc5cef000 )
         libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 
(0x00007f9bc5ae00 00)
         libpam.so.0 => /lib/x86_64-linux-gnu/libpam.so.0 
(0x00007f9bc58d2000)
         libgssapi_krb5.so.2 => 
/usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x 00007f9bc5692000)
         libkrb5.so.3 => /usr/lib/x86_64-linux-gnu/libkrb5.so.3 
(0x00007f9bc53be0 00)
         libk5crypto.so.3 => /usr/lib/x86_64-linux-gnu/libk5crypto.so.3 
(0x00007f 9bc5195000)
         libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 
(0x00007f9bc4f9 0000)
         libattr.so.1 => /lib/x86_64-linux-gnu/libattr.so.1 
(0x00007f9bc4d8b000)
         libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 
(0x00007f9bc4b61000 )
         libunwind.so.7 => /usr/lib/libunwind.so.7 (0x00007f9bc4948000)
         libtasn1.so.3 => /usr/lib/x86_64-linux-gnu/libtasn1.so.3 
(0x00007f9bc473 6000)
         libp11-kit.so.0 => /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 
(0x00007f9b c4524000)
         libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 
(0x00007f9b c4321000)
         libjbig.so.0 => /usr/lib/x86_64-linux-gnu/libjbig.so.0 
(0x00007f9bc41120 00)
         libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 
(0x00007f9bc3ed5000)
         libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 
(0x00007f9bc3ccf000)
         libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 
(0x00007f9bc3aaf000 )
         libkrb5support.so.0 => 
/usr/lib/x86_64-linux-gnu/libkrb5support.so.0 (0x 00007f9bc38a6000)
         libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 
(0x00007f9bc3 6a1000)
         libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 
(0x00007f9bc349e000 )
         libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 
(0x00007f9bc329 8000)

**Comment by jwatzman** [comment]
`libcurl.so.4 => /usr/local/lib/libcurl.so.4 (0x00007f9bcaf07000)`

I think you have a rouge, broken libcurl. Can you move `/usr/local/lib/libcurl.so.4` out of the way and see if that fixes it? This wasn't installed by the system, and so must be locally installed.

**Comment by knoxcard** [comment]
So should I just rename the file?  Is that what you a referring to by "moving it out of the way"?

**Comment by jwatzman** [comment]
Yeah, rename it to something like `libcurl.DISABLED` or something like that, so that the linker won't find it.

**Comment by knoxcard** [comment]
Thanks, that seems to have done the trick!

**Comment by knoxcard** [comment]
i removed the symlink entirely by running ... "unlink <symlink>"

**Comment by jwatzman** [comment]
Glad we got it sorted out.

**Comment by chenyachao** [comment]
Thanks. I have solved the problem too. ^_^

**Comment by zhaoj8333** [comment]
I've solved this issue too :+1:
