### ISSUE TITLE
Provide a secure connection (https) to hhvm.com

### ISSUE THREAD

**Issue by J0WI** [facebook/hhvm#6427]
Let's encrypt the web and make it more secure

**Comment by Orvid** [comment]
I'm going to be the odd one here and say it doesn't need it. There's no direct downloads on it, and it only provides information. This is just me being odd, so feel free to ignore it :D

**Comment by war59312** [comment]
Web by default is going secure. As it should be. No GOOD excuse not too anymore.

Even more so now that certs are free thanks to https://letsencrypt.org/ .

**Comment by Orvid** [comment]
Free certs have been available for many years now, but there are many downsides from a network perspective to using secure connections for things that really don't need it.

**Comment by J0WI** [comment]
This is just about providing https, not to force it. You are free to continue using http.

Of course there are free certs available, but I don't think that Facebook care about these costs.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Visiting hhvm.com in 2020, https://hhvm.com and http://hhvm.com redirects to the https version.
