### ISSUE TITLE
Hack's type checker fails to report type mismatch in strict mode

### ISSUE THREAD

**Issue by pbl64k** [facebook/hhvm#6428]
Public gist:

https://gist.github.com/pbl64k/78c01eb7a35f1ccc9b59

The return type of lambda in https://gist.github.com/pbl64k/78c01eb7a35f1ccc9b59#file-tc-bug2-minimal-hh-L269 (`Stream::takeIncorrect`) is incorrect (compare `Stream::take` above: https://gist.github.com/pbl64k/78c01eb7a35f1ccc9b59#file-tc-bug2-minimal-hh-L255) -- the rhs should be `OptionalT<Tuple2T<int, Tuple2T<int, Stream<Tp, Tt>>>>`, while here it is `OptionalT<Tuple2T<int, Tuple2T<int, LazyT<Stream<Tp, Tt>>>>>`.

Type checker reports no errors:

```
lepin@xub:~/Sandbox/hack/hack-playground$ hh_client 
No errors!
lepin@xub:~/Sandbox/hack/hack-playground$ hhvm tc-bug2-minimal-runme.hh 
Element: 1
Element: 2
Element: 3
Element: 4
Element: 5
Element: 6
Element: 7
Element: 8
Element: 9
Element: 10
End of stream.
Element: 1
End of stream.
lepin@xub:~/Sandbox/hack/hack-playground$ hhvm --version
HipHop VM 3.9.1 (rel)
Compiler: tags/HHVM-3.9.1-0-g0f72cfc2f0a01fdfeb72fbcfeb247b72998a66db
Repo schema: 6416960c150a4a4726fda74b659105ded8819d9c
```

**Comment by SiebelsTim** [comment]
Okay wow, that is a huge block of code. Couldn't you minimize the reproduction case?

**Comment by pbl64k** [comment]
I'll try to cut this down further, but this is already a significant reduction from the case where I run into this. All the interfaces and methods that are not involved in the implementation of the faulty method are stripped. I'll see what I can do, but I expect there to be a lot of trial and error to see which transformations  preserve the bug and which don't.

**Comment by pbl64k** [comment]
Okay, I cut down some of the fat. Better yet, this now fails at runtime due to a call to `match` on `Lazy`.

https://gist.github.com/pbl64k/5a311319d191ffb8c1fb

The line that causes the problem:

https://gist.github.com/pbl64k/5a311319d191ffb8c1fb#file-tc-bug2-minimal-hh-L100

Compare with the correct version:

https://gist.github.com/pbl64k/5a311319d191ffb8c1fb#file-tc-bug2-minimal-hh-L86

Console output:

    lepin@xub:~/Sandbox/hack/hack-playground$ hh_client 
    No errors!
    lepin@xub:~/Sandbox/hack/hack-playground$ hhvm tc-bug2-minimal-runme.hh 
    Element: 1
    Element: 2
    Element: 3
    Element: 4
    Element: 5
    Element: 6
    Element: 7
    Element: 8
    Element: 9
    Element: 10
    End of stream.
    Element: 1
    
    Fatal error: Call to undefined method Lazy::match() in /home/lepin/Sandbox/hack/hack-playground/tc-bug2-minimal.hh on line 100

**Comment by jwatzman** [comment]
@dlreeves @dabek or @int3 can you take a look at this?

**Comment by dlreeves** [comment]
We have known issues with inferring the types of lambda expressions. I remember @int3 looked into it a while ago, but we should take a look and at least emit an error asking for the lambda to be explicitly typed. Thanks for the repro

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Your repro reports a type error in the exact place you commented one should appear. The comment explaining which typeerror you'd expect matches the actual type error very well.

```HACK
// snip...
$xs->match(
        () ==> Optional::none(),
        // cf. take() above: $xs is of type Lazy<Stream<Tp, Tt>>, while a Stream<Tp, Tt> should be expected here
        ($x, $xs) ==>
            Optional::some(Tuple2::make($x, Tuple2::make($n - 1, $xs))),
    ),
```

```
Typing[4110] Invalid argument
   --> file.hack
216 |         (function(Tt, LazyT<Stream<Tp, Tt>>): Tv) $ifStream,
    |                       ^^^^^^^^^^^^^^^^^^^^^ But got Lazy<LazyPrx, Stream<Tp, Tt>>
273 |                             Tuple2::make($x, Tuple2::make($n - 1, $xs)),
    |                                                                   ^^^
277 |             Tuple2::make($n, $this),
    |                              ^^^^^ Expected Stream<Tp, Tt>

1 error found.
```
