### ISSUE TITLE
HHVM fails to compile when cmake 3.2.1 is used

### ISSUE THREAD

**Issue by diannne** [facebook/hhvm#6430]
Compiling hhvm with CMake 3.2.1 outputs error: 

CMake Error at CMakeLists.txt:171 (INCLUDE):
  include could not find load file:

    rocksdb

Dynamic plugins are disabled.
make[2]: *** [third-party/webscalesqlclient/build/src/webscalesqlclient-stamp/webscalesqlclient-configure] Error 1
make[1]: *** [third-party/webscalesqlclient/CMakeFiles/webscalesqlclient.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

You can see more about running context in the email report from:
https://lists.01.org/pipermail/langperf/2015-October/000226.html

**Comment by JoelMarcey** [comment]
@diannne Hi! If you rebase to the latest and possibly do this: 

https://twitter.com/HipHopVM/status/659130582010564609

this problem should be fixed. 

Let us know if it is not. Thanks!
