### ISSUE TITLE
HHVM Compile error

### ISSUE THREAD

**Issue by diannne** [facebook/hhvm#6431]
HHVM compilation fails with error:
http://pastebin.com/Mmy9SctF

Offending commit seems to be d0d8fd9

You can see more about running context at:
https://lists.01.org/pipermail/langperf/2015-October/000226.html

**Comment by yaslama** [comment]
A simple fix is to replace in the line 50 of hphp/runtime/base/tv-helpers.h
```
reinterpret_cast<HPHP::HeaderWord<uint16_t, true>*>(           \
```
by
```
reinterpret_cast<HPHP::HeaderWord<uint16_t, HPHP::Counted::Always>*>(           \
```

**Comment by yaslama** [comment]
In fact per  8e526a49ee true needs to be replaced by HPHP::Counted::Maybe

**Comment by JoelMarcey** [comment]
@diannne Hi. @yaslama is correct. If you rebase to the latest, you should be able to compile now. Please reopen if you cannot.
