### ISSUE TITLE
Implement ldap_modify_batch() and LDAP_MODIFY_BATCH_* constants

### ISSUE THREAD

**Issue by sgolemon** [facebook/hhvm#6432]
Noticed these were missing while migrating things out of constants.idl.json

I don't know if anyone is asking for them yet, but it's a nice easy project to pick up if someone wants to make a pull request.

**Comment by apeabody** [comment]
Hey @Orvid - looks like this was resolved in #6826, but it didn't include the keyword to close this issue.
