### ISSUE TITLE
Missing function 'convert.quoted-printable-encode'

### ISSUE THREAD

**Issue by aseering** [facebook/hhvm#6440]
I'm trying to run AfterLogic WebMail Lite under HHVM.  When trying to send an e-mail, I see the following in my logs:

```
./data/logs/log-2015-10-29.txt:[23:33:12.68][3adc41ff] PHP[NOTICE]: Error: stream_filter_append(): unable to locate filter "convert.quoted-printable-encode"
```

Despite the hhvm docs, it appears that this function is not available.

I'm running the following hhvm binary release:

```
$ hhvm --version
HipHop VM 3.10.1 (rel)
Compiler: tags/HHVM-3.10.1-0-g689b4969a141620ee5a282ce0dbf72278c84d44b
Repo schema: 6c99ee1f98340f6f3ef397a332583f0e843a627d
```

The same issue seems to have been hit here:  [https://github.com/RainLoop/rainloop-webmail/issues/634](https://github.com/RainLoop/rainloop-webmail/issues/634)

It looks, at a quick glance, like some other functions in this suite are missing as well.

**Comment by jesseschalken** [comment]
@aseering https://github.com/facebook/hhvm/commit/70441c3de6e0e6af51b45cc9241c5b60a2269fac supposedly adds support for `convert.quoted-printable-encode`.

Is this still an issue? Do you have a snippet of code it can be tested with?

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

`convert.quoted-printable-encode` is a stream filter, as far as I found when searching the PHP manual.
This requires functions like `\stream_filter_append()` or friends, which were removed from hhvm.

Tested on hhvm 4.56.
```
hphpd> =\stream_filter_append();
=\stream_filter_append();
Hit a php exception : Error: Call to undefined function stream_filter_append() in :1
Stack trace:
#0 (1): include()
#1 {main}
```
