### ISSUE TITLE
ocamlc.opt errors when compiling master branch on AARCH64

### ISSUE THREAD

**Issue by sskblr** [facebook/hhvm#6442]
I see the following compile errors when compiling master branch on AARCH64 (Ubuntu 14.10):

-------8<------------------------
Finished, 11 targets (11 cached) in 00:00:01.
+ /root/hhvm_aarch64_github/local/bin/ocamlc.opt -c -g -w A -warn-error A -w -3-27 -w -4-6-29-35-44-48 -I utils -I globals -I heap -I client -I format -I fsnotify_linux -I server -I typing -I socket -I procs -I stubs -I parsing -I naming -I deps -I emitter -I h2tp -I search -I dfind -I hh_matcher -I hhi -I third-party/core -I third-party/inotify -I third-party/avl -I h2tp/unparser -I h2tp/test -I h2tp/mapper -I h2tp/common -I hh_matcher/test -o utils/exit_status.cmo utils/exit_status.ml
File "utils/exit_status.ml", line 37, characters 6-8:
Warning 41: Ok belongs to several types: t result
The first one was selected. Please disambiguate if this is wrong.
File "utils/exit_status.ml", line 61, characters 4-6:
Warning 41: Ok belongs to several types: t result
The first one was selected. Please disambiguate if this is wrong.
File "utils/exit_status.ml", line 1:
Error: Some fatal warnings were triggered (2 occurrences)
Command exited with code 2.
Compilation unsuccessful after building 118 targets (117 cached) in 00:00:06.
make[4]: *** [_build/hh_server.native] Error 10
make[3]: *** [hphp/hack/CMakeFiles/hack] Error 2
make[2]: *** [hphp/hack/CMakeFiles/hack.dir/all] Error 2
make[1]: *** [hphp/hack/CMakeFiles/hack.dir/rule] Error 2
make: *** [hack] Error 2
--------------------8<----------------------------

Thanks,
-sk

**Comment by Orvid** [comment]
Is this still the case?

**Comment by lbianc** [comment]
I got the same issue after update my fork yesterday (building in PPC64). Any solution for that?

**Comment by Orvid** [comment]
As a temporary solution, you should be able to disable the warning.
