### ISSUE TITLE
hphp/test/slow/lang/reflection.php.hphp_opts is a broken symlink

### ISSUE THREAD

**Issue by Tyrael** [facebook/hhvm#6443]
hphp/test/slow/lang/reflection.php.hphp_opts is a symlink to hphp_opts.optimization_level_0 but there is no hphp_opts.optimization_level_0 in hphp/test/slow/lang/
81534fea0e710a5b5cadb682b2c207330c93b01e moved reflection.php.hphp_opts from hphp/test/quick/ to hphp/test/slow/lang but the link target wasn not moved/copied nor updated to point to the original file.

**Comment by Orvid** [comment]
Diff up internally to fix this.
