### ISSUE TITLE
xdebug_server.cpp XDEBUG_SESSION_START doesn't work

### ISSUE THREAD

**Issue by sandman7920** [facebook/hhvm#6449]
During

``` C++
// hphp/runtime/ext/xdebug/xdebug_server.cpp(373)
static void HPHP::XDebugServer::onRequestInit()
```

Globals are not populated "get_global_variables()" returns empty values

However during

``` C++
// hphp/runtime/ext/xdebug/xdebug_server.cpp(433)
static bool HPHP::XDebugServer::isNeeded()
```

Values are populated

Tested on HHVM-3.10.1

Log

static void HPHP::XDebugServer::onRequestInit()
/root/dev/hhvm3/hphp/runtime/ext/xdebug/xdebug_server.cpp(373)

HTTP_RAW_POST_DATA (Null 0x0)
_REQUEST (Array 0x34c9670)
   empty
_COOKIE (Array 0x34c9670)
   empty
argv (Null 0x0)
_SERVER (Array 0x34c9670)
   empty
_POST (Array 0x34c9670)
   empty
_GET (Array 0x34c9670)
   empty
argc (Null 0x0)
GLOBALS (Array 0x7fc461889040)
_SESSION (Array 0x34c9670)
   empty
_FILES (Array 0x34c9670)
   empty

static bool HPHP::XDebugServer::isNeeded()
/root/dev/hhvm3/hphp/runtime/ext/xdebug/xdebug_server.cpp(433)

HTTP_RAW_POST_DATA (Null 0x0)
_REQUEST (Array 0x7fc46188fc80)
_COOKIE (Array 0x34c9670)
   empty
argv (Null 0x0)
_SERVER (Array 0x7fc461894940)
_POST (Array 0x34c9670)
   empty
_GET (Array 0x7fc46188fc00)
   _GET[XDEBUG_SESSION_START] = netbeans-xdebug
   _GET[test1] = a
   _GET[test2] = b
argc (Null 0x0)
GLOBALS (Array 0x7fc461889040)
_FILES (Array 0x34c9670)
   empty

**Comment by lhorace** [comment]
This is fixed? or does the source code have to be modified to make this work?

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This issue depends on XDebug, which was removed from hhvm in version [3.27.0](https://hhvm.com/blog/2018/06/18/hhvm-3.27.0.html).
