### ISSUE TITLE
 Eclipse HHVM/XDebug connection stuck at 78%: “Waiting for XDebug session…”

### ISSUE THREAD

**Issue by oxwivi** [facebook/hhvm#6450]
The following is copypasta from my question on [Unix.SE](http://unix.stackexchange.com/q/239742/8305):

 > I've setup a LEMH stack for development purposes in a LXD container, configured as described in [this answer](http://unix.stackexchange.com/a/239263/8305) with [sockets](http://unix.stackexchange.com/a/239595/8305) for HHVM. (Huge thanks to @mef for both) And the configuration worked (and still works) flawlessly. ([Except for HHVM just going jealous and hogging all the processor core to itself and unresponsive for a period of time every now and then](https://github.com/facebook/hhvm/issues/5081); but that's a different matter)

 > Since HHVM does support XDebug, I wanted to configure Eclipse's PDT plugin to take advantage of it, and enabled it:

 >     $ less /etc/hhvm/php.ini
 >     xdebug.enable = 1
 >     xdebug.remote_enable = 1
 >     xdebug.remote_connect_back = 1

 > Since I've configured nginx/HHVM sockets and since Eclipse is running on the host, not the LEMH container, there is no chance of port conflicts and I've left it to default `9000`.

 > [![Eclipse XDebug global settings][1]][1]

 > I've configured Eclipse XDebug client as above, basically leaving everything their default values, and the internal browser works since I've installed `libwebkitgtk-1.0-0`. But this is the result:

 > [![enter image description here][2]][2]

 > I've confirmed, using `telnet`, that the `9000` port is open on the host running Eclipse, and I've tried to `strace -p [pid]` HHVM but I'm unfamiliar with it. There's no output for it other than it `attached`, even with opening PHP pages normally. I've tried with other PHP files with the same result.

 > I've changed the remote port settings on both Eclipse and HHVM for the heck of it:

 >     xdebug.remote_port = 9001

 > But of course that made no difference.

Version details I forgot to provide in the question:

    $ nginx -v
    nginx version: nginx/1.9.5
    $ hhvm --version
    HipHop VM 3.10.1 (rel)
    Compiler: tags/HHVM-3.10.1-0-g689b4969a141620ee5a282ce0dbf72278c84d44b
    Repo schema: 6c99ee1f98340f6f3ef397a332583f0e843a627d

Please help me with this!

  [1]: http://i.stack.imgur.com/MQ1kb.png
  [2]: http://i.stack.imgur.com/zBNK5.png

**Comment by sandman7920** [comment]
add
xdebug.idekey=ECLIPSE_DBGP
xdebug.remote_autostart=1

**Comment by sandman7920** [comment]
and maybe
xdebug.remote_host = YOUR_IP_ADDRESS

**Comment by oxwivi** [comment]
It's working now, thanks @sandman7920! But why does the `remote_autostart` need to be manually set, why not default? And what exactly is `idekey`? Does that mean only one IDE can be used with XDebug at a time?

`remote_host`, according to the original XDebug implementation docs, will be overridden if `connect_back` is defined. Don't know about HHVM's implementation, but it's working.

**Comment by sandman7920** [comment]
Your initial configuration was correct, but there's a bug in HHVM that doesn't populate server globals during xdebug initialization.

**Comment by oxwivi** [comment]
That explains `autostart`, but I needed both `autostart` and `ide` for XDebug plus the initial config to finally work.

**Comment by sandman7920** [comment]
In default php implementation if xdebug.idekey is not set it's extracted from XDEBUG_SESSION_START=(ECLIPSE_DBGP,netbeans-xdebug,etc), but again globals are not populated during initialization (_GET,_POST,_REQUEST).
Take a look on the issue that i posted just before yours
xdebug_server.cpp XDEBUG_SESSION_START doesn't work https://github.com/facebook/hhvm/issues/6449

**Comment by sandman7920** [comment]
If you don't want  xdebug.remote_autostart=1 (always start xdebug) add/delete cookie XDEBUG_SESSION=ECLIPSE_DBGP this will trick HHVM server but noting can be done for  xdebug.idekey (at least don't known any workaround. I tried SetEnv XDEBUG_CONFIG="idekey=abcd" per virtual host but....)

**Comment by sandman7920** [comment]
```C++
// Environment variables the idekey is grabbed from
const StaticString
  s_DBGP_IDEKEY("DBGP_IDEKEY"),
  s_USER("USER"),
  s_USERNAME("USERNAME");

// Attempts to load the default idekey from environment variables
static void loadIdeKey(std::map<std::string, std::string>& envCfg) {
  auto const dbgp_idekey = g_context->getenv(s_DBGP_IDEKEY);
  if (!dbgp_idekey.empty()) {
    envCfg["idekey"] = dbgp_idekey.toCppString();
    return;
  }

  auto const user = g_context->getenv(s_USER);
  if (!user.empty()) {
    envCfg["idekey"] = user.toCppString();
    return;
  }

  auto const username = g_context->getenv(s_USERNAME);
  if (!username.empty()) {
    envCfg["idekey"] = username.toCppString();
  }
}

// Environment variable that can be used for certain settings
const StaticString s_XDEBUG_CONFIG("XDEBUG_CONFIG");

// Loads the "XDEBUG_CONFIG" environment variables.
static void loadEnvConfig(std::map<std::string, std::string>& envCfg) {
  auto const cfg_raw = g_context->getenv(s_XDEBUG_CONFIG);
  if (cfg_raw.empty()) {
    return;
  }

  // Parse the config variable. Format is "key=val" list separated by spaces
  // This parsing isn't very efficient, but this isn't performance sensitive and
  // it's similar to what php5 xdebug does.
  auto cfg = StringUtil::Explode(cfg_raw, " ").toArray();
  for (ArrayIter iter(cfg); iter; ++iter) {
    auto keyval = StringUtil::Explode(iter.second().toString(), "=").toArray();
    if (keyval.size() != 2) {
      continue;
    }

    auto key = keyval[0].toString().toCppString();
    auto val = keyval[1].toString().toCppString();
    if (key == "remote_enable" ||
        key == "remote_port" ||
        key == "remote_host" ||
        key == "remote_handler" ||
        key == "remote_mode" ||
        key == "idekey" ||
        key == "profiler_enable" ||
        key == "profiler_output_dir" ||
        key == "profiler_enable_trigger" ||
        key == "remote_log" ||
        key == "remote_cookie_expire_time" ||
        key == "cli_color") {
      envCfg[key] = val;
    }
  }
}
```

**Comment by oxwivi** [comment]
Thanks for all the clarifications, @sandman7920. I'm closing the issue now.

**Comment by oxwivi** [comment]
Well now, unfortunately, it seems I've to repoen the issue.

Additionally configuring HHVM as @sandman7920 suggests finally allows proper functioning of XDebug, but the `autostart` means files not part of an Eclipse project will trigger XDebug and contact Eclipse which will, of course, be always listening. Since Eclipse doesn't recognize the file, it'll always bother me with a dialog box: "No appropriate file located or no file selected. Debug Terminated"

Other than the project I'm developing, I also have phpMyAdmin on the server, so whenever I do anything in it, Eclipse will react for every PHP files that is handled by HHVM. Frankly, this is ridiculous and annoying.

**Comment by lhorace** [comment]
@oxwivi Looks like, it would probably be best to create ie. include/xdebug.php (put your checks and set cookie there), and include that file from every file you are debuging.

@sandman7920 Am I understanding this correctly; No Global variables are set due to this bug #6449 ? Soooo I can't do something like if ($_GET['start_xdebug'] == true) { setcookie(); } ?

**Comment by sandman7920** [comment]
I'm using EditThisCookie extention in chrome.

**Comment by Orvid** [comment]
What's the actual issue here?

**Comment by lhorace** [comment]
The issue here is the same in bug #6449 due to a bug in HHVM not populating global variables during Xdebug initialization. For now, I'll debug PHP code in PHP.

**Comment by pavi32** [comment]
please help i have same problem
`[xdebug]
	zend_extension=xdebug.so
	xdebug.enable =1
	xdebug.remote_enable=1
	xdebug.remote_handler=dbgp
	xdebug.remote_mode=req
	xdebug.remote_host=localhost
	xdebug.remote_port=9000
	xdebug.idekey=ECLIPSE_DBGP
	xdebug.remote_autostart=1	
	xdebug.remote_connect_back=1`

that is my php.info code i added for xdebug

![phpinfo](https://cloud.githubusercontent.com/assets/5644696/16379940/a88e0cc0-3c91-11e6-9b73-7b41e5fa8847.png)
that is my php.info

![error](https://cloud.githubusercontent.com/assets/5644696/16379969/d67d8354-3c91-11e6-88b1-f6fa56a6c052.png)
still showing the launching .... what is my mistake

**Comment by Orvid** [comment]
As it's the same issue and the other issue (#6449) has better descriptions of the actual issue, I'm going to close this one for now.
