### ISSUE TITLE
Strict and Safe-Indexing for Hack Arrays

### ISSUE THREAD

**Issue by dlreeves** [facebook/hhvm#6454]
This is a part of the [Hack array proposal](http://hhvm.com/blog/10649/improving-arrays-in-hack)

Indexing for Hack arrays will have stricter semantics when using square brackets to match the behavior of Hack Collections.

### No Coercion of Keys

When indexing or setting a key of an array, PHP sometimes coerces a value to either an `int` or `string`. Hack arrays should not do this. Indexing a Hack array with an invalid key type results in an exception. This also means int-like strings will not be converted to ints.

```hack
// These will result in exceptions for Hack arrays
$harray[0.0];
$harray[false];

// The string '0' will not be converted to the int 0
$harray['0'];
```

### Throw on Non-existent Keys

Accessing an non-existent key for a PHP array results in raising a `E_NOTICE` and returning `null`. Hack arrays will throw an exception if you attempt to access an element that is not present.

### Safe-Indexing

If you do not want to risk an exception being thrown when indexing into a Hack array then you can index using curly braces. Currently indexing with curly braces is the same as indexing with square brackets for PHP arrays. We will slightly change this behavior to return `null` when the key is not set, but NOT raise a `E_NOTICE`.

```hack
$dict = dict[];
$x = $dict{0}; // $x will be null
$y = $dict[0]; // Exception thrown since 0 is not set
```

This is meant to emulate the `get` methods that the various Collection APIs provide.

**Comment by simonwelsh** [comment]
I don't like the differing behaviour between using `[]` and `{}` for access. Looks too much like an accidental typo and requires a different understanding of the symbols (as they're currently equivalent).

How common would using the `{}` syntax be? Is it common enough to need a shorthand for `idx`?

**Comment by deadalnix** [comment]
ditto the {} syntax seems unnecessary. Using idx seems like the right way to get null on missing entry.

**Comment by dlreeves** [comment]
Given the feedback we are going to forgo adding this feature for now. Especially with the `??` operator this seems like it would be a bit redundant.

Thanks for your input
