### ISSUE TITLE
Introduce Expression Pipe Operator

### ISSUE THREAD

**Issue by dlreeves** [facebook/hhvm#6455]
This is a part of the [Hack array proposal](http://hhvm.com/blog/10649/improving-arrays-in-hack)

To put simply, writing in a functional style with arrays can produce some ugly code. Consider this example

```hack
// arrays
count(
  array_filter(
    array_map(
      $x ==> $x->getNumber(),
      array(...),
    ),
    $x ==> is_even($x),
  )
)
```

Since Collections are objects, methods calls can be chained to produce a more fluid interface. Here is the same piece of code written in terms of collections.

```hack
// collections
(Map {...})
  ->map($x ==> $x->getNumber())
  ->filter($x ==> is_even($x))
  ->count()
```

This code is considerably easier to read because the operations are chained one after another. First you map, then you filter, then you count. Functions do not have this property, so any functional API involving arrays will lead to the deep nesting demonstrated earlier. This can be fixed by introducing some sugar syntax borrowed from functional languages such as [F#](https://msdn.microsoft.com/en-us/library/dd233229.aspx#Anchor_11) and OCaml.

```hack
// map -> filter -> count
array(...)
  |> array_map($x ==> $x->getNumber(), $$)
  |> array_filter($$, $x ==> is_even($x))
  |> count($$)
```

The `|>` operator will be known as the **expression pipe operator**. It takes the value on the left of the operator, evaluates it and passes the result into the placeholder on the right of the operator. This is analogous to piping in a Linux command line. The `$$` is the placeholder for where the result of the left expression will be substituted. The beauty of this solution is that it can be transformed trivially to the nested function style by the HHVM compiler, meaning this will have zero runtime impact. 

This can also improve the utility of Collections or other APIs that rely heavily on method chaining. Now static utility methods can be added without breaking the style.

```hack
function compact<T>(Traversable<?T> $vector): Vector<T> {
...
}

// What is happening here?
compact($vec->map($x => $x?->foo()))->count(); 

// Maintain chaining style
$vec
  ->map($x ==> $x?->foo())
  |>compact($$)
  ->count()
```

**Comment by steelbrain** [comment]
IMO the syntax of this is too confusing. It would be nice if you would provide us with an example about how this code is going to be transpiled like
```hack
// Source:
$arr = get_some_array()
  |> do_something($$)
```
```hack
// Output
$arr = do_something(get_some_array());
```

Other questions I have in mind are
  - Does this operator work on the same line? or is a new line a requirement?
  - Can we use this for non-array things?

**Comment by Orvid** [comment]
The syntax of this is, while not quite as clean as [D's Uniform Function Call Syntax (UFCS)](http://dlang.org/function.html#pseudo-member), is far cleaner than the alternative of not having anything. Due to some limitations of UFCS, in particular that the argument that's being chained on (`$$` in this proposal) must be the first parameter, I think this is a better way of doing it.

**Comment by SiebelsTim** [comment]
Either I misunderstood something, or you have a bug in your last example. I assume you didn't want to pass an argument to the `count` method.

**Comment by dlreeves** [comment]
@SiebelsTim  - Thanks. Had it confused with the `count` function

**Comment by Daniel15** [comment]
Why not just use collections?

**Comment by simonwelsh** [comment]
@Daniel15 that's covered in the linked blog post

**Comment by Daniel15** [comment]
Thanks, somehow I totally missed that link.

**Comment by mglinski** [comment]
Damn, having a expression-pipe operator would be soooooo nice in vanilla php. Once you get this implemented, you should put in a RFC to add it for 7.x.

**Comment by paulbiss** [comment]
This is done on the hhvm side (992c816e19428ad3bae026702a0755827a3cba9c), I think we're still missing hack support. cc @dlreeves

**Comment by dlreeves** [comment]
Yep we are currently working on adding the type checker support. Initially we won't have support for this in h2tp (the dehackificator) because the transformation we do in the runtime is a bit more complicated than I presented in the original issue. Namely we cannot simply de-nest the operator into nested function calls because of potential side effects. Instead we create temporary variables to store the result of the left operand.

If there is demand for support of the future for h2tp I think the simplest way to do the transpile is nested closures, i.e.

```hack
1 |> $$ + $$
```

Could be translated to

```php
(function($x) {
  return $x + $x
})(1)
```

**Comment by dlreeves** [comment]
The type checker support for this feature has now landed. Please play around with it and report any issues you run into

**Comment by beerendlauwers** [comment]
@dlreeves Is there support for this in `h2tp` ?

**Comment by SiebelsTim** [comment]
@beerendlauwers h2tp is not supported anymore. And development stopped some time ago. This feature is not supported.

    Internal Error:
    error unparsing /var/www/test/test.hh. unsupported construct in Unparser:  Dollardollar

**Comment by beerendlauwers** [comment]
@SiebelsTim That's a shame. Any reason why `h2tp` is no longer being developed?

**Comment by SiebelsTim** [comment]
@beerendlauwers See https://www.facebook.com/groups/hhvm.general/permalink/803847413101987/
The infrastructure around it was removed, however a replacement is on the way. A replacement for h2tp however is not yet confirmed.

**Comment by beerendlauwers** [comment]
@SiebelsTim Ok, thank you for the clarification. I have to work with Drupal codebases that cannot be hosted on HHVM-capable servers, so `h2tp` seemed the perfect solution to be able to use Hack. I will look into static analysis tools for PHP 5 / 7, and I'll probably write a simple preprocessor myself to get some nicer syntax.
