### ISSUE TITLE
HHVM socket is gone with 3.10 on Ubuntu

### ISSUE THREAD

**Issue by J0WI** [facebook/hhvm#6458]
Since HHVM 3.10.0 ```hhvm.server.file_socket=/var/run/hhvm/hhvm.sock``` seems to be broken.
There is no hhvm.sock created, neither in /var/run nor anywhere else.

I'm using Ubuntu 15.04 and HHVM 3.10.1
Sadly I didn't find an easy way to downgrade HHVM, so I can't confirm the regression for sure.

**Comment by simonwelsh** [comment]
If you use a user/group other than www-data/www-data for HHVM, you'll need to run `chown` on the `/var/run/hhvm/` folder.

**Comment by J0WI** [comment]
It's running as ```www-data``` and everything worked well with 3.9.x

**Comment by Daniel15** [comment]
Is HHVM actually running? Check the error log (`/var/log/hhvm/error.log`) and see if anything is in there?

**Comment by J0WI** [comment]
systemd told me, that HHVM was running.
However I found the issue in the logs: There was an error with [RepoAuthoritative](https://github.com/facebook/hhvm/wiki/Performance-Tuning#easy-way).
