### ISSUE TITLE
Compil fails on Ubuntu 14.04

### ISSUE THREAD

**Issue by julienmary** [facebook/hhvm#6494]
make -j 32
...
100%] Built target hphp_runtime_static
Linking CXX executable hhvm
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc-client.a(osdep.o):function checkpw_cleanup: error: undefined reference to 'pam_setcred'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc-client.a(osdep.o):function kerberos_server_valid: error: undefined reference to 'krb5_init_context'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc-client.a(osdep.o):function kerberos_server_valid: error: undefined reference to 'krb5_kt_default'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc-client.a(osdep.o):function kerberos_server_valid: error: undefined reference to 'krb5_free_context'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc-client.a(osdep.o):function kerberos_server_valid: error: undefined reference to 'krb5_kt_start_seq_get'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc-client.a(osdep.o):function kerberos_server_valid: error: undefined reference to 'krb5_kt_close'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc-client.a(osdep.o):function kerberos_server_valid: error: undefined reference to 'krb5_kt_end_seq_get'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc-client.a(osdep.o):function auth_gssapi_valid: error: undefined reference to 'gss_nt_service_name'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc-client.a(osdep.o):function auth_gssapi_valid: error: undefined reference to 'gss_import_name'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc-client.a(osdep.o):function auth_gssapi_valid: error: undefined reference to 'gss_release_name'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc-client.a(osdep.o):function auth_gssapi_client_work: error: undefined reference to 'gss_nt_service_name'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc-client.a(osdep.o):function auth_gssapi_client_work: error: undefined reference to 'gss_import_name'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc-client.a(osdep.o):function auth_gssapi_client_work: error: undefined reference to 'gss_init_sec_context'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc-client.a(osdep.o):function auth_gssapi_client_work: error: undefined reference to 'gss_release_buffer'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc-client.a(osdep.o):function auth_gssapi_client_work: error: undefined reference to 'gss_delete_sec_context'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc-client.a(osdep.o):function auth_gssapi_client_work: error: undefined reference to 'gss_display_status'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc-client.a(osdep.o):function auth_gssapi_client_work: error: undefined reference to 'gss_display_status'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc-client.a(osdep.o):function auth_gssapi_client_work: error: undefined reference to 'gss_release_buffer'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc-client.a(osdep.o):function auth_gssapi_client_work: error: undefined reference to 'gss_release_buffer'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc-client.a(osdep.o):function auth_gssapi_client_work: error: undefined reference to 'gss_init_sec_context'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc-client.a(osdep.o):function auth_gssapi_client_work: error: undefined reference to 'gss_delete_sec_context'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc-client.a(osdep.o):function auth_gssapi_client_work: error: undefined reference to 'gss_display_status'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc-client.a(osdep.o):function auth_gssapi_client_work: error: undefined reference to 'gss_release_name'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc-client.a(osdep.o):function auth_gssapi_client_work: error: undefined reference to 'gss_release_buffer'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc-client.a(osdep.o):function auth_gssapi_client_work: error: undefined reference to 'gss_delete_sec_context'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc-client.a(osdep.o):function auth_gssapi_client_work: error: undefined reference to 'gss_unwrap'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc-client.a(osdep.o):function auth_gssapi_client_work: error: undefined reference to 'gss_wrap'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc-client.a(osdep.o):function auth_gssapi_client_work: error: undefined reference to 'gss_display_status'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc-client.a(osdep.o):function checkpw: error: undefined reference to 'pam_start'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc-client.a(osdep.o):function checkpw: error: undefined reference to 'pam_set_item'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc-client.a(osdep.o):function checkpw: error: undefined reference to 'pam_authenticate'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc-client.a(osdep.o):function checkpw: error: undefined reference to 'pam_acct_mgmt'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc-client.a(osdep.o):function checkpw: error: undefined reference to 'pam_setcred'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc-client.a(osdep.o):function kerberos_login: error: undefined reference to 'krb5_init_context'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc-client.a(osdep.o):function kerberos_login: error: undefined reference to 'krb5_parse_name'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc-client.a(osdep.o):function kerberos_login: error: undefined reference to 'krb5_free_context'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc-client.a(osdep.o):function kerberos_login: error: undefined reference to 'krb5_aname_to_localname'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc-client.a(osdep.o):function kerberos_login: error: undefined reference to 'krb5_free_principal'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc-client.a(osdep.o):function auth_gssapi_server: error: undefined reference to 'gss_nt_service_name'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc-client.a(osdep.o):function auth_gssapi_server: error: undefined reference to 'gss_import_name'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc-client.a(osdep.o):function auth_gssapi_server: error: undefined reference to 'gss_acquire_cred'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc-client.a(osdep.o):function auth_gssapi_server: error: undefined reference to 'gss_accept_sec_context'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc-client.a(osdep.o):function auth_gssapi_server: error: undefined reference to 'gss_release_name'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc-client.a(osdep.o):function auth_gssapi_server: error: undefined reference to 'gss_delete_sec_context'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc-client.a(osdep.o):function auth_gssapi_server: error: undefined reference to 'gss_release_cred'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc-client.a(osdep.o):function auth_gssapi_server: error: undefined reference to 'gss_release_name'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc-client.a(osdep.o):function auth_gssapi_server: error: undefined reference to 'gss_display_name'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc-client.a(osdep.o):function auth_gssapi_server: error: undefined reference to 'gss_display_name'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc-client.a(osdep.o):function auth_gssapi_server: error: undefined reference to 'gss_wrap'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc-client.a(osdep.o):function auth_gssapi_server: error: undefined reference to 'gss_unwrap'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc-client.a(osdep.o):function ssl_onceonlyinit: warning: the use of `tmpnam' is dangerous, better use `mkstemp'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc-client.a(osdep.o):function checkpw_cleanup: error: undefined reference to 'pam_end'

**Comment by wjywbs** [comment]
Can you try to add `-lpam` in `hphp/hhvm/CMakeFiles/hhvm.dir/link.txt` and run `make` again? Looks like your libc-client library is linked with the libpam library. https://github.com/facebook/hhvm/pull/5728 is related.

**Comment by sokol-44** [comment]
Maybe it's related to ISPConfig ?
https://github.com/facebook/hhvm/issues/1172
