### ISSUE TITLE
"Failed to initialize central HHBC repository: Failed to initialize schema - unable to open database file"

### ISSUE THREAD

**Issue by Daniel15** [facebook/hhvm#6495]
I tried moving all the sites on my server from PHP-FPM to HHVM. It was mostly going well, then I started seeing this error, which appears to crash the whole server :cry: 

```
Failed to initialize central HHBC repository:\n  Failed to initialize schema in /var/run/hhvm/hhvm.hhbc: \n  Failed to initialize schema in /root/.hhvm.hhbc: RepoQuery::step(repo=0x7f0ad5b36a00) error: 'CREATE TABLE main.magic_6416960c150a4a4726fda74b659105ded8819d9c(product TEXT);' --> (14) unable to open database file\n  Failed to open /var/www/.hhvm.hhbc: 14 - unable to open database file\n
Core dumped: Aborted
Stack trace in /tmp/stacktrace.9775.log
```

`/var/run/hhvm/hhvm.hhbc` exists and is 103 MB. It is writable by the webserver user (`www-data`). ` /root/.hhvm.hhbc` exists too (but it's just 2.3 MB) and I've tried making it world-read-write (`chmod 0777`) just to see if that'd help.

`/tmp/stacktrace.9775.log` is totally empty, it just contains:
```

PHP Stacktrace:

```

**Comment by JoelMarcey** [comment]
Can you try deleting `/var/run/hhvm/hhvm.hhbc` and see what happens?

**Comment by Daniel15** [comment]
Seems okay after removing that file. I'll keep an eye on it - I set PHP-FPM as a fallback in case HHVM crashes again.

Is it possible something corrupted the `hhvm.hhbc` file somehow?

**Comment by satyriasizz** [comment]
I stumble with this problem second time in two days now, where I should search the issue? How to cure it?

**Comment by JoelMarcey** [comment]
@satyriasizz Did you try deleting `/var/run/hhvm/hhvm.hhbc` so it can be regenerated again?

**Comment by satyriasizz** [comment]
Yes, I deleted the file and problem repeated in few hours

**Comment by aftabnaveed** [comment]
I just got this error, and it is recurring 
Failed to initialize central HHBC repository:\n  Failed to open /var/run/hhvm/hhvm.hhbc: 14 - unable to open database file\n

**Comment by Orvid** [comment]
Do you have any steps to reproduce it?

**Comment by aorenste** [comment]
This issue has been waiting for more info for more than 2 weeks. I'm closing it for now, but feel free to re-open it if you can provide more info. https://github.com/facebook/hhvm/wiki/Human-Timeouts

**Comment by aftabnaveed** [comment]
This is issue is back. This time I am able to see some stacktrace.  

```
ProcessID: 1915
ThreadID: 140455933114112
ThreadPID: 1967
Name: unknown program
Type: Aborted
Runtime: hhvm
Version: tags/HHVM-3.18.0-0-g9b285191feb2bb1558bb6682da135263bd2a9e60
DebuggerCount: 0

ThreadType: Web Request
Assertion Message: Failed to initialize central HHBC repository:
  Failed to initialize schema in /var/run/hhvm/hhvm.hhbc(rw-r--r-- root:root): 
  Failed to open /var/www/.hhvm.hhbc: 14 - unable to open database file

Assertion Failure: /tmp/tmp.Fv54re7NgD/hphp/runtime/vm/repo.cpp:562: HPHP::Repo::initCentral()::__lambda62: assertion `false' failed.
URL: /ping.php
Server_SERVER_NAME: mydomain.com
Server: 10.129.29.6

# 0  00000000034bf8f6
# 1  00000000014a6872
# 2  00007fbe8d4ec340
# 3  00007fbe88236cc9
# 4  00007fbe8823a0d8
# 5  0000000000dd5569
# 6  000000000184a768
# 7  0000000001859dcf
# 8  000000000185a9d4
# 9  000000000185add6
# 10 000000000185ae39
# 11 0000000001147e31
# 12 000000000114895c
# 13 000000000346a383
# 14 00000000034c77da
# 15 00000000034c7af2
# 16 00000000034c58d4
# 17 0000000001621df4
# 18 00000000034b9597
# 19 000000000162ed3a
# 20 000000000162f2ae
# 21 0000000001624ca6
# 22 0000000000dd5797
# 23 00000000014bc317
# 24 00007fbe8d4e4182
# 25 00007fbe882fa47d

PHP Stacktrace:

```
I did did delete the file /var/run/hhvm/hhvm.hhbc, but the error comes back after a while.
