### ISSUE TITLE
hhbc File not found when using relative paths

### ISSUE THREAD

**Issue by jshthornton** [facebook/hhvm#6504]
Using HHVM version 3.10.0 Ubuntu 14.04
Compiled bytecode as follows:
```
+ mktemp
+ OUT=/tmp/tmp.kvXMeJVmFU
+ find . -type f -name *.php
+ hhvm --hphp -thhbc -o some_dir --input-list /tmp/tmp.kvXMeJVmFU
```

Any PHP file that uses `require('abc.php');` rather than `require(__DIR__ . '/abc.php');` will get the file not found treatment.

**Comment by paulbiss** [comment]
You may need to use the `--module` option to specify your document root

**Comment by jshthornton** [comment]
@paulbiss Have you got a link to any docs on that argument?

**Comment by paulbiss** [comment]
Unfortunately nothing about building a repo is particularly well documented. You can have a look at where we build repos for oss-performance benchmarks [here](https://github.com/hhvm/oss-performance/blob/master/base/HHVMDaemon.php#L152-L194). There are also some descriptions the go along with the options [here](https://github.com/facebook/hhvm/blob/753741d1557601578f12d3a81860e0a67b9af2b0/hphp/compiler/compiler.cpp#L207-L314).

**Comment by jshthornton** [comment]
Thank you. I will give it a go. If it doesn't work I will just have to do a find and replace during the build step (a lot of 3rd party libraries also use this pattern).

**Comment by jshthornton** [comment]
@paulbiss How can I use the module option (for document root) when building on a server that isn't the server running the codebase? For example a CI. As it appears that hhvm tries to open that directory.

**Comment by paulbiss** [comment]
I think you just need to specify the root of the tree you're /building/ with, not the actual document root on the server. As an aside, it shouldn't really matter what the document root on the server is when you run in repo mode since it shouldn't ever need to read any php files. It will read static content from there.

**Comment by jshthornton** [comment]
With `module` is it supposed to be the directory all the files are in?
As I am using it with a directory that is 777 and as sudo. But I am getting `FileUtil::find(): unable to open directory`

**Comment by paulbiss** [comment]
I think module is relative to `--input-dir`

**Comment by jshthornton** [comment]
So this problem effects multiple directories. Does module support multiple directories? Currently passing two directories results in the second one being unable to be opened.

**Comment by JoelMarcey** [comment]
@jshthornton Our new docs coming out soon will have some information on building a repo. You can see the markdown here: https://github.com/hhvm/user-documentation/blob/master/guides/hhvm/03-advanced-usage/02-repo-authoritative.md

**Comment by jshthornton** [comment]
@JoelMarcey Nice. I think you guys should really concentrate on getting those docs and the build part seamless and production worthy. Once PHP7 comes out it will be one of the only things separating HHVM and PHP.

**Comment by paulbiss** [comment]
Well there's also Hack, async, xhp, etc, but you're point is well taken we're working hard to get the new documentation ready and we should invest in making repo mode easier to use.

**Comment by karpa13a** [comment]
@JoelMarcey can you provide a step-by-step guide how to supply new hhbc file on production server under load.
for example, currently, with php we upload new .php file on prod servers, after succefully this stage we issue a clear apc cache to load new .php code.
how to gracefully reload hhvm in this case?
1. upload hhbc repo file on each server
2. service hhvm restart (or some "magic" command thru admin port)? on each

plz add this to docs too.

**Comment by jshthornton** [comment]
@paulbiss Using module didn't work in the end. Guess it is definitely broken. Will just have to find and replace all instances of require / include.

**Comment by paulbiss** [comment]
@jshthornton I'll have a look when I get a spare moment

**Comment by JoelMarcey** [comment]
@karpa13a There is no "graceful" way to swap out `hhbc` files without restarting HHVM.
