### ISSUE TITLE
404 File Not Found on Debian Jessie + Nginx

### ISSUE THREAD

**Issue by elend80** [facebook/hhvm#6509]
Hi. I have typically used with the NginX.

Ubuntu:Trusty + Nginx 1.8.0 + HHVM 3.10 = Ok

Debian:jessie + Nginx 1.8.0 + HHVM 3.10 = php file is 404 File Not Found Error

/etc/nginx/conf.d/default.conf file includes hhvm.conf

Version Info

OS : #1 SMP Debian 3.16.7-ckt11-1+deb8u5 (2015-10-09)

Nginx : nginx version: nginx/1.8.0

HipHop VM 3.10.1 (rel)
Compiler: tags/HHVM-3.10.1-0-g689b4969a141620ee5a282ce0dbf72278c84d44b
Repo schema: 6c99ee1f98340f6f3ef397a332583f0e843a627d
root@debian:/etc/hhvm# nano /var/log/hhvm/error.log

**Comment by keepxtreme** [comment]
try to sett fcgi_fix_path to 0 or 1 contrary to your current setting.

**Comment by elend80** [comment]
I found solution. My Nginx default.conf 

    #location / {
        root   /usr/share/nginx/html;
        index  index.php index.html index.htm;
    #}
