### ISSUE TITLE
get_object_vars and numeric keys

### ISSUE THREAD

**Issue by vanviegen** [facebook/hhvm#6512]
```php
$obj = new stdClass;
$obj->{1} = 2;
$arr = get_object_vars($obj);
print_r($arr); // Array ( [1] => 2 ) as expected
print $arr[1] . "\n"; // php: outputs "2" as expected, hhvm: notices "Undefined index: 1"
```

So the array gets in an inconsistent state, presumably because the numeric key is still encoded as a string, instead of an int, as arrays expects. PHP has the same astonishing behavior when an object cast is used instead of `get_object_vars`. But at least `get_object_vars` offers an okay work-around there.

**Comment by aorenste** [comment]
In this case HHVM is matching the php7 behavior.
