### ISSUE TITLE
Ubuntu 15.04 package doesn't apply config from server.ini

### ISSUE THREAD

**Issue by SG5** [facebook/hhvm#6514]
HHVM was installed  from [Prebuilt packages on Ubuntu 15.04](https://github.com/facebook/hhvm/wiki/Prebuilt-packages-on-Ubuntu-15.04-%28vivid%29). I try hhvm and hhvm nightly packages.
My `/etc/hhvm/server.ini` looks like
```
; php options

pid = /var/run/hhvm/pid-test

; hhvm specific

hhvm.server.port = 9001
;hhvm.server.file_socket = /tmp/hhvm.sock
hhvm.server.type = fastcgi
hhvm.server.default_document = index.php
hhvm.log.use_log_file = true
hhvm.log.file = /var/log/hhvm/error.log
hhvm.repo.central.path = /var/run/hhvm/hhvm.hhbc
```
But after restart pid file still located at `/var/run/hhvm/pid` and `netstat -an` tell nothing about 9000 or 9001 port or hhvm socket

**Comment by jwatzman** [comment]
You can override the pid file in `/etc/default/hhvm`. Not sure why the port isn't working... have you tried `telnet localhost 9001` and see if anything is in fact listening there?

**Comment by SG5** [comment]
I've changed pid location only for test. From `/etc/default/hhvm` settings load successful.
As you said, i tried check port with `nc`, and it failed.
