### ISSUE TITLE
Can`t compile in Ubuntu 14.04

### ISSUE THREAD

**Issue by brunoric** [facebook/hhvm#6528]
I am trying to compile HHVM 3.10.1 from source as described [here](https://github.com/facebook/hhvm/wiki/Building-and-installing-HHVM-on-Ubuntu-14.04) but without any success. I also tried to compile 3.9.1 and also without any success. Please see the compilation log [here](https://gist.github.com/brunoric/87e2d7680454eb858580).

I see another issues here with gcc 4.9.X AND 5.X, but I am using gcc 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04). Do you guys have any clue about it?

**Comment by JoelMarcey** [comment]
I don't actually see the error in the compilation log. Can you highlight the line that is causing the error?

**Comment by brunoric** [comment]
I found these errors:

```
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
make[2]: *** [hphp/compiler/CMakeFiles/hphp_analysis.dir/analysis/emitter.cpp.o] Error 4
make[1]: *** [hphp/compiler/CMakeFiles/hphp_analysis.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

```
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
make[2]: *** [hphp/runtime/CMakeFiles/hphp_runtime_static.dir/base/execution-context.cpp.o] Error 4
make[1]: *** [hphp/runtime/CMakeFiles/hphp_runtime_static.dir/all] Error 2
```

```
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
make[2]: *** [hphp/runtime/ext/CMakeFiles/hphp_runtime_ext.dir/fileinfo/libmagic/apprentice.cpp.o] Error 4
make[1]: *** [hphp/runtime/ext/CMakeFiles/hphp_runtime_ext.dir/all] Error 2
```
I found this [thread](https://bitcointalk.org/index.php?topic=304389.0) with an error with a similar message. Since I am using docker-machine on Mac (docker environment through a virtuabox) I will try to increase the VM memory and see if works. If I have luck or not I will post here. But if anyone has other clues please I would appreciate any help.

Thank you in advance.

**Comment by jwatzman** [comment]
> c++: internal compiler error: Killed (program cc1plus)

Yeah, this is almost always an OOM. Building HHVM requires quite a bit of RAM, much more than actually running it in many cases. You'll probably want a few GB allocated to your VM.

**Comment by brunoric** [comment]
It worked! First I bumped the VM RAM to 2GB and still get problems but with 4GB everything compiled well.

Thank you all.

**Comment by Orvid** [comment]
Assuming I gate it properly to support both posix and windows, would there be any objection to me adding a CMake check for memory, and triggering a fatal error, optionally overridden, if the machine doesn't have at least 4gb of ram?

**Comment by jwatzman** [comment]
The problem is 4G is pretty arbitrary, and it also depends on the value you pass to `make -j`. I suspect that 2G (maybe even 1G) is probably enough for `make -j1`, but you might want a lot more than 4G for `make -j4` or something.

**Comment by SiebelsTim** [comment]
additionally it depends on the build type. 
The linker for debug builds take ~6GB+ for me if I remember correctly

**Comment by Orvid** [comment]
The MSVC linker gets away with < 4GB even for debug builds, but it does some things a bit differently. The 4G is pretty arbitrary but is enough for a basic release build, and for those that really want to build with less than 4G, they can override the check.

As a random note, to do a release build with LTCG under MSVC you need at least 16gb of ram, because the linker uses up to 12gb before it cuts down its working set to what's referenced, which only drops usage to 9gb.
