### ISSUE TITLE
CMake Error With MyCrypt

### ISSUE THREAD

**Issue by DIntertech** [facebook/hhvm#6529]
I am trying to compile for 3.10 and I get this error:

    -- mcrypt NOT found.
    CMake Error at CMake/HHVMExtensionConfig.cmake:543 (message):
      The mcrypt extension '2' 'OFF' is an extension you probably want, but
      resolving the dependency 'libMCrypt' failed!
    Call Stack (most recent call first):
      CMake/HHVMExtensionConfig.cmake:839     (HHVM_EXTENSION_INTERNAL_SET_FAILED_DEPENDENCY)
      CMake/HHVMExtensionConfig.cmake:479 (HHVM_EXTENSION_INTERNAL_HANDLE_LIBRARY_DEPENDENCY)
      CMake/HHVMExtensionConfig.cmake:348 (HHVM_EXTENSION_INTERNAL_RESOLVE_DEPENDENCIES_OF_EXTENSION)
      hphp/runtime/ext/CMakeLists.txt:41 (HHVM_EXTENSION_RESOLVE_DEPENDENCIES)

I am following this installation here: https://github.com/facebook/hhvm/wiki/Building-and-installing-HHVM-on-CentOS-6.6  When I switch too HHVM-3.8 I get a similar error:

    CMake Error at CMake/FindMcrypt.cmake:31 (message):
      Could NOT find mcrypt library.
    Call Stack (most recent call first):
      CMake/HPHPFindLibs.cmake:306 (find_package)
      CMake/HPHPSetup.cmake:125 (include)
  third-party/CMakeLists.txt:18 (include)

I have mcrypt installed with yum install libmcrypt-devel.

**Comment by DIntertech** [comment]
NVM, this one can be closed. In Centos 6, use the rhel, otherwise the otherwise crypt will not work.

**Comment by Orvid** [comment]
If mcrypt is installed, it should be getting found, was it just in an unusual location?
