### ISSUE TITLE
PharData tar extract different results with hhvm and php

### ISSUE THREAD

**Issue by mefiblogger** [facebook/hhvm#6530]
Hello,

We just came across a problem with hhvm using composer. We have a tar file in composer's cache, and the following lines:

```
<?php

$archive = new \PharData($argv[1]);
$archive->extractTo('.', null, true);
```

resulting different file structure with hhvm and native php. The hhvm version puts some directories to the top of the target directory, instead of their original place which is deeper in the directory structure.

So we have this file:

somefile.tar

which contains:

```
lib/BusinessCore/SearchEngine/Business/Service/Search/ResultCountWithoutRowsSearchHandlerParameter.php
```

and the hhvm extract results this:

```
* lib/
  * ...
* BusinessCore
  * SearchEngine
    * Business
      * Service
        * Search
          * ResultCountWithoutRowsSearchHandlerParameter.php
```

We are using:

```
HipHop VM 3.6.6 (rel)
Compiler: tags/HHVM-3.6.6-0-gead6875c956d4bd5e906ebea899c71c3b8a7182d
Repo schema: 5034239b4e72c991556d7e651946e7fe89d8c2f4
```

But we can reproduce this bug with:

```
HipHop VM 3.10.1 (rel)
Compiler: tags/HHVM-3.10.1-0-g689b4969a141620ee5a282ce0dbf72278c84d44b
Repo schema: 6c99ee1f98340f6f3ef397a332583f0e843a627d
```

Unfortunatelly, this is a private composer repository, so I cannot attach the tar file, but if you contact me, I can send you in an e-mail.

Thx,
Gábor Nádai

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

The phar extension has been removed in hhvm version [4.1.0](https://hhvm.com/blog/2019/04/09/hhvm-4.1.0.html).
