### ISSUE TITLE
mysqli::ping change last insert id

### ISSUE THREAD

**Issue by noony** [facebook/hhvm#6531]
Following code is showing a HHVM incompatibility, call of mysqli_ping or mysqli::ping function resets last insert id.

```
<?php

$l = mysqli_init();
$l->real_connect('localhost', 'root', 'root', 'test');

$dropTableQuery = "DROP TABLE test_table_noony";
$l->query($dropTableQuery);

$createTableQuery = "CREATE TABLE test_table_noony ( id INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY, lol int(10) )";
$l->query($createTableQuery);

$queryInsert = "INSERT INTO test_table_noony (`lol`) VALUES (1)";
$l->query($queryInsert);
var_dump($l->insert_id);
$l->ping();
var_dump($l->insert_id);
```

HHVM result :
```
tcolomb@tcolomb-nginx:~/hhvm/hphp$ ./hhvm/hhvm toto.php
int(1)
int(0)
```
PHP result :
```
tcolomb@tcolomb-nginx:~/hhvm/hphp$ php toto.php
int(1)
int(1)

**Comment by SiebelsTim** [comment]
Hi, I cannot reproduce this (thanks for the great test case btw).
Maybe this is related to your database server. HHVM pretty much only calls the mysql_* C functions.

```
$ php mysqlping.php 
int(1)
int(1)
$ hhvm mysqlping.php 
int(1)
int(1)
```
---

```
$ mysql --version
mysql  Ver 14.14 Distrib 5.5.46, for debian-linux-gnu (x86_64) using readline 6.3
```

**Comment by noony** [comment]
I have almost the same version of mysql :
```
noony@noony-desktop:~/hhvm$ ./hphp/hhvm/hhvm toto.php 
int(1)
int(0)
noony@noony-desktop:~/hhvm$ mysql --version
mysql  Ver 14.14 Distrib 5.5.44, for debian-linux-gnu (x86_64) using readline 6.3

**Comment by noony** [comment]
With 3.8 there is no problem. I have to git besect.
```
noony@noony-desktop:~/hhvm$ hhvm --version
HipHop VM 3.8.0 (rel)
Compiler: tags/HHVM-3.8.0-0-gbb32f8d645b28561d8491870c44730b9b3f08d35
Repo schema: 74bee5d310450724cfd49245fd6c2e1e4323b10a
noony@noony-desktop:~/hhvm$ hhvm toto.php
int(1)
int(1)

**Comment by SiebelsTim** [comment]
FWIW: I am running 3.10.1 (package) and 3.10.0 (self compiled, commit hash below) right now.

```
$ hhvm --version
HipHop VM 3.10.1 (rel)
Compiler: tags/HHVM-3.10.1-0-g689b4969a141620ee5a282ce0dbf72278c84d44b
Repo schema: 6c99ee1f98340f6f3ef397a332583f0e843a627d

$ _hhvm --version
HipHop VM 3.10.0-dev (dbg)
Compiler: heads/master-0-g5d70cbc03d741acb81a582040d4b4f88ddb72a0c
Repo schema: 2414f44cb0fd984402662a6571cd8f025113a6d4

```

**Comment by noony** [comment]
Seems related to https://github.com/facebook/hhvm/commit/74f7e7af7219257bb17bef42fb1ebfae1887ba54 @JoelMarcey

**Comment by noony** [comment]
https://github.com/webscalesql/webscalesql-5.6/blob/30d93217019b0c595b6016d173cd1612edce8db9/sql-common/client.c#L5370 webscalesql modify last insert id and affected_rows only if net_field_length == 0

**Comment by noony** [comment]
Someone to handle this issue in fb/mysql-5.6 third party ?

**Comment by JoelMarcey** [comment]
@noony Do you want to file an issue here: https://github.com/facebook/mysql-5.6/issues referencing this issue?

cc: @drilibo

**Comment by drilibo** [comment]
I'll look into this, but please file the report in mysql-5.6 because this will need to be patched there. I'll try to repro and will let you know.

**Comment by noony** [comment]
Done.
