### ISSUE TITLE
Duplicate Symlink Error

### ISSUE THREAD

**Issue by DIntertech** [facebook/hhvm#6532]
When make install, I get this error:

    -- Installing header files for mcrouter
    CMake Error at CMake/HPHPFunctions.cmake:221 (file):
      file COPY cannot duplicate symlink
      "/usr/local/hhvm/third-party/mcrouter/src/mcrouter/lib/network/CaretSerializedMessage.h"
      at
      "/usr/local/include/hphp/third-party/mcrouter/src/mcrouter/lib/network/CaretSerializedMessage.h".
    Call Stack (most recent call first):
      third-party/cmake_install.cmake:117 (HHVM_INSTALL_HEADERS)
      cmake_install.cmake:101 (include)

    make: *** [install] Error 1

Any suggesions on how to handle?

**Comment by jwatzman** [comment]
tbqh, I'm not sure. Some configurations of cmake don't hit this. But it's preventing our vivid nightly builds from working, so it needs to get solved at some point :\

**Comment by Orvid** [comment]
I just put up a PR to fix this by writing a file that does a literal include instead of symlinks as [hhvm-third-party #98](https://github.com/hhvm/hhvm-third-party/pull/98).
