### ISSUE TITLE
Create package RPM HHVM for OpenSUSE 

### ISSUE THREAD

**Issue by jniltinho** [facebook/hhvm#6541]
Please create Official Package

Like
http://download.opensuse.org/repositories/home:/munix9/openSUSE_Leap_42.1/x86_64/

http://download.opensuse.org/repositories/home:/munix9/openSUSE_Leap_42.1/x86_64/hhvm-3.10.1-1.8.x86_64.rpm

http://download.opensuse.org/repositories/home:/munix9/openSUSE_Leap_42.1/x86_64/hhvm-devel-3.10.1-1.8.x86_64.rpm

http://download.opensuse.org/repositories/home:/munix9/openSUSE_Leap_42.1/x86_64/hhvm-ext-geoip-1.1.0.1-2.1.x86_64.rpm

http://download.opensuse.org/repositories/home:/munix9/openSUSE_Leap_42.1/x86_64/hhvm-fastcgi-3.10.1-1.8.x86_64.rpm

**Comment by jwatzman** [comment]
Unfortunately we don't have the in-house time or expertise to maintain packages for anything but Debian/Ubuntu. Anything else will have to be community contributed at this time, sorry! We have some community contributed information at https://github.com/facebook/hhvm/wiki/Building-and-Installing-HHVM -- and as far as RPM-based distros are concerned, @jrobeson did some good work for CentOS/Fedora; not sure how close OpenSUSE is to those, but his work is at https://copr.fedoraproject.org/coprs/jrobeson/hhvm/

**Comment by jniltinho** [comment]
Hi @jwatzman , Sorry

I will read all links I will try to create package using OpenSUSE Builder Server
Thank's
