### ISSUE TITLE
Null coalesce operator should only consider null falsey

### ISSUE THREAD

**Issue by daviddoran** [facebook/hhvm#6545]
In #5500 (PR #824) support for the "PHP7 null coalesce operator" was added but its behaviour doesn't match the [PHP RFC](https://wiki.php.net/rfc/isset_ternary) nor the operator as described in the issue.

Per the RFC:

    returns the result of its first operand if it exists and is not NULL, or else its second operand

Per issue #5500:

    expr1 ?? exp2 => isset(expr1) ? expr1 : expr2

In contrast, the [pull request](https://github.com/php/php-src/pull/824/files) seems to have implemented it like so:

    expr1 ?? exp2 => (isset(expr1) && expr1) ? expr1 : expr2

We can confirm this by running the following code with HHVM:

    var_dump(0 ?? 3); // int(3)
    var_dump(false ?? 3); // int(3)
    var_dump('' ?? 3); // int(3)

In contrast, in PHP7, the operator [correctly returns the falsey (but non-null) values](https://3v4l.org/nqXDF):

    var_dump(0 ?? 3); // int(0)
    var_dump(false ?? 3); // bool(false)
    var_dump('' ?? 3); // string(0) ""

PS: The root cause IMHO is that the [PHP test for the null coalesce operator](https://github.com/php/php-src/blob/250938e2d35fc54161a18167b7901c5e3b574371/tests/lang/operators/coalesce.phpt) doesn't include test cases for falsey values.

**Comment by jwatzman** [comment]
Did you intend to file this issue against HHVM or against PHP7? HHVM will match whatever the PHP7 implementation does, but whether they want to change their implementation, if it doesn't match their RFC, is a good question for php-internals.

Basically, I'm not sure who does what behavior, and which you want to consider wrong :)

**Comment by daviddoran** [comment]
Hey @jwatzman:

The [PHP7 implementation](https://3v4l.org/nqXDF):

- Matches their RFC
- Only considers unset and `null` to be falsey

The current HHVM implementation:

- Doesn't match @sgolemon's description of the operator in #5500
- Doesn't match the RFC
- Considers unset, `null`, `false`, `0`, `''` etc to be falsey

In my last sentence I was just pointing out that the PHP folks neglected to add an explicit test case for a non-null falsey value, so even though HHVM passes the PHP tests it has very different behaviour.

**Comment by jwatzman** [comment]
Aha, thanks. I misunderstood your report. Will look into it, thanks!

**Comment by jwatzman** [comment]
I think this is a simple fix and am looking into it.

**Comment by jwatzman** [comment]
Internal change D2653756 is up for review.

**Comment by jwatzman** [comment]
Also thanks @daviddoran this was a really good catch!
