### ISSUE TITLE
CentOS 7 CMake failed in progress

### ISSUE THREAD

**Issue by Richardevs** [facebook/hhvm#6553]
System:CentOS Linux release 7.1.1503 (Core)
Kernel:4.1.5-x86_64-linode61

Following the instructions from https://github.com/facebook/hhvm/wiki/Building-and-installing-hhvm-on-CentOS-7.x and then got the error below:（Using CMake）

Linking CXX static library libhphp_runtime.a
[ 94%] Built target hphp_runtime_static
make: *** [all] Error 2

**Comment by jwatzman** [comment]
You've omitted the actual error message. Can you paste the full output from `make`?

**Comment by Richardevs** [comment]
'make clean' and re-built the whole thing, saving output to another file but this time it went so smoothly and no error came up...well...

I think this issue can be closed for now.
