### ISSUE TITLE
gcc-current/configure --enable-languages=c,c++,fortran --enable-multilib --prefix=/usr/local/gcc 

### ISSUE THREAD

**Issue by ghost** [facebook/hhvm#6555]
sudo make
/tmp/gcc-current/isl/include/isl/ctx.h:83: warning: comma at end of enumerator list
In file included from ../../gcc-current/gcc/graphite.c:88:
../../gcc-current/gcc/graphite-poly.h:398: error: ‘isl_constraint’ has not been declared
../../gcc-current/gcc/graphite-poly.h:402: error: variable or field ‘debug_isl_constraint’ declared void
../../gcc-current/gcc/graphite-poly.h:402: error: ‘isl_constraint’ was not declared in this scope
../../gcc-current/gcc/graphite-poly.h:402: error: expected primary-expression before ‘)’ token
make[3]: *** [graphite.o] Error 1
make[3]: Leaving directory `/tmp/gcc-build/gcc'
make[2]: *** [all-stage1-gcc] Error 2
make[2]: Leaving directory `/tmp/gcc-build'
make[1]: *** [stage1-bubble] Error 2
make[1]: Leaving directory `/tmp/gcc-build'
make: *** [all] Error 2

**Comment by wjywbs** [comment]
There are known issues to compile hhvm with gcc 5+ and the compiled hhvm may not be stable: https://github.com/facebook/hhvm/issues/5474#issuecomment-125887435 https://github.com/facebook/hhvm/issues/5219#issuecomment-97158069

So it's better to revert https://github.com/facebook/hhvm/wiki/Building-and-installing-HHVM-on-CentOS-6.6 to use gcc 4.9 until gcc 5 is supported.

**Comment by paulbiss** [comment]
@wjywbs feel free to edit it (it's a wiki), we don't have any officially supported CentOS packages so those instructions are entirely community contributed. It looks like @AlNahari was the one who edited the wiki to include gcc5.

@AlNahari please don't update the wiki with build instructions that don't work for you-- this is confusing for anyone else trying to use them. If you want to work on gcc 5 support there are already several issues open about it IIRC, once it works feel free to update the wiki to indicate it as an option (we don't have any continuous integration testing for gcc5 so it may be best to leave other options in the wiki even once it works).

**Comment by fredemmott** [comment]
This also looks like you're failing to build GCC5, and the error you're posting here has nothing to do with HHVM.

**Comment by Orvid** [comment]
As fred said, this isn't related to HHVM, closing.
