### ISSUE TITLE
Unbound name: SessionHandler (an object type) (Naming[2049])

### ISSUE THREAD

**Issue by belka-ew** [facebook/hhvm#6566]
If I'm extending \SessionHandler or implementing \SessionHanlderInterface in the strict mode the type checker complains about "Unbound name". The same if I use \PHP_SESSION_ACTIVE.
HHVM works, so I get no error if I run the script.

Should I configure something or is it a bug?

I use hhvm 3.10.1

**Comment by SiebelsTim** [comment]
It's a missing `.hhi`. 
If you want to take a shot, add the class outline for `SessionHandler` in `hphp/hack/hhi/` :)

**Comment by belka-ew** [comment]
Thanks @SiebelsTim.
I can't find this class in master. Should/can I test it and make a pull request?

**Comment by SiebelsTim** [comment]
> I can't find this class in master. 
Exactly, that's the problem ;)

> Should/can I test it and make a pull request?

Yes, that would be awesome :)

**Comment by aorenste** [comment]
Fixed in #6619
