### ISSUE TITLE
Server.FileSocket has wrong permissions on OS X

### ISSUE THREAD

**Issue by SimonSimCity** [facebook/hhvm#6567]
As written in #4416 it should be possible to change the permissions of the fastcgi unix socket by using the configuration `hhvm.server.file_socket_mode`, right?

Today, on my OS X 10.10 I wanted to test some projects and started by installing HHVM using homebrew (the installed HHVM version is 3.10.1) and discovered, that the permissions of my socket do not change - what ever I use as file mode there.

In #1727, @stuartcarnie suggested to set the default permissions for sockets to 0760 - and that's also the permissions the file has as of now, but I need it to be 0666.

Has the setting `hhvm.server.file_socket_mode` some edge-cases where it doesn't work?

**Comment by jwatzman** [comment]
It's possible this is an OS X-only issue. I'll take a look when I get some time -- it may be a few weeks.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Support for MacOS was removed in June of 2022. https://hhvm.com/blog/2022/06/17/deprecating-homebrew.html
