### ISSUE TITLE
CURLOPT_SAFE_UPLOAD is not supported

### ISSUE THREAD

**Issue by mattflaschen** [facebook/hhvm#6569]
Per http://php.net/manual/en/function.curl-setopt.php , CURLOPT_SAFE_UPLOAD is a new option 5.5.0+.  In 5.5.0 it defaults to false.  In  5.6.0 it defaults to true:

" TRUE to disable support for the @ prefix for uploading files in CURLOPT_POSTFIELDS, which means that values starting with @ can be safely passed as fields. CURLFile may be used for uploads instead."

See also https://wiki.php.net/rfc/curl-file-upload .

We are using 5.6.99-hhvm, but it does not recognize CURLOPT_SAFE_UPLOAD at all.

**Comment by ryanmce** [comment]
This is breaking arcanist at Facebook :-p

**Comment by Orvid** [comment]
Well then, bug us internally :P
