### ISSUE TITLE
PHP function not implemented: stream_set_chunk_size

### ISSUE THREAD

**Issue by doublecompile** [facebook/hhvm#6573]
It seems like `stream_set_chunk_size` isn't around in HHVM (I'm using 3.10.1).

```hack
echo (function_exists('stream_set_chunk_size') ? 'true' : 'false') . PHP_EOL;
```
Result: `false`

Searching for this method in the repository didn't yield any C++ results.

PHP introduced this method in 5.4.0.

**Comment by doublecompile** [comment]
Still missing as of 3.12.1.

**Comment by apeabody** [comment]
I would submit a pull request, but I want to clarify the underlying implementation.  For socket streams it *might* make sense to change SO_RCVLOWAT - if that is sufficient/appropriate.  Also, the PHP documentation (https://secure.php.net/manual/en/function.stream-set-chunk-size.php) isn't clear, so I have to assume $buffer_size is bytes.

**Comment by Orvid** [comment]
In PHP that sets the size of the internal buffer used to read or write, though I'm not sure its interaction with Sockets. `$buffer_size` is in bytes though.

**Comment by apeabody** [comment]
Are you thinking just wrap stream_set_read_buffer() and stream_set_write_buffer() which adjusts the socket or file buffer?  Or did you have another buffer in mind?  For Linux sockets we could also set SO_RCVLOWAT which sets the minimum number of input bytes to receive before processing - unfortunately the send version isn't implemented in Linux...   If we don't like any of these, it might be better to just leave unimplemented.

**Comment by kiler129** [comment]
I believe in PHP it's more high level, since it applies to streams only (which are wrapper for native sockets).

**Comment by Orvid** [comment]
There's both a buffer and a chunk size.

**Comment by apeabody** [comment]
Streams can also be used with File operations, but I'm only aware of chunk size as a Network concept.  Based on @kiler129 experience (which will return less data than requested in some situations) it sounds like it is depending DIRECTLY on the underlying sockets library to handle chunk size, which isn't the most fully features (at least under Linux) as it can only be used to control receive side.  Anyway, I'll submit a pull request in a little while and let further discussion take place there.

**Comment by Orvid** [comment]
It's been implemented as a no-op for the moment, but implementing it fully is still planned.
