### ISSUE TITLE
"convert.*" filters missing in Stream Functions

### ISSUE THREAD

**Issue by paulocoghi** [facebook/hhvm#6582]
HHVM version: **3.10.1**

---

In RainLoop project, [some stream filters are needed](https://github.com/RainLoop/rainloop-webmail/issues/634#issuecomment-99578443), specifically `convert.*` filters:

`'convert.base64-decode'`
`'convert.base64-encode'`
`'convert.quoted-printable-decode'`
`'convert.quoted-printable-encode'`

Doing a `var_dump(stream_get_filters());` HHVM returns:

`'zlib.deflate'`
`'zlib.inflate'`
`'string.rot13'`
`'string.toupper'`
`'string.tolower'`
`'convert.iconv.*'`

I am not experienced to add this to HHVM, but I am open to learn. Which would be the first steps so I can make this contribution?

**Comment by Orvid** [comment]
Duplicate of #4255 (not the other way around)
