### ISSUE TITLE
Short operators and class members not being passed to JIT

### ISSUE THREAD

**Issue by nilwave** [facebook/hhvm#6583]
There is a bug in Repo.authoritative = true and Eval.Jit=1:

<?
 class Test {
  private $a = 0;
  function increment()
  {
    $this->a += 1;
  }
 function increment_jit()
 {
   $this->a = $this->a + 1;
 }
 }
?>

Test::increment_jit is run in JIT mode while Test::increment runs in VM

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

GitHub is rendering the markdown in a manner that makes it impossible to see what you meant.

Rendered as-is.
```
There is a bug in Repo.authoritative = true and Eval.Jit=1:
a += 1; } function increment_jit() { $this->a = $this->a + 1; } } ?>

Test::increment_jit is run in JIT mode while Test::increment runs in VM
```
