### ISSUE TITLE
xhprof CPU time greater than Wall time

### ISSUE THREAD

**Issue by JohanTan** [facebook/hhvm#6589]
I have tried using xhprof in Vanilla PHP and compared that with profiling results in HHVM. As the results indicate, Vanilla PHP always has CPU time smaller than wall time, while in HHVM CPU time is exact the opposite: CPU being greater than wall time, sometimes even 10x greater. Below are two profiling requests, running on PHP and HHVM, respectively
```
Method URL Time wt cpu
GET	127.0.0.1:8000/stat/?use_php=1&from=web3b-vpc	Nov 23rd 09:01:15	10,700 µs 	9,784 µs	
GET	127.0.0.1:8000/stat/?from=web3b-vpc	Nov 23rd 09:01:15	21,938 µs 	202,124 µs
```
Currently running HHVM version is:
```
HipHop VM 3.9.1 (rel)
Compiler: tags/HHVM-3.9.1-0-g0f72cfc2f0a01fdfeb72fbcfeb247b72998a66db
Repo schema: 6416960c150a4a4726fda74b659105ded8819d9c
```
I'd be happy to get more detailed information if needed.

**Comment by Orvid** [comment]
What code are you running that's triggering this?

**Comment by aorenste** [comment]
This issue has been waiting for more info for more than 2 weeks. I'm closing it for now, but feel free to re-open it if you can provide more info. https://github.com/facebook/hhvm/wiki/Human-Timeouts
