### ISSUE TITLE
Map::takeWhile and Map::skipWhile never complete in certain situations

### ISSUE THREAD

**Issue by daviddoran** [facebook/hhvm#6597]
Assuming the Map has at least 5 elements:

1. `Map::skipWhile` never completes if the callback returns `false` for the first value
2. `Map::takeWhile` never completes if the callback returns `true` for all values

For example, given the following `Map`:

~~~hack
$m = Map {
  0 => 'one',
  1 => 'two',
  2 => 'three',
  3 => 'four',
  4 => 'five',
};
~~~

(1) The following code never completes (it pegs the CPU forever). The callback is only called once.

~~~hack
$m->skipWhile($v ==> $v !== 'one');
~~~

(2) The following code never completes (it pegs the CPU forever). The callback is called for all values.

~~~hack
$m->takeWhile($_ ==> true);
~~~

Relatedly, the following code completes under v3.10.1 but the `Map` `$m2` is always empty:

~~~hack
$m = Map {0 => 'one', 1 => 'two', 2 => 'three', 3 => 'four', 4 => 'five'};
$m2 = $m->takeWhile($v ==> $v !== 'five');
var_dump($m2);
~~~

Full repro (gist): https://gist.github.com/daviddoran/1d712ccebaa81a26dd03
Reproduced with:

    HipHop VM 3.10.1 (rel)
    Compiler: 1447354126_N
    Repo schema: 3704d0484c185ade6b25470d88e5f7d4574a3340

and:

    HipHop VM 3.11.0-dev (rel)
    Repo schema: 51cc73cde6783b0ed9f6b65f930689ae90f89513

**Comment by jwatzman** [comment]
I think there are a few bugs here, but I tracked down at least one of them. Working on writing it up now.

**Comment by daviddoran** [comment]
I filed a recent bug against HHVM for these two. Totally broken.

**Comment by jwatzman** [comment]
Internal change D2745145 is up which should fix the loops and crashes.

**Comment by jwatzman** [comment]
Sorry for the delay; should be fixed in master now.
