### ISSUE TITLE
Ubuntu 12.04 docs are out of date/wrong

### ISSUE THREAD

**Issue by reedy** [facebook/hhvm#6606]
Trying to test https://github.com/hhvm/oss-performance/pull/57

https://github.com/facebook/hhvm/wiki/Prebuilt-Packages-on-Ubuntu-12.04

"Don't forget to Install Boost 1.49 on Ubuntu 12.04. See Building and Installing HHVM on Ubuntu 12.04 for details." link is https://github.com/facebook/hhvm/wiki/Building-and-installing-HHVM-on-Ubuntu-12.04#installing-boost-149 which doesn't work. https://github.com/facebook/hhvm/wiki/Building-and-installing-HHVM-on-Ubuntu-12.04#installing-boost-155 is there instead

Install libboost1.55-all-dev

```
root@hhvm-oss-performance:~# apt-get install hhvm mysql-server unzip php5 php5-mysql siege
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 hhvm : Depends: libboost-filesystem1.49.0 but it is not installable
        Depends: libboost-program-options1.49.0 but it is not installable
        Depends: libboost-system1.49.0 but it is not installable
        Depends: libboost-regex1.49.0 but it is not installable
        Depends: libboost-thread1.49.0 but it is not installable
E: Unable to correct problems, you have held broken packages.
root@hhvm-oss-performance:~#
```

https://github.com/facebook/hhvm/wiki/Building-and-installing-HHVM-on-Ubuntu-12.04/_compare/4b3d35bef1cb494408a4d5ef0eaeca44f5adf270...d8aeff00ca508eb8f5996bc565185e686b08615b was the update

**Comment by reedy** [comment]
https://github.com/facebook/hhvm/wiki/Prebuilt-Packages-on-Ubuntu-12.04

That says no packages > 3.6, but http://dl.hhvm.com/ubuntu/dists/ has 3.9

**Comment by reedy** [comment]
http://dl.hhvm.com/ubuntu/dists/precise-lts-3.6/main/binary-amd64/Packages wants 1.49

https://launchpad.net/~mapnik/+archive/ubuntu/boost?field.series_filter=precise only has boost1.49 and boost-defaults


So the docs update for 12.04 is wrong, 1.51 won't work because of the wanted dependancy

**Comment by jwatzman** [comment]
Do the old directions work? I just reverted it, you're right that 1.51 makes no sense.

**Comment by jwatzman** [comment]
Actually, that page might have been correct for building master (which is unsupported BTW), https://github.com/facebook/hhvm/wiki/Prebuilt-Packages-on-Ubuntu-12.04 should still be correct? (The dep should get pulled in automatically.)

**Comment by reedy** [comment]
Nope, if you follow https://github.com/facebook/hhvm/wiki/Prebuilt-Packages-on-Ubuntu-12.04 exactly, you end up the errors above that I posted in the original comment.

I don't see a libboost in https://launchpad.net/~mapnik/+archive/ubuntu/boost, which I guess is the problem. Guess we need to find a new ppa?

**Comment by reedy** [comment]
Hmm, apt-get install boost1.49 should work... Will report back in a few

**Comment by reedy** [comment]
Ok, so I did something wrong. Or there was something wrong with loading the PPA when I tried a couple of days ago.... It seems to work fine today. Sorry about that...

**Comment by jwatzman** [comment]
np, glad it's sorted.
