### ISSUE TITLE
Why is Memcached::deleteMulti() not supported?

### ISSUE THREAD

**Issue by tslettebo** [facebook/hhvm#6611]
I realise we can iterate over the keys in a loop, calling delete() on each of them, bui I'd think that deleteMulti() would be more efficient.

Why isn't deleteMulti() supported in HHVM?

**Comment by JoelMarcey** [comment]
What version of HHVM are you using? It is supported as of October 5.

https://github.com/facebook/hhvm/commit/fa0de179a9de28f130b9b5cb819807a77af3065a

**Comment by fredemmott** [comment]
Closing as no reply.
