### ISSUE TITLE
Recursively counting an array with reference to itself causes segfault

### ISSUE THREAD

**Issue by taueres** [facebook/hhvm#6615]
HHVM crashes while executing the following snippet:

```php
<?php

$var = array(1);
$var[] = &$var;

$recursiveCount = count($var, COUNT_RECURSIVE);
```

PHP standard implementation correctly detects the recursion and issues a warning without interrupting the execution.
This is the message: `Warning: count(): recursion detected in /count.php on line 6`

The previous snippet obviously contains a bug but segfaults do not provide enough information for the developers during debugging. Something more verbose would be better.

**Comment by taueres** [comment]
For example `count($GLOBALS, COUNT_RECURSIVE);` is also affected.
Because $GLOBALS["GLOBALS"] is a self reference.

**Comment by fredemmott** [comment]
Still exists on 3.11 and nightlies

**Comment by mpu** [comment]
I created diff D3495098 internally for that issue.

**Comment by mpu** [comment]
We can now close this.
