### ISSUE TITLE
Include With File Not Existing Causes Crashing

### ISSUE THREAD

**Issue by DIntertech** [facebook/hhvm#6617]
I'm noticing that HHVM crashes with the following functions:

include
include_once
require
require_once

tries to fetch a file that does not exist. I have a StackTrace and a coredump for each crash, and each the crashes ends with one of those functions with no information beyond that. Using file_exists before the functions are called does mitigate the problem but it's a band-aid for the root cause.

Any thoughts?

**Comment by fredemmott** [comment]
We can't reproduce this problem (and it's covered by our test suite). Can you provide short and complete example code without dependencies?
