### ISSUE TITLE
typechecker should probably disallow `extract`

### ISSUE THREAD

**Issue by jwatzman** [facebook/hhvm#6618]
We allow this right now apparently?!

**Comment by jwatzman** [comment]
Ping @int3 @dabek @dlreeves

**Comment by dlreeves** [comment]
Isn't this just changing/removing it from HHI files, or is there something more needed?

**Comment by SiebelsTim** [comment]
It might be worth adding a message like unset() has.

**Comment by jwatzman** [comment]
Yeah, I think we should ban it in partial mode, even with `assume_php = true`.

**Comment by fredemmott** [comment]
Why is assume_php relevant? IIRC that doesn't affect locals, and extract() only affects locals?

**Comment by simonwelsh** [comment]
Means you can't just remove the HHI entry

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

`\extract()` has been removed from Hack.
_removal of functions (or ways to invoke functions) that need to inspect or alter the caller frame such as compact(), extract(), get_declared_variables(), func_get_args(), or parse_str() with a single argument._ [4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html)
