### ISSUE TITLE
Generator not being destroyed correctly when exception happens

### ISSUE THREAD

**Issue by scottrice** [facebook/hhvm#6624]
Example Script:

```
<?php

class FooBar implements Iterator {
    function __construct()   { echo "Constructing new FooBar\n"; }
    function __destruct()    { echo "Destructing FooBar\n"; }
    function current ()      { throw new Exception; }
    function key ()          { return 0; }
    function next ()         {}
    function rewind ()       {}
    function valid ()        { return true; }
}

function foo() {
    $f = new FooBar;
    foreach ($f as $val) {
        yield $val;
    }
}

function bar() {
    echo "Starting bar()\n";
    $x = foo();
    try {
        $x->next();
        var_dump($x->current());
    } catch (Exception $e) {
        echo "Caught Exception\n";
    }
    echo "Unsetting \$x\n";
    unset($x);
    echo "Finishing bar()\n";
}

bar();
```

Expected Output (aka PHP's output):

```
Starting bar()
Constructing new FooBar
Destructing FooBar
Caught Exception
Unsetting $x
Finishing bar()
```

Notice that FooBar is destructed as soon as the exception is thrown.

HHVM's output:

```
Starting bar()
Constructing new FooBar
Caught Exception
Unsetting $x
Finishing bar()
Destructing FooBar
```

Notice that "Destructing FooBar" happens at the very end of the script, so something is holding onto FooBar even after the generator has been trashed.

**Comment by jesseschalken** [comment]
Your example works without the generator. The problem is specifically that when iterating over an Iterator that throws an exception inside `current()`, the Iterator is leaked.

```php
class FooBar implements Iterator {
    function __construct() { echo "ctor\n"; }
    function __destruct() { echo "dtor\n"; }
    function current() { throw new \Exception(); }
    function key() { return 0; }
    function next() {}
    function rewind() {}
    function valid() { return true; }
}

function bar() {
    try {
        echo "try\n";
        foreach (new FooBar() as $val) {}
    } catch (Exception $e) {
        echo "catch\n";
    }
}

bar();

echo "finish\n";
```
PHP
```
try
ctor
dtor
catch
finish
```
HHVM
```
try
ctor
catch
finish
dtor
```

https://3v4l.org/fNEM2

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This issue applies to running php code on hhvm. Hhvm [nolonger supports running php code](https://hhvm.com/blog/2018/09/12/end-of-php-support-future-of-hack.html) since [hhvm version 4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html).

Hhvm does not have a concept of destuctors. This behavior can not be observed in modern hhvm versions.
