### ISSUE TITLE
Magento 1.9.2.2 - HHVM stucks and use 90% on all cores

### ISSUE THREAD

**Issue by ksaltik** [facebook/hhvm#6625]
I have Lamp stack debian jessie or wheezy Magento 1.9.2.2 installed. 
The situation happens on Amazon EC2, Google Cloud Platform and in Virtualbox whether virtualization selected Hypervisor or KVM.

When we try to AB Benchmark test with concurrent user 50 - 100 - 250 with 1000 - 10.000 request the CPU usage instantly increase to 90% percent and in latest releases of HHVM after a while it stucks but not failed and test ends with connection timeout our refused etc.But early releaeses don't stuck but uses same amount of CPU 90%.This situation happens in one core Virtual Machine. Because HHVM is a virtual machine we think this is a normal situation. So we try the test with 2 and 4 core machine the CPU usage multiplied with available cores, in 2 core machine CPU usage increase to 2x90% = 180% and in 4 core machine the CPU usage increase to 4x90% = 360%-370%. In early releases 3.0.0 it never stucks or failed but the latest releases stucks after a while.

The configuration files do not changed. The usage is same whether test performed with 50 - 100 - 250 concurrent users.

Is this a normal behaviour of HHVM or is there a problem ?

**Comment by ksaltik** [comment]
Same situation and can't get any answer from developers. 

Read it 

https://www.redy.host/blog/drupal-8-stress-test-round-3
In our previous test (Making Drupal 8 Fly), this same setup (but using HHVM) was maxing out at 13542 responses received (the test stopped counting responses strictly at 1 minute 00 seconds since the test start) and the average response time was 4426ms. As you see in the picture above, PHP7 was able to outperform HHVM by serving 32.7% more responses in 33.3% less average response time.

As mentioned in this article after one minute HHVMstarts to eat CPU it doesn't matter how many cores you have.

.they don't accept this issue because accepting this issue will make them vulnerable to attacks and recent failures of Facebook shows the problem is obvious.

**Comment by fredemmott** [comment]
Deleted @ksaltik's comment for spamming it all over the place.

**Comment by fredemmott** [comment]
- "This situation happens in one core Virtual Machine. Because HHVM is a virtual machine we think this is a normal situation. " < nope - while they're both called virtual machines, they're entirely separate concepts. HHVM is a VM that executes bytecode that represents PHP/Hack code, the VM it's running in is a virtual copy of a real PC.

 - this either needs an isolated example, output from 'perf', or a gdb backtrace from a debug build to be worked on

**Comment by ksaltik** [comment]
There is already same situations issues reported but I know hhvm written for Facebook's needs not for Wordpress Magento users.

http://etcinsider.com/blog/2015/05/11/hhvm-is-futex-abuser/

There is lots of example here.

But If you wan't I can build a virtual Machine on Amazon AWS and you can run any test to get the problem and solve it. I want the solution and I will mention about this solution to gey an answer.

As I mention I read all the issues recommendations one of your you told about the kvm vs Hypervisor I try everything and get same result. 2 core - 4 core - 8 core gbytes of memory nothing solved. The problem just multplied with cpu cores.

Is this is a problem or not. CPU usage multplied with core numbers if we increase the cores!

**Comment by ksaltik** [comment]
I am not spamming by the time I try to get your attention to this problem....

**Comment by ksaltik** [comment]
http://www.techenablement.com/facebook-hhvm-saves-wikipedia-30-page-load-time-50-cpu-load-zend/

We make something wrong maybe 

Facebook HHVM Saves Wikipedia 30% Page Load Time and 50% CPU load over Zend

What is strange with our installation.....

**Comment by fredemmott** [comment]
The comment here wasn't spam, but comments on other issues was.

Sorry, but we're too small a team to be able to look into individual deployments; if you can provide a backtrace from gdb or strace, or an isolated example (eg "If I run this single PHP file with no dependendencies, then execute this curl commant, I get <>"), then we're likely to be able to look into it and fix it.

**Comment by ksaltik** [comment]
OK I will write my bedtime it is very late here. Thank you ...teşekkürler

**Comment by aorenste** [comment]
This issue has been waiting for more info for more than 2 weeks. I'm closing it for now, but feel free to re-open it if you can provide more info. https://github.com/facebook/hhvm/wiki/Human-Timeouts
