### ISSUE TITLE
HHVM restart loop, every 126 seconcs process dies

### ISSUE THREAD

**Issue by dignus81** [facebook/hhvm#6628]
Hi all,

Recently we've run into an issue with HHVM and a Magento shop. Although we didn't find a root cause, we did find out that a restart of HHVM did fix the issue. Since then, couple of weeks ago, we restarted HHVM every night at 4. Nasty, but it worked.

Yesterday however, something strange started to happen. Since the restart at 4 in the morning, the main HHVM process died every 126/127 seconds. Every 126/127 seconds all day long, untill I killed the main process manually, since then it's running fine.

When it comes to loggin: nothing special is logged to HHVM log, only that it started again. In syslog I find this:

Dec  3 18:05:10 hostname kernel: [4770483.277245] init: hhvm main process (31110) terminated with status 1
Dec  3 18:05:10 hostname kernel: [4770483.277261] init: hhvm main process ended, respawning

Every 126/127 seconds, without skipping a beat. When I kill it manually it shows this:

Dec  3 19:11:18 hostname kernel: [4774450.735024] init: hhvm main process (18118) killed by KILL signal
Dec  3 19:11:18 hostname kernel: [4774450.735039] init: hhvm main process ended, respawning

The manual kill fixes the issue.

Environment: ubuntu 14.04 x64 with latest patches applied, HHVM version from the officiel repo's:

root@hostname:~# hhvm --version
HipHop VM 3.10.1 (rel)
Compiler: tags/HHVM-3.10.1-0-g689b4969a141620ee5a282ce0dbf72278c84d44b
Repo schema: 6c99ee1f98340f6f3ef397a332583f0e843a627d

This issue has occurred on 2 seperate servers. They have the same setup though, but it was 2 different machines. What extra info do I need to provide?

**Comment by fredemmott** [comment]
- can you get a backtrace from a debug build?
 - by any chance do you have monitoring that checks every 2 minutes? :)

**Comment by fredemmott** [comment]
- can you reproduce this on 3.11 ? 3.10 is no longer supported as it isn't an LTS release

**Comment by fredemmott** [comment]
No response, can't investigate.
