### ISSUE TITLE
timezone_open throws an exception rather than returning false

### ISSUE THREAD

**Issue by nicholas-eden** [facebook/hhvm#6632]
This is a rather obscure one, but reporting it so it is noted.  The timezone_open method returns false in php but throws an exception in hhvm.

```php
php > var_dump(timezone_open('sdf'));
bool(false)
```

```php
hphpd> var_dump(timezone_open('sdf'));
Hit a php exception : exception 'Exception' with message 'DateTimeZone::__construct(): Unknown or bad timezone (sdf)' in :1
```

**Comment by jurchiks** [comment]
Actually, timezone_open('invalid argument') should also output a warning, according to this: https://github.com/php/php-src/blob/master/ext/date/tests/timezone_open_variation1.phpt#L112
