### ISSUE TITLE
Hack: Add support for PHP7 engine exceptions

### ISSUE THREAD

**Issue by simonwelsh** [facebook/hhvm#6633]
Now that HHVM supports PHP7's Engine Exceptions and the Throwable parent thing, would be nice if the type checker did too.

**Comment by simonwelsh** [comment]
I had a quick look at this. Since using engine exceptions and exposing Throwable is being one of the php7 INI flags, this will either need a flag in `.hhconfig` or for Hack to switch to PHP7 mode by default.

If a flag is used, may also need a way to have certain HHI files only load in PHP7 mode.

Beyond that, it just looks like the only changes beyond the HHI ones would be to change the base class used in `exception_ty` in `typing/typing.ml`

**Comment by DemiMarie** [comment]
Ping?  This can be a big help during debugging.

**Comment by fredemmott** [comment]
This was mostly addressed in 3.25 - please file specific issues for any remaining problems (such as #8153)
