### ISSUE TITLE
PHP 7 and PHP_MAJOR_VERSION

### ISSUE THREAD

**Issue by etcinit** [facebook/hhvm#6636]
I've noticed that projects like PHPUnit and Laravel use the `PHP_MAJOR_VERSION` constant to check if the current runtime is PHP 7. However, HHVM reports the major version as `5`, which makes sense given that it supports both PHP 5 and PHP 7.

One option could be to set `PHP_MAJOR_VERSION` to `7` when `hhvm.php7.all = true` (or separate setting) is set on the ini file.

Alternatively, PHPUnit, Laravel, etc could use something like `version_compare(HHVM_VERSION, '3.11') >= 0` or `ini_get('hhvm.php7.all') == true` to check for PHP 7 support on HHVM.

**Comment by SiebelsTim** [comment]
PHP_MAJOR_VERSION should definitely report the correct configuration in my opinion.

**Comment by MarkGavalda** [comment]
Setting PHP_MAJOR_VERSION to 7 should be fine, I wouldn't burden (or wait for... :) ) framework developers to implement special rules just to check if the tests are run on HHVM and if yes, which version...

**Comment by jwatzman** [comment]
Diff up internally for this.

**Comment by etcinit** [comment]
Thanks!
