### ISSUE TITLE
PHP 7 return types and "self" type hint

### ISSUE THREAD

**Issue by etcinit** [facebook/hhvm#6640]
The `self` return type hint throws errors in some cases on PHP 7 but not in HHVM:

**test3.php:**
```php
<?php

declare(strict_types=1);

interface InterfaceA
{
    function beMyself(): self;
}

class ClassA implements InterfaceA
{
    function beMyself(): self
    {
        return $this;
    }
}

var_dump((new ClassA)->beMyself());
```

**Output of test3.php:**
```
➜  ~  hhvm test3.php
class ClassA#1 (0) {
}
➜  ~  php test3.php 

Fatal error: Declaration of ClassA::beMyself(): ClassA must be compatible with InterfaceA::beMyself(): InterfaceA in /home/etcinit/test3.php on line 10
```

Replacing self with the interface name removes the error in PHP 7:

**test4.php:**
```php
<?php

declare(strict_types=1);

interface InterfaceA
{
    function beMyself(): self;
}

class ClassA implements InterfaceA
{
    function beMyself(): InterfaceA
    {
        return $this;
    }
}

var_dump((new ClassA)->beMyself());
```

**Output of test4.php:**
```
➜  ~  hhvm test4.php
class ClassA#1 (0) {
}
➜  ~  php test4.php 
object(ClassA)#1 (0) {
}
```

---

**Environment:**
OS: Fedora 23 x86_64
PHP and HHVM versions:
```
➜  ~  php --version
PHP 7.0.0 (cli) (built: Dec  6 2015 23:14:45) ( NTS )
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2015 Zend Technologies

➜  ~  hhvm --version              
HipHop VM 3.11.0-dev (rel)
Compiler: heads/master-0-gbfa816e32c7b1a74e7aaee3d2688af2112439003
Repo schema: b244c08341aac2b3ca55b1a60c134d546e130c7d
```

**Comment by jwatzman** [comment]
I wasn't aware that PHP7's type system even had a `self` type at all?

**Comment by etcinit** [comment]
It's listed on their docs (apparently since 5.0?): http://php.net/manual/en/functions.arguments.php#functions.arguments.type-declaration.types

**Comment by Orvid** [comment]
I would actually argue that PHP7 is the one that's wrong here, as the same thing happens if the interface becomes an abstract class. As the `self` type in `ClassA` will always be more derived from the `self` in `InterfaceA`, the typing should be perfectly valid.

**Comment by nikic** [comment]
@Orvid PHP uses invariant types for technical reasons. If HHVM doesn't have these problems, it should be fine for HHVM to support covariant returns. At least, if you can do so consistently, rather than only for this case.

**Comment by jwatzman** [comment]
@nikic right, but then wouldn't you expect `test3.php` above to work, since the two are textually the same? I thought that was the rule. (HHVM is also invariant in most places for the same technical reasons that PHP7 ended up that way.)

**Comment by jwatzman** [comment]
Oh, but although they're textually the same, they don't refer to the same *type*. Hm. This particular case I guess is always safe, since `self` is always covariant in this case?

**Comment by nikic** [comment]
@jwatzman IIRC HHVM supports interface on traits, in which case it would not necessarily be covariant.
