### ISSUE TITLE
3.10 => 3.11 regression: can't run hh_server --check if hh_server already running

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#6646]
This makes running hh_server --check as part of a test suite very annoying, as hh_client stop must be ran first, which then makes the next run take longer.

**Comment by fredemmott** [comment]
fb task 9379602

**Comment by alexchow** [comment]
Fixed. Will be in next release.

**Comment by fredemmott** [comment]
@alexchow : for cherry-pick, do we just need eb4a0cd2a26cbfe138a32798ec88682e5c9f14fd or do we need/want a90f8ad1f7df7f89568d4993d686fae35e35d3ce as well?

**Comment by int3** [comment]
eb4a0cd alone should fix this issue, though it seems reasonable to cherry-pick a90f8ad as well (breaking --retries is not great)

**Comment by alexchow** [comment]
That's right.

**Comment by fredemmott** [comment]
eb4a0cd isn't picking cleanly, and is going beyond my limited ocaml; any chance you could do an equivaelent change to the 3.11 branch?

**Comment by JoelMarcey** [comment]
I tried cherry-picking as well, and it seemed like the rabbit hole was on the order of 10 diffs to be safe, but I am sure there might be some that can be left out.

**Comment by fredemmott** [comment]
Picking the dependencies is too much, it looks like it can be done with just that one diff + a few small changes, if someone more familiar with ocaml than me tries.

**Comment by alexchow** [comment]
Redid eb4a0cd in #6691
