### ISSUE TITLE
Hack: fun doesn't play nice inside namespaces

### ISSUE THREAD

**Issue by simonwelsh** [facebook/hhvm#6652]
Hack and HHVM treat the string based to `fun` when in a namespace relative to different things. HHVM treats it as relative to the global namespace (which matches using strings as callables) whereas Hack treats it as relative to the current namespace.

``` hack
<?hh // strict

namespace foo;

function baz(): string {
    return 'Hello';
}

function foo(): void {
    $blah = fun('foo\baz');
    var_dump($blah());
}

/* HH_FIXME[1002] */
foo();
```

```
$ hhvm test.php 
string(5) "Hello"
$ hh_single_type_check test.php
File "test.php", line 10, characters 14-22:
Unbound name: foo\foo\baz (a global function) (Naming[2049])
```

If I change the call to `fun('baz)`, then:

```
$ hhvm test.php 

Fatal error: Call to undefined function baz() in /home/vagrant/test/test.php on line 11
$ hh_single_type_check test.php
No errors
```

**Comment by simonwelsh** [comment]
Interestingly, this has now switched. `hh_client` works fine, but `hhvm` gives `Fatal error: Uncaught Error: Failure to resolve undefined function foo\foo\baz() `

**Comment by MohamedNabil97** [comment]
facing same issue

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This work in hhvm 4.56, but I can't find the commit that fixed this. Both hhvm and hh_client look from the global namespace now (as if the namespace started with an implicit `\`). You are also allowed to prefix the function name with a `\`.

```
namespace MyNamespace;

<<__EntryPoint>>
function main(): void {
    fun('MyNamespace\my_function');
    fun('my_function');
}


function my_function(): void {}
```

```
Naming[2105] Unbound global function: 'my_function' is not a valid name for fun()
   --> file.hack
  6 |     fun('my_function');
    |         ^^^^^^^^^^^^^

Typing[4107] Unbound name (typing): my_function
   --> file.hack
  6 |     fun('my_function');
    |         ^^^^^^^^^^^^^

2 errors found.
```
