### ISSUE TITLE
503 error, almost-omnipresent race condition with proxy_fcgi

### ISSUE THREAD

**Issue by calimeroteknik** [facebook/hhvm#6654]
Using apache 2.2.31 with hhvm 2c752c1ba on gentoo stable, I get very unreliable behaviour from HHVM.

Sometimes things work as expected (a script running `<?php echo "ok\n";`), but most of the time I get a 503 error with this in error_log:
`[error] (104)Connection reset by peer: proxy: FCGI: Error dispatching request to :80:`

Running strace on the apache and hhvm processes help, especially over laggy SSH, which makes this likely to be a race condition. No crashes, ever, of any process.
[strace.txt](https://github.com/facebook/hhvm/files/60305/strace.txt)

Running php-fpm instead of hhvm makes things work flawlessly, even under bulk tests.

Somebody notes the same issue with apache 2.4 in the comments here: https://serversforhackers.com/proxying-to-fastcgi-in-ubuntuapache-24

**Comment by fredemmott** [comment]
Can you attach a trace from gdb or the linux perf tools (eg perf trace)? strace is not really useful for HHVM :(

**Comment by calimeroteknik** [comment]
I updated, and could not reproduce with 9f83ce115e450f4c928b37700f4f252222028e2c
