### ISSUE TITLE
HHVM and ViMbAdmin

### ISSUE THREAD

**Issue by akosveres** [facebook/hhvm#6655]
Hi,

Running HHVM on a freshly installed Debian 8. Nginx installed with ee, also wanted to install a mail server with ee stack install --mail, this uses vimbadmin as an admin panel for the mail users. After the installation the following error greets us.

hhvm --version
HipHop VM 3.11.0 (rel)
Compiler: tags/HHVM-3.11.0-0-g3dd564a8cde23e3205a29720d3435c771274085e
Repo schema: 52047bdda550f21c2ec2fcc295e0e6d02407be51

>#0 /var/www/22222/htdocs/vimbadmin/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(182): content_566d936f9db729_36030751()
>#1 /var/www/22222/htdocs/vimbadmin/vendor/opensolutions/oss-framework/src/OSS/View/Smarty.php(300): Smarty_Internal_TemplateBase->fetch()
>#2 /var/www/22222/htdocs/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Controller/Action/Helper/ViewRenderer.php(914): OSS_View_Smarty->render()
>#3 /var/www/22222/htdocs/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Controller/Action/Helper/ViewRenderer.php(933): Zend_Controller_Action_Helper_ViewRenderer->renderScript()
>#4 /var/www/22222/htdocs/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Controller/Action/Helper/ViewRenderer.php(972): Zend_Controller_Action_Helper_ViewRenderer->render()
>#5 /var/www/22222/htdocs/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Controller/Action/HelperBroker.php(277): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
>#6 /var/www/22222/htdocs/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(527): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
>#7 /var/www/22222/htdocs/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch()
>#8 /var/www/22222/htdocs/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch()
>#9 /var/www/22222/htdocs/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
>#10 /var/www/22222/htdocs/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
>#11 /var/www/22222/htdocs/vimbadmin/public/index.php(34): Zend_Application->run()
>#12 {main}

Let me know if you need any further information.

**Comment by Orvid** [comment]
This doesn't actually tell us anything about what is actually failing.

**Comment by aorenste** [comment]
This issue has been waiting for more info for more than 2 weeks. I'm closing it for now, but feel free to re-open it if you can provide more info. https://github.com/facebook/hhvm/wiki/Human-Timeouts
