### ISSUE TITLE
memcached session save handler doesn't work

### ISSUE THREAD

**Issue by Haravikk** [facebook/hhvm#6661]
I've configured `/etc/hhvm/php.ini` with the following settings:

```
session.save_handler = memcached
session.save_path = /tmp/memcached.sock
memcached.sess_prefix = 'php_'
```

With `memcached` running (and verified) on the correct socket. However, HHVM isn't saving sessions via `memcached`, and it isn't outputting any errors in its log, however, sessions do appear to work.

Either my configuration is wrong, in which case HHVM should be producing some kind of errors at startup or at runtime, or the configuration is correct in which case HHVM should be using `memcached` to load and store sessions in RAM.

I am using HHVM v3.10.1

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Support for the `$_SESSION` variable and ext_session was removed in https://hhvm.com/blog/2019/05/06/hhvm-4.4.0.html
