### ISSUE TITLE
krsort should be reverse of ksort, but isn't

### ISSUE THREAD

**Issue by SjonHortensius** [facebook/hhvm#6662]
It seems `krsort` sometimes results in arrays that are not the reverse of `ksort`. Php does this better, so this is *also* an incompatibility with php:

```php
$example = array(
    "ae1" => 1,
    "ae2" => 2,
    0 => 3,
    1 => 4,
);
    
 ksort($example); print_r($example); # results in 1,2,3,4
krsort($example); print_r($example); # results in 4,2,1,3
```
See also: https://3v4l.org/g5G3T

**Comment by SiebelsTim** [comment]
Du check on using the ZendSorting flag?

**Comment by WizKid** [comment]
If your sorting is not stable which it isn't. Then you will not get the reverse result if you using krsort.

**Comment by fredemmott** [comment]
Yep, ae0, ae1, and 0 are all equivalent for sorting, and the order is expliclty undefined according to the PHP documentation (the notes and warnings on http://php.net/manual/en/function.sort.php apply to all sorting functions).

Your expected output is not even consistent with various releases of php - the 3v4l link you shared shows PHP5 and PHP7 given you different output:

```
fred@hhvm-oss-bench:/tmp/test$ grep PRETTY_NAME /etc/*release
/etc/os-release:PRETTY_NAME="Ubuntu 14.04.3 LTS"
fred@hhvm-oss-bench:/tmp/test$ uname -a
Linux hhvm-oss-bench 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
fred@hhvm-oss-bench:/tmp/test$ php5 --version
PHP 5.5.9-1ubuntu4.9 (cli) (built: Apr 17 2015 11:44:57)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
fred@hhvm-oss-bench:/tmp/test$ php5 test.php
Array
(
    [ae1] => 1
    [0] => 3
    [ae2] => 2
    [1] => 4
)
Array
(
    [1] => 4
    [ae2] => 2
    [0] => 3
    [ae1] => 1
)
```

Though, the zend sorting flag does make HHVM match it:

```
fred@hhvm-oss-bench:/tmp/test$ hhvm test.php
Array
(
    [ae1] => 1
    [ae2] => 2
    [0] => 3
    [1] => 4
)
Array
(
    [1] => 4
    [ae2] => 2
    [ae1] => 1
    [0] => 3
)
fred@hhvm-oss-bench:/tmp/test$ hhvm -dhhvm.enable_zend_sorting=1 test.php
Array
(
    [ae1] => 1
    [0] => 3
    [ae2] => 2
    [1] => 4
)
Array
(
    [1] => 4
    [ae2] => 2
    [0] => 3
    [ae1] => 1
)
```

We provide the option as PHP5's

**Comment by SjonHortensius** [comment]
Thanks for explaining; I didn't realize the sorting wasn't stable; that explains it
