### ISSUE TITLE
clang 3.6.2 compile hhvm in ubuntu 15.10 x64 report error after [100%]

### ISSUE THREAD

**Issue by javacty** [facebook/hhvm#6663]
<pre>
CXX=/opt/clang362/bin/clang++ CC=/opt/clang362/bin/clang \
./configure  -DCMAKE_BUILD_TYPE=MinSizeRel \
-DCLANG_FORCE_LIBSTDCXX=ON -DENABLE_AVX2=ON \
-DENABLE_COTIRE=ON -DENABLE_ZEND_COMPAT=OFF
============================================================
Linking CXX static library libhphp_runtime.a
[100%] Built target hphp_runtime_static
[100%] Generating CXX unity source hphp/hhvm/cotire/hhvm_CXX_unity.cxx
[100%] Generating CXX prefix source hphp/hhvm/cotire/hhvm_CXX_prefix.cxx
[100%] Generating CXX prefix header hphp/hhvm/cotire/hhvm_CXX_prefix.hxx
[100%] Building CXX precompiled header hphp/hhvm/cotire/hhvm_CXX_prefix.hxx.pch
Scanning dependencies of target hhvm
[100%] [100%] [100%] Building CXX object hphp/hhvm/CMakeFiles/hhvm.dir/process-init.cpp.o
Building CXX object hphp/hhvm/CMakeFiles/hhvm.dir/main.cpp.o
Building CXX object hphp/hhvm/CMakeFiles/hhvm.dir/global-variables.cpp.o
In file included from /opt/hhvm/hphp/hhvm/process-init.cpp:17:
In file included from /opt/hhvm/hphp/compiler/option.h:23:
In file included from /opt/hhvm/hphp/runtime/base/runtime-option.h:20:
In file included from /opt/hhvm/third-party/folly/folly/dynamic.h:78:
In file included from /opt/hhvm/third-party/folly/folly/FBString.h:65:
/opt/hhvm/third-party/folly/folly/Traits.h:243:1: warning: inline namespace cannot
      be reopened as a non-inline namespace
FOLLY_GLIBCXX_NAMESPACE_CXX11_BEGIN
^
inline
/opt/hhvm/third-party/folly/folly/Portability.h:230:46: note: expanded from macro
      'FOLLY_GLIBCXX_NAMESPACE_CXX11_BEGIN'
# define FOLLY_GLIBCXX_NAMESPACE_CXX11_BEGIN _GLIBCXX_BEGIN_NAMESPACE_CXX11
                                             ^
/usr/lib/gcc/x86_64-linux-gnu/5.2.1/../../../../include/x86_64-linux-gnu/c++/5.2.1/bits/c++config.h:225:51: note:
      expanded from macro '_GLIBCXX_BEGIN_NAMESPACE_CXX11'
# define _GLIBCXX_BEGIN_NAMESPACE_CXX11 namespace __cxx11 {
                                                  ^
/usr/lib/gcc/x86_64-linux-gnu/5.2.1/../../../../include/c++/5.2.1/bits/locale_conv.h:160:1: note:
      previous definition is here
_GLIBCXX_BEGIN_NAMESPACE_CXX11
^
/usr/lib/gcc/x86_64-linux-gnu/5.2.1/../../../../include/x86_64-linux-gnu/c++/5.2.1/bits/c++config.h:225:51: note:
      expanded from macro '_GLIBCXX_BEGIN_NAMESPACE_CXX11'
# define _GLIBCXX_BEGIN_NAMESPACE_CXX11 namespace __cxx11 {
                                                  ^
In file included from /opt/hhvm/hphp/hhvm/process-init.cpp:17:
In file included from /opt/hhvm/hphp/compiler/option.h:23:
In file included from /opt/hhvm/hphp/runtime/base/runtime-option.h:20:
In file included from /opt/hhvm/third-party/folly/folly/dynamic.h:78:
In file included from /opt/hhvm/third-party/folly/folly/FBString.h:65:
/opt/hhvm/third-party/folly/folly/Traits.h:255:1: warning: inline namespace cannot
      be reopened as a non-inline namespace
FOLLY_GLIBCXX_NAMESPACE_CXX11_BEGIN
^
inline
/opt/hhvm/third-party/folly/folly/Portability.h:230:46: note: expanded from macro
      'FOLLY_GLIBCXX_NAMESPACE_CXX11_BEGIN'
# define FOLLY_GLIBCXX_NAMESPACE_CXX11_BEGIN _GLIBCXX_BEGIN_NAMESPACE_CXX11
                                             ^
/usr/lib/gcc/x86_64-linux-gnu/5.2.1/../../../../include/x86_64-linux-gnu/c++/5.2.1/bits/c++config.hIn file included from :225:51: note:
      expanded /opt/hhvm/hphp/hhvm/main.cppfrom macro :17'_GLIBCXX_BEGIN_NAMESPACE_CXX11'
:
In file included from /opt/hhvm/hphp/runtime/base/program-functions.h:20:
In file included from /opt/hhvm/hphp/runtime/base/types.h:# define _GLIBCXX_BEGIN_NAMESPACE_CXX11 namespace __cxx11 {21:
In file included from
                                                  ^/opt/hhvm/hphp/util/low-ptr.h
:20/opt/hhvm/third-party/folly/folly/Traits.h:
In file included from /opt/hhvm/hphp/util/assertions.h:243::28:
In file included from /opt/hhvm/third-party/folly/folly/Format.h:124:
In file included from : /opt/hhvm/third-party/folly/folly/Conv.hnote: previous:27:
In file included from  definition/opt/hhvm/third-party/folly/folly/FBString.h:65 is:
/opt/hhvm/third-party/folly/folly/Traits.h
      here:243
:1: warning: FOLLY_GLIBCXX_NAMESPACE_CXX11_BEGINinline namespace
^ cannot

      /opt/hhvm/third-party/folly/folly/Portability.hbe reopened:230 as :46a non-inline: note namespace
: expanded from macro
      'FOLLY_GLIBCXX_NAMESPACE_CXX11_BEGIN'
FOLLY_GLIBCXX_NAMESPACE_CXX11_BEGIN
^
inline # define FOLLY_GLIBCXX_NAMESPACE_CXX11_BEGIN _GLIBCXX_BEGIN_NAMESPACE_CXX11

                                             ^
/usr/lib/gcc/x86_64-linux-gnu/5.2.1/../../../../include/x86_64-linux-gnu/c++/5.2.1/bits/c++config.h:/opt/hhvm/third-party/folly/folly/Portability.h225:51::230 note: :46:
       noteexpanded : expandedfrom macro from  '_GLIBCXX_BEGIN_NAMESPACE_CXX11'macro

      'FOLLY_GLIBCXX_NAMESPACE_CXX11_BEGIN'
# define _GLIBCXX_BEGIN_NAMESPACE_CXX11 namespace __cxx11 {
                                                  ^
# define FOLLY_GLIBCXX_NAMESPACE_CXX11_BEGIN _GLIBCXX_BEGIN_NAMESPACE_CXX11
                                             ^
/usr/lib/gcc/x86_64-linux-gnu/5.2.1/../../../../include/x86_64-linux-gnu/c++/5.2.1/bits/c++config.h:225:51: note:
      expanded from macro '_GLIBCXX_BEGIN_NAMESPACE_CXX11'
# define _GLIBCXX_BEGIN_NAMESPACE_CXX11 namespace __cxx11 {
                                                  ^
/usr/lib/gcc/x86_64-linux-gnu/5.2.1/../../../../include/c++/5.2.1/bits/locale_conv.h:160:1: note:
      previous definition is here
_GLIBCXX_BEGIN_NAMESPACE_CXX11
^
/usr/lib/gcc/x86_64-linux-gnu/5.2.1/../../../../include/x86_64-linux-gnu/c++/5.2.1/bits/c++config.h:225:51: note:
      expanded from macro '_GLIBCXX_BEGIN_NAMESPACE_CXX11'
# define _GLIBCXX_BEGIN_NAMESPACE_CXX11 namespace __cxx11 {
                                                  ^
In file included from /opt/hhvm/hphp/hhvm/main.cpp:17:
In file included from /opt/hhvm/hphp/runtime/base/program-functions.h:20:
In file included from /opt/hhvm/hphp/runtime/base/types.h:21:
In file included from /opt/hhvm/hphp/util/low-ptr.h:20:
In file included from /opt/hhvm/hphp/util/assertions.h:28:
In file included from /opt/hhvm/third-party/folly/folly/Format.h:24:
In file included from /opt/hhvm/third-party/folly/folly/Conv.h:27:
In file included from /opt/hhvm/third-party/folly/folly/FBString.h:65:
/opt/hhvm/third-party/folly/folly/Traits.h:255:1: warning: inline namespace cannot
      be reopened as a non-inline namespace
FOLLY_GLIBCXX_NAMESPACE_CXX11_BEGIN
^
inline
/opt/hhvm/third-party/folly/folly/Portability.h:230:46: note: expanded from macro
      'FOLLY_GLIBCXX_NAMESPACE_CXX11_BEGIN'
# define FOLLY_GLIBCXX_NAMESPACE_CXX11_BEGIN _GLIBCXX_BEGIN_NAMESPACE_CXX11
                                             ^
/usr/lib/gcc/x86_64-linux-gnu/5.2.1/../../../../include/x86_64-linux-gnu/c++/5.2.1/bits/c++config.h:225:51: note:
      expanded from macro '_GLIBCXX_BEGIN_NAMESPACE_CXX11'
# define _GLIBCXX_BEGIN_NAMESPACE_CXX11 namespace __cxx11 {
                                                  ^
/opt/hhvm/third-party/folly/folly/Traits.h:243:1: note: previous definition is
      here
FOLLY_GLIBCXX_NAMESPACE_CXX11_BEGIN
^
/opt/hhvm/third-party/folly/folly/Portability.h:230:46: note: expanded from macro
      'FOLLY_GLIBCXX_NAMESPACE_CXX11_BEGIN'
# define FOLLY_GLIBCXX_NAMESPACE_CXX11_BEGIN _GLIBCXX_BEGIN_NAMESPACE_CXX11
                                             ^
/usr/lib/gcc/x86_64-linux-gnu/5.2.1/../../../../include/x86_64-linux-gnu/c++/5.2.1/bits/c++config.h:225:51: note:
      expanded from macro '_GLIBCXX_BEGIN_NAMESPACE_CXX11'
# define _GLIBCXX_BEGIN_NAMESPACE_CXX11 namespace __cxx11 {
                                                  ^
In file included from /opt/hhvm/hphp/hhvm/global-variables.cpp:17:
In file included from /opt/hhvm/hphp/runtime/ext/extension.h:21:
In file included from /opt/hhvm/hphp/runtime/base/debuggable.h:19:
In file included from /opt/hhvm/hphp/runtime/base/type-string.h:20:
In file included from /opt/hhvm/hphp/runtime/base/req-ptr.h:20:
In file included from /opt/hhvm/hphp/runtime/base/countable.h:23:
In file included from /opt/hhvm/hphp/util/assertions.h:28:
In file included from /opt/hhvm/third-party/folly/folly/Format.h:24:
In file included from /opt/hhvm/third-party/folly/folly/Conv.h:27:
In file included from /opt/hhvm/third-party/folly/folly/FBString.h:65:
/opt/hhvm/third-party/folly/folly/Traits.h:243:1: warning: inline namespace cannot
      be reopened as a non-inline namespace
FOLLY_GLIBCXX_NAMESPACE_CXX11_BEGIN
^
inline
/opt/hhvm/third-party/folly/folly/Portability.h:230:46: note: expanded from macro
      'FOLLY_GLIBCXX_NAMESPACE_CXX11_BEGIN'
# define FOLLY_GLIBCXX_NAMESPACE_CXX11_BEGIN _GLIBCXX_BEGIN_NAMESPACE_CXX11
                                             ^
/usr/lib/gcc/x86_64-linux-gnu/5.2.1/../../../../include/x86_64-linux-gnu/c++/5.2.1/bits/c++config.h:225:51: note:
      expanded from macro '_GLIBCXX_BEGIN_NAMESPACE_CXX11'
# define _GLIBCXX_BEGIN_NAMESPACE_CXX11 namespace __cxx11 {
                                                  ^
/usr/lib/gcc/x86_64-linux-gnu/5.2.1/../../../../include/c++/5.2.1/bits/locale_conv.h:160:1: note:
      previous definition is here
_GLIBCXX_BEGIN_NAMESPACE_CXX11
^
/usr/lib/gcc/x86_64-linux-gnu/5.2.1/../../../../include/x86_64-linux-gnu/c++/5.2.1/bits/c++config.h:225:51: note:
      expanded from macro '_GLIBCXX_BEGIN_NAMESPACE_CXX11'
# define _GLIBCXX_BEGIN_NAMESPACE_CXX11 namespace __cxx11 {
                                                  ^
In file included from /opt/hhvm/hphp/hhvm/global-variables.cpp:17:
In file included from /opt/hhvm/hphp/runtime/ext/extension.h:21:
In file included from /opt/hhvm/hphp/runtime/base/debuggable.h:19:
In file included from /opt/hhvm/hphp/runtime/base/type-string.h:20:
In file included from /opt/hhvm/hphp/runtime/base/req-ptr.h:20:
In file included from /opt/hhvm/hphp/runtime/base/countable.h:23:
In file included from /opt/hhvm/hphp/util/assertions.h:28:
In file included from /opt/hhvm/third-party/folly/folly/Format.h:24:
In file included from /opt/hhvm/third-party/folly/folly/Conv.h:27:
In file included from /opt/hhvm/third-party/folly/folly/FBString.h:65:
/opt/hhvm/third-party/folly/folly/Traits.h:255:1: warning: inline namespace cannot
      be reopened as a non-inline namespace
FOLLY_GLIBCXX_NAMESPACE_CXX11_BEGIN
^
inline
/opt/hhvm/third-party/folly/folly/Portability.h:230:46: note: expanded from macro
      'FOLLY_GLIBCXX_NAMESPACE_CXX11_BEGIN'
# define FOLLY_GLIBCXX_NAMESPACE_CXX11_BEGIN _GLIBCXX_BEGIN_NAMESPACE_CXX11
                                             ^
/usr/lib/gcc/x86_64-linux-gnu/5.2.1/../../../../include/x86_64-linux-gnu/c++/5.2.1/bits/c++config.h:225:51: note:
      expanded from macro '_GLIBCXX_BEGIN_NAMESPACE_CXX11'
# define _GLIBCXX_BEGIN_NAMESPACE_CXX11 namespace __cxx11 {
                                                  ^
/opt/hhvm/third-party/folly/folly/Traits.h:243:1: note: previous definition is
      here
FOLLY_GLIBCXX_NAMESPACE_CXX11_BEGIN
^
/opt/hhvm/third-party/folly/folly/Portability.h:230:46: note: expanded from macro
      'FOLLY_GLIBCXX_NAMESPACE_CXX11_BEGIN'
# define FOLLY_GLIBCXX_NAMESPACE_CXX11_BEGIN _GLIBCXX_BEGIN_NAMESPACE_CXX11
                                             ^
/usr/lib/gcc/x86_64-linux-gnu/5.2.1/../../../../include/x86_64-linux-gnu/c++/5.2.1/bits/c++config.h:225:51: note:
      expanded from macro '_GLIBCXX_BEGIN_NAMESPACE_CXX11'
# define _GLIBCXX_BEGIN_NAMESPACE_CXX11 namespace __cxx11 {
                                                  ^
2 warnings generated.
2 warnings generated.
2 warnings generated.
Linking CXX executable hhvm
../runtime/libhphp_runtime.a(timezone.cpp.o):/opt/hhvm/hphp/runtime/base/timezone.cpp:function std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* google::MakeCheckOpString<char const*, char const*>(char const* const&, char const* const&, char const*): error: undefined reference to 'google::base::CheckOpMessageBuilder::NewString()'
../runtime/libhphp_runtime.a(timezone.cpp.o):/opt/hhvm/hphp/runtime/base/timezone.cpp:function std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* google::MakeCheckOpString<double, double>(double const&, double const&, char const*): error: undefined reference to 'google::base::CheckOpMessageBuilder::NewString()'
../runtime/libhphp_runtime.a(preg.cpp.o):/opt/hhvm/hphp/runtime/base/preg.cpp:function std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* google::MakeCheckOpString<HPHP::StringData const*, HPHP::StringData const*>(HPHP::StringData const* const&, HPHP::StringData const* const&, char const*): error: undefined reference to 'google::base::CheckOpMessageBuilder::NewString()'
../runtime/libhphp_runtime.a(program-functions.cpp.o):/opt/hhvm/hphp/runtime/base/program-functions.cpp:function HPHP::execute_program_impl(int, char**): error: undefined reference to 'boost::program_options::option_description::long_name() const'
../runtime/libhphp_runtime.a(program-functions.cpp.o):/opt/hhvm/hphp/runtime/base/program-functions.cpp:function HPHP::execute_program_impl(int, char**): error: undefined reference to 'boost::program_options::option_description::format_name() const'
../runtime/libhphp_runtime.a(program-functions.cpp.o):/opt/hhvm/hphp/runtime/base/program-functions.cpp:function boost::program_options::typed_value<bool, char>::name() const: error: undefined reference to 'boost::program_options::arg'
../runtime/libhphp_runtime.a(program-functions.cpp.o):/opt/hhvm/hphp/runtime/base/program-functions.cpp:function boost::program_options::validation_error::validation_error(boost::program_options::validation_error::kind_t, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int): error: undefined reference to 'boost::program_options::validation_error::get_template(boost::program_options::validation_error::kind_t)'
../runtime/libhphp_runtime.a(static-string-table.cpp.o):/opt/hhvm/hphp/runtime/base/static-string-table.cpp:function std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* google::MakeCheckOpString<unsigned long, unsigned long>(unsigned long const&, unsigned long const&, char const*): error: undefined reference to 'google::base::CheckOpMessageBuilder::NewString()'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
hphp/hhvm/CMakeFiles/hhvm.dir/build.make:390: recipe for target 'hphp/hhvm/hhvm' failed
make[2]: *** [hphp/hhvm/hhvm] Error 1
CMakeFiles/Makefile2:2624: recipe for target 'hphp/hhvm/CMakeFiles/hhvm.dir/all' failed
make[1]: *** [hphp/hhvm/CMakeFiles/hhvm.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2
root@u15:/opt/hhvm#
</pre>

**Comment by fredemmott** [comment]
We don't currently support clang, sorry.
