### ISSUE TITLE
AutoTypecheck: Can't use Hack libraries in PHP projects

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#6666]
```
fred@dev:~/hhvm-autoload-map-generator$ hhvm ~/composer.phar --verbose dump-autoload
Generating autoload files
> post-autoload-dump: FredEmmott\AutoloadMap\Bootstrap::build
Script FredEmmott\AutoloadMap\Bootstrap::build handling the post-autoload-dump event terminated with an exception



  [ErrorException]
  Error: could not find a .hhconfig file in /home/fred or any of its parent d
  irectories. Do you have a .hhconfig in your code's root directory?
```

There is one in the current direcotry, but it appears to be looking for a .hhconfig in the directory where composer.phar is located

**Comment by fredemmott** [comment]
Given that the ini settings for this can't be changed at runtime, this means that it is impossible to write composer plugins in Hack.

**Comment by fredemmott** [comment]
Okay, maybe not impossible :p

cc @jwatzman 

```PHP
<?php

namespace FredEmmott\AutoloadMap;

use \__SystemLib\HH\Client\CacheKeys;
use \HH\Client\TypecheckResult;
use \HH\Client\TypecheckStatus;

final class Bootstrap {
  private static function disableTypechecker(): \HH\void {
    /* Theses APC sets and the '<?php' are because of
     * auto-typecheck being over-eager:
     *
     * https://github.com/facebook/hhvm/issues/6666
     */
    touch('/tmp/hh_server/stamp');
    apc_store(CacheKeys::TIME_CACHE_KEY, time());
    apc_store(
      CacheKeys::RESULT_CACHE_KEY,
      new TypecheckResult(TypecheckStatus::SUCCESS, /* error = */ null)
    );
  }

  public static function build(): \HH\void {
    self::disableTypechecker();
```

**Comment by jwatzman** [comment]
Is easily possible for userspace to know if it's running from a phar? If so, should be easy to just disable this check.

- Fairly hot C++ code that calls the PHP function: https://reviews.facebook.net/diffusion/HHVM/browse/master/hphp/runtime/vm/hh-utils.cpp;79bdc658f5a2de70088de7a4bf9ba5e207d031c0$104
- Relevant PHP function, might be easier: https://reviews.facebook.net/diffusion/HHVM/browse/master/hphp/runtime/ext/hh_client/ext_hh_client.php;79bdc658f5a2de70088de7a4bf9ba5e207d031c0$1

For the love of god don't land anything using those APC keys, that's not a stable interface (as the usage of `namespace __SystemLib` is clear :-P)

**Comment by fredemmott** [comment]
I'm looking for a way to disable it without modifying HHVM to keep it working on 3.11.0 - what function were you intending to link to?

**Comment by fredemmott** [comment]
also, it doesn't really matter if I'm running from a phar or not - If I run /path/to/anything.php and that runs ./foo/bar.php which is Hack, it should look in parent dirs of ./foo/bar for .hhconfig instead of /path/to/anything.php

**Comment by fredemmott** [comment]
The only current alternative seems to be a custom error handler, but hardcoding undocumented patterns for the value of $error seems just as bad as touching __SystemLib

**Comment by fredemmott** [comment]
Actually a more general problem:

1. If PHP code (that requires HHVM) uses a Hack library that depends on another Hack library, we have:

```
foo/
foo/vendor/vendorname/hacklib1/
foo/vendor/vendorname/hacklib2/
```

There is no appropriate place for a .hhconfig if 'foo/' itself is a PHP project.

2. Running code from somewhere that is not an ancestor of the class being loaded can not autotypecheck, unless there's a .hhconfig in a common ancestor

Composer problem above, but more generally, if I'm in `/herp/derp` and load `/foo/bar/baz.php':

 - maybe there should be a /foo/bar/.hhconfig that could be loaded...
 - but maybe not - it could reasonably have missing definitions somewhere else entirely that are still valid

This isn't trivial given we still want /foo/bar/src to complain if /foo/bar is a hack project and we're in /foo/bar/public and there's no /foo/bar/.hhconfig - but not if we're in /foo/someotherproject 

Suggested Fix
---------------------

If current behavior fails:

1. Also look for .hhconfig in the ancestor directories of the file being loaded
2. if there is one, but we didn't find one for the overall project, don't error or typecheck
3. If there isn't any, raise the current error for no hhconfig

**Comment by fredemmott** [comment]
Another option: once we have added `<?hh // entrypoint`, don't typecheck if entrypoint is <?php.

Possibly makes the whole thing useless as being too easy to avoid.

**Comment by fredemmott** [comment]
Or.... we just don't autotypecheck for CLI?

cc @sgolemon , @jwatzman ping

**Comment by jwatzman** [comment]
CLI is where a lot of the oversights that auto-typecheck was supposed to catch were coming up, unfortunately. (Not as many as server mode, but quite a few.) The whole "no good way to put an hhconfig into a composer package" problem is definitely an obnoxious and related one, that I wanted to solve this half but ran out of time :)

Since I'm in the middle of my move, I'm kind of behind on this thread, and not 100% sure I'm following what you're suggesting anyways... we can call/VC some time next week or the week of Jan 11 when I get to London?

**Comment by fredemmott** [comment]
For others: I'm likely to add `HH\disable_auto_typecheck_for_build_step()` or similar; other uses will be unsupported. This will need to be called by PHP code before any hack code is executed.

**Comment by fredemmott** [comment]
@mofarrell : any thoughts on this? An easy solution could just be to make ini_set('hhvm.hack.lang.look_for_typechecker', <bool>) work

**Comment by fredemmott** [comment]
Better temporary workaround: https://github.com/fredemmott/hack-error-suppressor

**Comment by mofarrell** [comment]
@fredemmott Wow nice temporary solution.  Fixing `ini_set` for this `hhvm.hack.lang.look_for_typechecker` does seem like a easy way to get this working.  In general, I think the `hhvm.` options are not modifiable in scripts.  I still think it might be the way go.

How hard it would be to get the search paths working for this case?  Couldn't it just use the current behavior, but start its search from the file being loaded?

**Comment by fredemmott** [comment]
That only fixes the composer plugin/phar problem, not writing build steps or installers in hack

**Comment by fredemmott** [comment]
also, using the file-to-be-loaded would be incorrect: if the file is in foo/vendor/herp/derp, it needs to use foo/.hhconfig, not foo/vendor/herp/derp/.hhconfig

**Comment by mofarrell** [comment]
I was thinking it would search recursively upwards.

**Comment by fredemmott** [comment]
Not just in the way it currently does - when it finds one, it would need to keep searching parent directories all the way to / to see if there's another one that overrides it.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

There is no interoperability between PHP and hhvm anymore since hhvm version [4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html).
