### ISSUE TITLE
HHVM allow access to files with 000 permission

### ISSUE THREAD

**Issue by hmvar** [facebook/hhvm#6683]
I'm trying to setup a magento store to run with HHVM and Proxygen on CentOS
Everything is working perfectly, but I can access files from the browser even when I don't have read permission. I've changed the permission to 000 on some files and I was still able to access them on the browser and through wget.

**Comment by fredemmott** [comment]
What user is hhvm running as?

**Comment by hmvar** [comment]
Sorry, my mistake I was running it as root.
