### ISSUE TITLE
Small typo in the official docs

### ISSUE THREAD

**Issue by StoneWolf** [facebook/hhvm#6688]
https://docs.hhvm.com/hhvm/advanced-usage/fastCGI

Paragraph "Making it work with nginx":
Shouldn't "Now nginx **is** needs to be configured to know where your PHP files are and how to forward them to HHVM to execute." be instead "Now nginx needs to be configured to know where your PHP files are and how to forward them to HHVM to execute." ?

**Comment by fredemmott** [comment]
Could you file an issue here? https://github.com/hhvm/user-documentation/issues

The 'report a problem or make a suggestion' links/buttons at the top and bottom of each page should take you there - if that didn't happen, please file another issue against the documentation for that :)

**Comment by StoneWolf** [comment]
Sorry, I didn't see that. Will post there.
