### ISSUE TITLE
No PHP 7 release yet?

### ISSUE THREAD

**Issue by ricordisamoa** [facebook/hhvm#6692]
Version 7.0.0 of the official PHP engine has been released 20 days ago; that had even been scheduled to happen [3 weeks before](//wiki.php.net/todo/php70?rev=1442320590#timetable).
Being employed by a giant company, I had no doubt that the HHVM team was closely following Zend and would have reached full feature parity since the first RCs, taking advantage of the competitor's delay to test it even longer. But AFAICS HHVM 3.11.0 is still considered unstable.
From the previous releases, it seems that your cycle is anything but slow-paced. Has anything gone wrong with the schedule?
Just wondering, please don't take it personally :smiley:

**Comment by SiebelsTim** [comment]
3.11.0 has been released 14 days ago if I see correctly.
https://github.com/facebook/hhvm/releases

also, see http://hhvm.com/blog/10859/php-7-support

**Comment by ricordisamoa** [comment]
"3.11.0 [...] will be delayed to ensure PHP 7 stability"
https://docs.hhvm.com/hhvm/installation/release-schedule#dates

**Comment by SiebelsTim** [comment]
I assume that's outdated as the packages ship 3.11.0

http://dl.hhvm.com/ubuntu/dists/wily/main/binary-amd64/Packages

**Comment by fredemmott** [comment]
Yep. Filed https://github.com/hhvm/user-documentation/issues/240 to update the docs

3.11.0 is "a stable release", but yes, there are some issues and we're planning a 3.11.1 as soon as they're sorted (https://github.com/facebook/hhvm/issues/6685)

**Comment by ricordisamoa** [comment]
I understand now, thank you.
