### ISSUE TITLE
No response from terminal with hhvm command

### ISSUE THREAD

**Issue by mrdShinse** [facebook/hhvm#6693]
when I input hhvm command. Terminal deoesn't response.

[environment]
Ubuntu 15.10
HipHop VM 3.11.0
Composer 1.0-dev

    vagrant@vagrant-ubuntu-trusty:/var/www/html$ cat test2.hh
    <?hh
    require_once 'vender/facebook/xhp-lib/init.php';
    echo <p>test</p>;
    vagrant@vagrant-ubuntu-trusty:/var/www/html$ sudo hhvm test2.hh
Why??

If I remove .hhconfig file and input "touch .hhconfig" command, "hhvm test.hh" success one time. But, I re-try "hhvm test.hh" and no-response....

    vagrant@vagrant-ubuntu-trusty:/var/www/html/project$ sudo rm .hhconfig 
    vagrant@vagrant-ubuntu-trusty:/var/www/html/project$ sudo touch .hhconfig
    vagrant@vagrant-ubuntu-trusty:/var/www/html/project$ sudo hhvm test.hh
    <p>test</p>vagrant@vagrant-ubuntu-trusty:/var/www/html/project$ 
    vagrant@vagrant-ubuntu-trusty:/var/www/html/project$ sudo hhvm test.hh
    ^Cvagrant@vagrant-ubuntu-trusty:/var/www/html/project$ 
I guess some service got lock of .hhconfig file... Does someone give me hint??

**Comment by elijahb** [comment]
Hi, this also started happening to me after installing version 3.11, and it happens when using Nuclide at the same time. If I close it, hhvvm continues.

**Comment by SiebelsTim** [comment]
Sounds typecheckerrelated.

cc @dlreeves  @int3

**Comment by simonwelsh** [comment]
Yeah, this sounds like #6671

**Comment by oyamauchi** [comment]
If you set HHVM to not look for the typechecker, does this go away?

```
$ sudo hhvm -d hhvm.hack.lang.look_for_typechecker=0 test.hh
```

**Comment by fredemmott** [comment]
#6671
