### ISSUE TITLE
Questions about HHVM and caching. 

### ISSUE THREAD

**Issue by chromafunk** [facebook/hhvm#6694]
I've been looking for asnwers to this but I seem not to be able to get a response, so I will drop here some questions : 

-Does HHVM integrates APCU ? What kind of object caching it does if it does any ? 

-Would it be redundant to try to use APCU with HHVM ?

-If you are using a caching layer like Varnish in front of it, can you improve the performance of HHVM for the non-cached requests with other caching layer working with HHVM ?

-HHVM integrated cache works on disk and not on memory. Is there a way to use Redis, for example, to work on memory instead ? 

Thank you for the clarification.

**Comment by fredemmott** [comment]
- `apc_store()` and `apc_fetch()` are built-ins in HHVM and function the same way as in PHP

 - in general no, but it depends on your application. Benchmark/profile to see.

 - having a caching layer like varnish in front of PHP, HHVM, or anything else will generally slow down non-cached requests slightly. Using HHVM doesn't change how you optimize requests or use application-layer caches.

 - Yes, use the same functions for redis/memcached/apc as you would in PHP.
