### ISSUE TITLE
include/require  perfomance

### ISSUE THREAD

**Issue by R-omk** [facebook/hhvm#6696]
Why is so slow with include/require statement ? 

```
<?php
$milliseconds = round(microtime(true) * 1000);
$l=3000000;
for ($index = 0; $index < $l; $index++) {
//  include __DIR__.DIRECTORY_SEPARATOR.'a.php';  // php7(opcache) faster x8.6
  require_once __DIR__.DIRECTORY_SEPARATOR.'a.php'; // php7(opcache) faster x22
}
$total = round(microtime(true) * 1000) - $milliseconds;

$milliseconds = round(microtime(true) * 1000);
for ($index = 0; $index < $l; $index++) {
}
$total = $total - (round(microtime(true) * 1000) - $milliseconds);

print_r($total . "\n\n");
```

a.php is just empty.

I also tested Repo Authoritative mode, but no perfomanse difference with this statements.

I have not tested it but I think that the previous php version is also faster.

**Comment by WizKid** [comment]
How are you testing? You are sure the JIT is on and the JIT is warmed up?

**Comment by fredemmott** [comment]
Closing as we do not investigate micro benchmarks - they generally have no relevance to real world performance.

**Comment by R-omk** [comment]
https://3v4l.org/6BhJ5/perf#tabs

But I was testing both warmed up and cold on own machine.
There are frameworks based on the use require_once statement. Such constructs can be used many times.
I suppose that it is necessary to pay attention to the design, perhaps there's just some piece misunderstanding.
