### ISSUE TITLE
hhvm error_log not handle \n well

### ISSUE THREAD

**Issue by netroby** [facebook/hhvm#6698]
In php, we can log PHP_EOL to error_log using error_log function.
but hhvm not handle PHP_EOL or \n well.
```
all_user_func()\n#7 /www/ex-phpsource/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\\EventManager\\EventManager->triggerListeners()\n#8 /www/ex-phpsource/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\\EventManager\\EventManager->trigger()\n#9 /www/ex-phpsource/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\\Mvc\\Controller\\AbstractController->dispatch()\n#10 (): Zend\\Mvc\\DispatchListener->onDispatch()\n#11 /www/ex-phpsource/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func()\n#12 /www/ex-phpsource/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\\EventManager\\EventManager->triggerListeners()\n#13 /www/ex-phpsource/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\\EventManager\\EventManager->trigger()\n#14 /www/ex-phpsource/public/index.php(12): Zend\\Mvc\\Application->run()\n#15 {main} \n/www

```

**Comment by simonwelsh** [comment]
You probably want to set the `hhvm.log.always_escape_log` INI setting to `false`

**Comment by netroby** [comment]
But does this means less safe than default setting?

**Comment by netroby** [comment]
Escape string seems ok for me ,but please do not escape PHP_EOL or \n, Escape html tags i think reasonable.

**Comment by SiebelsTim** [comment]
@netroby The reason for this is to make the log more machine readable. It's easier to process one error per line.

This simple changes '\n' to a line break. This is not about security.
If you are going to show logs in a web browser you should escape on your end.

**Comment by fredemmott** [comment]
This is documented on the ini settings change. There is no security issue, the default is purely to make the logs machine-parsable.
