### ISSUE TITLE
Add support for AWS ElastiCache Cluster Client

### ISSUE THREAD

**Issue by nikolay** [facebook/hhvm#6702]
It's Amazon's fork of the Memcached extension, which supports Amazon's Autodiscovery for high availability: https://github.com/awslabs/aws-elasticache-cluster-client-memcached-for-php

**Comment by r3wt** [comment]
:+1:

**Comment by fredemmott** [comment]
This is probably best created/maintained as a separate extension, not in HHVM, given that we have nothing internal or in our test infra covering AWS.

**Comment by nikolay** [comment]
@fredemmott Okay. Can you provide a little bit of guidance on how to best approach this, please?

**Comment by fredemmott** [comment]
http://blog.golemon.com/2015/01/hhvm-extension-writing-part-i.html is probably the best starting point; https://github.com/PocketRent/hhvm-pgsql/ may be useful for reference
