### ISSUE TITLE
Use HHVM as php-cgi

### ISSUE THREAD

**Issue by amarc** [facebook/hhvm#6703]
Hello,

i want to use HHVM as php-cgi alternative with Apache so I did:

    /usr/bin/update-alternatives --install /usr/bin/php-cgi php-cgi /usr/bin/hhvm 70

but I get Error 500 on Apache and I have this in log:

    Nothing to do. Either pass a .php file to run, or use -m server

I am running apache mpm_event with mod_fcgid and this vhost:

    <VirtualHost *:8090>
       ServerAdmin hello@site.com
        ServerName site.com
        ServerAlias www.site.com
        DocumentRoot /var/www/vhosts/user/www/site.com
        SuexecUserGroup user user

        LogLevel warn
        ErrorLog "/var/log/apache2/_error.log"
        CustomLog "/var/log/apache2/_access.log" combined

        <Directory "/var/www/vhosts/user/www/site.com">
                DirectoryIndex index.php index.html
                AddHandler fcgid-script .php
                Options ExecCGI FollowSymLinks
                AllowOverride All
                allow from all
                FCGIWrapper /var/www/vhosts/user/cgi-bin/php-wrapper .php
                Action application/x-httpd-php /usr/bin/php-cgi
        </Directory>

</VirtualHost>

and php-wrapper is like this:

    #!/bin/sh
    PHPRC="/etc/hhvm/"
    PHP_FCGI_CHILDREN=0
    PHP_FCGI_MAX_REQUESTS=0
    export PHPRC PHP_FCGI_CHILDREN PHP_FCGI_MAX_REQUESTS
    exec /usr/bin/php-cgi

Any tips running HHVM as regular php-cgi ? For various reasons I need this as I need to run multiple vhosts/users and run php as each user so my idea is to administer this with apache and mod_fcgid/suexec.

 ty.

**Comment by fredemmott** [comment]
HHVM does not support CGI - you either need to use it's built-in webserver or FastCGI.
