### ISSUE TITLE
Pregenerated lexer/parser files should not be included in git

### ISSUE THREAD

**Issue by paravoid** [facebook/hhvm#6705]
(At least) the lexer & parser are generated using make-lexer.sh and make-parser.sh but a pregenerated copy of them is included in the source tree. The build system is not detecting changes to the original files and rebuilding the .cpp/.hpp files, which is quite counter-intuitive. It's also against distributions' policies (at least Debian's and Fedora's) to ship pregenerated files like that and not use the "preferred form of modification".

I'd propose to:
- integrate make-lexer.sh/make-parser.sh into the build system
- always re-generate them if bison/flex are found in the system (we already have CMake/FindBISON.cmake and CMake/FindFLEX.cmake)
- stop shipping the pregenerated files *at least in git*. If you're really worried about build dependencies, you could potentially ship them in the official tarballs, although I'd probably wouldn't ship them there either.

**Comment by nikic** [comment]
Given how HHVM already [requires](https://docs.hhvm.com/hhvm/installation/building-from-source#ubuntu-14.04-trusty) 55 dependencies to build, I doubt adding two more will be a major issue. Flex and bison should be widely available.

**Comment by fredemmott** [comment]
Agree in general, but not for flex/bison: incompatibilities between versions are just too frequent, and requiring a specific version is a pain.

**Comment by paravoid** [comment]
The breakages we've seen so far have been between bison 2.x and bison 3 aren't they? (I was involved with #2573 and #6674). This was mainly because Facebook has been running and testing with 2.x which is a bit old by now.

In any case, these reveal real bugs that should be caught and fixed, shouldn't they?

**Comment by fredemmott** [comment]
We've seen BC incompatibilities between various values of x that can not be fixed in a way that also supports older versions of Bison, and I've seen this in several other projects. If this has stopped with Bison 3, we need to wait until the distros we support all include Bison 3.

**Comment by paravoid** [comment]
We've been building HHVM with various minor releases of Bison 3 since at least 3.2. master is currently broken, #6674 fixes this. In both cases of breakages, the incompatibilities haven't been Bison's fault, but rather the assumptions that `make-parser.sh` made when post-processing the C++ output with sed(!). Adjusting the seds was the fix both times and in both it was done in (I think) a backwards-compatible way, so the current source (w/ #6674) would work against both 2.x (for whichever x FB currently runs), and 3.0.y.

**Comment by fredemmott** [comment]
IIRC we used to rebuild the parser (though for some reason still included the generated files in the tree), but too many users had incompatible bisons that required non-BC changes to the grammar.

Needs to support at least:

 - 2.4
 - 2.5 (Wheezy)
 - 3.x

If that's not a problem, we can revisit it after 3.12 (so if it turns out this does break anyone we support, they still get a year of security updates, compared to a month if they're currently on 3.6 and we change this before 3.12).

**Comment by paravoid** [comment]
That makes sense, thanks for considering it :)
