### ISSUE TITLE
missing SoapClient constants from PHP 5.5.0

### ISSUE THREAD

**Issue by jurchiks** [facebook/hhvm#6709]
http://php.net/manual/en/soapclient.soapclient.php
The ssl_method option is one of SOAP_SSL_METHOD_TLS, SOAP_SSL_METHOD_SSLv2, SOAP_SSL_METHOD_SSLv3 or SOAP_SSL_METHOD_SSLv23.

Changelog
5.5.0	New ssl_method option.

All 4 of these constants are missing in 3.11.0, and I'm wondering if the option itself is also missing.

**Comment by fredemmott** [comment]
Sorry, that option isn't yet implemented:

https://github.com/facebook/hhvm/blob/master/hphp/runtime/ext/soap/ext_soap.cpp#L2436

Note for whoever implements this: a similar warning to https://github.com/facebook/hhvm/blob/85d3041838dce60e16987978c604105a0b731288/hphp/runtime/ext/stream/ext_stream.cpp#L736-L740 should be added if any of these constants other than _TLS is passed in.

**Comment by jurchiks** [comment]
I don't think this is "probably easy" because besides adding the constants, you also need to add the actual support for changing the encryption method.
Also, `5.4.0 New keep_alive option.` is also missing.

**Comment by fredemmott** [comment]
That's still probably easy given we have mode switching code for stream_socket_enable_crypto and other context options, and soapclient is built on top of the stream code

**Comment by jurchiks** [comment]
Well, I'm planning to work on it sometime soon, so I guess I'll see how easy it will be. I have never really seriously programmed in C++.
