### ISSUE TITLE
3.11 regression: value of XML_ATTRIBUTE_ENTITY has changed

### ISSUE THREAD

**Issue by simonwelsh** [facebook/hhvm#6711]
In versions prior to HHVM 3.11.0, and in PHP, XML_ATTRIBUTE_ENTITY is 6. In 3.11.0, it is now 5.

See https://3v4l.org/IpM1i

This may be related to 49bf021.

**Comment by Orvid** [comment]
PHP appears to define `XML_ATTRIBUTE_ENTITY` as `XML_ATTRIBUTE_ENTITIES`, so the RC_SAME isn't correct here.
