### ISSUE TITLE
getimagesize fails occasionally if missing second (optional) argument

### ISSUE THREAD

**Issue by Zenexer** [facebook/hhvm#6712]
getimagesize will return `false` without explanation for certain images when only a single argument is passed.  Adding a throwaway variable as the second argument is a valid workaround.  This creates incompatibilities with numerous popular web applications, including XenForo.

You can see such an image here: https://www.namepros.com/data/avatars/l/949/949273.jpg?1404107788  The image is opened via a stream wrapper, so the improper MIME type is irrelevant.

This could be related to #2985.

**Comment by aorenste** [comment]
I cannot repro this with the latest HHVM.
