### ISSUE TITLE
MySQLi->multi_query not setting error if first query fails

### ISSUE THREAD

**Issue by HRMsimon** [facebook/hhvm#6714]
If the first result set in a multi query is an error, then the `error` and `errno` values aren't set on the connection object. If a normal query is used, or if the second result set is the one with the error, then the values are set correctly.

``` php
<?php

$con = new MySQLi('localhost', 'root', '', 'mysql');
$res = $con->multi_query('SHOW TABLES1');
var_dump('First query', $res, $con->error, $con->errno);

$res = $con->multi_query('SHOW TABLES; SHOW TABLES1');
var_dump('Second query, first result', $res);
$con->store_result();
$res = $con->next_result();
var_dump('Second query, second result', $res, $con->error, $con->errno);
```

outputs:

```
string(11) "First query"
bool(false)
string(0) ""
int(0)
string(26) "Second query, first result"
bool(true)
string(27) "Second query, second result"
bool(false)
string(155) "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'TABLES1' at line 1"
int(1064)
```

This is with HHVM-3.11, though we've seen it for some time.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This issue depends on ext/mysqli, wihch has been removed from hhvm in version [4.9.0](https://hhvm.com/blog/2019/06/10/hhvm-4.9.0.html).
