### ISSUE TITLE
Recommended way to run HHVM using CLI?

### ISSUE THREAD

**Issue by thibaultlavoisey** [facebook/hhvm#6718]
Hello,

I use HHVM to run a Laravel project. Laravel provides task scheduling using Cron to execute many commands.

However, this feature is slow and use 100% of the CPU. I saw on the Web it's because HHVM needs warm up.

Someone recommended me to use PHP binary to execute scheduled tasks using CLI but there are two inconvenients:
- It requires to maintain to HHVM and PHP (main package but also MySQL for example) on the server
- If someone of the team needs to run Artisan command manually he must be careful as "php" is an alias of HHVM binary

I found a setting to disable HHVM JIT on the fly ("hhvm -v Eval.Jit=0 /var/www/project/artisan command"): it works if I execute the command manually but it doesn't work if the command is executed via Cron :/

Is there a recommended way to run HHVM using CLI?

 Thanks

Bye

**Comment by fredemmott** [comment]
`-v Eval.Jit=0` is correct. What is showing you that it "doesn't work" from cron? We don't do anything special.

**Comment by thibaultlavoisey** [comment]
Hello @fredemmott,

I think it doesn't work because if I execute the command manually the output is fast and the CPU is not busy. When the command is executed from Cron, the output is slower and the CPU is busy (100% each time the command is executed). After some time, the CPU is less busy (50%). After some time again, the CPU is less busy again (25%). After some time again the CPU is not busy anymore when a command is executed from Cron (0%) and the RAM usage increased. 

Here is the graph of the CPU usage:

<img width="767" alt="screen shot 2016-01-08 at 09 56 07" src="https://cloud.githubusercontent.com/assets/2022117/12194535/13891ed4-b5f1-11e5-94f9-79b216a681f5.png">

I think it looks like a warm up time, no?

Here is the Cron (in /etc/cron.d/project) :

```
* * * * * www-data hhvm -v Eval.Jit=0 /var/www/project/artisan command >> /dev/null 2>&1
```

No problem using PHP-FPM.

Thanks

Bye

**Comment by fredemmott** [comment]
Is 'some time' between multiple runs of the job, or one long-running job?

**Comment by thibaultlavoisey** [comment]
'some time' is between multiple runs of the job.

**Comment by fredemmott** [comment]
This is not JIT warmup: the JIT cache only lasts for one process.

**Comment by thibaultlavoisey** [comment]
Ok, so it's no due to HHVM?

**Comment by fredemmott** [comment]
It's not HHVM JIT warmup. There's no evidence either way for if it is HHVM or not.
