### ISSUE TITLE
hphpd: default to Hack code

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#6728]
By default, it's not possible to use Hack features (collections, lambdas, XHP) in hphpd. This can be fixed by specifying `-d hhvm.force_hh=1`

I suggest:
- adding a new setting for debugger mode with values of 'hack', 'php5', 'php7'
- add a convenience CLI flag (eg `hhvm -m debug --php7`)
- if nothing specified on CLI or INI file, default to Hack and print out single-line warning/info on the above

**Comment by jurchiks** [comment]
Better make that `--compat php7` or something like that.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

The default value of `force_hh` has been changed to true in hhvm [4.9.0](https://hhvm.com/blog/2019/06/10/hhvm-4.9.0.html). I believe the hphpd issue was already fixed earlier.
