### ISSUE TITLE
Readline() has a required parameter but it should be a optional parameter

### ISSUE THREAD

**Issue by mbutkereit** [facebook/hhvm#6731]
function readline(string $prompt): mixed;

$prompt is in hhvm required and in php optional.

https://github.com/facebook/hhvm/blob/master/hphp/runtime/ext/readline/ext_readline.php 
http://php.net/manual/en/function.readline.php

**Comment by noony** [comment]
Can be closed by https://github.com/facebook/hhvm/commit/2ba88997d3b70bc6e872749f243bd299ebd1c888
