### ISSUE TITLE
Building and Installing HHVM on Centos7

### ISSUE THREAD

**Issue by Azuraxe** [facebook/hhvm#6732]
Hello,
I'm currently up to the multi thread compiling stage:
make -j$(($(nproc)+1))

and get this following error: 
http://pastebin.com/WkjPsM6x

I've followed the tutorial and haven't got an errors until now.

Thanks,

**Comment by Azuraxe** [comment]
Got another error after a few hours of it building itself 
[ 48%] Building CXX object hphp/compiler/CMakeFiles/hphp_analysis.dir/analysis/emitter.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
make[2]: *** [hphp/compiler/CMakeFiles/hphp_analysis.dir/analysis/emitter.cpp.o] Error 4
make[1]: *** [hphp/compiler/CMakeFiles/hphp_analysis.dir/all] Error 2
make: *** [all] Error 2

**Comment by simonwelsh** [comment]
You don't have enough ram for the number of jobs you're trying to run. Either, increase your ram or use a small value for -j.

**Comment by Azuraxe** [comment]
Thank you very much Simon. Unfortunately I'm having issues now with the php files downloading instead of displaying. 

I'm running Nginx, FastCGI and HHVM. I'm not sure what needs to be done. If there is a guide for this it'd be fantastic. I'm using Centos 7. 

Thanks!

**Comment by Azuraxe** [comment]
No /usr/share/hhvm/install_fastcgi.sh is generating so I can't include the hhvm.conf.

All that is in my hhvm folder is a php.ini
http://prntscr.com/9o9w31

**Comment by JoelMarcey** [comment]
We don't officially support CentOS 7, but what happens if you try a simple server like described here:

https://docs.hhvm.com/hhvm/basic-usage/server

Basically, take Nginx and FastCGI out of the equation and see what happens using the builtin webserver, even on a simple hello world program.

**Comment by Azuraxe** [comment]
Hey Joel,
I've removed Nginx, and FastCGI, and reinstalled HHVM, however when I run the command: 
hhvm -m server -p 8080

No update occurs, it doesn't finish running the command. I've waited about 15 minutes. (http://prntscr.com/9okqkm)

And as you can probably see, http://128.199.230.91:8080 is refusing the connection.

Thanks,
Mas

**Comment by JoelMarcey** [comment]
What version of HHVM are you using? If it is 3.11, this might be a known problem.

**Comment by Azuraxe** [comment]
Since I wasn't able to compile a Centos 7 version, I found a repo (https://www.ulyaoth.net/resources/hhvm-lts-3-6.22/)


I could try and reinstall a later version, since the one that I'm  using looks like it's 3.6?

**Comment by Azuraxe** [comment]
Any update?

**Comment by fredemmott** [comment]
`hhvm -m server` is meant to never return, it just runs the server. If you want it to go into the background, you want `-m daemon`

3.12 has not been released yet.

**Comment by Orvid** [comment]
The first issue was already resolved, so I'm closing this for now. If the second issue is still a problem, please open a separate issue for it.
