### ISSUE TITLE
MySQL persistent connection never working if mysqli.max_persistent=-1 (default value)

### ISSUE THREAD

**Issue by nilwave** [facebook/hhvm#6734]
From hphp/runtime/ext/mysql/mysql_common.cpp:

 if (MySQL::IsAllowPersistent() && 
628       MySQL::GetCurrentNumPersistent() < MySQL::GetMaxNumPersistent() && 
629       persistent) { 
630     auto p_mySQL = MySQL::GetPersistent(host, port, socket, username, 
631                                         password, client_flags); 

MySQL::GetMaxNumPersistent() = -1 (default value) -> if never passing, I suggest

if (persistent && (MySQL::IsAllowPersistent() && (MySQL::GetMaxNumPersistent() == -1 || (MySQL::GetCurrentNumPersistent() < MySQL::GetMaxNumPersistent() ))))

**Comment by nilwave** [comment]
Also please note that if mysqli.reconnect = 0 (default value) mysql persistent connections will not work.

To make persistent connections work properly:

mysqli.reconnect = 1
mysqli.max_persistent = 999 (??)

**Comment by aorenste** [comment]
Probably related to #6542

**Comment by nilwave** [comment]
It's not related to #6542

**Comment by aorenste** [comment]
@nilwave - You're right.  I misread what you were saying when I quickly looked at this issue (and since about 4 other issues were related to 6542).  This seems to be that we're not treating (max_persistent == -1) as infinite.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This issue is is about etc/mysqli, which has been removed from hhvm in version [4.9.0](https://hhvm.com/blog/2019/06/10/hhvm-4.9.0.html).
