### ISSUE TITLE
ReflectionParameter - incorrect scalar types

### ISSUE THREAD

**Issue by jurchiks** [facebook/hhvm#6739]
```php
<?php
function foo(string $a, int $b, float $c, bool $d)
{
}

$reflectionFunction = new ReflectionFunction('foo');
$functionParameters = $reflectionFunction->getParameters();

foreach ($functionParameters as $parameter)
{
	var_dump($parameter->getType()->__toString());
}

```

Output:
```
string(9) "HH\string"
string(6) "HH\int"
string(8) "HH\float"
string(7) "HH\bool"
```

As a result, my framework, which uses reflection to read the expected data types of route handler parameters, breaks on hhvm.

**Comment by JoelMarcey** [comment]
@jurchiks It was intentional that we return `HH\string`, `HH\int`, etc. because that is indeed what the types are in this case. So they are not incorrect. An argument can be made that we have a compatibility issue, sure. 

I can think about maybe allowing an ini setting to control which ones get output. That could be a way to get around this. But that is just an off the top thought.

cc @fredemmott @sgolemon if they want to chime in here.

**Comment by jurchiks** [comment]
Well, since Hack and PHP 7 scalar types are the same, you should move to PHP 7 types.

**Comment by fredemmott** [comment]
https://3v4l.org/mqCIb

```
fred@hhvm-oss-bench:~/hhtest$ hhvm --no-config test.php
string(6) "string"
string(3) "int"
string(5) "float"
string(4) "bool"
```

**Comment by fredemmott** [comment]
```
fred@hhvm-oss-bench:~/hhtest$ hhvm --no-config -d hhvm.php7.scalar_types=true test.php
string(9) "HH\string"
string(6) "HH\int"
string(8) "HH\float"
string(7) "HH\bool"
```

For PHP5 code, we consider them to be classnames (and need to continue doing this); for PHP7 code, we need to treat them as equivalent to the HH types, but not report that as their name.

**Comment by JoelMarcey** [comment]
I think that shouldn't be too hard to get working. I can give this a go.

**Comment by jurchiks** [comment]
Thanks, much appreciated!

**Comment by fredemmott** [comment]
Ideally we should keep the HH prefix for force_hh and Hack code, as some stuff might care about the difference. One approach would be make them `__SystemLib\PHP7\string` or similar, and strip that prefix in reflection

**Comment by jurchiks** [comment]
As long as it works the same in PHP and HHVM.

**Comment by JoelMarcey** [comment]
Internal diff up: D2828116
