### ISSUE TITLE
ReflectionParameter - discrepancies between PHP7 and HHVM

### ISSUE THREAD

**Issue by jurchiks** [facebook/hhvm#6741]
https://gist.github.com/jurchiks/b6d35a6e054f2f7978fe
As you can see by the output, there are several issues with ReflectionParameter class in HHVM:
1) scalar type hints are named incorrectly, they all start with "HH\"; as such, PHP7's getType() is broken in HHVM. I've made a separate issue here: #6739
2) for type hints `callable` and `resource`, you get `Uncaught Error: Call to undefined method ReflectionParameter::isDefaultValueConstant()`

**Comment by jurchiks** [comment]
@JoelMarcey perhaps you could also look into # 2 here? I think this one should be even simpler to fix than the first one.

**Comment by JoelMarcey** [comment]
Internal diff up for #1: D2828116

**Comment by JoelMarcey** [comment]
Internal diff up for #2: D2830424
