### ISSUE TITLE
No HHI for XHProf

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#6744]
Probably best done by an FB employee, as we already have these internally, just marked as fbonly for some reason.

**Comment by DemiMarie** [comment]
Ping?

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This hhi entries have been pulished at [builtins_fb.hhi](https://github.com/facebook/hhvm/blob/3d90af43805bef562b213efff3d0b3fb62a5200d/hphp/hack/hhi/builtins_fb.hhi#L59).
