### ISSUE TITLE
Hack definition of ArrayAccess does not match runtime definition

### ISSUE THREAD

**Issue by dk-zero-cool** [facebook/hhvm#6745]
For some reason the `ArrayAccess` interface does not work when used with Hack. It works fine if used with pure PHP. 

``` php
<?hh
class Test implements ArrayAccess<string, string> {
    public function offsetSet(string $name, string $value): void {

    }

    public function offsetExists(string $name): bool {
        return false;
    }

    public function offsetUnset(string $name): void {

    }

    public function offsetGet(string $name): string {
        return "";
    }
}
```

```
Fatal error: Declaration of Test::offsetExists() must be compatible with that of ArrayAccess::offsetExists()
```

The above example fails.

``` php
<?php
class Test implements ArrayAccess {
    public function offsetSet($name, $value) {

    }

    public function offsetExists($name) {
        return false;
    }

    public function offsetUnset($name) {

    }

    public function offsetGet($name) {
        return "";
    }
}
```

This one works fine. Both example is executed with the `HHVM` server.

**Comment by fredemmott** [comment]
https://github.com/facebook/hhvm/blob/8b42adf12ee4973b8c9ad71c1aeeba74304336a7/hphp/system/php/lang/ArrayAccess.php

As far as HHVM is concerned, offsetGet must be willing to take *any* $name, so your PHP example is fine - however, your hack version only takes strings, so is not compatible.

**Comment by dk-zero-cool** [comment]
Okay, is there a similar interface in hack then? One without to much additional stuff like iterates etc. I have looked through a lot of interfaces described in the docs, but they seriously lack information.

**Comment by fredemmott** [comment]
I don't think so; cc @sgolemon . The interfaces we have at the moment were designed for flexiblity we never took advantage of or made possible for others to take advantage of. Hopefully they can be simplified (most of them simply removed) at some point.

**Comment by dk-zero-cool** [comment]
Your first explanation indicated that the issue was that I did not allow mixed type. This seams to be true. The code below works fine, but only is included into a `php` file. Hack now gives me a different issue, one I think would be fixable. 

```php
<?hh
class Test implements ArrayAccess<mixed, mixed> {
    if (is_string($name)) {
            
    }

    public function offsetExists(mixed $name): bool {
        if (is_string($name)) {
            return false;
        }

        return false;
    }

    public function offsetUnset(mixed $name): void {
        if (is_string($name)) {
            
        }
    }

    public function offsetGet(mixed $name): mixed {
        if (is_string($name)) {
            return null;
        }

        return null;
    }
}
```
```
Catchable fatal error: Hack type error: This is not an object of type KeyedContainer
```

**Comment by fredemmott** [comment]
You get the full error for that when using `hh_client`; HHVM is only able to show a truncated version of the typechecker errors.

**Comment by dk-zero-cool** [comment]
```
system/core/Runtime.hh:257:18,44: This is not an object of type KeyedContainer, this is an object of type core\utils\Bundle (Typing[4005])
  system/core/Runtime.hh:199:19,25: You might want to check this out
```
It does not longer complaint when including the file, no ArrayAccess errors. Creating an instance of the class is no problem either. I only get error when trying to access the instance like an array `$inst["key"]`. If I include the ArrayAccess extended hack file into a normal php file, I can access the object as an array just fine. 

So ArrayAccess works with mixed data types, but it seams as the hhvm server/typechecker refuses to accept ArrayAccess, or rather does not check it to begin with. Also adding the `KeyedContainer` interface to the class does not help, it keeps giving the same error.

**Comment by fredemmott** [comment]
Sorry if I was unclear: I was explaining why HHVM/Hack don't like this; I didn't mean to imply that there is a form that it does like, and fundamentally the definitions in HHVM and Hack are incompatible. This does seem like a real problem.

**Comment by simonwelsh** [comment]
Hack doesn't support ArrayAccess on user land classes. Should probably be added to https://docs.hhvm.com/hack/unsupported/others

**Comment by SiebelsTim** [comment]
What's the solution? Using a `KeyedContainer`?

**Comment by dk-zero-cool** [comment]
Well I will just try to live without this small feature for now, but future support for array like custom objects would be great. Both `$inst[""]` as well as `CustomClass {}`. The last especially since it would allow instantiating custom classes on properties, which is a big deal in Hack due to it's `Nullable` type which causes a lot of problems on static properties. 

Lastly, any reason why hacks own interfaces cannot be added to custom classes? Like I mentioned above, adding `KeyedContainer` is ignored by hhvm.

**Comment by simonwelsh** [comment]
@SiebelsTim to use a different design pattern (custom methods instead of array syntax). The old docs site had something on this, so may be a good starting point.

**Comment by JoelMarcey** [comment]
@simonwelsh Do you think this was the part of the old docs you are referring to?

https://github.com/facebookarchive/hack-hhvm-docs/blob/The-End-Of-An-Era/__docs/phpdoc/en/hack/predefined/arrayaccesstktv.xml#L20

**Comment by simonwelsh** [comment]
@JoelMarcey along with https://github.com/facebookarchive/hack-hhvm-docs/blob/The-End-Of-An-Era/__docs/phpdoc/en/hack/predefined/arrayaccesstktv.xml#L61

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

The repro you gave now passes typechecks in strict mode.
The definition of ArrayAccess is generic on both key and value types.
```
interface ArrayAccess<Tk, Tv> {
  public function offsetExists(Tk $key): bool;
  public function offsetGet(Tk $key): Tv;
  public function offsetSet(Tk $key, Tv $val): void;
  public function offsetUnset(Tk $key): void;
}
```

The typechecker understands that `ArrayAccess<string, string>` implementors can refer to `Tk` as `string` instead.
The runtime accepts the declaration of `\Test` too.
