### ISSUE TITLE
compile error, Fedora release 24 (Rawhide)  gcc 5.3.1

### ISSUE THREAD

**Issue by javacty** [facebook/hhvm#6746]
<pre>
[ 48%] Built target hphp_hhbbc
[ 49%] Built target neo
[ 49%] Building CXX object hphp/runtime/CMakeFiles/hphp_runtime_static.dir/vm/jit/frame-state.cpp.o
In file included from /opt/hhvm/hphp/runtime/vm/jit/frame-state.cpp:16:0:
/opt/hhvm/hphp/runtime/vm/jit/frame-state.h: 在成员函数‘void HPHP::jit::FrameStateMgr::clearStack()’中:
/opt/hhvm/hphp/runtime/vm/jit/frame-state.h:82:25: 错误：‘default_type’在此作用域中尚未声明
   Type type{default_type()};
                         ^
/opt/hhvm/hphp/runtime/vm/jit/frame-state.cpp:1367:24: 错误：could not convert ‘{<expression error>}’ from ‘<brace-enclosed initializer list>’ to ‘HPHP::jit::Type’
       stk = StackState{};
                        ^
/opt/hhvm/hphp/runtime/vm/jit/frame-state.cpp:1367:24: 错误：could not convert ‘{<expression error>}’ from ‘<brace-enclosed initializer list>’ to ‘HPHP::jit::Type’
hphp/runtime/CMakeFiles/hphp_runtime_static.dir/build.make:9188: recipe for target 'hphp/runtime/CMakeFiles/hphp_runtime_static.dir/vm/jit/frame-state.cpp.o' failed
make[2]: *** [hphp/runtime/CMakeFiles/hphp_runtime_static.dir/vm/jit/frame-state.cpp.o] Error 1
CMakeFiles/Makefile2:1477: recipe for target 'hphp/runtime/CMakeFiles/hphp_runtime_static.dir/all' failed
make[1]: *** [hphp/runtime/CMakeFiles/hphp_runtime_static.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Orvid** [comment]
Is this still an issue?

**Comment by Orvid** [comment]
This issue has been waiting for more info for more than 2 weeks. Closing for now, feel free to re-open it if you can provide more info.

https://github.com/facebook/hhvm/wiki/Human-Timeouts
