### ISSUE TITLE
Throwable interface problems in namespaces

### ISSUE THREAD

**Issue by jurchiks** [facebook/hhvm#6747]
test.php:

``` php
<?php
namespace test;

function a(\Throwable $t) {}

a(new \RuntimeException('foo'));
```

```
$ hhvm --no-config -d hhvm.php7.all=true test.php

Fatal error: Uncaught TypeError: Argument 1 passed to test\a() must be an instance of Throwable, RuntimeException given in /home/jsudmalis/test.php:6
Stack trace:
#0 /home/jsudmalis/test.php(8): test\a()
#1 {main}
```

It seems HHVM does not recognise Throwable inside a namespace. Since this is a class in __SystemLib, I'm worried this might be an issue with other classes there.

**Comment by jurchiks** [comment]
Update:
`<?php var_dump(interface_exists('Throwable'));`
returns false if executed via `hhvm --no-config test.php -d hhvm.php7.all=true`.

**Comment by jurchiks** [comment]
I see that the Throwable interface was added a while ago here:
https://github.com/facebook/hhvm/commit/b44b798e489ae2637459b3721fda7baa5a42d584#diff-8740aea90ea2cddc6d742af4c02654f1
So this problem seems really weird.

**Comment by fredemmott** [comment]
`-d hhvm.php7.all=true` needs to go before test.php, otherwise it goes into test.php's argv instead of being considered an HHVM option:

```
 hhvm --no-config -d hhvm.php7.all=true test.php
bool(false)
bool(true)
bool(true)
```

So RuntimeException does implement Throwable. `interface_exists()` fails because:

```
<?php
var_dump(interface_exists('Throwable'));
var_dump(interface_exists(Throwable::class));
var_dump(Throwable::class);
[fredemmott@devbig349 ~/test] hhvm --no-config -d hhvm.php7.all=true test.php
bool(false)
bool(true)
string(21) "__SystemLib\Throwable"
```

Also an issue, but probably much less important.

**Comment by jurchiks** [comment]
Well, I have a weird issue.
https://github.com/jurchiks/simpleframe
if you clone this at revision eb01501aafa043974ef4f899a72954ce153efaea (Adding support for console testing of basic GET URLs.)
go into simpleframe/public and execute `hhvm --no-config -d hhvm.php7.all=true index.php route /`,
you will see this exception:
```
Exception handler threw an object exception: TypeError: Argument 1 passed to responses\ExceptionResponse::__construct() must be an instance of Throwable, routing\exceptions\RouteException given in /var/www/simpleframe/framework/responses/ExceptionResponse.php:9
Stack trace:
#0 /var/www/simpleframe/framework/App.php(80): responses\ExceptionResponse->__construct()
#1 (): Closure$App::init()
#2 {main}
```
This does not happen with PHP 7:
```$ php index.php route /
Hello, World!
```

**Comment by jurchiks** [comment]
Found the issue!
```php
<?php
namespace test;

function a(\Throwable $t) {}

a(new \RuntimeException('foo'));
```

```
$ hhvm --no-config -d hhvm.php7.all=true test.php

Fatal error: Uncaught TypeError: Argument 1 passed to test\a() must be an instance of Throwable, RuntimeException given in /home/jsudmalis/test.php:6
Stack trace:
#0 /home/jsudmalis/test.php(8): test\a()
#1 {main}
```
It seems HHVM does not recognise Throwable inside a namespace. Since this is a class in __SystemLib, I'm worried this might be an issue with other classes there.

**Comment by fredemmott** [comment]
heh, that's pretty bad D: we need to not auto-import it into the current namespace (like we do for hack stuff), but actually alias it.

**Comment by jurchiks** [comment]
@fredemmott cleaned my comments up a bit, you can delete your first one as well, to keep the topic brief.

**Comment by fredemmott** [comment]
Keeping it in, the Throwable::class vs 'Throwable' vs \Throwable could be useful for whoever works on this.

**Comment by fredemmott** [comment]
https://3v4l.org/fKiQ3

```
<?php

namespace Foo;

$x = new \Exception();
var_dump($x instanceof \Throwable);
```
