### ISSUE TITLE
HHVM Breaks with Segmentation fault at higher loads

### ISSUE THREAD

**Issue by anshu2212** [facebook/hhvm#6748]
I use Ubuntu prebuilt **hhvm** at a 2gb ram 1vcpu vps. I need to read some csv file so i used **Spout** from box inc. but HHVM got segmentation fault . i tried it using Php5-fpm on the same server and it worked well.

My csv contains 6k rows with 15 columns. so it creates a lot of variables .

I tried to reduce the memory limit of hhvm and running from command line but none worked.

Message is:
`Core dumped: Segmentation fault`
`Stack trace in /tmp/stacktrace.12516.log`
`Segmentation fault`

and stack trace contains

`#0  feof(Resource id #4) called at [/home/<user>/public_html/grievance/Spout/Common/Helper/GlobalFunctionsHelper.php:215]`
`#1  Box\Spout\Common\Helper\GlobalFunctionsHelper->feof(Resource id #4) called at [/home/<user>/public_html/grievance/Spout/Reader/CSV/RowIterator.php:132]`
`#2  Box\Spout\Reader\CSV\RowIterator->next() called at [/home/<user>/public_html/grievance/test.php:47]`

it should throgh error if it reached some limits .but segmentation faults closses the HHVM ad site goes down which is a problem.

**Comment by jurchiks** [comment]
I think you need to *increase* the memory limit of HHVM...
Is the memory limit the same for PHP and HHVM?
If not, then perhaps that is the problem.

Also, what kind of code do you have that it "creates a lot of variables"? When processing your data in a loop, those variables should get overwritten every iteration and as such not increase memory usage that much since the previous values are discarded, so that shouldn't be a problem unless you also build up additional data.

**Comment by anshu2212** [comment]
what should be the ideal memory limit for a 2gb machine . by defalt hhvm puts no limit . so i tried from 128 mb to 8 mb and none worked.

php had 64 mb limit.

**Comment by jurchiks** [comment]
Well, if it failed with double the PHP's memory then yeah, something else is causing this.

**Comment by anshu2212** [comment]
i cant undestand 
i tested with 8mb , 16 mb 32mb, 64 mb 128 mb. 
only hhvm running(switching off the php fpm), running script from hhvm terminal, from hhvm-fpm with nginx, giving all general load o php and using hhvm for the script  

but none worked., php runs on same server . so external config must me same.

if you want php.ini of php and php.ini, server.ini of hhvm i can give that
