### ISSUE TITLE
filesize() returns "filesize" of filesystem root on empty filename

### ISSUE THREAD

**Issue by marc1706** [facebook/hhvm#6749]
When using the ```filesize()``` function, hhvm returns the "filesize" of the root folder when called with an empty string as filename. The returned filesize is usually the same as the block size in linux distributions.
However, PHP returns false when passing an empty string as filename. HHVM seems to treat an empty string the same way as ```/```.

Here is a short script for testing this behavior:
```
<?php

var_dump(filesize(''));
var_dump(filesize('/'));
```

Also see this: https://3v4l.org/bUN1c

**Comment by paulbiss** [comment]
Looks like this was fixed by the linked commit.
