### ISSUE TITLE
hhvm stuck in lookupUnitNonRepoAuth 

### ISSUE THREAD

**Issue by phoenixfight** [facebook/hhvm#6750]
hhvm version:
```
HipHop VM 3.7.3-dev (rel)
Compiler: heads/HHVM-3.7-0-g7b4b7f9e5cfc9cf2426fd78691b2b40fb81b508b
Repo schema: 40d17e3c4b24b15059e02e4089f26d1398c1c618
```
system:
```
CentOS Linux release 6.2 (Final)
```
hhvm no respond , high cpu used! 
backtrace log : 
[gdbout.txt](https://github.com/facebook/hhvm/files/88722/gdbout.txt)

**Comment by fredemmott** [comment]
3.7 has not been supported for almost a year, and '-dev' versions are not supported (unless they're recent enough to indicate problems with the next release). If you can reproduce this with 3.11 or a recent nightly, please re-open with example code.
