### ISSUE TITLE
mysql_pdo doesn't honor hhvm.mysql.typed_results setting

### ISSUE THREAD

**Issue by karpa13a** [facebook/hhvm#6754]
in php, we use "hack" to get typed results, example:

``` php
<?
$dbh = new PDO('mysql:host=<host>;dbname=<database>', '<user>', '<pass>');

$dbh->setAttribute( PDO::ATTR_EMULATE_PREPARES, false ); // note this "hack" line, if remove it, hhvm have same behaviour like php5.5.9 in ubuntu 14, all results get string type

$stmt = $dbh->query('SELECT ...', PDO::FETCH_ASSOC);
$row = $stmt->fetchAll();
var_dump($row);
```

it there any way to do same typed result in hhvm as in php?
ini directive
hhvm.mysql.typed_results = true
do not affect result set.

**Comment by Scorcher** [comment]
A little bit more detailed explanation...


```mysql
MariaDB [test]> show variables like 'version';
+---------------+-----------------------------+
| Variable_name | Value                       |
+---------------+-----------------------------+
| version       | 5.5.45-MariaDB-1~trusty-log |
+---------------+-----------------------------+
1 row in set (0.00 sec)

MariaDB [test]> CREATE TABLE test_types (
   intField   INT(6) UNSIGNED NOT NULL DEFAULT 0,
   floatField FLOAT NOT NULL DEFAULT 0,
   strField   VARCHAR(255) NOT NULL DEFAULT ''
) ENGINE=InnoDB;
Query OK, 0 rows affected (0.02 sec)

MariaDB [test]> INSERT INTO test_types VALUES (123, 1234.5674323, '123214qwe');
Query OK, 1 row affected (0.01 sec)

MariaDB [test]> SELECT *, floatField / intField AS calc FROM test_types;
+----------+------------+-----------+--------------------+
| intField | floatField | strField  | calc               |
+----------+------------+-----------+--------------------+
|      123 |    1234.57 | 123214qwe | 10.037133193597562 |
+----------+------------+-----------+--------------------+
1 row in set (0.00 sec)
```


PHP test code:
```php
<?
error_reporting(E_ALL);

$dbh = new PDO('mysql:unix_socket=/var/run/mysqld/mysqld.sock;dbname=test', 'tt', 'tt');
echo $dbh->getAttribute( PDO::ATTR_DRIVER_NAME ) .' - '.$dbh->getAttribute(PDO::ATTR_CLIENT_VERSION). PHP_EOL;
$dbh->setAttribute( PDO::ATTR_EMULATE_PREPARES, false );

$stmt = $dbh->query('SELECT *, floatField / intField AS calc FROM test_types', PDO::FETCH_ASSOC);
$row = $stmt->fetchAll();
var_dump($row);
```

HHVM Result:
```
mysql - 5.6.24
array(1) {
  [0]=>
  array(4) {
    ["intField"]=>
    string(3) "123"
    ["floatField"]=>
    string(7) "1234.57"
    ["strField"]=>
    string(9) "123214qwe"
    ["calc"]=>
    string(18) "10.037133193597562"
  }
}
```


PHP Result:
```
mysql - mysqlnd 5.0.11-dev - 20120503 - $Id: bf9ad53b11c9a57efdb1057292d73b928b8c5c77 $
array(1) {
  [0]=>
  array(4) {
    ["intField"]=>
    int(123)
    ["floatField"]=>
    float(1234.5673828125)
    ["strField"]=>
    string(9) "123214qwe"
    ["calc"]=>
    float(10.037133193598)
  }
}
```


Versions:
```
HipHop VM 3.11.0-dev (rel)
Compiler: heads/cp1251-0-gae98ae5274c94268560b754b257df9e6453f55b7
Repo schema: 1f7def69abb7ebe090d761f53b0b9309cc699b93


PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
```

Part of phpinfo() (mysqlnd used in PDO as mysql driver):
```
PDO drivers => mysql
pdo_mysql
Client API version => mysqlnd 5.0.11-dev - 20120503 - $Id: bf9ad53b11c9a57efdb1057292d73b928b8c5c77 $
```



How to get PHP-mysqlnd like behaviour using HHVM-libmysql?

**Comment by fredemmott** [comment]
There appear to be two problems here; please split one off into another issue if you care about both:

1. In general, we don't support 'nd'-specific behavior at the moment; if PDO MySQL gives the same behavior with the non-nd driver in PHP, this is a compatibility bug that we'll fix (if I'm reading correctly ATTR_EMULATE_PREPARES has an undocumented side effect of changing result types?), otherwise it's a feature request for mysqlnd support.

2. mysql_pdo doesn't honor the `hhvm.mysql.typed_results` ini setting and probably should; this is because it's a fairly straight port of the PHP extension

For both of these, it needs to call https://github.com/facebook/hhvm/blob/4a3be43df46ea29b5d7860aaa524bd3ee8aaf4c8/hphp/runtime/ext/mysql/mysql_common.cpp#L1272 in the appropriate places.

**Comment by karpa13a** [comment]
@fredemmott retitle issue. to be more specific.

**Comment by Scorcher** [comment]
> 1. if PDO MySQL gives the same behavior with the non-nd driver in PHP, this is a compatibility bug that we'll fix

No, non-nd driver hasn't same behavior. There is a string any time with any value of ATTR_EMULATE_PREPARES option.

> (if I'm reading correctly ATTR_EMULATE_PREPARES has an undocumented side effect of changing result types?)...

Right, ATTR_EMULATE_PREPARES option has some side effect, that used widely not only in our projects.

> 2. mysql_pdo doesn't honor the hhvm.mysql.typed_results ini setting and probably should; this is because it's a fairly straight port of the PHP extension

What do you mean, when say "mysql_pdo"? PDO with libmysql or PDO with mysqlnd?
Which "PHP" functions/classes/modules uses hhvm.mysql.typed_results?


I prepared different configurations test case: https://github.com/Scorcher/hhvm-php-mysql-diff
**HHVM doesn't honor hhvm.mysql.typed_results ini setting.**

**Comment by fredemmott** [comment]
HHVM's implementation of MySQL PDO, which is never mysqlnd. GitHub search or grep for 'TypedResults' will show you where it's used.

**Comment by fredemmott** [comment]
Did you see the comments on https://reviews.facebook.net/D54993 ?

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

AsyncMysqlClient is the typed mysql API. Back in hhvm 4.8.0 and below, `\mysqli()` could also be used in a typed way. Changing this behavior now would make it impossible to migrate from PDO to AsyncMysqlClient piecemeal.
Migrating from untyped PDO to typed AsyncMysqlClient is the preferred migration path. This way each function can be migrated to become type aware one by one. If the setting would apply to all api's, flipping it would be a change the world event.
