### ISSUE TITLE
RFC: Move classes that are completely __HipHopSpecific to the HH namespace

### ISSUE THREAD

**Issue by JoelMarcey** [facebook/hhvm#6756]
We have classes like `AsyncMysqlClient` that are basically littered with `<<__HipHopSpecific>>` throughout.

Should those type of classes just be moved to the `HH\` namespace?

What other type of cleanup can we do?

Ref https://github.com/facebook/hhvm/issues/5931 for background info.

**Comment by lexidor** [comment]
Is this still needed?
As far as I understand, entities that are in the `\HH` namespace are there in order to not collide with PHP projects that want to use these names.
Since there is no PHP support anymore, do we still need to put things into `\HH`?

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

All existing Hack apps / libraries are typechecked with hh_client. This will prevent name collisions with the existing root namespaced hhvm specific types. New types ought to be introduced in the `HH` namespace.

Footnote: The use of `__HipHopSpecific` has become uncommon.
