### ISSUE TITLE
Hack's type checker appears to disagree with the runtime regarding the ConstIndexAccess interface

### ISSUE THREAD

**Issue by pbl64k** [facebook/hhvm#6758]
Minimal example in a public gist:

https://gist.github.com/pbl64k/adbf1c035e21efc6a4d2

Type checker accepts this code, which seems to be in accordance with `interfaces.hhi`, but running this (both on `3.11.0~vivid` and `2016.01.15~vivid` nightly) results in the following:

    lepin@xub:~/Sandbox/hack/test$ hh_client 
    No errors!
    lepin@xub:~/Sandbox/hack/test$ hhvm main.hh 
    
    Fatal error: Declaration of Dummy::at() must be compatible with that of ConstIndexAccess::at() in /home/lepin/Sandbox/hack/test/Dummy.hh on line 3
    lepin@xub:~/Sandbox/hack/test$

**Comment by pbl64k** [comment]
Same as #6745?

**Comment by Orvid** [comment]
Yes, this is the same issue as #6745

**Comment by SiebelsTim** [comment]
@Orvid If so, you should close this one =)
