### ISSUE TITLE
$_POST is populated even when content type is not x-www-form-urlencoded

### ISSUE THREAD

**Issue by aaronbski** [facebook/hhvm#6759]
We recently switched our application to use HHVM and encountered an issue. When receiving a POST request with `Content-Type: application/json`, some of the JSON body content can erroneously populate the $_POST variable. A test case is below.

```
<?php 
echo 'POST: ' . $_POST['a'] . PHP_EOL;
```

The following works as expected:

```
curl -H "Content-Type: application/json" -X POST -d '{"something":"a=z"}' http://localhost/test.php
POST: 
```

Things get interesting when we add an ampersand to the "a=z" portion of the JSON body. We get `z"}` instead.

```
curl -H "Content-Type: application/json" -X POST -d '{"something":"&a=z"}' http://localhost/test.php
POST: z"}
```

**Comment by fredemmott** [comment]
#6676
