### ISSUE TITLE
HHVM 3.11.0 Release notes missing

### ISSUE THREAD

**Issue by andrerom** [facebook/hhvm#6762]
Trying to look for info on 3.11.0 release I could not find anything in NEWS\* file, or in the doc\*\*.

\* Not updated since September 2nd in 171a53b551c3c26234e63327bb5606ecb8f6d7c0
\*\* https://docs.hhvm.com/hhvm/installation/release-schedule

**Comment by fredemmott** [comment]
- news file should probably just be removed as it's basically git log --oneline and we're not maintaining a copy of that any more
 - not announcing 3.11.0 is intentional due to issues listed in #6685; this will be addressed in 3.11.1
