### ISSUE TITLE
Error finding libglog.so.0 on linux

### ISSUE THREAD

**Issue by vanderhoff** [facebook/hhvm#6763]
I have libglog installed and confirmed,
sudo find / -name libglog.so.0
/home/mybin/lib/libglog.so.0

when running a compile the following error occurs

    [ 20%] Building C object third-party/libmbfl/mbfl/CMakeFiles/mbfl.dir/__/filters/mbfilter_iso8859_13.c.o
../tools/bootstrap/gen-class-map: error while loading shared libraries: libglog.so.0: cannot open shared object file: No such file or directory

I have added the following to my make command

    make  verbose=1 EXTRA_INCLUDE_PATHS="/home/mybin/include" EXTRA_LIB_PATHS="/home/mybin/lib" EXTRA_CC_FLAGS="-DHAVE_ELF_GETSHDRSTRNDX"

what other flag should I set to point the make to the correct libglog.so.0?

thx
Art

**Comment by Orvid** [comment]
You should be passing the paths to glog as variables to CMake, not to make.
