### ISSUE TITLE
Asserts active by default in nightlies, incompatible with repo auth

### ISSUE THREAD

**Issue by octmoraru** [facebook/hhvm#6764]
Commit d7ce713deeb541e05c0b2b66c30114f6931c1bb5 activates PHP assertions by default. These are not supported in RepoAuthoritative mode.

For this reason. the oss-performance MediaWiki benchmark fails:

```
Fatal error: assert() is not supported: assert with strings argument in RepoAuthoritative mode in /tmp/hhvm-nginxHMBBMk/mediawiki/includes/parser/Preprocessor_Hash.php on line 492
```
Line 492 in Preprocessor_Hash.php contains, as expected, an _assert()_ with string arguments:

```php
// A heading must be open, otherwise \n wouldn't have been in the search list
assert( '$piece->open == "\n"' );
$part = $piece->getCurrentPart();

```

**Comment by fredemmott** [comment]
cc @paulbiss: I assume there's a way to disable it? Possibly should also disable it by default when building repos/using repo auth mode, but not sure that silent behavior change would be a good thing.

**Comment by fredemmott** [comment]
Also, error should probably either give the appropriate ini settings or link to the documentation.

**Comment by octmoraru** [comment]
Hi. Until this issue is fixed, we'll be running our nightly MediaWiki benchmark with "assertions.active=0" in the INI file: https://lists.01.org/pipermail/langperf/2016-January/000443.html
