### ISSUE TITLE
HHVM ignoring values in php.ini

### ISSUE THREAD

**Issue by dhaval17** [facebook/hhvm#6769]
This is my current php.ini at /etc/hhvm/

```
; php options
session.save_handler = files
session.save_path = /var/lib/hhvm/sessions

session.auto_start on
session.cookie_lifetime 31536000
session.gc_maxlifetime 31536000
session.name SESS
session.cookie_secure on
session.cookie_httponly on

; hhvm specific
hhvm.log.level = Warning
hhvm.log.always_log_unhandled_exceptions = true
hhvm.log.runtime_error_reporting_level = 8191
hhvm.mysql.typed_results = false
```

Even after restarting apache and hhvm
And clearing all the cookies in my browser for the specific domain

I see the session cookie is being created with the name `PHPSESSID`
with httponly flag set to off

Am I doing anything wrong ?

**Comment by simonwelsh** [comment]
You're missing `=` signs for your `session` values.

**Comment by dhaval17** [comment]
Oops my bad
Feeling kinda stupid right now

Thanks for the help
