### ISSUE TITLE
Able to change by-refness of return values in subclasses

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#6775]
```
<?php

abstract class foo {
  abstract public function &bar();
}

class herp extends foo {
  public $member = 'derp';

  public function bar() {
    return $this->member;
  }
}
```

PHP: `Fatal error: Declaration of herp::bar() must be compatible with & foo::bar() in /in/C6TPr on line 13`

HHVM: no problem

https://3v4l.org/C6TPr

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This issue is about `&$references`, which were [removed from hhvm](https://hhvm.com/blog/2019/10/01/deprecating-references.html).
