### ISSUE TITLE
Compile fail, centos 7 gcc 4.9.2

### ISSUE THREAD

**Issue by javacty** [facebook/hhvm#6776]
<pre>
[ event, clientPtr = data->m_async_pool->getMysqlClient() ](
                  ^
/opt/hhvm/hphp/runtime/ext/async_mysql/ext_async_mysql.cpp: In function ‘bool HPHP::c_AsyncMysqlConnection_ni_sslSessionReused(HPHP::ObjectData*)’:
/opt/hhvm/hphp/runtime/ext/async_mysql/ext_async_mysql.cpp:620:25: error: ‘class facebook::common::mysql_client::Connection’ has no member named ‘sslSessionReused’
     ret = data->m_conn->sslSessionReused();
                         ^
/opt/hhvm/hphp/runtime/ext/async_mysql/ext_async_mysql.cpp: In function ‘bool HPHP::c_AsyncMysqlConnection_ni_isSSL(HPHP::ObjectData*)’:
/opt/hhvm/hphp/runtime/ext/async_mysql/ext_async_mysql.cpp:630:25: error: ‘class facebook::common::mysql_client::Connection’ has no member named ‘isSSL’
     ret = data->m_conn->isSSL();
                         ^
make[2]: *** [hphp/runtime/ext/CMakeFiles/hphp_runtime_ext.dir/async_mysql/ext_async_mysql.cpp.o] Error 1
make[1]: *** [hphp/runtime/ext/CMakeFiles/hphp_runtime_ext.dir/all] Error 2
make: *** [all] Error 2

**Comment by javacty** [comment]
I have try in Mint 17 with gcc 4.8.4, the error still show:
<pr>
[ 83%] Built target hphp_runtime_static
[ 83%] Building CXX object hphp/runtime/ext/CMakeFiles/hphp_runtime_ext.dir/icu/ext_icu_date_fmt.cpp.o
/opt/hhvm/hphp/runtime/ext/async_mysql/ext_async_mysql.cpp: In function ‘bool HPHP::c_AsyncMysqlConnection_ni_sslSessionReused(HPHP::ObjectData*)’:
/opt/hhvm/hphp/runtime/ext/async_mysql/ext_async_mysql.cpp:620:25: error: ‘class facebook::common::mysql_client::Connection’ has no member named ‘sslSessionReused’
     ret = data->m_conn->sslSessionReused();
                         ^
/opt/hhvm/hphp/runtime/ext/async_mysql/ext_async_mysql.cpp: In function ‘bool HPHP::c_AsyncMysqlConnection_ni_isSSL(HPHP::ObjectData*)’:
/opt/hhvm/hphp/runtime/ext/async_mysql/ext_async_mysql.cpp:630:25: error: ‘class facebook::common::mysql_client::Connection’ has no member named ‘isSSL’
     ret = data->m_conn->isSSL();

**Comment by hkirsman** [comment]
How to debug these kinds of errors? Should I make a separate post? I just tried the latest hhvm on Centos 7 and I get:
[ 37%] Building CXX object third-party/mcrouter/CMakeFiles/mcrouter.dir/mcrouter/tools/mcpiper/mcpiper.cpp.o
Linking CXX static library libmcrouter.a
[ 37%] Built target mcrouter
make: *** [all] Error 2

It should be the same config that I used to build HHVM-3.11.1

**Comment by Orvid** [comment]
The initial issue is likely due to the third-party repo being out of sync. `git submodule update` should be enough to fix that

@hkirsman,  that looks like the error is probably further up in the build log, as you were probably compiling multiple files at once.

**Comment by hkirsman** [comment]
For me it was probably not giving enough memory to my virtual maschine. Now it works with 10-11gb ram.

**Comment by javacty** [comment]
when I  re clone hhvm ,it can compile success.

so, when I "git pull" update source, I also need run "git submodule update --init --recursive" for each ?

**Comment by hkirsman** [comment]
Don't know about that. Just wanted to add that I've created rpm from the latest hhvm for centos 7 at https://github.com/hkirsman/hhvm_centos7_rpms Planning on adding more version if they come out.

**Comment by javacty** [comment]
Oh, that's great.
What is your updae cycle ?

**Comment by hkirsman** [comment]
I haven't done this for very long. I had separate repo where I held the compiled version but not rpm. This is my first rpm. Otherwise with the last hhvm versions I tried creating the new compile right after I noticed there's new version. Only problem was noticing there was a new version :D But I added hhvm to feed now.
