### ISSUE TITLE
is possible delete the php source file?

### ISSUE THREAD

**Issue by 6api** [facebook/hhvm#6777]
i saw hhvm will generate a file named " .hhvm.hhbc"
may i delete all the php files and run my website only with hhvm code?

**Comment by karpa13a** [comment]
@6api read about hhvm-repo-mode (or hhvm.repo.authoritative setting)

**Comment by 6api** [comment]
my php files store in /data/www
hhvm-repo-mode enable /data/www
it is ok, but how can i add special path & files?
for example:
i want only include 2 folders 
/data/www/path1
/data/www/path2
and other folders and php files keep original php code

**Comment by karpa13a** [comment]
@6api you cannot work with repomode in "mixed" mode.
or you keep all files on disk
or you enable repomode on all your .php files

**Comment by cergfix** [comment]
According to the docs it should be possible to rely only on hhbc:
```
You build a bytecode file ahead of time called the repo and deploy that file to production instead of the PHP source files.
```

But it appears that the files should still be present on disk. Is this true?

Steps to reproduce:
```
echo "<?php echo 'hello';" > /data/www/test.php
hhvm-repo-mode enable /data/www/

curl 127.0.0.1/test.php
//response is: hello

mv /data/www/test.php /data/www/test2.php

curl 127.0.0.1/test.php
//response is: 404 File Not Found
``` 

```
HipHop VM 3.11.1 (rel)
Compiler: tags/HHVM-3.11.1-0-g64d37362bc0b6aee919492ad61cf65ce0a5d5e92
Repo schema: 8b80ba45250a6669cd610c189dbbb55b6218c2a3
```

```
; php options

pid = /var/run/hhvm.pid

; hhvm specific

hhvm.server.port = 9060
hhvm.server.type = fastcgi
hhvm.server.ip = 127.0.50.50
hhvm.server.default_document = index.php
hhvm.log.use_log_file = true
hhvm.log.header = true
hhvm.log.file = /var/log/hhvm/error.log
hhvm.server.thread_count = 40
hhvm.server.expose_hphp = false
hhvm.server.request_timeout_seconds = 8
hhvm.repo.central.path = /var/run/hhvm/hhvm.hhbc
hhvm.repo.authoritative = true
```

**Comment by fredemmott** [comment]
- Have you checked that your webserver is configured to pass requests for non-existent PHP files to HHVM?
 - Relatedly, do you have the same behavior when you use HHVM's built in webserver (`hhvm.server.type=proxygen`) ?

**Comment by cergfix** [comment]
For hhvm.server.type=proxygen I added 
```
hhvm.server.source_root = /data/www/
hhvm.server.type=proxygen
```

and then
```
hhvm-repo-mode disable
curl http://127.0.50.50:9060/test.php
//response is: hello

hhvm-repo-mode enable /data/www/
curl http://127.0.50.50:9060/test.php
//response is: hello

mv /data/www/test.php /data/www/test2.php
curl http://127.0.50.50:9060/test.php
//response is: 404 File Not Found
```

hhvm error log shows: 
```
[Mon Feb  1 16:06:42 2016] [hphp] [17484:7f906cbff700:6:000001] [] receiving test.php
[Mon Feb  1 16:06:42 2016] [hphp] [17484:7f906cbff700:6:000002] [] Matching host:127.0.50.50:9060 url:/test.php using vhost:
```

Basically hhvm just checks file's existence and not the content (content is precompiled in hhbc). But I guess this is not normal behavior?

Also, I'm always getting 404 error when hhvm.server.source_root is not specified in proxygen mode, even with enabled repo authoritative mode.

**Comment by icukeng** [comment]
hello all,
this diff https://gist.github.com/icukeng/7a2b9e3836d688974be1013812d467b1 just works for me.
It is aganist tag 3.10.1, I suppose it is suitable some way to other versions.
Also therre must be some better way to just check if path exists in repo, I doesn't search deep in hhvm logic.

There is a side effect: if your program check some php file - it is absent, but it still can be included. So, for example, composer autoload ruins all the idea. And twig cache checks too.
But in general it works.
May be php's FS functions need to be rewritten to also check file in cache for repo autoritative mode.
