### ISSUE TITLE
Cannot inherit previously-inherited constant

### ISSUE THREAD

**Issue by olvlvl** [facebook/hhvm#6780]
Hi,

Something strange is happening with constants:

https://travis-ci.org/ICanBoogie/Validate/jobs/104031807

Basically it boils down to this:

```php
<?php

interface A
{
    const ALIAS = null;
}

class B implements A
{
    const ALIAS = 'alias';
}

class C extends B
{
    const ALIAS = 'other-alias';
}

echo A::ALIAS;
echo B::ALIAS;
echo C::ALIAS;
```

Expected result:

```
null
alias
other-alias
```

Got:

```
Fatal error: Cannot inherit previously-inherited constant ALIAS …
```

This works fine in PHP.

**Comment by aorenste** [comment]
All recent versions of PHP seem to behave the same way HHVM does: https://3v4l.org/IOW7G
