### ISSUE TITLE
hh_client errors on first run

### ISSUE THREAD

**Issue by steelbrain** [facebook/hhvm#6782]
This is what I get on stderr on first run

```
Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
For more detailed logs, try tail -f $(hh_client --logname)
Server launched with the following command: '/usr/bin/hh_server' '-d' '/storage/Workspace/Call/website' '--waiting-client' '12'
Spawned hh_server (child pid=7395)
Logs will go to /tmp/hh_server/zSstoragezSWorkspacezSCallzSwebsite.monitor_log
```

While the rest of stuff is normal, the first line indicates an error I think
Because in previous versions the stderr contents used to start with `Server launched with`

**Comment by lexidor** [comment]
It appears this has been fixed, but I can't find out how to test a repro for this or what needs to happen for this error to occur. I am assuming that this happened on every invocation first invocation of the typechecker for you.
