### ISSUE TITLE
DateTimeZone doesn't understand "+00:00" timezones

### ISSUE THREAD

**Issue by nicolas-grekas** [facebook/hhvm#6783]
``` php
<?php

apc_store('foo', \DateTime::createFromFormat('U', time()));

var_dump(apc_fetch('foo'));
```

=> `DateTimeZone::__construct(): Unknown or bad timezone (+00:00)` on line 5

**Comment by SiebelsTim** [comment]
Similar, easier repro case `unserialize(serialize(...))
https://3v4l.org/3n7ut

**Comment by swtaarrs** [comment]
This is more involved than I thought and unfortunately I don't have time to fix it properly right now.

**Comment by tgabi333** [comment]
+1

**Comment by daiyam** [comment]
+1

I'm getting that error when I'm emptying the trash in wordpress...

**Comment by daiyam** [comment]
workaround:

```php
$date->setTimezone(new \DateTimeZone('UTC'))
```

**Comment by daiyam** [comment]
workaround:

```
$date->setTimezone(new \DateTimeZone('UTC'))
```

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Thanks for the repro. This issue no longer occurs in hhvm 4.56, but has been fixed earlier. I can't find the commit that fixed this issue.

```
object(DateTime) (3) {
  ["date"]=>
  string(26) "2020-05-25 01:11:02.000000"
  ["timezone_type"]=>
  int(1)
  ["timezone"]=>
  string(6) "+00:00"
}
```
