### ISSUE TITLE
is_scalar() returns true for static array variable in class

### ISSUE THREAD

**Issue by kaisung** [facebook/hhvm#6785]
The is_scalar() function incorrectly returns true for static array variables within a class.  The is_array() function seems to work correctly (and I'm using it as a workaround).  Tested on HHVM 3.11.1 release.

The code below prints "true" instead of "false".

```
<?php

class Config
{
    static $STATIC_ARRAY = array('foo' => 'bar');
}

if (is_scalar(Config::$STATIC_ARRAY)) {
    print "true\n";
}
else {
    print "false\n";
}
```

**Comment by jazzdan** [comment]
This [matches](https://3v4l.org/v3SNG) PHP 5 and PHP 7's behavior.

**Comment by jazzdan** [comment]
Ah whoops, 3v4l doesn't have 3.11.1 yet

**Comment by kaisung** [comment]
It's failing for our 3.11.0 build too.  Could there be something in our php.ini that's causing this?

pid = /var/run/hhvm/hhvm.pid
hhvm.server.user = nginx
hhvm.server.type = fastcgi
hhvm.server.file_socket = /var/run/hhvm/hhvm.sock
hhvm.server.thread_count = 32
hhvm.server.backlog = 30000
hhvm.server.stat_cache = true
hhvm.admin_server.port = 9001
hhvm.admin_server.password = xxxxxx
hhvm.dynamic_extension_path = /usr/lib64/hhvm/extensions
hhvm.dynamic_extensions[aerospike] = aerospike.so
hhvm.dynamic_extensions[geoip] = geoip.so
hhvm.server.always_use_relative_path = false
hhvm.log.file = /var/log/httpd/am/bidder/error
hhvm.log.header = true
aerospike.shm.use = true

**Comment by Orvid** [comment]
This is still the same as PHP. https://3v4l.org/Tcdmo
