### ISSUE TITLE
hhvm problem with libboost_chrono on CentOS 6.7

### ISSUE THREAD

**Issue by Alehap** [facebook/hhvm#6789]
Hello, I've installed hhvm on CentOS 6.7 with the tut of CentOS 6.6
But I've got a trouble when type `hhvm`, it's show: "hhvm: error while loading shared libraries: libboost_chrono.so.1.58.0: cannot open shared object file: No such file or directory"

Anyone, please help me fix this trouble.
Thanks too much

**Comment by aorenste** [comment]
Is this still a problem? How are you installing HHVM? Have you tried a newer version of either CentOS or HHVM?

**Comment by Alehap** [comment]
Hi. I've installed the HHVM on Centos7 and it works well.

Vào 07:18 AM T.4, 28 Th9 2016 Aaron Orenstein <notifications@github.com>
viết:
