### ISSUE TITLE
Serializing a Carbon\Carbon date doesn't work in HHVM

### ISSUE THREAD

**Issue by JoelESvensson** [facebook/hhvm#6792]
It's easily reproducible in 3.11.1 with this one-liner:

`serialize(Carbon\Carbon::now());`

**Comment by earnaway** [comment]
This was also mentioned in #5893 and not sure if anything further is being done on it, but certainly stopping us moving to HHVM if Carbon dates can't be serialized.

**Comment by Orvid** [comment]
Reported as #5893, though it's never been isolated to what specifically HHVM is missing to make it work.
