### ISSUE TITLE
Occasional segfault with Joomla 3.4.6

### ISSUE THREAD

**Issue by creativeprogramming** [facebook/hhvm#6793]
This is what i get in the stacktrace .log in tmp folder when it happens (I'm using latest hhvm on ubuntu apt repo):

```
PHP Stacktrace:

#0  JDate->__construct(now) called at [/omissis/libraries/joomla/log/entry.php:96]
#1  JLogEntry->__construct(JError::setErrorHandling() is deprecated., 16, deprecated, ) called at [/omissis/libraries/joomla/log/log.php:148]
#2  JLog::add(JError::setErrorHandling() is deprecated., 16, deprecated) called at [/omissis/libraries/legacy/error/error.php:350]
#3  JError::setErrorHandling(8, message) called at [/omissis/includes/framework.php:18]
#4  include(/omissis/includes/framework.php) called at [/omissis/index.php:36]
```

this is the JData constructor method signature:

```php
/**
	 * Constructor.
	 *
	 * @param   string  $date  String in a format accepted by strtotime(), defaults to "now".
	 * @param   mixed   $tz    Time zone to be used for the date. Might be a string or a DateTimeZone object.
	 *
	 * @since   11.1
	 */
	public function __construct($date = 'now', $tz = null)
	{
```

this is how is getting invoked at entry.php:96:

```php
$this->date = new JDate($date ? $date : 'now');
```
Can I provide more data to help you debbugging it? let me know

**Comment by davidxdunn** [comment]
I've also had one of our servers report a similar issue with this (Wordpress however):

```
#0  DateTimeZone->__construct(Australia/Brisbane)
#1  timezone_open(Australia/Brisbane) called at [/sites/x.net/www/wp-includes/functions.php:4189]
#2  wp_timezone_override_offset() called at [/sites/x.net/www/wp-includes/plugin.php:235]
#3  apply_filters(pre_option_gmt_offset, , gmt_offset) called at [/sites/x.net/www/wp-includes/option.php:49]
#4  get_option(gmt_offset) called at [/sites/x.net/www/wp-includes/functions.php:64]
#5  current_time(mysql) called at [/sites/x.net/www/wp-content/plugins/google-analyticator/google-analytics-summary-widget.php:47]
#6  GoogleAnalyticsSummary->GoogleAnalyticsSummary() called at [/sites/x.net/www/wp-content/plugins/google-analyticator/google-analyticator.php:110]
#7  include(/sites/x.net/www/wp-content/plugins/google-analyticator/google-analyticator.php) called at [/sites/highlifemagazine.net/www/wp-settings.php:254]
#8  include(/sites/x.net/www/wp-settings.php) called at [/sites/highlifemagazine.net/www/wp-config.php:82]
#9  include(/sites/x.net/www/wp-config.php) called at [/sites/highlifemagazine.net/www/wp-load.php:37]
#10 include(/sites/x.net/www/wp-load.php) called at [/sites/highlifemagazine.net/www/wp-admin/admin-ajax.php:22]
```

```
HipHop VM 3.11.1 (rel)
Compiler: tags/HHVM-3.11.1-0-g64d37362bc0b6aee919492ad61cf65ce0a5d5e92
Repo schema: 8b80ba45250a6669cd610c189dbbb55b6218c2a3
```

Let me know if you would like me to try and replicate in a debug version in order to get a full backtrace?

- David.

**Comment by fredemmott** [comment]
Might be fixed with https://github.com/facebook/hhvm/commit/47cff55935064e66d315fb3082195b911a74b1eb

Can you reproduce with a nightly build?

**Comment by davidxdunn** [comment]
Tested using nightly debug and unable to replicate the crash :)

**Comment by fredemmott** [comment]
leaving open for @creativeprogramming  to respond, will close in 2 weeks or at 3.12 if no response

**Comment by photodude** [comment]
@creativeprogramming Are you still seeing the segfault with HHVM and Joomla? ( same as #5520 )

I've been working on and off at getting the php unit tests for Joomla working ( see https://github.com/joomla/joomla-cms/issues/10220 ), right now we are faced with some HHVM issues like `memory_get_peak_usage()` causing a `Fatal error: request has exceeded memory limit` related to the HHVM implementation of `ini_restore` + a few (fairly new) unrelated compiler bugs found by @aorenste  ( see #7035 ) and running under hhvm's php 7 mode there is an issue with "type annotations on internal functions" ( see #7198 )

**Comment by paulbiss** [comment]
Going to close this for now as there are more specific issues open for the known problems. If anyone gets a repro please let me know and I will reopen.

**Comment by photodude** [comment]
@creativeprogramming Joomla staging now passes unit tests on HHVM 3.15.3 and the pre-release 3.7.0 Alpha 1 should be testable for developer site preview with HHVM 3.15.3+
