### ISSUE TITLE
strcmp compatibility with PHP

### ISSUE THREAD

**Issue by GrahamCampbell** [facebook/hhvm#6795]
Consider the following code:

```
var_dump(strcmp('aa', 'abc'));
```

The output on PHP is:

```
int(-256)
```

The output on HHVM is:

```
int(-1)
```

---

https://3v4l.org/KhcsU

**Comment by Orvid** [comment]
There is a very small difference between our string_strcmp and zend_binary_strcmp. I'll poke this either tomorrow or Monday, as the diff should be a 1-liner and I already have both definitions in front of me.

**Comment by GrahamCampbell** [comment]
Nice. This isn't a major issue for me, but I just thought I'd let you guys know about it all the same. :)

**Comment by Orvid** [comment]
Poking the blame internally says that this was a deliberate change from PHP, although I don't see any information about why the change was made, so it may take a bit longer to get worked out.

**Comment by Orvid** [comment]
The internal diff for this is D2885844.

**Comment by GrahamCampbell** [comment]
Any news here?

**Comment by Orvid** [comment]
The fix is easy, and the diff does do so, I just didn't have time to go through our internal codebase to make sure we weren't relying on HHVM's current behavior.

@paulbiss @aorenste Maybe worth looking at again?

**Comment by shweaye810** [comment]
std in C or C++ doesn't specify which value to be return. From [http://en.cppreference.com/w/cpp/string/byte/strcmp](url)
```
Negative value if lhs appears before rhs in lexicographical order.
Zero if lhs and rhs compare equal.
Positive value if lhs appears after rhs in lexicographical order.
```
Some implementation return the difference, some return -1, 0, or 1. That's why they are different value, but technically correct output value.
