### ISSUE TITLE
Multiple HHVM - 111: Connection refused

### ISSUE THREAD

**Issue by ssimpo** [facebook/hhvm#6796]
I am getting "(111: Connection refused)" when I have multiple instances of HHVM running with different user names. The errors only start after I restart one of the HHVM services.  I have tried many different arrangements but this seems to be an error with HHVM?

My setup is as follows:
- Debian Jessie
- Nginx (1.6.2)
- HHVM (using file sockets)

The idea is that each website is running under its own user name as is the normal setup with php-fpm.  For this purpose we have a series of init.d scripts each running HHVM as a different user.  Nginx is connecting to these servers via file sockets (although we have tried normal network sockets and get the same errors).  Each server then has its' own ini file with the user set in this as well.

I have checked the file permissions on just about everything I can imagine and am sure these are set correctly. Also, used setfacl to make sure both www-data and the website user both have access (just in case).

Basically, on first run all is well. The services start and each website connects perfectly.  However, if we restart one of the HHVM instances it seems to knock-out all the other file sockets.

Eg.  Two websites:

- example.org - HHVM running as example-org user and group
- example.com - HHVM running as example-com user and group

On initial start the file sockets are created and the sites run perfectly.  Say you then restart the first HHVM instance (example.org) then it will restart and example.org will run perfectly.  However, the other site will now not work (111: Connection refused).  If you then try to restart the 2nd site it will then work but knock-out the first.

The only way to get all sites working after a restart is to stop all the HHVM instances, delete file sockets and then restart all again.

I hope this makes sense? It is quite complicated to explain clearly. However, I guess it can easily be duplicated by anyone who tries to copy this

I have been working on this for a few days so have tried multiple setups and options.  Everyone seems to lead to the the same restart issue.  It is like the other sockets are closed or changed on a restart.  I am guessing this is a bug? Since, this actually works on first-run, I feel reasonably confident that the file permissions on the sockets (...etc) are correct.

It would be possible of course to write a script, which closed all HHVM instances, deleted all file sockets and then restarted all.  However, once you have a more than a handful of sites running it would be a pain.

Perhaps, this is just wrong setup? Is this even the right way to run each site securely as a different user? Obviously, the idea is to increase security. Sorry if I am wasting anyone's time.

**Comment by ssimpo** [comment]
Really sorry, think this might be to do with the default Debian init.d script for HHVM.  I will post a response once I have confirmed this.  Do not want to waste people's time.

**Comment by aorenste** [comment]
This issue has been waiting for more info for more than 2 weeks. I'm closing it for now, but feel free to re-open it if you can provide more info. https://github.com/facebook/hhvm/wiki/Human-Timeouts
