### ISSUE TITLE
"new" operator incorrect precedence check

### ISSUE THREAD

**Issue by klesun** [facebook/hhvm#6809]
``` hack
<?hh

$source = [5,1,2,4,3];
$pred = $n ==> $n > 2;
$matched = new ImmVector($source)
    ->filter($pred)
    ->count();

```

hh_client reports "No errors!"
hhvm scriptName.hh fails with: 

```
Fatal error: syntax error, unexpected T_OBJECT_OPERATOR in /path/to/script/scriptName.hh on line 6
```

Same with:

``` hh
$matched = ImmVector{5,1,2,4,3}
    ->filter($pred)
```

**Comment by klesun** [comment]
```bash
$ hhvm --version
HipHop VM 3.11.1 (rel)
Compiler: tags/HHVM-3.11.1-0-g64d37362bc0b6aee919492ad61cf65ce0a5d5e92
Repo schema: 8b80ba45250a6669cd610c189dbbb55b6218c2a3
```
```bash
$ hh_client --version
64d37362bc0b6aee919492ad61cf65ce0a5d5e92 Jan 22 2016 13:43:10
```

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

`ImmVector{}->filter($_x ==> false)` is fine to the typechecker and runtime in hhvm 4.56.

`new ImmVector()->filter($_x ==> false)` is a typechecker error, but fine at runtime. This is consitent with other objects created with the `new` operator.

The second case is intended and Hack requires you to add parens around `new ImmVector`.
