### ISSUE TITLE
After a fatal error HHVM fails to respond

### ISSUE THREAD

**Issue by beatscode** [facebook/hhvm#6810]
I just upgraded from hhvm 3.7 to 3.11.1. In development i see the type checker error messages in the browser. This is fine but I'm curious why after attempting to fix the error hhvm doesn't respond to the changes in the code. I end up restarting the server everytime instead. I don't want to turn the type checker off altogether. How do I keep the typechecker from halting the subsequent requests?

An example of a hack type error.

````
Unhandled Exception

Message:

Hack type error: You are trying to access the member id but this is not an object, it is a mixed value at /var/www/a/application/controllers/ajax/b.php line 173
Location:

/var/www/leonardo/laravel/autoloader.php on line 120
Stack Trace:

#0 /var/www/leonardo/laravel/laravel.php(40): Laravel\Error::native()
#1 (): Closure$Laravel\#2()
#2 (): HH\Client\TypecheckResult->triggerError()
#3 /var/www/a/laravel/autoloader.php(120): HH\Client\typecheck_and_error()
#4 /var/www/a/laravel/autoloader.php(79): Laravel\Autoloader::load_psr()
#5 /var/www/a/application/routes.php(57): Laravel\Autoloader::load()
#6 /var/www/a/laravel/bundle.php(136): include()
#7 /var/www/a/laravel/bundle.php(108): Laravel\Bundle::routes()
#8 /var/www/a/laravel/laravel.php(76): Laravel\Bundle::start()
#9 /var/www/a/public/index.php(34): include()
#10 {main}
````

**Comment by fredemmott** [comment]
It usually does; common causes are using a filesystem that does not report changes - eg nfs or some virtualization "mount host directory on guest" implementation.

- do the errors still show up in `hh_client` after fixing them?
- if so, does `hh_client restart; hh_client` show errors?

**Comment by beatscode** [comment]
ok I'm using docker within vagrant so that would explain that. Thanks.
