### ISSUE TITLE
preg_split() does not accept $limit NULL

### ISSUE THREAD

**Issue by pstast** [facebook/hhvm#6815]
`preg_split("/[\s,]+/", "hypertext language, programming", NULL);`

results in:

> PHP Warning: preg_split() expects parameter 3 to be integer, null given

Although PHP documentation states that:

> A limit of -1, 0 or NULL means "no limit" and, as is standard across PHP, you can use NULL to skip to the flags parameter.

PHP 5.6 and 7.0 accept NULL as $limit parameter.

HipHop VM 3.11.1 (Jessie)

**Comment by pstast** [comment]
**preg_replace()** may have the same issue

**Comment by apeabody** [comment]
I haven't been able to reproduce this problem in 3.14.0-dev or https://3v4l.org/mo86f - can someone provide more details?

**Comment by Orvid** [comment]
Enable PHP7's scalar type hints option in HHVM and you'll hit the error. `preg_split` is currently typed as this in the systemlib:
```PHP
function preg_split(string $pattern,
                    string $subject,
                    int $limit = -1,
                    int $flags = 0): mixed;
```
