### ISSUE TITLE
Mac OS X - setup issue, HHVM with Nginx

### ISSUE THREAD

**Issue by kumar2013** [facebook/hhvm#6819]
I have installed HHVM using the official doc commands "brew tap hhvm/hhvm" and then "brew install hhvm". After this, I have installed Nginx using "brew install Nginx". Both of them installed perfectly (nginx serves static page "index.html" on the browser and "hhvm -a" starts the debugger). 

In some articles, they have mentioned to connect HHVM with NginX I need to run a command "sudo /usr/share/hhvm/install_fastcgi.sh", but this gives "no such file or directory" error and also there is no folder called "hhvm" inside "share". Hence, I am stuck here.

I need to create "/etc/nginx/hhvm.conf" file to proceed further. I haven't seen any document for setup HHVM and Nginx on Mac OSX, most of the documents explaining for Debian and Ubuntu.

I have MAMP server separately and that works fine. Could anyone please help me with this issue or direct me in a right path since I am new to this. Thanks in advance.

**Comment by denji** [comment]
`"sudo /usr/share/hhvm/install_fastcgi.sh"` work only linux debian/ubuntu

/etc/nginx - linux
/usr/local/etc/nginx - bsd/osx

**Comment by kumar2013** [comment]
Hi, denji, Thank you for the reply, I understood what you mean. Still I haven't figured it out how to configure HHVM with Nginx on mac. By following this [http://paulherron.com/blog/simple_nginx_setup_with_homebrew/](URL) article I have configured Nginx successfully. However, it is not processing any PHP code instead it just paste the code inside comment out. I have come across few articles with php-fcgi but I have to use HHVM. Could you please help me with the right direction, thanks.

**Comment by jwatzman** [comment]
There's some information in the official docs: https://docs.hhvm.com/hhvm/advanced-usage/fastCGI#using-fastcgi__making-it-work-with-nginx -- have you tried to follow those?

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Support for MacOS has been dropped in June of 2022. https://hhvm.com/blog/2022/06/17/deprecating-homebrew.html
