### ISSUE TITLE
Support for HTTP/2

### ISSUE THREAD

**Issue by raeesbhatti** [facebook/hhvm#6822]
Support for HTTP/2 has been [stabilized in Proxygen](https://github.com/facebook/proxygen/commit/61af0f95c5fc96d4263062f9dad05144db831e62). I would love to see it in HHVM as soon as possible.

**Comment by fredemmott** [comment]
especially easy for an FB employee, we have an internal extension already. Probably just needs cleaning up (eg moving to the HH\namespace).

**Comment by fredemmott** [comment]
uh, actually, that's true for HTTP2 push support - the protocol should already be supported automaticdally by the built in server. What exactly do you want?

**Comment by raeesiqbal** [comment]
Well, how do I use it then? How do I make it the preferred protocol for Proxygen in an `.hdf` or `.ini`?

**Comment by raeesiqbal** [comment]
bump

**Comment by afrind** [comment]
You can enable HTTP/2 in HHVM by adding this to the Server section of your .hdf:

SSLNextProtocols = { 
  * = h2
  * = http/1.1
}

**Comment by fredemmott** [comment]
cc @JoelMarcey re INI documentation of those (HDF is deprecated externally)

**Comment by raeesiqbal** [comment]
@fredemmott any updates on HTTP/2 push support?

**Comment by fredemmott** [comment]
Sorry, no, I'm not actively working on HHVM any more. It shouldn't be much work, but needs someone to have the time to release it. This isn't quite as trivial as just moving the files - we need to rename the functions from 'server_push_*' to "HH\something' and make sure that doing so doesn't break facebook.

**Comment by raeesiqbal** [comment]
Is there anyone else on the team you can talk to to do this? It would be lovely to have this soon.

:)

**Comment by SiebelsTim** [comment]
Blindly guessing: @paulbiss ?

**Comment by afrind** [comment]
Can we create a separate issue for HTTP/2 push support since it's optional?  I can help drive it internally.  Does PHP have a standard mechanism to initiate a push or do we need to create an extension?

**Comment by raeesbhatti** [comment]
HHVM Proxygen is no longer supports for Google Chrome because Chrome has recently dropped support for SSL NPN and only supports ALPN now. I'm not sure if there is parameter to enable this because I only saw this [one occurrence of ALPN](https://github.com/facebook/proxygen/blob/61793e895cdbe51c436148d4355d9b1abb1706cf/proxygen/httpclient/samples/curl/CurlClientMain.cpp#L40) in Proxygen source.

**Comment by Orvid** [comment]
Well, I'm not sure exactly where we're handling NPN/ALPN for the proxygen backend, but if you're using the fastcgi backend through apache or nginx, or have a separate layer (like varnish) between the web and HHVM, HTTP/2 is supported and does get used. The fastcgi setup is HHVM's default.

**Comment by afrind** [comment]
Proxygen supports ALPN via folly/io/async/SSLContext.  The API for setting next protocols didn’t change when we added ALPN support (about 1 year ago).  It does require you are using a version of openssl that supports ALPN (1.0.2 or higher).

**Comment by raeesbhatti** [comment]
@afrind I installed OpenSSL 1.0.2j and then installed HHVM 3.15.2 package for Debian Jessie. Now when I try to connect to the server, it still says "No ALPN negotiated" and when looked at connections in Google Chrome, it is using HTTP/1.1
```
$ > openssl s_client -connect mysite.example.com:443 -nextprotoneg '' | grep ALPN
depth=2 O = Digital Signature Trust Co., CN = DST Root CA X3
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
verify return:1
depth=0 CN = mysite.example.com
verify return:1
No ALPN negotiated
```

Firefox however, is using `h2` as protocol because it still supports NPN. I installed HHVM via `apt`. Does it use the dynamic OpenSSL package or it has a statically-linked one?

**Comment by afrind** [comment]
The command line arg to s_client for ALPN is -alpn I think, -nextprotoneg is for NPN only.

**Comment by afrind** [comment]
Also, I’m pretty sure that the package needs to also have been compiled with openssl-1.0.2 to support ALPN.  I’m not sure of the compilation details of your prebuilt debian package.

**Comment by raeesbhatti** [comment]
I've compiled HHVM 3.15.2 with OpenSSL 1.0.2j and can confirm that the Proxygen is serving `h2` via ALPN as expected.
