### ISSUE TITLE
MediaWiki 1.26.2 causes HHVM 3.12 to segfault

### ISSUE THREAD

**Issue by alex-mashin** [facebook/hhvm#6825]
After upgrading HHVM to 3.12 from 3.11 under Ubuntu 15.10, when I attempt to save (or reparse) a MediaWiki 1.26.2 page, HHVM process segfaults. The segmentation fault happens in different places, not always, but the longer the MediaWiki page, the greater chances for segfault are. More or less long pages, as a result, cannot be saved at all.

There are numerous warnings about type mismatches in HHVM logs and in the stacktraces (see MW bug https://phabricator.wikimedia.org/T126871):

`/var/log/hhvm/error.log':
```Warning: Cannot use a scalar value as an array in /var/www/wiki/w/includes/jobqueue/JobQueueGroup.php on line 30```

```Notice: Array to string conversion in /var/www/wiki/w/extensions/Scribunto/engines/LuaSandbox/Engine.php on line 3```

```Notice: Array to string conversion in /var/www/wiki/w/includes/libs/objectcache/APCBagOStuff.php on line 96```

```Notice: Array to string conversion in /var/www/wiki/w/includes/Sanitizer.php on line 1044```

In stack traces:
```AbstractContent->getParserOutput(Традиция:Идеи/Традиция, 399847, Object of class ParserOptions could not be converted to string) called at [/var/www/wiki/w/includes/poolcounter/PoolWorkArticleView.php:140]```

```MediaWiki->performAction(Object of class Article could not be converted to string, Традиция:Идеи/Традиция) called at [/var/www/wiki/w/includes/MediaWiki.php:287]```

However, stack traces not always show any PHP errors or warnings. Example:
```
PHP Stacktrace:

#0  AutoLoader::autoload(PathRouter) called at [/var/www/wiki/w/includes/WebRequest.php:120]
#1  WebRequest::getPathInfo(title) called at [/var/www/wiki/w/includes/WebRequest.php:269]
#2  WebRequest->interpolateTitle() called at [/var/www/wiki/w/includes/Setup.php:676]
#3  include(/var/www/wiki/w/includes/Setup.php) called at [/var/www/wiki/w/includes/WebStart.php:137]
#4  include(/var/www/wiki/w/includes/WebStart.php) called at [/var/www/wiki/w/index.php:38]
```

**Comment by alex-mashin** [comment]
It is less frequent under HHVM 3.12.1.

**Comment by Orvid** [comment]
The PHP stacktrace isn't very helpful. Could you get a gdb backtrace for the native side?

**Comment by aorenste** [comment]
This issue has been waiting for more info for more than 2 weeks. I'm closing it for now, but feel free to re-open it if you can provide more info. https://github.com/facebook/hhvm/wiki/Human-Timeouts
