### ISSUE TITLE
DatePeriod does not support getter methods from PHP 5.6.5+

### ISSUE THREAD

**Issue by nyamsprod** [facebook/hhvm#6828]
DatePeriod does not support getter methods from PHP 5.6.5+

The following methods are missing:

- DatePeriod::getDateInterval;
- DatePeriod::getStartDate;
- DatePeriod::getEndDate;

https://3v4l.org/hYYc5

**Comment by SiebelsTim** [comment]
I'm angry. They are very broken on PHP's side. 

https://3v4l.org/dH3O6
https://3v4l.org/a044v
