### ISSUE TITLE
Ftruncate behaves differently

### ISSUE THREAD

**Issue by bramp** [facebook/hhvm#6830]
The following snippet behaves differently on HHVM 3.11 to PHP 5.6 and 7

```php
$fp = fopen('php://memory', 'r+b');
fwrite($fp, "1234567890");
ftruncate($fp, 0);
fwrite($fp, "abcdefghij");
rewind($fp);
echo "'" . fread($fp, 10) . "'";
```

```
 php prints 'abcdefghij'
hhvm prints ''
```

I suspect the behaviour of hhvm is actually correct, because ftruncate is not meant to reset the pointer, however I point this out due as a inconsistency.

The workaround is to add rewind after the ftruncate.

**Comment by Orvid** [comment]
I'm going to say we're the ones doing something wrong here.

**Comment by Orvid** [comment]
Once #6919, this might also be fixed, but this might also require more to fix.

**Comment by apeabody** [comment]
@orvid I agree HHVM is operating according to the PHP doc:

https://secure.php.net/manual/en/function.ftruncate.php
"The file pointer is not changed."

That said PHP does not appear to behave per it's DOC, but instead changes the file point to the new eof.  If we want to copy that non-spec implementation, let me know, otherwise we should close this issue.

**Comment by Orvid** [comment]
Doing this with a file on disk in PHP may yield a different result, as seeking past the end of a file stream is allowed (I think) in both PHP and HHVM, but I haven't checked. In the case where seeking beyond the end of a stream is not supported for a particular stream type, it makes perfect sense for the file pointer to be effected if it is pointing past the end of the stream after the call to ftruncate.

**Comment by apeabody** [comment]
I did some simple testing yesterday and it does appear that PHP allows seeking past the end of a standard disk based file, but not a memory (php://) one.  So the desired behavior change should only be for the later.

**Comment by paulbiss** [comment]
The PR needed to be reverted
