### ISSUE TITLE
Fatal error: Uncaught TypeError: Argument 2 passed to stream_set_blocking() must be an instance of int, bool given

### ISSUE THREAD

**Issue by lethanhviet** [facebook/hhvm#6831]
Having this issue when I switch to hhvm.php7.all = 1. I'm using hhvm, redis and wordpress with php7.0-fpm as fall back. This is a clean build.

With hhvm using php5, everything is working fine. However, performance of wordpress+hhvm(php5)+redis is noticeably slower than wordpress+php7.0-fpm+redis.

~ # hhvm --version
HipHop VM 3.12.0 (rel)
Compiler: tags/HHVM-3.12.0-0-g440e6a096b2db8a449b9690a72f2f1792530e86a
Repo schema: 033b8dedf4af99b892f2488b103a8d67a58ff816

~ # redis-server --version
Redis server v=3.0.7 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=6afb1e1f0d80abd0

~ # php -v
PHP 7.0.3-1~dotdeb+8.1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

Wordpress 4.4.2

\nWarning: strcasecmp() expects parameter 2 to be string, null given in /var/www/wp-content/object-cache.php on line 358
\nFatal error: Uncaught TypeError: Argument 2 passed to stream_set_blocking() must be an instance of int, bool given in /var/www/wp-content/object-cache.php:377\nStack trace:\n#0 /var/www/wp-content/object-cache.php(377): Redis->connect()\n#1 /var/www/wp-content/object-cache.php(158): WP_Object_Cache->__construct()\n#2 /var/www/wp-includes/load.php(473): wp_cache_init()\n#3 /var/www/wp-settings.php(95): wp_start_object_cache()\n#4 /var/www/wp-config.php(91): include()\n#5 /var/www/wp-load.php(37): include()\n#6 /var/www/wp-blog-header.php(12): include()\n#7 /var/www/index.php(17): include()\n#8 {main}

**Comment by JohanTan** [comment]
@lethanhviet I have been experiencing the same issue. How did you fix this one (assuming it's fixed)?
