### ISSUE TITLE
Install boost_context on CentOS 6

### ISSUE THREAD

**Issue by Alehap** [facebook/hhvm#6836]
Hello, I'm try to install HHVM on CentOS 6, but I've trouble with boost_context library:

```
`- Build type not specified: cmake build type Release.
CMake Error at /usr/share/cmake/Modules/FindBoost.cmake:1138 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.60.0

  Boost include path: /usr/include

  Could not find the following Boost libraries:

          boost_context

  Some (but not all) of the required Boost libraries were found.  You may
  need to install these additional Boost libraries.  Alternatively, set
  BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
  to the location of Boost.
Call Stack (most recent call first):
  CMake/HPHPFindLibs.cmake:31 (find_package)
  CMake/HPHPSetup.cmake:127 (include)
  third-party/CMakeLists.txt:18 (include)`
```

On CentOS 7, I can easily install by type: yum install boost-context So how can I install this boost_context library on CentOS 6?

Thank you very much!!

**Comment by sbagmeijer** [comment]
You will need allot of external packages I think to get it build on CentOS 6 allot of packages are to outdated to get it build.

But if you find a way I would be interested to know also.

**Comment by apeabody** [comment]
The wiki suggests rebuilding the CentOS 7 boost srpm under CentOS 6.x: https://github.com/facebook/hhvm/wiki/Building-RPMs-for-HHVM-on-CentOS-6.6

Of course my personal suggestion would be to move to CentOS 7 if possible.  Centos 6 was released nearly 5 years ago and its development toolchain wasn't the freshest to being with, so I suspect this problem will only snowball with time.

**Comment by Alehap** [comment]
Thank you all so much. 
For some reasons, I cannot move to CentOS 7 at this time. I'll try with the RPMs' solutions.
Thanks^^
