### ISSUE TITLE
rename_function vs. fb_rename_function inconsistencies

### ISSUE THREAD

**Issue by kmafb** [facebook/hhvm#6839]
For historical reasons, HHVM calls the apd extension's 'rename_function' functionality 'fb_rename_function.' If HHVM wants to keep this difference, the docs for Eval.JitEnableRenameFunction (and probably the flag's name as well?) ought to be updated, but the difference seems like the sort of thing one would not choose to do this way if starting from scratch in 2016.

**Comment by kmafb** [comment]
See, e.g., https://docs.hhvm.com/hhvm/configuration/INI-settings's reference to 'rename_function', which will fatal no matter what you set that flag to.

**Comment by fredemmott** [comment]
https://github.com/hhvm/user-documentation/issues/282
