### ISSUE TITLE
Fatal error: Could not create variable environment (repo mode only)

### ISSUE THREAD

**Issue by karpa13a** [facebook/hhvm#6840]
Hello,
i got this error, in array_filter function
code looks like
```php
public function getdata()
{
...
$this->data = array_filter( $tree->data, function ( $node ) use ( $__params )
                {
                          extract( $__params, EXTR_SKIP );
...
```

error line is extract ...
how to fix that?

n.b. this is repo.mode, without - works fine.

**Comment by Orvid** [comment]
`extract` is a dynamic function that imports variables into the current scope. This violates the assumptions made by repo-authoritative mode, which is why you can't use `extract` in it.

**Comment by firodj** [comment]
If `extract` or `compact` is not possible in repo mode, it is better to failing the compilation process and give the proper error message.
