### ISSUE TITLE
datetime extension : wrong behaviour on incorrect input format 

### ISSUE THREAD

**Issue by archibaldhaddock** [facebook/hhvm#6841]
Hello everybody,

While testing typo3 PHPUnit under hhvm, I came across a small compatibilty issue : php zend and hhvm version of datetime extension don't react the same way to incorrectly formated input (most of the time, hhvm throws exceptions when zend returns false)
Modifying some function definitions (from <<__Native>>
to <<__ParamCoerceModeFalse,__Native>>) in
hphp/runtime/ext/datetime/ext_datetime.php I made the tests pass
You'll found attached an overview of the different questions of this kind 
[test_datetime.php.gz](https://github.com/facebook/hhvm/files/138009/test_datetime.php.gz)

that may be raised by the extension.

regards
Gwen

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

In [hhvm 4.3.0](https://hhvm.com/blog/2019/04/30/hhvm-4.3.0.html) the failure mode of calling a built-in function with the wrong types has been changed to be a TypeError. This matches the user defined Hack functions. It is not possible to get the PHP coercion behavior. PHP support was dropped with the release of [hhvm 4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html) and Hack does not coerce to make values match typehints.
