### ISSUE TITLE
HHVM incompatibilities with Magento

### ISSUE THREAD

**Issue by zw0lsman** [facebook/hhvm#6856]
I'm running into some (4) incompatibilities while using HHVM + Nginx on Magento. Can someone help me to fix these? I've tried to exclude these url's from running HHVM (just run PHP-FPM instead), but it doesn't seem to work.

Here are the errors:
```
\nFatal error: An iterator cannot be used with foreach by reference in /PATH/Simtech/Searchanise/Helper/ApiProducts.php on line 1018

\nFatal error: Call to undefined function stream_socket_enable_crypto() in /PATH/lib/Zend/Mail/Protocol/Smtp.php on line 206

\nFatal error: Uncaught exception 'Exception' with message 'File '/PATH//media/css' does not exists.' in /PATH//lib/Varien/File/Transfer/Adapter/Http.php:96\nStack trace:\n#0 /data/web/public/get.$

Unhandled server exception: exception 'PDOException' with message 'SQLSTATE[HY000] [1205] Lock wait timeout exceeded; try restarting transaction' in :\nStack trace:\n#0 /PATH//lib/Zend/Db/Statement/Pdo.php($

```
I've tried to exclude them using this:
# Rewrite Searchanise to use PHP-FPM
location /PATH/Simtech/Searchanise/Helper/ApiProducts.php {
    rewrite / /index.php break;
    echo_exec @phpfpm;
}
# Rewrite Adapter to use PHP-FPM
location /lib/Varien/File/Transfer/Adapter/Http.php {
    rewrite / /index.php break;
    echo_exec @phpfpm;
}
# Rewrite SMTP sender to use PHP-FPM
location ^~ /lib/Zend/Mail/Protocol/Smtp.php {
    rewrite / /index.php break;
    echo_exec @phpfpm;
}

**Comment by jg-development** [comment]
"Call to undefined function stream_socket_enable_crypto()"

Looks like you are using an old version of hhvm .... stream_socket_enable_crypto was implemented first in 3.9 ... use the actual 3.12 lts

**Comment by fredemmott** [comment]
Yep, it's in all supported versions of HHVM right now, that's 3.9 and 3.12: https://3v4l.org/LZMWq

**Comment by fredemmott** [comment]
As a side note, this means that whatever version of HHVM you're using is not getting security updates, and is likely to have issues.
