### ISSUE TITLE
Single-threaded hhvm support?

### ISSUE THREAD

**Issue by gopedib** [facebook/hhvm#6863]
Hi, is it possible to compile and run hhvm in single-threaded environment that cannot support pthread calls? This hhvm framework will be fine with serving one php file at a time. Only issue is I cannot support pthread and its associated thread forking/join in my emulated environment in which I am trying to port hhvm. I can see that thread-manipulating functions defined in util directory are being used in many places. I was wondering can I compile hhvm for single-threaded environment by changing any config (I do not see any in CMakeCache.txt!) or by turning off any #defines deep down in the codebase/repository.

**Comment by Orvid** [comment]
HHVM is not designed to run in a single threaded environment, and threading is used heavily. I've been doing work as part of my port to Windows to provide paths that don't need to call the unix `fork()` function, but I'm still using the pthread API.

Anything is possible if you're determined enough, so it's probably possible to do, but the easiest route would probably be to support the pthread API, even if that means implementing a task scheduler yourself.
