### ISSUE TITLE
HHVM + Nginx + Wordpress + W3 Total Cache -> Crash after 3-4 article editing / posting

### ISSUE THREAD

**Issue by Mandrake990** [facebook/hhvm#6864]
Hi,

I have this configuration:

Debian 8.4
Nginx
MariaDB 10.0
HHVM 3.12.0

I'm testing HHVM (from apt HHVM repos) on a MS Wordpress environment with Nginx. I love its performance, but i cannot use as replacement of PHP 7.0 FPM because it crashes after 3-4 article posting/editing by my journalists.

This is what my dmesg logs:

[215370.963717] hhvm[10190]: segfault at 231 ip 0000000001e7cefb sp 00007fb2a5be7810 error 4 in hhvm[400000+2579000]
[215605.501182] hhvm[22666]: segfault at c600000000 ip 0000000001e7cefb sp 00007fe445fe78d0 error 4 in hhvm[400000+2579000]
[293052.740645] hhvm[911]: segfault at 135 ip 0000000001e7cefb sp 00007f894e3e7810 error 4 in hhvm[400000+2579000]
[295658.816093] hhvm[12217]: segfault at 0 ip 0000000001e7cefb sp 00007fa2f87e78d0 error 4 in hhvm[400000+2579000]
[296258.586250] hhvm[13450]: segfault at ffffffff00000001 ip 0000000001e7cefb sp 00007fbb577e78d0 error 5 in hhvm[400000+2579000]
[296352.818732] hhvm[13837]: segfault at 28b ip 0000000001e7cefb sp 00007f59213e7810 error 4 in hhvm[400000+2579000]
[299743.495125] hhvm[21769]: segfault at 0 ip 0000000001e7cefb sp 00007fc1383e78d0 error 4 in hhvm[400000+2579000]

And stacktrace ends with:

:/tmp# cat stacktrace.22951.log

PHP Stacktrace:

#0  remove_accents(Società) called at [/var/www/vhosts/***/wp-includes/formatting.php:1524]
#1  sanitize_title(Società) called at [/var/www/vhosts/***/wp-includes/taxonomy.php:1733]
#2  term_exists(Società, post_tag) called at [/var/www/vhosts/***/wp-includes/taxonomy.php:2812]
#3  wp_set_object_terms(40078, Array, post_tag, ) called at [/var/www/vhosts/****/wp-includes/post.php:3770]
#4  wp_set_post_terms(40078, Array, post_tag, ) called at [/var/www/vhosts/***/wp-includes/post.php:3728]
#5  wp_set_post_tags(40078, Array) called at [/var/www/vhosts/***/wp-includes/post.php:3236]
#6  wp_insert_post(Array, ) called at [/var/www/vhosts/***/wp-includes/post.php:3458]
#7  wp_update_post(Array) called at [/var/www/vhosts/****/wp-admin/includes/post.php:369]
#8  edit_post() called at [/var/www/vhosts/***/wp-admin/post.php:193]

This is the configuration on server.ini:                                 

; php options

; hhvm specific
hhvm.server.ip = 127.0.0.1
hhvm.server.port = 9000
hhvm.server.type = fastcgi
hhvm.server.default_document = index.php
hhvm.server.source_root=/var/www/vhosts/*****

hhvm.jit_a_max_usage = 536870912
hhvm.jit_a_size = 536870912
hhvm.jit_a_frozen_size = 482344960
hhvm.jit_a_prof_size = 629145600
hhvm.jit_a_cold_size = 167772160
hhvm.jit_global_data_size = 268435456

hhvm.server.apc.enable_apc = true
hhvm.server.apc.table_type = concurrent
hhvm.server.apc.expire_on_sets = true
hhvm.server.apc.purge_frequency = 4096

hhvm.log.use_log_file = true
hhvm.log.use_syslog = false
hhvm.repo.central.path = /var/cache/hhvm/hhvm.hhbc

hhvm.server.thread_count=16
hhvm.server.max_post_size=100M

hhvm.enable_zend_compat=true
hhvm.enable_zend_sorting=false

I know that HHVM works with WP without problems since years!

I also applied the patch of W3 total cache of the file TotalCache.php that was causing warnings and error.

I tried to run without using APC as object cache storage, no success.

For your info, i use Sharepress for publishing automatically to Facebook. So it does actions while the articles are being published.

I don't have many ideas on how to fix my problem.  I rollbacked to PHP 7 for now, but i would like to implement HHVM as main PHP engine for my network. PHP is too slow for my standards even if reliable.

Can you please help me to fix?

Thanks!

**Comment by codeaken** [comment]
Probably related: #6786

**Comment by Mandrake990** [comment]
Thank you for the hint.

Trying 3.12-dev and i'll update this post.

Thanks again!

**Comment by Mandrake990** [comment]
Ok upgraded to 3.13-dev and everything seems fine for now.

# hhvm --version
HipHop VM 3.13.0-dev (rel)
Compiler: heads/master-0-g79e045f3ad1cbe079ff15c163131eb184db025f9
Repo schema: 3bc9bc7924ab37a19149dc95641f450a3e3c655c

I hope this problem wouldn't reappear in future! 

Thank you again! :)
