### ISSUE TITLE
hhvm 3.12 crashes generating empty stacktrace.

### ISSUE THREAD

**Issue by fcorriga** [facebook/hhvm#6865]
Hello.

I've updated hhvm 3.9.1 to 3.12 in my test environment (Debian 7) and got several crashes (and consequent http 502 errors until hhvm fastcgi was restarted). The problem is stacktrace is 0 bytes...
I'm running a highly customized version of Magento 1.9.x and everything is fine and working on hhvm 3.9.1.
Is there anything that should be changed between 3.9.1 and 3.12.0 in the .ini files?
Are you aware of such kind of crashes?
Thanks.

**Comment by fcorriga** [comment]
FYI: HHVM 3.12.1 crashes the same way.

**Comment by fredemmott** [comment]
A *lot* has changed since 3.9 - too much to list: https://github.com/facebook/hhvm/compare/HHVM-3.9...HHVM-3.12

This could be investigated if you can provide a small, isolated way to reproduce the problem - also, you might get more information from a debug build.

**Comment by fcorriga** [comment]
Il will try a debug build and provide info as required

**Comment by fcorriga** [comment]
3.12.0 debug build for wheezy seems to have problems too:
[Fri Mar  4 19:13:50 2016] [hphp] [11138:7fbae53a4560:0:000005] [] Unable to read pid file /var/run/hhvm/pid for any meaningful pid
[Fri Mar  4 19:14:51 2016] [hphp] [11138:7fbae53a4560:0:000006] [] Unable to start page server
[Fri Mar  4 19:14:51 2016] [hphp] [11138:7fbae53a4560:0:000007] [] Shutting down due to failure(s) to bind in HttpServer::runAndExitProcess

the pid file is there and is both readable and writeable but contains no pid. also, nginx returs http 502 when requesting pages

**Comment by fredemmott** [comment]
```
[Fri Mar 4 19:14:51 2016] [hphp] [11138:7fbae53a4560:0:000007] [] Shutting down due to failure(s) to bind in HttpServer::runAndExitProcess
```

The means the port you're trying to use is already in use, or the user doesn't have permission (eg trying to bind to port 80 when running as a normal user)

**Comment by fcorriga** [comment]
found the problem... socket file had wrong permissions...
i'll be back in a minute... after the crash

**Comment by fcorriga** [comment]
same...
empty stacktrace... and even non sign of segfault in error.log.
hhvm process just disappeared

**Comment by fcorriga** [comment]
how can i get more info?

**Comment by effeks** [comment]
Same issue, upgraded from 3.9.1 to 3.12.1 on test server, same code-base but crashes every now and then. Production is still running 3.9.1 and works fine.

Stacktrace-files are created, but they are always empty. Only logged messages are like these:
```
Mar  2 11:09:35 localhost kernel: [204389.521245] traps: hhvm[18666] trap invalid opcode ip:de089ce sp:7fe58aff9990 error:0
Mar  2 11:10:44 localhost kernel: [204459.188078] hhvm[18985]: segfault at 0 ip 0000000002f93467 sp 00007ff7033f7920 error 4 in hhvm[400000+3a13000]

Mar  3 16:14:38 localhost kernel: [309093.190877] hhvm[9964]: segfault at 7fc7ffc00000 ip 00007fc80559a3d8 sp 00007fc7f2bfa0c8 error 4
Mar  3 16:14:38 localhost kernel: [309093.194576] hhvm[9967]: segfault at 5000001c6 ip 0000000002fe6e20 sp 00007fc7f1ff9900 error 4 in hhvm[400000+3a13000]
Mar  3 16:14:38 localhost kernel: [309093.200948]  in libc-2.19.so[7fc805461000+1a2000]

Mar  4 10:26:56 localhost kernel: [374630.753260] hhvm[23498]: segfault at 0 ip 0000000002f93467 sp 00007f63a07f7020 error 4 in hhvm[400000+3a13000]
Mar  4 10:28:38 localhost kernel: [374733.321084] hhvm[23749]: segfault at 100000000 ip 0000000002f8f719 sp 00007f1312ff98f0 error 4 in hhvm[400000+3a13000]
Mar  4 10:28:38 localhost kernel: [374733.331421] hhvm[23723]: segfault at 10 ip 00007f132aeee65c sp 00007f131a7f38b8 error 4 in libstdc++.so.6.0.20[7f132ae79000+ec000]
```

**Comment by fcorriga** [comment]
I used even insanely high jit cache parameters:
hhvm.jit_a_size = 306184192
hhvm.jit_a_cold_size = 100663296
hhvm.jit_a_frozen_size = 201326592
;hhvm.jit_a_hot_size = 0
hhvm.jit_a_prof_size = 306184192
hhvm.jit_a_max_usage = 306184192
hhvm.jit_global_data_size = 306184192

It keeps crashing. However, before doing that, at the end of page request, after the page is served, HHVM process keeps running at 100% for a few seconds (maybe 2 or 3) and then crashes.

**Comment by fcorriga** [comment]
@fredemmott how can i provide more info?

**Comment by fredemmott** [comment]
Attaching gdb and getting a backtrace from all threads is likely the most useful. I won't be investigating as I don't currently work on HHVM.

**Comment by fcorriga** [comment]
@fredemmott who should i ask to investigate? thanks anyway.

**Comment by fredemmott** [comment]
The team looks at issues periodically - contacting specific people does not work for a project of this size.

**Comment by fcorriga** [comment]
ok, thanks.

**Comment by fcorriga** [comment]
gdb backtrace is available here: http://pastebin.com/gMjMSaXB

**Comment by fcorriga** [comment]
this was the cause: https://github.com/facebook/hhvm/issues/6911
