### ISSUE TITLE
hhvm 3.12 crashes with cms drupal (using views module)

### ISSUE THREAD

**Issue by attisan** [facebook/hhvm#6879]
Using HHVM 3.11, with some tedious and "voodoo like repeated page reloading" (resulting in error 500) HHVM would, after some time, start to cease errors, and work just fine with [drupal 7](https://www.drupal.org/project/drupal) using [views](https://www.drupal.org/project/views).

With HHVM 3.12, this reloading 'trick' is no more as the HHVM process just stops with an 'assertion' (all telemetry included; see attachments). Sometimes, possibly connected with the time HHVM has been up before asserting, an empty stacktrace is generated and HHVM just stops without information (see #6865).

As HHVM works fine with drupal core, the problem seems to be with the views module / addon.

The working environment:
Debian stretch/sid
nginx 1.9.10-1
hhvm 3.12.0+dfsg-1
mariadb 10.1.12-MariaDB-1~sid

Please let me know if I can provide any usefull / further information.

[stacktrace.22119.log.gz](https://github.com/facebook/hhvm/files/154319/stacktrace.22119.log.gz)
[perf-22119.map.gz](https://github.com/facebook/hhvm/files/154316/perf-22119.map.gz)
[hhvm.syslog.log.gz](https://github.com/facebook/hhvm/files/154318/hhvm.syslog.log.gz)
[hhvm.info.gz](https://github.com/facebook/hhvm/files/154338/hhvm.info.gz) (hhvm settings dump)

**Comment by attisan** [comment]
Supplement:

When trying to access a page involving the aforementioned views module directly after HHVM (re)started, without navigating to other pages or 'letting some time pass by', errors like these are issued:

- kernel: [764366.730636] hhvm[23217]: segfault at 7fb710ae9580 ip 00007fb0dc11b467 sp 00007fb0c9bf7580 error 6 in libjemalloc.so.1[7fb0dc117000+33000]
- kernel: [764391.722024] hhvm[23235]: segfault at 18 ip 00007f7414ab584d sp 00007f7400ff6e18 error 4 in libsqlite3.so.0.8.6[7f7414a56000+d1000]
- kernel: [764590.119116] hhvm[23282]: segfault at 18 ip 00007f0d0d86684d sp 00007f0cf9ff6e18 error 4 in libsqlite3.so.0.8.6[7f0d0d807000+d1000]
- kernel: [764656.789921] hhvm[23347]: segfault at 7f049eee9580 ip 00007efd08658467 sp 00007efcf5ff7580 error 6 in libjemalloc.so.1[7efd08654000+33000]

**Comment by aorenste** [comment]
Is this still happening with newer versions of HHVM?

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones are very unlikely to be worked on.

This issue has been created some time ago and there is not enough information in this issue to reproduce this issue on a modern build of hhvm. I am closing this issue, since the chances are low that a repro will be added after all this time. If you are reading this and have a way to reproduce this issue in a modern hhvm version, feel free to open a new issue.
