### ISSUE TITLE
Got "zombie" threads

### ISSUE THREAD

**Issue by zhil** [facebook/hhvm#6881]
We use HipHop VM 3.12.0 in fast-cgi mode with nginx and everything works just great except one problem.

After 10 hours or so server load start growing until hhvm eat 100% of server (all 4 cores). Server keep working, but new relic show 100% load. It has nothing to do with trafic. If I restart service - server load return to normal (10-20%) for next 10-12 hours.
So, basically I have added to cron restart for hhvm service 3 times per day.
Its pretty dirty solution and I got mistakes from google (which get 502 bad gateway response from nginx sometime). So I decided to locate problem.

When I open 
http://hhvm-admin/check-health - I got load: 0 in most cases after restart. However, if I disable hhvm service restart, after some time server load start increasing. And at the same time I dont get load: 0 any more in status. 

In next test case I had load: 2 or more all times I request hhvm server status.
When I checked hhvm threads - I got pretty strange picture
![image](https://cloud.githubusercontent.com/assets/981783/13472252/ae3a24e6-e0bc-11e5-8fe7-02a1856dcce8.png)

There was exactly 2 threads with long "life". I didnt founded anything like php time limit for hhvm.
## My question

: is it possible, that HHVM got some threads, which are just hangs forever and that lead to increased server load? If yes - how could I check it?

my configs is above
- php.ini

```
; php options
date.timezone = Europe/Kiev

; hhvm specific.
hhvm.log.level = Warning
hhvm.log.always_log_unhandled_exceptions = true
hhvm.log.runtime_error_reporting_level = 8191
hhvm.log.use_log_file = true
hhvm.mysql.typed_results = false

memory_limit = 2048M

hhvm.libxml.ext_entity_whitelist = file,http

```
- server.ini

```
; php options
date.timezone = Europe/Kiev
pid = /var/run/hhvm/pid
memory_limit = 2048M

; hhvm specific.

hhvm.admin_server.password = ************************
hhvm.admin_server.port = 9898

hhvm.server.ip = 127.0.0.1
hhvm.server.port = 9011
hhvm.server.type = fastcgi
hhvm.server.default_document = index.php
hhvm.log.level = Warning
hhvm.log.always_log_unhandled_exceptions = true
hhvm.log.runtime_error_reporting_level = 8191
hhvm.log.use_log_file = true
hhvm.log.header = true
hhvm.log.file = /var/log/hhvm/error.log
hhvm.repo.central.path = /opt/hhvm/hhvm.hhbc
hhvm.mysql.typed_results = false

hhvm.debug.fullbacktrace = true
hhvm.debug.serverstacktrace = true
hhvm.debug.servererrormessage = true
hhvm.debug.translatesource = true

;hhvm.dynamic_extensions.openssl = ext_openssl.so
;hhvm.dynamic_extensions.ssh2 = ext_ssh2.so

hhvm.server.thread_count = 8
```

**Thanks in advance if anybody will direct me to what should I do next in order to locate this problem**

**Comment by zhil** [comment]
got 100% server load again. In "tree view mode" in top I got such a picture. Few threads are just load system for ever, until I restart hhvm

![image](https://cloud.githubusercontent.com/assets/981783/13494216/93d0ae24-e14b-11e5-86aa-6f52e61671e4.png)

**Comment by r3wt** [comment]
@Orvid the "no isolated repro" tag being used in hhvm's repo has become a bit of a faux pas, as its just a baseless lie. this issue has been reported *probably* over 1000 times by many people, and casually swept under the rug by the hhvm team each time. its intermittently reproducible but as everyone who has been down this road, its impossible to debug. if the issue isn't going to be addressed, how about a known issues entry on the wiki for this problem?

**Comment by fredemmott** [comment]
Lots of reports without an isolated repro still means that there is no isolated repro. There are too many issues with isolated repros for looking at ones without to be a good use of time - in this case, given how many internal deployments we have without this issue, it is extremely unlikely that an internal attempt to reproduce without more information will be anything other than a waste of time.

**Comment by zhil** [comment]
@r3wt @fredemmott 
do you have any ideas how could I move forward with this bug?

**Comment by fredemmott** [comment]
Ideally, all of these - but just the first two will be useful if nothing else:

 - confirm this still exists on 3.12
 - get a multithreaded backtrace from a debug build (we provide debug build packages for 3.12.0): attach gdb to the process, and run 'thread apply all bt'
 - provide instructions to reproduce the problem that do not include 'install <some-project>' or similar

**Comment by zhil** [comment]
@fredemmott thanks for your help. 
strace for "zombie" threads return nothing.

backtrace for default build return 
```
(gdb) thread apply all bt

Thread 1 (process 12314):
#0  0x00000000063efce0 in ?? ()
#1  0x00007f2976a7f9d0 in ?? ()
#2  0x000000000684178e in ?? ()
#3  0x00007f2976a7fbb0 in ?? ()
#4  0x00007f2900000002 in ?? ()
#5  0x00000000030ca719 in enterTCHelper ()
#6  0x0000000001224c73 in HPHP::jit::x64::enterTCImpl(unsigned char*, HPHP::ActRec*) ()
#7  0x00000000030ca679 in HPHP::jit::MCGenerator::enterTC(unsigned char*, HPHP::ActRec*) ()
#8  0x00000000030c8219 in HPHP::ExecutionContext::invokeFunc(HPHP::TypedValue*, HPHP::Func const*, HPHP::Variant const&, HPHP::ObjectData*, HPHP::Class*, HPHP::VarEnv*, HPHP::StringData*, HPHP::ExecutionContext::InvokeFlags, bool) ()
#9  0x00000000030b5731 in HPHP::vm_call_user_func(HPHP::Variant const&, HPHP::Variant const&, bool) ()
#10 0x000000000198f647 in HPHP::f_call_user_func_array(HPHP::Variant const&, HPHP::Array const&) ()
#11 0x000000000613966b in ?? ()
#12 0x00007f2976a7fd80 in ?? ()
#13 0x000000000648915d in ?? ()
#14 0x00007f2976a7fea0 in ?? ()
#15 0x000000000653dc8c in ?? ()
#16 0x00007f2976a7ff20 in ?? ()
#17 0x00000000060d8b29 in ?? ()
#18 0x00000000030ca719 in enterTCHelper ()
#19 0x0000000001224c73 in HPHP::jit::x64::enterTCImpl(unsigned char*, HPHP::ActRec*) ()
#20 0x00000000030ca679 in HPHP::jit::MCGenerator::enterTC(unsigned char*, HPHP::ActRec*) ()
#21 0x00000000030c8219 in HPHP::ExecutionContext::invokeFunc(HPHP::TypedValue*, HPHP::Func const*, HPHP::Variant const&, HPHP::ObjectData*, HPHP::Class*, HPHP::VarEnv*, HPHP::StringData*, HPHP::ExecutionContext::InvokeFlags, bool) ()
#22 0x00000000031733ad in HPHP::ExecutionContext::invokeUnit(HPHP::TypedValue*, HPHP::Unit const*) ()
#23 0x00000000031731d7 in HPHP::invoke_file(HPHP::String const&, bool, char const*) ()
#24 0x0000000003173561 in HPHP::include_impl_invoke(HPHP::String const&, bool, char const*) ()
#25 0x00000000031718e4 in HPHP::hphp_invoke(HPHP::ExecutionContext*, std::string const&, bool, HPHP::Array const&, HPHP::VRefParamValue const&, std::string const&, std::string const&, bool&, std::string&, bool, bool, bool) ()
#26 0x0000000003169989 in HPHP::HttpRequestHandler::executePHPRequest(HPHP::Transport*, HPHP::RequestURI&, HPHP::SourceRootInfo&, bool) ()
#27 0x00000000031631bf in HPHP::HttpRequestHandler::handleRequest(HPHP::Transport*) ()
#28 0x0000000000f1211f in HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJobImpl(std::shared_ptr<HPHP::FastCGIJob>, bool) ()
#29 0x0000000000f12a2f in HPHP::JobQueueWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::Server*, true, false, HPHP::JobQueueDropVMStack>::start() ()
#30 0x000000000233de27 in HPHP::AsyncFuncImpl::ThreadFunc(void*) ()
#31 0x0000000000d004f7 in HPHP::start_routine_wrapper(void*) ()
#32 0x00007f298798db50 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#33 0x00007f298745595d in clone () from /lib/x86_64-linux-gnu/libc.so.6
#34 0x0000000000000000 in ?? ()
```

will it help? Is it still required to use debug build of hhvm?

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones are very unlikely to be worked on.

This issue has been created some time ago and there is not enough information in this issue to reproduce this issue on a modern build of hhvm. If you are reading this and have a way to reproduce this issue in a modern hhvm version, feel free to open a new issue.

A lot has changed in hhvm in the last 8 years. For example, hhvm does not run PHP code anymore. The chances that the backtrace and other data provided will be useful to create a repro are very slim.

There is no good way to resolve this issue, since there is no isolated repo. Even if an problem with similar symptoms were found and then resolved, there is no way to conclusively say if this issue has been fixed.

Don't let the closing of this issue discourage you anyone from filing a new issue.
