### ISSUE TITLE
HHVM "Crashing" - 502 Errors - Bug or User-Error?

### ISSUE THREAD

**Issue by s3w47m88** [facebook/hhvm#6886]
Forgive me if this is not the correct place to report this, and I have searched and read many other Issues here in Github but can't confirm whether or not my issue is a duplicate of others or not beside on Issue that was closed for reason of Human Timeout.

I'm seeking confirmation as to whether or not others are experiencing this same issue and whether or not the issue is with HHVM itself (as in a bug). If not I assume it's a configuration issue and that I'll need to turn to proper forums for further support as I understand this is not necessarily a support forum.

**That being said; I'm running an AWS EC2 T2 Medium Instance with Webmin / Virtualmin atop NGinx, Reddis and HHVM (called web-server-1). It's connected to a separate AWS EC2 T2 Large Instance that runs MySQL (called database-server-1). Web-server-1 operates about 25 WordPress websites. On web-server-1 HHVM recently started "crashing" multiple times a day at seemingly random intervals. When HHVM stops operating correctly any websites I visit display 502 errors. The only that that resolves it is restarting HHVM.**

**I have New Relic installed on web-server-1 and database-server-1. So I looked at the CPU and RAM usage at the times of the "crash" I don't see higher than normal usage of those resources - which would indicate to me there is a memory leak or a runaway script.**

After looking through the forums here I see that many others (https://github.com/facebook/hhvm/issues/3876) are experiencing this issue and that it was confirmed as a bug but I'm not sure where to go from here.

Thank you all for your time and assistance, I hope this is helpful to others!

HHVM Error Log: https://gist.github.com/s3w47m88/fac1e0cbf4ae5846fbd2

**Comment by fcorriga** [comment]
same issue here on both normal and debug builds.
no log is created...

**Comment by kor-ea** [comment]
Increasing hhvm.jit_a_size to 128Mb fixed the issue

**Comment by fcorriga** [comment]
my JIT parameterts
-vEval.JitASize=201326592 -vEval.JitAFrozenSize=139460608 -vEval.JitAColdSize=69206016 -vEval.JitGlobalDataSize=201326592

you mean i should RISE JitASize even more?

**Comment by fcorriga** [comment]
.. keeps crashing even with insanely high values... like:
hhvm.jit_a_size = 306184192
hhvm.jit_a_cold_size = 100663296
hhvm.jit_a_frozen_size = 201326592
;hhvm.jit_a_hot_size = 0
hhvm.jit_a_prof_size = 306184192
hhvm.jit_a_max_usage = 306184192
hhvm.jit_global_data_size = 306184192

**Comment by MounirHamani** [comment]
As a workaround, you can use Monit to automatically restart your HHVM instance when it crashes.

**Comment by fcorriga** [comment]
i already use it.. but it crashes so often monit won't be useful.

**Comment by MounirHamani** [comment]
Sorry about that.
In the mean time, you can set it up to check "every minute" that HHVM is
running.
And if it's still really that bad, you can set up a fallback to php-fpm.

Also, sometimes it might be caused by some unsupported or mis-coded call to
a function, so check your log files to find out what happend prior to the
crashes.

Hope this helps.

2016-03-11 10:41 GMT+01:00 fcorriga <notifications@github.com>:

**Comment by fredemmott** [comment]
- it is crashing, or stopping to respond?
- is there a way to reproduce this, or a backtrace from all threads? (needs gdb for the latter)

There's not enough information for someone to try to fix this.

**Comment by fcorriga** [comment]
it does crash. the hhvm process ends leaving no trace of the crash.
no stacktrace, no log... nothing.
it's a random crash but it happens FREQUENTLY. 
i've never used GDB, so please bear with me... is there a HHVM specific guide to run it thru GDB?

**Comment by fcorriga** [comment]
@MounirHamani yes it is THAT bad...
i have already monit running every 30 seconds... and that's not enough.
hhvm crashes after 2 to 5 (or 6 maybe) page requests and as i told to Fred, the debug build crashes even more.

**Comment by fredemmott** [comment]
Standard gdb documentation for attaching to a running process should cover it; the only thing is that most guides are for single-threaded programs - use 'thread apply all bt' instead of just 'bt' to get the backtrace for all threads.

**Comment by fcorriga** [comment]
ok, thanks a lot.
will post the backtrace as soon as possible.

**Comment by fcorriga** [comment]
First problem i noticed. HHVM remain stuck doing something AFTER the page has been served.
It keeps "eating" cpu cycles while does nothing.
GDB reports:
warning: (Internal error: pc 0x3d6ae23 in read in psymtab, but not in symtab.)

warning: (Internal error: pc 0x3d6ae22 in read in psymtab, but not in symtab.)

while hhvm is running. seems stuck in an infinite loop.
However i'm running the 3.12.0-dbg build... there is no 3.12.1-dbg for debian wheezy.

**Comment by fcorriga** [comment]
ok...
heres's the backtrace: http://pastebin.com/gMjMSaXB

**Comment by fcorriga** [comment]
it's the same as: https://github.com/facebook/hhvm/issues/6865

**Comment by fcorriga** [comment]
Found the cause. It is: https://github.com/facebook/hhvm/issues/6911

**Comment by fredemmott** [comment]
@s3w47m88: does #6911 also explain your issue?

**Comment by fcorriga** [comment]
Uhm... i think he experienced 2 issues at the same time. One is crash caused by the reusable_tc and the other, is the impossibility to connect to redis (at least, at the end of the the error log, it says HHVM was unable to connect to redis).

**Comment by gooki** [comment]
Upgrading from 3.12.1 to 3.13.x brought on a plague of 502 on my 1.9 nginx server. I had to go back to 3.12.1 in particular and saw no more 502. I double checked that it was not an nginx issue but playing with 1.8 etc. Every version had issues with 3.13.x and played well with 3.12.1. 

The 502 were caused by hhvm failing after about 5 page loads. (Sometimes even less). 

I was also getting the pesky blank stack traces. 

Don't know if this helps anyone but hey

**Comment by Orvid** [comment]
Were you upgrading to 3.13.0 or 3.13.1? 3.13.0 had issues that caused it to crash.

**Comment by gooki** [comment]
3.13.0 I believe was the version that had the crashes yes. I will try 3.13.1 today again to make sure and I'll let you know.

**Comment by txaqo** [comment]
Hi guys,
im having a similar issue, but my line numbers are diff?

[Tue Apr 19 13:22:24 2016] [hphp] [31340:7fdd03bff700:1285:000001] [] \nWarning: Parameter 1 to W3_Plugin_TotalCache::ob_callback() expected to be a reference, value given in /var/www/xxx.com/htdocs/wp-includes/functions.php on line **3553**


}

/**
 * Flush all output buffers for PHP 5.2.
 *
 * Make sure all output buffers are flushed before our singletons are destroyed.
 *
 * @since 2.2.0
 */
function wp_ob_end_flush_all() {
        $levels = ob_get_level();
        for ($i=0; $i<$levels; $i++)
                ob_end_flush();                  <<<<<3553
}

any ideas?

**Comment by Orvid** [comment]
Your issue is probably a different one, could you file a separate issue for it?

**Comment by txaqo** [comment]
sure thing..

**Comment by txaqo** [comment]
@Orvid  new thread opened for new issue.. 
https://github.com/facebook/hhvm/issues/7003
