### ISSUE TITLE
partially infer unspecified return types for async functions in partial mode

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#6887]
``` Hack
public async function foo() {
 // ...
}
```

Would it be practical for the typechecker to know that this returns `Awaitable<... something ... >`, even though it doesn't know what that something is?

For example, I've recently seen `$foo = await nullthrows(someAsyncFunction());` which doesn't make sense

**Comment by mxw** [comment]
Pretty sure we're allowed to `await null`—one of the slow tests has a case for it.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This heuristic has been added. The typechecker infers `Awaitable<_>`.

```HACK
<?hh // partial

async function func_async() {}
```

```HACK
<<__EntryPoint>>
function main(): void {
    func_async();
}
```

```
Typing[4015] This expression is of type Awaitable, but it's either being discarded or used in a dangerous way before being awaited
   --> file.hack
  3 |     func_async();
    |     ^^^^^^^^^^^^
   --> file.php
  3 | async function func_async() {
    |                ^^^^^^^^^^ This is why I think it is Awaitable

1 error found.
```
