### ISSUE TITLE
Undefined function throws fatal error when PHP7 mode is on

### ISSUE THREAD

**Issue by JohanTan** [facebook/hhvm#6893]
One of the newest features of php 7 is most fatal errors no longer terminate the script execution but throwing an exception instead. Undefined function is one example. However, it still throws a fatal error under HHVM 3.12.0 even when php7 mode is on. Is it still on the roadmap to implement this feature? This is one of the biggest features on php7 and we'd be thrilled to have it work on hhvm as well.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This works in newer versions on hhvm.

```HACK
<<__EntryPoint>>
function main(): void {
    try {
        function_that_doesnt_exist();
    } catch (\Error $e) {
        echo "Recovered from ".$e->getMessage();
    }
}
```

_Recovered from Call to undefined function function_that_doesnt_exist()_
