### ISSUE TITLE
help needed to enable tracing

### ISSUE THREAD

**Issue by mibintc** [facebook/hhvm#6901]
I am trying to build hhvm with Intel compiler. I have a runtime difference with a workload so i want to enable tracing in store-elim.cpp. i compiled store-elim.cpp with -DUSE_TRACE and likewise hphp/util/trace.cpp; Besides these 2 files, none are compiled with DEBUG. When running the workload i set environemnt variable TRACE=hhir_store:5 however the file /tmp/hphp.log is 0 bytes after the assertion failure which occurs in optimize_stores. My basic question is: what steps to enable tracing? Should I recompile all with -DDEBUG? hhvm-3.10.0.tar.xz Thanks and regards, Melanie #iwork4intel

**Comment by edwinsmith** [comment]
There are a few places in the code we have tracing enabled for release builds, but for the most part wherever you see TRACE or FTRACE instrumentation, it requires a Debug build. Those macros are compiled out in release builds.

**Comment by mibintc** [comment]
thank you
