### ISSUE TITLE
How to enable xmlrpc in HHVM version 3.12.1

### ISSUE THREAD

**Issue by yuunoa** [facebook/hhvm#6902]
My website with wordpress self hosting have issue, "Your website needs to be publicly accessible to use Jetpack: site inaccessible"
i think hhvm not allow access to xmlrpc, how to fix it?

**Comment by Orvid** [comment]
XMLRPC is a message passing format, so I don't know what you mean by HHVM not allowing access to is.

Is there something specific in the code that is failing?

**Comment by aorenste** [comment]
This issue has been waiting for more info for more than 2 weeks. I'm closing it for now, but feel free to re-open it if you can provide more info. https://github.com/facebook/hhvm/wiki/Human-Timeouts
