### ISSUE TITLE
password_verify() fails on password generated with crypt()

### ISSUE THREAD

**Issue by elazar** [facebook/hhvm#6905]
### HHVM Version

3.11.0

### Standalone code, or other way to reproduce the problem

```php
<?php
$password = 'password';
$salt = 'salt';
$crypt = crypt($password, $salt);
var_dump(password_verify($password, $crypt));
```

PHP 5.5.0 through 7.0.4 yields the expected result, HHVM 3.6.1 through 3.12.0 does not.

https://3v4l.org/rg2Qn

### Expected result

bool(true)

### Actual result

bool(false)

**Comment by Orvid** [comment]
Apparently we were failing if the hash was exactly 13 characters, while PHP allows that.
