### ISSUE TITLE
redis.php should close connect when read timeout

### ISSUE THREAD

**Issue by Ryen** [facebook/hhvm#6912]
### Standalone code, or other way to reproduce the problem

  protected function checkConnection($auto_reconnect = true) {
    if (!$this->connection) {
        return false;
    }
    // Check if we have hit the stream timeout
    if (stream_get_meta_data($this->connection)['timed_out']) {
     **// seems we should close the connection.**
      throw new RedisException("read error on connection");
    }
### Expected result
  protected function checkConnection($auto_reconnect = true) {
    if (!$this->connection) {
        return false;
    }
    // Check if we have hit the stream timeout
    if (stream_get_meta_data($this->connection)['timed_out']) {
      **$this->close();  // may resolve the problem, need check.**
      throw new RedisException("read error on connection");
    }

**Comment by Orvid** [comment]
Could you explain the specific issue this would solve? Also, it would be easier if you just opened a pull request with the change rather than filing an issue with the change.

**Comment by fredemmott** [comment]
Closing to stop people looking at it: no-one except for you who has looked at this issue can fix this, as the change isn't contributed under the CLA.

Please send a pull request, or file a *new* issue describing the problem/how to reproduce it without including code.

**Comment by fredemmott** [comment]
If you file a new issue/pull request, please do not reference this issue to avoid tainting the new one.
