### ISSUE TITLE
max function produces different results on arguments that compare equal depending on whether jit is turned on

### ISSUE THREAD

**Issue by zodiac** [facebook/hhvm#6915]
### HHVM Version

3.12.1

### Standalone code, or other way to reproduce the problem

```
➜  ~ cat ./jit-max-test 
<?php

var_dump(max(1.0, 1));
➜  ~ hhvm -c /dev/null -d hhvm.jit=0 ./jit-max-test 
float(1)
➜  ~ hhvm -c /dev/null -d hhvm.jit=1 ./jit-max-test
int(1)
```

### Expected result

The second command should return `float(1)`

At the very least, the first and second commands should return the same thing

For reference, zend interpreter returns `float(1)`

**Comment by Orvid** [comment]
Already fixed in https://github.com/facebook/hhvm/commit/c1b414e85f9ab358845bdf26435a5800cf522ff4.
