### ISSUE TITLE
fseek beyond the end of the stream is allowed

### ISSUE THREAD

**Issue by Orvid** [facebook/hhvm#6916]
It appears that we allow seeking beyond the end of a file. PHP does not. This is likely part of the cause of #6830.

https://3v4l.org/MTMtH

**Comment by apeabody** [comment]
I was looking into this, but I think the PHP behavior might actually be a bug:

https://bugs.php.net/bug.php?id=52335

https://secure.php.net/manual/en/function.fseek.php
"In general, it is allowed to seek past the end-of-file; if data is then written, reads in any unwritten region between the end-of-file and the sought position will yield bytes with value 0. However, certain streams may not support this behavior, especially when they have an underlying fixed size storage."

**Comment by Orvid** [comment]
We should go with the PHP behavior. I think I only tested using memory streams, so you should definitely check the other stream types in PHP to see what the expected behavior is for each type.

**Comment by paulbiss** [comment]
The PR needed to be reverted

**Comment by Orvid** [comment]
Well... That's not good :(

**Comment by apeabody** [comment]
Hmm, based on test/slow/ext_oauth it appears that StatCache::lstat isn't returning the correct value in *some* cases - a "pure" fstat() works correctly, but I know we want to avoid that for performance reasons.  I'll have to look into StatCache further..
