### ISSUE TITLE
3.12 cherry-pick request: strtr segfault fix, #6767

### ISSUE THREAD

**Issue by rinu** [facebook/hhvm#6918]
### HHVM Version
HipHop VM 3.12.1 (rel)
Compiler: tags/HHVM-3.12.1-0-gf516f1bb9046218f89885a220354c19dda6d8f4d
Repo schema: f2e5f39b2ad4a08bcbd90b5d8bcb580f40fba6c8

### Standalone code, or other way to reproduce the problem
```php
<?php
$chars = [
	'ā' => 'a',			'ậ' => 'a',			'ặ' => 'a',			'à' => 'a',
	'â' => 'a',			'á' => 'a',			'ầ' => 'a',			'ẩ' => 'a',
	'ấ' => 'a',			'ẳ' => 'a',			'ẫ' => 'a',			'ẵ' => 'a',
	'ả' => 'a',			'ắ' => 'a',			'ã' => 'a',			'ằ' => 'a',
	'ä' => 'a',			'å' => 'a',			'ạ' => 'a',			'ă' => 'a',
	'ª' => 'a',			'ǎ' => 'a',			'ą' => 'a',			'ɑ' => 'a',

	'û' => 'u',			'ǘ' => 'u',			'ü' => 'u',			'ú' => 'u',
	'ǖ' => 'u',			'ừ' => 'u',			'ử' => 'u',			'ǜ' => 'u',
	'ǚ' => 'u',			'ủ' => 'u',			'ữ' => 'u',			'ǔ' => 'u',
	'ù' => 'u',			'ự' => 'u',			'ů' => 'u',			'ű' => 'u',
	'ų' => 'u',			'ŭ' => 'u',			'ứ' => 'u',			'ũ' => 'u',
	'ư' => 'u',			'ū' => 'u',			'ụ' => 'u',

	'Ũ' => 'U',			'Ự' => 'U',			'Ǖ' => 'U',			'Ǔ' => 'U',
	'Ǚ' => 'U',			'Ù' => 'U',			'Ú' => 'U',			'Ǘ' => 'U',
	'Ụ' => 'U',			'Ŭ' => 'U',			'Ừ' => 'U',			'Ứ' => 'U',
	'Ữ' => 'U',			'Ủ' => 'U',			'Ử' => 'U',			'Ư' => 'U',
	'Ü' => 'U',			'Ǜ' => 'U',			'Û' => 'U',			'Ů' => 'U',
	'Ű' => 'U',			'Ū' => 'U',			'Ų' => 'U'
];
echo strtr('testdata', $chars) . PHP_EOL;
```

### Expected result
testdata

### Actual result
Segmentation fault (core dumped)

**Comment by leewillis77** [comment]
I'm seeing this as well. Same symptoms as the I experienced in #6786 ?

**Comment by rinu** [comment]
I'm not using Wordpress or any other PHP library. It's a custom string format service, the above is a tiny part of it (minimal code to reproduce).

**Comment by leewillis77** [comment]
Sure - but it you follow that ticket through - you'll see that the issue there was in strtr as you noted in your report, so it's almost certainly related in some way.

**Comment by rinu** [comment]
OK now I get it. I assumed it got fixed because the issue you referenced has been closed.
The minimal test case you provided there is segfaulting with the latest release available, which is what I'm using. Why is that issue closed if it's not fixed?

**Comment by leewillis77** [comment]
It was fixed - as per my comment https://github.com/facebook/hhvm/issues/6786#issuecomment-182579196 it was definitely fixed. Either than fix didn't make it into the final release, or there's been some kind of regression I guess.

**Comment by fredemmott** [comment]
Yeah, that fix didn't go into 3.12 (https://github.com/facebook/hhvm/blob/HHVM-3.12/hphp/runtime/ext/string/ext_string.cpp#L1798) - I'm guessing the people reporting that it was fixed in 3.12.0 were either running nightlies (3.12-dev) or had a slightly different issue.

@paulbiss: Maybe cherry-pick for 3.12.2?

**Comment by fredemmott** [comment]
already fixed in master, but looks self-contained enough to consider for 3.12, so not just closing.

**Comment by rinu** [comment]
Downloaded the source from master, compiled following build instructions. hhvm executable segfaults every time, even without any arguments given. I think I'll wait for a release.

**Comment by fredemmott** [comment]
Will file a separate task for cherry pick then. If this is broken in master for you, it's unlikely to work in the next release. Added the 'no isolated repro' as the example you've given works fine in master on all the builds I have access to :(

**Comment by fredemmott** [comment]
Actually undoing, misread - always segfaulting is a different issue (that I think I've seen, buyt can't find) - can you file a separate issue for that, with your distribution information and gcc version? Also, you might have more luck with a -nightly package.

**Comment by rinu** [comment]
Thanks for the -nightly tip. Cannot reproduce the with nightly.

**Comment by fredemmott** [comment]
re-opening for cherry-pick
