### ISSUE TITLE
filter_input_array() expects at least 2 parameters, 1 given

### ISSUE THREAD

**Issue by WebDevJL** [facebook/hhvm#6919]
### HHVM Version
HipHop VM 3.6.6 (rel) on travis-ci.org

### Standalone code, or other way to reproduce the problem
`$arrayInput = filter_input_array(INPUT_SERVER);`

### Expected result
No exception!

### Actual result
This code throws an exception: https://api.travis-ci.org/jobs/116750389/log.txt?deansi=true
Apparently fixed in #6403 but not the case in v3.6.6.

**Comment by simonwelsh** [comment]
HHVM 3.6 is no longer supported. You should upgrade to a newer version.

This has also been fixed in 3.12.
