### ISSUE TITLE
Special-case preg_match(_all)'s $matches

### ISSUE THREAD

**Issue by HRMsimon** [facebook/hhvm#6923]
### HHVM Version

3.12.1
### Standalone code, or other way to reproduce the problem

``` hack
<?hh

function foo(string $blah) {
  preg_match('/./', $blah, $matches);
  var_dump($matches);
}
```
### Expected result

Hack would know that `preg_match` and `preg_match_all` have a reference parameter that gets set as an array, so doesn't require it to be defined beforehand.
### Actual result

Undefined variable: $matches

**Comment by Wilfred** [comment]
No longer relevant according to @simonwelsh.
