### ISSUE TITLE
Typechecker nullable check

### ISSUE THREAD

**Issue by wake-up-neo** [facebook/hhvm#6927]
### HHVM Version
HipHop VM 3.11.0 (rel)
Compiler: 1455186033_N
Repo schema: 4d3d19cb46fb2651317d6269a2f601f2d8e29601

### Standalone code, or other way to reproduce the problem

Case 1:
```
$params = [];
$currency = (array_key_exists('currency', $params) ? $params['currency'] : null) ?? 'USD';
$f = (string $currency) ==> { echo $currency; };
$f($currency);

```
Case 2:
```
$params = [];
$currency = (array_key_exists('currency', $params) ? $params['currency'] : null);
if ($currency === null) {
	$currency = 'USD';
}
$f = (string $currency) ==> { echo $currency; };
$f($currency);
```

### Expected result

Case 1:

> USD

Case 2:

> USD

### Actual result

Case 1:

> Invalid argument (Typing[4110])
> This is a string
> It is incompatible with a nullable type

Case 2:

> USD

### P.S.
This issue is related to typechecker and Null coalescing operator, but not to
```
$currency = (array_key_exists('currency', $params) ? $params['currency'] : 'USD')
```

But then again, this works normally
```
$currency = (array_key_exists('currency', $params) ? $params['currency'] : null);
$f = (string $currency) ==> { echo $currency; };
$f($currency ?? 'USD');
```

**Comment by fredemmott** [comment]
3.11 is unsupported, and this does not reproduce on 3.12:

```
fred@hhvm-oss-bench:/tmp/hhtest$ hhvm --version
HipHop VM 3.12.1 (rel)
Compiler: tags/HHVM-3.12.1-0-gf516f1bb9046218f89885a220354c19dda6d8f4d
Repo schema: f2e5f39b2ad4a08bcbd90b5d8bcb580f40fba6c8
fred@hhvm-oss-bench:/tmp/hhtest$ cat test.php
<?hh

function foo() {
$params = [];
$currency = (array_key_exists('currency', $params) ? $params['currency'] : null) ?? 'USD';
$f = (string $currency) ==> { echo $currency; };
$f($currency);
}
fred@hhvm-oss-bench:/tmp/hhtest$ hh_client
No errors!
```

As a side note, it's useful for typechecker examples to be complete files, and to include the full output, including line numbers etc.
