### ISSUE TITLE
SplFileObject with DROP_NEW_LINE flag, trims trailing tab char 

### ISSUE THREAD

**Issue by mudhoney** [facebook/hhvm#6928]
Hi, I have a problem with reading my tabbed file with SplFileObject. 
You can check the problem from this [link](https://3v4l.org/ChiNh) 

### HHVM Version
``3.6.1 - 3.12.0``

### Standalone code, or other way to reproduce the problem
```php 
<?php

$text =  "a\tb\tc\t\n";
$text .= "a\tb\tc\n";
$text .= "1\t2\t";

$file = new SplFileObject('data://text/plain,' . $text);
$file->setFlags(SplFileObject::DROP_NEW_LINE);

foreach($file as $row) {
    echo "+".$row."+\n";
}

$file = null;

```

### Expected result
```
+a	b	c	+
+a	b	c+
+1	2	+
```

### Actual result
```
+a	b	c+
+a	b	c+
+1	2+
```

**Comment by Orvid** [comment]
D3084508 up internally to fix this.
