### ISSUE TITLE
hhvm 3.12 crash in daemon when running with repo.authoritative=true

### ISSUE THREAD

**Issue by sINusBob** [facebook/hhvm#6931]
### HHVM Version
3.12
### Standalone code, or other way to reproduce the problem
Standalone code (Following the instructions from 'Building and installing hhvm on CentOS 7.x' - https://github.com/facebook/hhvm/wiki/Building-and-installing-hhvm-on-CentOS-7.x)

### Expected result
Should run after "sysctl start hhvm && sysctl status hhvm"

### Actual result
HHVM crash. hhvm.hhbc: No rows in main.GlobalData

If repo.authoritative=false, apparently ok

**Comment by Orvid** [comment]
Need more info before I can look into this, could you get a backtrace of the crash via gdb?

**Comment by aorenste** [comment]
This issue has been waiting for more info for more than 2 weeks. I'm closing it for now, but feel free to re-open it if you can provide more info. https://github.com/facebook/hhvm/wiki/Human-Timeouts
