### ISSUE TITLE
Support of curl CURLOPT_MAX_RECV_SPEED_LARGE option

### ISSUE THREAD

**Issue by laoneo** [facebook/hhvm#6935]
HHVM is supporting most of the curl options, but not the one to limit receiving speed (*CURLOPT_MAX_RECV_SPEED_LARGE*). Probably some more options are missing as well. For example *CURLOPT_MAX_SEND_SPEED_LARGE* can't be find [here](https://github.com/facebook/hhvm/blob/master/hphp/runtime/ext/curl/ext_curl.cpp).

### HHVM Version
HipHop VM 3.6.6 (rel)
Compiler: tags/HHVM-3.6.6-0-gead6875c956d4bd5e906ebea899c71c3b8a7182d
Repo schema: 5034239b4e72c991556d7e651946e7fe89d8c2f4

### Standalone code, or other way to reproduce the problem
    $ch = curl_init('http://github.com/facebook/hhvm');
    curl_setopt($ch,CURLOPT_MAX_RECV_SPEED_LARGE,10);
    curl_exec($ch);

### Expected result
Should not throw any error.

### Actual result
Error *Use of undefined constant CURLOPT_MAX_RECV_SPEED_LARGE - assumed 'CURLOPT_MAX_RECV_SPEED_LARGE'* is thrown.

**Comment by Orvid** [comment]
D3056455 already up internally to fix this.
