### ISSUE TITLE
Typechecker suggestion: flip default of assume_php to false

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#6936]
This catches a lot of problems, and is generally preferable. Would also need:
- hackificator to write assume_php=true by default for migration of PHP projects
- ideally, hackificator would also /try/ assume_php=false at the end
- documentation of assume_php=true in the migration docs

Previous discussion here: https://www.facebook.com/groups/hhvm.general/permalink/569799193173478/

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

`assume_php` was removed in hhvm [4.1.0](https://hhvm.com/blog/2019/04/09/hhvm-4.1.0.html). The value is always false.
