### ISSUE TITLE
Blocked sockets aren't working (stream_set_blocking() bug?)

### ISSUE THREAD

**Issue by kiler129** [facebook/hhvm#6938]
I spent couple of minutes trying to resolve this puzzle, but I'm still left with multi-bug rather than pinpointed issue.

I started with following code:
```php
<?php

$stream = stream_socket_server('tcp://127.0.0.1:32000');
$meta = stream_get_meta_data($stream);
var_dump($meta['blocked']);

stream_set_blocking($stream, 1);
$meta = stream_get_meta_data($stream);
var_dump($meta['blocked']);

stream_set_blocking($stream, 0);
$meta = stream_get_meta_data($stream);
var_dump($meta['blocked']);
```
Just by looking at https://3v4l.org/gI1rC it's clearly visible that `stream_set_blocking()` behavior is reversed or `stream_get_meta_data()` reports invalid state.
Issue is also consistent using standard client sockets: https://3v4l.org/pqTa9

Next I came up with following code:
```php
<?php
$stream = stream_socket_server('tcp://127.0.0.1:0');
$meta = stream_get_meta_data($stream);
var_dump($meta['blocked']);
fread($stream, 1);

stream_set_blocking($stream, 0);
$meta = stream_get_meta_data($stream);
var_dump($meta['blocked']);
fread($stream, 1);

stream_set_blocking($stream, 1);
$meta = stream_get_meta_data($stream);
var_dump($meta['blocked']);
fread($stream, 1);
```
This code running on PHP freezes at first `fread()` and blocked mode is reported, which is expected. However running it at HHVM 3.12.1 on OS X results in false/true/false without any freezing.
This suggests:
 - Stream is non-blocking by default (while in PHP is blocking)
 - `stream_set_blocking()` has reversed 2nd argument
 - `stream_get_meta_data()` reports just a state set by `stream_set_blocking()` instead of actual socket status

After I modified this code for client socket I noticed socket is opened in blocking mode but reported as non-blocking :-)
```php
$stream = stream_socket_client('tcp://example.com:80');
$meta = stream_get_meta_data($stream);
//stream_set_blocking($stream, 0);
var_dump($meta['blocked']);
fread($stream, 1);

stream_set_blocking($stream, 0);
$meta = stream_get_meta_data($stream);
var_dump($meta['blocked']);
fread($stream, 1);

stream_set_blocking($stream, 1);
$meta = stream_get_meta_data($stream);
var_dump($meta['blocked']);
fread($stream, 1);
```
However after I uncommented the line setting magic thing started to happen - non-blocking mode was reported (false from 1st var_dump), `fread()` passed, the second exact the same call to `stream_set_blocking()` didn't changed the real state of the socket (since 2nd `fread()` also passed) but it was reported as blocked (true from 2nd `var_dump()`)

### Summary
![summary](http://i.imgur.com/k9cdpBI.png)

**Comment by kiler129** [comment]
Any word on this issue? I don't want to sound rude or put pressure on anyone, but I think it's rather important bug - improperly working stream blocking disqualifies HHVM completely from any network-related applications.

**Comment by Orvid** [comment]
D3192557 up internally to fix this.

The issue was exclusive to Socket::getMetaData(), which was setting `blocked` to true if the socket was non-blocking, and false otherwise. Non-blocking sockets were working correctly, they just weren't being correctly reported as non-blocking via `stream_get_meta_data`.

**Comment by kiler129** [comment]
Great, so is there any way to determine if socket is blocked besides verifying if `fread()` freezes? Using `stream_get_meta_data()` in tests is pretty easy, but I don't see another way to unit test a code for that behavior.

**Comment by Orvid** [comment]
I think `stream_get_meta_data()` is probably enough.

**Comment by kiler129** [comment]
Yes, it is after path, but if possible I would like to provide BC solutions in my tests ;)
Now the only thing I can do is skip test on lower HHVM version and leave a explanatory command since `stream_get_meta_data()` is little unpredictable on lower versions (+ stream state is different from ZE one).
