### ISSUE TITLE
stream_select() error handling is broken (and may result in endless loop)

### ISSUE THREAD

**Issue by kiler129** [facebook/hhvm#6942]
### HHVM Version
Installed from official Debian repo.
```
# cat /etc/debian_version
stretch/sid

# hhvm --version
HipHop VM 3.12.0 (rel)
Compiler: 3.12.0+dfsg-1
Repo schema: 3b8615dabdef35cea5c1628aa44d7ac692cf5346
```

### Standalone code, or other way to reproduce the problem
This issue was found during testing of problem described on PHP-Internals list: http://news.php.net/php.internals/91974 

HHVM react differently than PHP and in fact completely different than POSIX [`select()`](http://man7.org/linux/man-pages/man2/select.2.html).
PHP returns all the arrays unmodified with `false` from `stream_select()` while HHVM returns `0` and empty arrays. It will send the script into endless loop - it makes **impossible** to detect any kind of errors on sockets (since arrays are empty).

**Comment by aorenste** [comment]
I'm seeing the same behavior for php 5, 7 and hhvm: https://3v4l.org/h8hAn.  If I'm misinterpreting the issue please clarify and reopen.
