### ISSUE TITLE
Please provide extension for postgres.

### ISSUE THREAD

**Issue by jpuri** [facebook/hhvm#6944]
### HHVM Version
HipHop VM 3.12.1 (rel)
Compiler: 1459072447_N
Repo schema: 6e9fe4a2450529ea53f4e4acdbc4723a472bbd66

Please provide extension for postgres.

**Comment by fredemmott** [comment]
- https://github.com/PocketRent/hhvm-pgsql
 - https://github.com/facebook/hhvm/pull/6849

**Comment by jpuri** [comment]
Trouble with PocketRent on my MAC: https://github.com/PocketRent/hhvm-pgsql/issues/109
