### ISSUE TITLE
stream_context_set_option with array of options does not work

### ISSUE THREAD

**Issue by effeks** [facebook/hhvm#6948]
### HHVM Version
3.12.1

### Standalone code, or other way to reproduce the problem
```
<?php
$opts = array('http' =>
    array(
        'method' => 'GET',
    )
);
$context = stream_context_create($opts);

$o = array('ssl' => array('verify_peer' => false));

stream_context_set_option($context, $o);
```

### Expected result
No warning.

### Actual result
```
[Wed Mar 30 11:33:58 2016] [hphp] [25062:7f463d85b100:0:000001] [] 
Warning: called with wrong number or type of parameters; please RTM in epa.php on line 11
```

### HHVM code at
`https://github.com/facebook/hhvm/blob/fd456ffad5d164c1563dc8bd97bcc2f200ff6f69/hphp/runtime/ext/stream/ext_stream.cpp` line 241.

**Comment by aorenste** [comment]
It looks like this has been fixed since the original report.
