### ISSUE TITLE
compilation error in array-init.cpp with -DDEBUG -DNDEBUG

### ISSUE THREAD

**Issue by mibintc** [facebook/hhvm#6951]
### Standalone code, or other way to reproduce the problem; compilation error with -DDEBUG -DNDEBUG : hhvm-3.10.0/hphp/runtime/base/array-init.cpp:26:5: error: class HPHP::ArrayInitâ does not have any field named m_addCount
   : m_addCount(0)

### Actual result: compilation error
 I'm building hhvm with the Intel compiler and wanted to make a debug build so I can use the trace facility. I can add -DDEBUG onto all compilation lines by using a facility built into the Intel compiler (environment variables). When I did this all files compiled successfully except array-init.cpp. I noticed that in array-init.h the members m_addCount are defined # ifndef NDEBUG but in array-init.cpp the members are initialized # if DEBUG.  Does it make sense to use the same macro in both source files?
Thanks and regards, Melanie Blower (iworkforintel)
PS No doubt I used the wrong way to build the makefile /cmake -DCMAKE_C_COMPILER:FILEPATH=`which icc` -DMYSQL_UNIX_SOCK_ADDR=/dev/null -DCMAKE_INSTALL_PREFIX=.../hhvminstall -DCMAKE_CXX_COMPILER:FILEPATH=`which icpc` -DCMAKE_VERBOSE_MAKEFILE=ON .

**Comment by fredemmott** [comment]
HHVM 3.10 is unsupported, so we won't be doing a change. Does the same problem exist with master or 3.12?

**Comment by mibintc** [comment]
Yes it’s on master

**Comment by Orvid** [comment]
You shouldn't be building with both of those defined.
