### ISSUE TITLE
500 hphp_invoke

### ISSUE THREAD

**Issue by baobeixiaolanyu** [facebook/hhvm#6956]
my HHVM Version:
HipHop VM 3.8.1 (rel)
Compiler: tags/HHVM-3.8.1-0-g3006bc45691762b5409fc3a510a43093968e9660
Repo schema: 253b3802ce1bcd19e378634342fc9c245ac76c33

my php.ini
; php options
session.save_handler = files
session.save_path = /var/lib/hhvm/sessions
session.gc_maxlifetime = 1440
 
 ; hhvm specific 
 hhvm.log.level = Error
 hhvm.log.always_log_unhandled_exceptions = false
 hhvm.log.runtime_error_reporting_level = 8191
 hhvm.mysql.typed_results = false

my server.ini
; php options
pid = /var/run/hhvm/pid
; hhvm specific 
 hhvm.server.port = 9000
 hhvm.server.type = fastcgi
 hhvm.server.default_document = index.php
 hhvm.log.use_log_file = true
 hhvm.log.file = /var/log/hhvm/error.log
 hhvm.repo.central.path = /var/run/hhvm/hhvm.hhbc

in my project, when i request url -- http://10.1.1.163/platform/gm/application/webroot/index.php?r=user/login by ajax , get the results--500 hphp-invoke,  and no log in /var/log/hhvm/error.log

please hlep

**Comment by baobeixiaolanyu** [comment]
when i change hhvm to php5, there is no 500 error

**Comment by racardoso** [comment]
I got the same error running oss-performance on 3.13 version. Solved this adding `assert.active=false` to php.ini file. I don't known if it can helps you.

**Comment by Orvid** [comment]
This usually means that HHVM crashed. Is HHVM still running after you get the 500 error?

**Comment by baobeixiaolanyu** [comment]
added assert.active=false to php.ini file, it's useless.  

and the hhvm is still running

**Comment by Orvid** [comment]
Does it still happen on 3.13.1?

**Comment by baobeixiaolanyu** [comment]
my version is not 3.13.1

**Comment by SiebelsTim** [comment]
He wants you to test version 3.13.1, as 3.8 is outdated

**Comment by baobeixiaolanyu** [comment]
ok

**Comment by aorenste** [comment]
This issue has been waiting for more info for more than 2 weeks. I'm closing it for now, but feel free to re-open it if you can provide more info. https://github.com/facebook/hhvm/wiki/Human-Timeouts
