### ISSUE TITLE
cd to /hphp/util

### ISSUE THREAD

**Issue by alex-mashin** [facebook/hhvm#6957]
### HHVM version:
HHVM 3.13 (does not occur under 3.12.1), Ubuntu 15.10

### To reproduce:
get luasandbox (`git clone https://gerrit.wikimedia.org/r/p/mediawiki/php/luasandbox.git`) and build it: `sudo hphpize && cmake . && sudo make install`.

### Expected result:
`luasandbox.so` is built in `/usr/lib/x86_64-linux-gnu/hhvm/extensions/20150212`.

### Actual result: 
```
cd /hphp/util && /hphp/util/generate-buildinfo.sh
/bin/sh: 1: cd: can't cd to /hphp/util
CMakeFiles/luasandbox.dir/build.make:218: recipe for target 'luasandbox.so' failed
make[2]: *** [luasandbox.so] Error 2
make[2]: Leaving directory '/var/www/wiki/w/extensions/luasandbox'
CMakeFiles/Makefile2:63: recipe for target 'CMakeFiles/luasandbox.dir/all' failed
make[1]: *** [CMakeFiles/luasandbox.dir/all] Error 2
make[1]: Leaving directory '/var/www/wiki/w/extensions/luasandbox'
Makefile:119: recipe for target 'all' failed
make: *** [all] Error 2
```

The command to cd to `/hphp/util` is in `./CMakeFiles/luasandbox.dir/build.make`. This file also has `objcopy --add-section compiler_id=/hphp/util/generated-compiler-id.txt --add-section repo_schema_id=/hphp/util/generated-repo-schema-id.txt --add-section ext.44d8b84210d7=ext_luasandbox.php luasandbox.so`. Another file references another non-existing directory: `./CMakeFiles/luasandbox.dir/CXX.includecache` has: `/usr/include/hphp/runtime/ext_zend_compat/php-src/TSRM/hphp/util/thread-local.h` and `/usr/include/hphp/runtime/ext_zend_compat/php-src/main/hphp/util/type-scan.h`.

**Comment by simonwelsh** [comment]
We're seeing this with hhvm-pgsql too. Commit that caused it was 1af590b760b1f362a61b55d023aecddb3485aa1c by @alexmalyshev

**Comment by alex-mashin** [comment]
> Commit that caused it was 1af590b by @alexmalyshev
Thank you Alex.

**Comment by alex-mashin** [comment]
> Commit that caused it was 1af590b by @alexmalyshev
What is ${HPHP_HOME}? Perhaps, I can set it somewhere correctly?

**Comment by derickr** [comment]
Please note, that a fix for this has been merged ages ago, but it has not made it into a release yet: https://github.com/facebook/hhvm/pull/6900

**Comment by raeesiqbal** [comment]
Bump...

**Comment by Orvid** [comment]
As the fix already merged, I'm going to close this for now.

**Comment by alex-mashin** [comment]
In which released version was the patch merged?

**Comment by simonwelsh** [comment]
It hasn't been released, and is unlikely to be until 3.14, so there's no support for building extensions in a 3.13 release.

**Comment by alex-mashin** [comment]
As its number would suggest, a really unlucky release.

**Comment by derickr** [comment]
When is 3.14 supposed to come out?

**Comment by bmcfarlin** [comment]
I solved the problem by cloning the hhvm repository, copying the hphp folder to the root directory and setting the proper permissions.  

1.  git clone https://github.com/facebook/hhvm.git
2. cd hhvm
3. cp -R hphp /
4. sudo chown -R [username]:root /hphp

After that I was able to build an extension.

**Comment by asgrim** [comment]
Can't build against 3.13 because of this bug, and the last compilation I have (for 3.12) for my exts won't run in 3.13 (e.g. `Uncaught exception: ./calc.so was built for HHVM 3.12, and cannot be loaded with HHVM 3.13`) so stuck somewhat between a rock and a hard place; currently only option for me is to downgrade to 3.12...

**Comment by alex-mashin** [comment]
Exactly. HHVM 3.13 is not functional if you build any extensions.

**Comment by hopeseekr** [comment]
Shame on FB for not caring about corporations who have decided to use HHVM in production!! We are *stuck* on `3.12` because of your inane decision **NOT** to give a patch release for this **critical** issue! Do you think we can somehow go without PostgreSQL support???

**Comment by photodude** [comment]
Is this still an issue with recent hhvm 3.13.2 release?

**Comment by simonwelsh** [comment]
Yes.

**Comment by alex-mashin** [comment]
Repaired in 3.14.
