### ISSUE TITLE
gcc 6 compile successful

### ISSUE THREAD

**Issue by javacty** [facebook/hhvm#6958]
HipHop VM 3.14.0-dev (rel)
Compiler: heads/master-0-g79e548a0a401a92fcaa192e814ef5e4770f969dc
Repo schema: 6e1d192b91b64543bdc40d54e299532c62dd30f4

Fedora release 25 (Rawhide)
gcc Version 6.0.0 20160311 (Red Hat 6.0.0-0.17) (GCC)

Modify hhvm/hphp/runtime/vm/bytecode.h
130:  "TypedValue m_extraArgs[];" ===> "TypedValue m_extraArgs[0];"

**Comment by Orvid** [comment]
Open a PR for this rather than an issue.
