### ISSUE TITLE
Some Informations are not getting updated regularly

### ISSUE THREAD

**Issue by corientdev** [facebook/hhvm#6965]
Hi, 

Just a suggestion Kind of Post.

I regularly check release schedule of HHVM and some other softwares. It actually gives me better idea about when i should touch my server for software updates. For HHVM it was regularly updated here @https://github.com/facebook/hhvm/wiki/release-schedule

Now after you guys moved it to @https://docs.hhvm.com/hhvm/installation/release-schedule

There is no update after 2015. If you require i can contribute for this at least. but, request you guys to please keep it updated. It is actually a great sign of project management and add up so much postive about project in the mind of users and others.

**Comment by corientdev** [comment]
anybody's here?
@jwatzman 
@fredemmott

**Comment by jwatzman** [comment]
@paulbiss you're the one in charge of this now right?

**Comment by vishirockz** [comment]
+1

**Comment by mofarrell** [comment]
The release schedule is now updated, and has been for the last 3 months.  We will do our best to keep it up to date, and post release notes on the blog.  It is worth noting that security releases are not publicized, but occur at the cadence of every two weeks (assuming there are security patches).
