### ISSUE TITLE
PHP 7 Inconsistency in substr

### ISSUE THREAD

**Issue by GrahamCampbell** [facebook/hhvm#6966]
### Standalone code, or other way to reproduce the problem

```php
<?php var_dump(substr('', 0, 1));
```

### Expected result

```
string(0) ""
```

### Actual result

```
bool(false)
```

**Comment by SiebelsTim** [comment]
Yep, this changed in 7.0
https://3v4l.org/42oCR

**Comment by LZL0** [comment]
is it a real issue?

**Comment by Orvid** [comment]
Yes.

**Comment by LZL0** [comment]
I am just wondering why

**Comment by GrahamCampbell** [comment]
> is it a real issue?

I'm a bit confused by that question? The return value of a function differs from that of PHP 7, thus we clearly have a bug here, albeit, pretty minor.
