### ISSUE TITLE
Anonymous functions optimization

### ISSUE THREAD

**Issue by nazar-pc** [facebook/hhvm#6969]
In my system there are multiple anonymous functions used as callbacks for events.

I'm running ReactPHP server in order to avoid bootstrap overhead and reuse as much of existing stuff between requests as possible.

Having that said I was trying to reuse anonymous functions stored in array, since when request processing begins, set of event handlers is always constant.

### Very trivial shortened example

First request:
```php
class Event {
...
    function on ($event, $callback) {
        $this->callbacks[$event] = $callback;
    }
    function fire ($event, $data) {
        return $this->callbacks[$event]($data);
    }
    function save () {
        $this->callbacks_cache = $this->callbacks;
    }
    function restore () {
        $this->callbacks = $this->callbacks_cache;
    }
...
}
...
$Event->on('whatever', function () {...});
$Event->on('whatever2', function () {...});
...
$Event->save();
...
$Event->fire('whatever');
```
And starting from second request just:
```php
$Event->restore();
...
$Event->fire('whatever');
```
`$Event` is always the same instance.

However I haven't seen any significant performance boost after this change.

So there is a question: **does HHVM optimize anonymous functions in such cases?** I'd like to avoid using classes with static methods instead of anonymous functions for situations like mentioned above.

**Comment by Orvid** [comment]
HHVM would already be re-using the closure wherever possible.
