### ISSUE TITLE
extended ascii heredoc labels not accepted

### ISSUE THREAD

**Issue by nikic** [facebook/hhvm#6970]
### HHVM Version

3v4l all

### Standalone code, or other way to reproduce the problem

```
var_dump(eval("return <<<\xff\nXYZ\n\xff\n;"));
```

https://3v4l.org/fWX9I

### Expected result

```
string(3) "XYZ"
```

### Actual result

```
Fatal error: Unterminated heredoc at end of file (Line: 1, Char: 18) syntax error, unexpected $end in /in/fWX9I(3)(11cd92606aa2a975a0958cb20ba5a4f0) : eval()'d code on line 1 bool(false)
```

Probably some kind of signed unsigned mismatch. Maybe IS_LABEL_START?

**Comment by Orvid** [comment]
Fix already landed.
