### ISSUE TITLE
HHVM Stops every minute

### ISSUE THREAD

**Issue by vishirockz** [facebook/hhvm#6976]
Newest version of HHVM stops every minute and do not log any error in `/var/log/hhvm/error.log`

I run wordpress. It was working fine till last release

**Comment by vishirockz** [comment]
@jwatzman @paulbiss @fredemmott  kindly confirm and please tell me how to roll back to last version

**Comment by Orvid** [comment]
What version of HHVM are you running currently?

**Comment by vishirockz** [comment]
`3.13.0`

**Comment by Orvid** [comment]
Upgrade to 3.13.1 and it should work correctly. 3.13.0 had an issue with logging.

**Comment by vishirockz** [comment]
yaa i just did that didn't expected release this often.

nobbody knows this days when next version of hhvm will be released as release schedule n some docs are not updated regularly..

cheers man for the fix you rock!

**Comment by SiebelsTim** [comment]
The .1 release was specifically for this error. It wasn't planned.

**Comment by corientdev** [comment]
yes but even the major release date are also missing from release schedule.

**Comment by jwatzman** [comment]
See #6965 for the issue with the release schedule.
