### ISSUE TITLE
PHP function not implemented: stream_set_read_buffer

### ISSUE THREAD

**Issue by kiler129** [facebook/hhvm#6977]
### HHVM Version
All, latest checked: 3.12.0

### Standalone code, or other way to reproduce the problem
[See at 3v4l](https://3v4l.org/Lq3hf)
```php
<?php
var_dump(function_exists('stream_set_read_buffer'));
```

### Expected result
`bool(true)`

### Actual result
`bool(false)`

**Comment by doublecompile** [comment]
To whichever of our wonderful contributors tackles the implementation of this function, please see also #6573
