### ISSUE TITLE
stream_socket_shutdown() with already shutdown stream raises warning on OSX

### ISSUE THREAD

**Issue by kiler129** [facebook/hhvm#6978]
### HHVM Version

3.12.1 running on OS X

`Darwin X.local 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64`
### Standalone code, or other way to reproduce the problem

``` php
<?php
$s = stream_socket_client('udp://127.0.0.1:9999');
var_dump(
    stream_socket_shutdown($s, STREAM_SHUT_RD),
    stream_socket_shutdown($s, STREAM_SHUT_RD)
);
```
### Expected result

``` php
bool(true)
bool(false)
```
### Actual result

``` php
Warning: unable to shutdown socket [57]: Socket is not connected in /.../test.php on line 5
bool(true)
bool(false)
```

**Comment by Vahanerevan** [comment]
+1

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Support for MacOS was dro0ed in June of last year. https://hhvm.com/blog/2022/06/17/deprecating-homebrew.html
