### ISSUE TITLE
Cannot call getMethods on newReflectionClass('Exception') in debugger

### ISSUE THREAD

**Issue by zodiac** [facebook/hhvm#6983]
### HHVM Version

3.14.0

### Standalone code, or other way to reproduce the problem

In the debugger, enter

```
$e = new ReflectionClass('Exception');
var_dump($e->getMethods());
```

### Expected result

An array of 16 objects. Running just the hhvm cli on the above code prints it properly.

### Actual result

```
wire error: unserialize() threw 'A null object pointer was used.
'
null
```

**Comment by aorenste** [comment]
This should now be implemented.
