### ISSUE TITLE
libwangle.a(Dummy.cpp.o) has no symbols

### ISSUE THREAD

**Issue by threkk** [facebook/hhvm#6984]
### HHVM Version
`hhvm/hhvm/hhvm: stable 3.12.1, HEAD`
### Standalone code, or other way to reproduce the problem
Installing or upgrading HHVM in Mac OS X 10.10.5 (14F1713) using `brew`
### Expected result
Successful install or update.
### Actual result
[Error logs and verbose install](https://gist.github.com/threkk/4aad7009e22dc60ba94675e19f293603)

*(From #6324)*

**Comment by Orvid** [comment]
That's not what is causing that build to fail, https://gist.github.com/threkk/4aad7009e22dc60ba94675e19f293603#file-brew_install_verbose-txt-L2953 says that _sdallocx is referenced but not defined.

**Comment by threkk** [comment]
Any suggestion about what to do?

**Comment by Orvid** [comment]
You want to be building with JEMalloc enabled, as that's where that function is defined.

**Comment by Orvid** [comment]
I'm going to assume you got the issue fixed and close this.
