### ISSUE TITLE
PHP 7 incompatibility with type converter for 'INF'/'NAN'

### ISSUE THREAD

**Issue by darkain** [facebook/hhvm#6986]
With hhvm.php7.all both enabled and disabled, HHVM returns the PHP 5.x results for string to float conversions, instead of the PHP 7 results.
### HHVM Version

3.13.1
### Standalone code, or other way to reproduce the problem

var_dump( (float)'INF' );
var_dump( (float)'NAN' );
var_dump( (float)'STRING' );
### Results

https://3v4l.org/GK4he

**Comment by jwatzman** [comment]
Sigh, I don't recall this one being documented in any of the PHP7 RFCs back when I was doing this feature for PHP7. It is indeed probably easy. (But I've moved off the team and likely won't get time to do it myself.)

**Comment by Orvid** [comment]
Well, this is easy for us to do on our side for var_dump, but the change in PHP to do this was in the implementation of `spprintf`, and trying to get that everywhere it's supposed to be... Ekk...

**Comment by Orvid** [comment]
D3289627 up internally to fix this.

**Comment by darkain** [comment]
As a note, var_dump was just an example to output the value, but this issue isn't related to var_dump at all. It is the internal type converter that is at fault here, actually. It is the basic STRING to FLOAT conversion that is going on, changing special string values to special float values, instead of defaulting to 0.0 float value.

**Comment by Orvid** [comment]
Yep, I just failed to realize which direction this was going at first (I eventually got it right, which is what's in that diff internally)

**Comment by darkain** [comment]
As a note to anyone finding this in the future:
PHP 7.1 reverted this behavior back to the 5.6 style.
HOORAY FOR CONSISTENCY!

**Comment by nikic** [comment]
The behavior was also reverted in 7.0 -- the original change was an unintended side-effect of a strtod update.

**Comment by Orvid** [comment]
-_-... Alright, time to revert the commit :)

**Comment by Orvid** [comment]
Reverted in 0e76916224bb4a9dfc7cc427778c65922fc47911.
