### ISSUE TITLE
Incorrect parsing of interpolated constant-variable expressions. in ${}

### ISSUE THREAD

**Issue by sgolemon** [facebook/hhvm#6987]
### Standalone code, or other way to reproduce the problem

```
define('foo', 'bar');
$bar = 'Interpolated as constant';
$foo = 'Interpolated as variable';
echo "${foo }\n";
echo "${ foo}\n";
echo "${ foo }\n";
echo "${foo}\n";
```
### Expected result (PHP5 & PHP7 output)

Interpolated as constant
Interpolated as constant
Interpolated as constant
Interpolated as variable
### Actual result from HHVM

Interpolated as variable
Interpolated as variable
Interpolated as variable
Interpolated as variable

See also: https://3v4l.org/Z8pHh for executed code

**Comment by Orvid** [comment]
Can we file a bug against PHP for their behavior being wrong? :P

**Comment by SiebelsTim** [comment]
@Orvid That's what I wanted to say too, but how would you use a constant then? :P

**Comment by Orvid** [comment]
I don't see how the spacing should have any effect on it though, it should be consistent in all cases, which is what HHVM is doing. HHVM does still have an issue here though, because when you attempt to force interpolation as a constant by surrounding it in parenthesis, HHVM still interprets it as a variable, such that:
```PHP
define('foo', 'bar');
$bar = 'Interpolated as constant';
$foo = 'Interpolated as variable';
echo "${(foo)}\n";
```
Gets this under PHP:
```
Interpolated as constant
```
But this under HHVM:
```
Interpolated as variable
```

https://3v4l.org/45XqG

**Comment by sgolemon** [comment]
There is a PHP bug (where I found this, actually): https://bugs.php.net/bug.php?id=71927

There's one comment so far suggesting that the behavior is **intentional**.  I have a hard time imagining how one would get that result accidentally, tbqh.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Support for `${name}` style interpolation has been removed from hhvm [4.19.0](https://hhvm.com/blog/2019/08/19/hhvm-4.19.0.html), use `{$name}` instead.
