### ISSUE TITLE
Cannot execute script using hhvm, php7 works yet xml extension not loaded even if it is configured

### ISSUE THREAD

**Issue by ItsAdventureTime** [facebook/hhvm#6989]
Hello,

I saw the following errors in the error.log file of nginx:

Finished singleJitRequest 1
Finished singleJitRequest 2
Finished singleJitRequest 3
Finished singleJitRequest 4
Finished singleJitRequest 5
Finished singleJitRequest 1
Finished singleJitRequest 2
Finished singleJitRequest 3
Finished singleJitRequest 4
Finished singleJitRequest 5
Finished singleJitRequest 1
Finished singleJitRequest 2
Finished singleJitRequest 3
Finished singleJitRequest 4
Finished singleJitRequest 5

HipHop VM 3.13.1 (rel)
Compiler: tags/HHVM-3.13.1-0-g4f382ad928a6e2a0607a8dcb251002aca77f11f6
Repo schema: 655b5912cb8136e9df6f9be972153e38ac446e0f

I am also using Ubuntu 14.04.

I have attached the hhvm server.ini and php.ini. The error log file of hhvm is blank.

[php.ini.txt](https://github.com/facebook/hhvm/files/218517/php.ini.txt)
[server.ini.txt](https://github.com/facebook/hhvm/files/218516/server.ini.txt)

As for nginx, I also attached the useful conf files.

[access-nginx.log.txt](https://github.com/facebook/hhvm/files/218510/access-nginx.log.txt)
[error-nginx.log.txt](https://github.com/facebook/hhvm/files/218511/error-nginx.log.txt)
[default.conf.txt](https://github.com/facebook/hhvm/files/218512/default.conf.txt)
[fastcgi.conf.txt](https://github.com/facebook/hhvm/files/218513/fastcgi.conf.txt)
[hhvm.conf.txt](https://github.com/facebook/hhvm/files/218514/hhvm.conf.txt)
[nginx.conf.txt](https://github.com/facebook/hhvm/files/218515/nginx.conf.txt)

I look forward resolving the issues with your help.

Thanks.

**Comment by Orvid** [comment]
What is the script you are trying to run?

**Comment by ItsAdventureTime** [comment]
rutorrent. It works before. I don't know if it is because I added the following in the nginx configuration:

`Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' ; script-src 'self' 'unsafe-inline' 'unsafe-eval' ; style-src 'self' 'unsafe-inline' ; img-src * ; font-src * ; connect-src * ; media-src 'self' ; object-src 'none' ; child-src 'self' ; frame-ancestors 'self' ; form-action 'self' ; upgrade-insecure-requests; block-all-mixed-content; sandbox allow-forms allow-same-origin allow-scripts allow-top-navigation allow-popups; reflected-xss block; manifest-src 'self' ;`

I generated it here https://report-uri.io/home/generate

**Comment by Orvid** [comment]
What do you mean by "xml extension not loaded even if it is configured"?

**Comment by Orvid** [comment]
This issue has been waiting for more info for more than 2 weeks. Closing for now, feel free to re-open it if you can provide more info.

https://github.com/facebook/hhvm/wiki/Human-Timeouts
