### ISSUE TITLE
Array access on constants not supported

### ISSUE THREAD

**Issue by simonwelsh** [facebook/hhvm#6992]
### HHVM Version

3.13.1

### Standalone code, or other way to reproduce the problem

```php
<?php

define('great','my');

echo great[1];
```

### Expected result

`y`

### Actual result

`Fatal error: syntax error, unexpected '[', expecting ',' or ';' `

Support for this was added in PHP 5.6 (https://3v4l.org/0EiYf)

**Comment by apeabody** [comment]
Interestingly this DOES work in conjunction with round brackets such as:
hphp/hhvm/hhvm --php -r 'define("great","my"); echo (great)[1];'

Even more suprising it appears this particular syntax "echo (great)[1]" SHOULDN'T work in php5, only in php7: https://3v4l.org/V430Y

I'm pretty sure all of these can be resolved in hphp/parser/hphp.y - but I haven't used Bison before.  If I get a chance maybe I'll look into it tomorrow.
