### ISSUE TITLE
Piwigo setting upload_form_chunk_size (500kB) should be smaller than PHP configuration setting upload_max_filesize (0kB)

### ISSUE THREAD

**Issue by kamijoutouma** [facebook/hhvm#6996]
### HHVM Version
HipHop VM 3.13.1 (rel)
Compiler: tags/HHVM-3.13.1-0-g4f382ad928a6e2a0607a8dcb251002aca77f11f6
Repo schema: 655b5912cb8136e9df6f9be972153e38ac446e0f

### Standalone code, or other way to reproduce the problem
Install piwigo and goto the admin control panel and try to add an image. http://example.com/admin.php?page=photos_add

### Expected result
Should be no errors

### Actual result
Gets an error stating this "Piwigo setting upload_form_chunk_size (500kB) should be smaller than PHP configuration setting upload_max_filesize (0kB)"

http://i.imgur.com/FhchxuQ.png

**Comment by kamijoutouma** [comment]
As far as i know hhvm sets the default to 100MB so 0kB makes no sense.

**Comment by kamijoutouma** [comment]
https://github.com/Piwigo/Piwigo/issues/465

**Comment by Orvid** [comment]
It appears that HHVM is only handling the PHP INI setting at a MB level, and is returning 0M as the `upload_max_filesize`. Setting the `upload_max_filesize` setting to at least 1 MB should be enough to get it to not produce an error.

**Comment by Orvid** [comment]
D3192410 up internally to fix this.

**Comment by kamijoutouma** [comment]
Awesome

**Comment by kamijoutouma** [comment]
@Orvid will this be in the nightly build because i just installed the nightly and i'm still getting the same issue. Although this time when uploading an image the upload bar is forever loading.

**Comment by kamijoutouma** [comment]
@Orvid http://i.imgur.com/XTHP0Tc.png
