### ISSUE TITLE
How to disable static file serving?

### ISSUE THREAD

**Issue by lethalman** [facebook/hhvm#6997]
### HHVM Version

3.12.1
### Standalone code, or other way to reproduce the problem

Configuration:

```
hhvm.server.source_root = /somedir

hhvm.virtual_host[default][rewrite_rules][*][pattern] = (.*)
hhvm.virtual_host[default][rewrite_rules][*][to] = /index.php$1
hhvm.virtual_host[default][rewrite_rules][*][qsa] = true
```
### Expected result

All requests to be rewritten to `/index.php`, static files are not being served.
### Actual result

Static files are still being served.

If I add `hhvm.server.enable_static_content_from_disk = false` static files are parsed as php. That means if I point to an existing php file it's executed.
I've also tried `hhvm.virtual_host[default][CheckExistenceBeforeRewrite] = false` but it seems to be ignored.

How do I make sure every url is rewritten to `/index.php`?

**Comment by javacty** [comment]
Try it like this:
hhvm.virtual_host[default][rewrite_rules][*][pattern] = '^(.*)$'
hhvm.virtual_host[default][rewrite_rules][*][to] = /index.php/$1
hhvm.virtual_host[default][rewrite_rules][*][qsa] = true

I test it ,OK.

**Comment by lethalman** [comment]
@javacty it's the same, it's still serving static files.

**Comment by lethalman** [comment]
Any hints on this? It's a high security issue for running web apps.

**Comment by Orvid** [comment]
How are you using HHVM? Are you using it through the fastcgi interface in combination with apache or nginx, or are you using proxygen?

**Comment by lethalman** [comment]
I'm using `hhvm -m server` behind nginx with proxy pass.

**Comment by raeesiqbal** [comment]
@lethalman you can use [HHVM in FastCGI mode](https://docs.hhvm.com/hhvm/advanced-usage/fastCGI) and have [NGINX connect to it via that interface](https://www.digitalocean.com/community/tutorials/how-to-install-hhvm-with-nginx-on-ubuntu-14-04) only to execute a `php` or `hh` file.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

There is an ini setting available for Proxygen deployments. `hhvm.server.enable_static_content_from_disk=false` https://github.com/hhvm/user-documentation/blob/main/hhvm.prod.ini

If you do not provide a file cache, your server will always serve requests by evaluating your code (provided you have a 404 document) even when the provided file name matches a file on disk. In nginx (or fpm more generally), your webserver is responsible for serving static files.

**Comment by lexidor** [comment]
Sorry, I memorized the wrong setting name. The setting is not 404 document but global document. The global document always takes control, even if there is a file on disk, not the 404 document.

**Comment by lexidor** [comment]
https://github.com/facebook/hhvm/commit/c59a087967633a37c8cd2389d38a0fb7904428e1

The Global Document mode is best documented in its commit message.
