### ISSUE TITLE
fopen mode is not converted

### ISSUE THREAD

**Issue by jg-development** [facebook/hhvm#6999]
### HHVM Version 3.13.1

Hi,

the stream_get_meta_data does not convert file modes.
The given file mode "rw" should be convert in "r+b" or "r+".

$file = fopen('php://memory', 'rw');
stream_get_meta_data($file);

The result of hhvm is "rw", which is not correct.

Greetings Jan

**Comment by Orvid** [comment]
Clearer repro case:
https://3v4l.org/6bntD

**Comment by Orvid** [comment]
A bit of digging produces an interesting tidbit of information: PHP doesn't translate them on normal files, https://3v4l.org/UE5Zs

I'm still digging to see if this behavior is specific to memory streams.

**Comment by Orvid** [comment]
D3197336 up internally to fix this.
