### ISSUE TITLE
HHVM Warning: Parameter 1 to W3_Plugin_TotalCache::ob_callback() line 3553

### ISSUE THREAD

**Issue by txaqo** [facebook/hhvm#7003]
### HHVM Version

HipHop VM 3.12.1 (rel)
Compiler: tags/HHVM-3.12.1-0-gf516f1bb9046218f89885a220354c19dda6d8f4d
Repo schema: f2e5f39b2ad4a08bcbd90b5d8bcb580f40fba6c8

### Standalone code, or other way to reproduce the problem

[Tue Apr 19 16:14:40 2016] [hphp] [31340:7fdd03bff700:1429:000001] [] \nWarning: Parameter 1 to W3_Plugin_TotalCache::ob_callback() expected to be a reference, value given in /var/www/xxx.com/htdocs/wp-includes/functions.php on line 3553

```
function wp_ob_end_flush_all() {
        $levels = ob_get_level();
        for ($i=0; $i<$levels; $i++)
                ob_end_flush();                  <<<<< 3553
}
```

**Comment by txaqo** [comment]
could i be the one going through this?

**Comment by Orvid** [comment]
This may be an issue with the TotalCache plugin itself, as PHP should be giving you the same warning.

**Comment by chadschulz** [comment]
This is a well documented issue that also affects W3TC and php 7.
Check this link:
[github fork with code change for W3TC fix.](https://github.com/gadelkareem/wp-w3-total-cache/commit/e71030e89f4cd666742ae2ec39451782beb42f3a)

**Comment by Orvid** [comment]
As it's external, there's nothing we can do about it, closing.
