### ISSUE TITLE
XHP Library From Facebook Has TypeChecker Problems

### ISSUE THREAD

**Issue by ChrisReeves12** [facebook/hhvm#7005]
### Standalone code, or other way to reproduce the problem
I installed xhp-lib from composer it has several typechecker issues. My code won't
run because of this.

**Comment by Orvid** [comment]
Could you provide what specific errors the typechecker gives?

**Comment by fredemmott** [comment]
Please file here: https://github.com/facebook/xhp-lib/issues

Please include the specific HHVM version you are using. 3.14 does not exist.

**Comment by fredemmott** [comment]
I can't reproduce with 3.12, 3.13, or last night's nightly. As a guess, did you run composer install? If not, phpunit will be undefined.
