### ISSUE TITLE
php 7 incompatibility

### ISSUE THREAD

**Issue by r3wt** [facebook/hhvm#7008]
### HHVM Version
3.12 (3v4l)

### Standalone code, or other way to reproduce the problem
https://3v4l.org/KKRtk

### Expected result
able to use array access on constant that was defined as an array

### Actual result
parse error

**Comment by simonwelsh** [comment]
This seems like a more specific case of #6992.

Also 3v4l runs HHVM in PHP5 mode, so you won't be able to test PHP7 features on it.

**Comment by r3wt** [comment]
Thanks for the info simon, should i go ahead and close this as a non issue?

**Comment by Orvid** [comment]
Correct.
