### ISSUE TITLE
Make Phar stream wrapper working with streams instead of strings

### ISSUE THREAD

**Issue by nazar-pc** [facebook/hhvm#7015]
There is one major problem with Phar/Tar/Zip archives integration into runtime: big files will use too much RAM (and files that are bigger than available RAM will fail).
Namely, this part: https://github.com/facebook/hhvm/blob/5cc97b6b31131dc3189900f5461b2ee7e4df875e/hphp/runtime/ext/phar/ext_phar.cpp#L52-L64

My C++ knowledge is poor, but if someone can adust those lines to support resource (file handler) instead of string as returned value from `openPhar` I'll adjust the rest of bits.

Otherwise it is very easy to exhaust memory when dealing with relatively big arrays.

PR against https://github.com/nazar-pc/hhvm/tree/phar-compression-support would be perfect.

**Comment by Orvid** [comment]
A wild [PR](https://github.com/nazar-pc/hhvm/pull/1) appears!

**Comment by nazar-pc** [comment]
Is there something in HHVM that can provide stream slice functionality?
Namely, lets say I have Tar file opened as stream and I need some file inside with offset `X` and length `Y`. Do I need to hook up new stream wrapper for internal use of there is something already available?

**Comment by nazar-pc** [comment]
I suspect `virtual String read()` and `virtual String read(int64_t length)` and others might be implemented on `PharStreamWrapper` like they are in `File`, but it is a bit over my capabilities right now.
If we can implement both of them I can then return from PHP/Hack `[resource, offset, size]` kind of array without the need to introduce stream wrapper.
