### ISSUE TITLE
Assertion failure with closure

### ISSUE THREAD

**Issue by nazar-pc** [facebook/hhvm#7020]
### HHVM Version
3.14.0-dev

### Standalone code, or other way to reproduce the problem
Open `hphp/system/php/phar/Phar.php` and add following simple method:
```
  public static function isValidPharFilename() {
    array_filter([], function () {});
  }
```

Now compile HHVM and run ANY php script: `hphp/hhvm/hhvm empty.php`

### Expected result
No crash

### Actual result
```
Assertion failure: /hhvm/hphp/runtime/vm/unit.cpp:1129: void HPHP::Unit::initialMerge(): assertion `cls != nullptr' failed.


Core dumped: Aborted
Stack trace in /tmp/stacktrace.1290.log
fish: “hphp/hhvm/hhvm empty.php” terminated by signal SIGABRT (Abort)
```

**Comment by jwatzman** [comment]
Historically closures weren't allowed in systemlib for technical reasons. @paulbiss is that still the case, and is this the expected failure mode?

**Comment by Orvid** [comment]
That limitation was due to the order things were registered wasn't it? We killed IDL so we might actually be able to allow this now.

**Comment by Orvid** [comment]
If you shift the `.php` side of the implementation over to `/hphp/runtime/ext/phar/` you should be able to use closures without an issue.

**Comment by Orvid** [comment]
As this is a known limitation, I'm going to close this for now.
