### ISSUE TITLE
Failed to open /var/www/.hhvm.hhbc: 14 - unable to open database file

### ISSUE THREAD

**Issue by elfeffe** [facebook/hhvm#7026]
I have

`HipHop VM 3.12.1 (rel)
Compiler: tags/HHVM-3.12.1-0-gf516f1bb9046218f89885a220354c19dda6d8f4d
Repo schema: f2e5f39b2ad4a08bcbd90b5d8bcb580f40fba6c8`

On Ubuntu 14.04
HHVM works good, but it gives error when I try to use it in command line using a cron task.

I edit www-data cron using 
`crontab -e -u www-data`

And the same command that works on command line, gives that error when running from cron.
Is this a bug?

**Comment by fcorriga** [comment]
check directory persmissions and ensure the www-data user can write to /var/www/

**Comment by elfeffe** [comment]
But correct path is
hhvm.repo.central.path = /var/run/hhvm/hhvm.hhbc

Do I have to give permissions to var/www too?

**Comment by Orvid** [comment]
That repo central path is referring to the path of the repo in Repo Authoritative mode, not this file. The file it's trying to write is a cache for the compiled bytecode of the systemlib. Normally it gets put in the home directory of the user running HHVM, so I'm going to assume that www-data's home directory is set to /var/www.

**Comment by elfeffe** [comment]
Yes, it is working now.
Thank you
