### ISSUE TITLE
h2tp crashes while finding free variables in lambdas that call static methods

### ISSUE THREAD

**Issue by rightfold** [facebook/hhvm#7029]
### HHVM Version

    % hh_client --version
    f516f1bb9046218f89885a220354c19dda6d8f4d Feb 25 2016 23:32:12

### Standalone code, or other way to reproduce the problem

    <?hh // strict

    class C { public static function f(): int { return 1; } }

    function f(): (function(): int) {
        return $x ==> C::f();
    }

### Expected result

Everything compiles and runs as expected.

### Actual result

    Raised by primitive operation at file "utils/utils.ml", line 335, characters 4-32
    Called from file "naming/naming.ml", line 270, characters 34-65
    Called from file "naming/naming.ml", line 422, characters 20-96
    Called from file "naming/naming.ml", line 1973, characters 16-40
    Called from file "naming/naming.ml", line 1652, characters 23-43
    Called from file "naming/naming.ml", line 1583, characters 25-36
    Called from file "naming/naming.ml", line 1792, characters 25-35
    Called from file "naming/naming.ml", line 1583, characters 25-36
    Called from file "third-party/core/option.ml", line 144, characters 21-26
    Called from file "naming/naming.ml", line 1393, characters 41-52
    Called from file "third-party/core/core_list.ml", line 231, characters 13-17
    Called from file "naming/naming.ml", line 458, characters 14-19
    Called from file "naming/naming.ml", line 1935, characters 18-36
    Called from file "naming/naming.ml", line 1334, characters 9-28
    Called from file "h2tp/mapper/lambda_expressions.ml", line 26, characters 13-36
    Called from file "h2tp/mapper/map_ast.ml", line 529, characters 37-49
    Called from file "third-party/core/option.ml", line 144, characters 21-26
    Called from file "h2tp/mapper/map_ast.ml", line 25, characters 24-39
    Called from file "list.ml", line 55, characters 20-23
    Called from file "h2tp/mapper/map_ast.ml", line 421, characters 21-39
    Called from file "h2tp/mapper/map_ast.ml", line 84, characters 27-38
    Called from file "list.ml", line 55, characters 20-23
    Called from file "list.ml", line 55, characters 32-39
    Called from file "h2tp/mapper/map_ast.ml", line 687, characters 37-58
    Called from file "h2tp/mapper/map_ast.ml", line 695, characters 8-44
    Called from file "list.ml", line 84, characters 24-34
    Called from file "third-party/core/core_list.ml", line 185, characters 22-47
    Called from file "h2tp/engine.ml", line 124, characters 6-34
    Called from file "list.ml", line 73, characters 12-15
    Called from file "third-party/core/core_list.ml", line 182, characters 16-30
    Called from file "h2tp/h2tp.ml", line 58, characters 4-64
    Internal Error:
    error processing /tmp/foo/src/foo.hh

**Comment by rightfold** [comment]
It appears this isn't the only case causing a crash. Other cases involving lambdas also cause similar crashes, for example, lambdas with `self::class` in their bodies.

**Comment by jwatzman** [comment]
I don't have time to look at this myself, but my suspicion is that it's a simple oversight somewhere, if someone wanted to look into some ML code.

**Comment by rightfold** [comment]
This only happens in strict mode.

**Comment by paulbiss** [comment]
Closing h2tp issues as there is currently no maintainer for this tool. If anyone wants to step up and maintain h2tp we will reopen these issues.
