### ISSUE TITLE
Segfault when recursively iterating over directory with unreadable subdirectories

### ISSUE THREAD

**Issue by zodiac** [facebook/hhvm#7030]
### HHVM Version

3.10.1

### Standalone code, or other way to reproduce the problem

Assume that `/home` contains some directories that the current user (as in `whoami`) cannot `cd` into.
 
```
<?php

$x = new RecursiveIteratorIterator(new RecursiveDirectoryIterator('/home'), RecursiveIteratorIterator::LEAVES_ONLY, RecursiveIteratorIterator::CATCH_GET_CHILD);
foreach ($x as $file) {
	var_dump($file);
}
```

### Expected result

On zend, I see a list of the files in my home directory (the only directory I can read).

### Actual result

On hhvm, I get a segfault.

**Comment by apeabody** [comment]
In HHVM-master I'm not seeing a segfault (didn't check 3.10.1 as it's pretty old - but I can't replicate it in https://3v4l.org/1AuIL), however HHVM-master is throwing an UnexpectedValueException (with a stack trace which might be interpreted as a segfault).  This (at least to my reading) is the behavior as listed in the PHP documentation: https://secure.php.net/manual/en/class.unexpectedvalueexception.php

HOWEVER I've been able to identify that PHP (5.4.16 tested) appears to NOT throw this exception for sub-directories while HHVM does, but both HHVM and PHP do for the initial directory: https://3v4l.org/1AuIL
