### ISSUE TITLE
hh_format error on tabs in heredocs

### ISSUE THREAD

**Issue by HRMsimon** [facebook/hhvm#7031]
### HHVM Version

3.13.1
### Standalone code, or other way to reproduce the problem

``` hack
<?hh

function foo() {
  $foo = <<<BAH
Hello
    There
BAH;
}
```

If the tab inside the heredoc is removed or replaced with spaces, the issue goes away.
### Expected result

`hh_format` on the file formats it correctly, leaving the content in the heredoc alone
### Actual result

```
Internal error in /home/simon/test/test.hh
```

**Comment by Wilfred** [comment]
No longer relevant: `hh_format` has been replaced by `hackfmt`.
