### ISSUE TITLE
running hhvm 3.12.1 with nginx, hhvm not following memory_limit of php.ini

### ISSUE THREAD

**Issue by soochanlee** [facebook/hhvm#7033]
### HHVM Version
3.12.1
### Standalone code, or other way to reproduce the problem
hhvm/php,ini
![2016-05-03 7 27 21](https://cloud.githubusercontent.com/assets/4545333/14981929/2b109b5c-1165-11e6-8960-e58fda7c83cb.png)
![2016-05-03 7 27 48](https://cloud.githubusercontent.com/assets/4545333/14981933/316089ae-1165-11e6-8a37-21fe0967a2fe.png)

### Expected result
hhvm shouldn't take more than 300MB?

### Actual result
hhvm take 95% of server memory(4G) and cause server hang

Hi,
I'm running hhvm with laravel on 4G memory server and have problem like above.
Not sure about configuration, is it right way to set memroy_limit?
Or should server memory be more than 4G?
Thanks.

**Comment by Orvid** [comment]
memory_limit refers to the max memory used by each request, not the max memory used by all requests.
