### ISSUE TITLE
HHVM memory management question

### ISSUE THREAD

**Issue by soochanlee** [facebook/hhvm#7034]
### HHVM Version
3.12.1

Hi, I'm running HHVM, nginx with laravel on server with 4GB memory.

I have a problem that hhvm takes more than 95% of server memory and causes server down.

I couldn't find which configuration to prevent this,

so, is there anyway to prevent this?

will upgrading server memory to 16GB help?

My hhvm php.ini is like below.

Thank you.

![2016-05-04 11 38 07](https://cloud.githubusercontent.com/assets/4545333/15004706/e97f07f4-11ec-11e6-86ef-585c4c2bbf49.png)

**Comment by fcorriga** [comment]
HHVM is known to eat up memory due to leaks "here and there".
Use monit to check HHVM process(es) memory usage and restart HHVM when it's eating up too much RAM.

**Comment by firodj** [comment]
can you give the admin /memory.json output ?

**Comment by paulbiss** [comment]
Getting HHVM under 4GB might be a tall order. It looks like you're already adjusting the TC size (jit_a_size etc). You could try reducing `hhvm.server_thread_count` and `hhvm.jit_target_cache_size ` but I doubt either of those will be more than a couple hundred MB. For most workloads HHVM will definitely run fine on a 16GB server.

**Comment by ksaltik** [comment]
It is still doing the same thing I write it several years before 2016. HHVM is not for other frameworks it is for facebook own usage I recommend you to not use it.
