### ISSUE TITLE
Hiphop make error@Sydney_o9 

### ISSUE THREAD

**Issue by athulase** [facebook/hhvm#7038]
# ERROR while make command on HipHop Installation
Following the link Building and installing HHVM on CentOS 6.6
On Step#15 ---HipHop Installation "make"
Make was successful till 82%, after that
getting  errors ---->>>/usr/local/hhvm/hphp/runtime/ext/collections/ext_collections-set.cpp:895:32: error: no matches converting function 
## # ERROR
[ 82%] Building CXX object hphp/runtime/ext/CMakeFiles/hphp_runtime_ext.dir/collections/ext_collections-set.cpp.o
/usr/local/hhvm/hphp/runtime/ext/collections/ext_collections-set.cpp: In member function ‘void HPHP::collections::CollectionsExtension::initSet()’:
/usr/local/hhvm/hphp/runtime/ext/collections/ext_collections-set.cpp:895:32: error: no matches converting function ‘php_map’ to type ‘struct HPHP::Object (struct HPHP::BaseSet::* const)(const struct HPHP::Variant&) const’
   auto const m     = &BaseSet::php_map<c_Set, false>;
                                ^
/usr/local/hhvm/hphp/runtime/ext/collections/ext_collections-set.cpp:420:1: note: candidate is: template<class TSet, bool useKey> typename std::enable_if<std::is_base_of<HPHP::BaseSet, TSet>::value, HPHP::Object>::type HPHP::BaseSet::php_map(const HPHP::Variant&) const
 BaseSet::php_map(const Variant& callback) const {
 ^
/usr/local/hhvm/hphp/runtime/ext/collections/ext_collections-set.cpp:896:32: error: no matches converting function ‘php_map’ to type ‘struct HPHP::Object (struct HPHP::BaseSet::* const)(const struct HPHP::Variant&) const’
   auto const mk    = &BaseSet::php_map<c_Set, true>;
                                ^
/usr/local/hhvm/hphp/runtime/ext/collections/ext_collections-set.cpp:420:1: note: candidate is: template<class TSet, bool useKey> typename std::enable_if<std::is_base_of<HPHP::BaseSet, TSet>::value, HPHP::Object>::type HPHP::BaseSet::php_map(const HPHP::Variant&) const
 BaseSet::php_map(const Variant& callback) const {
 ^
/usr/local/hhvm/hphp/runtime/ext/collections/ext_collections-set.cpp:897:32: error: no matches converting function ‘php_map’ to type ‘struct HPHP::Object (struct HPHP::BaseSet::* const)(const struct HPHP::Variant&) const’
   auto const immm  = &BaseSet::php_map<c_ImmSet, false>;
                                ^
/usr/local/hhvm/hphp/runtime/ext/collections/ext_collections-set.cpp:420:1: note: candidate is: template<class TSet, bool useKey> typename std::enable_if<std::is_base_of<HPHP::BaseSet, TSet>::value, HPHP::Object>::type HPHP::BaseSet::php_map(const HPHP::Variant&) const
 BaseSet::php_map(const Variant& callback) const {
 ^
/usr/local/hhvm/hphp/runtime/ext/collections/ext_collections-set.cpp:898:32: error: no matches converting function ‘php_map’ to type ‘struct HPHP::Object (struct HPHP::BaseSet::* const)(const struct HPHP::Variant&) const’
   auto const immmk = &BaseSet::php_map<c_ImmSet, true>;
                                ^
/usr/local/hhvm/hphp/runtime/ext/collections/ext_collections-set.cpp:420:1: note: candidate is: template<class TSet, bool useKey> typename std::enable_if<std::is_base_of<HPHP::BaseSet, TSet>::value, HPHP::Object>::type HPHP::BaseSet::php_map(const HPHP::Variant&) const
 BaseSet::php_map(const Variant& callback) const {
 ^
/usr/local/hhvm/hphp/runtime/ext/collections/ext_collections-set.cpp:904:32: error: no matches converting function ‘php_filter’ to type ‘struct HPHP::Object (struct HPHP::BaseSet::* const)(const struct HPHP::Variant&) const’
   auto const f     = &BaseSet::php_filter<c_Set, false>;
                                ^
/usr/local/hhvm/hphp/runtime/ext/collections/ext_collections-set.cpp:460:1: note: candidate is: template<class TSet, bool useKey> typename std::enable_if<std::is_base_of<HPHP::BaseSet, TSet>::value, HPHP::Object>::type HPHP::BaseSet::php_filter(const HPHP::Variant&) const
 BaseSet::php_filter(const Variant& callback) const {
 ^
/usr/local/hhvm/hphp/runtime/ext/collections/ext_collections-set.cpp:905:32: error: no matches converting function ‘php_filter’ to type ‘struct HPHP::Object (struct HPHP::BaseSet::* const)(const struct HPHP::Variant&) const’
   auto const fk    = &BaseSet::php_filter<c_Set, true>;
                                ^
/usr/local/hhvm/hphp/runtime/ext/collections/ext_collections-set.cpp:460:1: note: candidate is: template<class TSet, bool useKey> typename std::enable_if<std::is_base_of<HPHP::BaseSet, TSet>::value, HPHP::Object>::type HPHP::BaseSet::php_filter(const HPHP::Variant&) const
 BaseSet::php_filter(const Variant& callback) const {
 ^
/usr/local/hhvm/hphp/runtime/ext/collections/ext_collections-set.cpp:906:32: error: no matches converting function ‘php_filter’ to type ‘struct HPHP::Object (struct HPHP::BaseSet::* const)(const struct HPHP::Variant&) const’
   auto const immf  = &BaseSet::php_filter<c_ImmSet, false>;
                                ^
/usr/local/hhvm/hphp/runtime/ext/collections/ext_collections-set.cpp:460:1: note: candidate is: template<class TSet, bool useKey> typename std::enable_if<std::is_base_of<HPHP::BaseSet, TSet>::value, HPHP::Object>::type HPHP::BaseSet::php_filter(const HPHP::Variant&) const
 BaseSet::php_filter(const Variant& callback) const {
 ^
/usr/local/hhvm/hphp/runtime/ext/collections/ext_collections-set.cpp:907:32: error: no matches converting function ‘php_filter’ to type ‘struct HPHP::Object (struct HPHP::BaseSet::* const)(const struct HPHP::Variant&) const’
   auto const immfk = &BaseSet::php_filter<c_ImmSet, true>;
                                ^
/usr/local/hhvm/hphp/runtime/ext/collections/ext_collections-set.cpp:460:1: note: candidate is: template<class TSet, bool useKey> typename std::enable_if<std::is_base_of<HPHP::BaseSet, TSet>::value, HPHP::Object>::type HPHP::BaseSet::php_filter(const HPHP::Variant&) const
 BaseSet::php_filter(const Variant& callback) const {
 ^
make[2]: *** [hphp/runtime/ext/CMakeFiles/hphp_runtime_ext.dir/collections/ext_collections-set.cpp.o] Error 1
make[1]: *** [hphp/runtime/ext/CMakeFiles/hphp_runtime_ext.dir/all] Error 2
make: *** [all] Error 2

Followed every step correctly so far, Can somebody please help?

**Comment by Orvid** [comment]
What version of GCC are you building with?

**Comment by athulase** [comment]
I installed gcc v4.9.2, as per the instruction in document.

**Comment by mattlqx** [comment]
I'm encountering the same on Ubuntu 14 with gcc 4.9.1.

**Comment by mattlqx** [comment]
FWIW, I can checkout the revision prior to https://github.com/facebook/hhvm/commit/ed39e9ae87960511e608eb74ad475f4cef571c25 and build HHVM just fine.

**Comment by Orvid** [comment]
This was fixed.
