### ISSUE TITLE
Behavior inconsistent with PHP when a variable is listed both in the parameter list and the use clause of a closure

### ISSUE THREAD

**Issue by rightfold** [facebook/hhvm#7039]
### HHVM Version

3.12.0

### Standalone code, or other way to reproduce the problem

    <?php
    $x = 1;
    $f = function($x) use($x) {
        echo $x;
    };
    $f(2);

### Expected result

The same as PHP:

    1

### Actual result

    2

**Comment by Orvid** [comment]
Already reported as #5541.
