### ISSUE TITLE
Add include/require support for compressed Phar without phar:// schema

### ISSUE THREAD

**Issue by nazar-pc** [facebook/hhvm#7068]
Currently `include 'test.phar'` works (since phar itself starts with stub and stub ends with `__HALT_COMPILER()`, which is generally a valid PHP file).

However, `include 'test.phar.gz'` doesn't work (it just outputs content of the file as is), even though all flavors of phar are currently supported for reading and through phar schema like `include 'phar://test.phar.gz'`. This is because compressed contents is not valid PHP.

How I'd suggest to implement this:
- use `Phar::isValidPharFilename(filename_here, true)` to determine whether this file is a valid supported Phar (since this would not be true in majority of cases simple check for `.phar` in filename might be added to avoid running regular expression execution on each file include)
- if file schema is not `phar://` already, just add this schema as prefix
- uncomment tests in [hphp/test/slow/ext_phar/basic.php](https://github.com/facebook/hhvm/blob/master/hphp/test/slow/ext_phar/basic.php) (marked with TODO)

As far as I've traced it changes, are very likely to happen in [hphp/runtime/base/stream-wrapper-registry.cpp](https://github.com/facebook/hhvm/blob/master/hphp/runtime/base/stream-wrapper-registry.cpp), but I'm not C++ developer, so can't implement it myself.

This should be fairly easy and straightforward to implement.

**Comment by Orvid** [comment]
I can't seem to find a test case for this in the PHP tests for phar support. Does PHP actually support include/require of compressed phars without the schema?

**Comment by nazar-pc** [comment]
Yes, PHP supports this case (I've checked it before writing those commented tests).
I think this is related test from PHP source (they mix most files under just `.phar` extension, so it is not immediately clear which are compressed and which are not): https://github.com/php/php-src/blob/master/ext/phar/tests/phar_gzip.phpt
Consider even simpler rude example like following:
```
~> gzip -9 -k composer.phar
~> php composer.phar.gz --version
#!/usr/bin/env php
Composer version 1.1.0 2016-05-10 15:21:19
~> hhvm composer.phar.gz --version

Fatal error: Unexpected character in input: '' (ASCII=23) (Line: 27, Char: 62)
syntax error, unexpected T_STRING in ../composer.phar.gz on line 27
```

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Hhvm dropped support for the phar extension in hhvm version [4.1.0](https://hhvm.com/blog/2019/04/09/hhvm-4.1.0.html).
