### ISSUE TITLE
Symbol lookup error

### ISSUE THREAD

**Issue by kayalvizhi-g05** [facebook/hhvm#7074]
HHVM Version is 3.13.1

I execute `make test` command after pgsql.so is built and I got the following error.

`hhvm: symbol lookup error: /etc/hhvm/pgsql.so: undefined symbol: _ZN4HPHP6Config7GetBoolERKNS_13IniSettingMapERKNS_3HdfERKSsbb`

**Comment by Orvid** [comment]
3.13.1 doesn't work with dynamic extensions, as the fixes to get them working didn't make it in time :( 3.12 supports them properly and 3.14 will as well.
