### ISSUE TITLE
Only the last parameter in a function call is allowed to use ...

### ISSUE THREAD

**Issue by nazar-pc** [facebook/hhvm#7087]
### HHVM Version

```
HipHop VM 3.14.0-dev (rel)
Compiler: heads/master-0-gd8285fbc906f340182a2a94b1fd0cf40787a40b9
Repo schema: 093188019b394a8a53aee6c073772c7db4ffc5e6
```
### Standalone code, or other way to reproduce the problem

```
$foo = ['x', 'y', 'z'];
var_dump(...$foo, ...$foo);
```
### Expected result

```
~> php index.php
string(1) "x"
string(1) "y"
string(1) "z"
string(1) "x"
string(1) "y"
string(1) "z"
```
### Actual result

```
~> hhvm index.php

Fatal error: Only the last parameter in a function call is allowed to use ... in * on line *
```

There are 2 tests: [hphp/test/slow/unpack_args/unpack_call_error.php](https://github.com/facebook/hhvm/blob/master/hphp/test/slow/unpack_args/unpack_call_error.php) and [hphp/test/slow/unpack_args/unpack_call_multi.php](https://github.com/facebook/hhvm/blob/master/hphp/test/slow/unpack_args/unpack_call_multi.php), but they are both wrong, such usage is completely valid in PHP7

**Comment by nazar-pc** [comment]
Submitted PR #7088, it seems to fix this strange incompatibility (looks like the one who implemented this was confused with only one `...` use allowed in function declaration, while during call any number of unpacking arguments is allowed).

**Comment by jesseschalken** [comment]
This is a duplicate of https://github.com/facebook/hhvm/issues/4940
