### ISSUE TITLE
Links against mysqlclient_r, not mysqlclient

### ISSUE THREAD

**Issue by paravoid** [facebook/hhvm#7090]
Over at the Debian bug tracking system, we got a [bug report](https://bugs.debian.org/825077) from Robie Basak of Ubuntu, about mysqlclient_r:
> Please stop linking against libmysqlclient_r and link directly against
> libmysqlclient instead.
> 
> Your package currently links against libmysqlclient_r. libmysqlclient_r
> was the thread-safe version of libmysqlclient in previous MySQL
> releases. However, libmysqlclient has been itself been made thread-safe
> since before the current libmysqlclient18. Thus libmysqlclient_r is
> currently deprecated and provided as a compatibility symlink only, and
> will disappear in MySQL 5.7. This change can be made now, in advance of
> a possible future transition to libmysqlclient20, which does not provide
> the _r variant.
> 
> For hhvm, we have done this in Ubuntu with the attached quilt
> patch, which I believe is also applicable to Debian.

I won't attach the patch for copyright/CLA reasons, but let's just say that `s/mysqlclient_r/mysqlclient/` in `CMake/FindMySQL.cmake` would do it.

**Comment by Orvid** [comment]
Well, we don't actually build against the system MySQL client unless you have async mysql disabled, which it shouldn't be in any of the distributed packages, so our situation is a bit different from 99% of the other projects linking against MySQL...

**Comment by paravoid** [comment]
Indeed, this is for the async MySQL disabled case. This affects custom builds and the packages shipped by Debian and Ubuntu — not Facebook's packages.

**Comment by Orvid** [comment]
Diff up internally D3367294, to fix this. I've gone with the approach of preferring `_r` if it exists and falling back to the normal version otherwise.
