### ISSUE TITLE
Studying the evolution of HHVM's project

### ISSUE THREAD

**Issue by gustavopinto** [facebook/hhvm#7122]
Hi there, 

I'm a researcher studying software evolution. As part of my current research, I'm studying the implications of open-sourcing a proprietary software, for instance, if the project succeed in attracting newcomers. HHVM was in my list. 

To further analyze the impacts of HHVM’s migration, we analyzed the git log commit history of your project in terms of _number of contributions_, _number of newcomers_, and _number of contributors per month_. The following figure presents a temporal perspective regarding these three measures. 

![hhvm](https://cloud.githubusercontent.com/assets/235062/15752147/92af5232-28a1-11e6-9d0c-ef76d1b55e37.png)

Given the numbers presented in the graphic, we would like to ask HHVM developers the following questions:

1. What motivated the project to open its source code at Github? How do you evaluate the benefits of this migration?
2. Does this snapshot make sense? Did you find any inconsistency on the data?
3. Do you have any internal policy to promote/attract/retain newcomers? If so, do them succeed?
4. Why did the number of contributors increase only several months after the project became open-source? 
5. In 2014 the newcomers rate decreased. Is there any explanation for this fact?

Thanks in advance for your collaboration,

Gustavo Pinto, PhD
http://www.gustavopinto.org

**Comment by jwatzman** [comment]
cc @fredemmott who used to work on HHVM and does more general OSS stuff at FB now, also cc @sgolemon who doesn't work at FB any more but this is the sort of stuff she cared about and might have a different perspective on

@gustavopinto -- you might want to see if you can find recordings of any of @sgolemon's talks about HHVM from years past, I think she goes into some (but not all) of this; I seem to remember an OSCON talk that might be up this alley in particular?

**Comment by gustavopinto** [comment]
Thank  you for your link, @jwatzman. 

I'd love to hear your comments, @fredemmott and @sgolemon.

**Comment by aorenste** [comment]
Closing as this really isn't an HHVM issue (i.e. bug).  Please feel free to contact the developers on IRC (http://webchat.freenode.net/?channels=hhvm)

**Comment by gustavopinto** [comment]
Hi @jwatzman, @fredemmott, @sgolemon, @aorenste I have additional questions, do you mind in answering them?

What was the main motivation for going open-source?

For example, was the main motivation of the companies to attract and retain new contributors? Or was the main motivation perhaps to promote a profile of open-source-friendliness and get goodwill from the community?

Could you please elaborate a bit over it?

Additionally, were there instances that companies recruited people from the community after they contributed to the (now open-sourced) project?

Were there discussions between the companies and the community that indicate a communication between them?

Finally, what are the recommendations for policies to create a sustainable community?

BTW, I saw your comment about chatting over IRC. However, since this is for research purposes, that would be better to chat in a public place. If you have any constraints about making this conversation public, we can shift to IRC.
