### ISSUE TITLE
http_build_query with enc_type = PHP_QUERY_RFC3986 works incorrect for multidimensional arrays and complex objects.

### ISSUE THREAD

**Issue by dmitry-kulikov** [facebook/hhvm#7137]
### Standalone code, or other way to reproduce the problem

```php
$data = array('model' => array('foo bar' => 'herp derp'));
echo http_build_query($data, null, null, PHP_QUERY_RFC3986);
```

### Expected result

`model%5Bfoo%20bar%5D=herp%20derp`

### Actual result

`model%5Bfoo+bar%5D=herp+derp`

This is PHP incompatibility.
Problem also affects complex objects.
See https://3v4l.org/RjMiu, https://3v4l.org/EIfeD.

**Comment by chadschulz** [comment]
I'm also experiencing problems with this issue. It might be allowing a variable array built with `http_build_query` with `enc_type = PHP_QUERY_RFC3986` to slip through a 'if(!is_scalar($var))' conditional?

More a minor annoyance than anything.
