### ISSUE TITLE
Hack: casting mixed to array

### ISSUE THREAD

**Issue by donkeysmash** [facebook/hhvm#7141]
This may sound stupid but I don't know how to cast mixed value to an array in strict mode:
```(array) $a```
And if I do
```(array<arraykey, mixed>) $a```
it produces syntax errors. Thanks a lot for your help.

**Comment by SiebelsTim** [comment]
If `$a` is an array and you know it, you can use `invariant

```
function f(mixed $a): array {
  invariant(is_array($a), 'Error, $a is not an array');
  return $a; // it's an array now after the invariant check
}
```

If it may be an array, or something else, simply make an if check:

```
function f(mixed $a):void {
  if (is_array($a)) {
    // You can use $a as an array now.
    $a[0] = 'a';
  } else {
    // Here it's still mixed
  }
}
```

You don't want to cast things to an array, if it isn't an array.

See https://docs.hhvm.com/hack/types/refining

**Comment by donkeysmash** [comment]
thank you very much
