### ISSUE TITLE
DateTimeZone->getOffset() with DateTimeZone as input crashes HHVM

### ISSUE THREAD

**Issue by thijsw** [facebook/hhvm#7142]
### HHVM Version (tested for two versions)

``` bash
$ hhvm --version
HipHop VM 3.10.1 (rel)
Compiler: tags/HHVM-3.10.1-0-g689b4969a141620ee5a282ce0dbf72278c84d44b
Repo schema: 6c99ee1f98340f6f3ef397a332583f0e843a627d
```

``` bash
$ hhvm --version
HipHop VM 3.13.1 (rel)
Compiler: tags/HHVM-3.13.1-0-g4f382ad928a6e2a0607a8dcb251002aca77f11f6
Repo schema: 655b5912cb8136e9df6f9be972153e38ac446e0f
```
### Standalone code, or other way to reproduce the problem

``` php
<?php

$utc = new \DateTimeZone('UTC');
$amsterdam = new \DateTimeZone('Europe/Amsterdam');

echo $amsterdam->getOffset($utc);
```
### Expected result

Warning: DateTimeZone::getOffset() expects parameter 1 to be DateTimeInterface, object given in /home/vagrant/test.php on line 6
### Actual result

``` bash
$ hhvm test.php
Core dumped: Segmentation fault
Stack trace in /tmp/stacktrace.2615.log
Segmentation fault (core dumped)
```

/tmp/stacktrace.2615.log:

``` log
PHP Stacktrace:

#0  DateTimeZone->getOffset(Object of class DateTimeZone could not be converted to string) called at [/home/vagrant/test.php:6]
```

This is a user error, as one should provide an instance of \DateTimeInterface instead of \DateTimeZone to this method, however, I believe HVVM should give a regular warning instead of crashing.

**Comment by mpu** [comment]
Created diff D3500647 internally to solve this.

**Comment by jesseschalken** [comment]
This was fixed in https://github.com/facebook/hhvm/commit/a234c82ce5e6c8895a1a6c3b217a4b12c0efd2a0

https://3v4l.org/CDNlA
