### ISSUE TITLE
PHP7 support: Undefined function gc_mem_caches()

### ISSUE THREAD

**Issue by robations** [facebook/hhvm#7155]
### HHVM Version
= 3.14.0

### Standalone code, or other way to reproduce the problem
    # hhvm.php7.all=1
    echo '<?php echo gc_mem_caches();' | hhvm --php

### Expected result
some integer (or if this has no equivalent in hhvm, 0 and no side effects)

### Actual result
```
Fatal error: Uncaught Error: Call to undefined function gc_mem_caches() in /tmp/php-wrap-MI6Igh:1
Stack trace:
#0 {main}
```

See also: https://secure.php.net/manual/en/function.gc-mem-caches.php

**Comment by jwatzman** [comment]
Docs: http://php.net/manual/en/function.gc-mem-caches.php

An implementation of this to just `return 0` is probably the right one for HHVM; we can put it next to `gc_collect_cycles` which [does the same thing in HHVM](http://php.net/manual/en/function.gc-collect-cycles.php).
