### ISSUE TITLE
HHVM Signed Zero PHP incompability

### ISSUE THREAD

**Issue by hopeseekr** [facebook/hhvm#7156]
### HHVM Version
3.14.0 and -dev
### Standalone code, or other way to reproduce the problem
```
<?php

$a = 0 * -1;
echo '$a = 0 * -1 === ' . $a . "\n";
var_dump($a);

$b = 0.0 * -1;
echo '$b = 0.0 * -1 === ' . $b . "\n";
var_dump($b);

$c = 0.0;
echo '$c = 0.0 === ' . $c . "\n";
var_dump($c);
if ($a == $b) {
    echo '$a is loosely equal to $b' . "\n";
    if ($b == $c) {
        echo '$b is loosely equal to $c' . "\n";
    }
}
else {
    echo '$a is NOT loosely equal to $b' . "\n";
}

if ($a === $b) {
    echo '$a is strictly equal to $b' . "\n";
}
else {
    echo '$a is NOT strictly equal to $b' . "\n";
}

if ($c === $b) {
    echo '$b is strictly equal to $c' . "\n";
}
else {
    echo '$b is NOT strictly equal to $c' . "\n";
}

if ((string)$c === (string)$b) {
    echo '(string)$b is strictly equal to (string)$c' . "\n";
}
else {
    echo '(string)$b is NOT strictly equal to (string)$c' . "\n";
}
```
### Expected result

> $a = 0 * -1 === 0
> int(0)
> $b = 0.0 * -1 === -0
> float(-0)
> $c = 0.0 === 0
> float(0)
> $a is loosely equal to $b
> $b is loosely equal to $c
> $a is NOT strictly equal to $b
> $b is strictly equal to $c
> (string)$b is NOT strictly equal to (string)$c
> 

### Actual result

> $a = 0 * -1 === 0
> int(0)
> **$b = 0.0 * -1 === 0**
> float(-0)
> $c = 0.0 === 0
> float(0)
> $a is loosely equal to $b
> $b is loosely equal to $c
> $a is NOT strictly equal to $b
> $b is strictly equal to $c
> **(string)$b is strictly equal to (string)$c**
> 

### Comment

I prefer the HHVM way, but I wanted to report this incompatibility, nonetheless.

**Comment by hopeseekr** [comment]
This may have deeper implications for HHVM, because the `$b === $c` should be comparing, basically, `var_dump($b) == var_dump($c)`, but it isn't, since the values are `float(-0)` and `float(0)`, respectively.

**Comment by hopeseekr** [comment]
PHP 5.6.21:

> -0 * -0 === -0
> -0 * 0 === -0
> 0 * -0 === -0
> -0 * null === -0
> 2 * null === 0

HHVM 3.14.0:

> -0 * -0 === 0
> -0 * 0 === 0
> 0 * -0 === 0
> -0 * null === 0
> 2 * null === 0
>

**Comment by jwatzman** [comment]
3v4l: https://3v4l.org/9SkX1

I wonder what IEEE says about `-0 * -0` -- unclear which way it should go to my intuition.

This one's interesting and I actually know something about this area of HHVM (I worked on it for the PHP7 support). If I get some spare time, I'll take a look -- but that's a big "if" right now.

**Comment by nikic** [comment]
`-0.0 * -0.0` gives me `0.0` on all versions of PHP and HHVM. Not sure where that -0 comes from.

Note that `-0.0` only works correctly since PHP 7 -- previously it was implemented as `0.0-0.0` instead of `-1.0*0.0`, so gave a positive zero instead.

**Comment by jwatzman** [comment]
The problem -- or at least part of it -- seems to be due to the string case of negative zero in HHVM -- we render it as `"0"` instead of `"-0"`. https://3v4l.org/PM6Zc

**Comment by jwatzman** [comment]
lol: https://reviews.facebook.net/diffusion/HHVM/browse/master/hphp/runtime/base/type-string.cpp;00aa638773bc88f184e1591b3a78409362107de2$128

I'm trying out just removing that line :-P
