### ISSUE TITLE
strcasecmp doesn't properly handle alternate locales

### ISSUE THREAD

**Issue by drewklein** [facebook/hhvm#7157]
### HHVM Version
HipHop VM 3.14.0-dev (rel)
Compiler: heads/master-0-g61f6e951df4b54e32265d2ae276e5b3743666776
Repo schema: 4efed6889a9a3510fcd33c0bb0d25ff4d64617d4

### Standalone code, or other way to reproduce the problem
<?php
$chars = "äöü";
setlocale(LC_CTYPE, "de_DE", "de", "german", "ge", "de_DE.ISO8859-1", "ISO8859-1");
echo strcasecmp($chars, strtoupper($chars))."\n";
?>

### Expected result
0

### Actual result
32

**Comment by drewklein** [comment]
The test above depends on the file encoding.  Change the string to "\xE4" to more easily see the failure.

**Comment by Orvid** [comment]
Fixed in #7159.
