### ISSUE TITLE
HHVM slow due to the rewrite rules Inefficient

### ISSUE THREAD

**Issue by netroby** [facebook/hhvm#7163]
hhvm version

```
HipHop VM 3.13.1 (rel)
Compiler: tags/HHVM-3.13.1-0-g4f382ad928a6e2a0607a8dcb251002aca77f11f6
Repo schema: 655b5912cb8136e9df6f9be972153e38ac446e0f

```

We running hhvm with proxygen mode. but we found hhvm slow. we using strace to look inside.

```
[pid 20568] stat("/www/public/apiv1/chat/pull", 0x7f1623bfa310) = -1 ENOENT (No such file or directory) <0.000008>
[pid 20568] stat("/www/public/apiv1/chat/pull", 0x7f1623bfa1e0) = -1 ENOENT (No such file or directory) <0.000005>
[pid 20568] stat("/www/public/apiv1/chat/pull", 0x7f1623bfa250) = -1 ENOENT (No such file or directory) <0.000005>
[pid 20568] stat("/www/public/apiv1/chat", 0x7f1623bfa250) = -1 ENOENT (No such file or directory) <0.000005>
[pid 20568] stat("/www/public/apiv1", 0x7f1623bfa250) = -1 ENOENT (No such file or directory) <0.000005>
[pid 20568] stat("/www/public/apiv1/chat/pull/index.php", 0x7f1623bfa250) = -1 ENOENT (No such file or directory) <0.000005>
[pid 20568] stat("/www/public/index.php", {st_dev=makedev(8, 3), st_ino=12845992, st_mode=S_IFREG|0664, st_nlink=1, st_uid=1000, st_gid=1000, st_blksize=4096, st_blocks=8, st_size=391, st_atime=2016/06/16-07:48:02.298732812, st_mtime=2016/05/17-13:55:10.034296550, st_ctime=2016/05/17-13:55:10.034296550}) = 0 <0.000010>
```

We have an webapp, we would like to have a more efficient rewrite rules.
do not need to find 6 times to find that file.
if /apiv1/chat/pull file not exists. we should go /index.php to handle the request.

**Comment by Orvid** [comment]
You should be able to add an explicit rewrite rule in Proxygen to get the behavior you're wanting. Alternatively, putting HHVM into fastcgi mode and using Apache or nginx to do the rewrite should also work.

**Comment by netroby** [comment]
Where is the proxygen document? how to write rewrite rules using hhvm builtin proxygen server

**Comment by eryi** [comment]
I don't think there are any rewrite rules in proxygen that can help you with that. It doesn't seem to be possible to ignore files in source_root. Related to #6997
