### ISSUE TITLE
I need help for HHVM Installation

### ISSUE THREAD

**Issue by jasonromando** [facebook/hhvm#7164]
### HHVM Version : 3.5

I following this page to build and install HHVM in my Amazon Linux EC2.
https://github.com/facebook/hhvm/wiki/Building-and-installing-HHVM-3.5-on-Amazon-Linux-2014.09.2

I finished the last step. Building HHVM, Compiling and installing

My EC2 dont have hhvm command, i cant even find hhvm config file.

I dont know where's should i start to solve the problem

**Comment by Orvid** [comment]
I would recommend trying to build against HHVM 3.14.1 instead of 3.5, as 3.5 is unsupported.

In [this section](https://github.com/facebook/hhvm/wiki/Building-and-installing-HHVM-3.5-on-Amazon-Linux-2014.09.2#checkout-hhvm-and-submodules) just do a `git checkout HHVM-3.14.1` instead of `git checkout HHVM-3.5`.

**Comment by jasonromando** [comment]
Finally reinstall the server and recompile all of the component, and install hhvm 3.14.1

[ec2-user@ip-172-31-30-222 ~]$ which hhvm
/usr/local/bin/hhvm

The command is work.

However, i don't know where is the hhvm located.

I want to change the hhvm server config

**Comment by jasonromando** [comment]
find -name "server.ini"
./hphp/test/server/fastcgi/config/server.ini
./hphp/test/server/http/config/server.ini
./hphp/test/server/debugger/config/server.ini

The result i got is the folder which i clone from git only.

cannot access /etc/hhvm: No such file or directory
hhvm: unrecognized service

**Comment by Orvid** [comment]
The main repo does not include any default configuration files, the [packaging repo](https://github.com/hhvm/packaging) has the default configs that we ship.

**Comment by apeabody** [comment]
FYI: I updated the recipe to Amazon Linux 2016.03 and HHVM 3.14.1: https://github.com/facebook/hhvm/wiki/Building-and-installing-HHVM-on-Amazon-Linux-2016.03

This version also requires less builds from source, except for glog and tbb which is a newer version (and looks to not have the OOM when building).

YMMV as it is obviously not tested extensively...  As Amazon Linux appears to be mostly CentOS-6 under the hood which has a rather old toolchain, I'd suggest Ubuntu 14.04 as an alternative "free tier" AMI.

**Comment by aorenste** [comment]
This issue has been waiting for more info for more than 2 weeks. I'm closing it for now, but feel free to re-open it if you can provide more info. https://github.com/facebook/hhvm/wiki/Human-Timeouts

This feature request doesn't appear to be actively being worked on. We would happily consider a pull request implementing it. If you plan to work on this issue let us know in the comments and we will re-open the issue and assign it to you. If you feel strongly that this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.

This issue has been waiting for more info for more than 2 weeks. I'm closing it for now, but feel free to re-open it if you can provide more info. https://github.com/facebook/hhvm/wiki/Human-Timeouts
