### ISSUE TITLE
OSX - compilation hangs while generating build id

### ISSUE THREAD

**Issue by alekitto** [facebook/hhvm#7170]
HHVM-3.14.1 (source)

On OS X, while compiling from source code, but outside a repository (non-git, non-hg folder, source extracted from tar.gz), compilation hangs indefinitely while executing
`ocaml -I scripts unix.cma scripts/gen_build_id.ml src/_build/utils/get_build_id.gen.c` from `hphp/hack`

OS X: 10.11.5
cmake 3.5.2
ocaml 4.03.0
GNU Make 3.81

**Comment by Orvid** [comment]
I believe there's a fix up for this internally.

**Comment by jwatzman** [comment]
@Orvid do you know if this was fixed? Do you have the internal diff number handy?

**Comment by Orvid** [comment]
D3461485 is the diff in question, and yes, it was fixed.

**Comment by jwatzman** [comment]
d22a1384455180d9d5e5b41eec90d3a69a6a823f is the public commit hash. Thanks for the pointer @Orvid!
