### ISSUE TITLE
There is no version of Composer available for your PHP version (7.0.99-hhvm)

### ISSUE THREAD

**Issue by donutloop** [facebook/hhvm#7171]
HHVM  Version: 3.14.1

Hello, 
i use a docker container with nginx and HHVM . When i try to install composer i get follow exception:

Fatal error: Uncaught exception 'RuntimeException' with message 'There is no version of Composer available for your PHP version (7.0.99-hhvm)' in /tmp/php-wrap-OspoPb:517

i enabled the option hhvm.php7.all

How can i fix that ?

Best regards,

Marcel

**Comment by WizKid** [comment]
Sounds like a composer bug

**Comment by donutloop** [comment]
i loaded the binary (Latest Snapshot and 1.1.2) with wget. Then i tried to install with "hhvm --php composer.phar install" the Dependencies. Now i get these error:

Fatal error: Uncaught TypeError: Argument 1 passed to unserialize() must be an instance of string, null given in /var/www/app/composer.phar:23
Stack trace:
#0 (): unserialize()
#1 (): __SystemLib\PharArchiveHandler->parsePhar()
#2 (): __SystemLib\PharArchiveHandler->__construct()
#3 (): Phar->__construct()
#4 /var/www/blog-api/composer.phar(23): Phar::mapPhar()
#5 {main}

Composer 
please read last comment
reference -->  https://github.com/composer/composer/issues/5449

**Comment by apeabody** [comment]
I just tested this under Debian Jessie with HHVM 3.14.1 and the HHVM nightly, and Ubuntu Xenial with the nightly and the newest Composer 1.1.3 installed without difficulty.  Looks like this was fixed 9 days ago in the composer installer: https://github.com/composer/getcomposer.org/commit/66d40ce674d8e61ba29aedef0f274f35132f783f

I'd suggest closing the issue unless there is something new on this particular problem.
