### ISSUE TITLE
Soap client segmentation fault in daemon mode.

### ISSUE THREAD

**Issue by Vahanerevan** [facebook/hhvm#7174]
HipHop VM 3.12.1 (rel)
Compiler: 1461965772_N
Repo schema: e2d5aa874f1738ad823f1f1e430e653b80c7e7f0

```bash
System Version: OS X EL Capitan 10.11.2 (15C50)
Kernel Version: Darwin 15.2.0
```

```php
 $client = new \SoapClient("any.wsdl");
```
```bash
hhvm -m daemon
```

Expected No Errors :)

But got.
```php
Array to string conversion in ... on line ...
Stack trace in /tmp/stacktrace.37813.log
```

**Comment by Vahanerevan** [comment]
In mode server  or hhvm index.hh it works.

**Comment by Vahanerevan** [comment]
I understand that soap is not priority , but maybe this not only about soap. I use mode server with nohup it's not a problem for me.

**Comment by Orvid** [comment]
Could you try with 3.14.2?

**Comment by aorenste** [comment]
This issue has been waiting for more info for more than 2 weeks. I'm closing it for now, but feel free to re-open it if you can provide more info. https://github.com/facebook/hhvm/wiki/Human-Timeouts
