### ISSUE TITLE
I build HHVM-3.14.1 in arm64, run hhvm hello.php fail

### ISSUE THREAD

**Issue by zhangkehong2brad** [facebook/hhvm#7176]
### HHVM Version
HHVM-3.14.1

### Standalone code, or other way to reproduce the problem
After build HHVM-3.14.1 in arm64 server, run hhvm hello.php, it report error:
Assertion failure: /home/hhvm_for_arm64_old/hhvm-HHVM-3.14.1/hphp/runtime/vm/jit/vasm-arm.cpp:106: void HPHP::jit::{anonymous}::Vgen::emit(Inst&) [with Inst = const HPHP::jit::stubret]: assertion `false' failed.
unimplemented instruction: stubret in B0
Core dumped: Aborted
Stack trace in /tmp/stacktrace.4685.log
Aborted (core dumped)

**Comment by mxw** [comment]
ARM support is in development.  Feel free to follow along here: https://www.facebook.com/groups/hhvm.arm/
