### ISSUE TITLE
Fatal error calling function in static array in class

### ISSUE THREAD

**Issue by eryi** [facebook/hhvm#7177]
### HHVM Version
3.13.2

### Standalone code, or other way to reproduce the problem
````
<?hh
class Test {
  private static array<string, (function():void)> $funcArray = array();
  public static function init():void {
    self::$funcArray = array(
      'doit' => () ==> {print "works";}
    );
  }

  public static function doit1():void {
      $func = self::$funcArray['doit'];
      $func();
  }

  public static function doit2():void {
    self::$funcArray['doit']();
  }
}

Test::init();
Test::doit1(); //works
Test::doit2(); //Fatal error: Function name must be a string
````

### Expected result
Both doit1() and doit2() should print "works".

### Actual result
doit1() prints "works" while doit2() throws Fatal error: Function name must be a string

**Comment by simonwelsh** [comment]
This matches PHP5: https://3v4l.org/RQXfd

Running HHVM in PHP7 mode produces "worksworks"

**Comment by Orvid** [comment]
This has to do with the way it was being parsed in PHP 5. As PHP 7 switched to an AST, it became possible to parse this correctly.
