### ISSUE TITLE
Compilation of ppc64-asm/decoder-ppc64.cpp.o fails after commit a96a950 with OOM

### ISSUE THREAD

**Issue by apeabody** [facebook/hhvm#7180]
### HHVM Version

HHVM on or after commit:
https://github.com/facebook/hhvm/commit/a96a9507c84586170120f7375c39a5b4cb85bf51

CentOS 7
gcc version 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC) - might be gcc bug/incompatibility?

### Standalone code, or other way to reproduce the problem

Compilation at this commit (or more recent) fails at decoder-ppc64.cpp.o with OOM (see below for full OOM details).  

The immediately previous commit compiles on my system normally.

### Actual result

c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
make[2]: *** [hphp/ppc64-asm/CMakeFiles/ppc64-asm.dir/decoder-ppc64.cpp.o] Error 4
make[1]: *** [hphp/ppc64-asm/CMakeFiles/ppc64-asm.dir/all] Error 2
make: *** [all] Error 2

DMESG:
[53283.573384] vmstats invoked oom-killer: gfp_mask=0x201da, order=0, oom_score_adj=0
[53283.573392] vmstats cpuset=/ mems_allowed=0
...
[56966.196670] Killed process 17828 (cc1plus) total-vm:5283432kB, anon-rss:3658256kB, file-rss:8kB

I have ~4GB of RAM on the system, with 1.5GB of swap configured.  Building HHVM was the only task of consequence.

**Comment by apeabody** [comment]
Confirmed the same problem, but under Ubuntu 14.04
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4


[ 54%] Building CXX object hphp/ppc64-asm/CMakeFiles/ppc64-asm.dir/decoder-ppc64.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
make[2]: *** [hphp/ppc64-asm/CMakeFiles/ppc64-asm.dir/decoder-ppc64.cpp.o] Error 4
make[1]: *** [hphp/ppc64-asm/CMakeFiles/ppc64-asm.dir/all] Error 2
make: *** [all] Error 2


[11110.348627] Out of memory: Kill process 14709 (cc1plus) score 942 or sacrifice child
[11110.349452] Killed process 14709 (cc1plus) total-vm:3882924kB, anon-rss:3809240kB, file-rss:52kB

**Comment by Orvid** [comment]
Yep, we've got a fix up internally. GCC wasn't applying the NO_OPT attribute because it was only on the definition and not on the declaration.

**Comment by apeabody** [comment]
Resolved in commit cdb110c589e47ccd03248f8d8a4898f709713829
