### ISSUE TITLE
RFI: RAII Supported?

### ISSUE THREAD

**Issue by huggsboson** [facebook/hhvm#7181]
I'm curious if RAII is still supported in HHVM or if objects may get cleaned up later by the GC.  The context is that we have a pool of objects sized to a max size, and we seem to be exhausting the pool. Items are returned to the pool when a __destruct is called which holds the underlying pool.  Based on some numbers I'd assume the pool is big enough that we shouldn't be having a problem, but if __destruct calls aren't being called until the GC runs that may explain some pool exhaustion I'm seeing.

### HHVM Version
HipHop VM 3.12.1 (rel)
Compiler: heads/master-0-ge1c05d8e5ce8cf1821ba9570fee0b6c3a5c0f405
Repo schema: da39a3ee5e6b4b0d3255bfef95601890afd80709

### Standalone code, or other way to reproduce the problem
Any use of RAII class X { function __destruct() { ... } }

### Expected result
Destruct called as soon as object goes out of scope.

### Actual result
Not sure if it is getting called then or at GC time.

**Comment by fredemmott** [comment]
- We support this pattern
 - We currently don't have a GC (we use similar refcounting to PHP)
 - When we do get a GC, we're aware that we will need to address this somehow.

Adding logging to your constructors/destructors seems like the best next step for debugging; if this involves an extension, make sure you deal with sweeps appropriately.

**Comment by fredemmott** [comment]
As a concrete example, we currently depend on this for copying code to github: https://github.com/facebook/fbshipit/commit/c9f6dfd1956697ccf04ec57f0b68dda7d9e00dfe

**Comment by huggsboson** [comment]
thanks for the quick, thoughtful and thorough reply.  There was a hackernews post about the removal of the RAII requirement for implementations a while ago, I'm curious if you have plans to remove it in the future?

https://news.ycombinator.com/item?id=8115704

**Comment by fredemmott** [comment]
We have no current plans. Changing this would be a huge break in compatibility - it'd either need to be optional, or some future version of PHP would need to do it first.
