### ISSUE TITLE
Hack regression: Incorrect case throwing duplicate errors

### ISSUE THREAD

**Issue by simonwelsh** [facebook/hhvm#7183]
### HHVM Version

3.14.1
### Standalone code, or other way to reproduce the problem

``` test.php
<?hh // strict

namespace phpunit\hhi\test {

use phpunit\framework\TestCase as TestCase;

class Test extends TestCase {}

}

namespace PHPUnit\Framework {
class TestCase {}
}
```
### Expected result

```
vagrant@homestead:~/test$ hh_client
test.php:7:20,27: Could not find phpunit\framework\TestCase (Naming[2006])
  test.php:12:7,14: Did you mean PHPUnit\Framework\TestCase?
vagrant@homestead:~/test$ 
```
### Actual result

```
vagrant@homestead:~/test$ hh_client
test.php:7:20,27: Could not find phpunit\framework\TestCase (Naming[2006])
  test.php:12:7,14: Did you mean PHPUnit\Framework\TestCase?
test.php:7:20,27: Could not find phpunit\framework\TestCase (Naming[2006])
  test.php:12:7,14: Did you mean PHPUnit\Framework\TestCase?
vagrant@homestead:~/test$ 
```

This has only started happening after upgrading to 3.14, which is breaking my phpunit-hhi unit tests ([3.14 build](https://git.simon.geek.nz/91-carriage/phpunit-hhi/builds/630), [3.13 build](https://git.simon.geek.nz/91-carriage/phpunit-hhi/builds/625), [3.9 build](https://git.simon.geek.nz/91-carriage/phpunit-hhi/builds/629))

**Comment by jwatzman** [comment]
@simonwelsh any chance you could bisect?

cc @dlreeves -- duplicate errors like this usually indicate we're running the same checks twice, so there could be an easy perf win in fixing this

**Comment by jwatzman** [comment]
cc @andrewjkennedy too, who I just saw on an internal task about `check_todo` running more than once which is a potential cause of this :)

**Comment by simonwelsh** [comment]
c354e482dc73ea4487ce22a75b11d0e554a938ac is the first bad commit
```
commit c354e482dc73ea4487ce22a75b11d0e554a938ac
Author: Jez Ng <jezng@fb.com>
Date:   Sat May 7 15:04:33 2016 -0700

    Kill the Nast heap
    
    Reviewed By: dabek
    
    Differential Revision: D3241214
    
    fb-gh-sync-id: fae8bc92260c4f7cc631ca371bfde71be254a20e
    fbshipit-source-id: fae8bc92260c4f7cc631ca371bfde71be254a20e

:040000 040000 6fd85470748b47713ad5380a9f6f5216fbf240db a215bc8248410cc1f6821a57bcf7dff3f4713770 M	php
```

**Comment by simonwelsh** [comment]
Back to only one error
