### ISSUE TITLE
Dynamic property access with hidden classes?

### ISSUE THREAD

**Issue by gopedib** [facebook/hhvm#7191]
Hi, I was wondering why HHVM does not optimize dynamic property access using "hidden classes" like mechanism used in V8 javascript jit compiler. "Hidden classes" in conjunction with "inline caching" convert accesses to the dynamic properties of an object to simple offset accesses? Below is a link for reference to hidden classes mechanism in V8. Is there any strong reason behind not implementing such mechanism in HHVM?

https://developers.google.com/v8/design

**Comment by edwinsmith** [comment]
The workloads that HHVM has been optimized for don't use dynamic properties very much. PHP and Hack have genuine classes; object instances have class metadata. The majority of callsites can be either statically resolved (via whole-program analysis with hhbbc), or are monomorphic, where a simple inline-cache mechanism is used.

**Comment by jwatzman** [comment]
Closing since the question was answered and I don't think there's anything else actionable here.
