### ISSUE TITLE
Typechecker does not consider a `mixed` shape field to be optional

### ISSUE THREAD

**Issue by eryi** [facebook/hhvm#7192]
### HHVM Version

3.13.2
### Standalone code, or other way to reproduce the problem

``` php
<?hh //strict
type TestShape = shape('optional' => mixed);
function testFunc (TestShape $testShape):void {}
function testFunc2 ():void {
  testFunc(shape());
}
```
### Expected result

Running hh_client shouldn't produce any errors.
### Actual result

Running hh_client produces "The field 'optional' is missing"  
Making the optional field ?mixed produces "?mixed is a redundant typehint - just use mixed"

**Comment by wake-up-neo** [comment]
It is OK from the type checker perspective, because you pass an empty shape. Just re-think your design or use ?CustomType in this case

**Comment by jwatzman** [comment]
cc @dlreeves -- since `mixed` allows null, it should probably be considered nullable for the purposes of shape checking. Not sure where nullable vs optional landed in shape checking though.

**Comment by rzvc** [comment]
Any news on this? It prevents working with not-yet declared types/libraries, which is important when migrating codebases to Hack.

As the typechecker suggests, ?mixed should be equivalent to mixed. If they're not, ?mixed should be allowed as a type.

**Comment by paulbiss** [comment]
cc @dlreeves @andrewjkennedy 

I'll let someone from the Hack team comment on the feasibility here. As a workaround if you make a type alias for mixed it looks like hack will let you use "?mixed_alias" as a type.

**Comment by rzvc** [comment]
Why was this closed? Was it fixed or will it never get fixed?

**Comment by eryi** [comment]
HHVM 3.23 changed how shapes worked. Optional and nullable is not the same thing anymore.  
https://hhvm.com/blog/2017/09/26/hhvm-3-22.html

**Comment by rzvc** [comment]
Awesome, thank you.
