### ISSUE TITLE
HHVM and PHP7 differ on type annotations on internal functions (rtrim in particular)

### ISSUE THREAD

**Issue by apeabody** [facebook/hhvm#7198]
What is the expected behavior with regards to strict type checking?  PHP7 defaults to “coercive mode” while hhvm.php7.all = 1 appears to act like "strict mode" in this example?
### HHVM Version

HHVM 3.14.1 hhvm.php7.all = 1
PHP 7.0.4
### Standalone code, or other way to reproduce the problem

```
<?php

$result = rtrim(null);
echo $result;
```
### Expected result

identical (no output)
### Actual result

```
hhvm --php test.php

Warning: rtrim() expects parameter 1 to be string, null given in /home/vagrant/hhvm/hphp/test.php on line 3
```

`php7 test.php`
### Potential Solutions

Perhaps hhvm.php7.scalar_types should be left out of hhvm.php7.all?  It appears currently to make HHVM act like PHP7's `declare(strict_types=1);` mode.

**Comment by jwatzman** [comment]
The typechecker understands only a few PHP7 features, and for all of the BC breaks, takes the PHP5 behaviour. Basically it follows the same logic as HHVM with `hhvm.php7.all = 0`.

**Comment by apeabody** [comment]
Hmm, well is there a more elegant way to have HHVM emulate the PHP7 default behavior example above?  Currently the example is preventing code that should work in PHP7 from running under HHVM in php7.all mode, and I worry about the side effects from the below "work-around" configuration:
```
hhvm.php7.all = 1
hhvm.php7.scalar_types = 0
```
Otherwise at the very least I think it makes sense to better document the expected divergence in PHP7 behavior.  Or if it is, I can't find the citation: https://docs.hhvm.com/hhvm/configuration/INI-settings#php-7-settings

**Comment by fredemmott** [comment]
@jwatzman : this is runtime, not the typechecker

**Comment by jwatzman** [comment]
Yeah looks like I misunderstood your question, ignore my comment above :-P

I remember there being some discussion on internal functions and type enforcement. Unfortunately I don't remember if it was in the context of PHP7, Hack types, or even a discussion on internals itself about PHP7's behaviour.

While HHVM's behaviour is different than PHP7, it's just a warning -- doesn't strict mode mean that it would throw some sort of exception? The difference seems to be that HHVM has a type annotation on an internal function and PHP7 does not. Maybe we should fix `rtrim` to accept `null` (eww though).

My recollection of how all of this fits together is super rusty, please correct anything above that sounds wrong. Also cc @paulbiss who implemented this for HHVM.

**Comment by apeabody** [comment]
Including @paulbiss per recommendation.

Here are some more samples, same rtrim(null) as above, but similar behavior occurs in other string functions such as substr().

PHP7.0.4
(no warning)

HHVM-nightly hhvm.php7.all = 1
Warning: rtrim() expects parameter 1 to be string, null given in /home/ubuntu/test.php on line 3

PHP7 declare(strict_types=1)
PHP Fatal error:  strict_types declaration must not use block mode in /home/ubuntu/test.php on line 2

HHVM hhvm.php7.all = 1 declare(strict_types=1)
Fatal error: Uncaught Error: strict_types declaration must not use block mode in /home/ubuntu/test.php:2
Stack trace:
#0 {main}

The potential issue is some frameworks/unit tests (Composer is an this case: https://getcomposer.org) catch the warning from rtrim in HHVM's php7.all=1 mode above as a fatal error/incompatiblity.  I don't know if true PHP7 compatibility is the goal, of if this should be a documented difference.

**Comment by plstand** [comment]
From the [Scalar Type Declarations RFC](https://wiki.php.net/rfc/scalar_type_hints_v5) (emphasis added):

> The weak type checking rules for the new scalar type declarations are **mostly the same** as those of extension and built-in PHP functions. The only **exception** to this is the handling of NULL: in order to be consistent with our existing type declarations for classes, callables and arrays, **NULL is not accepted by default**, unless it is a parameter and is explicitly given a default value of NULL.

So if HHVM does apply the PHP7 weak type checking rules to built-in functions, for PHP7 compatibility, each and every parameter of a built-in function having a scalar type hint (to match zend_parse_parameters()) must accept NULL (unlike user-defined functions), **EXCEPT** in `strict_types` mode:

>  The strict type checking rules are quite straightforward: when the type of the value matches that specified by the type declaration it is accepted, otherwise it is not.
>
> These strict type checking rules are **used for userland scalar type declarations, and for extension and built-in PHP functions**.
>
> The one exception is that [widening primitive conversion](http://docs.oracle.com/javase/specs/jls/se7/html/jls-5.html#jls-5.1.2) is allowed for int to float. This means that parameters that declare float can also accept int.

**Comment by plstand** [comment]
> The potential issue is some frameworks/unit tests (Composer is an this case: https://getcomposer.org) catch the warning from rtrim in HHVM's php7.all=1 mode above as a fatal error/incompatiblity. I don't know if true PHP7 compatibility is the goal, of if this should be a documented difference.

This is not merely a warning that PHP7 does not generate, yet HHVM does. Rather, the function call fails because of the type error:
```
hphpd> =str_pad('', 8)
=str_pad('', 8)
"        "
hphpd> =str_pad(null, 8)
=str_pad(null, 8)

Warning: str_pad() expects parameter 1 to be string, null given
null
```

In PHP7, I get the same result in both cases:
```
php > var_dump(str_pad('', 8));
string(8) "        "
php > var_dump(str_pad(null, 8));
string(8) "        "
```

**Comment by Orvid** [comment]
HHVM enables `strict_types` by default.

**Comment by apeabody** [comment]
Thanks - so it sounds like this is by design.  If that's the case and desired, then I would suggest documenting (or at least point to) that HHVM's PHP7 is always/really PHP7 strict_types and isn't targeting default compatibility with PHP7's default “coercive mode”.  That would hopefully assist with putting issues to rest about 3rd party code that consider HHVM's PHP7 as "broken" because the code doesn't work in strict_types.

**Comment by plstand** [comment]
> HHVM enables strict_types by default.

Is that true? If so, I would expect line 4 of the following test case to generate an uncaught TypeError, at which point the script should terminate. Instead, only line 5 generates an error. (In PHP7, no error is generated.)

```
<?php

var_dump(str_pad('', 8));
var_dump(str_pad(1, 8));
var_dump(str_pad(null, 8));
```

Also, changing line 2 (the blank line) to read `declare(strict_types=0);` makes no difference, and changing it to read `declare(strict_types=1);` causes line 4 to generate a TypeError, as in PHP7.

**Comment by apeabody** [comment]
I don't know about str_pad in particular, but feel free to test my example of using rtrim(null) above for the behavior I'm seeing.

**Comment by plstand** [comment]
> I don't know about str_pad in particular, but feel free to test my example of using rtrim(null) above for the behavior I'm seeing.

rtrim is the same:
```
<?php

var_dump(rtrim(''));
var_dump(rtrim(1));
var_dump(rtrim(null));
```

----

Actual result in PHP7:
```
string(0) ""
string(1) "1"
string(0) ""
```

Changing line 2 to `declare(strict_types=0);` makes no difference.

Actual result in HHVM, with `hhvm.php7.all` on:
```
string(0) ""
string(1) "1"

Warning: rtrim() expects parameter 1 to be string, null given in /home/ki/Projects/hhvm/ttt3.php on line 5
NULL
```

Changing line 2 to `declare(strict_types=0);` makes no difference.

----

Actual result in PHP7, with line 2 changed to `declare(strict_types=1);`:
```
string(0) ""

Fatal error: Uncaught TypeError: rtrim() expects parameter 1 to be string, integer given in /home/ki/Projects/hhvm/ttt3.php:4
Stack trace:
#0 /home/ki/Projects/hhvm/ttt3.php(4): rtrim(1)
#1 {main}
  thrown in /home/ki/Projects/hhvm/ttt3.php on line 4
```

Actual result in HHVM, with `hhvm.php7.all` on, and with line 2 changed to `declare(strict_types=1);`:
```
string(0) ""

Fatal error: Uncaught TypeError: Argument 1 passed to rtrim() must be an instance of string, int given in /home/ki/Projects/hhvm/ttt3.php:4
Stack trace:
#0 /home/ki/Projects/hhvm/ttt3.php(4): rtrim()
#1 {main}
```

----

Note the following:

1. With `declare(strict_types=1);`, HHVM is consistent with PHP7, in that line 4, which passes an integer, throws a TypeError.

2. With `declare(strict_types=0);` (the default), PHP7 accepts the string, the integer, and NULL. If the function were a user-defined function, NULL would not have been accepted (by either PHP7 or HHVM), and a warning would have been generated.

3. With `declare(strict_types=0);` (the default), HHVM accepts the string and the integer, but not NULL. Essentially, HHVM treats the built-in function like a user-defined function, whereas in PHP7, built-in functions are a special case, and NULL is accepted. For scalar (int, float, string, or bool) parameters to user-defined functions, neither PHP7 nor HHVM accept NULL.

**Comment by apeabody** [comment]
OK, got it.  

So guess the guess the question is in HHVM's PHP7 mode with declare(strict_types=0), is the *absence* of the special case for built-in's (str_pad, rtrim, etc) to accept NULL for a strings and integers by design or accident?

**Comment by paulbiss** [comment]
So the current behavior is definitely wrong. There are a number of issues with the way that we handle types on builtins. Right now for builtins HHVM will follow the correct PHP7 behavior for declare(strict_types=1), but falls back to PHP5 behavior for declare(strict_types=0) (hence the warning rather than a fatal).

The fix for this shouldn't be overly complicated, should just require some updates to tv-helpers.cpp and native.cpp. Will try to give it a look this week.

**Comment by photodude** [comment]
Related Errors
```php
Fatal error: Uncaught exception 'BadMethodCallException' with message 'Call to a member function executeUpdate() on a non-object (null)' in /home/travis/build/doctrine/doctrine2/tests/Doctrine/Tests/ORM/Functional/ValueConversionType/ManyToManyCompositeIdForeignKeyTest.php:50
Stack trace:
#0 /home/travis/build/doctrine/doctrine2/vendor/phpunit/phpunit/src/Framework/TestSuite.php(758): Doctrine\Tests\ORM\Functional\ValueConversionType\ManyToManyCompositeIdForeignKeyTest::tearDownAfterClass()
#1 /home/travis/build/doctrine/doctrine2/vendor/phpunit/phpunit/src/Framework/TestSuite.php(753): PHPUnit_Framework_TestSuite->run()
#2 /home/travis/build/doctrine/doctrine2/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(465): PHPUnit_Framework_TestSuite->run()
#3 /home/travis/build/doctrine/doctrine2/vendor/phpunit/phpunit/src/TextUI/Command.php(185): PHPUnit_TextUI_TestRunner->doRun()
#4 /home/travis/build/doctrine/doctrine2/vendor/phpunit/phpunit/src/TextUI/Command.php(115): PHPUnit_TextUI_Command->run()
#5 /home/travis/build/doctrine/doctrine2/vendor/phpunit/phpunit/phpunit(47): PHPUnit_TextUI_Command::main()
#6 {main}
```

```php
Fatal error: Uncaught TypeError: Argument 1 passed to unserialize() must be an instance of string, null given in /home/travis/.phpenv/versions/hhvm-stable/bin/composer:23
Stack trace:
#0 (): unserialize()
#1 (): __SystemLib\PharArchiveHandler->parsePhar()
#2 (): __SystemLib\PharArchiveHandler->__construct()
#3 (): Phar->__construct()
#4 /home/travis/.phpenv/versions/hhvm-stable/bin/composer(23): Phar::mapPhar()
#5 {main}
```

**Comment by iangcarroll** [comment]
`rtrim` not taking `null` breaks Composer, FYI.

**Comment by photodude** [comment]
@paulbiss Is there any progress on this issue? It would be nice to be able to resume testing against hhvm in php7 mode and this is a blocking issue.

**Comment by photodude** [comment]
possibly related error
php
Warning: ini_get_all() expects parameter 1 to be string, null given in /phpunit/src/Util/GlobalState.php on line 79
    #0 PHPUnit_Util_GlobalState::getIniSettingsAsString(), called at [/phpunit/src/Framework/TestCase.php:809]
    #1 PHPUnit_Framework_TestCase->run(), called at [/phpunit/src/Framework/TestSuite.php:753]
    #2 PHPUnit_Framework_TestSuite->run(), called at [/phpunit/src/Framework/TestSuite.php:753]
    #3 PHPUnit_Framework_TestSuite->run(), called at [/phpunit/src/Framework/TestSuite.php:753]
    #4 PHPUnit_Framework_TestSuite->run(), called at [/phpunit/src/TextUI/TestRunner.php:465]
    #5 PHPUnit_TextUI_TestRunner->doRun(), called at [/phpunit/src/TextUI/Command.php:185]
    #6 PHPUnit_TextUI_Command->run(), called at [/phpunit/src/TextUI/Command.php:115]
    #7 PHPUnit_TextUI_Command::main(), called at [/phpunit/phpunit:47]
```

**Comment by photodude** [comment]
@paulbiss Just checking back on this issue? It would be nice to be able to resume testing against hhvm in php7 mode and this is a blocking issue.

**Comment by Kazanir** [comment]
Right now this issue means that no one can use HHVM to build a Composer project which contains PHP7-only packages, FYI.

**Comment by photodude** [comment]
@aorenste Just checking back on this issue....
It would be nice to be able to resume testing against hhvm in php7 mode and this is a blocking issue since it breaks most composer based builds.

**Comment by Orvid** [comment]
We have a mostly functional diff up internally to deal with correctly enabling compliance with PHP7 strict mode, but there are still a few edge cases left to solve.

**Comment by photodude** [comment]
@Orvid that's great news. 
Looking forward to the eventual fix on this. (patiently, but eagerly waiting)

**Comment by aorenste** [comment]
@photodude Yeah - the "mostly easy" tag turns out to be quite false.  The internal patch is passing tests and is making its rounds through review.

**Comment by asuth** [comment]
How's this fix coming along? Would love to see it land! Thanks for all your work on this.

For others following along, here's where we (Quizlet) got stuck with this issue:
- Mockery doesn't believe parameter hinting and return types exist for functions when it thinks it's in PHP < 7
- If you turn on PHP7 mode (`hhvm.php7.all = 1`) in HHVM, it switches to PHP7 "strict mode" which causes errors when you call builtins with bad types e.g. call `strpos` with an int instead of a string. This happens all over our code and in library code (e.g. Composer)
- If you edit Mockery to do return types in php5 mode (aka what we're in now), it complains that eval() cannot use Hack code (aka code with return types)

These three problems are intractable if you want methods with return type hints to be mocked, until HHVM fixes this issue.

So for now, because we want to keep our typehints, and conveniently typehint errors are `E_RECOVERABLE_ERROR` which do not break php internals when they happen, we setup a `set_error_handler` to specifically ignore this exact typehinting error, but throw on everything else. It's definitely messy but the only workaround we could think of.

**Comment by photodude** [comment]
@asuth you should also look at Issues #7467 and #7544

**Comment by aorenste** [comment]
@asuth - It turns out to be much harder than I originally thought (a bunch of changes have to wind through the code).  I still have it as a background task but am currently working on other issues.

**Comment by photodude** [comment]
@aorenste We look forward to the fix. Especially since some projects are now moving to requiring PHP 7.0+ through composer which make this an even bigger blocking issue.

**Comment by photodude** [comment]
Another function used by composer which is affected...

```php
 strtolower() expects parameter 1 to be string, null given 
```

**Comment by photodude** [comment]
@aorenste Just checking back on this issue.... How's the progress on getting the patch for this issue through review?

**Comment by aorenste** [comment]
@photodude I still haven't gotten back to it.  It's not really a patch as much as a "work in progress".  If I remember where I was at the time it works about 90% of the time but fails in cases of inlined functions and also has some problems in repo mode.

**Comment by photodude** [comment]
@aorenste thanks for the update. I learned of an HHVM internal related failure due to this issue
```php
Fatal error: Uncaught TypeError: Argument 1 passed to dirname() must be an instance of string, bool given in phar://composer.phar/bin/../src/../vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php:141
```

the root of this from composer to symfony/finder comes from HHVM itself. The dirname call is not in the symfony/finder code, but in the implementation of SplFileInfo->getPath(), which is part of HHVM.
see https://github.com/facebook/hhvm/blob/master/hphp/system/php/spl/file_handling/SplFileInfo.php#L40

#### related issues
- https://github.com/symfony/symfony/issues/21897
- https://github.com/composer/composer/issues/6230

**Comment by SCIF** [comment]
@photodude , @aorenste , any forecast on the solution date? Also, will that solution be backported to previous releases? Thanks in advance!

**Comment by photodude** [comment]
@SCIF I'm just an interested party in the solution. I have know knowledge in to progress.

@fredemmott Who is assigned to this issue now that you unassigned @aorenste ? This is a major blocking issue for any project that has moved on to only supporting php 7 and uses composer. (it's also another reason that major projects are or have dropped HHVM support)

**Comment by fredemmott** [comment]
No one is actively working on this as far as I'm aware - I'm no longer working on HHVM though.

**Comment by fredemmott** [comment]
I unassigned Aaron as I believe he's no longer working on compatibility issues; having it in the unassigned pile is better than having it incorrectly marked as being worked on.

**Comment by photodude** [comment]
If unassigned at the moment is best, then that is best. This is a long standing issue that needs to be addressed to continue php support in hhvm. More php projects will likely drop HHVM support the longer this issue continues to not be addressed.

**Comment by Orvid** [comment]
@aorenste Would you be willing to at least put the change up as a PR rather than a diff so anyone externally that wants to try to get things working has a decent idea of the scope and where to start?

**Comment by aorenste** [comment]
@Orvid The problem is that @paulbiss pointed out that the approach I took isn't even close because it fails if the called function is inlined.  As such I'm not sure that my starting point would help someone else.  I never got very far on the alternative approach.

**Comment by fredemmott** [comment]
`dirname()` completely breaks composer (https://gist.github.com/fredemmott/783596a9591f19d34940c223dc75dd5b)

given that the PHP ecosystem is rapidly moving on from PHP5, this is really a big deal.

**Comment by photodude** [comment]
@fredemmott I have also seen that? it comes back to the rtrim issue 

```php
Fatal error: Uncaught TypeError: Argument 1 passed to dirname() must be an instance of string, bool given in phar://composer.phar/bin/../src/../vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php:141
```

the root of this from composer to symfony/finder comes from HHVM itself. The dirname call is not in the symfony/finder code, but in the implementation of `SplFileInfo->getPath()`, which is part of HHVM.
see https://github.com/facebook/hhvm/blob/master/hphp/system/php/spl/file_handling/SplFileInfo.php#L40

digging deeper we are back to the rtrim issue at the class construct call to this method
https://github.com/facebook/hhvm/blob/master/hphp/system/php/spl/file_handling/SplFileInfo.php#L438-L443

#### related issues
- https://github.com/symfony/symfony/issues/21897
- https://github.com/composer/composer/issues/6230

**Comment by photodude** [comment]
Looks like another couple of projects have dropped HHVM. Breaks like this issue are one of the reasons
- Symfony
  - https://twitter.com/fabpot/status/865263458903875584
- doctrine
  - https://twitter.com/lcobucci/status/865081210128793601

**Comment by asuth** [comment]
We depend on HHVM and also a lot of open-source code, so this is really bad/stressful for us. Is there anything we can do to vote for this or otherwise support this?

**Comment by mxw** [comment]
Hi folks!

First off, sorry that the communication on this issue has been a bit choppy and less than upfront.  We're going to be meeting very soon to discuss how to prioritize PHP7 compat issues, this one being the biggest of the bunch.

I'll try to update here early next week about when we expect we'll be able to get this fixed (it sounds like this is the main remaining incompatibility).  As @aorenste mentioned, we had an almost-working patch for the fix, but it's been stuck in rebase hell for a while.  That's on us (obviously), and I'm hoping we'll be able to get it sorted out for you all soon.  Thanks for your patience, to everyone who's been sticking it out.

**Comment by robfrawley** [comment]
This should have been a *priority* for the past year since this issue was reported. Just yesterday @mofarrell noted in https://github.com/symfony/symfony/pull/22733#issuecomment-302516789 that

> It happens to not be trivial to fix, and also currently not at the top of our priority list.

Which leaves me particularly confused about the priority of this issue.

As this issue makes it __impossible__ to properly support PHP 7 only code in combination with HHVM, this needs to be a priority if there is any expectation that library authors will support HHVM. And since many of the projects I maintain require Symfony components, they will be dropping support ATM as well. 

For example, as described in https://github.com/liip/LiipImagineBundle/pull/908#issuecomment-299654044, the [liip/imagine-bundle](https://github.com/liip/LiipImagineBundle/) package removed HHVM support from the `2.x` development branch two weeks ago.

**Comment by FractalizeR** [comment]
It's a very sad thing that because of the lack of attention to such issues [major framework just drop HHVM compatibility](http://symfony.com/blog/symfony-4-end-of-hhvm-support).

**Comment by photodude** [comment]
And another has dropped support Joomla is now out.
https://github.com/joomla/joomla-cms/pull/16232

**Comment by oliverklee** [comment]
Also phpList 4 and Emogrifier: https://github.com/phpList/phpList/pull/45 https://github.com/jjriv/emogrifier/pull/386

**Comment by hikari-no-yume** [comment]
I think I remember pointing out, before HHVM implemented this, that it would need to handle null differently here. I guess that was overlooked.

**Comment by photodude** [comment]
Thanks @mofarrell for pushing a fix for this. With the fix merged, What versions will be getting it? Will all of the current LTS versions be fixed?

**Comment by fredemmott** [comment]
This is probably too intrusive a change for LTS backporting: it's much more important that 3.x.y can run code that 3.x.(y-1) could than for 3.x.y to be able to run /more/ code. Exceptions are rare, except for security fixes.

**Comment by robfrawley** [comment]
The was a _language bug that diverged your internal function type handling_ from that of PHP's; it should be back-ported IMHO.

**Comment by Orvid** [comment]
@fredemmott My understanding is that we do have plans to backport it to at least the current LTS.

**Comment by fredemmott** [comment]
If you're reasonably confident that this won't break existing code written to run on HHVM, I don't mind.

Regardless of the type of bug, unless there's a security issue that makes code changes required, upgrading from 3.x.y to 3.x.(y+1) should *never* break code that is already running. If it does, that breaks the entire purpose of having LTS releases.

**Comment by simonwelsh** [comment]
If this does end up in 3.18, can you also make sure it ends up in 3.19/3.20? It'd be rather strange to have things work in 3.18 but not 3.19, and will make version constraints that much more annoying.

**Comment by fredemmott** [comment]
The general problem was fixed, but composer isn't; repro case for that issue: https://3v4l.org/ahpE3 (based on @photodude's comment above)

**Comment by fredemmott** [comment]
Filed #7869 for composer as the original issue here is fixed; working on the splfileinfo issue, and whatever else comes up when testing composer.

**Comment by photodude** [comment]
Also broken if `null` is passed to `splfileinfo()` resulting in the same `rtrim()` issue originally reported (since `splfileinfo()` is dependent on `rtrim()` as [noted above](https://github.com/facebook/hhvm/issues/7198#issuecomment-299605882) ).
https://3v4l.org/4ljZ8

**Comment by fredemmott** [comment]
yeah, we differ on any non-string input to splfileinfo

**Comment by hopeseekr** [comment]
This PR is needed, because **WE ARE NOT IN A PHP5 WORLD ANY LONGER*. 

The HHVM team, and Facebook Corp., need to be *galvanized* to committing to stay compatible with PHP7 or they need to break all pretenses and start marking Hack Language as its own thing.

Otherwise, once all PHP5 code is collecting dust, relatively soon, all of your and my HHVM efforts will have been in vain!

*Hopefully this PR is a wakeup call!*

**Comment by photodude** [comment]
@hopeseekr PHP 5.6 is EOL the same month as PHP 7.0 at the end of 2018. I agree primary efforts should be on compatibility issues with PHP 7.1 and with the alpha/beta release of PHP 7.2.

the majority of new development in PHP land has moved to just PHP 7+ support, I agree HHVM needs to make more effort to do the same.
