### ISSUE TITLE
Error while trying to install phpmyadmin on hhvm server

### ISSUE THREAD

**Issue by ghost** [facebook/hhvm#7199]
### HHVM Version:

HipHop VM 3.13.1 (rel)
### Issue

when I try to install phpmyadmin on hhvm I got this error
phpMyAdmin - Error
Error during session start; please check your PHP and/or webserver log file and configure your PHP installation properly. Also ensure that cookies are enabled in your browser.

open(/usr/local/var/lib/hhvm/sessions/sess_263ec31562637626a719b3800e89790ad0d153e4, O_RDWR) failed: No such file or directory (2)
### Actual result:

Error during session start; please check your PHP and/or webserver log file and configure your PHP installation properly. Also ensure that cookies are enabled in your browser.

open(/usr/local/var/lib/hhvm/sessions/sess_263ec31562637626a719b3800e89790ad0d153e4, O_RDWR) failed: No such file or directory (2)

**Comment by alex-mashin** [comment]
Bump.

I have the following error after I enter login and password:
```
Fatal error: Uncaught TypeError: Argument 5 to mysqli_real_connect() must be of type ?string, bool given in /usr/share/phpmyadmin/libraries/dbi/DBIMysqli.class.php:122\nStack trace:\n#0 /usr/share/phpmyadmin/libraries/dbi/DBIMysqli.class.php(122): mysqli_real_connect()\n#1 /usr/share/phpmyadmin/libraries/dbi/DBIMysqli.class.php(192): PMA_DBI_Mysqli->_realConnect()\n#2 /usr/share/phpmyadmin/libraries/DatabaseInterface.class.php(2689): PMA_DBI_Mysqli->connect()\n#3 /usr/share/phpmyadmin/libraries/common.inc.php(1000): PMA_DatabaseInterface->connect()\n#4 /usr/share/phpmyadmin/index.php(12): include()\n#5 {main}
```

**Comment by Orvid** [comment]
Ah, the error helps. In this case PHPMyAdmin is the one at fault, as HHVM is behaving correctly. PHPMyAdmin is passing a literal `false` for the `$dbName` parameter, which is documented to be a string.  In PHP that IIRC, that should be getting implicitly converted to a string `"false"`, which is almost definitely not what was intended.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This issue applies to running php code on hhvm. Hhvm [nolonger supports running php code](https://hhvm.com/blog/2018/09/12/end-of-php-support-future-of-hack.html) since [hhvm version 4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html).
