### ISSUE TITLE
Treat \Traversable in systemlib as HH\Traversable when called from Hack

### ISSUE THREAD

**Issue by HRMsimon** [facebook/hhvm#7203]
### HHVM Version

3.14
### Standalone code, or other way to reproduce the problem

``` hack
<?hh

function foo<T>(Traversable<T> $baz): array<T> {
  return iterator_to_array($baz);
}

foo([1, 2, 3]);
```
### Expected result

Runtime does not error
### Actual result

Runtime errors with `Argument must implement interface Traversable`

When calling builtins from Hack, it'll be nice if the interfaces matched those used in Hack. In this case, that means allowing an `array` to be passed to something expecting `Traversable`, even though an array only implements `HH\Traversable`

**Comment by fredemmott** [comment]
Replacing with #8465
