### ISSUE TITLE
Please add support for tuple as a key for Map

### ISSUE THREAD

**Issue by ethanjyx** [facebook/hhvm#7220]
### HHVM Version

latest
### Standalone code, or other way to reproduce the problem

```
hphpd> $a = Map{};
hphpd> $b = tuple(1, 2);
hphpd> $a[$b] = 3;
```
### Expected result

$a becomes a map with only one value ((1,2) => 3)
### Actual result

Hit a php exception : exception 'InvalidArgumentException' with message 'Only integer keys and string keys may be used with Maps' in :1
Stack trace:
#0 (1): include()
#1 {main}

**Comment by Orvid** [comment]
`Map` was specifically intended to represent the `int` and `string` keying of arrays.

**Comment by ethanjyx** [comment]
@Orvid why is that? Other languages like Java and C++ support these

**Comment by paulbiss** [comment]
@ethanjyx `Map` is backed by a PHP array, they only support ints and strings. It might be nice to have a more generic map data structure but this one was designed for speed and interoperability with PHP arrays (there's a zero cost conversion), so it's unlikely we would ever change the allowed key types.

**Comment by lexidor** [comment]
Sadly, even with the PHP array removed, this is still not something that could be done. `Map<Tk, Tv>` implements `KeyedContainer<Tk, Tv>` which has a type constraint on `Tk` or `as arraykey`. Allowing non arraykey keys in a Map, would either require Map to stop being a KeyedContainer or KeyedContainer would need to drop its constraint. This would break all code that works with KeyedContainers. If Map wasn't a KeyedContainer, you could not covariantly accept both a `Vector` and a `Map`. If the `as arraykey` constraint was dropped, all `Dict\` functions in the HSL would stop working.

Having something like this would be cool, but it would have to be its own distinct type.
