### ISSUE TITLE
ARM64: Crashes on A57 core - missing clear_cache in a few cases

### ISSUE THREAD

**Issue by sunil-sk** [facebook/hhvm#7223]
ARM requires explicit cache flush for self modifying code. In the current ARM64 support, cache flush is done after VASM is emitted as part of Vgen destructor (See vasm-arm.cpp). There are a few cases where code is directly emitted without involving VASM lowering. We need to clear cache for these cases too. For this reason, hhvm is crashing on A57 core (Juno reference platform). 
Missing cases:
1. align-arm.cpp (AlignImpl::pad())
2. func-guard-arm.cpp (emitFuncGuard())
3. smashable-instr-arm.cpp (emitSmashable*())
4. unique-stubs-arm.cpp (emitCallToExit())

This can be fixed by either flushing the cache explicitly in each of the above cases or doing it once in VIXL assembler after generating the code. I can submit PR for either approach based on what we decide.

**Comment by edwinsmith** [comment]
all of the places you mention above are in -arm.cpp files, so it probably is just up to you. If it was me I'd do it outside the assembler, because in general I wouldn't want to tie the flush effects to the assembler destructor. triggering the flush seems like an important action to keep explicit.

**Comment by sunil-sk** [comment]
Agree, I will do it outside the assembler.
