### ISSUE TITLE
SQLite doesn't throw an exception

### ISSUE THREAD

**Issue by nazar-pc** [facebook/hhvm#7224]
### HHVM Version
```
HipHop VM 3.15.0-dev (rel)
Compiler: heads/master-0-g438b54f98e0f85f0ed59e9921dd4f7ccb83fcab9
Repo schema: cff2737467d2ca6d2896b717c762ddbdbe7b0f72
```

### Standalone code, or other way to reproduce the problem
```php
<?php
new SQLite3('/'.uniqid('random', true).'/db');
```
### Expected result (PHP 7, already formatted as PHPT test)
```
PHP Fatal error:  Uncaught Exception: Unable to open database: unable to open database file in %s:2
Stack trace:
#0 %s(2): SQLite3->__construct('/random%s')
#1 {main}
  thrown in %s on line 2
```

### Actual result (HHVM)
```
Fatal error: Unable to open database: unable to open database file
```

Sure, error is present, but there should be an exception.

**Comment by Orvid** [comment]
I shall claim (without having actually looked yet) that SQLite changed something between v3.7.15.2 (which is what, for some reason, we had been building OSS against) to v3.13.0, which is what master is building against after I updated pretty much everything in third-party.

**Comment by Orvid** [comment]
Actually, it's been there, and is probably because we are throwing a C++ exception rather than a php exception, whoops.
