### ISSUE TITLE
SQLite doesn't fail with empty path

### ISSUE THREAD

**Issue by nazar-pc** [facebook/hhvm#7225]
### HHVM Version
```
HipHop VM 3.15.0-dev (rel)
Compiler: heads/master-0-g438b54f98e0f85f0ed59e9921dd4f7ccb83fcab9
Repo schema: cff2737467d2ca6d2896b717c762ddbdbe7b0f72
```
### Standalone code, or other way to reproduce the problem
```php
<?php
$x = new SQLite3('');
```
### Expected result (PHP 7, already formatted as PHPT test)
```
PHP Fatal error:  Uncaught Exception: Unable to expand filepath in %s:2
Stack trace:
#0 %s(2): SQLite3->__construct('')
#1 {main}
  thrown in %s on line 2
```
### Actual result (HHVM)
No output

**Comment by Orvid** [comment]
I'm going to be optimistic and hope that this is caused by the same thing as #7224

**Comment by apeabody** [comment]
It appears that FileUtil::checkPathAndError is fine with an empty filename, and even more surprisingly sqlite is comfortable (see below) with an empty string filename.  This begs the question: should checkPathAndError() error on an empty filename, or would it be safer to just verified locally for this function only?  Also is there a better helper function in HHVM than raise_fatal_error() which doesn't really match the PHP exception format above?

https://www.sqlite.org/c3ref/open.html
If the filename is an empty string, then a private, temporary on-disk database will be created. This private database will be automatically deleted as soon as the database connection is closed.

**Comment by Orvid** [comment]
As far as exceptions, there's https://github.com/facebook/hhvm/blob/master/hphp/system/systemlib.h#L119

In this case we're allowing something that's actually reasonable to allow that PHP isn't. It could even technically be called a bug that PHP doesn't allow it. It might be interesting to see what sort of response you get from reporting the SQLite extension not allowing an empty path in PHP as a bug.

**Comment by nazar-pc** [comment]
I agree that this is rather bug in PHP, not in HHVM: https://bugs.php.net/bug.php?id=72653
