### ISSUE TITLE
async's execution starts with await - \HH\Asio\curl_exec

### ISSUE THREAD

**Issue by tugrul** [facebook/hhvm#7228]
### HHVM Version
HipHop VM 3.14.2 (rel)
Compiler: tags/HHVM-3.14.2-0-ge8134a09af2bc6e27191a63b6ed2f113ac80ee92
Repo schema: 676c6f18d2f55ba8ce519ca7af4c26a9747c1563

### Standalone code, or other way to reproduce the problem
```hack
<?hh

async function main(): Awaitable<void> {
    $result1 = \HH\Asio\curl_exec('http://localhost:8080');
    $result2 = \HH\Asio\curl_exec('http://localhost:9090');

    sleep(10);

    $a = await $result1;
    $b = await $result2;

    echo $a, $b;
}

\HH\Asio\join(main());
```

### Expected result
Web requests should be started on call `\HH\Asio\curl_exec` and wait response to complete on `await` or finally if web request are already completed before sleep function.

### Actual result
Web request are started on `await`

![async](https://cloud.githubusercontent.com/assets/163442/16857601/95fc8852-4a29-11e6-9958-109721a7033b.gif)

**Comment by WizKid** [comment]
Why would it start before await? await means that you want to wait on the result. There is nothing saying that the request should be sent before that.

**Comment by fredemmott** [comment]
This is intentionally undefined behavior. If you have something else you want to run in parallel, it also needs to be async. HH\asio\usleep may be interesting if you have a real case for sleeping.

**Comment by fredemmott** [comment]
Also, depending on what libraries are on your system (in particular, if HHVM is linked with libares), it /may/ have started executing immediately - however, it went back to executing your PHP code after starting the DNS request, but before starting to open the HTTP connection.

**Comment by fredemmott** [comment]
Actually, that's true even without libares - just that without it, we have to poll for the DNS response (https://github.com/facebook/hhvm/blob/97c76fe30eaf299c740696830e60b6c1ac69312f/hphp/runtime/ext/curl/ext_curl.php), but that still re-enters the scheduler and potentially your blocking code.

**Comment by fredemmott** [comment]
@tugrul yep, that's exactly what's happening - your example shows this if you replace 'localhost' with '127.0.0.1'

**Comment by tugrul** [comment]
@fredemmott correct behavior when i use '127.0.0.1'. Looks like dns resolver is blocking.

![async2](https://cloud.githubusercontent.com/assets/163442/16858662/269ecb66-4a31-11e6-9d75-11d2106c9e88.gif)

**Comment by fredemmott** [comment]
It's not blocking - it starts, then as the DNS query is *not* a blocking call, the scheduler does something else: in this case, executes your PHP code, which does have a blocking call.

**Comment by tugrul** [comment]
I Understood. DNS query and HTTP request are not atomic. sleep command seperating execution of them

**Comment by WizKid** [comment]
It has nothing to do with atomic. PHP is single threaded and can only do one thing at a time except IO. So it kicks of the DNS request and then go to sleep. When result comes back it needs to do someth9ing else but can't because you are sleeping. So it has to wait up until it can do something and now it can do the HTTP request.
