### ISSUE TITLE
php4 style constructors halt on deprecated under php7 compatability

### ISSUE THREAD

**Issue by photodude** [facebook/hhvm#7229]
### HHVM Version

3.12.4 / 3.14.2
### Standalone code, or other way to reproduce the problem

[travis ci unit test of Joomla showing the error and point processing halts](https://travis-ci.org/photodude/joomla-cms/jobs/142317919)
`Methods with the same name as their class will not be constructors in a future version of PHP; Cache_Lite has a deprecated constructor: in JCacheStorageTest::casesGetInstance`
### Expected result

with PHP 7 compatability turned on php4 style constructors halt on deprecated under php7 compatability. 

**Deprecation messages should throw a deprecation message, and should not halt the processing of the file.**
### Actual result

Program halts on message : 
`Methods with the same name as their class will not be constructors in a future version of PHP; Cache_Lite has a deprecated constructor: in JCacheStorageTest::casesGetInstance`

**Comment by photodude** [comment]
PHP unit says this is likely an HHVM issue https://github.com/sebastianbergmann/phpunit/issues/2278#issuecomment-242958436

**Comment by aorenste** [comment]
I tried to create a small test and it seems that the deprecation message doesn't halt processing of the file:
```
<?php
class Foo {
  function Foo() { printf("in Foo::Foo\n"); }
}
$x = new Foo();
printf("After Foo()\n");
```
```
$ hhvm -d hhvm.php7.all=1 tmp.php

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; Foo has a deprecated constr$
in Foo::Foo
After Foo()
```
Am I misunderstanding the issue?

**Comment by photodude** [comment]
Perhaps it's just causing phpunit to halt and no longer to process files. It's not the same behavior that I'm seeing with php 7.

**Comment by photodude** [comment]
Here is a travis test comparison
HHVM php unit tests dies at about 13% https://travis-ci.org/photodude/joomla-cms/jobs/142317919
PHP 7 php unit tests completes https://travis-ci.org/photodude/joomla-cms/jobs/163263564

I would re-run a current test but I'm no longer able to run HHVM tests in php 7 mode due to https://github.com/facebook/hhvm/issues/7198

**Comment by photodude** [comment]
Closing as I no longer interested in HHVM.
