### ISSUE TITLE
How to enable xdebug %R trace specifier

### ISSUE THREAD

**Issue by beatscode** [facebook/hhvm#7232]
### HHVM Version

HipHop VM 3.13.1 (rel)
Compiler: tags/HHVM-3.13.1-0-g4f382ad928a6e2a0607a8dcb251002aca77f11f6
Repo schema: 655b5912cb8136e9df6f9be972153e38ac446e0f

How do I find the version of xdebug? I tried running phpinfo() but got all the xdebug settings and not the particular version. 
I'm trying to use xdebug.collect_params while auto_trace =1 but I'm getting `[Sun Jul 17 03:48:47 2016] [hphp] [1:7fbefcfff700:7:000002] [] \nFatal error: Tracing with collect_params enabled is not implemented yet.`

**Comment by beatscode** [comment]
When I var_dump $_SERVER, I get an accurate value for REQUEST_URI. How can i confirm that s_REQUEST_URI is available in the code below is there an ini setting responsible for this?

https://github.com/facebook/hhvm/blob/c9853dcf7ec783e6589c3d36d7949e6be060593b/hphp/runtime/ext/xdebug/ext_xdebug.cpp#L180
```
      // $_SERVER['REQUEST_URI']
      case 'R': {
        auto server = globals->get(s_SERVER).toArray();
        if (globals->exists(s_REQUEST_URI)) {
          const String requri(server[s_REQUEST_URI].toString(), CopyString);
          replace_special_chars(requri.get());
          buf.append(requri);
        }
        break;
```

**Comment by fredemmott** [comment]
```
        auto server = globals->get(s_SERVER).toArray();
        if (globals->exists(s_REQUEST_URI)) {
          const String requri(server[s_REQUEST_URI].toString(), CopyString);
```

`globals->exists` should probably be `server->exists`

**Comment by beatscode** [comment]
thanks @fredemmott, should I fork and submit a PR (never written or tested C++ before) or wait for the next nightly.

**Comment by fredemmott** [comment]
PR would be best; I wouldn't expect this to be in a nightly until someone says they've fixed it. I don't work on HHVM any more.

**Comment by beatscode** [comment]
Hey @fredemmott , So i'm taking a stab at this PR. It has been building for the past 6 hours. After I changed about 2 lines of code. Any suggestions on whether I'm headed on the right path? Is there a faster way to test/build the project in less time?

**Comment by Orvid** [comment]
6 hours seems a bit odd. What version of GCC are you using and how much RAM does the machine you're building on have?

**Comment by beatscode** [comment]
Not sure if i could build on my mac for linux. So I created a docker container based off ubuntu:15.10 
Here is my Dockerfile. Docker vm has 5GB of ram. I'm using a MacBook Pro (Retina, 15-inch, Mid 2015).

```
FROM ubuntu:15.10

RUN apt-get update -y
RUN apt-get -y install software-properties-common
RUN add-apt-repository ppa:george-edison55/cmake-3.x
RUN apt-get -y update
RUN apt-get install -y autoconf automake binutils-dev build-essential cmake g++ gawk git \
  libboost-dev libboost-filesystem-dev libboost-program-options-dev libboost-regex-dev \
    libboost-system-dev libboost-thread-dev libboost-context-dev libbz2-dev libc-client-dev libldap2-dev \
      libc-client2007e-dev libcap-dev libcurl4-openssl-dev libdwarf-dev libelf-dev \
        libexpat-dev libgd2-xpm-dev libgoogle-glog-dev libgoogle-perftools-dev libicu-dev \
	  libjemalloc-dev libmcrypt-dev libmemcached-dev libmysqlclient-dev libncurses-dev \
	    libonig-dev libpcre3-dev libreadline-dev libtbb-dev libtool libxml2-dev zlib1g-dev \
	      libevent-dev libmagickwand-dev libinotifytools0-dev libiconv-hook-dev libedit-dev \
	        libiberty-dev libxslt1-dev ocaml-native-compilers libsqlite3-dev libyaml-dev libgmp3-dev \
		  gperf libkrb5-dev libnotify-dev
RUN apt-get install -y cmake

VOLUME /hhvm
```

gcc --version
```
gcc (Ubuntu 5.2.1-22ubuntu2) 5.2.1 20151010
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by Orvid** [comment]
You shouldn't need the newer CMake version, but I would recommend more ram if you're trying to do a debug build. Hopefully you've assigned it more than 1 core at the very least? Building the debug package for Ubuntu 15.10 on our packaging VMs, which we give 8gb of ram and 8 cores each only takes ~1 hour. Building in release mode can take a bit longer if you've enabled both gold and the linker script, but both of those are disabled by default.

**Comment by beatscode** [comment]
I'm using docker for mac. Was able to get the build time down to 1hr 45. (Set docker vm to 8cpu cores and 11GB of ram) I'll keep messing around with the settings. Lest you think I should be using a different version of CMake? 

I changed the code https://github.com/facebook/hhvm/blob/c9853dcf7ec783e6589c3d36d7949e6be060593b/hphp/runtime/ext/xdebug/ext_xdebug.cpp#L180

```
      // $_SERVER['REQUEST_URI']
      case 'R': {
        auto server = globals->get(s_SERVER).toArray();
        if (server.exists(s_REQUEST_URI)) {
          const String requri(server[s_REQUEST_URI].toString(), CopyString);
          replace_special_chars(requri.get());
          buf.append(requri);
        }
        break;
      }

```

I replaced the custom built binary but did not see a change in the trace.xt filename. I was curious how do I debug something like this?

**Comment by apeabody** [comment]
@beatscode,

I was looking into this some today and (at least in my testing) it initially appears that globals->get(s_SERVER).toArray() isn't returning anything and the output of get_global_variables()->asArrayData(); looks strange -, although it could be *my* mock test setup (which would also be good to know).  Anyway, I would suggest this as a place to start.

**Comment by beatscode** [comment]
Here's a gist of my gdb session. I made the changes as suggested previously by @fredemmott but I wasn't able step past the server.exists clause.  
Once I'm in the block info local yields
```
server = {m_arr = {m_px = 0xa2dfd80 <HPHP::s_theEmptyArray>}}
c = 82 'R'
pos = 7
formatlen = 8
buf = {static kDefaultOutputLimit = 2146435072, static sweep = false, m_str = 0x7fe8a093c000,
  m_buffer = 0x7fe8a093c018 "/var/www/leonardo/storage/cachegrind/trace.", m_initialCap = 16, m_maxBytes = 2146435072, m_cap = 87, m_len = 43}
globals = 0x7fe8a0932060
```

Should server be populated by this time?

**Comment by apeabody** [comment]
Hi @beatscode, for this code/method to work, it certainly should.

This matches my finding that the earlier globals->get(s_SERVER).toArray() is returning nothing.  As I mentioned get_global_variables()->asArrayData(); doesn't appear to contain a valid _SERVER entry, however I haven't looked into why that might be.  I'm not familiar with how HHVM handles PHP global variables internally - especially when they (_SERVER) should be available.  I can't even say for sure if the original implementation worked, as at least in my testing the other two cases that use PHP globals exhibit the same issue.

**Comment by beatscode** [comment]
While Debugging I started looking for other instances where hhvm might be gathering global variables. Besides get_global_variables() i see php_globals_as_array() is called from
hphp/runtime/server/upload.cpp and hphp/runtime/ext/xdebug/xdebug_command.cpp.

I included
`#include "hphp/runtime/vm/globals-array.h"`
and replaced
 ```
//auto globals = get_global_variables()->asArrayData();
auto globals = php_globals_as_array();
```

Info locals yields the following

`globals = {m_arr = {m_px = 0x7ffb6cd3b040}}`

I'm not sure if there is something wrong with the way I'm trying to access globals. I would imagine it is "Somewhere" since php land gets accurate values for $_SERVER global. I don't see any other logical place where globals are being accessed.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

XDebug support was remove in hhvm version [3.27.0](https://hhvm.com/blog/2018/06/18/hhvm-3.27.0.html)
