### ISSUE TITLE
'yield' is not allowed in constructor, destructor, or magic methods

### ISSUE THREAD

**Issue by nyamsprod** [facebook/hhvm#7233]
### HHVM Version

3.9+
### Standalone code, or other way to reproduce the problem

https://3v4l.org/V29vX
### Expected result

I expect `yield` to work like with the Zend Engine
### Actual result

Fatal error: 'yield' is not allowed in constructor, destructor, or magic methods in /in/V29vX on line 8

**Comment by slaughter550** [comment]
@fredemmott is there an update on this issue? I just hit it using the aws-sdk

**Comment by fredemmott** [comment]
No update. I'll see if allowing it *just for __invoke* is straightforward; if not, it's unlikely be to be addressed.

**Comment by fredemmott** [comment]
(full PHP compatibility is no longer a goal of HHVM - see https://hhvm.com/blog/2017/09/18/the-future-of-hhvm.html )

**Comment by slaughter550** [comment]
Sounds good, thank you for the update!

**Comment by fredemmott** [comment]
Internal diff id D7961417

Seems to work with a trivial test. Might not land if it turns out to have jit implications.
