### ISSUE TITLE
No return from array_unique() with Nested arrays halts and throws array to string conversion

### ISSUE THREAD

**Issue by photodude** [facebook/hhvm#7239]
### Standalone code, or other way to reproduce the problem

No return from array_unique() with Nested arrays halts and throws array to string conversion

Happens with two nested arrays merged and made unique

 `array_unique(array_merge($this->_links, $data['links']))`

``` php
<?php
error_reporting(E_ALL);
$b = array(
  'index.php' =>
  array(
    'relation' => "Start",
    'relType'  => "rel",
    'attribs'  => array(),
  )
);
$c = array(
  'index.php' => 
  array(
    'relation' => "Start",
    'relType'  => "rel",
    'attribs'  => array(),
  )
);
$u = array_unique(array_merge($b,$c));
```

Related issue https://github.com/facebook/hhvm/issues/1561
### Expected result

Should return a new array without duplicate values ignoring internal `array to string conversion` notices from the nested arrays
### Actual result

[no array is returned, just the `array to string conversion` notice is thrown](https://travis-ci.org/photodude/joomla-cms/jobs/145968091#L1259-L1260)

**Comment by simonwelsh** [comment]
PHPUnit converts notices to exceptions, so this looks like it's working as expected. If you're not using an error handler that converts everything to exceptions, you get the array returned.

https://3v4l.org/Mcd7d

**Comment by photodude** [comment]
@simonwelsh I've looked into the information you noted on "PHPUnit converts notices to exceptions" I'm not sure I agree that is the whole issue. Based on your information I would have to assume that [my other HHVM php7 compatibility issue](https://github.com/facebook/hhvm/issues/7229) is related to "PHPUnit converts notices to exceptions", when [in testing with just PHP7](https://travis-ci.org/joomla/joomla-cms/jobs/146139507#L1250-L1254) we get the notices but tests continue. 

Seems to me that there is something more going on than just "PHPUnit converts notices to exceptions" which is causing HHVM to halt or not return values.

**Comment by aorenste** [comment]
It seems like the underlying problem is that array_unique() is complaining about an array to string conversion when it shouldn't.
https://3v4l.org/16RgR

**Comment by nikic** [comment]
@aorenste PHP is simply special-casing the `<= 1` elements case, in which case it directly returns the array. It does throw the notice for more elements: https://3v4l.org/kvaEq

**Comment by photodude** [comment]
this was my test case https://3v4l.org/OfMqV

**Comment by photodude** [comment]
Here is a test case that uses `SORT_REGULAR` as a workaround solution similar to what we implemented
https://3v4l.org/aqsrn

It seems to work for hhvm 3.15+ but causes `Uncaught exception: std::bad_alloc` on hhvm 3.14.4

**Comment by Orvid** [comment]
@photodude The hhvm 3.14.4 error is an issue with 3v4l.org's config currently. :(

**Comment by photodude** [comment]
@Orvid is the hhvm 3.14.4 config issues on 3v4l related to 3v4l enabling the hhvm php7 mode ? see this item https://3v4l.uservoice.com/forums/219058-general/suggestions/16257685-hhvm-in-php-5-mode

**Comment by photodude** [comment]
Looks like this is still an issue with HHVM 3.18.1

**Comment by photodude** [comment]
closing as per https://hhvm.com/blog/2017/09/18/the-future-of-hhvm.html
