### ISSUE TITLE
Aliasing hhvm by "php" never returns.

### ISSUE THREAD

**Issue by Klaim** [facebook/hhvm#7241]
### HHVM Version

    ╰─$ hhvm --version
    HipHop VM 3.14.2 (rel)
    Compiler: 1468002658_327003001
    Repo schema: 0fd4bacb1acae0a4a223e5bf13104ab6f79487f3

This is ArchLinux.

### Standalone code, or other way to reproduce the problem

I have `~/bin` set first in my PATH. I did:

    ╰─$ ln -s /usr/bin/hhvm php

Which is a way to solve using the scripts in php projects which use the shebang with "php".

Now I call:

    ╰─$ php

### Expected result

Like calling hhvm:

    ╰─$ hhvm
    Nothing to do. Either pass a .php file to run, or use -m server

### Actual result

No return. Needs to CTRL+C to stop it.

I am not a linux expert so I might be missing something, anyway I have no idea what is happening but maybe it's related to hhvm looking at `argc[0]`?

**Comment by simonwelsh** [comment]
This is actually working as intended. When running `php` without any arguments, it expects to be based code to run through stdin. If you're not piping into it, it sits there and waits for input.

You can see this by running:
```
echo '<?= "Hello world!\n";' | php
```

Or by running `php` then typing in `<?= "Hello world!\n";` and ending input with `CRTL+D` (may need to send it twice, depending on if you're on a newline or not).

**Comment by Klaim** [comment]
Hum then it looks like something else is wrong:

    ╰─$ echo '<?= "Hello world!\n";' | php                                                                                                                    127 ↵
    zsh: command not found: php

Is it a zsh issue?
