### ISSUE TITLE
SplFileObject::getCsvControl does not return the escape character

### ISSUE THREAD

**Issue by nyamsprod** [facebook/hhvm#7249]
`SplFileObject::setCsvControl` takes 3 parameters 
- the delimiter character
- the enclosure character
- the escape character

But the equivalent `SplFileObject::getCsvControl` returns an array with only two of those parameters. The escape character is missing.

> The same bug was also reported to PHP bug system and it is already resolved 
https://bugs.php.net/bug.php?id=72646
This bug fix will lend on the next stable version of PHP 5.6.25 and 7.0.10
The [php.net documentation was also updated accordingly](http://be2.php.net/manual/en/splfileobject.getcsvcontrol.php)

### HHVM Version

all

### Standalone code, or other way to reproduce the problem

```php
<?php

$file= new SplTempFileObject();
$file->getCsvControl();
print_r($controls);
```
### Expected result

```php
<?php
Array
(
 [0] => ,
 [1] => "
 [2] => \
)
```
### Actual result

```php
<?php
Array
(
 [0] => ,
 [1] => "
)
```

**Comment by SiebelsTim** [comment]
This seems to be very easy for anyone who wants to get their hands dirty.

https://github.com/facebook/hhvm/blob/master/hphp/system/php/spl/file_handling/SplFileObject.php#L448
