### ISSUE TITLE
Laravel's JSON responses > Numeric strings are not automatically encoded as numbers even as JSON_NUMERIC_CHECK was used

### ISSUE THREAD

**Issue by ralphstodomingo** [facebook/hhvm#7251]
### HHVM Version

HipHop VM 3.11.1 (rel)
Compiler: 3.11.1+dfsg-1ubuntu1
Repo schema: 2f678922fc70b326c82e56bedc2fc106c2faca61
### Standalone code, or other way to reproduce the problem
1. Install Laravel (tested with 5.1 and 5.2)
2. Create tbl_sample (tested using MySQL/MariaDB) with following column:
    maintenance: int(11) and add a row: 0.
3. Create model App/Sample.php: 

``` php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Sample extends Model
{
     /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'tbl_sample';
    public $timestamps = false;
}
```
1. Create resource controller App/Http/Controllers/SampleController.php:

``` php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Sample; 

class SampleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return Sample::all()->first();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}
```
1. Edit routes.php:
   Route::resource('sample', 'SampleController');
### Expected result

Using Apache/2.4.16 (Win32) OpenSSL/1.0.1p PHP/5.6.11:
![image](https://cloud.githubusercontent.com/assets/15341353/17097994/c1415224-5292-11e6-86cc-84c7187449f8.png)
### Actual result

Using HHVM in FastCGI server mode:
![image](https://cloud.githubusercontent.com/assets/15341353/17098049/ed7626bc-5292-11e6-8151-eed2c7d88706.png)

Both results were using the same database server, same database, same table.
I initially thought this was HHVM not supporting [JSON_NUMERIC_CHECK](http://php.net/manual/en/json.constants.php) constant used as option in [json_encode](http://php.net/manual/en/function.json-encode.php) (and Laravel's models use this by default: [Numeric strings to number type](https://github.com/laravel/framework/issues/138)).
But after testing this using a vanilla PHP script:

``` PHP
<?php
 $numbers = array('+123123', '-123123', '1.2e3', '0.00001');
    foreach($numbers as $number){
        var_dump(json_encode($number));
    }
```

both returned the same results. I can't think of something else that leads to such.
I was migrating an Angular app that used this Laravel backend to HHVM, and it was breaking the API that before, the API returned numeric strings from Eloquent models as numbers, and now as strings, which lead me to investigate.

**Comment by prime-ralph** [comment]
Will probably be using HTTP response interceptors in the Angular side to make the API act like before, but will be happy to see if anyone knows how to deal with this.

**Comment by simonwelsh** [comment]
When passing `JSON_NUMERIC_CHECK` to `json_encode`, the output is as expected: https://3v4l.org/ketdA

It's more likely that the query layer isn't returning raw types from the database. If Laravel uses PDO rather than MySQLi, this is likely to be the same issue as #6754.

**Comment by prime-ralph** [comment]
Whoa, found out in my database config file that it actually uses PDO.
Are there any possible workarounds?

**Comment by ArmeniaH** [comment]
Any news on this ?

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This issue applies to running php code on hhvm. Hhvm [nolonger supports running php code](https://hhvm.com/blog/2018/09/12/end-of-php-support-future-of-hack.html) since [hhvm version 4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html).

As @simonwelsh pointed out, the issue in not with `\JSON_NUMERIC_CHECK`.

I rechecked his repro and I got numeric results.
```HACK
$numbers = array('+123123', '-123123', '1.2e3', '0.00001');
foreach ($numbers as $number) {
    var_dump(json_encode(darray['id' => $number], JSON_NUMERIC_CHECK));
}
```

```
string(13) "{"id":123123}"
string(14) "{"id":-123123}"
string(11) "{"id":1200}"
string(13) "{"id":1.0e-5}"
```
