### ISSUE TITLE
hphp fails when a constant refers to a duplicated class

### ISSUE THREAD

**Issue by xJakub** [facebook/hhvm#7262]
### HHVM Version

3.12.4
### Standalone code, or other way to reproduce the problem

Just have one of your classes' constant refer to a duplicated class and have hphp build your code.
- Alfa.php:

```
<?php
class Alfa { const A = 1; }
```
- Alfa2.php:

```
<?php
class Alfa { }
```
- Beta.php:

```
<?php
require_once 'Alfa.php';
class Beta { const A = Alfa::A; }
```
### Expected result

Code is compiled without errors.
### Actual result

```
# rm fcache; hhvm --hphp -t hhbc -v AllVolatile=true --file-cache fcache -l 6 -o . -i Alfa.php -i Beta.php -i Alfa2.php --optimize-level 1
running hphp...
parsing inputs...
parsing ./Alfa.php ...
parsing ./Alfa2.php ...
parsing ./Beta.php ...
analyzeProgram...
Analyzing Includes
Analyzing All
analyzeProgram took 0'00" (37607 us) wall time
parsing inputs took 0'00" (40377 us) wall time
pre-optimizing...
saving file cache......
saving Alfa.php
saving Alfa2.php
saving Beta.php
0 MB fcache saved
saving file cache... took 0'00" (354 us) wall time
hphp failed
running hphp took 0'00" (482657 us) wall time
# echo $?
255
```

However, the code is built correctly if optimizations are disabled.

**Comment by paulbiss** [comment]
Hmm, this isn't all that surprising. We run repo mode internally against our Hack codebase, and Hack doesn't allow duplicate class names. It's probably worth fixing this, but I'm not certain there won't be other problems with hhbbc's optimizations given duplicate class names.

**Comment by xJakub** [comment]
Well, even if it is not going to be fixed, I think hhvm should at least output a better error message than "hphp failed", since it gives no hints about what caused the failure.

**Comment by paulbiss** [comment]
Agreed, I think this whole experience needs to be cleaned up. Building/optimizing a repo should be a lot easier.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This issue applies to running php code on hhvm. Hhvm [nolonger supports running php code](https://hhvm.com/blog/2018/09/12/end-of-php-support-future-of-hack.html) since [hhvm version 4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html). Hack code cannot be compiled in Repo Auth mode with duplicate class declarations, since the typechecker acts as a gatekeeper.
