### ISSUE TITLE
Memcached::getVersion PHP incompatibility

### ISSUE THREAD

**Issue by dustindoiron** [facebook/hhvm#7265]
A PHP API inconsistency was discovered in HHVM 3.12.1 surrounding the `Memcached::getVersion` command.

### HHVM Version
HipHop VM 3.12.1 (rel)
Compiler: 1456975633_498207370
Repo schema: c0420568dcd107e78ab04e13142e17663b4804c2

### Standalone code, or other way to reproduce the problem
```
$servers = [
  ['host' => '127.0.0.1', 'port' => 11211, 'weight' => 50], // this server is functional
  ['host' => '127.0.0.1', 'port' => 11212, 'weight' => 50], // this server is *NOT* functional
];
$memcached = new \Memcached();
$memcached->addServers($servers);
var_dump($memcached->getVersion());
```
### Expected result
```
array(2) {
  '127.0.0.1:11211' =>
  string(6) "1.4.17"
  '127.0.0.1:11212' =>
  string(11) "255.255.255"
}
````
### Actual result
```
(bool) false
```

**Comment by apeabody** [comment]
This actually turned out to be two issues:
1. HHVM didn't handle key based arrays for addServers()
2. The above mentioned bool(false) instead of always an array for getVersion()
