### ISSUE TITLE
Variance rules for static methods permit type violation

### ISSUE THREAD

**Issue by acrylic-origami** [facebook/hhvm#7271]
### HHVM Version

```
$ hhvm --version
HipHop VM 3.15.0-dev (rel)
```
### Standalone code, or other way to reproduce the problem

Static methods take no heed of the variance of type parameters. We can take advantage of overriding rules to break the type system by calling an overridden method with the expectation of a concrete type through the signature of the original method:

``` hack
<?hh // strict
class Base {}
class Derived extends Base {
    public function __construct(public int $v) {}
}
class Cov<+T> {
    public static function foo(T $v): void {}
}
class Concrete extends Cov<Derived> {
    <<__Override>>
    public static function foo(Derived $v): void {
        echo $v->v;
    }
}
```

— performing the violation with the following:

``` hack
class Violate {
    public static function foo(classname<Concrete> $z): void {
        self::bar($z);
    }
    public static function bar(classname<Cov<Base>> $y): void {
        $y::foo(new Base()); // Concrete::foo tries to coax an `int $v` out of Base!
                             // It's not very effective.
    }
}
```
### Expected result

```
Illegal usage of a covariant type parameter. [...] Function parameters are contravariant.
```
### Actual result

`No Errors!` from the typechecker, but `Violate::foo(Concrete::class)` produces `Notice: Undefined property: Base::$v` at runtime.

**Comment by paulbiss** [comment]
cc @andrewjkennedy this looks like something you might be interested in.

**Comment by andrewjkennedy** [comment]
Another good catch! My hunch is that statics should have the same restrictions applied as for ordinary members, because classname can be used to vary the type through which they are accessed in the same way as subtyping can be used to vary the type of the object through which a  non-static member can be invoked.

**Comment by andrewjkennedy** [comment]
Further to my above comment, I believe it is sound to permit arbitrary use of variant parameters in static *final* methods or static methods in final classes. Happy to be proved wrong on this!

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This issue has been fixed, you now get a typeerror for this situation.

```
Typing[4120] Illegal usage of a covariant type parameter
   --> src/file.hack
 10 | class Cov<+T> {
    |            ^ This is where the parameter was declared as covariant (+)
 11 |     public static function foo(T $v): void {}
    |                                ^
    |                                ^ Function parameters in non-final static functions are contravariant

1 error found.
```
