### ISSUE TITLE
json_decode refuses cr/lf in "-delimited strings

### ISSUE THREAD

**Issue by kmaslack** [facebook/hhvm#7276]
### HHVM Version

master

### Standalone code, or other way to reproduce the problem

This short program: https://gist.github.com/kmaslack/e528fc3bf2b77e1be51693415a55cdf3 successfully decodes the JSON object under most versions of Zend. It fails, returning NULL and setting json_last_error() to a syntax error, under HHVM as built by default. Configured with -DUSE_JSONC, HHVM's behavior matches that of Zend.

A digression: the JSON grammar laid out on the front page of http://www.json.org/ defines a string as a "-delimited sequence of "any UNICODE character except " or \ or control character", and yes, carriage return, linefeed, formfeed, etc. are control characters. The problem is, we at Slack, like everybody else in this day and age considering a migration away from Zend, have a legacy API to support. We have customers using this legacy API using data-at-rest that was hand-constructed, and tested, against the ubiquitous, more permissive JSON implementations. To ease the burden of switching, and reduce surprises, HHVM should probably go along with this behavior rather than narrowly reading the standard. Since JSON is an interchange format, network effects, and data-at-rest that is hard to programmatically change, forces some pragmatism.

### Expected result
array(1) {
  ["5.6.99-hhvm"]=>
  array(1) {
    ["a"]=>
    string(1) "
"
  }
}
### Actual result
array(1) {
  ["5.6.99-hhvm"]=>NULL
}

**Comment by nikic** [comment]
To clarify, the program will *not* successfully decode the JSON object under *any* version of PHP. Decoding only works if you use the non-standard jsonc extension, which is well-known to be non-conforming in many respects.

**Comment by Orvid** [comment]
https://3v4l.org/hV1hW

As said above, PHP doesn't, by default allow this.

**Comment by kmaslack** [comment]
_Any_ seems a little aggressive. The version of PHP we've been using in production _does_ allow this out of the box, producing the output:

```
  '5.5.9-1ubuntu4.19' =>
  array(1) {
    'a' =>
    string(1) "
"
  }
}
```

I remember being fuzzy on this when I used to work at FB, but I assure you this "ubuntu" thing is popular! A lot of the audience of people considering migrating to HHVM are doing so from it.

Taking a step back, if you choose not to allow this, potential HHVM users like me need to maintain a patch that does allow it in perpetuity, because our paying customers have data-at-rest that they will not change no matter how firmly I assure them that our json_decode adheres to the spec. I could continue in this vein, but it's all pretty much just Postel's Law. It's also why Python's json.load has made the decision to allow this as well.

**Comment by kmaslack** [comment]
By the way, I'm perfectly happy to continue building against json-c if that's the preferred story here, assuming patches to actually fix that build remain welcome.

**Comment by simonwelsh** [comment]
JSON.parse also won't parse the string as javascript strings can't contain literal newlines. This seems more like jsonc being incompatible with JSON rather than an HHVM issue.

**Comment by paulbiss** [comment]
If the json-c build is broken we should definitely fix that. It sounds to me as though the ubuntu packages behave this way because they're also built against json-c.
