### ISSUE TITLE
Modifying an array with square bracket syntax results in Fatal error

### ISSUE THREAD

**Issue by photodude** [facebook/hhvm#7277]
I am getting the following error `Fatal error: [] operator not supported for strings in /libraries/joomla/cache/storage/memcache.php on line 194`

This is happening when Modifying an array with square bracket syntax array by omitting the key value with an empty pair of brackets ([]).

See this reference on [Creating/modifying with square bracket syntax](http://php.net/manual/en/language.types.array.php#language.types.array.syntax.modifying)

### HHVM Version 
- 3.12.7
- 3.14.4

### Standalone code, or other way to reproduce the problem
```php
		$tmparr       = new stdClass;
		$tmparr->name = $cache_id;
		$tmparr->size = strlen($data);
		$index[] = $tmparr;
```

above is a code snip from  [/libraries/joomla/cache/storage/memcache.php](https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/cache/storage/memcache.php)

### Expected result
The value should be added to the end of the array and a new key will be created that is maximum value plus 1 (but at least 0).

### Actual result
`Fatal error: [] operator not supported for strings in /libraries/joomla/cache/storage/memcache.php on line 194`

**Comment by paulbiss** [comment]
Hmm, my best guess is that something else must be happening. If array append was broken it's unlikely anything at all would work on hhvm.

Based on the error message `$index` is actually a string when the error gets triggered. I don't know anything about joomla but it doesn't sound like an hhvm bug.

See: https://3v4l.org/Fj6tK

**Comment by photodude** [comment]
From what I can tell from our code... MEMCACHE in HHVM is returning a string rather than an array or false from the following line. 

```php 
$index = static::$_db->get($this->_hash . '-index');
```

**Comment by paulbiss** [comment]
That sounds like the correct behavior. Memcache::get returns a string unless it was passed an array of keys.

http://php.net/manual/en/memcache.get.php

**Comment by photodude** [comment]
I think there maybe a documentation error in the [php `Memcache::get()` manual](http://php.net/manual/en/memcache.get.php)

In testing, I think it should say something like the following
>Memcache::get returns previously stored data of an item if such key exists on the server at this moment
Return Values 
Returns the value associated with the key, or an array of found key-value pairs when key is an array. Returns FALSE on failure, key is not found or key is an empty array.

in other words

`Memcache::get(key)` | Return description | return Types
------------ | ------------- | -------------
string key - `Memcache::get('a1')` | value associated with the key | string, or array
array keys- `Memcache::get(array(a1,a2))` | found key-value pairs | array
not found - `Memcache::get(array(b1,b2))` | not found or other failure | boolean `false`

you can check this in the following for ($m - an instance of memcache):
```php
$m->set('a', 'a1');
$m->set('b', 'b1');
$m->get(array('a', 'b')); // this return array
$m->get('b'); // this return string
```
but
```php
$m->set('x', array('a', 'b'));
$m->get('x'); // this return array
```

so `memcache::get` might return an array for a single key if the key value was an array.

**Comment by photodude** [comment]
Closing as correct behavior.

There is a very specific set of circumstances in our unit test that resulted in the failure. Basically, some data was being truncated and left floating in the cache, This junk data and was getting picked up and passed as valid data from the specific key checking the cache. 

We have corrected that situation and believe no further action is needed.
