### ISSUE TITLE
Assert failures when running OSS wordpress benchmark on ARM64

### ISSUE THREAD

**Issue by sunil-sk** [facebook/hhvm#7282]
### HHVM Version
All
### Standalone code, or other way to reproduce the problem
OSS wordpress on ARM64 consitently fails assert due to corrupted FreeStubList.
Does not show up on X64 but seems to be a potential bug.
### Expected result
Successful run of wordpress benchmark.
### Actual result
Assert failure in MCGenerator::getFreeStub()

### Potential Problem
In hphp/runtime/vm/jit/service-requests.cpp:emit_svcreq(), after emitting a re-usable stub, enough space must be reserved in the code-block to avoid potential memory corruption when this stub is reused to emit code of size larger than the original stub. Stub reuse code assumes that all stubs are of fixed size.

### Possible Solution
When emiting a reusable stub for the first time, skip enough bytes in the code-block to accomodate the maximum sized stub. Below patch fixes the crash on ARM64.
```
diff --git a/hphp/runtime/vm/jit/service-requests.cpp b/hphp/runtime/vm/jit/service-requests.cpp
index ab5cd32..45b13f7 100644
--- a/hphp/runtime/vm/jit/service-requests.cpp
+++ b/hphp/runtime/vm/jit/service-requests.cpp
@@ -133,7 +133,12 @@ void emit_svcreq(CodeBlock& cb,
     vasm.unit().padding = !persist;
   }

-  if (!is_reused) cb.skip(stub.used());
+  if (!is_reused) {
+    if (persist)
+      cb.skip(stub.used());
+    else
+      cb.skip(stub_size());
+  }
 }
```

**Comment by mxw** [comment]
This is because the implementation of `pad()` in `vasm-arm.cpp` is obviously broken—it's a no-op, and it needs to not be a no-op if you want this to work.

Why not submit a PR?

**Comment by sunil-sk** [comment]
Thanks, I will submit a PR.

**Comment by sunil-sk** [comment]
Pull Request:
https://github.com/facebook/hhvm/pull/7304
