### ISSUE TITLE
centos7 cmake3 error

### ISSUE THREAD

**Issue by rich2016** [facebook/hhvm#7287]
...................................
-- Building the shmop extension.
-- Building the simplexml extension.
-- Building the soap extension.
-- Building the sockets extension.
-- Building the spl extension.
-- Building the sqlite3 extension.
-- Building the std extension.
-- Building the stream extension.
-- Building the string extension.
-- Building the thread extension.
-- Building the thrift extension.
-- Building the url extension.
-- Building the wddx extension.
-- Building the xdebug extension.
-- Building the xenon extension.
-- Building the xhprof extension.
-- Building the xml extension.
-- Building the xmlreader extension.
-- Building the xmlwriter extension.
-- Found LibXslt: /usr/lib64/libxslt.so (found version "1.1.28") 
-- Building the xsl extension.
-- Building the zip extension.
-- Building the zlib extension.
-- Found LibYaml: /usr/lib64/libyaml.so  
-- Found LibNuma: /usr/lib64/libnuma.so  
-- Found gold: /usr/bin/ld.gold
-- Performing Test NOT_REQUIRE_ATOMIC_LINKER_FLAG
-- Performing Test NOT_REQUIRE_ATOMIC_LINKER_FLAG - Success
CMake Warning (dev) at CMake/HPHPFunctions.cmake:199 (get_target_property):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "hhvm".  Use the
  target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

Call Stack (most recent call first):
  hphp/hhvm/CMakeLists.txt:81 (HHVM_INSTALL)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/hhvm

when I do it  as https://github.com/facebook/hhvm/wiki/Building-and-installing-hhvm-on-CentOS-7.x
I meet an error like The LOCATION property should not be read from target "hhvm"
I don't know how to solve it,who can help me ? Thanks very much

**Comment by Orvid** [comment]
As it says, that's a warning, not an error. Ignore it.
