### ISSUE TITLE
aarch64-centos7 error

### ISSUE THREAD

**Issue by JohnGW05** [facebook/hhvm#7291]
### HHVM Version

3.15
### Standalone code, or other way to reproduce the problem

./configure
### Expected result

produce makefile
### Actual result

I’m working on run hhvm in aarch64-centos7, and now when I run ./configure ,the terminal prints information as follows:
-- Building the xmlwriter extension.
-- Building the xsl extension.
-- Building the zip extension.
-- Building the zlib extension.
-- Configuring incomplete, errors occurred!
See also "/home/gongwei05/hhvm/CMakeFiles/CMakeOutput.log".
See also "/home/gongwei05/hhvm/CMakeFiles/CMakeError.log".
and the CMakeError.log print these information:
Performing C++ SOURCE FILE Test IS_X64 failed with the following output:
Change Dir: /home/gongwei05/hhvm/CMakeFiles/CMakeTmp

Run Build Command:"/bin/gmake" "cmTC_f4e93/fast"
/bin/gmake -f CMakeFiles/cmTC_f4e93.dir/build.make CMakeFiles/cmTC_f4e93.dir/build
gmake[1]: Entering directory `/home/gongwei05/hhvm/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_f4e93.dir/src.cxx.o
/bin/c++     -DIS_X64   -o CMakeFiles/cmTC_f4e93.dir/src.cxx.o -c /home/gongwei05/hhvm/CMakeFiles/CMakeTmp/src.cxx
/home/gongwei05/hhvm/CMakeFiles/CMakeTmp/src.cxx:3:2: error: #error Not x64
 #error Not x64
  ^
gmake[1]: **\* [CMakeFiles/cmTC_f4e93.dir/src.cxx.o] Error 1

**Comment by paulbiss** [comment]
Hmm, I've not seen that failure before, but that src file is supposed to fail to build. I'm not sure why it stopped the cmake from continuing.

https://github.com/facebook/hhvm/blob/c3876687e1ec21280441ece448c5f45eeb91713e/CMake/HPHPSetup.cmake#L9

**Comment by cmuellnerTheobromaSystems** [comment]
I've just tested and can confirm, that the branches HHVM-3.15 and master successfully build on aarch64/CentOS 7.  Are there other errors in CMakeOutput.log or CMakeError.log?

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

CentOS is not a support distribution for running hhvm. I am closing this issue, assuming you've moved on.

If you haven't, or anyone else is trying to get a CentOS build going, please open a new issue. Please note that this build will have to be community supported.
