### ISSUE TITLE
Please add release notes for each version.

### ISSUE THREAD

**Issue by netroby** [facebook/hhvm#7295]
What's the different with 3.12 lts branch and 3.14 branch. 
What's changed. and what's not changed.

There no details . no release logs. please add more details about each released version.

Thanks

**Comment by paulbiss** [comment]
There were 1119 commits which touched 4525 files between those two versions (https://github.com/facebook/hhvm/compare/HHVM-3.12...HHVM-3.14). It's safe to say there were a great many changes. We gave up trying to summarize all of the changes sometime ago. @simonwelsh has made some attempt to track changes on a week to week basis [here](https://coding.simon.geek.nz/).

**Comment by netroby** [comment]
Every open source project should have release notes. I am not saying let you compare two large version.
but what about 3.12.1- 3.12.2

**Comment by netroby** [comment]
I like VisualStudio code . It has a good release notes.

http://code.visualstudio.com/Updates

**Comment by paulbiss** [comment]
We're going to resume posting updates about major versions, which should provide some of that detail. Nearly all point releases are only a handful of predominantly security related commits, the log should be more than sufficient to figure out what happened there.

There's a lot of churn in this repo though as the project is quite active, so I wouldn't expect to find comprehensive notes anywhere other than the commit logs.  We're putting together 3.15 right now and I will make sure there is a blog post to accompany it.
