### ISSUE TITLE
HHVM is unable to execute '/usr/bin/hh_client' - fails with Invalid operand type was used: implode() expects a container as one of the arguments

### ISSUE THREAD

**Issue by jimfb** [facebook/hhvm#7309]
### HHVM Version

HipHop VM 3.14.4 (rel)
Compiler: tags/HHVM-3.14.4-0-gcee2aedf82cffa3f4959adf9e0409c9ec7b314cb
Repo schema: c6d3b7c365d7be3fe41c697542afe0a1b1802987
Operating system: Linux ip-10-229-4-143 4.2.0-42-generic #49-Ubuntu SMP Tue Jun 28 21:26:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
### Bug

After a while, launching HHVM gives me this cryptic error:

```
Warning: Unable to execute ''/usr/bin/hh_client' --timeout 5 --retries 0 --json '/home/ubuntu/php' 2>&1'

Warning: Invalid operand type was used: implode() expects a container as one of the arguments

Catchable fatal error: 
```

Observed on a standard/fresh install of ubuntu, standard OSS debs.  The machine was installed and turned on for the sole purpose of running hhvm.

The first time I witnessed this bug, it would occur 50% of the time that I executed HHVM programmatically and 0% when executed from an interactive shell.  This initially lead me to wonder if it was an environment variable issue.  A day later (no changes), it failed 100% of the time, regardless of the environment (programmatically or shell).  Rebooting the machine resolved the issue.

The problem kept recurring every couple of days.  The machine is working, then goes into a "bad" state (HHVM is unable to launch, failing with the above message).  Rebooting consistently solves the problem.

I'm fairly certain it is not a permissions issue, since that wouldn't result in the inconsistent behavior described above.  Permissions on /usr/bin/hh_client are: "-rwxr-xr-x 1 root root 4192776 Aug 2 02:25 /usr/bin/hh_client". As far as I know, there is no application security policy (ie. I have not configured AppArmor/SELinux).

The only "odd" thing I do with my server... I have a unit test suite that hits the server.  The unit test suite invokes hhvm ~15 times (generally serially/synchronously) in rapid succession.  Total hhvm invocation count is probably a couple hundred times per day.  This, combine with the fact that it appears to become a problem over time, leads me to believe there is some sort of race condition or resource leak that is causing a latent hhvm bug to show its self.

Josh Watzman (@jwatzman) suggested disabling the typechecker (via ini configuration) and running hh_client manually.  That worked beautifully, and this problem is no longer affecting my workflow.  Still, something seems wrong with HHVM, so it's probably worth investigating the issue at some point.

I tried to reproduce the relevant comments here.  Internal facebook people can view the original conversation here: https://www.facebook.com/groups/hhvm.oss/permalink/1125569694158311/

**Comment by aorenste** [comment]
There's no stack trace after the 'Catchable fatal error:' part?

**Comment by jimfb** [comment]
@aorenste Correct, no trace.

**Comment by mcsharma1990** [comment]
I am also experiencing this.

**Comment by jwatzman** [comment]
For anyone else hitting this, the INI option is `hhvm.hack.lang.auto_typecheck` -- please don't turn that off if you aren't hitting this problem though.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

The behavior `hhvm.hack.lang.look_for_typechecker` has been disabled for a long while. This setting appears to have superceded the auto_typecheck setting. This behavior was enabled by default and worked in 3.21. (The version of hhvm that shipped with my old Ubuntu install.)

Cc. The setting you mention does not appear on the documentation page.
