### ISSUE TITLE
  rtrim() doesn't work properly

### ISSUE THREAD

**Issue by donutloop** [facebook/hhvm#7310]
HipHop VM 3.15.0-dev (rel)
Compiler: heads/master-0-g1ba4d437a6c089d38a45f6116f166f57ac2e0703
Repo schema: 0be2fa54a27f9d56a3ee99cb13d075fcaecb0610

Composer Version: 1.2.0

i try to execute "hhvm -php composer.phar install"

 [ErrorException]                                      
  rtrim() expects parameter 1 to be string, null given

**Comment by DerPapst** [comment]
#7198 seems to be the same.
