### ISSUE TITLE
php compatibility: mb_strrpos()

### ISSUE THREAD

**Issue by voku** [facebook/hhvm#7318]
### HHVM Version
tested: hhvm-3.10.0 - 3.12.0

### Standalone code, or other way to reproduce the problem
```php
echo mb_strrpos('한국어', '국', 0, '8bit');
```
https://3v4l.org/2H3Lg

### Expected result
3

### Actual result
1

**Comment by aorenste** [comment]
A slightly more portable version of the example:

```
<?php
$b = html_entity_decode('&#xAD6D;', ENT_COMPAT, 'UTF-8');
$a = html_entity_decode('&#xD55C;&#xAD6D;&#xC5B4;', ENT_COMPAT, 'UTF-8');
echo mb_strrpos($a, $b, 0, '8bit');
```
