### ISSUE TITLE
Uncaught exception: Could not open extension ./pgsql.so

### ISSUE THREAD

**Issue by photodude** [facebook/hhvm#7321]
### HHVM Version
3.15
### Standalone code, or other way to reproduce the problem
hhvm.dynamic_extensions[pgsql] = pgsql.so
### Expected result
use of the included pgsql.so extension
### Actual result
`Uncaught exception: Could not open extension ./pgsql.so: ./pgsql.so: cannot open shared object file: No such file or directory`

See travis ci build https://travis-ci.org/photodude/joomla-cms/jobs/158452122

Note: documentation is out of date on how to use the included pgsql.so extension and is still linking to the PocketRent/hhvm-pgsql page 

cc// @simonwelsh

**Comment by photodude** [comment]
[Documentation for installed extensions](https://docs.hhvm.com/hhvm/extensions/introduction) should show the following as of 3.15.0
- apc
- array
- asio
- async_mysql
- bcmath
- bz2
- collections
- ctype
- curl
- date
- debugger
- dom
- domdocument
- enum
- exif
- fb
- fileinfo
- filter
- gd
- generator
- gettext
- gmp
- hash
- heapgraph
- hh
- hh_client
- hhvm.debugger
- hhvm.ini
- hosthealthmonitor
- hotprofiler
- iconv
- idn
- imagick
- imap
- intervaltimer
- intl
- json
- ldap
- libxml
- mail
- mailparse
- mbstring
- mcrouter
- mcrypt
- memcache
- memcached
- mysql
- mysqli
- objprof
- openssl
- password
- pcntl
- pcre
- pdo
- pdo_mysql
- pdo_pgsql
- pdo_sqlite
- pgsql
- phar
- posix
- random
- readline
- redis
- reflection
- scrypt
- server
- session
- shmop
- simplexml
- soap
- sockets
- spl
- sqlite3
- standard
- stream
- string
- sysvmsg
- sysvsem
- sysvshm
- thread
- thrift_protocol
- tokenizer
- url
- wddx
- xenon
- xhprof
- xml
- xmlreader
- xmlwriter
- xsl
- zip
- zlib

Note: pgsql.so should no longer be listed under hhvm.dynamic_extensions

**Comment by photodude** [comment]
Documentation issue opened https://github.com/hhvm/user-documentation/issues/365

**Comment by Orvid** [comment]
The issue here is that pgsql is included as a build-in extension rather than a dynamic extension, so listing it in the `dynamic_extensions` section is expected to fail. The documentation issue does still need to be addressed though.
