### ISSUE TITLE
How to disable HHVM's memory manager?

### ISSUE THREAD

**Issue by trylab** [facebook/hhvm#7322]
I 'd like to try the system's default memory manager. Could you please tell me how to disable HHVM's memory manager? I can build HHVM from source.

**Comment by Orvid** [comment]
We don't currently support this, and have no plans to support it, but if you *really* want to try it (I wouldn't recommend it), you can probably replace bits of the allocator `hphp/util/alloc.h` and `hphp/util/alloc.cpp`.

**Comment by paulbiss** [comment]
If you're talking about the request memory allocator you can set `hhvm.disable_small_allocator` to disable slab allocation and have all request allocations pass through `malloc`.
