### ISSUE TITLE
PHP7 mode issue with composer dependency installs

### ISSUE THREAD

**Issue by photodude** [facebook/hhvm#7323]
### HHVM Version
3.15 **with PHP 7 mode fully enabled**
### Standalone code, or other way to reproduce the problem
install dependencies with composer via `composer install`
### Expected result
composer works the same way that it does in HHVM php 5 mode
### Actual result
```php
[ErrorException] rtrim() expects parameter 1 to be string, null given
```
The specifics of what `rtrim()` should have received that resulted in null being passed are unknown, as the error did not identify what line caused the failure. Based on where the travis build failed is how I extrapolated that the issue is related to something composer was expecting to be passed to `rtrim()` during the `composer install`.

IMO this is not a composer issue but an issue caused by something HHVM is doing differently with PHP 7 mode fully enabled.

Travis build https://travis-ci.org/photodude/joomla-cms/jobs/158463036

Possibly related to another HHVM composer issue with HHVM3.14 in this travis build https://travis-ci.org/photodude/joomla-cms/jobs/157488284
```php
Fatal error: Uncaught TypeError: Argument 1 passed to unserialize() must be an instance of string, null given in /home/travis/.phpenv/versions/hhvm-stable/bin/composer:23
Stack trace:
#0 (): unserialize()
#1 (): __SystemLib\PharArchiveHandler->parsePhar()
#2 (): __SystemLib\PharArchiveHandler->__construct()
#3 (): Phar->__construct()
#4 /home/travis/.phpenv/versions/hhvm-stable/bin/composer(23): Phar::mapPhar()
#5 {main}
```

Seems something in HHVM **with PHP 7 mode fully enabled** is causing a lot of functions to receive null for input.

**Comment by aorenste** [comment]
It's also possible that these functions have always passed null to rtrim() but in php 7 more we're being more strict.

**Comment by photodude** [comment]
@aorenste I don't think `rtrim()` and `unserialize()` take null as parameters in any version of PHP. Technically `rtrim()` and `unserialize()` are not the issue, it's the function(s) being passed as a parameter.

Basically, there is a function(s) being passed to `rtrim()` and `unserialize()` whose return is `null`. These other functions that are returning `null` are the issue. Unfortunately, because it's a travis build I'm not sure the details on what specific function is being passed to  `rtrim()` and `unserialize()` in composer that should be returning a `string` but instead is returning `null`

Although in https://github.com/facebook/hhvm/issues/7306 that's a different story. Null is a valid  parameter, but is getting rejected.

**Comment by donutloop** [comment]
https://github.com/facebook/hhvm/issues/7310

**Comment by aorenste** [comment]
If I run this script:
```
<?php
printf("'%s'\n", rtrim(null));
```

In php 5, php 7 or normally under hhvm I get:
```
''
```

But if I run hhvm in php7 mode I get:
```
$ hhvm -d hhvm.php7.all=1 tmp.php

Warning: rtrim() expects parameter 1 to be string, null given in /home/aorenste/tmp/tmp.php on line 2
''
```

**Comment by Orvid** [comment]
@aorenste HHVM's PHP7 mode needs to be adjusted so that strict types aren't enabled by default (they aren't in PHP)

**Comment by aorenste** [comment]
Marking as a dup of #7198

**Comment by photodude** [comment]
Thanks I'll follow #7198
