### ISSUE TITLE
Recently, it was found that there was a process of suicide

### ISSUE THREAD

**Issue by MrPack** [facebook/hhvm#7324]
### HHVM Version
3.9

_Recently, it was found that there was a process of suicide._Do you have similar problems？

**Comment by aorenste** [comment]
Could you please explain what you mean in more detail?  Do you mean the HHVM process is killing itself?  Have you looked in the logs?

**Comment by MrPack** [comment]
Thank you very much! I don't have any problems after the re deployment. I‘ll close this issues.
