### ISSUE TITLE
Segfault in creating then modifying an array of 278036506 elements

### ISSUE THREAD

**Issue by photodude** [facebook/hhvm#7331]
### HHVM Version

3.15 
memory limit 16.384 GB
### Standalone code, or other way to reproduce the problem

Test [based on this script](https://books.google.com/books?id=G_djDAAAQBAJ&pg=PA212&dq=memory_get_peak_usage%28%29&hl=en&sa=X&ved=0ahUKEwj26dWb6PvOAhVI2mMKHYcTCWwQ6AEIKzAC#v=onepage&q=memory_get_peak_usage%28%29&f=false)

``` php
<?php
$var1 = array();
$prePop = 278036506;
for ($i = 0; $i < $prePop; $i++)
{
    $var1[] = "this is a short string";
}
$r = 0;
for ($i = 0; $i < PHP_INT_MAX - 10000; $i++)
{
    $var1[] = "this is a short string";
    $e = $prePop + $i;
    if ($i = $r + 1000)
    {
        echo "Memory usage for $e elements = " . memory_get_usage() / 1048576 . " MB\n";
        $r = $i;
        echo "Maximum Memory usage at $e elements is = " . memory_get_peak_usage(true) / 1048576 . " MB\n";
    }
}
```
### Expected result

array created and modified until memory limit is hit
See travis build with $prePop = 268036506;
https://s3.amazonaws.com/archive.travis-ci.org/jobs/159038741/log.txt
(log errors out at 363289507 elements)
### Actual result

Segfault in creating array
see travis built
https://travis-ci.org/photodude/HHVM_memory_test/jobs/159038060
### Note about test

This was created to do some HHVM memory testing on travis ci with the intent of the test crashing at some memory limit. Basically attempting programmatically reproduce the error from https://github.com/facebook/hhvm/issues/7035 did not expect that I would hit a segfault from creating then modifying an array of 278036506 elements 
I can create a smaller array of just  268036506 elements and modify it far beyond 6,200,468,036,507 elements.

**Comment by photodude** [comment]
Note: in modifying an array a segfault happens between 9200000000268036507 elements and 9300000000268036507 elements

**Comment by aorenste** [comment]
Using the latest dev build (so not exactly the same condition) I get the following:
```
$ ./buck-out/gen/hphp/hhvm/hhvm/hhvm --php tmp.php
Memory usage for 67036505 elements = 1028 MB
Maximum Memory usage at 67036505 elements is = 1536.333190918 MB

Fatal error: request has exceeded memory limit in /data/users/aorenste/fbsource/fbcode/tmp.php on line 9
```

**Comment by photodude** [comment]
@aorenste that is closer to what I would have expected. no segfault and `Fatal error: request has exceeded memory limit`

So it looks like both of the segfaults reported maybe fixed in dev.
Although I'm apparently testing on travis ci default settings with about 6 times the memory limit that you are. `Memory: 6160.46MB`

For your smaller memory limit, I would expect that the `$prePop` would need to be something like `66036505` to cause the same issue.

**Comment by aorenste** [comment]
I started prepop at `67036000` or so to get the error on line 9.

**Comment by photodude** [comment]
when you started prepop at 67036000 or so to get the error on line 9; Did you get any output before it maxed out with 67036505 elements or did it fail on the first iteration?

**Comment by aorenste** [comment]
I got a lot of output.

**Comment by photodude** [comment]
That's what I would expect, lots of output until the memory limit is reached. So either the issue is fixed in dev or the issue is something that only shows up with the larger memory limit.

**Comment by photodude** [comment]
Closing as I no longer interested in HHVM.
