### ISSUE TITLE
v3.14.* of hhvm is no longer available in debian repos

### ISSUE THREAD

**Issue by dotboris** [facebook/hhvm#7332]
I have HHVM v3.14.4 deployed in production. I want to configure development environments that match prod as much as possible. To do so I want to install hhvm v3.14.* to my dev setup. I tried to install hhvm like so:

```sh
apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0x5a16e7281be7a449
echo deb http://dl.hhvm.com/debian jessie main > /etc/apt/sources.list.d/hhvm.list
apt-get update
apt-get install "hhvm=3.14.*"
```

When doing so, aptitude complains that it can't find v3.14.*:

```
E: Version '3.14.*' for 'hhvm' was not found
```

I've done some digging in the repo and I find that there is a deb package is present for v3.14.* but no repo is actually referencing it.

It seems like old versions are removed from the repos. 

Why is that?

How could I get an old versions installed if the old versions are removed?

**Comment by simonwelsh** [comment]
Because they're no longer supported, so are potentially unsafe to use.

You can download the `.deb` file and install it manually using `dpkg -i`.

**Comment by DemiMarie** [comment]
@dotboris you should upgrade the version of HHVM used in production, or use one of the long-term support (LTS) versions.
