### ISSUE TITLE
How to enable snappy_compression in HHVM 3.15

### ISSUE THREAD

**Issue by jasonromando** [facebook/hhvm#7335]
### HHVM Version - 3.15

I tried apt-get install and build from source.

I double confirm I installed libsnappy-dev, libsnappy1 & snappy.

I wanna use to compress the object and save memory caching.

Thanks!

**Comment by aorenste** [comment]
Unfortunately HHVM does not currently support the snappy extension.  Please see https://docs.hhvm.com/hhvm/extensions/introduction for a list of supported extensions.

**Comment by Orvid** [comment]
@aorenste We actually do have some support for it, it's just in hiding and is currently disabled in the OSS build. It's one of the things I intend to look at enabling for 3.16.

**Comment by jasonromando** [comment]
@Orvid Can i enable it in build from source, i tried but fail.
