### ISSUE TITLE
3.14.5 Source version fails to build on OSX

### ISSUE THREAD

**Issue by peterhal** [facebook/hhvm#7338]
### HHVM Version
3.14.5

### Standalone code, or other way to reproduce the problem

Following instructions here: https://docs.hhvm.com/hhvm/installation/building-from-source
With source downloaded from the brew tap here: http://dl.hhvm.com/source/hhvm-3.14.5.tar.bz2

### Expected result

Successful build.

### Actual result

Several errors relating to -Wc++14-extensions:

/Users/peterhal/brew/hhvm/src/hhvm-3.14.5/third-party/folly/folly/ThreadLocal.h:205:21: warning: initialized lambda
      captures are a C++14 extension [-Wc++14-extensions]
    auto deleter = [delegate = source.get_deleter()](

**Comment by paulbiss** [comment]
That's a warning, are there errors elsewhere in your output?

**Comment by aorenste** [comment]
This issue has been waiting for more info for more than 2 weeks. I'm closing it for now, but feel free to re-open it if you can provide more info. https://github.com/facebook/hhvm/wiki/Human-Timeouts
