### ISSUE TITLE
Hack type error: This equality test has incompatible types (enum)

### ISSUE THREAD

**Issue by wake-up-neo** [facebook/hhvm#7340]
### HHVM Version

> HipHop VM 3.15.0 (rel)
> Compiler: tags/HHVM-3.15.0-0-g92a682ebaa3c85b84857852d8621f528607fe27d
> Repo schema: 225d4323575bbc8a498dc809a1c41354f6bca830

### Standalone code, or other way to reproduce the problem
```
<?hh

enum IntEnumType: int {
	STATUS_ONE = 1;
	STATUS_TWO = 2;
	STATUS_THREE =  3;
};

enum IntEnumType2: int {
	STATUS_ONE = 1;
	STATUS_TWO = 2;
	STATUS_THREE =  3;
};


class Foo {
    public static function bar():void {
        if (IntEnumType::STATUS_ONE === IntEnumType2::STATUS_TWO) {
            echo 'ok';
        }
    }
}

foo::bar();
```

### Expected result

> No errors

### Actual result

> Catchable fatal error: Hack type error: This equality test has incompatible types at *** line 18

There was no issue before 3.15.
Should this be considered as a normal typechecker behaviour?

p.s.
However (int) casting for one of the sides removes an error.
`if ((int) IntEnumType::STATUS_ONE === IntEnumType2::STATUS_TWO) {`

**Comment by aorenste** [comment]
Is your question about the initial error or about the fact that casting one side to `int` fixes it (or both)?

**Comment by wake-up-neo** [comment]
the first one

**Comment by aorenste** [comment]
I'm pretty sure the new typechecker behavior is correct - you're comparing two enums which are unrelated.

**Comment by wake-up-neo** [comment]
hmm... I'm comparing values of enums which are both int but not enums itself. In case you are right where is hh_client error? @jwatzman

**Comment by aorenste** [comment]
You're comparing enums which both have the underlying type of `int` - they are not `int`.

From the [hack docs](https://docs.hhvm.com/hack/enums/introduction#casting-to-underlying-type):

> While enums have underlying types, they are not interchangeable. The enum is a distinct type.

If you actually want to treat them as `int` then you probably want to have them implicitly cast to `int` by declaring the enums as:

```
enum IntEnumType: int as int { ...
enum IntEnumType2: int as int { ...
```

Then the comparison passes.


When I run hh_single_type_check on that example I get:
```
File "tmp.php", line 18, characters 9-60:
This equality test has incompatible types (Typing[4157])
File "tmp.php", line 3, characters 19-21:
This is a value of enum IntEnumType
File "tmp.php", line 9, characters 20-22:
This is a value of enum IntEnumType2
```

**Comment by wake-up-neo** [comment]
@aorenste Thanks Aaron, it's clear now
