### ISSUE TITLE
ini_set doesn't support xdebug.enable or return false on hhvm.php7.all

### ISSUE THREAD

**Issue by photodude** [facebook/hhvm#7344]
### HHVM Version

3.15.0
### Standalone code, or other way to reproduce the problem

`hhvm --php -r 'ini_set("hhvm.php7.all", 1);'`
`hhvm --php -r 'ini_set("xdebug.enable", 1);'`
### Expected result

Return `false` as you cannot set ini with hhvm.php7.all = 1 at runtime
set ini with xdebug.enable = 1
### Actual result

no change in ini settings
travis build failed to set INI to php7 mode and thus did not fail due to https://github.com/facebook/hhvm/issues/7198
https://travis-ci.org/photodude/joomla-cms/jobs/159666919

Composer didn't complain about xdebug being enabled showing that it was not set with ini_set
https://travis-ci.org/photodude/joomla-cms/jobs/159666914
### command that does set ini vars

This will add a variable and setting to the ini, but can/will cause variable duplications in the ini
`echo hhvm.php7.all=1 >> /etc/hhvm/php.ini`
travis build that shows a correctly set ini (with php 7 mode enabled it fails due to https://github.com/facebook/hhvm/issues/7198 )
https://travis-ci.org/photodude/joomla-cms/jobs/159046458

I assume `echo xdebug.enable=1 >> /etc/hhvm/php.ini` will work to set xdebug but i haven't tested it

**Comment by paulbiss** [comment]
You definitely can't change `hhvm.php7.all` at runtime it has to be known prior to execution starting. The same is true of `xdebug.enable` (though it might be possible to lift that restriction).

**Comment by photodude** [comment]
Thanks, @paulbiss 

Being that "You definitely can't change `hhvm.php7.all` at runtime" I would have expected some kind of notice or message telling me that. Instead, HHVM seems to just carry on as though you didn't even attempt to change `hhvm.php7.all` with `ini_set()` it also didn't seem to return false as the [php manual on `ini_set()`](http://php.net/manual/en/function.ini-set.php) indicates it should (travis ci fails a build if a line returns false)

[Documentation for the ini values](https://docs.hhvm.com/hhvm/configuration/INI-settings) should [follow the PHP manual](http://php.net/manual/en/ini.list.php) and should be updated to indicate [the changeable status](http://php.net/manual/en/configuration.changes.modes.php). (documentation change filed with the documentation repository https://github.com/hhvm/user-documentation/issues/367) 

Based on the [the PHP manual](http://php.net/manual/en/ini.list.php) it would seem that `xdebug.enable` should have a changeable status of  `PHP_INI_ALL` Entry can be set anywhere

**Comment by paulbiss** [comment]
@photodude fixing the return behavior and adding xdebug support sounds reasonable. I haven't looked at how hard it would be to support xdebug.enable, it may not be a simple change.

**Comment by photodude** [comment]
I think the return behavior might be correct, but Travis ci might be failing to catch it. I tested 3.12 https://3v4l.org/PBMUl#version=hhvm-3.12.0 and the return is false as expected. 

So support xdebug.enable with a changeable status of `PHP_INI_ALL` Entry can be set anywhere may be all that is needed.

**Comment by photodude** [comment]
closing as per https://hhvm.com/blog/2017/09/18/the-future-of-hhvm.html
