### ISSUE TITLE
HHVM php.ini set display_error error_reporting invalid

### ISSUE THREAD

**Issue by ndj888** [facebook/hhvm#7346]
### HHVM Version
3.14.4
### Standalone code, or other way to reproduce the problem
HHVM Version 3.14.4

Version

Version	3.14.4
Version ID	31404
Debug	
Compiler ID	tags/HHVM-3.14.4-0-gcee2aedf82cffa3f4959adf9e0409c9ec7b314cb
Repo Schema	c6d3b7c365d7be3fe41c697542afe0a1b1802987
PHP Version	5.6.99-hhvm
Zend Version	2.4.99
uname	Linux ecbde53cc9f8 4.4.19-moby #1 SMP Thu Sep 1 09:44:30 UTC 2016 x86_64
INI

allow_url_fopen	1
apc.enable_cli	1
apc.enabled	1
apc.stat	1
curl.namedPools	
doc_root	/
expose_php	1
extension_dir	/usr/lib/x86_64-linux-gnu/hhvm/extensions
file_uploads	1
hhvm.admin_server.password	
hhvm.admin_server.passwords	Array ( )
hhvm.admin_server.port	0
hhvm.admin_server.thread_count	1
hhvm.allow_hhas	
hhvm.allow_scope_binding	1
hhvm.authoritative_mode	
hhvm.build_type	Release
hhvm.check_flush_on_user_close	1
hhvm.check_return_type_hints	2
hhvm.check_sym_link	1
hhvm.code_coverage_output_file	
hhvm.custom_settings	Array ( )
hhvm.debug.clear_input_on_success	1
hhvm.debug.core_dump_email	
hhvm.debug.core_dump_report	1
hhvm.debug.core_dump_report_directory	/tmp
hhvm.debug.native_stack_trace	
hhvm.debug.profiler_output_dir	/tmp
hhvm.debug.record_input	
hhvm.debug.server_error_message	
hhvm.debug.simple_counter.sample_stack_count	0
hhvm.debug.simple_counter.sample_stack_depth	5
hhvm.debug.stack_trace_timeout	0
hhvm.debugger.default_sandbox_path	
hhvm.debugger.disable_ipv6	
hhvm.debugger.enable_debugger	
hhvm.debugger.enable_debugger_color	1
hhvm.debugger.enable_debugger_prompt	1
hhvm.debugger.enable_debugger_server	
hhvm.debugger.enable_debugger_usage_log	
hhvm.debugger.port	8089
hhvm.debugger.rpc.default_auth	
hhvm.debugger.rpc.default_port	8083
hhvm.debugger.rpc.default_timeout	30
hhvm.debugger.rpc.host_domain	
hhvm.debugger.signal_timeout	1
hhvm.debugger.startup_document	
hhvm.deployment_id	
hhvm.disable_small_allocator	
hhvm.disable_some_repo_auth_notices	1
hhvm.disable_struct_array	1
hhvm.dump_ast	
hhvm.dump_bytecode	0
hhvm.dump_hhas	
hhvm.dump_ir	0
hhvm.dump_region	0
hhvm.dump_ring_buffer_on_crash	0
hhvm.dump_tc	
hhvm.dump_tc_anchors	
hhvm.dump_tc_annotations_for_all_trans	
hhvm.dynamic_extension_path	.
hhvm.dynamic_extensions	Array ( )
hhvm.dynamic_invoke_functions	Array ( )
hhvm.eager_gc	
hhvm.emit_switch	1
hhvm.enable_args_in_backtraces	1
hhvm.enable_asp_tags	
hhvm.enable_call_builtin	1
hhvm.enable_emitter_stats	1
hhvm.enable_gc	
hhvm.enable_gc_type_scan	
hhvm.enable_hip_hop_experimental_syntax	
hhvm.enable_intrinsics_extension	
hhvm.enable_numa	1
hhvm.enable_numa_local	1
hhvm.enable_obj_destruct_call	1
hhvm.enable_reusable_tc	
hhvm.enable_short_tags	1
hhvm.enable_xhp	1
hhvm.enable_zend_compat	
hhvm.enable_zend_ini_compat	1
hhvm.enable_zend_sorting	
hhvm.env_variables	Array ( )
hhvm.error_handling.call_user_handler_on_fatals	
hhvm.error_handling.log_native_stack_on_oom	
hhvm.error_handling.max_serialized_string_size	67108864
hhvm.error_handling.no_infinite_recursion_detection	
hhvm.error_handling.notice_frequency	1
hhvm.error_handling.throw_exception_on_bad_method_call	1
hhvm.error_handling.upgrade_level	0
hhvm.error_handling.warning_frequency	1
hhvm.extensions	Array ( )
hhvm.external_emitter_allow_partial	
hhvm.external_emitter_fallback	0
hhvm.fail_jit_prologs	
hhvm.filter_gc_points	1
hhvm.force_hh	1
hhvm.gdb_sync_chunks	128
hhvm.hack.lang.auto_typecheck	
hhvm.hack.lang.autoprime_generators	1
hhvm.hack.lang.ints_overflow_to_ints	1
hhvm.hack.lang.look_for_typechecker	
hhvm.health_monitor.enable_health_monitor	1
hhvm.health_monitor.update_freq	1000
hhvm.hh_prof.accum	
hhvm.hh_prof.active	
hhvm.hh_prof.enabled	
hhvm.hh_prof.request	
hhvm.hhbc_arena_chunk_size	10485760
hhvm.hhir_alloc_simd_regs	1
hhvm.hhir_dead_code_elim	1
hhvm.hhir_direct_exit	1
hhvm.hhir_enable_coalescing	1
hhvm.hhir_enable_gen_time_inlining	1
hhvm.hhir_enable_pre_coloring	1
hhvm.hhir_gen_opts	1
hhvm.hhir_generate_asserts	
hhvm.hhir_global_value_numbering	1
hhvm.hhir_inline_frame_opts	1
hhvm.hhir_inline_singletons	1
hhvm.hhir_inlining_max_return_dec_refs	6
hhvm.hhir_inlining_max_vasm_cost	400
hhvm.hhir_licm	
hhvm.hhir_memory_opts	1
hhvm.hhir_mixed_array_profile_threshold	0.8
hhvm.hhir_outline_generic_inc_dec_ref	1
hhvm.hhir_partial_inline_frame_opts	1
hhvm.hhir_prediction_opts	1
hhvm.hhir_refcount_opts	1
hhvm.hhir_simplification	1
hhvm.hhir_store_pre	1
hhvm.hhir_stress_spill	
hhvm.hhir_type_check_hoisting	
hhvm.hot_func_count	4100
hhvm.http.default_timeout	30
hhvm.http.slow_query_threshold	5000
hhvm.initial_named_entity_table_size	30000
hhvm.initial_static_string_table_size	500000
hhvm.inline_region_mode	both
hhvm.jit	1
hhvm.jit_a_cold_size	25165824
hhvm.jit_a_frozen_size	41943040
hhvm.jit_a_hot_size	0
hhvm.jit_a_max_usage	62914560
hhvm.jit_a_prof_size	67108864
hhvm.jit_a_size	62914560
hhvm.jit_always_interp_one	
hhvm.jit_auto_tc_shift	1
hhvm.jit_concurrently	0
hhvm.jit_disabled_by_hphpd	
hhvm.jit_enable_rename_function	1
hhvm.jit_evaled_code	1
hhvm.jit_global_data_size	15728640
hhvm.jit_global_translation_limit	-1
hhvm.jit_keep_dbg_files	
hhvm.jit_mature_size	20971520
hhvm.jit_max_region_instrs	1000
hhvm.jit_max_translations	12
hhvm.jit_no_gdb	1
hhvm.jit_nop_interval	0
hhvm.jit_pgo	1
hhvm.jit_pgo_array_get_stress	
hhvm.jit_pgo_hot_only	
hhvm.jit_pgo_max_func_size_dup_body	80
hhvm.jit_pgo_min_arc_probability	0
hhvm.jit_pgo_min_block_count_percent	0
hhvm.jit_pgo_region_selector	hotcfg
hhvm.jit_pgo_relax_percent	100
hhvm.jit_pgo_release_vv_min_percent	10
hhvm.jit_pgo_threshold	2000
hhvm.jit_pgo_use_post_conditions	1
hhvm.jit_profile_interp_requests	11
hhvm.jit_profile_record	
hhvm.jit_profile_requests	2000
hhvm.jit_profile_warmup_requests	
hhvm.jit_pseudomain	1
hhvm.jit_region_selector	tracelet
hhvm.jit_relocation_size	1048576
hhvm.jit_require_write_lease	
hhvm.jit_reset_prof_counters_request	1000
hhvm.jit_target_cache_size	67108864
hhvm.jit_timer	
hhvm.jit_trans_counters	
hhvm.jit_unlikely_dec_ref_percent	10
hhvm.jit_use_vtune_api	
hhvm.jit_write_lease_expiration	1500
hhvm.keep_perf_pid_map	
hhvm.log.access_log_default_format	%h %l %u %t "%r" %>s %b
hhvm.log.admin_log.file	
hhvm.log.admin_log.format	%h %t %s %U
hhvm.log.admin_log.sym_link	
hhvm.log.always_escape_log	1
hhvm.log.always_log_unhandled_exceptions	
hhvm.log.drop_cache_chunk_size	1048576
hhvm.log.file	/var/log/hhvm/error.log
hhvm.log.force_error_reporting_level	0
hhvm.log.header	
hhvm.log.header_mangle	0
hhvm.log.level	Info
hhvm.log.max_messages_per_request	-1
hhvm.log.native_stack_trace	1
hhvm.log.no_silencer	
hhvm.log.runtime_error_reporting_level	32767
hhvm.log.sym_link	
hhvm.log.use_cronolog	
hhvm.log.use_log_file	1
hhvm.log.use_request_log	
hhvm.log.use_syslog	
hhvm.log_thread_create_backtraces	
hhvm.mail.force_extra_parameters	
hhvm.mail.sendmail_path	/usr/lib/sendmail -t -i
hhvm.map_tc_huge	1
hhvm.map_tgt_cache_huge	
hhvm.max_hot_text_huge_pages	1
hhvm.max_low_mem_huge_pages	8
hhvm.mysql.connect_timeout	1000
hhvm.mysql.kill_on_timeout	
hhvm.mysql.max_retry_open_on_fail	1
hhvm.mysql.max_retry_query_on_fail	1
hhvm.mysql.read_only	
hhvm.mysql.read_timeout	60000
hhvm.mysql.slow_query_threshold	1000
hhvm.mysql.socket	
hhvm.mysql.typed_results	1
hhvm.mysql.wait_timeout	-1
hhvm.num_single_jit_requests	20
hhvm.pagelet_server.queue_limit	0
hhvm.pagelet_server.thread_count	0
hhvm.pagelet_server.thread_drop_cache_timeout_seconds	0
hhvm.pagelet_server.thread_drop_stack	
hhvm.pagelet_server.thread_round_robin	
hhvm.pcre.jit	1
hhvm.pcre_cache_type	static
hhvm.pcre_expire_interval	7200
hhvm.pcre_table_size	98304
hhvm.perf_data_map	
hhvm.perf_pid_map	1
hhvm.perf_relocate	0
hhvm.php7.all	
hhvm.php7.deprecate_old_style_ctors	
hhvm.php7.engine_exceptions	
hhvm.php7.int_semantics	
hhvm.php7.ltr_assign	
hhvm.php7.no_hex_numerics	
hhvm.php7.report_version	
hhvm.php7.scalar_types	
hhvm.php7.uvs	
hhvm.php_file.extensions	Array ( )
hhvm.pid_file	/var/run/hhvm/pid
hhvm.preg.backtrace_limit	1000000
hhvm.preg.error_log	1
hhvm.preg.recursion_limit	100000
hhvm.profile_bc	
hhvm.profile_heap_across_requests	
hhvm.profile_hw_enable	1
hhvm.profile_hw_events	
hhvm.proxy.origin	
hhvm.proxy.percentage	0
hhvm.proxy.proxy_patterns	Array ( )
hhvm.proxy.proxy_urls	Array ( )
hhvm.proxy.retry	3
hhvm.proxy.serve_urls	Array ( )
hhvm.quarantine	
hhvm.random_hot_funcs	
hhvm.record_code_coverage	
hhvm.record_subprocess_times	
hhvm.region_relax_guards	1
hhvm.repo.authoritative	
hhvm.repo.central.path	/var/run/hhvm/hhvm.hhbc
hhvm.repo.commit	1
hhvm.repo.debug_info	1
hhvm.repo.journal	delete
hhvm.repo.local.mode	r-
hhvm.repo.local.path	
hhvm.repo.local_readahead_concurrent	
hhvm.repo.local_readahead_rate	0
hhvm.repo.mode	readonly
hhvm.repo.preload	
hhvm.resource_limit.core_file_size	0
hhvm.resource_limit.core_file_size_override	0
hhvm.resource_limit.drop_cache_cycle	0
hhvm.resource_limit.heap_high_water_mark	1024
hhvm.resource_limit.heap_low_water_mark	16
hhvm.resource_limit.heap_reset_count_base	1
hhvm.resource_limit.heap_reset_count_multiple	2
hhvm.resource_limit.heap_size_mb	4096
hhvm.resource_limit.max_rss	0
hhvm.resource_limit.max_rss_polling_cycle	0
hhvm.resource_limit.max_socket	0
hhvm.resource_limit.max_sql_row_count	0
hhvm.resource_limit.rss	0
hhvm.resource_limit.serialization_size_limit	2146435072
hhvm.resource_limit.socket_default_timeout	60
hhvm.reusable_tc_padding	128
hhvm.sandbox.conf_file	
hhvm.sandbox.directories_root	
hhvm.sandbox.fallback	
hhvm.sandbox.from_common_root	
hhvm.sandbox.home	
hhvm.sandbox.logs_root	
hhvm.sandbox.pattern	
hhvm.sandbox.sandbox_mode	
hhvm.sandbox.server_variables	Array ( )
hhvm.server.add_vary_encoding	1
hhvm.server.allow_duplicate_cookies	
hhvm.server.allowed_directories	Array ( )
hhvm.server.allowed_exec_cmds	Array ( )
hhvm.server.allowed_files	Array ( )
hhvm.server.always_populate_raw_post_data	
hhvm.server.always_use_relative_path	
hhvm.server.apc.allow_object	
hhvm.server.apc.completion_keys	Array ( )
hhvm.server.apc.enable_apc	1
hhvm.server.apc.enable_apc_serialize	1
hhvm.server.apc.enable_const_load	
hhvm.server.apc.expire_on_sets	
hhvm.server.apc.file_storage.advise_out_period	1800
hhvm.server.apc.file_storage.enable	
hhvm.server.apc.file_storage.flag_key	_madvise_out
hhvm.server.apc.file_storage.keep_file_linked	
hhvm.server.apc.file_storage.prefix	/tmp/apc_store
hhvm.server.apc.force_const_load_to_apc	1
hhvm.server.apc.hot_key_alloc_low	
hhvm.server.apc.hot_load_factor	0.5
hhvm.server.apc.hot_map_alloc_low	
hhvm.server.apc.hot_prefix	Array ( )
hhvm.server.apc.hot_size	30000
hhvm.server.apc.key_frequency_update_period	1000
hhvm.server.apc.key_maturity_threshold	20
hhvm.server.apc.load_thread	15
hhvm.server.apc.maximum_capacity	0
hhvm.server.apc.mem_model_treadmill	1
hhvm.server.apc.no_ttl_prefix	Array ( )
hhvm.server.apc.prime_library	
hhvm.server.apc.prime_library_upgrade_dest	
hhvm.server.apc.purge_frequency	4096
hhvm.server.apc.purge_rate	-1
hhvm.server.apc.ttl_limit	-1
hhvm.server.backlog	128
hhvm.server.brotli_chunked_compression_enabled	-1
hhvm.server.brotli_compression_enabled	-1
hhvm.server.brotli_compression_lg_window_size	22
hhvm.server.brotli_compression_mode	0
hhvm.server.brotli_compression_quality	11
hhvm.server.cache_free_factor	50
hhvm.server.cleanup_request	
hhvm.server.connection_limit	0
hhvm.server.connection_timeout_seconds	-1
hhvm.server.default_charset_name	
hhvm.server.default_document	index.php
hhvm.server.default_server_name_suffix	
hhvm.server.enable_early_flush	1
hhvm.server.enable_h2c	
hhvm.server.enable_keep_alive	1
hhvm.server.enable_on_demand_uncompress	1
hhvm.server.enable_output_buffering	
hhvm.server.enable_ssl	
hhvm.server.enable_static_content_from_disk	1
hhvm.server.enable_static_content_m_map	1
hhvm.server.error_document404	
hhvm.server.error_document500	
hhvm.server.evil_shutdown	1
hhvm.server.exit_on_bind_fail	
hhvm.server.expires_active	1
hhvm.server.expires_default	2592000
hhvm.server.expose_hphp	1
hhvm.server.expose_xfb_debug	
hhvm.server.expose_xfb_server	
hhvm.server.fatal_error_message	
hhvm.server.file_cache	
hhvm.server.file_socket	
hhvm.server.fix_path_info	
hhvm.server.forbidden_as404	
hhvm.server.forbidden_file_extensions	Array ( )
hhvm.server.force_chunked_encoding	
hhvm.server.force_compression.cookie	
hhvm.server.force_compression.param	
hhvm.server.force_compression.url	
hhvm.server.force_server_name_to_header	
hhvm.server.graceful_shutdown_wait	0
hhvm.server.gzip_compression_level	3
hhvm.server.gzip_max_compression_level	9
hhvm.server.harsh_shutdown	1
hhvm.server.high_priority_end_points	Array ( )
hhvm.server.host	
hhvm.server.http_safe_mode	
hhvm.server.image_memory_max_bytes	209715200
hhvm.server.implicit_flush	
hhvm.server.include_search_paths	Array ( [0] => . )
hhvm.server.internal_warmup_threads	0
hhvm.server.ip	
hhvm.server.kill_on_sigterm	
hhvm.server.kill_on_timeout	1
hhvm.server.light_process_count	0
hhvm.server.light_process_file_prefix	./lightprocess
hhvm.server.lock_code_memory	
hhvm.server.max_array_chain	2147483647
hhvm.server.max_post_size	104857600
hhvm.server.max_request_age_factor	0
hhvm.server.memory_head_room	0
hhvm.server.output_handler	
hhvm.server.path_debug	
hhvm.server.port	9000
hhvm.server.pre_shutdown_wait	0
hhvm.server.psp_cpu_timeout_seconds	0
hhvm.server.psp_timeout_seconds	0
hhvm.server.request_body_read_limit	-1
hhvm.server.request_init_document	
hhvm.server.request_init_function	
hhvm.server.request_memory_max_bytes	17179869184
hhvm.server.request_timeout_seconds	0
hhvm.server.rss_needed_mb	4096
hhvm.server.safe_file_access	
hhvm.server.shutdown_eom_wait	0
hhvm.server.shutdown_listen_wait	0
hhvm.server.source_root	/
hhvm.server.ssl_certificate_dir	
hhvm.server.ssl_certificate_file	
hhvm.server.ssl_certificate_key_file	
hhvm.server.ssl_next_protocols	Array ( )
hhvm.server.ssl_port	443
hhvm.server.startup_document	
hhvm.server.stat_cache	
hhvm.server.stop_old	
hhvm.server.stop_old_wait	30
hhvm.server.takeover_filename	
hhvm.server.thread_count	4
hhvm.server.thread_drop_cache_timeout_seconds	0
hhvm.server.thread_drop_stack	
hhvm.server.thread_job_lifo_switch_threshold	2147483647
hhvm.server.thread_job_max_queuing_milli_seconds	-1
hhvm.server.thread_round_robin	
hhvm.server.tls_client_cipher_spec	
hhvm.server.tls_disable_tls1_2	
hhvm.server.type	fastcgi
hhvm.server.unserialization_big_map_threshold	65536
hhvm.server.unserialization_whitelist_check	
hhvm.server.unserialization_whitelist_check_warning_only	1
hhvm.server.upload.enable_file_uploads	1
hhvm.server.upload.enable_upload_progress	
hhvm.server.upload.rfc1867freq	262144
hhvm.server.upload.rfc1867name	video_ptoken
hhvm.server.upload.rfc1867prefix	vupload_
hhvm.server.upload.upload_max_file_size	104857600
hhvm.server.upload.upload_tmp_dir	/tmp
hhvm.server.use_direct_copy	
hhvm.server.user	www-data
hhvm.server.utf8ize_replace	1
hhvm.server.warmup_requests	Array ( )
hhvm.server.warmup_throttle_request_count	0
hhvm.server.warn_on_collection_to_array	
hhvm.server.whitelist_exec	
hhvm.server.whitelist_exec_warning_only	
hhvm.server.xfb_debug_ssl_key	
hhvm.server_variables	Array ( )
hhvm.simple_xml.empty_namespace_matches_all	
hhvm.soft_closure_return_type_hints	
hhvm.spin_on_crash	
hhvm.static_file.extensions	Array ( [zip] => application/zip [jpeg] => image/jpeg [html] => text/html [css] => text/css [gif] => image/gif [mp3] => audio/mpeg [png] => image/png [tif] => image/tiff [jpg] => image/jpeg [tiff] => image/tiff [txt] => text/plain )
hhvm.static_file.generators	Array ( )
hhvm.stats.apc	
hhvm.stats.enable	
hhvm.stats.enable_hot_profiler	1
hhvm.stats.max_slot	72
hhvm.stats.memory	
hhvm.stats.network_io	
hhvm.stats.profiler_max_trace_buffer	0
hhvm.stats.profiler_trace_buffer	2000000
hhvm.stats.profiler_trace_expansion	1.2
hhvm.stats.slot_duration	600
hhvm.stats.sql	
hhvm.stats.sql_table	
hhvm.stats.track_per_unit_memory	
hhvm.stats.web	
hhvm.stats.xsl	
hhvm.stats.xsl_proxy	
hhvm.tc_num_huge_cold_mb	4
hhvm.tc_num_huge_hot_mb	16
hhvm.timeouts_use_wall_time	1
hhvm.use_external_emitter	
hhvm.vm_initial_global_table_size	512
hhvm.vm_stack_elms	16384
hhvm.xbox.default_local_timeout_milli_seconds	500
hhvm.xbox.default_remote_timeout_seconds	5
hhvm.xbox.process_message_func	xbox_process_message
hhvm.xbox.server_info.always_reset	
hhvm.xbox.server_info.log_info	
hhvm.xbox.server_info.max_duration	120
hhvm.xbox.server_info.max_queue_length	2147483647
hhvm.xbox.server_info.max_request	500
hhvm.xbox.server_info.port	0
hhvm.xbox.server_info.request_init_document	
hhvm.xbox.server_info.request_init_function	
hhvm.xbox.server_info.thread_count	10
hhvm.xbox.server_info.warmup_document	
hhvm.xenon.force_always_on	
hhvm.xenon.period	0
hphp.build_id	
hphp.compiler_id	tags/HHVM-3.14.4-0-gcee2aedf82cffa3f4959adf9e0409c9ec7b314cb
hphp.compiler_version	3.14.4
max_file_uploads	20
mbstring.http_input	pass
mbstring.http_output	pass
mysqli.allow_local_infile	
mysqli.allow_persistent	1
mysqli.cache_size	
mysqli.max_links	-1
mysqli.max_persistent	-1
mysqli.reconnect	
notice_frequency	1
pdo_mysql.default_socket	
pid	/var/run/hhvm/pid
sendmail_path	/usr/lib/sendmail -t -i
upload_tmp_dir	/tmp
warning_frequency	1
xdebug.enable	1
arg_separator.input	&
arg_separator.output	&
assert.active	1
assert.bail	0
assert.exception	0
assert.warning	1
bcmath.scale	0
brotli.chunked_compression	
brotli.compression	
brotli.compression_lgwin	22
brotli.compression_quality	11
date.default_latitude	31.7667
date.default_longitude	35.2333
date.sunrise_zenith	90.583333
date.sunset_zenith	90.583333
date.timezone	
default_charset	
default_mimetype	text/html
default_socket_timeout	60
display_errors	1
error_log	
error_reporting	32767
hhvm.max_cpu_time	0
hhvm.max_wall_time	0
highlight.comment	#FF8000
highlight.default	#0000BB
highlight.html	#000000
highlight.keyword	#007700
highlight.string	#DD0000
html_errors	
imagick.locale_fix	
imagick.progress_monitor	
include_path	.
intl.default_locale	
log_errors	
max_execution_time	0
maximum_execution_time	0
memcache.hash_function	crc32
memcache.hash_strategy	standard
memcached.sess_prefix	
memory_limit	17179869184
mysqli.default_host	
mysqli.default_port	3306
mysqli.default_pw	
mysqli.default_socket	
mysqli.default_user	
open_basedir	
pcre.backtrack_limit	1000000
pcre.recursion_limit	100000
request_order	
session.auto_start	
session.cache_expire	180
session.cache_limiter	nocache
session.cookie_domain	
session.cookie_httponly	
session.cookie_lifetime	0
session.cookie_path	/
session.cookie_secure	
session.entropy_file	
session.entropy_length	0
session.gc_divisor	100
session.gc_maxlifetime	1440
session.gc_probability	1
session.hash_bits_per_character	4
session.hash_function	0
session.name	PHPSESSID
session.referer_check	
session.save_handler	files
session.save_path	
session.serialize_handler	php
session.use_cookies	1
session.use_only_cookies	1
session.use_trans_sid	
track_errors	
user_agent	
variables_order	EGPCS
xdebug.COOKIE	
xdebug.FILES	
xdebug.GET	
xdebug.POST	
xdebug.REQUEST	
xdebug.SERVER	
xdebug.SESSION	
xdebug.auto_trace	
xdebug.cli_color	0
xdebug.collect_assignments	
xdebug.collect_includes	1
xdebug.collect_memory	
xdebug.collect_params	0
xdebug.collect_return	
xdebug.collect_time	
xdebug.collect_vars	
xdebug.default_enable	1
xdebug.dump_globals	1
xdebug.dump_once	1
xdebug.dump_undefined	
xdebug.file_link_format	
xdebug.force_display_errors	
xdebug.force_error_reporting	0
xdebug.framebuf_expansion	1.5
xdebug.framebuf_size	100000
xdebug.halt_level	0
xdebug.idekey	phpstorm
xdebug.manual_url	http://www.php.net
xdebug.max_nesting_level	0
xdebug.overload_var_dump	1
xdebug.profiler_append	
xdebug.profiler_enable	1
xdebug.profiler_enable_trigger	1
xdebug.profiler_output_dir	/tmp
xdebug.profiler_output_name	cachegrind.out.%p
xdebug.remote_autostart	
xdebug.remote_connect_back	
xdebug.remote_cookie_expire_time	3600
xdebug.remote_enable	1
xdebug.remote_handler	dbgp
xdebug.remote_host	192.168.1.188
xdebug.remote_log	
xdebug.remote_mode	req
xdebug.remote_port	9028
xdebug.remote_timeout	0.2
xdebug.scream	
xdebug.show_exception_trace	
xdebug.show_local_vars	
xdebug.show_mem_delta	
xdebug.trace_enable_trigger	
xdebug.trace_format	0
xdebug.trace_options	
xdebug.trace_output_dir	/tmp
xdebug.trace_output_name	trace.%c
xdebug.var_display_max_children	128
xdebug.var_display_max_data	512
xdebug.var_display_max_depth	3
zend.assertions	1
zlib.output_compression	
zlib.output_compression_level	-1
Headers

Cache-Control	max-age=0
Cookie	username=15823978441; key=a281077b1cad4f62fa82b396bbef6764; PHPSESSID=kha695n0jqf4sud3kch2dd6d81; cart_count=0; DDF9_cart_goods_num=0; lang=zh-cn; theme=default
Accept-Language	zh-CN,zh;q=0.8
Content-Type	
Accept-Encoding	gzip, deflate, sdch
Accept	text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Upgrade-Insecure-Requests	1
Content-Length	
Connection	keep-alive
Host	localhost:8028
User-Agent	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
$_SERVER

REQUEST_START_TIME	1473834109
REQUEST_TIME	1473834109
REQUEST_TIME_FLOAT	1473834109.6095
HTTP_CACHE_CONTROL	max-age=0
HTTP_COOKIE	username=15823978441; key=a281077b1cad4f62fa82b396bbef6764; PHPSESSID=kha695n0jqf4sud3kch2dd6d81; cart_count=0; DDF9_cart_goods_num=0; lang=zh-cn; theme=default
HTTP_ACCEPT_LANGUAGE	zh-CN,zh;q=0.8
HTTP_CONTENT_TYPE	
HTTP_ACCEPT_ENCODING	gzip, deflate, sdch
HTTP_ACCEPT	text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
HTTP_UPGRADE_INSECURE_REQUESTS	1
HTTP_CONTENT_LENGTH	
HTTP_CONNECTION	keep-alive
HTTP_HOST	localhost:8028
HTTP_USER_AGENT	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
GATEWAY_INTERFACE	CGI/1.1
SERVER_ADDR	172.17.0.11
SERVER_NAME	
SERVER_PORT	8028
SERVER_SOFTWARE	nginx/1.11.3
SERVER_PROTOCOL	HTTP/1.1
SERVER_ADMIN	
SERVER_SIGNATURE	
SCRIPT_NAME	/test.php
REMOTE_ADDR	172.17.0.1
REMOTE_PORT	35936
DOCUMENT_URI	/test.php
REDIRECT_STATUS	200
REQUEST_URI	/test.php
CONTENT_TYPE	
CONTENT_LENGTH	
REQUEST_METHOD	GET
QUERY_STRING	
SCRIPT_FILENAME	/data/wwwroot/test.php
REQUEST_SCHEME	http
DOCUMENT_ROOT	/data/wwwroot
SCRIPT_URL	/test.php
SCRIPT_URI	http://localhost:8028/test.php
PHP_SELF	/test.php
PATH_TRANSLATED	/data/wwwroot/test.php
HTTPS	
argv	Array ( [0] => )
argc	1
THREAD_TYPE	Web Request
$_ENV

TERM	
PATH	/sbin:/usr/sbin:/bin:/usr/bin
LANG	
PWD	/
GLIBCPP_FORCE_NEW	1
GLIBCXX_FORCE_NEW	1
UNW_RBP_ALWAYS_VALID	1
HPHP	1
HHVM	1
HHVM_JIT	1
HHVM_ARCH	x64
HPHP_SERVER	1
HPHP_HOTPROFILER	1
HTTP_HOST	localhost:8028
SCRIPT_NAME	/test.php
HTTP_USER_AGENT	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
REMOTE_ADDR	172.17.0.1
REMOTE_PORT	35936
DOCUMENT_URI	/test.php
REDIRECT_STATUS	200
GATEWAY_INTERFACE	CGI/1.1
REQUEST_URI	/test.php
SERVER_PROTOCOL	HTTP/1.1
CONTENT_TYPE	
HTTP_ACCEPT_ENCODING	gzip, deflate, sdch
HTTP_ACCEPT_LANGUAGE	zh-CN,zh;q=0.8
SERVER_ADDR	172.17.0.11
CONTENT_LENGTH	
REQUEST_METHOD	GET
HTTP_UPGRADE_INSECURE_REQUESTS	1
HTTP_CACHE_CONTROL	max-age=0
HTTP_COOKIE	username=15823978441; key=a281077b1cad4f62fa82b396bbef6764; PHPSESSID=kha695n0jqf4sud3kch2dd6d81; cart_count=0; DDF9_cart_goods_num=0; lang=zh-cn; theme=default
QUERY_STRING	
SCRIPT_FILENAME	/data/wwwroot/test.php
SERVER_NAME	
REQUEST_SCHEME	http
SERVER_PORT	8028
SERVER_SOFTWARE	nginx/1.11.3
DOCUMENT_ROOT	/data/wwwroot
HTTP_ACCEPT	text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
HTTP_CONNECTION	keep-alive
### Expected result
Display error in the browser.
### Actual result
The browser display 500 error.

**Comment by paulbiss** [comment]
This isn't something we currently support. It's been discussed on here before, but the tl;dr is that we definitely don't want this to be the default behavior, and getting it working at all may be non-trivial because the logging and output buffering are so disconnected right now.

**Comment by ndj888** [comment]
@paulbiss I can not find documentation about how to debug in HHVM. HHVM recommended debugging method?

**Comment by paulbiss** [comment]
You can use set_error_handler to achieve a similar message https://github.com/facebook/hhvm/issues/3576#issuecomment-53205529
