### ISSUE TITLE
Build from source code hangs the system on Fedora 24

### ISSUE THREAD

**Issue by furkanusta** [facebook/hhvm#7349]
I've followed the steps from here https://github.com/facebook/hhvm/wiki/Building-and-installing-HHVM-on-Fedora-19-or-20

But I am using Fedora24.

Cmake run succesfully but when I run make it stops at this one and then whole computer freezes only thing I can do is power-off
[  7%] Building CXX object third-party/folly/CMakeFiles/folly.dir/src/folly/IPAddressV4.cpp.o

I've tested with both -jN option present and not

**Comment by paulbiss** [comment]
Do you seen any lines in the system log or any other logs indicating what may be happening? I've not ever seen this problem before.

**Comment by aorenste** [comment]
How long did you let it run before you decided it froze? If you have a disk activity light that you can see was it still lit?  Building can take a lot of system resources and that can make the UI freeze up - but eventually it should finish.  On a resource limited machine that can be a really long time.

Two other things to try:
1. `-j1` (so you only build with a single core)
2. Instead of `make` run `nice make` (so it allows other processes priority to run)

**Comment by furkanusta** [comment]
I've just tested 'nice make' and it let it run for 8 minutes, during that time UI didn't respond except a random mouse movements (I suppose it get processed over time). Clock didn't get updated either
Ctrl-C didn't work. 
Disk light was on

I've tested -j1 before result was the same

I have Intel(R) Core(TM) i5-6200U CPU with 8GB Ram, I suppose it isn't a resource limited machine

and I am not sure which logs to check but currently inspecting journalctl entries, I'll update here if I can find anything

**Comment by aorenste** [comment]
When I'm building gcc often at points uses more than 8GB so it wouldn't surprise me if your computer is thrashing from not having enough RAM.

**Comment by furkanusta** [comment]
I've checked journalctl and thought gnome tracker is the culprit but after disabling it and letting the make run for ~40minutes it was still at %7 . 

I will try to build folly separately

**Comment by Orvid** [comment]
To eliminate one possibility: What version of GCC are you using?

**Comment by furkanusta** [comment]
GCC 6.1.1

By the way, I've couldn't build folly alone and it looks like problem is caused by it

should I close this issue and open in folly's issue tracker?

**Comment by furkanusta** [comment]
It looks like it is already reported in Folly and Wangle
https://github.com/facebook/folly/issues/418

Thanks for the help, I'll check that out
