### ISSUE TITLE
Fatal error: Call to undefined method mysqli::get_server_info()

### ISSUE THREAD

**Issue by photodude** [facebook/hhvm#7350]
### HHVM Version

3.15.0
### Standalone code, or other way to reproduce the problem

with a Mysqli connection

``` php
$this->connect();
return $this->connection->get_server_info();
```
### Expected result

Returns the version of the MySQL server
### Actual result

`Fatal error: Call to undefined method mysqli::get_server_info()` in [/database/src/Mysqli/MysqliDriver.php on line 529](https://github.com/joomla-framework/database/blob/master/src/Mysqli/MysqliDriver.php#L518-L531)

Travis CI build with error
https://travis-ci.org/photodude/database/jobs/160602939

**Comment by photodude** [comment]
Just checking back on this issue. Any progress?

**Comment by aorenste** [comment]
No work has been done on this issue recently.

**Comment by photodude** [comment]
Thanks for the update @aorenste Look forward to this eventually being fixed.
Another issue just landed on our radar https://github.com/facebook/hhvm/issues/2060

**Comment by photodude** [comment]
Would the correct fix for this be to add the following to the php file under the mysqli class?
https://github.com/facebook/hhvm/blob/master/hphp/runtime/ext/mysql/ext_mysqli.php
```php
  /**
   * Get MySQL server info
   *
   * @return string - A character string representing the server version
   *
   */
  public function get_server_info(): string {
    return mysqli_get_server_info();
  }
```

and in the CPP file https://github.com/facebook/hhvm/blob/master/hphp/runtime/ext/mysql/ext_mysqli.cpp
```c++
static String HHVM_FUNCTION(mysqli_get_server_info) {
  return HHVM_FN(mysql_get_server_info)();
}

static Variant mysqli_server_info_get(const Object& this_) {
  return HHVM_FN(mysqli_get_server_info)();
}

static Variant mysqli_driver_server_info_get(const Object& this_) {
  return HHVM_FN(mysqli_get_server_info)();
}

HHVM_FE(mysqli_get_server_info);
```

**Comment by aorenste** [comment]
@photodude that doesn't look quite right to me.  I'd need to look in more detail to be sure.

**Comment by photodude** [comment]
closing as per https://hhvm.com/blog/2017/09/18/the-future-of-hhvm.html
