### ISSUE TITLE
HHVM random crashes with Mediawiki

### ISSUE THREAD

**Issue by kelson42** [facebook/hhvm#7351]
### HHVM Version
3.11.1+dfsg-1ubuntu1 (amd64)

### Standalone code, or other way to reproduce the problem
HHVM dies sporadically with Mediawiki 1.26.3. I have unfortunately no clear step-by-step reprocase. As a workaround I restart the HHVM service and then Mediawiki runs again. But I have a small syslog dump which might help.
[hhvm_crash.log.txt](https://github.com/facebook/hhvm/files/478049/hhvm_crash.log.txt)

### Expected result
HHVM service should not die randomly.

### Actual result
I dies time to time.

**Comment by photodude** [comment]
Just a guess based on the info from your log,
```php
message: Attempted to emit 6 byte(s) into a 18 byte DataBlock with 0 bytes available. This almost certainly means the TC is full. If this is the case, increasing Eval.JitASize, Eval.JitAColdSize, Eval.JitAFrozenSize and Eval.JitGlobalDataSize in the configuration file when running this script or application should fix this problem.
```

**Comment by kelson42** [comment]
Thank you. I have followed your advices and will re-open the ticket if the problem still occurs.

**Comment by paulbiss** [comment]
You can increase the size of the TC as @photodude suggested, but it looks to me like the translation you're failing on is a pseudomain (code not contained within any function). Until a2190ac60960d58dc77dd3f91c39be803ac648d1 we had a long-standing issue with over-specializing pseudomains which could cause hhvm to continue emitting (mostly useless) translations for them well after it had finished warming everything else up.

You'll probably solve the problem and see a performance bump if you set `hhvm.jit_pseudomain=false`.
