### ISSUE TITLE
Uncaught Error: syntax error, unexpected T_EMPTY

### ISSUE THREAD

**Issue by bolvarak** [facebook/hhvm#7354]
### HHVM Version
3.15.0

### Standalone code, or other way to reproduce the problem

```php
<?php

class Fubar
{
    const Empty = 'Fubar';
}

echo Fubar::Empty . "\n";
```

### Expected result
```shell
Fubar
```

### Actual result
```shell
Fatal error: Uncaught Error: syntax error, unexpected T_EMPTY
```

### Configuration (php.ini)
```shell
hhvm.php7.all = true
```
- NOTE:  This is vanilla PHP and works as expected in PHP7

**Comment by paulbiss** [comment]
Pretty sure it's just missing from this list: https://github.com/facebook/hhvm/blob/master/hphp/parser/hphp.y#L816
