### ISSUE TITLE
Confused about hhvm error `must be an instance of string, string given in`

### ISSUE THREAD

**Issue by magbicaleman** [facebook/hhvm#7369]
### HHVM Version
`HipHop VM 3.14.5 (rel)`
### Standalone code, or other way to reproduce the problem
```php
class User
{
    public $username;

    public function __construct(string $username)
    {
        $this->username = $username;
    }
}

$users = [
    new User('user 1'),
    new User('user 2'),
    new User('user 3'),
];

print_r(array_column($users, 'username'));
```
### Expected result
```
Array
(
    [0] => user 1
    [1] => user 2
    [2] => user 3
)
```
### Actual result

```
Catchable fatal error: Argument 1 passed to User::__construct() must be an instance of string, string given in
```

**Comment by fredemmott** [comment]
This is a PHP5-compatible error; you want one of these in your ini file:
 - `hhvm.php7.all=true` (most likely)
 - `hhvm.php7.scalar_types=true` (just the one part of PHP7 support)
 - `hhvm.force_hh=true` (allows Hack syntax in PHP files)

**Comment by fredemmott** [comment]
Under PHP5 (and HHVM by default), `string` is a reference to a class called `string`, which leads to the confusing error.

**Comment by magbicaleman** [comment]
thank you very much @fredemmott, I was under the impression `hhvm` was using `php7`by default, but this makes sense.
