### ISSUE TITLE
hhvm --hphp fails on pre-optimizing with magento 1.9.0.1

### ISSUE THREAD

**Issue by yaghmaie** [facebook/hhvm#7376]
Using CentOS 7.2.1511
HipHop VM 3.14.4
Magento 1.9.0.1

By running `hhvm --hphp -t hhbc -v AllVolatile=true  --input-dir /path/to/magento/root` I get:

```
running hphp...
parsing inputs...
analyzeProgram...
analyzeProgram took 0'44" (44998116 us) wall time
parsing inputs took 0'46" (46607550 us) wall time
pre-optimizing...
hphp failed
running hphp took 0'47" (47395623 us) wall time`
```

And I have no idea why it fails on pre-optimizing, or how to get some information for the reason it fails. By using `-l 4` there will be no more info.

It finishes with no errors using `--optimize-level 0`, however hhvm service can not start with the repo.

Thanks

**Comment by fblgit** [comment]
id  9856] stat("/var/www/lib/Zend/Service/Yahoo/PageDataResultSet.php", {st_mode=S_IFREG|0644, st_size=1694, ...}) = 0
[pid  9856] stat("/var/www/lib/Zend/Service/Yahoo/ResultSet.php",  <unfinished ...>
[pid  9855] <... stat resumed> {st_mode=S_IFREG|0644, st_size=3037, ...}) = 0
[pid  9856] <... stat resumed> {st_mode=S_IFREG|0644, st_size=4505, ...}) = 0
[pid  9856] open("/var/www/lib/Zend/Service/Yahoo/ResultSet.php", O_RDONLY) = 7
[pid  9856] lseek(7, 0, SEEK_CUR)       = 0
[pid  9856] lseek(7, 0, SEEK_END)       = 4505
[pid  9856] lseek(7, 0, SEEK_CUR)       = 4505
[pid  9856] lseek(7, 0, SEEK_SET)       = 0
[pid  9856] read(7,  <unfinished ...>
[pid  9855] open("/var/www/lib/Zend/Service/Yahoo/Result.php", O_RDONLY) = 8
[pid  9855] lseek(8, 0, SEEK_CUR)       = 0
[pid  9855] lseek(8, 0, SEEK_END)       = 3037
[pid  9855] lseek(8, 0, SEEK_CUR)       = 3037
[pid  9855] lseek(8, 0, SEEK_SET)       = 0
[pid  9855] read(8,  <unfinished ...>
[pid  9856] <... read resumed> "<?php\n\n/**\n * Zend Framework\n *\n"..., 8191) = 4505
[pid  9856] lseek(7, 0, SEEK_SET)       = 0
[pid  9856] ioctl(0, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, {B38400 opost isig icanon echo ...}) = 0
[pid  9856] read(7, "<?php\n\n/**\n * Zend Framework\n *\n"..., 65535) = 4505
[pid  9856] read(7, "", 61030)          = 0
[pid  9855] <... read resumed> "<?php\n\n/**\n * Zend Framework\n *\n"..., 8191) = 3037
[pid  9855] lseek(8, 0, SEEK_SET)       = 0
[pid  9855] ioctl(0, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, {B38400 opost isig icanon echo ...}) = 0
[pid  9855] read(8, "<?php\n\n/**\n * Zend Framework\n *\n"..., 65535) = 3037
[pid  9855] read(8, "", 62498)          = 0
[pid  9855] ioctl(0, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, {B38400 opost isig icanon echo ...}) = 0
[pid  9855] close(8)                    = 0
[pid  9855] stat("/var/www/lib/Zend/Service/Yahoo/Result.php", {st_mode=S_IFREG|0644, st_size=3037, ...}) = 0
[pid  9855] stat("/var/www/lib/Zend/Service/Yahoo/VideoResult.php", {st_mode=S_IFREG|0644, st_size=2819, ...}) = 0
[pid  9855] open("/var/www/lib/Zend/Service/Yahoo/VideoResult.php", O_RDONLY) = 8
[pid  9855] lseek(8, 0, SEEK_CUR)       = 0
[pid  9855] lseek(8, 0, SEEK_END)       = 2819
[pid  9855] lseek(8, 0, SEEK_CUR)       = 2819
[pid  9855] lseek(8, 0, SEEK_SET)       = 0
[pid  9855] read(8, "<?php\n\n/**\n * Zend Framework\n *\n"..., 8191) = 2819
[pid  9855] lseek(8, 0, SEEK_SET)       = 0
[pid  9855] ioctl(0, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, {B38400 opost isig icanon echo ...}) = 0
[pid  9855] read(8, "<?php\n\n/**\n * Zend Framework\n *\n"..., 65535) = 2819
[pid  9855] read(8, "", 62716)          = 0
[pid  9855] ioctl(0, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, {B38400 opost isig icanon echo ...}) = 0
[pid  9855] close(8)                    = 0
[pid  9855] stat("/var/www/lib/Zend/Service/Yahoo/VideoResult.php", {st_mode=S_IFREG|0644, st_size=2819, ...}) = 0
[pid  9855] stat("/var/www/lib/Zend/Service/Yahoo/VideoResultSet.php", {st_mode=S_IFREG|0644, st_size=1691, ...}) = 0
[pid  9855] open("/var/www/lib/Zend/Service/Yahoo/VideoResultSet.php", O_RDONLY) = 8
[pid  9855] lseek(8, 0, SEEK_CUR)       = 0
[pid  9855] lseek(8, 0, SEEK_END)       = 1691
[pid  9855] lseek(8, 0, SEEK_CUR)       = 1691
[pid  9855] lseek(8, 0, SEEK_SET)       = 0
[pid  9855] read(8, "<?php\n\n/**\n * Zend Framework\n *\n"..., 8191) = 1691
[pid  9855] lseek(8, 0, SEEK_SET)       = 0
[pid  9855] ioctl(0, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, {B38400 opost isig icanon echo ...}) = 0
[pid  9855] read(8, "<?php\n\n/**\n * Zend Framework\n *\n"..., 65535) = 1691
[pid  9855] read(8, "", 63844)          = 0

[pid  9855] +++ killed by SIGKILL +++
[pid  9856] +++ killed by SIGKILL +++
[pid  9843] +++ killed by SIGKILL +++
<... wait4 resumed> [{WIFSIGNALED(s) && WTERMSIG(s) == SIGKILL}], 0, NULL) = 53
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_KILLED, si_pid=53, si_status=SIGKILL, si_utime=4508, si_stime=1873} ---
write(2, "hphp failed\n", 12)           = 12
write(2, "running hphp took 3'12\" (1920583"..., 49) = 49
madvise(0x7f7a140e1000, 8192, MADV_DONTNEED) = 0
madvise(0x7f7a12818000, 4096, MADV_DONTNEED) = 0
madvise(0x7f7a1281a000, 4096, MADV_DONTNEED) = 0
madvise(0x7f7a12820000, 12288, MADV_DONTNEED) = 0
madvise(0x7f7a12828000, 4096, MADV_DONTNEED) = 0
madvise(0x7f7a1282c000, 4096, MADV_DONTNEED) = 0
madvise(0x7f7a12832000, 8192, MADV_DONTNEED) = 0
madvise(0x7f7a12837000, 4096, MADV_DONTNEED) = 0
madvise(0x7f7a12873000, 8192, MADV_DONTNEED) = 0
madvise(0x7f7a12894000, 12288, MADV_DONTNEED) = 0
madvise(0x7f7a12898000, 81920, MADV_DONTNEED) = 0
madvise(0x7f7a128af000, 53248, MADV_DONTNEED) = 0
madvise(0x7f7a12acf000, 8192, MADV_DONTNEED) = 0
madvise(0x7f7a12ad8000, 8192, MADV_DONTNEED) = 0
madvise(0x7f7a12ade000, 8192, MADV_DONTNEED) = 0
rt_sigaction(SIGCHLD, {SIG_DFL, [CHLD], SA_RESTORER|SA_RESTART, 0x7f7a1c5c6cb0}, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGCHLD, {SIG_DFL, [CHLD], SA_RESTORER|SA_RESTART, 0x7f7a1c5c6cb0}, {SIG_DFL, [CHLD], SA_RESTORER|SA_RESTART, 0x7f7a1c5c6cb0}, 8) = 0
rt_sigaction(SIGCHLD, {SIG_DFL, [CHLD], SA_RESTORER|SA_RESTART, 0x7f7a1c5c6cb0}, {SIG_DFL, [CHLD], SA_RESTORER|SA_RESTART, 0x7f7a1c5c6cb0}, 8) = 0
madvise(0x7f7a140fc000, 3149824, MADV_DONTNEED) = 0
madvise(0x7f7a1280c000, 49152, MADV_DONTNEED) = 0
madvise(0x7f7a12829000, 12288, MADV_DONTNEED) = 0
madvise(0x7f7a12ae0000, 8192, MADV_DONTNEED) = 0
madvise(0x7f7a12806000, 12288, MADV_DONTNEED) = 0
madvise(0x7f7a1281d000, 8192, MADV_DONTNEED) = 0
madvise(0x7f7a12826000, 4096, MADV_DONTNEED) = 0
madvise(0x7f7a12adb000, 8192, MADV_DONTNEED) = 0
madvise(0x7f7a12ae3000, 8192, MADV_DONTNEED) = 0
madvise(0x7f7a143fd000, 4096, MADV_DONTNEED) = 0
madvise(0x7f7a143ff000, 4096, MADV_DONTNEED) = 0
madvise(0x7f7a12823000, 4096, MADV_DONTNEED) = 0
madvise(0x7f7a12834000, 12288, MADV_DONTNEED) = 0
madvise(0x7f7a12add000, 4096, MADV_DONTNEED) = 0
madvise(0x7f7a12830000, 4096, MADV_DONTNEED) = 0
madvise(0x7f7a1287e000, 65536, MADV_DONTNEED) = 0
madvise(0x7f7a12ad4000, 4096, MADV_DONTNEED) = 0
madvise(0x7f7a12ae7000, 8192, MADV_DONTNEED) = 0
exit_group(-1)                          = ?
+++ exited with 255 +++

**Comment by mofarrell** [comment]
My guess is most of the benefit from running with the single path will not matter when running in repoauth mode with global optimizations.  One of repoauth's major advantages it that it allows cross file optimizations.  In repoauth moving more code into a single compilation unit should not impact the optimizations that can be done.
At the same time, hhvm shouldn't have issues running after the "compilation" process.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This issue applies to running php code on hhvm. Hhvm [nolonger supports running php code](https://hhvm.com/blog/2018/09/12/end-of-php-support-future-of-hack.html) since [hhvm version 4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html).

The underlying issue may still be around for Hack, but it is near impossible to figure out want specific snippet of code caused this.
