### ISSUE TITLE
Make it possible for a trait to require that it only be used by a specific class that actually does use it.

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#7383]
Example usage:

``` Hack
<?hh // strict

trait SomeCodegenForSomeRealClass {
  require extends SomeRealClass;
}

final class SomeRealClass {
  use SomeCodegenForSomeRealClass;
}
```

This currently gets:

```
test.php:3:7,29: Cyclic class definition : SomeCodegenForSomeRealClass SomeRealClass  (Typing[4013])
```

**Comment by jwatzman** [comment]
Is the request for

- `require extends` to allow usage in that class, as opposed to only a subclass? There is indeed some non-obvious circularity issue here that @elgenie ran into when he implemented it.
- a new modifier that says "this trait may only be used in this specific class"? I don't know if this would hit a circularity issue, but what's the advantage of moving the code out into a trait instead of just inlining it into the one class that can use it?

**Comment by fredemmott** [comment]
- either allowing require extends to be circular when the class is final or adding a new modifier works
 - inlining: where possible, putting codegen into a trait is much cleaner than the partially-codegen files approach, and there's only one library for doing those which hasn't had much testing outside of FB

**Comment by elgenie** [comment]
The distinction between "require extends" and "require is" is very much intentional.

I explicitly did not want to encourage the unreadable copy-pasta that traits were being used for within the FB codebase. Supporting partially generated files is the job of a simple code generation library.

**Comment by acrylic-origami** [comment]
I hope this use case, where this enables a unique behavior, can help justify the feature. This issue exists for interfaces defining class constraints as well, if `use` is replaced with `implements`. Here's a [full explanation](http://stackoverflow.com/questions/43929590/what-makes-this-class-requirement-a-cyclic-class-definition) I wrote just moments ago before I stumbled upon this issue. The core usefulness is that with this I could write a concrete upper bound for `class Comparable<T as Comparable<T>>` quite cleanly with:

```hack
<?hh // strict
interface Comparable<-T as Comparable<T>> {
    require extends ArtificialCeiling;
    public function compare(T $comparee): bool;
}
abstract class ArtificialCeiling implements Comparable<ArtificialCeiling> {
    abstract public function compare(ArtificialCeiling $comparee): bool;
}
```

and use it to type instance variables that don't care about the actual type of `Comparable` (similar to Scala existentials).

**Comment by lexidor** [comment]
The `require class X` syntax enforces that a trait may only be used in X (not a subclass of X). [blog mention of require class](https://hhvm.com/blog/2022/06/01/hhvm-4.161.html) and [documentation](https://github.com/facebook/hhvm/blob/fe869eaa648fe42a425cc4174052e60a7d1459cc/hphp/hack/manual/hack/07-traits-and-interfaces/04-trait-and-interface-requirements.md?plain=1#L114).
