### ISSUE TITLE
ReflectionExtension("phar")->getVersion() returns nothing

### ISSUE THREAD

**Issue by glensc** [facebook/hhvm#7384]
### HHVM Version
> HipHop VM 3.6.6 (rel)

### Standalone code, or other way to reproduce the problem
> php -r '$phar = new ReflectionExtension("phar");var_dump($phar->getVersion());'

### Expected result
> string(5) "2.0.2"

### Actual result
> string(0) ""

it is needed for box.phar:
https://github.com/box-project/box2/blob/gh-pages/installer.php#L48-L57

otherwise it's installer will fail:

the problem occurs under Travis-CI which has HHVM-3.6.6, but i think it's not implemented in newer versions either

i've created example job whose output can be seen:
https://travis-ci.org/glensc/eventum/builds/162610941
- [php 5.5](https://travis-ci.org/glensc/eventum/jobs/162610942)
- [php 5.6](https://travis-ci.org/glensc/eventum/jobs/162610943)
- [php 7](https://travis-ci.org/glensc/eventum/jobs/162610944)
- [hhvm](https://travis-ci.org/glensc/eventum/jobs/162610945)
- [php-nightly](https://travis-ci.org/glensc/eventum/jobs/162610946)

**Comment by aorenste** [comment]
Fixed in c544f595

**Comment by glensc** [comment]
looks like travis is using end of LTS support version 3.6:

https://docs.hhvm.com/hhvm/installation/introduction#lts-releases

LTS VERSION | RELEASE DATE | END OF SUPPORT
-------------------- | ----------------------- | --------------------------
3.6	| 11 March 2015 | 1 March 2016
3.9 | 14 August 2015 | 15 July 2016
3.12 | 29 January 2016	| 30 December 2016

**Comment by aorenste** [comment]
This should land in 3.16.  It's unlikely that we would backport it to any previous version.
