### ISSUE TITLE
HHVM service fails to run on Azure & Google Cloud when VM is restarted

### ISSUE THREAD

**Issue by eeeehaw** [facebook/hhvm#7387]
### HHVM Version
3.14.5
### Standalone code, or other way to reproduce the problem
used with latest Facebook CTF open source project code (fbctf), NGINX used as webserver produces "502 Bad Gateway" error page when HHVM service is not running, running on Ubuntu 14.04 LTS, 'sudo service hhvm restart' fails to restart hhvm service, everything works fine after initial provisioning/deployment but HHVM does not start when Azure or Google Cloud virtual is restarted forcing admin to re-provision to get working again.
### Expected result
HHVM survives and starts/runs when Azure or Google Cloud virtual machine with Ubuntu 14.04 OS is restarted, allowing fbctf & nginx to operate properly.
### Actual result
HHVM runs immediately after FBCTF is provisioned & started on Azure or Google Cloud virtual machine (VM) running Ubuntu 14.04, but when the VM is stopped and started (or "restart") HHVM service is not running and cannot be restarted (all other prior services appear to be restarted and running).  This results in nginx producing a "502 Bad Gateway" error page.

**Comment by fredemmott** [comment]
There are way too many things here that aren't part of HHVM, and this is realistically never going to get looked at by the HHVM team; you either need to narrow this down, or follow up with FBCTF.

**Comment by eeeehaw** [comment]
FBCTF team has reported this as open Issue to HHVM 14 days ago I just learned (one of them at https://github.com/facebook/hhvm/issues/7333).  I feel like I may be entering the middle of a finger-pointing contest.  ;-(  At the moment it looks pretty clear that HHVM is the only component of my environment that is not surviving the machine restart.  

Please advise steps I can take to "narrow this down".  I will be as helpful as possible, just not sure what else I can do at this moment.

**Comment by fredemmott** [comment]
> FBCTF team has reported this as open Issue to HHVM 14 days ago 

Then this is effectively a dupe

> Please advise steps I can take to "narrow this down". I will be as helpful as possible, just not sure what else I can do at this moment.

Backtraces (check for core dumps), error messages, etc

**Comment by eeeehaw** [comment]
Sorry, Fred, I did not discover the FBCTF Issue report (due to the 
search keywords I used before) until after posting my issue.

Here's some info on HHVM logs that may be helpful (the error.log was 
empty, or more accurately had several blank lines with no text):
----------------------
eeeehaw@cyberwars-vm1:/var/log/hhvm$ ls -al
total 12
drwxrwxr-x  2 www-data www-data 4096 Sep 26 19:10 .
drwxrwxr-x 12 root     syslog   4096 Sep 26 21:55 ..
-rw-rw-rw-  1 root     root      862 Sep 26 21:16 access.log
-rw-rw-r--  1 www-data www-data    0 Aug 16 01:33 error.log
eeeehaw@cyberwars-vm1:/var/log/hhvm$ tail error.log
eeeehaw@cyberwars-vm1:/var/log/hhvm$ tail access.log
73.19.22.162 - - [24/Sep/2016:04:39:22 +0000] "GET / HTTP/1.1" 200 862
73.19.22.162 - - [24/Sep/2016:04:39:30 +0000] "GET /index.php?page=login 
HTTP/1.1" 200 991
73.19.22.162 - - [24/Sep/2016:04:39:40 +0000] "POST 
/index.php?p=index&ajax=true HTTP/1.1" 200 62
73.19.22.162 - - [24/Sep/2016:04:39:40 +0000] "GET /index.php?p=admin 
HTTP/1.1" 200 2017
73.19.22.162 - - [24/Sep/2016:04:39:47 +0000] "GET 
/index.php?p=action&modal=logout HTTP/1.1" 200 267
73.19.22.162 - - [24/Sep/2016:04:39:47 +0000] "GET 
/index.php?p=action&modal=logout HTTP/1.1" 200 267
73.19.22.162 - - [24/Sep/2016:04:39:50 +0000] "GET /index.php?p=logout 
HTTP/1.1" 302 -
73.19.22.162 - - [24/Sep/2016:04:39:50 +0000] "GET /index.php HTTP/1.1" 
200 862
73.19.22.162 - - [26/Sep/2016:19:18:28 +0000] "GET / HTTP/1.1" 200 862
73.19.22.162 - - [26/Sep/2016:21:16:28 +0000] "GET / HTTP/1.1" 200 862
eeeehaw@cyberwars-vm1:/var/log/hhvm$
--------------------------

I'll see if I can find a debug package to install/run.  Meanwhile, let 
me know what other cli you'd like to see, but I'll likely need some 
specific cli.  Upfront: altho I've been thru Linux+ course and cert 
exam, I'm a newbie to Linux with little hands-on, so pls be gentle :-)

--Stephen

**Comment by eeeehaw** [comment]
More info that may be helpful; note missing "sock" entry after reboot:
------------
BEFORE rebooting and everything working:
eeeehaw@cyberwars-vm1:/var/run/hhvm$ ls -al
total 78592
drwxr-xr-x  2 www-data www-data      100 Sep 26 21:14 .
drwxr-xr-x 20 root     root          800 Sep 26 21:09 ..
-rw-r--r--  1 www-data www-data 80473088 Sep 26 21:14 hhvm.hhbc
-rw-r--r--  1 www-data www-data        4 Sep 26 21:15 pid
srwxrw----  1 www-data www-data        0 Sep 26 21:14 sock
eeeehaw@cyberwars-vm1:/var/run/hhvm$

AFTER rebooting and hhvm service not running:
eeeehaw@cyberwars-vm1:/var/run/hhvm$ ls -al
total 28
drwxr-xr-x  2 www-data www-data    80 Sep 26 21:55 .
drwxr-xr-x 20 root     root       800 Sep 26 21:57 ..
-rw-r--r--  1 www-data www-data 26624 Sep 26 21:55 hhvm.hhbc
-rw-r--r--  1 www-data www-data     0 Sep 26 21:55 pid
eeeehaw@cyberwars-vm1:/var/run/hhvm$ sudo service hhvm status
  * hhvm is not running
eeeehaw@cyberwars-vm1:/var/run/hhvm$

**Comment by fredemmott** [comment]
Sorry - I didn't mean that this is an FBCTF problem (if HHVM's shutting down by itself  except for things like running out of memory and 3.15 needs more) - just that the HHVM team does not investigate issues with specific frameworks.

 - logs and application-generated errors are not helpful
 - PHP backtraces are usually not helpful
 - system-level backtraces (i.e. showing the trace within C++ itself) and error messages from dmesg, or hhvm itself, not the code, are
