### ISSUE TITLE
Official HHVM package for ArchLinux gone?

### ISSUE THREAD

**Issue by TheAifam5** [facebook/hhvm#7400]
Hey,
Right now there is any available package for HHVM.
Without any reason HHVM package was removed from Community.
Please edit the actual Wiki for prebuild Arch package.

Are you planning to add the official HHVM package for ArchLinux community? :(

https://github.com/facebook/hhvm/wiki/Prebuilt-Packages-on-Arch-Linux)

**Comment by Orvid** [comment]
I don't believe we've ever had an official HHVM package for arch linux.

**Comment by paulbiss** [comment]
Pretty sure it was community maintained, someone needs to take over packaging on Arch if it's gone. In the meantime feel free to update the wiki.

**Comment by simonwelsh** [comment]
It got moved from the Arch community repo to AUR because of facebook/folly#463. Related to that, it's currently very difficult to get HHVM running on Arch.

**Comment by jesseschalken** [comment]
Last I checked (Sep 21) master compiled on Arch by suppressing these package upgrades

```
extra/boost         1.60.0-5 -> 1.61.0-2
extra/boost-libs    1.60.0-5 -> 1.61.0-2
community/oniguruma 6.0.0-1  -> 6.1.1-1
```

and including [this fix](https://github.com/facebook/hhvm/pull/7374) (now in master).

**Comment by jesseschalken** [comment]
You now also need to downgrade the `re2` package to version `20160301-1`.

**Comment by beefsack** [comment]
For those just wanting the Hack tools (hh_server, hh_client, hh_format and others) I've created an AUR package just for those as they don't depend on the old version of Boost: https://aur.archlinux.org/packages/hhvm-hack-git/

**Comment by Orvid** [comment]
Folly now builds against 1.61+ so the upgrades shouldn't need to be suppressed once I update third-party.

**Comment by jesseschalken** [comment]
@Orvid https://github.com/facebook/folly/issues/413 is still open though?

I didn't look at it very closely, but the incompatibilities with oniguruma 6.1 and re2 20160901 appear to be independent of the Boost 1.61 incompatibility.

**Comment by Orvid** [comment]
There, problem solved :P (I hadn't closed the issue yet). Not sure why oniguruma or re2 would be causing issues though. If they are causing issues, they should be compile errors rather than link errors, shouldn't they?

**Comment by jesseschalken** [comment]
Only `re2` is a link-time error, `oniguruma` is a compiler-time error. I wasn't able to figure either one out, so someone with who knows C++ better than I do will have to take a look.

**Comment by Ppjet6** [comment]
I am running boot 1.62 and I see the following error when building the package for aur/hhvm-git.

It should include the correct file since the condition in facebook/folly's [823ecf8](https://github.com/facebook/folly/commit/823ecf8917d7f0534ed02b8d38bfc966cb0fd7b6) (as per facebook/folly#413) is on >= 106100, and I have 106200.

```
hhvm-git/src/hhvm/third-party/folly/folly/fibers/BoostContextCompatibility.h:18:10: fatal error: 'boost/context/fcontext.hpp' file not found
```

**Comment by Ppjet6** [comment]
I most likely found the error, and opened an issue at facebook/hhvm#7482, it wasn't really smart of me to post on this closed issue in the first place.

**Comment by TheAifam5** [comment]
So, this package for ArchLinux works good: https://aur.archlinux.org/packages/hhvm-hack-git/

But doesn't have standard configuration so :(

**Comment by beefsack** [comment]
I left a comment on the package page you linked but I don't believe the Hack tools require a configuration from the package, the user can supply one themselves if they need it but it works without it.

Probably best to continue the conversation on the package page if you feel there is a strong reason to include a config.

**Comment by jesseschalken** [comment]
On current `master` (https://github.com/facebook/hhvm/commit/d0d6968c4e), the only necessary downgrade is `re2 (20160901-1 => 20160301-1)`, but it otherwise builds and runs fine.

**Comment by nos1609** [comment]
@Ppjet6 any success on a fresh build?

**Comment by Ppjet6** [comment]
On 2017/04/23, Aleksei Nosachev wrote:
> @Ppjet6 any success on a fresh build?

I just had a quick look, I reported one bug that's linked to the
PKGBUILD on the AUR tracker already, and I have this error when
building:

```
[  9%] Building CXX object third-party/folly/CMakeFiles/folly.dir/src/folly/io/IOBufQueue.cpp.o
[  9%] Building CXX object third-party/folly/CMakeFiles/folly.dir/src/folly/io/RecordIO.cpp.o
[  9%] Building CXX object third-party/folly/CMakeFiles/folly.dir/src/folly/io/ShutdownSocketSet.cpp.o
[  9%] Building CXX object third-party/folly/CMakeFiles/folly.dir/src/folly/io/async/AsyncPipe.cpp.o
In file included from /home/ppjet/abs/hhvm-git/src/hhvm/third-party/folly/src/folly/io/async/AsyncPipe.cpp:16:
In file included from /home/ppjet/abs/hhvm-git/src/hhvm/third-party/folly/src/folly/io/async/AsyncPipe.h:18:
In file included from /home/ppjet/abs/hhvm-git/src/hhvm/third-party/folly/src/folly/io/async/AsyncTransport.h:25:
/home/ppjet/abs/hhvm-git/src/hhvm/third-party/folly/src/folly/io/async/ssl/OpenSSLPtrTypes.h:69:49: error: use of undeclared identifier 'EVP_MD_CTX_destroy'
    folly::static_function_deleter<EVP_MD_CTX, &EVP_MD_CTX_destroy>;
                                                ^
/home/ppjet/abs/hhvm-git/src/hhvm/third-party/folly/src/folly/io/async/ssl/OpenSSLPtrTypes.h:70:55: error: unknown type name 'EvpMdCtxDeleter'; did you mean 'EvpPkeyCtxDeleter'?
using EvpMdCtxUniquePtr = std::unique_ptr<EVP_MD_CTX, EvpMdCtxDeleter>;
                                                      ^~~~~~~~~~~~~~~
                                                      EvpPkeyCtxDeleter
/home/ppjet/abs/hhvm-git/src/hhvm/third-party/folly/src/folly/io/async/ssl/OpenSSLPtrTypes.h:62:7: note: 'EvpPkeyCtxDeleter' declared here
using EvpPkeyCtxDeleter =
      ^
2 errors generated.
make[2]: *** [third-party/folly/CMakeFiles/folly.dir/build.make:2055: third-party/folly/CMakeFiles/folly.dir/src/folly/io/async/AsyncPipe.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:352: third-party/folly/CMakeFiles/folly.dir/all] Error 2
make: *** [Makefile:128: all] Error 2
```

Trying to build commit 2b0220e427e43675186e8b4c3c1d24e170866244.

cmake: 3.8.0
clang: 4.0.0
boost: 1.63

I'll have another try during the weekend.

-- 
Maxime Buquet
