### ISSUE TITLE
how HHVM handles includes, specifically variables' context

### ISSUE THREAD

**Issue by Shereen92** [facebook/hhvm#7406]
HHVM version 3.15.1

### Example of a php code that involves one included file:
*** index.php ***
<?php
include('inc/inc.php');
print $x;
?>

*** inc.php ***
<?php
$str = "hello";
$x = -1;
?>

I get the following HHVM bytecode: 

========== inc/inc.php ==========
Pseudo-main at 0
maxStackCells: 3
numLocals: 2
numIterators: 0
  // line 3
    0: String "hello"
    5: **SetL L:0**
    7: PopC
  // line 4
    8: Int -1
   17: **SetL L:1**
   19: PopC
   20: Int 1
   29: RetC
Pseudo-main at 0
maxStackCells: 3
numLocals: 2
numIterators: 0

========== index.php ==========
Pseudo-main at 0
maxStackCells: 2
numLocals: 1
numIterators: 0
  // line 3
    0: String "inc/inc.php"
    5: Incl
    6: PopC
  // line 4
    7: **CGetL L:0**
    9: Print
   10: PopC
   11: Int 1
   20: RetC
Pseudo-main at 0
maxStackCells: 2
numLocals: 1
numIterators: 0

Even though it works correctly and prints -1 (which is $x) but I'm confused about how the variables (locals) get associated from the main file "index.php" to the included file "inc.php". Isn't they supposed to be named the same (Local 0 in index.php is the same as local 0 in inc.php) or is there something I'm missing on how hhvm deals with variables inside included files?

**Comment by ricklavoie** [comment]
When we execute the Incl opcode, we copy all the values in the caller's environment into the callee's environment, by name. When we return, we do the opposite, copying the callee's environment back into the caller's. This is done by name, so the locals can be in different slots in the different environments. So, in this example, when we return, we copy the value in local slot #1 in inc.php into local slot #0 in index.php. See https://github.com/facebook/hhvm/blob/master/hphp/runtime/vm/name-value-table.cpp#L102-L141

**Comment by mofarrell** [comment]
@Shereen92 If you have additional questions about this reopen.
