### ISSUE TITLE
benchy.py triggers hack type error in command_line_lib.php:171

### ISSUE THREAD

**Issue by ghost** [facebook/hhvm#7407]
I tried to run benchy.py from the tools directory, but it seems to trigger
a hack type error in line 171 of command_line_lib.php.
### HHVM Version

git master (0f424317f905bbd609e2664ea329a4ee63820560)
### Standalone code, or other way to reproduce the problem

I created a ~/.benchy (based on dot-benchy) and started benchy via

> hphp/tools/benchy/benchy.py --suite php-octane master

The cmake and build process finish successfully, but running the benchmarks
does not work:

> [1/20] master: HuffmanTraceback (most recent call last):
>   File "/home/cmuellner/src/hhvm/hphp/tools/benchy/any_mean.py", line 132, in <module>
>     main()
>   File "/home/cmuellner/src/hhvm/hphp/tools/benchy/any_mean.py", line 122, in main
>     infile = open(args.file, 'r')
> IOError: [Errno 2] No such file or directory: '/home/cmuellner/src/hhvm_work/runlog.1'
> Traceback (most recent call last):
>   File "hphp/tools/benchy/benchy.py", line 305, in <module>
>     main()
>   File "hphp/tools/benchy/benchy.py", line 283, in main
>     process_results(branches, output_mode)
>   File "hphp/tools/benchy/benchy.py", line 193, in process_results
>     stdout=result_file)
>   File "/home/cmuellner/src/hhvm/hphp/tools/benchy/benchy_utils.py", line 30, in run_command
>     stderr=(stderr or sys.stderr))
>   File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['/home/cmuellner/src/hhvm/hphp/tools/benchy/any_mean.py', '--geomean', '/home/cmuellner/src/hhvm_work/runlog.1']' returned non-zero exit status 1

The runlog.1 file is missing, because the benchmark could not be started.
The runscript is created successfully and issues the following command:

> /home/cmuellner/src/hhvm/hphp/tools/hhvm_wrapper.php --compile --build-root=/home/cmuellner/src/hhvm_build/master/hphp   -- /home/cmuellner/src/hhvm/hphp/benchmarks/php-octane/harness-run.ph

When issuing the command on the command line, the following output is generated:

/home/cmuellner/src/hhvm/hphp/tools/hhvm_wrapper.php --compile --build-root=/home/cmuellner/src/hhvm_build/master/hphp   -- /home/cmuellner/src/hhvm/hphp/benchmarks/php-octane/harness-run.php

> Catchable fatal error: Hack type error: You are trying to access the member add but this is not an object, it is a bool at /home/cmuellner/src/hhvm/hphp/tools/command_line_lib.php line 171

**Comment by a--hoang** [comment]
This can be closed, benchy was removed in https://github.com/facebook/hhvm/commit/5e64be1c484c5746e098c5eb7119a12630ea0a1a

@cmuellnerTheobromaSystems

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Closing, bency was indeed removed in 5e64be1.
