### ISSUE TITLE
hhvm in aarch64

### ISSUE THREAD

**Issue by JohnGW05** [facebook/hhvm#7416]
### HHVM Version

3.16.0-dev (rel)
### Standalone code, or other way to reproduce the problem

when we are trying to run hhvm as a web server and as a fastcgi mode engine, the Jit didn’t work when we had passed hhvm.jit=true to the daemon. We used these two method as  https://docs.hhvm.com/hhvm/basic-usage/server referenced, using pointed config file /etc/hhvm/server.ini and command line passed –d hhvm.jit=true, but they all didn’t work. 
could anyone give me help and advise? thank you very much
### Expected result

Jit worked
### Actual result

Jit didn't work

**Comment by paulbiss** [comment]
The architecture ports are all still very experimental, I'm not sure what state they were in when 3.16 was cut. cc @mxw

**Comment by aorenste** [comment]
Can you explain in more detail about "Jit didn't work"? Is it crashing? How do you know that Jit isn't working?

**Comment by JohnGW05** [comment]
thank you ，You can recurrence the test environment in this way:
一、start up hhvm as proxygen in arm server
Hhvm reversion:
root@localhost:~/gw05/hhvm# /usr/local/bin/hhvm --version
HipHop VM 3.16.0-dev (rel)
Compiler: heads/master-0-g8920e2cd8f9251978713612dcc6891d7334a5d96
Repo schema: 922cef7ce4ceb4cc7b7ff58c0cc0972ee69ae429

Put the following test_cpu.php in the current  dir and run following command:
hhvm -m daemon -d hhvm.server.type=proxygen -d hhvm.server.port=8080 -d hhvm.jit=1

Run test_cpu.php in the local server:
root@localhost:~/gw05/hhvm# /usr/local/bin/hhvm -vEval.Jit=1 test_cpu.php
fib(36) = 14930352
test used  0.497519 second

二、commit the request to run test_cpu.php from client：
curl "http://10.130.48.73:8080/test_cpu.php"
fib(36) = 14930352
test used  10.343394 second

So Compare the result of test_cpu.php, we can see hhvm didn’t open jit when run as daemon


test_cpu.php
=========================
<?php
$x = gettimeofday("return_float");
function fib($n)
{
        if ($n <= 2)
                return 1;
        else
                return fib($n - 1) + fib($n - 2);
}
$n = 36;
printf("fib(%d) = %d\n", $n, fib($n,2));
$y = gettimeofday("return_float");
printf("test used  %f second\n",$y-$x)
?>
===========================

**Comment by cmuellnerTheobromaSystems** [comment]
Here are the results of that code run on our merlin via HHVM
(from a recent commit from master branch):

cmuellner@merlin1:/mnt/cmuellner/hhvm$ ./hphp/hhvm/hhvm --version
HipHop VM 3.16.0-dev (rel)
Compiler: heads/master-0-g8a300ec84994e9af86e74a0bde0b17650756ef73
Repo schema: 34952e91ec09070a017ee651428369c6c4c1a43c

cmuellner@merlin1:/mnt/cmuellner/hhvm$ ./hphp/hhvm/hhvm -vEval.Jit=0 test_cpu.php
fib(36) = 14930352
test used 13.043785 second
cmuellner@merlin1:/mnt/cmuellner/hhvm$ ./hphp/hhvm/hhvm -vEval.Jit=1 test_cpu.php
fib(36) = 14930352
test used 1.722911 second
cmuellner@merlin1:/mnt/cmuellner/hhvm$ ./hphp/hhvm/hhvm -vEval.Jit=0 test_cpu.php
fib(36) = 14930352
test used 13.115950 second
cmuellner@merlin1:/mnt/cmuellner/hhvm$ ./hphp/hhvm/hhvm -vEval.Jit=1 test_cpu.php
fib(36) = 14930352
test used 0.487373 second

**Comment by Orvid** [comment]
When run through proxygen you have to call a few times, otherwise you're still in profiling mode by default.

**Comment by mofarrell** [comment]
This issue has been waiting for more info for more than 2 weeks. I'm closing it for now, but feel free to re-open it if you can provide more info. https://github.com/facebook/hhvm/wiki/Human-Timeouts
