### ISSUE TITLE
Hack: Error when a method overrides another without using <<__Override>>

### ISSUE THREAD

**Issue by jesseschalken** [facebook/hhvm#7417]
### HHVM Version

```
HipHop VM 3.16.0-dev (rel)
Compiler: heads/master-0-ge9eb3fc414fbae9b2c999a4f11390e23050b23b7
Repo schema: 9cc0ebe15bc9d2ba3609c5e4458deeef9ed86dcc
```
### Standalone code, or other way to reproduce the problem

``` php
<?hh // strict

class Base {
  public function method():void {
  }
}

class Sub extends Base {
  public function method():void {
    print "method() overridden";
  }
}
```

Rename `Base::method`:

``` php
<?hh // strict

class Base {
  public function method2():void {
  }
}

class Sub extends Base {
  public function method():void {
    print "method() overridden";
  }
}
```

The way in which `Sub` extends `Base` has now changed, but no type error is produced to indicate that a method was overridden and no longer is.
### Expected result

Original code produces error: "`Sub::method` overrides `Base::method` but does not use `<<__Override>>`."
### Actual result

No errors.
### Discussion

The `<<__Override>>` attribute is very useful for renaming methods that may be overridden (you just change the name and the overrides with the old name show up as errors).

However, it's only useful insofar as you have a guarantee that all methods that are intended to override actually have the `<<__Override>>` attribute, but this is not enforced by Hack.

Request: Make it an error to override a method without using the `<<__Override>>` attribute.

**Comment by lexidor** [comment]
This issue has been addressed via the MustUseOverrideLinter in hhast (with a near-100%-fidelity) and fully by the HHClientLinter. Not adding an `__Override` if one could use it is now a lint error. This seems like the correct error level for this, since it isn't a hard error (provided the signatures are compatible).
