### ISSUE TITLE
Compilation issue on Centos 6.8

### ISSUE THREAD

**Issue by vernesto84** [facebook/hhvm#7419]
Hi Guys, i have an issue trying to compile the hhvm for my server on Centos6.8, i only find this tutorial to follow:
https://github.com/facebook/hhvm/wiki/building-and-installing-hhvm-on-centos-6.6#5-install-boost-version-1580.

I have installed all dependencies and folow all steps but when im compiling the hhvm, doing : 
sudo make
I got the following error :

> Scanning dependencies of target hphp_hhbbc
> [ 53%] Building CXX object hphp/hhbbc/CMakeFiles/hphp_hhbbc.dir/main.cpp.o
> [ 53%] Building CXX object hphp/hhbbc/CMakeFiles/hphp_hhbbc.dir/peephole.cpp.o
> [ 53%] Building CXX object hphp/hhbbc/CMakeFiles/hphp_hhbbc.dir/show.cpp.o
> /usr/local/hhvm/hphp/hhbbc/show.cpp: In lambda function:
> /usr/local/hhvm/hphp/hhbbc/show.cpp:203:5: error: no matching function for call to ‘match(const boost::variant<HPHP::HHBBC::php::FaultRegion, HPHP:
> :HHBBC::php::TryRegion>&, HPHP::HHBBC::php::show(const HPHP::HHBBC::php::Func&)::__lambda82::__lambda83, HPHP::HHBBC::php::show(const HPHP::HHBBC::
> php::Func&)::__lambda82::__lambda84)’
>      ) + '\n';
>      ^
> /usr/local/hhvm/hphp/hhbbc/show.cpp:203:5: note: candidates are:
> In file included from /usr/local/hhvm/hphp/hhbbc/misc.h:26:0,
>                  from /usr/local/hhvm/hphp/hhbbc/bc.h:32,
>                  from /usr/local/hhvm/hphp/hhbbc/representation.h:35,
>                  from /usr/local/hhvm/hphp/hhbbc/show.cpp:16:
> /usr/local/hhvm/hphp/util/match.h:99:1: note: template<class Ret, class Var, class ... Funcs> typename std::enable_if<HPHP::match_detail::is_varian
> t<typename std::remove_cv<U>::type>::value, Ret>::type HPHP::match(Var&, Funcs&& ...)
>  match(Var& v, Funcs&&... funcs) {
>  ^
> /usr/local/hhvm/hphp/util/match.h:99:1: note:   template argument deduction/substitution failed:
> /usr/local/hhvm/hphp/util/match.h: In substitution of ‘template<class Ret, class Var, class ... Funcs> typename std::enable_if<HPHP::match_detail::
> is_variant<typename std::remove_cv<U>::type>::value, Ret>::type HPHP::match(Var&, Funcs&& ...) [with Ret = std::basic_string<char>; Var = const boo
> st::variant<HPHP::HHBBC::php::FaultRegion, HPHP::HHBBC::php::TryRegion>; Funcs = {HPHP::HHBBC::php::show(const HPHP::HHBBC::php::Func&)::__lambda82
> ::__lambda83, HPHP::HHBBC::php::show(const HPHP::HHBBC::php::Func&)::__lambda82::__lambda84}]’:
> /usr/local/hhvm/hphp/hhbbc/show.cpp:203:5:   required from here
> /usr/local/hhvm/hphp/util/match.h:99:1: error: no type named ‘type’ in ‘struct std::enable_if<false, std::basic_string<char> >’
> /usr/local/hhvm/hphp/util/match.h:112:1: note: template<class Ret, class Var, class ... Funcs> typename std::enable_if<HPHP::match_detail::is_discr
> iminated_ptr<typename std::remove_cv<U>::type>::value, Ret>::type HPHP::match(Var&, Funcs&& ...)
>  match(Var& v, Funcs&&... funcs) {
>  ^
> /usr/local/hhvm/hphp/util/match.h:112:1: note:   template argument deduction/substitution failed:
> /usr/local/hhvm/hphp/util/match.h: In substitution of ‘template<class Ret, class Var, class ... Funcs> typename std::enable_if<HPHP::match_detail::
> is_discriminated_ptr<typename std::remove_cv<U>::type>::value, Ret>::type HPHP::match(Var&, Funcs&& ...) [with Ret = std::basic_string<char>; Var =
>  const boost::variant<HPHP::HHBBC::php::FaultRegion, HPHP::HHBBC::php::TryRegion>; Funcs = {HPHP::HHBBC::php::show(const HPHP::HHBBC::php::Func&)::
> __lambda82::__lambda83, HPHP::HHBBC::php::show(const HPHP::HHBBC::php::Func&)::__lambda82::__lambda84}]’:
> /usr/local/hhvm/hphp/hhbbc/show.cpp:203:5:   required from here
> /usr/local/hhvm/hphp/util/match.h:112:1: error: no type named ‘type’ in ‘struct std::enable_if<false, std::basic_string<char> >’
> make[2]: **\* [hphp/hhbbc/CMakeFiles/hphp_hhbbc.dir/show.cpp.o] Error 1
> make[1]: **\* [hphp/hhbbc/CMakeFiles/hphp_hhbbc.dir/all] Error 2
> make: **\* [all] Error 2

Could anyone help me with this, i dont know what else to do, thanks

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Sorry, it looks like nobody got around to answering your question. CentOS is not a supported distribution for hhvm (in 2023).
