### ISSUE TITLE
h2tp: "$a" is converted to $a

### ISSUE THREAD

**Issue by jesseschalken** [facebook/hhvm#7424]
### HHVM Version

```
HipHop VM 3.16.0-dev (rel)
Compiler: heads/master-0-ge9eb3fc414fbae9b2c999a4f11390e23050b23b7
Repo schema: 9cc0ebe15bc9d2ba3609c5e4458deeef9ed86dcc
```
### Standalone code, or other way to reproduce the problem

``` php
<?hh

$a = 1;
print \is_string("$a");
```

Run `h2tp` on file.
### Expected result

``` php
<?php
require_once ($GLOBALS["HACKLIB_ROOT"]);
$a = 1;
echo (\is_string("$a"));
```
### Actual result

``` php
<?php
require_once ($GLOBALS["HACKLIB_ROOT"]);
$a = 1;
echo (\is_string($a));
```

The conversion to a string via variable interpolation is lost.

**Comment by jesseschalken** [comment]
Since `"{$a}foo"` is converted to `$a."foo"`, my guess is that it converts interpolated variables to a list of expressions to be concatenated together, and if that list of expressions contains 1 element, it emits it directly since it has nothing to concat it with. A special case would be needed for an expr list of 1 element so it is emitted as `$a.""`.

**Comment by paulbiss** [comment]
Just to set some expectations here, there isn't anyone who's currently maintaining h2tp. If you or someone else from the community would like to fix this we'd gladly take a pull request but it's unlikely any of us will have the bandwidth to look at h2tp related issues right now.

**Comment by paulbiss** [comment]
Aha, I just saw https://github.com/facebook/hhvm/pull/7427

**Comment by SiebelsTim** [comment]
h2tp is dead. This can be closed I guess.

**Comment by Pacerier** [comment]
Re "there isn't anyone who's currently maintaining h2tp", https://github.com/facebook/hhvm/issues/2236#issuecomment-346159936

**Comment by fredemmott** [comment]
If someone in the community wants to build a replacement, https://github.com/hhvm/hhast could be a good starting point.

**Comment by fredemmott** [comment]
We won't be revisiting our decision to drop support for H2TP; we expect Hack and PHP to continue to diverge, to the point where targeting PHP for cross-compilation won't make more sense than any other language.
