### ISSUE TITLE
key builtin does not work on cast objects

### ISSUE THREAD

**Issue by drewklein** [facebook/hhvm#7428]
### HHVM Version
hhvm-3.12.0 - 3.14.4

### Standalone code, or other way to reproduce the problem
https://3v4l.org/dFNRo

### Expected result
bool(false)
int(1)
### Actual result
bool(false)

Warning: Invalid operand type was used: expecting an array in /in/dFNRo on line 4
bool(false)

**Comment by paulbiss** [comment]
https://docs.hhvm.com/hhvm/inconsistencies/classes-and-objects#object-internal-cursors
