### ISSUE TITLE
How to use SSL certificates with Proxygen 

### ISSUE THREAD

**Issue by raeesbhatti** [facebook/hhvm#7429]
### HHVM Version
HHVM 3.15.2

### Standalone code, or other way to reproduce the problem
Try to run Proxygen with these parameters in server.ini:
```ini
hhvm.server.enable_ssl = true
hhvm.server.ssl_port = 8443
hhvm.server.ssl_certificate_dir = /etc/hhvm/certs/example.com
hhvm.server.ssl_certificate_file = /etc/hhvm/certs/example.com/fullchain.pem
hhvm.server.ssl.certificate_key_file = /etc/hhvm/certs/example.com/privkey.pem
```
There are four certificate files `cert.pem`,`chain.pem`,`fullchain.pem`,`privkey.pem` provided by Let's Encrypt.
### Expected result
Proxygen would work as expected and serve encrypted HTTP on port 8443.
### Actual result
HHVM crashes with these errors:
```
hhvm_1     | Invalid certificate file or key file
hhvm_1     | Core dumped: Segmentation fault
hhvm_1     | Stack trace in /tmp/stacktrace.1.log
```
stacktrace.1.log is useless:
```

PHP Stacktrace:


```

**Comment by raeesbhatti** [comment]
It turns out that `hhvm.server.ssl.certificate_file` requires `cert.pem` (server certificate only) and `hhvm.server.ssl.certificate_key_file` requires `privkey.pem` (private key). And the paths to these files should be absolute.

And `PHP Stacktrace` was empty most likely because I was on a normal build instead of a debug one.

**Comment by raeesbhatti** [comment]
But these options and other quirks for HHVM Proxygen are hugely under-documented. I had to spend a lot of time trying to figure out what the problem was only because these behaviors were not documented.

**Comment by jesseschalken** [comment]
If `hhvm.server.ssl.certificate_file` doesn't contain the whole chain where does it get the intermediate certificates from? From `hhvm.server.ssl_certificate_dir`?

**Comment by raeesbhatti** [comment]
To my knowledge there is actually [no configurable parameter](https://github.com/facebook/hhvm/blob/ca168e2bc50d8e1840d9378c6e57a525a6e8d047/hphp/runtime/server/proxygen/proxygen-server.cpp#L653-L679) to specify intermediate certificates in HHVM Proxygen.

**Comment by jesseschalken** [comment]
Does that mean certificates that need intermediate certificates aren't supported, or does HHVM not need them? (I'm asking both you and the HHVM team)

**Comment by raeesbhatti** [comment]
Weird enough I am able to use `fullchain.pem` now for `hhvm.server.ssl_certificate_file` also which is exactly what I was doing previously when it was not working. Nevertheless, I guess this is how you specify intermediate certificates.

**Comment by fredemmott** [comment]
Looks like the fix for you was:

```
-hhvm.server.ssl.certificate_key_file
+hhvm.server.ssl_certificate_file
```

Likely originally from the documentation typo in the commit I just attached. Same as #8061
