### ISSUE TITLE
http_build_query numeric_prefix php7

### ISSUE THREAD

**Issue by belka-ew** [facebook/hhvm#7431]
### HHVM Version
Compiler: tags/HHVM-3.15.2-0-g83ac3e5e3f5657be0cf4c55884044f86a7818b90
Repo schema: 608339137764e8365964a1adaa7a27d125b6076f

### Standalone code, or other way to reproduce the problem
```php
<?php
$query = array(
	'version'            => "4.6.1",
	'php'                => "7.0.99-hhvm",
	'locale'             => "de_DE",
	'mysql'              => "5.5.5",
	'local_package'      => "de_DE",
	'blogs'              => 1,
	'users'              => 5,
	'multisite_enabled'  => 0,
	'initial_db_version' => 27916,
);
var_dump(http_build_query($query, null, "&"));
```

### Expected result
string(135) "version=4.6.1&php=7.0.99-hhvm&locale=de_DE&mysql=5.5.5&local_package=de_DE&blogs=1&users=5&multisite_enabled=0&initial_db_version=27916"

### Actual result
NULL

If the second argument of `http_build_query` is `null` it returns `null`. This happens only for php7 mode, works fine for php5. I would make a pull request, but since it is related only to php7 and  as it seems, not to the function implementation itself, I have no idea where to look for the bug.

**Comment by aorenste** [comment]
https://3v4l.org/WPV2m
This looks like a typechecker problem.   Probably the second parameter of http_build_query needs to be `?string` instead of `string` - which also implies that in the .cpp file it needs to change from `String` to `Variant`.

**Comment by belka-ew** [comment]
Ok, thanks. I'll look into till the weekend and test if I can get it working. And I'll add a unit test in the case of success

**Comment by belka-ew** [comment]
Can it be that http_build_query in [hphp/hack/hhi/stdlib/builtins_url.hhi#L25](https://github.com/facebook/hhvm/blob/10b4a1aeb38979d8632ab7496ddab390777f6b2d/hphp/hack/hhi/stdlib/builtins_url.hhi#L25) is missing the last parameter (enc_type)?

**Comment by aorenste** [comment]
@belka-ew I think you're right
