### ISSUE TITLE
Missing PDO::MYSQL_ATTR_MULTI_STATEMENTS constant

### ISSUE THREAD

**Issue by caioiglesias** [facebook/hhvm#7434]
HipHop VM 3.16.0-dev (rel)

step to reproduce: `print_r(PDO::MYSQL_ATTR_MULTI_STATEMENTS);`

expected: `1013`

actual: `\nFatal error: Couldn't find constant PDO::MYSQL_ATTR_MULTI_STATEMENTS in /.../Mysql.php on line 342`

This error prevents Magento 2.1.2 from completing the installation.

**Comment by Orvid** [comment]
This should be fairly trivial to implement, https://github.com/php/php-src/blob/6053987bc27e8dede37f437193a5cad448f99bce/ext/pdo_mysql/mysql_driver.c#L568

It's just a flag being passed to MySQL itself.

**Comment by aftabnaveed** [comment]
Same error on HHVM 3.18

**Comment by caioiglesias** [comment]
well @aftabnaveed ... it hasn't been implemented yet.

**Comment by halid** [comment]
I'm getting the same error.

version: HHVM 3.18

**Comment by racardoso** [comment]
I made a PR to fix this issue https://github.com/facebook/hhvm/pull/7737

**Comment by jesseschalken** [comment]
This was fixed in https://github.com/facebook/hhvm/commit/b07bca0f325155a435f05329b2660711557af065

https://3v4l.org/6VS1h (not sure why Zend versions don't have that constant defined on 3v4l.org)
