### ISSUE TITLE
MySQL SSL not working with just some SSL attributes

### ISSUE THREAD

**Issue by schmittjoh** [facebook/hhvm#7436]
### HHVM Version
HipHop VM 3.16.0-dev (rel)
Compiler: heads/master-0-g04ae377b260dbc7ad34d88c31e9595e1ada50e69
Repo schema: a4233923e1fc5628a4d1146e99ff0cd8264ecfa3

### Standalone code, or other way to reproduce the problem
```php
new \PDO('mysql:host=localhost;dbname=test;', 'root', '', array(
    \PDO::ATTR_MYSQL_SSL_CA => 'path-to-ca.pem',
));
```

### Expected result
Connection to server is established.

### Actual result
SSL connection error: Failed to set ciphers to use

The problem here is that in the current implementation if one of the SSL related PDO attributes is not set, it passes on an empty string to mysql_set_ssl. Instead it should probably pass on null in such cases so that MySQL uses its default setting (see #5101).

The only way to get it to work is if you pass all of the SSL attributes, whether you need them or not. This behavior is different from vanilla PHP.

**Comment by aorenste** [comment]
I think this is fixed by #7423
