### ISSUE TITLE
CMake Error Cannot find source file: src/fastlz.c

### ISSUE THREAD

**Issue by nobicycle** [facebook/hhvm#7438]
Dear FB Team

**### HHVM Version**
commit 3fc74fcceffa633ce64c845d76e57bdc3c3f6d6f
Date:   Sat Oct 22 04:26:25 2016 -0700
Differential Revision: D4051256

**### Standalone code, or other way to reproduce the problem**
After cloning hhvm repo ..
export CMAKE_PREFIX_PATH=`pwd`
git submodule update --init --recursive
cmake -DMYSQL_UNIX_SOCK_ADDR=/var/run/mysqld/mysqld.sock .

### Expected result
No cmake errors
**### Actual result**

> -- Configuring done
> CMake Error at third-party/fastlz/CMakeLists.txt:1 (add_library):
>   Cannot find source file:
> 
>     src/fastlz.c

The git submodule update --init --recursive was as follows

> Cloning into '/media/esata/SYSTEM/archives/Development/PHP/hhvm/third-party/folly/src'...
> Cloning into '/media/esata/SYSTEM/archives/Development/PHP/hhvm/third-party/libafdt/src'...
> Cloning into '/media/esata/SYSTEM/archives/Development/PHP/hhvm/third-party/libzip/src'...
> Cloning into '/media/esata/SYSTEM/archives/Development/PHP/hhvm/third-party/lz4/src'...
> Cloning into '/media/esata/SYSTEM/archives/Development/PHP/hhvm/third-party/mcrouter/src'...
> Cloning into '/media/esata/SYSTEM/archives/Development/PHP/hhvm/third-party/proxygen/src'...
> Cloning into '/media/esata/SYSTEM/archives/Development/PHP/hhvm/third-party/re2/src'...
> Cloning into '/media/esata/SYSTEM/archives/Development/PHP/hhvm/third-party/squangle/src'...
> Cloning into '/media/esata/SYSTEM/archives/Development/PHP/hhvm/third-party/thrift/src'...
> Cloning into '/media/esata/SYSTEM/archives/Development/PHP/hhvm/third-party/wangle/src'...
> Cloning into '/media/esata/SYSTEM/archives/Development/PHP/hhvm/third-party/webscalesqlclient/mysql-5.6'...
> Submodule path 'third-party/brotli/src': checked out '98ed7a23a83d64133b0a36a884e489bffb0eb864'
> Submodule 'terryfy' (https://github.com/MacPython/terryfy.git) registered for path 'third-party/brotli/src/terryfy'
> Cloning into '/media/esata/SYSTEM/archives/Development/PHP/hhvm/third-party/brotli/src/terryfy'...
> Submodule path 'third-party/brotli/src/terryfy': checked out '8bb673f4410819df06920fdcfd24e18d235d84f7'
> Submodule path 'third-party/double-conversion': checked out 'f1b955eee1cb94c51074878264aecdd6ee1350dd'
> Submodule path 'third-party/fatal': checked out 'dc8cac9aa5f3c7599b24854048536a62da88a2f1'
> Submodule path 'third-party/folly/src': checked out '6a7f9395dde570c8dc01ef489da9185170c52385'
> Submodule path 'third-party/libafdt/src': checked out 'eb021a100e761616b35ad62c910d6c336e0711d2'
> Submodule path 'third-party/libzip/src': checked out '1d8b1ac4d20b8ef8d3f5d496dabebaa0ff9019ff'
> Submodule path 'third-party/lz4/src': checked out 'd86dc916771c126afb797637dda9f6421c0cb998'
> Submodule path 'third-party/mcrouter/src': checked out 'df78ae376df9c16c28245138f04d7354ebe95418'
> Submodule path 'third-party/proxygen/src': checked out 'fab05a83c68dd9752ca46d722f4b3da836155191'
> Submodule path 'third-party/re2/src': checked out '718df09610fee584c9038d8d519697e507e09c9b'
> Submodule path 'third-party/squangle/src': checked out 'b948f82145c89d3d45d036f221ba4f79d6c65294'
> Submodule path 'third-party/thrift/src': checked out '0f4f595d714e927911c943b447d2bdd608cb2b98'
> Submodule path 'third-party/wangle/src': checked out 'f1c06aa17b5e94ffa69cc8bab172135a3ed5bc69'
> Submodule path 'third-party/webscalesqlclient/mysql-5.6': checked out 'a9e580b5a0baa768210ef10544c8fab52003ec0b'
> Submodule 'rocksdb' (https://github.com/facebook/rocksdb.git) registered for path 'third-party/webscalesqlclient/mysql-5.6/rocksdb'
> Cloning into '/media/esata/SYSTEM/archives/Development/PHP/hhvm/third-party/webscalesqlclient/mysql-5.6/rocksdb'...
> Submodule path 'third-party/webscalesqlclient/mysql-5.6/rocksdb': checked out 'dcc898b0215cee3b1baa88149c1f39e37e9bfd09'

**Comment by Orvid** [comment]
Make sure you have the latest version of third-party checked out. You're missing multiple dependencies from third-party.

**Comment by nobicycle** [comment]
Thanks for the suggestion Orvid. How would I do what you suggest?

> cd hhvm
> git clone https://github.com/hhvm/hhvm-third-party.git

?

Will this conflict with what has already been downloaded via "git submodule update --init --recursive" ?

**Comment by Orvid** [comment]
Easiest way is to wipe out your existing third-party directory and let git re-clone it:
```
cd hhvm
rm -rf third-party
git submodule update --init --recursive
```

**Comment by nobicycle** [comment]
Thanks again Orvid. Compilation is chugging along nicely, 15% so far.
The reason I was reticent to restart update from scratch is that  the first time I ran the official hhvm Debian instructions, the downloaded size went over 2 GB, at which point I cancelled.

I will put this incident down to an unknown quirk. :)

best wishes
