### ISSUE TITLE
Make - FOLLY_FBVECTOR_INSERT_END - misleadingly indented as if it is guarded by the ‘if’

### ISSUE THREAD

**Issue by nobicycle** [facebook/hhvm#7439]
### HHVM Version

> commit 3fc74fcceffa633ce64c845d76e57bdc3c3f6d6f
> Author: Andrew Kennedy akenn@fb.com
> Date:   Sat Oct 22 04:26:25 2016 -0700
> Differential Revision: D4051256
### Standalone code, or other way to reproduce the problem

> git submodule update --init --recursive
> export CMAKE_PREFIX_PATH=`pwd`
> cmake -DMYSQL_UNIX_SOCK_ADDR=/var/run/mysqld/mysqld.sock .
> rm -rf third-party
> git submodule update --init --recursive
> cmake -DMYSQL_UNIX_SOCK_ADDR=/var/run/mysqld/mysqld.sock .
> make -j 2

**### Expected result**
Successful make

**### Actual result**

>  FOLLY_FBVECTOR_INSERT_PRE(cpos, n)
>      ^~~~~~~~~~~~~~~~~~~~~~~~~
> /media/esata/SYSTEM/archives/Development/PHP/hhvm/third-party/folly/folly/FBVector.h:1475:5: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
> /media/esata/SYSTEM/archives/Development/PHP/hhvm/third-party/folly/folly/FBVector.h:1480:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
>      FOLLY_FBVECTOR_INSERT_END(cpos, n)
>      ^~~~~~~~~~~~~~~~~~~~~~~~~
> /media/esata/SYSTEM/archives/Development/PHP/hhvm/third-party/folly/folly/FBVector.h:1480:5: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
> make[1]: **\* [CMakeFiles/Makefile2:346: third-party/folly/CMakeFiles/folly.dir/all] Error 2
> make: **\* [Makefile:128: all] Error 2

**Comment by nobicycle** [comment]
I repeated the above for branch 3.15

> /media/esata/SYSTEM/archives/Development/PHP/hhvm/hphp/util/logger-inl.h: In static member function ‘static void HPHP::Logger::FVerbose(Args&& ...)’:
> /media/esata/SYSTEM/archives/Development/PHP/hhvm/hphp/util/logger-inl.h:31:1: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
>  IMPLEMENT_LOGLEVEL(Verbose)
>  ^~~~~~~~~~~~~~~~~~
> 
> > /media/esata/SYSTEM/archives/Development/PHP/hhvm/hphp/util/logger-inl.h:31:1: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
> > [ 11%] Building ASM object hphp/util/CMakeFiles/hphp_util.dir/hash-crc.S.o
> > [ 11%] Building ASM object hphp/util/CMakeFiles/hphp_util.dir/memcpy-x64.S.o
> > [ 11%] Building ASM object hphp/util/CMakeFiles/hphp_util.dir/memset-x64-avx2.S.o
> > [ 11%] Building ASM object hphp/util/CMakeFiles/hphp_util.dir/strcmp-sse42.S.o
> > [ 11%] Linking CXX static library libhphp_util.a
> > [ 11%] Built target hphp_util
> > make: *** [Makefile:128: all] Error 2
>

**Comment by mofarrell** [comment]
Could you put up a paste of the complete build logs?

**Comment by Orvid** [comment]
Also, which compiler, as it has absolutely no idea what it's talking about.

**Comment by drewklein** [comment]
FWIW, I'm seeing these warnings with gcc 6.2

**Comment by drewklein** [comment]
The warnings can be turned off with -Wno-misleading-indentation

**Comment by DemiMarie** [comment]
@drewklein I would advise against that – `-Wmisleading-indentation` catches bugs that are very hard to otherwise track down.  It would have caught Apple's infamous "goto fail;" bug.  Furthermore, I believe that it can always be worked around by reformatting the code.

**Comment by Orvid** [comment]
In this case the warning is wrong. The if statements _are_ enclosed in curly braces.

**Comment by mofarrell** [comment]
Has anyone been able to isolate the case that falsely triggers the warning?  We could file a bug with gcc if that is the case.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones unlikely to be resolved.

This issue demonstrates a build warning in gcc. This issue is very, very old, so maybe it's been fixed in gcc. Hhvm builds with clang only for now. I don't think leaving this issue open on the hhvm repo is likely to result in anything changing, even if the build warning would still be around.

If you are experiencing build warnings, don't let the closing of this issue discourage you from filing a new issue.
