### ISSUE TITLE
Provide a nicer way of setting allowed user attributes

### ISSUE THREAD

**Issue by HRMsimon** [facebook/hhvm#7440]
As far as I can tell, the only way to set multiple allowed user attributes is to stick them all on a single line in `.hhconfig`. This gets rather unwieldy rather quickly with even a handful of attributes define.

Some possible options:
- Allow multiple `user_attributes =` lines
- Have some way to mark a new line as non-terminating (a-la `\<newline>` in bash/C macros)

**Comment by kritisingh1** [comment]
Hi @HRMsimon I would like to work on this issue if it is still open. Can you please elaborate the work to be done a bit more?

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Hack has switched to a different manner of providing user_attribute specifications.
You now write a class like this, in which the constructor is the arguments you need to pass to the attribute.
An instance of this class with these values can be obtained via reflection.

```HACK
final class MyAttribute extends \HH\FunctionAttribute {
  public function __construct(public int $speed) {}
}

<<MyAttribute(1)>>
function slow(): void {}

<<MyAttribute(10)>>
function fast(): void {}
```

Passing something other than an int to `<<MyAttribute(_)>>` is a typeerror.
