### ISSUE TITLE
Missing dependencies on Debian

### ISSUE THREAD

**Issue by Daniel15** [facebook/hhvm#7441]
The current version of HHVM doesn't install on Debian:
```
The following packages have unmet dependencies:
 hhvm : Depends: libboost-filesystem1.55.0 but it is not installable
        Depends: libboost-program-options1.55.0 but it is not installable
        Depends: libboost-system1.55.0 but it is not installable
        Depends: libboost-regex1.55.0 but it is not installable
        Depends: libgnutls-deb0-28 but it is not installable
        Depends: libicu52 but it is not installable
        Depends: libboost-thread1.55.0 but it is not installable
        Depends: libboost-context1.55.0 but it is not installable
        Depends: libgoogle-glog0 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

It looks like most of these are an old version of Boost that was removed from Debian a while back: https://tracker.debian.org/pkg/boost1.55

**Comment by Orvid** [comment]
Which version of Debian? I would be surprised if they removed packages from an existing release.

**Comment by Daniel15** [comment]
I'm using Debian Testing. Looks like all boost1.55 packages are only available in stable, they were removed from testing a while back. I guess I could try to install the packages from stable onto my system, but they may depend on a different glibc version or something like that :(

I wonder if we could have an HHVM Debian package that's statically linked to avoid these problems.

**Comment by Daniel15** [comment]
Ahh I figured it out - They replaced it with Boost 1.61 (eg. ` libboost-filesystem1.61.0`). Would HHVM run with that version? Can we just update the dependencies?

**Comment by Orvid** [comment]
No. We can't build against anything above 1.60 currently due to Folly's fibers lib being incompatible with  >= 1.61

**Comment by Daniel15** [comment]
Hmmm... I wonder how I'm going to upgrade my system. Currently I can't really touch anything as packages that HHVM requires conflict with packages that other apps require. Is it possible to statically link the libraries that HHVM requires?

**Comment by paulbiss** [comment]
You might be able to get it working that way if you edit the cmake files and build from source, but our cmake configs aren't currently setup to do that. There's a STATIC_CXX_LIB option but I'm not aware of options to link any other parts of the binary statically.

**Comment by Orvid** [comment]
Boost can be linked in statically fairly trivially by setting `Boost_USE_STATIC_LIBS` as I do in the default config for [MSVC](https://github.com/facebook/hhvm/blob/master/CMake/MSVCDefaults.cmake#L32). Linking in the rest of the dependencies statically is a bit harder, though, as you're on linux, should be possible by just setting the resolved library variables (the same ones I set in the MSVC config above) to the static libraries. The extra defines are only needed for Windows.

**Comment by jwatzman** [comment]
Back when we used to do wheezy releases, they had too old a version of boost, and so the packaging script built a newer one and statically linked against it -- here's how that worked https://github.com/hhvm/packaging/blob/a8573b6896c803134e32dbe5ec387f05ebe0e606/hhvm/deb/package#L119-L137 -- might have bitrotted by now, or might still work.

**Comment by Orvid** [comment]
It still works for wheezy, and we do still do wheezy releases :P

**Comment by Daniel15** [comment]
Out of curiosity, I tried the Wheezy package on Debian Testing, but it also fails:
```
 hhvm : Depends: libicu48 but it is not installable
        Depends: libmagickwand5 but it is not installable
```

It looks like these two libraries are only available in Wheezy.

It seems like we could use a similar build script like that Wheezy one to also make a build that works on newer Debian versions.

**Comment by Daniel15** [comment]
Well, I set up a new server today, and had no issues installing HHVM on it, even using Debian Testing. I suspect there's something strange in my environment causing conflicts, or it's installing an old version of the package or something like that. Anyways, I'm going to close this out since the new server is working fine.
