### ISSUE TITLE
Possible bad config node: Eval.JitWarmupRequests

### ISSUE THREAD

**Issue by JohnGW05** [facebook/hhvm#7442]
### HHVM Version

HipHop VM 3.16.0-dev (rel)
Compiler: heads/master-0-g8920e2cd8f9251978713612dcc6891d7334a5d96
Repo schema: 922cef7ce4ceb4cc7b7ff58c0cc0972ee69ae429
### Standalone code, or other way to reproduce the problem

i set following in the config file:
Jit = true
JitWarmupRequests = 0
### Expected result

hhvm run as fastcgi proxygen and jit enabled at begin
### Actual result

root@localhost:~/gw05/nginx# /usr/local/bin/hhvm -c /usr/local/etc/hhvm/hhvm.hdf -m server -d hhvm.jit_warmup_requests = 0 -vEval.JitProfileInterpRequests=0 -d hhvm.jit_profile_interp_requests=0 -vhhvm.jit_profile_interp_requests=0 -v Eval.JitProfileInterpRequests=0 -v Eval.Jit=1 -v Eval.JitProfileInterpRequests=0
Possible bad config node: Eval.JitWarmupRequests
Possible bad config node: Eval.JitAStubsSize
Possible bad config node: Log.InjectedStackTrace
Possible bad config node: Server.DanglingWait

question:
so, 1、why hhvm didn't warmup jit at the fisrt ?how to make the jitWarmupRequests=0works?
2、i run "webbench -c 200 -t 60 http://10.130.48.73:80/bench.php" in the other client machine,when i set jit = true or jit = false, the results is the same, so does the jit called? and how can i know if the jit works? 
thank you

**Comment by paulbiss** [comment]
Well `hhvm.jit_warmup_requests` isn't an hhvm option. The first `Eval.JitProfileInterpRequests` run in the interpreter and it looks like you set that to zero already.

You need to send enough requests to the jit for it to (1) generate profile translations, (2) collect profile data, and (3) generate optimized translations. The hhvm JIT is tuned based on profile data, and running without these optimizations would be highly inadvisable. At a minimum the first set of requests will need to actually generate the machine code which can take time, there is no way around this.

**Comment by dave-estes** [comment]
Downloaded Facebook's Xenial package project for 3.25.1.

    dget -u http://dl.hhvm.com/ubuntu/pool/main/h/hhvm/hhvm_3.25.1-1~xenial.dsc
    cd hhvm-3.25.1/

Made a few changes to the project to build for AArch64 instead of x86_64. The largest issues was to remove the dependence on jemalloc. Xenial's current version of jemalloc only supports 4k pages. HHVM runs much better with 64k pages, and so I wanted to build a binary that would work on either system. Initially I tried to install the hhvm package build on the 4k page ThunderX machine on another machine with 64k pages and an upgraded version of jemalloc. Well, even building hhvm against an old version of jemalloc locks it into systems with only 4k pages due to various code that's compiled in from jemalloc header files.

    === modified file 'debian/control'
    --- debian/control	2018-03-23 17:28:16 +0000
    +++ debian/control	2018-03-27 18:29:00 +0000
    @@ -41,7 +41,6 @@
       libiconv-hook-dev,
       libicu-dev,
       libinotifytools0-dev,
    -  libjemalloc-dev,
       libkrb5-dev,
       libldap2-dev,
       libmagickwand-dev,
    
    === modified file 'debian/hhvm-dev.install'
    --- debian/hhvm-dev.install	2018-03-23 17:28:16 +0000
    +++ debian/hhvm-dev.install	2018-03-26 17:11:34 +0000
    @@ -1,4 +1,4 @@
     /usr/bin/hhvm-gdb /usr/bin
     /usr/bin/hphpize /usr/bin
     /usr/include/hphp /usr/include
    -/usr/lib/x86_64-linux-gnu/hhvm /usr/lib/x86_64-linux-gnu
    +/usr/lib/aarch64-linux-gnu/hhvm /usr/lib/aarch64-linux-gnu
    
    === modified file 'debian/rules'
    --- debian/rules	2018-03-23 17:28:16 +0000
    +++ debian/rules	2018-03-27 18:29:00 +0000
    @@ -7,7 +7,8 @@
     	-Wno-dev \
     	-DMYSQL_UNIX_SOCK_ADDR=/var/run/mysqld/mysqld.sock \
    - 	-DCMAKE_BUILD_TYPE=RelWithDebInfo
    + 	-DCMAKE_BUILD_TYPE=RelWithDebInfo \
    +	-DUSE_JEMALLOC=off \
    +	-DENABLE_LD_GOLD=off
     
     override_dh_strip:
     	dh_strip --dbg-package=hhvm-dbg

Built the packages with:

    bzr builddeb -- -us -uc
