### ISSUE TITLE
HHVM seems to buffer output from readfile and fpassthru even if output buffering is disabled

### ISSUE THREAD

**Issue by chetan-prime** [facebook/hhvm#7444]
### HHVM Version

HipHop VM 3.15.2 (rel)
Using through nginx+fastcgi (Have disabled nginx fastcgi buffers)
### Standalone code, or other way to reproduce the problem

header("Content-Type: application/octet-stream");
header('Content-Disposition: attachment; filename="' . htmlentities($outputFile) . '"');
header('X-Accel-Buffering: no');

$output=popen($cmd,"r");
while (@ob_end_flush());
error_log("ob_get_level=".ob_get_level()."\n");

fpassthru($output);
pclose($output);
### Expected result

Data to stream into the client
### Actual result

If output is < 100M it works , When output is large then hhvm crashes

HTTP/404 after this in hhvm/error.log-
Core dumped: Segmentation fault
Stack trace in /tmp/stacktrace.22157.log

The stack trace is empty and has only one line - "PHP Stacktrace:"

If monitor using "top" , it shows hhvm using up all available RAM then crashing. Not a single byte of data is received in client end as if it's all sitting in some sort of buffer which never gets flushed to the client end.

**Comment by chetan-prime** [comment]
### Additional code, which gives the same behavior

**Comment by chetan-prime** [comment]
Clicked the wrong button. Reopening issue

**Comment by Orvid** [comment]
The key detail of this is that the machine this is running on has very little RAM. 512mb was the first test. I would suspect we just need to be flushing the buffer and reading in chunks, and that we're probably currently reading the file entirely into memory and then writing it all at once.

**Comment by chetan-prime** [comment]
Thanks for the feedback @Orvid  , Yes this PC had 512MB and hhvm works great with everything else I throw at it. However there is an issue with it trying to cache everything to RAM with the readfile & fpassthru functions . This isn't how http://php.net/readfile says the functions are supposed to work. With output buffering disabled they should stream the data out from the 1st kb.
I have even tried the below code , but the same result. As you can see I'm flushing the output every kb

###Poor Man's fpassthru
while (1) {
	$buff=fread($output,1024);
	if ($buff==FALSE || $buff=="")
		break;
	echo $buff;
	@ob_end_flush();
}

This looks like a defect in hhvm that tries to cache the entire response to memory before sending it over to nginx thro fastcgi even though output buffering is turned off completely.  I even edited /etc/hhvm/php.ini and set output_buffering=Off
If I run top I can see hhvm increasing its memory usage until it runs out of RAM and crashes. RAM isn't the issue as hhvm should be able to support even 4+ GB files if the streaming works right.

**Comment by chetan-prime** [comment]
I tried the workaround http://stackoverflow.com/questions/4481235/php-flush-ob-flush-not-working
Added one line -
ob_implicit_flush(true);

Before streaming the output if I add the above line then it works as expected and streaming starts almost instantly. Ideally this shouldn't be required if ob_get_level() == 0 .

**Comment by chetan-prime** [comment]
Closing issue as I no longer need a fix.
Have moved this code to another language more suited to streaming http output with inbuilt http server support
