### ISSUE TITLE
Hack/h2tp: Heredoc/nowdoc parsing is broken

### ISSUE THREAD

**Issue by jesseschalken** [facebook/hhvm#7445]
The parsing of heredocs and nowdocs in Hack is broken, and this is visible in both the typechecker and `h2tp`.
### HHVM Version

```
HipHop VM 3.15.2 (rel)
Compiler: tags/HHVM-3.15.2-0-g83ac3e5e3f5657be0cf4c55884044f86a7818b90
Repo schema: 608339137764e8365964a1adaa7a27d125b6076f
```
### Standalone code, or other way to reproduce the problem

``` php
<?hh // strict

function main():void {
  echo <<<eof
hello $foo1
eof;
  // no error?

  echo "hello $foo2";
  // error: Undefined variable $foo2
}
```
### Expected result

Hack produces a type error for both the undefined variables `$foo1` and `$foo2`.
### Actual result

An error is only produced for the reference to `$foo2`. The Hack parser can't see the variable `$foo1` in the heredoc.
### Standalone code, or other way to reproduce the problem

Run `h2tp` on this file:

``` php
<?hh // strict

function main():void {
  echo <<<'end'
test1
end;

  $foo = 1;
  echo <<<end
test2 $foo test2
end;
}
```
### Expected result

``` php
<?php
require_once ($GLOBALS["HACKLIB_ROOT"]);
function main() {
  echo ("test1");
  $foo = 1;
  echo ("test2 " . $foo . " test2");
}
```
### Actual result

``` php
<?php
require_once ($GLOBALS["HACKLIB_ROOT"]);
function main() {
  echo ("'end'\ntest1\nen");
  $foo = 1;
  echo ("end\ntest2 \044foo test2\nen");
}
```

**Comment by jesseschalken** [comment]
@ericlippert I'm thinking of trying to fix this, but is the new parser close enough to being finished that I shouldn't bother?

**Comment by ericlippert** [comment]
Fine by me if you fix it. We're still a ways out from having the new parser ready for production. Thanks!

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Support for h2tp was removed in 486f44a.
