### ISSUE TITLE
Q: Zend statement handler equivalent for HHVM?

### ISSUE THREAD

**Issue by sidkshatriya** [facebook/hhvm#7447]
In PHP, Zend extensions can define a [statement handler](https://github.com/php/php-src/blob/PHP-7.0.12/Zend/zend_extensions.h#L52) callback. This callback will be called before _every_ PHP statement is executed. This callback is the basis for a lot of debugging/profiling tools on PHP. 

(Search for: 
zend statement handler callback 
in Google for more info)

**Is there something equivalent for HHVM?** 

I found the [onOpcode](https://github.com/facebook/hhvm/blob/HHVM-3.14/hphp/runtime/vm/debugger-hook.h#L135) debugger hook. If I understand correctly, if you define a HHVM extension that subclasses `DebuggerHook` class and overrides the onOpcode method, it will be called before every HHVM opcode is executed.

So I suppose I'll have to somehow check every time onOpcode is called that the current opcode represents a new PHP statement that was not encountered before. I'm guessing my job is likely to be a bit complicated because I'd only be interested in situations where a proper PHP statement is about to be executed and not things like a class being defined etc.

As an idea, could I somehow use the code coverage [machinery](https://github.com/facebook/hhvm/blob/HHVM-3.14/hphp/runtime/base/code-coverage.cpp#L32) in HHVM to emulate Zend Statement Handler?

I don't know enough of the HHVM internals at this stage and was hoping for some help in figuring out how to create a HHVM debugger hook that is effectively like the Zend Statement Handler callback in PHP.

**Comment by aorenste** [comment]
Hi @sidkshatriya - Your idea sounds like it might be a reasonable approach.  Assuming that there was no performance penalty when not being used we'd certainly accept a pull request for this.  I'm going to close this issue for now - if you submit a pull request a new issue will be created for the PR.

**Comment by sidkshatriya** [comment]
@aorenste I think there might be a misunderstanding:

- I'd like to know if there is such a statement handler available in HHVM or not
- I was mentioning various thinks like the onOpcode etc. with a view of giving ideas to someone who might know HHVM deeply and tell me _how_ I could get such a statement handler (if something like this did not exist).

Essentially I'm looking for bit of help/advice in how I can get a Zend statement handler equivalent on HHVM...

**Comment by Orvid** [comment]
A statement handler doesn't currently exist in HHVM. The quickest and dirtiest way to do it might just be to hook into the parser and output an extra op-code at the end of each statement.
