### ISSUE TITLE
AsyncMysqlConnection::queryf() crashes with RangeSse42.cpp:32 qfind_first_byte_of_sse42 only works with SSE42!

### ISSUE THREAD

**Issue by eryi** [facebook/hhvm#7448]
### HHVM Version
HipHop VM 3.15.2 (rel)
Compiler: tags/HHVM-3.15.2-0-g83ac3e5e3f5657be0cf4c55884044f86a7818b90
Repo schema: 608339137764e8365964a1adaa7a27d125b6076f

For docker:
 - Issue occurs on hhvm/hhvm:3.15-lts-latest
 - Issue does not occur on hhvm/hhvm:3.13.2

### Standalone code, or other way to reproduce the problem
````
<?hh
$pool = new \AsyncMysqlConnectionPool(array());
$conn = $pool->connect(
      'localhost',
      3306,
      'myDb',
      "myUsername",
      "myPassword"
    );

\HH\Asio\join($conn)->queryf('SELECT * from my_table');
````
### Expected result

HHVM shouldn't crash.

### Actual result
````
WARNING: Logging before InitGoogleLogging() is written to STDERR
F1028 15:17:34.517529 28885 RangeSse42.cpp:32] Check failed: false Function qfind_first_byte_of_sse42 only works with SSE42!
*** Check failure stack trace: ***
Core dumped: Aborted
Stack trace in /tmp/stacktrace.28872.log
Aborted (core dumped)
````
 /tmp/stacktrace.28872.log is empty

**Comment by fredemmott** [comment]
@drilibo, could you take a look at this?

**Comment by mofarrell** [comment]
This looks related https://github.com/facebook/folly/pull/349

**Comment by Orvid** [comment]
Upstream issue is fixed in https://github.com/facebook/folly/commit/5c3799297109076c31ee801f00312cfaa0bbc605, so this will be fixed with the next third-party update.

**Comment by simonwelsh** [comment]
Can this be fixed in 3.15 too? `queryf` is kinda important ;)

**Comment by aorenste** [comment]
@simonwelsh The problem with fixing this in 3.15 is that since it's in a 3rd party library (folly) we basically get to either pull in a new version of the entire library or not - we can't just patch this one thing.  Pulling in a new version of the whole library as part of an LTS release is kind of sketchy.  Maybe @Orvid can confirm.

**Comment by Orvid** [comment]
As this is a tiny change, it should be possible, and do-able with a bit of trickery in the CMake file for compiling Folly. I think this is probably something worth doing even if the solution is a bit hacky.
