### ISSUE TITLE
Hack considers "null" to be partially type checked code

### ISSUE THREAD

**Issue by jesseschalken** [facebook/hhvm#7450]
### HHVM Version

```
HipHop VM 3.15.2 (rel)
Compiler: tags/HHVM-3.15.2-0-g83ac3e5e3f5657be0cf4c55884044f86a7818b90
Repo schema: 608339137764e8365964a1adaa7a27d125b6076f
```
### Standalone code, or other way to reproduce the problem

Write `null` anywhere in your Hack code (except as `=== null` or `!== null`, which appear to be special cased), and enable showing of diagnostic warnings in Nuclide.

This code is sufficient:

``` hack
function foo(): ?string {
  return null;
}
```
### Expected result

`null` is fully type checked, and no warning is produced.
### Actual result

Hack reports the `null` as "Partially type checked code. Consider adding type annotations."

![image](https://cloud.githubusercontent.com/assets/1559204/19830664/5829d8a4-9e48-11e6-82eb-482695b7abef.png)
### Discussion

It is possible to work around this problem by defining:

``` hack
function new_null<T>(): ?T {
  return null;
}
```

and using that. However, class property and function parameter defaults cannot be function calls (at least not in standard PHP) so this workaround doesn't always work, and it is therefore not possible to achieve 100% type coverage.

In principle I don't see why the Hack type checker can't see the expression `null` as type `<T> ?T`, just as a call to `new_null()` (as defined above) would be.

This was originally posted on the HHVM General Facebook group [here](https://www.facebook.com/photo.php?fbid=10210537284254587).

**Comment by elgenie** [comment]
This is because a null literal is typed as a Toption of a fresh type: https://github.com/facebook/hhvm/blob/master/hphp/hack/src/typing/typing.ml#L944

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

The typechecker understands that `null` is typed now.
