### ISSUE TITLE
Hack: Static variables are permitted, but they are not type safe

### ISSUE THREAD

**Issue by jesseschalken** [facebook/hhvm#7453]
### HHVM Version

```
HipHop VM 3.16.0-dev (rel)
Compiler: heads/master-0-ge9eb3fc414fbae9b2c999a4f11390e23050b23b7
Repo schema: 9cc0ebe15bc9d2ba3609c5e4458deeef9ed86dcc
```
### Standalone code, or other way to reproduce the problem

``` hack
<?hh // strict

class Foo {
  public function fooMethod(): void {}
}

function foo(bool $b = false): void {
  static $x;
  if ($b) {
    $x = 1;
  } else {
    $x = new Foo();
    foo(true);
    $x->fooMethod();
  }
}

/* HH_IGNORE_ERROR[1002] */
foo();
```

### Expected result

A type error from `hh_client` that static variables are disallowed.
### Actual result

No error from `hh_client`, but this error is produced at runtime:

```
Uncaught Error: Call to a member function fooMethod() on integer
```
### Discussion

I expected static variables to be disallowed by Hack, in the same way that global variables and references generally are disallowed, but they are permitted, and this creates a hole in the type system.

**Comment by andrewjkennedy** [comment]
It seems odd to permit statics but not globals. Presumably the only difference is that statics can be accessed only from within the enclosing method. But in terms of lifetimes they behave the same.

**Comment by fredemmott** [comment]
I thought globals were banned because unchecked code could modify them, which isn't the case for statics in Hack methods?

**Comment by jesseschalken** [comment]
Some options:

1. Disallow static variables.
  1. All other sources of references are already banned (`global $foo`, `&$foo`, `function &foo() {}`), and the typechecker already assumes that references don't exist (hence the undetected `Call to a member function fooMethod() on integer`), so this is consistent with existing design.
  2. References (including static variables) really have no use case since classes gained Java-style reference semantics in PHP5, and are only a holdover from PHP4 where classes were passed by value and so `&` was required to pass by ref. Global and static variables were superseded by static properties and the rest by instance properties.
  3. They really hurt readability. Does `$foo = 1;` simply assign a local variable, or is it modifying shared state? In a world with references, it can be very hard to know.
2. Try to make static variables type safe without an annotation.
  1. Having all assignments flow into all reads should be sufficient.
  2. Need to consider the positioning of `static $foo;`, since it is a normal local variable before that point and a reference thereafter.
  3. Complicates flow analysis.
3. Require a type annotation on the static variable, like a static property does.
  1. Disable flow analysis for that variable and always consider it having the declared type, as if you were reading/writing a static property.
  2. Need to consider the positioning of `static $foo;`, since it is a normal local variable before that point and a reference thereafter.

**Comment by jesseschalken** [comment]
@fredemmott Unchecked code can already modify non-private properties, so globals wouldn't be banned for that reason. It would be for the same reason that references are banned generally ([here](https://docs.hhvm.com/hack/unsupported/references)) - it causes a local variable to no longer be local, breaking (or at least complicating) flow analysis.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Static variables have been disallowed in hhvm [4.2.0](https://hhvm.com/blog/2019/04/23/hhvm-4.2.0.html).
