### ISSUE TITLE
HHVM requires stop working after a large amount of requests

### ISSUE THREAD

**Issue by xJakub** [facebook/hhvm#7454]
### HHVM Version
3.12.8, running in fastcgi + RepoAuth mode inside a Kubernetes container. Requests are forwarded by nginx.

### Standalone code, or other way to reproduce the problem
It seems that every require_once in our code stopped working in some of the requests. The proportion of failing requests seems constant, but increases over time. This has happened to us about 3 times in the last month: two times on our hhvm service with the highest requests count, while the other one was on our second highest one.

![errors](https://cloud.githubusercontent.com/assets/1308245/19851689/7b649904-9f5f-11e6-8417-e976e7b9e7ce.png)

### Expected result
Code works normally.

### Actual result
`\nFatal error: File not found: <somefile>.php in <somefile>.php on line 3`

After isolating the pod, we tried running 1000 requests to the pod and checking how many of them were replying correctly or failing due to bad require_once handling:
```
root@service-wdqa1:/# bash test.sh                                                           
709/1000 errors
root@service-wdqa1:/# bash test.sh
710/1000 errors
```
Our services have a RequestInitDocument configured. It also executes a require_once on every execution, but we have never seen it fail. We have tried getting more information through the admin port, but a /thread-mem request killed our container.

**Comment by mofarrell** [comment]
I don't think this is enough information for us to go by.  More information might allow us to work towards a solution.  It is worth noting that this issue may not be in more recent releases.  3.12 is about to go out of support.  If upgrading doesn't fix it, we would be happy to help if we could reproduce it, or if you could isolate the issue better yourself.
This issue has been waiting for more info for more than 2 weeks. I'm closing it for now, but feel free to re-open it if you can provide more info. https://github.com/facebook/hhvm/wiki/Human-Timeouts
