### ISSUE TITLE
The `/status.json` endpoint of the admin server is not working

### ISSUE THREAD

**Issue by Succo** [facebook/hhvm#7456]
### HHVM Version
HipHop VM 3.15.2 (rel)
Compiler: tags/HHVM-3.15.2-0-g83ac3e5e3f5657be0cf4c55884044f86a7818b90
Repo schema: 608339137764e8365964a1adaa7a27d125b6076f
It's running on a debian 8, installed from your debian repo (not the LTS one), and used in fastcgi mode.

### Standalone code, or other way to reproduce the problem

I'm trying to use `curl http://localhost/status.json?auth=password`. To get information about the running thread.

### Expected result
As you can see in the actual result, I get a json with detailled informations on the thread status. 
However all information apart from `id` and `tid` is the default 0 value.
It's very obvious by the start date which is "Thu, 01-Jan-1970 01:00:00 CET".

Actual code seems to be https://github.com/facebook/hhvm/blob/10b4a1aeb38979d8632ab7496ddab390777f6b2d/hphp/runtime/server/server-stats.cpp#L596

### Actual result
```
{
  "status": {
    "process": {
      "id": 5040
      , "build": ""
      , "compiler": "tags/HHVM-3.15.2-0-g83ac3e5e3f5657be0cf4c55884044f86a7818b90"
      , "debug": "no"
      , "hotprofiler": "yes"
      , "now": "Mon, 31-Oct-2016 16:14:25 CET"
      , "start": "Mon, 31-Oct-2016 10:31:32 CET"
      , "up": "5 hours 42 minutes 53.000s"
    }
    , "threads": [
      {
        "id": 140099369013184
        , "tid": 5040
        , "req": 0
        , "bytes": 0
        , "start": "Thu, 01-Jan-1970 01:00:00 CET"
        , "duration": "0 seconds"
        , "io": 0
        , "mode": "idle"
        , "url": ""
        , "client": ""
        , "vhost": ""
      }
      , {
        "id": 140098960094976
        , "tid": 5069
        , "req": 0
        , "bytes": 0
        , "start": "Thu, 01-Jan-1970 01:00:00 CET"
        , "duration": "0 seconds"
        , "io": 0
        , "mode": "process"
        , "url": ""
        , "client": ""
        , "vhost": ""
      }
      , {
        "id": 140098884597504
        , "tid": 5180
        , "req": 0
        , "bytes": 0
        , "start": "Thu, 01-Jan-1970 01:00:00 CET"
        , "duration": "0 seconds"
        , "io": 0
        , "mode": "idle"
        , "url": ""
        , "client": ""
        , "vhost": ""
      }
    ]
  }
}
```

**Comment by mofarrell** [comment]
@Succo  Assuming you have not issued any requests, this appears to be the correct behavior.

The way this data is presented may be slightly unclear.
There are three types of information presented here:
- Thread information and state (`tid`, `io`, `mode`, etc.)
- Request information for current or last request run on the thread (`start`, `duration`, `url`, `client`, `vhost`, etc.)
- Aggregated information for thread (`req`, `bytes`, etc.)

This means that the `start` time listed would be the start time of the current running request (or last running request) not the start time of the thread (in this case it looks like you haven't run any requests, so it is uninitialized).  If you are looking for the start time of the thread, it is probably close to the process start time, as the threads are pooled and reused from request to request.

**Comment by Succo** [comment]
@mofarrell thanks for the quick answer. But I don't think it's entirely solves my problem.

This is on a running hhvm instance serving a very small website. `request-count` returned by `/check-health` is 430. I'm not really looking for the start time of the thread, just playing around with what can be monitored.

-  Thread information and state seems correct.
-  Request information stays null even though it's serving content.
-  Aggregated information  stays null too.

BTW do you know if there is a place with detailed documentation about all the informations returned by the different endpoint of the admin server, I'd be interested, the doc I found is really sparse.

**Comment by simonwelsh** [comment]
@Succo you need to enable most stats before you get values for them. There's a [list](https://docs.hhvm.com/hhvm/configuration/INI-settings#statistics) of INI settings, though I suspect `hhvm.stats.enable = 1` and `hhvm.stats.web = 1`  are what you're after.

**Comment by simonwelsh** [comment]
@Succo you need to enable stats collection before you'll get anything being tracked. There's a list of [INI settings](https://docs.hhvm.com/hhvm/configuration/INI-settings#statistics), though the ones you want are probably `hhvm.stats.enable = 1` and `hhvm.stats.web = 1`.

**Comment by mofarrell** [comment]
@Succo It doesn't look like we have any resources documenting the endpoints themselves.  Just info about how to use the admin server:
https://docs.hhvm.com/hhvm/advanced-usage/admin-server
http://hhvm.com/blog/521/the-adminserver

**Comment by Succo** [comment]
Thank you both for your answer. 

@mofarrell yeah that's all I found, that's why I was having a hard time understanding what is returned I guess :smile:.
