### ISSUE TITLE
noreturn not working on instance methods

### ISSUE THREAD

**Issue by HRMsimon** [facebook/hhvm#7464]
### HHVM Version
3.16.0-dev, 3.15.2, 3.14.4
### Standalone code, or other way to reproduce the problem
```hack
<?hh // strict

class A {
  public function fetch(): A {
    $obj = self::internal_fetch();
    if (!$obj) {
      $this->oops();
    }

    return $obj;
  }

  private static function internal_fetch(): ?A {
    return null;
  }

  public function oops(): noreturn {
    throw new Exception('Oops');
  }
}
```
### Expected result
No errors!
### Actual result
```
test.php:10:12,15: Invalid return type (Typing[4110])
  test.php:4:28,28: This is an object of type A
  test.php:13:45,46: It is incompatible with a nullable type
```

If `oops()` is made static, then no error is produced.

This is causing issues with PHPUnit code that's using [`markTestIncomplete`/`markTestSkipped`/`fail`](https://git.simon.geek.nz/91-carriage/phpunit-hhi/blob/master/src/Framework/Assert.hhi#L518-521).

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

`noreturn` on non static methods has been improved in hhvm [4.15.0](https://hhvm.com/blog/2019/07/22/hhvm-4.15.0.html). Your repro works now.
