### ISSUE TITLE
Can't install HHVM on Ubuntu 16.04

### ISSUE THREAD

**Issue by baffinity** [facebook/hhvm#7470]
Hi all,

I'm having issues installing HHVM on Ubuntu 16.04.

I'm following the instructions [here](http://www.itzgeek.com/how-tos/linux/debian/hhvm-explained-install-hhvm-ubuntu-16-04-debian-8.html).

When i type: 

> sudo apt-get update

I get the warning:

> W: http://dl.hhvm.com/ubuntu/dists/trusty/InRelease: Signature by key 36AEF64D0207E7EXXXXXXXX81BE7A449 uses weak digest algorithm (SHA1).

Then when I type:

> sudo apt-get install hhvm

I get the error:

>  E: Unable to locate package hhvm

Any ideas?

**Comment by mofarrell** [comment]
@baffinity It looks like our package listing is broken.  The instructions you followed are correct, and also available on the [hhvm docs site](https://docs.hhvm.com/hhvm/installation/linux).

@Orvid @aorenste Any ideas why our i386 package listings look empty?
http://dl.hhvm.com/ubuntu/dists/xenial/main/binary-i386/Packages
If we need to touch related things, maybe https://github.com/facebook/hhvm/issues/7452 would be nice to get done as well.

**Comment by Orvid** [comment]
It's empty because we don't package (or even support) i386 :P

Though something else is odd here, because you're on 16.04 Xenial, so you should be pulling from the Xenial releases, not the Trusty ones.

**Comment by tslettebo** [comment]
That's probably a different issue. Before we upgraded our server, HHVM ran fine on Ubuntu 16.04.

The issue is that there's no HHVM package available for 16.10, and building from source fails, which I tried today.

**Comment by Daniel15** [comment]
The amd64 repo looks fine to me (http://dl.hhvm.com/ubuntu/dists/xenial/main/binary-amd64/Packages)... Can you confirm that you're on a 64-bit version of Ubuntu?

**Comment by baffinity** [comment]
@Daniel15 I'm on Ubuntu 16.04.1 lTS, release 16.04, codename xenial, i686 version.

**Comment by Daniel15** [comment]
> i686 version

i686 is 32-bit, and HHVM does not support 32-bit architectures. You need to use a 64-bit operating system (often called "x86_64" or "amd64") in order to use 64-bit.
