### ISSUE TITLE
type_structure() should throw exceptions instead of raising fatals

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#7473]
### HHVM Version

3.15.0, nightly (3.16-dev)

### Standalone code, or other way to reproduce the problem

```
type_structure('type_alias_that_does_not_exist');

// ... or ...

type_structure(Foo:class, 'SOME_CONSTANT_THAT_DOES_NOT_EXIST');
```

### Expected result

Some exception that's catchable and handleable nicely

### Actual result

Fatal error

**Comment by paulbiss** [comment]
Fatals are converted to exceptions in PHP 7 mode. I'm not opposed to changing it to always throw, but it strikes me that it's currently pretty consistent with most other builtins which fatal in 5 mode and throw in 7 mode.

**Comment by photodude** [comment]
+1 for always throw.

Even though choosing to always throw is not consistent with 5 vs 7 IMO this is one of those cases where HHVM could be better than php.

**Comment by fredemmott** [comment]
Fatals are less of an issue for PHP as you can use `@` then check for failure; given this function is pretty much only useful for Hack, which bans `@`, I don't think PHP5 is a reasonable comparison.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

An `\Error` is thrown in modern versions.
```HACK
<<__EntryPoint>>
function main(): void {
  try {
    type_structure(Foo::class, 'type_alias_that_does_not_exist');
  } catch (\Error $e) {
    \var_dump(\get_class($e));
  }
}
```

`string(5) "Error"`
