### ISSUE TITLE
type_structure() goes crazy if you give it a constant that isn't a type constant

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#7474]
### HHVM Version

3.15.2, nightly

### Standalone code, or other way to reproduce the problem

```
<?hh

class Foo {
const string NOT_A_TYPE_CONSTANT = 'bar';
}

$x = type_structure(Foo::class, 'NOT_A_TYPE_CONSTANT');
var_dump(gettype($x));
var_dump(count($x));
```

### Expected result

Ideally an exception. Given #7473 I expected a fatal. Null would also be fairly reasonable.

### Actual result

A *massive* array

```
string(5) "array"
int(140516688809296)
```

**Comment by fredemmott** [comment]
If you try to print them out, it segfaults.

**Comment by fredemmott** [comment]
Crash repro:

```
<?hh

class Foo {
const string NOT_A_TYPE_CONSTANT = 'bar';
}

$x = type_structure(Foo::class, 'NOT_A_TYPE_CONSTANT');
var_dump(gettype($x));
var_dump(count($x));

foreach ($x as $k => $v) {
printf("%s => %s\n", var_export($k, true), var_export($v, true));
}
```

**Comment by DemiMarie** [comment]
I suspect this is invoking undefined behavior somewhere in C++ code.  An `int(140516688809296)` shouldn't be able to fit in the machine's memory (over 140 entries).  I suspect that the "array" is actually junk memory.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This has been fixed at some point. HHVM 4.56 throws a very helpful error instead.
```HACK
<<__EntryPoint>>
function main(): void {
  try {
    $x = type_structure(Foo::class, 'NOT_A_TYPE_CONSTANT');
    invariant_violation('This code is not reached');
  } catch (\Error $e) {
    \var_dump(\get_class($e));
    \var_dump($e->getMessage());
  }
}


class Foo {
  const string NOT_A_TYPE_CONSTANT = 'bar';
}
```

```
string(5) "Error"
string(51) "Non-existent type constant Foo::NOT_A_TYPE_CONSTANT"
```
