### ISSUE TITLE
Converting cassandra php extension into hhvm extension

### ISSUE THREAD

**Issue by rishabhpoddar** [facebook/hhvm#7476]
### HHVM Version 3.15.2

Is there an already converted datastax cassandra php extension for hhvm? 
If not, then when would one be available?

**Comment by mofarrell** [comment]
https://github.com/facebook/hhvm/issues/971
It looks like there is some interest from others in the community.  We probably won't have time to get to this, but if you are interested writing/converting the extension, I am sure others would appreciate it.

**Comment by rishabhpoddar** [comment]
Okay.. thank you..

**Comment by aorenste** [comment]
I'm going to close this for now.  If you plan on writing the extension please reopen.
