### ISSUE TITLE
Can't resolve dl.hhvm.com on opendns

### ISSUE THREAD

**Issue by mkleinsasser** [facebook/hhvm#7479]
### Expected result

$ dig @8.8.8.8 dl.hhvm.com

; <<>> DiG 9.8.3-P1 <<>> @8.8.8.8 dl.hhvm.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 14787
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;dl.hhvm.com.                   IN      A

;; ANSWER SECTION:
dl.hhvm.com.            6838    IN      CNAME   ftp.osuosl.org.
ftp.osuosl.org.         238     IN      A       64.50.233.100
ftp.osuosl.org.         238     IN      A       64.50.236.52
ftp.osuosl.org.         238     IN      A       140.211.166.134

;; Query time: 66 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Tue Nov  8 16:58:41 2016
;; MSG SIZE  rcvd: 105

### Actual result

$ dig @208.67.222.222 dl.hhvm.com

; <<>> DiG 9.8.3-P1 <<>> @208.67.222.222 dl.hhvm.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 55457
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;dl.hhvm.com.                   IN      A

;; ANSWER SECTION:
dl.hhvm.com.            5846    IN      CNAME   ftp.osuosl.org.

;; AUTHORITY SECTION:
osuosl.org.             984     IN      SOA     ns1.auth.osuosl.org. hostmaster.osuosl.org. 1478643222 3600 900 604800 86400

;; Query time: 35 msec
;; SERVER: 208.67.222.222#53(208.67.222.222)
;; WHEN: Tue Nov  8 16:58:28 2016
;; MSG SIZE  rcvd: 133

**Comment by Orvid** [comment]
Something is up with the DNS servers upstream, as `ftp.osuosl.org` is not resolving.

**Comment by Orvid** [comment]
https://twitter.com/osuosl/status/796122719477633024

Will take a bit to propagate everywhere.
