### ISSUE TITLE
Lost where to begin

### ISSUE THREAD

**Issue by mattstar** [facebook/hhvm#7483]

**Comment by mofarrell** [comment]
A little confused by what you are trying to "begin"?
The docs site should have all the resources necessary to get started using HHVM
https://docs.hhvm.com/hhvm/
If this is not the case please raise your concerns.
For contributing we have resources described here:
https://github.com/facebook/hhvm/blob/master/CONTRIBUTING.md

**Comment by mofarrell** [comment]
@mattstar I am going to close this.  If you have a question that is more specific/actionable, open a new issue so we can address it appropriately.
