### ISSUE TITLE
Add error category to `hh_client --json` response

### ISSUE THREAD

**Issue by PranayAgarwal** [facebook/hhvm#7484]
### HHVM Version

Any

### Standalone code, or other way to reproduce the problem

Any code with errors

### Example

Regular typechecker output (`hh_client check`) returns:

> recipes/unescaped-string/MySecureRequest.php:11:29,39: Invalid argument (Typing[4110])

The JSON formatted output (`hh_client check --json`), however, skips the error type ("Typing"):

```json
{
    "message": [{
        "descr": "Invalid argument",
        "path": "/Users/pranay/repos/hack-example-site/recipes/unescaped-string/MySecureRequest.php",
        "line": 11,
        "start": 29,
        "end": 39,
        "code": 4110
    }]
}
```

The two responses should ideally be equivalent.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

All clients hardcode the names of the phase of 1xxx, 2xxx, 3xxx, and 4xxx. This shouldn't be required, but adding it to the json now won't change all those existing tools. This means that the ranges have to be unchanging anyway.
