### ISSUE TITLE
Catchable Errors are not catchable

### ISSUE THREAD

**Issue by eryi** [facebook/hhvm#7492]
### HHVM Version
HipHop VM 3.15.2 (rel)
Compiler: tags/HHVM-3.15.2-0-g83ac3e5e3f5657be0cf4c55884044f86a7818b90
Repo schema: 608339137764e8365964a1adaa7a27d125b6076f

### Standalone code, or other way to reproduce the problem
````
<?hh
function testTypeError(int $x):void {}
try {
  testTypeError("hello");
} catch (Error $e) {
  print "Error caught!";
} catch (Throwable $e) {
  print "Throwable caught!";
} catch (TypeError $e) {
  print "TypeError caught!";
}

````

### Expected result
````
Error caught!
````

### Actual result
Script terminates with 
````
Catchable fatal error: Argument 1 passed to testTypeError() must be an instance of int, string given in crash.hh on line 2
````

### Motivation
When invoking methods through Reflection class, it is very possible to run into runtime type errors. I would like to handle these errors myself.

**Comment by mofarrell** [comment]
@aorenste I think you saw something like this recently.  Do you end up finding a fix?

**Comment by aorenste** [comment]
This is a dup of #7198

**Comment by simonwelsh** [comment]
* Running this with PHP7 mode enabled works as expected
* Hack doesn't support the PHP7 exceptions
