### ISSUE TITLE
Typechecker does not allow array append for array<int, string>

### ISSUE THREAD

**Issue by eryi** [facebook/hhvm#7500]
### HHVM Version
HipHop VM 3.15.2 (rel)
Compiler: tags/HHVM-3.15.2-0-g83ac3e5e3f5657be0cf4c55884044f86a7818b90
Repo schema: 608339137764e8365964a1adaa7a27d125b6076f

### Standalone code, or other way to reproduce the problem
````
<?hh //strict
function testTypeError(array<int, string> $x):void {
  $x[] = "append";
}
````

### Expected result
Typechecker reports no errors

### Actual result
Typechecker reports: an array (used like a hashtable) does not allow array append (Typing[4006]).

How do I let the Typechecker know this is not a hashtable?

**Comment by simonwelsh** [comment]
`array<string>`? If you're using it as a vector, you should type it as one.

**Comment by fredemmott** [comment]
Not a bug, simonwelsh's suggestion is correct.
