### ISSUE TITLE
Typechecker doesn't refine mixed to num or arraykey

### ISSUE THREAD

**Issue by gabiseabra** [facebook/hhvm#7501]
### HHVM Version
```
HipHop VM 3.15.2 (rel)
Compiler: tags/HHVM-3.15.2-0-g83ac3e5e3f5657be0cf4c55884044f86a7818b90
Repo schema: 608339137764e8365964a1adaa7a27d125b6076f
```
### Standalone code, or other way to reproduce the problem
```php
<?hh
class Foo
{
	public Map<string, mixed> $container;

	public function __construct(?Map<string, mixed> $values = null): void
	{
		$this->container = $values ?: Map {};
	}

	public function inc(string $key, num $step, num $default = 0): num
	{
		$value = idx($this->container, $key, $default);
		// Should be able to perform operations with $value and return it.
		invariant(is_numeric($value), "Value should be numeric.");
		// This doesn't work either.
		invariant(is_int($value) || is_float($value), "Value should be numeric.");
		$value += $step;
		$this->container[$key] = $value;

		return $value;
	}
}

$foo = new Foo();
var_dump($foo->inc("bar", 1, 0));
var_dump($foo->inc("bar", 1, 0));
```
### Expected result
```
int(1);
int(2);
```
### Actual result
```
index.hh:18:3,8: Typing error (Typing[4110])
  index.hh:18:3,8: This is a num (int/float) because this is used in an arithmetic operation
  index.hh:4:21,25: It is incompatible with a mixed value
  /tmp/hh_server/hhi_1075a478/collections/Map.hhi:58:51,52:   via this generic Tv
  /tmp/hh_server/hhi_1075a478/collections/interfaces.hhi:1036:51,52:   via this generic Tv
  /tmp/hh_server/hhi_1075a478/collections/interfaces.hhi:789:50,51:   via this generic Tv
  /tmp/hh_server/hhi_1075a478/interfaces.hhi:102:57,58:   via this generic Tv
```

**Comment by elgenie** [comment]
1. `is_numeric` can't refine to `num` because it is true for numeric strings (ie [`is_numeric("1.0")` is `true`](https://3v4l.org/XJ1MG)). It can't refine to `arraykey` either because a float cannot be an array key. `is_numeric` checks for something being convertible to a numberlike thing with sloppy type-juggling coercion, which the typechecker frowns upon.
2. `is_int($value) || is_float($value)` would be valuable for the typechecker to learn (a union type consisting of primitives).

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Support for `is` and `as` expressions wwas added to Hack in hhvm version [3.28.0](https://hhvm.com/blog/2018/08/28/hhvm-3.28.0.html).
This allows you to say `$mixed is num`.

With hhvm version [4.14.0](https://hhvm.com/blog/2019/07/15/hhvm-4.14.0.html) support for real union types was added. This allows the typechecker to understand the following code too.

```HACK
<<__EntryPoint>>
function main(): void {
  $mixed = \gmp_init('1');
  invariant($mixed is int || $mixed is num, 'union types are okay too');
  takes_num($mixed);
}

function takes_num(num $_): void {}
```
