### ISSUE TITLE
HHVM Redis Extension support Redis 3 Cluster?

### ISSUE THREAD

**Issue by jasonromando** [facebook/hhvm#7505]
### HHVM Version  3.15 & 3.16

Wanna know does HHVM Redis supprot Redis 3 Cluster, This feature can improve the redis performance and balance the multi-usage.

**Comment by abhishekbuyt** [comment]
This is also the major concern for me while shifting to HHVM from PHP-FPM. My Application relies heavily on redis cluster& and using the php only library Predis, eats away most of the CPU advantage that HHVM would have provided me.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Support for ext/redis was dropped in hhvm [4.56](https://hhvm.com/blog/2020/05/04/hhvm-4.56.html).
