### ISSUE TITLE
hhvm segfaults during w3af scan

### ISSUE THREAD

**Issue by fzg** [facebook/hhvm#7507]
### HHVM Version
`HipHop VM 3.12.1 (rel)
Compiler: 3.12.1+dfsg-1+b3
Repo schema: 5952618d81a00656bef66a46d9dbf73f1ed75fe9`

### Platform
`model name      : Intel(R) Core(TM)2 Duo CPU     L9400  @ 1.86GHz`
`Linux box 4.2.0-1-amd64 #1 SMP Debian 4.2.6-1 (2015-11-10) x86_64 GNU/Linux`

### Standalone code, or other way to reproduce the problem
Server is started like this:
`hhvm -m server -c /etc/hhvm/server.ini`
Then a w3af OWASP_TOP10 scan is ran against it.
`w3af Version: 1.2 Revision: unknown Distribution: Debian`

### Expected result
Server handles requests.
### Actual result
Server segfaults, stacktrace.$PID.log is empty.

After installing hhvm-dbg and running `hhvm-gdb --args -m server -c /etc/hhvm/server.ini`

    (gdb) bt
    #0  0x0000000001ef95fc in     HPHP::ProxygenTransport::messageAvailable(HPHP::ResponseMessage&&) (
        this=<optimized out>, message=<optimized out>)
        at /build/hhvm-jhUwuB/hhvm-3.12.1+dfsg/hphp/runtime/server/proxygen/proxygen-transport.cpp:509
    #1  0x0000000001f3735b in     folly::NotificationQueue<HPHP::ResponseMessage>::Consumer::consumeMessages (
        this=0x0, isDrain=false, numConsumed=0x0)
        at /build/hhvm-jhUwuB/hhvm-3.12.1+dfsg/third-party/folly/folly/io/async/NotificationQueue.h:683

    #2  0x00007ffff1c0a5a0 in event_base_loop () from /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5

    #3  0x0000000001f0ebeb in folly::EventBase::loopBody (this=0x7fffe18f7f40, this@entry=0x119, 
        flags=flags@entry=0)
        at /build/hhvm-jhUwuB/hhvm-3.12.1+dfsg/third-party/folly/src/folly/io/async/EventBase.cpp:347

    #4  0x0000000001e391a0 in folly::EventBase::loop (this=0x119)
        at /build/hhvm-jhUwuB/hhvm-3.12.1+dfsg/third-party/folly/src/folly/io/async/EventBase.cpp:299

    #5  folly::EventBase::loopForever (this=0x119, this@entry=0x7fffe480fd00)
        at /build/hhvm-jhUwuB/hhvm-3.12.1+dfsg/third-party/folly/src/folly/io/async/EventBase.cpp:446

    #6  0x0000000001b24459 in proxygen::WorkerThread::runLoop (this=0x119)
        at /build/hhvm-jhUwuB/hhvm-3.12.1+dfsg/third-party/proxygen/lib/services/WorkerThread.cpp:137

    #7  0x0000000001b246cf in proxygen::WorkerThread::<lambda()>::operator() (__closure=0x131)
        at /build/hhvm-jhUwuB/hhvm-3.12.1+dfsg/third-party/proxygen/lib/services/WorkerThread.cpp:43

    #8  std::_Bind_simple<proxygen::WorkerThread::start()::<lambda()>()>::_M_invoke<> (this=0x131)
        at /usr/include/c++/5/functional:1531

    #9  std::_Bind_simple<proxygen::WorkerThread::start()::<lambda()>()>::operator() (this=0x131)
        at /usr/include/c++/5/functional:1520

    #10 std::thread::_Impl<std::_Bind_simple<proxygen::WorkerThread::start()::<lambda()>()>     >::_M_run(void) (
        this=0x119) at /usr/include/c++/5/thread:115

    #11 0x00007fffefaa4ca0 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6

    #12 0x00007fffefd73464 in start_thread (arg=0x7fffdc3ff700) at pthread_create.c:333

    #13 0x00007fffef21a9df in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105

**Comment by aorenste** [comment]
FYI - 3.12.1 is pretty old (although it's still under LTS)

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones are unlikely to be worked on.

I am proud of your efforts of trying and succeeding to break hhvm with an automated tool. More people should try something like this with software they depend on.

This scan result is 7 years old. The chances are zero that someone is going to use this backtrace as a starting point anymore. A lot has changed in the proxygen layer in the last half decade. If someone can run this against a supported version and it still falls over and dies, please file an issue. I'd be very surprised if it does.
