### ISSUE TITLE
Porting rewrite rules to make CodeIgniter work

### ISSUE THREAD

**Issue by kyleboddy** [facebook/hhvm#751]
I have installed hiphop-php and got it working using the demo for WordPress - absolutely love it. However, I am having trouble properly rewriting/routing URLs for CodeIgniter. Here is a sample mod_rewrite apache htaccess for CI:

http://www.farinspace.com/codeigniter-htaccess-file/

<IfModule mod_rewrite.c>

```
RewriteEngine On
RewriteBase /

### Canonicalize codeigniter URLs

# If your default controller is something other than
# "welcome" you should probably change this
RewriteRule ^(welcome(/index)?|index(\.php)?)/?$ / [L,R=301]
RewriteRule ^(.*)/index/?$ $1 [L,R=301]

# Removes trailing slashes (prevents SEO duplicate content issues)
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.+)/$ $1 [L,R=301]

###

# Removes access to the system folder by users.
# Additionally this will allow you to create a System.php controller,
# previously this would not have been possible.
# 'system' can be replaced if you have renamed your system folder.
RewriteCond %{REQUEST_URI} ^system.*
RewriteRule ^(.*)$ /index.php/$1 [L]

# Checks to see if the user is attempting to access a valid file,
# such as an image or css document, if this isn't true it sends the
# request to index.php
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php/$1 [L]
```

</IfModule>

I've tried a bunch of stuff but can't figure out how to route the requests through the index.php file of CI. 

I have read the options.compiled blob over here:

https://github.com/dpaneda/hiphop-php/blob/master/doc/options.compiled

Any help? Thanks a bunch!

**Comment by X17** [comment]
Did you find a way to rewrite url with nginx and routing options?
