### ISSUE TITLE
Add an E_HHVM_FATAL_ERROR constant

### ISSUE THREAD

**Issue by joshuaspence** [facebook/hhvm#7511]
PHP defines constants such as `E_ERROR`, `E_WARNING`, `E_NOTICE`. HHVM defines a new error constant within the `ErrorMode` as follows:

```
  /*
   * PHP's fatal errors cannot be fed into error handler. HipHop can. We
   * still need "ERROR" bit, so old PHP error handler can see this error.
   * The extra 24th bit will help people who want to find out if it's
   * a fatal error only HipHop throws or not.
   */
  FATAL_ERROR = ERROR | (1 << 24), // 16777217
```

This constant, however, isn't exposed to the runtime in any way, which means that I need to know how `FATAL_ERROR` is implemented in order to know what the error code value is. It would be great if HHVM exposed this value to the runtime as `E_HHVM_FATAL_ERROR`.

**Comment by lswith** [comment]
any update on this?
