### ISSUE TITLE
[Solved] HHVM stopped frequently

### ISSUE THREAD

**Issue by wbxno** [facebook/hhvm#7512]
### HHVM Version

HipHop VM 3.12.0 (rel)
Compiler: tags/HHVM-3.12.0-0-g440e6a096b2db8a449b9690a72f2f1792530e86a
Repo schema: 033b8dedf4af99b892f2488b103a8d67a58ff816

### Standalone code, or other way to reproduce the problem

Using https://github.com/sierracircle/services-checker to create automatic restart if the service is down.

### Expected result

HHVM is running well on my server. No stopped frequently.

### Actual result

HHVM stopped frequently for 3-6 hours.

### This is my last log 

[Mon Nov 28 00:14:05 2016] [hphp] [10410:7f3a482e43c0:0:000045] [] BootTimer: onig_init = 0ms wall, 0ms cpu
[Mon Nov 28 00:14:05 2016] [hphp] [10410:7f3a482e43c0:0:000046] [] BootTimer: pagein_self = 1769ms wall, 126ms cpu
[Mon Nov 28 00:14:05 2016] [hphp] [10410:7f3a482e43c0:0:000047] [] BootTimer: pcre_reinit = 3ms wall, 3ms cpu
[Mon Nov 28 00:14:05 2016] [hphp] [10410:7f3a482e43c0:0:000048] [] BootTimer: pthread_init = 4ms wall, 4ms cpu
[Mon Nov 28 00:14:05 2016] [hphp] [10410:7f3a482e43c0:0:000049] [] BootTimer: rds::requestExit = 0ms wall, 0ms cpu
[Mon Nov 28 00:14:05 2016] [hphp] [10410:7f3a482e43c0:0:000050] [] BootTimer: servers started = 14ms wall, 13ms cpu
[Mon Nov 28 00:14:05 2016] [hphp] [10410:7f3a482e43c0:0:000051] [] BootTimer: timezone_init = 0ms wall, 0ms cpu
[Mon Nov 28 00:14:05 2016] [hphp] [10410:7f3a482e43c0:0:000052] [] BootTimer: warmup = 0ms wall, 0ms cpu
[Mon Nov 28 00:14:05 2016] [hphp] [10410:7f3a482e43c0:0:000053] [] BootTimer: xenon = 14ms wall, 7ms cpu
[Mon Nov 28 00:14:05 2016] [hphp] [10410:7f3a482e43c0:0:000054] [] BootTimer: xmlInitParser = 0ms wall, 0ms cpu

**Comment by mofarrell** [comment]
The information you have provided doesn't make it clear this is a crash.  If it is, a backtrace and information about your system would be great.
Consider starting HHVM manually.  If that works there may be something wrong with the way you are attempting auto restart.  Consider trying something more standard like https://www.digitalocean.com/community/tutorials/how-to-configure-a-linux-service-to-start-automatically-after-a-crash-or-reboot-part-1-practical-examples.  You may need to create some configuration files for systemd (https://github.com/facebook/hhvm/issues/4520)

**Comment by wbxno** [comment]
Thanks @mofarrell,
It happens because HHVM is have limit open files. 

So, i use this tutorial to fix this issue : 
http://serverfault.com/questions/679408/hhvm-exit-after-too-many-open-files

After get the PID's and checked limits file, i set the **/usr/lib/systemd/system/hhvm.service**

[Unit]
Description=HHVM HipHop Virtual Machine (FCGI)

[Service]
ExecStart=/usr/local/bin/hhvm --config /etc/hhvm/server.ini --user nginx --mode$
LimitNOFILE=100000

[Install]
WantedBy=multi-user.target

Finally, HHVM working fine without stopped frequently.

Reference links : 
http://serverfault.com/questions/679408/hhvm-exit-after-too-many-open-files
https://github.com/sierracircle/services-checker

Thanks for your attention!
