### ISSUE TITLE
Can't have trailing commas in array generic typedefs

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#7517]
### HHVM Version

3.15 and latest FB internal

### Standalone code, or other way to reproduce the problem

```Hack
<?hh // strict

type TFoo = array<
    string,
    string,
>;
```

### Expected result

No errors

### Actual result

```
[fredemmott@devbig349.prn1 /tmp/hhtest] hh_client
No errors!
[fredemmott@devbig349.prn1 /tmp/hhtest] hhvm test.php

Fatal error: syntax error, unexpected ',', expecting T_TYPELIST_GT in /tmp/hhtest/test.php on line 5
```

If I use `Map` or `dict` instead, it's happy.

**Comment by fredemmott** [comment]
Related to #6199, but not quite dupe

**Comment by lexidor** [comment]
This is treated differently to `darray<Tk, Tv,>`, where the trailing comma is allowed.

```HACK
<<__EntryPoint>>
function main(): void {

}

type TFoo1 = array<
    string,
    string,
>;

type TFoo2 = darray<
    string,
    string,
>;
```

```
Parsing[1002] Encountered unexpected token ','.
   --> src/file.hack
  8 |     string,
    |           ^

1 error found.
```

```
Fatal error: Uncaught Error: Encountered unexpected token ','. in /path/to/file.hack:8
Stack trace:
#0 {main}
```

**Comment by lexidor** [comment]
In hhvm [4.68.0](https://hhvm.com/blog/2020/07/30/hhvm-4.68.html) and above, you cannot have a plain array typehint. This means that this issue is not relevant for the newest hhvm version.
