### ISSUE TITLE
Allow building without mcrypt

### ISSUE THREAD

**Issue by sofar** [facebook/hhvm#7518]
### HHVM Version
3.15.0

### Standalone code, or other way to reproduce the problem
Compile without mcrypt library

### Expected result
Compile succeeds.

### Actual result
```
CMake Error at CMake/HHVMExtensionConfig.cmake:506 (message):
  The mcrypt extension is an extension you probably want, but resolving the
  dependency 'libMCrypt' failed!
```

I hope I don't need to explain this - it should at least be an option for people to compile hhvm without mcrypt since it's abandonware and using crypto abandonware is just plain dangerous. Right now that's not possible.

I'll test a patch, but my cmake skills are nonexistant, so I have no idea what the right way to patch this out is.

**Comment by Orvid** [comment]
`cmake -DHHVM_ENABLE_MCRYPT=Off`.

**Comment by sofar** [comment]
Thanks for the quick reply.

Can I ask where this is documented? Even google can't find any hits for HHVM_ENABLE_MCRYPT, and I would love to know what other cmake flags I may consider.

I'd also suggest by default disabling mcrypt if it is absent, due to the enormous security concerns of using an outdated and potentially insecure crypto library. This is what php's build does, for instance.

**Comment by Orvid** [comment]
`HHVM_ENABLE_*` can be used to disable or forcefully enable any extension in HHVM that isn't marked as `REQUIRED`. I don't think I documented that anywhere properly when I put the mechanism together a year ago.

Marking mcrypt as `IMPLICIT` is probably a reasonable thing to do though.
