### ISSUE TITLE
Default 120 second timeout seems impossible to override

### ISSUE THREAD

**Issue by rsouthgate** [facebook/hhvm#7520]
### HHVM Version
3.15.0

### Standalone code, or other way to reproduce the problem
/etc/hhvm/php.ini:

```
; php options
session.save_handler = files
session.save_path = /var/lib/hhvm/sessions
session.gc_maxlifetime = 1440
memory_limit = 6000M
max_execution_time = 900
max_input_time = 60

; hhvm specific
hhvm.log.level = Warning
hhvm.log.always_log_unhandled_exceptions = true
hhvm.log.runtime_error_reporting_level = 8191
hhvm.mysql.typed_results = false

hhvm.server.connection_timeout_seconds = 900
hhvm.server.request_timeout_seconds = 900
```

### Expected result
Script should run for 900 seconds

### Actual result
Fatal Error after 120 seconds. Actual error message:
```
\nFatal error: entire web request took longer than 120 seconds and timed out
```
(Also, as an aside... Strange that hhvm always seems to log the line breaks encoded).

The max execution time defined in the php ini seems respected when invoking test scripts from CLI. But the particular setup where I see the fatal error in the logs is when the script is invoked from a server connection (nginx -> unix socket to hhvm. Nginx hast a fastcgi read timeout also set to 900 seconds). Script initialised from a wget call in cron. In addition the script being called has a set_time_limit(900) which also seems to be ignored.

**Comment by mofarrell** [comment]
https://github.com/facebook/hhvm/issues/6157

**Comment by rsouthgate** [comment]
I've read that ticket but I already have those timeouts defined... 

But can I just check... I've defined the timeout settings in php.ini which I assume is read when hhvm is run through command line or a cgi connection... but perhaps I'm wrong - is it an either/or with regards php.ini/server.ini

**Comment by mofarrell** [comment]
You are correct they are both loaded.  I am unable to reproduce the issue with your provided php.ini.    I am on 3.15.3, but I doubt that would make difference here.  Maybe check they aren't being overriden in some other config file.  Also worth noting a restart is necessary because these are hhvm options.  (Also connection_timeout_seconds > request_timeout_seconds would allow it to respond to nginx)

**Comment by rsouthgate** [comment]
Apologies, I tried to recreate a test case for repro but on simple scenarios where I tell php to sleep my max_execution_time is always respected, so in looking further I'm trying to understand under what other circumstances HHVM will through that fatal error.

I've tried looking through the HHVM source but I'm no c++ expert so could someone tell me is there more than one scenario where that exception can be thrown? 

Because in the logs, taking one example I see the error thrown at 11:03:21
```
[Sun Dec 11 11:03:21 2016] [hphp] [1078:7f109d7ff700:7521:000195] [] \nFatal error: entire web request took longer than 120 seconds and timed out
```
But when I look back at that `1078:7f109d7ff700:7521:000195` which I assume identifies this thread the first entry is `[Sun Dec 11 11:00:02 2016] [hphp] [1078:7f109d7ff700:7521:000001]` which to me implies it's been running 200 seconds when the error is thrown (but that is not a consistent time - there are plenty of other threads killed in the same vein but after 220, 240 seconds etc). 

So is it possible that HHVM spawns threads within the main thread for other tasks and these are assigned a different timeout? In looking through the HHVM codebase (and having a poor understanding of c++) I can see timeouts set in vhosts and the xbox server for various request handlers. The xbox server seems to have a default timeout of 120 seconds but from the docs it sounds like I'd be needing to explicitly instantiate that for messaging queues and I'm not.

**Comment by mofarrell** [comment]
All the runtime options are read in at startup and the options are stored in [runtime-option.h](https://github.com/facebook/hhvm/blob/master/hphp/runtime/base/runtime-option.h) and [runtime-option.cpp](https://github.com/facebook/hhvm/blob/master/hphp/runtime/base/runtime-option.cpp) files.
I am unclear on what exactly is happening for you.  If you give us code (the smallest possible example) that can reproduce the issue that would be helpful.  It is hard to believe this would work fine with some code snippets, and not with others.

**Comment by rsouthgate** [comment]
Argh! In trying to condense a repro test case I finally stumbled across the bit of code that was occasionally calling set_time_limit(2 * 60)... if only it had been calling set_time_limit(120) my search would have found it straight away! Please close this... mark 'User error'

**Comment by mofarrell** [comment]
That is rough.
