### ISSUE TITLE
Prometheus text exposition format support

### ISSUE THREAD

**Issue by filippog** [facebook/hhvm#7530]
hi,
It would be nice to expose hhvm metrics in [Prometheus text exposition format](https://prometheus.io/docs/instrumenting/exposition_formats/). I've assumed the text format since that would be the simplest (UTF-8, line-oriented) and not overly different than the existing json.
Metric-wise, looks like most existing metrics are gauges so just writing the values out from memory would work already (i.e. no support for more complex metric types like histograms is needed). What do you think?

**Comment by mofarrell** [comment]
The solution here would be to make a wrapper around the emitted json.  We probably aren't interested in exposing another format.

**Comment by filippog** [comment]
@mofarrell yeah that's what we did at WMF, write our own `hhvm_exporter` (https://gerrit.wikimedia.org/r/#/admin/projects/operations/software/hhvm_exporter). Though I think having support in HHVM admin interface directly would make things easier for folks using Prometheus to get started monitoring HHVM.

**Comment by RichiH** [comment]
FYI, Prometheus exposition format will be moved into https://github.com/OpenObservability/OpenMetrics

@robskillington wanted to re-poke people inside FB about restarting this effort.

**Comment by RichiH** [comment]
PS: I decided against opening a new issue for now, but I can do that if preferred.
