### ISSUE TITLE
GCC Build Fails on master

### ISSUE THREAD

**Issue by octmoraru** [facebook/hhvm#7539]
### HHVM Version
Master branch - revision 07c7a02
gcc version 4.8.3
### Standalone code, or other way to reproduce the problem
N/A - build failure
### Expected result
HHVM build succeeds
### Actual result
HHVM build fails:

```
In file included from ./hphp/runtime/vm/jit/tc.h:22:0,
                 from ./hphp/runtime/vm/jit/translator.h:28,
                 from ./hphp/runtime/vm/jit/translator-inline.h:23,
                 from ./hphp/runtime/ext_zend_compat/php-src/Zend/zend_API.cpp:34:
./hphp/runtime/vm/jit/ir-opcode.h:120:46: fatal error: hphp/runtime/ir-opcode-generated.h: No such file or directory
 #include "hphp/runtime/ir-opcode-generated.h"
                                              ^
compilation terminated.
```
It looks to me as if the compilation of some files that include `ir-opcode-generated.h` is triggered before the header is actually generated. Especially because if you keep hitting `make`, the build will eventually succeed. Maybe there should be a build dependency added somewhere?

**Comment by Orvid** [comment]
Yep, I'm actually seeing this on the build that happens before we do the actual sync as well :(

**Comment by racardoso** [comment]
Some files at `/hphp/runtime/ext_zend_compat/` includes `/hphp/runtime/vm/jit/ir-opcode.h` which includes this file `hphp/runtime/ir-opcode-generated.h` that's generated by a script invoked by a `add_custom_command` in CMakeLists.txt on hphp/runtime folder. The custom command that generates the file `ir-opcode-generated.h` is invoked after make starts to build ext_zend_compat when we do a parellel build with `make -jn`. Notice that problem only occurs when build with `-jn` option.

**Comment by racardoso** [comment]
https://github.com/facebook/hhvm/blob/master/hphp/runtime/CMakeLists.txt#L31

**Comment by Orvid** [comment]
I've got a fix internally, but we're having issues with our syncing tool.
Until we can get that sorted out, here's the diff: https://gist.github.com/Orvid/688301723979cf2e8568e5de596a8850

**Comment by octmoraru** [comment]
Was fixed in https://github.com/facebook/hhvm/commit/25c12df80e929b286bc72556d8f346ee835e097a
