### ISSUE TITLE
`echo` not allowed as lambda body

### ISSUE THREAD

**Issue by HRMsimon** [facebook/hhvm#7548]
### HHVM Version

3.16.0-dev

### Standalone code, or other way to reproduce the problem
```hack
<?hh // strict

function foo(array<Stringish> $vals): void {
  array_map(($v) ==> echo($v), $vals);
}
```

### Expected result

Either Hack complains about the `echo` or HHVM allows it

### Actual result
```
$ hh_client
No errors!
$ hhvm test.php
Fatal error: syntax error, unexpected T_ECHO in test.php on line 4
```

Switching to `echo $v` gives rather weird errors:
```
test.php:4:3,26: Too few arguments (Typing[4104])
  /tmp/hh_server/hhi_29d3e0bd/stdlib/builtins_array.hhi:117:10,18: Definition is here
test.php:4:22,25: Unbound name: echo (a global constant) (Naming[2049])
test.php:4:22,25: Unbound global constant (Typing) (Typing[4106])
test.php:4:27,28: Expected ) (Parsing[1002])
```

**Comment by paulbiss** [comment]
Echo is a statement not a function, so you need to say:

```
array_map(($v) ==> { echo $v; }, $vals);
```

Also your lambda is returning null implicitly so array_map is giving you an array of nulls. Hack should complain about this.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

hh_client reports an error when using a statement as a expression bodied lambda in newer hhvm versions.
```
Parsing[1002] An expression is expected here.
   --> src/file.hack
  6 |   array_map(($v) ==> echo($v), $vals);
    |                          ^

1 error found.
```
