### ISSUE TITLE
SQL Server new driver support

### ISSUE THREAD

**Issue by sirio3mil** [facebook/hhvm#7551]
Now that Microsoft release new https://github.com/Microsoft/msphpsql driver for linux and windows, there are plans to support this extension in a near future?

**Comment by mofarrell** [comment]
We're a small team, and it doesn't look as though anyone in the community is actively working on this issue, so we've decided to close it. If you plan to send us a pull request resolving the issue let us know in the comments and we will re-open it and assign it to you. If you feel this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
