### ISSUE TITLE
Missing Hacklang interface for "everything convertible to a string"

### ISSUE THREAD

**Issue by janoszen** [facebook/hhvm#7566]
### HHVM Version

3.15.2

### Standalone code, or other way to reproduce the problem

The typechecker complains about this code:

```
<?hh // strict

function test(\Stringish $test) : void {
}

function test2() : void {
    test(1);
}
```

### Expected result

Either \Stringish should cover everything that's convertible to a string, or there should be an interface to express that.

This would be useful when writing exceptions that are generic in nature. It can be worked around by using generics, but it's not ideal because there has to be code explicitly checking for string convertibility when including the original data into the exception message.

### Actual result

Typechecker error:

```
test.php:7:10,10: Invalid argument (Typing[4110])
  test.php:3:15,24: This is an object of type Stringish
  test.php:7:10,10: It is incompatible with an int
```

**Comment by elgenie** [comment]
"Convertible to a string" means that, were you to typecast to a string (ie `(string) $foo`), the cast would succeed **and be meaningful**. A `Stringish` typehint means that the caller should've made their decisions about how the argument is to be stringified either at the callsite by converting to a string or by passing an object whose class specifies how it is to be stringified (via `__toString`).

Hack tries to avoid the implicit conversion craziness of http://php.net/manual/en/language.types.string.php#language.types.string.casting .

The code in question should be:

    test('1');

Or, more meaningfully:
 
   $foo = something_that_returns_an_int();
   test((string) 10);

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

The [blogpost](https://hhvm.com/blog/2018/12/17/hhvm-3.30.html) for hhvm 3.30.0 announced the deprecation of the `\Stringish` typelike. With `__toString()` gone, you could argue that `arraykey` covers both `string` and `int`. Maybe `float` should be in that list too, in which case, you'd need to declare a union type. `type TStringLike = (arraykey | float)`, which requires an **experimental** flag announced in hhvm [4.26.0](https://hhvm.com/blog/2019/10/09/hhvm-4.26.0.html).
