### ISSUE TITLE
Feature request: Union interface for IndexAccess and KeyedContainer for MutableVector and MutableMap

### ISSUE THREAD

**Issue by acrylic-origami** [facebook/hhvm#7573]
### HHVM Version

```
$ hhvm --version
HipHop VM 3.16.0-dev (rel)
```

### Standalone code, or other way to reproduce the problem

My specific application is with tree structures in Hack, but in general, this would be incredibly useful for immutable collection wrappers with mutable interfaces that extend them. For example, consider the following:

```php
<?hh // strict
interface MutableUnion<Tk, Tv> extends KeyedContainer<Tk, Tv>, IndexAccess<Tk, Tv> {}
// such that `MutableVector extends MutableUnion` and `MutableMap extends MutableUnion`
class ImmutableWrapper<+Tk, +Tv> {
	public function __construct(private KeyedContainer<Tk, Tv> $collection) {}
	public function get_collection(): KeyedContainer<Tk, Tv> {
		return $this->collection;
	}
	public function use_collection(/* ... */): void {
		$collection = $this->get_collection();
		// do things with $collection;
		// in MutableWrapper, this would be MutableUnion.
	}
}
class MutableWrapper<Tk, Tv> extends ImmutableWrapper<Tk, Tv> {
	public function __construct(private MutableUnion<Tk, Tv> $collection) {
		parent::__construct($collection);
	}
	<<__Override>>
	public function get_collection(): MutableUnion<Tk, Tv> {
		return $this->collection;
	}
	public function mutate_collection(Tk $k, Tv $v): void {
		$this->collection->set($k, $v); // for example
	}
}
```

### Expected result

If `MutableVector` and `MutableMap` both extended `MutableUnion`, since they both already implement `KeyedContainer`, I could pass either to both classes.

### Actual result

In lieu of a union type, I would accept `KeyedContainer` collection and reconstruct it to a `Map` (`Map::__construct(?KeyedTraversable<Tk,Tv> $it)`, and `KeyedContainer <: KeyedTraversable`). Then, I would override `ImmutableWrapper::get_collection` in `MutableWrapper`. All in all:

```php
class MutableWrapper<Tk, Tv> extends ImmutableWrapper<Tk, Tv> {
	private Map<Tk, Tv> $collection;
	public function __construct(KeyedContainer<Tk, Tv> $collection) {
		$this->collection = new Map($collection);
		parent::__construct($collection);
	}
	<<__Override>>
	public function get_collection(): KeyedContainer<Tk, Tv> {
		return $this->collection;
	}
	public function mutate_collection(Tk $k, Tv $v): void {
		$this->collection->set($k, $v); // for example
	}
}
```

Copying and destroying the original collection type is much less flexible, which is why I would prefer to avoid this solution.

**Comment by lexidor** [comment]
Hack arrays do have nice interface types.
```
                AnyArray<Tk, Tv>
     vec_or_dict<Tk, Tv>         keyset<Tk>
vec<Tv>    dict<Tk, Tv>
```

Adding more features for legacy Hack collections would go against the spirit of modern Hack.

[Array introductions](https://docs.hhvm.com/hack/arrays-and-collections/introduction)
> Hack collections are deprecated object types for storing iterable data. The types available include [Vector](https://docs.hhvm.com/hack/reference/class/HH.Vector/), [Map](https://docs.hhvm.com/hack/reference/class/HH.Map/), [Set](https://docs.hhvm.com/hack/reference/class/HH.Set/), [Pair](https://docs.hhvm.com/hack/reference/class/HH.Pair/) and helper interfaces.

[Ref release notes](https://github.com/hhvm/hsl/releases/tag/v4.7.0)
> There are cases like the above where Ref is the cleanest solution; you may also find Ref<vec<T>> to be preferable to Vector<T>, in order to use a consistent API and be more explicit about when a function is likely to mutate a container.

I am closing this issue, because Hack collections don't get new features anymore.
