### ISSUE TITLE
Awaitable can be disposed by assigning to local

### ISSUE THREAD

**Issue by acrylic-origami** [facebook/hhvm#7578]
### HHVM Version

```
$ hhvm --version
HipHop VM 3.16.0-dev (rel)
Compiler: heads/master-0-g07c7a02cd850b51c85ab64692298a91eb1c3e0c5
Repo schema: a0d9f666dd3c0dc8a940e03788cabf7bed52809d
```

### Standalone code, or other way to reproduce the problem

```php
<?hh // strict
function foo(): void {
	$_ = async{};
}
```

### Expected result

> This expression is of type Awaitable, but it's either being discarded or used in a dangerous way before being awaited (Typing[4015])

### Actual result

> No errors!

I'm guessing that the current implementation of this error check just checks for _something_ on the left side of an Awaitable? If an Awaitable is available in some scope, I imagine it not too far of a departure from the current toolset to check if the value is exported (e.g. returning, throwing, stashing in static property, stashing in local property, stashing in locally-declared object and returning object, stashing in argument object and applying the same rules to the setter). However, I can imagine some other cases might be more challenging, like proving an Awaitable stashed in a property isn't disposed in the parent scope, e.g.:

```php
<?hh // strict
class A {
	private Awaitable<void> $v;
	public function __construct() {
		$this->v = async{};
	}
}
function foo(): void {
	new A(); // <- Error here along the lines of 'A::__construct() generated Awaitable that is either being discarded... (Typing[4015])
}
```

I'm making a Reactive library in Hack built off of async, and this would be a really nice and simple way to ensure the top-level scope always awaits the longest Awaitable. Were/are there any plans to strengthen this check?

**Comment by lexidor** [comment]
Hack would need to scan your entire method to ensure that you don't have an unconditionally executed `await $v` in your method, in order to not give you false positives.
This may simply be an implementation constraint.

Assigning an Awaitable to `$_` is in effect dropping it, since `await $_` is illegal use. This could be reported on, but this should be super rare.

**Comment by acrylic-origami** [comment]
@lexidor Yeah, fair enough. It was just a nice-to-have to help avoid any holes in my time management for the framework I was building, but some good ol' fashioned prudence was really the best solution here.
