### ISSUE TITLE
hhvm error 330 net::ERR_CONTENT_DECODING_FAILED

### ISSUE THREAD

**Issue by wgnsa** [facebook/hhvm#7579]
### HHVM Version
HipHop VM 3.18.0-dev (rel)
Compiler: heads/master-0-gc6a4294bba1e43420c55d48fee0b93ee30ac7ee6
Repo schema: 41f61001c736ec679517afb2fd1daadc680ddc26
### Standalone code, or other way to reproduce the problem
Content Encoding Error

The page you are trying to view cannot be shown because it uses an invalid or unsupported form of compression.

    Please contact the website owners to inform them of this problem.

**Comment by mofarrell** [comment]
This issue has been waiting for more info for more than 2 weeks. I'm closing it for now, but feel free to re-open it if you can provide more info. https://github.com/facebook/hhvm/wiki/Human-Timeouts
