### ISSUE TITLE
lz4_compress output not readable by php (php-ext-lz4)

### ISSUE THREAD

**Issue by nemphys** [facebook/hhvm#7580]
### HHVM Version
3.17.0 (and all previous)
### Standalone code, or other way to reproduce the problem
function strToHex($string){
    $hex = '';
    for ($i=0; $i<strlen($string); $i++){
        $ord = ord($string[$i]);
        $hexCode = dechex($ord);
        $hex .= substr('0'.$hexCode, -2);
    }
    return strToUpper($hex);
}
echo strToHex(lz4_compress('test'));
### Expected result
040000004074657374
### Actual result
044074657374

It seems that the result header in hhvm is calculated in a different way than in php-ext-lz4 (v0.2.7, before the 0.3.0 syntax change) and therefore the result is not interchangeable (though the method signature is the same).
This leads to unexpected results when accessing the same compressed data with both hhvm and php.

**Comment by mklooss** [comment]
Test 001.phpt just results also wrong:
https://github.com/kjdev/php-ext-lz4/tree/536bd8d71a345c3985d8d857c9c5e4d1f3237c53/tests

**Comment by azjezz** [comment]
should be closed.

PHP is not supported any more.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Following @azjezz's advice on this.
Hhvm can decompress "test" if compessed by hhvm.

```HACK
<<__EntryPoint>>
function main(): void {
  echo \lz4_uncompress(\lz4_compress('test') as string);
}
```
