### ISSUE TITLE
Building repo fails without any useful error message

### ISSUE THREAD

**Issue by alex-mashin** [facebook/hhvm#7588]
### HHVM Version
3.17, 3.17.1

### Standalone code, or other way to reproduce the problem
MediaWiki 1.28, building a repo for Repo Authoritative mode

### Expected result
At least say something helpful before dying

### Actual result
```
'hhvm' '--hphp' '--target' 'hhbc' '--format' 'binary' '--force' '1' '--keep-tempdir' '1' '--log' '3' '-v' 'AllVolatile=true' '--input-dir' '/var/www/wiki/w/' '--input-list' '/tmp/mw-make-repo1097927029/file-list' '--output-dir' '/tmp/mw-make-repo1097927029'
```

(unable to stat several files (mostly present) as usual)

```
analyzeProgram...
analyzeProgram took 0'09" (9039240 us) wall time
parsing inputs took 0'19" (19782415 us) wall time
pre-optimizing...
hphp failed
running hphp took 0'22" (22410038 us) wall time
Error: HHVM returned error code 255
```

I hadn't really expected hphp to build a repo, but I had hoped that it would fail for something that would look like a reason. But no. Nothing in `var/log/hhvm/error.log` either.

**Comment by paulbiss** [comment]
It looks like it may be crashing, do you see any core dumps or stacktraces?

**Comment by alex-mashin** [comment]
> It looks like it may be crashing, do you see any core dumps or stacktraces?

There are no dumps or stacktraces; I have provided everything.

>  mofarrell added the needs more info label 4 days ago

That's the problem: I need more info too.

Under HHVM 3.17.1 the problem persists.

**Comment by Reasno** [comment]
Saw the same error here. You are not along. Don't have a clue either.

**Comment by mofarrell** [comment]
A trace with symbols would be useful if possible to reproduce.

**Comment by alex-mashin** [comment]
Since MW no longer supports HHVM, the issue can be closed.
