### ISSUE TITLE
hhvm.server.startup_document does not seem to do anything

### ISSUE THREAD

**Issue by eryi** [facebook/hhvm#7590]
### HHVM Version
HipHop VM 3.17.0 (rel)
Compiler: tags/HHVM-3.17.0-0-ga34af693b558ed98ffafc3f5127e00959e145e4f
Repo schema: 8eda451fe80742a18e0e2e8917aa4053c2c1afe7

### Standalone code, or other way to reproduce the problem
/home/user/startup.hh
````
<?hh
file_put_contents('/tmp/startup.txt', 'contents');
````

start server

    hhvm -m server -p 8080 -d hhvm.server.startup_document=/home/user/startup.hh
    
### Expected result
/tmp/startup.txt is created

### Actual result
/tmp/startup.txt is not created

Looking at [hphp/runtime/server/http-server.cpp](https://github.com/facebook/hhvm/blob/10b4a1aeb38979d8632ab7496ddab390777f6b2d/hphp/runtime/server/http-server.cpp), there is no reference to StartupDocument option at all

**Comment by mofarrell** [comment]
This was [deleted](https://github.com/facebook/hhvm/commit/e4c4e0ef0789da3b3daa14ea01d2a476212403d5) in august.  If you want to check if HHVM is running (what you appear to be doing with your `startup.txt`) look for the pid file in `/var/run/hhvm/`.  If you are trying to warmup HHVM (what this used to be intended for) see the new way of doing this [here](https://github.com/facebook/hhvm/issues/5312#issuecomment-105287618).
