### ISSUE TITLE
Different floating point results with on modern machines (-ffp-contract)

### ISSUE THREAD

**Issue by cmuellner** [facebook/hhvm#7594]
We've observed, that on modern machines (arm64 machines or Intel Haswell+)
the selftest hphp/test/slow/ext_date/date_sunrise_test.php fails, because of
a calculated value which does not match the expected value
(we got 9.6226631046689 instead of 9.622663104669).

The reproduce the issue gcc needs to emit FMA (floating-point multiply-add)
instructions, which will be done by default when using -O2 when the target system
supports them (arm64 or Intel Haswell+).

So a function like this:

```
double foo(double a, double b, double c) {
    return a*b+c;
}
```

results in this code on arm64:

```
foo(double, double, double):
        fmadd   d0, d0, d1, d2
        ret
```

and this code on x64 Haswell (-march=native):

```
foo(double, double, double):
        vfmadd132sd     xmm0, xmm2, xmm1
        ret
```

The FMA instruction does not round the intermediate result (of the multiplication).
This can lead to the result to be more precise (which is different than expected).

GCC offers the flag -ffp-contract to disable emitting contracted floating-point
instructions (-ffp-contract=off).
I can prepare a patch for putting that flag to the CFLAGS, but I don't know if
this is the desired "fix" for the issue.

An alternative solution would be to compare imprecise (value must be within
epsilon environment of expected value).

Our analysis showed that the affected code by this issue is in timelib,
where astro.c contains lots of lines like `w = 282.9404 + 4.70935E-5 * d;`.
Note, that this means that PHP (5/7) is affected by this issue as well.

What is the desired fix for this issue?

**Comment by cmuellner** [comment]
Mentioning @mxw @ptomsich @swalk-cavium @dave-estes

**Comment by apinski-cavium** [comment]
Hmm, I wonder here.  PowerPC has the same issue too.  The difference between the two numbers is 1^-12% not enough to even worry about.  Though there are other cases where the difference matters a lot.

I think the biggest question here is what are the requirements for floating point with PHP, is 1-2 ulp difference ok not to worry about it?

**Comment by cmuellner** [comment]
@apinski-cavium PHP (the language) is not affected as the JIT does (currently) not emit such instructions. It is just about C/C++ code which gets compiled by GCC (e.g. timelib).
Interesting fact is, that the result is "equal or more correct" than before (I guess that's why it is
turned on by default in GCC).

**Comment by swalk-cavium** [comment]
In my previous life, this was the kind of thing that would be documented and left for the
end user to decide.  Something like you mentioned above with the gcc option.
I guess we need to hear from the PHP language lawyers.

I did find a couple of packages which suggest somewhere someone is doing numerical
analysis in php.

https://github.com/markrogoyski/math-php

**Comment by swalk-cavium** [comment]
Actually, I would vote for a bad test case.  Should it really be checking down in the ulp range?

**Comment by mxw** [comment]
cc/ @markw65, @binliu19 

Consensus internally is that at the very least, the test should probably not care about this much precision.  We can use `printf()` or `round()` instead to specify.

@cmuellner—Want to update the test, confirm it works for you on the relevant platforms, and put up a PR?

**Comment by cmuellner** [comment]
@mxw sure.

**Comment by cmuellner** [comment]
@mxw how to deal with the same problem in libgd?

Test case hphp/test/slow/ext_gd/imageaffine.php fails, when arrAffine contains floats.
The reason is that the function gdAffineApplyToPointF() in gd_matrix.cpp contains
C++ code, which g++ converts to FMA instructions:

```
int gdAffineApplyToPointF (gdPointFPtr dst, const gdPointFPtr src,
      const double affine[6])
{
  double x = src->x;
  double y = src->y;
  x = src->x;
  y = src->y;
  dst->x = x * affine[0] + y * affine[2] + affine[4];
  dst->y = x * affine[1] + y * affine[3] + affine[5];
  return GD_TRUE;
}
```

arm64 GCC on Ubuntu Xenial:

```
00000000022c3ad8 <gdAffineApplyToPointF>:
 22c3ad8:       6d400820        ldp     d0, d2, [x1]
 22c3adc:       aa0003e3        mov     x3, x0
 22c3ae0:       fd400843        ldr     d3, [x2,#16]
 22c3ae4:       52800020        mov     w0, #0x1                        // #1
 22c3ae8:       fd400041        ldr     d1, [x2]
 22c3aec:       fd401044        ldr     d4, [x2,#32]
 22c3af0:       1e630843        fmul    d3, d2, d3
 22c3af4:       1f410c01        fmadd   d1, d0, d1, d3
 22c3af8:       1e642821        fadd    d1, d1, d4
 22c3afc:       fd000061        str     d1, [x3]
 22c3b00:       fd400c44        ldr     d4, [x2,#24]
 22c3b04:       fd400443        ldr     d3, [x2,#8]
 22c3b08:       fd401441        ldr     d1, [x2,#40]
 22c3b0c:       1e640842        fmul    d2, d2, d4
 22c3b10:       1f430800        fmadd   d0, d0, d3, d2
 22c3b14:       1e612800        fadd    d0, d0, d1
 22c3b18:       fd000460        str     d0, [x3,#8]
 22c3b1c:       d65f03c0        ret
```

We could append `-ffp-contract=off` to the `CXXFLAGS`.
However, it is not possible to set this for the gd extension only,
so the flag would be set for the whole HHVM project.

**Comment by ptomsich** [comment]
Christoph,

Let’s keep the use of FMADD on AArch64, as it’s not a ISA extension but an ISA feature.
I would consider this an issue in the test-case again (if a test-case fails).

For what it’s worth, FP contraction should always be preferable to compounded rounding errors from individual FP instructions.
Usually the code using individual instructions will have a slightly less accurate result.

--Phil.

**Comment by mofarrell** [comment]
Reopening.  Still more PR to land before the tests are entirely fixed.

**Comment by cmuellner** [comment]
@mofarrell : I think only two tests are affected by this issue,
because only two tests failed reliably in release builds,
while never failed in debug builds (tested on four arm64 machines
running Ubuntu Xenial, Fedora 25, CentOS 7 and OpenSuse LEAP 42.2).
No other failed tests showed this characteristics (failing on release
builds only).

The two tests are date_sunrise_test.php and imageaffine.php.

A PR for date_sunrise_test.php is already merged and a PR for
allowing an alternative result for floating-point calculations of
libgd in test imageaffine.php has been opened yesterday.

**Comment by mofarrell** [comment]
@cmuellner I was just reopening because the image affine change hadn't landed yet.  It should be closed again once I get that one in.
