### ISSUE TITLE
Incorrect scope handling enforces bug-prone code.

### ISSUE THREAD

**Issue by rzvc** [facebook/hhvm#7599]
### HHVM Version
3.17.1

### Standalone code, or other way to reproduce the problem
```
$items = [1, 2, 3];

foreach ($items as &$v)
{
}

unset($v); // Not allowed, says the variable does not exist in this scope, but it does.

// Given that we can't unset it, any subsequent use of the variable $v, will overwrite the
// last item it points to.
$v = 'corrupted';

print_r($items);
```

Same thing happens here:
```
$items = [1, 2, 3];

foreach ($items as $k => $v)
{
	$z = &$items[$k];
}

unset($z); // Complains about the undefined variable.

$z = 'corrupted';

print_r($items);
```

### Expected result
I would expect it to either let me unset it and if I don't, keep track of the variable with its current type, or, it could simply remove it once it goes out of scope, so writing to it would simply initialize a new variable.

### Actual result
Array
(
    [0] => 1
    [1] => 2
    [2] => corrupted
)

**Comment by photodude** [comment]
I ran tests on travis CI and on 3v4l and did not get your errors, seems like something else is going on causing your errors

https://travis-ci.org/photodude/HHVM_code_snip_tests/jobs/191747068
https://3v4l.org/CmFK6
https://3v4l.org/n0mYu

**Comment by rzvc** [comment]
This is my test setup:
```
$ cat test.hh 
<?hh

function test()
{
	$items = [1, 2, 3];

	foreach ($items as &$v)
	{
	}

	unset($v);
}
```

And if I run it:
```
$ hhvm test.hh 

Catchable fatal error: Hack type error: The variable $v is defined at /home/rzvc/tmp/code/test.hh line 11
```

Please take note of the following:
1) The error is not there in <?php mode.
2) The error is not there if the code is in the global scope.
3) I'm not getting that error on 3v4l, which might indicate that it's an issue introduced in later versions, since 3v4l is using 3.13.2.

https://3v4l.org/6st1c

**Comment by photodude** [comment]
so It's **hack** specific and not HHVM in php mode specific. (I only test vs php modes)

FYI for hack language in strict mode, 'unset is banned except on array indexing'

**Comment by simonwelsh** [comment]
Hack also does not support references. Silently ignores them in partial, errors on them in strict.

**Comment by rzvc** [comment]
Ignoring them is clearly the wrong solution here. It's fine if it doesn't support them in strict mode, but if it allows them in partial mode, it should do it properly.

**Comment by photodude** [comment]
You have two things here, references and unset() both are banned in strict mode hack. Even in partial mode hack references are silently ignored (i.e. Runs as though the references were not there)  
It's language design intention,

**Comment by photodude** [comment]
Here is the documentation that explains why references are not supported in hack

https://docs.hhvm.com/hack/unsupported/references

**Comment by photodude** [comment]
And here is a reference regarding unset() in hack and why it's not supported 
https://www.safaribooksonline.com/library/view/hack-and-hhvm/9781491920862/ch04.html

**Comment by rzvc** [comment]
It doesn't matter.

If it's not meant to support them, it should error out. If it allows them however, it shouldn't throw errors like that one, which will make the programmer think it's ok to remove the unset(), because the error message implies that hhvm takes care of that reference when it goes out of scope.

There are 3 options here:
1) Ban references in partial mode.
2) Track them outside of the scope in which they're defined.
3) Actually unset them when they go out of scope, as that error message is implying (but that breaks compatibility with PHP).

There's no way around it and no amount of specification is going to make up for the fact that the way it's currently dealing with them is wrong and makes the programmer create bad code, which is exactly what Hack is meant to prevent.

**Comment by photodude** [comment]
>You can use references in partial mode and decl mode, but they are not typechecked. The typechecker pretends that references don't exist: the & is invisible to the typechecker in these modes. **So use them at your own risk**, because with more complicated reference usage, it is easy to cause type errors the typechecker can't see.

>The typechecker issues an error in strict mode anytime you try to use a reference.

>unset is a bit different. There’s simply no reason to use it on a variable in Hack. If you want to get the same effect, just assign null to the variable. In PHP, there’s one other reason to use unset on a variable—to break a reference relationship—but in Hack this isn’t necessary because references aren’t supported.

**Comment by rzvc** [comment]
> You can use references in partial mode and decl mode, but they are not typechecked. The typechecker pretends that references don't exist: the & is invisible to the typechecker in these modes. So use them at your own risk, because with more complicated reference usage, it is easy to cause type errors the typechecker can't see.

This is not applying here as this is not a type error that's being generated because of code the typechecker can't see/analyze. It's an error generated by the typechecker itself because it's trying to enforce block scope level typing, when the underlying engine doesn't really support it.

> The typechecker issues an error in strict mode anytime you try to use a reference.

This is not about strict mode.

> unset is a bit different. There’s simply no reason to use it on a variable in Hack. If you want to get the same effect, just assign null to the variable. In PHP, there’s one other reason to use unset on a variable—to break a reference relationship—but in Hack this isn’t necessary because references aren’t supported.

Obviously false. As long as it's not issuing an error, it's supporting them.

**Comment by fredemmott** [comment]
References aren't really relevant here: the typechecker does not make a distinction between empty and non-empty containers. If the container were empty, it would be an undefined variable.

**Comment by fredemmott** [comment]
To clarify:

```Hack
function foo<T>(array<T> $in) {
  foreach ($in as $x) {
    // ...
  }
 do_stuff($x); // clearly unsafe
}
```

**Comment by fredemmott** [comment]
as for special-casing unset to not care: unset is unsupported in hack code. Partial mode is not defined (even in the language specification)
