### ISSUE TITLE
Type refining issue in the Hack specification.

### ISSUE THREAD

**Issue by rzvc** [facebook/hhvm#7601]
### HHVM Version
3.17.1

### Issue
As described here: https://docs.hhvm.com/hack/types/refining#object-instance-checks__instanceof-gotcha

That instanceof gotcha, while it's not a bug, since it seems to be intended, it also seems to be defying logic and it shouldn't be in the specification.

Given that $b is already type checked, we know that at any point in that function, it's **AT LEAST** of type Base. The further instanceof test, makes it Base + I, not an intersaction of the two types.

Inside the block of the if () statement, we know that $b object implements the I interface too, in addition to being a Base. Outside of the if () statement, it's just a Base and even if we had an else statement there, we'd just know that $b is not extending I at that point, nothing more.

The current explanation states:

> Even though bar() was passed in a Base, and all children of Base implement foo(), once the instanceof check was done on $b, and the check returned true, the typechecker has to assume that $b is now an unresolved type of both Base and I.

This is obviously the wrong conclusion, proven both by the example itself (which is perfectly correct) and, I hope, by what I said above.

If I'm wrong and there's a real reason why it's being interpreted like that, perhaps the scenario that makes this behavior desirable should be added to the documentation.

For reference, the code from the documentation:
```
<?hh

namespace Hack\UserDocumentation\Types\Refining\Examples\Unresolved;

interface I {
  public function i_method(): bool;
}

abstract class Base {
  abstract public function foo(): string;
}

class Child1 extends Base implements I {
  <<__Override>>
  public function foo(): string {
    return "Child1";
  }
  public function i_method(): bool {
    return true;
  }
}

class Child2 extends Base {
  <<__Override>>
  public function foo(): string {
    return "Child2";
  }
}

function bar(Base $b): void {
  if ($b instanceof I) { // refine $b to interface I, but makes $b unresolved
    echo $b->i_method();
  }
  // This is a type error!
  // Given the instanceof check above, we have now made $b unresolved, a union
  // between a type of I and Base. So we can only call methods common to both.
  // which in this case there are none.
  echo $b->foo();
}

function unresolved(): void {
  $c = new Child1();
  bar($c);
}

unresolved();
```

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This `instanceof` gotcha has been addressed by the introduction of intersection types in hhvm [4.14.0](https://hhvm.com/blog/2019/07/15/hhvm-4.14.0.html).
