### ISSUE TITLE
official docker facebook/hhvm image and automated- build? for docker

### ISSUE THREAD

**Issue by 08ski11s** [facebook/hhvm#7621]
it will be great to have an official docker image/build for facebook/hhvm for docker pull image/automated-build

latest version - to docker pull latest version 
latest version tags - to choose which version 
with updates / changelogs etc
with properly documented docker image/build

**Comment by jazzdan** [comment]
I believe this exists

https://github.com/hhvm/hhvm-docker
https://registry.hub.docker.com/u/hhvm/hhvm/

**Comment by 08ski11s** [comment]
i think its not an official docker image/build for hhvm

**Comment by jazzdan** [comment]
@08ski11s it's in the hhvm namespace on GitHub, and updated by members of the core team so I think it is official. :)

**Comment by 08ski11s** [comment]
@jazzdan request to make it official or marked it official.. :)

**Comment by 08ski11s** [comment]
@jazzdan thanks ^_^

**Comment by 08ski11s** [comment]
follow-up: also make it official on docker hub

**Comment by SiebelsTim** [comment]
See: https://docs.hhvm.com/hhvm/installation/docker

**Comment by mofarrell** [comment]
I will look into getting it marked as official.  This is being tracked by https://github.com/hhvm/packaging/issues/138
