### ISSUE TITLE
Use of undefined constant ARRAY_FILTER_USE_BOTH

### ISSUE THREAD

**Issue by Gummibeer** [facebook/hhvm#7622]
### HHVM Version
3.6.6~precise

### Standalone code, or other way to reproduce the problem
https://travis-ci.org/fenos/Notifynder/jobs/195472386
```php
array_filter($array, $callback, ARRAY_FILTER_USE_BOTH);
```
The Code itself is in the `illuminate/support` package.

### Expected result
no Exception - by default it's defined with `define("ARRAY_FILTER_USE_BOTH", 1);`

### Actual result
> ErrorException: Use of undefined constant ARRAY_FILTER_USE_BOTH - assumed 'ARRAY_FILTER_USE_BOTH'

**Comment by mofarrell** [comment]
@Gummibeer HHVM 3.6 has been out of support for over a year now.  The most recent LTS release at the moment is 3.15, and 3.18 will be released shortly.  3.15 and 3.18 will on Ubuntu Trusty or Xenial.

This appears to have been fixed before the 3.15 cut: https://3v4l.org/PGZkQ
