### ISSUE TITLE
foo()::blah() not supported

### ISSUE THREAD

**Issue by jesseschalken** [facebook/hhvm#7625]
### HHVM Version

HipHop VM 3.18.0-dev (rel)
Compiler: heads/master-0-g0f6803df27b27f929f5edc175e11d302643f3a2c
Repo schema: 1733dfccb8791a77b6ce7b894ddd66e3238c2106

### Standalone code, or other way to reproduce the problem

```php
<?hh // strict

class Foo {
    public static function blah(): void {
        echo __METHOD__ . "\n";
    }
}

function get_foo(): classname<Foo> {
    return Foo::class;
}

function main(): void {
    get_foo()::blah();
}

main();
```
```
$ hh_client
$ hhvm test.php
```

### Expected result

```
$ hh_client
No errors!
$ hhvm test.php
Foo::blah
```

### Actual result

```
$ hh_client
test.php:14:5,13: Expected class name (Parsing[1002])
$ hhvm test.php
Fatal error: Uncaught Error: syntax error, unexpected T_DOUBLE_COLON in ./test.php:14
Stack trace:
#0 {main}
```

### Discussion

If I change `<?hh` to `<?php` and remove the type annotations, running the file in PHP works fine.

```
$ php test.php
Foo::blah
```

But still doesn't work on HHVM, even in PHP7 mode.

```
$ hhvm test.php
Fatal error: Uncaught Error: syntax error, unexpected T_DOUBLE_COLON in ./test.php:14
Stack trace:
#0 {main}
$ hhvm -dhhvm.php7.all=1 test.php
Fatal error: Uncaught Error: syntax error, unexpected T_DOUBLE_COLON in ./test.php:14
Stack trace:
#0 {main}
```

**Comment by jesseschalken** [comment]
@jwatzman Would you happen to know how to fix this? It seems related to https://github.com/facebook/hhvm/commit/799c136e865a95f6bed8988f37adbab2912af50a in which you added support for `Foo::bar()::baz()`, but not `foo()::baz()` or `$obj->foo()::bar()`. Is there a reason you didn't allow class name expressions to be something more general?

PHP7 permits the class name (`variable_class_name`) to be an arbitrary `dereferencable`, which includes `variable` which includes `callable_variable` which includes `function_call` ([link](https://github.com/php/php-src/blob/master/Zend/zend_language_parser.y#L1106)), but I'm having trouble correlating the rules between the two parsers considering they give things different names and split things up differently for inexplicable reasons.

**Comment by jwatzman** [comment]
Sadly I don't recall. The most likely reason is that it was just an oversight on my part. I do recall there was at least one construction that I ran into serious issues getting the parser to support properly without horrific reduce/reduce issues -- it might have been this one, I sadly don't remember :(

**Comment by jwatzman** [comment]
Looking at the history of that diff and my comments on #5523, it seems most likely this was just an oversight on my part.
