### ISSUE TITLE
MySQL poll() syscall can hang request indefinitely

### ISSUE THREAD

**Issue by RyanGordon** [facebook/hhvm#7627]
### HHVM Version

HHVM 3.17.1

### Standalone code, or other way to reproduce the problem
1. Start a SELECT query on a MySQL table that takes a long time to run. Use `strace -e poll -f` to watch for poll() syscalls
2. sudo kill -SIGSTOP `MYSQL PID` (close to simulating a MySQL that is frozen or under very high load)
3. Observe that the `poll` syscall hangs there indefinitely.

Simple example observed output:
```
...
poll([{fd=9, events=POLLIN|POLLPRI}], 1, 4294967295) = 1 ([{fd=9, revents=POLLIN}])
poll([{fd=9, events=POLLIN|POLLPRI}], 1, 4294967295) = 1 ([{fd=9, revents=POLLIN}])
poll([{fd=9, events=POLLIN|POLLPRI}], 1, 4294967295
# --> sudo kill -SIGSTOP 5424
...
# poll indefinitely hangs due to high default timeout
```

### Expected result

While this is not buggy behavior, it is undesirable because there is currently no way to configure the timeout on `poll` through the PDO extension to enable clients to be more resilient to failure edge cases.

### Actual result

The client code hangs indefinitely.

**Comment by mofarrell** [comment]
cb8c85679d4e800b86bfd77a618cf19a69878a67 should mitigate this issue
