### ISSUE TITLE
Hack doesn't know about MySQLi

### ISSUE THREAD

**Issue by HRMsimon** [facebook/hhvm#7652]
### HHVM Version
c1aff71d41 

There's no HHI files for the MySQLi classes, functions or constants which makes it annoying to use in strict mode

**Comment by Sebastiansch** [comment]
:+1:

**Comment by fredemmott** [comment]
*cough* https://docs.hhvm.com/hack/async/extensions#mysql :p

**Comment by HRMsimon** [comment]
While I'd like to switch to async mysql, that's a lot more work than typing our existing code :p

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

MySQLi was dropped from hhvm in version [4.9.0](https://hhvm.com/blog/2019/06/10/hhvm-4.9.0.html).
