### ISSUE TITLE
Static closures not supported by typechecker

### ISSUE THREAD

**Issue by jesseschalken** [facebook/hhvm#7653]
### HHVM Version

```
HipHop VM 3.18.0-dev (rel)
Compiler: heads/master-0-gd0d6968c4e0edea745d22f6db4507eeac2f064c5
Repo schema: 42c3f634d8a4de5c0683a82845e0f34562748899
```

### Standalone code, or other way to reproduce the problem

```php
<?hh // strict

function main(): void {
  $f = static function () {
    echo __METHOD__, "\n";
  };
  $f();
}

/* HH_IGNORE_ERROR[1002] */
main();
```

### Expected result

```
No errors!
```

### Actual result

```
test.php:4:8,13: Unbound name: static (a global constant) (Naming[2049])
test.php:4:8,13: Unbound global constant (Typing) (Typing[4106])
test.php:4:15,22: Expected ; (Parsing[1002])
```

### Discussion

Running the file in HHVM works fine:

```
$ hhvm test.php
{closure}
$
```

It also works if I convert it to PHP and run it with `php`:

```
$ php test.php
{closure}
$
```

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Static closures have been removed from hhvm in version [4.58.0](https://hhvm.com/blog/2020/05/19/hhvm-4.58.html).
