### ISSUE TITLE
Typechecker error for missing variadiac typehint has incorrect suggestion

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#7655]
### HHVM Version

3.17

### Standalone code, or other way to reproduce the problem

```Hack
<?hh // strict
function foo(... $bar): void {}
```

### Expected result

hh_client either just gives the error, or the errorr and a useful suggestion

### Actual result

hh_client says `Was expecting a type hint (what about: array)`

While it is correct that `$bar` is an `array`, the `array` part of the typehint is implicit for PHP compatibility, and is not likely to be part of the actual typehint

refs hhvm/hack-codegen#25

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

The typechecker error doesn't mention `varray<_>` in hhvm 4.56.
```
Typing[4033] Was expecting a type hint on this variadic parameter
   --> src/file.hack
  5 | function foo(...$bar): void {}
    |                 ^^^^

1 error found.
```
