### ISSUE TITLE
'Stringish' interface is in the wrong namespace, and not autoimported by the typechecker

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#7656]
### HHVM Version

3.17

### Standalone code, or other way to reproduce the problem

```
<?hh

namespace Foo\Bar;

function foo(Stringish $bar): void {
  var_dump($bar);
}

function main(): void {
  foo('123');
}
```

### Expected result

Typechecker and runtime are fine with either this, or `\HH\Stringish $bar`

### Actual result

Runtime is fine with this; typechecker is upset.

If I use `\HH\Stringish $bar`, both runtime and typechecker are upset - it appears to actually be `\Stringish`

**Comment by nguyennhuthu** [comment]
<?hh

namespace Foo\Bar;

function foo(Stringish $bar): void {
  var_dump($bar);
}

function main(): void {
  foo('123');
}

**Comment by kmeht** [comment]
Are you sure the runtime is fine with the example? Autoimport is done in the compiler, and nothing in the code leads me to believe the compiler is treating Stringish specially. What is the HHAS output?

**Comment by fredemmott** [comment]
This issue is from 2017, pre-HackC. In current releases, it's consistently `\Stringish`
