### ISSUE TITLE
Base64 Stream Filter

### ISSUE THREAD

**Issue by egeloen** [facebook/hhvm#7659]
Hey!

In 70441c3de6e0e6af51b45cc9241c5b60a2269fac, `convert.base64-(encode|decode)` stream filters has been added. This is nice but unfortunatelly, the current implementation does not take care of the base64 spec when buffering the read/write calls.

Take the following example:

```
// Replace by a file on your system
$binary = file_get_contents(__DIR__.'/Fixtures/Model/binary');
$size = strlen($binary);

$file = fopen('php://temp', 'w+');
stream_filter_append($file, 'convert.base64-encode', STREAM_FILTER_WRITE);

for ($i = 0; $i < $size; ++$i) {
    fwrite($file, substr($binary, $i, 1));
}

rewind($file);

if (stream_get_contents($file) === base64_encode($binary)) {
    echo 'OK';
} else {
    echo 'KO';
}

fclose($file);
```

The expected result of this snippet is OK but it is not (the same snippet using the PHP engine renders OK).

An other issue related is the fact that `fwrite` always returns 0 instead of the expected size. Maybe related on `__SystemLib\ConvertFilter::filter` which does not update the `$consumed` param?

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This requires functions like `\stream_filter_append()` or friends, which were removed from hhvm.

Tested on hhvm 4.56.
```
hphpd> =\stream_filter_append();
=\stream_filter_append();
Hit a php exception : Error: Call to undefined function stream_filter_append() in :1
Stack trace:
#0 (1): include()
#1 {main}
```
