### ISSUE TITLE
typechecker results caching (issues with running hhvm on a linux VM with Vagrant)

### ISSUE THREAD

**Issue by underscorefunk** [facebook/hhvm#7662]
### HHVM Version
3.17.2

### Environment
Vagrant VM Running Ubuntu 16.04, Apache 2.4.18
/var/www/html is synced to my desktop
I have checked this issue without the shared folder through virtualbox and things work as they should

### Way to reproduce the problem
Typing hh_client in /var/www/html starts up the typechecker.
The typechecker checks the files, as it should. Any errors get posted to my prompt.
If I fix a blatant error and save the file, the typechecker runs again 

### Expected result
The typechecker presents new results

### Actual result
The typechecker presents results from its first run

### Details
First off, I had "enable_on_nfs = true" to /etc/hh.conf. Otherwise the hh_client wouldn't even start up

`vagrant@vagrant:/var/www/site-name/public_html$ hh_client
For more detailed logs, try `tail -f $(hh_client --monitor-logname) $(hh_client --logname)`
Server launched with the following command:
	'/usr/bin/hh_server' '-d' '/var/www/site-name/public_html' '--waiting-client' '5'
Spawned typechecker (child pid=2600)
Logs will go to /tmp/hh_server/zSvarzSwwwzSsite-namezSpublic_html.monitor_log
No errors!`

vagrant@vagrant:/var/www/thewoodwhispererguild-xhp/public_html$ tail -f $(hh_client --monitor-logname) $(hh_client --logname)
==> /tmp/hh_server/zSvarzSwwwzSthewoodwhispererguild-xhpzSpublic_html.monitor_log <==
/etc/hh.conf:
enable_on_nfs = true

[2017-02-10 20:43:36] About to spawn typechecker daemon. Logs will go to /tmp/hh_server/zSvarzSwwwzSthewoodwhispererguild-xhpzSpublic_html.log

[2017-02-10 20:43:36] Just started typechecker server with pid: 2605.
[2017-02-10 20:43:36] Got request for typechecker. Prior request 0.0 seconds ago

==> /tmp/hh_server/zSvarzSwwwzSsite-namezSpublic_html.log <==
[2017-02-10 20:43:37] Naming: 0.011318
[2017-02-10 20:43:37] Heap size: 4181056
[2017-02-10 20:43:37] Type-decl: 0.109835
[2017-02-10 20:43:37] Heap size: 4181056
[2017-02-10 20:43:37] Type-check: 0.150852
[2017-02-10 20:43:37] Dependency table load factor: 6005 / 131072 (0.05)
[2017-02-10 20:43:37] Hashtable load factor: 18312 / 262144 (0.07) with 18312 nonempty slots
[2017-02-10 20:43:37] Waiting for daemon(s) to be ready...
[2017-02-10 20:43:37] Server is READY
[2017-02-10 20:43:37] Took 0.814597 seconds to initialize.

.... I can then go in, break the site, and the log above doesn't update. The only time I see a request for the typechecker is if I type:

`$ /var/www/site-name/public_html/hh_client`

And when I do, it says prints "no errors!" because it's not updating properly. 

Any ideas or advice you can provide is hugely appreciated. I can imagine this is an uncommon setup for local development. I find it strange that the subject doesn't seem to be covered in detail.

**Comment by underscorefunk** [comment]
Update, if I'm in the document root and type hh_client --json I get the busted error msgs. If I'm typing hh_server ./ --json I get the correct reporting of typechecker's results.

**Comment by fredemmott** [comment]
the hh_client/server workflow requires full support for interfaces like inotify, which some shared folder implementations (along with NFS) don't support.

You can use hh_server directly instead, or use a different approach. Docker on linux works fine - I've never used vagrant, but it looks like just configuring vagrant to use Docker may fix this for you.
