### ISSUE TITLE
XHP doesn't support type constants

### ISSUE THREAD

**Issue by HRMsimon** [facebook/hhvm#7664]
### HHVM Version
3.17.2

### Standalone code, or other way to reproduce the problem
```hack
<?hh

abstract class :test:user extends :x:element {
  use XHPHelpers;

  attribute string user, UserValidator::RESULT error @required, :div;
}
```

### Expected result

Type constant works.

### Actual result

hh_client: `No errors!`
hhvm: `Fatal Error: syntax error, unexpected T_DOUBLE_COLON in test.php on line 6`

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

The hh_client error has been updated to reflect this restriction.
```
Parsing[1002] Type constants are not allowed on xhp class attributes
   --> src/file.hack
 15 |     UserValidator::RESULT error @required,
    |     ^^^^^^^^^^^^^^^^^^^^^

1 error found.
```
