### ISSUE TITLE
Can't run token_get_all() on code with invalid unicode escape sequence

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#7668]
### HHVM Version

3.17, latest FB internal

### Standalone code, or other way to reproduce the problem

```PHP
<?php

$code = '<?php "Invalid\u{nope}Chars"';

var_dump(token_get_all($code));
```

Found while analyzing `hhvm/hphp/test/slow/parser/unicode-literal-error.php`

### Expected result

Token list (Same as PHP 7, PHP5)

### Actual result

```
Fatal error: Invalid UTF-8 codepoint escape sequence
```

PHP5 and 7 will show that when actually trying to execute that code, but don't make token_get_all() fail.

https://3v4l.org/EFZdE

**Comment by fredemmott** [comment]
There's also no workaround - while `hhvm.error_handling.call_user_handler_on_fatals=1` calls the error handler, the error handler is not able to convert it to an exception.

**Comment by azjezz** [comment]
should be closed.

**Comment by fredemmott** [comment]
Yep, token_get_all() was removed
