### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by ProdigyView** [facebook/hhvm#7670]
### HHVM Version
3.17
### Standalone code, or other way to reproduce the problem
Running FFMPEG? Its not clear where it fails.
### Actual result
```
Host: hhvm-worker-main
ProcessID: 14124
ThreadID: 140641638536960
ThreadPID: 14124
Name: /usr/local/bin/hhvm
Type: Segmentation fault
Runtime: hhvm
Version: heads/HHVM-3.17-0-g745ebd8121ab0d35bf40aeb2e77398c35781f161
DebuggerCount: 0

Arguments: helium.php PodcastCli process
ThreadType: CLI

#0  000000000324f8a6
#1  0000000001230673
#2  00007fe9ac464100
#3  00007fe9aea82dff
#4  00000000012d07a2
#5  00000000013ccdcc
#6  00000000031a1c5a
#7  00000000031accac
#8  000000000127cffb
#9  00000000028ebdaf
#10 000000000288a794
#11 000000000827371f
#12 000000000827277b
#13 0000000008243fa9
#14 0000000004619d1e
#15 000000000460029e
#16 0000000001fc7999
#17 000000000195e9ea
#18 00000000016e0151
#19 0000000001255732
#20 00000000032574fd
#21 00000000032577f2
#22 0000000003255914
#23 0000000001309283
#24 000000000131a7f7
#25 000000000131d595
#26 00000000009bd5b3 
#27 00007fe9a6054b15
```

**Comment by mofarrell** [comment]
Do you have an isolated example that produces the crash?
This isn't going to be enough to go by.  At least grab a build with symbols (We should have [hhvm-dbg](https://docs.hhvm.com/hhvm/installation/linux#other-packages) packages available), and give us a paste with the backtrace with symbols.

**Comment by mofarrell** [comment]
This issue has been waiting for more info for more than 2 weeks. I'm closing it for now, but feel free to re-open it if you can provide more info. https://github.com/facebook/hhvm/wiki/Human-Timeouts
