### ISSUE TITLE
CMake Error LBER_LIBRARIES (ADVANCED)

### ISSUE THREAD

**Issue by marketsystems** [facebook/hhvm#7671]
doing cmake throws and error:

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LBER_LIBRARIES (ADVANCED)
    linked by target "jit_sort" in directory /hhvm/hphp/tools/hfsort
    linked by target "hhvm" in directory  /hhvm/hphp/hhvm

I have installed ldap libraries and some error lines disappeared. I have also checked and lib-lber is present in same place as lib-ldap yet it doesnt appear to be seen...

in /usr/lib64 

ls -lt liblber*
lrwxrwxrwx 1 root root 10 Feb 14 21:49 liblber-2.4.so.2 -> liblber.so
lrwxrwxrwx 1 root root 28 Feb 14 21:49 liblber.so -> /lib64/liblber-2.4.so.2.10.3

**Comment by Orvid** [comment]
You need to do a clean CMake after installing the libraries, otherwise the CMake variable will still be set to NOTFOUND and CMake will not attempt to find them again.

**Comment by marketsystems** [comment]
ok looks like removing CMakeCache.txt worked thanks
