### ISSUE TITLE
No nightly builds since 2017-01-04

### ISSUE THREAD

**Issue by nazar-pc** [facebook/hhvm#7677]
http://dl.hhvm.com/ubuntu/pool/main/h/hhvm-nightly/

**Comment by mofarrell** [comment]
We are reworking our packaging systems, and the nightlies are still running on our old system.  They have been slowly breaking.  Hopefully our new system will be stable enough to get the nightlies onto it soon.  @aorenste

**Comment by nazar-pc** [comment]
No nightlies for over half a year, no builds for latest Ubuntu version, manual building fails hard too.
If this doesn't change, I'll have to drop HHVM support in my project, since I can't even test stuff myself.
I understand that your team is small and busy, but still.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

HHVM nightly builds are being built again.
The first nightly on https://dl.hhvm.com/ubuntu/pool/main/h/hhvm-nightly/ is from
`Mon, 06 Nov 2017 03:19:28 GMT`.

I am sorry to hear that this happened a couple of months after you dropped hhvm support from your project.
