### ISSUE TITLE
CMake version requirement incorrect

### ISSUE THREAD

**Issue by Norbyte** [facebook/hhvm#7679]
(HHVM version 3.18.0)

HHVM currently specifies CMake 2.8.7 as the minimum required version (see https://github.com/facebook/hhvm/blob/master/CMakeLists.txt#L1).
This version reqirement is incorrect, as a 6 January 2017 commit (see https://github.com/hhvm/hhvm-third-party/commit/6751564d468efb8157ac434523396fdbae65a32f) that changed the build process for ocaml uses the `-E env` CMake parameter, that was added in CMake v3.2.

**Comment by aorenste** [comment]
This is a mistake - it's fixed in third-party HHVM-3.18 ee21108e077b9d2878dfab28e1a5f0bb724791be and needs to be pulled into master.

**Comment by mofarrell** [comment]
This appears to be fixed on the 3.18 released branch, and master.
