### ISSUE TITLE
wordpress crash in repo mode

### ISSUE THREAD

**Issue by marketsystems** [facebook/hhvm#7681]
Repo mode seems to crash everytime on mysqli fetch array calls

HHVM 3.15

created repo with:

./hhvm --hphp -t hhbc -v AllDynamic=true AllVolatile=true --input-dir /var/www/vhosts/mysite/

have tried various combinations of alldynamic and allvolatile this one gets me the furthest, the page does actually display then hhvm crashes

PHP Stacktrace:

#0  mysqli_result->fetch_array()
#1  mysqli_fetch_array() called at [/wp-includes/wp-db.php:-1]
#2  wpdb->set_sql_mode() called at [/wp-includes/wp-db.php:-1]
#3  wpdb->db_connect() called at [/wp-includes/wp-db.php:-1]
#4  wpdb->__construct() called at [/wp-includes/load.php:-1]
#5  require_wp_db() called at [/wp-settings.php:-1]
#6  include() called at [/wp-config.php:-1]
#7  include() called at [/wp-load.php:-1]
#8  include() called at [/wp-blog-header.php:-1]
#9  include() called at [/index.php:-1]

always seems to happen after this in hhvm error log:

runtime/ext_mysql: successfully executed [0ms] [SELECT @@SESSION.sql_mode]
Core dumped: Aborted
Stack trace in /tmp/stacktrace.18031.log

Any clues how to debug this

**Comment by mofarrell** [comment]
Do you have the stack trace from `/tmp/stacktrace.18031.log`

**Comment by marketsystems** [comment]
That is all that was in there. Im sure i did build with debug switch too, but doesnt seem to be any backtrace anywhere

**Comment by mofarrell** [comment]
Can you run it in GDB, and paste the logs from `thread apply all bt` after the crash?

**Comment by mofarrell** [comment]
This issue has been waiting for more info for more than 2 weeks. I'm closing it for now, but feel free to re-open it if you can provide more info. https://github.com/facebook/hhvm/wiki/Human-Timeouts

**Comment by mofarrell** [comment]
I am just
