### ISSUE TITLE
Missing dependencies in HHVM 3.18 binary package for Yakkety

### ISSUE THREAD

**Issue by alex-mashin** [facebook/hhvm#7682]
HHVM Version 3.18.0, Ubuntu 16.10 Yakkety
HHVM cannot start after upgrade: `error while loading shared librarues: libboost_program_options.so.1.61.0: cannot open shared object file: No such file or directory`

Two dependencies are missing in binary package: `libboost-program-options.1.61.0` and `libboost-context.1.61.0`.

**Comment by mofarrell** [comment]
@aorenste can you confirm this is fixed in 3.18.1?

**Comment by aorenste** [comment]
Yes.  Just verified on a buildd chroot.
