### ISSUE TITLE
No HHI for \HH\facts_parse

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#7683]
### HHVM Version

3.18

### Standalone code, or other way to reproduce the problem

`\HH\fact_parse()`

### Expected result

Not enough arguments error

### Actual result

unknown name error

**Comment by jazzdan** [comment]
I think this is fixed as a result of https://github.com/facebook/hhvm/commit/87bf274cade187dc147a2f5bdb50199f2ffb1dbe.
