### ISSUE TITLE
file_get_contents() raises notice when using http header option

### ISSUE THREAD

**Issue by Norbyte** [facebook/hhvm#7684]
### HHVM Version
HipHop VM 3.18.0-dev (rel)
Compiler: heads/master-0-g3fb5e0b2512234155bb07fd7bfa18b4047c42deb
Repo schema: 3ddd9660d9a7ad9cd9acd0503620d1eb9269e95a

### Standalone code, or other way to reproduce the problem
I've used the following code to fetch an URL that echoes back the `$_SERVER` array to the client.
```php
<?php

$opts = [
    'http' => [
        'header' => ['AAA: 1', 'BBB: 2']
    ]
];
$context = stream_context_create($opts);
echo file_get_contents('http://<url>/', null, $context);
```

On PHP 7 and HHVM 3.12.2 this works correctly; on 3.18 this raises an `Notice: Array to string conversion` notice.
The notice doesn't occur when the headers are concatenated to a single string (`'header' => "AAA: 1\r\nBBB: 2"`).

### Expected result
```
Array
(
    (...)
    [HTTP_AAA] => 1
    [HTTP_BBB] => 2
    (...)
)
```

### Actual result
```
Notice: Array to string conversion in (...)/a.php on line 9

Array
(
    (...)
    [HTTP_AAA] => 1
    [HTTP_BBB] => 2
    (...)
)
```

**Comment by pondermatic** [comment]
This issue first appeared in commit eec9da990e7344af985735ec53d73325579931eb, between HHVM releases 3.14.5 and 3.15.0. The code handles the stream context options header value ONLY as a string. According to the [PHP HTTP context options](http://php.net/manual/en/context.http.php) page, header can be an array or a string.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Using fgc() on urls is a phpism. Hhvm strongly encourages using curl instead. Fixing fgc is not likely going to happen. PHP code is unsupported, so we don't have to consider all the php code using fgc() anymore.
