### ISSUE TITLE
hhvm.static_file.files_match config doesn't work

### ISSUE THREAD

**Issue by eryi** [facebook/hhvm#7685]
### HHVM Version
3.17.2

### Standalone code, or other way to reproduce the problem
Start hhvm server with any of the following and load any static file
````
hhvm -m server -p 9000 -d hhvm.static_file.files_match[pattern]=".*" -d hhvm.static_file.files_match[headers][]="Expires: 0"
hhvm -m server -p 9000 -d hhvm.static_file.files_match[0][pattern]=".*" -d hhvm.static_file.files_match[0][headers][]="Expires: 0"
````

### Expected result
HTTP response should have "Expires: 0" in the header.

### Actual result
HTTP response does not have "Expires: 0" in the header.

**Comment by mofarrell** [comment]
Have you tried putting these settings in a config file?  I am looking to fix this, but I believe the options are parsed separately when passed in on the CLI.

**Comment by mofarrell** [comment]
I have a fix for this coming.  For now putting the settings in the same `.ini` file should work.

**Comment by eryi** [comment]
The main difficulty I had with testing this is that this config is very poorly documented:
https://docs.hhvm.com/hhvm/configuration/INI-settings#server-mode__static-file-files-match-format

The example provided looks like:
````
hhvm.static_file.files_match[pattern]   = "[regex](here)*"
hhvm.static_file.files_match[headers][] = "header1"
hhvm.static_file.files_match[headers][] = "header2"
````

Looking through the hhvm code, I'm guessing a correct config would look like
````
hhvm.static_file.files_match[0][pattern]=".*"
hhvm.static_file.files_match[0][headers][]="Expires: 0"
````

The questions I have are:  
1. Is it files_match[0] or files_match?
2. Is my regex written correctly? (I'm trying to match everything)
3. Is the header specified correctly? (I'm not sure if that's the correct format or if there are any restricted headers that I can't modify)

Really hoping to avoid nginx/fastcgi or proxying things through hhvm!

**Comment by mofarrell** [comment]
It should be
```
hhvm.static.files_match[0][pattern]=".*"
hhvm.static.files_match[0][headers][]="Abc: 0"
```
Right now this only works if the settings are in a single INI file.  This is because the INI maps from multiple parsings are not merged properly.  I have a change to fix it so you can pass the args in through the CLI.
I will update the docs to include the `[0]`

**Comment by eryi** [comment]
I'm still do not see the headers with the exact config you've given. I'm loading the config file via `hhvm -m server -c test.ini`

My entire config file is
````
hhvm.server.port="9000"
hhvm.static.files_match[0][pattern]=".*"
hhvm.static.files_match[0][headers][]="Content-Type: application/json"
hhvm.static.files_match[0][headers][]="Expires: 0"
hhvm.static.files_match[0][headers][]="Abc: 0"
````

**Comment by mofarrell** [comment]
@eryi Try with master. 	b53d70c also changed the way it is parsed now.  It should work considering there is a basic test in the test suite now that is passing.
