### ISSUE TITLE
UTCDateTime() should accept float

### ISSUE THREAD

**Issue by macdabby** [facebook/hhvm#7691]
### HHVM Version
3.14

### Standalone code, or other way to reproduce the problem
new UTCDateTime(microtime(true) * 1000)

### Expected result
New UTCDateTime with the current time

### Actual result
Throws error `Error parsing [float] as 64-bit integer"`
According to the PHP docs, this constructor should accept a float:
http://php.net/manual/en/mongodb-bson-utcdatetime.construct.php

**Comment by mofarrell** [comment]
This is an issue in the [mongodb extension](https://github.com/mongodb/mongo-hhvm-driver)
The error is being produced here: https://github.com/mongodb/mongo-hhvm-driver/blob/82b86e5d78aa7c0b84b7eef55d8ac0f95b359307/ext_mongodb.php#L1744
