### ISSUE TITLE
HHVM explode() limit issue.

### ISSUE THREAD

**Issue by reposys** [facebook/hhvm#7696]
HHVM 3.18

I use my own wrapper function named "explodeTrim()" based on PHP function "explode()".
Here is snippet:

    `function explodeTrim($delimiter, $string, $limit = PHP_INT_MAX)
    {
    	// About explode() and PHP_INT_MAX 
    	// http://php.net/manual/en/function.explode.php

        $split = explode($delimiter, $string, $limit);

        // further custom logic
    }

    $emails = 'test1@example.com, test2@example.com';
    $emailsArr = explodeTrim(',', $emails); // using default limit=PHP_INT_MAX

    var_dump($emailsArr);
    // output: array(1) { [0] => string(17) "test1@example.com" }`

My problem is that using default limit to "explode()" on HHVM I cannot get last element from exploded string. The same code works in PHP properly.

If I pass explicit positive value of limit e.g. 7 then it works fine on HHVM too.

What I should to do in order "explode()" with default limit=PHP_INT_MAX worked as expected on http://php.net/manual/en/function.explode.php ?

**Comment by biesnecker** [comment]
Is this an integer overflow? The C++ implementation takes the limit as 32-bit signed int (https://github.com/facebook/hhvm/blob/902cbf05e4392f560366f76e10b11c4185e3b17a/hphp/runtime/ext/string/ext_string.h#L108), but PHP_INT_MAX 9223372036854775807. If you change the limit to 0x7FFFFFFF does it work?

**Comment by mofarrell** [comment]
@reposys @biesnecker Looking at our suggested types for extensions, that should probably be an `int64_t`.  https://github.com/facebook/hhvm/wiki/Extension-API
