### ISSUE TITLE
Redis session handling

### ISSUE THREAD

**Issue by Gauss23** [facebook/hhvm#7697]
Hello,

just tried a custom PHP framework. This framework uses PHP session handlers ( i.e. files, memcached, redis). In HHVM the files handler is working fine. The redis handler is throwing:

> Fatal error: Uncaught TypeError: Argument 5 passed to fsockopen() must be an instance of float, int given 

Argument 5 is the timeout value. There is no chance for the code to set a float value. Seems like an internal issue.

### HHVM Version
3.18.0 with hhvm.php7.all=true

### Standalone code, or other way to reproduce the problem
Ini-Setting:
`hhvm.php7.all=true`

```
<?php
ini_set('session.save_handler', 'redis');
session_save_path('tcp://127.0.0.1:6379');
session_start();

```

Even setting the save path to: `tcp://127.0.0.1:6379?timeout=2.5`
is not changing this behaviour.

### Expected result
Working session handler

### Actual result
Fatal error:
> Fatal error: Uncaught TypeError: Argument 5 passed to fsockopen() must be an instance of float, int given

**Comment by Gauss23** [comment]
Just tried to connect by socket:
`session_save_path('unix:///var/run/redis/redis.sock');`

Same problem.

Message:

> Fatal error: Uncaught TypeError: Argument 5 passed to pfsockopen() must be an instance of float, int given

**Comment by Gauss23** [comment]
Looks like it´s in the file:

> hhvm/hphp/system/php/redis/RedisSessionModule.php

on line 116:
`if (!$redis->{$func}($r['host'], $r['port'], $r['timeout'])) {`

`$r['timeout']` seems to be an `int`. Maybe just cast it to float?

Like so:
`if (!$redis->{$func}($r['host'], $r['port'], (float) $r['timeout'])) {`

Best regards

**Comment by mofarrell** [comment]
@Gauss23 any chance you want to try it and submit a pull request if it fixes it?

**Comment by Gauss23** [comment]
I would really like to do that. I followed the instructions to compile HHVM from source. For Ubuntu 14.04 and 16.04 it fails on cmake.
On Debian Jessie it fails during compiling because of `ext_mcrouter`. Now I´m trying to disable mcrouter with `-DENABLE_EXTENSION_MCROUTER=OFF`. Build is currently running, let´s see if it finishs successfully.

Are those instructions up-to-date? I followed those instructions on fresh ubuntu/debian installations in a Vagrant, 4GB Ram, 4 Cores. 

Which build environment is preferred and tested for the current master of HHVM from git?

Best regards

**Comment by Gauss23** [comment]
Ok, it finally compiled successfully and my idea is working. Can´t find any side-effects

**Comment by mofarrell** [comment]
Sounds great!  I think we would say that Ubuntu is best supported.  At the moment Ubuntu 16.04 is the system we test most regularly with.

What issue did you get when compiling on ubuntu?  If the docs aren't up to date I want to fix them
