### ISSUE TITLE
HHVM Version 3.2 file_get_contents Unknown cipher in list: ALL

### ISSUE THREAD

**Issue by dipenpatel235** [facebook/hhvm#7706]
### Standalone code, or other way to reproduce the problem
`<?php
$url = 'https://json/uri';
$pageContent = file_get_contents($url);
var_dump($pageContent);
?>
`
### Expected result
json result display
### Actual result
bool(false)
backend error log is 
\nWarning: Failed to open https://json/uri (Unknown cipher in list: ALL) in /usr/local/nginx/html/index.php on line 3

**Comment by mofarrell** [comment]
HHVM 3.2 Has been out of support for several years.  If you can reproduce this on 3.15 or 3.18 comment here, and I will reopen the issue.

**Comment by dipenpatel235** [comment]
Yes that is same issue in below version also.
 hhvm --version
HipHop VM 3.16.0-dev (rel)
Compiler: heads/master-0-g247e6f39ed7276f6e16f2c1bcee393d30841ee47
Repo schema: 922cef7ce4ceb4cc7b7ff58c0cc0972ee69ae429

**Comment by mofarrell** [comment]
You code works for me on:
HipHop VM 3.18.0 (rel)
Compiler: 1487182957_N
Repo schema: e5478f9dc830bea49323509807c7581ae7265970

**Comment by mofarrell** [comment]
The endpoint tried was a '/wp-json/posts' endpoint on a secure wordpress blog.
