### ISSUE TITLE
Large Performance slowdown on oss-performance WordPress, MediaWiki, and Drupal7

### ISSUE THREAD

**Issue by octmoraru** [facebook/hhvm#7711]
### HHVM Version
Master branch, commit 2edf202a5d064abacbe96f5f04894e496ece7441
### Standalone code, or other way to reproduce the problem
Run oss-performance with default options on the three targets

### Description
Our Performance Lab has [reported](https://lists.01.org/pipermail/langperf/2017-February/001650.html) a large performance slowdown on WordPress (7%), Drupal 7 (2.5%), and MediaWiki (9%). The lab has identified commit 2edf202a5d064abacbe96f5f04894e496ece7441 as being responsible for the degradation.

### Hardware:
CPU: dual socket Intel Xeon Processor E5-2699 v3 (Haswell)
CPU core frequency: 2.3 GHz
CPU Last Level Cache Size: 45 MB
Hyper Threading: off
Turbo Boost: off
Memory: 8x16GB DDR4 @2133MHz

### Sofware:
Distribution: CentOS 7.1
Kernel: 3.10.0-229
GCC:  4.8.3

**Comment by photodude** [comment]
I wonder where Joomla lands on that list???

**Comment by Orvid** [comment]
If it is that commit, my guess would be we accidentally re-ordered some things and the proper command line flags aren't being passed to the compiler so they aren't getting optimized properly.

**Comment by craigcarnell** [comment]
Does this affect Magento?

**Comment by octmoraru** [comment]
@photodude @craigcarnell If this is caused by what @Orvid suggested, I suspect it affects Joomla and Magento as well; but we haven't run any benchmarks.

**Comment by photodude** [comment]
@octmoraru How can we get Joomla added to your benchmarks?

**Comment by gdbentley** [comment]
@photodude A first step would be to submit a pull request to https://github.com/hhvm/oss-performance that adds Joomla.

**Comment by craigcarnell** [comment]
Any chance anybody interested in adding Magento 2? Also, where can we see more recent results on M1?
