### ISSUE TITLE
 How to download pictures in bulk all together from Facebook and upload them to Pinterest alltogether 

### ISSUE THREAD

**Issue by chandannasta** [facebook/hhvm#7714]
How to upload pictures in bulk all together from Facebook business page as pins to Pinterest all together in one single shot. Is it possible if yes then how

So there are 10 albums on my business page with total 4000 pictures and I want to upload them all to Pinterest. Is it possible if yes then how? My engineer friend told me that you would need a api to download the pictures from Facebook business page for those 10 albums first all together . Once its downloaded then you would need a api of Pinterest site to upload them all together. So he told me anyone who is a master in making api would know how to do that. Its just some codes and its not just for Pinterest it can be done with any social media website. If someone knows about API.

So does anyone has such API. If yes let me know please. I am even ready to pay if someone can do this for me.

**Comment by Orvid** [comment]
Not related to HHVM.
