### ISSUE TITLE
Memory leak in pgsql driver

### ISSUE THREAD

**Issue by Norbyte** [facebook/hhvm#7716]
### HHVM Version
HipHop VM 3.18.1 (rel)
Compiler: tags/HHVM-3.18.1-0-g4f792a827d9b6fcc4bcd7940a1b92280f3fdedc3
Repo schema: b9aebb86bbda024eeeed6f608c9a49076563f9c7

### Standalone code, or other way to reproduce the problem
```php
<?php
$pdo = new PDO('pgsql:host=(host);dbname=(dbname)', '(user)', '(password)');
$stmt = $pdo->prepare('select 1');
for ($i = 0; $i < 100; $i++)
{
    $stmt->execute();
}
```

During testing with `ab -c 4 -n 1000000 http://<url>`, HHVM started leaking memory at a rate of about ~40 MB/sec. (The OOM killer killed it after a few minutes).

This issue does not occur if another driver (eg. mysql, sqlite) is selected. Directly calling `$pdo->exec()`, instead of preparing a statement with `$pdo->prepare()` also seems to work without leaks. The leak only occurs when executing a pgsql prepared statement,

**Comment by photodude** [comment]
@simonwelsh any thoughts on this?

**Comment by Norbyte** [comment]
Not sure if it helps, but I created a core dump of a running HHVM process after triggering this leak, and almost 80% of the dump is this exact sequence repeating endlessly (with some noise inbetween):

```
00 00 00 00 01 00 00 00 00 45 4C 45 43 54 20 31   .........ELECT 1
00 45 00 00 00 00 00 00 00 00 00 00 00 00 00 00   .E..............
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
00 00 00 00 00 00 00 00 00 00 00 00 F0 63 1C 03   ............đc..
00 00 00 00 00 00 00 00 00 00 00 00 70 63 1C 03   ............pc..
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
00 00 00 00 00 00 00 00 06 00 00 00 00 00 00 00   ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
00 00 00 00 01 00 00 00 00 45 4C 45 43 54 20 31   .........ELECT 1
00 45 00 00 00 00 00 00 00 00 00 00 00 00 00 00   .E..............
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
```

**Comment by Norbyte** [comment]
I've tracked down the issue.
The move assigment operator as implemented in https://github.com/facebook/hhvm/blob/10b4a1aeb38979d8632ab7496ddab390777f6b2d/hphp/runtime/ext/pgsql/pq.h#L41 is incorrect.

If the `Result` struct already has a non-null `m_res` member, it'll discard the `PGresult` object without releasing it first, thus leaking memory.

Experimental patch:
```patch
diff --git a/hphp/runtime/ext/pgsql/pq.h b/hphp/runtime/ext/pgsql/pq.h
index f29aeb2..7a80e70 100644
--- a/hphp/runtime/ext/pgsql/pq.h
+++ b/hphp/runtime/ext/pgsql/pq.h
@@ -39,6 +39,7 @@ struct Result {
   }

   Result& operator=(Result&& other) {
+    clear();
     m_res = other.m_res;
     other.m_res = nullptr;
     return *this;
```

**Comment by mofarrell** [comment]
This should be fixed with your change.
