### ISSUE TITLE
base64_decode is still treating + signs as spaces

### ISSUE THREAD

**Issue by thehappycoder** [facebook/hhvm#7721]
From http://php.net/manual/en/function.base64-decode.php:
"In short php <= 5.0.5's base64_decode( $string ) will assume that a space is meant to be a + sign where php >= 5.1.0's base64_decode( $string ) will no longer make that assumption."

It seems that hhvm is still behaving like old php version by treating + signs as spaces.

**Comment by mofarrell** [comment]
A repro case would be great.  Try pasting an example from https://3v4l.org/

**Comment by mofarrell** [comment]
This issue has been waiting for more info for more than 2 weeks. I'm closing it for now, but feel free to re-open it if you can provide more info. https://github.com/facebook/hhvm/wiki/Human-Timeouts
