### ISSUE TITLE
require_once includes twice

### ISSUE THREAD

**Issue by nicolas-grekas** [facebook/hhvm#7722]
### HHVM Version

HipHop VM 3.18.1 (rel)
Compiler: tags/HHVM-3.18.1-0-g4f792a827d9b6fcc4bcd7940a1b92280f3fdedc3
Repo schema: b9aebb86bbda024eeeed6f608c9a49076563f9c7

### Standalone code, or other way to reproduce the problem

create file foo.php:
```php
<?php class foo {}
```

create file bug.php:
```php
<?php

require_once 'foo.php';
touch('foo.php');
require_once 'foo.php';
```

then `hhvm bug.php`

### Expected result

no output, status zero

### Actual result

Fatal error: Class already declared: foo in foo.php on line 1

**Comment by questionpython** [comment]
i have a Question : `touch()` what do?

**Comment by nicolas-grekas** [comment]
http://php.net/touch
