### ISSUE TITLE
Available Fast way for build HHVM from source?

### ISSUE THREAD

**Issue by questionpython** [facebook/hhvm#7728]
Hello ,
Available Fast way for build HHVM from source?

HHVM team for work on this and change some code, and for develop them every time press make ? this need long time for generate output file!.

Is there any other better way?

**Comment by mofarrell** [comment]
The build is very complex and can take quite a long time to run.  There isn't a way to work around this.

**Comment by questionpython** [comment]
You are sure?, build from source HHVM need very time!
I think this need about an hour(or a long time). :-1: 
this is very bad for develop a software or core!

**Comment by Orvid** [comment]
It should only take an hour if you're doing a clean build. If you've only modified a couple of things the build time should be much much shorter.

**Comment by questionpython** [comment]
mean of just change `main.cpp` and `test.cpp`, next just delete `main.o` and `test,o` ? and next `make`?

**Comment by Orvid** [comment]
You don't need to delete `main.o` and `test.o` after changing `main.cpp` and `test.cpp`. Just run `make` and it will re-compile only the things that have changed.

**Comment by mofarrell** [comment]
You don't need to delete anything.  If you modify a file.  Say main.cpp, and run make again, it should be much quicker.  Also consider running make as `make -j32`

**Comment by questionpython** [comment]
"Say main.cpp, and run make again" ==> how can say and call a file?, what mean this?
"make -j32" ==> -j mean? so why 32?

tank you. :+1:

**Comment by mofarrell** [comment]
make changes to main.cpp, then make again.  -j allows the build to happen in parallel.  the number specifies the number of things to do in parallel.  i choose 32 because it is higher than the core count of your processor.  (or so I am guessing).  In the future consider googling what options for command line utilities do
