### ISSUE TITLE
stream_socket_get_name function add ":" for unix domain socket.

### ISSUE THREAD

**Issue by s2x** [facebook/hhvm#7733]
The stream_socket_get_name function add ":" when using a unix domain socket.

### HHVM Version
3.18.1
### Standalone code, or other way to reproduce the problem
```php
<?php
$socket = stream_socket_server("unix://test.sock", $errno, $errstr);
if (!$socket) {
  echo "$errstr ($errno)<br />\n";
} else {
  $socket_path = stream_socket_get_name($socket, false);
  echo "$socket_path\n";
  fclose($socket);
  unlink($socket_path);
}
```

### Expected result
```stream_socket_get_name
test.sock
```
### Actual result
```
test.sock:

Warning: unlink(test.sock:): No such file or directory in test.php on line 9
```

**Comment by mofarrell** [comment]
It looks like https://github.com/facebook/hhvm/blob/master/hphp/runtime/ext/stream/ext_stream.cpp#L827 needs a case to handle this.

**Comment by s2x** [comment]
I have made PR for this issue https://github.com/facebook/hhvm/pull/7738
