### ISSUE TITLE
Update hhvm-third-party/webscalesqlclient to avoid "Lost connection to MySQL server during query" after handled signals

### ISSUE THREAD

**Issue by pprasse** [facebook/hhvm#7736]
The currently referenced commit of hhvm-third-party/webscalesqlclient still has the upstream mysql bug https://bugs.mysql.com/bug.php?id=82019 which leads to a "Lost connection to MySQL server during query" after every handled signal, as EINTR is not handled correctly.

This was fixed in webscalesqlclient commit https://github.com/facebook/mysql-5.6/commit/2674cf91c5dad871f59704685e77e76ba8f462cd

### HHVM Version
<= 3.8.1 - 3.18.1

### Standalone code, or other way to reproduce the problem

MysqlSignalTestStandalone.php:
```php
<?php

fwrite( STDERR, "Setting handler USR2\n" );
pcntl_signal( SIGUSR2, function() {
    fwrite( STDERR, "SIGUSR2 received\n" );
}, true);
pcntl_sigprocmask(SIG_UNBLOCK, [ SIGUSR2 ]);

fwrite( STDERR, "SELECTING...\n" );

$conn = new \PDO('mysql:host=XXX;port=XXX;dbname=test', 'XXX', 'XXX' );
$res = $conn->query( "SELECT SLEEP(20)" );
$result = $res->fetchAll();
fwrite( STDERR, "DONE selecting\n" );
```

Console 1:
```bash
hhvm MysqlSignalTestStandalone.php
```

Console 2:
```bash
ps ax | grep MysqlSignalTestStandalone | grep -v grep | awk '{print $1}' | xargs -n1 kill -s USR2
ps ax | grep MysqlSignalTestStandalone | grep -v grep | awk '{print $1}' | xargs -n1 kill -s USR2
```

### Expected result
Using the a customized build from tag HHVM-3.18.1:
```
cd third-party/webscalesqlclient/mysql-5.6
git checkout   93c3081  # branch https://github.com/facebook/mysql-5.6/tree/fb-mysql-5.6.35
```
```
Setting handler USR2
SELECTING...
SIGUSR2 received
DONE selecting
```

### Actual result
Using the standard build from tag HHVM-3.18.1
```
Setting handler USR2
SELECTING...
SIGUSR2 received
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2013] Lost connection to MySQL server during query' in :
Stack trace:
#0 /home/patrickprasse/sandboxes/actindo3-patrickprasse/actindo3/Tests/Core/Database/MysqlSignalTestStandalone.php(12): PDO->query()
#1 {main}
```

**Comment by Orvid** [comment]
We can't do this until WebscaleSQL is updated to fix the build on Mac.

**Comment by Orvid** [comment]
The WebscaleSQL has been fixed on Mac, so I'm in progress of updating it.
