### ISSUE TITLE
typechecker: support empty placeholders in destructuring assignment

### ISSUE THREAD

**Issue by bcopeland** [facebook/hhvm#7739]
### HHVM Version
```
HipHop VM 3.18.0 (rel)
Compiler: tags/HHVM-3.18.0-0-g9b285191feb2bb1558bb6682da135263bd2a9e60
Repo schema: cc987335f4691fa6ed98336c2378d8e71a751b22
```
### Standalone code, or other way to reproduce the problem
```
<?hh

function foo()
{
    list(,,,$foo,,,) = explode("|","A|B|C|D|E|F|G");
    echo $foo;
}

foo();
```
The above file runs without error with hhvm and prints 'D'.  But the typechecker doesn't understand this construct.

We use this kind of assignment in some cases to avoid introducing a variable name when it is understood (and checked, in our tooling) that all assigned variables are subsequently used.

### Expected result

Typechecker parses this construct.  

### Actual result
```
test.php:5:10,10: Expected expression (Parsing[1002])
```
Interestingly, as long as the list assignment is of the form ```list($a,) = ...``` then it is handled.

**Comment by fredemmott** [comment]
- `list($a,)` is considered to be `list($a)` with a trailing comma, not a two-item list
 - FYI, `$_` or $_anything` can be used as placeholders; `list($_, $_, $foo)` would be one way to write this, though generally we'd write `list($_somethingdescriptive, $_somethingelsedescriptive, $foo)` instead, to make it more obvious what's going wrong if the input changes without the callsites also changing

**Comment by mofarrell** [comment]
This is quite a bizarre syntax, and leads to needing to count commas.  In this case you probably just want `$foo =  = explode("|","A|B|C|D|E|F|G")[3];`.  I am closing this issue because we aren't interested in supporting the syntax.

That being said, a syntax allowing the deconstruction of arrays and objects might be interesting:
```
list(3 => $foo, 5 => $bar) = explode("|","A|B|C|D|E|F|G");
echo $foo;  // D
echo $bar;  // F
```
