### ISSUE TITLE
`new Error` in a namespace doesn't refer to the class from that namespace when hhvm.php7.all=1 - it refers to __SystemLib\Error 

### ISSUE THREAD

**Issue by TysonAndre** [facebook/hhvm#7741]
### HHVM Version
Reproduced with 3.18.1 and nightly.

This only happens with the ini setting `hhvm.php7.all=1`

### Standalone code, or other way to reproduce the problem

```
<?php
// a.php
namespace MyNS;

class A {
    public static function foo() {
        var_export(new Error());
    }
}
spl_autoload_register(function($class) {
    echo "Requiring $class\n";
    require_once __DIR__ . '/b.php';
});

A::foo();
```

```php
<?php
// b.php
namespace MyNS;

class Error extends \Exception {
}
```

- Function declarations also have this bug, and seem to use  `__SystemLib\Error`

### Expected result

Should create an instance of `\MyNS\Error`, like php 7.
(For compatibility with php7 libraries)
See https://github.com/nikic/PHP-Parser/pull/368#issuecomment-288182749

### Actual result

Creates an instance of `__SystemLib\Error`, ignoring the current namespace

**Comment by fredemmott** [comment]
Fixed by https://github.com/facebook/hhvm/commit/29fc86f9ddefc918549c201ebe5ee8a978efde44
