### ISSUE TITLE
XPath query for "//body[1]" sometimes returns a DOMText

### ISSUE THREAD

**Issue by mrclay** [facebook/hhvm#7745]
### Standalone code, or other way to reproduce the problem

The HHVM branch of our Travis builds fails frequently ([recent example](https://travis-ci.org/Elgg/Elgg/jobs/214122343#L405)), and I've tried to isolate this to a simple PHP file test case ([in this gist](https://gist.github.com/mrclay/cf984302052bf1830e0d)), but cannot duplicate the issue that way. As the failure is intermittent, advice on creating a more thorough test would be helpful.

The core issue:
```php
$nodeList = $xpath->query('//body[1]');
echo get_class($nodeList->get(0));
```

### Expected result

`DOMElement`

### Actual result

`DOMText` (sometimes). When this occurs, the node's textcontent has the HTML of the body.

## Walkthrough of issue

1. Our code takes a chunk of HTML, wraps it in a BODY element, and [parses it with DOMDocument::loadHTML](https://github.com/Elgg/Elgg/blob/2.3.2/engine/classes/ElggAutoP.php#L98).
2. We create a DOMXPath and [query](https://github.com/Elgg/Elgg/blob/2.3.2/engine/classes/ElggAutoP.php#L108) `//body[1]`.

In all PHP versions this reliably returns a DOMNodeList containing only the body in a DOMElement. On HHVM, frequently the node list contains a DOMText node instead. This occurs [here](https://travis-ci.org/Elgg/Elgg/jobs/214122343#L405) in our currently failing build, using [this HTML](https://github.com/Elgg/Elgg/blob/2.3.2/engine/tests/phpunit/test_files/autop/wysiwyg-test.in.html) as input in the failing case. As noted above, [this gist](https://gist.github.com/mrclay/cf984302052bf1830e0d), should duplicate the setup.

I've not had the opportunity to investigate further (e.g. to see if the node list contains other nodes), but I may be able to do more legwork.

This was previously closed as #6903, but the issue has been further isolated and hopefully better explained here.

**Comment by fredemmott** [comment]
3.6 is completely unsupported - have you tried a more recent version? Travis supports up to 3.18 with this config: https://github.com/facebook/xhp-lib/blob/master/.travis.yml

Future releases of HHVM are likely to need a docker-based config, eg https://github.com/facebook/xhp-lib/blob/try-docker-tests/.travis.yml + 
https://github.com/facebook/xhp-lib/blob/try-docker-tests/.travis.sh

**Comment by mrclay** [comment]
Thanks, I'll try that.

**Comment by mrclay** [comment]
Tests are passing under 3.15 👍 Thanks!
