### ISSUE TITLE
mb_parse_str truncates strings with semicolons

### ISSUE THREAD

**Issue by wulftone** [facebook/hhvm#7751]
This bug is causing us some grief:

### HHVM Version
```bash
# hhvm --version
HipHop VM 3.18.1 (rel)
Compiler: tags/HHVM-3.18.1-0-g4f792a827d9b6fcc4bcd7940a1b92280f3fdedc3
Repo schema: b9aebb86bbda024eeeed6f608c9a49076563f9c7
```
### Standalone code, or other way to reproduce the problem
```
hphpd> @mb_parse_str("preds=status|=|3;id|>|1000&limit=1",$output)
hphpd> =$output
```
### Expected result
```php
Array
(
    [preds] => "status|=|3;id|>|1000"
    [limit] => "1"
)
```
### Actual result
```php
Array
(
    [preds] => "status|=|3"
    [limit] => "1"
)
```
### PHP 7
```php
Psy Shell v0.7.1 (PHP 7.1.1 — cli) by Justin Hileman
>>> mb_parse_str("preds=status|=|3;id|>|1000&limit=1",$output)
=> true
>>> $output
=> [
     "preds" => "status|=|3;id|>|1000",
     "limit" => "1",
   ]
```

Thank you!

**Comment by mofarrell** [comment]
https://3v4l.org/grKXL
As far as I can see we have the same behavior.  That link shows the behavior in many versions.  I also tried in 3.18, and master in the debugger, and observed the same behavior as PHP.  You should check your environment to see what might be causing it to behave differently.

**Comment by mofarrell** [comment]
If you have more information that makes this reproducible, I will reopen the issue.

**Comment by wulftone** [comment]
Sorry, I pasted the wrong example in the HHVM part.  It should be 
```
hphpd> @mb_parse_str("preds=status|=|3;id|>|1000&limit=1",$output)
hphpd> =$output
```
Note the title emphasizing "semicolons" but I failed in my copy-pasting in one out of two examples I pasted.  The PHP example was correctly pasted.

**Comment by wulftone** [comment]
https://3v4l.org/4gbTQ
