### ISSUE TITLE
[bug] `token_get_all` produces `T_HH_ERROR`

### ISSUE THREAD

**Issue by keradus** [facebook/hhvm#7755]
### HHVM Version

3.12.14 - 3.18.1
maybe others as well

### Standalone code, or other way to reproduce the problem
```php
<?php

function normalizeTokens(array $tokens) {
    return array_map(function ($item) {
        if (!is_array($item)) {
            return $item;
        }
        return array(token_name($item[0]), $item[1], $item[2]);
    }, $tokens);
}

var_dump(normalizeTokens(token_get_all('<?php# a')));
```

### Expected result
```php
array(3) {
  [0]=>
  array(3) {
    [0]=>
    string(10) "T_OPEN_TAG"
    [1]=>
    string(2) "<?"
    [2]=>
    int(1)
  }
  [1]=>
  array(3) {
    [0]=>
    string(8) "T_STRING"
    [1]=>
    string(3) "php"
    [2]=>
    int(1)
  }
  [2]=>
  array(3) {
    [0]=>
    string(9) "T_COMMENT"
    [1]=>
    string(3) "# a"
    [2]=>
    int(1)
  }
}
```

### Actual result
```php
array(4) {
  [0]=>
  array(3) {
    [0]=>
    string(10) "T_OPEN_TAG"
    [1]=>
    string(5) "<?php"
    [2]=>
    int(1)
  }
  [1]=>
  array(3) {
    [0]=>
    string(10) "T_HH_ERROR"
    [1]=>
    string(5) "<?php"
    [2]=>
    int(1)
  }
  [2]=>
  array(3) {
    [0]=>
    string(10) "T_HH_ERROR"
    [1]=>
    string(5) "<?php"
    [2]=>
    int(1)
  }
  [3]=>
  array(3) {
    [0]=>
    string(10) "T_HH_ERROR"
    [1]=>
    string(5) "<?php"
    [2]=>
    int(1)
  }
}
```

or better, implement `TOKEN_PARSE` flag for `token_get_all` and raise `ParseError`

-----

ref https://3v4l.org/rFr7p

**Comment by keradus** [comment]
any news here ?

**Comment by mofarrell** [comment]
I am a little confused by why this is important to you.  I understand it is an incompatibility, but something like `<?php# a` is invalid php.  https://3v4l.org/RYVP9

**Comment by keradus** [comment]
2 months of bug and nobody noticed it, looks like hhvm is dead or don't care about bugs that community raises.
As history of bugs raised by me to hhvm shown, my concern is incompatibility of `token_get_all` in general (Of course I report issues one by one).
Why it's important to me? simply because I'm... using this function and rely on it's output.

**Comment by nikic** [comment]
Adding an explicit `<<EOF>>` in https://github.com/facebook/hhvm/blob/master/hphp/parser/hphp.ll#L821 would probably fix this (assuming flex actually supports that).

Please don't forget that there is a vanishingly small number of people who care about edge-case tokenizer output, so one shouldn't expect such issues to be prioritized.

**Comment by mofarrell** [comment]
@keradus This is not a high priority, as @nikic pointed out.  We would certainly accept a pull request for this, and hope to get to issues like this one soon.

**Comment by azjezz** [comment]
should be closed. 

PHP is not supported any more ( as well as the tokenizer extension ).

For hack lang, please see : https://github.com/hhvm/hhast
