### ISSUE TITLE
Redis.php and QUIT command on close() generating TCP RST

### ISSUE THREAD

**Issue by elukey** [facebook/hhvm#7757]
Hi everybody,

while debugging a timeout issue in https://phabricator.wikimedia.org/T125735 I noticed frequent TCP RST in wireshark/tcpdump from hhvm while sending requests to our Redis cluster (more details in https://phabricator.wikimedia.org/T125735#3109323). We use HHVM 3.12 (currently migrating to 3.18) and the Redis.php class included in hhvm. 

I checked https://github.com/facebook/hhvm/blob/master/hphp/system/php/redis/Redis.php#L86-L90 and now I am wondering if the code suffers the same issue as described in https://github.com/phpredis/phpredis/issues/562:

HHVM calls Redis.php close() that sends a QUIT command to Redis and then close the TCP connection. When Redis returns the "OK" response the TCP connection is gone and it gets a RST.

Two possible solutions:

1) Wait for the "OK" Response after issuing the QUIT command.
2) Remove the QUIT command (as it was done https://github.com/phpredis/phpredis/issues/562). 

Thanks in advance!

Luca

**Comment by mofarrell** [comment]
@elukey My guess is we would like to follow the phpredis behavior.  If you don't mind a pull request for this would be awesome.

**Comment by elukey** [comment]
Sure I can try to come up with a patch, trying to solve the issue on my testing environment. I still haven't found a good way to reproduce, as mentioned in https://phabricator.wikimedia.org/T125735#3151306 the issue seems depending on whether or not Redis returns "OK" in response to a QUIT command.

**Comment by elukey** [comment]
@mofarrell There are two possible solutions that seems to fix the issue, both of them are in the close() function:

1) simply remove $this->processCommand('QUIT');
2) add $this->processBooleanResponse(); right after $this->processCommand('QUIT');

From https://redis.io/commands/quit it seems that the response is always "OK" so it shouldn't be necessary to check the return value, but just simply wait for it before closing the TCP socket.

Any preference?

**Comment by elukey** [comment]
@atdt Hi! If you have any suggestion/feedback for this bug it would be helpful as well :)

**Comment by mofarrell** [comment]
https://github.com/phpredis/phpredis/commit/d701d02f9c9c58401543560f666f44b5d413a5a7 makes me think 1 is the way to go.  2 also seems fine, and has some merits of its own.

**Comment by elukey** [comment]
@mofarrell created https://github.com/facebook/hhvm/pull/7771 that should be a compromise between the two solutions.

**Comment by elukey** [comment]
@mofarrell anything left to do from my side? I saw the pull req a bit stuck, but it is probably due to reviewers backlog :)

**Comment by mofarrell** [comment]
@elukey Nope.  Should be out soon.  Just was waiting for clean test runs.  Had to rebase it past some broken revs.  The test look good, so it should be merged in shortly.

**Comment by hashar** [comment]
Fixed by PR #7771 / 671c259942fc2212ac346cd9830a31ec5d545c1b
