### ISSUE TITLE
`else if` captured too greedily by HHVM

### ISSUE THREAD

**Issue by sgolemon** [facebook/hhvm#7762]
### Standalone code, or other way to reproduce the problem
function ifit() { echo "🐘\n": }
if (false) {}
else ifit();

https://3v4l.org/7q1Kp

### Expected result
🐘

### Actual result
Parse error, unexpected T_STRING

### Analysis
Same basic issue (with similar potential fix) to https://github.com/facebook/hhvm/issues/7746

When looking at the token stream in userspace: https://3v4l.org/e1Zi5 , recall that HHVM's token_get_all() turns an `else if` token back into three parts.  Because Hacks.

### Apology
Sorry about introducing that hack.  You could always fix the parser not to explode at 100 chained `else if` blocks instead. :)

**Comment by sgolemon** [comment]
https://github.com/facebook/hhvm/commit/d3375f7f49fa83bc3ebe273d6beb54992c75ae6f

`I look forward to regretting these words.`

**Comment by edwinsmith** [comment]
Strong use of unicode in the test case, though.
