### ISSUE TITLE
3.18 and OSX Sierra: terminating with uncaught exception of type HPHP::ExitException: 

### ISSUE THREAD

**Issue by wake-up-neo** [facebook/hhvm#7764]
Every http request through nginx+fastcgi+hhvm kills hhvm. 
Even on interceptor without code.
However CLI works fine.

```
hhvm --mode server -d hhvm.server.type=fastcgi -d hhvm.server.port=9000
```

```
Macbook-Pro-Taras:build wakeupneo$ hhvm --version
HipHop VM 3.18.2-dev (rel)
Compiler: 1490694981_N
Repo schema: 1ad296a7eac9d2cbb440774f1ad08e62d3bd0a5a

```

```
libc++abi.dylib: terminating with uncaught exception of type HPHP::ExitException: 
 
Core dumped: Abort trap: 6
Stack trace in /tmp/stacktrace.30280.log
Abort trap: 6

```
```
Macbook-Pro-Taras:build wakeupneo$ cat /tmp/stacktrace.30280.log
Host: Macbook-Pro-Taras.local
ProcessID: 30280
ThreadID: 2952798208
ThreadPID: -1
Name: /usr/local/bin/hhvm
Type: Abort trap: 6
Runtime: hhvm
Version: 1490694981_N
DebuggerCount: 0

Server: 127.0.0.1
ThreadType: Web Request
Server_SERVER_NAME: local-avalanche.tripmydream.com
URL: /


PHP Stacktrace:

#0  api\Router->finishExecution() called at [/Users/wakeupneo/Documents/Development/Services/avalanche/api/Router.hh:138]
#1  api\Router->route() called at [/Users/wakeupneo/Documents/Development/Services/avalanche/web/interceptor.hh:45]
```

**Comment by wake-up-neo** [comment]
The same with Proxygen

`Macbook-Pro-Taras:tmp wakeupneo$ hhvm --mode server --config /usr/local/etc/hhvm/server.ini 
`

Config
```
pid = /usr/local/var/run/hhvm/pid

hhvm.server.port = 9001
hhvm.log.use_log_file = true
hhvm.log.file = /usr/local/var/log/hhvm/error.log
hhvm.repo.central.path = /usr/local/var/run/hhvm/hhvm.hhbc
hhvm.server.default_document = interceptor.hh
hhvm.server.error_document404 = interceptor.hh
hhvm.server.type = proxygen 
hhvm.server.source_root=/Users/wakeupneo/Documents/Development/Services/avalanche/web

```

Single http request
```
curl -X GET http://127.0.0.1:9001
```

Result
```
Macbook-Pro-Taras:tmp wakeupneo$ hhvm --mode server --config /usr/local/etc/hhvm/server.ini 
libc++abi.dylib: terminating with uncaught exception of type HPHP::ExitException: 

Abort trap: 6
```

**Comment by bombino** [comment]
Same behavior here.  The PHP die() function is what seems to trigger the HPHP::ExitException for me, which causes the server crash.

**Comment by wake-up-neo** [comment]
Nothings has changed with brew hhvm 3.20.3 except another [new issue](https://github.com/hhvm/homebrew-hhvm/issues/87) :\

_(OSX 10.12.5, Xcode 8.3.3)_

Trying to build from source the newest everything and get 

> [100%] Linking CXX executable hhvm
> Generating Repo Schema ID and Compiler ID
> ld: library not found for -lsodium
> clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
> make[3]: *** [hphp/hhvm/hhvm] Error 1
> make[2]: *** [hphp/hhvm/CMakeFiles/hhvm.dir/all] Error 2
> make[1]: *** [hphp/hhvm/CMakeFiles/hhvm.dir/rule] Error 2
> make: *** [hhvm] Error 2

However: 

1.
> bash-3.2$ brew install libsodium
> Warning: libsodium 1.0.12 is already installed

2.
> bash-3.2$ ls -l /usr/local/lib | grep libsodium
> lrwxr-xr-x    1 wakeupneo  admin        49 Jun 23 23:47 libsodium.18.dylib -> ../Cellar/libsodium/1.0.12/lib/libsodium.18.dylib
> lrwxr-xr-x    1 wakeupneo  admin        42 Jun 23 23:47 libsodium.a -> ../Cellar/libsodium/1.0.12/lib/libsodium.a
> lrwxr-xr-x    1 wakeupneo  admin        46 Jun 23 23:47 libsodium.dylib -> ../Cellar/libsodium/1.0.12/lib/libsodium.dylib

3.
> cat CMakeCache.txt | grep libsodium
> HHVM_EXTENSION_35_DEPENDENCIES:INTERNAL=libsodium 1.0.12
> HHVM_EXTENSION_35_NAME:INTERNAL=libsodium
> HHVM_EXTENSION_35_PRETTY_NAME:INTERNAL=libsodium
> HHVM_EXTENSION_35_ROOT_DIR:INTERNAL=/Users/wakeupneo/Documents/Development/Laboratory/hack/hhvm/hphp/runtime/ext/libsodium
> HHVM_EXTENSION_35_SOURCE_FILES:INTERNAL=ext_libsodium.cpp
> HHVM_EXTENSION_35_SYSTEMLIB:INTERNAL=ext_libsodium.php
> LIBSODIUM_CFLAGS:INTERNAL=-I/usr/local/Cellar/libsodium/1.0.12/include
> LIBSODIUM_INCLUDEDIR:INTERNAL=/usr/local/Cellar/libsodium/1.0.12/include
> LIBSODIUM_INCLUDE_DIRS:INTERNAL=/usr/local/Cellar/libsodium/1.0.12/include
> LIBSODIUM_LDFLAGS:INTERNAL=-L/usr/local/Cellar/libsodium/1.0.12/lib;-lsodium
> LIBSODIUM_LIBDIR:INTERNAL=/usr/local/Cellar/libsodium/1.0.12/lib
> LIBSODIUM_LIBRARY_DIRS:INTERNAL=/usr/local/Cellar/libsodium/1.0.12/lib
> LIBSODIUM_PREFIX:INTERNAL=/usr/local/Cellar/libsodium/1.0.12
> LIBSODIUM_STATIC_CFLAGS:INTERNAL=-I/usr/local/Cellar/libsodium/1.0.12/include
> LIBSODIUM_STATIC_INCLUDE_DIRS:INTERNAL=/usr/local/Cellar/libsodium/1.0.12/include
> LIBSODIUM_STATIC_LDFLAGS:INTERNAL=-L/usr/local/Cellar/libsodium/1.0.12/lib;-lsodium
> LIBSODIUM_STATIC_LIBRARY_DIRS:INTERNAL=/usr/local/Cellar/libsodium/1.0.12/lib
> LIBSODIUM_libsodium_INCLUDEDIR:INTERNAL=
> LIBSODIUM_libsodium_LIBDIR:INTERNAL=
> LIBSODIUM_libsodium_PREFIX:INTERNAL=
> LIBSODIUM_libsodium_VERSION:INTERNAL=
> __pkg_config_arguments_LIBSODIUM:INTERNAL=libsodium>=1.0.12
> prefix_result:INTERNAL=/usr/local/Cellar/libsodium/1.0.12/lib

4 - why?

> bash-3.2$ ld -lsodium
> ld: warning: -arch not specified
> ld: warning: -macosx_version_min not specified, assuming 10.10
> Undefined symbols for architecture x86_64:
>   "start", referenced from:
>      implicit entry/start for main executable
> ld: symbol(s) not found for inferred architecture x86_64


-----

any ideas?

**Comment by wake-up-neo** [comment]
No more issues
> brew reinstall hhvm
