### ISSUE TITLE
Memory leaks in APC

### ISSUE THREAD

**Issue by azmng** [facebook/hhvm#7776]
HHVM 3.18.2 + cherry-picked [c7da29b](https://github.com/facebook/hhvm/commit/c7da29b93b895faca98fc75119bd55bbb8ed256e)

We have been experiencing memory leaks in HHVM for quite long time with different versions. After upgrading to latest version I've performed memory heap profiling again (with hhvm-leak-isolator script + jeprof) and found few old issues + one new. You can see all of them in the attached PDF:
[hhvm-profiling20.pdf](https://github.com/facebook/hhvm/files/907629/hhvm-profiling20.pdf)

Basically you can ignore thread that leads to _je_prof_backtrace_ as it seems to be related to profiling process itself. 
Then we can see that 76% of memory consumed has gone through _f_apc_store_ to:
- _strdup_  - probably missing free() - ate 13%
- _tbb::interface5::concurrent_hash_map::allocate_node_default_construct_  - introduced after deadlock fix in [c7da29b](https://github.com/facebook/hhvm/commit/c7da29b93b895faca98fc75119bd55bbb8ed256e) - ate 14%
- APCHandle -> APCArray -> 3 different _MakeUncounted_'s - ate 48%

Kindly advise.

**Comment by mofarrell** [comment]
@mmuehlenhoff Have you been seeing a memory leak in Stat Cache as well?
It seems like c7da29b shouldn't add a leak unless other part of stat cache are behaving badly.  Was it around before then?

**Comment by mmuehlenhoff** [comment]
@mofarrell We haven't noticed that memory leak in our setup (at least from high level server monitoring, I haven't done as specific profiling as azmng). I think this is entirely unrelated to the stat_cache patch, I think azmng only mentioned it to provide context that he's not running pristine 3.18.2 (since 3.18.2 by itself was too unstable until your c7da29b patch)

**Comment by azmng** [comment]
@mofarrell we were unable to use in production any 3.15+ versions of HHVM due to #7756 
So above report was the first memory heap profiling since 3.14.5
Below is the old profiling for 3.14.5 so you can compare them: 
[hhvm-profiling17.pdf](https://github.com/facebook/hhvm/files/911563/hhvm-profiling17.pdf)

**Comment by azmng** [comment]
I've tried recommendations from #805:
`hhvm.server.apc.expire_on_sets = true
hhvm.server.apc.purge_frequency = 4096
hhvm.server.apc.purge_rate = -1`

So far so good, memory usage looks much better and it seems actually purging the cache.
Hopefully we'll close this issue in a couple of days.

**Comment by azmng** [comment]
Enabled APC expire works well. Closing this issue.
