### ISSUE TITLE
create_function() broken in PHP: Error: could not find a .hhconfig file

### ISSUE THREAD

**Issue by ekn33** [facebook/hhvm#7783]
Ubuntu 16.04.2 LTS
Update from  HHVM/3.18.2 to 3.9.0
HHVM Version 3.9.0

\nCatchable fatal error: Error: could not find a .hhconfig file in /var/www/example or any of its parent directories. Do you have a .hhconfig in your code's root directory? in /var/www/example/wp-includes/pomo/translations.php on line 208

from hhvm log

wp site runs in a internal error and shows a withe page

**Comment by ptitpoulet** [comment]
Hi,

I had the same problem this morning with the update.

```
cd /var/www/example
touch .hhconfig
hh_client
```
My problem was solved like that.

**Comment by fredemmott** [comment]
I guess you mean HHVM 3.19.0 ?

**Comment by fredemmott** [comment]
Got another report of this in IRC from @byeskille

**Comment by fredemmott** [comment]
https://github.com/WordPress/WordPress/blob/master/wp-includes/pomo/translations.php#L208

**Comment by fredemmott** [comment]
Can you log the value of func_body there?

**Comment by fredemmott** [comment]
- I don't have an OSS build handy, but https://gist.github.com/fredemmott/f3da262a4588c5beff4c16689c9daa50 is suspicious
 - https://github.com/facebook/hhvm/commit/458c115692e430ff08070348078d981d0ef14343 and https://github.com/facebook/hhvm/commit/3d667ef5a1a13575790a84ea103bfd034392d4eb are the only commits in that timeframe that directly modify create_function, and are related to HH vs PHP

**Comment by fredemmott** [comment]
https://github.com/facebook/hhvm/blob/master/hphp/test/zend/good/ext/reflection/tests/config.ini should not be present for any zend tests - @ricklavoie

**Comment by mofarrell** [comment]
If we could do the opposite, and have `hhvm.hack.lang.look_for_typechecker=true` that would be best.

**Comment by mofarrell** [comment]
We are working on fixing this in the 3.19 release.  It is already fixed in master.  You can run successfully by disabling `hhvm.hack.lang.look_for_typechecker`.

**Comment by mofarrell** [comment]
This has been fixed in master for a while, and the new 3.19.1 packages should have the fix.

**Comment by byeskille** [comment]
Updated to 3.19.1, and can confirm I do not experience any problems.

**Comment by fredemmott** [comment]
I'm guessing https://github.com/facebook/hhvm/commit/bf75af53e6407a9e6d9620eb2c6a82ef97da4c6c ?

**Comment by mofarrell** [comment]
Yeah.  It was fixed before the release, but wasn't cherrypicked into the release branch.

**Comment by fredemmott** [comment]
Is there a diff flipping hphp/test/zend/good/ext/reflection/tests/config.ini to true, or removing it and setting it to true for all zend tests? If that creates problems, there's more bugs :(

**Comment by mofarrell** [comment]
I have one but it creates problems atm.

**Comment by fredemmott** [comment]
😢
