### ISSUE TITLE
ResourceBundle::create() throws TypeError instead of returning null

### ISSUE THREAD

**Issue by villfa** [facebook/hhvm#7787]
### HHVM Version
3.19.0
### Standalone code, or other way to reproduce the problem
```php
<?php
$r = ResourceBundle::create('en_US', 'foo');
var_dump($r);
```
### Expected result
```
NULL
```
### Actual result
```
Fatal error: Uncaught TypeError: Value returned from method ResourceBundle::create() must be of type ResourceBundle, null given
```

**Comment by mofarrell** [comment]
Typehint on this needs to be `?ResourceBundle` https://github.com/facebook/hhvm/blob/10b4a1aeb38979d8632ab7496ddab390777f6b2d/hphp/runtime/ext/icu/ext_icu_rsrc_bundle.php#L59
