### ISSUE TITLE
hhvm complete

### ISSUE THREAD

**Issue by phoenixfight** [facebook/hhvm#7794]
### HHVM Version
3.19.1

In file included from /data/hhvm/hhvm/third-party/folly/src/folly/Conv.cpp:16:0:
/data/hhvm/hhvm/third-party/folly/src/folly/Conv.h:39:81: fatal error: double-conversion/double-conversion.h: No such file or directory
 #include <double-conversion/double-conversion.h> // V8 JavaScript implementation
                                                                                 ^
compilation terminated.
make[2]: *** [third-party/folly/CMakeFiles/folly.dir/src/folly/Conv.cpp.o] Error 1
make[1]: *** [third-party/folly/CMakeFiles/folly.dir/all] Error 2
make: *** [all] Error 2

fix code
```diff --git a/CMake/HPHPFindLibs.cmake b/CMake/HPHPFindLibs.cmake
index a6e300a..a930c5a 100644
--- a/CMake/HPHPFindLibs.cmake
+++ b/CMake/HPHPFindLibs.cmake
@@ -427,6 +427,7 @@ macro(hphp_link target)
     target_link_libraries(${target} ${GOOGLE_TCMALLOC_MIN_LIB})
   endif()
 

   target_link_libraries(${target} boost)
   target_link_libraries(${target} ${MYSQL_CLIENT_LIBS})
   if (ENABLE_ASYNC_MYSQL)
@@ -497,7 +498,7 @@ macro(hphp_link target)
     target_link_libraries(${target} sqlite3)
   endif()
 
-  if (DOUBLE_CONVERSION_LIBRARY)
+  if (DOUBLE_CONVERSION_FOUND)
     target_link_libraries(${target} ${DOUBLE_CONVERSION_LIBRARY})
   else()
     target_link_libraries(${target} double-conversion)
```
third_party
```
diff --git a/folly/CMakeLists.txt b/folly/CMakeLists.txt
index c25e512..e76be9c 100644
--- a/folly/CMakeLists.txt
+++ b/folly/CMakeLists.txt
@@ -146,7 +146,7 @@ find_package(PThread REQUIRED)
 target_include_directories(folly PUBLIC ${LIBPTHREAD_INCLUDE_DIRS})
 target_link_libraries(folly ${LIBPTHREAD_LIBRARIES})
 
-if (DOUBLE_CONVERSION_LIBRARY)
+if (DOUBLE_CONVERSION_FOUND)
   target_link_libraries(folly ${DOUBLE_CONVERSION_LIBRARY})
 else()
   target_link_libraries(folly double-conversion)
```

**Comment by Orvid** [comment]
Could you submit a PR for this?

**Comment by mofarrell** [comment]
I believe both of your fixes have landed.  This may still be broken till the next third-party update.
