### ISSUE TITLE
Request: add support for private/protected const in classes, in hack and non-hack php 7.1 files

### ISSUE THREAD

**Issue by TysonAndre** [facebook/hhvm#7812]
### HHVM Version

nightly/all, as of today

### Standalone code, or other way to reproduce the problem

With the `hhvm.php7.all=1` ini setting

```php
<?php
class MyClass {
    private const BAR = 'bar';
}
```

This is supported in php 7.1: https://secure.php.net/manual/en/language.oop5.constants.php#language.oop5.basic.class.this

Related to https://github.com/facebook/hhvm/issues/7544 - This was filed since I didn't see any issues for this when searching for "private const" or "protected const" or const visibility

I think it would need to work with both `<?php` and `<?hh`, it currently doesn't: https://github.com/hhvm/hack-langspec/blob/master/tests/Constants/constants.php

### Expected result

There should be an ini setting which makes `private const` and `protected const` syntactically valid (non-class) in php compatibility mode (In files with the tag `<?php`)
(Not aware of any settings when looking at ini documentation)

With this ini setting, there should be no error.

### Actual result

Fatal error: Uncaught Error: syntax error, unexpected T_CONST, expecting T_VARIABLE in foo.php:3

**Comment by vlechemin** [comment]
Hello,

Do you have any news on this? Compatibility with the latest PHP features used to be really reactive, please continue!
Is PHP compatibility still important for HHVM? PHP 7.0 is reaching end of support in a few months and 3.20 just fixed compatibility issues.

A lot of frameworks are starting to require 7.1 in their latest version, such as Symfony.

Thank you

**Comment by fredemmott** [comment]
Not sure that this will be going into Hack, but we're at least not going to raise a parse error in PHP7.

Internal diff: D7011391

**Comment by fredemmott** [comment]
> Is PHP compatibility still important for HHVM?

As needed for Hack users (see https://hhvm.com/blog/2017/09/18/the-future-of-hhvm.html); this fits in this bucket, and I'm specifically addressing it because of Symfony's dependency on it.

We are not aiming to implement all 7.1 (or 7.2) features - just enough to minimize problems for Hack users.

**Comment by fredemmott** [comment]
No longer going to be a parse error in PHP7 code (https://github.com/facebook/hhvm/commit/6c69a10f40510b3158149c15730f608b84df69a4)

It is not enforced, and not supported at all in Hack.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This issue applies to running php code on hhvm. Hhvm [nolonger supports running php code](https://hhvm.com/blog/2018/09/12/end-of-php-support-future-of-hack.html) since [hhvm version 4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html).

This is indeed not supported in Hack.

```HACK
class Example {
  private const int A = 0;
}
```

```
Parsing[1002] Constants cannot be declared private
   --> src/file.hack
  9 |   private const int A = 0;
    |   ^^^^^^

1 error found.
```
