### ISSUE TITLE
Add support for `->modify("+$micro microseconds");`

### ISSUE THREAD

**Issue by mofarrell** [facebook/hhvm#7814]
Issue is on master.

https://github.com/facebook/hhvm/issues/7394 has more context.

### Standalone code, or other way to reproduce the problem
https://3v4l.org/1SBFd

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

#7394 was closed.
HHVM matches the behavior of PHP 7.1.0 -> 7.4.6. https://3v4l.org/BBBSl
