### ISSUE TITLE
HHVM 3.18 "libicudata not found" error

### ISSUE THREAD

**Issue by rheemap** [facebook/hhvm#7815]
HHVM version: 3.18 (commit 9ee1e5f82be4471502ab943b831be94b4e279cc2)
Standalone code

I am using custom ICU library for hhvm:
PKG_CONFIG_PATH=%{_builddir}/temp_install_dir/lib/pkgconfig/ CMAKE_INCLUDE_PATH=%{_builddir}/temp_install_dir/include/ CMAKE_LIBRARY_PATH="%{_builddir}/temp_install_dir/lib/" CC=`which gcc` CXX=`which g++` cmake . \
	-DLIBMAGICKWAND_INCLUDE_DIRS=%{_builddir}/temp_install_dir/include/ImageMagick-6 \
	-DOCAMLC_EXECUTABLE=%{_builddir}/temp_install_dir/bin/ocamlc \
	-DOCAMLC_OPT_EXECUTABLE=%{_builddir}/temp_install_dir/bin/ocamlc.opt \
	-DBoost_DEBUG=ON \
	-DBOOST_LIBRARYDIR=%{_builddir}/temp_install_dir/include/boost/ \
	-DBoost_USE_STATIC_LIBS=ON \
	-DICU_LIBRARY=/opt/myicu/usr/lib64/libicuuc.so.52 \
	-DICU_I18N_LIBRARY=/opt/myicu/usr/lib64/libicui18n.so.52 \
	**-DICU_DATA_LIBRARY=/opt/myicu/usr/lib64/libicudata.so.52 \**
	-DICU_INCLUDE_DIR=/opt/myicu/usr/include \
	-DMYSQL_UNIX_SOCK_ADDR=/dev/null \
	-DCMAKE_CXX_FLAGS="-g" \
	-DCMAKE_BUILD_TYPE=Release

HHVM builds successfully but when I deploy it, I am getting an error:

```libicudata.so.52 => not found```

cmakeCache.txt has the correct path for libicudata.

I also noticed that libicudata is no longer listed as 'Required' library for HHVM 3.18. It is missing from the list of required libraries that are printed when the RPM is built. There are other libraries in the same custom ICU package like ICU_I18N_LIBRARY which are mentioned as 'required' libraries.

Also, the RPM does not define RUNPATH for libicudata:
```
$ readelf -a /usr/bin/hhvm | grep icudata
[no output]
```
It used to define the RUNPATH for libicudata in 3.12.1 HHVM (previous version that we were using).

Please let me know if anyone has any insights into how to resolve the issue. 
Thanks in advance.

**Comment by Orvid** [comment]
Which linux distro are you trying to run on?

**Comment by rheemap** [comment]
Scientific linux 6

**Comment by strobox** [comment]
Similar issue after installing on Mac:
`
brew tap hhvm/hhvm
brew install hhvm-preview
`
`
Vasiliys-MacBook-Air:~ chikovvas$ hhvm
dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicudata.59.1.dylib
  Referenced from: /usr/local/bin/hhvm
  Reason: image not found
Abort trap: 6
`

**Comment by fredemmott** [comment]
we don’t build or support rpms - whoever set up the rpm build needs to add a dependency on the appropriate major version of libicu. Same issue on Mac (though that’s filed over at https://github.com/hhvm/homebrew-hhvm/issues/98 ), however brew doesn’t let us depend on a specific major release.
