### ISSUE TITLE
Classes can't weaken argument types from interfaces or superclasses

### ISSUE THREAD

**Issue by acrylic-origami** [facebook/hhvm#7818]
### HHVM Version

```
$ hhvm --version
HipHop VM 3.19.1 (rel)
Compiler: tags/HHVM-3.19.1-0-g6129094b1b61e1ae32245a583db0283e645384c1
Repo schema: 062f6c54b49727e83a10a43cdbb861741076e51d
```

### Standalone code, or other way to reproduce the problem

```hack
<?hh // strict
class Base {}
class Derived extends Base {}
interface I {
	public function foo(Derived $v): void;
}
class C implements I {
	public function foo(Base $v): void {}
}
```

### Expected result

```
No errors!
```

Return types in overridden methods can be subtypes of their parents' return types by `() -> Derived <: () -> Base`; so argument types in overridden methods should be allowed to supertype their parents' by `(Base) -> void <: (Derived) -> void`.

### Actual result

```
Member foo has the wrong type
This is an object of type Base
It is incompatible with an object of type Derived
```

**Comment by jesseschalken** [comment]
Relevant docs: https://docs.hhvm.com/hack/types/advanced-rules#method-inheritance (to be updated if this is ever fixed)

**Comment by fredemmott** [comment]
Renamed, and documentation appears wrong, given this is fine:

```Hack
<?hh // strict

class Foo {
}
class Bar extends Foo {
}

class Herp {
    public function dostuff(Bar $_): void {}
}

class Derp extends Herp {
    public function doStuff(Foo $_): void {}
}
```

**Comment by fredemmott** [comment]
Whoops, sorry. Turns out that's a different issue: the behavior for incorrect case differs.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Hack and hhvm understand that `C::foo(mixed)` and `C::foo(Base)` are valid overrides for `I::foo(Derived)`.

```HACK
class Base {}
class Derived extends Base {}
interface I {
  public function foo(Derived $v): void;
}
class C implements I {
  public function foo(Base $v): void {}
}
```

_No errors!_
