### ISSUE TITLE
Segfault creating new DateTime() if tzdata is not installed

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#7822]
### HHVM Version

3.19.1

### Standalone code, or other way to reproduce the problem

```
<?php new DateTime();
```

Or, full oneliner:

```
docker run hhvm/hhvm:latest /bin/bash -c 'echo "<?php new DateTime();" | hhvm --php -'
```

### Expected result

Exception or warning + invalid datetime

### Actual result

Segmentation fault.

**Comment by mofarrell** [comment]
The new hhvm 3.19.2 packages include `tzdata` as a dependency.  The new docker images for 3.19.2 should not have this issue.  New LTS packages were not made because they are running on ubuntu 14.04 in docker, which includes `tzdata`.
