### ISSUE TITLE
complie HHVM master error

### ISSUE THREAD

**Issue by saga1015** [facebook/hhvm#7825]
### HHVM Version
master
### Standalone code, or other way to reproduce the problem
standalone code
use devtoolset-2  gcc/g++ 4.8.2
complie hhvm error,  error info:
[ 53%] Building CXX object hphp/hhbbc/CMakeFiles/hphp_hhbbc.dir/cfg-opts.cpp.o
/root/source/hhvm/src/hhvm/hphp/hhbbc/cfg-opts.cpp: In function ‘bool HPHP::HHBBC::rebuild_exn_tree(const HPHP::HHBBC::FuncAnalysis&)’:
/root/source/hhvm/src/hhvm/hphp/hhbbc/cfg-opts.cpp:401:7: error: no matching function for call to ‘match(boost::variant<HPHP::HHBBC::php::FaultRegion, HPHP::HHBBC::php::CatchRegion>&, HPHP::HHBBC::rebuild_exn_tree(const HPHP::HHBBC::FuncAnalysis&)::__lambda49, HPHP::HHBBC::rebuild_exn_tree(const HPHP::HHBBC::FuncAnalysis&)::__lambda50)’
       );
       ^
/root/source/hhvm/src/hhvm/hphp/hhbbc/cfg-opts.cpp:401:7: note: candidates are:
In file included from /root/source/hhvm/src/hhvm/hphp/hhbbc/misc.h:26:0,
                 from /root/source/hhvm/src/hhvm/hphp/hhbbc/analyze.h:22,
                 from /root/source/hhvm/src/hhvm/hphp/hhbbc/cfg-opts.cpp:21:
/root/source/hhvm/src/hhvm/hphp/util/match.h:99:1: note: template<class Ret, class Var, class ... Funcs> typename std::enable_if<HPHP::match_detail::is_variant<typename std::remove_cv<Var>::type>::value, Ret>::type HPHP::match(Var&, Funcs&& ...)
 match(Var& v, Funcs&&... funcs) {
 ^
/root/source/hhvm/src/hhvm/hphp/util/match.h:99:1: note:   template argument deduction/substitution failed:
/root/source/hhvm/src/hhvm/hphp/util/match.h: In substitution of ‘template<class Ret, class Var, class ... Funcs> typename std::enable_if<HPHP::match_detail::is_variant<typename std::remove_cv<Var>::type>::value, Ret>::type HPHP::match(Var&, Funcs&& ...) [with Ret = unsigned int; Var = boost::variant<HPHP::HHBBC::php::FaultRegion, HPHP::HHBBC::php::CatchRegion>; Funcs = {HPHP::HHBBC::rebuild_exn_tree(const HPHP::HHBBC::FuncAnalysis&)::__lambda49, HPHP::HHBBC::rebuild_exn_tree(const HPHP::HHBBC::FuncAnalysis&)::__lambda50}]’:
/root/source/hhvm/src/hhvm/hphp/hhbbc/cfg-opts.cpp:401:7:   required from here
/root/source/hhvm/src/hhvm/hphp/util/match.h:99:1: error: no type named ‘type’ in ‘struct std::enable_if<false, unsigned int>’
/root/source/hhvm/src/hhvm/hphp/util/match.h:112:1: note: template<class Ret, class Var, class ... Funcs> typename std::enable_if<HPHP::match_detail::is_discriminated_ptr<typename std::remove_cv<Var>::type>::value, Ret>::type HPHP::match(Var&, Funcs&& ...)
 match(Var& v, Funcs&&... funcs) {
 ^
/root/source/hhvm/src/hhvm/hphp/util/match.h:112:1: note:   template argument deduction/substitution failed:
/root/source/hhvm/src/hhvm/hphp/util/match.h: In substitution of ‘template<class Ret, class Var, class ... Funcs> typename std::enable_if<HPHP::match_detail::is_discriminated_ptr<typename std::remove_cv<Var>::type>::value, Ret>::type HPHP::match(Var&, Funcs&& ...) [with Ret = unsigned int; Var = boost::variant<HPHP::HHBBC::php::FaultRegion, HPHP::HHBBC::php::CatchRegion>; Funcs = {HPHP::HHBBC::rebuild_exn_tree(const HPHP::HHBBC::FuncAnalysis&)::__lambda49, HPHP::HHBBC::rebuild_exn_tree(const HPHP::HHBBC::FuncAnalysis&)::__lambda50}]’:
/root/source/hhvm/src/hhvm/hphp/hhbbc/cfg-opts.cpp:401:7:   required from here
/root/source/hhvm/src/hhvm/hphp/util/match.h:112:1: error: no type named ‘type’ in ‘struct std::enable_if<false, unsigned int>’
/root/source/hhvm/src/hhvm/hphp/hhbbc/cfg-opts.cpp: In instantiation of ‘HPHP::HHBBC::{anonymous}::strip_exn_tree(const HPHP::HHBBC::php::Func&, HPHP::CompactVector<std::unique_ptr<HPHP::HHBBC::php::ExnNode> >&, const std::set<HPHP::HHBBC::php::ExnNode*>&, uint32_t&, S&) [with S = std::unordered_map<long unsigned int, std::set<unsigned int> >; uint32_t = unsigned int]::__lambda45’:
/root/source/hhvm/src/hhvm/hphp/hhbbc/cfg-opts.cpp:362:11:   required from ‘struct HPHP::HHBBC::{anonymous}::strip_exn_tree(const HPHP::HHBBC::php::Func&, HPHP::CompactVector<std::unique_ptr<HPHP::HHBBC::php::ExnNode> >&, const std::set<HPHP::HHBBC::php::ExnNode*>&, uint32_t&, S&) [with S = std::unordered_map<long unsigned int, std::set<unsigned int> >; uint32_t = unsigned int]::__lambda45’
/root/source/hhvm/src/hhvm/hphp/hhbbc/cfg-opts.cpp:363:10:   required from ‘bool HPHP::HHBBC::{anonymous}::strip_exn_tree(const HPHP::HHBBC::php::Func&, HPHP::CompactVector<std::unique_ptr<HPHP::HHBBC::php::ExnNode> >&, const std::set<HPHP::HHBBC::php::ExnNode*>&, uint32_t&, S&) [with S = std::unordered_map<long unsigned int, std::set<unsigned int> >; uint32_t = unsigned int]’
/root/source/hhvm/src/hhvm/hphp/hhbbc/cfg-opts.cpp:411:57:   required from here
/root/source/hhvm/src/hhvm/hphp/hhbbc/cfg-opts.cpp:359:11: error: no matching function for call to ‘match(boost::variant<HPHP::HHBBC::php::FaultRegion, HPHP::HHBBC::php::CatchRegion>&, HPHP::HHBBC::{anonymous}::strip_exn_tree(const HPHP::HHBBC::php::Func&, HPHP::CompactVector<std::unique_ptr<HPHP::HHBBC::php::ExnNode> >&, const std::set<HPHP::HHBBC::php::ExnNode*>&, uint32_t&, S&) [with S = std::unordered_map<long unsigned int, std::set<unsigned int> >; uint32_t = unsigned int]::__lambda45::__lambda46, HPHP::HHBBC::{anonymous}::strip_exn_tree(const HPHP::HHBBC::php::Func&, HPHP::CompactVector<std::unique_ptr<HPHP::HHBBC::php::ExnNode> >&, const std::set<HPHP::HHBBC::php::ExnNode*>&, uint32_t&, S&) [with S = std::unordered_map<long unsigned int, std::set<unsigned int> >; uint32_t = unsigned int]::__lambda45::__lambda47)’
           );
           ^
/root/source/hhvm/src/hhvm/hphp/hhbbc/cfg-opts.cpp:359:11: note: candidates are:
In file included from /root/source/hhvm/src/hhvm/hphp/hhbbc/misc.h:26:0,
                 from /root/source/hhvm/src/hhvm/hphp/hhbbc/analyze.h:22,
                 from /root/source/hhvm/src/hhvm/hphp/hhbbc/cfg-opts.cpp:21:
/root/source/hhvm/src/hhvm/hphp/util/match.h:99:1: note: template<class Ret, class Var, class ... Funcs> typename std::enable_if<HPHP::match_detail::is_variant<typename std::remove_cv<Var>::type>::value, Ret>::type HPHP::match(Var&, Funcs&& ...)
 match(Var& v, Funcs&&... funcs) {
 ^
/root/source/hhvm/src/hhvm/hphp/util/match.h:99:1: note:   template argument deduction/substitution failed:
/root/source/hhvm/src/hhvm/hphp/util/match.h: In substitution of ‘template<class Ret, class Var, class ... Funcs> typename std::enable_if<HPHP::match_detail::is_variant<typename std::remove_cv<Var>::type>::value, Ret>::type HPHP::match(Var&, Funcs&& ...) [with Ret = unsigned int; Var = boost::variant<HPHP::HHBBC::php::FaultRegion, HPHP::HHBBC::php::CatchRegion>; Funcs = {HPHP::HHBBC::{anonymous}::strip_exn_tree(const HPHP::HHBBC::php::Func&, HPHP::CompactVector<std::unique_ptr<HPHP::HHBBC::php::ExnNode> >&, const std::set<HPHP::HHBBC::php::ExnNode*>&, uint32_t&, S&) [with S = std::unordered_map<long unsigned int, std::set<unsigned int> >; uint32_t = unsigned int]::__lambda45::__lambda46, HPHP::HHBBC::{anonymous}::strip_exn_tree(const HPHP::HHBBC::php::Func&, HPHP::CompactVector<std::unique_ptr<HPHP::HHBBC::php::ExnNode> >&, const std::set<HPHP::HHBBC::php::ExnNode*>&, uint32_t&, S&) [with S = std::unordered_map<long unsigned int, std::set<unsigned int> >; uint32_t = unsigned int]::__lambda45::__lambda47}]’:
/root/source/hhvm/src/hhvm/hphp/hhbbc/cfg-opts.cpp:359:11:   required from ‘HPHP::HHBBC::{anonymous}::strip_exn_tree(const HPHP::HHBBC::php::Func&, HPHP::CompactVector<std::unique_ptr<HPHP::HHBBC::php::ExnNode> >&, const std::set<HPHP::HHBBC::php::ExnNode*>&, uint32_t&, S&) [with S = std::unordered_map<long unsigned int, std::set<unsigned int> >; uint32_t = unsigned int]::__lambda45’
/root/source/hhvm/src/hhvm/hphp/hhbbc/cfg-opts.cpp:362:11:   required from ‘struct HPHP::HHBBC::{anonymous}::strip_exn_tree(const HPHP::HHBBC::php::Func&, HPHP::CompactVector<std::unique_ptr<HPHP::HHBBC::php::ExnNode> >&, const std::set<HPHP::HHBBC::php::ExnNode*>&, uint32_t&, S&) [with S = std::unordered_map<long unsigned int, std::set<unsigned int> >; uint32_t = unsigned int]::__lambda45’
/root/source/hhvm/src/hhvm/hphp/hhbbc/cfg-opts.cpp:363:10:   required from ‘bool HPHP::HHBBC::{anonymous}::strip_exn_tree(const HPHP::HHBBC::php::Func&, HPHP::CompactVector<std::unique_ptr<HPHP::HHBBC::php::ExnNode> >&, const std::set<HPHP::HHBBC::php::ExnNode*>&, uint32_t&, S&) [with S = std::unordered_map<long unsigned int, std::set<unsigned int> >; uint32_t = unsigned int]’
/root/source/hhvm/src/hhvm/hphp/hhbbc/cfg-opts.cpp:411:57:   required from here
/root/source/hhvm/src/hhvm/hphp/util/match.h:99:1: error: no type named ‘type’ in ‘struct std::enable_if<false, unsigned int>’
/root/source/hhvm/src/hhvm/hphp/hhbbc/cfg-opts.cpp: In instantiation of ‘HPHP::HHBBC::{anonymous}::strip_exn_tree(const HPHP::HHBBC::php::Func&, HPHP::CompactVector<std::unique_ptr<HPHP::HHBBC::php::ExnNode> >&, const std::set<HPHP::HHBBC::php::ExnNode*>&, uint32_t&, S&) [with S = std::unordered_map<long unsigned int, std::set<unsigned int> >; uint32_t = unsigned int]::__lambda45’:
/root/source/hhvm/src/hhvm/hphp/hhbbc/cfg-opts.cpp:362:11:   required from ‘struct HPHP::HHBBC::{anonymous}::strip_exn_tree(const HPHP::HHBBC::php::Func&, HPHP::CompactVector<std::unique_ptr<HPHP::HHBBC::php::ExnNode> >&, const std::set<HPHP::HHBBC::php::ExnNode*>&, uint32_t&, S&) [with S = std::unordered_map<long unsigned int, std::set<unsigned int> >; uint32_t = unsigned int]::__lambda45’
/root/source/hhvm/src/hhvm/hphp/hhbbc/cfg-opts.cpp:363:10:   required from ‘bool HPHP::HHBBC::{anonymous}::strip_exn_tree(const HPHP::HHBBC::php::Func&, HPHP::CompactVector<std::unique_ptr<HPHP::HHBBC::php::ExnNode> >&, const std::set<HPHP::HHBBC::php::ExnNode*>&, uint32_t&, S&) [with S = std::unordered_map<long unsigned int, std::set<unsigned int> >; uint32_t = unsigned int]’
/root/source/hhvm/src/hhvm/hphp/hhbbc/cfg-opts.cpp:411:57:   required from here
/root/source/hhvm/src/hhvm/hphp/util/match.h:112:1: note: template<class Ret, class Var, class ... Funcs> typename std::enable_if<HPHP::match_detail::is_discriminated_ptr<typename std::remove_cv<Var>::type>::value, Ret>::type HPHP::match(Var&, Funcs&& ...)
 match(Var& v, Funcs&&... funcs) {
 ^
/root/source/hhvm/src/hhvm/hphp/util/match.h:112:1: note:   template argument deduction/substitution failed:
/root/source/hhvm/src/hhvm/hphp/util/match.h: In substitution of ‘template<class Ret, class Var, class ... Funcs> typename std::enable_if<HPHP::match_detail::is_discriminated_ptr<typename std::remove_cv<Var>::type>::value, Ret>::type HPHP::match(Var&, Funcs&& ...) [with Ret = unsigned int; Var = boost::variant<HPHP::HHBBC::php::FaultRegion, HPHP::HHBBC::php::CatchRegion>; Funcs = {HPHP::HHBBC::{anonymous}::strip_exn_tree(const HPHP::HHBBC::php::Func&, HPHP::CompactVector<std::unique_ptr<HPHP::HHBBC::php::ExnNode> >&, const std::set<HPHP::HHBBC::php::ExnNode*>&, uint32_t&, S&) [with S = std::unordered_map<long unsigned int, std::set<unsigned int> >; uint32_t = unsigned int]::__lambda45::__lambda46, HPHP::HHBBC::{anonymous}::strip_exn_tree(const HPHP::HHBBC::php::Func&, HPHP::CompactVector<std::unique_ptr<HPHP::HHBBC::php::ExnNode> >&, const std::set<HPHP::HHBBC::php::ExnNode*>&, uint32_t&, S&) [with S = std::unordered_map<long unsigned int, std::set<unsigned int> >; uint32_t = unsigned int]::__lambda45::__lambda47}]’:
/root/source/hhvm/src/hhvm/hphp/hhbbc/cfg-opts.cpp:359:11:   required from ‘HPHP::HHBBC::{anonymous}::strip_exn_tree(const HPHP::HHBBC::php::Func&, HPHP::CompactVector<std::unique_ptr<HPHP::HHBBC::php::ExnNode> >&, const std::set<HPHP::HHBBC::php::ExnNode*>&, uint32_t&, S&) [with S = std::unordered_map<long unsigned int, std::set<unsigned int> >; uint32_t = unsigned int]::__lambda45’
/root/source/hhvm/src/hhvm/hphp/hhbbc/cfg-opts.cpp:362:11:   required from ‘struct HPHP::HHBBC::{anonymous}::strip_exn_tree(const HPHP::HHBBC::php::Func&, HPHP::CompactVector<std::unique_ptr<HPHP::HHBBC::php::ExnNode> >&, const std::set<HPHP::HHBBC::php::ExnNode*>&, uint32_t&, S&) [with S = std::unordered_map<long unsigned int, std::set<unsigned int> >; uint32_t = unsigned int]::__lambda45’
/root/source/hhvm/src/hhvm/hphp/hhbbc/cfg-opts.cpp:363:10:   required from ‘bool HPHP::HHBBC::{anonymous}::strip_exn_tree(const HPHP::HHBBC::php::Func&, HPHP::CompactVector<std::unique_ptr<HPHP::HHBBC::php::ExnNode> >&, const std::set<HPHP::HHBBC::php::ExnNode*>&, uint32_t&, S&) [with S = std::unordered_map<long unsigned int, std::set<unsigned int> >; uint32_t = unsigned int]’
/root/source/hhvm/src/hhvm/hphp/hhbbc/cfg-opts.cpp:411:57:   required from here
/root/source/hhvm/src/hhvm/hphp/util/match.h:112:1: error: no type named ‘type’ in ‘struct std::enable_if<false, unsigned int>’
/root/source/hhvm/src/hhvm/hphp/hhbbc/cfg-opts.cpp: In instantiation of ‘bool HPHP::HHBBC::{anonymous}::strip_exn_tree(const HPHP::HHBBC::php::Func&, HPHP::CompactVector<std::unique_ptr<HPHP::HHBBC::php::ExnNode> >&, const std::set<HPHP::HHBBC::php::ExnNode*>&, uint32_t&, S&) [with S = std::unordered_map<long unsigned int, std::set<unsigned int> >; uint32_t = unsigned int]’:
/root/source/hhvm/src/hhvm/hphp/hhbbc/cfg-opts.cpp:411:57:   required from here
/root/source/hhvm/src/hhvm/hphp/hhbbc/cfg-opts.cpp:363:10: error: no matching function for call to ‘match(boost::variant<HPHP::HHBBC::php::FaultRegion, HPHP::HHBBC::php::CatchRegion>&, HPHP::HHBBC::{anonymous}::strip_exn_tree(const HPHP::HHBBC::php::Func&, HPHP::CompactVector<std::unique_ptr<HPHP::HHBBC::php::ExnNode> >&, const std::set<HPHP::HHBBC::php::ExnNode*>&, uint32_t&, S&) [with S = std::unordered_map<long unsigned int, std::set<unsigned int> >; uint32_t = unsigned int]::__lambda44, HPHP::HHBBC::{anonymous}::strip_exn_tree(const HPHP::HHBBC::php::Func&, HPHP::CompactVector<std::unique_ptr<HPHP::HHBBC::php::ExnNode> >&, const std::set<HPHP::HHBBC::php::ExnNode*>&, uint32_t&, S&) [with S = std::unordered_map<long unsigned int, std::set<unsigned int> >; uint32_t = unsigned int]::__lambda45)’
         });
          ^
/root/source/hhvm/src/hhvm/hphp/hhbbc/cfg-opts.cpp:363:10: note: candidates are:
In file included from /root/source/hhvm/src/hhvm/hphp/hhbbc/misc.h:26:0,
                 from /root/source/hhvm/src/hhvm/hphp/hhbbc/analyze.h:22,
                 from /root/source/hhvm/src/hhvm/hphp/hhbbc/cfg-opts.cpp:21:
/root/source/hhvm/src/hhvm/hphp/util/match.h:99:1: note: template<class Ret, class Var, class ... Funcs> typename std::enable_if<HPHP::match_detail::is_variant<typename std::remove_cv<Var>::type>::value, Ret>::type HPHP::match(Var&, Funcs&& ...)
 match(Var& v, Funcs&&... funcs) {
 ^
/root/source/hhvm/src/hhvm/hphp/util/match.h:99:1: note:   template argument deduction/substitution failed:
/root/source/hhvm/src/hhvm/hphp/util/match.h: In substitution of ‘template<class Ret, class Var, class ... Funcs> typename std::enable_if<HPHP::match_detail::is_variant<typename std::remove_cv<Var>::type>::value, Ret>::type HPHP::match(Var&, Funcs&& ...) [with Ret = void; Var = boost::variant<HPHP::HHBBC::php::FaultRegion, HPHP::HHBBC::php::CatchRegion>; Funcs = {HPHP::HHBBC::{anonymous}::strip_exn_tree(const HPHP::HHBBC::php::Func&, HPHP::CompactVector<std::unique_ptr<HPHP::HHBBC::php::ExnNode> >&, const std::set<HPHP::HHBBC::php::ExnNode*>&, uint32_t&, S&) [with S = std::unordered_map<long unsigned int, std::set<unsigned int> >; uint32_t = unsigned int]::__lambda44, HPHP::HHBBC::{anonymous}::strip_exn_tree(const HPHP::HHBBC::php::Func&, HPHP::CompactVector<std::unique_ptr<HPHP::HHBBC::php::ExnNode> >&, const std::set<HPHP::HHBBC::php::ExnNode*>&, uint32_t&, S&) [with S = std::unordered_map<long unsigned int, std::set<unsigned int> >; uint32_t = unsigned int]::__lambda45}]’:
/root/source/hhvm/src/hhvm/hphp/hhbbc/cfg-opts.cpp:363:10:   required from ‘bool HPHP::HHBBC::{anonymous}::strip_exn_tree(const HPHP::HHBBC::php::Func&, HPHP::CompactVector<std::unique_ptr<HPHP::HHBBC::php::ExnNode> >&, const std::set<HPHP::HHBBC::php::ExnNode*>&, uint32_t&, S&) [with S = std::unordered_map<long unsigned int, std::set<unsigned int> >; uint32_t = unsigned int]’
/root/source/hhvm/src/hhvm/hphp/hhbbc/cfg-opts.cpp:411:57:   required from here
/root/source/hhvm/src/hhvm/hphp/util/match.h:99:1: error: no type named ‘type’ in ‘struct std::enable_if<false, void>’
/root/source/hhvm/src/hhvm/hphp/hhbbc/cfg-opts.cpp: In instantiation of ‘bool HPHP::HHBBC::{anonymous}::strip_exn_tree(const HPHP::HHBBC::php::Func&, HPHP::CompactVector<std::unique_ptr<HPHP::HHBBC::php::ExnNode> >&, const std::set<HPHP::HHBBC::php::ExnNode*>&, uint32_t&, S&) [with S = std::unordered_map<long unsigned int, std::set<unsigned int> >; uint32_t = unsigned int]’:
/root/source/hhvm/src/hhvm/hphp/hhbbc/cfg-opts.cpp:411:57:   required from here
/root/source/hhvm/src/hhvm/hphp/util/match.h:112:1: note: template<class Ret, class Var, class ... Funcs> typename std::enable_if<HPHP::match_detail::is_discriminated_ptr<typename std::remove_cv<Var>::type>::value, Ret>::type HPHP::match(Var&, Funcs&& ...)
 match(Var& v, Funcs&&... funcs) {
 ^
/root/source/hhvm/src/hhvm/hphp/util/match.h:112:1: note:   template argument deduction/substitution failed:
/root/source/hhvm/src/hhvm/hphp/util/match.h: In substitution of ‘template<class Ret, class Var, class ... Funcs> typename std::enable_if<HPHP::match_detail::is_discriminated_ptr<typename std::remove_cv<Var>::type>::value, Ret>::type HPHP::match(Var&, Funcs&& ...) [with Ret = void; Var = boost::variant<HPHP::HHBBC::php::FaultRegion, HPHP::HHBBC::php::CatchRegion>; Funcs = {HPHP::HHBBC::{anonymous}::strip_exn_tree(const HPHP::HHBBC::php::Func&, HPHP::CompactVector<std::unique_ptr<HPHP::HHBBC::php::ExnNode> >&, const std::set<HPHP::HHBBC::php::ExnNode*>&, uint32_t&, S&) [with S = std::unordered_map<long unsigned int, std::set<unsigned int> >; uint32_t = unsigned int]::__lambda44, HPHP::HHBBC::{anonymous}::strip_exn_tree(const HPHP::HHBBC::php::Func&, HPHP::CompactVector<std::unique_ptr<HPHP::HHBBC::php::ExnNode> >&, const std::set<HPHP::HHBBC::php::ExnNode*>&, uint32_t&, S&) [with S = std::unordered_map<long unsigned int, std::set<unsigned int> >; uint32_t = unsigned int]::__lambda45}]’:
/root/source/hhvm/src/hhvm/hphp/hhbbc/cfg-opts.cpp:363:10:   required from ‘bool HPHP::HHBBC::{anonymous}::strip_exn_tree(const HPHP::HHBBC::php::Func&, HPHP::CompactVector<std::unique_ptr<HPHP::HHBBC::php::ExnNode> >&, const std::set<HPHP::HHBBC::php::ExnNode*>&, uint32_t&, S&) [with S = std::unordered_map<long unsigned int, std::set<unsigned int> >; uint32_t = unsigned int]’
/root/source/hhvm/src/hhvm/hphp/hhbbc/cfg-opts.cpp:411:57:   required from here
/root/source/hhvm/src/hhvm/hphp/util/match.h:112:1: error: no type named ‘type’ in ‘struct std::enable_if<false, void>’
make[2]: *** [hphp/hhbbc/CMakeFiles/hphp_hhbbc.dir/cfg-opts.cpp.o] error 1
make[1]: *** [hphp/hhbbc/CMakeFiles/hphp_hhbbc.dir/all] error 2
make: *** [all] error 2

**Comment by mofarrell** [comment]
GCC 4.8 support stopped with HHVM 3.18 - http://hhvm.com/blog/2017/02/15/hhvm-3-18.html
