### ISSUE TITLE
Question: Is it possible to tell HHVM to provide a certain PHP version (PHP_VERSION)?

### ISSUE THREAD

**Issue by k00ni** [facebook/hhvm#7826]
## Question

Is it possible to tell HHVM to provide a certain PHP version (PHP_VERSION)?

## Background

I am currently try to run PHPUnit + HHVM inside a Travis build ([link](https://travis-ci.org/k00ni/knorke/jobs/229189844#L514)), but PHPUnit tests the PHP_VERSION [here](https://github.com/sebastianbergmann/phpunit/blob/master/phpunit#L12):

```php
if (version_compare('7.0.0', PHP_VERSION, '>')) {
```
and stops by complaining that the PHP version is not supported:

```
This version of PHPUnit is supported on PHP 7.0 and PHP 7.1.
You are using PHP 5.6.99-hhvm (/usr/bin/hhvm).
``` 
Current discussion on the PHPUnit side can be found here: https://github.com/sebastianbergmann/phpunit/issues/2581

I tried overriding the PHP_VERSION environment variable which wasn't successful:

```bash
PHP_VERSION=7.0.1 vendor/bin/phpunit
```

**Comment by fredemmott** [comment]
You want hhvm.php7.all=1 in your configuration file; that switches it to `7.0.99-hhvm`, and changes the runtime behavior to match php7

**Comment by nikic** [comment]
Anyone have instructions for making HHVM in PHP 7 mode work on Travis?

**Comment by fredemmott** [comment]
Is just running `hhvm -d hhvm.php7.all=1` an option?

**Comment by k00ni** [comment]
If you are using Travis with different PHP versions plus HHVM, you have to check for HHVM before running this command. Is there a one-liner available? 

As stated [here](https://github.com/sebastianbergmann/phpunit/issues/2581), i am struggling to get this running.
