### ISSUE TITLE
complie hhvm 3.19.1 error

### ISSUE THREAD

**Issue by saga1015** [facebook/hhvm#7829]
### HHVM Version
3.19.1
### Standalone code, or other way to reproduce the problem
standalone
### Expected result
gcc 4.92 --devtoolset-3
OS: centos 6.5 x86_64
error info:
[100%] Built target hphp_ext_zend_compat
[100%] Built target systemlib
Linking CXX executable hhvm
Generating Repo Schema ID and Compiler ID
../runtime/ext/libhphp_runtime_ext.a(ext_session.cpp.o):ext_session.cpp:function HPHP::WddxSessionSerializer::encode(): error: undefined reference to 'HPHP::WddxPacket::WddxPacket(HPHP::Variant const&, bool, bool)'
../runtime/ext/libhphp_runtime_ext.a(ext_session.cpp.o):ext_session.cpp:function HPHP::WddxSessionSerializer::encode(): error: undefined reference to 'HPHP::WddxPacket::recursiveAddVar(HPHP::String const&, HPHP::Variant const&, bool)'
../runtime/ext/libhphp_runtime_ext.a(ext_session.cpp.o):ext_session.cpp:function HPHP::WddxSessionSerializer::encode(): error: undefined reference to 'HPHP::WddxPacket::packet_end()'
collect2: error: ld returned 1 exit status
make[2]: *** [hphp/hhvm/hhvm] 错误 1
make[1]: *** [hphp/hhvm/CMakeFiles/hhvm.dir/all] 错误 2
make: *** [all] 错误 2

complie options:
export CMAKE_PREFIX_PATH=/opt/websuite/hhvm-dep
./configure -DCMAKE_BUILD_TYPE=Release \
-DCMAKE_CXX_COMPILER=/opt/rh/devtoolset-3/root/usr/bin/g++ \
-DCMAKE_C_COMPILER=/opt/rh/devtoolset-3/root/usr/bin/gcc \
-DCMAKE_C_FLAGS="-Wunused-function" \
-DCMAKE_CXX_FLAGS="-Wunused-function" \
-DDEFAULT_CONFIG_DIR=/opt/config/hhvm \
-DCMAKE_INSTALL_PREFIX=/opt/websuite/hhvm \
-DENABLE_ASYNC_MYSQL=ON \
-DENABLE_HHPROF=ON \
-DENABLE_FASTCGI=ON \
-DENABLE_MCROUTER=ON \
-DUSE_JEMALLOC=OFF \
-DUSE_TCMALLOC=ON \
-DENABLE_EXTENSION_LDAP=OFF \
-DENABLE_EXTENSION_MEMCACHE=OFF \
-DENABLE_EXTENSION_MEMCACHED=OFF \
-DENABLE_EXTENSION_ODBC=OFF \
-DENABLE_EXTENSION_PDO_SQLITE=OFF \
-DENABLE_EXTENSION_SQLITE3=OFF \
-DENABLE_EXTENSION_THRIFT=OFF \
-DENABLE_EXTENSION_WDDX=OFF \
-DTBB_INCLUDE_DIRS=/opt/websuite/hhvm-dep/include/tbb \
-DTBB_LIBRARY_DIRS=/opt/websuite/hhvm-dep/lib \
-DLIBINOTIFY_LIBRARY=/usr/lib64/libinotifytools.so \
-DENABLE_EXTENSION_WATCHMAN=OFF \
-DENABLE_EXTENSION_IMAP=OFF \
-DENABLE_EXTENSION_PGSQL=OFF \
-DENABLE_EXTENSION_FRIBIDI=OFF \
-DENABLE_EXTENSION_SNAPPY=OFF \
-DENABLE_MCROUTER=OFF \
-DENABLE_EXTENSION_MCROUTER=OFF \
-DENABLE_EXTENSION_IMAP=OFF \
-DENABLE_EXTENSION_IMAGICK=OFF

**Comment by mofarrell** [comment]
It looks like we currently don't support building with that configuration.
https://github.com/facebook/hhvm/blob/master/hphp/runtime/ext/session/ext_session.cpp#L1115 depends on wddx.

**Comment by mofarrell** [comment]
We would accept a PR to fix this.

**Comment by saga1015** [comment]
thank you very much !   :-)
