### ISSUE TITLE
hh_client: autocomplete on shape fields

### ISSUE THREAD

**Issue by vlechemin** [facebook/hhvm#7831]
Is there any reason this is not available yet?
It would help greatly on the every day use of shapes.

**Comment by dlreeves** [comment]
@ljw1004 is this something we plan on doing?

**Comment by ljw1004** [comment]
@vlechemin could you spell out precisely the autocomplete scenario you're imagining? (I can imagine several different shape-related autocompletes and want to make sure we're thinking of the same thing).

**Comment by vlechemin** [comment]
@ljw1004 It think it's the most common one, it would work the same way than for objects when you start typing ->, but with ['.
Given that it's already possible to detect wether a key is present inside a shape, it should be possible to autocomplete.
Thank you!

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Hack autocompletes shape keys when the type is known (tested in hhvm 4.56 with [vscode-hack](https://marketplace.visualstudio.com/items?itemName=pranayagarwal.vscode-hack)).
![image](https://user-images.githubusercontent.com/31805625/83063900-26b6af80-a061-11ea-9526-70c61c429909.png)
