### ISSUE TITLE
Ubuntu 17.04?

### ISSUE THREAD

**Issue by nazar-pc** [facebook/hhvm#7842]
I've head you've changed something in build process and it should be now possible to bring support for new Ubuntu releases faster than before. So, 17.04 is available for a long time now, but there is no `hhvm-nightly` even for 16.10, while I'd prefer to have `hhvm-nightly` on 17.10 already.
Can you do something about this?

**Comment by mofarrell** [comment]
We are still working on the nightly portion of the build system.  The next point release, HHVM 3.20, should have 17.04 packages.

**Comment by nazar-pc** [comment]
Great! Any chance for nightly on nightly (namely nightly HHVM build on not yet released Ubuntu 17.10)?

**Comment by mofarrell** [comment]
We aren't going to support unreleased OS versions.  In that case you can try to get the build working on the system yourself (PRs would be appreciated).  We have a lot of compatibility surface area as is with the current OSes.  Increasing this to unreleased versions would significantly add to the workload.

**Comment by nazar-pc** [comment]
As third-party application it would be much easier to deliver HHVM as static binary. The main issue I have with newer versions of Ubuntu is libboost's components and few others. Other than that it works wonderfully.

Anyway, waiting for nightly builds.

**Comment by vieira** [comment]
Hello,

Any news about pre built binaries for Ubuntu 17.04, now that 3.20 has been released?

Thanks!

**Comment by soundslocke** [comment]
I'm curious about a release for Ubuntu 17.04 as well.

**Comment by alex-mashin** [comment]
Where!?
