### ISSUE TITLE
\nFatal error: Cannot access protected property DiffEngine::$seq

### ISSUE THREAD

**Issue by edwh** [facebook/hhvm#7846]
This is on 3.13.2~trusty.  I don't have a standalone setup that reproduces this problem - it happens around twice a day on a live server.  Fairly soon after this log, hhvm exits, and is restarted by monit.

I'm not changing the code under the feet of the hhvm process - when I do that, I often see a crash afterwards, but this particular crash happens whether or not the code is changing.  

The error is a bit unhelpful - any suggestions?

Here's my server.ini

```
; php options

pid = /var/run/hhvm/pid
include_path = ".:/usr/share/php"

; hhvm specific
session.gc_maxlifetime = 604800
session.save_handler = redis
session.save_path = "tcp://localhost:6379"

hhvm.server.port = 9000
hhvm.server.type = fastcgi
hhvm.server.file_socket = /var/run/hhvm/sock
hhvm.server.default_document = index.php
hhvm.log.use_log_file = true
hhvm.log.file = /var/log/hhvm/error.log
hhvm.repo.central.path = /var/run/hhvm/hhvm.hhbc

hhvm.server.thread_count = 32
hhvm.server.backlog = 30000
hhvm.server.connection_limit = 30000

hhvm.jit_a_size=251658240
hhvm.jit_a_cold_size=100663296
hhvm.jit_a_frozen_size=167772160
hhvm.jit_a_prof_size=268435456
hhvm.jit_a_max_usage=251658240
hhvm.jit_global_data_size=62914560
```

**Comment by mofarrell** [comment]
HHVM `3.13.2` is out of support.  We may have already fixed the issue you are seeing.  If you update to the latest HHVM, and are still experiencing issues I will reopen this.  In addition we would need isolated repro steps, or at least a stack trace.  If you run the debug build, HHVM should spit out a stack trace with symbols whenever it crashes.
