### ISSUE TITLE
Cassandra access from HHVM

### ISSUE THREAD

**Issue by alex94040** [facebook/hhvm#7850]
I can't find a way to access Cassandra from HHVM, which is blocking our scenario. Am I missing something?

There's a couple other inquiries on this topic from the community, with no solution referenced.. #971 #7476 

Thanks!
-Alex

**Comment by mofarrell** [comment]
Like the previous issues mentioned, we are unlikely to get to this, but be really excited to see someone in the community work on an extension.  There is definitely interest out there.
