### ISSUE TITLE
Persistent Connection with Redis and stream_socket_client

### ISSUE THREAD

**Issue by elukey** [facebook/hhvm#7854]
Hi everybody,

I am testing persistent connections with the Redis() module on HHVM 3.12 (and soon 3.18 but the issue seems present in the master branch as well) and I noticed the following snippet:

https://github.com/facebook/hhvm/blob/master/hphp/system/php/redis/Redis.php#L1689-L1700

`stream_socket_client seems` initialized with the value `2` in the `flags` parameter, that as far as I can see from builtins_stream.hhi seems to be STREAM_CLIENT_ASYNC_CONNECT. 

Shouldn't it be something like `STREAM_CLIENT_ASYNC_CONNECT| STREAM_CLIENT_PERSISTENT` to implement persistent connections?

Apologies if this is not a real issue, for the moment I wasn't able to test/build hhvm to verify.

Thanks in advance!

Luca

**Comment by mofarrell** [comment]
@elukey I agree it seems off.  I am curious what behavioral change you are experiencing.

It would be great to see a pull request here, especially if you could add a test case for the behavior.

**Comment by elukey** [comment]
@mofarrell we wrap Redis() in the following class:

https://github.com/wikimedia/mediawiki/blob/master/includes/libs/redis/RedisConnectionPool.php

We have some workers called "Jobrunners", that basically polls regularly our Redis shards to get async jobs to process. They are now opening a TCP socket for each Redis command and I am trying to set persistent connections to reduce the sockets usage/churn and possibly solve some connect timeout issue.

We have recently [changed](https://github.com/wikimedia/mediawiki/commit/0d89c642bde78be0b1093945d69e21bd5e3c6fff) the RedisConnectionPool class to use persistent_ids, so we've never encountered the problem in the past probably because of it.

From [ext_stream.cpp](https://github.com/facebook/hhvm/blob/master/hphp/runtime/ext/stream/ext_stream.cpp#L741-L753)  it seems that the STREAM_CLIENT_PERSISTENT flag is needed, but I am not sure if the STREAM_CLIENT_ASYNC_CONNECT and STREAM_CLIENT_CONNECT are contemplated in `socket_impl`. I checked after reading http://www.php.net/manual/en/stream.constants.php, in which it is written that STREAM_CLIENT_ASYNC_CONNECT should be used with STREAM_CLIENT_CONNECT (meanwhile in the current code it is not).

If my understanding is right leaving STREAM_CLIENT_ASYNC_CONNECT might be counterproductive since if it will be supported in future versions of HHVM it could immediately trigger some side effects in the Redis() code.

Any suggestion?

**Comment by mofarrell** [comment]
Maybe https://github.com/facebook/hhvm/blob/master/hphp/system/php/redis/Redis.php#L1696 should just use all three (`STREAM_CLIENT_CONNECT`, `STREAM_CLIENT_ASYNC_CONNECT`, and `STREAM_CLIENT_PERSISTENT`)?  It seems like the only option we pay attention to `STREAM_CLIENT_PERSISTENT` anyways.  Just adding all three would make this callsite compliant with what the standard says (like you mentioned).

**Comment by elukey** [comment]
I'd agree but I am unsure if in the future STREAM_CLIENT_ASYNC_CONNECT will be picked up (say because of a change in the stream apis) changing the current behavior (that theoretically should be STREAM_CLIENT_CONNECT only). Maybe _ASYNC is the right way to go but there should be a good reason for it (or maybe a flag to specify in Redis() that explicitly enables it).

**Comment by mofarrell** [comment]
Im fine with any options, as none change the behavior.  We can drop the `STREAM_CLIENT_ASYNC_CONNECT` in favor of `STREAM_CLIENT_CONNECT`.

**Comment by elukey** [comment]
@mofarrell I am trying to test a HHVM build with STREAM_CLIENT_PERSISTENT enabled, but now I am wondering a basic question - is HHVM supposed to keep the connection open and available across multiple php script requests or only within the same script run?

**Comment by mofarrell** [comment]
@elukey It should be per request.  Unless PHP persists a connection from request to request (unlikely as they just started to do process pooling).

**Comment by elukey** [comment]
@mofarrell I was convinced about the opposite (persistence across requests), since as far as I can see it is already possible to reuse a connection within the same script (fwrite multiple times to it before closing).

https://github.com/facebook/hhvm/blob/master/hphp/runtime/ext/sockets/ext_sockets.cpp#L1460-L1466 seems to indicate that each HHVM thread has a socket_s store in which sockets are kept indexed by host:port combinations. Does it get cleaned right after each script/request run? I would have expected that the connections were kept persistent on a per thread basis, but then I wasn't also sure how/when they would have been closed (after a fclose()? Only after a timeout? etc..).

Moreover from the PHP documentation (that is used IIUC by HHVM if the persistent_id is not provided):

http://php.net/manual/en/function.pfsockopen.php

> This function behaves exactly as fsockopen() with the difference that the connection is not closed after the script finishes. It is the persistent version of fsockopen().

And the function seems to be a wrapper of sockopen_impl with persistent=true..

Is it the case that the PHP documentation is misleading about the persistent expectations?

**Comment by mofarrell** [comment]
Yeah I agree it looks like they are kept open, and should be.
