### ISSUE TITLE
Bug in erealloc() when transitioning from big to small chunks

### ISSUE THREAD

**Issue by mmuehlenhoff** [facebook/hhvm#7864]
We've been encountering segfaults with HHVM and mediawiki which are reproducible with the mediawiki test suite. The HHVM version is 3.18.2 with two additional patches cherrypicked from master (794124550bd679ff83293c67d1e43a776a4294f8 and c7da29b93b895faca98fc75119bd55bbb8ed256e) running on Debian jessie.

Some background: Wikimedia is using an PHP/HHVM extension to sandbox Lua script code:
https://github.com/wikimedia/mediawiki-php-luasandbox

These crashes are exposed by the Luasandbox and did not occur with HHVM 3.12. Further inspection points to a bug in HHVM. Below are the test results of the php-luasandbox maintainer's investigation (quoted from our Phabricator):

After a lot of experimentation, I determined that the segfaults go away if Scribunto_LuaInterpreterTest::testTestMemoryLimit() is commented out. So it seems to be something about that test in particular that's breaking things.

Playing with it some more, I made some more observations:
-  If I change the test to do 100 strings with 100000 repeats each (instead of 10 with 1000000 repeats), the segfaults go away.
- If I raise the memory limit enough that the test fails, the segfaults still remain.
- If I change alloc.c line 73 in the luasandbox PHP extension so that the memory limit is effectively ignored, the segfaults still remain.
- If I change luasandbox to use the C library malloc, realloc, and free instead of PHP's emalloc, erealloc, and efree, the segfaults go away.

All this points to a bug of some sort in HHVM's implementation of emalloc, erealloc, and/or efree.

Glancing through the HHVM sources, I see it has two different methods of allocating memory, one for "small" chunks and one for "big" chunks. The definition of "small" and "big" depends on HPHP::kMaxSmallSize. I had a hunch that it gets confused if you allocate a "small" chunk, reallocate it "big", then free it, and/or vice versa.

On that hunch, I adjusted luasandbox to use emalloc/memcpy/efree instead of erealloc. The segfaults went away. Then I adjusted it to use do that only if the reallocation crosses the HPHP::kMaxSmallSize boundary, and the segfaults still went away.

```
if((osize <= HPHP::kMaxSmallSize) != (nsize <= HPHP::kMaxSmallSize)){
     nptr = emalloc(nsize);
     memcpy(nptr, ptr, nsize < osize ? nsize : osize);
     efree(ptr);
} else {
     nptr = erealloc(ptr, nsize);
}
```
A little more experimentation establishes that the segfault only manifests when the erealloc takes it from "big" to "small", not in the other direction. This does make sense on further examination, since HHVM internally does a malloc/memcpy/free when reallocing from "small"-sized chunks.

**How to reproduce:**

The problem can be reproduced using the vagrant-mediawiki setup with these steps:

```
git clone https://gerrit.wikimedia.org/r/mediawiki/vagrant
cd vagrant
vagrant up
vagrant roles enable scribunto
vagrant provision
vagrant ssh
```

The run the following inside the Vagrant environment:

```
sudo apt-get install hhvm-luasandbox-dbg
cd /vagrant/mediawiki/
sudo -u www-data hhvm tests/phpunit/phpunit.php --wiki wiki --verbose --testsuite extensions
```
You can pass --tap to show the specific test being executed in a more verbose manner.

Let me know if you need any additional information.

**Comment by edwinsmith** [comment]
I haven't had a chance to look at this yet but it's probably a legit memory corruption bug.

**Comment by edwinsmith** [comment]
reproduced... fix coming.

**Comment by mmuehlenhoff** [comment]
Great, I'll also run some tests when a patch is available. We've been hitting that bug pretty reliably.

**Comment by mmuehlenhoff** [comment]
Thanks, I can confirm the patch addresses the bug in our environment.
