### ISSUE TITLE
Performance questions/tops : loops/arithmetic & typed arrays

### ISSUE THREAD

**Issue by soywiz** [facebook/hhvm#7865]
### HHVM Version

HipHop VM 3.19.2 (rel) bash/ubuntu/windows Ubuntu 16.04.2 LTS

First of all, congratulations for the awesome project. I have search for a forum/mailing list to ask for this; something less ethereal than an irc chat. But no luck. So I'm creating an issue. Please, feel free to close it, if there is a place where I can place these questions.

I'm creating a project that allows to AOT convert JVM code (Java/Kotlin/Scala) into PHP and other languages. This allows to run java code into a PHP VM or use java libraries/algorithms in php directly. https://github.com/jtransc/jtransc
It already works and passes my internal test suite in php7.1-x86, but it is much slower than other targets like JavaScript. 

I'm comparing JS running in Node.JS v4.2.6 vs HHVM 3.19.2 running on cli on bash/ubuntu/windows.

```
nodejs --version
v4.2.6

hhvm --version
HipHop VM 3.19.2 (rel)
Compiler: tags/HHVM-3.19.2-0-g8e7759b4b00535d65969dec6a56a03b4ed238b35
Repo schema: a02544d8eb49139aa02e1bc91bbdb6416e02af2c
```

Running this simple test that just adds an integer using a huge loop. I get the following results:
https://raw.githubusercontent.com/jtransc/jtransc-benchmark-binaries/6ed008b928ba7d0189f6cdb664c66cdff43da500/test.js
https://raw.githubusercontent.com/jtransc/jtransc-benchmark-binaries/6ed008b928ba7d0189f6cdb664c66cdff43da500/test.php

```
hhvm test.php
139.26267623901
136.86728477478
138.1516456604
136.67178153992
```

```
nodejs test.js
26
26
25
25
```

In this mini benchmark, it is 5x times slower. I'm not sure if I'm calling bad the hhvm cli. Or if it's the expected performance. So this is the first question. I know that php is not usually used for complex algorithms and that it doesn't means that it is 5 times slower than js. But just raw loops/integer arithmetic.

### Question 1:
Is JIT enabled by default in the cli? Does the JIT figure out which vars are integers, or there is something to hint them to improve performance?

In my convert java benchmark (which is bigger and does a lot of things), the performance is also bad.

source code: https://github.com/jtransc/jtransc-benchmark/blob/9c79ba8d276597eb31a451e68ac2b4b050172068/benchmark/src/Benchmark.java

nodejs version: https://raw.githubusercontent.com/jtransc/jtransc-benchmark-binaries/0bd672747f76894a7dfe052c95fb44587d1fe6e7/program.js

php/hhvm version: https://raw.githubusercontent.com/jtransc/jtransc-benchmark-binaries/0bd672747f76894a7dfe052c95fb44587d1fe6e7/program.php
Running with: `hhvm -v Eval.EnableHipHopSyntax=true program.php`

Benchmark is something like 20x slower than JS. Probably due to loop/arithmetic but also due to typed arrays access; and the second question is related to that:

### Question 2:
Does HHVM/PHP support some kind of typed arrays?

I have a TypedBuffer class, defined here, where I'm using a string that I'm mutating in order to simulate typed arrays:
https://github.com/jtransc/jtransc/blob/fb7421234c6b5d9fa81c5ac3316f64d71fd25496/jtransc-rt/resources/php/Base.php#L619

This is much slower than proper typed arrays. I have also tried  to use plain arrays or SplFixedArray, or similar . But the memory requirements are prohibitive. Does hhvm or hack support / or have plans with something similar to javascript's typed arrays. Or efficient numeric arrays? If it doesn't support it already/or it isn't planed. I would like to suggest it.
I need S8, U16, S16, S32, F32, F64 typed arrays, that just use the expected memory based on their length and with fast reading and writting.

Thanks in advance

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Hhvm's JIT received specialized types for vec/dict where all values are of the same type, MonoTypedVec and MonoTypedDict. Their performance is amazing compared to be a of Variants. There is no way for a Hack developer to explicitly request a MonoTypeVec. The JIT will intelligently choose array implementation based on profiling data. If you insert a second type into such an array, it will get deopted to a normal vec/dict again.
