### ISSUE TITLE
hhvm : Depends: libsodium but it is not installable

### ISSUE THREAD

**Issue by thebatundertaken** [facebook/hhvm#7871]
Unable to upgrade HHVM in Debian Jessie

### HHVM Version
Current version:
HipHop VM 3.19.2 (rel)
Compiler: tags/HHVM-3.19.2-0-g8e7759b4b00535d65969dec6a56a03b4ed238b35
Repo schema: a02544d8eb49139aa02e1bc91bbdb6416e02af2c

### Standalone code, or other way to reproduce the problem

apt-get upgrade hhvm

### Expected result

upgrade hhvm to latest version

### Actual result

hhvm : Depends: libsodium but it is not installable

**Comment by mofarrell** [comment]
The dependency should be on `libsodium13` not `libsodium` I will push up new packages for that.

**Comment by mofarrell** [comment]
This should be resolved now.
```
sudo apt-get update
sudo apt-get install hhvm
```
Comment here if it is still an issue.

**Comment by thebatundertaken** [comment]
It works like a charm.
thanks!
