### ISSUE TITLE
Calling static methods on classnames is a parse error in short lambdas

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#7875]
### HHVM Version

All <= 3.20.1

### Standalone code, or other way to reproduce the problem

```
<?hh

$x = (classname<mixed> $foo) ==> $foo::bar();
$y = ((classname<mixed> $foo) ==> $foo::bar());
```

### Expected result

Both of these are valid.

### Actual result

`$y` line is a parse error:

```
Fatal error: Uncaught Error: syntax error, unexpected T_VARIABLE, expecting T_DOUBLE_COLON in /in/ICa3M:4
```

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This parses correctly in hhvm 4.56.
The code doesn't passe the typechecker, since there is no static method bar on mixed.

```HACK
<<__EntryPoint>>
function main(): void {
  $x = (classname<Foo> $foo) ==> $foo::bar();
  $y = ((classname<Foo> $foo) ==> $foo::bar());
  $y(Foo::class);
}

final class Foo {
  public static function bar(): void {
    \var_dump(__FUNCTION_CREDENTIAL__->getClassName());
  }
}
```

_string(3) "Foo"_
