### ISSUE TITLE
Anonymous classes and self::-reference

### ISSUE THREAD

**Issue by thekid** [facebook/hhvm#7878]
### HHVM Version
3.20.2

### Standalone code, or other way to reproduce the problem
```bash
$ echo '<?php
  $c= (new class() {
    static function ref() { return "ref"; }
    public function test() { return self::ref(); }
  });
  var_dump($c->test());
' | hhvm --php /dev/stdin
```
### Expected result
`string(3) "ref"`
### Actual result
``` 
Fatal error: Uncaught Error: Class undefined: class@anonymous$ in /dev/stdin:1
Stack trace:
#0 /dev/stdin(1): class@anonymous$;2->test()
#1 {main}
```

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Support for anonymous classes was dropped in hhvm [4.2.0](https://hhvm.com/blog/2019/04/23/hhvm-4.2.0.html).
