### ISSUE TITLE
Difference from PHP when using __callStatic in traits combined with class inheritance

### ISSUE THREAD

**Issue by fpoirotte** [facebook/hhvm#7881]
Hello,

While writing abstractions using traits and __callStatic, I noticed a subtle difference in behavior between HHVM & PHP.

It seems that when __callStatic is used through a trait in a hierarchy of classes, all classes in the hierarchy share the same code in PHP, while they each use a different copy in HHVM.
See the reproduce code and results below (also available on https://3v4l.org/03KVS)

Interestingly, this issue does not appear when calling an existing static method instead of relying on __callStatic (PHP's behavior then matches HHVM's). See https://3v4l.org/r8o1Z for an example of that.
So the issue may actually reside in PHP rather than HHVM.

Cheers,
François

### HHVM Version
3.19.0

### Standalone code, or other way to reproduce the problem
```
<?php

trait Factory
{
    final public static function __callStatic($name, $args)
    {
        static $foo = array();
        var_dump($foo);
        $foo[get_called_class()] = __CLASS__;
    }
}

class Bar
{
    use Factory;
}

final class Baz extends Bar
{
}


Bar::make();
Baz::make();
```

### Expected result
PHP's output:
```
array(0) {
}
array(1) {
  ["Bar"]=>
  string(3) "Bar"
}
```
It seems like "Bar" & "Baz" both use the same copy of the code, and so the static variable $foo is shared between the two classes.

### Actual result
HHVM's output
```
array(0) {
}
array(0) {
}
```
Each class seems to use its own copy of the __callStatic method and hence, its own copy of the static variable.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

`Object::__callStatic()` has been removed from hhvm in version [4.4.0](https://hhvm.com/blog/2019/05/06/hhvm-4.4.0.html).
