### ISSUE TITLE
HHVM configured fail when building by msvc on windows 

### ISSUE THREAD

**Issue by PhoebeHui** [facebook/hhvm#7882]
I try to build HHVM by msvc on windows, the https://github.com/facebook/hhvm/wiki/Building-and-installing-HHVM-on-Windows-with-MSVC seems a bit simple, do you guys have any update for this guideline now?

I try to build the HHVM as following:
1. Open VS2015 x64 Native tools command prompt
2. git clone --recursive https://github.com/facebook/hhvm d:\HHVM\src
3. Download and extract deps.7z to d:\HHVM\src
   deps.7z: https://github.com/Orvid/hhvm/releases/tag/v0.0.1
4. Cd d:\HHVM
5. Mkdir build && pushd build
6. cmake -G "Visual Studio 14 Win64" ..\src

It failed to configure:
CMake Error at CMake/FindMySQL.cmake:112 (MESSAGE):
  Cannot find MySQL.  Include dir: MYSQL_INCLUDE_DIR-NOTFOUND library dir:
Call Stack (most recent call first):
  CMake/HPHPFindLibs.cmake:56 (find_package)
  CMakeLists.txt:113 (include)

Once I set -DMYSQL_INCLUDE_DIR  and -DMYSQL_LIB_DIR, it looks works, however it continued to fail due to ‘Could NOT find LibDwarf (missing: LIBELF_FOUND LIBDWARF_LIBRARIES  LIBDWARF_INCLUDE_DIRS)’

Could you help have look this issue? looking forward to building successfully on windows.

**Comment by fredemmott** [comment]
HHVM is not currently supported (or usable) natively on Windows - but orvid is continuing to work on it.

For now, your options are using the docker images, or to use the ubuntu packages inside Windows Subsystem for Linux.

**Comment by PhoebeHui** [comment]
Thanks!
