### ISSUE TITLE
Parse error on direct calls to functions returned by method

### ISSUE THREAD

**Issue by tomterl** [facebook/hhvm#7884]
### HHVM Version
HipHop VM 3.20.2 (rel)
Compiler: tags/HHVM-3.20.2-0-gad133f299ece0e45db8536473a8ef77cc4612ae3
Repo schema: 962ff68f0831a12b292f0eb9acd17f705a904446

### Standalone code, or other way to reproduce the problem
````
<?php
/**
 * User: tregner
 * Date: 15.06.2017
 * Time: 11:35
 */

class Test {
        public static function getFunc($a) {
                return function($b) use ($a) { echo "just returned {$a} ${b}\n"; };
        }
}

Test::getFunc('a')('b');
````
### Expected result
````
workstation:scratch ❯ php test.php
just returned a b
````
### Actual result
````
workstation:scratch ❯ hhvm test.php

Fatal error: Uncaught Error: syntax error, unexpected '(' in /home/tregner/scratch/test.php:14
Stack trace:
#0 {main}
````

### PHP version 
````
PHP 7.1.6-1~ubuntu16.04.1+deb.sury.org+1 (cli) (built: Jun  9 2017 08:26:34) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.6-1~ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.4, Copyright (c) 2002-2017, by Derick Rethans
````

Also tested against 7.0.X

**Comment by tomterl** [comment]
This issue shouldn't be only a php7 incompatibility, it should be accepted as error -- why would you enforce an intermediary variable in this case?

**Comment by fredemmott** [comment]
Internal references:

 - enabling for PHP7 mode and OSS hack (in runtime; it appears the typechecker already allows it): D7057672
 - enabling in (unsupported) PHP5 mode because why not: D7047841

**Comment by fredemmott** [comment]
https://github.com/facebook/hhvm/commit/e3910ad26fe2b34b21505ec9ea32ff672474ab6c
