### ISSUE TITLE
install HHVM 3.20 via YUM  on centos 6/64

### ISSUE THREAD

**Issue by linadlight** [facebook/hhvm#7885]
### HHVM Version
3.20

i did my home work and searched for 3.20 repo for centos , but it seems no luck , so i deside to ask ,
installing from source may take LOOOONG time 

Please advice

**Comment by mofarrell** [comment]
We only publish packages for Debian and Ubuntu.  We also have docker images that can be run on any distribution using Docker.  If you or someone else would like to publish and  maintain centos packages that would be great

**Comment by usox** [comment]
We're using hhvm on centos 6/7 at work and build our own binaries. Maybe, we can publish those...

**Comment by instagramlover** [comment]
@usox i will be very thankful if you can arrange for such rpm , Yum installer

**Comment by usox** [comment]
Working on it.. ;)

**Comment by linadlight** [comment]
Thank you so much.. I am in centos 6.9

**Comment by instagramlover** [comment]
@usox any good news :+1:

**Comment by usox** [comment]
@instagramlover We have the repository up and running with hhvm 3.18 rpms for centos 7 (maybe, they will work with 6 as well). We have some minor issues with the 3.20 build process, as 3.20 depends on newer versions of some dependencies. Also we have to switch to newer gcc version. I'll let you know when we're done.

**Comment by instagramlover** [comment]
Well i am using 

```
root@server []# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/gcc/libexec/gcc/x86_64-unknown-linux-gnu/4.9.2/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: ../gcc-current/configure --enable-languages=c,c++,fortran --enable-multilib --prefix=/usr/local/gcc
Thread model: posix
gcc version 4.9.2 (GCC)
```
And my php is 
```
php -v
ea-php-cli Copyright 2016 cPanel, Inc.
PHP 5.6.30 (cli) (built: Apr 28 2017 13:01:32)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend Guard Loader v3.3, Copyright (c) 1998-2014, by Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2015, by Zend Technologies

```

So is 3.18 will works just fine in my box !

**Comment by usox** [comment]
So, we finished building the 3.20 rpm. It is utterly untested as we use the tls versions (3.18) in our dev/production environments. Also, we won't provide any offiicial support. Apart from this, have fun.
http://dev.sc-networks.com/centos/7/x86_64/hhvm/

**Comment by internalsync** [comment]
@usox  The http://dev.sc-networks.com/centos/7/x86_64/hhvm/ is not valid！Can I have one available？

**Comment by usox** [comment]
@internalsync Yep, sorry. We had to move away from our companies domain :(
http://www.devblues.de/centos/7/x86_64/hhvm/

hhvm 3.27.1 and 3.27.2 will land there, too...

**Comment by internalsync** [comment]
@usox  Thank you very much！

**Comment by internalsync** [comment]
@usox  Which can be used in a production environment ？

**Comment by internalsync** [comment]
@usox  Which version is recommended？

**Comment by usox** [comment]
@internalsync Stick to the lts versions - currently 3.27.x

**Comment by internalsync** [comment]
@usox  Any recommendations for choosing between php7 and HHVM

**Comment by usox** [comment]
@internalsync I will always recommend using hack+hhvm. But be aware of the lack of tools and libraries coded in hack - compared to the php-universe.

**Comment by internalsync** [comment]
@usox Thank you very much！

**Comment by meteorlad** [comment]
@usox   The http://www.devblues.de/centos/7/x86_64/hhvm/ is not valid！Can I have one available？
