### ISSUE TITLE
42::class evaluates to "42"

### ISSUE THREAD

**Issue by rightfold** [facebook/hhvm#7890]
### HHVM Version

HHVM 3.19.0

### Standalone code, or other way to reproduce the problem

```php
<?php

var_dump(42::class);
```

### Expected result

PHP 7 fails with the error:

```
Parse error: syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM), expecting ',' or ')' in /in/bnjG0 on line 3

Process exited with code 255.
```

### Actual result

HHVM succeeds with the output:

```
string(2) "42"
```

---

Even stranger, the following code *does* fail on HHVM:

```php
<?php
$x = 42;
var_dump($x::class);
```

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Hhvm now throws an `\Error` for `42::class`.
_Uncaught Error: Cls: Expected string or object_

`$x::class` is disallowed altogether.
_Uncaught Error: Dynamic class names are not allowed in compile-time ::class fetch_
