### ISSUE TITLE
The redis extension does not support redis 3.x

### ISSUE THREAD

**Issue by maobohe** [facebook/hhvm#7893]
### HHVM Version
3.18.x

That's extremly improtant extension! why do not support redis 3.0 cluster so far?
Using hhvm set a key to redis server of cluster nodes, but result as this key always move to other cluster node.   like below
![qq 20170623190936](https://user-images.githubusercontent.com/25583472/27479695-86d24a74-5847-11e7-97f3-8e78fac6aa97.png)

**Comment by EasonFeng5870** [comment]
Yeah, this should be supported, please do it!!!

**Comment by mofarrell** [comment]
A pull request here would be great.  Most of the redis extension is even implemented in PHP.
`hphp/system/php/redis/`

**Comment by EasonFeng5870** [comment]
It will be great if guys could provide much error information to business layer, when the moved error occur, right ?

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Support for ext/redis has been removed in hhvm version [4.56.0](https://hhvm.com/blog/2020/05/04/hhvm-4.56.html).
