### ISSUE TITLE
Cannot get value by reference from generator

### ISSUE THREAD

**Issue by tgr** [facebook/hhvm#7896]
### HHVM Version
3.18.2 (3.18.2+dfsg-1+wmf5, 5.6.99-hhvm)

### Standalone code, or other way to reproduce the problem

    function &g() {
        $n = 0;
        yield $n;
        yield $n;
    }
    
    foreach ( g() as &$n ) {
        $n++;
    }
    echo $n;

### Expected result

A reference to `$n` is yielded ( so `$n === 2` at the end).
This is supported in PHP 5.5+ [per the docs](http://php.net/manual/en/language.generators.syntax.php#control-structures.yield.references).

### Actual result

PHP 5.5+: works as expected.
HHVM: `Fatal error: An iterator cannot be used with foreach by reference`
https://3v4l.org/sqZvL

**Comment by azjezz** [comment]
should be closed.

- php is not supported any more
- references have been removed from hack.
