### ISSUE TITLE
Unable to compile admin-request-handler.cpp - crypto_pwhash_str_verify was not declared

### ISSUE THREAD

**Issue by TysonAndre** [facebook/hhvm#7905]
### HHVM Version
3.20.2

### Other Versions
OS: Linux Mint 18
libsodium version : 1.0.8-5

### Standalone code, or other way to reproduce the problem

Compile with standard build instructions with libsodium 1.0.8-5 installed.

### Expected result
HHVM compiles successfully when building from source

(or configure rejects libsodium for being too old, before it starts compiling)

### Actual result

```
...
Building CXX object hphp/runtime/CMakeFiles/hphp_runtime_static.dir/server/admin-request-handler.cpp.o

/path/to/hhvm/hphp/runtime/server/admin-request-handler.cpp: In member function ‘virtual void HPHP::AdminRequestHandler::handleRequest(HPHP::Transport*)’:
/path/to/hhvm/hphp/runtime/server/admin-request-handler.cpp:427:53: error: ‘crypto_pwhash_str_verify’ was not declared in this scope
                                      password.size()) == 0) {
                                                     ^
```

---

It seems like crypto_pwhash_str_verify was added between 1.0.8 and 1.0.9 , see https://github.com/jedisct1/libsodium/commit/b5ed4cc34b4f5ab466de53428e25ee3a5eb9220c#diff-e888090b823e28f653c2ec14dcf6150fR78 

sodium_library_version_major() and sodium_library_version_minor() may be useful here (Or the macro SODIUM_LIBRARY_VERSION_MAJOR). I'd suggest only using that function if libsodium is >= 1.0.9

The code in question:

```c
#if defined(FACEBOOK) || defined(HAVE_LIBSODIUM)
      const auto password = transport->getParam("auth");
      for (const std::string& hash : RuntimeOption::HashedAdminPasswords) {
        if (crypto_pwhash_str_verify(hash.data(),
                                     password.data(),
                                     password.size()) == 0) { 
          matched = true;
          break;
        }
      }  
#endif
```

**Comment by fredemmott** [comment]
Sorry for the slow reply; a few tangental notes:
 - I recommend building in a clean environment: we're now building all our packages in clean docker containers
 - while we won't support them, if you're interested in having us automatically build packages, you could send a pull request to https://github.com/hhvm/packaging
