### ISSUE TITLE
HHVM core dumps every time an exception is thrown

### ISSUE THREAD

**Issue by Swahvay** [facebook/hhvm#7908]
I just upgraded to HHVM 3.20.2 on my Mac OS Sierra, and it worked fine until I needed to restart it. Then for some reason it now completely dies and restarts anytime an exception is thrown (even if it's caught). All I see in my error logs is `Core dumped: Abort trap: 6` and then HHVM auto-restarts. This is through Homebrew and I've tried both 3.20.2 and HEAD.

HHVM 3.20.2 (Mac OS Sierra)
Sample code:
```
try {
  throw new Exception('Foo');
} catch (Exception $e) {
  echo('Caught');
}
```
Expected: **Caught**
Actual:

**Comment by Swahvay** [comment]
If I run the same script from a command line I get this:
```
<jemalloc>: Invalid conf pair: lg_dirty_mult:5
```

**Comment by Swahvay** [comment]
The generated stacktrace log file looks like this:
```
Host: Barnlog.local
ProcessID: 21894
ThreadID: 2952798208
ThreadPID: -1
Name: unknown program
Type: Abort trap: 6
Runtime: hhvm
Version: 1499651054_N
DebuggerCount: 0

Server: dev.barnlog.com
ThreadType: Web Request
Server_SERVER_NAME: dev.barnlog.com
URL: /

PHP Stacktrace:
...
```

**Comment by fredemmott** [comment]
#7821
