### ISSUE TITLE
Serious memory leak running MediaWiki

### ISSUE THREAD

**Issue by KenanSulayman** [facebook/hhvm#7911]
### Envionment
HHVM 3.20.2 (hhvm/hhvm-proxygen tag 3.20.2) as Docker deployment
Docker version 17.05.0-ce, build 89658be
Ubuntu 16.04.2 LTS using kernel 4.4.0-78-generic

## Issue description
HHVM is running into serious memory problems (and with that latency issues) every few days, running a contained MediaWiki 1.28.0 instance.

## Metrics
![screen shot 2017-07-11 at 23 06 35](https://user-images.githubusercontent.com/280212/28091174-4af7d040-668f-11e7-9d1f-e2d2d082cc09.png)
![screen shot 2017-07-11 at 23 06 43](https://user-images.githubusercontent.com/280212/28091180-4d3fadb4-668f-11e7-8497-3b9320166a1f.png)
![screen shot 2017-07-11 at 23 07 00](https://user-images.githubusercontent.com/280212/28091183-50be8c80-668f-11e7-80b9-fb0d15157ade.png)
![screen shot 2017-07-11 at 23 09 01](https://user-images.githubusercontent.com/280212/28091723-4a0c2e04-6691-11e7-8950-b6aeb1f61e77.png)

## Spawned sub-processes (by MediaWiki)
![screen shot 2017-07-11 at 23 23 35](https://user-images.githubusercontent.com/280212/28091529-5ef94032-6690-11e7-9292-83df98415d66.png)

This has happened ever since deploying hhvm into production (PHP7 was used before).

I'm unsure whether the typechecker has something to do with it, but I have disabled it as of now.

**Comment by denzuko** [comment]
more than a year and a half later and this is open still. Is there any resolution on this issue?
