### ISSUE TITLE
Build packages for Debian 9 (aka. Debian Stretch)

### ISSUE THREAD

**Issue by fpoirotte** [facebook/hhvm#7917]
Hello,

The repository over at http://dl.hhvm.com/debian/dists/ only provides packages for Debian 7 & 8 (Wheezy & Jessie). Would it be possible to also build packages for Debian 9/Stretch?

Simply trying to install the ones from Debian Jessie fails due to missing dependencies:
```
The following packages have unmet dependencies:
 hhvm : Depends: libmagickwand-6.q16-2 but it is not going to be installed
        Depends: libgoogle-glog0 but it is not going to be installed
        Depends: libsnappy1 but it is not going to be installed
```

Starting with Debian Stretch, libmagickwand-6.q16-2 has been replaced with libmagickwand-6.q16-3 libgoogle-glog0 has been replaced with libgoogle-glog0v5, and libsnappy1 has been replaced with libsnappy1v5.

As a side question, do you provide the contents of the debian/ folder used to build those packages? (just curious as I wanted to rebuild the packages with updated dependencies to test them, but could not find the required files to do so)

Thank you for your hard work,
François

**Comment by lambertlu** [comment]
Also like to know the build process.
And I am interesting of disable some feature or extensions to save memory/cpu resources.

**Comment by fpoirotte** [comment]
I just found out about https://github.com/hhvm/packaging/ where it says work to support Debian Stretch is currently underway. I'm therefore closing this issue.

@lambertlu : you'll probably find the information you need there

**Comment by lambertlu** [comment]
Thank you @fpoirotte
