### ISSUE TITLE
Prebuilt packages for Ubuntu 17.04 (Zesty)

### ISSUE THREAD

**Issue by vieira** [facebook/hhvm#7923]
### HHVM Version
HHVM 3.20 which was released well after Ubuntu 17.04 (zesty) was released.

### Standalone code, or other way to reproduce the problem
N.A.

### Expected result
Dropping prebuilt binaries for Ubuntu 16.10 and starting building for 17.04.

### Actual result
Still building for 16.10 but not for 17.04.

**Comment by alex-mashin** [comment]
Bump.

**Comment by fredemmott** [comment]
Closing, tracking over at hhvm/packaging#128
