### ISSUE TITLE
Uncaught Error: Class 'UConverter' not found in /root/src/github.com/facebook/hhvm/hphp/test/run:1360

### ISSUE THREAD

**Issue by vielmetti** [facebook/hhvm#7928]
### HHVM Version

HipHop VM 3.20.0-dev (rel)
Compiler: heads/master-0-g26a2f8c2795726e89dd636c16b2e1e6316dee7df
Repo schema: c9ccdb2b68ae4d61f3c1c0232b4b2426ff39c26e

Compiled from source on a Packet Type 2A aarch64 (ARMv8) system.

PHP version: 

PHP 7.0.18-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.18-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies

### Standalone code, or other way to reproduce the problem

% pushd hphp
% test/run quick

### Expected result

Test runs without error.

### Actual result

Uncaught Error: Class 'UConverter' not found in /root/src/github.com/facebook/hhvm/hphp/test/run:1360

### Comments

This looks like #3307 all over again?

**Comment by swalk-cavium** [comment]
@vielmetti - Hi Ed,  if you add the -v option to your command line it will show you the exact
arguments presented to hhvm.  I've seen that failure message when something is asserting internally.

**Comment by vielmetti** [comment]
Thanks @swalk-cavium - here's a longer trace from `test/run quick -v`.

```
~/src/github.com/facebook/hhvm/hphp# test/run quick -v > /tmp/hhvm.test.out
PHP Fatal error:  Uncaught Error: Class 'UConverter' not found in /root/src/github.com/facebook/hhvm/hphp/test/run:1360
Stack trace:
#0 /root/src/github.com/facebook/hhvm/hphp/test/run(1258): Status::utf8Sanitize('002+ bool(true)...')
#1 /root/src/github.com/facebook/hhvm/hphp/test/run(1430): Status::fail('test/quick/chdi...', 5.1396479606628, 1500997591, 1500997596)
#2 /root/src/github.com/facebook/hhvm/hphp/test/run(2949): run(Array, Array, '/tmp/test-run-U...')
#3 /root/src/github.com/facebook/hhvm/hphp/test/run(3074): main(Array)
#4 {main}
  thrown in /root/src/github.com/facebook/hhvm/hphp/test/run on line 1360
PHP Fatal error:  Uncaught Error: Class 'UConverter' not found in /root/src/github.com/facebook/hhvm/hphp/test/run:1360
Stack trace:
#0 /root/src/github.com/facebook/hhvm/hphp/test/run(1258): Status::utf8Sanitize('001+ Foo: Segme...')
#1 /root/src/github.com/facebook/hhvm/hphp/test/run(1430): Status::fail('test/quick/setg...', 2.4440221786499, 1500997610, 1500997612)
#2 /root/src/github.com/facebook/hhvm/hphp/test/run(2949): run(Array, Array, '/tmp/test-run-W...')
#3 /root/src/github.com/facebook/hhvm/hphp/test/run(3074): main(Array)
#4 {main}
  thrown in /root/src/github.com/facebook/hhvm/hphp/test/run on line 1360
PHP Fatal error:  Uncaught Error: Class 'UConverter' not found in /root/src/github.com/facebook/hhvm/hphp/test/run:1360
Stack trace:
#0 /root/src/github.com/facebook/hhvm/hphp/test/run(1258): Status::utf8Sanitize('001+ Foo: Segme...')
#1 /root/src/github.com/facebook/hhvm/hphp/test/run(1430): Status::fail('test/quick/sets...', 2.7450850009918, 1500997613, 1500997616)
#2 /root/src/github.com/facebook/hhvm/hphp/test/run(2949): run(Array, Array, '/tmp/test-run-6...')
#3 /root/src/github.com/facebook/hhvm/hphp/test/run(3074): main(Array)
#4 {main}
  thrown in /root/src/github.com/facebook/hhvm/hphp/test/run on line 1360
```

**Comment by vielmetti** [comment]
and here's `php -m` for good measure:

```
~/src/github.com/facebook/hhvm/hphp# php -m
[PHP Modules]
calendar
Core
ctype
date
exif
fileinfo
filter
ftp
gettext
hash
iconv
json
libxml
openssl
pcntl
pcre
PDO
Phar
posix
readline
Reflection
session
shmop
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
Zend OPcache
zlib

[Zend Modules]
Zend OPcache
```

Note that the "intl" module is not compiled in.

**Comment by vielmetti** [comment]
I did `sudo apt-get install php7.0-intl` and reran the tests. In this case three failed, but no mysterious errors.

Since the failed tests are likely unrelated to the `intl` module, I'm going to noted this as fixed, but with a note that it should really be reflected in the documentation the contents of http://php.net/manual/en/intl.installation.php which were enough to get this going on Ubuntu.
