### ISSUE TITLE
Compile error because libxed is missing

### ISSUE THREAD

**Issue by wwbmmm** [facebook/hhvm#7931]
### HHVM Version
3.20-dev (9b1f53360d2)

### Actual result
compile error:

hphp/tools/tc-print/offline-x86-code.cpp:243:3: error: ‘error’ does not name a type
   error "tc-print on x86_64 requires libxed"

How to get libxed?

**Comment by swalk-cavium** [comment]
Looks like 978e3c0 refactoring was not right when libxed is not installed.

The source for libxed can be found here:
https://software.intel.com/en-us/articles/xed-x86-encoder-decoder-software-library

I'll work on a pull request to correct this.

**Comment by swalk-cavium** [comment]
PR#7933 submitted.

**Comment by fredemmott** [comment]
That PR was merged, fixing this.
