### ISSUE TITLE
Redis session handler does not use multiple servers or have failover

### ISSUE THREAD

**Issue by AnoopAlias** [facebook/hhvm#7941]
### HHVM Version
# hhvm --version
HipHop VM 3.15.3 (rel)
Compiler: tags/HHVM-3.15.3-0-g965cd8d30670726d88720412c3384225a2da011d
Repo schema: 7f22464926cb7fc3a19c6af88309c612a8581c55

### Standalone code, or other way to reproduce the problem
hhvm.ini settings set to 

; Redis session store backend
session.save_handler = redis
session.save_path = "tcp://127.0.0.1:9501?database=2&timeout=3,tcp://127.0.0.1:6379?database=2&timeout=3"

### Expected result

Session must be stored in both 127.0.0.1:9501 and 127.0.0.1:6379 instances .This is how it works with PHP and can be used as a multi server redundancy technique

### Actual result

The session is only stored in the first redis server in the list and not both and in case of one redis server is down there is no failover to the second.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Support for the Redis extension has been removed in hhvm [4.56](https://hhvm.com/blog/2020/05/04/hhvm-4.56.html).
