### ISSUE TITLE
Memcached extension hhi out of sync

### ISSUE THREAD

**Issue by bakks** [facebook/hhvm#7950]
This is an issue on master and going back at least as far as 3.18.

The [.hhi file](https://github.com/facebook/hhvm/blob/master/hphp/hack/hhi/stdlib/builtins_memcached.hhi) for the built in memcached extension is out of sync with the [extension code itself](https://github.com/facebook/hhvm/blob/master/hphp/runtime/ext/memcached/ext_memcached.php). For example, the extension implements a `resetServersList()` method that doesn't appear in the hhi definition. Another example: the extension implements a 4 argument `increment()` method, while the hhi file defines this method as having 2 arguments.

This causes problems if you're working with the memcached extension while in strict mode. At the very least the hhi should agree with the implementation. It would also be nice if the Memcached hhi declared types on its methods.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This issue was addressed by f284e0a as the author mentioned.
