### ISSUE TITLE
有没有centos7的有效可用的安装教程啊？

### ISSUE THREAD

**Issue by pop300p** [facebook/hhvm#7952]
有没有centos7的有效可用的安装教程啊？
始终找不到资料……
看到hhvm不断的更新，可惜没有什么资料可以学习、使用。

**Comment by wwbmmm** [comment]
hhvm还是ubuntu安装比较方便
centos7你可以先装个docker，
docker里面跑个ubuntu镜像然后安装hhvm

**Comment by fredemmott** [comment]
Sorry, we don't currently target any distributions other than Debian and Ubuntu, and currently don't have enough time to investigate adding support on top of all the other things we need to do for the open source community.

That said, we'd now be able to take pull requests adding support to https://github.com/hhvm/packaging - currently, this would be against the contents of the ng/ directory, though I expect that to replace the root directory shortly.
