### ISSUE TITLE
code.cold cache  always  increase,,then will crash

### ISSUE THREAD

**Issue by ghost** [facebook/hhvm#7963]
### HHVM Version
 3.20.0
the below messege  which comes from admin server status  (vm-tcsapce)

> mcg: 104155512 bytes (38%) in code.cold

when it reaches 100%, the hhvm will restart ,probably once one day
This is what causes it?

**Comment by fredemmott** [comment]
This is probably from usage of eval() or create_function(); both of these are best avoided (e.g. use lambdas instead). adding -vEval.EnableReusableTC=true to the HHVM parameters may help.
