### ISSUE TITLE
oss-performance drupal8-page-cache scores are down by 10x 

### ISSUE THREAD

**Issue by jim-saxman** [facebook/hhvm#7976]
### HHVM Version
HHVM master branch as of Monday Aug 28, 2017 with commit dc21525c3ab21fcdb2e5755243f7662403f003e4
Author: Taylor Hopper <thopper@fb.com>
Date:   Mon Aug 28 11:32:17 2017 -0700

    Detect incorrect type in group use clause

### Standalone code, or other way to reproduce the problem
~/oss-perfomance$ hhvm perf.php --drupal8-page-cache --hhvm=../hhvm/hphp/hhvm/hhvm

### Expected result
about 6000 trans/sec on an x86-64 machine

### Actual result
about 600 trans/sec

I bisected the slow-down to this commit from Friday:
commit a7446e5f553489f271e217f1e1c1ad63d460d819
Author: Mark Williams <mwilliams@fb.com>
Date:   Fri Aug 25 09:45:56 2017 -0700

    Support constprop for CnsU when HardConstProp is enabled
    
    Summary:
    If we know the namespaced constant isn't defined anywhere, and we know
    the fallback constant *is* defined, we should just use the fallback
    constant.
    
    Also fix an issue where we would propagate constants even when
    HardConstProp was false.
    
    Reviewed By: alexeyt, ricklavoie

Specifically this code block https://github.com/facebook/hhvm/blob/01034c4f20e11049c1c1c26e2a09a91876c014e0/hphp/hhbbc/index.cpp#L2736

**Comment by mofarrell** [comment]
Can you verify that the site was functioning correctly when it was operating at 6000 rps?  My guess is the request were 500ing until this change.

**Comment by jim-saxman** [comment]
@mofarrell, Nothing but
HTTP/1.1 200   0.06 secs:   60384 bytes ==> GET    /node/18
HTTP/1.1 200   0.06 secs:   13019 bytes ==> GET    /node/49
HTTP/1.1 200   0.07 secs:   15552 bytes ==> GET    /node/45
HTTP/1.1 200   0.06 secs:   13025 bytes ==> GET    /node/50
HTTP/1.1 200   0.06 secs:   13363 bytes ==> GET    /node/16
HTTP/1.1 200   0.06 secs:   13203 bytes ==> GET    /node/6
HTTP/1.1 200   0.06 secs:   68795 bytes ==> GET    /index.php
HTTP/1.1 200   0.06 secs:   16025 bytes ==> GET    /node/47
HTTP/1.1 200   0.06 secs:   13203 bytes ==> GET    /node/6
As far as the eye can siege. Although I really thought you had the right idea after reading your post.

**Comment by mofarrell** [comment]
@markw65  Figured out what is happening.
> I downloaded drupal, and just built it with hhvm before and after that change.                                                                 
as expected, very little difference, except a bunch of system constants got resolved, eliminating a lot of code                                             
but I think the problem is PHP_SAPI. its being resolved to "cli", and drupal does different things according to its value                                   
this really has nothing to do with the cnsu change, except that because PHP_SAPI was being used inside a namespace, we were failing to resolve it previously
but if it had been used outside a namespace, the bug already existed...
