### ISSUE TITLE
hhvm seems not optimized for gmp

### ISSUE THREAD

**Issue by j0101s** [facebook/hhvm#7979]
### HHVM Version
HipHop VM 3.18.4 (rel)
Compiler: tags/HHVM-3.18.4-0-g16ddc38f40e2464696fc5dbcb22de5440c5a1455
Repo schema: 9c1e11cdaaabdc99e7f7b515ce920d899fd2fc3a

### PHP Version
PHP 5.5.9-1ubuntu4.21 (cli) (built: Feb  9 2017 20:54:58) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies

### Standalone code, or other way to reproduce the problem

https://benchmarksgame.alioth.debian.org/u64q/program.php?test=pidigits&lang=php&id=5

### Expected result
hhvm 3.x.x faster than php 5.x.x

### Actual result
php 5.x.x much faster than hhvm 3.x.x

time hhvm pidigits.php 10000 > pi.txt
real    0m1.915s
user    0m1.896s
sys     0m0.008s

time php pidigits.php 10000 > pi.txt
real    0m0.723s
user    0m0.712s
sys     0m0.008s

No optimization for gmp module?? This is quite disappointing result.

**Comment by fredemmott** [comment]
We generally don't optimize for/investigate microbenchmarks, as they tend not to be representative of real-world situations. In this case, jit warmup time is likely to be a significant amount of that time, if the jit even gets involved at all.

**Comment by j0101s** [comment]
Well, you didn't actually do the testing. Below is the warmup time for php and hhvm respectively.
Subtracting that, hhvm is still more than twice slower than php 5.x.x in gmp involved calculations.
You should know that there are people who do scientific calculations in PHP.

* no actual calculation performed to check only warmup time.

time php pidigits.php

real    0m0.014s
user    0m0.008s
sys     0m0.004s


time hhvm pidigits.php

real    0m0.103s
user    0m0.080s
sys     0m0.008s
