### ISSUE TITLE
Syntax error calling method (but not property) of object assigned within Parentheses

### ISSUE THREAD

**Issue by n8man** [facebook/hhvm#7992]
### HHVM Version

> HipHop VM 3.21.0 (rel)
> Compiler: tags/HHVM-3.21.0-0-gbdbaff80f67e02080f1ea377d30efee63f10126d
> Repo schema: 1381c379b9e7d8cd9efa2ce49aeb6f699919dc3a
> 

### Standalone code, or other way to reproduce the problem
`hhvm --php -r 'echo ($a = new ArrayObject)->count();'`

### Expected result
`0`

### Actual result

> Fatal error: Uncaught Error: syntax error, unexpected '(', expecting ',' or ';' in /tmp/php-wrap-erj8Ww:2
> Stack trace:
> #0 {main}
> 

### Standalone code, or other way to reproduce the problem
```
<?php

class Greeter {
        public $greeting = "Hello!";

        public function greet() {
                return $this->greeting;
        }
}

echo ($greeter1 = new Greeter)->greeting . " -Property \n"; // Accessing property
echo ($greeter2 = new Greeter)->greet() . " -Method \n"; // Accessing method
```
### Expected result
> Hello! -Property 
> Hello! -Method 

### Actual result
> 
> Fatal error: Uncaught Error: syntax error, unexpected '(', expecting ',' or ';' in /var/www/new/public/hhvm_break.php:12
> Stack trace:
> #0 {main}

Commenting out line 12 returns:
> Hello! -Property

**Comment by yvanoers** [comment]
This seems to be fixed upstream.
Checked with master from 4 Nov 2017 (HHVM 3.23.0-dev).

**Comment by fredemmott** [comment]
https://github.com/facebook/hhvm/commit/0e41d15abc9a435d22161acf96f920a3fe4db2eb
