### ISSUE TITLE
magento seg fault

### ISSUE THREAD

**Issue by ollyboy** [facebook/hhvm#7993]
### HHVM Version

HHVM-3.21.0 on ubunto LTS 16 

### Standalone code, or other way to reproduce the problem

Can find anything in the logs

Finished singleJitRequest 17
Finished singleJitRequest 18
Finished singleJitRequest 19
Finished singleJitRequest 20
perf_event_open failed with: No such file or directory
perf_event_open failed with: No such file or directory
perf_event_open failed with: No such file or directory
perf_event_open failed with: No such file or directory
perf_event_open failed with: No such file or directory
perf_event_open failed with: No such file or directory
perf_event_open failed with: No such file or directory
perf_event_open failed with: No such file or directory
perf_event_open failed with: No such file or directory
Core dumped: Segmentation fault
Stack trace in /tmp/stacktrace.1071.log
### Actual result - here is the stacktrace

Host: ip-172-31-43-21
ProcessID: 1072
ThreadID: 139936401454848
ThreadPID: 23435
Name: unknown program
Type: Segmentation fault
Runtime: hhvm
Version: tags/HHVM-3.21.0-0-gbdbaff80f67e02080f1ea377d30efee63f10126d
DebuggerCount: 0

# 0  0000000003651676
# 1  000000000119abc2
# 2  00007f45ba89b390
# 3  000000000175bda8
# 4  0000000001c3ff1b
# 5  0000000001e069a8
# 6  00000000022d863a
# 7  00000000022df30a
# 8  0000000000e108f3
# 9  000000000137cb36
# 10 00007f45ba8916ba
# 11 00007f45b3edc3dd

PHP Stacktrace:

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This issue applies to running php code on hhvm. Hhvm [nolonger supports running php code](https://hhvm.com/blog/2018/09/12/end-of-php-support-future-of-hack.html) since [hhvm version 4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html).
