### ISSUE TITLE
HHVM 3.21 in PHP 7 mode reports itself as PHP 7.1, but doesn't support the iterable pseudo-type

### ISSUE THREAD

**Issue by ezzatron** [facebook/hhvm#8003]
### HHVM Version

3.21

### Standalone code, or other way to reproduce the problem

From https://3v4l.org/lBSQB

```php
<?php

var_dump(PHP_MAJOR_VERSION . '.' . PHP_MINOR_VERSION);

$r = new ReflectionFunction(function (iterable $a) {});
$p = $r->getParameters()[0];
var_dump(strval($p->getType()), $p->getClass());
```

### Expected result

```
string(3) "7.1"
string(8) "iterable"
NULL
```

### Actual result

```
string(3) "7.1"

Fatal error: Uncaught exception 'ReflectionException' with message 'Class iterable does not exist' in /in/lBSQB:7
Stack trace:
#0 (): ReflectionClass->__construct()
#1 /in/lBSQB(7): ReflectionParameter->getClass()
#2 {main}
```

**Comment by Neustradamus** [comment]
http://hhvm.com/blog/2017/09/18/the-future-of-hhvm.html

**Comment by ezzatron** [comment]
I actually saw that this morning. Makes sense, but unfortunately that probably spells the end of HHVM support for my mocking library.

Thanks for the years of effort on HHVM, and good luck in the future.
