### ISSUE TITLE
unknown_fields_shape_is_not_subtype_of_known_fields_shape requires optional_shape_field

### ISSUE THREAD

**Issue by simonwelsh** [facebook/hhvm#8008]
### HHVM Version

3.22.0/master

### Standalone code, or other way to reproduce the problem

`.hhconfig`:
```
enable_experimental_tc_features = unknown_fields_shape_is_not_subtype_of_known_fields_shape
```

`test.php`:
```hack
<?hh // strict

type MyShape = shape('myfield' => string);
function foo(MyShape $_): void {}

function main(): void {
  foo(shape('myfiedl' => 'oops I typoed'));
}
```

### Expected result

```
test.php:7:7,11: Invalid argument (Typing[4166])
  test.php:4:14,20: The field 'myfiedl' is not defined in this shape type, and this shape type does not allow unknown fields.
  test.php:7:7,11: The field 'myfiedl' is set in the shape.
```

### Actual result

```
No errors!
```

Adding `optional_shape_field` to `enable_experimental_tc_features` gets it working

**Comment by fredemmott** [comment]
I'll change the post; wontfix as:
 - we shouldn't backport a change here to a stable release
 - the options will be changing in 3.23 anyway as we change to opt-out
