### ISSUE TITLE
xlocale.h inclusion causes build failure with glibc 2.26

### ISSUE THREAD

**Issue by mmuehlenhoff** [facebook/hhvm#8009]
glibc 2.26 removed <xlocale.h>, see https://sourceware.org/glibc/wiki/Release/2.26#Removal_of_.27xlocale.h.27

It's included in https://github.com/facebook/hhvm/blob/master/hphp/util/locale-portability.h#L34 which makes hhvm fail to build on glibc 2.26.

Since xlocale.h is a superset of locale.h, which is included in the same file, it can simply be removed.

**Comment by octmoraru** [comment]
b506902af2b7c53de6d6c92491c2086472292004 should solve this @fredemmott
