### ISSUE TITLE
3.22 segfault running wordpress

### ISSUE THREAD

**Issue by PlayYou** [facebook/hhvm#8015]
### HHVM Version

HHVM-3.22.1

### Standalone code, or other way to reproduce the problem

Updated the HHVM to the latest version

### Expected result

All work perfectly ans my web site can be accessed

### Actual result

Got a 502 bad gateway with that error : "upstream prematurely closed connection while reading response header from upstream"

**Comment by eipporko** [comment]
I got the same 502 response when I updated the HHVM to this version.

**Comment by RC-Thoughts** [comment]
One more here. Installing hhvm-nightly in Debian Jessie works with same settings in server.ini & nginx.

**Comment by fredemmott** [comment]
This can't be investigated as is: this just says that nginx stopped being able to talk to HHVM, which isn't a usuable starting point. Please open issues with any errors you're getting **from HHVM**, for example, stack traces from the segmentation faults you mentioned.

**Comment by PlayYou** [comment]
Thanks, I have now the error :

`Host: playyou.be
ProcessID: 31156
ThreadID: 140653910554368
ThreadPID: 31191
Name: unknown program
Type: Segmentation fault
Runtime: hhvm
Version: tags/HHVM-3.22.1-0-ge8ce62608d2d14e6418772b07ebaddcbdb37598f
DebuggerCount: 0

Server: payday2.fr
ThreadType: Web Request
Server_SERVER_NAME: payday2.fr
URL: /

# 0  0000000000e45da6
# 1  000000000122e153
# 2  00007feca48b6890
# 3  00000000012b0180
# 4  000000000367a3a0
# 5  000000000173b8c5
# 6  0000000001913571
# 7  00000000036965ed
# 8  0000000003694f4f
# 9  00000000037b19f1
# 10 00000000037b1821
# 11 00000000037b15e1
# 12 00000000013bb5c4
# 13 000000000379fbf7
# 14 0000000003796d97
# 15 00000000016d320f
# 16 00000000016d3def
# 17 0000000000e0adb7
# 18 000000000124d355
# 19 00007feca48af064
# 20 00007fec9eab162d

PHP Stacktrace:

#0  join() called at [/home/www/payday2.fr/public_html/wp-includes/post-template.php:557]
#1  body_class() called at [/home/www/payday2.fr/public_html/wp-content/themes/salient/header.php:121]
#2  include() called at [/home/www/payday2.fr/public_html/wp-includes/template.php:688]
#3  load_template() called at [/home/www/payday2.fr/public_html/wp-includes/template.php:647]
#4  locate_template() called at [/home/www/payday2.fr/public_html/wp-includes/general-template.php:45]
#5  get_header() called at [/home/www/payday2.fr/public_html/wp-content/themes/salient/page.php:3]
#6  include() called at [/home/www/payday2.fr/public_html/wp-includes/template-loader.php:74]
#7  include() called at [/home/www/payday2.fr/public_html/wp-blog-header.php:19]
#8  include() called at [/home/www/payday2.fr/public_html/index.php:17]
`

**Comment by fredemmott** [comment]
Thanks;
 - are you able to reproduce the problem with the `hhvm-dbg` package instead? If so, that'll give a more useful backtrace
 - are you able to reduce the problem running wordpress to a small example without dependencies?
 - what distribution version are you running?

**Comment by fredemmott** [comment]
> I can't connect to the web site, it's show a 504 Gateway Time-out

Can you provide the HHVM error you get with hhvm-dbg, like you did for the non-dbg package in your previous comment?

> small example without dependencies

We generally don't have time to investigate whole frameworks such as wordpress. It is much more likely that issues like this will be fixed if you can simplify the code needed to reproduce the crash to a single file with a small number of lines.

Also, if you've not seen it already, you probably want to read through hhvm.com/blog/2017/09/18/the-future-of-hhvm.html - 3.24 will be the last release where we aim to support PHP websites.

**Comment by PlayYou** [comment]
I don't have any segmentation fault, I have only this in my **error.log** in **var/log/hhvm**

```
perf_event_open failed with: Permission denied
perf_event_open failed with: Permission denied
perf_event_open failed with: Permission denied
Finished singleJitRequest 1
perf_event_open failed with: Permission denied
perf_event_open failed with: Permission denied
perf_event_open failed with: Permission denied
Finished singleJitRequest 2
Finished singleJitRequest 3
perf_event_open failed with: Permission denied
perf_event_open failed with: Permission denied
perf_event_open failed with: Permission denied
perf_event_open failed with: Permission denied
perf_event_open failed with: Permission denied
perf_event_open failed with: Permission denied
Finished singleJitRequest 4
Finished singleJitRequest 5
Finished singleJitRequest 6
perf_event_open failed with: Permission denied
perf_event_open failed with: Permission denied
perf_event_open failed with: Permission denied
Finished singleJitRequest 7
Finished singleJitRequest 8
Finished singleJitRequest 9
Finished singleJitRequest 10
Finished singleJitRequest 11
Finished singleJitRequest 12
Finished singleJitRequest 13
```

Do you mean I give the code line with the error ?

**Comment by RC-Thoughts** [comment]
hhvm-dbg does not segfault, it times out and site is slow. 

```
http://dl.hhvm.com/debian/ jessie/main hhvm-dbg amd64 3.22.1~jessie
 
HipHop VM 3.22.1 (dbg)
Compiler: tags/HHVM-3.22.1-0-ge8ce62608d2d14e6418772b07ebaddcbdb37598f
Repo schema: 05fc45ee8e70c9f18dfb1e867219c8528be87996
```
My error log does look a bit different:
```
tail -f /var/log/hhvm/error.log
[Tue Oct 10 19:28:11 2017] [hphp] [752:7fa174bff700:0:000001] [] perf_event_open failed with: No such file or directory
[Tue Oct 10 19:28:11 2017] [hphp] [752:7fa174bff700:0:000002] [] perf_event_open failed with: No such file or directory
[Tue Oct 10 19:28:11 2017] [hphp] [752:7fa174bff700:0:000003] [] perf_event_open failed with: No such file or directory
[Tue Oct 10 19:28:11 2017] [hphp] [752:7fa1987ff700:0:000001] [] perf_event_open failed with: No such file or directory
[Tue Oct 10 19:28:11 2017] [hphp] [752:7fa1987ff700:0:000002] [] perf_event_open failed with: No such file or directory
[Tue Oct 10 19:28:11 2017] [hphp] [752:7fa1987ff700:0:000003] [] perf_event_open failed with: No such file or directory
[Tue Oct 10 19:31:28 2017] [hphp] [752:7fa197bff700:2:000001] [] Finished singleJitRequest 1
[Tue Oct 10 19:31:50 2017] [hphp] [752:7fa18bbff700:1:000001] [] Finished singleJitRequest 2
[Tue Oct 10 19:32:36 2017] [hphp] [752:7fa190bff700:2:000001] [] Finished singleJitRequest 3
[Tue Oct 10 19:32:52 2017] [hphp] [752:7fa197bff700:3:000001] [] Finished singleJitRequest 4
lll[Tue Oct 10 19:33:34 2017] [hphp] [916:7fe80ebff700:0:000001] [] perf_event_open failed with: No such file or directory
[Tue Oct 10 19:33:34 2017] [hphp] [916:7fe80ebff700:0:000002] [] perf_event_open failed with: No such file or directory
[Tue Oct 10 19:33:34 2017] [hphp] [916:7fe80ebff700:0:000003] [] perf_event_open failed with: No such file or directory
[Tue Oct 10 19:33:34 2017] [hphp] [916:7fe80a3ff700:0:000001] [] perf_event_open failed with: No such file or directory
```
I'm also curious what file or dir hhvm does not find. Unfortunately it's kept as secret for now, all the sock, pid etc files are in place.

**Comment by fredemmott** [comment]
> Do you mean I give the code line with the error ?

No: create a short example that I can execute by itself (i.e. without wordpress or any other dependencies) that shows the problem.

So far, there's not enough information to be sure, but this is sounding a lot like #8011 - same distribution versions, same "doesn't crash in debug builds" behavior, and the first few points of the stack trace are the same addresses (though given we can't get the problem with a debug build, we're not entirely sure that that is actually pointing at the problem rather than being something generic)

> hhvm-dbg does not segfault, it times out and site is slow.

Yep, the -dbg packages are *much* slower. It may work anyway if you increase the timeouts - though this isn't a viable approach for production, but could get us a detailed enough backtrace to get us more confidence in the cause.

The `perf_event_open()` things can be ignored, and there isn't actually a file: "No such file or directory" is the generic message for ENOENT, but here it means that your kernel doesn't support the performance counters that we're trying to collect (http://man7.org/linux/man-pages/man2/perf_event_open.2.html) - it's just a warning, not a major issue.

**Comment by PlayYou** [comment]
So, after increase the timeouts, the web site is very slow but can be accessible (wordpress).

**Comment by fredemmott** [comment]
So, no errors in debug build, just really slow? Sounding more and more like #8011; if you're not able to reduce the code around the error to a small example, then yes, could you share the code from the top two frames of the stack? Thanks.

**Comment by RC-Thoughts** [comment]
Same here. This means (I assume?) that hhvm-dbg works but hhvm does not. 

Looking at [issue8011](https://github.com/facebook/hhvm/issues/8011) and making the test's with the php-examples it does behave the same except that php-examples do work in hhvm-dbg but not in hhvm so traces are simpler.

**Comment by RC-Thoughts** [comment]
Here:
```
Name: /usr/bin/php
Type: Segmentation fault
Runtime: hhvm
Version: tags/HHVM-3.22.1-0-ge8ce62608d2d14e6418772b07ebaddcbdb37598f
DebuggerCount: 0

Arguments: /tmp/test.php
ThreadType: CLI

# 0  0000000000e45da6
# 1  000000000122e153
# 2  00007f6c60763890
# 3  00000000012b0180
# 4  000000000367a3a0
# 5  00000000054003ef
# 6  000000000540056b
# 7  000000000540031e
# 8  0000000003696104
# 9  0000000003695e9a
# 10 0000000003696626
# 11 0000000003694f4f
# 12 00000000037b19f1
# 13 00000000037b1821
# 14 00000000037b15e1
# 15 00000000013bb5c4
# 16 00000000013bbe85
# 17 00000000013d1297
# 18 00000000013d3145
# 19 00000000013a7bd0
# 20 0000000000a2036f
# 21 00007f6c5a8dab45
# 22 0000000000a1bd29
PHP Stacktrace:

#0  var_dump() called at [/tmp/test.php:15]
```

Looks very similar to 8011 to me.

**Comment by fredemmott** [comment]
Are there calls to array_unique on strings around the code that's triggering the problem for you? It's not surprising that you can reproduce the problem from 8011, but that doesn't mean that it's what's actually crashing HHVM on your sites.

**Comment by PlayYou** [comment]
I did it and I got this : 

```
root@playyou.be:~# hhvm test.php
array(1) {
  [0]=>
  string(8) "/tmp/bar"
}

```

**Comment by RC-Thoughts** [comment]
Here's a trace from WP causing segfault:

```
ThreadType: Web Request
Server_SERVER_NAME: www.rc-thoughts.com
Server: www.rc-thoughts.com
URL: /setup-related/

# 0  0000000000e45da6
# 1  000000000122e153
# 2  00007f381ccc4890
# 3  00000000012b01c9
# 4  000000000367aa0a
# 5  000000000140adfa
# 6  00000000018d34ec
# 7  000000000191433e
# 8  00000000036965ed
# 9  0000000003694f4f
# 10 00000000037b19f1
# 11 00000000037b1821
# 12 00000000037b15e1
# 13 00000000013bb5c4
# 14 000000000379fbf7
# 15 0000000003796d97
# 16 00000000016d320f
# 17 00000000016d3def
# 18 0000000000e0adb7
# 19 000000000124d355
# 20 00007f381ccbd064
# 19 000000000124d355
# 20 00007f381ccbd064
# 21 00007f3816f0262d

PHP Stacktrace:

#0  W3TC\ObjectCache_WpObjectCache_Regular->add_global_groups() called at [/var/www/blog/wp-content/plugins/w3-total-cache/ObjectCache_WpObjectCache.php:130]
#1  W3TC\ObjectCache_WpObjectCache->add_global_groups() called at [/var/www/blog/wp-content/object-cache.php:144]
#2  wp_cache_add_global_groups() called at [/var/www/blog/wp-includes/load.php:518]
#3  wp_start_object_cache() called at [/var/www/blog/wp-settings.php:113]
#4  include() called at [/var/www/blog/wp-config.php:94]
#5  include() called at [/var/www/blog/wp-load.php:37]
#6  include() called at [/var/www/blog/wp-blog-header.php:13]
#7  include() called at [/var/www/blog/index.php:17]
```

**Comment by RC-Thoughts** [comment]
My limited webskills are hinting this is getting closer to 8011 at least for my part. The lines for causing this are array-related:

```
        /**
         * Add global groups
         *
         * @param array   $groups
         * @return void
         */
        function add_global_groups( $groups ) {
                if ( !is_array( $groups ) )
                        $groups = array( $groups );

                foreach ( $groups as $group ) {
                        $cache = $this->_get_engine( $group );
                        $cache->add_global_groups( array( $group ) );
                }
        }
```
The line mentioned in trace is 3rd from down:
`$cache->add_global_groups( array( $group ) );`

**Comment by fredemmott** [comment]
Are you using ObjectCache_WpObjectCache_Regular ? https://github.com/crowdfavorite-mirrors/wp-w3-total-cache/blob/f14fa4fe8c908109c44939d5e27360fe7ae7b01d/ObjectCache_WpObjectCache_Regular.php#L359 would explain this

**Comment by PlayYou** [comment]
So, for me, how can I get the segfault error to fix the problem ? Cause with the -dbg, the web site is very slow and show rarely a 504 timed out.

**Comment by RC-Thoughts** [comment]
Ok. Confirmed here. I disabled object-cache and looked for more info, it's always the array_unique causing the segfault. So my case is the same as [#8011](https://github.com/facebook/hhvm/issues/8011);

**Comment by fredemmott** [comment]
@PlayYou: As we can't get a meaningful backtrace for this, try to create a minimal PHP or Hack script that crashes HHVM, using your site/wordpress as a starting point, then copying/deleting code until you have a small test case with no dependencies.

Without that, there's nothing else we can practically do to investigate, so we'll have to assume that you've also got the same issue as #8011

**Comment by PlayYou** [comment]
I don't know PHP or Hack script so I'm stuck right now and I don't know what to do.

**Comment by RC-Thoughts** [comment]
First MAKE A BACKUP of files inside `/etc/hhvm` !

look inside your  `/var/cache/apt/archives/` for `hhvm_3.21.3` package, mine was named as `hhvm_3.21.3~jessie_amd64.deb` 

You need either root or sudo to these:

- Do a `apt remove hhvm` to remove current hhvm-version. 
- Then install the working 3.21.3 with `dpkg -i /var/cache/apt/archives/hhvm_3.21.3~jessie_amd64.deb`,
- Restart your web-server with `systemctl restart apache2.service` or `systemctl restart nginx.service` or what you might have.
- You are now on hhvm 3.21.3 and everything should be ok again
- Don't update hhvm (apt upgrade for example) in mistake before issue 8011 is fixed somehow.

**Comment by PlayYou** [comment]
I don't have any hhvm_3.21.3

**Comment by RC-Thoughts** [comment]
Then my suggestion is to first remove the current hhvm-installation, then move to lts-version of hhvm. Hints are [here](https://docs.hhvm.com/hhvm/installation/linux). Again, save your config-files from `/etc/hhvm`.

While trying to resolve my issue I tried the LTS, 3,18 worked fine.

**Comment by fredemmott** [comment]
Closing this then: for @rc-thoughts, it's #8011, and I think we have to assume it's the case for @PlayYou too.

**Comment by PlayYou** [comment]
I found the hhvm_3.21.3~jessie_amd64.deb on the end page of this link : 

http://dl.hhvm.com/debian/pool/main/h/hhvm/

It's the official web site and all work perfectly ;)
