### ISSUE TITLE
Null-safe operator for arrays/shapes

### ISSUE THREAD

**Issue by vlechemin** [facebook/hhvm#8016]
Version 3.21

Is it possible to add it as well for arrays and shapes? `$array?['field']?['subfield']`
The operator `??` seems to work with `$array['field']['subfield'] ?? null` but the type checker is not happy with it: 
> You are trying to access an element of this container but the container could be null.  (Typing[4063])

Both solutions would be great, but for now it's very verbose to replace `isset`, thanks!

**Comment by fredemmott** [comment]
This is supported in 3.22; sorry, but we don't plan on backporting it as it's tied to some not-entirely-BC changes.
