### ISSUE TITLE
502 Bad Gateway HHVM

### ISSUE THREAD

**Issue by kenygamer** [facebook/hhvm#8030]
### HHVM Version
(From source)
HipHop VM 3.11.1 (rel)
Compiler: 3.11.1+dfsg-1ubuntu1
Repo schema: 2f678922fc70b326c82e56bedc2fc106c2faca61

### Standalone code, or other way to reproduce the problem
I have rebooted the server, try to do `service hhvm restart` or `systemctl restart hhvm` returns the actual result (when navigating to https://website.net or https://website.net/index.php)
### Expected result
Remove the 502 bad gateway error and display the index.php code to the visitor.
### Actual result
Returns 502 bad gateway, however command `php -v` returns Hiphop etc.... PHP-FPM is **not** installed.

Output `service hhvm status`
```sh
● hhvm.service - HHVM PHP/Hack runtime
   Loaded: loaded (/lib/systemd/system/hhvm.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2017-10-21 11:59:31 EDT; 3min 1s ago
 Main PID: 13802 (hhvm)
   CGroup: /system.slice/hhvm.service
           └─13802 /usr/bin/hhvm --mode server --config /etc/hhvm/php.ini --config /etc/hhvm/server.ini -v PidFil

Oct 21 11:59:31 server2 systemd[1]: Started HHVM PHP/Hack runtime.
lines 1-8/8 (END)
```

### Nginx Config file
```conf
	# Force SSL
	server {
	listen         80;
    	server_name    www.website.net website.net;
    	return         301 https://website.net$request_uri;
	}

	# Open Server
    	server {
	listen      443 ssl http2;
    	server_name www.website.net website.net;
    	access_log off;
	error_log off;
	root /home/web/rlands.net;

	# Headers
    	add_header X-Frame-Options SAMEORIGIN;
    	add_header X-Content-Type-Options nosniff;
    	add_header X-XSS-Protection "1; mode=block";
    	add_header Strict-Transport-Security 'max-age=31536000; includeSubDomains; preload';

	# SSL
    	ssl on;
    	ssl_certificate /etc/letsencrypt/live/www.website.net/fullchain.pem;
    	ssl_certificate_key /etc/letsencrypt/live/www.website.net/privkey.pem;
    	ssl_trusted_certificate /etc/letsencrypt/live/www.website.net/fullchain.pem;
    	ssl_stapling on;
    	ssl_stapling_verify on;
    	ssl_session_cache shared:SSL:50m;
    	ssl_session_timeout 10m;
    	ssl_prefer_server_ciphers on;
    	ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
	ssl_ciphers 'TLS13-CHACHA20-POLY1305-SHA256:TLS13-AES-256-GCM-SHA384:TLS13-AES-128-GCM-SHA256:EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';
	resolver 8.8.8.8 8.8.4.4;

	# PageSpeed
	pagespeed on;
	pagespeed DisableFilters lazyload_images;

    	# Let's Encrypt
    	location ~ /.well-known {
    	allow all;
    	}
	    
	# Index
	location / {
    	index index.html index.htm index.php;
	}

	# Cache
    	location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
    	log_not_found     off;
    	expires 1y;
    	}

	# HHVM
	include /etc/nginx/hhvm.conf;

	}
	# Close Server
```

### /etc/nginx/hhvm.conf included in the previous Nginx conf
```conf
location ~ \.(hh|php)$ {
    fastcgi_keep_conn on;
    fastcgi_pass unix:/run/hhvm/hhvm.sock;
    fastcgi_index  index.php;
    fastcgi_buffer_size 128k;
    fastcgi_buffers 256 16k;
    fastcgi_busy_buffers_size 256k;
    fastcgi_temp_file_write_size 256k;
    fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
    include        fastcgi_params;
}
```

Thanks for your answers.

**Comment by fredemmott** [comment]
Is HHVM crashing? Are there any errors in the HHVM logs?

**Comment by kenygamer** [comment]
@fredemmott No, the issue was that socket mode for HHVM isn't working. I tried switching to port 9000 (FastCGI) and it worked. I had spent a lot in finding a solution.

May I ask, when are you going to fix the broken sockets? They're completely unusable and I'm not the only one.

**Comment by fredemmott** [comment]
Can you link to an issue describing the problem with sockets?

**Comment by kenygamer** [comment]
@fredemmott The issue is that simply sockets are not working and broken. HHVM is up and running, no error logs but you get a *502 Bad Gateway* server error.

**Comment by fredemmott** [comment]
Do you have the same problem with recent versions of HHVM? 3.11 is *extremely* old and unsupported. This also doesn't look it's from one of our packages.

**Comment by kenygamer** [comment]
@fredemmontt How do I upgrade?

**Comment by fredemmott** [comment]
Use the apt repositories accessible from here: https://docs.hhvm.com/hhvm/installation/introduction

These may not be a drop-in replacement for the packages you're currently using - for example, we don't include systemd configuration.

I'm guessing these are from the default Xenial sources? We weren't aware that HHVM was packaged in Ubuntu until today; as Ubuntu's support lifecycles don't match our own, you might also have some luck reporting issues to the ubuntu package maintainers.

The HHVM project supports:
 - the latest stable release of HHVM
 - every third release of HHVM for 1 year; you can see the supported versions at https://docs.hhvm.com/hhvm/installation/introduction#prebuilt-packages__lts-releases

Closing as this issue is currently for an unsupported release.

**Comment by kenygamer** [comment]
@fredemmott Somehow, I have found out how to deal with it. Thanks anyway.
