### ISSUE TITLE
hhvm+proxygen: assertion failure

### ISSUE THREAD

**Issue by genych** [facebook/hhvm#8037]
tags/HHVM-3.21.3-0-gce34e5458e6a75931438a2d8fc41b91454a2f2b2

```
Assertion Failure: /opt/hhvm/hphp/runtime/vm/jit/refcount-opts.cpp:2793: void HPHP::jit::{anonymous}::do_clean_graph(HPHP::jit::{anonymo
us}::Env&, HPHP::jit::queue<std::pair<HPHP::jit::{anonymous}::Node*, HPHP::jit::{anonymous}::Node*> >&, HPHP::jit::hash_set<HPHP::jit::{
anonymous}::Node*>&, bool&, HPHP::jit::{anonymous}::Node*, HPHP::jit::{anonymous}::Node*): assertion `0' failed.
```

Not easily reproducible, very project-specific tests related to #8029 (now with proxygen)

Do you need more info? I have an obscure stacktrace.log of this event and perf.maps

Looks very similar to #5329

**Comment by genych** [comment]
Also, sometimes two processes of hhvm -m server -p 8080 -d hhvm.jit=false just hangs with 100% cpu usage

**Comment by fredemmott** [comment]
Sorry for the slow reply:

 - can you reproduce this on 3.23?
 -can you get a backtrace? install the `hhvm-dbg` package, then after triggering it in gdb, `thread apply all bt`
 - same applies for without jit - that almost certainly won't be the same issue. You can attach gdb to HHVm while it's running (with `gdb -p`), and again `thread apply all bt`
