### ISSUE TITLE
Segmentation fault in 3.22.1

### ISSUE THREAD

**Issue by ocasta** [facebook/hhvm#8040]
Has happened a number of times but we have not been able to identify the exact circumstance

### HHVM Version
3.22.1

### Standalone code, or other way to reproduce the problem
Not identified

### Expected result
Normal operation

### Actual 
Following log messages:

> Scheduling
> the retranslation of all profiled translations
> retranslateAll: starting to build the call graph
> retranslateAll: finished building the call graph
> Assertion failure: /tmp/tmp.HMafscw8rE/hphp/runtime/vm/jit/frame-state.cpp:1419: HPHP::jit::irgen::StackState& HPHP::jit::irgen::FrameStateMgr::stackState(HPHP::jit::FPInvOffset): 
> assertion idx >= 0 failed.
stack idx went negative: irSPOff: 13, fpRel: 0
> -----------------------------------RegionDesc-----------------------------------
> Region (1 blocks):
> Block 35192 Walker::display_element@141 length 3 initSpOff 13 profTransID 35192
>  predict: Local{1} :: BoxedArr
>  predict: Local{5} :: BoxedStr
>  141 NewVecArray 40
>  146 Gt
>  147 IsUninit
>  changed postcondition: MBase{} :: Gen
> digraph RegionCFG {
> node[shape=box,style=filled]
> \"B35192\" [label=\"B 35192\\np: 4\",fillcolor=\"#ff0000\"]
> }

stacktrace

> Host: cabc92c368b6
> ProcessID: 15
> ThreadID: 140661290432256
> ThreadPID: 38
> Name: unknown program
> Type: Segmentation fault
> Runtime: hhvm
> Version: tags/HHVM-3.22.1-0-ge8ce62608d2d14e6418772b07ebaddcbdb37598f
> DebuggerCount: 0

> Assertion Message: stack idx went negative: irSPOff: 13, fpRel: 0

> -----------------------------------RegionDesc-----------------------------------
> : Region (1 blocks):
> Block 35192 Walker::display_element@141 length 3 initSpOff 13 profTransID 35192
>  predict: Local{1} :: BoxedArr
>  predict: Local{5} :: BoxedStr
>    141  NewVecArray 40
>   146  Gt
>    147  IsUninit
>  changed postcondition: MBase{} :: Gen

> digraph RegionCFG {
> node[shape=box,style=filled]
> "B35192" [label="B 35192\np: 4",fillcolor="#ff0000"]
>}

>Assertion Failure: /tmp/tmp.HMafscw8rE/hphp/runtime/vm/jit/frame-state.cpp:1419:
> HPHP::jit::irgen::StackState& HPHP::jit::irgen::FrameStateMgr::stackState(HPHP:
> :jit::FPInvOffset): assertion `idx >= 0' failed.

> #0  0000000000dd20d6
> #1  00000000011cb452
> #2  00007fee7f5c1390
> #3  00000000016b4760
> #4  0000000001b7a593
> #5  0000000001b7f4e0
> #6  0000000001b809a6
> #7  0000000001b8156c
> #8  0000000001d897cc
> #9  0000000000dde277
> #10 0000000000de0b2a
> #11 0000000001b9e109
> #12 0000000002428516
> #13 00000000024271d5
> #14 0000000002427543
> #15 0000000001c80acb
> #16 0000000001f44acc
> #17 0000000001eee14e
> #18 0000000001d96a79
> #19 0000000001d9935f
> #20 0000000002378ec7
> #21 0000000002379e6d
> #22 00000000023805ea
> #23 0000000000e016e3
> #24 00000000013a6164
> #25 00007fee7f5b76ba
> #26 00007fee78c023dd

PHP Stacktrace:

**Comment by fredemmott** [comment]
Sorry - can you:
 - confirm you still have this issue on 3.23
 - reproduce with the hhvm-dbg package also installed, and get a backtrace from gdb

**Comment by fredemmott** [comment]
This issue has been waiting for more info for more than 2 weeks. I'm closing it for now, but feel free to re-open it if you can provide more info. https://github.com/facebook/hhvm/wiki/Human-Timeouts
