### ISSUE TITLE
Implementing the IndexAccess interface generates a fatal error for the 'set' function

### ISSUE THREAD

**Issue by stevenramirezgames** [facebook/hhvm#8042]
### HHVM Version
HipHop VM 3.18.3-dev (rel)
Compiler: heads/HHVM-3.18-0-g59962ae2d65dd4f43379f9a16d0f97ce7d035f3c
Repo schema: aae5f369a1bccb00ec321aa269a15aeef001482c

### Standalone code, or other way to reproduce the problem
Hello there,

So on our team, we are working on writing some collections that have auto serialization/deserialization. Right now we have a vector that implements IndexAccess and it generates a fatal error at runtime. Here is the code (parts cut out for brevity)

    interface StorableVectorInterface<Tv >
      extends StorableObjectInterface, Collection<Tv>, IndexAccess<int, Tv> {}

    class StorableVector<Tv as TypeInterface> implements StorableVectorInterface<Tv> {
       private Vector $vector;

      // constructors and other methods...

      public function set(int $k, Tv $v): this {
        $this->vector->set($k, $v);
        return $this;
      }
    }

The above generates this error:

"Fatal error: Declaration of StorableVector::set() must be compatible with that of IndexAccess::set() in <file path here>"

I looked at the declaration for "Vector" to see what was different and other than the return type, they are basically the same. I tried removing the constraint and that still generates the error. Any thoughts to this issue? Thanks!
### Expected result
Generic declaration shouldn't cause a runtime exception.

### Actual result
"Fatal error: Declaration of StorableVector::set() must be compatible with that of IndexAccess::set() in <file path here>"

**Comment by fredemmott** [comment]
Yep, this isn't supported.

The specific problem you're hitting now is that the typechecker and the runtime disagree on the types of the parameters, so you can't make both happy.
