### ISSUE TITLE
hhi file for pgsql extension not bundled

### ISSUE THREAD

**Issue by aloiret** [facebook/hhvm#8044]
Hello,

### HHVM Version

HipHop VM 3.22.1 (rel)
Compiler: tags/HHVM-3.22.1-0-ge8ce62608d2d14e6418772b07ebaddcbdb37598f
Repo schema: 05fc45ee8e70c9f18dfb1e867219c8528be87996

### Standalone code, or other way to reproduce the problem

$ cat test.hh 
```php
<?hh // strict

function test (): void {
    $connection = \pg_connect ('...');
}
```
$ hh_client .
test.hh:4:19,29: Unbound name: pg_connect (a global function) (Naming[2049])
test.hh:4:19,29: Unbound name: pg_connect (a global constant) (Naming[2049])
test.hh:4:19,29: Unbound name (typing): pg_connect (Typing[4107])

### Expected result

No typing error and hhi file bundled:

$ grep -R pg_connect /tmp/hh_server/hhi_*

### Actual result

Using the pgsql extension requires to create an in-project hhi file with declarations of used functions, based on the ext_pgsql.php file from hphp/runtime/ext/pgsql.

Thanks a lot for your terrific work on HHVM.

**Comment by fredemmott** [comment]
cc @simonwelsh  :)

**Comment by juanfernandoe** [comment]
+1
