### ISSUE TITLE
Does Zend Extension Source Compatibility Layer work with c

### ISSUE THREAD

**Issue by TeBoring** [facebook/hhvm#8045]
Can I use header files in Zend Extension Source Compatibility Layer to write extension in c?

**Comment by fredemmott** [comment]
Yes, however I strongly recommend not using it:
 - it's based on the PHP5 API, and we're dropping support for PHP5 very soon
 - we are likely to drop it entirely in the future as part of https://hhvm.com/blog/2017/09/18/the-future-of-hhvm.html

**Comment by TeBoring** [comment]
Thanks for the info.
Right now, I have an php c extension (work on both php5 and php7). What's your recommendation to make it work with hhvm? (prefer reuse existing code)

**Comment by fredemmott** [comment]
Honestly, that's unlikely to be a practical approach as HHVM and PHP continue to diverge.

**Comment by TeBoring** [comment]
If I write a normal hhvm extension from scratch, can I write in c? Or cpp is required?

**Comment by TeBoring** [comment]
If it's much harder to write c extension than cpp extension, I'll also choose cpp. (e.g., is there standard collection like hashmap provided in c?)
