### ISSUE TITLE
file_get_contents() doubles stream context http headers

### ISSUE THREAD

**Issue by pondermatic** [facebook/hhvm#8046]
### HHVM Version
```
HipHop VM 3.22.1 (rel)
Compiler: tags/HHVM-3.22.1-0-ge8ce62608d2d14e6418772b07ebaddcbdb37598f
Repo schema: 05fc45ee8e70c9f18dfb1e867219c8528be87996
```
### Standalone code, or other way to reproduce the problem
```php
<?php
# client side
$context = stream_context_create(['http' => ['header' => 'X-TEST-STRING-1: value1']]);
echo file_get_contents('http://YOUR_SERVER_HOST/return_request_headers.php', null, $context);
```
```php
<?php
# return_request_headers.php
foreach($_SERVER as $key => $value) {
    if (substr($key, 0, 5) == 'HTTP_') {
        $key = str_replace('_', '-', substr($key, 5));
        echo "$key: $value\r\n";
    }
}
```
### Expected result
```
HOST: YOUR_SERVER_HOST
ACCEPT: */*
X-TEST-STRING-1: value1
```
### Actual result
```
HOST: YOUR_SERVER_HOST
ACCEPT: */*
X-TEST-STRING-1: value1, value1
```

This issue first appeared in commit eec9da9, between HHVM releases 3.14.5 and 3.15.0.

**Comment by pondermatic** [comment]
Looking at the raw TCP dump with ```sudo tcpdump -A -n -s 2024 dst port 80``` shows:
```
Host: YOUR_SERVER_HOST
Accept: */*
X-TEST-STRING-1:  value1
X-TEST-STRING-1: value1
```

This issue is related to issue #5553.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Using fgc() on urls is a phpism. Hhvm strongly encourages using curl instead. Fixing fgc is not likely going to happen. PHP code is unsupported, so we don't have to consider all the php code using fgc() anymore.
