### ISSUE TITLE
segmentation fault if ssl enabled but ssl_certificate_file and ssl_certificate_key_file not specified

### ISSUE THREAD

**Issue by jsthind** [facebook/hhvm#8061]
### HHVM Version
3.21.3 on Debian 8 64bit

### Standalone code, or other way to reproduce the problem
Trying to enable LetsEncrypt SSL in hhvm. I tried out the following three options:

**Test 1**
_SSL generated automatically from SSH via certbot_

hhvm.server.enable_ssl = true
hhvm.server.ssl_port = 443
hhvm.server.ssl_certificate_file = /home/user1/hhvm/example1.com/cert.pem
hhvm.server.ssl.certificate_key_file = /home/user1/hhvm/example1.com/privkey.pem
hhvm.server.ssl_certificate_dir = /home/user1/hhvm/example1.com

**Test 2**
_SSL generated automatically from SSH via certbot_

hhvm.server.enable_ssl = true
hhvm.server.ssl_port = 443
hhvm.server.ssl_certificate_file = /home/user1/hhvm/example1.com/fullchain.pem
hhvm.server.ssl.certificate_key_file = /home/user1/hhvm/example1.com/privkey.pem
hhvm.server.ssl_certificate_dir = /home/user1/hhvm/example1.com

**Test 3**
_SSL generated and downloaded manually from https://www.sslforfree.com_

hhvm.server.enable_ssl = true
hhvm.server.ssl_port = 443
hhvm.server.ssl_certificate_file = /home/user1/hhvm/example1.com/certificate.crt
hhvm.server.ssl.certificate_key_file = /home/user1/hhvm/example1.com/private.key
hhvm.server.ssl_certificate_dir = /home/user1/hhvm/example1.com

### Expected result
HHVM up and running with SSL enabled

### Actual result
Invalid certificate file or key file
Core dumped: Segmentation fault
Stack trace in /tmp/stacktrace.13127.log

**Comment by fredemmott** [comment]
You are specifying:

```
hhvm.server.ssl.certificate_key_file = /home/user1/hhvm/example1.com/private.key
```

This needs to be:

```
hhvm.server.ssl_certificate_key_file = /home/user1/hhvm/example1.com/private.key
```

If I don't specify both, I can reproduce the error, and the error message you provided appears to only happen with no trailing punctuation if not fully configured. That said, we really shouldn't segfault when misconfigured.

**Comment by fredemmott** [comment]
oh yay, and we sigabort if the ssl port is not bindable.

```
$ hhvm -m server -d hhvm.server.enable_ssl=true -p 8080
Invalid certificate file or key file
Uncaught exception: 13failed to bind to async server socket: [::]:443: Permission denied
Core dumped: Abort trap: 6
Stack trace in /tmp/stacktrace.79094.log
Abort trap: 6
$ hhvm -m server -d hhvm.server.enable_ssl=true -d hhvm.server.ssl_port=8443 -p 8080
Invalid certificate file or key file
Core dumped: Segmentation fault: 11
Stack trace in /tmp/stacktrace.79122.log
Segmentation fault: 11
```

**Comment by fredemmott** [comment]
https://github.com/facebook/wangle/commit/ab7a6f191c1150fb4aa95f325023b88ae4201850#diff-4b2301cbccffd1cdf60ff6feddd327b0 appears to fix the segfault, trying backporting.

**Comment by fredemmott** [comment]
Documentation and crashes fixed.
