### ISSUE TITLE
XDebug enabling issue with php scalar type hint

### ISSUE THREAD

**Issue by neilmatillano** [facebook/hhvm#8069]
### HHVM Version
3.21.0 rel

### Standalone code, or other way to reproduce the problem
When adding xdebug.enable=1 inside php.ini and rebuilding.
Should xdebug supposed to work with php scalar type hint?

### Expected result
running "composer install" should not yield any error

### Actual result
[ErrorException]
Value returned from method Symfony\Flex\Flex::getFlexId() must be of type ?Symfony\Flex\string, string given ( using a symfony/flex fork -- https://github.com/MakeMeReach/flex )

**Comment by fredemmott** [comment]
Do you have `hhvm.php7.all=1` in your configuration file? Does this problem not happen if you don't have xdebug enabled?

**Comment by neilmatillano** [comment]
Yes I have hhvm.php7.all => 1   but unfortunately no, the error doesnt occur if i don't add xdebug.enable.

**Comment by neilmatillano** [comment]
@fredemmott  : I am still stucked with this issue on enabling xdebug. Is there a possible workaround on this issue?

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Support for XDebug was removed in hhvm [3.27.0](https://hhvm.com/blog/2018/06/18/hhvm-3.27.0.html).
