### ISSUE TITLE
Log Directory Missing on 3.23.1

### ISSUE THREAD

**Issue by justinwray** [facebook/hhvm#8072]
**HHVM Version**: 3.23.1

During installation the HHVM log directory (`/var/log/hhvm`) is not created.  This log location is the default location and is included in the configuration provided by the HHVM package.

Manually creating the directories and setting appropriate permissions resolves the issue as a workaround.

**Comment by justinwray** [comment]
Tagging: @fredemmott @stevcoll @gsingh93

**Comment by fredemmott** [comment]
Can you re-file this over at https://github.com/hhvm/packaging please? :)

**Comment by justinwray** [comment]
Certainly!

**Comment by justinwray** [comment]
Submitted as https://github.com/hhvm/packaging/issues/159 and closed here.
