### ISSUE TITLE
HHVM service status active (exited)

### ISSUE THREAD

**Issue by ManuelRighi** [facebook/hhvm#8075]
### HHVM Version
3.23.2-1~xenial

I have Ubuntu Server 16.04.3 LTS.
After I have upgraded from HHVM 3.22.1~xenial to 3.23.2-1~xenial, command "service hhvm status" show me "Active: active (exited)" intead of "Active: active (running)".

Complete output of service hhvm status is this:

hhvm.service - LSB: Starts The HHVM FastCGI Daemon
   Loaded: loaded (/etc/init.d/hhvm; bad; vendor preset: enabled)
   Active: active (exited) since Fri 2017-12-15 16:58:28 CET; 9min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 4926 ExecStop=/etc/init.d/hhvm stop (code=exited, status=0/SUCCESS)
  Process: 4937 ExecStart=/etc/init.d/hhvm start (code=exited, status=0/SUCCESS)
    Tasks: 0
   Memory: 0B
      CPU: 0

Dec 15 16:58:28 cls5-pweb1 systemd[1]: Starting LSB: Starts The HHVM FastCGI Daemon...
Dec 15 16:58:28 cls5-pweb1 systemd[1]: Started LSB: Starts The HHVM FastCGI Daemon.

**Comment by fredemmott** [comment]
Probably https://github.com/hhvm/packaging/issues/159 - otherwise it needs filing there anyway. I'll take a look at that issue later today.
