### ISSUE TITLE
HHVM from 2.22.2 to 2.23.1-2 brings bad gatway 502 and purge DIRs

### ISSUE THREAD

**Issue by ekn33** [facebook/hhvm#8079]
### HHVM Version
2.23.1-2 want to update from 2.22.1 to latest i mean it is 2.23.1-2

### Operating System and Version
ubuntu 16.04, nginx, hhvm

### Standalone code, or other way to reproduce the problem
after update server gives a bad gatway 502 back
### Expected result
if i connect via ftp i see after the update /var/log/hhvm/ is gone so i make a new dir and start/stop nginx
now i have the error file and here i found just one line
Failed to initialize central HHBC repository:\n  Failed to open /var/cache/hhvm/hhvm.hhbc: 14 - unable to open database file\n  Failed to open /var/www/.hhvm.hhbc: 14 - unable to open database file\n
i look now for /var/cache/hhvm and see its gone

pid files is here and writeable
What can i do?

**Comment by fredemmott** [comment]
Make /var/cache hhvm yourself, and chown to www-data:www-data; I'll include it in the next round of packages.

If this doesn't fix it, please file an issue with the error that HHVM is giving you, not nginx.

**Comment by ekn33** [comment]
thanks
