### ISSUE TITLE
Hack: error with `self` as a return type in namespaced code

### ISSUE THREAD

**Issue by morrisonlevi** [facebook/hhvm#8081]
### HHVM Version

    $ hhvm --version
    HipHop VM 3.23.2 (rel)
    Compiler: 1511206899_294537079
    Repo schema: 57a6d72ee7a93fe666bcfd7e75d7e2e160e38911

### Operating System and Version

Ubuntu 17.04 (Zesty Zapus)

### Standalone code, or other way to reproduce the problem

```php
<?hh

namespace MyNS {
	class Foo {
		public function(): self {
			return $this;
		}
	}
}
```

### Expected result

No error.

### Actual result

```
tmp.php:6:11,15: Invalid return type (Typing[4110])
  tmp.php:5:22,25: This is an object of type MyNS\self
  tmp.php:6:11,15: It is incompatible with an object of type MyNS\Foo
```

**Comment by simonwelsh** [comment]
You probably want the return type of `this`, not `self`.

**Comment by fredemmott** [comment]
Yep.

**Comment by morrisonlevi** [comment]
@fredemmott @simonwelsh No, I don't want `this`. This comes up in code that's been transferred from PHP 7. It's a real defect that doesn't ever seem to happen in non-namespaced code.
