### ISSUE TITLE
Declared Property Handler in extension

### ISSUE THREAD

**Issue by TeBoring** [facebook/hhvm#8082]
In php, one can change the default property handlers for declared property. Can I do the same in hhvm? (I note there is native property handler, but it works for __set/__get and not for declared property)

**Comment by TeBoring** [comment]
ping?

**Comment by TeBoring** [comment]
ping again?

**Comment by TeBoring** [comment]
hi

**Comment by fredemmott** [comment]
I'm not familiar with how this works, but if you grep hphp/runtime/ext/ for Native:::Prop you'll find a small number of examples. For future (and followups), you'll have a better experience on https://www.facebook.com/groups/hhvm.dev/ or #hhvm-dev on irc.freenode.net
