### ISSUE TITLE
yaml.decode_php ini setting is not supported

### ISSUE THREAD

**Issue by Nikerabbit** [facebook/hhvm#8085]
### HHVM Version
HipHop VM 3.23.2 (rel)
Compiler: 1511206599_661801426

### Operating System and Version
Ubuntu 16.04.3 LTS

### Standalone code, or other way to reproduce the problem
Requires hhvm.enable_zend_compat = true
```
$dangerous = 'a: !php/object "O:8:\"stdClass\":1:{s:1:\"a\";s:1:\"b\";}"';
ini_set( 'yaml.decode_php', false );
var_dump( yaml_parse( $dangerous ) );
```

### Expected result
```
array(1) {
  'a' =>
  string(35) "O:8:"stdClass":1:{s:1:"a";s:1:"b";}"
}
```

### Actual result
```
array(1) {
  ["a"]=>
  object(stdClass)#422 (1) {
    ["a"]=>
    string(1) "b"
  }
}
```

### See also
It seems it defaults to disabled now in PHP https://github.com/php/pecl-file_formats-yaml/pull/18

**Comment by fredemmott** [comment]
Sorry, I'm going to close this: today is the last working day before we drop support for PHP5, including the entirety of EZC - the branch cut for 3.24 is due on 1/1.

Threading through ini_set support to EZC is too risky a change to do at this point in time - especially as we should be more conservative about what going into 3.24, as the last PHP5-compatible release.
