### ISSUE TITLE
oss-performance test suite Mediawiki fails all transactions

### ISSUE THREAD

**Issue by jim-saxman** [facebook/hhvm#8088]
### HHVM Version
Since this commit:
commit aeacd50432c7031143eb7f30534e0e8a8dbd8288
Author: Mark Williams <mwilliams@fb.com>
Date:   Thu Oct 19 09:40:38 2017 -0700

    Better method resolution

### Operating System and Version
CentOS 7 on both ARMv8 and x64

### Standalone code, or other way to reproduce the problem
~/oss-performance$ hhvm perf.php --mediawiki --hhvm=/home/jsaxman/hhvm/hphp/hhvm/hhvm

### Expected result
>0 Transactions per second

### Actual result
0 Transactions per second

**Comment by jim-saxman** [comment]
Mediawiki passes if the --no-repo-auth option is passed to perf.php.

**Comment by fredemmott** [comment]
this needs filing over at https://github.com/hhvm/oss-performance/issues ; also , all the targets need replacing: we're no longer targetting PHP5 in master, but all the targets are PHP5.
