### ISSUE TITLE
Generic functions with default arguments not supported?

### ISSUE THREAD

**Issue by tslettebo** [facebook/hhvm#8090]
This function gives the following error messages from the typechecker:

```
function f<T>(classname<T> $class_name = stdClass::class)
{
}

test.php:3:28,38: Wrong type hint (Typing[4110])
test.php:3:25,25: This is a value of generic type T
test.php:3:42,49: It is incompatible with an object of type stdClass
```

Is there any way to make this pass?

**Comment by fredemmott** [comment]
Sorry, not currently

**Comment by asuth** [comment]
Bumped into this today. Here's a simple repro of a related case:

```php
<<__ConsistentConstruct>>
class QModel {}
class QUser extends QModel {}

class ModelMaker {
    public static function createModel<T as QModel>(classname<T> $class = QUser::class): T {
        return new $class();
    }
}
```

**Comment by manzyuk** [comment]
I think the error is correct: the default value of a function argument must match the declared type of that argument.  In the example above, `QUser::class` is not compatible with the type `classname<T>`: `QUser::class` has the type `classname<QUser>`, and `classname<T>` is covariant in `T`, so `classname<QUser>` is a subtype of `classname<T>` iff `QUser` is a subtype of `T`, but we only know about `T` that it is a subtype of `QModel`.

Think of it this way: If we accept the above code as well-typed, then `createModel()` has the type `T` for //any// `T` that is a subtype of `QModel`.  In particular, we can pass `createModel()` to a function expecting `QOther`, where `QOther` is another class extending `QModel`:
```
class QOther extends QModel {
    public function doSomething(): void {}
}

function expectQOther(QOther $m): void {
    $m->doSomething();
}

function ouch(): void {
  expectQOther(ModelMaker::createModel());
}
```
The above code would then also be accepted by the type-checker but it's unsound: the runtime type of `ModelMaker::createModel()` is `QUser`, which doesn't have method `doSomething()`, so calling `ouch()` fails at runtime.

**Comment by asuth** [comment]
Thanks for the comment and example. I'm still struggling to understand one point though.

Take this example, which works correctly:
```php
<<__ConsistentConstruct>>
class QModel {}
class QUser extends QModel {}

class ModelMakerWithoutDefault {
    public static function createModel<T as QModel>(
        classname<T> $class
    ): T {
        return new $class();
    }
}

$a = ModelMakerWithoutDefault::createModel(QUser::class); // gives me a QUser
```

The only difference here is that the parameter is passed at the call-site, versus being passed as a default parameter. I don't understand why a default parameter couldn't be applied as the generic type but a regularly parameter can.

**Comment by manzyuk** [comment]
A default parameter of a generic function must work for all instantiations of the generic type parameters, whereas when you pass a parameter explicitly at the call site you only need to make it match the expected type for one particular instantiation of the generic type parameters.

**Comment by azjezz** [comment]
I'm currently facing the same issue : 

```hack
<<__Sealed(File::class, Folder::class)>>
abstract class Node {
  /*
   * Shared functionality between file and folder objects.
   */
}

final class File extends Node {
  ...
}

final class Folder extends Node {
  ...
  public async function read<T as Node>(
    bool $sort = false,
    bool $recursive = false,
    classname<T> $filter = Node::class,
  ): Awaitable<Container<T>> {
    if (!$this->exists()) {
      throw ...;
    }

    $contents = vec[];
    try {
      $directory = $this->path()->toString();
      $flags = FilesystemIterator::SKIP_DOTS |
        FilesystemIterator::UNIX_PATHS |
        FilesystemIterator::NEW_CURRENT_AND_KEY;

      if ($recursive) {
        $iterator = new RecursiveIteratorIterator(
          new RecursiveDirectoryIterator($directory, $flags),
          RecursiveIteratorIterator::CHILD_FIRST,
        );
      } else {
        $iterator = new FilesystemIterator($directory, $flags);
      }
    } catch (Exception $e) {
      throw ...;
    }

    $iterator->rewind();
    while ($iterator->valid()) {
      $node = $iterator->current() as SplFileInfo;
      if (
        $node->isDir() && ($filter === Node::class || $filter === Folder::class)
      ) {
        $contents[] = new Folder(Path::create($node->getPathname()));
      } elseif (
        $node->isFile() && ($filter === Node::class || $filter === File::class)
      ) {
        $contents[] = new File(Path::create($node->getPathname()));
      }

      $iterator->next();
    }

    if ($sort) {
      ...
    }

    // UNSAFE
    return $contents;
  }
}

```

the work around : 


```hack
  public async function read<T as Node>(
    bool $sort = false,
    bool $recursive = false,
    ?classname<T> $filter = null,
  ): Awaitable<Container<T>> {
    $filter ??= Node::class;
    ...
  }
```

but this introduces another issue : 

```hack
// Contaienr<Node> - fine
$nodes = await $folder->read(false, false, Node::class);
// Container<File> - fine
$files = await $folder->read(false, false, File::class);
// Container<Folder> - fine
$folders = await $folder->read(false, false, Folder::class);

// Container<[unresolved]> - not fine
// expected : Container<Node>
$nodes = await $folder->read();
```

**Comment by lexidor** [comment]
> A default parameter of a generic function must work for all instantiations of the generic type parameters, whereas when you pass a parameter explicitly at the call site you only need to make it match the expected type for one particular instantiation of the generic type parameters.

You hit the nail on the head here. The only way to make this valid is to have a `super DefaultClass` constraint on the generic.

**Comment by lexidor** [comment]
```HACK
// Container<[unresolved]> - not fine
// expected : Container<Node>
$nodes = await $folder->read();
```

Regarding the example above, type inference now assumes the upper bound `Node` rather than unresolved.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

The behavior described is correct according to the type theory. All repro cases are either invalid from  a type perspective or their broken parts are correct in hhvm 4.168.
