### ISSUE TITLE
Make HHVM run Hack faster than PHP7 runs equivalent PHP code

### ISSUE THREAD

**Issue by DemiMarie** [facebook/hhvm#8091]
It used to be that migration from PHP to HHVM (and, thus, to Hack) came with a big perf win.  It doesn’t anymore.

**Comment by fredemmott** [comment]
Closing; not enough information to be actionable.

That said, for background:
 - HHVM does not currently run Hack code that is straight ports of PHP any differently than it would run the PHP code
 - Hack code that isn't a straight port has different profiles (e.g. hack arrays, collections, use of async); we are not aiming to optimize straight ports.
 - this sounds likely to be a relatively small codebase; we make many optimization decisions that benefit large codebases but hurt small ones
