### ISSUE TITLE
Is there any way to convert an array to a shape in strict mode?

### ISSUE THREAD

**Issue by juanfernandoe** [facebook/hhvm#8093]
### HHVM Version
HipHop VM 3.23.2 (rel)
Compiler: 1511206975_379303617
Repo schema: 57a6d72ee7a93fe666bcfd7e75d7e2e160e38911

### Operating System and Version
Linux

### Standalone code, or other way to reproduce the problem
```
<?hh //strict
$x = [];
$x['code'] = 1;

type customType = shape('code'=>int);

something like that?
$y = HH\Shapes::fromArray(customType,$x); 
```

**Comment by simonwelsh** [comment]
The `matches_type_structure` function from [type-assert](https://github.com/hhvm/type-assert) will do this.

**Comment by fredemmott** [comment]
For now, yep, type-assert is the only approach. we're hoping to introduce an `is` operator in the next few months.
