### ISSUE TITLE
HHVM latency get increasing but cpu not utilizing

### ISSUE THREAD

**Issue by namjithwisilica** [facebook/hhvm#8105]
### Operating System and Version ubuntu 16.04 xenial

As we are testing our php command line batch which contain for loops processing 7000 data in array and its taking around 1 second to finish. But cpu usage is only max 6 % only. If we increase data to 14000 latency will be 2 seconds but cpu is not increasing at all. I dont have basics to understand this.So i would like to know why cpu is not utilizing?

**Comment by fredemmott** [comment]
Taking twice the time for twice the data with no change in CPU usage is usually expected; could you explain why this isn't the case for you?

As for why you're only getting 6%: how many cores does your CPU have? And can you provide a trace from `perf` ? see https://github.com/facebook/hhvm/wiki/Profiling

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones are very unlikely to be worked on.

This issue has been created some time ago and there is not enough information in this issue to reproduce this issue on a modern build of hhvm. I am closing this issue. If you are reading this and have a way to reproduce this issue in a modern hhvm version, feel free to open a new issue.
