### ISSUE TITLE
vsdebug unit tests

### ISSUE THREAD

**Issue by swalk-cavium** [facebook/hhvm#8106]
### HHVM Version

hphp/hhvm/hhvm --version
HipHop VM 3.25.0-dev (dbg)
Compiler: heads/master-0-g9661e54afd8f4d9f4f6a04c82563786b8d27426f
Repo schema: 2f2da741feffd7185b0067d6ea257e7a153b726b

### Operating System and Version

Built same commit on two different machines, both running
Ubuntu 16.04

uname -a
Linux dell 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

uname -a
Linux lab1 4.2.0 #1 SMP Wed Nov 25 14:00:54 CST 2015 aarch64 aarch64 aarch64 GNU/Linux

### Standalone code, or other way to reproduce the problem

hphp/test/run -v -m interp all 
...
hphp/test/slow/ext_vsdebug/set_variable.php FAILED (xxx)    
hphp/test/slow/ext_vsdebug/step.php FAILED (xxx)                 
hphp/test/slow/ext_vsdebug/dummy.php FAILED (xxx)            
hphp/test/slow/ext_vsdebug/exception_bp.php FAILED (xxx) 
hphp/test/slow/ext_vsdebug/context.php FAILED (xxx)           
hphp/test/slow/ext_vsdebug/initialize.php FAILED (xxx)         
hphp/test/slow/ext_vsdebug/launch.php FAILED (xxx)            
hphp/test/slow/ext_vsdebug/breakpoints.php FAILED (xxx)   
hphp/test/slow/ext_vsdebug/not_enabled.php FAILED (xxx)   

### Expected result

All pass

### Actual result

9 new failures.  See above.

Tracked to this commit
https://github.com/facebook/hhvm/commit/af974f3c4be8911561bdeed8c1587c130d40d2ac

**Comment by fredemmott** [comment]
Temporarily disabled, but hopefully back soon. cc @ebluestein

**Comment by fredemmott** [comment]
Internal diff D6771518 should fix this - not public yet.

**Comment by fredemmott** [comment]
Should be resolved by 8aed204da5b9e3b7e43bb6b31b22bbde9939f531
