### ISSUE TITLE
hackfmt -diff removing trailing new lines

### ISSUE THREAD

**Issue by simonwelsh** [facebook/hhvm#8117]
### HHVM Version

3.24.2 and master (built this morning)

### Operating System and Version

Ubuntu 16.04

### Standalone code, or other way to reproduce the problem

```
$ echo '<?hh' > test.php
$ git add -N test.php
$ git diff test.php | hackfmt --diff
```

Alternatively,

```
hackfmt --diff-dry-run <<'FILE'
diff --git a/test.php b/test.php
--- a/test.php
+++ b/test.php
@@ -0,1 +1 @@
<?hh
FILE
```

### Expected result

`test.php` still has a trailing new line

### Actual result

`test.php` no longer has a trailing new line. In this very simple case, this means that the file now has a syntax error (the opening tag has to be followed by whitespaced but it no longer is).

This appears to happen whenever the last line of the file is a changed line

`hackfmt` and `hackfmt -i` both work correctly. Only `--diff`/`--diff-dry-run` have the issue.

**Comment by fredemmott** [comment]
Internal task: t23977068

**Comment by simonwelsh** [comment]
Seems to be fixed
