### ISSUE TITLE
Add support for "parameter info" for vscode language server

### ISSUE THREAD

**Issue by mwildehahn** [facebook/hhvm#8125]
### HHVM Version
3.23+

vscode supports parameter info: https://code.visualstudio.com/docs/editor/intellisense. Autocompletion works with the `hh_client` but it doesn't show you parameter hints when you start invoking the function.

**Comment by fredemmott** [comment]
@ljw1004 : is this something you'd be interested in adding?

**Comment by fredemmott** [comment]
If I'm reading correctly, this was implemented by https://github.com/facebook/hhvm/commit/8db9d0f6796f16d04aafe21ae760bf8ea6e9b696 (with coincidental timing)

**Comment by ljw1004** [comment]
Yes, @pittsw just committed it recently.
