### ISSUE TITLE
new inout tests fail regression testing

### ISSUE THREAD

**Issue by swalk-cavium** [facebook/hhvm#8127]
### HHVM Version
/data2/swalk/play.021418a/hhvm$ hphp/hhvm/hhvm --version
HipHop VM 3.25.0-dev (dbg)
Compiler: heads/master-0-g08456ddcf8739219b281d40cb575ac2d8340cf10
Repo schema: 83ed4d3ed54d47353601eba8e29afa01fd6f110e

### Operating System and Version

Ubuntu 16.04

### Expected result

All pass

### Actual result

Build: 
Commit: 08456ddcf8739219b281d40cb575ac2d8340cf10
File | interp | interp -r | jit -a '-vEval.JitPGO=0' | jit -r -a '-vEval.JitPGO=0' | jit -a '-vEval.JitPGO=1' | jit -r -a '-vEval.JitPGO=1' | 
...
hphp/test/slow/inout/interp-callm/tests/autoloader.php | F | F | F | F | F | F | 
hphp/test/slow/inout/interp-callm/tests/bad-abstract.php | F | F | F | F | F | F | 
hphp/test/slow/inout/interp-callm/tests/bad-async-generator.php | F | F | F | F | F | F | 
hphp/test/slow/inout/interp-callm/tests/bad-async.php | F | F | F | F | F | F | 
hphp/test/slow/inout/interp-callm/tests/bad-call-1.php | F | F | F | F | F | F | 
hphp/test/slow/inout/interp-callm/tests/bad-call-10.php | F | . | F | . | F | . | 
hphp/test/slow/inout/interp-callm/tests/bad-call-11.php | F | . | F | . | F | . | 
hphp/test/slow/inout/interp-callm/tests/bad-call-12.php | F | . | F | . | F | . | 
hphp/test/slow/inout/interp-callm/tests/bad-call-13.php | F | F | F | F | F | F | 
hphp/test/slow/inout/interp-callm/tests/bad-call-14.php | F | . | F | . | F | . | 
hphp/test/slow/inout/interp-callm/tests/bad-call-15.php | F | . | F | . | F | . | 
hphp/test/slow/inout/interp-callm/tests/bad-call-2.php | F | F | F | F | F | F | 
hphp/test/slow/inout/interp-callm/tests/bad-call-3.php | F | F | F | F | F | F | 
hphp/test/slow/inout/interp-callm/tests/bad-call-4.php | F | F | F | F | F | F | 
hphp/test/slow/inout/interp-callm/tests/bad-call-5.php | F | F | F | F | F | F | 
hphp/test/slow/inout/interp-callm/tests/bad-call-6.php | F | F | F | F | F | F | 
hphp/test/slow/inout/interp-callm/tests/bad-call-7.php | F | F | F | F | F | F | 
...

Appears to be related to be8eaeb

Missing .ini file?

**Comment by swalk-cavium** [comment]
./hphp/hhvm/hhvm -c /data2/swalk/play.021418a/hhvm/hphp/test/slow/inout/tuple/config.ini -vEval.EnableArgsInBacktraces=true -vEval.EnableIntrinsicsExtension=true -vRepo.Local.Mode=-- -vRepo.Central.Path=/data2/swalk/play.021418a/hhvm/hphp/hhvm/verify.hhbc -vEval.Jit=0   -vEval.ProfileHWEnable=false  -vResourceLimit.CoreFileSize=0    --file 'hphp/test/slow/inout/tuple/tests/side-effects.php'


Fatal error: Uncaught Error: /data2/swalk/play.021418a/hhvm/hphp/test/slow/inout/tuple/tests/side-effects.php appears to be a Hack file, but you do not appear to be running the Hack typechecker. See the documentation at http://docs.hhvm.com/hack/typechecker/setup for information on getting it running. You can also set `-d hhvm.hack.lang.look_for_typechecker=0` to disable this check (not recommended). in :
Stack trace:
#0 {main}

**Comment by fredemmott** [comment]
What commit do you build from? Did it include https://github.com/facebook/hhvm/commit/313861b11c509ba254b8b921828d1f896f2731d2 ?

**Comment by fredemmott** [comment]
From IRC: probably already fixed. Will re-open if needed.

**Comment by swalk-cavium** [comment]
@fredemmott - Hi, it's the second line of the report above.  I start a Matrix-of-Pain test usually every morning, so if a fix was added later it won't show up until the next day.

**Comment by fredemmott** [comment]
ah, yeah, the 'g' threw me off >_<

**Comment by swalk-cavium** [comment]
Still seeing lots of errors on build including 313861b.
Here's first one

/data2/swalk/play.021518a/hhvm$ hphp/test/run -v -m interp hphp/test/slow/inout/interp-callm/tests/bad-async-generator.php
Warning: $_SERVER/$_ENV variables not available, please check 
your ini setting: variables_order, it should have both 'E' and 'S'
You are using the binary located at: ./hphp/hhvm/hhvm
Running 1 tests in 1 threads (0 in serial)
001+ Fatal error: Uncaught Error: Parameters may not be marked inout on async generators in /data2/swalk/play.021518a/hhvm/hphp/test/slow/inout/interp-callm/tests/bad-async-generator.php:3
001- Fatal error\: Parameters may not be marked inout on async [^\r\n]+ in [^\r\n]+\/bad\-async\-generator\.php on line 3
002+ Stack trace:
003+ #0 {main}hphp/test/slow/inout/interp-callm/tests/bad-async-generator.php FAILED (xxx)

1 tests failed

Build at this commit

/data2/swalk/play.021518a/hhvm$ git branch -vv
* master c4927d0 [origin/master] Fix ocamldebug issue with local module include

It looks like the reference output needs updating.

**Comment by fredemmott** [comment]
That one needs the PHP7 flag setting - cc @paulbiss

**Comment by swalk-cavium** [comment]
@fredemmott - I should mention, it's about 145 tests that are failing in interpreter.

**Comment by swalk-cavium** [comment]
There are still a large number of tests failing with Uncaught Errors.  Are these tests still considered
valid and this is just a question of updating the reference?

hphp/hhvm/hhvm -vEval.ReffinessInvariance=True -c /data2/swalk/play.030118a/hhvm/hphp/test/slow/inout/tuple/config.ini -vEval.EnableArgsInBacktraces=true -vEval.EnableIntrinsicsExtension=true -vRepo.Local.Mode=-- -vRepo.Central.Path=/data2/swalk/play.030118a/hhvm/hphp/hhvm/verify.hhbc -vEval.Jit=0   -vEval.ProfileHWEnable=false  -vResourceLimit.CoreFileSize=0    --file 'hphp/test/slow/inout/tuple/tests/bad-parent-1.php' 

Fatal error: Uncaught Error: Parameter 1 on function foo was not declared inout but is declared inout on parent function P::foo in /data2/swalk/play.030118a/hhvm/hphp/test/slow/inout/tuple/tests/bad-parent-1.php:7
Stack trace:
#0 {main}

@fredemmott , @paulbiss  - Comments?

**Comment by swalk-cavium** [comment]
cat hphp/test/slow/inout/tuple/tests/bad-parent-1.php.ini
hhvm.php7.all=0

@fredemmott - Is this the right flag?  It avoids the error above.

**Comment by fredemmott** [comment]
PHP7 mode probably shouldn't have an affect here. I'll poke Paul.

**Comment by swalk-cavium** [comment]
@fredemmott , @paulbiss , @mxw - I heard that you are not seeing these failures internally.
Could it be something on how the tests are presented to github?

**Comment by swalk-cavium** [comment]
This issue is no longer present in testing on 07/23/2018  (build at commit df74e0f).
It was present in testing on 07/20/2018 (build at commit 10ece41)

Most likely it was fixed by  dd9a10f
