### ISSUE TITLE
hh_client does not return syntax errors for functions within static arrays

### ISSUE THREAD

**Issue by spark4** [facebook/hhvm#8129]
### HHVM Version
3.23.4

### Operating System and Version
High Sierra 10.13.3

### Standalone code, or other way to reproduce the problem
It appears that there are syntax rules around function calls within static arrays within classes. `hh_client` is unable to catch the following syntax errors (written inline) that was caught by my linter.

```
class TestClass1 {
    static array<string, test_shape> $test_array = array(
        'test' => shape(
            'foo' => 'hi',
            'bar' => fun('x'), ### Fatal error: syntax error, unexpected '(', expecting ')'
        ),
    );
}
```

```
class TestClass2 {
    static array<string, test_shape> $test_array = array(
        'test' => shape(
            'foo' => 'hi',
            'bar' => ($x) ==> {return $x;}, ### Fatal error: syntax error, unexpected T_LAMBDA_OP
        ),
    );
}
```

### Expected result
`hh_client` would return the error.

### Actual result
`hh_client` returns `No errors!`.

**Comment by fredemmott** [comment]
Closing as:
 - 3.23 is no longer supported
 - we are working on using a single parser for the typechecker and runtime; this will resolve this issue, but in the mean time, we're not going to be doing case-by-case fixes
