### ISSUE TITLE
php 5.3 support

### ISSUE THREAD

**Issue by momkin** [facebook/hhvm#8130]
### HHVM Version
latest
### Operating System and Version
centos 7
### Standalone code, or other way to reproduce the problem
My php script works on php 5.3 well , but with hhvm doesn't works it only give white pages , does hhvm 3.24.2 works with php 5.3 ??

if not which version of hhvm does ??
### Expected result
to work well
### Actual result
white pages

**Comment by fredemmott** [comment]
We don't aim to support any versions of PHP that are not supported by the PHP project either; this means that any version < 5.6 is not targetted.

 - does your code work on 5.6?
 - if so, what do you get in the error logs?

**Comment by fredemmott** [comment]
(Source: http://php.net/supported-versions.php )

Also, future releases will not be supporting PHP5 at all. 3.24 will be supported until 3.30.

**Comment by momkin** [comment]
fredemmott
Hi , can you tell me which version of hhvm will work fine with php 5.3 codes ?
yes i know its end of life but i'm asking if there is old version of hhvm that will works fine with php 5.3 ?

thank you !

**Comment by fredemmott** [comment]
It seems unlikely; we were still working on hphpc rather than HHVM until after 5.4 was released.

**Comment by momkin** [comment]
Hi 
i just tested it with php 5.4 and its working , 
can you tell me which version of hhvm that will support php 5.4 without issues ?

thank you !

**Comment by fredemmott** [comment]
Sorry; I'm not able to spend time investigating unsupported old releases - especially as the relevant versions (if any) are old enough we don't have prebuild binaries for them any more.

**Comment by momkin** [comment]
Hi , fredemmott
I'm will not ask you to give me any support , i'm just asking for version that supports 5.4 that's all , 
if then the version failed or aynthing i won't bother asking for help !

thank you !

**Comment by fredemmott** [comment]
We don't have an easily accessible record of that; answering your question would require running old very old versions of HHVM to investigate, and it would then still just be an approximation.
