### ISSUE TITLE
[vsdebug] "threads" command response has incorrect schema

### ISSUE THREAD

**Issue by PranayAgarwal** [facebook/hhvm#8132]
### HHVM Version
```
HipHop VM 3.25.0-dev (rel)
Compiler: 1519182417_090784734
Repo schema: ebd66af5d2ef02d9c0b602d944acbb6fc7c4b5f0
```
### Operating System and Version
* Ubuntu 16.04.3 LTS

### Problem

When the vscode debug adapter sends over the `threads` command to HHVM, the response `body` returned is an array of `Thread` elements. However, `body` needs to contain a single field, "threads", which contains a list of `Thread` objects.

See https://github.com/Microsoft/vscode-debugadapter-node/blob/master/protocol/src/debugProtocol.ts#L823

```TypeScript
/** Response to 'threads' request. */
export interface ThreadsResponse extends Response {
	body: {
		/** All threads. */
		threads: Thread[];
	};
}
```

**Comment by ebluestein** [comment]
Thanks, fixed by d9ec052861fd17b9613a859dd9257f217d2a6405
