### ISSUE TITLE
[vsdebug] Debugger needs to return "exceptionBreakpointFilters" in the capabilities list

### ISSUE THREAD

**Issue by PranayAgarwal** [facebook/hhvm#8133]
### HHVM Version
```
HipHop VM 3.25.0-dev (rel)
Compiler: 1519182417_090784734
Repo schema: ebd66af5d2ef02d9c0b602d944acbb6fc7c4b5f0
```
### Operating System and Version
* Ubuntu 16.04.3 LTS

### Problem

When vscode asks HHVM for its capabilities in the initialize request, HHVM does not include the "exceptionBreakpointFilters" property. This means that vscode doesn't send the `SetExceptionBreakpoints` request as the next step and HHVM doesn't configure the debugger to break on exceptions.

HHVM needs to include something like the following in the capabilities list:

```TypeScript
event.body.exceptionBreakpointFilters = [
    {
        filter: 'all',
        label: 'All Exceptions',
        default: true
    }
];
```

**Comment by ebluestein** [comment]
Thanks, I added a breakpoint filter for "all" breakpoints in c687c3f92924862719b2941c40a8ebdb39d6aa95.

Currently we don't have a way in HHVM to distinguish between caught and uncaught exceptions unfortunately, so for now we'll just provide all or none.
