### ISSUE TITLE
[vsdebug] "stackTrace" responses need a valid "column" field

### ISSUE THREAD

**Issue by PranayAgarwal** [facebook/hhvm#8134]
### HHVM Version
```
HipHop VM 3.25.0-dev (rel)
Compiler: 1519182417_090784734
Repo schema: ebd66af5d2ef02d9c0b602d944acbb6fc7c4b5f0
```
### Operating System and Version
* Ubuntu 16.04.3 LTS

### Problem

In the `stackTrace` command resonse sent by the HHVM debugger, the value of the `output.body.stackFrames[i].column` field is always 0. VSCode treats this as invalid, however, so the field either needs to be removed completely or set to point to the relevant place in line.

**Comment by ebluestein** [comment]
HHVM doesn't maintain column info for source locations, so providing anything other than 0 is not possible at this time.

Per the protocol spec, the field must be present and 0 if there is no column information:

	export interface StackFrame {
		/** An identifier for the stack frame. It must be unique across all threads. This id can be used to retrieve the scopes of the frame with the 'scopesRequest' or to restart the execution of a stackframe. */
		id: number;
		/** The name of the stack frame, typically a method name. */
		name: string;
		/** The optional source of the frame. */
		source?: Source;
		/** The line within the file of the frame. If source is null or doesn't exist, line is 0 and must be ignored. */
		line: number;
		/** The column within the line. If source is null or doesn't exist, column is 0 and must be ignored. */
		column: number;
		/** An optional end line of the range covered by the stack frame. */
		endLine?: number;
		/** An optional end column of the range covered by the stack frame. */
		endColumn?: number;
		/** The module associated with this frame, if any. */
		moduleId?: number | string;
		/** An optional hint for how to present this frame in the UI. A value of 'label' can be used to indicate that the frame is an artificial frame that is used as a visual label or separator. A value of 'subtle' can be used to change the appearance of a frame in a 'subtle' way. */
		presentationHint?: 'normal' | 'label' | 'subtle';
	}
