### ISSUE TITLE
[vsdebug] Breakpoint event should have valid values for "column", "endLine" and "endColumn"

### ISSUE THREAD

**Issue by PranayAgarwal** [facebook/hhvm#8136]
### HHVM Version
```
HipHop VM 3.25.0-dev (rel)
Compiler: 1519182417_090784734
Repo schema: ebd66af5d2ef02d9c0b602d944acbb6fc7c4b5f0
```
### Operating System and Version
* Ubuntu 16.04.3 LTS

### Problem

The `breakpoint` event currently sent by HHVM only has the `line` field set correctly. `column`, `endLine` and `endColumn` are set to 0. VSCode doesn't recognize 0 as a valid value, however, and fails to recognize the breakpoint entirely. 

If there aren't real values for these fields, they should be omitted from the event body.

**Comment by ebluestein** [comment]
Fixed by 605d3d734cb4bc009fb6f2df6627edfc9b4de8db!
