### ISSUE TITLE
[vsdebug] Debugger should support the "ExceptionInfo" event

### ISSUE THREAD

**Issue by PranayAgarwal** [facebook/hhvm#8137]
### HHVM Version
```
HipHop VM 3.25.0-dev (rel)
Compiler: 1519182417_090784734
Repo schema: ebd66af5d2ef02d9c0b602d944acbb6fc7c4b5f0
```
### Operating System and Version
* Ubuntu 16.04.3 LTS

### Problem

Because HHVM includes the `supportsExceptionInfoRequest` capability on initialization, VSCode will send over an `ExceptionInfo` event whenever the debugger breaks due to a runtime error or exception. HHVM doesn't recognize this event, however, so exception details aren't shown in the debugger UI.

HHVM should support this event and store and return details of the exception that was hit.

**Comment by ebluestein** [comment]
We don't currently support this request yet, updated capabilities to correctly return that this is not supported (f6c785463e30122c9ff5c95de2cb5dc6ea462807)
