### ISSUE TITLE
[vsdebug] Extension logger is too noisy when waiting for socket connection

### ISSUE THREAD

**Issue by PranayAgarwal** [facebook/hhvm#8138]
### HHVM Version
```
HipHop VM 3.25.0-dev (rel)
Compiler: 1519268871_493360405
Repo schema: df346ce39f19608fe862842f8bd5b86c706e9fa3
```
### Operating System and Version
* Ubuntu 16.04.3 LTS
* Can only repro in a Docker container (`hhvm/hhvm:nightly` image)

### Problem

If an HHVM server is started with `-v Eval.Debugger.VSDebugEnable=1 -v Eval.Debugger.VSDebugLogFile=xxx`, the extension continuously logs a stream of "SocketTransport polling for connections..." messages to the log file.

In my latest repro it logged ~2 million lines in 90 seconds, generating a 1.3 GB file.

**Comment by ebluestein** [comment]
I'm looking into this now, I haven't been able to repro it yet but it could indicate the socket poll thread is spinning, which it is not supposed to do.

**Comment by ebluestein** [comment]
@PranayAgarwal  I haven't been able to repro this on the latest HHVM. Does your log file contain any lines that start with "Polling inputs failed" (followed by an error code) ?
