### ISSUE TITLE
Libsodium not loaded in prebuilt hhvm

### ISSUE THREAD

**Issue by eryi** [facebook/hhvm#8140]
### HHVM Version
HipHop VM 3.24.2 

### Operating System and Version
Ubuntu 16.04 Xenial

### Standalone code, or other way to reproduce the problem
extension_loaded("sodium")

### Expected result
true

### Actual result
false

According to #7827 libsodium seems included.  Do I need to do anything to load the extension?

**Comment by fredemmott** [comment]
Sodium support in HHVM requires libsodium 1.0.9; for Ubuntu, this means Zesty or later.

**Comment by xxtanisxx** [comment]
@fredemmott We have Centos7 and libsodium 1.0.16-1.el7 included but `extension_loaded("sodium")` is false with `HipHop VM 3.24.7 (rel)`. Anything that need to be done to enable that?
