### ISSUE TITLE
Type inferencing issue for generic arrays

### ISSUE THREAD

**Issue by tslettebo** [facebook/hhvm#8141]
The following code passes the typechecker:

    <?hh // strict

    function f(array<int> $test): void
    {
      $test[0]=1;
    }

Yet, the following doesn't:

    <?hh // strict

    function f(): array<int>
    {
      $test=[];

      $test[0]=1;

      return $test;
    }

test.php:9:10,14: Invalid return type (Typing[4110])
  test.php:3:15,19: This is an array (used like a vector)
  test.php:7:3,12: It is incompatible with an array (used like a hashtable) because it is used as map here

Is there a way to make the second version pass the typechecker?

**Comment by fredemmott** [comment]
It looks like you want `array<int, int>` instead of `array<int>`

**Comment by fredemmott** [comment]
(or, better: use Hack Arrays: https://docs.hhvm.com/hack/collections/hack-arrays )
