### ISSUE TITLE
[3.15] file not found with require_once

### ISSUE THREAD

**Issue by momkin** [facebook/hhvm#8148]
### HHVM Version
HipHop VM 3.15.3 (rel)
### Operating System and Version
centos 7
### Standalone code, or other way to reproduce the problem
`<?php
require_once( "../config.php" );`
### Expected result
to load the file
### Actual result
\nFatal error: require_once(../config.php): File not found in

**Comment by fredemmott** [comment]
- 3.15 is unsupported. Are you able to reproduce a problem on more recent version?
 - Does ../config.php exist? The error message is saying it doesn't
 - How are you executing it?

**Comment by momkin** [comment]
Hi
yes i tried the version HHVM-3.21 and also the problem exist ,
config.php is exist of course , when i use the full path it works without problems , but when i usee ../ it doesn't

i'm using phtml files

**Comment by fredemmott** [comment]
What exact command are you using to execute it?

**Comment by momkin** [comment]
Its this code 

<?php require_once( "../config.php" );

its should ready config.php without problems , but it doesn't read it its says File not found , but when i change the location to the full path like this
<?php require_once( "/home/user/www/system/config.php" );

it works then !

**Comment by fredemmott** [comment]
What command are you using to run HHVM against this file? Is a webserver involved? Are you using fastcgi?

**Comment by momkin** [comment]
Hi
its nginx with hhvm as fastcgi !

**Comment by fredemmott** [comment]
Does setting `hhvm.server.fix_path_info=true` in your ini file fix this?

If not, you should be able to workaround with `require_once(__DIR__.'/../config.php');`

**Comment by lexidor** [comment]
This issue cannot be reproduced. HHVM can include and require files with relative paths. in modern Hack code, you shouldn't to to require anything other than autoload.hack, because of autoloading.

If someone can reproduce this issue, please open a new issue and refer back to tihs using `#8148`.
