### ISSUE TITLE
Can't reopen STDIN stream after closing

### ISSUE THREAD

**Issue by gsherwood** [facebook/hhvm#8150]
### HHVM Version
HipHop VM 3.25.0 (rel)

### Operating System and Version
Ubuntu Trusty, macOS 10.13.3

### Standalone code, or other way to reproduce the problem
```php
<?php
$handle = fopen('php://stdin', 'r');
fclose($handle);
$handle = fopen('php://stdin', 'r');
fclose($handle);
```

### Expected result
No output.

### Actual result
Warning: Not a valid stream resource in temp.php on line 5

Saw this as soon as Travis updated HHVM to 3.25 today. All unit tests failing as they call code that opens STDIN, the closes it when done. But this happens multiple times during a test run.
Last good run (3.24.3): https://travis-ci.org/squizlabs/PHP_CodeSniffer/jobs/353671579
First bad run (3.25.0): https://travis-ci.org/squizlabs/PHP_CodeSniffer/jobs/354112941

Not sure if this is intended, so reporting just in case. Have worked-around by detecting the unit test run + HHVM and not closing the stream.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

It seams like this issue has been fixed.
I don't get the error message and I can still read from `$handle`.

```HACK
<<__EntryPoint>>
function main(): void {
    $handle = fopen('php://stdin', 'r');
    fclose($handle);
    $handle = fopen('php://stdin', 'r');
    fclose($handle);
    $handle = fopen('php://stdin', 'r');
    echo fread($handle, 4);
}
```

```
$ hhvm src/file.hack 
12345678 << input passed to stdin
1234 << output
```
