### ISSUE TITLE
Linting is producing an uncaught exception

### ISSUE THREAD

**Issue by gsherwood** [facebook/hhvm#8151]
### HHVM Version
HipHop VM 3.25.0 (rel)

### Operating System and Version
Ubuntu Trusty, macOS 10.13.3

### Standalone code, or other way to reproduce the problem
Contents of temp.php:
```php
<?php
$a = 'foo'
```
hhvm -l temp.php

### Expected result
Fatal error: Uncaught Error: syntax error, unexpected $end in ...

### Actual result
Uncaught exception: (unknown)

This only started happening after upgrading to 3.25.0. Not sure if there is a workaround to get the error message back.

**Comment by fredemmott** [comment]
Confirmed we get the message in 3.24 and not 3.25

**Comment by fredemmott** [comment]
internal task: t27053673

**Comment by fredemmott** [comment]
`hhvm -d hhvm.php7.all=0 -l test.php`

Probably caused by the change to raising ParseError in PHP7 mode

**Comment by lexidor** [comment]
Hi, I know dash l must work in modern hhvm versions, since hhast runs it in the codegen code. This issue appears to have been resolved.
