### ISSUE TITLE
Current ubuntu xenial builds lack libyaml 

### ISSUE THREAD

**Issue by tomterl** [facebook/hhvm#8155]
### HHVM Version
3.25.0-1
### Operating System and Version
Ubuntu 16.04
### Standalone code, or other way to reproduce the problem
Use `yaml_parse()`
### Expected result
call into libyaml.so
### Actual result
Call to undefined function

Version lts-3.24 is linked against libyaml.so --

Is this a momentary laps in the build system or is the yaml-extension no longer supported?

**Comment by fredemmott** [comment]
This was provided by the PHP5 C extension; HHVM no longer supports PHP5 C extensions, so this is no longer supported.

You might want to look at https://github.com/mustangostang/spyc , or if you have control over what's being generated, use JSON instead - if you're passing it to other services, that should continue to work, as JSON is valid YAML.
