### ISSUE TITLE
\HH\Asio\curl_exec takes 100% cpu while waiting if no other work being awaited

### ISSUE THREAD

**Issue by eryi** [facebook/hhvm#8156]
### HHVM Version
HipHop VM 3.25.0 (rel)
(3.24.2 was not affected)

### Operating System and Version
Ubuntu 16.04

### Standalone code, or other way to reproduce the problem
````hack
<?hh

$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, "https://httpbin.org/delay/10");

// this line takes 100% cpu for 10 seconds
\HH\Asio\join(\HH\Asio\curl_exec($ch));

// this line *does not* takes 100% cpu for 10 seconds
// curl_exec($ch);

curl_close($ch);
````

### Expected result
CPU should not stay at 100% for 10 seconds

### Actual result
CPU stayed at 100% for 10 seconds

**Comment by fredemmott** [comment]
This is currently a tradeoff:
 - the implementation in 3.24 and below crashes a lot
 - the implementation we have now assumes other things are going on, and tells the async scheduler 'come back to me when there's nothing left'. If there's nothing else, it will spin, but usually this isn't the case.

The main alternative here would be to make it say "don't come back for at least <0.x> seconds", though then we would have users with problems about massive latency overhead for fast requests.

One potential improvement would be to use something like https://github.com/facebookarchive/asio-utilities/pull/11 to wait on both a sleep awaitable and a low-pri reschedule awaitable and change behavior depending on which finishes first; I'm not entirely sure that this is workable though, and would be a fairly intrusive change.

**Comment by fredemmott** [comment]
@jano : is this a reasonable approach?

```
<?hh

async function later_maybe_sleep(): Awaitable<void> {
  $block = async function(?ConditionWaitHandle<int> &$condition) {
    await HH\Asio\va(
      (async function(?ConditionWaitHandle<int> &$condition) {
        await HH\Asio\usleep(100);
        invariant($condition !== null, 'got a null condition');
        $condition->succeed(1);
      })(&$condition),
      (async function(?ConditionWaitHandle<int> &$condition) {
        await RescheduleWaitHandle::create(RescheduleWaitHandle::QUEUE_DEFAULT, 1);
        invariant($condition !== null, 'got a null condition');
        $condition->succeed(2);
      })(&$condition),
    );
  };
  $condition = null;
  $condition = ConditionWaitHandle::create($block(&$condition));
  $result = await $condition;

  if ($result === 1) {
    // Sleep finished first, so we're not the only thing on the queue. As we've
    // already slept a bit, let's call it done.
    return;
  }
  // Reschedule finished first, so there wasn't at least one hundred microseconds of
  // work on the queue; assume that means it's empty, so sleep for a millisecond instead.
  await HH\Asio\usleep(1000);
}
```

**Comment by fredemmott** [comment]
(a direct usleep(1000) would probably be fine for internet requests, but nasty for LAN requests)

**Comment by jano** [comment]
async sleep already has a similar behavior to RescheduleWaitHandle that it gets processed only after all runnable async functions (although before other RescheduleWaitHandles if it finished while CPU was still busy)

why not just keep it simple and use exponential backoff capped at something like 10ms? this should make it fast in low-latency environments, but not busy spin CPU if we actually need to wait for data

also, it's important to reset the backoff time per every curl_multi_await() call, as once data start coming, the latency between packets is expected to be low even over high latency link

```
async function curl_multi_await(
  resource $mh,
  float $timeout = 1.0,
): Awaitable<int> {
  $finish_by = \microtime(true) + $timeout;
  $backoff = 1;
  do {
    $result = \curl_multi_select($mh, 0.0);
    if ($result !== 0) {
      return $result;
    }
    await \HH\Asio\usleep($backoff);
    $backoff = min($backoff * 2, 10000);
  } while (\microtime(true) < $finish_by);
  return 0;
}
```

**Comment by eryi** [comment]
Did something change in 3.25.0? For me, the crashing/cpu hasn't been an issue in 3.24 after 9273c7ecb17e280a7b34551d473b8b67e9f5644c

````
docker run -it --rm -v `pwd`:/tmp hhvm/hhvm:3.24.4 hhvm -d hhvm.hack.lang.look_for_typechecker=0 /tmp/curl.hh
````

**Comment by fredemmott** [comment]
Sorry if I've missed it, but I don't believe that commit was ever in a 3.24.x release; it landed after the branch cut, and doesn't appear in https://github.com/facebook/hhvm/commits/HHVM-3.24

**Comment by eryi** [comment]
That commit fixed #8043 in early January

Regardless, my main point is that
1. \HH\Asio\curl_exec used to crash a lot, then it didn't from around January #8043
2. \HH\Asio\curl_exec didn't take 100% CPU in in 3.24.4, then it took 100% CPU in 3.25.0

**Comment by Rowern** [comment]
Just to do some follow up, any news on this issue?
We are still seeing the 100% CPU pattern when doing a lot of async curl_exec.

**Comment by fredemmott** [comment]
No progress, though there's a chance that https://github.com/facebook/hhvm/pull/8258 fixes the issues with the original implementation
