### ISSUE TITLE
compilation error when USE_LOWPTR flag is enabled

### ISSUE THREAD

**Issue by sushmakt** [facebook/hhvm#8159]
### HHVM Version
HipHop VM 3.25.0 (rel)
Compiler: tags/HHVM-3.25.0-0-g2104634d0f4b78cc0d4ea3ad2113bd31db67c702
Repo schema: 0f52812b28b236066c28dd4b97bc4706d90d8433
(Also seen on hhvm-master)

### Operating System and Version
Cent OS:7.4.1708

### Standalone code, or other way to reproduce the problem
Edit hhvm-src/hphp/runtime/base/string-data-macros.h 
to define USE_LOWPTR
#define USE_LOWPTR
Build hhvm 

### Expected result
Build should complete without any failures

### Actual result
Build fails with static assertion failures
hhvm_master/hphp/runtime/ext/collections/ext_collections-pair.h: In static member function ‘static void HPHP::c_Pair::compileTimeAssertions()’:
hhvm_master/hphp/runtime/ext/collections/ext_collections-pair.h:152:5: error: static assertion failed:
static_assert(offsetof(c_Pair, m_size) ==
When this assert is commented, it further fails at 
/hhvm_master/hphp/runtime/base/string-data.cpp: In member function ‘bool HPHP::StringData::checkSane() const’:
hhvm_master/hphp/runtime/base/string-data.cpp:970:3: error: static assertion failed: StringData size changed---update assertion if you mean it
static_assert(sizeof(StringData) == (use_lowptr ? 16 : 24),
Upon commenting this assert, the build succeeds but very likely will show the after-effects of these assert failures some place else.

This flag enables the asm implementation for string-data functions and hence would be nice to have this build without failures.

**Comment by sushmakt** [comment]
Thanks for the quick response @fredemmott 
Was able to build fine this way without any static asserts.

**Comment by swtaarrs** [comment]
@fredemmott is correct; `USE_LOWPTR` needs to be applied to the whole build. I expect your problem was that there are files that check `#ifdef USE_LOWPTR` but don't include `string-data-macros.h`.
