### ISSUE TITLE
HHVM Memory Doc

### ISSUE THREAD

**Issue by TeBoring** [facebook/hhvm#8160]
I am writing hhvm extension.
Is there any document how hhvm manages memory?

**Comment by fredemmott** [comment]
Probably https://github.com/facebook/hhvm/tree/master/hphp/doc and https://github.com/facebook/hhvm/tree/master/hphp/doc/hackers-guide

Github Issues are not a good place for *questions* about HHVM; for questions about extensions you want #hhvm-dev on irc.freenode.net or https://www.facebook.com/groups/hhvm.dev/

**Comment by TeBoring** [comment]
Only facebook group members can ask question?

**Comment by fredemmott** [comment]
#hhvm-dev on irc.freenode.net is an alternative
