### ISSUE TITLE
hhvm getting terminated after start

### ISSUE THREAD

**Issue by gyanendraojha** [facebook/hhvm#8169]
### Expected result

service hhvm status
hhvm is running

### Actual result

service hhvm status
hhvmis stopped

When itry to run hhvm as below , it starts without any error but when i check its status it  shpws stopped

service hhvm start
hhvm starting ...
hhvm start/running, process 11783

when i checked /var/log/messages

Apr  5 00:31:38 qa-ccios-524 init: hhvm main process (14206) terminated with status 127
Apr  5 00:31:38 qa-ccios-524 init: hhvm main process ended, respawning
Apr  5 00:31:38 qa-ccios-524 init: hhvm main process (14217) terminated with status 127
Apr  5 00:31:38 qa-ccios-524 init: hhvm main process ended, respawning
Apr  5 00:31:38 qa-ccios-524 init: hhvm main process (14222) terminated with status 127
Apr  5 00:31:38 qa-ccios-524 init: hhvm main process ended, respawning
Apr  5 00:31:39 qa-ccios-524 init: hhvm main process (14224) terminated with status 127
Apr  5 00:31:39 qa-ccios-524 init: hhvm main process ended, respawning

/var/log/hhvm/error.log and access.log are empty

**Comment by fredemmott** [comment]
Sorry, we're not able to help here.
 - HHVM 2.x has been unsupported since 2014 (and I don't see a `2.40` in our release history)
 - We do not support Amazon Linux
