### ISSUE TITLE
mb_ereg_match segmentation fault

### ISSUE THREAD

**Issue by momkin** [facebook/hhvm#8177]
### HHVM Version
HipHop VM 3.26.0-dev (rel)
### Operating System and Version
centos 7
### Standalone code, or other way to reproduce the problem
hhvm nginx fastcgi
### Expected result
to work 
### Actual result

```
Host: server.xxxx.xxxx
ProcessID: 14328
ThreadID: 140033730279168
ThreadPID: 14458
Name: /usr/local/bin/hhvm
Type: Segmentation fault
Runtime: hhvm
Version: heads/master-0-g9f302a6511e9f324c85c7f047b0382c180171098
DebuggerCount: 0

Server: www.xxxxx.xxx
ThreadType: Web Request
Server_SERVER_NAME: www.xxxx.xxx
URL: /ajax.php?id=20809&ajax=true&server=3&_=1524595276042

# 0  0000000000d3d436
# 1  0000000001327bd6
# 2  00007f5c43cce5e0
# 3  0000000002ad472c
# 4  0000000002ad5164
# 5  000000000a81a177
# 6  000000000a81b02d
# 7  000000000a8175aa
# 8  0000000006c0019a
# 9  0000000003786a94
# 10 00000000037869aa
# 11 0000000003786fae
# 12 0000000003785427
# 13 00000000037719e5
# 14 0000000002f5d717
# 15 000000000a8146a1
# 16 000000000a8144d9
# 17 0000000006c01ce7
# 18 0000000006c0019a
# 19 0000000003786a94
# 20 00000000037869aa
# 21 0000000003786fae
# 22 0000000003785427
# 23 00000000038a5e15
# 24 00000000038a5c99
# 25 00000000038a5aa1
# 26 0000000001401ebc
# 27 0000000003893d5c
# 28 000000000388b3ca
# 29 00000000016f5136
# 30 00000000016f5dfc
# 31 0000000000cf3951
# 32 00000000014e2a67
# 33 00007f5c43cc6e25
# 34 00007f5c3d2b734d

PHP Stacktrace:

#0  mb_ereg_match() called at [/home/user/public_html/phpQuery/phpQuery/phpQueryObject.php:737]
#1  phpQueryObject->find() called at [/home/user/public_html/phpQuery/phpQuery.php:230]
#2  phpQuery::pq()
#3  call_user_func_array() called at [/home/user/public_html/phpQuery/phpQuery.php:1329]
#4  pq() called at [/home/user/public_html/ajax.php:40]
```

**Comment by fredemmott** [comment]
Are you able to:
- reproduce with a debug build (that should produce a useful native stacktrace)
- provide an example call to mb_ereg_match() that causes this?

**Comment by momkin** [comment]
Hi
the is the line causing this i think

                                $isTag = extension_loaded('mbstring') && phpQuery::$mbstringSupport
                                        ? mb_ereg_match('^[\w|\||-]+$', $s) || $s == '*'
                                        : preg_match('@^[\w|\||-]+$@', $s) || $s == '*';

**Comment by fredemmott** [comment]
Do you have an example input (e.g. value of '$s') that triggers this failure?

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones are very unlikely to be worked on.

This issue has been created some time ago and there is not enough information in this issue to reproduce this issue on a modern build of hhvm. I am closing this issue. If you are reading this and have a way to reproduce this issue in a modern hhvm version, feel free to open a new issue.
