### ISSUE TITLE
limit hhvm memory usage

### ISSUE THREAD

**Issue by momkin** [facebook/hhvm#8179]
### HHVM Version
3.25.2
### Operating System and Version
centos 7
### Actual result
i found my server memory is 100% used 32 GB of memory all gone
i need some way to limit this usage !

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

I found this issue, which is you asking for help. I know that the chances are low you are still using hhvm. The INI setting you were looking for in 2018 is `hhvm.server.memory_head_room`. Maybe this answer will help someone else.

I am sorry that you question remained unanswered for years.
