### ISSUE TITLE
Typechecker does not catch undefined variable under certain conditions

### ISSUE THREAD

**Issue by eryi** [facebook/hhvm#8182]
### HHVM Version
HipHop VM 3.25.2 (rel)

### Operating System and Version
Ubuntu 17.10

### Standalone code, or other way to reproduce the problem
Minimal code to reproduce problem. Commenting out any line fixes the problem.

````php
<?hh //strict

function test(): void {
  try {
    if (false) {}

    print $myvar;

    $myvar = null;

  } catch (\Throwable $e) {
    return;
  }
}

````

### Expected result
````
error.hh:7:11,16: Undefined variable: $myvar (Naming[2050])
````

### Actual result
````
No errors!
````

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Happy to report that this is fixed. I have seen other issues against facebook/hhvm that reported on the same problem #7582.
