### ISSUE TITLE
composer / hh_autoload termination with exception, hhvm 3.26.0

### ISSUE THREAD

**Issue by mderosa** [facebook/hhvm#8184]
### HHVM Version
3.26.0
### Operating System and Version
Ubuntu 17.10
### Standalone code, or other way to reproduce the problem
using composer as: Composer version 1.6.5 2018-05-04 11:44:59 run
$ hhvm composer install 
or 
$ hhvm composer update

### Expected result
update or installation of dependencies

### Actual result
termination by invariant exception, ex:
$ hhvm /home/marco/bin/composer install
hhvm /home/marco/bin/composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 1 install, 18 updates, 0 removals
  - Updating sendgrid/php-http-client (3.9.6 => 3.7.0): Downloading (100%)
  - Updating sendgrid/sendgrid (5.6.2 => 5.5.0): Downloading (100%)
  - Updating symfony/event-dispatcher (v2.8.39 => v2.8.20): Downloading (100%)
  - Updating tecnickcom/tcpdf (6.2.17 => 6.2.12): Downloading (connecting...)SlowTimer [10706ms] at curl: https://api.github.com/repos/tecnickcom/TCPDF/zipball/2f732eaa91b5665274689b1d40b285a7bacdc37f
Downloading (100%)
  - Updating webmozart/assert (1.3.0 => 1.2.0): Downloading (100%)
  - Updating phpdocumentor/reflection-common (1.0.1 => 1.0): Downloading (100%)
  - Updating phpdocumentor/type-resolver (0.4.0 => 0.2.1): Downloading (100%)
  - Updating phpdocumentor/reflection-docblock (4.3.0 => 3.1.1): Downloading (100%)
  - Updating phpunit/php-token-stream (2.0.2 => 1.4.11): Downloading (100%)
  - Updating symfony/yaml (v4.0.9 => v3.2.8): Downloading (100%)
  - Updating sebastian/diff (1.4.3 => 1.4.1): Downloading (100%)
  - Updating doctrine/instantiator (1.1.0 => 1.0.5): Downloading (100%)
  - Updating phpunit/phpunit-mock-objects (3.4.4 => 3.4.3): Downloading (100%)
  - Updating phpunit/php-file-iterator (1.4.5 => 1.4.2): Downloading (100%)
  - Updating phpspec/prophecy (1.7.6 => v1.7.0): Downloading (100%)
  - Updating myclabs/deep-copy (1.7.0 => 1.6.1): Downloading (100%)
  - Updating phpunit/phpunit (5.7.27 => 5.7.19): Downloading (100%)
  - Installing fredemmott/type-assert (v1.1): Downloading (100%)
  - Updating giorgiosironi/eris dev-master (d7cbea4 => 42f1cb7):  Checking out 42f1cb7319
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.
Package phpoffice/phpexcel is abandoned, you should avoid using it. Use phpoffice/phpspreadsheet instead.
Generating autoload files

                                                              
  [HH\InvariantException]                                     
  FactParse typesshould be an array<shape('name' => string)>  
                                                              

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...

**Comment by fredemmott** [comment]
There's a chance this is resolved by https://github.com/hhvm/hhvm-autoload/releases/tag/v1.6.3 - if not, 1.6.3 will point out hte problematic file name in error messages.
