### ISSUE TITLE
[HackC] Empty if statements in the alternative syntax

### ISSUE THREAD

**Issue by wrwrwr** [facebook/hhvm#8185]
### HHVM Version

HipHop VM 3.26.0 (rel)
Compiler: 1525486095_960434512
Repo schema: c646932d70c613060a2f6b7cc8b58722b0b4e193

### Operating System and Version

Ubuntu 17.10

### Standalone code, or other way to reproduce the problem

```php
if (0):
endif;
```

### Expected result

Parses with both PHP 7.1 and `-d hhvm.hack_compiler_default=false`.

### Actual result

```
Fatal error: Uncaught Error: missing case in statement.
   - pos: File "hhvm-empty-if.php", line 3, characters 1-1:
   - unexpected: ''
   - kind: missing
    in hhvm-empty-if.php:1
Stack trace:
#0 {main}
```

Not a style I'd personally recommend, but happens to be used in [some popular software](https://github.com/WordPress/WordPress/blob/4.9-branch/wp-includes/template-loader.php#L46). A possible workaround is to just add a semicolon after the colon.

**Comment by fredemmott** [comment]
@wrwrwr thanks for the clear bug report :)
