### ISSUE TITLE
[HackC] different values for is_array() on pseudoglobals

### ISSUE THREAD

**Issue by soundslocke** [facebook/hhvm#8186]
### HHVM Version

```
$ hhvm --version
HipHop VM 3.26.0 (rel)
Compiler: 1525486170_997833549
Repo schema: 9922b892086778e6d226bdad68875052ee9b4099
```

### Operating System and Version

Ubuntu 16.04

### Standalone code, or other way to reproduce the problem

Run a fresh copy of [CodeIgniter](https://codeigniter.com/) (I'm using version 3.1.8) in HHVM 3.26.0.

```
$ hhvm -m server -p 8080 -d hhvm.server.source_root=/path/to/codeigniter/
```

Then navigate to http://localhost:8080/

### Expected result

Render the CodeIgniter default welcome page.

### Actual result

Several odd undefined variable PHP errors:

![image](https://user-images.githubusercontent.com/1626411/39774150-1a6ce1f6-52c8-11e8-87ef-35ccace05fcd.png)

There are no errors and the page loads as expected when the `-d hhvm.hack_compiler_default=false` option is specified.

**Comment by fredemmott** [comment]
Isolated repro:

```
<?php

function foo() {
  var_dump(is_array($_GET));
  var_dump($_GET);
}

foo();
```

```
hhvm -m server -p 8080
```

```
curl 'http://localhost:8080/test.php?foo=bar'
```

# With HackC

```
bool(false)
array(1) {
  ["foo"]=>
  string(3) "bar"
}
```

```
\nNotice: Undefined variable: _GET in /private/tmp/hhtest/test.php on line 4
```

## Without HackC

```
bool(true)
array(1) {
  ["foo"]=>
  string(3) "bar"
}
```

No notice.
