### ISSUE TITLE
mysql_get_client_info with parameter gives incorrect Warning

### ISSUE THREAD

**Issue by ocasta** [facebook/hhvm#8188]
### HHVM Version
3.21.10
3.26.0

### Operating System and Version
Ubuntu Xenial

### Standalone code, or other way to reproduce the problem
$con=mysqli_connect("localhost","my_user","my_password","my_db");
$client_version = mysqli_get_client_info( $con );

### Expected result
No warning as the php manual indicates that an optional parameter is permitted

### Actual result
Warning: mysqli_get_client_info() expects exactly 0 parameters, 1 given

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Support for ext/mysqli was removed in hhvm [4.9.0](https://hhvm.com/blog/2019/06/10/hhvm-4.9.0.html).
