### ISSUE TITLE
error pulling updates from repository

### ISSUE THREAD

**Issue by copenhaus** [facebook/hhvm#8190]
trying to pull in the latest update from my Ubuntu 16.04.4:

Get:1 http://dl.hhvm.com/ubuntu xenial InRelease [2,411 B]
Hit:2 http://us.archive.ubuntu.com/ubuntu xenial InRelease
Get:3 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]
Err:1 http://dl.hhvm.com/ubuntu xenial InRelease
  _**The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B4112585D386EB94**_
Get:4 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]
Get:5 http://security.ubuntu.com/ubuntu xenial-security InRelease [107 kB]

**Comment by fredemmott** [comment]
https://hhvm.com/blog/2017/11/14/gpg-key-migration.html

**Comment by copenhaus** [comment]
this is my whole interaction....i can't find out what's wrong...


root@mailbox:/tmp# sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xB4112585D386EB94
Executing: /tmp/tmp.C9sWejjIWE/gpg.1.sh --recv-keys
--keyserver
hkp://keyserver.ubuntu.com:80
0xB4112585D386EB94
gpg: requesting key D386EB94 from hkp server keyserver.ubuntu.com
gpg: key D386EB94: "HHVM Package Signing <opensource+hhvm@fb.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
root@mailbox:/tmp# gpg --keyring /etc/apt/trusted.gpg --list-sigs
/etc/apt/trusted.gpg
--------------------
pub   1024D/437D05B5 2004-09-12
uid                  Ubuntu Archive Automatic Signing Key <ftpmaster@ubuntu.com>
sig 3        437D05B5 2004-09-12  Ubuntu Archive Automatic Signing Key <ftpmaster@ubuntu.com>
sig 3        AB2A91F5 2004-09-22  [User ID not found]
sig          65FBC7A2 2006-01-06  [User ID not found]
sig          FB3807DB 2006-02-21  [User ID not found]
sig          192E415C 2006-07-28  [User ID not found]
sig          6C33DF08 2006-09-13  [User ID not found]
sig          340AEDA8 2006-09-28  [User ID not found]
sig          87E4865F 2006-09-28  [User ID not found]
sig          CBA76619 2006-09-28  [User ID not found]
sig          A550E784 2006-09-28  [User ID not found]
sig          7E4B5C97 2006-11-25  [User ID not found]
sig          874BEBC8 2007-01-06  [User ID not found]
sig          EDE3B565 2007-01-22  [User ID not found]
sig          FF031580 2007-03-15  [User ID not found]
sig          10FA4CD1 2007-07-31  [User ID not found]
sig 3        C6913CF6 2005-06-01  [User ID not found]
sig 3        E11D7813 2005-06-01  [User ID not found]
sig    R     B220ADC6 2007-01-03  [User ID not found]
sig          3F272F5B 2007-11-09  [User ID not found]
sub   2048g/79164387 2004-09-12
sig          437D05B5 2004-09-12  Ubuntu Archive Automatic Signing Key <ftpmaster@ubuntu.com>

pub   4096R/C0B21F32 2012-05-11
uid                  Ubuntu Archive Automatic Signing Key (2012) <ftpmaster@ubuntu.com>
sig 3        C0B21F32 2012-05-11  Ubuntu Archive Automatic Signing Key (2012) <ftpmaster@ubuntu.com>
sig          7D86500B 2012-05-11  [User ID not found]
sig          3F272F5B 2012-05-11  [User ID not found]
sig          AB2A91F5 2012-05-11  [User ID not found]

pub   4096R/EFE21092 2012-05-11
uid                  Ubuntu CD Image Automatic Signing Key (2012) <cdimage@ubuntu.com>
sig 3        EFE21092 2012-05-11  Ubuntu CD Image Automatic Signing Key (2012) <cdimage@ubuntu.com>
sig          3F272F5B 2012-05-11  [User ID not found]
sig          7D86500B 2012-05-11  [User ID not found]
sig          01AA4A64 2012-05-12  [User ID not found]

pub   1024D/FBB75451 2004-12-30
uid                  Ubuntu CD Image Automatic Signing Key <cdimage@ubuntu.com>
sig 3        FBB75451 2004-12-30  Ubuntu CD Image Automatic Signing Key <cdimage@ubuntu.com>
sig 3        10FA4CD1 2004-12-31  [User ID not found]
sig          B0A8602B 2006-06-16  [User ID not found]
sig          61E11153 2006-06-17  [User ID not found]
sig          6C33DF08 2006-09-13  [User ID not found]
sig          874BEBC8 2007-01-06  [User ID not found]
sig          A0B3E88B 2007-03-14  [User ID not found]
sig    R     8EE90411 2006-06-02  [User ID not found]
sig    R     55185820 2006-06-03  [User ID not found]
sig    R     B220ADC6 2007-01-03  [User ID not found]
sig          09E9A1D5 2005-11-07  [User ID not found]
sig          2CC39120 2006-08-16  [User ID not found]
sig          2CC39120 2006-08-17  [User ID not found]
rev          2CC39120 2006-08-16  [User ID not found]
rev          2CC39120 2006-08-17  [User ID not found]
sig          3F272F5B 2007-11-09  [User ID not found]

pub   2048R/1BE7A449 2013-12-25
uid                  Paul Tarjan <pt@fb.com>
sig 3        1BE7A449 2013-12-25  Paul Tarjan <pt@fb.com>
sub   2048R/452A652F 2013-12-25
sig          1BE7A449 2013-12-25  Paul Tarjan <pt@fb.com>

pub   4096R/D386EB94 2017-11-03
uid                  HHVM Package Signing <opensource+hhvm@fb.com>
sig 3        1BE7A449 2017-11-03  Paul Tarjan <pt@fb.com>
sig 3        D386EB94 2017-11-03  HHVM Package Signing <opensource+hhvm@fb.com>

root@mailbox:/tmp# gpg --keyring /etc/apt/trusted.gpg --verify < file
gpg: Signature made Tue 14 Nov 2017 08:38:20 AM PST using RSA key ID 1BE7A449
gpg: BAD signature from "Paul Tarjan <pt@fb.com>"
gpg: Signature made Tue 14 Nov 2017 08:38:20 AM PST using RSA key ID D386EB94
gpg: BAD signature from "HHVM Package Signing <opensource+hhvm@fb.com>"
root@mailbox:/tmp# cat file
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

In November 2017, the HHVM project will be migrating from GPG key 0x1BE7A449, with fingerprint:

36AE F64D 0207 E7EE E352  D487 5A16 E728 1BE7 A449

to GPG key 0xD386EB94, with fingerprint:

0583 41C6 8FC8 DE60 17D7  75A1 B411 2585 D386 EB94
-----BEGIN PGP SIGNATURE-----

iQE+BAEBCAAoFiEENq72TQIH5+7jUtSHWhbnKBvnpEkFAloLG/wKHHB0QGZiLmNv
bQAKCRBaFucoG+ekSe/ZB/4tuH5ZgV1whKPgZIlhi9iDdqTEbANT2nuCaCQuSupU
Dfha1KiYYqnZraw2EBDs0Ve6xrfIdhMKEoF7L2yRsWq/2i490Tf1Ug28MWaLiI23
ZqBpmv9djA9l/xi4CjWWjJaI60kZOL4WUzXrwlU6g6GwcObJweBjrZgA0NMrZwQP
F3Ll0czrxXxUS4ujpv5wSwYVGpJ0zZik8krFzb80Ttkum6icYJuTV8/85VEh8qHo
0557G94w8p5iAUNIdYbG510A0WfKe9s/5CEFCDyYuo3igFYipFWPy5/jK2j7F3VU
4LaWbSfzMMyVI746AMr5LJeFFTRi9YhQg9nnwgay+/yNiQJLBAEBCAA1FiEEBYNB
xo/I3mAX13WhtBElhdOG65QFAloLG/wXHG9wZW5zb3VyY2UraGh2bUBmYi5jb20A
CgkQtBElhdOG65R+ag//SVhZyYiJj35UK8rdKe9y53VdJtDQdD4GGJk/Y52c2pAi
xgs5AdHuTwVb+OzPJMUf/HpBFfNR6Ny86LlFEGqJvnWTJ5gVM6iN+UhPqgFBviqN
Xc6U+Ix3XF0vx6fQSNtK8YSP201psV7d7QKvDTaIEt0pm5JkrCp4VCwwiEAK/R0S
RcFh3cghSzCrdYbmr5lX4I6jkjEw/DyjqGsM9ctldNmqxGC55MfYMrx3tw+PiHTx
eivtw6L0X9z4mRJ0ONs9ULjtamurQbHWyVw8CA/BJ89X/1B9mNyLCxJlT5vrlb6a
ctzbowOFH9IviKFMxIqdRdenDOjIvWdvIf6jloT8ibt5s+ZGixf/0rWYzCTdi+fS
cjbuc7DW4Aru2i6DdQb63mXCjhpmEnkX3gvq1b2TYYQSCm7bd6vSwEQmoTUGOkDZ
Jm7sH97WgiOOBw5EmyBM1Coa5OaOq8qWghE5buzFpONA9gBXTxgJRS8lxswC0K5o
od+AhGTEuecVCEl7lIP/N5ASjrEBkEVKsFaGCX0tSDfgqCZW1JJ+WPD+TllUoEfd
m9jEaNjiApKSOxYg94+1M5Mv+BWh3AoEwz5Jm1xFnVhEocPqhX5Bh53OEfVWoPNX
Po7IgHHd574CLddZrzCslCsnhISm/ARHA2MZBLhfgl71eqz4nqiSwQ4IkUHEMGQ=
=WORw
-----END PGP SIGNATURE-----
