### ISSUE TITLE
[HackC] does not support unicode property names

### ISSUE THREAD

**Issue by samdark** [facebook/hhvm#8192]
### HHVM Version

HipHop VM 3.26.0 (rel)
Compiler: 1525486493_012661467
Repo schema: eb95eed00a26ef54923c9f5f6ff48e5694401b93

### Operating System and Version

Ubuntu Trusty (Travis)

### Standalone code, or other way to reproduce the problem

The source code is provided in the error message.

### Expected result

Build https://travis-ci.org/yiisoft/yii2/jobs/376998007 passes.

### Actual result

Failure of https://travis-ci.org/yiisoft/yii2/jobs/376998007 with 

```
ExternCompiler Generated a bad unit: Assembler Error: line 1152: expected name for property
```

**Comment by samdark** [comment]
Weird. It was OK in previous releases.

**Comment by fredemmott** [comment]
See "HackC: The Hack Compiler" on https://hhvm.com/blog/2018/05/07/hhvm-3.26.html

**Comment by samdark** [comment]
Got it. Thanks.
