### ISSUE TITLE
hhvm.mysql.read_timeout cannot be changed at runtime

### ISSUE THREAD

**Issue by pbl64k** [facebook/hhvm#8193]
### HHVM Version

HipHop VM 3.21.3 (rel)
Compiler: tags/HHVM-3.21.3-0-gce34e5458e6a75931438a2d8fc41b91454a2f2b2
Repo schema: 90ed4216b98563d0585cf5c87959dc9ff7c2e1a1

### Operating System and Version

Ubuntu 16.04.3 LTS (xenial)

### Standalone code, or other way to reproduce the problem

    <?hh
    $res = ini_set('hhvm.mysql.read_timeout', 300000);
    print(($res ? 'CHANGED' : 'NOT CHANGED') . "\n");
    print(ini_get('hhvm.mysql.read_timeout') . "\n");

### Expected result

CHANGED
300000

### Actual result

NOT CHANGED
60000

### Details

We're generally happy with the default 60s timeout, and do not want to raise it (if anything, I'd rather lower it even further for normal operation). But it's also not unusual for us to execute longer-running queries under specific circumstances, e.g. when running migrations changing the schema. The inability to control this setting at run-time is therefore quite a hindrance for us.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This setting was required for MySQL() and mysqli() functions. AsyncMysqlConnection::query() takes a timeout_micros parameter, as does the AsyncMysqlClient::connect() method.

The mysqli extension was removed in hhvm 4.9.0.
