### ISSUE TITLE
[hackc] HackC generates invalid HHAS if the directory name contains backslashes

### ISSUE THREAD

**Issue by SamMousa** [facebook/hhvm#8196]
### HHVM Version
nightly

### Operating System and Version
trusty

### Standalone code, or other way to reproduce the problem
https://travis-ci.org/yiisoft/yii2/jobs/377607694#L1019

Strange thing is, if i copy the PHP source from the error message and pass it directly into hhvm (via the docker nightly image) it works.

### Expected result
It should work without any errors, in this specific example there's not even a PHP tag.

### Actual result

Error: Assembler Error: line 5: unrecognized character escape

**Comment by samdark** [comment]
Looks like another regression in compiler.

**Comment by fredemmott** [comment]
```
.filepath "/home/travis/build/yiisoft/yii2/tests/runtime/yiiunit\framework\mail\BaseMailerTest_9126/test_view.php";

```

Do you have backslashes in filenames?

**Comment by fredemmott** [comment]
```
Error: Assembler Error: line 5: unrecognized character escape
```

This is saying that the HHVM can't understand the HHAS that HackC generates; it's line 5 of the `========== ExternCompiler Result ==========` section that's interesting

**Comment by fredemmott** [comment]
...

```
fredemmott-pro:hhtest fredemmott$ cd yiiunit\\framework\\mail\\BaseMailerTest_9126/
fredemmott-pro:yiiunit\framework\mail\BaseMailerTest_9126 fredemmott$ echo '<?php echo "hello, world";' > test.php
fredemmott-pro:yiiunit\framework\mail\BaseMailerTest_9126 fredemmott$ cd ..
fredemmott-pro:hhtest fredemmott$ hhvm yiiunit\\framework\\mail\\BaseMailerTest_9126/test.php
ExternCompiler Generated a bad unit: Assembler Error: line 5: unrecognized character escape
========== PHP Source ==========
<?php echo "hello, world";

========== ExternCompiler Result ==========
# /private/tmp/hhtest/yiiunit\framework\mail\BaseMailerTest_9126/test.php starts here

.strict 0;

.filepath "/private/tmp/hhtest/yiiunit\framework\mail\BaseMailerTest_9126/test.php";

.hh_file 0;

.main (1,1) {
  .srcloc 1:12,1:25;
  String "hello, world"
  .srcloc 1:7,1:26;
  Print
  .srcloc 1:7,1:26;
  PopC
  Int 1
  RetC
}

# /private/tmp/hhtest/yiiunit\framework\mail\BaseMailerTest_9126/test.php ends here



Fatal error: Uncaught Error: Assembler Error: line 5: unrecognized character escape
========== PHP Source ==========
<?php echo "hello, world";

========== ExternCompiler Result ==========
# /private/tmp/hhtest/yiiunit\framework\mail\BaseMailerTest_9126/test.php starts here

.strict 0;

.filepath "/private/tmp/hhtest/yiiunit\framework\mail\BaseMailerTest_9126/test.php";

.hh_file 0;

.main (1,1) {
  .srcloc 1:12,1:25;
  String "hello, world"
  .srcloc 1:7,1:26;
  Print
  .srcloc 1:7,1:26;
  PopC
  Int 1
  RetC
}

# /private/tmp/hhtest/yiiunit\framework\mail\BaseMailerTest_9126/test.php ends here

 in /private/tmp/hhtest/yiiunit\framework\mail\BaseMailerTest_9126/test.php:-1
Stack trace:
#0 {main}
fredemmott-pro:hhtest fredemmott$
```

**Comment by fredemmott** [comment]
filenames appear to be fine, it's the directory name that matters

**Comment by SamMousa** [comment]
Let me know specifically if I need to look up something; I'm not at all familiar with hhvm and not very familiar with this specific test case.

**Comment by fredemmott** [comment]
Nope - I just made an empty directory with the same name as yours, and a trivial file. It failed.

**Comment by fredemmott** [comment]
@SamMousa : thanks for the reports - I took a quick look at yii's recent travis runs, and I don't see anything else that stands out as a regression in 3.26.2 or HHVM nightlies - are you aware of any remaining?

Also, while we appreciate these reports and will continue to prioritize fixing regressions, I want to make sure you're aware that HHVM's long term plans do not include supporting PHP: https://hhvm.com/blog/2017/09/18/the-future-of-hhvm.html

**Comment by SamMousa** [comment]
I'm not aware of any issues.

 We're aware and it will drop support for hhvm in the next framework version.

Thanks for everything!
