### ISSUE TITLE
HHVM does not build from source on aarch64

### ISSUE THREAD

**Issue by swalk-cavium** [facebook/hhvm#8197]
### HHVM Version
Last successful build
HipHop VM 3.27.0-dev (dbg)

### Operating System and Version
ubuntu 16.04

### Standalone code, or other way to reproduce the problem
Build from source steps previously published in hhvm wiki

### Expected result
[100%] Built target hack
Embedding php in hhvm
Embedding php in tc-print
Creating symlinks for hhvm
[100%] Built target hhvm
[100%] Built target tc-print

### Actual result
 7422 /data2/swalk/play.051018a/hhvm/third-party/folly/src/folly/container/detail/F14IntrinsicsAvailability.h:30:5: note      : #pragma message: Vector intrinsics unavailable on this platform, falling back to std::unordered_map / set
 7423      "falling back to std::unordered_map / set"
 7424      ^   
 7425 [ERROR] core.v0.9.1 is not available because your system doesn't comply with
 7426         ocaml-version >= "4.03.0" & ocaml-version < "4.06.0" & arch !=
 7427         "aarch64".
 7428 hphp/hack/CMakeFiles/opam.stamp.dir/build.make:57: recipe for target 'hphp/hack/CMakeFiles/opam.stamp' failed
 7429 make[2]: *** [hphp/hack/CMakeFiles/opam.stamp] Error 66
 7430 CMakeFiles/Makefile2:1673: recipe for target 'hphp/hack/CMakeFiles/opam.stamp.dir/all' failed
 7431 make[1]: *** [hphp/hack/CMakeFiles/opam.stamp.dir/all] Error 2
 7432 make[1]: *** Waiting for unfinished jobs....

Traced to this commit
97fdc99 Add core_kernel dependency, fix missing variable, remove OCAML_LIBRARIES in favor of ocamlfind and _tags

Confirmed by FB on hhvm-dev IRC
related to Jane Street (ocaml replacement library)

**Comment by fredemmott** [comment]
https://github.com/facebook/hhvm/commit/8ccd4d456e25a6d43e66056d6a73786782003161
