### ISSUE TITLE
Language server should ignore URI schemes it doesn't recognize rather than log an error

### ISSUE THREAD

**Issue by PranayAgarwal** [facebook/hhvm#8202]
### HHVM Version
3.24.6+

### Operating System and Version
macOS High Sierra (10.13.4)

### Standalone code, or other way to reproduce the problem
Edit a Hack file in VS Code with language server enabled. Open Git diff view for the file and hover over a function or variable in the left panel (representing the unchanged file). VS Code sends a hover request for the symbol at mouse position, with the file having a `git:/` scheme. 

### Expected result
Language server should ignore the request if it doesn't handle the file scheme and not log an error.

### Actual result
Language server logs an error to editor output panel. 
```
[Error - 1:27:06 PM] Request textDocument/hover failed.
  Message: Not a valid file url 'git:/Users/pranay/repos/site/test.php?%7B%22path%22%3A%22%2FUsers%2Fpranay%2Frepos%2Fsite%2Ftest.php%22%2C%22ref%22%3A%22~%22%7D'
  Code: -32602 
[object Object]
```

**Comment by fredemmott** [comment]
Fb task: T29412524

**Comment by fredemmott** [comment]
"ignore the request" meaning never send any kind of response? Specifying the scheme in documentSelector (as you're doing in master) and returning an error if this fails seems more correct

**Comment by PranayAgarwal** [comment]
Yeah, I added the selector after filing this and forgot to post an update. This one can be closed.
