### ISSUE TITLE
It is incompatible with an untyped array from the argument to this \is_array test

### ISSUE THREAD

**Issue by wake-up-neo** [facebook/hhvm#8206]
### HHVM Version
3.26.2 //strict

`function foo():?array<mixed>;`

`return is_array($unsafe_array) ? $unsafe_array :  null;`

> Invalid return type (Typing[4110])
> This is an array (used like a vector)
> It is incompatible with an untyped array from the argument to this \is_array test

### Why it is so hard ?

**Comment by fredemmott** [comment]
Since 3.25, `array`, `array<Tv>`, and `array<Tk, Tv>` can not be coerced between each other.

`is_array()` refines to an `array`, not to either variant.

You can use https://github.com/hhvm/type-assert or simialr to perform this refinement safely.
