### ISSUE TITLE
Compilation fails with GCC7 

### ISSUE THREAD

**Issue by leitao** [facebook/hhvm#8207]
Currently HHVM fails to compile with GCC7 on POWER platform with the following error:
```

/<<BUILDDIR>>/hhvm-3.24.7+dfsg/hphp/runtime/base/heap-scan.h: In member function ‘void HPHP::{anonymous}::Collector::traceRoots() [with bool apcgc = true]’:
/<<BUILDDIR>>/hhvm-3.24.7+dfsg/hphp/util/portability.h:203:25: error: PIC register clobbered by ‘r2’ in ‘asm’
                   "v31");
```

Full buildlog at https://launchpadlibrarian.net/370225142/buildlog_ubuntu-cosmic-ppc64el.hhvm_3.24.7+dfsg-2ubuntu1_BUILDING.txt.gz

In order to fix it, we basically removed r2 from the clobbered list[1]. With this patch, HHVM is compiling fine with all tests passing on Ubuntu/ppc64el as showed in https://launchpad.net/ubuntu/+source/hhvm/3.24.7+dfsg-2ubuntu2

[1] http://launchpadlibrarian.net/370416124/hhvm_3.24.7+dfsg-2ubuntu1_3.24.7+dfsg-2ubuntu2.diff.gz

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This compilation error is so old, it isn't likely to be the first compilation error for a community trying to create a PowerPC build of hhvm. PowerPC is currently community supported.
