### ISSUE TITLE
HHVM Pdo Dblib could not find driver

### ISSUE THREAD

**Issue by asim-vax** [facebook/hhvm#8209]
Hi,

When using hhvm PDO throws an error could not find driver trying to connect to a MSSQL database, but in PHP7.0 with correct extras works - I am probably missing something obvious

### HHVM Version
 hhvm --version
HipHop VM 3.26.1 (rel)
Compiler: 1526064234_005371528
Repo schema: e9be7850d7f2754adce2aa2e75b18df03f8da9a0

### Operating System and Version
Ubuntu 18.04

### Standalone code, or other way to reproduce the problem
try {
            $this->db = new PDO("dblib:host=" . $connection['host'] . ":1433;dbname=" . $connection['database'], $connection['username'], $connection['password']);
        } catch (PDOException $e) {
            echo "Connection to database server could not be established: " . $e->getMessage() . "\n";
            exit;
        }

### Actual result
Exception thrown - error: "could not find driver"

### Expected result
Connect to mssql database which works fine in PHP7.0

Thanks

**Comment by fredemmott** [comment]
Sorry - we do not support mssql, or ODBC, and are not planning to change this.
