### ISSUE TITLE
hackfmt overindents docblocks if input contains tabs

### ISSUE THREAD

**Issue by ssandler** [facebook/hhvm#8211]
### HHVM Version

```
hh_client --version
hh-4a60dc2e4ccbca67883a3d945806d07d57db8a5e-3.24.6 Tue Apr  3 14:35:32 2018

hhvm --version
HipHop VM 3.24.6-0-slack (rel)
Compiler: 1522791322_N
Repo schema: bda5c3fb6f702a10e423d69e81f99d2e5ee0664c
```

### Operating System and Version

MacOS High Sierra

### Standalone code, or other way to reproduce the problem

https://gist.github.com/ssandler/a4b49b290640d92b615f1373c6b0de17

Using the above file, run this command:
```
hackfmt --in-place --indent-width 8 --tabs --line-width 160 test.php
```

This only repros if the file starts off with tab indenting to begin with, so make sure that wherever you paste this into, you have tabs in the file.

### Actual result

Each time I run `hackfmt`, it indents part of the docblock by one level.
![fmt](https://user-images.githubusercontent.com/1163725/40327201-e97c9418-5cf6-11e8-9d0b-1a7295eb69b9.gif)

### Expected result

The code should be unchanged by formatting.

**Comment by fredemmott** [comment]
we might fix this slightly differently: I'm unsure if 'leave it alone' is going to be workable here. Our desired formatting is:

```
/** foo
 * bar
 * baz
 */
```

i.e. the first `*` is aligned.

**Comment by ssandler** [comment]
It seems like the only way to do that would be to introduce mixed tabs and spaces, though, right? (maybe that's fine but currently our linter also complains about mixed whitespace).

**Comment by fredemmott** [comment]
We don't generally like tabs, but when we do, I think "tabs for indentation, spaces for alignment" is the guideline

**Comment by fredemmott** [comment]
Also happens without `--tabs`, all that matters is that the input file contains tabs.

**Comment by ssandler** [comment]
Fred, do you have a sense of when this one might be able to be fixed? We're definitely interested in using `hackfmt` and I think this bug may be the only blocker, since we do use tabs.

**Comment by fredemmott** [comment]
Sorry, no (though for my future reference, FB T29652790).

If you're able to send a pull request, I'll review it/get it merged if possible.

**Comment by fredemmott** [comment]
Sorry, no update (though for my future reference, FB T29652790). I'll try to take a look if the maintainers haven't once I've finished some work to unblock my intern and got hhast-lint's LSP support finished.

If you're able to send a pull request sooner, I'll review it/get it merged if possible.

**Comment by ssandler** [comment]
Ok, I'll ask around for volunteers on our side as well.
