### ISSUE TITLE
Databases/references/cufa: Different behavior in <?php file

### ISSUE THREAD

**Issue by elfprince13** [facebook/hhvm#8212]
### HHVM Version
```
HipHop VM 3.26.2 (rel)
Compiler: 1526415514_310797325
Repo schema: 06f33850d25d866a8c05ac8142bb51e72256fb04
```
### Operating System and Version
```
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.4 (stretch)
Release:	9.4
Codename:	stretch
```
### Standalone code, or other way to reproduce the problem
This isn't quite standalone, because it needs a database, but we have the following function:
```php
<?php
function stmt_prep_assoc($stmt, &$row) {
        $meta = $stmt->result_metadata();
        while ($field = $meta->fetch_field()) {
                $parameters[] = &$row[$field->name];
        }
        
        call_user_func_array([$stmt, 'bind_result'], $parameters);
        return;
}
?>
```

This is a common pattern in PHP, and used to work around the lack of `get_result()` and `fetch_assoc_array()` provided by the mysqlnd drivers (which Hack is also missing -cf. #2368).

At the use-site, you would see:
```php
<?php

$row = [];
stmt_prep_assoc($stmt, $row);
$stmt->fetch();

?>
``` 

### Actual result
`$row` is an empty array.

### Expected result
Should result in the results of `$stmt` being loaded into `$row` as an associative array.

**Comment by elfprince13** [comment]
Oddly enough, this works:

```php
<?php


$foo = function (&$bar, &$baz) {
	echo "before: bar = $bar, baz = $baz";
	$bar = 2;
	$baz = 3;
	echo "after: bar = $bar, baz = $baz";
	return;
};


$vars = ['bar' => 0, 'baz' => 0];

$args = [];
$args[] = &$vars['bar'];
$args[] = &$vars['baz'];

echo "Before:";
print_r($vars);

call_user_func_array($foo, $args);

echo "After:";
print_r($vars);

?>
```

```
[thomas@frontend-dev-vm] web-hack $ php -f test_ref.php
Before:Array
(
    [bar] => 0
    [baz] => 0
)
before: bar = 0, baz = 0after: bar = 2, baz = 3After:Array
(
    [bar] => 2
    [baz] => 3
)
[thomas@frontend-dev-vm] web-hack $ hhvm test_ref.php
Before:Array
(
    [bar] => 0
    [baz] => 0
)
before: bar = 0, baz = 0after: bar = 2, baz = 3After:Array
(
    [bar] => 2
    [baz] => 3
)
[thomas@frontend-dev-vm] web-hack $
```

This makes me wonder if it's a bug specifically with the implementation of `mysqli_stmt::bind_result`?

**Comment by Argonautic** [comment]
Thomas: If you could make some code that
(a) uses bind_result directly on variables
(b) uses bind_result directly on associative array entries
(c) uses stmt_prep_assoc as it exists in our code base,

**Comment by elfprince13** [comment]
@WizKid - I've done some more debugging, and it seems to happen when our selection query has a column of type `BIT(1)`. I saw [your blog post](https://hhvm.com/blog/3689/implementing-mysqli) and wonder if you have any insights.

Unfortunately, as far as I can tell, HHVM fails silently in these cases.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

`\stmt_prep_assoc()` and `ext/mysqli were removed in hhvm [4.9.0](https://hhvm.com/blog/2019/06/10/hhvm-4.9.0.html).
