### ISSUE TITLE
[hackc] bracketed variable variables aren't supported in string interpolation

### ISSUE THREAD

**Issue by craigcarnell** [facebook/hhvm#8223]
### HHVM Version

HipHop VM 3.26.3 (rel)
Compiler: 1527193607_720265267
Repo schema: ac3cdc27d1cbfe6b4dc78fec3c3e88dd2ee9b239

### Operating System and Version

Ubuntu 16.04

### Standalone code, or other way to reproduce the problem

```
$defaultTaxString = $currentTaxString = '';

        $rateToVariable = array(
            'defaultTaxString' => 'defaultTaxes',
            'currentTaxString' => 'currentTaxes',
        );
        foreach ($rateToVariable as $rateVariable => $rateArray) {
            if ($$rateArray && is_array($$rateArray)) {
                $$rateVariable = '';
                foreach ($$rateArray as $classId => $rate) {
                    if ($rate) {
                        $$rateVariable .= sprintf("WHEN %d THEN %12.4f ", $classId, $rate / 100);
                    }
                }
                if ($$rateVariable) {
                    $$rateVariable = "CASE {$taxClassField} {$$rateVariable} ELSE 0 END";
                }
            }
        }
```
### Actual result

$defaultTaxString = 'CASE price_index.tax_class_id {$defaultTaxString} ELSE 0 END'

### Expected result

Under PHP 7.1:
$defaultTaxString should be: CASE price_index.tax_class_id WHEN 2 THEN       0.2000  ELSE 0 EN

**Comment by craigcarnell** [comment]
Any updates on this issue?

**Comment by fredemmott** [comment]
We deprioritize (and often aren't able to look at) issues that don't have an isolated example, especially if they don't identify a specific issue.

That said,  here is a true isolated example:

```
<?php
$foo = 'hello';
$bar = 'foo';
echo "{$$bar}\n";
```

```
$ hhvm  test.php
{$foo}
$ hhvm -d hhvm.hack_compiler_default=false test.php
hello
```

**Comment by fredemmott** [comment]
FB: D8543351

**Comment by craigcarnell** [comment]
@fredemmott Thanks 👍 what version is the fix included in?

**Comment by fredemmott** [comment]
It's not yet in any released versions or release branches
