### ISSUE TITLE
Could not open extension /etc/hhvm/ZendGuardLoader.so

### ISSUE THREAD

**Issue by wangmao** [facebook/hhvm#8228]
### HHVM Version

>HipHop VM 3.15.3 (rel)
Compiler: tags/HHVM-3.15.3-0-g965cd8d30670726d88720412c3384225a2da011d
Repo schema: 7f22464926cb7fc3a19c6af88309c612a8581c55

965cd8d30670726d88720412c3384225a2da011d Sat Nov 19 05:54:55 2016

### Operating System and Version

>CentOS 7.2 / Linux version 3.10.0-514.26.2.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ) #1 SMP Tue Jul 4 15:04:05 UTC 2017

### Standalone code, or other way to reproduce the problem

>Need to load ZendGuardloader.

### Actual result

>Uncaught exception: Could not open extension /etc/hhvm/ZendGuardLoader.so: /etc/hhvm/ZendGuardLoader.so: undefined symbol: zend_execute

### Expected result

**Comment by fredemmott** [comment]
3.15 is unsupported, and we do not support Zend extensions.
