### ISSUE TITLE
`stream_await` timeout parameter has significant behavior effects beyond timeouts

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#8230]
### HHVM Version

3.27 preview

### Operating System and Version

MacOS High Sierra
### Standalone code, or other way to reproduce the problem

```
<?hh

stream_set_blocking(STDIN, false);
HH\Asio\join(stream_await(STDIN, STREAM_AWAIT_READ)); // blocks forever
HH\Asio\join(stream_await(STDIN, STREAM_AWAIT_READ, INF)); // blocks forever
HH\Asio\join(stream_await(STDIN, STREAM_AWAIT_READ, 0xffffffff)); // works fine
$magic = (float) ((0xffffffff << 21) | 0xffffffff);
HH\Asio\join(stream_await(STDIN, STREAM_AWAIT_READ, $magic)); // works fine
HH\Asio\join(stream_await(STDIN, STREAM_AWAIT_READ, $magic + 1)); // instantly returns
$magic = (float) ((0xffffffff << 22) | 0xffffffff);
HH\Asio\join(stream_await(STDIN, STREAM_AWAIT_READ, $magic)); // blocks forever
var_dump(stream_get_contents(STDIN));
```

Send data, newlines, eof (^D) etc

### Actual result

As above. 'blocks forever' means even in the present of data

### Expected result

- timeout value of 0 should mean no timeout, but should return as soon as data is available
- timeout parameter should only affect timeout

**Comment by fredemmott** [comment]
The highest safe value is roughly `(PHP_INT_MAX / 1000) - 1.1`

**Comment by fredemmott** [comment]
@jano : are you also able to take a look at this one? In particular, the `0` case is strange - I don't see anything particularly obvious in FileAwait for why we should not return if we don't construct a timeout case

**Comment by jano** [comment]
All of your "blocks forever" cases work fine for me (and reading the code, I can't see why they would behave differently). The $magic + 1 probably causes int64 to overflow so it ends up waiting for a negative timeout.

**Comment by fredemmott** [comment]
huh, possibly a portability issue. Also can't reproduce in the linux builds.

**Comment by fredemmott** [comment]
Fixed by https://github.com/facebook/hhvm/commit/93c31ec66fdd74eb691b6e400de7ffc465d14a5d
