### ISSUE TITLE
Commit 6a19df5 broke aarch64 build

### ISSUE THREAD

**Issue by swalk-cavium** [facebook/hhvm#8232]
### HHVM Version

/data2/swalk/play.255b103/hhvm$ hphp/hhvm/hhvm --version
HipHop VM 3.28.0-dev (rel)
Compiler: tags/gcc-4.6-20960-g255b10366675b25f51bb7251372e4009c55d8d42
Repo schema: 971a9be218b58bc449ff940eb959369b561f2421

### Operating System and Version

ubuntu 16.04

### Standalone code, or other way to reproduce the problem

https://docs.hhvm.com/hhvm/installation/building-from-source

### Actual result

/data2/swalk/play.6a19df5/hhvm/hphp/runtime/vm/memo-cache.cpp:919:9: error: ‘class folly::F14ValueMap<long unsigned int, HPHP::memoCacheDetail::CellWrapper, HPHP::memoCacheDetail::SharedOnlyKeyHasher, std::equal_to<long unsigned int>, HPHP::req::Allocator<std::pair<const long unsigned int, HPHP::memoCacheDetail::CellWrapper>, HPHP::type_scan::Action::Conservative<std::pair<const long unsigned int, HPHP::memoCacheDetail::CellWrapper> > > >’ has no member named ‘insert_or_assign’
   cache.insert_or_assign(key, CellWrapper{val});
         ^     
### Expected result

Clean build

This commit for hhvm is expecting a later version of the folly library
https://github.com/facebook/hhvm/commit/6a19df50cd2ce4dc7ea0e7a7505f706cd29233c6

hhvm is currently using this version of folly

git submodule status
3f0f6c9764beced284aaeeae53536208af8d0963 folly/src (v2018.03.26.00-3-g3f0f6c9)

According to the git log for folly, this was 441 commits ago.
 441 * 3f0f6c9 Forward iterator for F14VectorMap

The folly commit which introduced insert_or_assign was 17 commits ago.
  17 * b51d740 heterogeneous mutation for F14 maps and sets     //<<---

**Comment by fredemmott** [comment]
> The folly commit which introduced insert_or_assign was 17 commits ago.

No - that added heterogenuos key support.

**Comment by fredemmott** [comment]
https://github.com/facebook/folly/blob/3f0f6c9764beced284aaeeae53536208af8d0963/folly/container/F14Map.h#L351 shows this existing in the pinned version; we're also successfully building on x86_64 with this pinned version.

**Comment by fredemmott** [comment]
See https://docs.hhvm.com/hhvm/installation/building-from-source#requirements__gcc-5

**Comment by fredemmott** [comment]
Tag is wrong apparnetly

**Comment by jim-saxman** [comment]
Hi Steve, 

I also see this issue. I've been able to workaround it by cherry-picking 19c316ae (enables F14 intrinsics for Aarch64) in the third-party/folly/src/folly tree. I'm also cherry-picking 101c87e4 (crc32), but it's not required to complete a successful build. 

-Jim

**Comment by fredemmott** [comment]
Happy to review a PR, otherwise this will hopefully be resolved the next time we update folly. Sorry, but we're not able to actively support external builds beyond our supported platforms.

**Comment by swalk-cavium** [comment]
This issue has been resolved in a later version of folly as Jim Saxman points out above.
Any estimate for when a later version of folly will be used?

**Comment by fredemmott** [comment]
> @fredemmott - I think you're intertwingling issues. This was a Ubuntu failure.

Ubuntu, but either with a modified tree (x86_64), or an architecture we're not actively supporting externally.

> Any estimate for when a later version of folly will be used?

Sorry, this isn't on a schedule; happy to take PRs though (the PR to this repository should both update the submodule and clean up patches/ to remove fixes that are no longer needed).

**Comment by swalk-cavium** [comment]
This was resolved by
https://github.com/facebook/hhvm/pull/8237
