### ISSUE TITLE
hh_client: strange behaviour with `?->` operator

### ISSUE THREAD

**Issue by baptistemarchand** [facebook/hhvm#8234]
### Version
```
$ hh_client --version
hh-be385b2bdcc79e0129b423926959ea8622458ec8-3.25.0 Thu Mar 15 19:58:29 2018
```

### Operating System and Version
macOs High Sierra 10.13.4

### Repro code
```php
$e = new Exception();
$e?->getMessage();
if (false){}
$e?->getMessage();
```

### Actual result
When running `hh_client` I get an error on the first call to `getMessage()` **but not on the second one**.
The error is `You are using the ?-> operator but this object cannot be null.`

### Expected result
The expected behaviour is to have an error on **both** calls to `getMessage()`.
If I remove the `if (false){}` line it works as expected.

Thank you for your help!

**Comment by fredemmott** [comment]
Looks like this was fixed by @CatherineGasnier  in 88be75956f68cad4b549d1ebe2d97aae1a8d7c3c
