### ISSUE TITLE
Fail to build HHVM on AARCH64 fedora 28

### ISSUE THREAD

**Issue by taitringuyen** [facebook/hhvm#8236]
### HHVM Version

master branch 3.28-dev

commit 7701cbcf6e13135d869ddd467d9e27dba7ddff7f (HEAD -> master, origin/master, origin/HEAD)
Author: Manuel Fahndrich <fahndrich@fb.com>
Date:   Tue Jun 19 18:43:25 2018 -0700

    Fix blunder
    
    Summary: When reversing logic, exists turns into forall duh.

### Operating System and Version

Aarch64 Fedora release 28 (Twenty Eight)

### Standalone code, or other way to reproduce the problem

mkdir build && cd build
cmake .. && make hack -j8

### Actual result

[NOTE] Package core_kernel is already installed (current version is v0.11.0).
[NOTE] Package ppx_deriving is already installed (current version is 4.2.1).
[NOTE] Package visitors is already installed (current version is 20180513).
Built target opam.stamp
[WARNING] Running as root is not recommended
Finished, 2 targets (2 cached) in 00:00:00.
Finished, 2 targets (0 cached) in 00:00:00.
Finished, 30 targets (30 cached) in 00:00:00.
+ ocamlfind ocamldep -package core_kernel -package visitors.runtime -package unix -package str -package bigarray -package ppx_deriving.std -modules hh_server.ml > hh_server.ml.depends
File "hh_server.ml", line 1:
Error: Error while running external preprocessor
Command line: /media/ttnguyen/web_workloads/hhvm_installation/hhvm_fedora28_2/hphp/hack/src/_build/.opam/system/lib/ppx_deriving/./ppx_deriving /media/ttnguyen/web_workloads/hhvm_installation/hhvm_fedora28_2/hphp/hack/src/_build/.opam/system/lib/ppx_deriving/./ppx_deriving_show.cma /media/ttnguyen/web_workloads/hhvm_installation/hhvm_fedora28_2/hphp/hack/src/_build/.opam/system/lib/ppx_deriving/./ppx_deriving_eq.cma /media/ttnguyen/web_workloads/hhvm_installation/hhvm_fedora28_2/hphp/hack/src/_build/.opam/system/lib/ppx_deriving/./ppx_deriving_ord.cma /media/ttnguyen/web_workloads/hhvm_installation/hhvm_fedora28_2/hphp/hack/src/_build/.opam/system/lib/ppx_deriving/./ppx_deriving_enum.cma /media/ttnguyen/web_workloads/hhvm_installation/hhvm_fedora28_2/hphp/hack/src/_build/.opam/system/lib/ppx_deriving/./ppx_deriving_iter.cma /media/ttnguyen/web_workloads/hhvm_installation/hhvm_fedora28_2/hphp/hack/src/_build/.opam/system/lib/ppx_deriving/./ppx_deriving_map.cma /media/ttnguyen/web_workloads/hhvm_installation/hhvm_fedora28_2/hphp/hack/src/_build/.opam/system/lib/ppx_deriving/./ppx_deriving_fold.cma /media/ttnguyen/web_workloads/hhvm_installation/hhvm_fedora28_2/hphp/hack/src/_build/.opam/system/lib/ppx_deriving/./ppx_deriving_create.cma /media/ttnguyen/web_workloads/hhvm_installation/hhvm_fedora28_2/hphp/hack/src/_build/.opam/system/lib/ppx_deriving/./ppx_deriving_make.cma '/tmp/camlppx453a83' '/tmp/camlppxd9e1c8'

Command exited with code 2.
Compilation unsuccessful after building 1 target (0 cached) in 00:00:00.
make[4]: *** [Makefile:206: _build/hack.stamp] Error 10
make[3]: *** [hphp/hack/CMakeFiles/hack.dir/build.make:57: hphp/hack/CMakeFiles/hack] Error 2
make[2]: *** [CMakeFiles/Makefile2:1381: hphp/hack/CMakeFiles/hack.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:1393: hphp/hack/CMakeFiles/hack.dir/rule] Error 2
make: *** [Makefile:450: hack] Error 2

### Expected result

No issue seen on a x86 Fedora 28 system

**Comment by taitringuyen** [comment]
The issue occurs since tag 3.26.0. I could build 3.25.3 properly.

**Comment by fredemmott** [comment]
We only actively support x86_64, and on MacOS or various versions of Debian/Ubuntu.

**Comment by taitringuyen** [comment]
Pulling in this ocaml patch helps fixing this issue.

https://github.com/ocaml/ocaml/pull/1330/commits/4274dfe22ae37c4c5589a6fe7fe9d53d62013df5
