### ISSUE TITLE
[hackc] various Hack-only keywords can't be used in PHP files

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#8240]
### HHVM Version

3.27

### Operating System and Version

MacOS High Sierra
### Standalone code, or other way to reproduce the problem

```
<?php

class inout {}

function foo(): inout {
  return new inout();
}

var_dump(foo());
class bar extends inout {}
var_dump(new bar())
```

More examples of both keywords and situations (replace `<?hh` with `<?php`) : https://github.com/hhvm/definition-finder/blob/fd0ab8190bd302580d318a7cb0c538d571250c99/tests/NamingTest.php#L28 downwards
### Actual result

```
fredemmott-pro:definition-finder fredemmott$ hhvm /tmp/test.php

Fatal error: Uncaught Error: A type specifier is expected here. in /private/tmp/test.php:5
Stack trace:
#0 {main}
```

### Expected result

```
fredemmott-pro:definition-finder fredemmott$ php --version
PHP 7.1.16 (cli) (built: Apr  1 2018 13:14:42) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
fredemmott-pro:definition-finder fredemmott$ php /tmp/test.php
object(inout)#1 (0) {
}
object(bar)#1 (0) {
}
fredemmott-pro:definition-finder fredemmott$ hhvm -d hhvm.hack_compiler_default=false /tmp/test.php
object(inout)#1 (0) {
}
object(bar)#1 (0) {
}
```

**Comment by melechi** [comment]
Hi,

I'm still having issues with this. I think it may be related but could be wrong so please correct me if I am.

I'm using a 3rd party library which is including this library:
https://github.com/FGrosse/PHPASN1

It has class names such as "Integer", "Nul", "Boolean" etc. These are triggering E_ERROR messages such as: 
"Cannot use 'FG\ASN1\Universal\Integer' as class name as it is reserved".

This was working in previous versions. I am wondering if this is related to this issue or there was a previous change which I missed which caused this to be reserved?
