### ISSUE TITLE
mysqli->bind_param fails if values are passed via splat syntax

### ISSUE THREAD

**Issue by Argonautic** [facebook/hhvm#8246]
mysqli bind_param doesn't seem to work as expected if the values are passed to bind_param via splat syntax. Curiously, not using splat syntax and hardcoding the indexes of each value does work when passing those into bind_param.

### HHVM Version

3.62.2

### Operating System and Version

Debian 3.16.43-2+debu8u3. Not using docker or other container tech

### Standalone code, or other way to reproduce the problem

Dependent on a db so not copy paste reproducible, unfortunately
```
function testDbInsert($columns, $types, ...$values) {
    global $mysqli;
    mysqliInit();

    $qqS = [];
    foreach ($columns as $column) {
        $qqS[] = '?';
    }

    $qqS = implode(', ', $qqS);
    $columns = implode(', ', $columns);

    $sql = "INSERT INTO hack_test ($columns) VALUES ($qqS)\n";
    $stmt = null;  

    if (!($stmt = $mysqli->prepare($sql)) ||
        !$stmt->bind_param($types, ...$values) ||
        !$stmt->execute()) {
        
        echo "Insert Unsuccessful\n";
        echo $stmt->error . "\n";
    } else {
        echo 'Insert Successful';
    }
}
testDbInsert(['hack_varchar', 'hack_int'], 'si', 'test_str', 15);
```

### Actual result

Warning: Argument 1 not passed as reference in /home/kerm/geopipe/deps/web-hack/sql_data.php on line 105
Insert Unsuccessful

### Expected result

Insert Successful

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Support for ext/mysqli has been removed in hhvm [4.9.0](https://hhvm.com/blog/2019/06/10/hhvm-4.9.0.html) and `&$references` have been [removed](https://hhvm.com/blog/2019/10/01/deprecating-references.html) from the language.
