### ISSUE TITLE
Make `hh_client lsp` more selective about error messages

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#8253]
3.27.0

vscode shows error messages, and makes the output tab active when they happen (as you type). This is very distracting. Perhaps these should be gated by a `--debug` flag or similar?

Examples:

- [ ] Request textDocument/hover failed. Message: not a valid file url 'git://....'
- [ ] Request textDocument/rangeFormatting failed. Message: Formatter internal error
- [ ] Request textDocument/documentSymbol failed. Message: Failure("Inconsistent trivia classification: Received ignore_error, but failed to match regexp for FIXME or IGNORE_ERROR. Either the lexer hasa bug in its trivia classification, or the lowerer is more restrictive than the lexer."

**Comment by ljw1004** [comment]
These are interesting examples.

`textDocument/hover` - this sounds like an illegal request made by VSCode. In general how should an LSP server behave when it receives an illegal request? That's a question for @dbaumer.

The other two examples are internal bugs in the HackLSP server. The LSP spec specifically has an error case `InternalError` to report in such cases. That's what HackLSP is using.

I feel uneasy about deviating from the LSP spec here - the `--debug` would really be papering over it. Let's get a clear answer about what is the intended behavior first.

To help this, it'd be great if we could get concrete repros. One way to do this (assuming the Hack VSCode extension is built on top of vscode-languageserver-node) is documented here: https://microsoft.github.io/language-server-protocol/inspector/

**Comment by fredemmott** [comment]
`textDocument/hover`: this one appears when using the source control view in a git-controlled repository

Inconsistent trivia classification:

```
<?hh

/* HH_FIXME
```

This correctly raises the typechecker errors below, but also raises the LSP error.

```
test.php:4:1,1: HH_FIXME wrong format, expected '/* HH_FIXME[ERROR_NUMBER] */' (Parsing[1001])
test.php:5:1,0: unterminated comment (Parsing[1004])
```

**Comment by fredemmott** [comment]
re the first case: I don't see the specification mandating file:// URIs.

**Comment by ljw1004** [comment]
@fredemmott What initialize message does VSCode send prior to that git:// request? It feels weird that every LSP server should be expected to handle arbitrary URI protocols.

**Comment by fredemmott** [comment]
Ah, it's fixable via extension configuration, separate to the specification/LSP: the extension can just say it only wants file:// URIs.

I'm unsure if it's correct or not for error messages to be sent in response to commands that fail because of syntax errors in the hack file - but it turns out hte extension can also choose to disable the 'automatically switch to the output pane on error' behavior, which at least lets us paper over this until there's consensus.

**Comment by fredemmott** [comment]
Addressing this via extension change: https://github.com/PranayAgarwal/vscode-hack/pull/26
