### ISSUE TITLE
[hackc] Class names case sensitive under certain circumstances

### ISSUE THREAD

**Issue by bredman** [facebook/hhvm#8255]
### HHVM Version

```
root@dd622ea862b0:/mnt/hh_test#hh_client--version
hh-16546c16a279ba0898b2a9ede51babfefb05ee15-3.27.0MonJun1819:15:252018
root@dd622ea862b0:/mnt/hh_test#hhvm--version
HipHopVM3.27.0(rel)
Compiler:1529349195_321812285
Reposchema:c044d1d8129f7eab67490c16bdf55e3c9d408543
root@dd622ea862b0:/mnt/hh_test#
```

Also repros under `3.26.3`

### Operating System and Version

MacOS High Sierra - Docker

### Standalone code, or other way to reproduce the problem

`main-file.php`
```
<?hh

include(dirname('__FILE__') . '/include-file.php');

use Test\Type\TType;

function main(){
        var_dump(TType::STOP);
        var_dump(TTYPE::STOP);
        echo "DONE\n";
}

main();
```
`include-file.php`
```
<?hh

namespace Test\Type;

class TType
{
  const STOP   = 0;
  const VOID   = 1;
}
```
`one-file.php`
```
<?hh

namespace Test\Type;

class TType
{
  const STOP   = 0;
  const VOID   = 1;
}

function main(){
        var_dump(TType::STOP);
        var_dump(TTYPE::STOP);
        echo "DONE\n";
}

main();
```

### Actual result

```
root@dd622ea862b0:/mnt/hh_test# hhvm one-file.php
int(0)
int(0)
DONE
root@dd622ea862b0:/mnt/hh_test# hhvm main-file.php
int(0)

Fatal error: Uncaught Error: Class undefined: TTYPE in /mnt/hh_test/main-file.php:9
Stack trace:
#0 /mnt/hh_test/main-file.php(13): main()
#1 {main}
root@dd622ea862b0:/mnt/hh_test#
```

### Expected result

Expected that `TTYPE::STOP` resolves properly in both `main-file.php` and `one-file.php`

**Comment by fredemmott** [comment]
Not reproducible with legacy frontend

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which are unlikely to be worked on.

This issue only applies to Hack code that doesn't pass the Hack type system. Now that PHP support is gone, a programmer will always be informed of this case difference with a red squiggly. Hack is case sensitive and the runtime will become case sensitive any day now / soon (TM).

If this issue isn't resolved just yet, I'd imagine it being fixed once hhvm flips the switch from warn on case mismatch to erroring.
