### ISSUE TITLE
Hack LSP coverage check request does not work if a file has untyped regions

### ISSUE THREAD

**Issue by PranayAgarwal** [facebook/hhvm#8257]
### HHVM Version

3.27.0

### Operating System and Version

Ubuntu 18.04

### Standalone code, or other way to reproduce the problem

Run the Hack typechecker on a repo in LSP mode and send a (non-standard) `textDocument/typeCoverage` request for a file.

### Actual result

If the file has untyped regions, the typechecker returns the following error:

code: `-32001`
message: `Invalid_argument("Prefix has not been set!")`
stack: 
```Raised at file "utils/utils.ml", line 92, characters 12-41
Called from file "utils/relative_path.ml" (inlined), line 33, characters 2-68
Called from file "utils/relative_path.ml", line 96, characters 28-44
Called from file "utils/pos_embedded.ml", line 246, characters 11-51
Called from file "utils/pos_embedded.ml", line 254, characters 38-54
Called from file "typing/coverage_level.ml", line 179, characters 9-25
Called from file "list.ml", line 96, characters 24-34
Called from file "typing/coverage_level.ml", line 190, characters 2-37
Called from file "client/clientLsp.ml", line 1140, characters 16-61
Called from file "client/clientLsp.ml", line 2191, characters 4-79
Called from file "client/clientLsp.ml", line 2339, characters 6-65
```

### Expected result

Typechecker should return coverage result. This works fine if the file is 100% covered.

**Comment by PranayAgarwal** [comment]
Can confirm that this was working fine in 3.26.3 but broke starting 3.27.0

**Comment by ssandler** [comment]
My repro steps were:
- Clone https://github.com/hhvm/hhast and check out `origin/master`
- `brew install hhvm`
```
hhvm --version:
HipHop VM 3.27.1-0brew (rel)
```
- `killall hh_server`, then `hh_client` within my working copy of `hhvm/hhast`
- quit and reopen VSCode with `hhvm/hhast` working copy as working directory, and `find_position.php` as the current open file. The coverage % / outline is not present in the bottom panel.

Then repeated same steps with `hhvm-nightly` and the coverage outline did show up.

**Comment by fredemmott** [comment]
Possibly ff3d8c9678357f60cb1e33924dc8ffa2910e63d5

**Comment by PranayAgarwal** [comment]
This (or at least a similar bug) was fixed by https://github.com/slackhq/vscode-hack/pull/64, so closing this for now till it reappears.
