### ISSUE TITLE
Add a way to specify `hackfmt` options via `.hhconfig`

### ISSUE THREAD

**Issue by ssandler** [facebook/hhvm#8266]
### HHVM Version

3.27.1

### Operating System and Version

MacOS High Sierra

### Standalone code, or other way to reproduce the problem

The LSP currently makes it possible to specify using tabs vs. spaces, and the indent width (which covers the --tabs and --indent-width arguments of `hackfmt`.  It would be great to be able to specify `--line-width` somehow as well.

**Comment by fredemmott** [comment]
Given the LSP already supports editor-provided formatting settings (in `FormattingOptions`), we should probably extend that.

If that's impractical, an initializationOption would likely be best

**Comment by fredemmott** [comment]
Following discussion in slack:

- `.hhconfig` for now
- in case of conflict with LSP formatting options, editor wins to avoid confusing/frustrating users
- example settings: `hackfmt.tabs=true`, `hackfmt.line_width=180`

**Comment by ssandler** [comment]
Closing as this was fixed in #8422
