### ISSUE TITLE
hh_client namespace resolution in decl mode

### ISSUE THREAD

**Issue by ssandler** [facebook/hhvm#8268]
### HHVM Version

HipHop VM 3.27.0-1-slack (rel), 3.27.1, 2018.07.23 nightly
Compiler: heads/3.27.0-slack-0-g9db89dc930f3d0d0b1f765535032a05eb8846312
Repo schema: 458543a82f60df1bd7772634f8e7ae038c268162

This is built from the HHVM-3.27 branch from 2 days ago.

### Operating System and Version

MacOS High Sierra

### Standalone code, or other way to reproduce the problem

```
<?hh // decl

namespace Foo\Bar\Baz;

use type Foo\Qux;

class Squizz extends Qux {}

namespace Foo;

class Qux {}
```

echo `assume_php=false` > .hhconfig

### Actual result

This fails the type checker with `Unbound name: Foo\Bar\Baz\Qux (an object type) (Naming[2049])`, but it should pass. It's looking for `Foo\Bar\Baz\Qux` rather than `Foo\Qux` despite the `use type` statement.

Interestingly, it **only** fails in decl mode. Removing `// decl`, the type checker passes.

I tried several things to see if I could get the type checker to pass in decl mode - leading slash on the `use type \Foo\Qux`, `use Foo\Qux`, `use namespace \Foo`, etc. but the only thing that worked as a workaround was fully qualifying  as `class Squizz extends \Foo\Qux`.

### Expected result

The type checker passes.

**Comment by fredemmott** [comment]
I can't reproduce this with 3.27.1, or the nightly builds. @kmeht , does this look familiar?

**Comment by ssandler** [comment]
Good to know, I'll install a fresh 3.27.1 and report back to confirm that fixes it.

**Comment by fredemmott** [comment]
Reproduced, thanks

**Comment by Wilfred** [comment]
Is this still relevant now we're removing decl mode?

**Comment by ssandler** [comment]
I don't think it's important to fix given decl mode is going away. Closing.
