### ISSUE TITLE
 Can you externalize your parallel programming library?

### ISSUE THREAD

**Issue by UnixJunkie** [facebook/hhvm#8269]
Hello,

Someone told me that there is a shared memory parallel programming library
hidden in there.

It would be quite nice if this could be released as a separate library,
so that the whole ocaml community could benefit from it.

Thanks a lot,
F.

**Comment by UnixJunkie** [comment]
That's probably what's under:
hphp/hack/src/heap/

**Comment by fredemmott** [comment]
I don't think we can currently spare the time to split this out cleanly and maintain it as a separate project - though it is MIT licensed, so FB aren't the only people who can do this.

I'll ask some people who might be interested in supporting this, but I think the answer is going to be no, just from a "is this the best way for us to spend our time?" perspective

**Comment by UnixJunkie** [comment]
OK, just to check, can you confirm that this code base is the reference one,
maintained and the most up to date?

Also, to ease the work of others who could do this, can you point out some example code using this library?
Simple, if possible.

**Comment by rvantonder** [comment]
@UnixJunkie [wish granted](https://discuss.ocaml.org/t/a-parallel-and-shared-memory-library-based-on-hacks-implementation/3428).

**Comment by UnixJunkie** [comment]
thanks a lot!
