### ISSUE TITLE
[hackc] case sensitivity: Object cast broken (`object` is fine)

### ISSUE THREAD

**Issue by beatscode** [facebook/hhvm#8270]
### HHVM Version
hhvm --version 
3.27

### Operating System and Version
Docker for mac / MacOS Sierra

### Standalone code, or other way to reproduce the problem
https://github.com/danielmewes/php-rql/blob/1.16.0/src/rdb/connection.php#L102
```
  $jsonQuery = array(pb\Query_QueryType::PB_START, $jsonTerm, (Object)$globalOptargs);
```
### Actual result

> If applicable, please copy-paste output from `hhvm` or `hh_client`
![1112b072-a6a0-441d-9ab3-746fd12da4b7](https://user-images.githubusercontent.com/1777648/43195156-35128820-8fd2-11e8-98e6-f0b91bf08f34.png)

### Expected result
No error

**Comment by fredemmott** [comment]
```
<?php

$x = ['a' => 123];
var_dump((Object) $x);
```

```
fredemmott-pro:hhtest fredemmott$ hhvm test.php

Fatal error: Uncaught Error: Encountered unexpected token '$x'. in /private/tmp/hhtest/test.php:4
Stack trace:
#0 {main}
fredemmott-pro:hhtest fredemmott$ hhvm -d hhvm.hack_compiler_default=false test.php
object(stdClass)#1 (1) {
  ["a"]=>
  int(123)
}
```

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

The `(object)` cast was removed in hhvm [4.24.0](https://hhvm.com/blog/2019/09/23/hhvm-4.24.0.html).
