### ISSUE TITLE
Hack type system unsoundness: mutable arguments (inout or objects), shape subtyping and bounded quantification

### ISSUE THREAD

**Issue by pbl64k** [facebook/hhvm#8287]
### HHVM Version

    lepin@ap01dvgb:~/Sandbox/hack/soundness$ hhvm --version
    HipHop VM 3.27.1 (rel)
    Compiler: 1532025657_047601700
    Repo schema: af4015d91bd87a3d1aa40418d909ce80bb2a0bf3
    lepin@ap01dvgb:~/Sandbox/hack/soundness$ hh_client --version
    hh-e6d25982534cd57e1e7fa1e990dcb876c981b957-3.27.1 Thu Jul 19 18:43:08 2018

Unfortunately, I'm currently unable to test this on more recent versions. Search for previously reported issues yielded no results.

### Operating System and Version

    lepin@ap01dvgb:~/Sandbox/hack/soundness$ lsb_release -a
    No LSB modules are available.
    Distributor ID:	Ubuntu
    Description:	Ubuntu 16.04.2 LTS
    Release:	16.04
    Codename:	xenial

Should be independent of the OS.

### Standalone code, or other way to reproduce the problem

Public gist: https://gist.github.com/pbl64k/51610d55229dc67e4b6df20aefe893df

runme.hh:

    <?hh
    require_once(__DIR__ . '/soundness.hh');
    breakage();

soundness.hh:

    <?hh // strict
    final class Dummy
    {
        final public function bork(): void
        {
            print('Bork.' . "\n");
        }
    }
    type Narrow = shape(...);
    type Broad = shape('dummy' => Dummy);
    type Dad = shape('child' => Narrow);
    function naive<+Tx as Dad>(inout Tx $parent): void
    {
        $parent['child'] = shape();
    }
    function breakage(): void
    {
        $oops = shape('child' => shape('dummy' => new Dummy()));
        naive(inout $oops);
        $oops['child']['dummy']->bork();
    }

### Actual result

    lepin@ap01dvgb:~/Sandbox/hack/soundness$ hh_client
    No errors!
    lepin@ap01dvgb:~/Sandbox/hack/soundness$ hhvm runme.hh 
    
    Notice: Undefined index: dummy in /home/lepin/Sandbox/hack/soundness/soundness.hh on line 24
    
    Fatal error: Uncaught exception 'BadMethodCallException' with message 'Call to a member function bork() on a non-object (null)' in /home/lepin/Sandbox/hack/soundness/soundness.hh:24
    Stack trace:
    #0 /home/lepin/Sandbox/hack/soundness/runme.hh(5): breakage()
    #1 {main}
    lepin@ap01dvgb:~/Sandbox/hack/soundness$

### Expected result

Typechecker should prevent this kind of usage. Note that defining naive with `Dad` instead of `<+Tx as Dad>` will result in:

    lepin@ap01dvgb:~/Sandbox/hack/soundness$ hh_client
    soundness.hh:25:20,26: The field dummy is undefined (Typing[4108])
      soundness.hh:13:29,34: You might want to check this out
    lepin@ap01dvgb:~/Sandbox/hack/soundness$

Which is correct behavior, although the error message could be cryptic for those unaware of dangers of mixing mutability with width & depth subtyping.

**Comment by Wilfred** [comment]
I can replicate this on the latest HHVM, FWIW.

**Comment by pbl64k** [comment]
The problem can also be triggered without using `inout` parameters, simply by using objects which are passed by reference anyway. I can repro the problem as early as:

    lepin@web3:~/Sandbox/hack/soundness$ hhvm --version
    HipHop VM 3.21.3 (rel)
    Compiler: tags/HHVM-3.21.3-0-gce34e5458e6a75931438a2d8fc41b91454a2f2b2
    Repo schema: 90ed4216b98563d0585cf5c87959dc9ff7c2e1a1
    lepin@web3:~/Sandbox/hack/soundness$ hh_client --version
    ce34e5458e6a75931438a2d8fc41b91454a2f2b2 Fri Sep 22 21:03:07 2017

It probably existed from the beginning, but I don't have earlier version handy. Public gist updated with repro without using `inout` for 3.27, here's the version for 3.21:

`runme2.hh`:

    <?hh
    require_once(__DIR__ . '/soundness2.hh');
    breakage2();

`soundness2.hh`:

    <?hh // strict
    final class Dummy2
    {
        final public function bork(): void
        {
            print('Bork.' . "\n");
        }
    }
    type Narrow2 = shape();
    type Broad2 = shape('dummy' => Dummy2);
    type Dad2 = shape('child' => Narrow2);
    final class Breakage<Tx>
    {
        final public function __construct(public Tx $shape) { }
    }
    function naive2<Tx as Dad2>(Breakage<Tx> $parent): void
    {
        $parent->shape['child'] = shape();
    }
    function breakage2(): void
    {
        $oops = new Breakage(shape('child' => shape('dummy' => new Dummy2())));
        naive2($oops);
        $oops->shape['child']['dummy']->bork();
    }

The result is essentially the same as for the first repro:

    lepin@web3:~/Sandbox/hack/soundness$ hh_client
    No errors!
    lepin@web3:~/Sandbox/hack/soundness$ hhvm runme2.hh 

    Notice: Undefined index: dummy in /home/lepin/Sandbox/hack/soundness/soundness2.hh on line 29

    Fatal error: Uncaught exception 'BadMethodCallException' with message 'Call to a member function bork() on a non-object (null)' in /home/lepin/Sandbox/hack/soundness/soundness2.hh:29
    Stack trace:
    #0 /home/lepin/Sandbox/hack/soundness/runme2.hh(5): breakage2()
    #1 {main}
    lepin@web3:~/Sandbox/hack/soundness$

My guess is that the `forall`/Λ in the definition of `naive()`/`naive2()` somehow hides the constraints imposed by the two parts of the code from the type checker, which should disallow either `$parent->shape['child'] = shape();` or `$oops->shape['child']['dummy']->bork();`.

**Comment by pbl64k** [comment]
Just for the kicks, I tried to reproduce this without using shapes, but, thankfully, to no avail. I would always tun into one of the three expected outcomes:

1. The type checker correctly infers the more general type for the local variable and does not allow to unsafely refer to its innards (i.e., call `bork()` on a value that might not have it).
2. The type checker correctly infers the type of the passed argument as the more specific, and does not allow to assign a value of more a general type in the called function.
3. Variance checker kicks in and insist on invariance of the type argument to `DadFoo`.

Thus I'm pretty certain that there's something wonky with shape subtyping as compared to class subtyping.

**Comment by lexidor** [comment]
In hhvm 4.56, the typechecker is really confused by your repro.

First error is:
```
Typing[4313] Covariance or contravariance is not allowed in type parameter of method or function.
   --> src/file.hack
 15 | function naive<+Tx as Dad>(inout Tx $parent): void {
    |                 ^^
```

So I remove the `+`.

It also reports (with or without the `+`):
```
Typing[4337] Invalid assignment to an inout parameter
   --> src/file.hack
 15 | function naive<Tx as Dad>(inout Tx $parent): void {
    |                                 ^^
    |                                 ^^ Expected Tx (inout parameter)
    |                      ^^^ But got shape('child' => shape())

1 error found.
```

I think it tries to flag a problem, but in the wrong position.
It blames the `Tx` as an assignment.
The `^^^ But got shape('child' => shape())` points to `Dad`.
Removing the assignment in the body remove the typeerror.
So you can't declare this function this way. :confused: :confounded:

You need to removed `Tx as Dad` entirely and replace `Tx` with `Dad` to make the declaration of the function typecheck.
At which point, the faulty callsite is found:

```
Typing[4108] The field dummy is undefined
   --> src/file.hack
 14 | type Dad = shape('child' => Narrow);
    |                             ^^^^^^ Definition is here
 21 |     $oops['child']['dummy']->bork();
    |                    ^^^^^^^

1 error found.
```

I think the typechecker understands that you can't add or remove shape fields on and `inout`ed shape (since the callsite doesn't know about the change you are making), but the diagnostic is confusing.

Here is the raw typechecker output for this file:
```HACK
final class Dummy {
    final public function bork(): void {
        print('Bork.'."\n");
    }
}
type Narrow = shape(...);
type Broad = shape('dummy' => Dummy);
type Dad = shape('child' => Narrow);
function naive<Tx as Dad>(inout Tx $parent): void {
    $parent['child'] = shape();
}
```

```JSON
    [
        {
            "message": [
                {
                    "descr": "Invalid assignment to an inout parameter",
                    "path": "/path/to/file.hack",
                    "line": 9,
                    "start": 33,
                    "end": 34,
                    "code": 4337
                },
                {
                    "descr": "Expected Tx (inout parameter)",
                    "path": "/path/to/file.hack",
                    "line": 9,
                    "start": 33,
                    "end": 34,
                    "code": 4337
                },
                {
                    "descr": "But got shape('child' => shape())",
                    "path": "/path/to/file.hack",
                    "line": 9,
                    "start": 22,
                    "end": 24,
                    "code": 4337
                }
            ]
        }
    ]
```

**Comment by pbl64k** [comment]
The typechecker's behavior with `inout` seems to be confusing, what happens in the case of passing by reference through an object makes much more sense to me (using `runme2.hh`/`soundness2.hh`) as listed above:

    Typing[4166] Invalid argument
       --> soundness2.hh
     13 | type Dad2 = shape('child' => Narrow2);
        |                              ^^^^^^^ The field 'dummy' is not defined in this shape type, and this shape type does not allow unknown fields.
     27 |     $oops = new Breakage(shape('child' => shape('dummy' => new Dummy2())));
        |                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ The field 'dummy' is set in the shape.
     28 |     naive2($oops);
        |            ^^^^^

Nonetheless, unsafe usage appears to be prevented correctly, so I would say this issue should be closed.
