### ISSUE TITLE
Add more types to AsyncMysqlRow?

### ISSUE THREAD

**Issue by Daniel15** [facebook/hhvm#8288]
`AsyncMysqlRow` currently has these methods:
 - `getFieldAsDouble`
 - `getFieldAsInt`
 - `getFieldAsString`

But some other common types are missing. It would also be useful to add these methods:
 - `getFieldAsBool`: For `TINYINT(1)` fields: https://dev.mysql.com/doc/refman/8.0/en/numeric-type-overview.html
 - `getFieldAsDateTime`: For `DATETIME`s or `INT`s containing UNIX timestamps. Return an instance of `DateTimeImmutable`

Perhaps some stuff for [JSON fields](https://dev.mysql.com/doc/refman/8.0/en/json.html) and [spatial types](https://dev.mysql.com/doc/refman/8.0/en/spatial-type-overview.html) too?

### HHVM Version
```
HipHop VM 3.28.0-dev (rel)
Compiler: default-0-g890da9ed178200679419bac13cc2549d4a0ba1fc
Repo schema: 8486224ffe83330934d9afedfab9abde84693fe6
```

### Operating System and Version

CentOS Linux release 7.5.1804 (Core)

**Comment by lexidor** [comment]
`->getFieldAsBool()` is definitely a nice one to have.

**Comment by lexidor** [comment]
This API has fallen out of favor for the far faster ->dictRowsTyped(). You can assert that the return value matches a shape, making typed use correct by inspection. This doesn't resolve DateTime and book (which will be string and int respectively).
