### ISSUE TITLE
HHVM WordPress performance regression (gcc 5.5.0 compile hhvm)

### ISSUE THREAD

**Issue by skpgkp1** [facebook/hhvm#8290]
I'm running wordpress benchmark and it seems like huge performance(>50%) regression caused by this commit.

RPS: 2756.27(Commit: 15be1eb26b5ed5b5236b82f32c00f1258d5d17d1)

RPS: 1329.12(Commit: d68304a7cf5779a1a128fb5329ef985271966c56)

d68304a7cf5779a1a128fb5329ef985271966c56 is the first bad commit
commit d68304a7cf5779a1a128fb5329ef985271966c56
Author: Bin Liu <binliu@fb.com>
Date:   Sun Jul 8 00:05:36 2018 -0700

    refactor the job dispatcher code

    Summary: pass in numa node, huge stack size, and extra thread-local size from the job queue.

    Reviewed By: markw65

    Differential Revision: D7614750

    fbshipit-source-id: eff37284a4316ce2d25c9c1b72003c3f9aacfafd

### HHVM Version

Good:

$ ./hhvm --version
HipHop VM 3.28.0-dev (rel)
Compiler: 15be1eb26b5ed5b5236b82f32c00f1258d5d17d1
Repo schema: 285fe3d11a9d4728c7a769867d8085c555085561
$ ./hh_client --version
hh--3.28.0-dev Sat Jul  7 16:44:00 2018

Bad:

$ ./hhvm --version
HipHop VM 3.28.0-dev (rel)
Compiler: tags/gcc-4.6-21230-gd68304a7cf5779a1a128fb5329ef985271966c56
Repo schema: 0b994b3e98636c1cfa025c4be6ef847e4dce946c
$ ./hh_client --version
hh--3.28.0-dev Sun Jul  8 00:13:40 2018

### Operating System and Version

$ cat /etc/redhat-release
Fedora release 28 (Twenty Eight)

### Standalone code, or other way to reproduce the problem

Just compile both change set with GCC 5.5.0. and run like.

$hhvm  perf.php --wordpress --hhvm=`which hhvm`

### Actual result

Performance regression.

### Expected result

Shouldn't regress.

**Comment by skpgkp1** [comment]
I also tried with latest GCC 8. RPS is low with latest hhvm as of today.

$ ./hhvm --version
HipHop VM 3.28.0-dev (rel)
Compiler: heads/master-0-ge6bd378a184625eb71f04a1fef1ffe184b2f4d2e
Repo schema: cbadf5847cbe458cd245b4267b5387cd7f4a43f0

$ ./hh_client --version
hh--3.28.0-dev Mon Aug 20 12:29:13 2018

RPS: 1301.8

**Comment by skpgkp1** [comment]
llvm compiler build hhvm also get performance regression.

Good: 

    RPS: 2696.85
    hhvm commit 15be1eb26b5ed5b5236b82f32c00f1258d5d17d1
    $ ./hhvm --version
    HipHop VM 3.28.0-dev (rel)
    Compiler: tags/gcc-4.6-21229-g15be1eb26b5ed5b5236b82f32c00f1258d5d17d1
    Repo schema: 83829068478ab0f164b7302abf1f75d8bdbee77f
    $ ./hh_client --version
    hh--3.28.0-dev Sat Jul  7 16:44:00 2018


Bad:

    RPS: 1370.72
    hhvm commit d68304a7cf5779a1a128fb5329ef985271966c56
    $ ./hhvm --version
    HipHop VM 3.28.0-dev (rel)
    Compiler: tags/gcc-4.6-21230-gd68304a7cf5779a1a128fb5329ef985271966c56
    Repo schema: 0b994b3e98636c1cfa025c4be6ef847e4dce946c
    $ ./hh_client --version
    hh--3.28.0-dev Sun Jul  8 00:13:40 2018

**Comment by fredemmott** [comment]
>  as of today.

Did it start happening in the last few days, or is it the previously mentioned commit - or did it start happening in the last few days but only with that commit?

Are you running in a virtualized environment?
Have you built with libnuma?

**Comment by skpgkp1** [comment]
It is happening since previously mentioned commit. I just got time to find exact hhvm change-set which introduced this problem at first place.

I have dual socket physical server(Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz), No virtualization.

No change in build procedure. It is default build process for both good and bad case.

**Comment by binliu19** [comment]
It is a bug related to NUMA and it only appears when hhvm is built without NUMA support (but when the machine actually has multiple sockets).

**Comment by skpgkp1** [comment]
> It is a bug related to NUMA and it only appears when hhvm is built without NUMA support (but when the machine actually has multiple sockets).

Looking into hhvm build log it seems like it has numa support enabled and I still see performance degradation.

 Performing Test HAVE_LIBNUMA - Success

Actual compiler command line have -DHAVE_NUMA=1.

$ ldd hhvm | grep numa
        libnuma.so.1 => /lib64/libnuma.so.1 (0x00007f414140e000)

Can you please advise, how exactly I should enable numa in hhvm build.

**Comment by skpgkp1** [comment]
I look into perf data with and without change.

Before regression:
============
        There are 4 thread of hhvmworker.
        hhvmworker.ND0
        hhvmworker.ND1
        hhvmworker.ND2
        hhvmworker.ND3

After regression:
===========
       There is only one hhvmworker thread.
       hhvmworker.ND0

So it seems like something to do with numa, but it doesn't look like issue with build setup as posted above.

I provided all the SW/HW detail to reproduce issue. Not sure, what else I can do on my side to help.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This issue applies to running php code on hhvm. Hhvm [nolonger supports running php code](https://hhvm.com/blog/2018/09/12/end-of-php-support-future-of-hack.html) since [hhvm version 4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html).

If this perf regression is applicable to Hack code, feel free to open a new issue. I suspect that this applies to something phpish that WordPress does. Going through the entirety of WordPress would be a humongous effort.

Facebook's codebase was not affected by this issue. A regression of a couple percent would be a showstopper when deploying a new hhvm version internally.
