### ISSUE TITLE
Build HHVM Error on Centos 7.5

### ISSUE THREAD

**Issue by choungchamnab** [facebook/hhvm#8292]
`-- Patches: /tmp/hhvm/patches/ocaml.patch;/tmp/hhvm/patches/webscalesql-readline.patch
-- Applying /tmp/hhvm/patches/ocaml.patch
CMake Error at CMakeLists.txt:45 (message):
  Error applying patch /tmp/hhvm/patches/ocaml.patch`

Did i miss somethings ?

**Comment by fredemmott** [comment]
Most likely `git submodule update --init --recursive`

**Comment by choungchamnab** [comment]
still has the same problem.

**Comment by bms8197** [comment]
I'm having the same problem on a fresh CentOS 8 install
