### ISSUE TITLE
Can't reload server.ini

### ISSUE THREAD

**Issue by choungchamnab** [facebook/hhvm#8293]
### HHVM Version

HHVM VM 3.15.3  (Prebuilt)

### Operating System and Version

CentOS 7.5

### Standalone code, or other way to reproduce the problem

edited in /etc/hhvm/server.ini : port = 8000 , user = apache

### Actual result

/usr/local/bin/hhvm --config /etc/hhvm/server.ini --user nginx --mode daemon -vServer.Type=fastcgi -vServer.Port=9001

> If applicable, please copy-paste output from `hhvm` or `hh_client`

### Expected result

/usr/local/bin/hhvm --config /etc/hhvm/server.ini --user apache --mode daemon -vServer.Type=fastcgi -vServer.Port=8000

**Comment by fredemmott** [comment]
3.15 is no longer supported; if you have the same issue in a supported version, please reopen, and update the issue to incldue the command you're actually running
