### ISSUE TITLE
Dramatic jump in hh_client --coverage numbers in 3.28

### ISSUE THREAD

**Issue by ssandler** [facebook/hhvm#8305]
### HHVM Version

3.27.2 -> 3.28 (this issue shows a progression of changes throughout these versions)

### Operating System and Version

MacOS High Sierra

Repro'd with and without docker, and also on Linux

### Standalone code, or other way to reproduce the problem

The test case for this is the current commit of the hhvm user-documentation repository (https://github.com/hhvm/user-documentation). Throughout all the tests below, the Hacklang code under test is unchanged, only the build of hhvm changes.

```
commit 6420a6d5cbb557ddbe8a140c933b22b903d2e1b2 (origin/master, origin/HEAD)
Author: Fred Emmott <fe@fb.com>
Date:   Tue Jul 31 16:26:51 2018 -0700

    fix some bad automated fixes from the HSL support diff
```

The below shows that the `hh_client --coverage` output has changed quite a bit recently. The change is much more prounounced on Slack's codebase (5% total) but I wanted to illustrate it in a reproducible way with open source code.

To make the output smaller the only sections I'm including are lvar, call, and total. The others don't seem to change. The changes to `call` are also generally small, showing that this is probably *not* owing to typing/hhis for built-ins.

Methodology is to just start up a docker container running the appropriate nightly build of hhvm and check the coverage output.

My conclusion is that something changed about how lvars were counted on June 22nd, so the total number of lvars goes up significantly (both unchecked and checked, with more of them going into "checked"). 

## hhvm/hhvm:2018.06.04

```
docker run -t -d --name slack-hhvm -v /Users/ssandler/dev/user-documentation:/Users/ssandler/dev/user-documentation -w /Users/ssandler/dev/user-documentation hhvm/hhvm:2018.06.04
docker exec -it slack-hhvm hh_client --coverage .
docker stop slack-hhvm && docker rm slack-hhvm

== call ==
Unchecked: 1924
Partial: 253
Checked: 17988
Checked / Total: 0.892041
(Checked + Partial * 0.5) / Total: 0.898314
== lvar ==
Unchecked: 1068
Partial: 638
Checked: 28300
Checked / Total: 0.943145
(Checked + Partial * 0.5) / Total: 0.953776
== total ==
Unchecked: 3147
Partial: 964
Checked: 62025
Checked / Total: 0.937840
(Checked + Partial * 0.5) / Total: 0.945128
```

## June 6th: same as June 4th

which seems to indicate https://github.com/facebook/hhvm/commit/ff3d8c9678357f60cb1e33924dc8ffa2910e63d5 is not to blame
```
docker run -t -d --name slack-hhvm -v /Users/ssandler/dev/user-documentation:/Users/ssandler/dev/user-documentation -w /Users/ssandler/dev/user-documentation hhvm/hhvm:2018.06.06
docker exec -it slack-hhvm hh_client --coverage .
docker stop slack-hhvm && docker rm slack-hhvm

== call ==
Unchecked: 1924
Partial: 253
Checked: 17988
Checked / Total: 0.892041
(Checked + Partial * 0.5) / Total: 0.898314
== lvar ==
Unchecked: 1068
Partial: 638
Checked: 28300
Checked / Total: 0.943145
(Checked + Partial * 0.5) / Total: 0.953776
== total ==
Unchecked: 3147
Partial: 964
Checked: 62025
Checked / Total: 0.937840
(Checked + Partial * 0.5) / Total: 0.945128
```

## June 15th: we have some movement

`call` only changes by 1, by `lvar` changes from 1068 unchecked to 993

```
docker run -t -d --name slack-hhvm -v /Users/ssandler/dev/user-documentation:/Users/ssandler/dev/user-documentation -w /Users/ssandler/dev/user-documentation hhvm/hhvm:2018.06.15
docker exec -it slack-hhvm hh_client --coverage .
docker stop slack-hhvm && docker rm slack-hhvm

== call ==
Unchecked: 1923
Partial: 255
Checked: 17987
Checked / Total: 0.891991
(Checked + Partial * 0.5) / Total: 0.898314
== lvar ==
Unchecked: 993
Partial: 631
Checked: 28382
Checked / Total: 0.945877
(Checked + Partial * 0.5) / Total: 0.956392
== total ==
Unchecked: 3072
Partial: 956
Checked: 62108
Checked / Total: 0.939095
(Checked + Partial * 0.5) / Total: 0.946323
```

## June 21st: same as 15th basically

```
== call ==
Unchecked: 1923
Partial: 255
Checked: 17987
Checked / Total: 0.891991
(Checked + Partial * 0.5) / Total: 0.898314
== lvar ==
Unchecked: 990
Partial: 644
Checked: 28373
Checked / Total: 0.945546
(Checked + Partial * 0.5) / Total: 0.956277
== total ==
Unchecked: 3071
Partial: 969
Checked: 62097
Checked / Total: 0.938915
(Checked + Partial * 0.5) / Total: 0.946240
```

## June 22nd: dramatic jump in total number of lvars

Coverage goes up a bit here, but if you look closely you'll see that the raw number of lvars has changed from 30,007 to 37,378. Some unchecked and checked were added.
```
docker run -t -d --name slack-hhvm -v /Users/ssandler/dev/user-documentation:/Users/ssandler/dev/user-documentation -w /Users/ssandler/dev/user-documentation hhvm/hhvm:2018.06.22
docker exec -it slack-hhvm hh_client --coverage .
docker stop slack-hhvm && docker rm slack-hhvm

== call ==
Unchecked: 1926
Partial: 162
Checked: 18072
Checked / Total: 0.896429
(Checked + Partial * 0.5) / Total: 0.900446
== lvar ==
Unchecked: 1476
Partial: 383
Checked: 35519
Checked / Total: 0.950265
(Checked + Partial * 0.5) / Total: 0.955388
== total ==
Unchecked: 3792
Partial: 1420
Checked: 83303
Checked / Total: 0.941117
(Checked + Partial * 0.5) / Total: 0.949139
```

## July 1st: holding steady

Similar to 6/22
```
docker run -t -d --name slack-hhvm -v /Users/ssandler/dev/user-documentation:/Users/ssandler/dev/user-documentation -w /Users/ssandler/dev/user-documentation hhvm/hhvm:2018.07.01
docker exec -it slack-hhvm hh_client --coverage .
docker stop slack-hhvm && docker rm slack-hhvm

== call ==
Unchecked: 1926
Partial: 162
Checked: 18072
Checked / Total: 0.896429
(Checked + Partial * 0.5) / Total: 0.900446
== lvar ==
Unchecked: 1477
Partial: 383
Checked: 35518
Checked / Total: 0.950238
(Checked + Partial * 0.5) / Total: 0.955361
== total ==
Unchecked: 3793
Partial: 1420
Checked: 83302
Checked / Total: 0.941106
(Checked + Partial * 0.5) / Total: 0.949127
```

## August 4th, still more movement

Still showing 37,378 total lvars, there has been a bit of movement (a little over 100 went from Partial and Checked back into Unchecked).
```
docker run -t -d --name slack-hhvm -v /Users/ssandler/dev/user-documentation:/Users/ssandler/dev/user-documentation -w /Users/ssandler/dev/user-documentation hhvm/hhvm:2018.08.04
docker exec -it slack-hhvm hh_client --coverage .
docker stop slack-hhvm && docker rm slack-hhvm

== call ==
Unchecked: 1929
Partial: 162
Checked: 18069
Checked / Total: 0.896280
(Checked + Partial * 0.5) / Total: 0.900298
== lvar ==
Unchecked: 1586
Partial: 302
Checked: 35490
Checked / Total: 0.949489
(Checked + Partial * 0.5) / Total: 0.953529
== total ==
Unchecked: 3905
Partial: 1320
Checked: 83290
Checked / Total: 0.940970
(Checked + Partial * 0.5) / Total: 0.948427
```

## Conclusion
If this change represents an intentional change to how `hh_client` works, I'd love to know more. Since it's not in the 3.28 release notes and Fred didn't seem to think there were intentional changes here, it may be a bug. 

We're tracking the coverage numbers very carefully so we'd like to understand any major changes.

**Comment by fredemmott** [comment]
This looks like 8ff74cd3505304770b644f9fce5dd096e473aa6f and ae72cae81724138470695f8ecec1114cb854c3f8 giving more accurate numbers, by changing how coverage is implemented from region/line-based to AST based, using the Typed AST (TAST)
