### ISSUE TITLE
Feature request: (im)mutability attributes/annotations

### ISSUE THREAD

**Issue by pbl64k** [facebook/hhvm#8310]
It would be nice if classes could be annotated as immutable, allowing covariant type parameters is nominally contravariant positions, and preventing assignment to member variables outside of constructor. This would allow implementation of stuff such as:

    <<__Immutable>>
    class MyContainer<+Tx>
    {
        public function add(Tx $x): MyContainer<Tx>
        {
            // ...
        }
    }

And while it's possible to emulate that to an extent using static methods, not only the call syntax is more cumbersome, but we also lose run-time polymorphism that way.

(Personally, this hit me hard on the nose when I used a particularly ugly hack to circumvent this in the internal library of immutable containers we're using, only to realize months later that I've accidentally introduced a very nasty way to break the type safety.)

Possibly related to #6848 - apparently, the type checker is already aware to an extent that certain built-in classes are immutable, but there's no way to express that in the code.

**Comment by pbl64k** [comment]
Oh hey, that's great news. I had doubts this'd be viable at all. Thank you for the info!

**Comment by azjezz** [comment]
any progress here?

I was actually surprised today when i typed `<<__Immutable>>` and got `Naming[2049] Unrecognized user attribute: __Immutable starts with __ but is not a standard attribute - Hack(2049)` as i would have though this is something that is already supported.

**Comment by fredemmott** [comment]
It's changed significantly several times, due to issues surrounding shallow- vs deep- immutability, and interaction with reactive features. It's still being worked on.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

A more granular approach has landed in hhvm, read-only values. (Not to be confused with value type / reference type).

https://docs.hhvm.com/hack/readonly/introduction
