### ISSUE TITLE
Null coalesce on magic properties differs between hhvm and php >= 7.0.6

### ISSUE THREAD

**Issue by ebernhardson** [facebook/hhvm#8317]
### Problem Description

Accessing a magic property with the null coalesce operator behaves differently on hhvm and php 7. On php7 the `__isset` function is checked for the null coalesce, while in hhvm `__get` is checked for a null return value.  Php wasn't the most consistent with this either, 7.0.0 through 7.0.5 have the same behaviour as hhvm, while >= 7.0.6 check `__isset`.

### HHVM Version

3.11.1 - 3.22.0, via https://3v4l.org/

### Standalone code, or other way to reproduce the problem

https://3v4l.org/fWp8o
```
<?php

class Foo {
    public function __get($prop) {
        echo "CALLED GET\n";
        return null;
    }
    
    public function __isset($prop) {
        echo "CALLED ISSET\n";
        return false;
    }
}


$f = new Foo();
$f->y ?? 'y';
```

### Actual result

```
CALLED GET
```
### Expected result
```
CALLED ISSET
```

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

`__get()` has been removed from hhvm in version [4.56.0](https://hhvm.com/blog/2020/05/04/hhvm-4.56.html).
