### ISSUE TITLE
Errors status hhvm

### ISSUE THREAD

**Issue by Funky89** [facebook/hhvm#8363]
### HHVM Version

HipHop VM 3.28.3 (rel)
Compiler: 1538421613_684479632
Repo schema: a50ceefa110fe73c87de77ed0a6ff5683736c222

* i use a translator

Hello everyone,

When installing hhvm everything goes well.

By cons when I run hhvm and I make a status here is what he reports

`[Mon Oct 22 12:38:01 2018] [hphp] [18300:7f7f625d4700:0:000001] [] [external compiler 18304]: Raised at file "pervasives.ml", line 33, characters 20-45
[Mon Oct 22 12:38:01 2018] [hphp] [18300:7f7f625d4700:0:000002] [] [external compiler 18304]: Called from file "utils/hh_json/hh_json.ml", line 167, characters 12-25
[Mon Oct 22 12:38:01 2018] [hphp] [18300:7f7f625d4700:0:000003] [] [external compiler 18304]: Called from file "utils/hh_json/hh_json.ml", line 183, characters 14-22
[Mon Oct 22 12:38:01 2018] [hphp] [18300:7f7f625d4700:0:000004] [] [external compiler 18304]: Called from file "utils/hh_json/hh_json.ml", line 295, characters 10-22
[Mon Oct 22 12:38:01 2018] [hphp] [18300:7f7f625d4700:0:000005] [] [external compiler 18304]: Called from file "utils/hh_json/hh_json.ml", line 243, characters 12-23
[Mon Oct 22 12:38:01 2018] [hphp] [18300:7f7f625d4700:0:000006] [] [external compiler 18304]: Called from file "utils/hh_json/hh_json.ml", line 262, characters 14-21
[Mon Oct 22 12:38:01 2018] [hphp] [18300:7f7f625d4700:0:000007] [] [external compiler 18304]: Called from file "utils/hh_json/hh_json.ml", line 295, characters 10-22
[Mon Oct 22 12:38:01 2018] [hphp] [18300:7f7f625d4700:0:000008] [] [external compiler 18304]: Called from file "utils/hh_json/hh_json.ml", line 243, characters 12-23
[Mon Oct 22 12:38:01 2018] [hphp] [18300:7f7f625d4700:0:000009] [] [external compiler 18304]: Called from file "utils/hh_json/hh_json.ml", line 262, characters 14-21
[Mon Oct 22 12:38:01 2018] [hphp] [18300:7f7f625d4700:0:000010] [] [external compiler 18304]: Called from file "hh_single_compile.ml", line 530, characters 45-66
[Mon Oct 22 12:38:01 2018] [hphp] [18300:7f7f625d4700:0:000011] [] [external compiler 18304]: Called from file "hh_single_compile.ml", line 258, characters 18-49
[Mon Oct 22 12:38:01 2018] [hphp] [18300:7f7f625d4700:0:000012] [] [external compiler 18304]: Called from file "hh_single_compile.ml", line 670, characters 4-21
[Mon Oct 22 12:38:01 2018] [hphp] [18300:7f7f625d4700:0:000013] [] [external compiler 18304]: 
[Mon Oct 22 12:38:01 2018] [hphp] [18300:7f7f625d4700:0:000014] [] [external compiler 18304]: (Invalid_argument Char.chr)
[Mon Oct 22 12:38:01 2018] [hphp] [18300:7f7f746d7800:0:000001] [] ExternCompiler: exited with status code 2
[Mon Oct 22 12:38:01 2018] [hphp] [18300:7f7f746d7800:0:000002] [] ExternCompiler Error: error writing message: Broken pipe\n
[Mon Oct 22 12:38:01 2018] [hphp] [18300:7f7f746d7800:0:000003] [] ExternCompiler encountered too many communication errors, giving up.
[Mon Oct 22 12:38:01 2018] [hphp] [18300:7f7f746d7800:0:000004] [] An error has been introduced into the systemlib, but we cannot give you a file and line number right now.
[Mon Oct 22 12:38:01 2018] [hphp] [18300:7f7f746d7800:0:000005] [] Check all of your changes to hphp/system/php
[Mon Oct 22 12:38:01 2018] [hphp] [18300:7f7f746d7800:0:000006] [] HipHop Parse Error: error writing message: Broken pipe\n -1
[Mon Oct 22 12:38:01 2018] [hphp] [18303:7f7f746d7800:0:000001] [] Lost parent, LightProcess exiting`

Can you tell me where the problem comes from?
I looked on the internet and reinstall hhvm but still the same message

Thank you in advance for your answers

**Comment by fredemmott** [comment]
- Does this happen when executing a particular file? If so:
  - can you share small example code that reproduces the problem (i.e. delete parts of the file until it's as small as possible while keeping the problem)?
  - what happens when you run `hh_single_compile <filename>` on that file?
- What operating system and operating system version?

**Comment by Funky89** [comment]
I solved my problem with hhvm version hhvm_3.25.2-1~jessie_amd64.deb.
I didn't know why I had these error messages
