### ISSUE TITLE
Cosmic (Ubuntu 18.10) packaging?

### ISSUE THREAD

**Issue by craigcarnell** [facebook/hhvm#8372]
I can't see it in https://dl.hhvm.com/ubuntu/dists/

**Comment by asim-vax** [comment]
Would be great to have support for the latest ubuntu version, thanks!

**Comment by fredemmott** [comment]
Please re-file (or send as pull-request) against https://github.com/hhvm/packaging :)

I'll do that myself in a day or two if needed, just it's helpful for us to keep track of who actually requested issues

The primary reason we don't have support yet is that I didn't realize it was out, sorry :) Once nightlies work, I'll likely aim for 3.29 and 3.27 support
