### ISSUE TITLE
Feature request: backward_compatibility_level

### ISSUE THREAD

**Issue by ssandler** [facebook/hhvm#8377]
This would be a "minimum required version" for .hhconfig, similar to `forward_compatibility_level`. The intention is to say that "if you do not have this version, you need to upgrade before running hh_client".

The current situation is that if people happen to have an out of date hhvm and run hh_client, they are surprised by a slew of confusing type errors related to new functionality we're using in the code. Especially for hhvm newbies this tends to cause a lot of confusion. Ideally `hh_client` would be able to check this value and return an error saying that it is not at the minimum required version.

**Comment by fredemmott** [comment]
Summarizing a few other conversations:
- this overlaps with the duties of a package manager for most projects (though not necessarily 'most people who use hack at work or home')
- for the other projects, this kind of logic can be done by a wrapper script - e.g. most Facebook engineers run `hh` and are unaware of the real `hh_client`
- that said, given the code we already have for `forward_compatibility_level`, this is probably fairly trivial and worth adding anyway
- I can take a look at a pull request sooner, but I probably won't look at this until December or January, given the other work that needs doing by the 3.30 branch cut

**Comment by fredemmott** [comment]
I'm closing this - we ended up removing `forward_compatibility_level` due to lack of use, and in general our approaches to upgrades changed with the move to weekly releaes
