### ISSUE TITLE
Unexpected Hack error about non-reactive functions

### ISSUE THREAD

**Issue by ssandler** [facebook/hhvm#8378]
### HHVM Version

```
$ hh_client --version
hh-fb2388086a557df7739d388f2ff4704313ef5979-3.29.1 Tue Oct 30 18:44:05 2018
```

Note this doesn't happen in 3.28.3, only 3.29.

### Operating System and Version

MacOS High Sierra

### Standalone code, or other way to reproduce the problem

gist here: https://gist.github.com/ssandler/0b68ed30b85d386357c90aff570bd848

We have no options in our hhconfig related to reactivity and we have no Rx related annotations on functions in our codebase (aside from the vendored HSL ones)

### Actual result

```
/private/tmp/hh_server/hhi_1a8923d/stdlib/builtins_math.hhi:79:10,14: This function is non-reactive. (Typing[4203])
  include/isolated_repro.php:14:12,20: This function is reactive.
```

### Expected result

No errors

**Comment by fredemmott** [comment]
Minimal repro:

```
<?hh // strict
function foo(): (function(mixed):mixed) {
  $f = $x ==> $x;
  if (count([])) {
    $f = fun('log1p');
  }
  return $f;
}
```

Does not fail if I do any out of:
- get rid of the iff
- if (false)
- if (true)

**Comment by fredemmott** [comment]
For this error apparnetly being bogus, FB T35903875

Separate to that, it should be suppressed unless unsafe_rx=false

**Comment by fredemmott** [comment]
D12868386
