### ISSUE TITLE
GCC LOWPTR build fails when linking with jemalloc>=5.1

### ISSUE THREAD

**Issue by florinpapa** [facebook/hhvm#8379]
The GCC build fails when compiling the static_assert in hphp/util/extent-hooks.h:97, when using LOWPTR and jemalloc 5.1. Not sure why that assert is needed, since the HPHP::alloc::BumpExtentAllocator::s_hooks is declared static and can never be NULL. GCC 7.3 actually gives a warning saying the variable will never be null, but still fails, saying it is not a constant expression. The build works under CLANG 7.

### HHVM Version
Master branch, since this commit on 10/22: 2c33142f6b89c8ea2b020af94b90d3f14a407639

### jemalloc version
5.1.0-0-g61efbda7098de6fe64c362d309824864308c36d4

### Operating System and Version
Ubuntu 16.04, bare metal. Build fails under GCC 5.4 and 7.3.

### Standalone code, or other way to reproduce the problem
```
./configure \
    -DCMAKE_CXX_FLAGS="-DUSE_LOWPTR=1" \
    -DCMAKE_C_FLAGS="-DUSE_LOWPTR=1" \
    -DCMAKE_ASM_FLAGS="-DUSE_LOWPTR=1"
make
[  0%] Built target fbmysqlclient
[ 11%] Built target folly
[ 11%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/alloc.cpp.o
In file included from /home/slo/git/hhvm-perf/workspace-2018-10-24_10.36.48/hhvm/hphp/util/alloc.cpp:31:0:
/home/slo/git/hhvm-perf/workspace-2018-10-24_10.36.48/hhvm/hphp/util/extent-hooks.h:97:77: warning: the address of ‘HPHP::alloc::BumpExtentAllocator::s_hooks’ will never be NULL [-Waddress]
 static_assert(extent_allocator_traits<BumpExtentAllocator>::get_hooks(), "");
                                                                             ^
/home/slo/git/hhvm-perf/workspace-2018-10-24_10.36.48/hhvm/hphp/util/extent-hooks.h:97:1: error: non-constant condition for static assertion
 static_assert(extent_allocator_traits<BumpExtentAllocator>::get_hooks(), "");
 ^~~~~~~~~~~~~
/home/slo/git/hhvm-perf/workspace-2018-10-24_10.36.48/hhvm/hphp/util/extent-hooks.h:97:77: error: ‘((& HPHP::alloc::BumpExtentAllocator::s_hooks) != 0)’ is not a constant expression
 static_assert(extent_allocator_traits<BumpExtentAllocator>::get_hooks(), "");
                                                                             ^
hphp/util/CMakeFiles/hphp_util.dir/build.make:786: recipe for target 'hphp/util/CMakeFiles/hphp_util.dir/alloc.cpp.o' failed
make[2]: *** [hphp/util/CMakeFiles/hphp_util.dir/alloc.cpp.o] Error 1
CMakeFiles/Makefile2:2013: recipe for target 'hphp/util/CMakeFiles/hphp_util.dir/all' failed
make[1]: *** [hphp/util/CMakeFiles/hphp_util.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by florinpapa** [comment]
Any thoughts on this?

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones unlikely to be resolved.

This issue demonstrates a build error. This issue is multiple years old. Hhvm is not compiled with GCC anymore. If this issue reproduces on Clang, please open a new issue.

If you are experiencing build errors, don't let the closing of this issue discourage you from filing a new issue.
