### ISSUE TITLE
Building example extension fails.

### ISSUE THREAD

**Issue by DerPapst** [facebook/hhvm#8383]
### HHVM Version
hhvm 3.30-dev

### Operating System and Version
Debian Stretch (9)

### Standalone code, or other way to reproduce the problem
Trying to compile the [extension example](https://github.com/facebookarchive/extension-example).

### Actual result
```
[ 50%] Building CXX object CMakeFiles/example.dir/example.cpp.o
In file included from /usr/local/include/hphp/util/hdf.h:32:0,
                 from /usr/local/include/hphp/runtime/base/config.h:20,
                 from /usr/local/include/hphp/runtime/base/runtime-option.h:30,
                 from /usr/local/include/hphp/runtime/base/array-data.h:23,
                 from /usr/local/include/hphp/runtime/base/type-array.h:20,
                 from /usr/local/include/hphp/runtime/base/exceptions.h:28,
                 from /usr/local/include/hphp/runtime/base/string-data.h:29,
                 from /usr/local/include/hphp/runtime/base/type-string.h:22,
                 from /usr/local/include/hphp/runtime/base/debuggable.h:19,
                 from /usr/local/include/hphp/runtime/ext/extension.h:21,
                 from /root/build/hhvmextensions/extension-example/example.cpp:17:
/usr/local/include/hphp/util/hash-map.h:20:36: fatal error: folly/container/F14Map.h: No such file or directory
 #include "folly/container/F14Map.h"
                                    ^
compilation terminated.
```

### Expected result
Compiles fine.

**Comment by DerPapst** [comment]
From a recent convo in irc (just for completeness) from @fredemmott:

> the -dev packages in general need a  rework
>
> folly (and various other dependencies) don't provide enough stability guarantees to use the system version
>
> *some* things should be installed into an HHVM-specific location, including folly, and the cmake stuff/hphipze should be updated to set the paths as needed
>
> reverting the diff that broke it is worse though, as then we install headers for *everything* we potentially bundle into the system location, breaking peoples systems more thoroughly, not just the "I'm building an extension" case

**Comment by lexidor** [comment]
Hhvm now bakes in many dependencies in the repository including folly. (See [this commit](https://github.com/facebook/hhvm/commit/c429bdf725b6b24a7c300d57a90cc326585644c4)
 for example.)

This addresses Fred's comment. I am unable to verify the example extension builds, since hhvm can not be built in hhvm-packaging anymore.
