### ISSUE TITLE
php7.1 feature: array_creation_expression is not allowed in write context

### ISSUE THREAD

**Issue by mastef** [facebook/hhvm#8387]
PHP 7.1 introduced the `Square bracket syntax for list()`, which is currently not supported in hhvm. Instead of writing `list($a, $b) = method()`, you can shorten it to `[$a, $b] = method()`

Laravel updated their code-base recently to rely on this feature. https://github.com/laravel/framework/pull/25966/commits/2398d979e31599ed9e37f655c1916ea5072f63a8

### HHVM Version
HipHop VM 3.28.3 (rel)
Compiler: 1538421725_068926489
Repo schema: c6dbadff8e21627c2820cd174a43da91e63e7a08

### Operating System and Version
Debian

### Standalone code, or other way to reproduce the problem
```php
<?php
function somemethod() {
  return ["a", "b"];
}

[$key, $var] = somemethod();

print_r($key);
?>
```

### Actual result
```
Fatal error: Uncaught Error: array_creation_expression is not allowed in write context in test.php:7
```

### Expected result
```
a
```

**Comment by fredemmott** [comment]
We have WIP diffs for this, but the usage of them was not wide enough to do the significant changes required, especially given the plans to drop PHP support.
