### ISSUE TITLE
Build times absurdly long due to `opam init`

### ISSUE THREAD

**Issue by jmarrama** [facebook/hhvm#8407]
I'm trying to compile HHVM 3.30 and I get to the build step that runs [hphp/hack/opam_setup.sh](https://github.com/facebook/hhvm/blob/master/hphp/hack/opam_setup.sh), and it takes an absurd amount of time (at least 1 hour) to actually download everything that `opam init --no-setup` requires. When I let it run for a half day, it downloaded over *3 gigabytes* of packages in `hphp/hack/src/_build/.opam` and it wasn't even finished.

It looks like the script does some facebook-internal hack to get around this deficiency, but this is an absurd build process for facebook-external users.

Here's the output from the `opam init --no-setup` part of the build, in case I'm missing something:
```
[WARNING] Running as root is not recommended
Checking for available remotes: rsync and local, git, mercurial.
  - you won't be able to use darcs repositories unless you install the darcs
    command on your system.

[WARNING] Recommended external solver aspcud not found.

=-=- Fetching repository information =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[default: http]
[default: http]
[default: http]
[default: http]
[default] synchronized from https://opam.ocaml.org
[NOTE] The repository 'default' will be *permanently* redirected to
       https://opam.ocaml.org/1.2.2 (opam-version < "2.0~")
[default: http]```

**Comment by fredemmott** [comment]
This performance is unexpected; I'm working on confirming the expected download size.

- what platform?
- what's your internet connection?
- do you have an existing opam/ocaml installation?

> It looks like the script does some facebook-internal hack to get around this deficiency

This kind of performance wasn't something we saw; the hack is more from a reliability perspective - however small/fast it is, downloading a bunch of stuff from the internet on every CI run isn't a good idea.

If you have lz4 and sqlite installed system-wide, including development headers, reverting https://github.com/facebook/hhvm/commit/733eb5d7082831b6edccba88112c5f47f7d94eac may help - I'd appreciate feedback if you try that.

**Comment by swalk-cavium** [comment]
@fredemmott  - I think it's been doing this for a while.  I have build output back to April or so.  The
number of ocaml packages jumped from 13 on 050818, to 57 on 051818.   Wasn't there
some janestreet transition around then?

**Comment by jmarrama** [comment]
@fredemmott well, this is odd - i completely nuked my whole repo and started anew with a shallow checkout of `3.30.1`, and it seems like `opam init --no-setup` actually doesn't try to download the entire catalog of opam packages this time! it quickly progressed through and downloaded the minimum set of packages required to actually initialize opam. there must've been some artifacts lying around from previous builds of HHVM that `make clean` didn't cleanup (I had previously built HHVM at 3.24 in the same repo).

For reference, this is what a successful run of `opam init --no-setup` output:

```
[default: http]
[default] synchronized from https://opam.ocaml.org/1.2.2

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
-> installed base-bigarray.base
-> installed base-threads.base
-> installed base-unix.base
Done.

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
```

**Comment by jmarrama** [comment]
Feel free to close.
