### ISSUE TITLE
Any chance of resurrecting hh_ide.js for hacklang.org?

### ISSUE THREAD

**Issue by muglug** [facebook/hhvm#8408]
Not sure whether this belongs here or on https://github.com/hhvm/hacklang.org

The editor on the front page is running a > 2-year-old version of the Hack parser that doesn't recognise a number of newer features.

**Comment by fredemmott** [comment]
Not sure what we're going to do here- it was removed because keeping thigns working with js_of_ocaml was extremely painful. That's no longer true though

**Comment by muglug** [comment]
Yeah, I briefly tried to resuscitate it but quickly hit a wall of my own ignorance.

I've used it a lot to quickly figure out how Hack deals with situation X, but it could also be used to demonstrate the typechecker's features (e.g. https://getpsalm.org/r/89678aff60), and also reproduce parser/typechecker bugs

**Comment by fredemmott** [comment]
Another approach would be to build hh_single_typecheck with reason’s JS support, but I don’t know how practical that is, and we’d need to do something about HSL definitions

**Comment by fredemmott** [comment]
with the move to rust, extremely unlikely. We've also got rid of that tutorial now
