### ISSUE TITLE
Remove leading # character for comment text in hh_client LSP hover response

### ISSUE THREAD

**Issue by PranayAgarwal** [facebook/hhvm#8412]
### HHVM Version

Any

### Operating System and Version

Any

### Standalone code, or other way to reproduce the problem

Hover over a function or variable name that is documented with `#` style comments. The Hack language server returns the comment text in the hover response with the `#` prefixed in every line. VS Code, however, interprets this as a markdown heading, and the formatting is pretty off.

The hover would be a lot more readable if the `#` character was automatically removed from the response.

![image](https://user-images.githubusercontent.com/341507/50708712-22c46080-101a-11e9-8953-800c134adeef.png)

**Comment by Wilfred** [comment]
That's definitely a bug. I think `//` are more common, which is probably why this hasn't been noticed earlier.
