### ISSUE TITLE
Always use pass by ref annotation change introduces 8 regression failures

### ISSUE THREAD

**Issue by swalk-cavium** [facebook/hhvm#8418]
### HHVM Version

/data2/swalk/play.3631074/hhvm$ hphp/hhvm/hhvm --version
HipHop VM 3.30.0-dev (rel)
Compiler: tags/gcc-4.6-23343-g3631074f8992a83dadb37530e0b9f16b15b0cc4d
Repo schema: 2ee5967ea8a015b3abb6b1f504426dbafbf296df

### Operating System and Version

Ubuntu 16.04
uname -a
Linux lab-3 4.2.0 #1 SMP Wed Nov 25 14:00:54 CST 2015 aarch64 aarch64 aarch64 GNU/Linux

### Standalone code, or other way to reproduce the problem

Standard regression tests run with 6 different option sets, the post-processed.

hphp/test/run -v -m interp all
hphp/test/run -v -m interp -r all
hphp/test/run -v -m jit -a '-vEval.JitPGO=0' all
hphp/test/run -v -m jit -r -a '-vEval.JitPGO=0' all
hphp/test/run -v -m jit -a '-vEval.JitPGO=1' all
hphp/test/run -v -m jit -r -a '-vEval.JitPGO=1' all

### Actual result

swalk@lab-3:/data2/swalk/play.3631074/hhvm$ diff bad.3631074 ../../play.0ced1dd/hhvm/bad.0ced1dd 
117,121d116
< hphp/test/spec/tests/basic_concepts/memory_model_and_handle_types.php | F | . | F | . | F | . | 
< hphp/test/spec/tests/basic_concepts/memory_model_and_resources.php | F | . | F | . | F | . | 
< hphp/test/spec/tests/basic_concepts/memory_model_and_value_types.php | F | . | F | . | F | . | 
< hphp/test/spec/tests/expressions/primary_expressions/intrinsics_unset.php | F | . | F | . | F | . | 
< hphp/test/spec/tests/functions/byrefs.php | F | . | F | . | F | . | 
123,125d117
< hphp/test/spec/tests/functions/passing_by_reference.php | F | . | F | . | F | . | 
< hphp/test/spec/tests/functions/type_hints.php | F | . | F | . | F | . | 
< hphp/test/spec/tests/functions/using_byrefs_to_undefined_variables.php | F | . | F | . | F | . | 

Bi-sected to this checkin
https://github.com/facebook/hhvm/commit/3631074f8992a83dadb37530e0b9f16b15b0cc4d

### Expected result

Expect pass

**Comment by jano** [comment]
fixed by
https://github.com/facebook/hhvm/commit/b873299ca290a4d3c2ef30aedd721b89eff56a1c

**Comment by swalk-cavium** [comment]
swalk@1lab-3:/data2/swalk/play.013119a/hhvm$ hphp/hhvm/hhvm --version
HipHop VM 4.0.0-dev (rel)
Compiler: heads/master-0-g27796c0ed145127bb5526b90e888de1b07f58413
Repo schema: 1b7d82b1e3ed737590fa60de697520569a221edf

These failures are no longer present in a build from this morning.
