### ISSUE TITLE
hh_client doesn't complain about $GLOBALS in strict mode anymore

### ISSUE THREAD

**Issue by ssandler** [facebook/hhvm#8420]
### HHVM Version

```
HipHop VM 3.30.2 (rel)
Compiler: remotes/origin/3.30.2-slack-0-g327d860eb6f5b8c13c31d2674d607bc9badafafe
Repo schema: 1a3521cc3e29cfd81df07e6b64acade1241f6538
```

### Operating System and Version

Mac OS High Sierra, and Ubuntu 16.04

### Standalone code, or other way to reproduce the problem

```
<?hh // strict

<<__EntryPoint>>
function example(): noreturn {
        $GLOBALS['foo'] = 1;
        exit();
}
```

### Actual result

```
No errors!
```

### Expected result

This is what happens under 3.29 and prior releases in strict mode files. Since I'm told removing $GLOBALS from Hack entirely is on the roadmap, it'd be great to continue banning them in strict mode.

```
Undefined variable: $GLOBALS (Naming[2050])
```

**Comment by fredemmott** [comment]
Fixed in4.0
