### ISSUE TITLE
variable_variables.php regression test fails consistently

### ISSUE THREAD

**Issue by swalk-cavium** [facebook/hhvm#8424]
### HHVM Version

swalk@lab-3:/data2/swalk/play.012819a/hhvm$ hphp/hhvm/hhvm --version
HipHop VM 4.0.0-dev (rel)
Compiler: heads/master-0-gf4a14af79ee78cc07bdef643751efdf3886d6efc
Repo schema: ee3866aa56a3f8346d388cc1618622c9a7dc8815

### Operating System and Version

Ubuntu 16.04 aarch64
uname -a
Linux labb-3 4.2.0 #1 SMP Wed Nov 25 14:00:54 CST 2015 aarch64 aarch64 aarch64 GNU/Linux

### Standalone code, or other way to reproduce the problem

hphp/test/run hphp/test/spec/tests/variables/variable_variables.php

### Actual result

Fatal error: Variable Variables are not legal in /data2/swalk/play.012819a/hhvm/hphp/test/spec/tests/variables/variable_variables.php on line 17

### Expected result

Pass

Failure introduced between e646717 and f4a14af

I suspect this commit missed updating the test
https://github.com/facebook/hhvm/commit/39a1b840dace68bde80273bc2e4d0b926da60f6b

**Comment by swalk-cavium** [comment]
I should note it fails all 6 option sets tested.

hphp/test/spec/tests/variables/variable_variables.php | F | F | F | F | F | F |

**Comment by fredemmott** [comment]
cc @jano

**Comment by jano** [comment]
fixed by https://github.com/facebook/hhvm/commit/b873299ca290a4d3c2ef30aedd721b89eff56a1c

**Comment by swalk-cavium** [comment]
swalk@lab-3:/data2/swalk/play.013119a/hhvm$ hphp/hhvm/hhvm --version
HipHop VM 4.0.0-dev (rel)
Compiler: heads/master-0-g27796c0ed145127bb5526b90e888de1b07f58413
Repo schema: 1b7d82b1e3ed737590fa60de697520569a221edf

This issue is no longer present in this mornings build.
