### ISSUE TITLE
Regression tests using mysql_ssl_manager_get() fail consistently

### ISSUE THREAD

**Issue by swalk-cavium** [facebook/hhvm#8425]
### HHVM Version

swalk@lab-3:/data2/swalk/play.013119a/hhvm$ hphp/hhvm/hhvm --version
HipHop VM 4.0.0-dev (rel)
Compiler: heads/master-0-g27796c0ed145127bb5526b90e888de1b07f58413
Repo schema: 1b7d82b1e3ed737590fa60de697520569a221edf

### Operating System and Version

uname -a
Linux lab-3 4.2.0 #1 SMP Wed Nov 25 14:00:54 CST 2015 aarch64 aarch64 aarch64 GNU/Linux

### Standalone code, or other way to reproduce the problem

hphp/test/run hphp/test/slow/hack_arr_compat/mysql_ssl_manager_get_dv_array_hack_arr.php
hphp/test/run hphp/test/slow/hack_arr_compat/mysql_ssl_manager_get_typehint_notices.php

### Actual result

Fails with 6 different option sets

hphp/test/slow/hack_arr_compat/mysql_ssl_manager_get_dv_array_hack_arr.php | F | F | F | F | F | F | 
hphp/test/slow/hack_arr_compat/mysql_ssl_manager_get_typehint_notices.php | F | F | F | F | F | F | 

### Expected result

Pass.

Checking logs showed they first showed up in my testing on January 14th.

Example failure

FAILED: hphp/test/slow/hack_arr_compat/mysql_ssl_manager_get_typehint_notices.php
001+ Fatal error: Call to undefined function mysql_ssl_manager_get() in /data2/swalk/play.013119a/hhvm/hphp/test/slow/hack_arr_compat/mysql_ssl_manager_get_typehint_notices.php on line 11

**Comment by fredemmott** [comment]
FB: T39900936
