### ISSUE TITLE
CLI server: client does not exit on script completion

### ISSUE THREAD

**Issue by ssandler** [facebook/hhvm#8430]
### HHVM Version

```
$ hhvm --version
HipHop VM 3.30.2 (rel)
Compiler: remotes/origin/3.30.2-slack-0-g327d860eb6f5b8c13c31d2674d607bc9badafafe
Repo schema: 1a3521cc3e29cfd81df07e6b64acade1241f6538
```

### Operating System and Version

Ubuntu 16.04

Notable this does not repro on OSX

### Standalone code, or other way to reproduce the problem

```

$ hhvm -m server -d hhvm.unix_server_path=/tmp/mysock &

$ cat test.php
<?hh
echo 'test';

$ hhvm -d hhvm.use_remote_unix_server=true -d hhvm.unix_server_path=/tmp/mysock test.php
test
```

### Actual result

The client process hangs and does not return control after the script completes.

### Expected result

The client process exits when the script completes.

**Comment by fredemmott** [comment]
FYI, unlikely to look at this before 4.0, but I suspect a fix would be a candiate for backporting to both 4.0 and 3.30

**Comment by zuercher** [comment]
For reference, this bug describes the problem that occurs in the cli client: https://bugzilla.kernel.org/show_bug.cgi?id=40852
