### ISSUE TITLE
after updating centos release the hhvm hangs after a while

### ISSUE THREAD

**Issue by momkin** [facebook/hhvm#8431]
### HHVM Version
3.24.6
> Please include the output of `hhvm --version` and `hh_client --version`
HipHop VM 3.24.6 (rel)
Compiler: tags/HHVM-3.24.6-0-g5f227331c426ef58513feb5c92ffd0a705067b2f
Repo schema: e7d86156f8550752f1ab3668db770af9d0f1e995

hh-dc48b801c987d6855e5debe9f40facef9bf74f33-3.24.6 Fri Mar 30 20:24:20 2018

### Operating System and Version
CentOS Linux release 7.6.1810 (Core)
> For example, 'Debian Squeeze', 'Ubuntu 16.04', 'MacOS High Sierra'. Please
> also mention if you are using Docker or similar images.

### Standalone code, or other way to reproduce the problem
Using hhvm as fastcgi with nginx and wordpress its working fine for 1 day or 2 days after that hhvm it stopping takes any more connections it just hangs i'm pretty sure this happened after updating the centos release , but I'm not sure which one caused it !

**Comment by fredemmott** [comment]
3.24 is unsupported; do you have the same problem with 3.27 or 3.30?

**Comment by fredemmott** [comment]
We also don't support centos.

**Comment by momkin** [comment]
Hi
I'm trying to build another version and i'm getting this

[ 44%] Building CXX object hphp/compiler/CMakeFiles/hphp_analysis.dir/statement/static_statement.cpp.o
[ 44%] Building CXX object hphp/compiler/CMakeFiles/hphp_analysis.dir/statement/switch_statement.cpp.o
[ 44%] Building CXX object hphp/compiler/CMakeFiles/hphp_analysis.dir/statement/throw_statement.cpp.o
[ 44%] Building CXX object hphp/compiler/CMakeFiles/hphp_analysis.dir/statement/trait_alias_statement.cpp.o
[ 44%] Building CXX object hphp/compiler/CMakeFiles/hphp_analysis.dir/statement/trait_prec_statement.cpp.o
[ 44%] Building CXX object hphp/compiler/CMakeFiles/hphp_analysis.dir/statement/try_statement.cpp.o
[ 45%] Building CXX object hphp/compiler/CMakeFiles/hphp_analysis.dir/statement/typedef_statement.cpp.o
[ 45%] Building CXX object hphp/compiler/CMakeFiles/hphp_analysis.dir/statement/unset_statement.cpp.o
[ 45%] Building CXX object hphp/compiler/CMakeFiles/hphp_analysis.dir/statement/use_trait_statement.cpp.o
[ 45%] Building CXX object hphp/compiler/CMakeFiles/hphp_analysis.dir/statement/using_statement.cpp.o
[ 45%] Building CXX object hphp/compiler/CMakeFiles/hphp_analysis.dir/statement/while_statement.cpp.o
[ 45%] Building CXX object hphp/compiler/CMakeFiles/hphp_analysis.dir/analysis/analysis_result.cpp.o
[ 45%] Building CXX object hphp/compiler/CMakeFiles/hphp_analysis.dir/analysis/block_scope.cpp.o
[ 45%] Building CXX object hphp/compiler/CMakeFiles/hphp_analysis.dir/analysis/class_scope.cpp.o
[ 45%] Building CXX object hphp/compiler/CMakeFiles/hphp_analysis.dir/analysis/code_error.cpp.o
[ 45%] Building CXX object hphp/compiler/CMakeFiles/hphp_analysis.dir/analysis/constant_table.cpp.o
[ 45%] Building CXX object hphp/compiler/CMakeFiles/hphp_analysis.dir/analysis/emitter.cpp.o
[ 45%] Building CXX object hphp/compiler/CMakeFiles/hphp_analysis.dir/analysis/file_scope.cpp.o
[ 45%] Building CXX object hphp/compiler/CMakeFiles/hphp_analysis.dir/analysis/function_container.cpp.o
[ 45%] Building CXX object hphp/compiler/CMakeFiles/hphp_analysis.dir/analysis/function_scope.cpp.o
[ 45%] Building CXX object hphp/compiler/CMakeFiles/hphp_analysis.dir/analysis/symbol_table.cpp.o
[ 45%] Building CXX object hphp/compiler/CMakeFiles/hphp_analysis.dir/analysis/variable_table.cpp.o
[ 45%] Building CXX object hphp/compiler/CMakeFiles/hphp_analysis.dir/parser/parser.cpp.o
[ 45%] Linking CXX static library libhphp_analysis.a
[ 45%] Built target hphp_analysis
Scanning dependencies of target ocaml
make[2]: *** No rule to make target `third-party/ocaml/OCAMLBUILD-NOTFOUND', needed by `third-party/ocaml/CMakeFiles/ocaml'.  Stop.
make[1]: *** [third-party/ocaml/CMakeFiles/ocaml.dir/all] Error 2
make: *** [all] Error 2
[root@server-faselhd-com hhvm]#




any idea ?

**Comment by usox** [comment]
I also experienced this issue using centos and it's still existent with 3.30.
My current "solution" is to restart the daemon once in a while.

**Comment by momkin** [comment]
@usox Yes exactly but this is not a solution :(

**Comment by usox** [comment]
@momkin That's why I used the double quotes ;)
Well, I guess its somewhat related to stale resource handles, connections or something like that. I ended up playing with the following config options which MAY help but won't solve the issue at all
```
hhvm.server.thread_count = 256
hhvm.server.request_timeout_seconds = 240
```

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones are very unlikely to be worked on.

This issue has been created some time ago and there is not enough information in this issue to reproduce this issue on a modern build of hhvm. I am closing this issue, since asking for more info and adding a _`needs-more-info`+`no-isolated-repro`-combo_ would turn a large percentage of hhvm's issues into this kind of issue. If you are reading this and have a way to reproduce this issue in a modern hhvm version, feel free to open a new issue.
