### ISSUE TITLE
Parsing of .hhconfig may cause hh_client to fail to start if a comment is not on a new line

### ISSUE THREAD

**Issue by lexidor** [facebook/hhvm#8433]
I am under the assumption that .hhconfig is an .INI file. If it is not, this issue is useless.

### HHVM Version

```
HipHop VM 4.0.0 (rel)
Compiler: 1549919472_533085853
Repo schema: 920765fe2759670c9c32afc13d2051874758f91d
```

### Operating System and Version
Ubuntu 18.10 Cosmic Cuttlefish

### Standalone code, or other way to reproduce the problem

The following script makes a project in ~/Downloads/example_for_hhvm and initializes it with a .hhconfig file that contains: "unsafe_rx = false;". The `;` after false identifies the start of a comment. (You may type anything after the `;` and the issue will persist.)

```
#!/usr/bin/env bash
cd ~/Downloads
mkdir example_for_hhvm
cd example_for_hhvm
echo "unsafe_rx = false;" > ".hhconfig"
hh_client
```

### Actual result

The following text will appear on the terminal in a loop without end and the typechecker will fail to start.

```
For more detailed logs, try `tail -f $(hh_client --monitor-logname) $(hh_client --logname)`
Server launched with the following command:
	'/usr/bin/hh_server' '-d' '/home/lexidor/Downloads/example_for_hhvm' '--waiting-client' '6'
Spawned typechecker (child pid=7064)
Logs will go to /tmp/hh_server/monitor_logs/zShomezSlexidorzSDownloadszSexample_for_hhvm-2019-01-01-01-01-01.monitor_log
```

### Expected result

Hh_client should start normally and conclude that there are no errors.

### Contents of the logs that hh_client created

```
[2019-02-13 00:05:22.063] Loading config exception: (Sys_error "/etc/hh.conf: No such file or directory")
[2019-02-13 00:05:22.063] Could not load config at /etc/hh.conf, using defaults
(Invalid_argument bool_of_string)
Raised at file "format.ml" (inlined), line 239, characters 35-52
Called from file "format.ml", line 465, characters 8-33
Called from file "format.ml", line 480, characters 6-24
```

### Speculation

I guess the ini parser reads `unsafe_rx = false;` and it does not realize that the `;` is not a part of the value `false`. A `;` in an .ini file marks the end of the option and the start of a comment (in the same way that `//` does in .hh files). The `(Invalid_argument bool_of_string)` suggests that the function parsing the file did not pass `false`, but `false;` to the function that converts strings into a boolean value. This function (raises/throws) the exception, causing hh_client to retry over and over.

### Maybe related issues
This issue has a similar symptom (the rapid restarting), but I see no relation in the cause.
https://github.com/facebook/hhvm/issues/8376
#8376

**Comment by fredemmott** [comment]
AIUI it looks like an INI file, but isn't really one - @Wilfred ?

**Comment by fredemmott** [comment]
if that's the case, this is a dupe of #8376  - failed config parsing should give a reasonable error rather than an infinite loop.

**Comment by Wilfred** [comment]
@fredemmott yep, it's a homegrown file parser I'm afraid: https://github.com/facebook/hhvm/blob/master/hphp/hack/src/utils/config_file/config_file.ml

We did briefly discuss expanding the syntax (T38604972) but no concrete plans that I'm aware of.

**Comment by Wilfred** [comment]
FWIW I think adding `;` as comment syntax would be straightforward, and very worthwhile. `.ini` is an informal standard, but `;` is more widely supported for comments than `#` in most implementations. We'll probably see other folks caught out by this.

**Comment by lexidor** [comment]
Still exists under
```
HipHop VM 4.8.2 (rel)
Compiler: 1565220739_233913246
Repo schema: bd717b9b8a480df6180545a61316a52a2b6a92d4
```

**Comment by lexidor** [comment]
Needed to update the repro from `assume_php` to `unsafe_rx`, because it doesn't break with options that hh_client won't recognize.

I must have used a different option to test with with on Aug the 8th when testing under hhvm 4.8.2.

**Comment by lexidor** [comment]
Closing the issue, since adding `;` support at the end of a line is a very specific feature request.
The loop on failwith is a diffferent issue altogether, covered better by #8376.
