### ISSUE TITLE
Proxygen doesn't evaluate .hack files

### ISSUE THREAD

**Issue by azjezz** [facebook/hhvm#8440]
### HHVM Version

```
➜  nuxed-skeleton git:(master) ✗ hhvm --version
HipHop VM 4.0.0 (rel)
Compiler: 1549919361_837612118
Repo schema: 45c3d71f445f3a2a2c0482dabcc8333ead89a5ff
➜  nuxed-skeleton git:(master) ✗ hh_client --version

hh--4.0.0 Mon Feb 11 22:12:31 2019
➜  nuxed-skeleton git:(master) ✗ 
```

### Operating System and Version

Ubuntu 18.04 LTS

### Standalone code, or other way to reproduce the problem

`main.hack`
```
<<__EntryPoint>>
async function main(): Awaitable<noreturn> {
    echo 'Hello, World!';
    exit(0);
}
```
`server.ini`
```
hhvm.jit=1
hhvm.force_hh=true
hhvm.server.port = 8080
hhvm.server.type = "proxygen"
hhvm.server.default_document = "main.hack"
hhvm.server.error_document404 = "main.hack"
hhvm.server.utf8ize_replace = true
hhvm.log.file=/tmp/hhvm-proxygen-log.txt
```
Run the following command and visit http://localhost:8080 in your browser : 
```
$ hhvm -m daemon -c path/to/server.ini
```

### Actual result
Proxygen sends the `main.hack` file content over the wire :scream: 
### Expected result
the `main.hack` file gets evaluated and i see `Hello, World`

**Comment by azjezz** [comment]
when visiting `/foo` per example, proxygen executes the hack file normally.

**Comment by fredemmott** [comment]
Will be changed to work by default, but `hhvm.php_file.extensions[hack]=1` is the needed INI setting
