### ISSUE TITLE
Help explain pass by ref in hhvm 4.x

### ISSUE THREAD

**Issue by HillLiu** [facebook/hhvm#8444]
Before hhvm 4.x and php 7.x version, we only need add ampersand (&) with function declaration, but don't need pass with call.

such as following example.
http://php.net/manual/en/language.references.pass.php

But in hhvm 4 look like change the behavior, we need pass ampersand with call such as 
```
$arr = [1, 2, 3];
array_pop(&$arr);
```

I have several unit test fail cause by it, Just want make sure is it expected in hhvm4.x ?

## Fatal error message.
Fatal error: Uncaught exception 'InvalidArgumentException' with message 'array_pop() expects parameter 1 by reference, but the call was not annotated with '&'' 

## Issue version
http://dl.hhvm.com/ubuntu trusty/main amd64 hhvm amd64 4.0.1-1~trusty

## Travis report
https://travis-ci.org/pmvc-plugin/debug/jobs/494234980

**Comment by jjgriego** [comment]
Yes, this was a breaking change in 4.0.0

> Breaking Changes
> [...]
> All by-ref parameters must be marked with & at the callsite. This was previously a typechecker error, and is now also a runtime error.

https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html

**Comment by HillLiu** [comment]
Thanks!
