### ISSUE TITLE
Build error: Could not find ICU

### ISSUE THREAD

**Issue by vsiles** [facebook/hhvm#8445]
### HHVM Version

Not available, build failed

### Operating System and Version

MacOS Mojave 10.14.3

### Standalone code, or other way to reproduce the problem

Following http://docs.hhvm.com/hhvm/installation/building-from-source I ran:
```
brew tap hhvm/hhvm
brew deps --include-build hhvm | xargs brew install
git clone git://github.com/facebook/hhvm.git
cd hhvm
git submodule update --init --recursive
```
and the `cmake` invocation fails with 
```
CMake Error at CMake/FindICU.cmake:91 (MESSAGE):
  Could not find ICU
Call Stack (most recent call first):
  CMake/HPHPFindLibs.cmake:155 (find_package)
  CMakeLists.txt:106 (include)


-- Configuring incomplete, errors occurred!
See also "/Users/vsiles/Documents/work/hhvm/CMakeFiles/CMakeOutput.log".
See also "/Users/vsiles/Documents/work/hhvm/CMakeFiles/CMakeError.log".
```
(Both .log files are attached)
[CMakeError.log](https://github.com/facebook/hhvm/files/2876609/CMakeError.log)
[CMakeOutput.log](https://github.com/facebook/hhvm/files/2876611/CMakeOutput.log)

### Actual result

See previous section

### Expected result

Compilation success.

**Comment by vsiles** [comment]
For the record:
```
$ brew list icu4c
/usr/local/Cellar/icu4c/63.1/bin/derb
/usr/local/Cellar/icu4c/63.1/bin/genbrk
/usr/local/Cellar/icu4c/63.1/bin/gencfu
/usr/local/Cellar/icu4c/63.1/bin/gencnval
/usr/local/Cellar/icu4c/63.1/bin/gendict
/usr/local/Cellar/icu4c/63.1/bin/genrb
/usr/local/Cellar/icu4c/63.1/bin/icu-config
/usr/local/Cellar/icu4c/63.1/bin/icuinfo
/usr/local/Cellar/icu4c/63.1/bin/makeconv
/usr/local/Cellar/icu4c/63.1/bin/pkgdata
/usr/local/Cellar/icu4c/63.1/bin/uconv
/usr/local/Cellar/icu4c/63.1/include/unicode/ (183 files)
/usr/local/Cellar/icu4c/63.1/lib/libicudata.63.1.dylib
/usr/local/Cellar/icu4c/63.1/lib/libicui18n.63.1.dylib
/usr/local/Cellar/icu4c/63.1/lib/libicuio.63.1.dylib
/usr/local/Cellar/icu4c/63.1/lib/libicutest.63.1.dylib
/usr/local/Cellar/icu4c/63.1/lib/libicutu.63.1.dylib
/usr/local/Cellar/icu4c/63.1/lib/libicuuc.63.1.dylib
/usr/local/Cellar/icu4c/63.1/lib/icu/ (4 files)
/usr/local/Cellar/icu4c/63.1/lib/pkgconfig/ (3 files)
/usr/local/Cellar/icu4c/63.1/lib/ (18 other files)
/usr/local/Cellar/icu4c/63.1/sbin/escapesrc
/usr/local/Cellar/icu4c/63.1/sbin/genccode
/usr/local/Cellar/icu4c/63.1/sbin/gencmn
/usr/local/Cellar/icu4c/63.1/sbin/gennorm2
/usr/local/Cellar/icu4c/63.1/sbin/gensprep
/usr/local/Cellar/icu4c/63.1/sbin/icupkg
/usr/local/Cellar/icu4c/63.1/share/icu/ (4 files)
/usr/local/Cellar/icu4c/63.1/share/man/ (14 files)
```

**Comment by fredemmott** [comment]
Did you follow the instructions in this section? https://docs.hhvm.com/hhvm/installation/building-from-source#building-hhvm__macos

CMakeOutput shows `Compiler: /Applications/Xcode_10.1_fb.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ 
`  - which should have been overridden by `brew sh`

**Comment by vsiles** [comment]
I really don't remember. I'll try again and let you know !

**Comment by vsiles** [comment]
it seems that now it works, so I must have forgotten the `brew sh` step last time. Now it breaks with a lot of `_caml` missing symbols: `ld: symbol(s) not found for architecture x86_64`
But iirc, that's an issue with brew which might not have the correct links set up, so it's a different (and me only) problem.
