### ISSUE TITLE
Make builtins throw ..., introduces regression test failure

### ISSUE THREAD

**Issue by swalk-cavium** [facebook/hhvm#8455]
### HHVM Version

lab-7:~/extra/play.022819a/hhvm$ hphp/hhvm/hhvm --version
HipHop VM 4.1.0-dev (rel)
Compiler: heads/master-0-ga3638a796bb94fb74383a273031b068d6113efeb
Repo schema: e87c35514d08876eba0bd8bc3dc6c92468dee9c8

swalk@dellx3:~/play.022819a/hhvm$ hphp/hhvm/hhvm --version
HipHop VM 4.1.0-dev (rel)
Compiler: heads/master-0-ga3638a796bb94fb74383a273031b068d6113efeb
Repo schema: e87c35514d08876eba0bd8bc3dc6c92468dee9c8
### Operating System and Version

Two machines  - both Ubuntu 16.04

uname -a
Linux lab-7 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:15:48 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux

swalk@dellx3:~/play.022819a/hhvm$ uname -a
Linux dellx3 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

### Standalone code, or other way to reproduce the problem

hphp/test/run -v -m interp
hphp/test/run -v -m interp -r
hphp/test/run -v -m jit -a '-vEval.JitPGO=0'
hphp/test/run -v -m jit -r -a '-vEval.JitPGO=0'
hphp/test/run -v -m jit -a '-vEval.JitPGO=1'
hphp/test/run -v -m jit -r -a '-vEval.JitPGO=1'

### Actual result

Post-processed report below.  Columns line up with option sets above.

hphp/test/slow/typecheck/type_coersion_hh.php | F | F | F | F | F | F |

### Expected result

Pass

This showed up in my testing of 02/28/2019.
Suspect this commit
https://github.com/facebook/hhvm/commit/5763173f8f3dc1d8145d57ea82851f9859108477

**Comment by swalk-cavium** [comment]
Command output

lab-7:~/extra/play.022819a/hhvm$ ./hphp/hhvm/hhvm -c hphp/test/slow/typecheck/type_coersion_hh.php.ini -vEval.EnableArgsInBacktraces=true -vEval.EnableIntrinsicsExtension=true -vEval.HHIRInliningIgnoreHints=false -vRepo.Local.Mode=-- -vRepo.Central.Path=/mnt/diskb/swalk/play.022819a/hhvm/hphp/hhvm/verify.hhbc -vEval.Jit=true  -vEval.ProfileHWEnable=false -vEval.HackCompilerExtractPath='/mnt/diskb/swalk/play.022819a/hhvm/hphp/hhvm/hackc_%{schema}' -vEval.EmbeddedDataExtractPath='/mnt/diskb/swalk/play.022819a/hhvm/hphp/hhvm/hhvm_%{type}_%{buildid}'   -vResourceLimit.CoreFileSize=0    --file 'hphp/test/slow/typecheck/type_coersion_hh.php' 

Boolean

Fatal error: Uncaught TypeError: sha1() expects parameter 2 to be boolean, array given in /mnt/diskb/swalk/play.022819a/hhvm/hphp/test/slow/typecheck/type_coersion_hh.php:21
Stack trace:
#0 /mnt/diskb/swalk/play.022819a/hhvm/hphp/test/slow/typecheck/type_coersion_hh.php(21): sha1()
#1 /mnt/diskb/swalk/play.022819a/hhvm/hphp/test/slow/typecheck/type_coersion_hh.php(12): Closure$main_type_coersion_hh()
#2 /mnt/diskb/swalk/play.022819a/hhvm/hphp/test/slow/typecheck/type_coersion_hh.php(21): check()
#3 (): main_type_coersion_hh()
#4 {main}

**Comment by WizKid** [comment]
Not sure why I missed it. I'll fix it.

**Comment by WizKid** [comment]
So the problem is that for some reason the test is running in PHP7 mode for you. Which it shouldn't. Not sure if that is an opensource thing or something you have in some config. When not running in PHP7 mode it will throw a RuntimeException which the test catches and prints a Warning.

**Comment by swalk-cavium** [comment]
Hi @WizKid ,
My scripts do a fresh clone and submodule update every
night.  So it's most likely something presented to open source.
Where would this config information be set?

**Comment by swalk-cavium** [comment]
# 8455 - seems fixed.
swalk@lab-7:~/extra$ grep -n type_coersion_hh play.*/hhvm/bad*
play.022819a/hhvm/bad.022819a:26:hphp/test/slow/typecheck/type_coersion_hh.php | F | F | F | F | F | F | 
play.030119a/hhvm/bad.030119a:26:hphp/test/slow/typecheck/type_coersion_hh.php | F | F | F | F | F | F | 
play.030419a/hhvm/bad.030419a:25:hphp/test/slow/typecheck/type_coersion_hh.php | F | F | F | F | F | F | 
 
- last failed at this commit
swalk@lab-7:~/extra/play.030419a/hhvm$ git branch -v
* master f715c4a Improve error messages produced by the new inference algorithm when type-checking stringish objects

- no longer present
swalk@lab-7:~/extra/play.030619a/hhvm$ git branch -v
* master 3e218cb Fix a bunch of bugs (part 2)
