### ISSUE TITLE
Remove \Traversable, consistently use \HH\Traversable

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#8465]
at runtime, we currently have `\HH\Traversable<T>` and `\Traversable`. This is so that PHP code could could do, for example:

```
class Foo implements IteratorAggregate {
  public function getIterator() { 
    /* foo */
  }
}
```

PHP code also needed to be allowed to do `getIterator(): Traversable`

To be an `\HH\Traversable`, it would need to be `getIterator(): Traversable<T>` - or if `\Traversable` were an `\HH\Traversable<mixed>`, `getIterator(): Traversable<mixed>` would be required, breaking PHP compatibility.

We're no longer PHP-compatible, so this separation is no longer required.

The typechecker wasn't fully aware of this distinction, leading to runtime errors without typechecker errors. For example, the HHI files define `IteratorAggregate<+Tv>` with `getIterator(): Iterator<Tv>`, but when PHP was supported, IteratorAggregate could not be an `HH\Traversable` at runtime, so was not accepted by Hack functions taking 'Traversable'

**Comment by lexidor** [comment]
@fredemmott Fixed by https://github.com/facebook/hhvm/commit/7f4b187f5e39de84ea4c559175d3a96d03461cb8
