### ISSUE TITLE
hhvm requires \Iterator to implement key

### ISSUE THREAD

**Issue by ryangreenberg** [facebook/hhvm#8467]
### HHVM Version

```
hhvm --version
HipHop VM 4.0.3 (rel)
Compiler: 1551382911_N
Repo schema: 738e610628295bb89d752ed238c444f9687b1b67

hh_client --version
hh-fa45631b553ac2d50ded6d0edca9de77f9b2cd3f-4.0.3 Thu Feb 28 11:43:15 2019
```

### Operating System and Version

MacOS High Sierra

```
$ uname -a
Darwin [COMPUTERNAME] 17.7.0 Darwin Kernel Version 17.7.0: Thu Dec 20 21:47:19 PST 2018; root:xnu-4570.71.22~1/RELEASE_X86_64 x86_64
```

### Standalone code, or other way to reproduce the problem

See https://gist.github.com/ryangreenberg/26535ab2f9ba55b6a28f79804033e0a8

File square_iterator.php: 

```hack
<?hh // strict

/**
 * Sample iterator for demonstrating issues with Iterator
 */
final class SquareIterator implements Iterator<int> {
	private int $curr = 0;
	final public function __construct(private int $i) {
	}

	public function current(): int {
		return $this->curr * $this->curr;
	}

	public function next(): void {
		$this->curr += 1;
	}

	public function rewind(): void {
		$this->curr = 0;
	}

	public function valid(): bool {
		return $this->curr <= $this->i;
	}
}

<<__EntryPoint>>
function si_example(): noreturn {
	foreach(new SquareIterator(5) as $sq) {
		echo "$sq\n";
	}
	exit();
}
```

### Actual result

```
$ hhvm square_iterator.php 

Fatal error: Uncaught Error: Class SquareIterator contains abstract method (key) and must therefore be declared abstract or implement the remaining methods in […]/iterator_repro/square_iterator.php:6
Stack trace:
#0 {main}
```

### Expected result

SquareIterator does not cause a runtime error because `hh_client` reports "No errors" and it implements all the methods of the `Iterator` interface.

---

This issue may reflect my fundamental ignorance about how Iterator and KeyedIterator worked in PHP/work in Hack, but it seems like:

- (a) the interface for Iterator is wrong
- (b) the runtime should not require `key`
- (c) some other option

**Comment by fredemmott** [comment]
it's (a) for most of this hierarchy, including #8465

**Comment by lexidor** [comment]
@ryangreenberg \Iterator has been removed from the runtime 15 minutes ago. https://github.com/facebook/hhvm/commit/7f4b187f5e39de84ea4c559175d3a96d03461cb8
