### ISSUE TITLE
Probably easy - Remove mention of the zend compat layer from the extension wiki page

### ISSUE THREAD

**Issue by lexidor** [facebook/hhvm#8475]
### HHVM Version
N/A
### Operating System and Version
N/A
### Standalone code, or other way to reproduce the problem
N/A
### Actual result
https://github.com/facebook/hhvm/wiki/Extension-API mentions the existance of the zend compat layer.
### Expected result
The zend compat layer does not exist anymore, so it ought to be changed.

**Comment by fredemmott** [comment]
We should probably just remove the wiki; it's completely unmaintained and mostly ~ 5 years stale.

**Comment by lexidor** [comment]
Pulled out into separate issue.
