### ISSUE TITLE
Semantic error in hphp/test/slow/ext_memcached/cas.php

### ISSUE THREAD

**Issue by swalk-cavium** [facebook/hhvm#8477]
### HHVM Version

swalk@lab-7:~/extra/play.040519a/hhvm$ hphp/hhvm/hhvm --version
HipHop VM 4.1.0-dev (rel)
Compiler: heads/master-0-g6f5d83a3c74fccf165bb11d182e8b11b947c9891
Repo schema: 2f56021fdbf8e88de8eb2d20f02d8a1f609643fc

### Operating System and Version

Ubuntu 16.04
swalk@lab-7:~/extra/play.040519a/hhvm$ uname -a
Linux lab-7 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:15:48 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux

### Standalone code, or other way to reproduce the problem

hphp/test/run -v -m interp
hphp/test/run -v -m interp -r
hphp/test/run -v -m jit -a '-vEval.JitPGO=0'
hphp/test/run -v -m jit -r -a '-vEval.JitPGO=0'
hphp/test/run -v -m jit -a '-vEval.JitPGO=1'
hphp/test/run -v -m jit -r -a '-vEval.JitPGO=1'

### Actual result

Post-processed report below. Columns line up with option sets above.

hphp/test/slow/ext_memcached/cas.php | F | F | F | F | F | F | 

### Expected result

pass

swalk@lab-7:~/extra/play.040519a/hhvm$ ./hphp/hhvm/hhvm -c /mnt/diskb/swalk/play.040419a/hhvm/hphp/test/slow/config.ini -vEval.EnableArgsInBacktraces=true -vEval.EnableIntrinsicsExtension=true -vEval.HHIRInliningIgnoreHints=false -vRepo.Local.Mode=-- -vRepo.Central.Path=/mnt/diskb/swalk/play.040419a/hhvm/hphp/hhvm/verify.hhbc -vEval.Jit=true  -vEval.ProfileHWEnable=false -vEval.HackCompilerExtractPath='/mnt/diskb/swalk/play.040419a/hhvm/hphp/hhvm/hackc_%{schema}' -vEval.EmbeddedDataExtractPath='/mnt/diskb/swalk/play.040419a/hhvm/hphp/hhvm/hhvm_%{type}_%{buildid}'  -vResourceLimit.CoreFileSize=0    --file 'hphp/test/slow/ext_memcached/cas.php' 
bool(true)

Notice: Undefined variable: cas in /mnt/diskb/swalk/play.040519a/hhvm/hphp/test/slow/ext_memcached/cas.php on line 9

Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Memcached::get() expects parameter 3 by reference, but the call was not annotated with '&'' in /mnt/diskb/swalk/play.040519a/hhvm/hphp/test/slow/ext_memcached/cas.php:9
Stack trace:
#0 {main}

**Comment by billf** [comment]
fixed in b76dbb6a0a1e3d0dd458806fef1b68e513f21e38

**Comment by swalk-cavium** [comment]
Problem no longer appears in build from today.
Thanks for the quick fix.

hphp/test/slow/ext_memcached/cas.php passed 
hphp/test/slow/ext_memcached/cas.php passed
hphp/test/slow/ext_memcached/cas.php passed 
hphp/test/slow/ext_memcached/cas.php passed
hphp/test/slow/ext_memcached/cas.php passed 
swalk@lab-7:~/extra/play.041119a/hhvm$ git branch -v
* master 597ca65 New native HH\int_mul_overflow, HH\int_mul_add_overflow
