### ISSUE TITLE
[Feature Request][Wishlist] Add native async redis client

### ISSUE THREAD

**Issue by azjezz** [facebook/hhvm#8478]
- asynchronous non-blocking
- built-in connection pool
- support concurrent requests

**Comment by azjezz** [comment]
PS: this won't be necessary if hhvm/hsl-experimental#36 is implemented ( which needs #8451 to be implemented in hack ), as implementing an async redis client would be possible using `HH\Lib\Network\TcpSocket`.

**Comment by fredemmott** [comment]
Closing - the goal is for this to replaced by async HSL IO sockets; we're aiming to minimize the number of extensions, especially when pure Hack code is going to be a better solution long-term.
