### ISSUE TITLE
authoritative mode mysqli and bind_params

### ISSUE THREAD

**Issue by marcodepolo** [facebook/hhvm#8486]
Hello,

I have some code that I'm trying to port from hhvm 3.15 with authoritative mode to 3.27-lts 

Its working fine with mode authoritative switched off but when I turn it on, it seems the code is unable to pass the parameter to the mysqli bind_params function. 

### HHVM Version
root@a8e0176b1762:/# hhvm --version
HipHop VM 3.27.8 (rel)
Compiler: 1554315357_125187996
Repo schema: d9bf9fa970f475c836b9bc37750baf74ceb70759

root@a8e0176b1762:/# hh_client --version
hh-e6d25982534cd57e1e7fa1e990dcb876c981b957-3.27.8 Thu Apr  4 01:18:04 2019

### Operating System and Version
docker base image
FROM hhvm/hhvm-proxygen:3.27-lts-latest

### Standalone code, or other way to reproduce the problem
function doLogin($config, $myusername, $mypassword){
	ob_start();
	$mysqli = connect();
	// To protect MySQL injection
	$myusername = filter_var(stripslashes($myusername), FILTER_SANITIZE_STRING); 
	$mypassword = filter_var(stripslashes($mypassword), FILTER_SANITIZE_STRING);

	/**
	 * 
	 * use prepared statements for sql query to prevent sqli
	 */
	$stmt = $mysqli->prepare("SELECT P.ID, P.FAILED, P.APPPASSWORD, R.NAME as ROLENAME, P.ROLE as ROLE, POSID 
								FROM PEOPLE P
								JOIN ROLES R ON P.ROLE=R.ID
								WHERE P.VISIBLE=1 AND P.NAME = ? and P.ROLE=R.ID");
       // tried to change this call to $stmt->bind_param("s", &$myusername) but the error persists
	if (!$stmt->bind_param("s", $myusername)) {
	    logDebug("Binding parameters failed: (" . $stmt->errno . ") " . $stmt->error);
	}

### Actual result
debug log messages shows the bind failed and statement didn't receive any value.

2019-04-15 08:31:54	Binding parameters failed: (0) 
2019-04-15 08:31:54	1st db stmt failed to exec : No data supplied for parameters in prepared statement

hhvm log message shows the argument was not passed as reference

2019-04-15 08:31:54,191 DEBG 'hhvm' stdout output:
\nWarning: Argument 1 not passed as reference in /var/www/html/src-pos/lib-shared.php on line 4296

### Expected result
bind_param should succeed and stmt should execute successfully. 

Any help would be greatly appreciated

**Comment by marcodepolo** [comment]
For the record I had to switch to use PDO drivers whenever bind_param is needed

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

I actually had this issue myself when on hhvm 4.8, but it failed because the argument should be a `&$reference` and not a `&$reference` at the same time.

Mysqli support has been removed in hhvm [4.9.0](https://hhvm.com/blog/2019/06/10/hhvm-4.9.0.html).
