### ISSUE TITLE
Repo Authoritative Mode - 404 

### ISSUE THREAD

**Issue by JonatanBarr** [facebook/hhvm#8493]
HHVM Version : 4.2.0 
Operating System and Version: Linux Mint 18.2

Repo Authoritative Mode always returns 404, both in fastcgi and proxygen mode. hhvm.hhbc works only when using command line. Another user has the same problem on stackoverflow:
https://stackoverflow.com/questions/53561443/hhvm-repo-authoritative-delete-source 

(and yes these rows are in server.ini :
hhvm.repo.authoritative = true
hhvm.repo.central.path = /var/cache/hhvm/hhvm.hhbc)

**Comment by fredemmott** [comment]
Does the file exist? It doesn't need to actualy have the code, but the entrypoint file must be present on disk - e.g. if you run everything through index.php, `touch index.php` may fix it

**Comment by JonatanBarr** [comment]
`touch index.php` solved my problem. Should've thought of that! Now it works fine.

**Comment by lexidor** [comment]
This issue may be closed.
