### ISSUE TITLE
Allow to define anonymous functions for <<__EntryPoint>>

### ISSUE THREAD

**Issue by juanfernandoe** [facebook/hhvm#8495]
### HHVM Version
4.2

Please allow the below synxtax, in this way developer don't have to care about pickup a unique name for the main function.

```php
<<__EntryPoint>>
function(): noreturn {
   echo "Ok";
   exit(0);
}

**Comment by billf** [comment]
i doubt this is a feature we would add. we are moving towards not allowing code at the top-level and the "pseudo-main" that we create to wrap such code. imo, the amount of complexity that would be added to support a lambda in this position outweighs the convenience.

picking a unique function name is not hard once a standard is defined in a repository.
e.g. `foo/bar/script.php` can be `foo_bar_script_main()` or `FooBarScriptMain()` or `Foo_Bar_Script()`.

**Comment by fredemmott** [comment]
> e.g. foo/bar/script.php can be foo_bar_script_main() or FooBarScriptMain() or Foo_Bar_Script().

This needs to be combined with namespaces when not in a monorepo

**Comment by juanfernandoe** [comment]
Thanks for your ideas, currently I'm doing it like @fredemmott advise with namespace prefix.

foo/bar/script.php is FooBarScript_main()

**Comment by fredemmott** [comment]
Yeah, this seems extremely unlikely, and would be adding an unintuitive special case.
