### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by xywf221** [facebook/hhvm#8505]
### HHVM Version

HipHop VM 4.5.0 (rel)
Compiler: 1557767777_N
Repo schema: da39a3ee5e6b4b0d3255bfef95601890afd80709

### Operating System and Version

> MacOS Mojave

### Standalone code, or other way to reproduce the problem

I just tried to run hhvm --modules

### Actual result

[1]    24264 segmentation fault  hhvm --modules

### Expected result
show modules list!

**Comment by swalk-cavium** [comment]
Reproducible with yesterday's build on x86_64 and Aarch64.  Same failure signature.
Ubuntu 16.04
Linux lab-7 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:15:48 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux

swalk@lab-7:~/extra/play.052019a/hhvm$ hphp/hhvm/hhvm --version
HipHop VM 4.6.0-dev (rel)
Compiler: heads/master-0-g1da07f66fb0ac52ffc21e56311f90e3cf09eaca6
Repo schema: 3ba663ffa96fcc6996dcc2fd000435ba310662b8

(gdb) run --modules
Starting program: /mnt/diskb/swalk/play.052019a/hhvm/hphp/hhvm/hhvm --modules
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x000000000156e3dc in HPHP::MemoryManager::MemoryManager() ()
(gdb) thread apply all bt

Thread 1 (Thread 0xffffb4009010 (LWP 2649)):
#0  0x000000000156e3dc in HPHP::MemoryManager::MemoryManager() ()
#1  0x000000000141d97c in HPHP::execute_program_impl(int, char**) ()
#2  0x0000000001421bc4 in HPHP::execute_program(int, char**) ()
#3  0x0000000000cabecc in main ()
(gdb) 

Ubuntu 16.04
swalk@dellx3:~/play.052019a/hhvm$ uname -a
Linux dellx3 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
swalk@dellx3:~/play.052019a/hhvm$ hphp/hhvm/hhvm --version
HipHop VM 4.6.0-dev (rel)
Compiler: heads/master-0-g1da07f66fb0ac52ffc21e56311f90e3cf09eaca6
Repo schema: 1a27d20bb35f7dc5bce75bdf8346650e7d10d33c

(gdb) run --modules
Starting program: /home/swalk/play.052019a/hhvm/hphp/hhvm/hhvm --modules
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x000000000127cae4 in HPHP::MemoryManager::MemoryManager() ()
(gdb) thread apply all bt

Thread 1 (Thread 0x7ffff7fac840 (LWP 130243)):
#0  0x000000000127cae4 in HPHP::MemoryManager::MemoryManager() ()
#1  0x000000000161f806 in HPHP::execute_program_impl(int, char**) ()
#2  0x0000000001625930 in HPHP::execute_program(int, char**) ()
#3  0x0000000000c59241 in main ()
(gdb)

**Comment by fredemmott** [comment]
#6857
