### ISSUE TITLE
`AsyncMysqlConnection::queryf($format, ConstVector<mixed>)` may take `Container<mixed>`

### ISSUE THREAD

**Issue by lexidor** [facebook/hhvm#8510]
### HHVM Version

> Please include the output of `hhvm --version` and `hh_client --version`

```
Irrelevant 
HipHop VM 4.7.0 (rel)
Compiler: 1559070843_624481102
Repo schema: 2e1c72ec50ffb24346232d06dcc85156f2787281
```
### Operating System and Version

Irrelevant Ubuntu 18.04

### Standalone code, or other way to reproduce the problem

```HACK
$vec = vec[1,6,3];
await $connection->queryf('SELECT * FROM mytable WHERE id IN(%Ls)', $vec);
```

### Actual result

```
Typing[4110] Invalid argument
   --> src/lib/Posts.hack
 14 |                   'INSERT INTO %T (`content`) VALUES(%Ls)',
    |    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ This is an object of type ConstVector<string> because of the %Ls format specifier
 16 |                   Vec\map($posts, $post ==> $post->getContent()),
    |    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   --> vendor/hhvm/hsl/src/vec/transform.php
104 | ): vec<Tv2> {
    |    ^^^^^^^^ It is incompatible with an object of type vec<[unresolved]>
```

> If applicable, please copy-paste output from `hhvm` or `hh_client`

### Expected result

Don't require a ConstVector. `vec<T>` is great, but having to wrap each call in `new Vector($vec)` is a bummer.

**Comment by fredemmott** [comment]
needs HHI change and support adding to `::queryf()` to support converting vecs to `std::vector<QueryArgument>`

*not* probably-easy as we should also support converting `dicts` to `std::vector<ArgPair>` 

reference: https://github.com/facebookarchive/squangle/blob/f78a84fbed7545cd4ca27e0fbc6a7a6793344da5/squangle/mysql_client/Query.cpp#L586

**Comment by lexidor** [comment]
`AsyncMysqlConnention::queryAsync()` was added to address this.
