### ISSUE TITLE
hphp/test/slow/ext_scrypt/enc.php fails

### ISSUE THREAD

**Issue by swalk-cavium** [facebook/hhvm#8517]
### HHVM Version

Fails on x86_64 and Aarch64 built on this commit

swalk@lab-7:~/extra/play.061419a/hhvm$ hphp/hhvm/hhvm --version
HipHop VM 4.10.0-dev (rel)
Compiler: heads/master-0-ged76111bea59afdf6ead67000f4aaff80b7f453e
Repo schema: 598eb5a584bdab0353238892ad9952fc286ed030

### Operating System and Version

Ubuntu 16.04

swalk@dellx3:~/play.061419a/hhvm$ uname -a
Linux dellx3 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

swalk@lab-7:~/extra/play.061419a/hhvm$ uname -a
Linux 1scrb-7 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:15:48 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux

### Standalone code, or other way to reproduce the problem

hphp/test/run -v -m interp
hphp/test/run -v -m interp -r
hphp/test/run -v -m jit -a '-vEval.JitPGO=0'
hphp/test/run -v -m jit -r -a '-vEval.JitPGO=0'
hphp/test/run -v -m jit -a '-vEval.JitPGO=1'
hphp/test/run -v -m jit -r -a '-vEval.JitPGO=1'

### Actual result

Post-processed output

hphp/test/slow/ext_scrypt/enc.php | F | F | F | F | F | F | 

### Expected result

Pass

swalk@dellx3:~/play.061419a/hhvm$ ./hphp/hhvm/hhvm -c /home/swalk/play.061419a/hhvm/hphp/test/slow/config.ini -vEval.EnableArgsInBacktraces=true -vEval.EnableIntrinsicsExtension=true -vEval.HHIRInliningIgnoreHints=false -vRepo.Local.Mode=-- -vRepo.Central.Path=/home/swalk/play.061419a/hhvm/hphp/hhvm/verify.hhbc -vEval.Jit=true  -vEval.ProfileHWEnable=false -vEval.HackCompilerExtractPath='/home/swalk/play.061419a/hhvm/hphp/hhvm/hackc_%{schema}' -vEval.EmbeddedDataExtractPath='/home/swalk/play.061419a/hhvm/hphp/hhvm/hhvm_%{type}_%{buildid}'  -vResourceLimit.CoreFileSize=0    --file 'hphp/test/slow/ext_scrypt/enc.php' 

Fatal error: Call to undefined function scrypt_enc() in /home/swalk/play.061419a/hhvm/hphp/test/slow/ext_scrypt/enc.php on line 6

First showed up on testing of 06/12/19.  I waited until after latest third-party update to report.

swalk@lab-7:~/extra$ grep -n 'hphp/test/slow/ext_scrypt/enc.php' play.*/hhvm/bad.*
play.061219a/hhvm/bad.06219a:9:hphp/test/slow/ext_scrypt/enc.php | F | F | F | F | F | F | 
play.061319a/hhvm/bad.061319a:9:hphp/test/slow/ext_scrypt/enc.php | F | F | F | F | F | F | 
play.061419a/hhvm/bad.061419a:10:hphp/test/slow/ext_scrypt/enc.php | F | F | F | F | F | F | 

Started failing between these two builds

```
swalk@lab-7:~/extra$ cd play.061119a/hhvm
swalk@lab-7:~/extra/play.061119a/hhvm$ git branch -v  //<<--- good
* master 6920ef6 hphp/zend: handle new error from curl
swalk@lab-7:~/extra/play.061119a/hhvm$ cd ../../play.061219a/hhvm
swalk@lab-7:~/extra/play.061219a/hhvm$ git branch -v  //<<--- bad
* master 84b58b3 Strip genva optimizations

**Comment by fredemmott** [comment]
Probably cc331e4349e91706a673e2a09f1f2ea5bbb33815 which intentionally made ext_scrypt depend on libsodium; options are:
- install a new enough libsodium (>= 1.0.9 iirc) in your environment
- add skipif files checking for the extension
- wait a little longer for libsodium to become mandatory and built via third-party/ if absent

**Comment by swalk-cavium** [comment]
This test passes in yesterday's build.
~/extra/play.062619a/hhvm$ hphp/hhvm/hhvm --version
HipHop VM 4.12.0-dev (rel)
Compiler: heads/master-0-gec7d1320f5656831aa3c9ce07de3e8c630d81fde
Repo schema: ed69fe2e68001475b689f8329af64754d63f4f5f

~/extra/play.062619a/hhvm$ hphp/test/run -v hphp/test/slow/ext_scrypt/enc.php
You are using the binary located at: ./hphp/hhvm/hhvm
Running 1 tests in 1 threads (0 in serial)
hphp/test/slow/ext_scrypt/enc.php passed (14.74s)
