### ISSUE TITLE
multiple 'await_as_an_expression' failures

### ISSUE THREAD

**Issue by swalk-cavium** [facebook/hhvm#8518]
### HHVM Version

swalk@lab-7:~/extra/play.061819a/hhvm$ hphp/hhvm/hhvm --version
HipHop VM 4.10.0-dev (rel)
Compiler: heads/master-0-g35731a9a61097f798a3b90320f7253f2437b32ed
Repo schema: 0b06970e0da42a072d694b3b988f6899f1c53565

### Operating System and Version

Ubuntu 16.04, Aarch64 and X86_64

swalk@lab-7:~/extra/play.061819a/hhvm$ uname -a
Linux 1scrb-7 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:15:48 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux

swalk@dellx3:~/play.061819a/hhvm$ uname -a
Linux dellx3 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
### Standalone code, or other way to reproduce the problem

hphp/test/run -v -m interp
hphp/test/run -v -m interp -r
hphp/test/run -v -m jit -a '-vEval.JitPGO=0'
hphp/test/run -v -m jit -r -a '-vEval.JitPGO=0'
hphp/test/run -v -m jit -a '-vEval.JitPGO=1'
hphp/test/run -v -m jit -r -a '-vEval.JitPGO=1'

### Actual result

Post-processed report

hphp/test/slow/await_as_an_expression/error/binop2.php | F | F | F | F | F | F | 
hphp/test/slow/await_as_an_expression/error/binop3.php | F | F | F | F | F | F | 
hphp/test/slow/await_as_an_expression/error/binop4.php | F | F | F | F | F | F | 
hphp/test/slow/await_as_an_expression/error/binop5.php | F | F | F | F | F | F | 
hphp/test/slow/await_as_an_expression/error/binop6.php | F | F | F | F | F | F | 
hphp/test/slow/await_as_an_expression/error/binop7.php | F | F | F | F | F | F | 
hphp/test/slow/await_as_an_expression/error/binop8.php | F | F | F | F | F | F | 
hphp/test/slow/await_as_an_expression/error/binop9.php | F | F | F | F | F | F | 
hphp/test/slow/await_as_an_expression/error/cond2.php | F | F | F | F | F | F | 
hphp/test/slow/await_as_an_expression/error/cond3.php | F | F | F | F | F | F | 
hphp/test/slow/await_as_an_expression/error/fn_call2.php | F | F | F | F | F | F | 
hphp/test/slow/await_as_an_expression/error/fn_call4.php | F | F | F | F | F | F | 
hphp/test/slow/await_as_an_expression/error/for2.php | F | F | F | F | F | F | 
hphp/test/slow/await_as_an_expression/error/for3.php | F | F | F | F | F | F | 
hphp/test/slow/await_as_an_expression/error/pipe1.php | F | F | F | F | F | F | 
hphp/test/slow/await_as_an_expression/error/pipe2.php | F | F | F | F | F | F | 
hphp/test/slow/await_as_an_expression/error/pipe4.php | F | F | F | F | F | F | 
hphp/test/slow/await_as_an_expression/error/pipe5.php | F | F | F | F | F | F | 

### Expected result

Pass

swalk@lab-7:~/extra/play.061819a/hhvm$ ./hphp/hhvm/hhvm -c /mnt/diskb/swalk/play.061819a/hhvm/hphp/test/slow/await_as_an_expression/config.ini -vEval.EnableArgsInBacktraces=true -vEval.EnableIntrinsicsExtension=true -vEval.HHIRInliningIgnoreHints=false -vRepo.Local.Mode=-- -vRepo.Central.Path=/mnt/diskb/swalk/play.061819a/hhvm/hphp/hhvm/verify.hhbc -vEval.Jit=true  -vEval.ProfileHWEnable=false -vEval.HackCompilerExtractPath='/mnt/diskb/swalk/play.061819a/hhvm/hphp/hhvm/hackc_%{schema}' -vEval.EmbeddedDataExtractPath='/mnt/diskb/swalk/play.061819a/hhvm/hphp/hhvm/hhvm_%{type}_%{buildid}'  -vResourceLimit.CoreFileSize=0    --file 'hphp/test/slow/await_as_an_expression/error/binop2.php' 

Fatal error: Uncaught Error: Await cannot be used as an expression in this location because it's conditionally executed. in /mnt/diskb/swalk/play.061819a/hhvm/hphp/test/slow/await_as_an_expression/error/binop2.php:15
Stack trace:
#0 {main}

Looks like stack trace breaks expectf

Introduced here:
https://github.com/facebook/hhvm/commit/55e1483badac93a909fce7c24391e2d522d5a194

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Hhvm has had a passing test build since 4.10.0. I assume the broken test has either been fixed or removed.
