### ISSUE TITLE
[Typechecker] is not aware of `\HH\ReifiedGenerics\getClassname<MyType>()`

### ISSUE THREAD

**Issue by lexidor** [facebook/hhvm#8525]
### HHVM Version
```
HipHop VM 4.11.0 (rel)
Compiler: 1561398047_114259580
Repo schema: 520e2fedfb82e52f9393995caea047ec425b15ce
hackc-fc15a7f638ec69c8fdb7df14b24dc3cc49fda256-4.11.0
```

### Operating System and Version
Ubuntu 18.04

### Standalone code, or other way to reproduce the problem
```HACK
function reified<<<__Enforceable>>reify Tex as Exception>(Exception $e): void {
	$classname = \HH\ReifiedGenerics\getClassname<Tex>();
}
```

### Actual result
```

Naming[2049] Unbound name: HH\ReifiedGenerics\getClassname (a global function)Hack(2049)
Naming[2049] Unbound name: HH\ReifiedGenerics\getClassname (a global constant)Hack(2049)
Typing[4107] Unbound name (typing): HH\ReifiedGenerics\getClassnameHack(4107)
```

### Expected result
`$classname` should be a classname<Exception> and `No Errors!`

**Comment by fredemmott** [comment]
FB T46695073

- [x] put up docs for overall feature
- [ ] remove need for experimental option
- [ ] move HH\ReifiedGenerics HHI to main hhvm repo
- [ ] remove version warning from docs once they're shipped in a release

**Comment by fredemmott** [comment]
all done
