### ISSUE TITLE
Trying to use `T as ...` with a shape yields type checker error

### ISSUE THREAD

**Issue by jscheinblum** [facebook/hhvm#8526]
### HHVM Version

HipHop VM 4.12.0 (rel)
or 
HipHop VM 3.30.3

### Standalone code, or other way to reproduce the problem

In this code, we're trying to use a more specific shape to accept a broader set of shapes so the class can operate on just the common fields.

This works unless we modify the shape as in `$t['thingo'] = "x";` on line 36. If the shape isn't modified, then the typechecker is happy.

https://gist.github.com/jscheinblum/7efacd6adfae946d04c54377b6eb9bd5

### Actual result

Expected that we could set `$t['thingo'] = "x";` and return T from `p`.

### Expected result

3.30
```
thinger.php:32:10,11: Invalid return type (Typing[4110])
  thinger.php:26:27,27: This is a value of generic type T
  thinger.php:25:22,43: It is incompatible with a shape
```

4.12:
```
Typing[4110] Invalid return type
   --> thinger.php
 31 | final class Bar<T as most_specific_fields_t> implements foo<T> {
    |                      ^^^^^^^^^^^^^^^^^^^^^^ But got shape('thingo' => string, ...)
 32 | 	public function p(T $t): T {
    |                           ^ Expected T
 38 | 		return $t;
    |          ^^
```

**Comment by fredemmott** [comment]
@CatherineGasnier AIUI this is sound - any chance your current work will permit this kind of thing?

**Comment by fredemmott** [comment]
It has also been tested with current nightlies, so includes your diffs from last week

**Comment by CatherineGasnier** [comment]
This is a valid error. Let me illustrate with a slightly modified example. Here the last line of test fails at runtime:
```
class A {}
class B extends A {}

type specific_fields_t = shape(
  'thingo' => A,
  ...
);
type even_more_specific_fields_t = shape (
  'thingo' => B,
  ...
);  // so we do have even_more_specific_fields_t <: specific_fields_t

function x<T as specific_fields_t>(T $t): T {
  $t['thingo'] = new A (); // but what if T is in fact a even_more_specific_fields_t here, like below?
  return $t;
}

function test(even_more_specific_fields_t $s): void {
  $s = x<even_more_specific_fields_t>($s);
  expect_B($s['thingo']; // fails at runtime
}
```

**Comment by fredemmott** [comment]
Thanks; here's another example fitting the original code/string case.

```
enum SomeEnum: string as string {
  FOO = 'bar';
}

type some_shape = shape(
  'thingo' => SomeEnum,
  ...
);

function foo(some_shape $in): some_shape {
  // parameter is fine as some_shape is a subtype of most_specific_fields_t
  // return value is not: we get back a most_specific_fields_t (thingo is string), but thingo
  // is no longer a valid SomeEnum value so we don't get back a some_shape<T>
  return x($in);
}
```
