### ISSUE TITLE
undefined function session_start() 

### ISSUE THREAD

**Issue by mfurlend** [facebook/hhvm#8528]
### HHVM Version
HipHop VM 4.12.0 (rel)
Compiler: 1562000581_053014437
Repo schema: ae09177cea44bb26c3cc1f6d454eea4a349a5858

### hh_client Version:
hackc-d8c447b436c6a3bb4ac7c14ef9d9be51d80af59e-4.12.0
### Operating System and Version
Debian GNU/Linux 9 (stretch)

### Standalone code, or other way to reproduce the problem
```
session_start();
```

### Actual result

> Fatal error: Uncaught Error: Call to undefined function session_start() in /home/mfurlend/test.hack:1
> Stack trace:
> #0 {main}

### Expected result
no output

Also, `session` is not included in the strings returned by `get_loaded_extensions()`

This is my first time messing around with hhvm/hack, so its very possible that this is a stupid question. I saw in the change log that "ext_session and the $_SESSION superglobal have been removed" - but what is the workaround then? Are sessions no longer supported?

**Comment by lexidor** [comment]
You might want to take a look at this https://hhvm.com/blog/2019/05/06/hhvm-4.4.0.html
# Breaking Changes
...
ext_session and the $_SESSION superglobal have been removed

**Comment by azjezz** [comment]
the `session` extension has been removed from hhvm, as the API wasn't something that is worth keeping, implementing your session could be a little bit hard, but you can take a look here to how its done : https://github.com/nuxed/framework/tree/rx/src/Nuxed/Http/Session

if you have any questions regarding implementing a session or using `Nuxed\Http\Session`, i would be happy to help :) 

you can also compile the old session extension ( PHPs session extension ) and use it with HHVM, i can't guarantee that it would work as expected but its something worth trying :) 

session ext : https://github.com/facebook/hhvm/tree/HHVM-4.3/hphp/runtime/ext/session

**Comment by fredemmott** [comment]
> you can also compile the old session extension ( PHPs session extension ) and use it with HHVM, i can't guarantee that it would work as expected but its something worth trying :)

This is not a good use of time; the extension was removed as it depends on language features that are being entirely removed from the runtime. Even if it works /right now/, it's not going to work soon.

**Comment by mfurlend** [comment]
Thanks for the replies. I guess that sessions are simple enough to implement yourself, but I am a little surprised that this feature was removed as I was under the impression that hhvm strives to support all of the non-dynamic php features (e.g. not variable variables)

**Comment by fredemmott** [comment]
HHVM 4 does not aim for any PHP compatibility - more details at:
- https://hhvm.com/blog/2018/09/12/end-of-php-support-future-of-hack.html
- https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html

**Comment by scharger** [comment]
> Thanks for the replies. I guess that sessions are simple enough to implement yourself, but I am a little surprised that this feature was removed as I was under the impression that hhvm strives to support all of the non-dynamic php features (e.g. not variable variables)

A had same issue. So I decided to port ext_session from older HHVM. (only memcached and file storage methods left + added Crypto lib)  https://github.com/scharger/hhvm-ext_session
