### ISSUE TITLE
[HHI] Invalid edit to multiple hhi's makes valid code fail typechecks

### ISSUE THREAD

**Issue by lexidor** [facebook/hhvm#8536]
### HHVM Version

I understand that this is not a supported release. I am just an enthusiast who built a HHVM version from source to be closer to development. If you do not wish to see issues made on non-release versions of HHVM, please let me know.
```
HipHop VM 4.14.0-dev (rel)
Compiler: heads/master-0-g8e3fcca1a55b1cb6429a69485defbe419285cde1
Repo schema: 1f83a484891318b6b207071257df148e668d40e6
Git log commit hash: 3e7e6ddc21b7c2699099345360143379d01b4ba0
```

### Operating System and Version

Ubuntu 18.04 (irrelevant)

### Applicable commit
[4e46d78...](https://github.com/facebook/hhvm/commit/4e46d780848f5c6753e899fc0c7086a294d8680d#diff-27041fe31a9ef0c5f45cc80feb55e017R38)

### Standalone code, or other way to reproduce the problem

```HACK
use namespace HH\Lib\C;

<<__EntryPoint>>
async function main_example_async(): Awaitable<void> {
	Facebook\AutoloadMap\initialize();

	$before_commit = dict['string' => 0];
	$after_commit = dict['string' => 0];

	before_commit_krsort(inout $before_commit);
	takes_int(C\firstx($before_commit));
	takes_string(C\first_keyx($before_commit));

	after_commit_krsort(inout $after_commit);
	takes_int(C\firstx($after_commit));
	takes_string(C\first_keyx($after_commit));
}

// Before https://github.com/facebook/hhvm/commit/4e46d780848f5c6753e899fc0c7086a294d8680d#diff-27041fe31a9ef0c5f45cc80feb55e017
function before_commit_krsort<Tk as arraykey, Tv, T as KeyedContainer<Tk, Tv>>(inout T $_arg, int $_sort_flags = SORT_REGULAR): bool {
	return true;
}

// After https://github.com/facebook/hhvm/commit/4e46d780848f5c6753e899fc0c7086a294d8680d#diff-27041fe31a9ef0c5f45cc80feb55e017
function after_commit_krsort(inout KeyedContainer<arraykey, mixed> $_arg, int $_sort_flags = SORT_REGULAR): bool {
	return true;
}

function takes_int(int $_int): void {}

function takes_string(string $_string): void {}
```

### Actual result

```
   --> filename.hack
 17 | 	takes_int(C\firstx($after_commit));
    |                     ^^^^^^^^^^^^^
 27 | function after_commit_krsort(inout KeyedContainer<arraykey, mixed> $_arg, int $_sort_flags = SORT_REGULAR): bool {
    |                                                             ^^^^^ But got nonnull
 31 | function takes_int(int $_int): void {}
    |                    ^^^ Expected int

Typing[4110] Invalid argument
   --> filename.hack
 18 | 	takes_string(C\first_keyx($after_commit));
    |                            ^^^^^^^^^^^^^
 27 | function after_commit_krsort(inout KeyedContainer<arraykey, mixed> $_arg, int $_sort_flags = SORT_REGULAR): bool {
    |                                                   ^^^^^^^^ But got arraykey
 33 | function takes_string(string $_string): void {}
    |                       ^^^^^^ Expected string
```

### Expected result
```
No errors!
```
The generic type `T` in `before_commit_krsort` allowed the type of `$before_commit` to be preserved to `dict<string,int>`. `after_commit_krsort` does not preserve this truth about the program and will downcast the type to `KeyedContainer<arraykey, mixed>`. This is not just the case for krsort. If a function takes a `Container<_>` as inout, it should be generic. If a function takes one `Container<_>` and transforms it in some way, the generics should be preserved.

**Comment by lexidor** [comment]
P.S. I am using a undefined function `library_autoload_async`. This shouldn't matter, since the code doesnt need to run to prove its point. It is just a wrapper around `Facebook\AutoloadMap\initialize()`.
```HACK
async function library_autoload_async(): Awaitable<void> {
    require_once __DIR__.'/../vendor/autoload.hack';
    Facebook\AutoloadMap\initialize();
}
```

**Comment by lexidor** [comment]
Quote from previous author: [27041fe...](https://github.com/facebook/hhvm/commit/b9ff9fc695a233cc96e59ffa2a7d9c95009e030d#diff-27041fe31a9ef0c5f45cc80feb55e017)

```
Update hhi for builtin sort functions (& -> inout)
Summary: We need the new generic `T` to reflect that these functions are polymorphic and preserve the type of the input container.
Reviewed By: Wilfred
Differential Revision: D15821503
fbshipit-source-id: 7763b7709894b2d76c973e992395a62f7c938660
```

**Comment by fredemmott** [comment]
Shorter standalone example:

```
<<__EntryPoint>>
function main(): void {
  $x = dict['a' => 123];
  sort(inout $x);
  takes_stringkey($x);
  takes_intval($x);
}
```

**Comment by fredemmott** [comment]
FB: T47269952

**Comment by lexidor** [comment]
Also:
`ImmMap::containsKey()` should not take a mixed.
`ImmVector::concat()` should not return `ImmVector<Tv>`, but `ImmVector<Tu>`, since the new vector can contain values that are not of type `Tv`.
`Pair::containsKey()` should not take `mixed`, but `int`.
`Vector::containsKey()` should take `int`, not `mixed`.
This is not covered under `__PHPStdLib`.
This list may not be complete.

**Comment by fredemmott** [comment]
`ImmVector::concat()` is returning the broader type but seem correct; features such as newtype/enums require the broader types.

**Comment by lexidor** [comment]
Fixed in ae046ae

**Comment by lexidor** [comment]
Reopened, since valid code still fails to typecheck.
```HACK
function main(): void {
	$int_vec = vec[0, 1, 2, 3, 4, 5];
	sort(inout $int_vec);
	takes_int_vec($int_vec);
}

function takes_int_vec(vec<int> $ints): void {}
```
Typing[4110] Invalid argument
   --> file.hack
  4 |   takes_int_vec($int_vec);
    |                ^^^^^^^^
  7 | function takes_int_vec(vec<int> $ints): void {}
    |                        ^^^^^^^^ Expected vec<int>
   --> /tmp/hh_server/hhi_3e6154/container_functions.hhi
 28 | function sort(inout Container<T> $arg, int $sort_flags = SORT_REGULAR): bool;
    |                     ^^^^^^^^^^^^^^^^ But got Container<mixed>

1 error found.
```

**Comment by lexidor** [comment]
Closing temporarily, my dev env my very well be behind.

**Comment by lexidor** [comment]
```
HipHop VM 4.15.0-dev (rel)
Compiler: heads/master-0-gae046ae8509df69a2b0d96476fed2f96e9f1c64a
--------------------------ae046ae
Repo schema: 455f2c356c95482dea03838f9402d83d18019c60
```
My hhvm --version output matches the expected to have been built with ae046ae. However, the function in HHI is not up-to-date with your change.
```HACK
<<__PHPStdLib>>
function sort(inout Container<mixed> $arg, int $sort_flags = SORT_REGULAR): bool;
```
I'll ask @fredemmott how to properly build HHVM. My current approach is:
```
cd ~/hhvm
git checkout master
git reset HEAD --hard
git fetch upstream
git rebase upstream/master
make -j 4
sudo make install
```

**Comment by fredemmott** [comment]
`git clean -ffdx hphp/hack` is a handy step; there shouldn't be a need to clean the C++ parts, and this gives you a much better build time.
