### ISSUE TITLE
[Typechecker] dynamic/_/Tany intersections have unexpected results

### ISSUE THREAD

**Issue by lexidor** [facebook/hhvm#8538]
### HHVM Version
```
HipHop VM 4.14.0-dev (rel)
Compiler: heads/master-0-g8e3fcca1a55b1cb6429a69485defbe419285cde1
Repo schema: 1f83a484891318b6b207071257df148e668d40e6
hackc-5685814de1bbc4ba33102676d44d582672ad352a-4.14.0-dev
Hash: e6ec8e53d88950fd6b87ee95cc7b254dc242b531
Fri Jul 12 15:57:10 2019 -0700
```

### Operating System and Version
Ubuntu 18.04 (Irrelevant)

### Standalone code, or other way to reproduce the problem

```HACK
function from_timestamp(int $timestamp): null {
	$date_time = DateTime::createFromFormat('U', (string)$timestamp) as dynamic;
	invariant($date_time is DateTime, 'Could not turn %d into a DateTime', $timestamp);
	return $date_time;
}
```

### Actual result
Hover type of $date_time on line 2 is `(_ & dynamic)`.
Hover type of $date_time at the return is `(dynamic & _ & DateTime)`.
Return is allowed.

### Expected result
TAny should be overpowered by `invariant($date_time is DateTime)` and `as dynamic` , since it allows this variable to pass the bogus return type check of `null`.

### Why we do `as dynamic`
The runtime return type of `DateTime::createFromFormat()` is `false|DateTime`. The HHI return type is `TAny`, since this union can not be represented. The `as dynamic` is put in place to make the typechecker able to refine using invariant. (Sidenote, `$tany as DateTime` was still `TAny` in previous releases. This is why code written to old versions did not do the assertion directly.) The inclusion of a union with TAny lets a lot of provably wrong code pass typechecks.

**Comment by fredemmott** [comment]
`as dynamic` is not needed for this behavior; here's a simplified example, also avoiding the `null` type just in case:

```Hack
class DefinitelyNotADateTime {}
function from_timestamp(int $timestamp): DefinitelyNotADateTime {
  $date_time = DateTime::createFromFormat('U', (string)$timestamp);
  $ret = $date_time as DateTime;
  return $ret;
}
```

**Comment by fredemmott** [comment]
FB T47326888

**Comment by dlreeves** [comment]
We are focusing on a larger change to our underlying type system that looks to eliminate the TAny type with dynamic. This is currently what the team is focusing on and until then we won't be looking at changing/improving any interactions with TAny. From my experience this is a fruitless effort since the TAny type has no theoretical basis, so at best you can come up with heuristics that make sense in some cases, but not others.

**Comment by lexidor** [comment]
`TAny` is the culprit and this will not be worked on. Closing.
