### ISSUE TITLE
Backport (cherry-pick) requests

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#8543]
This would be for 3.30, 4.8, and for other supported releases (currently 4.12-4.17)

| state | issue | fix | applies since | cherry-picked to
|-|-|-|-|-
|   | local variables in debugger | ??? - #8542 | ??? | 
| x | CLI exit hang | b226a3653b49c5e1a2899c88694a0c4b76926d43 in 4.15 | ~forever | 3.30, 4.8, 4.12-4.14
| x | Xenon issues | c7622408c8b3a6f861ae9292433623163966cd21 in 4.9, c65b853724bc83204452493bea814eb026dba858 in 4.13 | ~forever | 3.30, 4.8, 4.12
| x| repo-auth on mac | 6eaa08c46d588731a472929f5f48c618b0de2482 in 4.12 | ~ 4.0 | 4.8 |
| x | accidental shared memory access in hackc  | b62da016122f19da39b9b6b6ae29fd41337d78c9 in 4.18 | 4.16 | 4.16, 4.17 |

**Comment by turadg** [comment]
If 3.30 is eligible (LTS according to https://docs.hhvm.com/hhvm/installation/release-schedule#Lifecycle) backporting these would be much appreciated.

We're on 3.x so any features and fixes on 3.30 help.

**Comment by fredemmott** [comment]
Will look at each; 3.30 is sufficiently older that the odds of these turning into major changes is significantly higher. If they're cherry-picks with a few small merge conflicts, will aim for that, but if it's basically re-write, the priority will be not to risk making the LTS less stable

**Comment by fredemmott** [comment]
- 4.17.1
- 4.16.2
- 4.15.1
- 4.14.1
- 4.13.1
- 4.12.1
- 4.8.2
- 3.30.7
