### ISSUE TITLE
[Typechecker | Regression] Truthiness checks on strings are allowed by the typechecker

### ISSUE THREAD

**Issue by lexidor** [facebook/hhvm#8561]
### Prelude
According to HHVM4.8 and below, you should not be allowed to do truthiness checks on strings. 
[OCaml code for thuthy strings](https://github.com/facebook/hhvm/blob/a54af4a06ca62c5d4d890e7c6e9011b09c96278a/hphp/hack/src/typing/tast_utils.ml#L181)

```ocaml
(** When a type represented by one of these variants is used in a truthiness
    test, it indicates a potential logic error, since the truthiness of some
    values in the type may be surprising. *)
type sketchy_type_kind =
  | String
  | Arraykey
  | Stringish
  | XHPChild
      (** Truthiness tests on strings may not behave as expected. The user may not
      know that the string "0" is falsy, and may have intended only to check for
      emptiness. *)
  | Traversable_interface of string
      (** Interface types which implement Traversable but not Container may be
      always truthy, even when empty. *)
```

### HHVM Version

```
HipHop VM 4.23.0-dev (rel)
Compiler: 1568605624_509374463
Repo schema: d3aeac4022c6a43fc3660e7d8141465a7fbb14c2
hackc-9f58f3799749c8d2680054e2c26f95325770390d-4.23.0-dev
```

### Operating System and Version

Ubuntu 18.04

### Standalone code, or other way to reproduce the problem

```HACK
<<__EntryPoint>>
function snippet(): void {
    $string = 'string';
    if ($string) {
        // Truthyness of string checks were warned about in HHVM 4.8.
    }
}

```

### Actual result
```
$ hh_client
No errors!
```

### Expected result

(This is not the exact error message, but something from memory. You'll not find this literal error message using grep.)
```
$ hh_client
You may not check the truthiness of a string, since both empty string and '0' are falsy. For emptiness checks, use Str\is_empty.
```

**Comment by fredemmott** [comment]
Sketchyness checks were moved to an ocaml linter, but that framework isn't open source. Unsure what the best solution is - probably worth trying to get it released given it'll probably be a while until that part goes to rust

**Comment by lexidor** [comment]
> Sketchyness checks were moved to an ocaml linter, but that framework isn't open source. Unsure what the best solution is - probably worth trying to get it released given it'll probably be a while until that part goes to rust

`hh_client --lint` has had some non API specific lints made public. I have a lot of sketchy truthyness checks to clean up that accumulated in my applications since 4.23-dev 🙂.
