### ISSUE TITLE
[Feature Request | Wishlist] Release the SQL formatter `%Q`.

### ISSUE THREAD

**Issue by lexidor** [facebook/hhvm#8565]
### HHVM Version
HHVM 4.23 and below

### Operating System and Version
Irrelevant

### Standalone code, or other way to reproduce the problem
```HACK
$conn = await get_sql_connection(); // returns a Awaitable<AsyncMysqlConnection>
$result = await $conn->queryf("SELECT id FROM %T WHERE %Q", $some_table, $a_list_of_conditions);
```

### Actual result
```
hh_client
Typing[4105] Too many arguments (expected 2 but got 3)

Typing[4038] I don't understand the format string %Q in %Q
type SQLFormatString = HH\FormatString<HH\SQLFormatter>;
                                       ^^^^^^^^^^^^^^^ You can add a new format specifier by adding format_upcase_q() to HH\SQLFormatter

2 errors found.
```

### Expected result
@fredemmott 

> Actually, looks like queryf doesn't support what we do (queryf() is basically what we use in prod C++, but our prod hack code uses a separate version)

> but right now the SQL object + %q placeholders aren't available

> we should definitely revisit that...

**Comment by fredemmott** [comment]
At runtime, we have `%Q`: https://github.com/facebookarchive/squangle/blob/f78a84fbed7545cd4ca27e0fbc6a7a6793344da5/squangle/mysql_client/Query.h#L67

It's documented as just taking a string (which I don't think we should directly add to the HHI) , but [does actually accept a sub-query object too](https://github.com/facebookarchive/squangle/blob/f78a84fbed7545cd4ca27e0fbc6a7a6793344da5/squangle/mysql_client/Query.cpp#L586)

We'd need a new hack class to represent a query, and to add support for it to `queryf()`; this should be pretty straightforward, in addition to the HHI change.

For specific use (a list of conditions), `%U` and `%W` might also be appropriate, and would need:
- adding to the HHI
- support for keyed containers (perhaps just dicts) in ::queryf, mapping to `QueryArgument(std::vector<ArgPair>)`

**Comment by lexidor** [comment]
`AsyncMysqlConnection::queryAsync()` was added to address this.
