### ISSUE TITLE
[Feature Request] Release the Facebookean version of the HSL

### ISSUE THREAD

**Issue by lexidor** [facebook/hhvm#8582]
### HHVM Version

Irrelevant

### Operating System and Version

Irrelevant

### Standalone code, or other way to reproduce the problem

```HACK
$vec = vec[1,2,3,4,5];
$five = C\pop_back(inout $vec);
```

### Actual result

Unbound name error, function pop_back is not defined.

### Desired result

Unify the HSL's.

**Comment by fredemmott** [comment]
There is no separate FB version of the HSL; it's published verbatim.

We have a set of extension functions in fb\ subnamespaces; some of these may make sense to release, but the majority don't belong in the HSL as such.
