### ISSUE TITLE
Significant memory usage increase in HHVM 4.12

### ISSUE THREAD

**Issue by ssandler** [facebook/hhvm#8606]
### HHVM Version

```
HipHop VM 4.12.0-dev (rel)
Compiler: remotes/origin/4.11-bisect6-0-g1303a3ed2305ba719bcb03c314386de03be39a0d
Repo schema: 15e155624e714d6155c5ea87bb1ee66d0b1ae2b2
```

This isn't a supported release, but we're trying to upgrade from `4.8.5` to newer versions, and have found a significant increase in memory usage that was introduced in this commit. We bisected down to the above commit which is https://github.com/facebook/hhvm/commit/1303a3ed23. 

### Operating System and Version

Ubuntu 16.04

### Standalone code, or other way to reproduce the problem

For open source shareable code: 

```
vendor/bin/hhast-lint $file
```

For a large file went from ~357 MB of memory consumed (as reported by both the OS and `memory_get_usage(true)` in the commit before this to 737MB after. We saw a similar doubling of memory usage across all web requests in our production fleet. This is without repo authoritative mode.

**Comment by ssandler** [comment]
Note also we attempted to set each of the newly introduced config options to all possible values and did not observe any changes in memory usage:
```
-v Eval.BigAllocUseLocalArena=false -v Eval.JsonParserUseLocalArena=false -v Eval.XmlParserUseLocalArena=false
```

true or false doesn't seem to make a difference on this number.

**Comment by ssandler** [comment]
I tried reverting just `hphp/runtime/ext/json/JSON_parser.cpp` from the commit in question and doing a build, and didn't see an improvement.

Also, we tried in repo auth mode. We found that repo auth cuts the memory usage in half for both hhvm versions, but it's still 2x more after https://github.com/facebook/hhvm/commit/1303a3ed23 either way.

i.e. a given endpoint is:
- 4.11 non repo auth: 11MB
- 4.11 repo auth: 5.9 MB
- 4.12 non repo auth: 22MB
- 4.12 repo auth: 13.8 MB

**Comment by ssandler** [comment]
The regression doesn't appear to be present when testing in a ubuntu 19.04 docker image, which may suggest that check dealing with libjemalloc >=4 may be at play, since libjemalloc 3.6 is the default for 16.04 and 18.04, but libjemalloc 5.1 is available for 19.04. Only part I don't understand is why toggling the `Eval.BigAllocUseLocalArena` setting wouldn't have an impact if that's the case, since the relevant code block is guarded by that option.

**Comment by ssandler** [comment]
Tried patching to remove the `#if JEMALLOC_VERSION_MAJOR >= 4` checks. Didn't help, also led to a segfault. But the segfault at least convinced me that the setting is being toggled properly, since it only happens with explicit `-v Eval.BigAllocUseLocalArena=false`.

**Comment by ssandler** [comment]
reverting just this part of the relevant commit solves the problem completely:

```
--- a/hphp/runtime/base/sparse-heap.cpp
+++ b/hphp/runtime/base/sparse-heap.cpp
@@ -111,12 +111,14 @@ HeapObject* SparseHeap::allocSlab(MemoryUsageStats& stats) {
 #ifdef USE_JEMALLOC
   auto const flags = MALLOCX_ALIGN(kSlabAlign) |
     (RuntimeOption::EvalBigAllocUseLocalArena ? local_arena_flags : 0);
-  auto slab = mallocx(kSlabSize, flags);
+  void* slab = mallocx(kSlabSize, flags);
+  auto usable = sallocx(slab, flags);
 #else
   auto slab = safe_aligned_alloc(kSlabAlign, kSlabSize);
+  auto usable = kSlabSize;
 #endif
   m_bigs.insert((HeapObject*)slab, kSlabSize);
-  stats.malloc_cap += kSlabSize;
+  stats.malloc_cap += usable;
   stats.peakCap = std::max(stats.peakCap, stats.capacity());
   return finish(slab);
 }
```

**Comment by kmaslack** [comment]
Just to highlight the bug Scott found as I understand it: `sallocx()` more precisely estimates the usable space than the overestimate of `kSlabSize`. This seems to result in a lot of fragmentation in practice for us. Can anybody upstream folks verify this was unintentional? It appears unrelated to the thrust of the change, and would subvert the apparent intention of the code. Note that `master` seems to have the same bug.

**Comment by fredemmott** [comment]
> reverting just this part of the relevant commit solves the problem completely:

Just to check I'm not mis-reading again: the patch you included *is* the partial revert; to fix it, *apply* that patch, don't reverse that patch?

**Comment by ssandler** [comment]
That's correct.

**Comment by fredemmott** [comment]
jemalloc < 5 puts metadata at the start of its' chunks, so when requesting a 2mb-aligned chunk, we actually need a 4mb-aligned chunk and get 4mb.

On older jemallocs, both the old and new versions have accounting bugs; this could theoretically be fixed by creating two 2mb slabs, but this is a complicated change not needed for newer systems.

This is most likely going to be fixed by building and statically linking jemalloc 5 on systems that do not have it.

**Comment by ssandler** [comment]
Statically linking jemalloc5 as of HHVM 4.36 appears to have resolved this issue.
