### ISSUE TITLE
Composer needed but unusable

### ISSUE THREAD

**Issue by chrisgraham** [facebook/hhvm#8619]
### HHVM Version

HipHop VM 4.34.0 (rel)
Compiler: 1575318969_858014129
Repo schema: e5c15841820ab38c7ec75ebe5ec9201013caa5bf

hackc-813332f24134bda11c88364188202cc63f6f958d-4.34.0

### Operating System and Version

Ubuntu 18.04.

### Issue

Your instructions (https://docs.hhvm.com/hack/getting-started/tools), and installation of other HHVM project(s) (https://github.com/hhvm/hhast/blob/master/docs/linters-usage.md), require using Composer.

This is what happens when I use the Ubuntu package for composer:
```
sudo hhvm /usr/bin/composer require hhvm/hhast

Fatal error: HHVM 4+ does not support PHP: /usr/bin/composer
```

And this is what happens when I use the phar, downloaded as per HHVM getting started instructions:
```
sudo hhvm ./composer.phar require hhvm/hhast

Fatal error: Uncaught Error: Keyword __HALT_COMPILER must be written in lowercase in /mnt/composer.phar:26
Stack trace:
#0 {main}
```

Now I can see way back in February you have a blog post (https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html) explaining Composer can be used still *1 if using a new version of it and if using it through PHP (which contradicts https://github.com/hhvm/hhast/blob/master/docs/linters-usage.md showing calling via `hhvm`).

*1: ""HHVM is no longer able to execute Composer; Composer 1.8.4 includes support for identifying the HHVM version when executing via PHP, which is how we currently recommend installing dependencies for Hack projects."

It does not work...

```
php ./composer.phar require hhvm/hhast
...
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested PHP extension ext-simplexml * is missing from your system. Install or enable PHP's simplexml extension.
  Problem 2
    - The requested PHP extension ext-zip * is missing from your system. Install or enable PHP's zip extension.
  Problem 3
    - The requested PHP extension ext-xml * is missing from your system. Install or enable PHP's xml extension.
  Problem 4
    - The requested PHP extension ext-curl * is missing from your system. Install or enable PHP's curl extension.
  Problem 5
    - The requested PHP extension ext-intl * is missing from your system. Install or enable PHP's intl extension.
  Problem 6
    - The requested PHP extension ext-gd * is missing from your system. Install or enable PHP's gd extension.
  Problem 7
    - The requested PHP extension ext-mbstring * is missing from your system. Install or enable PHP's mbstring extension.
  Problem 8
    - Installation request for hhvm/hhast ^4.33 -> satisfiable by hhvm/hhast[v4.33.0].
    - hhvm/hhast v4.33.0 requires hhvm ^4.33 -> you are running this with PHP and not HHVM.
```

You have many many issues affecting non-Facebook (external) users, that apparently have been here since February :(. You don't provide updated Ubuntu packages for anything older than HHVM 4.0 either.

**Comment by fredemmott** [comment]
> Composer

- We only test with the latest version of composer available from getcomposer.org
- Composer is not able to test if HHVM is built with certain PHP extensions; these must be removed from composer.json

For both of these, I'll update the documentation - thanks

>  You don't provide updated Ubuntu packages for anything older than HHVM 4.0 either.

In general, releases are supported for 6 weeks; LTS releases are made every 24 weeks, and supported for 48 weeks. The oldest supported release is currently HHVM 4.8. Prior to 4.0, releases were less frequent but supported for 8 weeks, except for the LTS releases that are unchanged.

**Comment by chrisgraham** [comment]
Beyond the HHVM page I highlighted getting documentation, how can HHAST be installed if Composer cannot be used? If you do a git clone you get errors about a missing autoloader. Are you supposed to manually copy in the PSR-compliant autoloader that Composer would have put there? Having to manually wire things together with no instructions isn't very reasonable IMO.

You don't need to answer that directly, it's really feedback for you. I was one of the first users of HipHop PHP and battled through the lack of working instructions at various phases during the project's life, submitting many bug reports. I think you might have got far more widespread use outside of Facebook if everything was battle tested and supported properly rather than constantly being on the bleeding edge and breaking. Then it might have been the case that the project would have enough external sponsors to keep PHP as a target and stayed more relevant. I realize this is a rant, but for a project framing itself as a serious independent project, having basic installation steps broken for 9 months is a big fail.

**Comment by fredemmott** [comment]
> how can HHAST be installed if Composer cannot be used?

Composer can be and is used - though the PHP extension requirements are not supported. For example:

https://github.com/hhvm/hhast/blob/master/.travis.sh (https://travis-ci.org/hhvm/hhast/builds)

... or, in a project that uses HHAST but is not hhast itself:

https://github.com/hhvm/hacktest/blob/master/.travis.sh (https://travis-ci.org/hhvm/hacktest/builds)

We test using composer with Hack projects many times every day.

> If you do a git clone you get errors about a missing autoloader. Are you supposed to manually copy in the PSR-compliant autoloader that Composer would have put there? 

Composer is recommended, however composer's autoloader is not used, and it's possible to use the autoloader that we use without composer: https://github.com/hhvm/hhvm-autoload is the specific project.

While that documentation does reference `composer dump-autoload`, that is just a composer plugin for usability - we don't actually use composer's autoloader, instead we have a plugin that triggers our autoloader whenever composer regenerates it.

It's closer to a classmap autoloader, however it also supports function and constant autoloading.

https://docs.hhvm.com/hack/getting-started/starting-a-real-project covers bootstrapping a real project

**Comment by chrisgraham** [comment]
Check problem 8 in my report above though. If I remove the extensions it is clearer...

```
php ./composer.phar require hhvm/hhast
...
  Problem 1
    - Installation request for hhvm/hhast ^4.33 -> satisfiable by hhvm/hhast[v4.33.0].
    - hhvm/hhast v4.33.0 requires hhvm ^4.33 -> you are running this with PHP and not HHVM.
```

So to use Composer to install HHAST requires Composer to be running under HHVM, but it can not be run under HHVM now.

Am I missing something?!

**Comment by fredemmott** [comment]
Perhaps you have a stale composer.lock that still references the extensions?

Ubuntu 18.04:

```
fredemmott@fredemmott-mm1 ~ % docker run -it --rm ubuntu:18.04 /bin/bash -l
root@3a38733397b0:/# export DEBIAN_FRONTEND=noninteractive
root@3a38733397b0:/# apt update
[ removed output ]
root@3a38733397b0:/# apt install -y  software-properties-common apt-transport-https|
root@3a38733397b0:/# apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xB4112585D386EB94
Executing: /tmp/apt-key-gpghome.xCwW1JawdA/gpg.1.sh --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xB4112585D386EB94
gpg: key B4112585D386EB94: 1 signature not checked due to a missing key
gpg: key B4112585D386EB94: public key "HHVM Package Signing <opensource+hhvm@fb.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
root@3a38733397b0:/# add-apt-repository https://dl.hhvm.com/ubuntu
[ removed output ]
root@3a38733397b0:/# apt install -y hhvm php-cli wget unzip curl
[ removed output ]
root@3a38733397b0:/# cd $(mktemp -d)
root@3a38733397b0:/tmp/tmp.R8tC7bHGFQ# wget https://getcomposer.org/composer.phar
root@3a38733397b0:/tmp/tmp.R8tC7bHGFQ# php composer.phar require hhvm/hhast
Using version ^4.33 for hhvm/hhast
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 7 installs, 0 updates, 0 removals
  - Installing hhvm/hsl (v4.25.2): Downloading (100%)
  - Installing hhvm/hhvm-autoload (v2.0.11): Downloading (100%)
  - Installing facebook/difflib (v1.2.0): Downloading (100%)
  - Installing hhvm/type-assert (v3.6.5): Downloading (100%)
  - Installing hhvm/hsl-experimental (v4.31.1): Downloading (100%)
  - Installing facebook/hh-clilib (v2.2.4): Downloading (100%)
  - Installing hhvm/hhast (v4.33.0): Downloading (100%)
Writing lock file
Generating autoload files
This executable must be ran from a directory containing an hh_autoload.json
```

The error on the last line is expected given the autoloader is not configured per the main hack/hhvm docs, but the dependency resolution succeeded.

ditto on MacOS:

```
fredemmott@fredemmott-mm1 tmp.dGdxfCXz % php --version
PHP 7.3.9 (cli) (built: Sep 10 2019 17:45:01) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.9, Copyright (c) 1998-2018 Zend Technologies
fredemmott@fredemmott-mm1 tmp.dGdxfCXz % hhvm --version
HipHop VM 4.34.0 (rel)
Compiler: 1575319465_N
Repo schema: 972cc97c5810b078a02cc71114f36c153ca38413
fredemmott@fredemmott-mm1 tmp.dGdxfCXz % php ~/composer.phar self-update
Updating to version 1.9.1 (stable channel).
   Downloading (100%)
Use composer self-update --rollback to return to version 1.9.0
fredemmott@fredemmott-mm1 tmp.dGdxfCXz % php ~/composer.phar require hhvm/hhast
Using version ^4.33 for hhvm/hhast
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 7 installs, 0 updates, 0 removals
  - Installing hhvm/hsl (v4.25.2): Loading from cache
  - Installing hhvm/hhvm-autoload (v2.0.11): Loading from cache
  - Installing facebook/difflib (v1.2.0): Loading from cache
  - Installing hhvm/type-assert (v3.6.5): Loading from cache
  - Installing hhvm/hsl-experimental (v4.31.1): Downloading (100%)
  - Installing facebook/hh-clilib (v2.2.4): Loading from cache
  - Installing hhvm/hhast (v4.33.0): Downloading (100%)
Writing lock file
Generating autoload files
This executable must be ran from a directory containing an hh_autoload.json
```

**Comment by fredemmott** [comment]
> you are running this with PHP and not HHVM.

So, in the past there have been issues where Composer would report this if there were any dependency resolution errors, and it's misleading. If you're still seeing that on the latest composer, I'll look into fixing that.

**Comment by fredemmott** [comment]
Hmm, looks like that's an artifact of 'hhvm composer' being correct for HHVM 3, but 'php composer' being correct for HHVM 4; given that 3.30 recently became unsupported, that can be cleaned up and simplified now probably.

**Comment by chrisgraham** [comment]
I have solved the problem after digging into what it is doing...
```
hhvm --php -d hhvm.jit=0 -r "echo HHVM_VERSION;"
Failed to initialize central HHBC repository:
  Failed to initialize schema in /home/chrisgraham/.hhvm.hhbc(rw-r--r-- root:root):
```

The problem is I initially ran hhvm under sudo as it could not run under my user. This created root-owned files in my home directory. This then caused a hidden error when Composer was instantiating it. Clearing out `/home/chrisgraham/.hhvm.hhbc` fixed it.

IMO Composer's error handling for HHVM version checks needs to not make this misleading statement about needing to be running it (as you identified above). But also it shouldn't assume it's `hhvm --php -d hhvm.jit=0 -r "echo HHVM_VERSION;"` command will pass - if it doesn't grep a version number out of it it should output the error message.

**Comment by chrisgraham** [comment]
Also Composer should ask hhvm for a version that doesn't require getting it to run code (with all the permission overhead involved in that), it can just do a simpler `hhvm --version` call.
