### ISSUE TITLE
[Typechecker | Bug] Invalid code passes typechecks / control flow analysis of unrelated variables caused weird behavior

### ISSUE THREAD

**Issue by lexidor** [facebook/hhvm#8647]
### HHVM Version

```
HipHop VM 4.41.0-dev (rel)
Compiler: 1579319220_458618021
Repo schema: 3fa55af43df2bf810968a55bfc64bafa0e33d74b
hackc-29bb6b1ce356c23f0abe0db3eef5ef2e549ad0be-4.41.0-dev
```

### Operating System and Version

Ubuntu 18.04

### Standalone code, or other way to reproduce the problem

```HACK
function main(): void {
    $dict = dict[];
    $_ = Shapes::toArray($dict);

    $huh = null;
    if ($huh is Container<_>) {
    }

    $dict2 = dict[];
    $_ = Shapes::toArray($dict2);
}
```

### Actual result

```
Typing[4323] Invalid argument
   --> bug.hack
  2 |     $dict = dict[];
    |             ^^^^^^ But got dict<nothing, nothing>
  3 |     $_ = Shapes::toArray($dict);
    |                          ^^^^^
   --> /tmp/hh_server/hhi_2f8525d9/Shapes.hhi
 62 |   public static function toArray<T as shape(...)>(
    |                                       ^^^^^^^^^^ Some type constraint(s) are violated here
    |                                  ^ T is a constrained type parameter
    |                                       ^^^^^^^^^^ Expected shape(...)

1 error found.
```

![image](https://user-images.githubusercontent.com/31805625/72670016-b22b8e80-3a38-11ea-83ba-436177f543b6.png)

This has something to do with `$huh is Container<_>` because `$huh is string` suddenly reports both errors.

![image](https://user-images.githubusercontent.com/31805625/72670029-dd15e280-3a38-11ea-8e6d-d12fba6bdb94.png)

### Expected result

Both lines should be an error.

**Comment by lexidor** [comment]
`Shapes::toArray()` is required to reproduce this. `takes_vec(vec<string>)` works as  expected.
![image](https://user-images.githubusercontent.com/31805625/72670086-a391a700-3a39-11ea-927d-fddbb5907bf2.png)

**Comment by Wilfred** [comment]
This is definitely a type hole. Here's a smaller example:

```
function main(): void {
    $huh = null;
    if ($huh is Container<_>) {
    }

    Shapes::toArray(1);
}
```

**Comment by Wilfred** [comment]
T61516868

**Comment by Wilfred** [comment]
Even smaller:

```hack
function main(): void {
    $huh = null;
    if ($huh is Container<_>) {
      // this block is never executed
    }

    takes_int("foo");
}

function takes_int<T as int>(T $_): void {}
```

Hack knows that the if block will never execute, so it allows generics to have their constraints violated. However, the scope of this 'inconsistent type environment' is too big, and it includes the `takes_int` call.

**Comment by lexidor** [comment]
Both repro cases correctly report errors in hhvm 4.138. The fix likely landed much much earlier. Closing.
