### ISSUE TITLE
[Namespaces] autoloading fully-automatic

### ISSUE THREAD

**Issue by ecreeth** [facebook/hhvm#8650]
**I know this feature is planned for the future, I just put it here to track it. :smile:**

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Hhvm 4.109 added ext_watchman, which includes a native, fully automatic autoloader.

https://hhvm.com/blog/2021/05/11/hhvm-4.109.html
