### ISSUE TITLE
HHVM For Windows: Works With WSL 2

### ISSUE THREAD

**Issue by mike2151** [facebook/hhvm#8669]
Hello,

I am new to using HHVM and Hack. It is my understanding that HHVM support for Windows is far away according to documentation. I  thought using [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10) (WSL) would allow me to use HHVM on my Windows machine.  When I tried using HHVM on WSL, I got the following error:
`cannot execute binary file: Exec format error`

However, I looked into [WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-index) and this looked promising because of the full Linux kernel. I upgraded to WSL 2 and HHVM seems to work fine in WSL 2! I am able to do Hack development in an IDE on my Windows machine and run Hack via WSL 2. 

Is WSL 2 a legitimate fix for the current limitations of using HHVM in WSL? Thanks!

**Comment by fredemmott** [comment]
We do not currently test on any Windows platform, though either Docker or WSL2 may work.

**Comment by kraisorna** [comment]
Hello,

I got the same error after installing hhvm on wsl on windows 10 (in my case i installed Ubuntu 18 lts).

then i tried to reinstall wsl again to have Debian instead Ubuntu and wish this will get positive changes.

unfortunately, in my case, the wsl Debian is also showing the same problem.

![image](https://user-images.githubusercontent.com/7168628/166626750-4effa44c-9490-4e9a-9147-1ca8ed4b580c.png)
