### ISSUE TITLE
Exception: class_alias with non-literal parameters is not allowed when WholeProgram optimizations are turned on

### ISSUE THREAD

**Issue by raulp** [facebook/hhvm#867]
after installing from deb packages on ubuntu, i was trying to compile a list of php files in my folder.
I've got: 

Exception: class_alias with non-literal parameters is not allowed when WholeProgram optimizations are turned on\n
hphp failed

Any clue what i might do ?

**Comment by tylermenezes** [comment]
If it's useful to anyone, disabling optimizations (`--optimize-level=0`) and disabling whole-program optimizations as specified above will make this _sort of work_ (read: break differently). The repo is created successfully, but it throws a new error when you try to use it: `HipHop Parse Error: Native functions/methods may only be defined in systemlib`

**Comment by onlyone0001** [comment]
@tylermenezes Have you found a way further? I got stuck in the same place.

**Comment by PLaRoche** [comment]
We've had no luck but are still looking for a solution

**Comment by onlyone0001** [comment]
Is there an option to exclude some files from compiling but including them without compilation?

**Comment by paulbiss** [comment]
No. For whole program analysis to work the compiler needs to have access to any code that will ever execute. The byteocde repo itself is still constructed in non-repo mode and can be used without enabling repo-authoritative mode if all you're looking for is precomputed bytecode.

I should stress that compiling a repo has basically no value as a form of obfuscation, and transformation back into PHP is a trivial process.

**Comment by onlyone0001** [comment]
Trivial sounds underestimating?
We are already disabling whole program analysis (-v WholeProgram=false) and disabling optimize level  (--optimize-level=0) for successful compiling. Logically it should be possible to exclude some files from compiling and including them as is for runtime processing.

**Comment by PLaRoche** [comment]
I'm also curious about "trivial". Do you mean trivial in the way all byte code is somewhat easy to be "un compiled" into some sort of legible original form, or do you mean, by nature of using hhvm to compile the php code, their is an amazingly easy way to transform back to php?

**Comment by paulbiss** [comment]
Trivial is absolutely not underestimating. Transforming bytecode back to PHP is itself a rather straightforward process (for a short enough piece anyone familiar enough with the way our emitter works could do it off the top of their head). In addition there's a great deal of metadata that needs to be stored alongside the bytecode (for error messages, backtraces, and other PHPisms).

The point here is that in addition to recovering logic and control flow you could recover variable, function, constant, trait, interface, and class names, modifiers on classes, functions, and properties, line numbers, and doc-comments. Depending on how sophisticated you want to be you can pretty much generate something every bit as legible as the original source.

While I'm not saying that writing a decompiler would itself be a "simple" task (I suppose it would be at least as complicated as the emitter that generated the bytecode), it's not exactly a particularly technically challenging problem in the grand scheme of things. With the bytecode and the metadata we're not just talking about reconstructing some of the logic, you could more or less recover the source in some nearly equivalent form.

**Comment by paulbiss** [comment]
With respect to partial compilation without optimizations, that's already done for you when you execute the code. To run PHP even in non-repo mode we require bytecode so it's generated on the fly and cached in an sqlite db (if you set Repo.Central.Path in your settings that's where it will be stored). As files are parsed for the first time their bytecode and metadata will be added to the repository.

AIUI we don't have a mode to generate such a repo ahead of time that's not intended to be complete, I'm not totally convinced of any use cases for this (see my answer above about the futility of obfuscation by bytecode repo), generally speaking the only advantage to pre-compiling the repo is to do more sophisticated ahead of time static analysis (for which the repo must be complete).
