### ISSUE TITLE
[ TypeChecker ] `yield from` in AsyncGenerator function causes an exception in the typechecker

### ISSUE THREAD

**Issue by lexidor** [facebook/hhvm#8671]
**Describe the bug**

```
Typing[4361] An exception occurred while typechecking this. Please file a bug.
   --> file.hack
  6 | async function exception_occured_during_typechecking(
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

1 error found.
```

**Standalone code, or other way to reproduce the problem**
> This should not depend on installing any libraries or frameworks. Ideally, it should be possible to copy-paste this into a single file and reproduce the problem by running hhvm and/or hh_client

```HACK
async function exception_occured_during_typechecking(
): AsyncGenerator<null, string, void> {
  yield from varray[];
}
```

**Expected behavior**

This should typecheck and not throw an exception in the typechecker.

**Screenshots**

Not applicable

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
> For example, 'Debian Squeeze', 'Ubuntu 16.04', 'MacOS High Sierra'. Please also mention if you are using Docker or similar images.
 - HHVM Version: 4.47
> Please include the output of `hhvm --version` and `hh_client --version`

```
HipHop VM 4.47.0 (rel)
Compiler: 1583190602_552330177
Repo schema: 3d75b2028824b57ef32d326917560f627c12d50c
hackc-b8563a3ecfeb35ef0b11a0ddb5229415634f8a6a-4.47.0
```

**Additional context**

**Comment by fredemmott** [comment]
AsyncGenerators are a special class, not just Awaitable<Generator>; that said, the error handling needs to be improved

**Comment by fredemmott** [comment]
FB T63722279

**Comment by lexidor** [comment]
`yield from` has been removed in 4.65 and it is a parse error.
