### ISSUE TITLE
[ Typechecker ] Use of uninitialized property when used as argument to a private method

### ISSUE THREAD

**Issue by lexidor** [facebook/hhvm#8687]
**Describe the bug**

The following code is unsound, but passes the typechecker.

**Standalone code, or other way to reproduce the problem**

```HACK
final class Bug {
  private string $a;
  public function __construct() {
    $this->method($this->a);
    $this->a = '';
  }
  private function method(string $_): void {}
}
<<__EntryPoint>>
function main(): void {
  new Bug();
}
```

1. hh_client

**Expected behavior**

This error is missing.
```
Typing[4083] Read access to $this->a before initialization
   --> src/bug.hack
  5 |     $this->method($this->a);
    |                   ^

1 error found.
```

**Screenshots**

The error on HH\Lib\Str\length() is correctly reported.
![image](https://user-images.githubusercontent.com/31805625/79906742-a88b3b80-8418-11ea-9bf8-d2675e25b44e.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - HHVM Version:
```
HipHop VM 4.54.0-dev (rel)
Compiler: 1587354233_047441010
Repo schema: d1ae8e21bf3419a65f12a010527485564e719d07
hackc-9a1dc97bc7a03dafc217b0c7d7212ce49f4f1ca3-4.54.0-dev
```

**Additional context**

At runtime this result in the following error.
```
Uncaught TypeError: Argument 1 passed to Bug::method()
must be an instance of string, null given
```

**Comment by lexidor** [comment]
@Wilfred Could you tag this issue as `hack`, please?

**Comment by Wilfred** [comment]
Yikes! That's definitely a bug.

Interestingly, the following is fine:

```
function takes_string(string $_): void {}

final class Bug {
  private string $a;
  public function __construct() {
    takes_string($this->a);
    $this->a = '';
  }
}
```

**Comment by Wilfred** [comment]
Filed T66969915 internally for this type hole.

**Comment by lexidor** [comment]
Fixed via https://github.com/facebook/hhvm/blob/6d1c785849d3bd52c1d88d327089bfa789df2fa0/hphp/hack/test/typecheck/visibilities/read_before_write_private.php
