### ISSUE TITLE
install_fastcgi.sh is missing on ubuntu 18.04

### ISSUE THREAD

**Issue by PrafullaKumarSahu** [facebook/hhvm#8692]
**Describe the bug**

install_fastcgi.sh file and hhvm directory missing from ubuntu 18.04.

**Desktop Configuration**
OS: Ubuntu 18.04
HipHop VM 4.55.0 (rel)
Compiler: 1588013642_403208051
Repo schema: d1ae8e21bf3419a65f12a010527485564e719d07
nginx version: nginx/1.14.0 (Ubuntu)

**Standalone code, or other way to reproduce the problem**
> This should be reproducible, as I have tried in 2 machines and multiple times. 

1. Run `sudo apt-get update`
2. And then `sudo apt-get install -y curl software-properties-common apt-transport-https`
3. And after this `curl https://dl.hhvm.com/conf/hhvm.gpg.key | sudo apt-key add -`
4. And after this `sudo apt-key finger 'opensource+hhvm@fb.com'`
5. After this `sudo add-apt-repository https://dl.hhvm.com/ubuntu`
6. After this `sudo apt update`
7.And in the end `sudo apt install hhvm`

Now in `/usr/share/` there is no hhvm or install_fastcgi.sh even grep -f install_fastcgi.sh returns empty.

**Expected behavior**
The specified file should be present in `/usr/share/hhvm` directory

**Screenshots**
![Screenshot from 2020-04-30 21-44-04](https://user-images.githubusercontent.com/2470646/80733828-d9abf000-8b2b-11ea-8612-a73d58150525.png)

**Comment by fredemmott** [comment]
Where did you find the reference to `/usr/share/hhvm` ? It is no longer there - it's in /opt/hhvm/4.55.0/share/hhvm

**Comment by PrafullaKumarSahu** [comment]
@fredemmott  thank you so much for this information, I was referring two posts one from digital ocean and  another from medium. Those needs to be updated, I will mention in comment. Thank you so much.
