### ISSUE TITLE
A class cannot precede the interface it implements, only if there's a "require extends"

### ISSUE THREAD

**Issue by jacobconley** [facebook/hhvm#8694]
**Describe the bug**

HHVM fails to recognize classes that implement an interface with a `require extends` trait when the interface definition comes after the aforementioned class definition.  See the example code below.

`hh_client` reports no errors, but when running such a script in CLI mode, `hhvm` will fail with an "Interface undefined" error.  

Moreover, when using `hhvm-autoload`, it will only fail at runtime with a misleading "Class undefined" error for the implementing class, even though the autoload map appears to generate correctly and other classes from the same file can be used normally.  This is how I found the bug, and it took me quite some time to get to the bottom of it.  

The issue goes away when there's no `require extends` trait present.  

**Standalone code, or other way to reproduce the problem**

The following code produces the issue:

```
class TestBaseClass { }

class Implementor extends TestBaseClass implements Thing { }

interface Thing { 
    require extends TestBaseClass;
}
```

Here, as long as `Thing` has the `required extends` clause and comes after `Implementor`, HHVM refuses to run the file.  

When using hhvm-autoload within `hhvm -m debug`, `TestBaseClass` can be instantiated, but attempting to instantiate `Implementor` causes a "Class Undefined" error, and attempting to instantiate `Thing` will also cause a class undefined error, suggesting that it is not recognized as an interface.  

**Expected behavior**
If this behavior is intended, `hh_client` should report an error. 

**Desktop (please complete the following information):**
 - OS: Linux Mint 
 - `hh_client --version`: hackc-9a1dc97bc7a03dafc217b0c7d7212ce49f4f1ca3-4.54.0
 - `hhvm --version`: 
HipHop VM 4.54.0 (rel)
Compiler: 1587406946_934746515
Repo schema: d1ae8e21bf3419a65f12a010527485564e719d07

Thanks

**Comment by lexidor** [comment]
There is indeed something fishy going on when you encounter this construct.
If you place the `Thing` interface in the same file as the `Implementor` class, you'll run into that fatal error.

This behavior can also be invoked by making the interface extend another interface.
`interface Thing extends SomeOtherInterface`, so `require extends` is not the culprit perse.
Just the fact that you need an autoload call to finish the interface declaration.
The autoload call for `SomeOtherInterface` is not performed however and an autoload call for `Thing` is created instead., so Thing could not be declared.

It is best to not define multiple entities in one file if you can help it.

I have used a raw `HH\autoload_set_paths()` with a `failure` key to inspect the autoloading cycle.

```HACK
<<__EntryPoint>>
function main(): void {
  \HH\autoload_set_paths(
    /*HH_FIXME[4110] Typechecker is unaware of 'failure'*/
    dict[
      'failure' => (string $type, string $name, mixed $extra) ==> {
        \var_dump(dict['type' => $type, 'name' => $name, 'extra' => $extra]);
        echo "Going to require $type $name\n";

        require_once __DIR__.
        '/'.
        dict[
          'Implementor' => 'Implementor.hack',
          'Thing' => 'Implementor.hack',
          'SomeOtherInterface' => 'SomeOtherInterface.hack',
        ][$name];

        echo "Required $type $name\n";
        if ($name === 'Thing') {
          $actually_found_it = \in_array('Thing', \get_declared_interfaces());
          if ($actually_found_it) {
            echo "Read past the class declaration to find Thing\n";
          } else {
            echo "Thing is not actually found though!\n";
          }
        }
      },
    ],
    __DIR__,
  );

  new Implementor();
}
```

```HACK
// Implementor.hack
class Implementor implements Thing {

  public function __construct() {
    echo "Created Implementor\n";
  }
}

interface Thing extends SomeOtherInterface {
}

```

```HACK
// SomeOtherInterface.hack
interface SomeOtherInterface {}
```

With `require extends`
```
dict(3) {
  ["type"]=>
  string(5) "class"
  ["name"]=>
  string(11) "Implementor"
  ["extra"]=>
  NULL
}
Going to require class Implementor
dict(3) {
  ["type"]=>
  string(5) "class"
  ["name"]=>
  string(5) "Thing"
  ["extra"]=>
  NULL
}
Going to require class Thing
Required class Thing
Thing is not actually found though!

Fatal error: Uncaught Error: Undefined interface: Thing in /path/to/src/Implementor.hack:1
Stack trace:
#0 /path/to/src/main.hack(16): include()
#1 /path/to/src/main.hack(32): Closure$main()
#2 (): main()
#3 {main}
```

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Only the userland autoloader (what hhvm-autoload uses) is affected by this defect. The userland autoloading facilities have been removed in this commit. https://github.com/facebook/hhvm/commit/d419828855998fc7c1f9e93647b6a4091647d956

The only autoloading facility left is ext-watchman / native facts / `HH\Facts`.
