### ISSUE TITLE
Typechecker does not error when using an invalid key for a dictionary

### ISSUE THREAD

**Issue by jpbrabec** [facebook/hhvm#8702]
**Describe the bug**
The typechecker does not produce an error when trying to use an invalid type as the key to a dictionary, even in cases where the type could not possibly be an int or string. 

**Standalone code, or other way to reproduce the problem**
I have a sample code block with a shape as the key, but this seems to be the case with other types of invalid keys as well:  
```
<<__EntryPoint>>
function test(): void {
    $test_dict = dict[];
    $invalid_key = shape('val' => 'sometestvalue');
    $test_dict[$invalid_key] = 5;
}      
```
Running the typechecker produces no errors, but actually running the code produces an exception as you would expect: 
```
$ hh_client          
No errors!
$ hhvm ./experiment.hack 

Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Invalid dict key: expected a key of type int or string, array given' in /Users/jbrabec/projects/experiments/experiment.hack:5
Stack trace:
#0 (): test()
#1 {main}
```

**Expected behavior**
I would expect to see a typechecker error when running `hh_client`, since in this example the type of the key is known and it cannot possibly be a valid key.

**Desktop (please complete the following information):**
macOS 10.14.6
HipHop VM 4.27.1 (rel)
Compiler: 1572293588_N
Repo schema: 0b4fea7ee5883d403774118b6753e8d6251e582d
hackc-8878e4f14ff6532df8850cebd8be2a843eb2fdba-4.27.1

**Comment by lexidor** [comment]
The default behavior has changed in hhvm [4.54](https://hhvm.com/blog/2020/04/21/hhvm-4.54.html) to report errors on this.
The `.hhconfig` setting that controls this behavior has been around for a while, and I believe it is also supported in hhvm 4.27.

Blogpost outake from 4.54:
_Containers are now more consistently checked for valid arraykeys; this behavior can be enabled on old releases with the disallow_invalid_arraykey=true .hhconfig setting._

Issue related to: #8675

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

I intended to close this issue with the comment above. It only took me three year to realize😀.
