### ISSUE TITLE
HHVM compilation issue for Ubuntu 16.04 for arm architecture.

### ISSUE THREAD

**Issue by VamshiMuthineni** [facebook/hhvm#8703]
When I try to compile hhvm from source for arm architecture, I'm facing the below error. I was following [https://docs.hhvm.com/hhvm/installation/building-from-source](this link). I was trying to build this as a docker image using buildx. Can anyone look into this? Thanks in advance.

#8 6849. common.copy /libevent-2.1.11-stable/hhvm/third-party/boost/build/include/boost/type_traits/has_left_shift.hpp
#8 6849. common.copy /libevent-2.1.11-stable/hhvm/third-party/boost/build/include/boost/type_traits/has_greater_equal.hpp
#8 6849. common.copy /libevent-2.1.11-stable/hhvm/third-party/boost/build/include/boost/type_traits/has_greater.hpp
#8 6849. common.copy /libevent-2.1.11-stable/hhvm/third-party/boost/build/include/boost/type_traits/has_equal_to.hpp
#8 6849. common.copy /libevent-2.1.11-stable/hhvm/third-party/boost/build/include/boost/type_traits/has_divides_assign.hpp
#8 6850. common.copy /libevent-2.1.11-stable/hhvm/third-party/boost/build/include/boost/type_traits/has_divides.hpp
#8 6850. common.copy /libevent-2.1.11-stable/hhvm/third-party/boost/build/include/boost/type_traits/has_dereference.hpp
#8 6850. ...updated 15645 targets...
#8 6850. [ 15%] No install step for 'boostBuild'
#8 6851. [ 15%] Completed 'boostBuild'
#8 6851. [ 15%] Built target boostBuild
#8 6851. Makefile:127: recipe for target 'all' failed
#8 6851. make: *** [all] Error 2
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c apt-get update && 	apt-get install -y --force-yes software-properties-common wget git build-essential && 	add-apt-repository -s "deb http://dl.hhvm.com/ubuntu $(lsb_release -sc) main" && 	apt-get update && 	wget https://github.com/libevent/libevent/releases/download/release-2.1.11-stable/libevent-2.1.11-stable.tar.gz && 	tar -xvzf libevent-2.1.11-stable.tar.gz && 	cd libevent-2.1.11-stable && 	./configure --prefix=/usr --disable-dependency-tracking --disable-static && make && 	make install && 	install  -v -m755 -d /usr/share/doc/libevent-2.1.11/api && 	apt-get build-dep -y --force-yes hhvm-nightly && 	git clone git://github.com/facebook/hhvm.git && 	cd hhvm && 	git submodule update --init --recursive && 	cmake -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DMYSQL_UNIX_SOCK_ADDR=/var/run/mysqld/mysqld.sock . && 	make -j 32 && 	make install]: buildkit-runc did not terminate successfully

**Comment by fredemmott** [comment]
Sorry, we no longer support either ARM or Ubuntu 16.04; you will at least need GCC7, probably OpenSSL 1.1, and will likely hit arm-specific issues.

If you’re happy investigating and fixing arm issues yourself, it’s probably best to start with Ubuntu 18.04 or 20.04 and work backwards to 16.04 once it’s working well on a newer version

**Comment by varatep** [comment]
Is this the case for the M1 arm64 mac architectures as well?
