### ISSUE TITLE
[ Typechecker ] Generic methods may not constrain generics from overriden methods

### ISSUE THREAD

**Issue by lexidor** [facebook/hhvm#8731]
**Describe the bug**

If a supertype declares `T as arraykey` and a child declares `T as int`, you can write unsafe code that passes the typechecker.

**Standalone code, or other way to reproduce the problem**

```HACK
abstract class Father {
  abstract public function f<T1 as arraykey>(T1 $x): int;
}
class Child extends Father {
  public function f<T1 as int, T2>(T1 $x): int {
    return $x;
  }
}

function get_father(): Father { return new Child(); }
function get_child(): Child { return new Child(); }

<<__EntryPoint>>
function main(): void {
  get_child()->f(0);
  echo "Child deal with this well, since T1 is constrained.\n";
  try {
    get_father()->f('prepare for a big boom');
  } catch (\TypeError $e) {
    echo "This API is not typesafe,\nbut the typechecker can not tell you that.\n";
  }

  try {
    get_child()->f('typechecker can see this as not being safe');
  } catch (\TypeError $e){
  }
}
```

1. Copy the code above.
2. Observe one typechecker error for `get_child()->f('type...safe');
3. Observe no typechecker error for the call `get_parent()->f('prep...boom');
4. Observe a `\TypeError` for both calls.

**Expected behavior**

In the same way that it is not valid to declare `Child::f(int)`, it should also not be valid to constrain `T1` to an int.
The method is no longer compatible with the parent, since the parent accepted ints and strings, but the Child only accepts ints.
This can cause `\TypeError`s when the child assumes `T1` to be an int, while it could also be a string type via `Parent`.

**Actual behavior**

Only one typechecker error is emitted for the bad call on `Child`.
```
Typing[4323] Invalid argument
   --> file.hack
  5 |   public function f<T1 as int, T2>(T1 $x): int {
    |                           ^^^ Some type constraint(s) are violated here
    |                     ^^ T1 is a constrained type parameter
    |                           ^^^ Expected int
 24 |     get_child()->f('typechecker can see this as not being safe');
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ But got string

1 error found.
```

**Environment**
 - Ubuntu 20.04
 - apt-get with dl.hhvm.com repository
```
HipHop VM 4.56.1 (rel)
Compiler: 1593547575_929404933
Repo schema: d1ae8e21bf3419a65f12a010527485564e719d07
hackc-0b10dd000fc9b454637d8dffc67fb542d231572c-4.56.1
```

**Additional context**

This is only possible if `T2` is present.
Removing `T2` makes the typechecker able to see the unsafe declaration of `Child::f<T1>`.
```
Typing[4341] The method f has the wrong type
   --> file.hack
  5 |   public function f<T1 as int>(T1 $x): int {
    |                   ^
    |                           ^^^ Some type constraint(s) are violated here
    |                     ^^ T1 is a constrained type parameter
    |                           ^^^ Expected int
    |                     ^^ But got T1
```

**Comment by jamesjwu** [comment]
This looks like it's caused by the TODO listed here: https://github.com/facebook/hhvm/blob/master/hphp/hack/src/typing/typing_subtype_method.ml#L69-L77

Not sure whether it's ever sound to allow child methods to have a different number of type parameters than its parent, but assuming we can safely disallow that behavior, it should allow the fix. In either case, we should at least be checking that the common type parameters between child and parent match up w.r.t constraints.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

An error is reported on the declaration of Child::f(). The expected behavior has become the actual behavior.
```
Typing[4341] The method f is not compatible with the overridden method [1]
-> T1 is a constrained type parameter [2]
-> This type constraint is violated [3]
-> Expected int [3]
-> But got T1 as arraykey [4]

src/file.hack:5:19
        1 | abstract class Father {
[4]     2 |   abstract public function f<T1 as arraykey>(T1 $x): int;
        3 | }
        4 | class Child extends Father {
[1,2,3] 5 |   public function f<T1 as int, T2>(T1 $x): int {
        6 |     return $x;
        7 |   }
```
