### ISSUE TITLE
Can't compile on Centos 8

### ISSUE THREAD

**Issue by IvorNetJam** [facebook/hhvm#8740]
The entire process goes well so far, but I'm stuck on compiling Folly

Done: 0/0 (jobs: 1)[ 25%] Built target folly
[ 25%] Built target neo
[ 25%] Built target version
[ 26%] Built target squangle
[ 30%] Built target hphp_util
[ 33%] Built target fizz
[ 33%] Built target hphp_parser
[ 33%] Built target hphp_zend
[ 33%] Built target hfsort
[ 33%] Built target ppc64-asm
[ 33%] Built target hphp_system
[ 34%] Built target vixl
[ 35%] Built target hphp_analysis
[ 37%] Built target wangle
[ 38%] Built target hphp_hhbbc
[ 44%] Built target hphp_proxygen
[ 50%] Built target hphp_thrift
[ 58%] Built target mcrouter
[ 58%] Built target jit_sort
[ 58%] Built target hack_dune
[ 58%] Built target hack
[ 84%] Built target hphp_runtime_static
[100%] Built target hphp_runtime_ext
[100%] Linking CXX executable hhvm
Generating Repo Schema ID and Compiler ID

../../third-party/folly/libfolly.a(../../third-party/folly/CMakeFiles/folly.dir/src/folly/detail/Demangle.cpp.o):Demangle.cpp:function folly::detail::cplus_demangle_v3_callback_wrapper(char const*, void (*)(char const*, unsigned long, void*), void*): error: undefined reference to 'cplus_demangle_v3_callback'
collect2: error: ld returned 1 exit status
make[2]: *** [hphp/hhvm/CMakeFiles/hhvm.dir/build.make:397: hphp/hhvm/hhvm] Error 1
make[1]: *** [CMakeFiles/Makefile2:2981: hphp/hhvm/CMakeFiles/hhvm.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

cc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --disable-libmpx --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 8.3.1 20191121 (Red Hat 8.3.1-5) (GCC)

**Comment by bms8197** [comment]
[root@hhvm hhvm]# uname -a
Linux hhvm 4.18.0-193.6.3.el8_2.x86_64 #1 SMP Wed Jun 10 11:09:32 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
[root@hhvm hhvm]# gcc --version
gcc (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

I'm having a similar issue:

```
[  0%] Built target fmtBuild
[  1%] Built target bundled_zstd
[  2%] Built target bundled_boost
[  2%] Built target libsodiumBuild
[  2%] Built target libsodiumMaybeBuild
[ 14%] Built target folly
[ 18%] Built target hphp_util
[ 18%] Built target libzipBuild
[ 18%] Built target timelib
[ 18%] Built target eaw_table
[ 23%] Built target mbfl
[ 26%] Built target fizz
[ 28%] Built target wangle
[ 28%] Built target brotlicommon
[ 28%] Built target brotlidec
[ 29%] Built target brotlienc
[ 35%] Built target hphp_proxygen
[ 41%] Built target hphp_thrift
[ 41%] Built target afdt
[ 44%] Built target ragel
[ 52%] Built target mcrouter
[ 53%] Built target jit_sort
[ 53%] Built target hfsort
[ 53%] Built target version
[ 53%] Built target hphp_parser
[ 53%] Built target hphp_system
[ 53%] Built target hphp_analysis
[ 54%] Built target opamDownload
[ 54%] Built target opam_setup
[ 54%] Built target bundled_rust
[WARNING] Running as root is not recommended
[WARNING] Running as root is not recommended
[ 54%] Built target hack_dune
[ 54%] Built target hack
[ 56%] Built target hphp_hhbbc
[ 56%] Built target neo
[ 57%] Built target hphp_zend
[ 57%] Built target bundled_fbmysqlclient
[ 58%] Built target squangle
[ 58%] Built target ppc64-asm
[ 59%] Built target vixl
[ 85%] Built target hphp_runtime_static
[100%] Built target hphp_runtime_ext
[100%] Built target systemlib
[100%] Linking CXX executable hhvm
Generating Repo Schema ID and Compiler ID
../../third-party/folly/libfolly.a(../../third-party/folly/CMakeFiles/folly.dir/src/folly/detail/Demangle.cpp.o):Demangle.cpp:function folly::detail::cplus_demangle_v3_callback_wrapper(char const*, void (*)(char const*, unsigned long, void*), void*): error: undefined reference to 'cplus_demangle_v3_callback'
collect2: error: ld returned 1 exit status
make[2]: *** [hphp/hhvm/CMakeFiles/hhvm.dir/build.make:398: hphp/hhvm/hhvm] Error 1
make[1]: *** [CMakeFiles/Makefile2:2774: hphp/hhvm/CMakeFiles/hhvm.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

CentOS is not a support distribution for running hhvm. I am sorry to hear nobody came to aid you in your efforts of building on CentOS. I am closing this issue, assuming you've moved on.

If you haven't, or anyone else is trying to get a CentOS build going, please open a new issue. Please note that this build will have to be community supported.
