### ISSUE TITLE
Dyld Library Not Loaded

### ISSUE THREAD

**Issue by huizhifan** [facebook/hhvm#8744]
macOS
I tried to follow the instruction: https://docs.hhvm.com/hhvm/installation/mac
Installation is good.
When I tried to run hhvm command, I got an error:
dyld: Library not loaded: /usr/local/opt/zstd/lib/libzstd.1.dylib
Referenced from: /usr/local/bin/hhvm
Reason: image not found
Abort trap: 6

Build ID: HHVM=HHVM-4.68.0:HSL=v4.41.0:2020-08-17T20:16:46+0000:7af74eee111304c3c25319df9d95501d92a64697
Page requested: /hhvm/installation/mac
Page requested at: Thu, 20 Aug 2020 18:22:57 +0000
Controller: GuidePageController

**Comment by fredemmott** [comment]
This should be resolved in recent packages; alternatively, install the `zstd` package with homebrew
