### ISSUE TITLE
Add JetBrains Support

### ISSUE THREAD

**Issue by andrisole92** [facebook/hhvm#8747]
**Is your feature request related to a problem? Please describe.**
VS Code is not that good, it's showing me some strange errors: e.g. `Other[undefined] hh_server isn't running, so there may be undetected errors. Try `hh` at the command line... hh_server: stopped.hh_server` even when the hh_server is running.

Nothing like this usually happens in IntelliJ.

**Describe the solution you'd like**
It would be good to have an ability to work with the Hack in JetBrains IDE such as PHPStorm or IntelliJ.

**Describe alternatives you've considered**
I have considered alternative of writing my own Hack plugin for IntelliJ, but I feel like it is ultimately duty of Facebook's engineering team.

**Additional context**

There is no additional context.

**Comment by fredemmott** [comment]
Sorry, we do not currently otherwise extending IDE support beyond LSP-focused editors.

PHPStorm in particular is not an appropriate target as Hack continues to diverge from PHP.

**Comment by andrisole92** [comment]
All right, thanks @fredemmott , any chance it can get any of the JetBrains product support? E.g. IntelliJ?

**Comment by xepozz** [comment]
@andrisole92 https://github.com/facebook/hhvm/discussions/9652
