### ISSUE TITLE
There is no repo or release for HHVM on el8 or Centos 8.

### ISSUE THREAD

**Issue by jdsjdk** [facebook/hhvm#8749]
Hello guys,  I'm running Centos 8:

Linux 4.18.0-193.14.2.el8_2.x86_64

and I'm trying to follow this tutorial:

https://www.hugeserver.com/kb/install-hhvm-centos-nginx/ 

But the only version they have is for hhvm 3, and you're on hhvm 4.73 stable for both debian and ubuntu.  Also, this tutorial does not work for el8, and I'm trying to fix that as we speak.  In fact, it looks like you only support Debian and Ubuntu and do not have hhvm packages for any other popular distro.  I _**really**_ don't want to start over and wipe the slate clean with a fresh OS, because that would be losing about 8-10 hours worth of work.  If there's something that can be done, that would be great.  Please let me know, thanks.  (FYI, I've looked **everywhere** on the internet, and I can't a repo for el8 for hhvm.)

**Comment by fredemmott** [comment]
Sorry, you're correct in that we only support Debian and Ubuntu (and MacOS); for other distributions, there is https://docs.hhvm.com/hhvm/installation/building-from-source , however we have not tested these instructions on other distributions.

We'd be open to a pull request following whatever the current rpm/yum/.... best practices are over at https://github.com/hhvm/packaging - we'd likely be able to review such a pull request, set up the necessary infrastructure to automate builds, fix it when it breaks, but we're not currently able to spend the time creating an initial version of rpm packaging.

**Comment by jdsjdk** [comment]
This is.... unfortunate.  I've now determined that the best course of action would to wipe the slate completely clean and start over with Debian.  This is going to set me back about 10 hours worth of work.  But to avoid bugs and issues, this ensures that I will not have any problems moving forward.
Something you guys might want to think want to think about is adding support for rpm/el# packages because for when customers have project regarding things like say, _**government contracting**_ the OS of choice is going to be Red Hat.  This would be very helpful for the future rather than compiling from scratch.  Anyway, thanks again for your time.

**Comment by fredemmott** [comment]
Thanks for the feedback; we do understand this will be important for adoption - however adoption-related issues are currently not a priority: our assumption is that the rate of breaking changes to the language will give a very bad experience to the vast majority of potential users (especially those seeking enterprise-levels of stability), so working on adoption now would be likely be harmful long-term. This (along with windows support) is something we’ll definitely be revisiting as the language stabilizes
