### ISSUE TITLE
Update facebook dependency pins (folly, thrift, etc)

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#8751]
- blocks D22125736
- tagit now creates release tarballs for these; these should be used instead of submodules (in a similar way to other recent conversions in third-party/)
- FBThrift's CPP2 generator no longer requires python; it might be practical to build the thrift compiler and remove the committed codegen. Limiting factor is likely to be flex/bison - needs testing on oldest+newest supported ubuntu + debian + macos

**Comment by jjergus** [comment]
Probably do a regular update first to unblock D22125736, then do the other changes separately? I can work on the update today.

**Comment by jjergus** [comment]
On top of the other changes, it would also be nice if we didn't have to maintain a copy of folly/mcrouter/etc. CMakeFiles that need to be kept in sync with the originals (https://github.com/jjergus/hhvm/commit/f3aa703b78186ba4cbd1da06a3b540d355ff418f). @fredemmott do you remember why we have these?

**Comment by fredemmott** [comment]
Folly's cmake support was added in April 2017; HHVM's been building it with cmake for somewhat longer. I don't know of a reason for us not to use it, but I don't think it's been tried

**Comment by jjergus** [comment]
https://github.com/facebook/hhvm/pull/8752 (still waiting for test builds so may need more changes -- I'm sure it will fail somehow on MacOS)

**Comment by yfeldblum** [comment]
@jjergus #8752 has closed; is this ready?

**Comment by jjergus** [comment]
The pins were updated in #8752 (I think your change that was waiting for that has also landed, wasn't that https://github.com/facebook/hhvm/commit/44dfa66b7e35f566f3fd9ea3f853cc9d349bea4b?) but we haven't done any of the other changes mentioned above yet.

Also I'm working on updating the pins again to this week's release of Folly etc. (#8754) which should help in case you're planning any more HHVM changes that need a newer Folly version.
