### ISSUE TITLE
var_export produces unparseable php arrays for d/varray

### ISSUE THREAD

**Issue by ssandler** [facebook/hhvm#8759]
**Describe the bug**
`var_export()` still produces the string `array()` for darray and varray, even though `array()` is no longer supported by HHVM's parser as of version 4.65. This breaks the contract that `var_export($data)` can be safely used for codegen.

**Standalone code, or other way to reproduce the problem**
```
hhvm -a
hphpd> var_export(shape('a' => true));
var_export(shape('a' => true));
array (
  'a' => true,
)
hphpd> var_export(varray[1, 2, 3])
var_export(varray[1, 2, 3])
array (
  0 => 1,
  1 => 2,
  2 => 3,
)
hphpd> var_export(darray['a' => 'test'])
var_export(darray['a' => 'test'])
array (
  'a' => 'test',
)
```

**Expected behavior**

`var_export()` should produce `darray[]` or `varray[]` literals for d/varrays.

**Actual behavior**

`var_export()` produces PHP `array()` literals, which aren't parseable.

**Environment**
 - Operating system: MacOS Catalina
- Installation method: homebrew
> Please include the output of `hhvm --version` and `hh_client --version`
```
HipHop VM 4.79.0 (rel)
Compiler: 1602537842_N
Repo schema: 09d2af8dd22201dd8d48e5dcfcaed281ff9422c7
```

**Additional context**
From my reading of the code there isn't a runtime option that impacts this. ext_std_variable.cpp uses `VariableSerializer::Type::VarExport`
https://github.com/facebook/hhvm/blob/master/hphp/runtime/ext/std/ext_std_variable.cpp#L244

And if the type is anything but `PHPOutput`,  `array()` is used even for darray and varray https://github.com/facebook/hhvm/blob/master/hphp/runtime/base/variable-serializer.cpp#L921

**Comment by fredemmott** [comment]
Thanks - FB D24427008 adds an option for this, which we expect to flip and remove relatively quickly

**Comment by fredemmott** [comment]
https://github.com/facebook/hhvm/commit/ff29bd02949b61366d6808d83f8c0bf22a8fa562 should be in 4.81 and above
