### ISSUE TITLE
Please add thrift support

### ISSUE THREAD

**Issue by legol** [facebook/hhvm#8760]
Apache/thrift doesn't support hack.
fbthrift claims support hack but the files in https://github.com/facebook/fbthrift/tree/master/thrift/lib/hack/src are way out of date. Latest HHVM won't be able to use those files.

Please either add support to Apache/thrift or fbthrift.

**Comment by fredemmott** [comment]
Closing; several duplicate issues on github.com/facebook/fbthrift
