### ISSUE TITLE
Is running PHP not supported anymore? If so, I wouldn't know.

### ISSUE THREAD

**Issue by IngwiePhoenix** [facebook/hhvm#8773]
**Describe the bug**
Consider the following:

```php
<?php

phpinfo();
```

Running it with `hhvm` only tells me it's not a Hack file, but that is just about it:
```
root@ingwie-io /s/artic.us.com $ hhvm test.php

Fatal error: Uncaught Error: Not a Hack file in :
Stack trace:
#0 {main}
root@ingwie-io /s/artic.us.com $ hhvm --php -f test.php

Fatal error: Uncaught Error: Not a Hack file in :
Stack trace:
#0 {main}
```

I am new to HHVM and want to poke around with it to see what it can do that plain PHP can't, which means I have to start using `<?hh` instead - or so I remember from when I last installed it (I think it was early 3.x back then). However, to just get going and see how it performs on certain scripts I have laying around, I'd love to run it in "PHP mode".

Now, what could *actually* be the case, is that PHP interpretation is completely gone and the end-user, who just installs it to give it a whirl, would never know.

**Standalone code, or other way to reproduce the problem**
See above.

1. Install HHVM through APT
2. Copy the above PHP script, save as `test.php`
3. `$ hhvm test.php`
4. `$ hhvm --php -f test.php`

**Expected behavior**
A clear indication if PHP mode is deprecated, not enabled, no longer available or has to be triggered by other means. In other words: A more user friendly error message.

**Actual behavior**
An error (that actually happens to miss the file path, now that I look at it) that tells me that this is a PHP file and how I should run it, if that is even still possible.

**Environment**
 - Operating system
Debian 10, amd64
 - Installation method
APT
 - HHVM Version
```
HipHop VM 4.85.0 (rel)
Compiler: 1606768708_844905998
Repo schema: d1ae8e21bf3419a65f12a010527485564e719d07
```

**Comment by fredemmott** [comment]
It’s been removed, as has the ability to reliably detect PHP files. HHVM is a runtime for Hack since v4.0 in Jan 2019

**Comment by fredemmott** [comment]
Sorry, let's go into some of the details:
- file names and line numbers: thanks, turns out this bug has been around for a while - filed #8774
- friendlier error messages: we generally don't want PHP to be in any way special, and we can't reliably say "you should use PHP instead for this file" any more, as the parser doesn't actually know anything other than "this isn't a hack file". We /could/ say "If this is a PHP file ..."
