### ISSUE TITLE
typechecker incorrectly raises error if a function is declared with a name that was `used` as a function name in a previous scope

### ISSUE THREAD

**Issue by lexidor** [facebook/hhvm#8791]
**Describe the bug**
hh_client --concatenate-all emits files in alphabetical order. When file A that `use`s an entity from file B is emitted first, the following error is created: _Cannot declare %s because the name was explicitly used earlier via a use statement on line %d_
This is both a typechecker and runtime error.

**Standalone code, or other way to reproduce the problem**

src/a.hack
```HACK
use function DependencyOrder\dependency;

function dependent(): int {
  return dependency();
}
```

src/b.hack
```HACK
namespace DependencyOrder;

function dependency(): int {
  return 42;
}
```

src/.hhconfig
```
```

./build.sh
```SH
#! /usr/bin/env sh
rm -rf dist
mkdir dist
cp src/.hhconfig dist/.hhconfig
cd src && hh_client --concatenate-all . > ../dist/target.hack
cd ../dist && hh_client; hhvm target.hack
```
_The files below this line are generated by executing build.sh._

dist/.hhconfig
```
```

dist/target.hack
```HACK
///// a.hack /////
use function DependencyOrder\dependency;

function dependent(): int {
  return dependency();
}
}
///// b.hack /////
namespace DependencyOrder{
function dependency(): int {
  return 42;
}
}
```

1. Recreate the directory structure `./build.sh`, `src/a.hack`, `src/b.hack`, `src/.hhconfig`
2. Make `build.sh` executable
3. Execute `./build.sh`
4. Observe the the typechecker error and runtime error emitted.
5. Verify that files have been laid out in the order `a.hack` followed by `b.hack`.

**Expected behavior**

The files should be laid out in an order which prevents situation in which a use statement refers to something declared later.

**Actual behavior**

```
Parsing[1002] Cannot declare DependencyOrder\dependency because the name was explicitly used earlier via a use statement on line 2 [1]

target.hack:10:10
     8 | ///// b.hack /////
     9 | namespace DependencyOrder{
[1] 10 | function dependency(): int {
    11 |   return 42;
    12 | }

1 error found.

Fatal error: Cannot declare `DependencyOrder\dependency` because the name was explicitly used earlier via a `use` statement on line 2 in /path/to/dist/target.hack on line 10
```

**Environment**
 - Operating system
> Ubuntu 20.04
 - Installation method
> apt-get with dl.hhvm.com repository
 - HHVM Version
```
HipHop VM 4.88.0 (rel)
Compiler: 1608057745_641342368
Repo schema: d1ae8e21bf3419a65f12a010527485564e719d07
hackc-9e3bb09ecef0a93ae0917fb44ed4e2434e990c17-4.88.0
```

**Additional context**
This may cause issues when making hsl components part of the builtins. #8642

**Comment by fredemmott** [comment]
Simpler example:


```hack
namespace A {
  use function Foo\bar;
}
namespace B {
  use function Foo\bar;
}
```

This should be valid but is not.

**Comment by fredemmott** [comment]
FB T86468166

Interestingly, this is considered valid - it's a bug specific to `use` statements:

```hack
namespace A {
  function foo(): void {}
}
namespace B {
  function foo(): void {}
}
```

**Comment by fredemmott** [comment]
> This may cause issues when making hsl components part of the builtins.

Kinda: to run the tests, I either need this resolved, or a native autoloader

**Comment by fredemmott** [comment]
TIL: definition order does not matter to HHVM any more. This is definitely not a dependency issue.
