### ISSUE TITLE
Segmentation fault Ubuntu 20.04

### ISSUE THREAD

**Issue by docfate111** [facebook/hhvm#8793]
Installing hhvm results in segmentation fault?
```
apt-get update
apt-get install software-properties-common apt-transport-https
apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xB4112585D386EB94

add-apt-repository https://dl.hhvm.com/ubuntu
apt-get update
apt-get install hhvm
```

```
hhvm -> Segmentation fault
hhvm file.hack -> -> Segmentation fault
```

**Comment by fredemmott** [comment]
This is probably #8797; if you're still seeing this on 4.94 (or shortly, 4.(88-93).1), please re-open with more information such as:
- information on the system it is running on
- if you are able to, install the `hhvm-dbg` package too, and run hhvm inside gdb. When it segfaults, run `thread apply all bt` and share the result
