### ISSUE TITLE
No way to call variadic functions at runtime after deprecation of call_user_func_array

### ISSUE THREAD

**Issue by eryi** [facebook/hhvm#8795]
**Describe the bug**
Methods such as AsyncMysqlConnection::queryf accepts a variable number of parameters. Currently, I am generating the SQL statement at runtime and using call_user_func_array to call queryf with a variable number of parameters. For complex queries, there could be 100+ parameters.

With the deprecation of call_user_func_array in HHVM 4.75, there is no way to call variadic functions at runtime with different number of parameters. Also, there doesn't seem to be any workaround.

**Comment by simonwelsh** [comment]
You can use a splat.

```hack
$values = vec[1, 2, 3, 4];
var_dump(...$values);
```

**Comment by eryi** [comment]
Thanks! Didn't know that.

**Comment by fredemmott** [comment]
That is unsafe, and likely to need FIXMEs (and for those fixmes to be whitelisted in hhconfig).

Refactorying to use `queryAsync()` and the `HH\Lib\SQL\Query` class is much better, and allows generating queries as long as they are not fully dynamic - for example, two queries can be concatenated with `new Query('%Q %Q', $query_a, $query_b)`.

Theses are definitely under-documented, and https://github.com/hhvm/user-documentation/pull/911 starts to fix that
