### ISSUE TITLE
Brotli files are installed during a release build

### ISSUE THREAD

**Issue by xuanruiqi** [facebook/hhvm#8798]
**Describe the bug**
Brotli files are installed during a release build.

**Standalone code, or other way to reproduce the problem**
I used a build command sequence similar to the official guidelines; the only difference is that I tweaked install prefixes (because I was building a package):

    cmake -Wno-dev \
          -DCMAKE_BUILD_TYPE=RelWithDebInfo \
          -DCMAKE_INSTALL_PREFIX=/usr \
          -DCMAKE_INSTALL_LIBDIR=lib \
          -DCMAKE_PREFIX_PATH="${srcdir}" \
          -DMYSQL_UNIX_SOCK_ADDR=/run/mysqld/mysqld.sock \
          .
    make
    make install

**Expected behavior**
Bundled brotli files are not installed.

**Actual behavior**
Bundle brotli files are installed during `make install`.

**Environment**
 - Operating system
> Arch Linux (rolling)
 - Installation method
> Built from source
 - HHVM Version

```
HipHop VM 4.94.0 (rel)
Compiler: tags/HHVM-4.94.0-0-g510a8a05894483f0f398f380df8587a03d52bf2d
Repo schema: 308c3a50e48f6f7ddd29aac56f7802daa2930fb9
```

**Comment by fredemmott** [comment]
Sorry for the extremely slow response:

our -dev packages - and management of third-party dependencies - are generally pretty broken at the moment.

I've been working through these, but takes a lot of time for each dependency. My overall plan is to make it so all the dependencies we build + statically link are handled consistency, then revisit making header/static library installation sane.

That said, I'm a little surprised to see this for brotli on 4.94 - I expected this to remain a general issue, but to be semi-fixed (i.e. not installed at all - fully fixed would be installing into an HHVM-specific subdir) with 464ee3f712bd0fb6d72a9735d3d6e34e90550611

**Comment by fredemmott** [comment]
Closing - this is part of https://github.com/hhvm/packaging/issues/163, and I'd like to centralize discussion
