### ISSUE TITLE
[ TypeChecker ] Ban `final private` on classes

### ISSUE THREAD

**Issue by lexidor** [facebook/hhvm#8805]
**Describe the bug**
When a base class declares a `final private` method and a child class declares a method with the same name, only the runtime catches this error, the typechecker doesn't catch it.

**Standalone code, or other way to reproduce the problem**
```HACK
abstract class Base {
    final private function privateFinal(): string {
        return 'Base';
    }
}

final class Child extends Base {
    private function privateFinal(): string {
        return 'Child';
    }
}
```

1. hh_client
2. hhvm %SCRIPT_NAME%

**Expected behavior**

The typechecker should emit an error that you are overriding a final private method of Base.

**Actual behavior**

The typechecker reports `No errors!`
HHVM reports `Fatal error: Cannot override final method Base::privateFinal()`.

**Environment**
 - Operating system
> Ubuntu 20.04
 - Installation method
> apt-get with dl.hhvm.com repository
 - HHVM Version
```
HipHop VM 4.98.1 (rel)
Compiler: 1614289828_486548987
Repo schema: d1ae8e21bf3419a65f12a010527485564e719d07
hackc-68e6c090a26fc254dc69c342e54a6469e51330b3-4.98.1
```

**Additional context**
Either `private final` is an error in and of itself, or `Child` is doing something that it should not be allowed to do.

**Comment by jthemphill** [comment]
Nice find!

`private final` feels like an oxymoron to me. A type shouldn't care about its parents' private methods. I'm in favor of banning `private final` altogether.

**Comment by jthemphill** [comment]
Filed T88186581 internally to ban `final private` from the language.

**Comment by lexidor** [comment]
Would this remain supported in traits? The meaning of `final private` in traits is different from within classes. It means that the using class can't override the method.

**Comment by jthemphill** [comment]
Yes, we’ll continue to support `final private` in traits.

On T88186581, @periodic1236 wrote:

> I agree with the goal here, but I think we need a solution for traits first. It is bad for framework designers if a class that uses a trait can silently override a private method that was defined in the trait, causing the new implementation to be used instead (note this does not happen when extending a class). Today, final private is the only way to have the type checker signal a problem (although the runtime would allow the override, the developer would still be forced to change the trait because of Hack).

Long term, @periodic1236 advocates for changing both traits and `final`:

> Personally, I wish we could have a concept of trait-private methods, require the remainder of such methods to be protected if they need to be used from users of the trait (unfortunately this changes the copy-paste nature of trait code, but meh), and also change methods to be final by default (requiring a keyword like "open" to allow a method to be overridden).

**Comment by Wilfred** [comment]
After doing some work on this, I kinda think we should ban it on traits too. If we only ban final private methods on classes, hh will still accept this code that HHVM rejects:

```
trait MyTrait {
  public function foo(): void { $this->bar(); }
  final private function bar(): void {}
}

class MyClass {
  use MyTrait;
}

class MyChild extends MyClass {
  private function bar(): void {}
}
```

@lexidor do you have any opinions here?

**Comment by lexidor** [comment]
We should indeed not allow a program to typecheck which won't even pass inheritance checks (can't even start to run). Most traits I touch have private methods and I lint that they must be final. The idea of a private method being overridden is very counterintuitive and rarely intended. Most private methods in traits are not even meant to be called by the using classish.

In the interim to truly internal private trait methods (not exposed to the using classish), I'll mangle the method names and lint for that instead. If a method declared in a trait is private, it must have the suffix. If a method declaration has this suffix, it must be in trait context. This enforces final through a lint rule, but only in trait-class usage, not trait-in-trait usage.

```HACK
trait One {
  private function isEven_TRAIT_PRIVATE(int $i): bool { return $i % 0 === 0; }
  //...
}
```

**Comment by lexidor** [comment]
Or I'll use `final protected` in the trait. This is more clutter in classes which extend the using class, but it is at least water tight.

**Comment by lexidor** [comment]
Hmmm, almost all private methods in traits are (or should) final though. Overriding a private trait method is very counterintuitive. The trait author can not call private methods from the the trait without the using class getting a chance to override. `final private` although an oximoron is the only valid defense. Unless the rules of the language change so that private trait methods can not be overridden by a using class / trait, trait authors will be forced to say `final protected` even though they most likely didn't want the method to be visible at all. I like the truly private trait method proposal.

**Comment by lexidor** [comment]
Linking context from the commit log: https://github.com/facebook/hhvm/commit/c8faa1a2e853364445f29f316c5f51a678b3053d
This commit bans `private final` on classes.

**Comment by lexidor** [comment]
Exported the trait issue to #9046. Private final is banned on classes, so the title of this issue has been resolved. Closing to minimize noise for people dealing with the trait case.
