### ISSUE TITLE
Possible to fork a compatible version with future version of php?

### ISSUE THREAD

**Issue by hiqsociety** [facebook/hhvm#8806]
Everything needs to be <?hh now and everything's different in 4.8 etc

possible to do one that's compatible with php?

i wanted to upgrade to hhvm 4.8 from 3.2 until i realised it's next to impossible to do so for wordpress

**Comment by fredemmott** [comment]
You are welcome to create such a fork, however it would be a substantial work. The HHVM team (and Facebook) have no plans to create or maintain such a fork, or to otherwise support PHP code in HHVM.
