### ISSUE TITLE
How to Apply LBR Events in Perf to Hfsort to Reliable Rearrange Program Functions？

### ISSUE THREAD

**Issue by majin2020** [facebook/hhvm#8807]
hi  ,

  I've been working on function rearrangement recently, and I've been honored to see hfsort and read related papers and source code. In the [paper](https://ieeexplore.ieee.org/abstract/document/7863743), the hfsort tool can use the lbr event of the perf tool to output accurate program call diagram information. Unfortunately, I did not find the related usage instructions. I only successfully run hf-prod-collect.sh and rearrange the program, but there does not seem to be any improvement in performance.

  The following sentence is included in this [paper](https://ieeexplore.ieee.org/abstract/document/7863743).
```
  The first one is to use hardware support available on modern Intel x86 processors, called last 
branch records (LBR) [10].This is basically a 16-entry buffer that keeps the last 16 executed 
control-transfer instructions, and which can be programmed to filter the events to only keep
records for function calls. The caller-callee addresses from the LBR can beread through a 
script passed to the Linux perf tool. 
```
  Will LBR events make hfsort more accurate and effective? I wonder how I can get LBR to work in hfsort? Or is there a script or command that processes the perf.data data whit LBR events  to generate function caller-callee information?

  Could you help me for this?

thanks，
ijinma

**Comment by lexidor** [comment]
Closing, since this question has not been answered in three+ years. Sorry for the out of the blue GitHub Notification.
