### ISSUE TITLE
dyld: Symbol not found when running for the first time (home-brew install)

### ISSUE THREAD

**Issue by el-pablo** [facebook/hhvm#8839]
**Describe the bug**
When I run HHVM in my terminal (zsh), I receive an error saying that dyld cannot find a symbol in the glog dependency (error message below)

Run the following commands:
```
brew install hhvm
hhvm
```

**Expected behavior**

HHVM to start up!

**Actual behavior**
```
dyld: Symbol not found: __ZN6google21kLogSiteUninitializedE
  Referenced from: /usr/local/bin/hhvm
  Expected in: /usr/local/opt/glog/lib/libglog.0.dylib
 in /usr/local/bin/hhvm

```
**Environment**
 - Operating system
> macOS Big Sur 11.2.3
 - Installation method
> homebrew
 - HHVM Version
> Please include the output of `hhvm --version` and `hh_client --version`

hh_client --version : hackc-4006312aa0c4fda408bfeefe2c14b940bc235658-4.110.0
hhvm --version: errors, but brew info says hhvm-4.110

**Additional context**
brew was a bit unstable throughout the process, but I have reinstalled both glog and hhvm successfully and I am still receiving the error.

**Comment by fredemmott** [comment]
This was fixed yesterday by https://github.com/hhvm/homebrew-hhvm/commit/79b342301b9729416a9a4e99c09f2885358f7eb7

- `brew upgrade` and `brew install` don't seem to pick up the rebuild; try `brew upgrade; brew uninstall hhvm-4.110; brew install hhvm-4.110`
- if that doesn't resolve the problem, please open an issue at https://github.com/hhvm/homebrew-hhvm/issues

**Comment by el-pablo** [comment]
That's fixed it - thanks!
