### ISSUE TITLE
Support more key types for TLS 1.3 certificates

### ISSUE THREAD

**Issue by lexidor** [facebook/hhvm#8862]
## Edit
> [TLS 1.3 is supported but currently is only configured with support for RSA or p256 public keys.](https://github.com/facebook/hhvm/issues/8862#issuecomment-891371671)

My key is of a different kind, causing these errors. If you are using proxygen, you'll either have had issues all the time (because your key is a little esoteric) or it has always worked. No need to go check 🙂.

**Is your feature request related to a problem? Please describe.**
I want to set up a public facing `hhvm -m deamon` instance using https. I have managed to get things running, but tls 1.3 capable clients fail to connect.

**Command used**
```
echo 
sudo iptables  --table nat --append PREROUTING --protocol tcp --dport 80 --jump REDIRECT --to 8080
sudo ip6tables --table nat --append PREROUTING --protocol tcp --dport 80 --jump REDIRECT --to 8080
sudo iptables  --table nat --append PREROUTING --protocol tcp --dport 443 --jump REDIRECT --to 8443
sudo ip6tables --table nat --append PREROUTING --protocol tcp --dport 443 --jump REDIRECT --to 8443

echo "Hello, World!" > hello_world.txt

hhvm -m server --no-config -p 8080 -dhhvm.server.ssl_port=8443 -dhhvm.server.enable_ssl=1 \
  -dhhvm.server.ssl_certificate_file=/path/to/server.crt -dhhvm.server.ssl_ceritificate_key_file=/path/to/server.key \
  -dhhvm.server.certificate_dir=/path/to -dhhvm.server.expose_hphp=0
```

**Connecting to the server**
```
openssl s_client -tls1_2 -connect example.com:443
... loads of information about the connection ...
GET /hello_world.txt HTTP/1.1

... HTTP/1.1 200 OK ...
Hello, World!
```

```
openssl s_client -tls1_3 -connect example.com:443
140431281452416:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../ssl/record/rec_layer_s3.c:1543:SSL alert number 40
---
no peer certificate available
---
No client certificate CA names sent
---
...
Secure Renegotiation IS NOT supported
...
Verify return code: 0 (ok)
---

echo $?
1
```

Same goes for curl:
```
curl --tls-max 1.2 https://example.com
Hello, World!

curl --tls-max 1.3 https://example.com
curl: (35) error:14094410:SSL routines:ssl3_read_bytes:sslv3 alter handshake failure

echo $?
35
```

Same goes for Firefox 90
```
Before changing about:config
SSL_ERROR_NO_CYPHER_OVERLAP

Change about:config security.tls.version.max change from 4 to 3.
Hello, World!
```

**Describe the solution you'd like**
I would like for tls 1.3 clients to be able to see my server.

**Describe alternatives you've considered**
Proxying using a reverse proxy that speaks tls 1.3.

**Additional context**
N/A

**Comment by knekritz** [comment]
Which public key algorithm does your server certificate use (you can find this out in the Subject Public Key Info section if you run `openssl x509 -in /path/to/server.crt -text`)?

**Comment by lexidor** [comment]
It uses:
```
Public Key Algorithm: id-ecPublicKey
    Public-Key: (384 bit)
    pub:
        <key material>
    ANS1 OID: secp384r1
    NIST CURVE: P-384
```

**Comment by knekritz** [comment]
TLS 1.3 is supported but currently is only configured with support for RSA or p256 public keys. You can use a certificate with one of those to workaround or I will send a fix shortly to add p384 and p521 curves.

**Comment by lexidor** [comment]
Thanks for the insights. I am always very close to hhvm-latest. I can use my intentionally hampered Firefox (tls 1.2 max) for testing my application and keep using fastcgi in production. Once support for this signature algo lands, I can try migrating to proxygen.

**Comment by fredemmott** [comment]
@lexidor can you give this a try on 4.133 or above?

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Support for more key types was added around 4.133.
