### ISSUE TITLE
Function reference syntax parsing errors in HHVM 4.80-4.83

### ISSUE THREAD

**Issue by ssandler** [facebook/hhvm#8867]
**Describe the bug**
The new function reference syntax is enabled, but can produce runtime parsing errors (not typechecker errors) when used as a default function argument value in HHVM 4.80-4.83.

**Standalone code, or other way to reproduce the problem**
```
$ cat test2.hack
function example((function(int, int): int) $pick = HH\Lib\SecureRandom\int<>): int {
	return $pick(0, 1000);
}

$ docker run -it -v $(pwd)/test2.hack:/tmp/test.hack hhvm/hhvm:4.83-latest hhvm /tmp/test.hack

Fatal error: Uncaught Error: (Failure
  "Failed: TODO Unimplemented: We are missing a lot of cases in the case match. Delete this catchall") in :
Stack trace:
#0 {main}
```

There's no typechecker error for this code. This works as expected on HHVM 4.102.

**Environment**
 - Operating system
Ubuntu 18.04
 - Installation method
hhvm/hhvm on dockerhub
 - HHVM Version
```
HipHop VM 4.80.5 (rel)
Compiler: 1626791065_167909337
Repo schema: d1ae8e21bf3419a65f12a010527485564e719d07
```

```
HipHop VM 4.83.1 (rel)
Compiler: 1605139242_659654933
Repo schema: d1ae8e21bf3419a65f12a010527485564e719d0
```

**Comment by Wilfred** [comment]
This parses and executes as expected, and we've added f61af0c56d31ea474d774e30c35557ee78d87703 to check that :). I presume it's been fixed since this task was filed.
