### ISSUE TITLE
hackfmt adds extra new lines to the top of .hack files

### ISSUE THREAD

**Issue by zmagg** [facebook/hhvm#8877]
**Describe the bug**
Running `hackfmt` on `.hack` suffixed files will add a new line to the top of the file. Running it repeatedly will add additional new lines.

**Standalone code, or other way to reproduce the problem**
I can reproduce this on a small file:

```
final class ReproHackfmt {
}
```

**Expected behavior**

I expect hackfmt to be idempotent and to not add new lines to the top of files.
e.g. from a version before this bug is introduced:
```
~/dev/webapp@SFO-M-MZHOU03:docker run -it -v "/Users/mzhou/dev/webapp:/mnt/webapp"  hhvm/hhvm:4.80-latest bin/hackfmt /mnt/webapp/repro_hackfmt.hack
final class ReproHackfmt {

}
```

**Actual behavior**
e.g. from a version after this bug is introduced
```
~/dev/webapp@SFO-M-MZHOU03:docker run -it -v "/Users/mzhou/dev/webapp:/mnt/webapp"  hhvm/hhvm:4.124-latest bin/hackfmt /mnt/webapp/repro_hackfmt.hack

final class ReproHackfmt {

}
```

**Environment**

**Operating system**
Mac OS Catalina (with HHVM running inside docker using public docker images)
**Installation method**
hhvm/hhvm on dockerhub
**HHVM Version**

**First repro in:**
I bisected this issue down to being introduced in the 2020.11.18 nightly, reproduced off of [this public image](https://hub.docker.com/layers/hhvm/hhvm/2020.11.18/images/sha256-534b84ee63838bd5cc9454436600bbc3ff2d3c1ad4c6faa440177d8bb519a769?context=explore). 

Issue is still in place in latest image: hhvm/hhvm:4.124-latest 

Note, I can repro this with a completely empty .hhconfig file.

**Comment by zmagg** [comment]
Perhaps it's this commit introduced in the 11.18 nightly that also messes with shebang parsing for .hack files?

https://github.com/facebook/hhvm/commit/a90c44c28b58f2aaad3c675e357f18a502be4d80

**Comment by fredemmott** [comment]
```
$ cat test.hack
final class ReproHackfmt {
}
$ hackfmt test.hack

final class ReproHackfmt {
}
$ cat test2.hack
#!/usr/bin/env hhvm
final class ReproHackFmt {
}
$ hackfmt test2.hack
#!/usr/bin/env hhvm

final class ReproHackFmt {
}
$ cat test3.hack
#!/usr/bin/env hhvm

final class ReproHackFmt {
}
$ hackfmt test3.hack
#!/usr/bin/env hhvm


final class ReproHackFmt {
}
$ cat test4.hack

final class ReproHackFmt {
}
$ hackfmt test4.hack


final class ReproHackFmt {
}
```

**Comment by fredemmott** [comment]
FB T100881159
