### ISSUE TITLE
Visual code debugger adapter immediately dies when using vscode-hack debugger extension

### ISSUE THREAD

**Issue by ajayvohra2005** [facebook/hhvm#8895]
**Describe the bug**
When I try to debug a Hack script in Visual Studio Code using vscode-hack extension, visual code debugger adapter launches and immediately dies. My visual code global settings.json configuration is as below:
```
"configurations": [
{
"name": "HHVM: Run Script",
"type": "hhvm",
"request": "launch",
"script": "${file}",
"hhvmPath": "/usr/local/bin/hhvm",
"hhvmArgs": ["--mode", "vsdebug", "--vsDebugPort", 8999],
"cwd":"${workspaceFolder}"
}
]
```

**Standalone code, or other way to reproduce the problem**
Debug any hack script in visual code studio version shown below with ```vscode-hack``` extension version v 2.10.0:

```
Version: 1.60.0
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Date: 2021-09-01T10:54:53.442Z (1 wk ago)
OS: Darwin x64 20.6.0
```

**Steps to reproduce the behavior:**
Run/Debug any hack script from visual code studio after setting a breakpoint, or without setting a breakpoint. The visual code studio debugger launches and immediately dies. 

**Expected behavior**

Visual Studio Debugger should launch successfully.

**Actual behavior**

Visual Studio Debugger launches and immediately dies.

**Environment**
 - Operating system
Mac Os Big Sur 11.5.2

**Comment by fredemmott** [comment]
Closing, as this appears to be a configuration question about a third-party project: https://github.com/slackhq/vscode-hack/issues/125
