### ISSUE TITLE
`/A` modifier no longer supports non-zero offset

### ISSUE THREAD

**Issue by muglug** [facebook/hhvm#8917]
**Describe the bug**
Behaviour of `preg_match` and related `Regex\matches` has changed recently

**Standalone code, or other way to reproduce the problem**

in HHVM 4.121:

```
hhvm -a
> var_dump(preg_match("/php/A", " php", 0, 1));
int(0);
```

in HHVM 4.102:

```
hhvm -a
> var_dump(preg_match("/php/A", " php", 0, 1));
int(1);
```

**Expected behavior**

Not sure what is expected

**Environment**
 - Operating system: 'MacOS Catalina'.
 - Installation method: 'homebrew'
 - HHVM Version: 4.121

**Comment by fredemmott** [comment]
Fixes in 1c4816f7b2
