### ISSUE TITLE
Bugs found please reward if possible

### ISSUE THREAD

**Issue by ayushkumar63123** [facebook/hhvm#8943]
I found these errors while running pytest.
./hphp/zend/html_tables/generate-html-table.py:38:6: E999 SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
    print 'static const entity_doctype_table_t %s {' % table_name
     ^
./hphp/tools/convert_make_target_to_command.py:35:10: E999 SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
        print "%s [Quick|Slow|Zend][<blank>|Repo][VM|Jit|JitIR][-SubSuiteName]" % sys.argv[0]
         ^
2     E999 SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
2
Error: Process completed with exit code 1.

**Comment by lexidor** [comment]
@ayushkumar63123 I do not understand what this issue is about. Would you mind following the bug report template? This will make it easier to understand what you are trying to point out.

**Comment by fredemmott** [comment]
This seems likely to be using an incompatible version of Python; these scripts are probably unneeded nowadays, and likely need python2
