### ISSUE TITLE
Issue when linking tc-print (undefined reference to vtable)

### ISSUE THREAD

**Issue by hlitz** [facebook/hhvm#8949]
**Describe the bug**
I am compiling HHVM with GCC 10 on aarch64 and linking tc-print fails with:
IKNS0_17FizzServerContextEERKSA_INS_16ServerExtensionsEENS_13AsyncFizzBase16TransportOptionsE]+0x100): undefined reference to `vtable for fizz::server::ServerStateMachine'

undefined reference to `fizz::server::ServerStateMachine::processAppWrite(fizz::server::State const&, fizz::AppWrite)'
...

I know ARM is currently not supported but 
a) I have a series of patches already that I am happy to submit a pull for and 
b) this issue does not seem to be ARM specific.

I examined /hhvm/build/hphp/tools/tc-print/CMakeFiles/tc-print.dir/link.txt which includes 
/third-party/fizz/bundled_fizz-prefix/lib/libfizz.a
and nm libfizz.a shows symbols for e.g. processAppWrite

Any ideas?

**Standalone code, or other way to reproduce the problem**

make

**Expected behavior**

Linker should succeed

**Actual behavior**

Linker fails

**Environment**
 - Operating system
Ubuntu 20.04,  kernel  5.2.8
 - Installation method
built from source

**Additional context**

**Comment by hlitz** [comment]
turns out the ordering of libraries during linking is the culprit. Now the questions is how can I change the link order for tc-print

**Comment by fredemmott** [comment]
Do you know which other object depends on the fizz symbol?

**Comment by fredemmott** [comment]
Dependency order: it's likely that a depends b depends c, but CMake only knows `a depends (b & c)`.

This can be fixed by introducing an intermediate target, e.g. https://github.com/facebook/hhvm/commit/f20702ae6520db1c536677347262d920dbbca1ad for fizz itself

It's likely that fizz is 'c' in this case, 'b' fails to properly specify its' dependencies, and somewhere down the line, tcprint knows it depends on 'c' and 'b', but not the relation between them
It's likely that 'c'

**Comment by hlitz** [comment]
ok I found that wangle depends on fizz and folly. In wangle's CMakeLists.txt these dependencies are correctly defined using target_link_libraries (wangle fizz folly)

However, in the final link command used to link tc-print, fizz and folly are linked against BEFORE wangle, although wangle should be linked against first so that the linker will look for the symbols of fizz.

So in your example wangle would be b and fizz would  be c, but the wangle CMakeLists.txt correctly defines the dependency to c.

**Comment by fredemmott** [comment]
It looks like wangle doesn't currently have the extra `_deps` target, and that should help

**Comment by hlitz** [comment]
this solved it, thanks! I'll try to send a pull request
