### ISSUE TITLE
Well ment but sadly broken on Win32: test/slow/bad\directory/i_am_a_very_bad\file.php

### ISSUE THREAD

**Issue by IngwiePhoenix** [facebook/hhvm#8952]
**Describe the bug**
I wanted to try and compile HHVM on Windows to see how far it gets. Unfortunately, this was shot down at the stage of cloning.

After the clone, I got a notice, that checkout failed and running `git checkout` itself revealed this:
```
> git checkout
error: invalid path 'hphp/test/slow/bad\directory/i_am_a_very_bad\file.php'
error: invalid path 'hphp/test/slow/bad\directory/i_am_a_very_bad\file.php.expect'
```

I get the idea, but this doesn't really work on Windows unfortunately. So... Is a Windows build only possible through MSYS?

**Standalone code, or other way to reproduce the problem**
- `git clone --recursive https://github.com/facebook/hhvm.git`

See above.

**Expected behavior**
A properly cloned and checked-out repo so I can run the other build steps (`mkdir out; cd out; cmake -G Ninja ..; ninja`)

**Actual behavior**
Already shown above. Sadly, the `git status` output suggested by the result of `git pull` pushed the actual command out of the buffer. But I was also recommended to run some `git restore` command...? Not sure, can't copy that because it went out of the buffer.

**Environment**
 - Operating system
> Windows 10 Pro (`10.0.19043 19043` via `systeminfo`)
 - Installation method
> Git
 - HHVM Version
> Master branch

**Additional context**
I was running this on an exFAT formatted harddrive within a VS 2019 64bit shell.

**Comment by Wilfred** [comment]
Hack/HHVM is not supported on Windows I'm afraid.
