### ISSUE TITLE
Does HHVM support Debian 11 and GCC 11.2? I always got -fPIC link error

### ISSUE THREAD

**Issue by DanielKui** [facebook/hhvm#8965]
I'm using debian 11 and GCC 11.2. I use the following command to build hhvm:

1. cmake -DMYSQL_UNIX_SOCK_ADDR=/dev/null  
2. make -j 4

then I got the below link error, How can I fix it?
![test](https://user-images.githubusercontent.com/578118/151134388-8698f74f-7c2c-40b0-8b63-24cd26367334.jpg)

**Comment by fredemmott** [comment]
Sorry, we only support using the system compilers at present; GCC 11 is not yet the system compiler on any platform we support.
