### ISSUE TITLE
Build from source code freezes the system on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by win3zz** [facebook/hhvm#8977]
I am trying to build HHVM from source in my Ubuntu guest machine from VirtualBox. As described in https://docs.hhvm.com/hhvm/installation/building-from-source `cmake -DMYSQL_UNIX_SOCK_ADDR=/var/run/mysqld/mysqld.sock .` runs successfully when building HHVM but when I run `make -j 3` it occupies my entire (10 GB) RAM and freezes.
The only option left with me is to power-off and restart the virtual machine.

> Tried to downgrade gcc and g++ version to 7 but faced the same problem
> I've tested both with and without -jN option

System specification:
- CPU(s): 3
- Architecture: x86_64
- Model name: Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz
- RAM: 10 GB
- OS: Ubuntu 20.04.3 LTS
- GCC and G++: 9.3.0

Please check below screenshot for your reference:
![2022-01-30_18-02](https://user-images.githubusercontent.com/12781459/151701416-bdd8e5ad-b24c-4832-91a4-fdff61870cff.png)

**Comment by fredemmott** [comment]
Sorry, the build is *extremely* ram hungry, both due to a heavy use of templates, and the final linking step. It's generally possible to get it built with 16GB, but we're not able to lower the requirements.
