### ISSUE TITLE
No rule to make target 'third-party/fmt/bundled_fmt-prefix/lib/libfmt.a', needed by 'hphp/tools/hfsort/hfsort'.

### ISSUE THREAD

**Issue by Atry** [facebook/hhvm#8982]
**Describe the bug**

Cannot build HHVM when `CMAKE_BUILD_TYPE` is `Debug`

**Standalone code, or other way to reproduce the problem**

1. Checkout the codebase
2. `cmake -DCMAKE_BUILD_TYPE=Debug -DMYSQL_UNIX_SOCK_ADDR=/var/run/mysqld/mysqld.sock .`
3. `make -j1 hfsort`

**Expected behavior**

No error
**Actual behavior**

```
[  4%] Built target bundled_zstd
[  9%] Built target bundled_boost
[  9%] Built target bundled_fmt
[ 13%] Built target bundled_double-conversion
[ 18%] Built target bundled_jemalloc
[ 22%] Built target bundled_folly
[ 22%] Built target bundled_brotli
[ 50%] Built target hphp_util
[ 50%] Built target bundled_libzip
[ 54%] Built target bundled_fizz
[ 59%] Built target bundled_lz4
[ 63%] Built target bundled_wangle
[ 63%] Built target eaw_table
[ 63%] Building C object third-party/forks/libmbfl/mbfl/CMakeFiles/mbfl.dir/__/filters/mbfilter_iso8859_2.c.o
[ 63%] Building C object third-party/forks/libmbfl/mbfl/CMakeFiles/mbfl.dir/__/filters/mbfilter_iso8859_3.c.o
[ 63%] Building C object third-party/forks/libmbfl/mbfl/CMakeFiles/mbfl.dir/__/filters/mbfilter_iso8859_4.c.o
[ 63%] Building C object third-party/forks/libmbfl/mbfl/CMakeFiles/mbfl.dir/__/filters/mbfilter_iso8859_5.c.o
[ 63%] Building C object third-party/forks/libmbfl/mbfl/CMakeFiles/mbfl.dir/__/filters/mbfilter_iso8859_6.c.o
[ 63%] Building C object third-party/forks/libmbfl/mbfl/CMakeFiles/mbfl.dir/__/filters/mbfilter_iso8859_7.c.o
[ 63%] Building C object third-party/forks/libmbfl/mbfl/CMakeFiles/mbfl.dir/__/filters/mbfilter_iso8859_8.c.o
[ 63%] Building C object third-party/forks/libmbfl/mbfl/CMakeFiles/mbfl.dir/__/filters/mbfilter_iso8859_9.c.o
[ 68%] Building C object third-party/forks/libmbfl/mbfl/CMakeFiles/mbfl.dir/__/filters/mbfilter_iso8859_10.c.o
[ 68%] Building C object third-party/forks/libmbfl/mbfl/CMakeFiles/mbfl.dir/__/filters/mbfilter_iso8859_13.c.o
[ 68%] Building C object third-party/forks/libmbfl/mbfl/CMakeFiles/mbfl.dir/__/filters/mbfilter_iso8859_14.c.o
[ 68%] Building C object third-party/forks/libmbfl/mbfl/CMakeFiles/mbfl.dir/__/filters/mbfilter_iso8859_15.c.o
[ 68%] Building C object third-party/forks/libmbfl/mbfl/CMakeFiles/mbfl.dir/__/filters/mbfilter_iso8859_16.c.o
[ 95%] Built target mbfl
[ 95%] Built target bundled_timelib
[ 95%] Built target afdt
[100%] Built target fastlz
[100%] Built target bundled_rust
[100%] Built target hhbc_ast_cbindgen
[100%] Built target parser_cxx
[100%] Built target parser_ffi
[100%] Built target compiler_cxx
[100%] Built target compiler_ffi
make[3]: *** No rule to make target 'third-party/fmt/bundled_fmt-prefix/lib/libfmt.a', needed by 'hphp/tools/hfsort/hfsort'.  Stop.
CMakeFiles/Makefile2:1799: recipe for target 'hphp/tools/hfsort/CMakeFiles/hfsort.dir/all' failed
make[2]: *** [hphp/tools/hfsort/CMakeFiles/hfsort.dir/all] Error 2
CMakeFiles/Makefile2:1811: recipe for target 'hphp/tools/hfsort/CMakeFiles/hfsort.dir/rule' failed
make[1]: *** [hphp/tools/hfsort/CMakeFiles/hfsort.dir/rule] Error 2
Makefile:541: recipe for target 'hfsort' failed
make: *** [hfsort] Error 2
```
**Environment**
 - Operating system
    'Ubuntu 18.04'
 - Installation method
    built from source
 - HHVM Version
    nightly-2022.01.28

**Additional context**

I did not encounter the error when the `CMAKE_BUILD_TYPE` is `RelWithDebInfo`.

**Comment by fredemmott** [comment]
https://github.com/fmtlib/fmt/blob/a7aecbfcaa0e1586da9cf8175bd8d1c4383acd8c/CMakeLists.txt#L277 means that in debug builds, fmt builds libfmtdby default

Two alternative ways to fix, both in https://github.com/facebook/hhvm/blob/master/third-party/fmt/CMakeLists.txt

1) pass "-DFMT_DEBUG_POSTFIX=" to fmt's cmake
2) change https://github.com/facebook/hhvm/blob/master/third-party/fmt/CMakeLists.txt#L29 to have fmt$<$<CONFIG:Debug>:d>${CMAKE_STATIC_LIBRARY_SUFFIX}

**Comment by fredemmott** [comment]
If you end up looking at this, it would be good to investigate updating the fmt version too; like the first-party stuff, it needs uploading to manifold for FB builds - see third-party/README.md

**Comment by fredemmott** [comment]
There's actually a better way in the future: use `FetchContent` to do the download at configure time, then we can use `add_subdir`, and we have fmt's own CMake targets exposed directly - [example in a personal project](https://github.com/fredemmott/OpenKneeboard/blob/682a7d36dda6f94400ef6e37ff29bc77bdf6048e/third-party/fmt.cmake)

Not doing that in HHVM yet as it requires a newer CMake than some of our supported platforms have.

**Comment by Atry** [comment]
Why do you use `third-party/fmt` instead of OS's `fmtlib`? Because we need a version of `fmtlib` newer than the Ubuntu/Debian's packages?

**Comment by fredemmott** [comment]
originally, because there was no `OS` fmtlib - fmtlib as a whole was too new.

Age is likely still an issue though, especially as it's a C++ library and we agressively enable new C++ standard versions.
