### ISSUE TITLE
TypeError when passing/verifying `\HH\Lib\_Private\_OS\ForkAndExecveOptions`

### ISSUE THREAD

**Issue by Atry** [facebook/hhvm#8989]
**Describe the bug**
Failed to invoke a closure that accepts a parameter of `\HH\Lib\_Private\_OS\ForkAndExecveOptions`

```
hhvm -a
```

```
hphpd> $f = (\HH\Lib\_Private\_OS\ForkAndExecveOptions $_options) ==> 1;
$f = (\HH\Lib\_Private\_OS\ForkAndExecveOptions $_options) ==> 1;
hphpd> $f(shape())
$f(shape())
Hit a php exception : TypeError: Argument 1 passed to __invoke() must be an instance of HH\Lib\_Private\_OS\ForkAndExecveOptions, HH\dict given in :1
Stack trace:
#0 (1): Closure$include()
#1 (1): include()
#2 (): include()
#3 {main}
```
**Expected behavior**

No error
**Actual behavior**

```
Hit a php exception : TypeError: Argument 1 passed to __invoke() must be an instance of HH\Lib\_Private\_OS\ForkAndExecveOptions, HH\dict given in :1
Stack trace:
#0 (1): Closure$include()
#1 (1): include()
#2 (): include()
#3 {main}
```

**Environment**
 - Operating system
    Ubuntu 20.04.3
 - Installation method
    Docker image `hhvm/hhvm:latest`
 - HHVM Version
    4.137.0

**Additional context**

**Comment by fredemmott** [comment]
the shape appears to only be defined in the .hhi file, not the runtime - it needs adding to hphp/runtime/ext/hsl

It works when called directly as it is defined as `shape()` - but when you specific it explicitly, as there's no runtime defintion, it assumes it's an object

**Comment by fredemmott** [comment]
Retitled as this is not a general problem: it is expected that runtime errors will be raised when attempting to verify types that are not defined in the runtime.

**Comment by fredemmott** [comment]
Most likely *any* type verification operation with this unknown type, e.g.

```
hphpd> = shape() as \HH\Lib\_Private\_OS\ForkAndExecVeOptions()
Hit fatal : when resolving anonymous type structure, class HH\Lib\_Private\_OS\ForkAndExecVeOptions not found
```

**Comment by dokfhrrbf** [comment]
?
