### ISSUE TITLE
Installation failed, deleting composer.json

### ISSUE THREAD

**Issue by codewizard13** [facebook/hhvm#9064]
### HHVM Version

- HipHop VM 4.155.0 (rel) (non-lowptr)
- Compiler: 1648749156_506524366
- Repo schema: 04d94ff27ad41e22663e624a2fee9a624072160a

### Operating System and Version

- Ubuntu 20.04.4 LTS (VirtualBox guest)
- Windows 10 64-Bit (host)
- VirtualBox 6.1.30 r148432
- VS Code

### Standalone code, or other way to reproduce the problem

Following this **HHVM** tutorial: https://docs.hhvm.com/hack/getting-started/starting-a-real-project

1. Install Composer and verify it is correctly installed
2. Run `https://docs.hhvm.com/hack/getting-started/starting-a-real-project`
3. Run:
```
curl https://raw.githubusercontent.com/hhvm/hhast/master/.hhconfig > .hhconfig
mkdir bin src tests
cat > hh_autoload.json
{
  "roots": [
    "src/"
  ],
  "devRoots": [
    "tests/"
  ],
  "devFailureHandler": "Facebook\\AutoloadMap\\HHClientFallbackHandler"
}
``` 
4. CTRL + C to end the write stream to hh_autoload.json
5. `composer require hhvm/hsl hhvm/hhvm-autoload`

That is the step where it fails.

### Actual result

I can see in VS Code that it begins to create the composer.json file and puts blank braces in the file
```
{

}
```
But, after some time waiting for it complete presumably downloading dependencies and repositories required by HHVM, the composer.json file suddenly disappears and then I get the following errors:

![ERROR: Installation failed, deleting ./composer.json](https://user-images.githubusercontent.com/3443044/162428460-180cb66b-9a10-45bc-bf49-563e8b3bf58f.png)

```
Installation failed, deleting ./composer.json.

In RequireCommand.php line 210:

  No composer.json present in the current directory (./composer.json), this may be the cause of the following exception.


In RemoteFilesystem.php line 477:

  The "https://repo.packagist.org/packages.json" file could not be downloaded: failed to open stream: Connection timed out

```

### Expected result

According to the linked HHVM tutorial I should see this:

```
Using version ^4.0 for hhvm/hsl
Using version ^2.0 for hhvm/hhvm-autoload
./composer.json has been created
```
And then I should be able to run the final command to create a working example project:

`composer require --dev hhvm/hhast hhvm/hacktest facebook/fbexpect`

But, it never gets that far

**Comment by lexidor** [comment]
Hi, the error you are reporting occurs in the composer/composer tool. The error you are seeing is due to a failed network connection. Are you able to wget/curl https://repo.packagist.org/packages.json from within your virtual box?

**Comment by lexidor** [comment]
I am closing this issue, because it is not an hhvm issue. This doesn't imply that I don't want to help you. If the problem persist with networking, @lexidor me in your reply. I'll be notified an I can have a second look.

**Comment by ayush2801sharma** [comment]
i am facing same issue how u resolved

**Comment by lexidor** [comment]
@ayush2801sharma this error occurs when composer can't access the internet. In order to troubleshoot, try using curl to fetch https://repo.packagist.org/packages.json. In the unlikely case you can fetch this file with curl, but composer is still unable to, you can file an issue against composer/composer.

**Comment by M9S9D** [comment]
i can open https://repo.packagist.org/packages.json .but i get this error again .also i use VPN .

**Comment by lexidor** [comment]
> i can open https://repo.packagist.org/packages.json .but i get this error again .also i use VPN .

Are you able to `curl example.com` from your container?

**Comment by sajidur319370** [comment]
Go to norton360 -> setting -> safe web and disabled it. Simply it works for me
