### ISSUE TITLE
Aarch64 - Fails on Fibonacci test

### ISSUE THREAD

**Issue by bgodala** [facebook/hhvm#9073]
I built hhvm on arm64 machine running Ubuntu 18.04.6 LTS. There were many minor issues that I resolved to compile hhvm on arm64 target. I was finally able to build hhvm but it fails on the fibonacci code (as shown https://docs.hhvm.com/hhvm/basic-usage/command-line) in command line mode. 

Command:
`hhvm fib.hack 10`

Output:
```
Assertion failure: /home/bgodala/benchmarks/tools/hhvm/hphp/util/optional.h:76: constexpr T* HPHP::Optional<T>::operator->() [with T = HPHP::StackTraceNoHeap]: assertion `m_opt.has_value()' failed.

-------------------------------Assertion Failure--------------------------------
/home/bgodala/benchmarks/tools/hhvm/hphp/util/optional.h:76: constexpr T* HPHP::Optional<T>::operator->() [with T = HPHP::StackTraceNoHeap]: assertion `m_opt.has_value()' failed.
Core dumped: Segmentation fault
Stack trace in /tmp/stacktrace.21343.log
Segmentation fault
```

I ran it through gdb to figure out where the issue is coming from. Here is the code snippet where it actually fails. The code snippet is jit generated code. The memory location `0xbe0001dc` is not accessible so it seg faults at branch instruction.

```
   0xaaaab7801084  mov    x16, #0x1dc                     // #476
   0xaaaab7801088  movk   x16, #0xbe00, lsl #16
>  0xaaaab780108c  br     x16
```

The value in the register x16 is supposed to be 64-bit value but it contains only 32-bit target address. I thought the issue could be missing upper half of 32-bits of the target address. In gdb, I changed the value in x16 register to `0xaaaabe0001dc` but it fails with a different error message.

**Environment**
 - Operating system
> Ubuntu 18.04.6 LTS arrch64 Kernel: 4.15.0-162-generic
 - Installation method
> 'built from source'
 - HHVM Version
> HipHop VM 4.158.0-dev (rel) (non-lowptr)
> Compiler: tags/nightly-2022.04.17-0-gf232390af76ea60526bc67941834525bd40c48b0
> Repo schema: af4ee0c0977889b28c58aa2d6f95ef415af396a8

**Comment by Atry** [comment]
Thank you for the experiments. ARM64 is not currently supported.

**Comment by dhananjaykumar880** [comment]
Is it in the plan to support. As many people have M1 machine now a days and struggling to run hack.
Can you share support for Arm64?

**Comment by lexidor** [comment]
Related to #8875

**Comment by lexidor** [comment]
My previous mention to 8875 has added a reference to this issue. This issue is a small part of getting hhvm working on arm. I hope you don't mind if I close it. Your findings can still be referenced via 8875.
