### ISSUE TITLE
dl.hhvm.com repo is unavailable due to SSL issuer

### ISSUE THREAD

**Issue by erik-bershel** [facebook/hhvm#9376]
**Describe the bug**
When you try to install the app via apt on Ubuntu 20.04/22.04, an error will return:
```
Failed to fetch https://dl.hhvm.com/ubuntu/dists/jammy/InRelease  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 18.244.87.67 443]
```

**Standalone code, or other way to reproduce the problem**

apt-get update
apt-get install software-properties-common apt-transport-https
apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xB4112585D386EB94
add-apt-repository https://dl.hhvm.com/ubuntu
apt-get update
apt-get install hhvm

**Expected behavior**
HHVM installed successfully.

**Actual behavior**
```
W: Failed to fetch https://dl.hhvm.com/ubuntu/dists/jammy/InRelease  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 18.244.87.67 443]
W: Some index files failed to download. They have been ignored, or old ones used instead.
```
**Environment**
 - Operating system
Ubuntu 20.04, Ubuntu 22.04
 - Installation method
apt-get with dl.hhvm.com repository
 - HHVM Version
N/A

**Additional context**

**Comment by vikash-itspe** [comment]
This is still not fixed 

The repository 'https://dl.hhvm.com/ubuntu focal-4.107 Release' does not have a Release file.
Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 108.159.80.79 443]

**Comment by fredemmott** [comment]
I no longer work for Meta, or on Hack/HHVM.

**Comment by vikash-itspe** [comment]
That's sad. Sorry for Meta loss ;)

**Comment by erik-bershel** [comment]
@vikash-itspe tmp workaround if needed: https://github.com/actions/runner-images/pull/7817

**Comment by vikash-itspe** [comment]
still there is no official solution to this from HHVM side. Worrying situation :(

**Comment by vikash-itspe** [comment]
Is anyone from hhvm fixing this ?

#0 0.296 Err:2 https://dl.hhvm.com/ubuntu focal-4.107 Release
#0 0.296   Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 108.159.80.42 443]
#0 6.313 Reading package lists...
#0 7.459 E: The repository 'https://dl.hhvm.com/ubuntu focal-4.107 Release' does not have a Release file.
------

**Comment by vikash-itspe** [comment]
@diliop can you look into this major outage issue.

**Comment by diliop** [comment]
@vikash-itspe I'll try to find someone that can take a look, I don't work on HHVM. In the meantime does the workaround posted by @erik-bershel work for you?

**Comment by paulbiss** [comment]
There was an issue with our SSL certificate a couple weeks ago but it's since been updated. When I load https://dl.hhvm.com/ I'm seeing a valid certificate now.

**Comment by erik-bershel** [comment]
Hey @paulbiss!
Try it please on Ubuntu with the instructions from the HHVM web-site. It wouldn't work. Works fine with the browsers but not with APT.

**Comment by Wilfred** [comment]
The certificate expired on the 23rd of June, so I installed the new certificate later that day. Browsers are totally happy but for some reason `apt` doesn't like the certificate.

https://www.ssllabs.com/ssltest/analyze.html?d=dl.hhvm.com&s=13.35.121.80&hideResults=on says that the chain is incomplete, so maybe `apt` is fussy about this?

**Comment by Wilfred** [comment]
Looks like we didn't have the intermediate certificate on AWS us-east-1, which hosts dl.hhvm.com. I believe this is now sorted, but I'll leave open for a few days in case we've missed anything.

**Comment by vikash-itspe** [comment]
@Wilfred Thanks Finally apt installed is working perfectly now .
👍🏻
