### ISSUE TITLE
Profile-Guided Optimization (PGO) and BOLT impact on HHVM

### ISSUE THREAD

**Issue by zamazan4ik** [facebook/hhvm#9385]
Hi!

Did you measure the impact of Profile-Guided Optimization (PGO) and/or BOLT (already LLVM BOLT) on HHVM performance (CPU usage/latency/something else)? if yes -  could you please share the actual numbers?

I did a quick research on the repo but found only the following mentions about PGO:
* Quite an old commit with PGO addition: https://github.com/facebook/hhvm/commit/b367bb66975b6f1507a70adba8eeefd92ff2fca3 . Didn't find yet the reason why it was deleted from the project.
* https://github.com/facebook/hhvm/issues/5306#issuecomment-101067115 . But it uses old compilers and hasn't results for Clang.

For BOLT I didn't find actual numbers but the [article](https://thenewstack.io/how-to-use-bolt-binary-optimization-and-layout-tool/) says that BOLT was applied to HHVM.

Would be great if you can share the results with the actual numbers. And if any of PGO/BOLT has a measurable impact on HHVM - would be nice to see a note about that in the project documentation (and have an additional build option to build HHVM with PGO/BOLT optimization).

I am interested in this topic since according to my [tests](https://github.com/zamazan4ik/awesome-pgo) PGO in general helps a lot, especially in compiler-like loads.

**Comment by paulbiss** [comment]
Hi! We see major improvements from both PGO and BOLT. We've published a couple of papers about BOLT that have some of the comparisons you're interested in:

 - https://research.facebook.com/publications/bolt-a-practical-binary-optimizer-for-data-centers-and-beyond/
 - https://research.facebook.com/publications/lightning-bolt-powerful-fast-and-scalable-binary-optimization/

**Comment by zamazan4ik** [comment]
Thanks for the links! So now I am wondering - did you think about integrating PGO/BOLT into the HHVM build scripts (which are open-source, not Facebook internal build scripts)? Also, would be great to see somewhere in the README or other documentation how HHVM could be optimized with PGO/BOLT and what benefits from the performance perspective could be achieved with that.
